### ISSUE TITLE
Can someone unblock me please @c0oys https://dev.to/c0oys

### ISSUE THREAD

**Issue by c0oys** [forem/forem#10013]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by c0oys** [comment]
Can you unblock me please and please dont close this trend until i am unblocked please.

**Comment by rhymes** [comment]
Hello @c0oys, thanks for notifying us of this problem, as this an issue specific to your account, please email yo@dev.to for more help.

GitHub is not the best place for support requests :) 

Thank you!
