### ISSUE TITLE
Canonical URL Missing Originally Publish At X

### ISSUE THREAD

**Issue by hmajid2301** [forem/forem#10028]
When I change the canonical url on an existing article. I cannot see the Originally published at `xxx`. I added the `canonical_url` option in the frontmatter. 

[Here](https://dev.to/hmajid2301/how-to-add-offline-search-to-a-gatsby-blog-4bnm
) is an article which was originally uploaded with a `canonical_url` option in the frontmatter.

[Here](https://dev.to/hmajid2301/react-native-expo-with-virtualbox-and-genymotion-3d7c) is an example of an article where the `canonical_url` has been added to the frontmatter. However it is set correctly in the `<head>` i.e.
`<link rel="canonical" href="https://haseebmajid.dev/blog/react-native-with-virtualbox">`

**To Reproduce**

1. Go to an article without a canonical_url in the frontmatter
2. Press `Edit` button
3. Add `canonical_url` to frontmatter
4. Press `save changes` button

**Expected behavior**

I would expect the article to update with a ` Originally published at <sitename.com>`

**Screenshots**

![](https://i.imgur.com/Y9E7RSk.png)
![](https://i.imgur.com/bSQ6DNB.png)

**Desktop (please complete the following information):**

- OS, version: Linux POP_!OS 20.04
- Browser, version: Firefox, 79

**Comment by justinyoo** [comment]
I have the same issue. I published a post with the `canonical_url` in the frontmatter. When the post was initially published, the message, `originally posted at xxx` existed. However, after I modified the same post, the original post message has disappeared. I confirm that the metadata still exists in the header section.
