### ISSUE TITLE
Sending "Reset password" link

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#10032]
**Describe the bug**

Even though I don't have set up password for my account, I can still use "Forgot password" form (linked form _Log in_ page) to send myself an email with Password Reset link. It's not very usable because it just logs me in and takes me to the Dashboard but nevertheless I think we should have better flow to handle that edge case.

**To Reproduce**

1. Make sure you don't have password set up on your account.
2. Make sure you're logged out.
3. Go to "[forgot password](https://dev.to/users/password/new)" page.
4. Enter your email address.
5. Check your inbox, you will see the reset email link.

**Expected behavior**

I'm not really sure what's the best flow.. Maybe prevent sending email like that by checking if user has set up password already? Orrrr send that email, even with that link but then show appropriate message..?

**Comment by citizen428** [comment]
If I remember correctly users _always_ have a password. If they sign up via another flow, we automatically create one but don't tell them about it.

**Comment by citizen428** [comment]
Double-checked. See `app/services/authentication/authenticator.rb:117`:

```ruby
   def default_user_fields
      password = Devise.friendly_token(20)
      ...
   end
```

**Comment by ludwiczakpawel** [comment]
Then either way this flow is incorrect. It was supposed to be "reset my password" kind of a flow, and turned out to be "magic link to log in" (we could consider that as a feature though :D)

**Comment by citizen428** [comment]
@ludwiczakpawel I end up on this page, not automatically logged in:

<img width="607" alt="Screen Shot 2020-08-28 at 10 48 31" src="https://user-images.githubusercontent.com/47985/91519180-19d58080-e91c-11ea-8d1a-d16418948043.png">

**Comment by rhymes** [comment]
It worked for me too

**Comment by ludwiczakpawel** [comment]
Huh, that's interesting... It didn't work for me like that... Actually, I couldn't login with social auth since yesterday due to some cookies issue and now, when I tried to reset my password I actually saw the screen you linked above AND was finally able to log back in.. Fun fact: now I can't log out...

**Comment by rhymes** [comment]
I can't logout either :-|

**Comment by rhymes** [comment]
@ludwiczakpawel is still happening for you?

**Comment by ludwiczakpawel** [comment]
I'm not sure because I can't verify this:

> 1. Make sure you don't have password set up on your account.

^ there's no indicator saying whether or not I have a password set up.

**Comment by rhymes** [comment]
@ludwiczakpawel as mentioned in https://github.com/forem/forem/issues/10032#issuecomment-681758621, all users have a password :)
