### ISSUE TITLE
Should comments belonging to unpublished articles be accessible?

### ISSUE THREAD

**Issue by rhymes** [forem/forem#10037]
**Is your feature request related to a problem? Please describe.**

Right now if a user deletes an articles, the comments attached it are still accessible provided one has the URL for them.

This is not true if a person unpublishes an article that has already been commented.

Should we consider comments on unpublished articles the same way?

**Describe the solution you'd like**

I'm okay with the status quo but this came up thanks to a consideration that @mstruve left on a PR review: https://github.com/forem/forem/pull/9990#discussion_r476701146

> Interestingly, I just found out that if someone unpublishes a post then you can no longer view those comments through the permalink. However, we do allow comments to be viewed from deleted posts. Wonder if this is something we should change. 🤔

**Describe alternatives you've considered**

We can either keep the status quo or allow those comments to be accessible either way.

**Additional context**

There's a larger consideration to be had about content and ownership as if one of those comments (on deleted articles or unpublished articles) contains major quotes of the since hidden article, whose is the ownership of that?  I wouldn't go too much in the deep here though, as there's an expectation that things that are published can be quoted or screenshotted in each and every social network, forum, community and so on that are public.

**Comment by twinsfan421** [comment]
I would work on this if approved. I worked on the deleted article comments being viewable.

**Comment by cmgorton** [comment]
@rhymes is this still an issue and if so should we add the potentiel RFC label to it?

**Comment by rhymes** [comment]
@cmgorton I think we should add the label! There's definitely a product conversation to be had here, to understand the relationship between a comment and the post it's attached to. I'm not sure we should implement this but advocating it through a RFC would lead to an exploration of the consenquences of these around ownership of content on the platform. Thank you!
