### ISSUE TITLE
Moderate Post Panel Cannot Close

### ISSUE THREAD

**Issue by aligoren** [forem/forem#10048]
**Describe the bug**

Hi, I'm using mod center regularly. Actually, I didn't use the close icon before. Today, I used it and it didn't close. It shows this error

```text
[Honeybadger] Ignoring cross-domain script error: enable CORS to track these types of errors Arguments(5) ["Script error.", "", 0, 0, null, callee: (...), Symbol(Symbol.iterator): ƒ]
actionsPanel.js:11 Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLButtonElement.<anonymous> (actionsPanel.js:11)
    at HTMLButtonElement.P.e.___hb.e.___hb (base.js:7669)
```

**To Reproduce**

1. Go to the **Mod Center**
2. Click on a post to moderate
3. Let's assume you moderated a post
4. Click on the **X** icon.

**Expected behavior**

It should close the post moderate section we opened.

**Screenshots**

![image](https://user-images.githubusercontent.com/4205423/91534932-0d9cf380-e91b-11ea-98ee-71a9943d6781.png)

**Desktop (please complete the following information):**

- OS, version: Window 10
- Browser, version: Chrome, Latest

**Additional context**

I disabled all the extensions. But it still doesn't work. So, ~I think this is a CORS problem~. This is a JavaScript problem.

Thanks.

**Comment by aligoren** [comment]
I closed the opened post using Chrome Developer Tools.

```js
const openedPost = document.querySelector(".article-iframes-container.opened");

openedPost.innerHTML = ''

openedPost.classList.toggle('opened')
```

It closed, @rhymes is this the only way to close this panel? I think, there is a trigger :)

**Comment by Rafi993** [comment]
Hello there, I think it is related to https://github.com/forem/forem/issues/10265 and it is addressed by PR https://github.com/forem/forem/pull/10353  (sorry for randomly jumping in)

**Comment by nickytonline** [comment]
@aligoren, just following up on this issue in regards to what @Rafi993 mentions.

**Comment by aitchiss** [comment]
Closing as I believe this has been resolved by the PRs mentioned above
