### ISSUE TITLE
Logout on navigation to homepage

### ISSUE THREAD

**Issue by IzMichael** [forem/forem#10044]
**Describe the bug**

On forem.dev, when I click the logo at the top left of the page to return home, I get logged out.

**To Reproduce**

1. Open any post
2. Click the Forem logo in the header
3. See that you've been logged out

**Expected behavior**

Should still be logged in.

**Desktop:**

- Windows 10, 1909:
- Microsoft Edge Dev Channel, 86.0.615.3:

**Comment by rhymes** [comment]
closing this as it doesn't seem to be happening anymore
