### ISSUE TITLE
i can't do anything in dev

### ISSUE THREAD

**Issue by praveenkalady** [forem/forem#10069]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
@praveenkalady what sort of problem do you have? have you tried clearing out your cookies?
