### ISSUE TITLE
Bug: Comments that Point to Another Comment via a Liquid Tag Are Invalid if Liquid Tag referenced Comment is Deleted 

### ISSUE THREAD

**Issue by mstruve** [forem/forem#10061]
**Describe the bug**

If you have a comment that references another comment and that comment is deleted, the original comment becomes invalid. For example:
Comment A Markdown: `Checkout {% devcomment 1b %}`
If Comment with id_code `1b` is deleted, Comment A becomes invalid and can no longer be saved. This prevents others from reacting to it amongst other things. 

**To Reproduce**

1. Create a comment with a comment liquid tag that points to a second comment. 
2. Delete the comment referenced by the liquid tag.
3. Attempt to save the original comment with the liquid tag. You will get the following error. `StandardError, "Invalid comment ID or comment does not exist"`

**Expected behavior**

Comments that reference other comments should remain valid even if the other comment is deleted. I would suspect that instead of displaying the comment for the liquid tag it would display a message along the lines of "Comment has been removed"

**Comment by msarit** [comment]
I'll grab this! 😄
