### ISSUE TITLE
Signup using Github profile 

### ISSUE THREAD

**Issue by Binston-sukhael-cardoza** [forem/forem#10099]
**Describe the bug**
I can't able to signup using GitHub profile 

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot_20200831-021712](https://user-images.githubusercontent.com/60263684/91713034-97acbc80-eba6-11ea-9162-8b1566816635.jpg)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:Oneplus 3
- OS, version:9.0
- Browser, version: Google chrome 85.0.4183.81

**Additional context**

**Comment by Zhao-Andy** [comment]
@Binston-sukhael-cardoza sorry about that issue. Could you provide your dev.to username? We'll fix this for your individual account.

**Comment by Zhao-Andy** [comment]
@Binston-sukhael-cardoza actually this is fixed for your account now. Let us know if you still can't log in.

**Comment by Binston-sukhael-cardoza** [comment]
Well Done, Bro
