### ISSUE TITLE
Link no longer available

### ISSUE THREAD

**Issue by omenking** [forem/forem#10096]
The link does exist
<img width="692" alt="Screen Shot 2020-08-30 at 4 03 53 PM" src="https://user-images.githubusercontent.com/7776/91668405-81d1c580-eada-11ea-8be7-297308c1f755.png">

But it displays this
<img width="773" alt="Screen Shot 2020-08-30 at 4 03 48 PM" src="https://user-images.githubusercontent.com/7776/91668403-7f6f6b80-eada-11ea-8d6c-c3da6d5c365d.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
Hi @omenking, this is definitely a bug but it's also a communication failure. The `link` liquid tag only works for `dev.to` articles

**Comment by Rafi993** [comment]
Hello there, If this still up for taking. I can help with this bug.

**Comment by rhymes** [comment]
@Rafi993 sure, go ahead! thanks

**Comment by Rafi993** [comment]
> @Rafi993 sure, go ahead! thanks

Thank you @rhymes

**Comment by Rafi993** [comment]
When you use url   
```
{% link https://www.freecodecamp.org/news/ %}
```
it displays the correct error message

![link_error](https://user-images.githubusercontent.com/8092120/94501112-aaa2c300-021e-11eb-9b8f-290b8c70654d.png)

but when I add the url with another '/' like

```
{% link https://www.freecodecamp.org/news/ultimate-dynamodb-2020-cheatsheet/ %}
```
it causes the problem
![link_error](https://user-images.githubusercontent.com/8092120/94501166-d3c35380-021e-11eb-95c2-77d71a219351.png)

It is probably issue in 

https://github.com/forem/forem/blob/1b8a497054cd03e60fafecad7c10a2b5d8c22816/app/liquid_tags/link_tag.rb#L23-L31
