### ISSUE TITLE
Code blocks lose indentation when imported through RSS

### ISSUE THREAD

**Issue by Swimburger** [forem/forem#10104]
**Describe the bug**

When importing blog posts using an RSS feed, the importer successfully imports pre-tags as code blocks, but loses all the indentation.

**To Reproduce**

1. Import article using RSS with pre-tag as code blocks into dev.to (https://swimburger.net/atom.xml)
2. Compare original post code formatting with markdown
Original:
![image](https://user-images.githubusercontent.com/3382717/91740869-e5fb9480-eb81-11ea-82ca-d9e067199182.png)
Markdown:
![image](https://user-images.githubusercontent.com/3382717/91740908-f6137400-eb81-11ea-9c2f-6f7c1d1db904.png)

**Expected behavior**

Code blocks should preserve indentation when imported using RSS.

**Additional context**

For example in Feedly feed reader, the indentation is preserved:
![image](https://user-images.githubusercontent.com/3382717/91741012-1fcc9b00-eb82-11ea-8446-e545d5b80b0c.png)

(dev.to post has already been manually fixed by copying the code from the original post to the markdown sections)

**Comment by rhymes** [comment]
Marked this as ready for Hacktoberfest, though I'm not entirely sure it's a problem on our side or if it's a problem in the Feedjira. If someone wants to explore this is more than welcome :)

**Comment by tudorpavel** [comment]
I found a fix for this bug, see #10922 for details.
