### ISSUE TITLE
Web scroll stuck when unsigned user click "heart"/"unicorn"/"reading list" on a post at mid page

### ISSUE THREAD

**Issue by maisonsmd** [forem/forem#10101]
**Describe the bug**
User not logged in, open a post, scroll down a bit, click "heart", the modal overlay for user to sign in appears on top of the page, but not visible in screen view because user scrolled down beforehand, and y-scroll is disabled, hence the page stucks.

**To Reproduce**

1. Go to https://dev.to/ without signing in
2. Click on any post
3. Scroll down to end of the page
4. Click on "heart" icon on the left of the page

**Expected behavior**
Modal overlay appear in screen view, to let user sign in

**Actual behavior**
Page stucks at current view, cannot be scrolled, scrollbar disappears, 

**Desktop (please complete the following information):**

- OS, version: Windows 10 Pro 10.0.19041 Build 19041
- Browser, version: Google Chrome 85.0.4183.83 64 bit

**Suggest fix**
Scroll to top of the page in JS if user click those buttons without signing in.
```javascript
scrollTo({
  top: 0,
  left: 0,
  behavior: 'smooth'
  });
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I can reproduce this issue on Firefox + macOS as well

**Comment by maisonsmd** [comment]
> I can reproduce this issue on Firefox + macOS as well

Firefox is also affected.
MacOS not tested, I don't have any devices nearby.

**Comment by nickytonline** [comment]
Would you like to work on this @maisonsmd ?

**Comment by maisonsmd** [comment]
I'm not familiar with most of the technologies used in this project, so I just put the issue here for someone else with ability to fix.

**Comment by ludwiczakpawel** [comment]
I'll work on that.
