### ISSUE TITLE
Login with Facebook bug

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10102]
**Describe the bug**

This is related to the great work recently completed on #9922  . Which works locally using ngrok but fails when rolled out to production. 

**To Reproduce**

1. Go to forem.dev
2. Click on 'sign in with Facebook'
3. Scroll down to 'accept Facebook request for email and profile permissions'
4. View error on completion.

When testing this on thisMMAlife.com I can see the following error showing in the log consistently but nothing else.

"Can’t Load URL: The domain of this URL isn’t included in the app’s domains. To be able to load this URL add all domains and subdomains of your app to the App Domains field in your app settings".

Although all App domains have been included on the Facebook app side of things.

Assuming this is the same on Forem.dev

**Expected behavior**

Facebook to ask for permissions, then the onboarding workflow to start.

**Screenshots**

<img width="1304" alt="Screenshot 2020-08-31 at 15 06 32" src="https://user-images.githubusercontent.com/12694270/91728836-95913080-eb9b-11ea-8bf7-d65e60736e12.png">

**Additional context**

All the required app domains and valid callback URLs have been included in the Facebook dev app for thisMMAlife including the naked heroku domain and the Fastly url (assuming this is the same for Forem.dev)

**Comment by rhymes** [comment]
@leewynne can we consider this fixed now that Login with Facebook works?

**Comment by leewynne** [comment]
Yup!
