### ISSUE TITLE
I18n: Tag pages with non ASCII characters are broken

### ISSUE THREAD

**Issue by eusonlito** [forem/forem#10116]
Tag page with a tag with non ASCII characters returns an error page.

**To Reproduce**

1. Go to https://dev.to/lito/pruebas-de-rendimiento-en-laravel-5-6-5-7-5-8-6-0-vs-php-7-1-7-2-7-3-7-4-2bpj
2. Click in `español` tag
3. Page loaded https://dev.to/t/espa%C3%B1ol
4. See the error page

**Expected behavior**

Render de page as any other tag.

**Screenshots**

![Screenshot from 2020-09-01 00-29-43](https://user-images.githubusercontent.com/644551/91774955-44f4f400-ebea-11ea-9d39-5b586b3e97c2.png)

**Desktop (please complete the following information):**

- OS, version: Ubuntu
- Browser, version: Version 85.0.4183.83 (Official Build) beta (64-bit)

**Comment by citizen428** [comment]
Thanks for the report @eusonlito. As far as I remember our tags currently only support ASCII characters, but I may be wrong on this. Maybe @jacobherrington knows more, as I vaguely remember discussing this in a PR with him.

**Comment by rhymes** [comment]
@citizen428 @jacobherrington 

Yeah, we definitely support only ASCII tags, but the check has been added on July 1st 2020 and this article is from September 2019.

We have 1190 tags with non ASCII characters in them, most of them attached to content.

I believe we have 2 options here:

- we convert those tags to something that rests in the realm of ASCII
- we find a way to make the link https://dev.to/t/espa%C3%B1ol work

**Comment by citizen428** [comment]
@rhymes The check was only added on July 1st, but as far as I remember it just made existing behavior explicit. I prefer the second option btw, maybe that's something we can look into during cooldown.

**Comment by rhymes** [comment]
added to our backlog :-)

**Comment by djuber** [comment]
I think this specific error (rendering the tag page for existing non-ascii tag names) is resolved after https://github.com/forem/forem/pull/13720 - however - there's still an open issue https://github.com/forem/forem/issues/14422 where it's not possible to create or add non-ascii tags (I believe that was added as a guard to prevent this issue from occurring).

I'm going to close this issue (the tag page renders correctly, does not raise an error).
