### ISSUE TITLE
Ellipsis menu in post manage page non-functional

### ISSUE THREAD

**Issue by alexzherdev** [forem/forem#10111]
**Describe the bug**

In the post manage page, clicking the "..." menu on the right seems to do nothing.

**To Reproduce**

1. Go to `https://dev.to/user/post-slug/manage`
2. Click on `...` on the right
3. Nothing happens

**Expected behavior**

I'm expecting a dropdown menu to appear? According to the markup, it contains an "Archive Post" button.

**Screenshots**

![devtoellipsis](https://user-images.githubusercontent.com/93752/91760560-6ae9ac80-eb88-11ea-9adb-f26e4f8c6f32.gif)

**Desktop (please complete the following information):**

- OS, version: macOS 10.14.6
- Browser, version: Chrome 84.0.4147.135

**Smartphone (please complete the following information):**

- Device: iPhone XS
- OS, version: iOS 13.5
- Browser, version: Chrome 85.0.4183.72

**Additional context**

Doesn't seem to work in the iOS native app either.

**Comment by Link2Twenty** [comment]
It looks like there's no JS to handle this. I'd guess there was a generalisation of naming that didn't quite get finished.

**JS to handle more button:**
https://github.com/forem/forem/blob/8c83aa336570e9f9085dcf4869270691ce131448/app/assets/javascripts/initializers/initializeEllipsisMenu.js

**Code for button on Dashboard:**
https://github.com/forem/forem/blob/dbbe158d21caabfffa2c7c5c56ebc2e615fc9fda/app/views/dashboards/_dashboard_article_row.html.erb#L92-L124

**Code for button in manage screen:**
https://github.com/forem/forem/blob/8c83aa336570e9f9085dcf4869270691ce131448/app/views/dashboards/_dashboard_article.html.erb#L11-L22

As you can see the naming is different so no functionality is added.

I think the `ellipsis-menu` naming makes more sense than the `js-dashboard-row-more` personally.

**Comment by alexzherdev** [comment]
Yep exactly—I traced it back to https://github.com/forem/forem/pull/8778 by @ludwiczakpawel.
If he's not available I might be able to fix this up if we can decide which naming to follow.

**Comment by ludwiczakpawel** [comment]
Yeap! I'm definitely the one to be blamed for this 🤦‍♂️

@alexzherdev I'm happy to hand it off to you if you wanna handle that. Let me know and I'll assign you.

@Link2Twenty thanks a ton for tracing that down!

**Comment by irmela** [comment]
If this one is not being worked on by someone else I'd be happy to take over.

/cc @ludwiczakpawel @alexzherdev

**Comment by ludwiczakpawel** [comment]
@irmela go for it! I'm assigning you :)
