### ISSUE TITLE
Stuttering on High Refresh rate devices

### ISSUE THREAD

**Issue by pramanikriju** [forem/forem#10112]
**Describe the bug**
On mobiles devices, the home page stutters at high refresh rates, which is anything beyond 60Hz. 
There's a massive delay on the first scroll and then it suddenly jumps. This issue is not present on 60Hz screens. 

**To Reproduce**
1. Go to 'https://dev.to/ 
2. Wait for it to load, and then scroll

**Expected behavior**

Scrolling can and should be smoother, especially in a scroll-based view

**Smartphone:**

- Device: OnePlus Nord
- OS, version: Android 10
- Browser, version: Chrome - 85.0.4183.81

**Additional context**

Can be reliably reproduced on other high refresh rate mobile devices

**Comment by ludwiczakpawel** [comment]
@pramanikriju does this still happen to you? I have a 60Hz monitor and I can't repro that. Maybe it's only limited to some mobile devices?

**Comment by pramanikriju** [comment]
No this issue is no longer persisting. Would you like me to close this issue or can you do that?

**Comment by ludwiczakpawel** [comment]
I'll close it, thanks!
