### ISSUE TITLE
UI Regression: title input box clips text

### ISSUE THREAD

**Issue by richardeschloss** [forem/forem#10114]
**Describe the bug**
Can you please look into this regression on the UI? I'm using Chrome (latest) for Windows 10 and the text box for the title is clipped.
![regression](https://user-images.githubusercontent.com/5906351/91770366-ed2c9d80-eb95-11ea-8a58-b4f19f3700d7.jpg)

**To Reproduce**

**Expected behavior**
No clipped text

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 84 (latest)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

Suggested fix: the textarea box with class "crayons-textfield" has height set to 27px. Removing that attribute fixed the sizing for me.  (perhaps using an absolute arbitrary pixels is not properly sizing the box on different platforms)

**Comment by ludwiczakpawel** [comment]
Hey @richardeschloss , thanks for the report. It definitely should not look like this. Since I can't repro that bug on my local (or prod) environment, would you mind helping me out a little with this?

1. Make sure you do hard refresh - maybe there's some caching issue there.
2. If that doesn't help, can you open Developer Tools in Chrome? You should be able to do so with CTRL+ALT+I on Windows (I think...)
3. There will be a tab called "Console" - could you check if there are any errors reported?

Also, if you have an option, are you able to test that also on other browsers?

**Comment by richardeschloss** [comment]
Hmm, I can repro it like this: start with the browser maximized, then unmaximize, then maximize again. It'll be clipped

**Comment by Zhao-Andy** [comment]
Hey @richardeschloss, I can't reproduce this on Windows 10, Chrome 85 :( What's your screen resolution? Also, do you see any errors in your browser console?

**Comment by richardeschloss** [comment]
Display resolution: 1366 x 768. No errors show in the console.

**Comment by ludwiczakpawel** [comment]
I can't repro that either but I'll try to do it on other machines I have around.

**Comment by richardeschloss** [comment]
try reducing the browser window size... keep reducing it. I think eventually it'll show since the 27px is fixed.

**Comment by nickytonline** [comment]
Hmm, I see that we have the height hard-coded to `60px`, so not sure where that `27px` is coming from. 

See https://github.com/forem/forem/blob/877bdba176759163f07e69b814400d4537bffa7c/app/views/articles/_v2_form.html.erb#L61

![image](https://user-images.githubusercontent.com/833231/91896062-419f4e00-ec66-11ea-9a56-151854346cae.png)

Is this what you see in the rendered markup @richardeschloss ?

**Comment by richardeschloss** [comment]
![height_27px](https://user-images.githubusercontent.com/5906351/91896454-bb770d80-ec4d-11ea-8327-2ccf1d310450.jpg)

**Comment by nickytonline** [comment]
I have a feeling this is a caching issue that maybe only some users are seeing. Thoughts @rhymes

**Comment by rhymes** [comment]
I can't reproduce it either, but I'm also not sure how the thing works. I see the 60px only in the HTML version:

https://github.com/forem/forem/blob/f023c6174f9706eb60249a7fe7a369817a754270/app/views/articles/_v2_form.html.erb#L60-L62

but I can't see it in the JSX component:

https://github.com/forem/forem/blob/f023c6174f9706eb60249a7fe7a369817a754270/app/javascript/article-form/components/Title.jsx#L11-L27

How does it stay there?

**Comment by ludwiczakpawel** [comment]
@rhymes the way it works:

We load the whole "Write a post" view with `.html.erb` and replace it with Preact component asap - it's some sort of a trickery we do to have that "blazing fast" feeling.

In Preact version we use JS to calculate the height of the Title field - that's where '60px' is coming from - it's calculated with JS. So if the value is '27px' then it means that something is off with JS. Btw. we don't do that calculation in `.html.erb` version of the view because there's no point.

But why the hell do we use **any** JS to calculate the height of the field in the first place? That's because title is actually a `textarea` that can wrap text to the next line. If we used classic `input` it wouldn't wrap the text and entire view would look weird. (cc @nickytonline that's why `height` is set in `style` attribute - it's not hardcoded though :)) 

> but I can't see it in the JSX component

It's another component - this is where the magic is coming from: https://github.com/forem/forem/blob/f023c6174f9706eb60249a7fe7a369817a754270/app/javascript/article-form/components/Title.jsx#L3

**Comment by rhymes** [comment]
So there might be a bug in that component? 

ps. could you add this great explanation of yours to https://docs.dev.to/frontend/preact/ or https://docs.dev.to/faqs/ or even as inline comment in https://github.com/forem/forem/blob/f023c6174f9706eb60249a7fe7a369817a754270/app/javascript/article-form/components/Title.jsx#L3

It's a pity to keep it "buried" in a github issue :)

**Comment by richardeschloss** [comment]
I'm not a tailwind expert...but what does "lh-tight" do? Does that mean "line-height tight"? Is tailwind trying to size the box to be as minimal as possible?

**Comment by richardeschloss** [comment]
I'm less familiar with tailwind but...what does "lh-tight" in the className do? Does that set a line-height style to be tight and does that "tightness" interact with what the "preact-textarea-autosize" is trying to do?

**Comment by ludwiczakpawel** [comment]
@richardeschloss `lh-tight` class sets the `line-height` to be `1.25`. It may indeed be taken into consideration while calculating height of the field but it should definitely not cause any harm to the layout, especially like you have in the screenshot...

So except some potential bug in the Textarea component I've mentioned earlier, I do have one more theory: does your machine do anything special with fonts? Have you somehow overwritten default fonts on your machine or something like that?

**Comment by richardeschloss** [comment]
For fonts, not that I can recall. I don't think I did, but I can try to remember.

**Comment by richardeschloss** [comment]
Some more information. I made sure to uninstall LibreOffice (which is the only thing I think could have changed default fonts). I have  pretty lightweight system here.

I have some more screenshots that may help.

This is the view on initial page load (everything looks fine. height set to 64 px)
![initial_view](https://user-images.githubusercontent.com/5906351/92272808-1fdcdb80-ee9f-11ea-8916-3eaf025919f1.jpg)

But then when I click on the title text area, the height changes to 27 px:
![after_click](https://user-images.githubusercontent.com/5906351/92272806-1eabae80-ee9f-11ea-8f76-a67015dd5205.jpg)

Does this help?

**Comment by ludwiczakpawel** [comment]
I still can't repro that bug on my local env and neither of us (other team members) can. Not sure what to do here.. 🤷‍♂️

**Comment by Coteh** [comment]
I was able to reproduce this with Firefox 80 (no extensions) on macOS Mojave #10261

**Comment by richardeschloss** [comment]
I have a thought...what version of the preact-textarea-autosize is being used? So, the one that's published in npm appears to point to a github repo which is 4 years old. It seems like the forked version has had more maintenance:

https://github.com/Andarist/react-textarea-autosize (fork)

https://github.com/evenius/react-textarea-autosize (npm)

**Comment by ludwiczakpawel** [comment]
> I have a thought...what version of the preact-textarea-autosize is being used? So, the one that's published in npm appears to point to a github repo which is 4 years old. It seems like the forked version has had more maintenance:

cc @nickytonline maybe you could help here?

**Comment by nickytonline** [comment]
Thanks for the suggestion @richardeschloss. I'll take a peek at this.

**Comment by CrazyOptimist** [comment]
Same issue here.
Same env, same screen resolution.

**Comment by marcysutton** [comment]
I can also reproduce this in Chrome 86 on a new Mac (and very unlikely to be cached). It happens when I open and close the DevTools, and when I click on the "Add up to 4 tags" or "Write your post content here" fields to move focus from the "New post title here" field.

**Comment by sshine** [comment]
As described in #12453, I can reproduce this bug by enabling uBlock Origin in my Chrome 87 on MacOS 10.15.7.

**Comment by ludwiczakpawel** [comment]
> As described in #12453, I can reproduce this bug by enabling uBlock Origin in my Chrome 87 on MacOS 10.15.7.

I tried to repro that with uBlock Origin as well but it doesn't seem to be an issue for me this time either.

**Comment by richardeschloss** [comment]
Is it easier to repro on Windows machines?

**Comment by nickytonline** [comment]
The component we use for the title input is [preact-textarea-autosize](https://www.npmjs.com/package/preact-textarea-autosize). So maybe it's an issue with that component potentially in whatever scenario causes this issue. I tried to recreate the issue like Marcy mentioned, but it still works fine for me.

**Comment by ludwiczakpawel** [comment]
One potential cause for that is a combination of that preact component with our current layout on /new view - we use `flex: 1 auto` on some elements within the form thanks to which body textarea can take as much space as is available. So my only guess is that this `flex: 1 auto` is sometimes (?) enforcing title field to be shrinked... buuuut.. it's a guess...

Maybe someone who experience this issue could help me test something real quick: when it happens try to add extra class to the `.crayons-article-form__title` element: `shrink-0` (it will add `flex-shrink: 0` styles to this element) - I'm wondering if that could be it..

<img width="2024" alt="Zrzut ekranu 2021-02-2 o 09 45 44" src="https://user-images.githubusercontent.com/108287/106574711-8859e280-653b-11eb-8b75-bb83e79c8f01.png">

**Comment by nickytonline** [comment]
> One potential cause for that is a combination of that preact component with our current layout on /new view - we use `flex: 1 auto` on some elements within the form thanks to which body textarea can take as much space as is available. So my only guess is that this `flex: 1 auto` is sometimes (?) enforcing title field to be shrinked... buuuut.. it's a guess...
> 
> 
> 
> Maybe someone who experience this issue could help me test something real quick: when it happens try to add extra class to the `.crayons-article-form__title` element: `shrink-0` (it will add `flex-shrink: 0` styles to this element) - I'm wondering if that could be it..
> 
> 
> 
> <img width="2024" alt="Zrzut ekranu 2021-02-2 o 09 45 44" src="https://user-images.githubusercontent.com/108287/106574711-8859e280-653b-11eb-8b75-bb83e79c8f01.png">
> 
> 

Another thing is I think for this field, it could either be a text field or textarea. Does the preact-autosize component really gives us much in this scenario?

**Comment by ludwiczakpawel** [comment]
> Another thing is I think for this field, it could either be a text field or textarea. Does the preact-autosize component really gives us much in this scenario?

Not sure if I understand correctly? Are you suggesting using `input[type="text"]` for title? <-- that wouldn't work because we need (well, want) to autoresize this field while typing the title. And you can't do that with classic `input` - that's why it's a textarea.

If anything, we could try to play with `div[contenteditable]` since this is preact component anyway we could go wild ;p

**Comment by nickytonline** [comment]
Yeah, forget an input of type of text, but just a plain old textarea would be fine no?

**Comment by ludwiczakpawel** [comment]
@nickytonline oldschool textarea doesn't auto resize afaik

**Comment by nickytonline** [comment]
Good point. I was thinking of the drag handle, but that's not the same thing.

**Comment by cmgorton** [comment]
Another report of this happening:
[Bug report in forem.dev](https://forem.dev/darkogj/new-post-bug-4cp7)

**Comment by ludwiczakpawel** [comment]
@forem/frontend I summon you 🤓

**Comment by darkogj** [comment]
Confirmed this is happening on Chrome as well. Try to click away from the title box, and then click on it again.

**Comment by ludwiczakpawel** [comment]
@darkogj yea - that behavior did not reproduced the issue for me :) That's why it's very tricky bug to fix unfortunately (no one internally I talked to could repro it, but we clearly have seen several bug reports)...

**Comment by sshine** [comment]
@ludwiczakpawel I was able to reproduce it in #12453 by installing uBlock Origin on Chrome on Mac. I can still do this.

**Comment by ludwiczakpawel** [comment]
@sshine i tried that too but no success 🤷

**Comment by benhalpern** [comment]
I'm now seeing this bug on all my browsers and all accounts.

**Comment by benhalpern** [comment]
https://user-images.githubusercontent.com/3102842/108401425-53f84e80-71ea-11eb-9b5b-832c75e37d15.mov

**Comment by ludwiczakpawel** [comment]
@benhalpern hah! that's the thing! i can now repro that!

![FINALLY](https://media.giphy.com/media/AuwBPJztsEWkw/giphy.gif)

**Comment by darkogj** [comment]
This is weird that it didn't reproduce, I've tried it on browsers not
related to each other. It prob has to do with the screen resolution? What
OS are you using? What resolution?

**Comment by benhalpern** [comment]
I have a 15.4-inch (2880 × 1800) Macbook Pro, Mac OS 11.1 @darkogj 

My question here is whether we are sure this is accounts for _all_ the occurrences of this issue? @richardeschloss can you confirm?

**Comment by richardeschloss** [comment]
I just repro'd it and...found the Windows setting that is similar to the Mac one that fixes it!  On Windows 10, it's "Show animations in Windows". I can't believe it! I usually have that turned off for performance reasons. So, when it's unchecked, the problem of clipped textbox always appears. (Well I'll be damned!). When it's checked, the problem never occurs.

Windows 10 setting:
![title_clip_repro](https://user-images.githubusercontent.com/5906351/108454432-9b51ff80-7229-11eb-88cd-dc366e291408.png)

Corrected height after the fix:
![title_correctly_sized](https://user-images.githubusercontent.com/5906351/108454531-c9cfda80-7229-11eb-8e64-d3d8f145cec4.png)

Fwiw...I came across this doc on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by rhymes** [comment]
OMG we finally found a way to reproduce this, I'm so happy!

**Comment by richardeschloss** [comment]
This sounds like it'd make for an interesting article. This elusive bug literally required thinking outside the box...to go outside the browser to troubleshoot it. I am impressed and I never would have guessed it be an OS config setting.
