### ISSUE TITLE
Signup overlay frontend issue

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#10122]
**Describe the bug**

With recent changes to the signup overlay, a bug has been introduced - the way the modal is being rendered doesn't really work well in all cases. When you scroll down before the modal shows up, you will actually not see the modal and page will become blockec.

**To Reproduce**

1. Log out.
2. Go to any article.
3. Scroll down a little.
4. Try to like that post. It should prompt the modal. And it does, but depending on where you are on the page you may or may not see it.

**Expected behavior**

Modal ALWAYS being visible.

**Screenshots**

[Video](https://d.pr/v/lZEmmh).

**Comment by rhymes** [comment]
I think this is also related to https://github.com/forem/forem/issues/10101

**Comment by ludwiczakpawel** [comment]
@rhymes correct. I'll fix it.
