### ISSUE TITLE
Link in notification overflows

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10121]
**Describe the bug**

Link in notification overflows in mobile

**To Reproduce**

1. Login as user1
2. Paste a long link as message 
3. Login as user2
4. Go to notification
5. Look for the notification to message by user1
6. You can see the link overflowing

**Expected behavior**

It should either be truncated or should wrap to the next line

**Screenshots**
![overflow](https://user-images.githubusercontent.com/8092120/91810540-adc08880-ec4b-11ea-8a0a-7c7e7b7af28f.jpeg)

**Smartphone:**

- Device: ReadMi note 6 pto
- OS, version: Android 9
- Browser, version: Brave browser 1.12.113

**Comment by citizen428** [comment]
@Rafi993 Thos does sound like #7170, right?

**Comment by Rafi993** [comment]
> @Rafi993 This does sound like #7170, right?

Yes it does

**Comment by Link2Twenty** [comment]
This one should be quite a simple fix.

Adding these 2 lines should do it 😁

```css
overflow: hidden;
text-overflow: ellipsis;
```

https://github.com/forem/forem/blob/877bdba176759163f07e69b814400d4537bffa7c/app/assets/stylesheets/notifications.scss#L144-L159
