### ISSUE TITLE
yarn test fails because of 24hr time format

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10141]
**Describe the bug**

Running the command yarn test fails because of 24hr time format while pc is set to 24hr time format

**To Reproduce**

1. Change your time format to 24hrs
2. Run yarn test
3. Test will fail

**Expected behavior**

Test should not fail irrespective of time format

**Screenshots**

![failing_tests](https://user-images.githubusercontent.com/8092120/91884896-7df19f00-eca4-11ea-9cd8-132c2edec618.png)

**Desktop:**
- OS, version: Ubuntu 20.04

**Comment by Rafi993** [comment]
Hi there, If this bug is not taken I can help with this (since the test are already failing for me).

**Comment by rhymes** [comment]
@Rafi993 sure, go ahead, thank you!
