### ISSUE TITLE
Support emgithub.com embed using Liquid Tags

### ISSUE THREAD

**Issue by kuncevic** [forem/forem#10151]
In my blog posts I want to be able to embed the github repo code directly using [emgithub.com](https://emgithub.com/) 
This way there is no need to create a separate gist file as you can just target any lines on existing github repo. 

![image](https://user-images.githubusercontent.com/1283734/91928705-12e5ae00-ed20-11ea-9e4b-a4448a9e55b7.png)

Here is the [link example](https://emgithub.com/embed.js?target=https%3A%2F%2Fgithub.com%2Fkuncevic%2Fprogressive-state-management-with-ngxs%2Fblob%2Fmaster%2Fsrc%2Fapp%2Freactive-service%2Fservices%2Fbasic-example%2Fcounter.service.ts%23L16-L40&style=zenburn&showBorder=on&showLineNumbers=on&showFileMeta=on) generated by emgithub. Currently there is no way to embed [emgithub.com](https://emgithub.com/)  using Liquid Tags.

Having [emgithub.com](https://emgithub.com/)  support would reduce a lot of hassle of providing code-samples within the [dev.to](dev.to) posts as well as maintaining the samples if they needs to be updated in the future.

**Comment by rhymes** [comment]
Hi @kuncevic, thanks for the proposal. 

We have a `{ {% github %}` liquid tag, so it might be worth expanding that?

We support issue links, repo links, pull request links. We also have a gist tag.

It's true that we don't support direct files though :) 

BTW this is a legit request for a new liquid tag, I'm going to mark it as such

**Comment by kuncevic** [comment]
@rhymes of i c, if `{% github %}` can be expanded to produce similar outcome the way emgithub.com does. Basically to be able to select any lines of github repo file and to embed that within dev.to

**Comment by kuncevic** [comment]
@rhymes yea i c, if `{% github %}` can be expanded to produce similar outcome the way emgithub.com does. 
Basically to be able to select any lines of github repo file and to embed that within dev.to as a code snapshot

**Comment by rhymes** [comment]
@kuncevic cool, I'll keep this one as it refers to a different website and link you the issue related to GitHub permalinks so that you can subscribe to it if you want https://github.com/forem/forem/issues/6777

**Comment by ShubhankarKG** [comment]
Hey, is this on? Can I have a shot at this one?

**Comment by citizen428** [comment]
I assigned you the issue @ShubhankarKG, thanks!

**Comment by ShubhankarKG** [comment]
I guess that script tags won't get executed in the preview mode. Is there any way to do so? The script tag runs well after the post is published, but I'm not able to get any output from script when previewing in the editor.

**Comment by rhymes** [comment]
@ShubhankarKG not sure, it'd be easier to troubleshoot it around a draft PR

**Comment by ShubhankarKG** [comment]
Okay, no issues. I'll file my PR in a day or two then

**Comment by cmgorton** [comment]
@ShubhankarKG 
Thanks so much for your work on this issue so far.
We have a new process moving forward to address feature requests and especially those that are more DEV specific. 
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
