### ISSUE TITLE
HTML is showing in "Following tags" description

### ISSUE THREAD

**Issue by markmead** [forem/forem#10154]
**Describe the bug**

The tag description in "Following tags" is printing HTML

**To Reproduce**

Go to [here](https://dev.to/dashboard/following_tags)

Currently showing on #rails and #javascript tags.

Don't show HTML

**Screenshots**

<img width="340" alt="Screenshot 2020-09-02 at 09 11 43" src="https://user-images.githubusercontent.com/50486078/91956259-53cbcb80-ecfc-11ea-9083-ffba8779d1fe.png">

**Desktop (please complete the following information):**

- OS, version: MacOS Catalina, 10.15.6 
- Browser, version: Chrome, 84

**Comment by markmead** [comment]
I'll take this on if/when available.

**Comment by rhymes** [comment]
Thank you @markmead, please go ahead!
