### ISSUE TITLE
Dark-mode toggle

### ISSUE THREAD

**Issue by vasco3** [forem/forem#10165]
**Is your feature request related to a problem? Please describe.**

It's annoying to have to set it from the settings everytime the light in my room changes

**Describe the solution you'd like**

It could be a keyboard shortcut to toggle between dark and light theme. Or quicker access to theme selection (less clicks) and without having to reload the page.

**Describe alternatives you've considered**

An alternative could be a middle tone theme like WesBos Cobalt for VSCode which can be used in both bright light and dim rooms.

**Additional context**

**Comment by rhymes** [comment]
Hi @vasco3, would this issue cover it https://github.com/forem/forem/issues/3222 ?

Thank you!

**Comment by vasco3** [comment]
@rhymes that's even better, thanks!

**Comment by rhymes** [comment]
I'm going to close this then, please add your comment over there ;-)

Thank you!
