### ISSUE TITLE
Display date of listings

### ISSUE THREAD

**Issue by rhymes** [forem/forem#10164]
**Is your feature request related to a problem? Please describe.**

Right now both https://dev.to/listings and the single page for a listing do not display any kind of date.

**Describe the solution you'd like**

Listings are currently sorted by reverse `bumped_at` in the index, so we should probably display that but I also think the creation date is meaningful

**Describe alternatives you've considered**

Show either creation or bump date

**Additional context**

Dates should be localized for the user that's viewing them

**Comment by Rafi993** [comment]
Hello there, If this is not taken I would like to help :)

**Comment by Rafi993** [comment]
I just realised this feature does not have tag "ready for dev". I'll take it up if it is "ready for dev".

**Comment by rhymes** [comment]
@Rafi993 this is definitely ready for dev, thank you!

**Comment by Rafi993** [comment]
Awesome thanks @rhymes
