### ISSUE TITLE
Videos page: title is duplicated

### ISSUE THREAD

**Issue by rhymes** [forem/forem#10166]
**Describe the bug**

For some odd reason the `<title>` in https://dev.to/videos is duplicated. I tried a quick fix but I was able to triplicate instead.
There must be something else going on.

Currently it is: "DEV VideosVideos - DEV Community 👩‍💻👨‍💻Videos - DEV Community 👩‍💻👨‍💻"

**To Reproduce**

1. Go to https://dev.to/videos
1. Check the title

**Expected behavior**

Expect the title to be similar to that of https://dev.to/pod

**Comment by diogoosorio** [comment]
✋ giving this one a go!
