### ISSUE TITLE
Cannot unfollow tags 

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#10174]
**Describe the bug**

I'm unable to unfollow tags that I'm currently following. In other words, when I click on the "following" button for a tag, the button changes to "follow" making it appear that I've unfollowed it, but when I refresh the page it says "following" again.

**To Reproduce**

1. Go to 'https://dev.to/dashboard/following_tags' -->
2. Use this page to see what tags you're following and navigate to a tag's landing page (`dev.to/t/nameoftag`) -->
3. Click on "following" next to the tag's name
4. See it change to "follow"
5. Refresh the page and you'll see it saying "following" again.

**Expected behavior**

When I click on "following" next to a tag's name, it should change to "follow" and remain that way even when I refresh the page.

**Screenshots**

Here's a link to a video of the issue in action - https://share.getcloudapp.com/bLuRy8yB

**Additional context**

A DEV user reported this issue and I've confirmed it is happening to me too.

It appears that another user was experiencing a similar (but different) issue here previously - https://github.com/forem/forem/issues/5397

**Comment by madarsbiss** [comment]
Works fine on Chrome 85.0.4183.83 (64-bit)

**Comment by michael-tharrington** [comment]
I'm out of date! 😅

I'm on Chrome 84.0.4147.135 (64-bit)

Let me see if updating solves the problem for me. Thanks for the suggestion!

**Comment by michael-tharrington** [comment]
I'm officially updated, but still experiencing issues.

So I returned to https://dev.to/dashboard/following_tags and it looks like #jokes is no longer an option there, so maybe I succesfully unfollowed it? I returned to https://dev.to/t/jokes and it still says "following". The pattern continues — I click to change it to "follow" -> refresh -> it's back to "following".

I thought that maybe this is some sort of caching issue so repeated the steps with a different tag: #history. I navigated to https://dev.to/t/history -> clicked on "following" -> it changed to "follow" -> I refresh -> it returns to saying "following" ... but, when I go back to https://dev.to/dashboard/following_tags "history" is gone.

**Comment by madarsbiss** [comment]
I would try to logout, clear cache, disable all extensions (for testing), login and see if the problem persists

**Comment by citizen428** [comment]
I experience the exact same behavior as @michael-tharrington on the latest Firefox Developer Edition.

**Comment by Link2Twenty** [comment]
You're not really following it anymore but the `userData()` function hasn't updated. You can write *this* 

```js
JSON.parse(userData().followed_tags).map(o=>o.name)
```

in your console to see what tags you're 'following' but then you can check the API like this <https://dev.to/follows/137?followable_type=Tag> (this is specifically for the history tag).

___

I've done a little more digging and <https://dev.to/async_info/base_data> is wrong

**Comment by takmar** [comment]
Hi. Can I work on this?

**Comment by rhymes** [comment]
@takmar sure, I'll assign the issue to you
