### ISSUE TITLE
Multiple domain support via APP_DOMAIN

### ISSUE THREAD

**Issue by jdoss** [forem/forem#10178]
**Is your feature request related to a problem? Please describe.**

In order to support many domains within the app we need the APP_DOMAIN env var to support many domains. 

**Describe the solution you'd like**

The application supports many domains in a comma separated list via APP_DOMAIN env. 

`APP_DOMAIN=foo.com,foo.biz,foo.forem.com`

**Comment by rhymes** [comment]
@jdoss as `APP_DOMAIN` is used for a few things, including building URLs at runtime, should be add a separate `APP_DOMAINS` variable for that?

How does the Rails app otherwise determine which absolute URL it should use to send email links, cookie domain, and other things?

**Comment by citizen428** [comment]
I'm with @rhymes on this one. Would keeping `APP_DOMAIN` as-is and adding a new var like `ADDITIONAL_DOMAINS` work for you @jdoss?

**Comment by jdoss** [comment]
That works for me! We just need the application to work with the main domain (APP_DOMAIN)  and any other additional domains (blah-12234.forem.cloud for example).

**Comment by rhymes** [comment]
Another aspect: as this doesn't seem to be about subdomains of the same domain but entirely different domains, we'll have to figure out how to deal with login session and multiple domains as the cookie can't be shared. But it might be easier if we just ignore that and expect that a person going to foor.com and foo.biz will have to essentially sign in again

**Comment by citizen428** [comment]
@jdoss I don't think that's something Rails supports too well out of the box, but it can be achieved. Maybe we can do a session during cooldown, gather requirements, etc.

**Comment by benhalpern** [comment]
@rhymes @jdoss I'm not sure it's critical we go as far as sharing sessions. As I understand it, the primary concern is that an admin could work on `tempname.forem.cloud` and then move to `canonicalforem.com`?

I think serving multiple domains will actually be _not so tough_, but not trivial, but what is our immediate need here? The way I understand it— we can have traefik supporting multiple domains— but what is the hard constraint around the app supporting multiple at the same time, could we not have a situation where we "support" one at a time and work to make it easier to swap the `APP_DOMAIN` when needed?

I'm just trying to get to the bottom of what our biggest needs are here.

**Comment by jdoss** [comment]
That is the usecase yes. We want to allow users to access `tempname.forem.cloud` before they point DNS so they can configure the app for their needs, onboard early users and get everything ready before they point their main domain name at the application.

I can easily configure the systems side of things to support many domains but that doesn't mean you could log in or do anything useful if you are accessing a domain that isn't the main `APP_DOMAIN`. Switching APP_DOMAIN requires an app restart. Totally doable but would require more work on systems end and I thought we were trying to avoid having to create a support event or app restart event.

**Comment by cmgorton** [comment]
Hey @jdoss do you think this would make a good RFC? If not we may want to close the issue here. Thanks!

**Comment by jdoss** [comment]
We solved with some other methods. Closing.

**Comment by manish-nference** [comment]
> We solved with some other methods. Closing.

@jdoss What method did you use for solving this?

**Comment by jdoss** [comment]
I honestly can't remember. You can grep through the code base for APP_DOMAIN and you should be able to track down how we solved this in the code. I believe we set a starter domain and then you can set a real domain on the first user signup.

**Comment by zhengjiuzhe0706** [comment]
@jdoss What method did you use for solving this?Can you provide your solution

**Comment by jdoss** [comment]
¯\_(ツ)_/¯

**Comment by sbowenwilliams** [comment]
> ¯_(ツ)_/¯

I think you dropped this:
\\

**Comment by zhengjiuzhe0706** [comment]
> ¯_(ツ)_/¯

Okay, thank you all the same, but I still hope you can think of a solution to this problem
