### ISSUE TITLE
Service worker cache is generating invalid markup

### ISSUE THREAD

**Issue by diogoosorio** [forem/forem#10173]
**Describe the bug**

Once you hit a scenario where the service worker is triggered to render the page header from cached data, the HTML that's getting generated is invalid (the `<html>`, `<head>`, `<body>`, ... tags are getting duplicated).

The browser (at least Chrome which is what I'm using), does a great job "hiding" the problem so the issue isn't quite visible just by looking at how the page is rendered (I found this while developing #10170 as I was specifically looking at those meta tags).

**To Reproduce**

1. Go to any page, e.g. https://dev.to/niharrs/10-things-to-know-as-a-fullstack-developer-2kip
1. Right click -> "View page source"
1. Search for the term `<html`
1. See that its present twice on the page

**Expected behavior**

No duplicated tags are generated.

**Screenshots**

Here's the HTML I'm seeing on the page:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title></title>
      <meta name="last-updated" content="2020-09-02 18:51:59 UTC">
      <meta name="user-signed-in" content="true">
        <!-- Experimental web monetization payment pointer for micropayments -->
        <!-- It lets readers make micropayments to websites they visit. -->
        <!-- This is step 1: Get live in production to test for platform-wide payment pointer. -->
        <!-- Step 2: Allow authors to set their payment pointer so they can directly monetize their content based on visitors. -->
        <!-- Step 3: Enable further functionality based on what we learn from this experimentation and how the ecosystem evolves. -->
        <meta name="monetization" content="$ilp.uphold.com/24HhrUGG7ekn">
      <meta name="environment" content="production">
      ...snipped the content for readability
</header>

        <div id="active-broadcast" class="broadcast-wrapper"></div>
        <div id="message-notice"></div>
        <div class="app-shell-loader">
          loading...
        </div>
    <!-- End Top Shell -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>10 Things To Know As A Fullstack Developer 👁️👄👁️ - DEV Community 👩‍💻👨‍💻</title>
  </head>

  <div id="base-payment-pointer" data-payment-pointer="$ilp.uphold.com/24HhrUGG7ekn"></div>
<style>.app-shell-loader {display: none;}</style>
<div id="page-content" class="universal-page-content-wrapper stories stories-show" data-current-page="stories-show">
  <div id="page-content-inner">
    
  <div id="author-payment-pointer" data-payment-pointer="$ilp.uphold.com/rXBmfEAWwKMi"></div>

...snipped the content for readability
```

**Desktop (please complete the following information):**

- OS, version: Mac OS
- Browser, version: Chrome

**Additional context**

I think this is a side effect of the service worker's request to - https://dev.to/shell_top - which returns the initial part of the page, including the `<html><head> ....`.

That response is then being appended to the existing DOM (which already has those nodes) == those tags get nested/duplicated. Disabling the service worker seems to make the problem go away.

**Comment by mstruve** [comment]
Hi there! We recently removed the majority of our Service Worker caching in https://github.com/forem/forem/pull/12834 With that change, I believe that this should no longer be an issue going forward. I am going to close this, please feel free to reopen if you continue to see this problem.
