### ISSUE TITLE
Vertical alignment of post title in notification

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10182]
**Describe the bug**

Vertical alignment of  post title in notification 

**To Reproduce**
 1. Go to notification
 2. Look at notification with post title

**Expected behavior**
Vertical alignment of notification title should be same at the notification message

**Screenshots**
![vertical_alignment_in_notification](https://user-images.githubusercontent.com/8092120/92076915-0f622d80-edd9-11ea-8298-9ab63cc857a1.png)

**Desktop:**

OS, version: Ubuntu 20.04
Browser, version: Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

**Additional context**

* This bug is actually caused because class ```notification-comment-reacted-link``` is inline-block while the rest of the elements in notification are inline

**Comment by Rafi993** [comment]
Adding ```vertical-align: middle``` to ```notification-comment-reacted-link``` should fix this

**Comment by citizen428** [comment]
Do you want to submit a PR for this @Rafi993? If yes I'll assign you this issue.

**Comment by Rafi993** [comment]
Yes, I can help with this. Thanks @citizen428
