### ISSUE TITLE
Improve UI/UX on smaller mobile devices (iPhone SE) in messages tab

### ISSUE THREAD

**Issue by jwedel** [forem/forem#1018]
**Describe the bug**
- The text box to enter the message is way to small
- The whole messages page only occupies 2/3rds of the screen (wasting space)
- It's had to select a word in that tiny box, especially of it wraps over more than one line. It starts to scroll or jump weirdly which makes editing very hard (This might be caused by the small text box and navigating with a finger on the screen)

**To Reproduce**

- Open messages tab on iPhone SE in Safari
- Try to enter a longer message
- Try to select a word or sentence that wraps over more than one line

**Expected behavior**
- On smaller mobile screen, the page should occupy as much space as possible in total. 
- The edit text box should also be as large as possible
- Selecting text should be possible without randomly scrolling / jumping

**Screenshots**
![image-1](https://user-images.githubusercontent.com/4849728/47613175-240d6600-da8a-11e8-93c9-dd0b14a965d3.jpg)

**Smartphone:**
- OS: iOS 12.0.1
- Browser: Safari
- Version: n.a.

**Comment by jessleenyc** [comment]
Hmm yeah this makes sense, especially for folks on the mobile app side as well. @benhalpern what do you think?

**Comment by jwedel** [comment]
BTW: I'm currently testing the dev.to iphone app. It takes up a little more vertical space than the web page but still, there is a lot of wasted space:
- The send button being as large as the edit box
- the side bar to switch between other devs (this should actually move to the top or to a separate screen)
- The padding/margin around the messages box

This works well on large screens but could be improved for mobile screens.

**Comment by maestromac** [comment]
not stale

**Comment by cmgorton** [comment]
@fdoxyz is this something that is still a problem? I know we have been changing a lot of things on mobile recently. If so I will leave this open but wanted to get your opinion on it since it has been open for awhile now. Thanks :)

**Comment by jwedel** [comment]
First, I have now an iPhone Mini, second im using the dev.to App. there, the ux of the message section has definitely improved a lot. I wouldnt consider this an issue anymore.

**Comment by cmgorton** [comment]
Thanks for letting me know @jwedel ! Going to go a head and close this issue then.
