### ISSUE TITLE
Fixing date duplication logic in app/javascript/listings/dashboard/rowElements/listingDate.jsx

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10233]
**Describe the bug**

1. Date format logic is duplicated in app/javascript/listings/dashboard/rowElements/listingDate.jsx
2. span tag is used instead of time tag
3. Missing title attribute

**Expected behavior**

Should use common date display logic and use time tag instead of span

**Additional context**

This should probably use common util function similar to PR https://github.com/forem/forem/pull/10217 for date formatting logic

**Comment by Rafi993** [comment]
If this not taken I can help with this issue.

**Comment by citizen428** [comment]
I assigned you the issue now @Rafi993, thanks for volunteering!
