### ISSUE TITLE
Link to post sections

### ISSUE THREAD

**Issue by eduherminio** [forem/forem#10234]
Hi,

It would be **awesome** to be able to link to dev.to post sections.
I'm currently cross posting from GitHub pages and I would certainly love to replace all my other post references with dev.to equivalent ones, but I'm not able to since some of them aim to a specific section of another blog post.

For instance, in my original post I have references to other articles (i.e. https://eduherminio.github.io/blog/previous-article#Conclusion) and it wouldn't make sense to replace that link with the whole dev.to hosted article (https://dev.to/eduherminio/previous-article) when cross posting to dev.to.
Ideally, I would expect https://dev.to/eduherminio/previous-article#Conclusion to work.

Apologies if I've missed any similar issue and keep up the good work!

**Comment by citizen428** [comment]
Note that this is already possible if you set an anchor in your Markdown, like this:

```markdown
## [Conclusion](#conclusion)
```

Here's an example draft with a couple of Lorem Ipsum paragraphs and a conclusion, the link will directly take you to the latter:

https://dev.to/citizen428/link-section-test-2c4c-temp-slug-9839207?preview=16733547845302d298a8839c15140b86ce2b9aeb4c8baaddcc05f86b37710fd93b22330c33a58f040d58e23a24c1d91cb837cd0e280f4849da087d08#conclusion

**Comment by eduherminio** [comment]
Awesome @citizen428, thanks!

**Comment by Link2Twenty** [comment]
Actually, you don't need to do anything special all headings can be linked to by default.

For instance <https://dev.to/eduherminio/waiting-in-arduino-i-delay-function-is-not-your-friend-4keh#case-study>

I believe it's title to lower case, all special characters removed, spaces replaced with hyphens and backticks (`) replaced with `-raw-` and `-endraw-` depending on where they are.

**Comment by eduherminio** [comment]
Wow, you're totally right @Link2Twenty, I don't know how could I missed that yesterday. I'll update the links when I have some spare time.

Thanks for your help folks! I guess that the feature request doesn't make sense any more @citizen428, feel free to close the issue if appropriated.

**Comment by Link2Twenty** [comment]
It does mean this documentation is wrong.

https://github.com/forem/forem/blob/9ee54bfe45725e2dfaab856aea1fea0315dc0413/app/views/pages/_editor_markdown_help.html.erb#L11-L20

**Comment by eduherminio** [comment]
I also noticed that those links (without doing anything special to the target header) only work if you open them in a new tab,
If you just left-click them in a post (try the first one in [this section](https://dev.to/eduherminio/waiting-in-arduino-ii-millis-function-to-the-rescue-33k6#going-back-to-our-case-study)), they take you to the top of the linked post rather than to the right section.

**Comment by Link2Twenty** [comment]
Oh interesting, because of the routing.

**Comment by Link2Twenty** [comment]
I guess we'd need to look for the hash in here when it comes in on `newUrl`

https://github.com/forem/forem/blob/e33029856161c21288c4e4b432d4111b0428fb94/app/assets/javascripts/base.js.erb#L115-L173

**Comment by eduherminio** [comment]
Thanks @Link2Twenty!

**Comment by receter** [comment]
> I also noticed that those links (without doing anything special to the target header) only work if you open them in a new tab, If you just left-click them in a post (try the first one in [this section](https://dev.to/eduherminio/waiting-in-arduino-ii-millis-function-to-the-rescue-33k6#going-back-to-our-case-study)), they take you to the top of the linked post rather than to the right section.

This is still the case, linking from one article to another using an anchor does not work internally.
https://dev.to/receter/linking-to-subheadings-not-working-internally-3o6p
