### ISSUE TITLE
data-testid is present in production build

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10248]
**Describe the bug**

data-testid added to components for unit testing is present in production builds. It could be removed by using https://www.npmjs.com/package/babel-plugin-jsx-remove-data-test-id

**To Reproduce**

1. Go to dev.to
2. Open developer tools
3. Inspect article
4. You can see data-testId

**Expected behavior**

data-testId should not be present in production build

**Screenshots**

![class_and_id_false](https://user-images.githubusercontent.com/8092120/92493108-bdbf0600-f211-11ea-81e9-c17f2dd1dda8.png)
 

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Comment by nickytonline** [comment]
@Rafi993 and @rhymes, I wouldn't consider this a bug. I think Kent C. Dodds explains it best in https://github.com/testing-library/react-testing-library/issues/479#issuecomment-529548194 . Perhaps though in the case of `<Article />` component, the `data-testid` might not be necessary.

**Comment by Rafi993** [comment]
> @Rafi993 and @rhymes, I wouldn't consider this a bug. I think Kent C. Dodds explains it best in [testing-library/react-testing-library#479 (comment)](https://github.com/testing-library/react-testing-library/issues/479#issuecomment-529548194) . Perhaps though in the case of `<Article />` component, the `data-testid` might not be necessary.

I never thought about it i that way. Thanks for that. Shall I close this issue and related PR?

**Comment by Rafi993** [comment]
> @Rafi993 and @rhymes, I wouldn't consider this a bug. I think Kent C. Dodds explains it best in [testing-library/react-testing-library#479 (comment)](https://github.com/testing-library/react-testing-library/issues/479#issuecomment-529548194) . Perhaps though in the case of `<Article />` component, the `data-testid` might not be necessary.

I think I missed the last sentence in the comment you are right in this case data-testid could be removed from article.

**Comment by nickytonline** [comment]
In fact, I was looking at article.test.jsx and the only usage of `data-testid` is to find the entire article DOM node in its tests. This is not necessary. Remove `data-testid` from the `<Article />` component and we just need some improvements to the tests in article.test.jsx.
