### ISSUE TITLE
[Documentation] Small issues in Windows Installation

### ISSUE THREAD

**Issue by kmcginn** [forem/forem#10240]
**Describe the bug**

I recently ran through the Windows installation instructions for setting up Forem, and I encountered a few issues/areas of improvement:

1. The `tar` command in the Elasiticsearch installation section has a slightly incorrect filename; it is missing `-oss` from `elasticsearch-oss-7.5.2-linux-x86_64.tar.gz`.
1. The `bin/setup` script will fail at various points if Elasticsearch, the PostgreSQL server, and the Redis server are not running. If someone is following the instructions to the letter, those should all be running when you run the script. However, if you're trying to keep things clean and kill the processes after testing them out (like I did 😬 ), you'll run into some issues. So it might be nice to have a note in the documentation saying that those three should be running before execution. (Maybe eventually the `bin/setup` script could check to see if they are running, and either try to start them or fail gracefully?)
1. When running `bin/startup`, I encountered a very strange error from the sidekiq process triggered by Foreman:
```
23:26:59 sidekiq.1   | 2020-09-06T06:26:59.301Z pid=18837 tid=230h WARN: Errno::ENOENT: No such file or directory - bs_fetch:atomic_write_cache_file:chmod
23:26:59 sidekiq.1   | 2020-09-06T06:26:59.301Z pid=18837 tid=230h WARN: /home/kmcginn/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/compile_cache/iseq.rb:38:in `fetch'
23:26:59 sidekiq.1   | /home/kmcginn/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/compile_cache/iseq.rb:38:in `load_iseq'
[many more stack trace lines under the gems folder]
23:26:59 sidekiq.1   | /home/kmcginn/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
23:26:59 sidekiq.1   | /home/kmcginn/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
23:26:59 sidekiq.1   | exited with code 1
```
I'm not quite sure what this was, but running sidekiq by itself for the first time with `bundle exec sidekiq` seemed to clear it up, so I'd like to add a note suggesting running it once before your first startup to the start-app.md doc.

**Desktop (please complete the following information):**

- OS, version: Windows 10, Version 2004
- Browser, version: N/A

**Additional context**
I'd like to make the changes to the documentation myself, if that's okay, to get my feet wet contributing to Forem. 😄 I'll be opening up a PR soon-ish, once this issue has an official number.

**Comment by kmcginn** [comment]
Per the bot's comment, I'd like to claim this issue 🙂

**Comment by citizen428** [comment]
Thanks @kmcginn, I assigned you the issue now.
