### ISSUE TITLE
Add more social icons to organisations.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10250]
Add more social icons to organisations.

Add social icons and URLs for FB, Instagram to create organisation form and allow them to be displayed in the organisations view.

**Comment by Rogue-Halo** [comment]
I like this idea, not claiming it yet but I'm keeping an eye on it.

**Comment by cmgorton** [comment]
Hey Lee! Thanks for sharing this issue. I think this would be a pretty interesting conversation to have on Forem.dev so that we could all talk about the trade-offs, complexities, and user experience behind this. :) Would you be interested in kicking off a conversation on Forem.dev? Thanks!
