### ISSUE TITLE
Consider No Mouse Fridays in the Application

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#10260]
**Is your feature request related to a problem? Please describe.**

Consider having "No Mouse Fridays" as part of our accessibility initiative.

**Describe the solution you'd like**

The simplest way to do this would be to include Marcy Sutton's package [No Mouse Days](https://github.com/marcysutton/no-mouse-days) when running in development mode.

**Describe alternatives you've considered**

This could be done with a browser extension that allows you to modify CSS for a page, but that requires work which means friction.

**Additional context**

**Comment by benhalpern** [comment]
I love the idea of this. @marcysutton's library seems great. Would it indicate that you are in no-mouse mode on the screen? That seems like it would be helpful.

**Comment by nickytonline** [comment]
Out of the box, the package does not do that, but it would not be that difficult to add a little banner somewhere on the site while it's active.

```javascript
if (process.env.NODE_ENV === 'development') {
    import("no-mouse-days")
        .then((data) => {
         // add a DOM element with the text "No mouse mode is activate"
         // or something along those lines.
        })
}
```

**Comment by marcysutton** [comment]
So we discussed this yesterday, which was really interesting! It sounded like enabling No Mouse Days with a command-line flag or option when you build the site locally would make it opt in and more predictable. I originally made the package to be cheeky and thought it would be impactful (and kinda funny) to disable the mouse cursor for an entire day each week. Which was admirable, but also potentially confusing to contributors. With an opt-in flag and some documentation, you could still get some of the same "nudge" benefit without confusing or bugging the heck out of everyone.

We also talked about the package itself injecting some kind of visible banner into pages when active, so users know there's something hiding the mouse cursor. I can tackle that in the No Mouse Days package, just wanted to mention it here.

Thanks for your thinking on this!

**Comment by mirie** [comment]
Great concept, but closing this issue based on the feedback/discussion on the closed PR
