### ISSUE TITLE
No Option to write

### ISSUE THREAD

**Issue by Lakkapatri** [forem/forem#10269]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by citizen428** [comment]
Can you please provide the information requested in the issue template, your DEV username, etc.?
