### ISSUE TITLE
Unable to close expanded article in moderator view

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10265]
**Describe the bug**

Unable to close expanded article in moderator view

**To Reproduce**

1. visit http://dev.to/mod
2. Click on article
3. Close the expanded article
4. Closing the expanded view will fail

**Expected behavior**

Expanded view of the article should close

**Screenshots**

![close_expanded_article](https://user-images.githubusercontent.com/8092120/92639870-0f42c000-f2fa-11ea-9d0f-69b5358104fb.gif)

**Desktop:**

OS, version: Ubuntu 20.04
Browser, version: Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

**Comment by citizen428** [comment]
Did you want to look into this yourself @Rafi993? From  a quick look, it seems that `const articleDocument = top.document;` isn't quite right. I managed to get a whole of the correct document like this in a console, maybe that helps:

```js
    const articleIframe = top.document.querySelector('.article-iframe');
    const articleDocument = articleIframe.contentDocument;
```
`

**Comment by Rafi993** [comment]
> ```js
>     const articleIframe = top.document.querySelector('.article-iframe');
> ```

sure I can help thanks @citizen428

**Comment by Rafi993** [comment]
> ```js
>     const articleIframe = top.document.querySelector('.article-iframe');
> ```

Same function is also called while closing the moderator panel when viewing the article directly. There top.document points to the right context but when the same things gets rendered as iframe this breakage is caused.

**Comment by Rafi993** [comment]
The moderator menu button is also hidden in /mod route (that would be the way only to open the panel back if it is closed)
![close_button](https://user-images.githubusercontent.com/8092120/92742029-d871b600-f39c-11ea-8c48-64d3f8fd7b37.png)

https://github.com/forem/forem/blob/master/app/javascript/actionsPanel/initializeActionsPanelToggle.js#L27-L35

I think the intention was to not have this right panel closed at all. So the actual bug might be that this close icon is rendered when visiting /mod view.  any thoughts on this?

**Comment by Rafi993** [comment]
![close_icon](https://user-images.githubusercontent.com/8092120/92742673-7d8c8e80-f39d-11ea-8b4d-d8dde5475e0e.png)

I meant this close icon

**Comment by citizen428** [comment]
Pinging @Zhao-Andy, he probably has the necessary context here @Rafi993 😃

**Comment by msarit** [comment]
> I think the intention was to not have this right panel closed at all in /mod route. So the actual bug might be that this close icon is rendered when visiting /mod view. any thoughts on this?

@Rafi993 you are exactly right 😄  In the `/mod` view, the Mod Actions Panel is always meant to be open and side-by-side with the article being moderated.

The panel's non-working "X" button is a known bug; right now, you click the article to open and close it.

**Comment by Rafi993** [comment]
Awesome. Thanks @msarit can I creare a pr to hide that x button in `/mod` route since it cannot be closed? Is that ok?

**Comment by msarit** [comment]
@Rafi993 Absolutely! Got for it, and thank you!

**Comment by Rafi993** [comment]
> @Rafi993 Absolutely! Got for it, and thank you!

Awesome, thank you.
