### ISSUE TITLE
Add Google Drive Video liquid tag

### ISSUE THREAD

**Issue by Maulikdes** [forem/forem#10271]
**Is your feature request related to a problem? Please describe.**

I want to embed a video in the blog which users can directly view on the page and don't have to navigate to a particular link. I saw that there already have an option to embed youtube and Vimeo video links but I don't want to post my videos on any of such platform but my google drive and want to share it from there

**Describe the solution you'd like**
So my request is if we can have a feature of embedding google drive videos too like Youtube and Vimeo

**Comment by lightlace** [comment]
I'd like to tackle this issue!

**Comment by rhymes** [comment]
@lightlace cool, I've assigned it to you!

**Comment by rhymes** [comment]
Hi @lightlace, as the conversation around this has been dormant lately and as we review our integration with external services to be less DEV specific and more mindful of the diverse array of users in the Forem ecosystem, I went ahead and removed the `ready for dev` label in the meantime
