### ISSUE TITLE
Action bar is full screen and blocks article

### ISSUE THREAD

**Issue by ReeceM** [forem/forem#10286]
**Describe the bug**

The 'crayons' action bar that has the heart, unicorn and bookmark icons fill the entire width of the screen on the browser.

This blocks the article and you cannot read anything

**To Reproduce**

1. Go to [dev.to](https://dev.to)
2. Click on any of the articles to view it
3. Observe the grey bar is across the visible screen area

**Expected behavior**

You should be able to read the article without any obstructions from the UI on the pages. The bar should be on the side

**Screenshots**
<img width="1280" alt="devto" src="https://user-images.githubusercontent.com/2767904/92951356-7f6a5680-f45e-11ea-8f3a-f424b921b547.png">

**Desktop (please complete the following information):**

- OS, version: macOS Sierra 10.12.6
- Browser, version: Safari 12.1.2

It doesn't happen on the latest chrome version

**Smartphone (please complete the following information):**

(Doesn't affect a smartphone)

- Device: iPhone 6s
- OS, version: 12.4.1
- Browser, version: Safari

**Additional context**

N/A

**Comment by fdoxyz** [comment]
Hi @ReeceM thank you for the bug report. I wasn't able to reproduce on macOS Catalina 10.15.5 and Safari 13.1.1 (15609.2.9.1.2)

Have you tried manually refreshing (with `CMD + R` not just browsing from one area of the app to another) or emptying your cache? I've seen these types of problems happen before when HTML/CSS updates are released

**Comment by ReeceM** [comment]
Hi @fdoxyz I forgot to mention that in the initial issue info that I have cleared cache via `ALT + CMD + E`

I have also opened the console to set safari to ignore cache when reloading in the network tab. I have also use the `ALT + CMD + R` option to reload the page when the console is open.

In all cases the action panel thing is across the entire area. Even though this has worked when other situations happen similar to this.

**Comment by KVanSant** [comment]
Hi! I was able to reproduce the issue in Safari 12.1 on macOS Mojave. The issue appears to have to do with position: sticky not being applied to the class "crayons-article-actions".

<img width="1267" alt="Screen Shot 2020-09-20 at 10 00 10 PM" src="https://user-images.githubusercontent.com/10014693/93734256-57c96b80-fb8d-11ea-8722-c206b52321ae.png">

I was able to fix in the dev tools using `position: -webkit-sticky`.  According to https://caniuse.com/?search=sticky, `position: sticky` only works in Safari 7.1 - 12.1 with a prefix.

<img width="906" alt="Screen Shot 2020-09-20 at 10 12 37 PM" src="https://user-images.githubusercontent.com/10014693/93734550-8ac02f00-fb8e-11ea-8274-9f5e6150ce1e.png">

Hope that helps! If you'd like me to setup a PR for this I'm more than happy to.

**Comment by ludwiczakpawel** [comment]
@KVanSant that analysis was very helpful, thanks! I'll add that prefix in.

---

@nickytonline Does this have anything potentially in common with recent changes to autoprefixer? Is this something we can address to be handled automatically?
