### ISSUE TITLE
Remove CAPTCHA for mods

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#10283]
**Is your feature request related to a problem? Please describe.**

Kind of... mods are trusted users and regularly reporting spam/abuse to us. While they have specific mod tools that help to efficiently report comments/articles/users, they occasionally need to use the public https://dev.to/report-abuse route to provide more context about what they are reporting.

We've heard feedback that CAPTCHA is slowing folks down here.

**Describe the solution you'd like**

Remove CAPTCHA on dev.to/report-abuse for mods.

**Describe alternatives you've considered**

I've not actually considered any other alternatives here, but am open to suggestions!

**Additional context**

A few mods brought up that CAPTCHA on this page is annoying and time consuming.

There's another issue here that focuses on upgrading reCAPTCHA - https://github.com/forem/forem/issues/9919 ... the convo there has a number of details that could be relevant:
1) Should we switch from reCAPTCHA to hCAPTCHA?
2) We need to make sure that our CAPTCHA practices are accessibility-friendly.

**Comment by yellow1912** [comment]
Or use the recaptcha v3. I really don't understand why the current captcha keeps showing me picture after picture. There can be much better way to do this for example a hidden credit/trust system.

**Comment by yellow1912** [comment]
![Screenshot_20201003-125157](https://user-images.githubusercontent.com/374134/94984605-e966af00-0577-11eb-83d7-da9dcb3c7cbc.png)
So easy to spam

**Comment by yellow1912** [comment]
![Screenshot_20201003-125757](https://user-images.githubusercontent.com/374134/94984623-15823000-0578-11eb-8925-79ce08bcae7d.png)
And impossible to report, keeps showing me picture after picture.

**Comment by rhymes** [comment]
Hi @yellow1912 have you tried to disable your extensions? I'm not sure but it could be that. What browser are you using?

**Comment by yellow1912** [comment]
Let me try, I was on chrome, had tons of extensions. I will try on edge which does not have any extension and will report back.

**Comment by yellow1912** [comment]
Hello, seems like captcha on chrome works fine, the one I'm having problem with is actually the Android app version of dev.to.

**Comment by rhymes** [comment]
@yellow1912 thank you! If you've installed the DEV Android app and are experiencing issues with it, please open an issue to the app repository so we can better track it: https://github.com/thepracticaldev/DEV-Android

thank you!
