### ISSUE TITLE
Soften inline code background color

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [forem/forem#10334]
**Is your feature request related to a problem? Please describe.**

The background color for inline code is too dark, making it difficult to read blog posts that have a lot of inline code:

![image](https://user-images.githubusercontent.com/19352442/93216418-b29a3780-f735-11ea-9f46-6fcd7de6b244.png)

**Describe the solution you'd like**

Softening the background color to `rgba(0, 0, 0, 0.08)` makes the UI easier on the eyes:

![image](https://user-images.githubusercontent.com/19352442/93216521-d9586e00-f735-11ea-8ab7-03a82c3e24f6.png)

**Comment by ludwiczakpawel** [comment]
Hey, I've picked slightly different value for that color (`rgba(0,0,0,0.1)`) so it should look a bit softer than the current version. Expect a PR in few mins.
