### ISSUE TITLE
Unable to move beyond Code of Conduct page 

### ISSUE THREAD

**Issue by khiga8** [forem/forem#10333]
**To Reproduce**

I just signed up for forem.dev via twitter authorization and was redirected to 
https://forem.dev/onboarding?referrer=https://forem.dev/. 

I see a pop up regarding code of conduct that I cannot get past.
It looks like there may be a checkbox, but I am unable to scroll to it.

**Expected behavior**

I would expect there to be a checkbox that I can click that would let me move beyond this page. 

**Screenshots**

![2020-09-14 20 09 21](https://user-images.githubusercontent.com/16447748/93161600-b7280700-f6c7-11ea-8c5b-d14137fd1e1c.gif)

**Desktop (please complete the following information):**

- OS, version: 85
- Browser, version: Chrome

**Comment by citizen428** [comment]
@khiga8 This is a known issue that we're currently working on fixing. There are invisible checkboxes to the left of the two the two sentences starting with "You agree". If you select them (a bit of guesswork) then the Continue button will work.

**Comment by khiga8** [comment]
Got it, thanks!
