### ISSUE TITLE
Bugs with code snippets

### ISSUE THREAD

**Issue by ewaDev** [forem/forem#10336]
**Describe the bug**
The bug appears with the formatting of the code in blog posts. 

When a code snippet is present, the snippet is not resized to fit the device - instead it is long and has a scroll bar. This could be how it is intended - i am not sure.

On the mobile view, there is no scrollbar unless the user interacts with the snippet so it is hard to see that you can scroll. I think there should be obe visible at all times, not only on interaction.

I am also not sure how this affects readability of the code on mobile devices.
**To Reproduce**

1. Create a new post.
2. Insert a code snippet with a long line - for example : 
```JavaScript
console.log("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
```
3. Publish.
4. On desktop you will see the code snippet is resized ( not sure if this is how it is intended)  
5.  On mobile you will see the code snippet is resized ( not sure if this is how it is intended)  but there is no scrollbar unless user interacts with it.

**Expected behavior**
Scroll bar should be visible at all times
Could the code snippet be "popped out" so that the code which does not fit can be seen bigger? would help with reading code on mobile devices. 

Thanks!!

**Screenshots**
![image](https://user-images.githubusercontent.com/17544636/93243444-1ba69d00-f780-11ea-9087-e8c60a38c8a5.png)
![image](https://user-images.githubusercontent.com/17544636/93243676-6fb18180-f780-11ea-9d1a-3956591bdced.png)

Attached.

**Desktop please complete the following information):**

- OS, version: Windows
- Browser, version: Browser, version: Version 85.0.4183.102 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

Tested on the pc, with chrome tools mimicking mobile. Pixel 2 in the screen shot

**Additional context**

post for testing: https://dev.to/lost_semicolon/tiless-19d4-temp-slug-4754613?preview=96cae2f620343c3c12d44b510b5bcd0923a167dd257cdff0027542b78c2e2fe02827369919594e014a3d2685712ffe1440c5360cb203d9b49874129b

**Comment by fdoxyz** [comment]
I'm adding a comparison screenshot side by side of Android (chrome) and iOS (Safari) of the sample post. Pinging @forem/design to hear their thoughts on the topic

<img width="1440" alt="Screen Shot 2020-09-15 at 14 48 00" src="https://user-images.githubusercontent.com/6045239/93263238-bf815000-f762-11ea-9f9d-bd12d8f09e50.png">

**Comment by lisasy** [comment]
Thank you for sharing, @ewaDev !

Your suggestions were:

> **Expected behavior**
> 1. Scroll bar should be visible at all times
> 2. Could the code snippet be "popped out" so that the code which does not fit can be seen bigger? would help with reading code on mobile devices.

I think they're great. I think the scrollbar should be visible at all times to signify that it's possible to view the overflow. 

Suggestion #2 would be a cool feature: I'm reading it as if there were a button where you can expand out and see code the way you could in Github, where it takes over the entire screen.

**Comment by fdoxyz** [comment]
I think this SO could help anyone that feels like they want to tackle this issue: https://stackoverflow.com/a/1202542/3462026

As a reminder:

```
To our amazing contributors: issues labeled type: bug are always up for grabs, but for feature requests, please wait until we add a ready for dev before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.
```

**Comment by ludwiczakpawel** [comment]
> When a code snippet is present, the snippet is not resized to fit the device - instead it is long and has a scroll bar. This could be how it is intended - i am not sure.

It is indeed intended. We intentionally don't want code snippets to wrap to the next line because that often affects readability of the code and author's intentions. That's pretty common behavior for code blocks.

But we do have some issue with code blocks rendering on desktop Safari as well as mobile browsers - long lines of code wrap to the next line and they should not. I have a PR addressing this issue: #10346 

---

> Scroll bar should be visible at all times

The visibility of the scrollbar is usually defined by the browser itself. We could potentially "overwrite" that default behavior but I don't think this is a good practice.

---

> > 2. Could the code snippet be "popped out" so that the code which does not fit can be seen bigger? would help with reading code on mobile devices.
>
> Suggestion #2 would be a cool feature: I'm reading it as if there were a button where you can expand out and see code the way you could in Github, where it takes over the entire screen.

Yeap, good idea. [We've been already thinking about this](https://github.com/forem/forem/issues/8990) but we're a bit short on resources :D

**Comment by Link2Twenty** [comment]
Ben did ask for a solution to this a while ago and it doesn't look like anything was implemented.

<https://dev.to/ben/safari-is-word-wrapping-the-pre-tag-creating-inappropriate-code-wrapping-a9g>

___

>Scroll bar should be visible at all times

As Paweł says this is not that straight forward on touch devices or macs without implementing a custom scrollbar. It might be possible to add something to the design to imply scrolling is possible though.
