### ISSUE TITLE
User can't remove empty series from dashboard view

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#10358]
**Describe the bug**

When a user views series from their dashboard (i.e. https://dev.to/yourusername/series) they're able to see "0 Part Series" for posts that they've drafted in a series but perhaps deleted for some reason along the way.

There's no way to delete the 0 part series and it doesn't seem like these should exist here in the first place.

**To Reproduce**

1. Create 2 posts under the same series
2. Unpublish and delete both posts
3. Navigate to your user dashboard (https://dev.to/dashboard)
4. Scroll down to "series" in the lefthand column and click on it (i.e. https://dev.to/yourusername/series)
5. You should see the series name you just created with "(0 part series)" beside it

**Expected behavior**

Only published multi-part series should appear in this list. It's debatable that drafted series should appear in the list too. But if a series has been deleted, then it should not appear in the list.

If 0 part series must appear in the list, then they should be deletable by the user.

**Screenshots**

![Image 2020-09-16 at 5 42 54 PM](https://user-images.githubusercontent.com/16007075/93395455-f54a3580-f843-11ea-980d-e129540f703d.png)

**Additional context**

This came about because a user wrote in asking how to remove an empty series.

**Comment by rhymes** [comment]
Hi! I think this is a duplicate of https://github.com/forem/forem/issues/9658

**Comment by michael-tharrington** [comment]
You're absolutely right. Sorry for missing this. I'll close this issue in favor of @beeman's.
