### ISSUE TITLE
Dev.to API not updating on request

### ISSUE THREAD

**Issue by timbogdanov** [forem/forem#10374]
**Describe the bug**

Recently I started playing around the the Dev.to api. After creating a few posts I decided to edit one of them. I went in and changed the cover image. Going back to my portfolio where the api is fetched I noticed the the cover image did not reflect the newly updated one.

### Fetching the post I get the old not-updated json object

```javascript
 useEffect(() => {
    axios
      .get('https://dev.to/api/articles?username=timbogdanov')
      .then((res) => {
        setPosts(res.data);
      });
  }, []);
```

But when visiting the link `https://dev.to/api/articles?username=timbogdanov` it shows the newly updated cover image 🤷‍♂️

**Expected behavior**

When fetching the api it should return the new updated in this case cover image url

**Screenshots**

console logging the output
![Alt Image](https://puu.sh/GtSxp/eb3757ff61.png)

visiting the link
![Alt Text](https://puu.sh/GtSy0/3c2864112b.png)

**Desktop (please complete the following information):**

- macOS, 11 Beta 20A5364e
- Chrome, 85.0.4183.102 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Hi @timbogdanov - I'm not sure I understood correctly: the Axios call returns cached data but if you visit manually the URL then it works? Could it be Axios that's caching data?

**Comment by timbogdanov** [comment]
> Hi @timbogdanov - I'm not sure I understood correctly: the Axios call returns cached data but if you visit manually the URL then it works? Could it be Axios that's caching data?

Ok, so currently I have 3 published posts. when I fetch them with axios it only returns 2.

**Comment by timbogdanov** [comment]
This looks to be an age constraint on the backend, closing issue

**Comment by Rage-ops** [comment]
I'm having the same issue

**Comment by rhymes** [comment]
@Rage-ops how are you fetching the data?

**Comment by arifszn** [comment]
I am fetching using axios and having the same issue. How did you solve it @timbogdanov ?

**Comment by pj-iitk** [comment]
Was this solved ? I am facing the same issue .
