### ISSUE TITLE
Publicly indicate if someone edits their comments

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#10373]
**Is your feature request related to a problem? Please describe.**

Yes, this is important for preventing gaslighting. I.e. It's helpful to stop situations where User A says something, then User B responds, User A modifies their comment so that User B’s response doesn’t make sense. (Not a great explanation, but sums it up well enough!)

**Describe the solution you'd like**

If someone edits their comments, we should publicly indicate it in the comment with the word "(edited)" appearing near the date of the comment similar to the UX that DEV uses in Connect chat channels for when folks edit their comments (pic below). It'd be nice to keep that UX somewhat consistent.

**Describe alternatives you've considered**

I've not thought of any alternatives, but am open to suggestions.

**Additional context**

Here's what a comment looks like when it's edited in Connect:

![Image 2020-09-17 at 5 28 49 PM](https://user-images.githubusercontent.com/16007075/93530325-61dc3780-f90b-11ea-8af2-7df35155ffcb.png)

**Comment by KarenEfereyan** [comment]
@rhymes this is up for grabs then? I am a new contributor to forem. My windows build is 1903 so I am looking at other ways to get my development environment set up. I would love to take on this issue.

**Comment by rhymes** [comment]
Hi @KarenEfereyan, welcome to Forem! I don't have experience on setting the code up in Windows but @maestromac could probably give you pointers in addition to what's written in the installation docs if you get stuck

I think we do need this feature as well, as mentioned by @michael-tharrington  :-)

On the technical side:

Comments have a `edited_at` column which indicates if the comment has been updated (and when). 

There are a bunch of views where a comment is built from, indicatively:

- https://github.com/forem/forem/blob/master/app/views/comments/_comment_proper.html.erb which renders the page where you see a comment, for example https://dev.to/_garybell/comment/14p92
- https://github.com/forem/forem/blob/master/app/views/notifications/_comment.html.erb which contains the comment notification, though I don't think we need to show it there obligatorily
- https://github.com/forem/forem/blob/master/app/assets/javascripts/utilities/buildCommentHTML.js.erb which I think it renders the comments at the bottom of an article page, like https://dev.to/vponamariov/how-i-built-architecture-of-uptime-monitoring-service-54h8#comments

**Comment by citizen428** [comment]
@KarenEfereyan If you would like to tackle this issue without setting up your dev environment first, give GitPod a try:

https://docs.dev.to/installation/gitpod/

I'll assign you this issue now since you expressed interest, thanks for volunteering! 😃

**Comment by michael-tharrington** [comment]
Hey @KarenEfereyan, thanks for being so quick to take this on. I'm really siked we're getting this in place!

Quick question — will the solution only affect newly edited comments or all previous comments too?

I think either way would be acceptable. But, if I could pick between the two, I think it'd be best if it affected previous comments too.

**Comment by KarenEfereyan** [comment]
> Hey @KarenEfereyan, thanks for being so quick to take this on. I'm really siked we're getting this in place!
> 
> Quick question — will the solution only affect newly edited comments or all previous comments too?
> 
> I think either way would be acceptable. But, if I could pick between the two, I think it'd be best if it affected previous comments too. 

Im not sure how itll work out. Im still setting up my environment. I should be done with this tomorrow

**Comment by KarenEfereyan** [comment]
![forem](https://user-images.githubusercontent.com/56835876/93665720-bbaa4200-fa70-11ea-947a-cb97c5612fff.PNG)

@rhymes @michael-tharrington  @citizen428 , yesterday wasn't the best for me. I wasted close to 3gb trying to update my windows following the links for the windows installation in the docs. I was unsuccessful.  I have however been able to successfully set up my dev environment using gitpod except that now I am confused as to how to use it. Here's how my gitpod looks.

**Comment by KarenEfereyan** [comment]
I'm thinking that the edit btn should be beside the preview and reply button, right? Like this....
![editbtn](https://user-images.githubusercontent.com/56835876/93668868-79402f80-fa87-11ea-910d-ce6beab48cbc.PNG)

**Comment by citizen428** [comment]
Thanks for your effort @KarenEfereyan and sorry this isn't a smooth process for you.

> I was unsuccessful.

Could you elaborate a bit on what went wrong? Is there something we should update in our docs?

> successfully set up my dev environment using gitpod except that now I am confused as to how to use it

It's basically VSCode in the Cloud. Gitpod itself has good [documentation](https://www.gitpod.io/docs/).

> I'm thinking that the edit btn should be beside the preview and reply button

That's where it already is when a user edits their own comment:

<img width="819" alt="Screen Shot 2020-09-21 at 09 51 47" src="https://user-images.githubusercontent.com/47985/93729762-1322ec00-fbf0-11ea-9ddd-4dd65cccf3ee.png">

**Comment by Link2Twenty** [comment]
I think in terms of a quick design something like this should work

![edited label](https://user-images.githubusercontent.com/3534427/93865661-85fa9880-fcbe-11ea-8a26-1fa6a9abb400.png)

Which would be a change to this code

https://github.com/forem/forem/blob/4e591fea1c8e062176fb79b1ed5546fa947fee1f/app/views/comments/_comment_date.erb#L1-L7

___

Something like this, though this is not tested it's just an idea.

```erb
<div class="comment-date">
  <a href="<%= decorated_comment.path %>">
    <time datetime="<%= decorated_comment.published_timestamp %>">
      <%= decorated_comment.readable_publish_date %>
    </time>
  </a>
  <% if !decorated_comment.edited_at.blank? %>
    •
    <span title="<% decorated_comment.edited_at %>">
      EDITED
    </span>
  <% end %>
</div>
```

@rhymes I don't think there is a readable version of edited_at, is there?

**Comment by KarenEfereyan** [comment]
@Link2Twenty thank you. I'm guessing this syntax is jekyll? I'm really new to it. Yes i think that design works, or maybe like was pointed out by the person who raised this, issue, the word edited, in small case in a bracket? I think any works fine by the way. How will I be able to test my changes though? Since I am using gitpod

**Comment by Link2Twenty** [comment]
> I'm guessing this syntax is jekyll?

The syntax is Ruby's [templating language](https://docs.ruby-lang.org/en/master/ERB.html) but basically is HTML with a little bit of Ruby sprinkled in.

> maybe like was pointed out by the person who raised this, issue, the word edited, in small case in a bracket?

Yeah that can work, the example they gave is how an edited message looks in the messaging area of Forem (called connect)

> How will I be able to test my changes though? Since I am using gitpod.

I'm not actually sure where the test data come from, I guess we'd have to change the test data to include some edited comments.

**Comment by Link2Twenty** [comment]
OK, I've done a little digging. In the console at the bottom of GitPod you can type the following (press return after each line).

```bash
psql PracticalDeveloper_development
UPDATE comments SET edited_at = current_timestamp;
exit
```

This will update every comment to say it was updated just then.

**Comment by KarenEfereyan** [comment]
@Link2Twenty that's a lot but let me try it out right now

**Comment by Link2Twenty** [comment]
To get out of the select list you have to press the `q` key

**Comment by Link2Twenty** [comment]
![Forem__edit-cells](https://user-images.githubusercontent.com/3534427/93905217-9d537900-fcf2-11ea-8faf-cee75a4b64a5.gif)

**Comment by KarenEfereyan** [comment]
@Link2Twenty Im thinking that video is for me. It's a little too fast. Here is a screenshot showing what I have currently. What i'm confused about is how to test those changes and see the edit button
![forem2](https://user-images.githubusercontent.com/56835876/93908497-975f9700-fcf6-11ea-94f6-90fc9da6bebc.png)

**Comment by KarenEfereyan** [comment]
@Link2Twenty im starting to get the essence of the video. Could you make another one and be a little slower. Using your mouse to highlight each step of the way? Please?

**Comment by citizen428** [comment]
@Link2Twenty Thanks for helping out here. I'm not sure if there's real value in adding an edited comment to the seeds, if I need something like that I usually do it with my own local user (create a commend and edit it in this case). At least you exactly which comment will be the updated one.

@KarenEfereyan Doing this through a SQL console can be a bit intimidating if you have never done it before, it's much easier in a Rails console:

```ruby
# update a single comment
Comment.last.update(edited_at: Time.now)

# update all comments
Comment.update_all(edited_at: Time.now)
```

You can start a Rails console by typing `rails c` into the terminal Window on GitPod:

<img width="976" alt="forem_forem_-_master" src="https://user-images.githubusercontent.com/47985/93977746-27f4b080-fda5-11ea-817e-46b61120c62c.png">

Once it has started, execute one of the commands above to mark the newest or all comments as edited:

<img width="931" alt="forem_forem_-_master" src="https://user-images.githubusercontent.com/47985/93977905-67230180-fda5-11ea-9895-7c457781038e.png">

**Comment by Link2Twenty** [comment]
@citizen428 That's a much better way to do it 😊

@KarenEfereyan In your screen shot it looks like you did everything right, you just need to load the preview.

Press the preview button.

![Preview button](https://user-images.githubusercontent.com/3534427/93984551-db48af80-fd7b-11ea-8ddf-c7f873746a39.png)

Then if you would rather have the preview in a new tab press the pop out button

![Pop out button](https://user-images.githubusercontent.com/3534427/93984724-164ae300-fd7c-11ea-8249-09a8e90ae964.png)

**Comment by KarenEfereyan** [comment]
@citizen428  and @Link2Twenty let me try that now. I'm sorry if i caused any inconveniences, Just really trying to learn

**Comment by KarenEfereyan** [comment]
I don't seem to have the preview button. Just the outline and the github button @Link2Twenty and @citizen428 
![nopreview](https://user-images.githubusercontent.com/56835876/94010247-959cde80-fd9d-11ea-8476-53c760e0b97b.png)

**Comment by Link2Twenty** [comment]
@KarenEfereyan you have nothing to be sorry for, if people hadn't been patient with me when I started out I'd still know nothing now 😊

**Comment by Link2Twenty** [comment]
It's still loading give it a few moments

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan you have nothing to be sorry for, if people hadn't been patient with me when I started out I'd still know nothing now 😊

that made me feel much better. I don't think its still loading though. The workspace's been open for the past 10mins

**Comment by Link2Twenty** [comment]
What does this bit say now?

![image](https://user-images.githubusercontent.com/3534427/94011634-946cb100-fd9f-11ea-9ab2-d03025197f34.png)

**Comment by KarenEfereyan** [comment]
> What does this bit say now?
> 
> ![image](https://user-images.githubusercontent.com/3534427/94011634-946cb100-fd9f-11ea-9ab2-d03025197f34.png)

I don't understand this. But up till now, I do not see a preview button.  I don't know why that is

**Comment by Link2Twenty** [comment]
Ok let's go through it.

Click this link <https://gitpod.io/#https://github.com/forem/forem>.
It will take a few minutes to load but then you'll see what looks like VSCode (do you use VSCode normally?)

You see when it first loads I don't have the preview button but that's because it's still loading.

![waiting](https://user-images.githubusercontent.com/3534427/94125716-a194a900-fe4e-11ea-8a64-6f8dff4fde56.png)

You see how it's running some commands for us? It's telling us it's waiting for port 3000 (this is where the test site will appear so it's waiting for us).

After waiting a few more minutes the text in that box has changed and we've got the preview button.

![complete](https://user-images.githubusercontent.com/3534427/94126034-0819c700-fe4f-11ea-8614-045b2beba938.png)

You see it's added a few more lines and now has changed in a way that allows us to type in

![image](https://user-images.githubusercontent.com/3534427/94126154-2b447680-fe4f-11ea-809a-59d1c5a8d1bf.png)

Now if we press the preview button we'll get a little panel like this, which also has the pop out button on it.

![image](https://user-images.githubusercontent.com/3534427/94126340-66df4080-fe4f-11ea-9896-211dcaddcb48.png)

Now when you make changes you just have to refresh the popped out page to see those changes.

**Comment by KarenEfereyan** [comment]
Trust me @Link2Twenty I saw all these steps. Except the preview button. Do you think that by any chance possible, we could have a zoom or google meet call and I could actually share my screen and you could explain to me better? If that would be at all possible, do let me know. I could whip up a meeting in less than a minute

**Comment by KarenEfereyan** [comment]
@Link2Twenty never mind. I've gotten the preview button. I am guessing the network was pretty bad earlier.
![Uploading newpreview.png…]()

**Comment by KarenEfereyan** [comment]
Now, let's see if I can get this to work

**Comment by KarenEfereyan** [comment]
@Link2Twenty i've gotten the preview button. Seems the network was bad earlier.
![newpreview](https://user-images.githubusercontent.com/56835876/94144413-ff35ef00-fe68-11ea-9280-6cee3eb23571.png)
Let's see if I can get this to work

**Comment by KarenEfereyan** [comment]
@Link2Twenty I'm trying to go over the steps again.
Step 1 : I've updated the _comment_date.erb file to look like the test code you sent me above. And i've run the psql practical dev command in the terminal. Here is how it looks 
![new1](https://user-images.githubusercontent.com/56835876/94145332-4a9ccd00-fe6a-11ea-99b0-8b3ffdfba12e.png)

**Comment by KarenEfereyan** [comment]
I ran this command, select id, LEFT(processed_html, 30) as processed_html, edited_at from comments order by id; 
![new2](https://user-images.githubusercontent.com/56835876/94145624-bf700700-fe6a-11ea-8ae9-6ee982f8bb3c.png)
 which then shows me the list of all available comments like this...

**Comment by KarenEfereyan** [comment]
![new3](https://user-images.githubusercontent.com/56835876/94146351-b469a680-fe6b-11ea-8cef-39c5e0efff15.png)
When I try to update the comments with these Id's , using this command, update comments set edited_at = current_timestamp where id in (1,3,5); 
I get this error

**Comment by Link2Twenty** [comment]
Yep so you don't need to log in to the preview, just find a comment you want to appear as though it's edited.

So if you click the first post you see with comments.
For me that's "Little Hands Clapping Saepe quia".

Scroll down to the comment and you see it says "Synth post-ironic chicharrones tote bag whatever marfa selvage actually. Sustainable vhs forage goth letterpress kogi mustache."

It looks like ID 5 matches that comment.

![image](https://user-images.githubusercontent.com/3534427/94146299-a3209a00-fe6b-11ea-94a7-e93f9a18593e.png)

so now I press q on my keyboard to close that list.

my update command now becomes

`update comments set edited_at = current_timestamp where id in (5);`

so I type that in and see this 

![image](https://user-images.githubusercontent.com/3534427/94146473-e7139f00-fe6b-11ea-8486-64c51630323a.png)

and that's it.

to reload the preview I press this button

![image](https://user-images.githubusercontent.com/3534427/94146558-01e61380-fe6c-11ea-96c0-91b52d3cb1ce.png)

And navigate back to that comment to see if the change has worked

**Comment by KarenEfereyan** [comment]
Oh okay. I get it now. I'll do it right now. That :q was my problem. I was figuring out  a way to quit that list. Give me a minute. Let me try that

**Comment by KarenEfereyan** [comment]
I thought the articles showing up in the preview should be synonymous to the description is the list of articles on the left. The other time the article with the title 'Synth ... something' corresponded with the id of 5. But ive tried refreshing the preview up to three times but I can't find any article in the preview similar to the one in the list. 
![new4](https://user-images.githubusercontent.com/56835876/94147938-e419ae00-fe6d-11ea-9ef0-dab9183bb283.png) I even tried using the search bar. Maybe my eyes missed it?

**Comment by Link2Twenty** [comment]
We're looking for comments not articles so click on an article with the comment icon like this:
![image](https://user-images.githubusercontent.com/3534427/94148124-1f1be180-fe6e-11ea-93be-e3416996dd45.png)
Scroll down to the comments section and you'll be able to find them in that list.

**Comment by KarenEfereyan** [comment]
Oh okay. See this
![new4](https://user-images.githubusercontent.com/56835876/94148526-a2d5ce00-fe6e-11ea-8f22-e0bc442f3f21.png)

**Comment by KarenEfereyan** [comment]
I guessed its worked now. But my laptop is dead now

**Comment by Link2Twenty** [comment]
I've made a super quick [video](https://www.youtube.com/watch?v=2RYvwYvkrFg) of me going through the steps I'm trying to show the tooltips at the end but my screen recorder didn't pick them up.

**Comment by Amorpheuz** [comment]
> `@rhymes` this is up for grabs then? I am a new contributor to forem. My windows build is 1903 so I am looking at other ways to get my development environment set up. I would love to take on this issue.

Hey @KarenEfereyan, Microsoft made WSL2 backward compatible with version 1903, Build 18362 or higher which should allow you to get WSL2 running with your current windows. If the GitPod approach doesn't end up working out, I can definitely help you out with getting it running on Windows!

**Comment by KarenEfereyan** [comment]
> I've made a super quick [video](https://www.youtube.com/watch?v=2RYvwYvkrFg) of me going through the steps I'm trying to show the tooltips at the end but my screen recorder didn't pick them up.
> 

Ill take a look at it. Electricity is a major problem for me over here

**Comment by KarenEfereyan** [comment]
> > `@rhymes` this is up for grabs then? I am a new contributor to forem. My windows build is 1903 so I am looking at other ways to get my development environment set up. I would love to take on this issue.
> 
> Hey @KarenEfereyan, Microsoft made WSL2 backward compatible with version 1903, Build 18362 or higher which should allow you to get WSL2 running with your current windows. If the GitPod approach doesn't end up working out, I can definitely help you out with getting it running on Windows!

That would be great. Do i set up a zoom meeting tomorrow while you take me through the steps?

**Comment by KarenEfereyan** [comment]
> > `@rhymes` this is up for grabs then? I am a new contributor to forem. My windows build is 1903 so I am looking at other ways to get my development environment set up. I would love to take on this issue.
> 
> Hey @KarenEfereyan, Microsoft made WSL2 backward compatible with version 1903, Build 18362 or higher which should allow you to get WSL2 running with your current windows. If the GitPod approach doesn't end up working out, I can definitely help you out with getting it running on Windows!

That would be great. Do i set up a zoom meeting tomorrow while you take me through the steps?

**Comment by KarenEfereyan** [comment]
> > `@rhymes` this is up for grabs then? I am a new contributor to forem. My windows build is 1903 so I am looking at other ways to get my development environment set up. I would love to take on this issue.
> 
> Hey @KarenEfereyan, Microsoft made WSL2 backward compatible with version 1903, Build 18362 or higher which should allow you to get WSL2 running with your current windows. If the GitPod approach doesn't end up working out, I can definitely help you out with getting it running on Windows!

That would be great. Do i set up a zoom meeting tomorrow while you take me through the steps?

**Comment by Amorpheuz** [comment]
> > > `@rhymes` this is up for grabs then? I am a new contributor to forem. My windows build is 1903 so I am looking at other ways to get my development environment set up. I would love to take on this issue.
> > 
> > 
> > Hey @KarenEfereyan, Microsoft made WSL2 backward compatible with version 1903, Build 18362 or higher which should allow you to get WSL2 running with your current windows. If the GitPod approach doesn't end up working out, I can definitely help you out with getting it running on Windows!
> 
> That would be great. Do i set up a zoom meeting tomorrow while you take me through the steps?

Would it be okay for you to contact me via [DEV Connect](https://dev.to/connect/@amorpheuz)? We can co-ordinate the call and other details over it. 

You will need to be on ` Version 1903 or higher, with Build 18362 or higher` for WSL2, which you can get via a minor Windows update if required. (Don't need to update versions)

**Comment by KarenEfereyan** [comment]
@Link2Twenty good evening. I'm so sorry I've been on and off.  I stay in Nigeria and in my area, electricity is a problem. We haven't had electricity in 2 days and that is why I have been mia. I am so sorry

**Comment by KarenEfereyan** [comment]
This issue has dragged on for a while and I am so grateful for the help and I have and am still learning so much. I wish I could have this issue completed tonight. I am free now. @Link2Twenty are you?

**Comment by KarenEfereyan** [comment]
@Link2Twenty im already watching the video by the way

**Comment by KarenEfereyan** [comment]
@citizen428 @rhymes @Link2Twenty does the work i did last solve the issue. I just commented on a post via dev and i edited it. I see why the edited span is needed. ![Screenshot_20200927-084924.png](https://user-images.githubusercontent.com/56835876/94359402-f0388200-009e-11eb-8162-d4ac9f9c5666.png)

**Comment by KarenEfereyan** [comment]
All im wondering now is if what ive done now solves that issue

**Comment by Link2Twenty** [comment]
> @Link2Twenty good evening. I'm so sorry I've been on and off. I stay in Nigeria and in my area, electricity is a problem. We haven't had electricity in 2 days and that is why I have been mia. I am so sorry. I seem to have gotten a hang of it though. It has been edited. Like so...
> [image]
> The next question I want to ask is, does the current implementation solve the issue? If not what more do I need to do?

No need to apologise 😊

That looks like it's exactly right. Now you need to make a pull request to request your code be merged into the main code base.

Once you've made the PR (pull request) some of the staff at forem will give it a look over and if they have any comments they'll make them, they may ask you to make a couple of changes but they will talk you through what they want. Once they're happy with it your code will be added to the code base for all forems including DEV 😁

**Comment by KarenEfereyan** [comment]
Yippie. But can i make a PR from gitpod? As i dont have the right dev environment set up

**Comment by Link2Twenty** [comment]
I'd suggest pressing the fork button on the top right of git
![image](https://user-images.githubusercontent.com/3534427/94417379-e8004580-0177-11eb-838c-4158cf8fe6d6.png)

Then in gitpod if you press the Git button 
![image](https://user-images.githubusercontent.com/3534427/94416819-37924180-0177-11eb-959d-9a35d908925d.png)

It will tell you you don't have permission but does give you a fork button.
![image](https://user-images.githubusercontent.com/3534427/94417235-bbe4c480-0177-11eb-8fb0-c7dc9171adc0.png)

press fork and it will ask you if you want to use the fork you just made
![image](https://user-images.githubusercontent.com/3534427/94417486-0c5c2200-0178-11eb-8561-7a7ff0f66394.png)

Press that top option and then you can push to your fork.

Visit your fork through git and you can create a PR from there.

**Comment by KarenEfereyan** [comment]
Thank you @Link2Twenty  ill let you know if i have any blockers

**Comment by KarenEfereyan** [comment]
@Link2Twenty @citizen428 I have made my changes and staged them. But when i try to make a PR, no changes are being found. Here is what the PR tab looks like from my forked copy of the forem repository. I thnk the comparison should be between this branch of my forked repo and master branch of the original main forem repo, right?
![branch](https://user-images.githubusercontent.com/56835876/94580137-75739080-0271-11eb-86d2-82dcd8b15455.png)
Meanwhile, here is how my PR page looks like
![compare](https://user-images.githubusercontent.com/56835876/94580316-ab187980-0271-11eb-8a1b-152834951195.png)
Am i to create a new branch? Though I thought the new branch is this one , karenefereyan/publicly-indicate/10373?
