### ISSUE TITLE
Bookmark a comment

### ISSUE THREAD

**Issue by flexdinesh** [forem/forem#1038]
**Problem**
Dev has grown into an open-minded discussion platform for developers from all backgrounds. Often, discussions in posts grow organically. Some comments are worthy of being a post on its own. Some comments highlight important points and references for the reader. There were times I wanted to bookmark a comment but I ended up bookmarking the post because we don't have the feature yet. Now, when I go through my bookmarks, I couldn't remember why I bookmarked a post and have to go through all the comments (and child-comments) to figure out why. Also, if I quickly want to recollect one of the comments, I couldn't remember on which post it was.

**Solution**
Ability to bookmark a comment and if it's not too much, I'd like to give each bookmark my own title/desc for reference.

**Comment by maestromac** [comment]
Thanks for this issue @flexdinesh . Sounds like a good feature. If implemented, would you prefer this pinned/bookmarked comment to be displayed or hiddened on your profile page?

**Comment by dimensi0n** [comment]
For me pinned and bookmarked are different but it we're good if we can pin a comment for our articles. Should I make another issue ?

**Comment by flexdinesh** [comment]
@maestromac I'd like everything in my dev profile to be public. I can't come up with any reason why I'd want to hide the bookmarked comments in my profile. I'd prefer it to be displayed.

**Comment by maestromac** [comment]
@dimensi0n yep, that sounds like a good feature request. Go ahead and create a separate issue.

**Comment by HugoLiconV** [comment]
It would be a great feature. 
I would like to work on it, but I'm not sure if it is hard to implement

**Comment by rhymes** [comment]
unstale

**Comment by dimensi0n** [comment]
No one wants to work on this ?

**Comment by arximughal** [comment]
I was gonna post the same thing. So, I'll just +1 this :) Pretty great feature since we get loads of long comments under posts and they are very informative. The ability to have those comments bookmarked for future reference would be great.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](https://github.com/forem/forem#community) for many of these feature requests that we need more discussion around. 

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](https://forem.dev/). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
