### ISSUE TITLE
Slack notification like current weekly mailing services

### ISSUE THREAD

**Issue by roeniss** [forem/forem#10386]
**Origin**

One of my favorite IT news source is [GeekNews](https://news.hada.io/weekly). It supports [weekly mailing](https://news.hada.io/weekly) and also [slack bot](https://news.hada.io/slackbot). This slack bot almost same contents with mail's. But more accessible to who uses slack so much time, as you can imagine.

**Describe the solution you'd like**

Add 'slack bot' feature. It would send weekly summing-up best posts using slack API. Of course it would have very limited parts so If interested he/she come to the websites for full contents.

**Additional context**

Belows are real example:

![image](https://user-images.githubusercontent.com/26613280/93659641-6f67fd80-fa82-11ea-9ab7-eac9bc5247c2.png)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).

**Comment by roeniss** [comment]
@cmgorton I'll check it. BTW your link (https://github.com/forem/forem/issues/forem.dev) returned 406. Would you check it please?

**Comment by cmgorton** [comment]
Ah sorry about that. It should have linked to forem.dev. 
[https://forem.dev/](https://forem.dev/)
