### ISSUE TITLE
I can't see footer of dev.to

### ISSUE THREAD

**Issue by roeniss** [forem/forem#10385]
**Describe the bug**

Due to infinite scroll UI on [main page](https://dev.to), I cannot touch footer until I manually disable my network.

**To Reproduce**

Scroll down on main page. you will always meet new posts instead of bottom fotter.

**Expected behavior**

Actually this is almost UI issue. AFAIN, most website, like facebook, doesn't put their information on bottom. I'm currently not sure where to put those info instead because I'm not familiar with design. All I know is that I cannot see footer! 🤣 

**Screenshots**

![image](https://user-images.githubusercontent.com/26613280/93659550-60348000-fa81-11ea-98cc-e9f20244e936.png)

**Desktop (please complete the following information):**

- OS, version: macOS latest
- Browser, version: chrome

**Additional context**

At this time I realize that i can see that when I clicked any posts.. but is it cool forever? Idk.

**Comment by citizen428** [comment]
Thanks for the report @roeniss! This seems to be a duplicate of #9034, can you please add a comment there and close this issue?

**Comment by roeniss** [comment]
of course!
