### ISSUE TITLE
Adding Web Monetization payment pointer doesn't work

### ISSUE THREAD

**Issue by ApoorvTyagi** [forem/forem#10407]
BUG report - After adding my web monetization payment pointer for my blog inside settings/misc, when i check the page source code it shows me a different payment pointer there

I checked visiting other blog as well, they all have the same payment pointer, it seems like everywhere there is a fixed same payment pointer👇
![image](https://user-images.githubusercontent.com/39600765/93784160-44c8a100-fc4a-11ea-8315-0545c0d3064b.png)

**Comment by citizen428** [comment]
The value you see here is `SiteConfig.payment_pointer`, which is indeed a site-wide setting. There is also a `payment_pointer` column on user, which gets rendered by the `app/views/shared/_payment_pointer.html.erb` partial in 3 places:

1. The user's profile page
2. Any articles written by the user
3. Any comments written by the user

The id of the correspoinding div is `author-payment-pointer`:

```html
  <div id="author-payment-pointer" data-payment-pointer=" $ilp.uphold.com/..."></div>
```

**Comment by ApoorvTyagi** [comment]
Yes, i checked my payment pointer is there in div id="author-payment-pointer"

Thanks.
