### ISSUE TITLE
Serving weird version of crayons.css

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#10408]
## Describe the bug

On some sites using Forem as engine, particular views are being broken. For example, look at

1. https://forem.dev/onboarding - this is broken view 🚨
2. https://dev.to/onboarding - this is **not** broken ok ✅
3. https://thismmalife.com/onboarding - this is **not** broken as well ✅

The reason why it's broken is because crayons.css file (one file with styles for our design system) is different on site 1. vs 2. and 3... We use lots CSS variables and on site 1 it seems like these variables are kinda preprocessed and translated into normal CSS values. Not sure why that happens BUT once thing I have noticed is: on site 1. we server crayons.css from assets folder: `https://forem.dev/assets/...` and on two other example we serve that file from some fastly.net server (due to caching or whatever - I don't know). I have checked it on other forem-powered sites as well and it does look like the ones serving CSS from assets folder are broken.

I have no idea why that happens and how to fix it but it is clearly a bug and the observation I described above is all I could find (**even though I'm not 100% sure this is the actual cause**). I can't see any other clue to figure it out :C 

## Expected behavior

Work.

## Screenshots

**Good**

![image](https://user-images.githubusercontent.com/108287/93787041-48e7c500-fc30-11ea-9eb8-37205ab864d2.png)

**Bad**

![image](https://user-images.githubusercontent.com/108287/93787095-58ffa480-fc30-11ea-9427-5dbbedd002c0.png)

**Comment by brandonleboeuf** [comment]
I am still having this issue on the Forem.dev "Create Account" page
<img width="503" alt="Screen Shot 2020-09-22 at 9 57 34 AM" src="https://user-images.githubusercontent.com/54607186/93913730-56e22800-fcba-11ea-9711-37c628e91f29.png">

**Comment by ludwiczakpawel** [comment]
@brandonleboeuf can you double check and clear your cache? It looks fine on my end.

**Comment by brandonleboeuf** [comment]
@ludwiczakpawel 

Confirmed! 
After clearing my cache, all looks good

<img width="1151" alt="Screen Shot 2020-09-23 at 7 20 43 AM" src="https://user-images.githubusercontent.com/54607186/94025669-9e75bc00-fd6d-11ea-9297-9c446648eb3d.png">
