### ISSUE TITLE
Support for dotnetfiddle.net

### ISSUE THREAD

**Issue by samfieldscc** [forem/forem#10402]
**Is your feature request related to a problem? Please describe.**

As a writer that blogs mainly about .NET and C#, I would like to be able to embed dotnetfiddle.net in my posts.

It might be a frustrating experience for users to exit the post to check or run code examples.

I would ask to expand the support that already exists for jsfiddle.net to include dotnetfiddle.net and maybe even other languages.

**Describe alternatives you've considered**

The current alternative is to use gists to include code snippets and link the users to external dotnetfiddle.net links.

**Comment by ShubhankarKG** [comment]
Hey @citizen428, I'm relatively new here. Could you point me in the right direction so that I could start working on this? Thanks :pray:

**Comment by citizen428** [comment]
Hi @ShubhankarKG, thanks for expressing interest in helping out, I will assign you this issue.

Some pointers:

1. Liquid tags are defined in `app/liquid_tags` and their corresponding specs in `spec/liquid_tag`.
2. All Liquid tags inherit from `LiquidTagBase`, which is defined in `app/liquid_tags/liquid_tag_base.rb` if you want to have a look at it.
3. The view of a Liquid tag can be found in a Rails partial, named `app/views/liquids/_[tag_name].html.erb`, in this case `app/views/liquids/_dotnetfiddle.html.erb`.
4. Please also update the documentation in `app/views/pages/_editor_guide_text.html.erb` and explain how the Liquid tag works.

@Link2Twenty's PR for the [JSFiddle](https://github.com/forem/forem/pull/1509) tag can serve as inspiration for your work.

**Comment by Link2Twenty** [comment]
It's worth noting since I built the tag it's become standard practice to build the iFrame in a `html.erb` view.

@mariocsee's PR for [updating the JSFiddle](https://github.com/forem/forem/pull/2746) tag can show a path for using `ActionController`

**Comment by citizen428** [comment]
Yes, that was the second point in my list above. I should probably have linked the follow up PR too, thanks for adding it!

**Comment by ShubhankarKG** [comment]
Hi, apologies for the delay :pray: , we have exams :sweat_smile: . I'm positive I'll be able to file a PR by the weekend. Thanks and apologies again :sweat_smile:

**Comment by rhymes** [comment]
@ShubhankarKG no worries, please take your time and good luck for the exams! :)

**Comment by ShubhankarKG** [comment]
Update: I have created the necessary files, but I'm not able to log in to add a snippet to see if my solution looks good. Is there a default username/password so that I can log in to the development env ? 

Thanks.

**Comment by rhymes** [comment]
@ShubhankarKG no but you can log-in with Twitter  / GitHub the same way you do on dev.to

**Comment by ShubhankarKG** [comment]
Awesome, thanks

**Comment by ShubhankarKG** [comment]
On attempting to login, I get a Github 404 page, unfortunately.

**Comment by Link2Twenty** [comment]
Are you using Gitpod? I noticed I couldn't log in to that.

**Comment by ShubhankarKG** [comment]
Nope, I'm on my local machine

**Comment by rhymes** [comment]
@ShubhankarKG can you provide additional details? Screenshot of the error? Is there anything logged in your JS console?

**Comment by ShubhankarKG** [comment]
![Screenshot from 2020-10-06 15-51-10](https://user-images.githubusercontent.com/50791000/95189788-f4297a00-07eb-11eb-9b41-9eff4883dfa3.png)

On clicking the Github button, I was redirected here : https://github.com/login/oauth/authorize?client_id&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fauth%2Fgithub%2Fcallback&response_type=code&scope=user%3Aemail&state=028561594ae0794ca644bf944b3128823733710614446980

**Comment by Link2Twenty** [comment]
Same errors from Gitpod

**Facebook:** 
![facebook error](https://user-images.githubusercontent.com/3534427/95190592-7a7f9500-07c7-11eb-8da7-0ec06dbb6319.png)

**Twitter:**
![twitter error](https://user-images.githubusercontent.com/3534427/95190570-6f2c6980-07c7-11eb-94f8-185990e73be5.png)

**Comment by rhymes** [comment]
@ShubhankarKG have you configured the GitHub keys? https://docs.dev.to/backend/auth-github/
@Link2Twenty have you configured the Facebook keys? https://docs.dev.to/backend/auth-facebook/

**Comment by ShubhankarKG** [comment]
Yup, that was it, apologies.

**Comment by ShubhankarKG** [comment]
Hey everyone, one final request, I was going to commit and this happened

```bash
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.18.x". Got "12.19.0"
error Commands cannot run with an incompatible environment.
```

Any suggestios would be great

**Comment by sau226** [comment]
My suggestion would be to bump the node version under ``engines`` in ``package.json`` to ``12.19.x`` or something similar and see how the change goes.

This change should technically work, however as there may be reasons a dependency is held back I will defer to more experienced community members on the matter.

**Comment by citizen428** [comment]
@ShubhankarKG Our Node dependency is currently locked to 12.18 (see `.nvmrc`). To get rid of this warning you need to use a Node version manager like [nvm](https://github.com/nvm-sh/nvm) (assumed by our documentation), [n](https://github.com/tj/n) or [fnm](https://github.com/Schniz/fnm) to install the correct version. Please consult our [installation docs](https://docs.dev.to/installation/) and follow the instructions for your operating system.
