### ISSUE TITLE
Squished Sloth footer image on forem.dev

### ISSUE THREAD

**Issue by KVanSant** [forem/forem#10414]
I'm not sure if this is the right place to report a bug for forem.dev...but here we are.

**Describe the bug**

The sloth image within the footer of forem.dev is squished. The image appears to have a specific size set of width: 52 and height: 120 however the image being used is a square and is being squished to fit within the fixed size. 

<img width="1372" alt="Screen Shot 2020-09-21 at 6 43 13 PM" src="https://user-images.githubusercontent.com/10014693/93837815-66229080-fc3c-11ea-9705-430a760dc1ad.png">
<img width="514" alt="Screen Shot 2020-09-21 at 6 43 25 PM" src="https://user-images.githubusercontent.com/10014693/93837820-6c187180-fc3c-11ea-8dd3-1af49350346f.png">

**To Reproduce**

Go to https://forem.dev/ and scroll to the footer to see the Sloth on the right hand side.

**Expected behavior**
The sloth in the footer at dev.to is NOT squished, the image is a rectangle. 

<img width="1339" alt="Screen Shot 2020-09-21 at 7 08 50 PM" src="https://user-images.githubusercontent.com/10014693/93838271-ec8ba200-fc3d-11ea-8bd1-c0826a3e2631.png">
<img width="576" alt="Screen Shot 2020-09-21 at 6 43 45 PM" src="https://user-images.githubusercontent.com/10014693/93837883-a71aa500-fc3c-11ea-9c0b-559ec8a67e85.png">

**Desktop (please complete the following information):**

- OS, version: macOS Catalina 10.15.6
- Browser, version: Chrome 85.0.4183.102 

**Additional context**

The image from forem.dev is a cropped version of what's used on dev.to. Appears the wrong image has been used. 

Might be beneficial to not have a fixed size set in case the image is changed in the future.

**Comment by citizen428** [comment]
@KVanSant Thanks for the report, this is indeed the right place 😃 I could have sworn this is a duplicate, but I can't find another issue right now, so maybe it just popped up in our Slack.

**Comment by Link2Twenty** [comment]
@citizen428 I had a post up about it on forem.dev, though it seems to have vanished.

**Comment by citizen428** [comment]
Thanks @Link2Twenty, much appreciated 😃

**Comment by ludwiczakpawel** [comment]
Closing since this should now be resolved.
