### ISSUE TITLE
Empty gist embed returns cryptic error for users when trying to save changes

### ISSUE THREAD

**Issue by samfieldscc** [forem/forem#10410]
**Describe the bug**

When a user tries to save changes in a post with the following:

{% gist %}

The following message is presented:

Whoops, something went wrong:
* base: undefined method `delete' for nil:NilClass

**To Reproduce**

1. Create a new post
2. Add the following text in the post: {% gist %}
3. Try to save changes or preview the post
4. Error message is displayed

**Expected behavior**

The user should be presented with a message that allows him to understand more easily where and what the problem is.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Google Chrome | 85.0.4183.102 (Official Build) (64-bit) (cohort: Stable)

**Additional context**

The problem is fixed when the URL is added to the  {% gist %}. But some users might not be able to find where the problem or can have a very frustrating experience using the platform.

**Comment by citizen428** [comment]
Thanks for the report @samfieldscc. Some of our Liquid tags certainly could do with more descriptive error messages 😅

**Comment by Rafi993** [comment]
Hello there, If this up for taking I can help with this.

**Comment by citizen428** [comment]
It's all yours @Rafi993, thanks!

**Comment by Rafi993** [comment]
> It's all yours @Rafi993, thanks!

Thank you @citizen428
