### ISSUE TITLE
Can't Update my twitter account link

### ISSUE THREAD

**Issue by ApoorvTyagi** [forem/forem#10425]
I changed my twitter account but can' update on my dev profile. It has feature to add links to various sites except twitter
![image](https://user-images.githubusercontent.com/39600765/94042489-48def500-fde9-11ea-8e37-314e2b7b087f.png)

**Comment by fdoxyz** [comment]
Hi @ApoorvTyagi, if you changed your twitter username you can logout from DEV and login again using your same twitter account. This should update your Twitter link on your profile page.

If you have an entirely new Twitter account that you want to migrate or the suggestion above doesn't fix your problem I would recommend you send an email to yo@dev.to for us to help with your situation.
