### ISSUE TITLE
Glitch liquid tag does not support ids with ~ in them

### ISSUE THREAD

**Issue by pavi2410** [forem/forem#10427]
**Describe the bug**

Glitch liquid tag does not support ids with `~` in them

**To Reproduce**

1. Create a new post
2. Write the following
	```liquid
	{% glitch ~the-super-tiny-compiler %}
	```
3. At the top, there will be an error message
	> Whoops, something went wrong:
	> - base: Invalid Glitch ID

**Expected behavior**

The glitch id containing `~` (tilde) should render correctly

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10 2004
- Browser, version: Firefox 81

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by Link2Twenty** [comment]
Yep, there is a regex that doesn't allow anything other than letters, numbers or hyphens.

https://github.com/forem/forem/blob/5eda086e782ef65d5fc14811de57a0efa90909ba/app/liquid_tags/glitch_tag.rb#L5

**Comment by irmela** [comment]
I'd love to work on it. Seems like a good ticket to get familiar with the codebase 🙂

**Comment by rhymes** [comment]
@irmela thanks! I've assigned you to it

**Comment by irmela** [comment]
@rhymes thanks! I’m on it 👩‍💻
