### ISSUE TITLE
Integration of a ready-made messenger to improve the user experience

### ISSUE THREAD

**Issue by volanar** [forem/forem#10420]
**Origin**

Messengers play an important role for community building software.
The chat solution to give end-users a fun, powerful way to interact and engage with viewers in real-time on community.

What should be the messenger for building communities?
1. Independent of the forem code to improve reliability.
2. Highly scalable.
3. Support for E2E encryption.
4. Support video conferencing.
5. Open source.
5. Support for federation.
6. Support for cloud platforms.
7. Support bots and integration with other instant messengers, for example slack.
8. Personal and group chats.
9. Voice and video calls.
10. Support for text, emoticons, gifs, emoticons, mentions, and attachment of files such as audio, video, images, links, or documents.
11. SDK for mobile apps.
12. Automatic translation of languages and others.

**Describe the solution you'd like**

I propose to integrate with rocket.chat.  Rocket.Chat is the most advanced free chat, which will replace the standard forem chat.
Rocket.chat meets all the criteria for community chat. 
It will be cool if you can connect multiple communities to a federise-enabled single rocket.chat installation or  rocket.chat cloud to communicate with all users on the all forem platforms.

**Additional context**

This solution is implemented in chat plus phpfox and una.io
https://www.phpfox.com/chatplus/
https://una.io/page/view-product?id=10
![2020-09-22_21-42-12](https://user-images.githubusercontent.com/20200970/93924945-16b49100-fd1e-11ea-921c-26c9bafbc668.png)
![2020-09-22_21-37-03](https://user-images.githubusercontent.com/20200970/93924952-1916eb00-fd1e-11ea-9e41-7ab5865d67be.png)
![2020-09-22_21-39-46](https://user-images.githubusercontent.com/20200970/93924958-1b794500-fd1e-11ea-8c86-c9eed3877240.png)

**Comment by rsmithlal** [comment]
I would also reccommend perhaps some integration with the matrix.org protocol for federated chat engines. Have you heard of their Element.io app?

**Comment by volanar** [comment]
> Я также порекомендовал бы, возможно, некоторую интеграцию с протоколом matrix.org для федеративных механизмов чата. Вы слышали об их приложении Element.io?

Rocket. chat has a much larger community and more features. And rocket. chat supports the Protocol matrix.org
https://github.com/RocketChat/Rocket.Chat.Federation

**Comment by rsmithlal** [comment]
Supporting the matrix protocol is definitely a good idea!  ---- On Fri, 25 Dec 2020 21:34:31 -0330  notifications@github.com  wrote ----



Я также порекомендовал бы, возможно, некоторую интеграцию с протоколом matrix.org для федеративных механизмов чата. Вы слышали об их приложении Element.io?



Rocket. chat has a much larger community and more features. And rocket. chat supports the Protocol matrix.org

https://github.com/RocketChat/Rocket.Chat.Federation

**Comment by msarit** [comment]
@cmgorton Hi Christina! 👋🏾 

This issue is a non-starter, seeing as we have Connect Channels and their continued development is a Forem priority (as opposed to integrating a third-party option).
