### ISSUE TITLE
An un-rendered flash appears right before search results get returned

### ISSUE THREAD

**Issue by madzadev** [forem/forem#10433]
**Describe the bug**
There is an un-rendered flash right before search results get returned.

**To Reproduce**

Type smth in the search bar, Hit enter.

**Screenshots**

![bug](https://user-images.githubusercontent.com/42511917/94188264-cd954600-feb1-11ea-85f1-e077b3da76b1.gif)

**Desktop (please complete the following information):**

- OS, version: Win10 Home, 64-bit
- Browser, version: Google Chrome, 85.0.4183.121

**Comment by Link2Twenty** [comment]
Hmm, can you try clearing your cache and reloading it. When I do a search it looks like this.

![forem__search-pop-in](https://user-images.githubusercontent.com/3534427/94247376-eedb4e00-ff14-11ea-8d30-925f4007c5ba.gif)

**Comment by madarsbiss** [comment]
@Link2Twenty it started working normally after I logged out and logged back in 😉

**Comment by cmgorton** [comment]
This appears to be fixed so I am going to close this issue. If you believe it is still a bug let me know and we can open it back up. Thanks for creating this bug report.
