### ISSUE TITLE
Update min. requirements of WSL2 for Windows Installation docs

### ISSUE THREAD

**Issue by Amorpheuz** [forem/forem#10438]
**Describe the bug**
[Microsoft has enabled support for WSL2 for Windows version 1903 and 1909](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/) with an update. The [WSL2 Installation docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10#requirements) state the correct builds required to make the same possible. The minimum requirements in the [Windows Installation docs](https://docs.dev.to/installation/windows/) should be updated to the new requirements.

**To Reproduce**
1. Visit [Windows Installation docs](https://docs.dev.to/installation/windows/) and read the prerequisites.
2. Read the [WSL2 Requirements](https://docs.microsoft.com/en-us/windows/wsl/install-win10#requirements).

**Expected behavior**
The Forem prerequisites match the ones stated on the Microsoft docs.

**Additional context**

**Comment by sabarish98** [comment]
Hi team. Can I take this up and work on it ??

**Comment by rhymes** [comment]
@sabarish98 yes! I've assigned you the issue!

**Comment by sabarish98** [comment]
![docs_loading_error](https://user-images.githubusercontent.com/50691454/94656840-38b1a300-031e-11eb-8676-d559b19e51f6.PNG)
I am not sure what I am doing wrong here. I tried setting up the dev environment on Windows WSL2 (Ubuntu 18.04 LTS), installed all the gems and node modules as well. 
When I give `yarn gitdocs serve`, the local server runs at port `8000`, but when I go through the menus, I am unable to view the documentation. I keeps on loading, but doesn't pull up the docs. Has this occurred before??

**Comment by rhymes** [comment]
@sabarish98 not really, I wonder if there's an issue with port redirection in the container

cc @maestromac

**Comment by maestromac** [comment]
@sabarish98 is that happening on every doc page?

**Comment by sabarish98** [comment]
Yes @maestromac , just the side menu loads. All the pages keep loading. 

Actually regarding the local setup steps, I didn't run the fixtures or set the environment variables, because I thought that wouldn't be necessary for making the fix for this issue. But made sure I installed all node modules and gems. 

Would that cause something like this?

**Comment by maestromac** [comment]
@sabarish98 yeah the gitdoc portion is a stand-alone application that woudln't require all the env var from the main rails app. Can you share your browser error you are getting?

**Comment by sabarish98** [comment]
Here you go @maestromac. This is the error that occurs 
[localhost-1601489232545.log](https://github.com/forem/forem/files/5307448/localhost-1601489232545.log)

**Comment by sabarish98** [comment]
Here you go @maestromac, this is the error that occurs 
```
index.js?ab97:46 WebSocket connection to 'ws://0.0.0.0:8000/' failed: Error in connection establishment: net::ERR_ADDRESS_INVALID
```
I am attaching the log file as well.
[localhost-1601489232545.log](https://github.com/forem/forem/files/5307450/localhost-1601489232545.log)

**Comment by maestromac** [comment]
Sorry @sabarish98 I'm not sure what's causing this issue for you but looks like you successfully updated the doc. Thank you for your PR!
