### ISSUE TITLE
Update to latest yarn version

### ISSUE THREAD

**Issue by abenettt** [forem/forem#10440]
**Is your feature request related to a problem? Please describe.**
The latest yarn v1 version is 1.22.5 and we're still bundling 1.22.4.

**Describe the solution you'd like**
Update yarn config to use latest version

**Describe alternatives you've considered**

**Additional context**

**Comment by KarenEfereyan** [comment]
Waow @abenettt that was fast. How did you do it so quickly?

**Comment by KarenEfereyan** [comment]
Woaw @abenettt  that was fast. Super fast

**Comment by abenettt** [comment]
I had the PR prepared before I opened the issue @KarenEfereyan.

**Comment by KarenEfereyan** [comment]
Oh thats true.🤣🤣🤣you both raised the issue and are tackling it. Waow
