### ISSUE TITLE
Dev API does not create article with tags or series

### ISSUE THREAD

**Issue by mudlabs** [forem/forem#10442]
**Describe the bug**
When using the Dev.to API to POST an article, _tags_ and _series_ are not being set in the generated article.

**To Reproduce**
Make a simple post request following the steps outlined on the [Dev API site](https://docs.dev.to/api/#operation/createArticle)

**Expected behavior**
A new article with `tags` and a `series` would be created on Dev.to.

**Screenshots**
![Screen Shot 2020-09-27 at 3 17 42 pm](https://user-images.githubusercontent.com/32623552/94356705-a2d70780-00d4-11eb-841e-116af351cdb3.png)
![Screen Shot 2020-09-27 at 3 12 32 pm](https://user-images.githubusercontent.com/32623552/94356690-7b803a80-00d4-11eb-8e90-8c67640bcd5e.png)
![Screen Shot 2020-09-27 at 3 12 47 pm](https://user-images.githubusercontent.com/32623552/94356693-80dd8500-00d4-11eb-8604-41fd0c113dba.png)

**Additional context**
I have tried changing `published` to `true`, and passing a comma sepperated `tag_list` instead of a `tags` array; None work.

**Comment by rhymes** [comment]
Hi @mudlabs, weird. I just tried with 

```shell
curl -X POST -H "Content-Type: application/json" \
  -H "api-key: API_KEY" \
  -d '{"article":{"title":"Title","body_markdown":"Body","published":false,"tags":["discuss", "javascript"],"series":"Hello series"}}' \
  http://localhost:3000/api/articles
```

and obtain the following:

![Screenshot_2020-09-29 Edit Post - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/94549328-5580a480-0252-11eb-9f66-4fcb0711b1ed.png)

As you can see both tags and series are there. I also tried with only one of the two params in the payload and it worked.

I then tried on production:

```shell
curl -X POST -H "Content-Type: application/json" \
  -H "api-key: API_KEY" \
  -d '{"article":{"title":"Title (production)","body_markdown":"Body","published":false,"tags":["discuss", "javascript"],"series":"Hello series"}}' \
  https://dev.to/api/articles
```

and once again it worked

<img width="1204" alt="Screenshot 2020-09-29 at 12 52 55 PM" src="https://user-images.githubusercontent.com/146201/94549596-c627c100-0252-11eb-9e10-82e6f35c558f.png">

I'm then wondering if the issue isn't in the JS library you're using, even though at first glance it looks okay. Can you reproduce it with another HTTP client and/or using CURL?

**Comment by mudlabs** [comment]
Just tried using [node-fetch](https://www.npmjs.com/package/node-fetch#post-with-json). It did _not_ work either.

**Comment by mudlabs** [comment]
🤦  D'oh

It was because of the way I was passing in the `article` object. You can see from my `unirest` example above I was passing the article directly into the `send` method. It should be a nested object. The `api` must looks for the named object.

```js
// WRONG
unirest.send(article)

// WRITE
unirest.send({ article });
```

It threw me because some fields _(i.e. title)_ were being set. Going forward it might be better if requests would either fail completely if the named `article` object is not set, or be intelligent enough to find every applicable field.
