### ISSUE TITLE
Could not be able to write post 

### ISSUE THREAD

**Issue by RuchikaAggarwal89** [forem/forem#10463]
- [ ]  #@

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
Hello @RuchikaAggarwal89, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
