### ISSUE TITLE
Support for syntax highlighting for Prisma schemas in Markdown

### ISSUE THREAD

**Issue by nikolasburk** [forem/forem#10467]
**Is your feature request related to a problem? Please describe.**

[Prisma](https://www.prisma.io/docs/) is a database toolkit that comes with its own [data modeling language](https://github.com/prisma/specs/tree/master/schema) to define the so-called [Prisma schema](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema).

Right now, Prisma schemas don't have proper syntax highlighting in dev.to articles.

**Describe the solution you'd like**

Ideally, dev.to could support the `prisma` annotation on fenced code blocks to render Prisma schemas more colorful! For example:

~~~
```prisma
datasource db {
  url      = env("DATABASE_URL")
  provider = "postgresql"
}
generator client {
  provider = "prisma-client-js"
}
model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  posts     Post[]
}
model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(false)
  title     String
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}
enum Role {
  USER
  ADMIN
}
```
~~~

**Additional context**

This has been enabled on GitHub already (see [here](https://twitter.com/prisma/status/1301816885974118400)).

This is the PR that enabled syntax highlighting for Prisma schemas on GitHub: https://github.com/github/linguist/pull/4668#issuecomment-541354215 

![image](https://user-images.githubusercontent.com/4058327/94447986-b6ed3880-01aa-11eb-8eca-352a01e0e42d.png)

![image](https://user-images.githubusercontent.com/4058327/94448016-bce31980-01aa-11eb-8272-5f471d794720.png)

**Comment by Jolg42** [comment]
I think it will need to be added there first https://github.com/rouge-ruby/rouge

**Comment by rhymes** [comment]
Thanks @nikolasburk, as @Jolg42 mentioned we use Rouge to highlight, so I recommend opening a similar issue to their repository so they can be notified of this new language and act accordingly.

**Comment by rhymes** [comment]
BTW it looks very similar to Go, so in the meantime you might want to enable that :P

**Comment by nikolasburk** [comment]
Done @rhymes 🙏  https://github.com/rouge-ruby/rouge/issues/1598

**Comment by ajcwebdev** [comment]
Is this issue actually resolved? I don't get syntax highlighting on any of my Dev posts with Prisma and the original root issue is [still open](https://github.com/rouge-ruby/rouge/issues/1598).

**Comment by nikolasburk** [comment]
Nope, not yet resolved indeed! If there's no work to be done in this repo after the other one gets resolved though, I this this can remain closed, otherwise maybe reopen it? cc @cmgorton

**Comment by cmgorton** [comment]
Hey folks. I am no longer at Forem and can not reopen this issue. The product team at Forem may be able to help with this one. :)

**Comment by ajcwebdev** [comment]
Thanks Christina, home Scarf is going well so far!
