### ISSUE TITLE
Add Twitch Clips Liquid Tag

### ISSUE THREAD

**Issue by ChaelCodes** [forem/forem#10475]
**Is your feature request related to a problem? Please describe.**

I'd love to include clips from my Twitch stream in Dev.To articles to support various points. I have a [live-coding setup log](https://dev.to/chaelcodes/live-coding-setup-changelog-2kda), and I'd love to include a clip for each version of the setup to demonstrate what it looked like. This will probably be helpful for the [Raise.Dev help desk as well](https://dev.to/devteam/preptember-start-getting-ready-for-hacktoberfest-this-month-58cn).

**Describe the solution you'd like**

It would be really nice to have embedded Twitch clips. I propose we create a new liquid tag called twitch_clip that embeds a twitch clip using [this twitch clip embed](https://dev.twitch.tv/docs/embed/video-and-clips#non-interactive-iframes-for-clips).

**Describe alternatives you've considered**

Embedding an iFrame in my article didn't work, and clicking links takes people away from Dev.To or reduces the likelihood of engagement.

**Additional context**

**Comment by ChaelCodes** [comment]
I'd really like to tackle this issue as part of Hacktoberfest. I know you prefer a feature be reviewed prior to a contributor starting work on them, but this seems fairly straightforward.

**Comment by Link2Twenty** [comment]
Looks simple enough the only complication I can see is the need for a parent url.

| **parent** | **string** | **(required)** Domain(s) that will be embedding Twitch. You must have one parent key for each domain your site uses. |
|:---|---|:---|

We can't hard code this to dev.to so will need to do something else.

**Comment by ChaelCodes** [comment]
@Link2Twenty Good point. I think we could get this by pulling the host off the request.
