### ISSUE TITLE
Add more edit capabilities to Podcast dashboard in /admin

### ISSUE THREAD

**Issue by fdoxyz** [forem/forem#10482]
**Is your feature request related to a problem? Please describe.**

We are currently lacking the ability to fully manage Podcasts from the `/admin` dashboard.

**Describe the solution you'd like**

Update the view and controller for `/admin/podcasts/:id/edit` in order for admins to fully manage existing podcasts. The fields to be added are:
- Description
- iTunes URL
- Overcast URL
- Android URL
- Soundcloud URL
- Website URL
- Twitter username
- Pattern Image
- Main color hex
- Slug
- Image
- Reachable
- Published

The current existing edit area in `/admin/podcasts/:id/edit`:

<img width="1315" alt="Screen Shot 2020-09-29 at 05 32 37" src="https://user-images.githubusercontent.com/6045239/94553515-dbcac580-0215-11eb-9c72-a395dbd0bc29.png">

**Additional context**

This is part of a larger effort to remove the /resource_admin dashboard in favor of /admin.

**Comment by wotta** [comment]
Hello, does mean we just need to add the fields and everything will work just fine, or do we also need to add "migrations" to get this working as expected?

**Comment by rhymes** [comment]
@wotta the data is already there, it needs an interface to be edited. See https://github.com/forem/forem/blob/bfa06466ef6aaca4bf2b368cb6e5a39d833de321/db/schema.rb#L878-L898 and https://github.com/forem/forem/blob/master/app/models/podcast.rb

**Comment by wotta** [comment]
Thank you @rhymes for the quick response. this answers my question.
I would love to pick this issue up.

**Comment by rhymes** [comment]
Great, I've assigned it to you!

**Comment by wotta** [comment]
_Note to self_

- [ ] Description
- [ ] iTunes URL
- [ ] Overcast URL
- [ ] Android URL
- [ ] Soundcloud URL
- [ ] Website URL
- [ ] Twitter username
- [ ] Pattern Image
- [ ] Main color hex
- [ ] Slug
- [ ] Image
- [ ] Reachable
- [ ] Published

**Comment by wotta** [comment]
Hello,

I have a quick question. Are forms being validated? if so where can I find those 🙂 ?
Will submit a pr shortly with the changes.

Not sure how I can test it in gitpod because I have never worked with ruby.

**Comment by fdoxyz** [comment]
Hey @wotta, sorry I replied over in the PR before noticing this message of yours. 

I left a couple links over there with with how to add the new parameters to the permitted params and also the test case that validates this functionality.

I'll ping the team so hopefully someone with more gitpod experience can help you out with working your way around that

**Comment by fdoxyz** [comment]
In case it helps, there was an awesome conversation about using gitpod over in #10373 by two other contributors. 

In case you want to browse that conversation, it may be helpful 🙂

**Comment by KarenEfereyan** [comment]
> In case it helps, there was an awesome conversation about using gitpod over in #10373 by two other contributors.
> 
> In case you want to browse that conversation, it may be helpful 🙂

Yes our conversation over at that thread was awesome. You should check it out

**Comment by joshpuetz** [comment]
Hi @wotta! In order to test these changes manually, you'll need to log into you locally (or running on Gitpod) forem as an administrator. The best way to do that is to create an account on your local forem, then grant it administrator rights via the console. There are details on how to do in our setup docs here: https://docs.forem.com/admin/

**Comment by wotta** [comment]
Hello everyone,

Thanks for the feedback. I will hopefully finish this somewhere in the weekend. Mainly because I am a bit sick and I need some rest.

Nothing to serious but annoying enough to know I should rest.
