### ISSUE TITLE
Message in connect chat input field not cleared after sending it

### ISSUE THREAD

**Issue by DarkSmile92** [forem/forem#10480]
**Describe the bug**
After typing a message in the input field on connect in a channel and sending it, the message is sent but the text is still in the input field and not cleared.

**To Reproduce**

1. Go to DEV Connect
2. Write a message in a channel
3. Send the message

**Expected behavior**

Expected the input field to be cleared after the message is sent. (worked in the past)

**Screenshots**

![image](https://user-images.githubusercontent.com/10928916/94552267-e48fbb80-0256-11eb-818e-89b8d5175ee8.png)

**Desktop (please complete the following information):**

- Browser, version: Google Chrome, Version 85.0.4183.121 (64-bit)

**Comment by reobin** [comment]
Taking this up :) It was introduced with the auto resized textarea. Some clean up is need with the component's state management.

**Comment by fdoxyz** [comment]
Thank you @reobin I just assigned you to the issue
