### ISSUE TITLE
Add ability to manage Listing Categories in /admin

### ISSUE THREAD

**Issue by fdoxyz** [forem/forem#10481]
**Is your feature request related to a problem? Please describe.**

The Admin dashboard (`/admin`) currently has a Listings section that allows administrators to manage them but we are lacking a way to manage Listing Categories.

**Describe the solution you'd like**

A common Rails CRUD dashboard for Listing Categories (`/admin/listings/categories`). This would require a new controller with at least an `index`, `new`, `create`, `edit` and `update` actions. For reference [there's this PR (#10153) for Display Ads](https://github.com/forem/forem/pull/10153/files) that can be used as blueprint for guidance.

As this can be considered a "nested dashboard" and in order to avoid growing the admin side menu (left) too much, the following is a suggested placement of the link/button that will take the administrators to the Listing Categories dashboard:

<img width="1334" alt="Screen Shot 2020-09-29 at 05 05 45" src="https://user-images.githubusercontent.com/6045239/94551831-357dc080-0213-11eb-8a8c-548b1ef40e5f.png">

**Additional context**

This is part of a larger effort to remove the `/resource_admin` dashboard in favor of `/admin`.

**Comment by Rafi993** [comment]
Hello there, If this up for taking I can help.

**Comment by rhymes** [comment]
Ok @Rafi993, I've assigned this to you

**Comment by Rafi993** [comment]
Thank you @rhymes
