### ISSUE TITLE
Feature Request: Ability to "Mute" Users

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#10497]
**Is your feature request related to a problem? Please describe.**

Occasionally, a user may want to mute another user's content from their feed. Currently, the only way to do this is to block the other user, which is more of a user safety feature and comes with other effects described in the [changelog post](https://dev.to/devteam/changelog-block-tools-for-user-safety-4no3).

**Describe the solution you'd like**

A mute feature that users can use to mute another user — this will hide the muted user's content from the other user's feeds (but not block comments & other interactions).

**Describe alternatives you've considered**

One interesting way to implement this would be to add a `...` menu to the articles in the feed view. This way people could click on the `...` and opt to mute users from their feed. It'd be helpful because this is the place where they are likely to see their feed get clogged up by another user.

And this actually leads me to another idea — can we prevent folks' feeds from showing lots of posts by one user in a row? I feel like this is a big part of the issue.

**Additional context**

We mentioned the plan to create this feature in the [changelog post for blocking tools](https://dev.to/devteam/changelog-block-tools-for-user-safety-4no3).

We also have a closed issue [here](https://github.com/forem/forem/issues/3127) that included this request.

I also see this feature request to ignore tags as being related - https://github.com/forem/forem/issues/1856.

**Comment by cmgorton** [comment]
@michael-tharrington do you think this should be labeled as a potential RFC?

**Comment by michael-tharrington** [comment]
Yes indeed! We mentioned the plan to create this feature in the [changelog post for blocking tools](https://dev.to/devteam/changelog-block-tools-for-user-safety-4no3) and I think it makes a lot of sense to follow through with this.

Also, whoever works on this might be interested in looking at the "blocking" feature and fixing the issues that folks have experienced with it not filtering out blocked folks' content from their feeds - https://github.com/forem/forem/issues/11636.
