### ISSUE TITLE
Refactors to reduce CodeClimate code smells

### ISSUE THREAD

**Issue by gabrielbarker** [forem/forem#10509]
Hey @forem-team !

I was looking at some of the issues on your CodeClimate report and thought I'd fix a couple for you. If this is kind of annoying then feel free to close this issue and my PR.

I've ran all the tests locally and everything still seems good 🙂

Thanks!

**Comment by rhymes** [comment]
Thanks @gabrielbarker!

**Comment by mirie** [comment]
Closing as the associated PR was also closed and discussion paused
