### ISSUE TITLE
🌈 Feature request: Rich Editor Toolbar

### ISSUE THREAD

**Issue by lisasy** [forem/forem#10522]
## Problem
Right now, our editor for writing a post is limited to using markdown. This limits the UX of our evolving audience as we move away from developer-only communities to other ones.

## Proposed Solution
We want to extend the functionality of our editor toolbar to have buttons for basic styles like bold, italic, link, list, quote, code.

[Design Mockup](https://www.figma.com/file/PIPeiiVSADmcpCbiZTdJm9/Write-a-Post?node-id=456%3A1502).

**Comment by leewynne** [comment]
⬆️⬆️⬆️⬆️ so need this 😎 I like the style also!

**Comment by hooopo** [comment]
+1 for this

**Comment by cmgorton** [comment]
Current conversation in issue #14807
