### ISSUE TITLE
Adjust flare tag display on Feed card

### ISSUE THREAD

**Issue by lisasy** [forem/forem#10523]
## Problem
Right now, the "flare tag" on feed cards sit above the title, but this visual design is clunky and not what we want to keep in long-term.

## Proposed solution
Change the way we display flare tag by highlighting it within the row of tags below the title. 

[Design mockup](https://www.figma.com/file/lMIzNY8ORLej9XInAqx34w/Untitled?node-id=0%3A1)

**Comment by akshayymahajan** [comment]
I would like to work on this..

**Comment by rhymes** [comment]
@akshayymahajan I've assigned you the issue, thanks!
