### ISSUE TITLE
Issues with z-index with Github Liquid tag and post options

### ISSUE THREAD

**Issue by dannyverp** [forem/forem#10531]
## Description
There seems to be an issue with the z-indexing of some of the cards on the preview post page in combination with the Github Liquid tag. The issue seems to be present in all themes.
 
## Steps to reproduce
1. Create a new post;
2. Add some headers and text so that the content overflows the editor and the scrollbar appears;
3. Use the Github Liquid tag (for example `{% github forum/forum no-readme %}`) at the bottom;
4. Click "preview" on the right top;
5. Scroll down all the way in the post;
6. Click the post options button.

## Displayed result
The Github card overlays the post options card.

## Expected result
The post options card should overlay the Github Card.

## Screenshots
![image](https://user-images.githubusercontent.com/7555537/94918020-ff11a100-04b1-11eb-8c09-dc5b5bdcabd0.png)

### OS, version:
macOS Catalina, 10.15.6

### Browser, version:
- Chrome 85.0.4183.121 (Official Build) (64-bit)
- Firefox 80.0.1 (64-bit)

**Comment by akshayymahajan** [comment]
I would like to fix this..

**Comment by rhymes** [comment]
@akshayymahajan I've assigned it to you! Thanks
