### ISSUE TITLE
Cannot install using docker-compose on macOS

### ISSUE THREAD

**Issue by lucasqueiroz** [forem/forem#10546]
**Describe the bug**

When running the steps described [here](https://docs.forem.com/installation/containers/) to install forem using docker-compose on a macOS, the installation fails with the following error:

```
Step 27/31 : RUN RAILS_ENV=production NODE_ENV=production bundle exec rake assets:precompile
 ---> Running in 793819cbb48b
rake aborted!
URI::BadURIError: both URI are relative
```
(Full log below)

**To Reproduce**

1. Fork the repository
2. Clone the forked repository
3. Inside the cloned folder, run `./bin/container-setup`

It also happens when directly running `docker-compose build`.

**Expected behavior**

The application should be installed successfully

**Desktop (please complete the following information):**

- OS, version: macOS 10.15.6
- Browser, version: N/A

**Additional context**

Full log:
https://pastebin.com/a04zWZRj

**Comment by rhymes** [comment]
I'm experiencing the same issue:

```
rake aborted!
URI::BadURIError: both URI are relative
/opt/apps/forem/app/lib/url.rb:17:in `url'
/opt/apps/forem/config/initializers/imgproxy.rb:9:in `block in <main>'
/opt/apps/bundle/gems/imgproxy-1.2.0/lib/imgproxy.rb:30:in `configure'
/opt/apps/forem/config/initializers/imgproxy.rb:1:in `<main>'
```

**Comment by musps** [comment]
Hi 👋, I start digging inside this issue

**Comment by rhymes** [comment]
Thanks @musps, I've assigned it to you

**Comment by Coteh** [comment]
I am running into the same issue as well. I'm assuming `ApplicationConfig` receives values from environment variables, and after printing out some of these values, it seems like the environment variables weren't assigned. And I double checked to see that I have indeed created a `.env` file from `.env_sample` as per the documentation, and that `.dockerignore` isn't ignoring the `.env` file.

**Comment by tonsofpcs** [comment]
Same happens on Debian 10.

**Comment by tonsofpcs** [comment]
same occurs with $ docker-compose build --build-arg APP_DOMAIN="localhost:3000" --build-arg APP_PROTOCOL="http://" --build-arg APP_NAME="forem_local" so I don't think it's an env issue but I'm not terribly familiar with docker.

**Comment by lucasqueiroz** [comment]
Hey @musps I didn't see you were assigned, really sorry! I'll make sure to check next time.

**Comment by jdoss** [comment]
This is fixed with https://github.com/forem/forem/pull/10681
