### ISSUE TITLE
Reducing Spam on Forem with Captcha

### ISSUE THREAD

**Issue by sampathbalivada** [forem/forem#10567]
**Is your feature request related to a problem? Please describe.**

We noticed that a lot of spam is being posted on dev.to starting today/yesterday (times zone differences). This is frustrating and hindering the experience for a lot of users on the platform.

**Describe the solution you'd like**

Present the user with a Captcha prompt when writing a post.

**Describe alternatives you've considered**

An alternative would be to limit the number of posts a day depending the age of user on the platform. A new user should only be able to write one post in a day and the limit would increase as the age increases. 

**Additional context**

This solution is based on the fact that I was not asked to solve a captcha before publishing my post. If the captcha prompt is already present and is only triggered in some circumstances, I'm afraid it doesn't seem to be working.

**Comment by Rafi993** [comment]
Hello there, I think there is a similar discussion happening in https://github.com/forem/forem/issues/8459

**Comment by rhymes** [comment]
Hi @sampathbalivada as @Rafi993 kindly mentioned there's already an open ticket about this, could you copy your comment over there? I'm going to close this as a duplicate in the meantime.

Keep in mind that articles can be written programmatically so the captcha wouldn't be effective against those. 

Thank you!
