### ISSUE TITLE
Attempting to run RSpec on Docker triggers Elastic error

### ISSUE THREAD

**Issue by ChaelCodes** [forem/forem#10579]
**Describe the bug**

When I attempt to run a particular spec in Docker, there's a complaint about a missing VCR stub for elasticsearch.

The spec I'm running: `docker exec -it forem_rails bundle exec rspec spec/liquid_tags/vimeo_tag_spec.rb`
The error I get:
```
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
[Zonebie] Setting timezone: ZONEBIE_TZ="Prague"

An error occurred in a `before(:suite)` hook.
Failure/Error: next unless Search::Client.indices.exists(index: search_class::INDEX_NAME)

VCR::Errors::UnhandledHTTPRequestError:


  ================================================================================
  An HTTP request has been made that VCR does not know how to handle:
    HEAD http://elasticsearch:9200/chat_channel_memberships_test

  There is currently no cassette in use. There are a few ways
  you can configure VCR to handle this request:

    * If you're surprised VCR is raising this error
      and want insight about how VCR attempted to handle the request,
      you can use the debug_logger configuration option to log more details [1].
```

**To Reproduce**

1. Install Docker on WSL2 (Ubuntu) (Not sure if this is present in other environments, test and see?)
1. Run `bin/container-setup`
1. While docker is up, run `docker exec -it forem_rails bundle exec rspec spec/liquid_tags/vimeo_tag_spec.rb`

**Expected behavior**

All test cases pass, and RSpec reports the output.

**Screenshots**

![image](https://user-images.githubusercontent.com/8124558/95024884-d6291180-0653-11eb-83df-5d1fd5df1561.png)

**Desktop (please complete the following information):**

- Windows 10 > (WSL2) Ubuntu > Docker

**Comment by tudorpavel** [comment]
I ran into the same issue with docker setup. I might look into it further but as a quick workaround so you can run some unit tests in isolation is to comment out this line in `rails_helper.rb`:

```rb
  config.before(:suite) do
    # Search::Cluster.recreate_indexes
  end
```

As long as you don't need to run specs related to Elasticsearch, it should unblock your work.

**Comment by tudorpavel** [comment]
After some further digging I think I found a more permanent solution for this, see PR #10950.
