### ISSUE TITLE
Make dialogue links "open in new tab"-able

### ISSUE THREAD

**Issue by deanveloper** [forem/forem#10576]
**Is your feature request related to a problem? Please describe.**

When I'm doing something where I want to make sure my current page stays open, I often will use middle-click to open a help page in a new tab. However, doing this with the dialogue links (at least on the [new post page](https://dev.to/new)) will open a new tab where the new page doesn't even have the dialogue open.

**Describe the solution you'd like**

Have the `<a>` tag link to a separate page that describes the contents of the dialogue box, but prevent default on left clicks so that it still opens in a dialogue box if they do a normal left click, but if they "open in a new tab"/middle-click/ctrl-click, open a new tab to that separate page.

**Describe alternatives you've considered**

Cancelling all click events and just opening the dialogue no matter what. I think this would feel a bit janky though, since default behavior is typically expected.

**Additional context**

Here is a more specific example of the dialogue pages I am talking about:
![area of "new post" page where links like "Jekyll front matter", "Markdown", and "Liquid tags" all open dialogues](https://user-images.githubusercontent.com/3196327/95022718-9c014500-063e-11eb-8ff8-41803fe14c4b.png)

**Comment by rhymes** [comment]
Could you provide a GIF/video? I'm not sure I understood where the issue lies :( Which link should open in a new tab?

BTW that's not a dialog/modal, it's just a side bar that appears, it's part of the current page

**Comment by Link2Twenty** [comment]
My understanding is they want these modal windows to be actual links.

![image](https://user-images.githubusercontent.com/3534427/95057134-a2022f00-06ed-11eb-98eb-5e69f25e9235.png)

Both the markdown and liquid tags 'links' open this way.

**Comment by ludwiczakpawel** [comment]
Yeap, definitely a good suggestion.

Do you want to work on that as well?

**Comment by Link2Twenty** [comment]
@ludwiczakpawel is it worth having a crayon style that makes buttons look like an anchor tag? This would be a good candidate for that, the anchor is really just a button.

https://github.com/forem/forem/blob/f0963c1bfa5d7ed56c0f964a57bde8ab86e6db85/app/javascript/article-form/components/Help.jsx#L134-L136

Just thinking of ways to make the middle mouse button no open a pointless tab.

**Comment by ludwiczakpawel** [comment]
@Link2Twenty I guess this one should be actually a classic link taking user to another page (one with help) IF you try to open it in a new tab. But for "regular clicks" it should bring the modal, likely with suggested `event.preventDefault();`..
