### ISSUE TITLE
Tag page update failing for tag moderator from /admin

### ISSUE THREAD

**Issue by SGGregory** [forem/forem#10581]
**Tag page update failing for tag moderator from /admin**

I am an admin at DEV/Forem and a tag moderator. When I attempt to edit/update a tag page in `/admin`, my updates do not appear, however, there is not a failure message.

**Expected behavior**

I expect to be able to make edits to the tag page by navigating there from /admin. 

**Desktop:**

- Mac 
- Chrome, version 85.0.4183.121:

**Additional context**
I CAN make edits if I add /edit to the end of the tag page URL (ex: dev.to/t/hacktoberfest/edit) — just not from /admin.

**Comment by nadiyaka** [comment]
I'd like to work on this issue

**Comment by nadiyaka** [comment]
@forem/oss

**Comment by fdoxyz** [comment]
It seems like the problem has been solved now. Thanks for volunteering to take on this issue @nadiyaka , feel free to try to tackle another issue or let us know if you need help :)
