### ISSUE TITLE
Add a captcha or more to prevent spam on new articles/comments

### ISSUE THREAD

**Issue by musps** [forem/forem#10601]
**Is your feature request related to a problem? Please describe.**

Recently i saw many new articles with spam title/content and comments.

**Describe the solution you'd like**

I don't know if it is implemented yet (I haven't see it) but we could add a captcha if a user create more than x comments or articles in a period of time to prevent the spam ?

**Describe alternatives you've considered**

None.

**Additional context**

I think it's all come from the same user ?

Article spam:
https://dev.to/kumar09807458/for-dot-store-customer-care-number-8391097664-8391097664for-dot-store-customer-care-number-8391097664-8391097664ggg-ij7
https://dev.to/mithunkumar991/livecozy-customer-care-number-6296493902-21l9
https://dev.to/wwwmangal/india-brand-customer-care-number-8617361391-5c6m

Screenshot with spamy comments:
<img width="300" alt="Capture d’écran 2020-10-05 à 11 10 17" src="https://user-images.githubusercontent.com/9492287/95061899-82bece00-06fc-11eb-84cb-f22649b653e3.png">

**Comment by rhymes** [comment]
Hi @musps - currently we have rate limiting of a few articles each 30 seconds. I think we should start by changing that, I think it was designed to limit flooding via API. Keep in mind that articles can be added programmatically, thus the captcha would just limit manual posting

Related to https://github.com/forem/forem/issues/8459
