### ISSUE TITLE
Connect shows my own message' badge.

### ISSUE THREAD

**Issue by aligoren** [forem/forem#10606]
**Describe the bug**

Hi, today I sent a message to a channel. After I saw count 1. It was my message.

**To Reproduce**

**Expected behavior**

Users shouldn't see their own message's count.

**Screenshots**

1-) Badge count

![image](https://user-images.githubusercontent.com/4205423/95073709-f91bfa00-0715-11eb-8d3c-faa7dfac7429.png)

2-) messages

![image](https://user-images.githubusercontent.com/4205423/95073734-046f2580-0716-11eb-80a2-4d1bf528e4c1.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome Latest version

**Comment by DRBragg** [comment]
I'll take a look at this if it's still available

**Comment by rhymes** [comment]
Go ahead @DRBragg, thanks !

**Comment by DRBragg** [comment]
@aligoren Was the channel you were messaging in a direct message (1 other user) or a Group message? I haven't been able to duplicate the issue yet.

**Comment by aligoren** [comment]
@DRBragg It was a group message.

For example, we have a group called "Issues".

I sent a message to that group on the other browser tab. After, I saw a badge for this message.

**Comment by DRBragg** [comment]
Copy, thanks, that should help

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
