### ISSUE TITLE
a11y: improve keyboard access on modals

### ISSUE THREAD

**Issue by lisasy** [forem/forem#10610]
# Problem

When I'm looking at a modal and tab through with a keyboard, it goes through everything behind the modal overlay first, making it a really frustrating user experience. 

# Proposed solution

When a modal is open and a user tabs through with their keyboard, have them navigate through the modal first, not what is behind the modal.

Video here: https://share.getcloudapp.com/6quPkxyr

**Comment by Monty7** [comment]
Hello, I would like to claim this issue.

**Comment by lisasy** [comment]
@Monty7 You can go ahead and claim this :)

Happy hacking!

**Comment by nickytonline** [comment]
@Monty7, I've assigned the issue to you.

**Comment by Link2Twenty** [comment]
I'd suggest looking at the [inert polyfill](https://github.com/WICG/inert).

**Comment by Rafi993** [comment]
<img src="https://user-images.githubusercontent.com/8092120/87239167-91615600-c429-11ea-917c-9f02bec477f4.png" width="16" height="16"/> Forwarded from issue https://github.com/thepracticaldev/dev.to/issues/10660

> I think it is related to https://github.com/forem/forem/issues/9585

**Comment by mstruve** [comment]
@Monty7 do you still have plans to work on this? If not we would like to get it prioritized for our internal team to get done.

**Comment by Rafi993** [comment]
There is something similar done by PR https://github.com/forem/forem/pull/12366
