### ISSUE TITLE
Login nahi ho sakta hai 

### ISSUE THREAD

**Issue by Rahulkumar1321** [forem/forem#10625]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by citizen428** [comment]
Hello @username, thanks for notifying us of this problem, this looks an issue specific to your account.
Please email yo@dev.to for more help.
