### ISSUE TITLE
Text goes outside the block (app)

### ISSUE THREAD

**Issue by mityaua** [forem/forem#10629]
**Describe the bug**

In mobile app (Android 10) text in bio (look like url type) goes outside the block.

**To Reproduce**

Open app on device with 393px viewport.

1. Go to mobile app on Android 10 (device width 393px)
2. Click on any post by https://dev.to/vaibhavkhulbe
3. Scroll down to end of article
4. See error https://prnt.sc/utvn2p

**Screenshots**

https://prnt.sc/utvn2p

**Smartphone (please complete the following information):**

- Device: MI 9 LITE
- OS, version: Android 10 (MIUI 12.0.3)
- Browser, version: App, 1.4.2

**Comment by Link2Twenty** [comment]
Same is true on the mobile web version
