### ISSUE TITLE
Sponsorship: differentiate tag sponsorships on organization profile

### ISSUE THREAD

**Issue by rhymes** [forem/forem#10670]
**Is your feature request related to a problem? Please describe.**

If an organization is sponsoring multiple tags, these will appear as ` Tag Community Sponsor ❤️ ` in separate boxes for as many tags as they are sponsoring:

![Screenshot_2020-10-06 HarperDB - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/95232312-97868900-0804-11eb-9f00-0e64a6a2466b.png)

(example taken from https://dev.to/harperdb)

**Describe the solution you'd like** 

Explicitly name the tag the sponsorship is about, so something like: "SQL tag community sponsor" (with the link to the tag page for example)

**Describe alternatives you've considered**

Nope, no alternative. We could just display one per category but it wouldn't make real sense to me.

**Comment by 13point5** [comment]
Hi, @rhymes I'd like to work on this, can I get some more info on the issue or maybe how to use a dummy sponsor account to test this?

**Comment by rhymes** [comment]
Hi sure! A "tag sponsorship" is a [Sponsorship](https://github.com/forem/forem/blob/master/app/models/sponsorship.rb) attached to a [Tag](https://github.com/forem/forem/blob/master/app/models/tag.rb) object whose `level` is set to `tag` and whose `sponsorable` is attached to the tag object.

A sponsorship belongs to a user and an organization. An organization can sponsor multiple tags and a tag can only have one sponsorship.

You can, for example, take a look at the sponsorship tests to see how we create them:

https://github.com/forem/forem/blob/f95acef2bc5c9f0c1c5f2301f1114b0d95a4871f/spec/models/sponsorship_spec.rb#L83

For example, you can use the admin panel to create them via http://localhost:3000/admin/sponsorships/new or you can do it manually by building a `Sponsorship` object pointing to a user, an org and tag.

The goal here is to show the name of the tag in the organization profile.

Let me know if anything is unclear

**Comment by 13point5** [comment]
Can I contribute to this issue for `hacktoberfest`?

**Comment by rhymes** [comment]
Yes @13point5, definitely. Thank you!

**Comment by 13point5** [comment]
Cool, I'll get started!

**Comment by 13point5** [comment]
Sorry @rhymes but I won't be able to contribute rn

**Comment by rhymes** [comment]
@13point5 no need to be sorry, thanks again for volunteering!

**Comment by bntzio** [comment]
Hey @rhymes I can take this one, do you have a link to learn more about forem sponsorships?

**Comment by rhymes** [comment]
Hey @bntzio, no not really :-(, other than the code and my comment up https://github.com/forem/forem/issues/10670#issuecomment-706889634 

Please do ask any questions if you might have them, in the meantime I've assigned you to the issue

**Comment by cmgorton** [comment]
@bntzio Thanks so much for your willingness to take this issue. 
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. 
Given this process I am going to unassign you from this issue for now. 

In the meantime if you see any bugs you want to squash let me know and we can assign them to you!
