### ISSUE TITLE
Connect screen doesn't resize after resizing browser

### ISSUE THREAD

**Issue by citizen428** [forem/forem#10695]
**Describe the bug**

As discussed in #10136, the Connect screen doesn't properly resize after developer tools were opened ([comment](https://github.com/forem/forem/pull/10136#pullrequestreview-502129412), [explanation](https://github.com/forem/forem/pull/10136#issuecomment-704029516)).

**To Reproduce**

1. Go to Connect
2. Inspect the page
3. Reload the page
4. Close the developer tools

**Expected behavior**

Connect fills up the whole page again after closing developer tools.

**Screenshots**

![image](https://user-images.githubusercontent.com/47985/95285122-3a351b00-088a-11eb-96b2-a55f3218ca01.png)

**Comment by Link2Twenty** [comment]
https://github.com/forem/forem/blob/3649c70872608e045e95b8c2c7eb3faf4c39ebc1/app/views/chat_channels/index.html.erb#L39-L45

Here's the issue, does anyone know (@ludwiczakpawel maybe?) why we're calculating `vh` in JS rather than using the CSS `vh`.

Our choices are we edit the SCSS to make it use the built in `vh`

https://github.com/forem/forem/blob/83b3baeac370e810ff2ed1ca707c84fcc7bdc5cd/app/assets/stylesheets/chat.scss#L14-L16

https://github.com/forem/forem/blob/83b3baeac370e810ff2ed1ca707c84fcc7bdc5cd/app/assets/stylesheets/chat.scss#L23-L29

Or we recalc the JS version on resize. Something like

```jsx
useEffect(() => {
  let resizeDebounce = null;

  const callback = () => {
    clearTimeout(resizeDebounce);
    resizeDebounce = setTimeout(() => {
      // First we get the viewport height and we multiple it by 1% to get a value for a vh unit
      let vh = window.innerHeight * 0.01;
      // Then we set the value in the --vh custom property to the root of the document
      document.documentElement.style.setProperty('--vh', `${vh}px`);
    }, 250);
  };
  window.addEventListener("resize", callback);

  return () => {
    window.removeEventListener("resize", callback);
  }
}, []);
```

**Comment by ludwiczakpawel** [comment]
> does anyone know (@ludwiczakpawel maybe?) why we're calculating vh in JS rather than using the CSS vh.

Not quite sure, @sarthology may know. It does seem a bit hacky in general and I feel it's to address some mobile bug. 

That being said, I have some design work in progress for updating entire Connect layout (including responsiveness) but it does require **a lot** of frontend coding. And Connect is quite a beast in terms of code... 

But this is clearly a bug, indeed.:)

**Comment by Cerchie** [comment]
I'd like to work on this one!

**Comment by rhymes** [comment]
Thanks @Cerchie, go ahead! :)

**Comment by sarthology** [comment]
> Here's the issue, does anyone know (@ludwiczakpawel maybe?) why we're calculating vh in JS rather than using the CSS vh.

The problem was with Firefox on iOS and this was the only way to resolve it. I have fixed that is this PR  [#9801](https://github.com/forem/forem/pull/9801). That makes this issue bit tricky to resolve.

**Comment by Cerchie** [comment]
I'm going to jump off this one, need to focus on the other issue I was assigned.

**Comment by citizen428** [comment]
I unassigned you now @Cerchie, thanks for contributing.

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
