### ISSUE TITLE
'Load more' shows last notification results (wrong scrollbar position)

### ISSUE THREAD

**Issue by madzadev** [forem/forem#10714]
**Describe the bug**

When I scroll to the bottom of notifications and click 'Load More', it displays last results loaded (scrollbar stays on the bottom) and I have to manually scroll up to see the start of newly loaded results.

**To Reproduce**

1.Click on notification bell
2.Scroll to the bottom of results
3.Click Load more (now the new results appear)
4.User has to scroll up to see the first part of the new results, as scrollbar stayed at the very bottom.

**Expected behavior**

Scrollbar gets positioned right where the newly loaded results start.

**Desktop (please complete the following information):**

- OS, version: Windows 10 Home (64-bit)
- Browser, version: Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- My display resolution is 1920x1080 (landscape) if you need that.

**Additional context**

I've been noticing this issue for a while now, so decided to report.
It's pretty annoying if you have lots of new notifications and have to click Load More multiple times to get through all of them.

Edit: or maybe you can implement dynamic loading, so that you can remove Load More button completely and notifications show up dynamically as you scroll (Twitter does that, for example)

**Comment by Rafi993** [comment]
Hello there, If this bug is not taken I would like to help.

**Comment by rhymes** [comment]
Thanks @Rafi993, assigned

**Comment by Rafi993** [comment]
Thank you @rhymes

**Comment by nickytonline** [comment]
Closing this as the design rework of the notifications appears to have fixed this.
