### ISSUE TITLE
Free Cultural Work content license, such as Creative Commons

### ISSUE THREAD

**Issue by brylie** [forem/forem#1072]
It would be nice if I could specify a [Creative Commons](https://creativecommons.org/) license for posts I make on dev.to, so that I can dedicate my writings as [Free Cultural Works](https://creativecommons.org/share-your-work/public-domain/freeworks/).

**Describe the solution you'd like**
When creating a post on dev.to, there would be an option to apply a Creative Commons license.

**Describe alternatives you've considered**
Alternatively, a public domain dedication would allow the content to be reused freely.

**Comment by jessleenyc** [comment]
This is a cool idea. I think we can get around to this soonish but if someone wants to grab this issue, it's approved!

**Comment by brylie** [comment]
Having a standardized way to select a license might:
- encourage authors to publish under open license
- provide a standard way to identify content license on dev.to
- open the possibility for open content to be discovered and syndicated via automated tools


So, yes people can paste a license text in the article body, but there may be advantages to having official platform support.

**Comment by omenking** [comment]
How are we to allow them to select the licensing? 
Dropdown to select from the 7 regularly used?
I would suggest to add it in front matter eg.

```
title: Steamboat Willy
creative_commons: BY-NC
```

Which would then result in the icons / badge appearing at the bottom of the article.

I can code it in if the core wants it, but I personally would not like to see its inclusion as @abraham  stated you could just drop an image in.

I myself have been considering publishing an entirely free course under public domain so the utility could be applicable to me but thinking about the code base and practical usage I strongly think its going result in added technical complexity to the codebase for a feature that just adds extra mental work for the content creators when publishing their articles.

The reason I like DEV.to over Hashnode is that it's so minimalistic and the DIY of writing posts This feature takes away from what I think makes DEV.to the reason why I want to publish content here.

I would suggest asking the DEV.to members in a post to see if its truely of interest.

@jessleenyc if think it should be done, say the word and I'll code it in.

<img width="900" alt="Screen Shot 2019-04-09 at 10 57 16 PM" src="https://user-images.githubusercontent.com/7776/55848515-3270ab00-5b1b-11e9-9d98-c7217948e710.png">

<img width="334" alt="Screen Shot 2019-04-09 at 10 57 18 PM" src="https://user-images.githubusercontent.com/7776/55848522-37355f00-5b1b-11e9-9de6-451f032b302c.png">

**Comment by cmgorton** [comment]
Hey all, this issue has gone stale and as we are starting to think more in terms of "Forem" in general and less of just DEV I agree with Andrew and Abraham. I propose we close this issue for now and use the proposed solution of simply adding text at the bottom/top of a post to specify a license.
