### ISSUE TITLE
Blocking user doesn't successfully stop user's posts from appearing in feed 

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#10744]
**Describe the bug**

When User A blocks User B, User A can still see User B's posts in their home feed.

**To Reproduce**

1. Go to your home feed on dev.to
2. Click onto an author's name whom you'd like to block
3. Once on the author's profile page, click the '...' icon to the right side of their name card and the block them
4. Return to home feed on dev.to and their post will still be there

**Expected behavior**

When you block someone, their posts should no longer appear in your feed.

**Additional context**

I have not tried to reproduce this behavior, but a user provided us with a video to confirm that this is happening.

Whoever works on this may want to pick up the feature request for mute functionality as well - https://github.com/forem/forem/issues/10497.

**Comment by rhymes** [comment]
Might also be related to https://github.com/forem/forem/issues/5342

**Comment by vaidehijoshi** [comment]
@benhalpern since you have assigned this to yourself, I am assuming you have started work on this already :) If that is the case, can you please add it to the in progress column so we can keep up-to-date with which tasks are currently being worked on? Thank you! 🙏🏽

**Comment by vaidehijoshi** [comment]
Closed by https://github.com/forem/forem/pull/12307 :)
