### ISSUE TITLE
Parallelize Travis build

### ISSUE THREAD

**Issue by maestromac** [forem/forem#1078]
**Is your feature request related to a problem? Please describe.**
It would be a substantial improvement to our developer experience if each individual Travis build is faster. 

**Describe the solution you'd like**
Utilize [Parallel test gem](https://github.com/grosser/parallel_tests) (already part of our gem file) on Travis. The coverage result should also [be combined](https://docs.codeclimate.com/docs/configuring-test-coverage#section-parallel-tests) into a unified report.

**Describe alternatives you've considered**
Travis also suggested to use matrix to parallelize test suite via multiple VMs. I think parallelize in single VM would be sufficient since there's a specialized ruby gem for this.

**Additional context**
Might need to set up a S3 instance for this. The easier alternative would be a temp folder in the Travis directory.

**Comment by jessleenyc** [comment]
Any additional thoughts on this?

**Comment by maestromac** [comment]
After some research, parallelization shouldn't be prioritized just yet. We should focus on having a leaner/faster test suite

**Comment by abraham** [comment]
Rails 6 added some level of parallel testing as well. That might be useful once DEV is upgraded. https://edgeguides.rubyonrails.org/testing.html#parallel-testing-with-threads

**Comment by maestromac** [comment]
Yeah I am very much looking forward to that.

**Comment by maestromac** [comment]
Resolved because we are now using Knapsack
