### ISSUE TITLE
Total time in video player wraps to next line

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10799]
**Describe the bug**

Total time shown in video player wraps to next line even if there is enough space to show in the same line

**To Reproduce**

1. Go to https://dev.to/devteam/building-out-the-go-playground-liquid-tag-for-dev-with-chuck-smith-32he
2. Play the video at the top
3. Open the video in full screen
4. The total time of the video shown wrap to next line

**Expected behavior**

It should show in the same line

**Screenshots**

![video_length_text](https://user-images.githubusercontent.com/8092120/95713073-882f9180-0c83-11eb-8498-0dedc221fd92.png)

**Desktop:**

OS, version: Ubuntu 20.04
Browser, version: Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

**Additional context**

I'm not sure if it is a bug in the video player or is it a bug in dev.to

**Comment by tudorpavel** [comment]
I found the CSS culprit and implemented a fix in PR #10889.
