### ISSUE TITLE
Undefined in url for delete listing in listing dashboard

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10800]
**Describe the bug**

Url for deleting listing in listing dashboard is `/listings/undefined/test-2fjm/delete_confirm`

**To Reproduce**

1. Go to https://dev.to/listings/dashboard
2. Create a draft listing
3. Hover over delete link of that listing it will have undefined in the url

**Expected behavior**

It should not have undefined in the url

**Screenshots**
![undefined_link](https://user-images.githubusercontent.com/8092120/95714109-57505c00-0c85-11eb-8bcd-952b41147cc6.png)

**Desktop:**

OS, version: Ubuntu 20.04
Browser, version: Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

**Comment by Rafi993** [comment]
This issue is happening because `listing.category` is undefined in https://github.com/forem/forem/blob/4babb9e6de4c5b8fe79c5342f154e53e365b1100/app/javascript/listings/dashboard/listingRow.jsx#L50-L55

**Comment by akshayymahajan** [comment]
Is anyone working on this? If not, I would like to work on this..

**Comment by rhymes** [comment]
@akshayymahajan assigned it to you. thanks!
