### ISSUE TITLE
Search bar in Dashboard to filter Articles

### ISSUE THREAD

**Issue by madzadev** [forem/forem#10803]
**Is your feature request related to a problem? Please describe.**

For users with lots of articles, it is impossible to filter the articles based on a keyword in the dashboard.
Let's say I have 500 articles and I specifically need to access all the articles with 'AWS' in the title. Currently, I would need to go through all 10 pagination pages (50 per view) and do ctrl+f on each of them (as I can't change how many articles are shown on 1 page, either). And, even if there would be an option to display 500 in one view, you should most likely use dynamic loading, so ctrl+f won't work either. 
Furthermore, using the general site search would work only on published articles and would filter efficiently only with like the whole title being queried. And what if I need to search for unpublished 'AWS' articles in the dashboard? 👀

**Describe the solution you'd like**

Search bar next to the current dropdown filter (recently created, published, and most views, reactions, comments) that dynamically filters the results as I start typing letters in it would be awesome! 🔥

**Comment by madzadev** [comment]
Any updates on this? 👀
Just the fact, the more I use DEV the more I need it 😀😀

**Comment by nickytonline** [comment]
Hi @madzadev. We haven't evaluated this feature request. Thanks, for following up!

**Comment by ludwiczakpawel** [comment]
I think it would be a great addition to Dashboard!

**Comment by benhalpern** [comment]
Yeah, this makes sense. Fits alongside the existing filter feature set nicely.

**Comment by madzadev** [comment]
@nickytonline @ludwiczakpawel @benhalpern thanks for your responses 🙏❤

**Comment by cmgorton** [comment]
@nickytonline @ludwiczakpawel @benhalpern, added the potential RFC label to thins. Let me know if this is something we should pursue as a team.

**Comment by nickytonline** [comment]
I definitely see this as a potential RFC.
