### ISSUE TITLE
Corners of organization profile images not fully filling the space

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#10815]
**Describe the bug**

The very corners of profile images on **organizations** are being cut off.

**To Reproduce**

Visit an organization page, for example:
- https://dev.to/devteam
- https://dev.to/twilio

**Expected behavior**

The organization logo fills the entire profile image frame.

**Screenshots**

![example of issue](https://p241.p3.n0.cdn.getcloudapp.com/items/Z4uyyvYn/Image%202020-10-12%20at%201.46.54%20PM.png?v=448d2001f22ca683efa6bcf660ae4fbd)

**Comment by query-string** [comment]
Can I pick this one please?

**Comment by rhymes** [comment]
Sure @query-string, thank you!

**Comment by tudorpavel** [comment]
@query-string did you manage to look into this?

I'm wondering what the expected design is:

A. keep the border radius but use the same background color as the frame

![forem_round](https://user-images.githubusercontent.com/2506871/96339176-89a1f500-109b-11eb-97d3-93e831fc13bf.png)

B. drop the border radius and have a square image

![forem_square](https://user-images.githubusercontent.com/2506871/96339179-8f97d600-109b-11eb-87e2-5df8eacf4ee0.png)
