### ISSUE TITLE
Comments box should grow as you type

### ISSUE THREAD

**Issue by jdoss** [forem/forem#10829]
**Describe the bug**

The comment box should grow as you type so you can see your whole comment the entire time.

**To Reproduce**

Type a long comment and you will see the comment box does not grow.

**Expected behavior**

A growing comment box.

**Comment by Link2Twenty** [comment]
Currently the comment box has a max height of 384px.

This is set here

https://github.com/forem/forem/blob/1375e8a4df4cb1dbaa13565347362c3502465be3/app/assets/stylesheets/views/comments.scss#L30-L43

It is currently working as designed so I'm not sure it's a bug but it's certainly worth looking at this to see if we want it to expand all the way.

This is the JS logic that handles the size changes.
https://github.com/forem/forem/blob/c60566b8a52d47c5c8897f91b5284032843f0cf0/app/assets/javascripts/initializers/initializeCommentsPage.js.erb#L405-L419

**Comment by narender2031** [comment]
Comment input size grows if you pressed enter. But if you do not press enter it always count line size 1. 
A possible solution is that we can add a condition where if the text box has 25 words or 30 words line count should increase.
