### ISSUE TITLE
Connect: Request center overlays last chat

### ISSUE THREAD

**Issue by citizen428** [forem/forem#10823]
**Describe the bug**

When opening the request center from a connect channel it overlays the existing channel which makes it hard to read. Switching away from the app and then switching back gives the desired result.

**To Reproduce**

1. Go to the Connect.
2. Open the Request Center
    <img width="212" alt="Screenshot_13_10_20_11_40" src="https://user-images.githubusercontent.com/47985/95816370-20dc1500-0d49-11eb-8acf-8bc57bf86a3a.png">
3. The Request Center overlays the current chat, which reamins scrollable in the background (but resized)
    ![IMG_1145](https://user-images.githubusercontent.com/47985/95816496-70badc00-0d49-11eb-9fe8-2cf521e6ca0e.PNG)
4. Switch away from the app
5. Switch back, everything works now.
    ![IMG_1147](https://user-images.githubusercontent.com/47985/95816527-87613300-0d49-11eb-9acf-215244c818f4.PNG)

**Expected behavior**

End up with the correct view right away.

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS, version: iOS 14.0.1
- Browser, version: DEV app

**Comment by Link2Twenty** [comment]
Does it do the same on the web in mobile on safari? I can't recreate the bug in firefox or chrome/edge.
I just wanna make sure it's not an app specific thing.

**Comment by narender2031** [comment]
no. It's not the same on the mobile web browser. It shows for a second in the mobile browser and then works normally.

**Comment by narender2031** [comment]
no. It's not the same on the mobile web browser. It shows for a second in the mobile browser and then works normally.
