### ISSUE TITLE
More information on 'logging in' on local environment

### ISSUE THREAD

**Issue by khendrikse** [forem/forem#10849]
**Describe the bug**

While setting up the app using docker desktop on mac and running a local version of the app, I find it very hard to figure out how I can see all views by, for example, logging in. I understand that this might be basic information for some people, but I can simply not seem to find the information that can help out here.

**To Reproduce**

Imagine being someone who has not yet set up the app before, has just succesfully started up localhost:3000 but does not understand how to see the profile view for example.

**Expected behavior**

I would love to know how to set up a mock user, or how to log in in any other way in the local environment so I can try to contribute on a front-end level.

**Additional context**

I don't mind helping to add this information to the documentation once I have it :) and also, maybe I am looking in the wrong places! Thanks!

**Comment by citizen428** [comment]
Thanks for the issue and wanting to contribute @khendrikse!

Our documentation has guiides on how to add a user via Github, Facebook, or Twitter login:

https://docs.dev.to/backend/authentication/

If you think these instructions are unclear, we'd be happy about PRs that add more clarification. Alternatively, you can also head over to https://forem.dev/ and ask for help there.

**Comment by khendrikse** [comment]
@citizen428 I tried it using the GitHub authentication, but it is unclear to me in which file within the railsapp I would have to add the credentials?

**Comment by citizen428** [comment]
@khendrikse These credentials don't go into a file, but into the environment. See `.env_sample` in the root directory for an example. The `bin/setup` script should copy this over into a `.env` file where you can add your credentials like this:

```
export GITHUB_KEY=XXXXXXX
export GITHUB_SECRET=XXXXXXX
```

**Comment by khendrikse** [comment]
Ah yes I was already searching in the `.env_sample` to see if it needed to go there but I could not see it there.

Does that mean that even though I am using docker, I should still run the `bin/setup` script in the folder before running `bin/container-setup`?

**Comment by citizen428** [comment]
Sorry, I missed that you're using Docker. Our [container docs](https://docs.dev.to/installation/containers/) state the following:

> Create .env by copying from the provided template (i.e. with bash: cp .env_sample .env). This is a personal file that is ignored in git.

**Comment by khendrikse** [comment]
Yes exactly! Thats what I did :) but of course I need to add my credentials to make it work. Thanks!

**Comment by khendrikse** [comment]
I seem to get further than I did before, except that it now sees a mismatch between the callback url provided.

![image](https://user-images.githubusercontent.com/30577427/96125789-3a6d9000-0ef4-11eb-9eb3-40bbfcfd42e8.png)

In the [documentation](https://docs.dev.to/backend/auth-github/) it does not say anything about the callback url, but I assumed it would be the same structure as Twitter and Facebook  so I changed the callback in GitHub to `http://localhost:3000/users/auth/github/callback`. Yet I am getting the same error, I think I might be doing something wrong?

**Comment by citizen428** [comment]
I just checked my own OAuth app, it uses `http://localhost:3000` as the callback URL.

**Comment by khendrikse** [comment]
It's so weird, when I use `http://localhost:3000`  I get referred back to:
`http://localhost:3000/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=` 

Hovering over the 'Sign up with GitHub' link I see the following url as a href for the link `http://localhost:3000/users/auth/github?callback_url=http%3A%2F%2Frails%2Fusers%2Fauth%2Fgithub%2Fcallback&state=navbar_basic` which does seem to point to `https://localhost:3000/users/auth/github/callback`. 

Seeing that it appears nobody else is having these issues I keep wondering if I am doing something wrong? But at the same time I wonder why the docs for authentication with Facebook and Twitter do have specific callback urls?

**Comment by citizen428** [comment]
Would you mind sharing a screenshot of the your GIthub OAuth app configuration (without the key of course)?

**Comment by khendrikse** [comment]
Of course :) here it is:

![image](https://user-images.githubusercontent.com/30577427/96414453-6c7d3b80-11ed-11eb-9bec-5b6b06c121eb.png)

**Comment by citizen428** [comment]
Well, these look identical 😞 

<img width="474" alt="Screen Shot 2020-10-19 at 18 51 29" src="https://user-images.githubusercontent.com/47985/96447478-7ad55280-1201-11eb-97fb-5f5d07e48ec5.png">

The one thing I noticed is that the callback URL in the param points to `http://rails/users/auth/github/callback&state=navbar_basic` once decoded, not `https://localhost:3000/users/auth/github/callback`.

**Comment by khendrikse** [comment]
Yeah I saw the same thing, I am assuming it is my own setup that might be the issue, as otherwise there must be other people having the same problem...

**Comment by citizen428** [comment]
Do you use anything to make `rails` resolve to localhost:3000, e.g. some dnsmasq setup, an entry in `/etc/hosts`, a development server like Pow, or something like that?

**Comment by khendrikse** [comment]
Sorry for my slow response, no I did not setup anything extra I am afraid. Just using the docker image and that is all...

**Comment by citizen428** [comment]
Have you tried `http://rails` as callback URL?

**Comment by citizen428** [comment]
Maybe for the time being it's easier if you just create a user with email login?

1. Start a Rails console (`rails c`)
2. Allow email registration: `SiteConfig.allow_email_password_registration = true`
3. Start your server
4. Go to "Create account"
    <img width="234" alt="DEV_Community_👩💻👨💻" src="https://user-images.githubusercontent.com/47985/97145509-e6d33000-1798-11eb-8c80-ff9e982b9b78.png">
5. You'll now see a new signup option:
    <img width="579" alt="Welcome__-_DEV" src="https://user-images.githubusercontent.com/47985/97146062-cc4d8680-1799-11eb-8e54-97eeb0bdba64.png">
6. You can confirm the account from the Rails console: `User.find_by_email("...").confirm`

**Comment by khendrikse** [comment]
Awesome, I'll try those options! I will close this for now :) thank you so much for your help 🙏

**Comment by khendrikse** [comment]
@citizen428 I am wondering how this would work when using the docker container?

**Comment by citizen428** [comment]
@khendrikse It would work the same way, but you need to run the Rails console inside the container, like `docker-compose run web rails console`.

**Comment by rafaVls** [comment]
For future reference, I was having this exact same issue, and apparently the problem was that I was missing double quotes (") around my env variables. 

So, instead of having:
_GITHUB_KEY=oe1o23ma13kamczm2
GITHUB_SECRET=1023k1m20a9xczxkqm23i123masd_

I used:
_GITHUB_KEY="oe1o23ma13kamczm2"
GITHUB_SECRET="1023k1m20a9xczxkqm23i123masd"_

Hope this helps!
