### ISSUE TITLE
Ellipsis "More" sharing menu on left side of post view stops working after you submit a comment

### ISSUE THREAD

**Issue by rsmithlal** [forem/forem#10842]
**Describe the bug**

When reading a post on Dev.to, the ellipsis button `#article-show-more-button` on the left side column with the heart icon no longer expands to show the sharing menu after the user submits a comment.

**To Reproduce**

1. Go to a post: https://dev.to/maxwell_dev/six-surprises-i-found-in-the-wcag-2-1-accessibility-rules-p1i
2. Click on the horizontal ellipsis `#article-show-more-button` in the column left of the post. It should expand the sharing menu.
3. Scroll down to the section where you create a new comment and fill in the comment box and submit.
4. After the comment is submitted and appears under the post, go back up and click on the horizontal ellipsis again. It no longer expands the sharing menu.

**Expected behavior**

It is expected that submitting a comment will not prevent the sharing button from being able to expand the sharing menu. The sharing menu should always be able to be opened.

**Screenshots**

![image](https://user-images.githubusercontent.com/11048570/95987969-2d6a7700-0df6-11eb-8fc0-0f6e61004e3e.png)

**Desktop (please complete the following information):**

- OS, version: Pop! OS Ubuntu 20.04
- Browser, version: Firefox 81

**Comment by fdoxyz** [comment]
I was able to reproduce on macOS using Firefox:

https://share.getcloudapp.com/v1ux0Joe

I can see the following in the console:

<img width="1435" alt="Screen Shot 2020-10-19 at 15 12 17" src="https://user-images.githubusercontent.com/6045239/96512283-80409600-121d-11eb-85bc-a1ab2f753658.png">

[This function](https://github.com/fdoxyz/forem/blob/master/app/javascript/packs/articleModerationTools.js#L8) seems to be raising an exception for some reason (and not caught/handled)

**Comment by vezwork** [comment]
I'm going to look into fixing this if that's alright :)

**Comment by fdoxyz** [comment]
That's great @vezwork thanks! I just assigned the issue to you

**Comment by vezwork** [comment]
Added PR #10976 to fix this issue!
