### ISSUE TITLE
Experience Level of Post range should be configurable

### ISSUE THREAD

**Issue by AfroDevGirl** [forem/forem#10845]
**Is your feature request related to a problem? Please describe.**

On a new cloud Forem my community is not related to software development. There are experience levels in my community though so when an author is managing a post it makes sense to adjust the experience level of post. Right now the range goes from 'Total Newbies' to 'Senior Devs'. 

**Describe the solution you'd like**

The experience level range should be admin configurable. This config should probably live in the Community Content config section, although User Experience and Brand might make sense as well.

**Describe alternatives you've considered**

I don't think there are any possible alternatives

**Additional context**

![Screen Shot 2020-10-14 at 10 48 17 AM](https://user-images.githubusercontent.com/12255511/96009768-0ff5d700-0e0f-11eb-8b49-d34815379d4a.png)

**Comment by AfroDevGirl** [comment]
I would be happy to work on this as soon as possible to unblock my community from rolling out.

**Comment by pkfrank** [comment]
Tagging in @benhalpern who is going to add some context to this issue.
