### ISSUE TITLE
Add rails dbconsole command to the documentation

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#10843]
**Is your feature request related to a problem? Please describe.**

This is a documentation update suggestion from @citizen428.

The suggestion is to add to the documentation another way to get to the database prompt (currently psql) by running `rails dbconsole`.

**Additional context**

For more context, see https://github.com/forem/forem/pull/10835/files#r504378131

**Comment by nickytonline** [comment]
Whoever decides to work on this, see the documentation on [running the documentation locally](https://docs.forem.com/contributing/docs/#running-the-documentation-locally) to test out your changes.

**Comment by ShubhankarKG** [comment]
Do we mean to remove the `psql` part in its entirety or add a new step here? In any way, this looks like an easy fix, and I'll be more than happy to take this one up.

**Comment by citizen428** [comment]
@ShubhankarKG I'd mention both, but with a preference on `rails dbconsole`, since it's easier (you don't need to know the DB name).
