### ISSUE TITLE
Title input field is being hidden when composing a new post!

### ISSUE THREAD

**Issue by CrazyOptimist** [forem/forem#10855]
**Describe the bug**
![image](https://user-images.githubusercontent.com/55074937/96039716-b9989080-0e2e-11eb-9cc1-f876e50116fe.png)
**To Reproduce**
1. Go to Dashboard
2. Click on `Write a Post`
3. Check the screenshot above
**Expected behavior**
Should be able to see full title as I type.
**Desktop**
OS: Windows 10 build 1904
Browser: Chrome latest version
**Additional context**
It happens every time.

**Comment by Link2Twenty** [comment]
Relates to #10114

**Comment by CrazyOptimist** [comment]
Added +1 on there, closing this.
Thanks @Link2Twenty
