### ISSUE TITLE
error 404 found

### ISSUE THREAD

**Issue by bhattanchal2201** [forem/forem#10863]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by bhattanchal2201** [comment]
my account has been hack

**Comment by bhattanchal2201** [comment]
all the files and redirect page are not found

**Comment by citizen428** [comment]
Hello @bhattanchal2201, thanks for notifying us of this problem, this looks an issue specific to your account. Please email yo@dev.to for more help.
