### ISSUE TITLE
Rich markdown editor not working

### ISSUE THREAD

**Issue by chrisdemars** [forem/forem#10869]
**Describe the bug**

When switching to the rich text editor in the UX settings it doesn't switch the editor when crafting a post.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: macOS
- Browser, version: Chrome and FF latest of both

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by citizen428** [comment]
Thanks for the report @chrisdemars. However, I'm not unable to reproduce this on FF on Mac. I just switched several times between the two editors and it always works. After the update there's a flash message stating "Your config has been updated. Refresh to see all changes.", did you do that?
