### ISSUE TITLE
Add color picker in more admin areas

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#10872]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin, I may be required to add color hexes in various configuration areas.

**Describe the solution you'd like**
Ideally the same color picker that we use on `/settings` could be added in more areas.  For instance:

- [ ] `/admin/tags/{tag id}`
- [ ] `/admin/config` (in User Experience & Brand section)
- Likely other areas I'm overlooking right now

**Additional context**
We seem to have two different color pickers.  One visible on `/settings` (which I prefer) and a different one on `/t/{tag name}/edit` which is available to moderators of that tag.  It might be nice to standardize?

I also believe we do contrast / accessibility checks in the User Experience & Brand section, but I'm not sure if we do it everywhere.  But that's probably out of scope.

**Comment by citizen428** [comment]
This was very quick, so I just did it for the two admin pages, PR incoming.
