### ISSUE TITLE
Update existing keyboard shortcuts

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#10878]
Currently there are a few different keyboard shortcuts in Forem and they've been built a few different ways. It would be good to now unify these under the new approach (#10713)

**Describe the solution you'd like**

Code should be changed to the new solution

**Describe alternatives you've considered**

We leave the old code as legacy until it breaks

**Additional context**

#10713 is waiting to be merged this issue is just a place to store code that needs updating

- [x] [Article form](https://github.com/forem/forem/blob/ebe398ba23f0c92adfa41274759c5e25e899a57a/app/javascript/article-form/articleForm.jsx)
- [x] [Article form component](https://github.com/forem/forem/blob/04f1260bf5579bb2f978247d7c56391b68e9c577/app/javascript/article-form/components/keyboardShortcutsHandler.jsx#L6)
- [x] [Search](https://github.com/forem/forem/blob/653ec123006b8bf7f93b9f32ca13a9a0c959200a/app/javascript/Search/Search.jsx)
- [x] [Listings modal has a listener on 'Escape' to close it](https://github.com/forem/forem/blob/04f1260bf5579bb2f978247d7c56391b68e9c577/app/javascript/listings/listings.jsx#L91)

**Comment by reobin** [comment]
Search and toggle Zen mode (`0`) are done in #10468 🌞

Let's make a list of the missing ones. They should be fun to update.

**Comment by reobin** [comment]
2 more:
- [Article form has a listener on 'P](https://github.com/forem/forem/blob/04f1260bf5579bb2f978247d7c56391b68e9c577/app/javascript/article-form/components/keyboardShortcutsHandler.jsx#L6) (The whole component is probably obsolete now)
- [Listings modal has a listener on 'Escape' to close it](https://github.com/forem/forem/blob/04f1260bf5579bb2f978247d7c56391b68e9c577/app/javascript/listings/listings.jsx#L91)

**Comment by Link2Twenty** [comment]
@reobin do you wanna make an issue for a shortcut 'store' that can compile shortcuts per component for documentation?

**Comment by reobin** [comment]
@Link2Twenty Sure! At least, to start the discussion on how to do it best.

**Comment by citizen428** [comment]
@Link2Twenty I assigned you this issue now since you seem to be coordinating this effort (thanks for that btw).

**Comment by reobin** [comment]
Seems like it can be closed already @Link2Twenty good work

**Comment by Link2Twenty** [comment]
We shared the work 🙂
