### ISSUE TITLE
feat: Add a key shortcuts modal

### ISSUE THREAD

**Issue by reobin** [forem/forem#10879]
#10713 added a keyboard shortcut hook, and the migration for the current keyboard shortcuts to use the new hook has started. See #10878 

**Describe the solution you'd like**

As suggested in #10713, the new hook could be used to populate a keyboard shortcut modal like GitHub's one:

<img width="931" alt="Screen Shot 2020-10-16 at 08 54 53" src="https://user-images.githubusercontent.com/5920450/96260612-43f70680-0f8d-11eb-8c29-75ae381479b1.png">

The key `?` would pop up that modal.

The details of the implementation have to be discussed. Using the hook to populate a keyboard shortcut store means that the modal would be different on a per-page basis depending on which shortcuts are used on the current page.

Also, they can't be added in there randomly. The shortcuts would need categorization, so the hook will probably need an update in order to receive the shortcuts categories.

**Describe alternatives you've considered**

It would be easier to just build a static modal, although less maintainable.

**Additional context**

#10468 
#10713 
#10878

**Comment by citizen428** [comment]
Thanks for the issue @reobin! Did you plan on implementing this yourself or is the issue up for grabs?

**Comment by reobin** [comment]
Yes, I'd like to work on this, thanks @citizen428 !

**Comment by Link2Twenty** [comment]
I had a thought but I'm not sure how good an idea it is.

When we set up a shortcut we could 'register' the shortcut by putting it in an object on `window` (we could then remove it on unmount). We'd need to come up with an object model then we can read the variable in another component to show all, currently, registered shortcuts.

There is a chance this can go out of sync I guess but I'm not sure.

**Comment by citizen428** [comment]
You probably want to involve @nickytonline in this discussion, but he's a bit swamped with Hacktoberfest work, so it may take a bit for him to reply.

**Comment by Link2Twenty** [comment]
I can flesh out my idea a little more now I'm at a keyboard.

```jsx
useKeyboardShortcuts({
  Slash: () => { }
});
```

would become something like

```jsx
useKeyboardShortcuts("Search", {
  Slash: {
    func: () => { }
    desc: "Set focus to the search bar"
  }
});
```

The `useKeyboardShortcuts` function would need some changes too

```jsx
useKeyboardShortcuts(area, shortcuts, target) {

if (!window.shortcuts) window.shortcuts = {};

const windowTarget = window.shortcuts[area.toLowerCase()];
const keys = Object.keys(shortcuts);

for (let key of keys) {
  const keyExists = [...windowTarget].filter(obj => obj.key === key).length >= 1;
  if (keyExists) {
    console.alert(`useKeyboardShortcuts: ${key} for ${area} was registered more than once`);
    continue;
  }

  windowTarget.push({
    key: key,
    desc: shortcuts[key].desc
  })
}

}
```

and in `window` we'd see something like.

```jsx
window.shortcuts.search = [{key: Slash, desc: "Set focus to the search bar"}]
```

`window.shortcuts` would then give us a list of areas for heading and the array within the heading would give us all the shortcuts.

**Comment by reobin** [comment]
No rush, the PRs mentioned still need to be merged.

In the mean time, let's work on using the keyboard shortcut hook on more stuff so that the modal has something to show :)

Sounds like a good idea @Link2Twenty! I don't think there is a solution implemented right now for a frontend global state, which could also be a good idea for this, but definitely needs discussion with the core team to go in the right direction.

**Comment by nickytonline** [comment]
I'll hopefully get a peek at this before the end of the week.

**Comment by Link2Twenty** [comment]
UI/UX: <https://twitter.com/i/keyboard_shortcuts>

**Comment by cmgorton** [comment]
Hey all! Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
