### ISSUE TITLE
Update post publish date as a Forem Admin

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#10871]
**Is your feature request related to a problem? Please describe.**

As a Forem Admin, I may sometimes need to manually adjust the publish date to account.  This is currently possible via `/resource_admin`, but not `/admin`. 

**Describe the solution you'd like**

As a Forem Admin with relevant permissions, I should be able to go into `/admin/articles` and manually adjust a publish date.

**Comment by matisnape** [comment]
@citizen428 hi, can I try this one? :)

**Comment by citizen428** [comment]
@matisnape Of course, thanks a lot! :-)

**Comment by matisnape** [comment]
hey @citizen428 I have problems with setting up the project with docker - forem_yarn and forem_bundle are failing and exiting. I can't seem to find tips how to resolve that, I'm not docker fluent. This is the current state: 
![image](https://user-images.githubusercontent.com/2719923/96342372-e3a1bb00-1099-11eb-8b67-aacae5913a0a.png)
Do you maybe have some ideas?

**Comment by matisnape** [comment]
hey @citizen428 I think I have problems with setting up the project with Docker. When I try to log in with admin@forem.local/password I get the following error: 
![image](https://user-images.githubusercontent.com/2719923/96347482-54e56c00-10a2-11eb-9567-255f54c7f2ce.png)
What am I doing wrong?

**Comment by matisnape** [comment]
Nvrm, when I installed everything manually, it worked.

**Comment by matisnape** [comment]
@citizen428 hey, after looking at the code I have to say this is beyond my skill :(

**Comment by citizen428** [comment]
No worries @matisnape, thanks for trying! 😄 Are there any specific questions you have or any points we could give you? You invested time in this, it's only fair you at least take some learnings from it. Feel free to email me, same username as here @dev.to

**Comment by matisnape** [comment]
@citizen428 I thought this would be a simple Rails form, but in code I saw a lot of JS stuff - the whole editor. JS is not my area of expertise at all

**Comment by akashdotsrivastava** [comment]
@citizen428 Hi, I am new to forem. I'd like to give this a shot. Can I take it?

**Comment by citizen428** [comment]
Thanks for giving it a shot @matisnape!

@akashdotsrivastava I assigned you this issue now, please let us know how it goes.

**Comment by akashdotsrivastava** [comment]
@citizen428 Thanks. I added a PR ^^

**Comment by akashdotsrivastava** [comment]
@citizen428 Thanks. I added a PR. Please let me know the feedback.
