### ISSUE TITLE
Support light/dark background versions of Forem Logo

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#10880]
**Is your feature request related to a problem? Please describe.**
As a Forem admin, I am able to set my logo in Config > Images.  However, the same logo won't necessarily look good on different themes (which community members can change via `/settings/ux`).

**Describe the solution you'd like**
Support for a "light background" and "dark background" version of the Forem logo.  It should intelligently flip over to the proper logo depending on the theme being used.

**Describe alternatives you've considered**
We can just upload all logos with a light background attached but that's sub-optimal.

**Additional context**
We already have a similar concept for sponsors logo images.

**Comment by ludwiczakpawel** [comment]
Flipping the logo shouldn't be too hard.
But we do need to have another field in the `/admin/config` for that... So we would eventually have two fields for logos:

1. Default logo SVG 
2. Dark mode logo SVG (will be put against dark background)

Then we can flip these two easily in the frontend. 

---

Although there's one tricky part which is our Pink theme... Is the header in Pink theme considered to be light or dark? :)  But I guess that's less important problem to solve...

**Comment by cmgorton** [comment]
I believe we have this feature now. If this isn't what you meant Peter let me know and I can reopen this issue. 
![light and dark mode logos](https://user-images.githubusercontent.com/21039864/140997084-e0a55f09-67c2-4f17-9419-979a405defbf.png)
.
