### ISSUE TITLE
this is one error?

### ISSUE THREAD

**Issue by popstar555** [forem/forem#10896]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by citizen428** [comment]
Hi and thanks for the report. Since you provided no further information I'll close this issue, but feel free to reopen it after providing context around the error you encountered.
