### ISSUE TITLE
Don't include "Enter fullscreen mode Exit Fullscreen mode" for code blocks in RSS feed

### ISSUE THREAD

**Issue by humphd** [forem/forem#10927]
**Describe the bug**

RSS feed versions of dev.to articles that include syntax-highlighted code (e.g.,  `<pre><code>...</code></pre>`) also include the following text after the code:

```

    Enter fullscreen mode
    


    Exit fullscreen mode
    


```

**To Reproduce**

1. Consider a post like https://dev.to/phast184/remotes-commits-and-merges-is-that-a-long-distance-relationship-bfo
2. The RSS feed at https://dev.to/feed/phast184 includes the extra UI element `<div class="highlight__panel-action js-fullscreen-code-action">`

**Expected behavior**

Before publishing the feed, it would be great if this UI `<div>` could be stripped out.  It doesn't make sense in the syndicated article.

**Comment by query-string** [comment]
I'd jump into this one

**Comment by rhymes** [comment]
Assigned to you @query-string, thanks!
