### ISSUE TITLE
Users occasionally receiving duplicate/multiple DEV Digest emails

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#10940]
**Describe the bug**

We offer a setting that says "Send me a periodic digest of top posts from my tags." Occasionally users who have checked this are receiving multiple/duplicate DEV Digests just a few hours apart which is a confusing experience.

**To Reproduce**

1. Visit https://dev.to/settings/notifications
2. Check "Send me a periodic digest of top posts from my tags"
3. Monitor email cadence.

NOTE: It's unclear if these reproduction steps are guaranteed to trigger duplicate/multiple DEV Digest bug behavior.

**Expected behavior**

When checking "Send me a periodic digest of top posts from my tags." I'd expect never to receive duplicate emails and only to receive these suggestions daily at most. That said, the exact cadence isn't specified.

**Screenshots**

Here's where users select to receive the digest - https://dev.to/settings/notifications:

![Image 2020-10-19 at 4 33 10 PM](https://user-images.githubusercontent.com/16007075/96508581-cf3ff880-1228-11eb-8b9a-0484da2d9d37.png)

**Additional context**

I'll notify users who have experienced duplicate digests about this issue so that they might follow along and comment if they'd like. 

For whoever decides to work on this issue, if it would help to be in contact with someone who is receiving duplicate digests or if you would like to me to forward any questions, then please let me know. 

FROM MOLLY:
We have a guard clause in our `class EmailDigestArticleCollector` that should prevent users from every receiving multiple emails even in the event that a job is rerun. However, we have seen that is not the case. This makes me believe that the guard clause `return true unless last_email_sent_at` is not working. 
```ruby
  def should_receive_email?
    return true unless last_email_sent_at

    # Has it been at least x days since @user received an email?
    Time.current - last_email_sent_at >= days_until_next_email
  end
```
That further leads me to think that we are not properly recording when the last email was sent for a user. That is where I would look first when trying to solve this bug.

**Comment by KenDarlingJr** [comment]
I am the one that was having some problems with this.  I think at some time along the way I have made a change to my email address. But I think that I only had one account.

**Comment by michael-tharrington** [comment]
Thanks for chiming in here @KenDarlingJr! I know a few others have experienced this too and believe that @jessleenyc might be affected as well.

I honestly don't typically receive the Daily Digest so haven't tested this thoroughly.

**Comment by michael-tharrington** [comment]
>> When checking "Send me a periodic digest of top posts from my tags." I'd expect never to receive duplicate emails and only to receive these suggestions daily at most. That said, the exact cadence isn't specified.

The more I think about this, the more I feel like we should specify an exact cadence if we can or at least provide more info about how frequent periodic is....

**Comment by karfau** [comment]
Is there any information that you could add to the mail headers to "debug" this?
I'm willing to add those headers to this issue whenever I get "the same" mail multiple times.

This is how it looks for me (german time zone):
![image](https://user-images.githubusercontent.com/135657/99300741-46c76e80-284d-11eb-9643-2183277594b0.png)
The only difference in those mails that have the same start (`"Title" +`) are the time send and the end of the subject, I never spotted any difference in the content.
And that's about it regarding "recognizable patterns".

If there is nothing I can do to support this case, I would rather switch of this option off and switch it back on when it's solved. So please let me know.

**Comment by mbenoukaiss** [comment]
I'm still receiving the duplicate emails, but I've noticed something, the emails are not fully duplicate, it's just part of the content, if that can help find the source of the issue.
![image](https://user-images.githubusercontent.com/34457865/102604310-48be6f00-4124-11eb-89d5-129d6ec007e5.png)
![image](https://user-images.githubusercontent.com/34457865/102604342-54119a80-4124-11eb-99ba-89146daf4391.png)

**Comment by rsamp** [comment]
Today seems like an extreme case, but this is getting pretty frustrating. I received the digest email 6 times this morning. From looking through email history, I typically get the digest 1, 2, or 3 times and I've oddly gotten used to it, but today was much more noticeable.

![image](https://user-images.githubusercontent.com/12284336/103382087-85825280-4aa2-11eb-84e3-d203386f9d60.png)

Article list breakdown in case it helps (some were exact duplicates aside from the emojis used in the Subject line):
- 3:33 AM and 3:34 AM were the exact same
- 7:37 AM had the same articles as the above, but with the order of the last two flipped
- 9:23 AM had the same top 5 as 7:37 AM but the 6th article was different
- 9:47 AM had the same articles and same order as 9:23 AM
- 10:38 AM had the same top 5 as 9:47 AM but the 6th article was different

**Comment by michael-tharrington** [comment]
@rsamp Thanks for flagging this! 

We found a bug in our code the other day that was causing a worker to run that should not have been which was sending multiple duplicate digest emails. A fix was merged and we killed the worker to hopefully prevent more duplicates. If you would like to view the PR, you can find it here: https://github.com/forem/forem/pull/12082.

All this said, I do believe we still have issues with the digest's cadence/subject line/content being too frequent/repetitive to the point that it seems like it's duplicate content.

**Comment by azurh** [comment]
![image](https://user-images.githubusercontent.com/5826537/114320506-75085c00-9b16-11eb-9aa9-8edada5d65f5.png)

**Comment by lisasy** [comment]
@joshpuetz will talk about this related issue: https://github.com/forem/forem/issues/13761

**Comment by joshpuetz** [comment]
This is being caused by a weird interaction between our digest frequency setting, and how often the digest sidekiq worker is running in production.

The setting to send digests ever day are working correctly: every 2 days a digest is queued up to be sent. The wrinkle is that sending digests happens in a background job, and that job only runs Wednesday through Saturday. On Sunday through Tuesday, the same digest is being queued up to be sent, resulting in duplicates (since our cadence is a digest every 2 days, just a single duplicate is sent). 

(Peter referenced/reported this same problem in issue https://github.com/forem/forem/issues/13761)

As for a solution: perhaps the digest job could check for undelivered digest before enqueuing another one?

**Comment by jwedel** [comment]
I get the digest between 1 and 4 times for an issue, one each day:

![image](https://user-images.githubusercontent.com/4849728/131227970-fd80f9cf-cce0-4c4b-9b6f-c096b8c74d79.jpeg)

This is really frustrating and time consuming as I start reading until I recognize, I read it already.
