### ISSUE TITLE
Incorrect number in series list truncation (x more parts...)

### ISSUE THREAD

**Issue by HaveSpacesuit** [forem/forem#10956]
**Describe the bug**

When listing the parts of a long series, the first and last few articles are visible while those in the middle are truncated with the message `X more parts...`

However, there seems to be an off-by-two error. For example, if there are two parts hidden, it shows `4 more parts...`.

![image](https://user-images.githubusercontent.com/15036346/96589871-f5a67800-12aa-11eb-8f51-981b25255feb.png)

https://dev.to/robole/how-to-run-webpack-automatically-in-vs-code-when-you-open-a-project-1c19

**Comment by Symasia** [comment]
I'd like to take this up if no one's going for it

**Comment by rhymes** [comment]
Thanks @Symasia, I've assigned it to you
