### ISSUE TITLE
Spotify liquid tags showing as 'bad request' in article preview and when published.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10951]
**Describe the bug**

When using the Spotify liquid tag in posts, they appear as "Bad Request" when previewed

**To Reproduce**

Create a new article
Insert a liquid tag for a spotify track such as > {% spotify spotify:track:3GfOAdcoc3X5GPiiXmpBjK %}
Publish or view the preview

**Expected behavior**

The spotify liquid tag to appear in the article

**Screenshots**

<img width="1028" alt="Screenshot 2020-10-20 at 10 44 08" src="https://user-images.githubusercontent.com/12694270/96569603-41641c00-12c1-11eb-8495-fb938b540da5.png">

**Comment by tudorpavel** [comment]
Identified the issue and fixed in #10953.

**Comment by leewynne** [comment]
> Identified the issue and fixed in #10953.

Great!!!!
