### ISSUE TITLE
Search doesn't find person with exact username

### ISSUE THREAD

**Issue by jeresuikkila** [forem/forem#10967]
**Describe the bug**
Searching with exact username does not find the person.

**To Reproduce**
1. Go to dev.to
2. Search for "davidkpiano"
3. Switch to "people" to enable the filter (url: https://dev.to/search?q=davidkpiano&filters=class_name:User)
4. "No results match that query"

**Expected behavior**
Show link to https://dev.to/davidkpiano

**Screenshots**
![image](https://user-images.githubusercontent.com/5408651/96640310-a48a9880-132b-11eb-8321-c7af56551e3f.png)

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04
- Browser, version: Firefox 81.0.2

**Comment by krzysiek1507** [comment]
I guess I should claim it since I submitted a PR already?
