### ISSUE TITLE
Fullscreen code blocks not working on comments page

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#10979]
**Describe the bug**

The new full screen code block feature does not work on the specific comments page

**To Reproduce**

1. Go to a [comment](https://dev.to/link2twenty/comment/1465h)
2. Click on the new code block expand option
3. See nothing happens

**Expected behavior**

Should expand to full screen like is does in the [comments section](https://dev.to/emmabostian/creating-a-custom-scroll-bar-in-24-lines-of-css-4gg0#comment-node-531483) of a post

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 86

**Additional context**

Feature first added in #10784

**Comment by citizen428** [comment]
@Link2Twenty Were you planning on attempting a fix for this yourself?

**Comment by Link2Twenty** [comment]
@citizen428, no it was just something I noticed.

**Comment by Winner95** [comment]
I would be interested in fixing this bug.

**Comment by citizen428** [comment]
Thanks @Winner95, I assigned you the issue.
