### ISSUE TITLE
Write a post - error 500

### ISSUE THREAD

**Issue by devilstars** [forem/forem#10986]
**Describe the bug**

Click on "write a post" - error 500, "You have encountered an error."

**To Reproduce**

1. Go to "write a post".
2. See error.

**Expected behavior**

No error

**Screenshots**

![2020-10-21_162143](https://user-images.githubusercontent.com/12907959/96725444-8bc8c400-13b9-11eb-9847-eba69c96ff58.jpg)

**Desktop (please complete the following information):**

- OS, version: windows 10
- Browser, version: new edge, vivaldi, chrome, opera, firefox (all latest)

**Comment by rhymes** [comment]
Hello @devilstars, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
