### ISSUE TITLE
Profile update - error 500

### ISSUE THREAD

**Issue by devilstars** [forem/forem#10987]
**Describe the bug**

Can't update profile info - error 500.

**To Reproduce**

1. Click "Settings"
2. Choose any type of settings. Let it be UX.
3. Click "Save"
4. See error.

**Expected behavior**

No error.

**Screenshots**

![2020-10-21_162655](https://user-images.githubusercontent.com/12907959/96726038-3fca4f00-13ba-11eb-9d5e-ddd41d326cc0.jpg)

**Desktop (please complete the following information):**

- OS, version: windows 10
- Browser, version: chrome, vivaldi, new edge, opera, firefox (all latest)

**Comment by rhymes** [comment]
Hello @devilstars, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
