### ISSUE TITLE
Reactions don't work - 404 error

### ISSUE THREAD

**Issue by devilstars** [forem/forem#10988]
**Describe the bug**

Reactions are not being saved.

**To Reproduce**

1. Open any post.
2. Click any of the available reactions.
3. Nothing happens.

**Expected behavior**

![2020-10-21_162921](https://user-images.githubusercontent.com/12907959/96726587-c4b56880-13ba-11eb-8d6a-e4091197bb22.jpg)

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: windows 10
- Browser, version: new edge, chrome, vivaldi, opera, firefox (all latest)

**Comment by rhymes** [comment]
Hello @devilstars, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
