### ISSUE TITLE
DEV social share/preview logo and images on Cluster Employment Community

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#10994]
**Describe the bug**

Not a bug per say, but social shares from our community on Forem show DEV's image and logo as opposed to the Cluster Employment's.

 

**To Reproduce**

1. Share a user profile, tag, listing or no-image article link on Facebook, Slack or any other social media platform
2. See DEV branding on article as opposed to Cluster Employment's

**Expected behavior**

Cluster Employment branding on social shares

**Screenshots**

![screen](https://user-images.githubusercontent.com/32549192/96747544-c4a76f80-139e-11eb-8d2d-8ee39271b75a.png)

**Desktop (please complete the following information):**

- OS, version: Microsoft Windows 8.1 
- Browser, version: Google Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S10e
- OS, version: Android 10
- Browser, version: Google Chrome 86.0.4240.00

**Additional context**

Here's a link to the Cluster Employment badge: https://cluster-assets.netlify.app/images/cluster-badge.png

**Comment by pkfrank** [comment]
This has been fixed for a while 👍
