### ISSUE TITLE
Full Contributors' Guide page does not load...

### ISSUE THREAD

**Issue by Angelfirenze01** [forem/forem#11004]
Full Contributors' Guide does not load.

I don't currently have any customizations on Firefox 83 Developer Edition.

**Describe the bug**

The page simply does not load.

**To Reproduce**

Copy and paste the URL for [https://docs.forem.com/contributing/forem/](https://docs.forem.com/contributing/forem/) and click 'enter/return'.

 

Forem Contributors' Guide link.

 Forem Contributors' Guide link.

 

N/A

 404 

Not Found
nginx/1.18.0

**Expected behavior**

The page should load, allowing readers to peruse the Contributors' guidelines for Forem-related projects.

**Screenshots**

 #https://hosting.photobucket.com/images/v204/Angelfirenze/Screenshot_2020_10_21_404_Not_Found.png

**Desktop (please complete the following information):**

- OS, version: Windows 10 

- Browser, version:

Version	10.0.18363 Build 18363

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

N/A

**Comment by citizen428** [comment]
It loads fine for me in Firefox and also returns a 200 when testing from the command line:

```
http --print=h https://docs.forem.com/contributing/forem/
HTTP/1.1 200 OK
Age: 1
Cache-Control: public, max-age=0, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Thu, 22 Oct 2020 04:46:21 GMT
Etag: "dc9a934409009779e645b9740bb77306-ssl-df"
Server: Netlify
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-NF-Request-ID: 340897a3-2195-4b69-82f1-fd003f5d8dfa-12821551
```

Can you please verify if it now works for you?

**Comment by rhymes** [comment]
https://docs.forem.com/contributing/forem/ works fine for me too

**Comment by Angelfirenze01** [comment]
Anytime I try and load it in Chrome, I get a warning about the connection to it not being private and do I want to go back to safety.

Tomorrow morning, I will try loading it again in Firefox, both on my iPhone and on my laptop.

**Comment by Angelfirenze01** [comment]
I was able to load it using Firefox, but Chrome...now, apparently, as decided to load properly.  I haven't disabled any extensions or done anything but wait, so I have no idea what caused that problem so persistently when I created the issue.  Does this count as a contribution or no?
