### ISSUE TITLE
Article rendering: make cursor style pointer on the collapsible details

### ISSUE THREAD

**Issue by korigod** [forem/forem#11011]
When the `details` liquid tag is used to create a collapsible section, cursor style is text. It is then not obvoius that the summary is clickable. Is it possible to change the cursor style somehow (e.g. to add custom css)? Don't you find logical to include this in the default css?

<details>
<summary>By the way, check out what style github uses for collapsibles!</summary>

```
details summary {
    cursor: pointer;
}
```
</details>

**Comment by morganrconnolly** [comment]
I'd like to work on this one please C:

**Comment by rhymes** [comment]
@morganrconnolly please go ahead, I've assigned it to you

**Comment by dengel29** [comment]
Not sure if @morganrconnolly is getting to this but I can help if not.

**Comment by rhymes** [comment]
@morganrconnolly 

Since this PR has not been active for a while I am going to go ahead and reassign it. Feel free to keep following this issue and adding your thoughts here or in the PR when it'll be read.

We couldn’t do what we do without awesome contributors like yourself, thank you so much for being a part of our awesome Forem community! :-)

**Comment by rhymes** [comment]
@dengel29 thanks for volunteering, I've reassigned the issue to you, thank you!

**Comment by cmgorton** [comment]
@dengel29 thanks for volunteering for this issue.
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. 
Given this process I am going to unassign you from this issue for now. 
In the meantime if you see any bugs you want to squash let me know and we can assign them to you!
