### ISSUE TITLE
Optimize SVGs entered via /admin/config

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11019]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin, I may supply an SVG that is not optimized.

**Describe the solution you'd like**
Upon supplying an SVG in `/admin/config`, we automatically optimize the SVG.

**Describe alternatives you've considered**
Live with an un-optimized SVG or provide the Forem Admins with documentation on self-optimizing.

**Additional context**
It sounds like we may be able to use Carrierwave for this (cc @maestromac)

**Comment by cmgorton** [comment]
@pkfrank would you like this to be a potential RFC? If not let me know if we should close it for now. Thanks.

**Comment by pkfrank** [comment]
@cmgorton given that the specific "pain point" hasn't come up recently, I'm fine to close it for now.  We can always revisit if we're responding to specific Creator feedback.
