### ISSUE TITLE
feat: Add a keyboard shortcut to save an article in the feed

### ISSUE THREAD

**Issue by reobin** [forem/forem#11018]
**Is your feature request related to a problem? Please describe.**
This feature will complement #10468 very well.

Basically, something like `s` or `b` would save/unsave an article when you are navigating the feed with the keyboard as long as the focus is inside an article item.

**Describe the solution you'd like**
Using the `useKeyboardShortcuts` hook, we can listen for the chosen key.

On press:
* fetch the parent article of the currently focused element using `element.closest`
* get the id of the article
* bookmark the article using the id

**Describe alternatives you've considered**
1. It could also click on the `save` button, which already has an `onClick` event listener that bookmarks, but that's hardly maintainable. With a refactor to that event listener, both shortcut and `onClick` could use the same `bookmark` function, which is a better option IMO.

2. Another option is to add an `onKeyDown` event listener on the article itself, which would make the process easier but would not use the `useKeyboardShorcuts` hook. Using the hook will be necessary for the eventual keyboard shortcuts modal.

3. Another option is to add the `useKeyboardShortcuts` hook on all the articles, which would have the benefits of the second option but would add potentially hundreds of `keydown` event listeners.

**Additional context**
#10713 
#10879

**Comment by rhymes** [comment]
I would keep `s` as an alias for `/` to focus on the search bar. Love the idea though!

**Comment by reobin** [comment]
Agree with `s` meaning search @rhymes 

It's doable right now using the `useKeyboardShortcut` hook, but there isn't that much value to it since you need to use `tab` and therefore are forced to focus on the save button anyway before passing to the next article.

Let's wait on #10468 :)

**Comment by Link2Twenty** [comment]
Remember we have access to modifier keys too `ctrl + s` means save to most people. By default it would save the html of the page but I don't think people need that?
