### ISSUE TITLE
Add settings for Discussion subscription

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#11036]
**Is your feature request related to a problem? Please describe.**

As a user I want to decide whether leaving a comment under a post will automatically subscribe me to the discussion or not.
- If yes, then I want to decide whether I want to receive notifications about all comments or only specific ones (post author, replies, top-level)

With that in place, we could by default subscribe all users to a discussion after leaving a comment UNLESS they've updated own settings.

**Describe the solution you'd like**

Add two fields in `/settings/notifications` so users can control it for themselves.

![image](https://user-images.githubusercontent.com/108287/96977194-0827e800-151d-11eb-9adf-21177d485556.png)

**Additional context**

[There's a PR](https://github.com/forem/forem/pull/7666) (currently closed because of lack of resources, but can be reopened) with frontend code for these settings. But it needs backend... 🤷

**Comment by rhymes** [comment]
My initial idea was to have a global subscribe option to all comments as well. Basically: someone posts an article, I'm then subscribed to all comments, regardless I pressed the subscribe button or not.

**Comment by ludwiczakpawel** [comment]
@rhymes you mean no matter whether or not I clicked "Subscribe" or commented on something, I will get notifications about new comments anyway? Feels shady :D

**Comment by rhymes** [comment]
@ludwiczakpawel that's why it should absolutely be an opt-in :D

**Comment by cmgorton** [comment]
Hey @ludwiczakpawel do you think this should be labeled as a `potential RFC`? If not let me know if we should close this issue here. Thanks.

**Comment by ludwiczakpawel** [comment]
@cmgorton yeap!

**Comment by cmgorton** [comment]
Great! Thank you for letting me know @ludwiczakpawel
