### ISSUE TITLE
UX on mobile version, code logo problem 

### ISSUE THREAD

**Issue by pipic1** [forem/forem#11043]
**Logo on code div big on mobile version**

On each article, logo to expand ans reduce code take the whole page

**To Reproduce**

Launch mobile version (Xiaomi MI 9T / K20 Pro)

On each article that contrains code

**Expected behavior**

**Screenshots**

![Screenshot_2020-10-23-20-40-23-227_to dev dev_android](https://user-images.githubusercontent.com/15725317/97041797-5914fc00-1570-11eb-8487-7a02511948bf.jpg)

**Smartphone (please complete the following information):**

- Device: Xiaomi MI 9T
- OS, version: Android 10
- Browser, version: Miui 12

**Comment by ludwiczakpawel** [comment]
This feels like some caching issue. I'm closing since I believe it should be fixed now. But let me know if it's not, I'll reopen the issue then.
