### ISSUE TITLE
Confusing how to add multiple tags in the post editor

### ISSUE THREAD

**Issue by clottman** [forem/forem#11048]
**Describe the bug**

I am writing a post. I want it to have two tags. When I press the space bar after typing the first tag, nothing happens. There is no text instructing me about any special things to do if I want multiple tags. Eventually after much confused keysmashing, I discovered a comma is required between tags, not just a space.

**To Reproduce**

Start drafting a post.
In the line that says you can have up to 4 tags, type a word. (I chose 'accessibility'). 
Press space at the end of typing your tag word. Nothing happens. Look at the help text about what tags might be - there is no instruction to enter a comma between tags.

**Expected behavior**
In the 'Tagging Guidelines', mention that multiple tags should be comma separated.

**Screenshots**
<img width="1357" alt="screenshot of tags area in the post editor" src="https://user-images.githubusercontent.com/4480480/97054949-679cec80-154b-11eb-8667-ba50e499d25e.png">

**Desktop**
- Device:
- OS, version: OSX
- Browser, version: latest firefox or chrome,

**Comment by citizen428** [comment]
As a quick fix, we could update the placeholder to "Add up to 4 comma-separated tags...". Want to give it a shot? 😀

**Comment by clottman** [comment]
You're lucky I saw the email first which didn't have the edit, which encouraged me to try it myself. :) And that I couldn't sleep tonight. Opened a PR, but I'm not a regular contributor here and didn't go through the effort to do run things locally & test - hope it helps a little bit at least.

**Comment by citizen428** [comment]
Thanks @clottman, much appreciated! 🚀
