### ISSUE TITLE
Selected repos in GitHub integration don't use dark theme color

### ISSUE THREAD

**Issue by pjsier** [forem/forem#11052]
When using the Night theme on the [Integrations page](https://dev.to/settings/integrations), selected repos in the GitHub section don't use theme colors so they aren't readable.

**To Reproduce**

1. Go to the [Integrations page](https://dev.to/settings/integrations) with the Night theme enabled
2. Select a repo in the GitHub section

**Expected behavior**

I would have expected it to use a color from the theme so that it's readable.

**Screenshots**

![2020-10-24_13-20](https://user-images.githubusercontent.com/8291663/97089198-e3567200-15fb-11eb-8adc-a725ffdad006.png)

**Desktop (please complete the following information):**

- OS, version: Pop_OS!, 20.04
- Browser, version: Firefox, 82.0

**Additional context**

Looks like the issue is that the selector `.github-repos .github-repo-row.github-repo-row-featured` has a hard-coded color. Based on the Notifications page it looks like this could use the `--body-bg` var. I'm happy to put in a PR if this is helpful, thanks!

**Comment by FreakLevel** [comment]
I want to work on this issue. The color of the hover cannot be seen either. Can I fix the hover and selected rows?

**Comment by rhymes** [comment]
Thanks @FreakLevel, I assigned you to it!
