### ISSUE TITLE
Article rendering: YouTube embed in a collapsible section

### ISSUE THREAD

**Issue by korigod** [forem/forem#11060]
YouTube embed (`{% youtube <id> %}`) is not being rendered if it appears inside the collapsible details, like this:

```
{% details <summary> %}
    {% youtube <id> %}
{% enddetails %}
```

However, some other liquid tags, e.g. Github embed, do work inside. Is it intentional behavior or a bug?

**Comment by rhymes** [comment]
@korigod mmm I think it's a bug though most liquid tags aren't intended to be "composable"

**Comment by akashdotsrivastava** [comment]
@rhymes I'd like to give this a shot if it's okay.

**Comment by rhymes** [comment]
@akashdotsrivastava thanks! I've assigned you to it

**Comment by akashdotsrivastava** [comment]
@rhymes Thanks, I've added a PR above. Feedback welcome.
