### ISSUE TITLE
Attach images to listings

### ISSUE THREAD

**Issue by leewynne** [forem/forem#11098]
**Describe the solution you'd like**

Over at thismmalife.com we have renamed listings to Marketplace (in the nav section).

I think it would be a delightful option to allow members to add a single image to their listings, which I think would make it more like a marketplace to buy and sell equipment rather than just services

**Describe alternatives you've considered**

Only the above option 😱

**Additional context**

I think this would provide a rich experience to the current listings experience without too much Dev effort 😇

**Comment by benhalpern** [comment]
I think the way images should work on listings is one spot for all images. (like the cover image for an article).... But if there are more than one image it acts like a slide show.

I think this is the experience folks have come to expect, and unlike a post (the article model) which I think should be really extensible and complex to the extent it needs to be, I think the listing model should stay sort of simple in format and i/o.... So no images in the body, but yes to a main image and/or carousel IMO.

Technically we've talked about an Image model (which an article can have many of, to keep track of overall media), and listings could also have a has many relationship to images in the same way.

**Comment by leewynne** [comment]
Agree, sounds like a plan!

**Comment by ludwiczakpawel** [comment]
+1 to the image(s).

And I also think we could make listing looks a little bit more like an article - at least in regards to how/where to display image (which I imagine would behave like a cover photo for articles). I'm also in favor of letting ppl upload more than one photo - and in that scenario cover image would become a slide show.

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
