### ISSUE TITLE
Add chaining to shortcuts

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#11094]
Currently shortcuts are a single key + any modifiers. It's quite common, on github and on twitter for instance, to be able to chain key presses to achieve something for instance `g` then `h` to go home.

**Describe the solution you'd like**

I think the new keyboard shortcut hook, #10713, should remember key presses for half a second and we should add a then syntax. Pressing a modifier key or nothing for half a second should clear the chain.

**Example:**

```js
useKeyboardShortcuts({
  "KeyG~KeyH": (e) => {
    e.preventDefault();
    alert("G has been pressed quickly followed by H");
});
```

**Describe alternatives you've considered**

We don't support chaining of keys in shortcuts.

**Additional context**

I noticed `G` for 'go to' is a common practice so perhaps something we should support.

**Comment by rhymes** [comment]
Aside: this is why I suggested https://github.com/github/hotkey in the initial discussion, glad we're getting there on our own :)
