### ISSUE TITLE
Do not clear fields on account creation page if failed from invalid username

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11099]
**Is your feature request related to a problem? Please describe.**
As a new user creating an account via `/users/sign_up?state=email_signup` (where a forem has enabled email/pass registration), I will lose all of the filled-out fields if I accidentally use an invalid username.

**Describe the solution you'd like**
Don't clear these fields.  I imagine that means validating the field in the browser before the form submits?

**Additional context**
[Here is a video in action.](https://p241.p3.n0.cdn.getcloudapp.com/items/WnurZYv6/Screen%20Recording%202020-10-26%20at%2003.44.58%20PM.mp4)

Raised by a community member of `the.community.club` [here](https://the.community.club/evanhamilton/comment/32).

**Comment by bntzio** [comment]
@rhymes may I work on this fix?

**Comment by rhymes** [comment]
@bntzio sure you can, thank you! I've assigned it to you

**Comment by bntzio** [comment]
Ready on #11201 @rhymes @pkfrank 😄
