### ISSUE TITLE
Enhance the "view more comments" functionality at the bottom of long comment threads

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11097]
**Is your feature request related to a problem? Please describe.**
As a viewer / participant of a long comment thread, I'll frequently click the "View More Comments" button at the bottom of a thread.  It takes me to the `/comments` page of that post, but I "lose my progress" and have to scroll back down to the bottom.

**Describe the solution you'd like**

1. _Ideally_, upon clicking "View More Comments" the comment section simply expands and populates with more comments without another page reload.

2. If approach 1 above isn't possible, having the `/comments` page take me to the proper "point" in the thread would be really nice.  That "point" is probably having the last visible comment from the previous page at the very top, so that I can stay "in the flow" and easily understand that the new comments are now underneath. 

**Additional context**
Originally raised as an idea on `the.community.club` [here](https://the.community.club/evanhamilton/comment/39).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
