### ISSUE TITLE
Profile menu (rightmost item in the header) is unclickable [UPDATE: Needs non-Chrome support]

### ISSUE THREAD

**Issue by trueneu** [forem/forem#1110]
**Describe the bug**
Profile menu (rightmost item in the header) is unclickable. "Dashboard", "Write a Post", "Reading List" etc menu items appear only on hover.

**To Reproduce**

1. Go to any https://dev.to/ page, including https://dev.to/
2. Click the profile picture without hovering your mouse pointer over it. (With Vimium, for example)
3. Nothing happens

**Expected behavior**
All the menu items ("Dashboard", "Write a Post", "Reading List" etc) should show up on click just as they do on hover. They're inacessible without hovering the pointer.

**Desktop (please complete the following information):**

- macOS 10.13.4
- Google Chrome
- v 70.0.3538.102

**Additional context**
https://medium.com/simple-human/why-hover-menus-are-problematic-b21d6c7de91c

**Comment by jessleenyc** [comment]
Thanks for flagging! This issue is approved if anyone wants to work on it.

**Comment by benhalpern** [comment]
Sorry I didn't even think to test this cross-browser. I sort of assumed this stuff was standard. I've got some other stuff to get to.

If anyone wants to give this a try, check out `initializeTouchDevice` for where the code currently lies.

**Comment by trueneu** [comment]
There's great to see some effort in that direction made already, but it still doesn't work with Vimium.
https://www.youtube.com/watch?v=5FxvMzs3drQ

**Comment by Link2Twenty** [comment]
> I noticed it doesn't work for Firefox or Safari. 

It works on Firefox 63.0.3 (64-bit) on Windows 10, I can't test Safari though.

**Comment by maestromac** [comment]
with `sVim`, it works on Safari 12.0.1

**Comment by trueneu** [comment]
It was not solved. Some other issue along were, not the original one.

**Comment by rhymes** [comment]
Is this still an issue?

**Comment by mstruve** [comment]
Thanks so much for the report! Since this no longer looks to be an issue so I am going to close it as we tidy things up for Hacktoberfest 😄

**Comment by trueneu** [comment]
It is still an issue and it was not fixed in any way.

**Comment by rhymes** [comment]
Thanks @trueneu - I'll keep this open

**Comment by trueneu** [comment]
I can only test it with Chrome and vimium at the moment - doesn't work there.
Chrome version 85.0.4183.121, vimium 1.66.

**Comment by aitchiss** [comment]
Closing this issue as it was fixed under #14317 - the profile menu now operates like a dropdown - it's visible on hover, but also stays open when clicked (either by mouse or keyboard) 🙂 

If you still encounter this issue please re-open and we'll investigate further!
