### ISSUE TITLE
Missing characters in /confirm-email route while resending email instructions

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#11106]
**Describe the bug**
On the `/confirm-email` route, certain characters seem to be stripped away from the email params.

**To Reproduce**

1. Sign up for an account on a Forem instance using _email authentication_. Use an email that has a `+` character in it (for example, `yourname+1@dev.to`) to sign up.
2. Go to through the sign up flow to the point of the `/confirm-email` route.
3. On the `/confirm-email` route, you'll notice that the email in the URL params is correct but the email rendered in the view is not. Then, if you try to actually click on the `Resend confirmation instructions` button, you'll see an error message, because the email is incorrect and doesn't contain the `+` character 😕 

**Expected behavior**

I expect that the email should match what I entered earlier in the sign up flow, and that the params in the URL should be the same as what is displayed in the form.

**Screenshots**

<img width="1357" alt="Screen_Shot_2020-10-26_at_4_39_08_PM" src="https://user-images.githubusercontent.com/6921610/97240005-48e86100-17aa-11eb-8b49-b85bc73ff505.png">

**Comment by vaidehijoshi** [comment]
@forem/smash Let me know if this aligns with any of your current/planned tasks! 😸

**Comment by pkfrank** [comment]
This is on the @forem/smash board ([link](https://github.com/forem/InternalProjectPlanning/issues/105)), so maybe we should close that issue if @forem/creator-onboarding is taking it?  It's not a particularly pressing item, but I do find myself needing this frequently when creating test accounts.

**Comment by vaidehijoshi** [comment]
@pkfrank Ah! I specifically searched our currently-open issues to make sure I wasn't creating a duplicate 🙈 but I guess I missed it! I ran into this today while working on the creator onboarding flow for new forem creators and I ended up having to change this enough times that I opened this issue for it.

I can definitely close this one out if it's already on @forem/smash's radar 😅

**Comment by vaidehijoshi** [comment]
Closing this out in favor of https://github.com/forem/InternalProjectPlanning/issues/105.
