### ISSUE TITLE
Add ability to crop profile image after upload

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11101]
**Is your feature request related to a problem? Please describe.**
As a community member uploading a non-square profile photo, my profile photo may appear distorted when it's displayed in the circular profile area.

**Describe the solution you'd like**
After profile image upload, an ability to set the "crop" area of the photo.

**Additional context**
This was raised by a member of `the.community.club` [here](https://the.community.club/jocelynhsu/comment/2c).

**Comment by maestromac** [comment]
this should be resolved with https://github.com/forem/forem/pull/11044
