### ISSUE TITLE
Adding a Mod to a Tag Should Automatically Mark the Tag as Supported

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#11140]
**Is your feature request related to a problem? Please describe.**

Yes, it's inefficient and opens the door for manual error to need to mark a tag as supported to a tag that is currently being modded.

**Describe the solution you'd like**

When you add a tag mod to a tag, it should automatically mark the tag as supported.

**Describe alternatives you've considered**

N/A

**Additional context**

We realized that some tags with tag mods are not marked as supported.

**Comment by citizen428** [comment]
I needed a break from profile work, so I quickly did this.
