### ISSUE TITLE
Followed Tags throws JS error

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#11158]
**Describe the bug**

When switching between tabs on home page, I've noticed there's a JS error in console.

**To Reproduce**

1. Go to dev.to
2. Open web inspector with console
3. Click through tabs on top of the feed.

**Expected behavior**

No JS error.

**Screenshots**

![image](https://user-images.githubusercontent.com/108287/97585937-f69d7f00-19f9-11eb-94b7-26c691248e5a.png)

**Comment by bntzio** [comment]
I don't see the error @ludwiczakpawel

**Comment by krzysiek1507** [comment]
Here is the fix https://github.com/forem/forem/pull/11054

**Comment by krzysiek1507** [comment]
Closed by #11054
