### ISSUE TITLE
Refactor: start using css variables for zIndex

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#11155]
We should move zIndexing over to css variables. This will make mass changes easier and also make zIndexing clearer for contributors

**Describe the solution you'd like**

Update the [variables file](https://github.com/forem/forem/blob/master/app/assets/stylesheets/config/_variables.scss) to be something like this.

```css
/////////////
// z index //
/////////////

--zi-app-bar: 100;
--zi-drawer: 300;
--zi-modal: 500;
--zi-snackbar: 700;
--zi-tooltip: 1000;
```

Work through all [existing](https://github.com/forem/forem/search?l=SCSS&q=z-index%3A) z-index references and update it to use a variable.

**Describe alternatives you've considered**

We don't do it

**Additional context**

https://github.com/forem/forem/pull/11132#issuecomment-717860314
https://github.com/forem/forem/pull/11132#discussion_r514088714

**Comment by ludwiczakpawel** [comment]
https://github.com/forem/forem/pull/11157
