### ISSUE TITLE
campaignmode-hackathon banner overflow on small screens

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#11156]
**Describe the bug**

On smaller screen `campaignmode-hackathon` goes off the end of the screen.
This problem is present on https://the.community.club/ but it has been fixed in https://community.snyk.io/

It looks like snyk removed the left right padding to solve this though adding box-sizing: border-box; would probably be a better solution.

**To Reproduce**

1. Go to https://the.community.club/ 
2. Shrink browser windows
3. See scroll bar

**Expected behavior**

The banner should not go over the edge of the screen

**Screenshots**

![mobile](https://user-images.githubusercontent.com/3534427/97565270-d65fc700-19dd-11eb-96b7-ec22ce715f8b.png)

![desktop](https://user-images.githubusercontent.com/3534427/97564802-08245e00-19dd-11eb-9768-2b8d514a97d8.png)

**Additional context**

I'm unsure if this is a Forem issue or a set up issue on the community club.

**Comment by AJuliette** [comment]
Maybe you could group this with this (older) issue ? https://github.com/forem/forem/issues/11100 It's on the width of the banner for different screens.

**Comment by ludwiczakpawel** [comment]
I don't think it's forem-specific issue since code for this banner is 100% custom. We don't provide (yet) any templates or "wrapper" for banners. We should though :).
