### ISSUE TITLE
Flag user is not visible in mobile version

### ISSUE THREAD

**Issue by Defman21** [forem/forem#11150]
**Describe the bug**

Mod panel is not scrollable thus the flag user action is not visible.

**To Reproduce**

1. Open dev.to in the mobile version. 
2. Press the mod button.

**Expected behavior**

All actions are visible.

**Screenshots**

<details>
<summary>Web App</summary>

![image](https://user-images.githubusercontent.com/7100645/97532106-b07af800-19c6-11eb-85e7-02a274ae3133.png)

</details>

<details>
<summary>Safari</summary>

![image](https://user-images.githubusercontent.com/7100645/97532359-38f99880-19c7-11eb-8143-cd9a5c5833e4.png)

</details>

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro
- OS, version: 14.0.1
- Browser, version: dev.to web app. Not reproducible in Safari.

**Comment by ludwiczakpawel** [comment]
This should be now fixed.
