### ISSUE TITLE
How long to receive a response?

### ISSUE THREAD

**Issue by darkogj** [forem/forem#11166]
Hey guys, I'm bootstrapping a community and seen that you don't recommend to self-host Forem right now. I submitted a post (asking for a "license") but haven't got a reply so far. Is it possible to speed things up? I have a Slack community approaching nearly 1000 members and want to slowly start migrating them to something like Forem.

**Comment by citizen428** [comment]
Thanks for the issue @darkogj, @pkfrank is the person to talk to for this, I assigned him here.

**Comment by pkfrank** [comment]
Hey @darkogj — followed up via email and will close this issue.
