### ISSUE TITLE
Documentation - Containers clarification regarding .env

### ISSUE THREAD

**Issue by kldickenson** [forem/forem#11163]
*Describe the bug**

https://docs.forem.com/installation/containers/

Need to clarify that an .env is required. My interpretation of the current wording is that is only needed if you are adding custom keys.

**To Reproduce**

Go to: https://docs.forem.com/installation/containers/

**Expected behavior**

N/A

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS, version: macOS Catalina 10.15.7
- Browser, version: N/A

**Additional context**
@cmgorton

**Comment by kldickenson** [comment]
I would be glad to take on this small issue. --Karen

**Comment by rhymes** [comment]
Thank you @kldickenson, I've assigned it to you!
