### ISSUE TITLE
Laporan bug

### ISSUE THREAD

**Issue by slotdepositviapulsa** [forem/forem#11173]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by citizen428** [comment]
Can you please fill in the issue template so we can help you? Otherwise, we'll have to close it due to lack of information.

**Comment by Link2Twenty** [comment]
Laporan bug means Report bug in Malay I think we can close this.
