### ISSUE TITLE
Two reply buttons in notifications, none working!

### ISSUE THREAD

**Issue by crimson-med** [forem/forem#11174]
**Describe the bug**

There are now two `reply` button in the notification and neither are working

**To Reproduce**

1. Go to `Notifications` through the bell in the top right
2. Find comment targeted to you
3. Two `reply` buttons are visible 
4. Click on either and nothing happens

**Expected behavior**

There should only be one button and clicking on reply opens up the reply box.

**Screenshots**

![Screenshot 2020-10-30 at 12 26 06 PM](https://user-images.githubusercontent.com/28290546/97659994-5bfd7880-1aab-11eb-8e9d-1b29d8f0e4c5.png)

What happens in network on click:

![Screenshot 2020-10-30 at 12 30 30 PM](https://user-images.githubusercontent.com/28290546/97660182-c7474a80-1aab-11eb-9d07-827ca3a0cb97.png)

**Video**

![Oct-30-2020 12-20-34](https://user-images.githubusercontent.com/28290546/97660015-6881d100-1aab-11eb-959b-eb73fb4c8a00.gif)

**Desktop (please complete the following information):**

- OS, version: MacOS Catalina
- Browser, version: Firefox, & Chrome 

**Additional context**

Tried on Firefox, Firefox Developer Edition and Chrome and all had the issue.

**Comment by ludwiczakpawel** [comment]
I think I've found the issue, working on the fix now. 

Thanks for reporting!

**Comment by madzadev** [comment]
I can confirm this 😉 Did not want to create a new issue, so I will just leave it here.
Also, it would be great if you could add some padding, and make like, save, and unicorn icons colorful again.
![chrome_WFsffR2SEJ](https://user-images.githubusercontent.com/42511917/97671832-a7a32880-1a91-11eb-827a-ce666929d67b.png)

**Comment by madzadev** [comment]
Yeah and comment notifications look like this, as OP mentioned 😉

![chrome_4OCiY37Rzm](https://user-images.githubusercontent.com/42511917/97672225-534c7880-1a92-11eb-9f5c-a35b8bef4257.png)

**Comment by ludwiczakpawel** [comment]
@madzadev can you try hit hard refresh / clear your cache?

**Comment by madzadev** [comment]
@ludwiczakpawel I did that before reporting here and it did not fix it 😉
Checked just now and the UI is ok, tho reply functionality is still down 😉

![chrome_nL8uO6ahwM](https://user-images.githubusercontent.com/42511917/97676983-3025c700-1a9a-11eb-8e61-f2c7b7c59b0e.png)

**Comment by madzadev** [comment]
![chrome_iHljNjEhLO](https://user-images.githubusercontent.com/42511917/97677370-d245af00-1a9a-11eb-865b-424cafc67c7f.png)

**Comment by rhymes** [comment]
Hi @madzadev, we're aware about the problem, we'll fix it as soon as possible, thanks for the info

**Comment by madzadev** [comment]
@rhymes Awesome! Good luck with it 😉

**Comment by crimson-med** [comment]
@ludwiczakpawel I dont think this is closed, the fix forces the appearance of two like icons and two save icons.
The design of the notifications is also now not spaced and padded


<img width="798" alt="Screenshot 2020-11-01 at 7 17 20 PM" src="https://user-images.githubusercontent.com/28290546/97801398-610f2300-1c77-11eb-9242-e2fc3f684660.png">

**Comment by rhymes** [comment]
@crimson-med have you tried to hard refresh your cache?
