### ISSUE TITLE
Add an option to "subscribe" to members posts

### ISSUE THREAD

**Issue by darkogj** [forem/forem#11171]
**Is your feature request related to a problem? Please describe.**
This is about motivating members to get more followers/subscribers.

It's so easy to extend this platform to be a mini Substack. Basically, add an option for members to not only follow, but "subscribe" to someone's post. If I like 4-5 people, I'd love to get a weekly digest of their posts. Or maybe an email immediately if someone posts.

**Describe the solution you'd like**

Add a "subscribe" option so people can subscribe to a member (the member could go as far as see the email of the person who subscribed, of course you'd make this very explicit).

**Describe alternatives you've considered**

There are currently no alternatives for this. This would be an extension that would turn Forem into an enhanced Substack alternative (each person would be his own publication.

**Comment by cmgorton** [comment]
Thank you for opening this request!

The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
