### ISSUE TITLE
Navigation overlapping content

### ISSUE THREAD

**Issue by ubaidisaev** [forem/forem#11222]
Start scrolling in order to see this problem. [https://docs.forem.com/installation/windows/](https://docs.forem.com/installation/windows/)
Same problem in similar pages.

**Screenshots**

![image](https://user-images.githubusercontent.com/38039843/97800388-ec6fc080-1c45-11eb-8868-e37e2a7597fe.png)
![image](https://user-images.githubusercontent.com/38039843/97800401-fc87a000-1c45-11eb-8060-140f4c28b752.png)

**Desktop (please complete the following information):**

- OS, version: Window 10
- Browser, version: Chrome 86

**Comment by citizen428** [comment]
Yes, this generally seems to be an issue, not related to any specific browser/OS combo. Thanks for the report!

**Comment by rhymes** [comment]
I believe this is similar to https://github.com/forem/forem/issues/6922 - right @ubaidisaev ?

**Comment by ubaidisaev** [comment]
@rhymes yeah.

**Comment by ubaidisaev** [comment]
> I believe this is similar to #6922 - I'm going to close this as a duplicate
> 
> can you confirm @ubaidisaev ?

Yeah it's duplicate
