### ISSUE TITLE
Quick follow option

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#1122]
When you hover over a users profile picture, be it in the comments or when looking at articles, it would be nice to see a small amount of information about the user and have an option to follow them.

![twitter-mini-profile](https://user-images.githubusercontent.com/3534427/48545316-8903f100-e8bd-11e8-9916-3c476fe7ee83.png)

**Comment by maestromac** [comment]
I really like this idea @Link2Twenty ! Thanks for the issue.

**Comment by Link2Twenty** [comment]
I was planning on making a quick mock-up so someone could easily implement this but discovered a bunch of `overflow: hidden` and `float: left` type stuff which is a minefield for new people so I've made a mockup using flexbox.

It also has some code in there for quick follow, it's just a mock-up so we'll need some design direction.

http://jsfiddle.net/link2twenty/s4tok56L/

**Comment by maestromac** [comment]
not stale

**Comment by jessleenyc** [comment]
For anyone who wants to tackle this, please let us know what you're thinking design-wise!

**Comment by Link2Twenty** [comment]
I'm closing this as it appears to have been superseded by #4745
