### ISSUE TITLE
sidebar overlap - z-index - crayons header dropdown menu

### ISSUE THREAD

**Issue by jmau111** [forem/forem#11236]
**Describe the bug**

**When logged in and in desktop mode**, if you set "Site Navbar" setting to  "Static top of page", the dropdown menu has a wrong display.

**To Reproduce**

1. Go to settings UX
2. Set  Site Navbar to "Static top of page"
3. Hover the header settings dropdown menu
4. See error when on a profile page or an article page

The bug does not affect the home page.

**Expected behavior**

The dropdown menu should be on top of sidebar

**Screenshots**

![](https://user-images.githubusercontent.com/6878027/97909561-b6ffcb80-1d48-11eb-98ea-2449f3ceb81c.jpg)
![](https://user-images.githubusercontent.com/6878027/97909563-b830f880-1d48-11eb-9400-3d5c2643792e.jpg)
![](https://user-images.githubusercontent.com/6878027/97909571-b9622580-1d48-11eb-9194-2c078b8d7530.jpg)

![](https://user-images.githubusercontent.com/6878027/97909619-d26ad680-1d48-11eb-8df8-2c4ca8f2faaa.jpg)

**Desktop (please complete the following information):**

- OS, version: mac, windows, linux
- Browser, version: chrome, edge, firefox, firefox dev, opera

**Comment by fdoxyz** [comment]
cc @ludwiczakpawel as this may be an edge case related to the recent z-index refactor
