### ISSUE TITLE
Listing modal does not show tags when refreshed

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#11231]
**Describe the bug**

Listing modal does not show up the tags in the listing always

**To Reproduce**
1. Go to https://dev.to/listings
2. Click on a listing with tags. It will open up a modal and it will show the tags
3. Now refresh the page
4. The modal will show up but without tags

**Expected behavior**

Tags in the listing modal should always be displayed

**Screenshots**
![listing_modal](https://user-images.githubusercontent.com/8092120/97883609-18289e80-1d4b-11eb-90d0-9d1ff4371664.gif)

**Desktop:**

- OS, version: Ubuntu 20.04
- Browser, version: Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)

**Additional context**

This bug is happening because elastic search mapping uses **tags** for listing tags (https://github.com/forem/forem/blob/master/config/elasticsearch/mappings/listings.json#L70)  while the API returns **tag_list** for listing tags. This could be fixed by renaming one of those to match the other.

**Comment by Rafi993** [comment]
Hello there if this bug is not taken I would like to help

**Comment by rhymes** [comment]
Go ahead @Rafi993 and thanks again! :D

**Comment by Rafi993** [comment]
Thank you @rhymes

**Comment by Rafi993** [comment]
other than renaming keys in elastic search to match API another way to fix this bug might involve changing **TagLinks** component used in https://github.com/forem/forem/blob/master/app/javascript/listings/singleListing/Header.jsx#L34

```javascript
      <TagLinks tags={listing.tags || listing.tag_list} onClick={onAddTag} />
```

this might not be an ideal solution.

**Comment by Rafi993** [comment]
> other than renaming keys in elastic search to match API another way to fix this bug might involve changing **TagLinks** component used in https://github.com/forem/forem/blob/master/app/javascript/listings/singleListing/Header.jsx#L34
> 
> ```js
>       <TagLinks tags={listing.tags || listing.tag_list} onClick={onAddTag} />
> ```
> 
> this might not be an ideal solution.

Should I fix this issue by renaming keys in elastic search (I'm not sure if the different key names was intented) or should I make the above change in the frontend to fix this any thought on this @forem/oss ?

**Comment by mstruve** [comment]
I dont understand why we would have to change the keys in elasticsearch since we have `tags` and `tags` is what we are using in the javascript.

With that said I think your solution with the `||` would suffice.
