### ISSUE TITLE
image upload on reply comments

### ISSUE THREAD

**Issue by equiman** [forem/forem#1123]
**Describe the bug**
1. Link on Image upload icon is not clickable on all image, right side is not covered. Affects desktop and mobile
2. When upload image, can't select url on input-box, so can't copy URL to use it on comment.
3. On mobile devices when image upload input-box is visible cancel button is using same space as cancel button. Then if you try select image, there is no way to not click cancel button. Related to #188  issue.

**To Reproduce**

1. Open post
2. Go to comment
3. Click reply button
4. Try click upload image

**Expected behavior**
When click on any part of upload image button, works.

**Screenshots**
![button](https://user-images.githubusercontent.com/933393/48558427-450ded80-e8b7-11e8-8ef8-34eda34da440.gif)
![inputbox](https://user-images.githubusercontent.com/933393/48558591-a635c100-e8b7-11e8-9849-d984e93ebfed.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 70.0.3538.102 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Maybe a better site to image input-box it's down action buttons. I think.

**Comment by RDumais** [comment]
I have encountered the same problem yesterday on Windows 7 Enterprise and on Chrome Version 70.0.3538.102 (Official Build) (64-bit).

**Comment by maestromac** [comment]
Thank you for reporting this issue @equiman & @RDumais .

**Comment by Link2Twenty** [comment]
I think this problem is caused, mainly, by the `.actions` class being used to describe the container for the new comment and well as the container for the reply actions.

Which leads to those buttons having a greater width than they require. That being said you can fix the problem by adding a couple of lines of CSS
```CSS
.single-comment-node .reply-actions {
  margin-left: auto;
  width: auto;
  padding: 4px 12px 0 0;
  display: inline-block;
}
```
It just feels a little hacky to me, I feel like the `.actions` class shouldn't be used to describe both containers.

**Comment by jessleenyc** [comment]
In general, it's hard getting to this link on mobile regardless. @benhalpern what do you think about moving the generate link below the buttons?

**Comment by benhalpern** [comment]
Yeah I think that makes sense.

Across the board, buttons/fields need to be bigger and more differentiated on mobile.

**Comment by maestromac** [comment]
not stale

**Comment by rhymes** [comment]
The quickest fix, keeping the current HTML is the following:

```diff
diff --git a/app/assets/stylesheets/comments.scss b/app/assets/stylesheets/comments.scss
index bd6b580a..34ffeb96 100644
--- a/app/assets/stylesheets/comments.scss
+++ b/app/assets/stylesheets/comments.scss
@@ -871,6 +871,7 @@ a.header-link {
     text-align: left;
     .uploaded-image {
       width: calc(93% - 54px);
+      z-index: 6; // it has to be 1 more than .actions
     }
     .image-upload-button {
       padding: 5px 2px 0px;
```

by adding a `z-index` that's 1 unit more than the `.actions`'s `z-index` the URL becomes selectable again. 

I tested it with Firefox and Chrome and it works

**Comment by catalinpit** [comment]
@rhymes if you want, I can make that change. :-)

**Comment by rhymes** [comment]
Hi @catalinpit, thanks for volunteering! It makes sense, though this is quite an old issue so my "quick fix" might not apply anymore.

pinging @ludwiczakpawel for confirmation on the right approach

**Comment by Link2Twenty** [comment]
@rhymes this is resolved.

**Comment by ludwiczakpawel** [comment]
Yeap, this is solved.
