### ISSUE TITLE
Editing old posts doesn't use current Editor Style

### ISSUE THREAD

**Issue by miku86** [forem/forem#11247]
Hey there,

I don't know if this is a bug or a feature, but it seems to be more like a bug.
I searched in the other issues, but couldn't find something similar.

**Describe the bug**

I wrote a post with the new Rich Editor after changing it in the settings.
I don't like it, so I want to go back to the old Editor.
So I changed this in the settings.
This works, new posts use the old Editor.
BUT: the one post I created with the new Rich Editor is only editable with the new Rich Editor, although I changed the settings back to the old Editor.
This goes in both directions, so a post created with the old Editor is only editable with the old Editor.

Expected: I want the Editor to be the Editor I currently have set in the settings, not the one that was set back when I originally created the post.

**To Reproduce**

1. Create a new post
1. Change Editor to the one currently not used for the creation of the post.
1. Try to edit the post.
1. The Editor you used to write the post shows up

**Expected behavior**

I want the Editor to be the Editor I currently have set in the settings, not the one that was set back when I originally created the post.

**Screenshots**

![Screenshot](https://i.imgur.com/fOSR7jj.png)

**Desktop (please complete the following information):**

- OS, version: Arch Linux 5.4.74-1-lts
- Browser, version: Firefox 83.0b7, extensions disabled

**Additional context**

I removed the Service Worker manually, but this doesn't change the problem.

**Comment by rhymes** [comment]
Hi @miku86, this is actually a feature, posts are tied to the version of the editor they were initially created with. The reason being that the newer editor doesn't support the front matter and each and every possible combination of its options.

Closing this and referring you to https://github.com/forem/forem/issues/6763 which is a feature request to allow the switch between versions

Thank you for bringing this up!
