### ISSUE TITLE
non-social login form gone (dev.to)

### ISSUE THREAD

**Issue by c33s** [forem/forem#11269]
last time i logged into dev.to i noticed that it is alread possible to login with a local email and password (refs: #242), which is awesome.
i set a password and disconnted my github account. it works like charm. today i wanted to login to dev.to  and there where no email and password fields, they where gone. 

it's quite uncool that you require me to connect my github account again to login after i setup a password. please keep the local login.

**Comment by Zhao-Andy** [comment]
Hi @c33s, sorry for that. We disabled it by accident. You should be able to login via email again!

**Comment by c33s** [comment]
@Zhao-Andy  again a "mistake"?

![image](https://user-images.githubusercontent.com/649209/99185617-56f72500-274b-11eb-8b9f-a411bbd5c44e.png)

**Comment by Zhao-Andy** [comment]
Thanks for the catch, we've resolved it again. 👍
