### ISSUE TITLE
Redirects sometimes lead to styling and loading errors

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#11270]
**Describe the bug**
When clicking a link that will redirect to a new page, the redirect sometimes misbehaves. My guess is that there is some caching involved, most likely from service workers. I believe that when the page is cached by service worker, and then the page is made into a redirect (changing your username or your organization's username/slug for example), the service worker sends a cached version of the page instead of following the redirect.

**To Reproduce**
In development:

1. Run `bin/startup` (you'll need background jobs running for this)
2. Create an organization: localhost:3000/settings/organization/new
3. Make a post under the organization: localhost:3000/new
4. Copy and paste the article link, or leave a comment under your article with it
5. Update your organization's `slug` or `username` to something else: localhost:3000/settings/organization
6. Wait for background jobs to complete
7. Visit the old article link
8. See that the page "breaks", for example:
![Screen Shot 2020-11-04 at 9 47 19 AM](https://user-images.githubusercontent.com/17884966/98126030-1eba3180-1e83-11eb-8b63-fd33f2aaef0d.png)

**Expected behavior**
Best solution is probably having the service worker know to redirect properly, instead of rendering a cached version. If not, rendering the navbar or "shell" properly is the next best solution.

**Comment by AJuliette** [comment]
I think this might be a duplicate of this issue, someone is working on it: https://github.com/forem/forem/issues/11205

**Comment by rhymes** [comment]
@AJuliette It might very well be that the fix for one will solve the others but I'm unsure so I'll keep the issue open in the meantime. Thanks for investigating!

**Comment by mstruve** [comment]
@Zhao-Andy we recently removed the majority of our Service Worker caching in #12834 which I believe should solve this problem. Any chance you can re-test it with the most recent code?

**Comment by Zhao-Andy** [comment]
This seems to be resolved mostly, but one thing I noticed is that going to the old link doesn't redirect. Instead the service worker is showing the cached content. That's probably not the appropriate routing we want, but IMO is a separate issue. Going to close this since the original issue is resolved. :)
