### ISSUE TITLE
PWA : Shortcuts menu

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#11287]
**Is your feature request related to a problem? Please describe.**

Add shortcuts to add rapidity and efficacity for view a page with less effort. 

https://web.dev/app-shortcuts

Example : 
![app-shortcuts-menu-android.png](https://user-images.githubusercontent.com/14293805/98275442-e9056d80-1f94-11eb-9e1b-1b653caae525.png)

**Describe alternatives you've considered**
/ 

**Additional context**

❤️ Open source and Forem Team ✨

**Comment by rhymes** [comment]
Closing this as a duplicateof https://github.com/forem/forem/issues/10009 - thank you @thomasbnt!

**Comment by thomasbnt** [comment]
Aarg so sorry for a another duplicate issue 😅
