### ISSUE TITLE
Resolve deprecation warning

### ISSUE THREAD

**Issue by citizen428** [forem/forem#11282]
Ruby 2.7.2 disables deprecation warnings:

> This release contains intentional incompatibility. Deprecation warnings are off by default on 2.7.2 and later. You can turn on deprecation warnings by specifying the` -w` or `-W:deprecated `option at the command-line.
https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/

We currently go with this default both in local development as well as CI, but we should address these warnings eventually. The best way to do this is to create a new branch, run the specs with `RUBYOPT="-W:deprecated" bundle exec rspec` and address them one by one. 

This issue would be good for potential contributors who already know enough Ruby to make sense of the deprecation warnings but don't have much experience with the Forem codebase yet.

**Comment by mstruve** [comment]
Given we are looking at upgrading to Ruby 3.0 I thought this would be a good issue to finally squash.
