### ISSUE TITLE
Filter Mod Center by following tags

### ISSUE THREAD

**Issue by eusonlito** [forem/forem#11300]
**Is your feature request related to a problem? Please describe.**

Today my status was upgraded to "trusted"  🥳 🥳

I'm excited with my new status, I have reported a dozens of SPAM posts and is great that I can moderate by myself to clean dev.to spammers.

But... I'm subscribed to `php` and `laravel` tags, and my browser bookmark is https://dev.to/t/php/latest

The problem is that the mod center there are hundred of posts not related with my skills or interests and I can not filter posts by my subscribed tags, then, the mod center is not useful for me on any way.

**Describe the solution you'd like**

On mod center, add a input search (to direct search for spam words) and a selector to filter for tags, loaded by default with following tags.

**Comment by Glennmen** [comment]
This please! I do not feel confident enough to moderate post quality of technologies that I am not experienced in.

Also same for languages, I don't think I can moderate a post that is in Spanish for example.

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
