### ISSUE TITLE
Android app is broken

### ISSUE THREAD

**Issue by gautamkrishnar** [forem/forem#11305]
**Describe the bug**
Android app of dev.to is broken

**To Reproduce**
Download fresh app from the play store, open it.

**Expected behavior**
App should work properly

**Screenshots**
![Screenshot_20201107-180728.jpg](https://user-images.githubusercontent.com/8397274/98441460-71664880-2124-11eb-9c3a-2d44bbb6b549.jpg)

**Smartphone (please complete the following information):**

- Device: OnePlus 6T
- OS, version: Android 10
- Browser, version: n/a

**Additional context**

**Comment by rhymes** [comment]
Hi @gautamkrishnar, thanks for the report, as this pertains mainly to the Android app for DEV, would you be willing to open this issue on the repo for the app? https://github.com/thepracticaldev/DEV-Android - Thank you!

**Comment by gautamkrishnar** [comment]
@rhymes Moving to https://github.com/thepracticaldev/DEV-Android/issues/105
