### ISSUE TITLE
Repositioning article's header image after upload

### ISSUE THREAD

**Issue by madzadev** [forem/forem#11335]
**Is your feature request related to a problem? Please describe.**

Beginner users might have trouble selecting the right aspect ratio images for their article headers. Currently, the positioning is done automatically, leaving no margin for any errors and options to fix it.

**Describe the solution you'd like**

It would be nice if the users would be able to reposition the image after upload. Currently, Twitter and lots of other sites use this.

**Describe alternatives you've considered**

A quick alternative would be to mention what is the optimal resolution of the image to upload or the aspect ratio to be used somewhere in the upload image pop up window.

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
