### ISSUE TITLE
onboarding page (/onboarding) has links that cant be opened in new windows

### ISSUE THREAD

**Issue by HighPlainsCoder** [forem/forem#11346]
**Describe the bug**

When on https://forem.dev/onboarding?referrer=https://forem.dev/ and trying to open either "Terms and Conditions" or "Code of Conduct" links in new tabs/windows, those new tabs get redirected back to https://forem.dev/onboarding

**To Reproduce**

1. go to forem.dev
2. create a new account
3. on the "onboarding" page that comes right after account creation, open either link in a new window (right-click or control-click depending on os and settings, and select "open in new window" from the menu)

**Expected behavior**

a new windows opens with the "/terms" or "/code-of-conduct" page on it.

** actual behavior **

those pages open, and very quickly redirect back to "/onboarding"

**Desktop (please complete the following information):**

- OS: macos Catalina, and Windows 10
- Browser, version: Firefox 82, Safari 14

**Smartphone (please complete the following information):**

(I failed to test on any smartphones or tablets. Given the nature of the issue, Im confident they behave the same )

**Comment by Link2Twenty** [comment]
Ctrl click doesn't open these links in a new tab, on windows, but perhaps it should?

Detecting ctrl in the handleShowText before preventing defaults would fix that minor side issue.

https://github.com/forem/forem/blob/a7938ed287899840238beb55b65ad481bb92c4a7/app/javascript/onboarding/components/IntroSlide.jsx#L54-L57

**Comment by HighPlainsCoder** [comment]
I have retested, and the bug is gone!

good work, everyone
