### ISSUE TITLE
Move away from gitdocs as documentation server

### ISSUE THREAD

**Issue by abenettt** [forem/forem#11352]
**Is your feature request related to a problem? Please describe.**
Currenlty `gitdocs` is used to host and generate the documentation, but the project has been long abandoned, the repository has been archived and there has been no update in two years. 

**Describe the solution you'd like**
Moving to another documentation solution like for example [`docosaurus`](https://docusaurus.io/)
[v1](https://docusaurus.io/docs/en/installation) could be used if internationalization is a concern for the documentation, otherwise [v2](https://v2.docusaurus.io/docs/) might even be used, which is currently in alpha.

**Describe alternatives you've considered**

**Additional context**
The move to a separate repo for documentation in #11285 sparked this line of thought.

**Comment by rhymes** [comment]
Hi @abenettt, thanks for surfacing this issue, we're aware of it and even discussed it in here https://github.com/forem/forem/issues/6922 and internally briefly. An alternative to docusaurus could be https://www.gitbook.com or even using [Hugo](https://gohugo.io/) and a template

**Comment by mstruve** [comment]
Hey @abenettt! Thanks for the issue! I am actually going to close this since the idea is being addressed  #11285 and we want to try and keep all the doc discussion in one place. Thanks for being a great part of the Forem community!
