### ISSUE TITLE
Add throttling for non-admin chat channel creation

### ISSUE THREAD

**Issue by citizen428** [forem/forem#11351]
As discussed in #9741 we want to rate limit chat channel creation for non-admin users. [This comment](https://github.com/forem/forem/pull/9741#issuecomment-724392842) by Molly provides more context:

1. Previous PR that added throttling for a user action: #7832
2. File to edit: [rate_limit_checker.rb](https://github.com/forem/forem/blob/master/app/services/rate_limit_checker.rb)

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
