### ISSUE TITLE
Keyboard navigation on feed requires hitting "return" twice to access an article

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#11372]
**Describe the bug**

When navigation through feed with keyboard (`j` & `k`) I have to press `return` twice to access selected article... However the first press activates the progress bar on top of the header.

**To Reproduce**

1. Go to home page
2. Press `j` and/or `k` to select random article on feed.
3. Press `return` - it will activate the progress bar on top of the page but it will not take you to the article itself.
4. Press `return` again - it will now take you to the selected article.

**Expected behavior**

Take me to the article on first `return` press.

**Desktop (please complete the following information):**

- OS, version: macOS X 10.15.7
- Browser, version: Chrome 86.0.42x

**Comment by reobin** [comment]
I have noticed that issue for quite some time using tab navigation, but I thought it was a bug with my browser's config.

It happens pretty much on any page for me. Here is an example on the dashboard:
![demo](https://user-images.githubusercontent.com/5920450/98803624-0b5b1900-23e3-11eb-894c-ac9d5de21995.gif)

**Comment by nickytonline** [comment]
I'll take a peek at this today.

**Comment by rhymes** [comment]
@nickytonline it looks like @reobin already submit a PR https://github.com/forem/forem/pull/11377
