### ISSUE TITLE
Improve date/time picker on /admin/events/new

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11392]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin creating events, it's frustrating to use the current date/time picker on `/admin/events/new`.

**Describe the solution you'd like**
An updated interface for choosing the start/end time of events.

**Additional context**
We haven't given this area of the `/admin` section too much love recently, so it's understandable that this hasn't been a priority.

Screenshot of the current system:
![current date and time picker](https://p241.p3.n0.cdn.getcloudapp.com/items/5zuwxgkn/Image%202020-11-12%20at%2010.44.58%20AM.png?v=a7a479a222ba2226b315e56e8479e55c)

**Comment by dominicduffin1** [comment]
I'd be interested in taking this one. Do you have any specific ideas on what changes you want to see or are you looking for the contributor to come up with improvements?

**Comment by juliannatetreault** [comment]
Hey, @dominicduffin1 - apologies for the delayed response! 

Thank you for offering to take on this issue -- I'd be happy to assign it to you! As far as ideas on changes go, maybe we could update the date/time picker on `/admin/events/new` to be similar to the date/time picker on `/admin/articles/` or `/admin/sponsorships/:id/edit` (please refer to the screenshot below!). I've cc'd our design team and @pkfrank on this to provide some further direction. 😄 
![Screen Shot 2020-12-16 at 11 57 54 AM](https://user-images.githubusercontent.com/32834804/102394130-83929c80-3f96-11eb-86fa-cc2615fa071a.png)

cc @ludwiczakpawel, @lisasy, @pkfrank

**Comment by dominicduffin1** [comment]
Thank you @juliannatetreault

**Comment by lisasy** [comment]
Hi @dominicduffin1,

Thanks for expressing interest in working on this issue. Here is documentation on how you can implement the correct styling by applying the CSS class name `crayons-select` to the `select` element. Let me know if you have any questions or comments. 🙂

<img width="879" alt="Screen Shot 2020-12-16 at 2 19 20 PM" src="https://user-images.githubusercontent.com/816402/102413473-d295fd00-3fa9-11eb-809b-a50c991e359c.png">

**Comment by ludwiczakpawel** [comment]
For future reference: we could probably use `<input type="datetime-local" />` instead of multiple selects here.
