### ISSUE TITLE
Add "Suggested Tags" to the "Onboarding" Section in SiteConfig

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#11395]
**Is your feature request related to a problem? Please describe.**
Currently, an Admin is only able to define "Suggested Tags" in the "Get Started" section of the SiteConfig. It would be ideal if Admins could also define "Suggested Tags" for the onboarding flow in the "Onboarding" section of the SiteConfig.

**Describe the solution you'd like**
Adding a "Suggested Tags" section to the SiteConfig (SiteConfig -> Onboarding), giving Admins the ability to suggest tags for users to follow during the onboarding flow.

**Additional context**
This pattern currently exists for "Suggested Users" -- an Admin is able to add suggested users in both the "Get Started" and the "Onboarding" sections of the SiteConfig. "Suggested Users" would be a great example of how to implement "Suggested Tags" in the "Onboarding" section of the SiteConfig (please refer to the screenshots below for further context!). 

**The "Get Started" section of the SiteConfig that contains "Suggested Tags"**:
<img width="984" alt="Screen Shot 2020-11-12 at 4 27 35 PM" src="https://user-images.githubusercontent.com/32834804/99008996-705a6000-2504-11eb-8fb6-cab81f805cf7.png">

**The "Onboarding" section of the SiteConfig that only contains "Suggested Users," but should also contain "Suggested Tags"**:
<img width="947" alt="Screen Shot 2020-11-12 at 4 24 14 PM" src="https://user-images.githubusercontent.com/32834804/99009102-aa2b6680-2504-11eb-80b4-04553f3ebee8.png">

**Comment by cmgorton** [comment]
@juliannatetreault do you think we should label this as a potential RFC?

**Comment by juliannatetreault** [comment]
> @juliannatetreault do you think we should label this as a potential RFC?

Yes, I think this could make a great RFC! Great suggestion, @cmgorton!

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
