### ISSUE TITLE
bug: Very wide code blocks overflow in comment preview

### ISSUE THREAD

**Issue by reobin** [forem/forem#11402]
**Describe the bug**

The comment preview with a code block that is very wide overflows.

**To Reproduce**

Example code block:
```js
function square(value) {
  if (value === 4) {
    return 4 + 4 + 4 + 4;
  }
  if (value === 16) {
    return 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16 + 16;
  }
  if (value === 51) {
    return 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51 + 51;
  }
}
```

1. Go on an article
2. Copy in a comment the example code block above inside a markdown code block
3. Check out the comment preview
4. Notice it overflows

**Expected behavior**

It scrolls horizontally just like it does once the comment is posted.

**Screenshots**

![demo](https://user-images.githubusercontent.com/5920450/99082844-b100ba80-2592-11eb-82ea-c3741a6f1f5c.gif)

It also happens on the article page:

![Screen Shot 2020-11-13 at 09 32 01](https://user-images.githubusercontent.com/5920450/99083149-1f457d00-2593-11eb-9d2d-5458161eecb9.png)

**Desktop (please complete the following information):**

- OS, version: macOS Catalina
- Browser, version: Chrome 86

**Comment by yogeshktm** [comment]
i would like to fix this issue like this 

![image](https://user-images.githubusercontent.com/3961774/103616396-6415e080-4f52-11eb-8628-12fcb2d02df3.png)

Code change required 
`
div.highlight .highlight{
white-space:pre-wrap
}` 

if you think this is fine. you can assign this to me. i will take it up as my first contribution in dev.to

**Comment by nickytonline** [comment]
@yogeshktm, thanks for wanting to tackle this issue. Modifying the white space is not the direction we're looking for for this fix. We're looking for the same behaviour for a code snippet in the body of a post, i.e. scrolling.

https://user-images.githubusercontent.com/833231/103707728-309c7b80-4f7d-11eb-8375-4c45fefe4fe6.mp4

Having said that, I still think this would be a great first issue for you. Let us know if you'd still like to work on it with the proposed fix.

**Comment by yogeshktm** [comment]
yes i would like to work on this. Please assign

In case of clarifications i will check with you @nickytonline 

Thanks

**Comment by yogeshktm** [comment]
Team, @nickytonline 

i have found `overflow-x:auto` is missing in the parent elements would have cause this issue. as far as my investigation we need below code changes to fix this issue. 

```
.comment-form.preview-open,.comments-container,.comment-form__inner{
   overflow-x:auto;
}
```

![image](https://user-images.githubusercontent.com/3961774/103795848-800da500-506c-11eb-9c83-556540a12033.png)

i tried finding scss related to these changes in the repository but i can't able to find scss files related to these. i am very new here. can anyone help me on guiding me to find the scss or is there any other way to add styles here ?

Thanks in advance.

**Comment by nickytonline** [comment]
@yogeshktm, thanks for investigating. Feel free to put up a pull request and we can continue the discussion in there.
