### ISSUE TITLE
My codepen in Google chrome is not working properly 

### ISSUE THREAD

**Issue by anandsoni143** [forem/forem#11401]
**Is your feature request related to a problem? Please describe.**

![Screenshot (551)](https://user-images.githubusercontent.com/47745941/99062878-a9a8d380-25c9-11eb-97ef-4930c63b544e.png)

**Comment by rhymes** [comment]
@anandsoni143 could you provide us with further details? Which post? Which version of Google Chrome? Thanks

**Comment by Link2Twenty** [comment]
> @anandsoni143 could you provide us with further details? Which post? Which version of Google Chrome? Thanks

The shared images isn't related to a dev post, or a specific browser, but actually looks like codepen was giving a 503 (Service Unavailable) for SVGs and images.

**Comment by rhymes** [comment]
Ah ah thanks for noticing @Link2Twenty, I'm going to close this as it's unrelated to Forem
