### ISSUE TITLE
Add Twitter and GitHub URLs in the Links Section of Settings

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#11404]
**Is your feature request related to a problem? Please describe.**

As a user of a Forem without GitHub/Twitter OAuth enabled, I'm unable to add my social profiles links via the links section in `/settings/profile`.

**Describe the solution you'd like**

I'd like to have available inputs for Twitter and GitHub URLs in the Links section.

**Describe alternatives you've considered**

I originally thought it might be best to only offer the ability to input these links when Twitter and GitHub 0Auth methods are turned off, this way it would encourage folks to 0Auth their accounts which has other benefits.

BUT, not everyone wants to 0Auth their Twitter or GitHub accounts on DEV, so I think it'd be best to offer the opportunity for folks to input these as basic links without using 0Auth (see https://github.com/forem/forem/issues/9646).

**Additional context**

There's also a super cool suggestion here - https://github.com/forem/forem/issues/9220#issuecomment-669632071 to reduce the link inputs to just a single input box this way the page isn't super long.

**Comment by rhymes** [comment]
Adding this as it's related https://github.com/forem/forem/issues/9646

+1 on the idea of decoupling authentication needs from online presence and profile :)

**Comment by rhymes** [comment]
Adding a related issue https://github.com/forem/forem/issues/11717

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
