### ISSUE TITLE
Add Accessibility prompt to GitHub PR template

### ISSUE THREAD

**Issue by marcysutton** [forem/forem#11406]
**Is your feature request related to a problem? Please describe.**

There's a really cool [PR template](https://github.com/forem/forem/blob/master/.github/PULL_REQUEST_TEMPLATE.md) in this project, for example how it prompts contributors about documentation and tests. It would be even cooler if it had a prompt for accessibility if the PR has UI-related changes!

**Describe the solution you'd like**

Add a mention of accessibility in the template, pointing to a more in-depth resource on the [Forem contributing docs](https://docs.forem.com/contributing/docs/).

**Describe alternatives you've considered**

I wouldn't recommend the alternative of not adding anything.

But I am considering whether to make a whole heading about accessibility or something else. I could see including a heading like "Updating UI?" and then writing something about accessibility, and anything else you'd want contributors to know like updating a design system.

**Comment by nickytonline** [comment]
I think this is great! Just pinging @forem-team to give everyone visibility on this.
