### ISSUE TITLE
Remove <social provider>_created_at field from user table

### ISSUE THREAD

**Issue by abenerd** [forem/forem#11414]
**Is your feature request related to a problem? Please describe.**
Not a problem perse but unnecessary data. The `user` table has fields like `github_created_at` or `facebook_created_at`, those are fields that indicate when these accounts have been linked to the user, this information is also available in the `identities` table under the `created_at` field. 

**Describe the solution you'd like**
Removing fields such as `github_created_at` and `facebook_created_at` from the user table and using the `created_at` field in the `identities` table. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
@abenettt nice find! they could be replaced by helper methods instead of being stored, we'd potentially lose the ability to easily sort users by those fields but we're not using it AFAIK

**Comment by mstruve** [comment]
This looks to only be used in 2 places so I think removing it and not having to worry about keeping it synced would be a win. Plus it would remove a very niche column from the user
```
/Users/mollystruve/forem/app/black_box/black_box.rb:
   66      def social_auth_registration_recent?(user)
   67        # was the social auth account created very recently?
   68:       social_auth_date_plus_two_days = ((user.github_created_at || user.twitter_created_at || 3.days.ago) + 2.days)
   69        user.registered_at < social_auth_date_plus_two_days
   70      end

/Users/mollystruve/forem/app/controllers/admin/feedback_messages_controller.rb:
   19  
   20        @possible_spam_users = User.registered.where(
   21:         "github_created_at > ? OR twitter_created_at > ? OR length(name) > ?",
   22          50.hours.ago, 50.hours.ago, 30
   23        )
```

**Comment by citizen428** [comment]
@mstruve Just to make sure we're on the same page: you want all 4 columns gone, plus the two usages above, plus all the code from `app/services/authentication` that sets the timestamps, correct?

**Comment by mstruve** [comment]
Correct! It's redundant data that doesn't really serve any purpose being on the user so lets ✂️
