### ISSUE TITLE
Indicate required fields on /podcasts/new

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11433]
**Is your feature request related to a problem? Please describe.**
As a user submitting a podcast for consideration, it's not clear which fields on `/podcasts/new` are required.

**Describe the solution you'd like**
Required fields are marked with an asterix symbol or similar (required) flair.

**Additional context**
Here's a live example of the page: `https://dev.to/podcasts/new`

**Comment by akashdotsrivastava** [comment]
@rhymes Hi. I'd like to give this a shot if that's okay.

**Comment by rhymes** [comment]
@akashdotsrivastava yes, thank you!

**Comment by joaoGabriel55** [comment]
I can work on that @pkfrank
