### ISSUE TITLE
More descriptive looking for work. 

### ISSUE THREAD

**Issue by jonathan-s** [forem/forem#11437]
**Is your feature request related to a problem? Please describe.**

I want other people to know what kind of work I'm looking for so that I don't waste other people's time. 

**Describe the solution you'd like**

Right now when people see a post and see my profile next to it it looks like this. 
<img width="337" alt="Screenshot 2020-11-16 at 12 07 26" src="https://user-images.githubusercontent.com/2124818/99245878-a4839880-2804-11eb-8bbf-c89159877548.png">

I would like a short description of what kind of work I'm looking for. In fact there is a field called "Available for" in settings that I would like to be there as a qualifier. 

Similarly on the profile it's easy to miss what kind of work I'm looking for. 
<img width="987" alt="Screenshot 2020-11-16 at 12 11 47" src="https://user-images.githubusercontent.com/2124818/99246041-edd3e800-2804-11eb-823b-fe1f78aae2e7.png">

Perhaps some kind of drop down that qualifies what work I'm looking for to display the information from "Available for".

**Comment by cmgorton** [comment]
@lisasy @vaidehijoshi any thoughts on whether this type of feature is something we will consider for Forem?

**Comment by lisasy** [comment]
@cmgorton With the way we've done profile generalization, we're enabling admins to create new form fields like this. 

For DEV specifically, this is a chance for our internal admin team to set this form field. I think this is a cool idea and am curious what @vaidehijoshi thinks as well.

**Comment by vaidehijoshi** [comment]
@cmgorton + @lisasy Currently, the whole concept of `looking_for_work` is a _very_ DEV-specific concept, and isn't very extensible to any other current/future Forem instances, which is a pattern that we don't want to double down on.

This topic actually came up recently in some work that @citizen428 did to remove the autofollowing hiring tag in https://github.com/forem/forem/pull/11722. We had a discussion around this in https://github.com/forem/InternalProjectPlanning/issues/366, and ultimately agreed to deprecate the `looking_for_work` feature and will advise current DEV users who are using this feature to update their profiles with their "looking for work" status. We plan to announce this change to users in the form of [a newsletter](https://github.com/forem/InternalProjectPlanning/issues/366#issuecomment-749637592)

I agree that there is definitely value in having _some_ kind of "available to hire" feature for the DEV instance (maybe something like a job board down the road?), but we need to make sure that adding a field like that to the profile works with our new `ProfileFields` feature, which allows Forem admins to create flexible fields for a user's profile, and which will ultimately be more extensible across _all_ Forems.

I think that we'll want to think about this kind of feature [much more critically](https://github.com/forem/InternalProjectPlanning/issues/366#issuecomment-735890212) in terms of the Foremverse.

I hope that all of this additional context is helpful! :)

**Comment by ludwiczakpawel** [comment]
Closing this because we no longer have this field in codebase. Also +1 to what @vaidehijoshi said above.
