### ISSUE TITLE
Give Forem Admin Ability to Customize Emojis in Dropdown Display URLs

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#11449]
**Is your feature request related to a problem? Please describe.**

As a Forem Admin, I'm unable to change the emojis that appear in the display URLs for key pages of the site  — i.e. these emojis: "👨‍💻👩‍💻 " that are visible beside the page name of the URL for many DEV pages. (See image under "Additional Context" for more clarification.)

**Describe the solution you'd like**

As a Forem Admin, I'd like to be able to choose the emojis to be placed in these URLs — I think by default these emojis should be turned off. This option should most likely live in `admin/config` > Community Content.

IF we could allow Forem Admin the ability to provide us with multiple inputs here that would alternate, I think that'd be an excellent bonus.

**Describe alternatives you've considered**

Perhaps we'd rather give Forem Admins more granular controls over each individual page's dropdown/display URL appearance. This would allow the Forem Admin to set separate emojis for each page if they'd like. If we went this route, I think these granular options would live in `admin/pages` and admin would need to click into individual pages to modify the emojis that appear with each page.

**Additional context**

This search should help to show where these emojis: "👨‍💻👩‍💻 " appear - https://github.com/forem/forem/search?q=%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB%F0%9F%91%A8%E2%80%8D%F0%9F%92%BB

I struggled to describe this, but these are where the emojis are placed in the dropdown/display URLs:
![Image 2020-11-16 at 5 09 58 PM](https://user-images.githubusercontent.com/16007075/99314145-a3fff780-282e-11eb-9357-45e36dc6c900.png)

**Comment by vaidehijoshi** [comment]
This is something that we should definitely remove from all the hard-coded instances that @michael-tharrington linked to; it is far too DEV-specific.

I see two paths forward here:
1) Remove the hardcoded emojis entirely (which removes it from DEV, too), and allow the Forem creator to add an emoji into the SiteConfig's community name like this:

<img width="1182" alt="Screen Shot 2020-11-16 at 2 33 05 PM" src="https://user-images.githubusercontent.com/6921610/99316176-bec77180-2818-11eb-8614-1a24f6cbfda5.png">

2) Add a `SiteConfig.community_emoji`, which should be _optional_ and not required, which we substitute for the places where the emojis are currently hardcoded.

Option 1 actually seems "cleaner" to me, but the downside is that it will change what the community_name looks like _everywhere_ in the app (and that's a big change, as [it is used in a lot of places](https://github.com/forem/forem/search?q=community_name)).

Option 2 prevents us from changing it everywhere, but then it adds _yet another configuration_ to SiteConfig, which I am weary of... 😩 but if we want to maintain feature-parity with what we are _currently_ doing, that's probably the right path forward.

**Comment by rhymes** [comment]
@vaidehijoshi 

I'm weary about Option 2 as well, `SiteConfig` currently contains 100 configuration values and it's only going to increase:

```ruby
[5] pry(main)> SiteConfig.keys.size
=> 100
```

That said, what prevents a person to write chars other than emojis `community_emoji`? Could that be confusing?

**Comment by vaidehijoshi** [comment]
@rhymes Good point! I updated the PR to include a validation around that field such that it _only_ allows for emoji characters. Thanks for the reminder 👍
