### ISSUE TITLE
Padding missing in podcast page comments section

### ISSUE THREAD

**Issue by reobin** [forem/forem#11443]
**Describe the bug**
There seems to be some padding missing to the comments section on a podcast's page

**To Reproduce**
1. Visit [a podcast's page](https://dev.to/devnews/s1-e0-season-1-trailer)
2. Look at the comments section

**Expected behavior**
Consistent spacing like on [an article's page](https://dev.to/itsmukulmishra/how-to-start-your-cs-career-45ij)

**Screenshots**
![Screen Shot 2020-11-16 at 11 13 22](https://user-images.githubusercontent.com/5920450/99278198-bfeaa580-27fc-11eb-89cf-f748641a3623.png)

**Desktop (please complete the following information):**

- OS, version: macOS Big Sur
- Browser, version: tested on both Chrome 86 and Safari 14

**Comment by ludwiczakpawel** [comment]
This should be now fixed.
