### ISSUE TITLE
Allow Webp Images in Posts

### ISSUE THREAD

**Issue by manasmithamn** [forem/forem#11452]
**webp images are not allowed in Dev.to posts. Webp takes less bandwidth & time to load, best it supports animation too**

** While uploading images, allow to upload webp images also.**

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Hi @manasmithamn, I'm going to close this as a duplicate of https://github.com/forem/forem/issues/9118 which contains a discussion and more info. Thanks for the reminder!
