### ISSUE TITLE
Remove `collective_noun` + `collective_noun_disabled` and use `community_name` instead

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#11456]
**Is your feature request related to a problem? Please describe.**

After https://github.com/forem/forem/pull/11107 was merged, I [pointed out](https://github.com/forem/forem/pull/11107#issuecomment-717406783) that we probably don't need to add `collective_noun` and `collective_noun_disabled` to the `SiteConfig`, which is _already_ pretty overloaded.

**Describe the solution you'd like**

Instead, it would be ideal to use `community_name` (which already exists and is a required field) in the places where `collective_noun` is used rather than adding another override-able config.

Something to consider is @jacobherrington's [comment](https://github.com/forem/forem/pull/11107#issuecomment-717408490) on the original PR:
> the only issue would be handling instances in which folks didn't want to include the "collective noun" value. For example, when we say "Welcome to DEV" versus "Welcome to the DEV Community"

**Comment by mstruve** [comment]
Seems like a nice little cleanup task. I'm thinking difficulty easy on this one. If you disagree feel free to update the label!
