### ISSUE TITLE
Tài khoản không thể đăng nhập để viết bài

### ISSUE THREAD

**Issue by VTThanhHung** [forem/forem#11467]
Tài khoản của tôi không thể đăng nhập để viết bài hay chia sẻ bất cứ điều gì trên https://dev.to/
Làm thế nào để sửa lỗi và khắc phục được tình trạng này! TKS admin

**Comment by Link2Twenty** [comment]
**Translation:** 
>**The account cannot be logged in:**
My account cannot login to post or share anything on https://dev.to/
How can I fix this problem? TKS admin

**Comment by rhymes** [comment]
Hello @VTThanhHung,  thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

@Link2Twenty, thanks!
