### ISSUE TITLE
Listing edit button doesn't work

### ISSUE THREAD

**Issue by nilsmehlhorn** [forem/forem#11469]
**Describe the bug**

The button for editing listings from the dashboard (`/listings/dashboard`) doesn't work. I'd say that's beacuse its a button with an href attribute.

**To Reproduce**

1. Create listing
2. Go to `/listings/dashboard`
3. Click 'Edit' on listing
4. Nothing happens

**Expected behavior**

Clicking the button should redirect to an edit form for the listing (`/listings/{listingId}/edit`, judging from the href)

**Desktop (please complete the following information):**

- OS, version: Ubuntu 18.04.5
- Browser, version: FF 82.0.3 (64-Bit)

**Additional context**

Possible duplicate of #10937

Fix would probably involve chaning the following line to a link:
https://github.com/forem/forem/blob/36e271e1cb6ec5382401ad36a3eedc77bb2a3f1f/app/javascript/listings/dashboard/rowElements/actionButtons.jsx#L13

**Comment by cmgorton** [comment]
Hey @nilsmehlhorn thank you for bringing up this issue! Since this does appear to be a known issue #10937 , I am going to close this one here. Please feel free to follow issue #10937 and leave any additional comments there. Thanks!
