### ISSUE TITLE
Replace PodcastEpisodes's social preview with HtmlCssToImage

### ISSUE THREAD

**Issue by maestromac** [forem/forem#11477]
**Is your feature request related to a problem? Please describe.**
This area of the code base, `podcast_episodes/_meta.html.erb`, is still using Cloudinary instead of HCTI to render the social preview images.

**Describe the solution you'd like**

Replace it with HCTI using our `SocialImageHelper`

**Describe alternatives you've considered**
nope

**Additional context**
n/a

**Comment by cmgorton** [comment]
@maestromac is this still something you are looking in to? Should we label this as a potential RFC?

**Comment by maestromac** [comment]
Thanks for the ping @cmgorton . Apparently, this was already resolved by https://github.com/forem/forem/pull/11961 !! :confetti_ball:
