### ISSUE TITLE
Checking for prefers-reduced-motion setting with images that accept GIFs (as GIFs usually contain motion)

### ISSUE THREAD

**Issue by sjarva** [forem/forem#11470]
**Is your feature request related to a problem? Please describe.**

I am a user with a vestibular order, and seeing animation and motion on the web gives me nausea. I appreciate that Forem already reduces animations and transitions elsewhere in the app (in `reset.scss`), but this doesn't affect any motion that that occurs in GIFs.
Recently I came across a user, who had particularly fast GIF in their profile image, and I had to leave the site and deal with the nausea. If this GIF was in a post cover image or some image inside the post, I could just not read that particular post, but since this the profile image, which is visible in all the comment this user has made, on top of their post (and in desktop view, sticking to the right side of all their posts), this causes me (and other users with vestibular disorders) nausea whenever I see this user's content on Forem. If I want to read their comments or posts, I have sacrifice a lot of energy and time to minimise the possibility of seeing their profile image.

**Describe the solution you'd like**

As it is possible to upload GIFs as (at least) a profile image (but possibly also to post cover images and images inside a post) to Forem, I'm suggesting that whenever user has uploaded a GIF, Forem asks the user to submit a static photo also. Forem could then check for the `prefers-reduced-motion` media query, and decide if the GIF can be shown, or should the static image be shown ([like in this example](https://css-tricks.com/gifs-and-prefers-reduced-motion/))

**Describe alternatives you've considered**

Another solution would be to auto pause GIFs, and let the users decide to play them.

Another solution would be to prevent users from uploading GIFs as an image.

**Comment by cmgorton** [comment]
Good suggestion and similar to #946. Will add this to our feature request project board for more visibility. Thanks.

**Comment by TobiasNickel** [comment]
Thanks @sjarva for reaching out. I had a [very busy gif](https://res.cloudinary.com/practicaldev/image/fetch/s--OuFtbSNT--/c_fill,f_auto,fl_progressive,h_320,q_66,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/84818/f7479d94-fecf-45d4-8d94-193c8e9c79b5.gif) as background picture and because I want everyone to enjoy the good content and the community on dev. I already changed to a static one:

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
