### ISSUE TITLE
Auto-create tags (if necessary) when added to sidebar

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11487]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin setting up my forem, I may set my sidebar tags via `Admin > Config > Tags`.  They will be added to the homepage sidebar, but if that tag doesn't exist yet, the link will 404.

**Describe the solution you'd like**
If a tag is added to the homepage sidebar via `Admin > Config > Tags`, it should be auto-created if it doesn't exist already.  This change will ensure Forem Admins don't accidentally add a prominent link that will 404 to the right-sidebar.

**Additional context**
I believe that tags are currently "created" after they are used in a post (even if it's just in a saved draft).

**Comment by cmgorton** [comment]
I believe this has been addressed with Ben's PR. If that is not the case we can open this issue back up.
