### ISSUE TITLE
Icon picker in /admin/navigation_links

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11486]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin adjusting icon links in `/admin/navigation_links`, I'm currently required to paste in the Icon SVG.  This is pretty painful.

**Describe the solution you'd like**
An "icon picker" that allows me to choose my icon of choice in a more streamlined manner.

**Additional context**
Forem recommends [Twemoji](https://twemoji.twitter.com/) and already provides acknowledgment in the project README.

![example of admin nav links](https://p241.p3.n0.cdn.getcloudapp.com/items/bLu0zzzY/Image%202020-11-18%20at%205.49.46%20PM.png?v=d833c41eb6f66f90bd1308a0e694adae)

**Comment by joaoGabriel55** [comment]
Nice issue! I will start to develop a solution.

**Comment by cmgorton** [comment]
Looks like this was implemented per PR #12388. I am going to go ahead and close this issue!
