### ISSUE TITLE
After the comment menu is triggered, the main top-right menu stops working.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#11489]
**Describe the bug**

Very odd, but if you trigger the menu dropdown to work, the main menu will all of a sudden _not_ work.
**To Reproduce**

- Go to page with comments
- Open a three-dots menu
- Go to top-right of page and hover... The menu won't work until you refresh.
**Expected behavior**

**Comment by rhymes** [comment]
This has been closed by #11498
