### ISSUE TITLE
Navbar UI issues on email confirmation page

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#11488]
**Describe the bug**

When going through the email/password signup flow, you have to confirm your email. The email is sent to you (or you can open the email by click through to the link via your development log.

When clicking through my "confirm your email" link, I am taken to the `/users/confirmation` page, and I see some wonky UI:
<img width="1487" alt="Screen_Shot_2020-11-18_at_3_32_53_PM" src="https://user-images.githubusercontent.com/6921610/99602206-ef90dd80-29b5-11eb-82fd-e0f03bc54769.png">

**To Reproduce**

1. Create a user using email/password
2. Confirm your email (use your development logs and find the confirmation email HTML content, which should look like this):

```
<p>You can confirm your account email through the link below:</p>

<p><a href="http://localhost:3000/ahoy/messages/4y6Fb6IDvGr5mAxRkz32o31Xx7taOOoC/click?signature=6438ae0a21c1b2e6c002a46bd440c48f67e73a31&amp;url=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fconfirmation%3Fconfirmation_token%3DwvV4s7WP9guWpbhyXUwa%26utm_source%3Ddevise_mailer%26utm_medium%3Demail%26utm_campaign%3Dconfirmation_instructions">Confirm my account</a></p>
<img alt="" src="http://localhost:3000/ahoy/messages/4y6Fb6IDvGr5mAxRkz32o31Xx7taOOoC/open.gif" width="1" height="1">
</body></html>
```

3. Copy-paste the `href` of the `<a>` tag (aka the URL) into a [URL decoder](https://www.urldecoder.org/)
It will look like this in the logs:
`http://localhost:3000/ahoy/messages/4y6Fb6IDvGr5mAxRkz32o31Xx7taOOoC/click?signature=6438ae0a21c1b2e6c002a46bd440c48f67e73a31&amp;url=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fconfirmation%3Fconfirmation_token%3DwvV4s7WP9guWpbhyXUwa%26utm_source%3Ddevise_mailer%26utm_medium%3Demail%26utm_campaign%3Dconfirmation_instructions`

But once you decode it, you only need to copy the value of the `url=`:
`url=http://localhost:3000/users/confirmation?confirmation_token=wvV4s7WP9guWpbhyXUwa&utm_source=devise_mailer&utm_medium=email&utm_campaign=confirmation_instructions`

4. Open that link in a new tab, and you should see the UI issues described in the screenshot. The search bar appears to be open, and the "create account" button from the nav bar seems to be rendering twice.

**Expected behavior**

I expect no UI issues when I open this page -- the search bar should not be open, and the nav bar should not double-render.

**Screenshots**
<img width="1487" alt="Screen_Shot_2020-11-18_at_3_32_53_PM" src="https://user-images.githubusercontent.com/6921610/99602206-ef90dd80-29b5-11eb-82fd-e0f03bc54769.png">

**Comment by benhalpern** [comment]
This is the same bug as here: https://github.com/forem/forem/pull/11476

Thanks for the detailed note. This is definitely worth getting to the bottom of.

It relates to how service workers do not cleanly deal with redirecting sometimes. But the reason this is happening here isn't immediately obvious to me because it seems like we skip `/ahoy/` URLs in the service workers. 🤔

**Comment by katiedavis** [comment]
Hello @vaidehijoshi  I tried recreating this a few times and had no luck: 
<img width="1483" alt="Screen Shot 2021-01-26 at 2 39 39 PM" src="https://user-images.githubusercontent.com/15366319/105896114-69f86200-5fe4-11eb-9c1c-ec7f11ff7e38.png">
When I discussed this issue with @nickytonline he mentioned [that this pr](https://github.com/forem/forem/pull/11744) may have solved this issue, but I'm having trouble trying to define *why* it would have fixed this issue. I have yet to see it pop up on my end, so if you have a chance can you see if its resolved for you as well?

**Comment by vaidehijoshi** [comment]
@katiedavis I guess it was inadvertently (?) fixed somewhere along the way! I just tried this out again locally and am not seeing that same UI bug anymore. I guess we can close this out now 😅
