### ISSUE TITLE
Update Copy for Orgs Call-to-action Box (too DEV-specific)

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#11482]
**Is your feature request related to a problem? Please describe.**

Yes, as a member of a Forem community that's not DEV, the copy explaining the call-to-action box available to orgs from `/settings/organization` feels a bit out of place and the link to the example on DEV simply doesn't work.

**Describe the solution you'd like**

I think we can remove the linked example of the call-to-action box.

**Describe alternatives you've considered**

We could answer this in an org FAQ page.

**Additional context**

![Image 2020-11-18 at 6 26 17 PM](https://user-images.githubusercontent.com/16007075/99600542-9f247a80-29cb-11eb-8a23-007c126b4113.png)

The link isn't really broken, it's just that it's pointing to `/devteam/the-dev-badge-is-available-on-font-awesome-2ihe` and the site assumes it's on whatever Forem instance the user is on. But, this post is only on DEV.

**Comment by mstruve** [comment]
This seems like a relatively straightforward bug and not crazy urgent. I think a contributor might jump at the chance to work on this so I am going to remove it from our EOY Priority board and open it up to the community.
