### ISSUE TITLE
Change style of "Toggle" in /admin/config

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11484]
**Is your feature request related to a problem? Please describe.**
As a Forem admin, I am confused by what `Toggle` refers to.  I may be afraid to click the button in case it breaks something.

**Describe the solution you'd like**
A more typical UI pattern / symbol that indicates the actual functionality.

Might need a bit of Product love to shape this issue before it's ready to work on.

**Additional context**
This has frustrated a few Forem Admins already.

![example of the page](https://p241.p3.n0.cdn.getcloudapp.com/items/z8u4EDyw/Image%202020-11-18%20at%205.47.38%20PM.png?v=6146d40a23dfbf32b835db5815736f15)

**Comment by lisasy** [comment]
Design recommendation: an approach to solving this problem with minimal engineering would be to update the label of the text. 

Change from "Toggle" to "Show info" or "Hide info". Eventually, with a more global update to `/admin`, this whole feature will become deprecated, so this is really a patch solution for the time.

**Comment by rhymes** [comment]
I'll get around to this later, thanks for the suggestion @lisasy

**Comment by nickytonline** [comment]
+1 to what @lisasy mentioned. Also, instead of `<div />`s, [<details />](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) and `<summary tags />` could be used. It's more semantic and it comes with open/close functionality out of the box.

**Comment by rhymes** [comment]
@nickytonline I didn't change the HTML though, I just tried to apply a quick patch given that we don't want to spend too much time on it as the existing code already used Bootstrap. But yeah, that's a much better idea. The issue is that that's need to be styled, Bootstrap already styles much of it IIRC, I might take a look at the switch in a following PR...
