### ISSUE TITLE
cant create post

### ISSUE THREAD

**Issue by Fortune-dot** [forem/forem#11496]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by cmgorton** [comment]
Hey @Fortune-dot this issue is lacking a lot of context. I am going to close this issue since it looks like maybe it was created before you were finished? If that is not the case please feel free to create a new issue with more information. Thanks.
