### ISSUE TITLE
PostCSS Warnings and Errors Flooding logs Causing Travis Build Failures

### ISSUE THREAD

**Issue by mstruve** [forem/forem#11490]
### Problem
Recently we have had [Travis builds fail](https://travis-ci.com/github/forem/forem/jobs/443192844) bc the log length exceeds the max allowed. This is a big problem bc despite the job showing as failed, the deploy still goes out successfully which sends the wrong message to the developer tracking their deploy. 

Here is an example of some of the logs:
```
yarn run v1.22.5
       $ postcss public/assets/*.css -d public/assets
       
       5:146912	⚠  Custom property ignored: not scoped to the top-level :root element (.site-logo { ... --max-width: ... }), in atrule [postcss-custom-properties]
       5:146969	⚠  Custom property ignored: not scoped to the top-level :root element (.site-logo { ... --max-width: ... }), in atrule [postcss-custom-properties]
       5:146988	⚠  Custom property ignored: not scoped to the top-level :root element (.site-logo { ... --font-size: ... }), in atrule [postcss-custom-properties]
       5:147013	⚠  Custom property ignored: not scoped to the top-level :root element (.site-logo { ... --font-weight: ... }), in atrule [postcss-custom-properties]
       5:147082	⚠  Cust
       
...

            1:104452    ⚠  variable '--su-2' is undefined and used without a fallback [postcss-custom-properties]
       1:106070 ⚠  variable '--body-color' is undefined and used without a fallback [postcss-custom-properties]
       1:106403 ⚠  variable '--body-color' is undefined and used without a fallback [postcss-custom-properties]
       1:107307 ⚠  variable '--link-brand-color' is undefined and used without a fallback [postcss-custom-properties]
       1:107500 ⚠  variable '--card-color-tertiary' is undefined and used without a fallback [postcss-custom-properties]
       1:107878 ⚠  variable '--card-bg' is undefined and used without a fallback [postcss-custom-properties]
       1:108523 ⚠  variable '--link-brand-color' is undefined and used without a fallback [postcss-custom-properties]
       1:108599 ⚠  variable '--card-bg' is undefined and used without a fallback [postcss-custom-properties]
       1:109255 ⚠  variable '--body-color' is undefined and used without a fallback [postcss-custom-properties]
       1:116689 ⚠  variable '--card-secondary-bg' is undefined and used without a fallback [postcss-custom-properties]
```  

After some Googling it [seems like we should not be loading postcss for certain node_modules](https://github.com/adobe/react-spectrum/issues/829#issuecomment-662816532) and that we need to update our configuration. Being a backend person this is all a foreign language to me. Hopefully someone with more front end prowess can figure this out. 

cc @nickytonline

**Comment by mstruve** [comment]
This has escalated now as every build is starting to show up as failed despite succeeding. 

<img width="579" alt="Screen Shot 2020-11-19 at 8 41 17 PM" src="https://user-images.githubusercontent.com/1813380/99747422-1aeff700-2aa0-11eb-986e-f807ed07ff6d.png">

**Comment by nickytonline** [comment]
I'm curious why it's gotten progressively worse though that it's started to cause false fails. Let's sync up in the morning.

**Comment by rhymes** [comment]
I'm going to take a look into it, self assigned temporarily

**Comment by nickytonline** [comment]
I did some tests yesterday evening and outputting the logs to a file then grepping seems to work. I haven't found a way to silence the logs though for those warnings. It also looks like the postcss configuration file is getting picked up when postcss runs.

**Comment by rhymes** [comment]
@nickytonline would something like this work? https://stackoverflow.com/a/49629759/4186181

**Comment by rhymes** [comment]
see also https://github.com/rails/webpacker/blob/master/docs/css.md#post-processing-css

**Comment by rhymes** [comment]
Submitted a PR with essentially the following change:

```js
/* globals module, require */
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-flexbugs-fixes'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009',
      },
      stage: 3,
      features: {
        customProperties: {
          warnings: false,
        },
      },
    }),
  ],
};
```

mutuated from the default `postcss.config.js` in https://github.com/rails/webpacker/blob/master/lib/install/config/postcss.config.js

Not sure it's going to work, i'll wait for the build https://github.com/forem/forem/pull/11518

**Comment by rhymes** [comment]
Reopening as it didn't hide the warnings https://travis-ci.com/github/forem/forem/jobs/444329926

**Comment by nickytonline** [comment]
Also, for context @rhymes this is not part of the webpack build. It's a post compile task. See https://github.com/forem/forem/blob/master/lib/tasks/post_precompile_assets.rake

**Comment by rhymes** [comment]
@nickytonline got it! shouldn't webpacker take care of that already?

**Comment by nickytonline** [comment]
It's not a webpacker thing. It was part of the asset pipeline with Sprockets and was originally handled in a gem and then the gem for deprecated or unmaintained. I can't remember what issue/pr it was, but it was an issue you had opened about that gem. I think it got merged a couple of months ago. I'll find it.

**Comment by rhymes** [comment]
Found it https://github.com/forem/forem/pull/10017 

the discussion is here https://github.com/forem/forem/issues/9965

**Comment by rhymes** [comment]
I went down a rabbit hole and emerged here https://github.com/postcss/postcss-custom-properties/issues/117 but apparently the `warnings: false` option doesn't exist anymore

**Comment by rhymes** [comment]
Ok, so I opened a random set of builds and the warnings have been there for a while. I bet that if we go back weeks or months the warnings are the same, it's probably just that for a combination of bad luck and some changes we exceeded the amount of lines we can emit in the build and now the builds are marked as failed.

For example, the cascade of build failures seems to have started in https://travis-ci.com/github/forem/forem/jobs/443950767 *but* if we go back to a random build on November 1st, the warnings are still there https://travis-ci.com/github/forem/forem/jobs/432714680#L1760 yet the build passes with flying colors and gets marked as green

**Comment by rhymes** [comment]
I hope I'm wrong but it might be that build stages are all counted towards the 4MB log limit for the single build, testing by disabling deployment to the secondary server here https://github.com/forem/forem/pull/11520

**Comment by nickytonline** [comment]
> I went down a rabbit hole and emerged here [postcss/postcss-custom-properties#117](https://github.com/postcss/postcss-custom-properties/issues/117) but apparently the `warnings: false` option doesn't exist anymore

I think if I recall correctly, I went down that Rabbit hole with the initial PR #10017.

If that's not possible, I think running yarn postcss &> somelogfile.log would work. `&>` means it logs the stderr, so if the file length is > 0, that should be a good enough check for failure.

**Comment by rhymes** [comment]
@nickytonline yeah, together with @maestromac we've decided to go full Unix and just suppress the logs https://github.com/forem/forem/pull/11521
