### ISSUE TITLE
Can't change Github email on profile

### ISSUE THREAD

**Issue by javitruhlar** [forem/forem#11493]
**Describe the bug**
There is not setting for changing a profile's Github email. Once it's set, it can't be changed

**Expected behavior**
You should be able to update your Github email 

**Desktop (please complete the following information):**

- OS, version: Linux Mint 19.3
- Browser, version: 78.0.1 (64-bit)

**Comment by rhymes** [comment]
@javitruhlar the GitHub email is linked to the primary GitHub email set in https://github.com/settings/emails - as it's used to verify your identity, I don't believe you should be able to "change it" on our side. We only use it for authentication purposes, for communication we use the `email` field. By changing that, you can change your DEV email

**Comment by javitruhlar** [comment]
Yes, that was useful. I was able to update it that way.
Thanks!
