### ISSUE TITLE
(Literally) Large Formatting Bug in Comments

### ISSUE THREAD

**Issue by Lathryx** [forem/forem#11508]
### Describe the bug
So this was in the comments of [this post](https://dev.to/ljcdev/easy-hamburger-menu-with-js-2do0). I had hit submit on the comment and shortly after had hit "Keep Writing" before the button went away (I was in preview mode). As a result, I got what is shown in screenshot # 1. This issue seems to go away after refreshing the page. 

### To Reproduce

1. Go to the comment section of a post (preferably the one this happened on).  
  
2. Write something using `inline code` (that's what I did).  
  
3. Go into preview mode.  
  
4. Hit submit and then "Continue editing" quickly after.  
  
5. See something like what's shown in screenshot # 1.  

### Expected behavior
Comments should be displayed normally as shown in screenshot # 2. 

### Screenshots
**Screenshot # 1:** 
![image](https://user-images.githubusercontent.com/52394238/99724130-2c75d680-2a81-11eb-8b57-49c0ce7773e3.png "Image of bug that occurred")  
_Image of bug that occured_

**Screenshot # 2:** 
![image](https://user-images.githubusercontent.com/52394238/99724152-3697d500-2a81-11eb-986e-71bf45658836.png "What the comment should look like")  
_What the comment should look like_

### Desktop:

- **OS, version:** Windows 10 Home, version 2004. 
- **Browser, version:** Google Chrome, Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by cmgorton** [comment]
Hey @Lathryx thanks for opening this issue. Have you noticed this happening any more since you initially opened this bug report?

**Comment by Lathryx** [comment]
> Hey @Lathryx thanks for opening this issue. Have you noticed this happening any more since you initially opened this bug report? 

No, I haven't. It was strange, but it seems like it was a fluke. I'll let you know of anymore appearances of this issue, but for now I think it's okay.
