### ISSUE TITLE
Use rate limit modal to alert users of rate limit exceeded warnings

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#11500]
**Describe the solution you'd like**

A generic modal for rate limit warnings was added in https://github.com/forem/forem/pull/11102. It would be idea if all places in Forem that warned a user about rate limits used that model.

Start with `app/services/rate_limit_checker.rb` and trace back paths from there. Some examples:

- creating too many reactions too quickly
- updating an article or user too much too quickly
- following too many users too quickly

**Comment by PauloVilarinho** [comment]
I would like to take this task!  @joshpuetz

**Comment by shilpi230** [comment]
@joshpuetz I would like to take this. Thanks!

**Comment by cmgorton** [comment]
Hey @shilpi230 looks like your comment slipped by all of us. Sorry about that!
Is this something you are still interested in working on?

**Comment by PawelBorkar** [comment]
@cmgorton 
If it's okay for @shilpi230 then I would like to work on this issue ☺️

**Comment by cmgorton** [comment]
I am going to go a head and assign it to you @PawelBorkar. Thanks for the help here! If you have any questions while you start working feel free to ask here or in your PR once it is created.

**Comment by cmgorton** [comment]
Hey @pawelborkar wanted to check in and see how you are doing with this issue. Did you have any questions or need any help?

**Comment by abhishekraj272** [comment]
@cmgorton could you assign this to me?

**Comment by Zappat0n** [comment]
Hi @cmgorton. I would like to work on this issue. Thank you very much.

**Comment by cmgorton** [comment]
Just assigned you @Zappat0n .Thanks for the help! Let us know if you have any more questions.

**Comment by tnir** [comment]
Looks like @Zappat0n finished this issue in #14609. @cmgorton @aitchiss Could you close this [good first issue](https://github.com/forem/forem/labels/good%20first%20issue)-labeled issue?

**Comment by joshpuetz** [comment]
Thanks for the heads up @tnir!
