### ISSUE TITLE
Inconsistency in API 

### ISSUE THREAD

**Issue by nishantwrp** [forem/forem#11517]
In `https://dev.to/api/articles` endpoint `tag_list` is an array of tags.
In `https://dev.to/api/articles/{id}` endpoint `tag_list` is a string where the tags are concatenated by a comma. There is also a `tags` property which is an array of tags.

It would be better if the keys are consistent with the type of values.

**Comment by rhymes** [comment]
Thanks @nishantwrp - this is a known inconsistency and it will remain as such for the time being. Changing it will break existing clients. We'll definitely fix it whenever we start designing v1 though :) 

See https://github.com/forem/forem/issues/4637 and https://github.com/forem/forem/issues/8183

I'm going ahead and close this :)
