### ISSUE TITLE
Contributing to api docs

### ISSUE THREAD

**Issue by nishantwrp** [forem/forem#11515]
Hi,
I just wanted to know that how can I contribute to API docs present at https://docs.dev.to/api/.

**Comment by rhymes** [comment]
Hi @nishantwrp, I think currently the API is fully documented but if you find something useful or want to improve the existing documentation, we do have a guide here which explains how to contribute to the documentation: https://docs.dev.to/contributing/api/

Let us know if ou have further questions

**Comment by nishantwrp** [comment]
Thanks for the link @rhymes. I have no further questions, so closing this issue.
