### ISSUE TITLE
Update default text/background color values on tag edit page

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11522]
**Is your feature request related to a problem? Please describe.**
As a tag admin, I don't want to accidentally set my tag to using `#000000` as the color hex for both text and background.

**Describe the solution you'd like**
New placeholder values; probably just text using `#ffffff`

**Additional context**
@juliannatetreault made a similar fix for the `/admin` edit view in this PR: https://github.com/forem/forem/pull/11105

Here's an example of the tag edit page:
![example tag edit page](https://p241.p3.n0.cdn.getcloudapp.com/items/BluQjbX2/Image%202020-11-20%20at%2010.06.35%20AM.png?v=7e6aaa4152530c1592982e7f245c1ee9)

**Comment by cmgorton** [comment]
@pkfrank do you think this should be labeled `potential RFC`?

**Comment by juliannatetreault** [comment]
> @pkfrank do you think this should be labeled `potential RFC`?

I'd be more than happy to champion this RFC if we decide to go in that direction since I'm familiar with this code/issue, @cmgorton and @pkfrank! 😊

**Comment by cmgorton** [comment]
Going to add the potential RFC label to this. @pkfrank Julianna is willing to champion this is we think it should move in to the RFC phase.

**Comment by vaidehijoshi** [comment]
@juliannatetreault I'm going to go ahead and close this since it looks like your PR has addressed it 👍🏽
