### ISSUE TITLE
Large images appear on screen after leaving a comment.

### ISSUE THREAD

**Issue by gippea** [forem/forem#11526]
**Describe the bug**

I started reading through the weekly retro. And shared some love and then a comment. When I left a comment with `const smile = createMoreTime();` and previewed it everything seemed fine. But when I published the comment a huge Twitter icon, GitHub icon and Heart icon appeared on the screen.

**To Reproduce**
1. Visit this week's retro.
2. Write a comment.
3. Preview the comment.
4. Post the comment.
5. See error.

**Expected behavior**
The user's profile social handle link images should be a normal size.

**Screenshots**

![Screenshot_20201120-211736](https://user-images.githubusercontent.com/64609347/99851673-5e696480-2b77-11eb-92d1-f00c9d9d2bda.png)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device: Pixel 3 XL
- OS, version: Android 10
- Browser, version: Chrome

**Additional context**

**Comment by ludwiczakpawel** [comment]
I believe this was due to some caching issue since that was around the time we released new comments UI.
For that reason, I'm closing this issue but please let me know if this still happens to you - I'll reopen and investigate.
