### ISSUE TITLE
Published comments not rendering markdown styles properly

### ISSUE THREAD

**Issue by lisasy** [forem/forem#11524]
## Describe the bug
When I write my comment in markdown, the markdown styles do not render properly when they're published. It's surprising between the `comment preview` shows the expected markdown styling, but the actual `published comment` does not. 

## To Reproduce

1. Write a comment in markdown including a variety of 
2. See its preview
3. Publish it and notice the discrepancy

## Expected behavior
When I write a comment in markdown with the proper syntax, I expect it to render properly. 

### Writing ✅
![Screen Shot 2020-11-20 at 11 09 07 AM](https://user-images.githubusercontent.com/816402/99840575-a3fb4280-2b21-11eb-8f76-1d281c3b1b54.png)

### Preview ✅
![Screen Shot 2020-11-20 at 11 09 55 AM](https://user-images.githubusercontent.com/816402/99840577-a493d900-2b21-11eb-8af9-a2174732ff98.png)

### Published output ❌
![Screen Shot 2020-11-20 at 11 08 48 AM](https://user-images.githubusercontent.com/816402/99840568-a1005200-2b21-11eb-89ad-5cb085cd473a.png)

**Comment by ludwiczakpawel** [comment]
I believe this is now fixed.
