### ISSUE TITLE
less nested comments

### ISSUE THREAD

**Issue by nicosmaris** [forem/forem#11532]
Comments that are more than 1 level of replies are hard to read.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

At android app, when I get notified that someone replied to my comment, I have the option to reply back but this leads to yet another nested comment

**Describe the solution you'd like**

Continue on the same thread when I press the reply button in the notification screen of the android app.

**Comment by cmgorton** [comment]
Thank you for opening this request!
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
