### ISSUE TITLE
Automatically grant "trusted" status to Superadmins / Admins

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11569]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin, I sometimes have "superadmin" and/or "admin" privileges but not "trusted" status.  This doesn't make all that much sense and is leading to confusion.

Trusted is a more widely-shared permission than admin status, and we can have  a lot of confidence that if someone can be "trusted" with admin/superadmin status, they can also be `trusted`.

**Describe the solution you'd like**
All superadmins and admins should automatically be granted `trusted` status.

**Describe alternatives you've considered**
Encourage superadmins / admins to manually grant themselves `trusted` through documentation and/or other areas.

**Additional context**
The very first user of a forem is currently a `superadmin`.

It's probably not a big deal, but it will add a bit of "noise" if they receive the automatic "trusted" email when they first set up their account.  cc @forem/creator-onboarding

**Comment by vaidehijoshi** [comment]
This should be fairly straightforward; I was in this code the other day, and adding the role can happen right after the first user is created. We probably can also conditionally 'turn off' the trusted email if we want -- although there might be some content in that email that we still want the forem creator to have knowledge of, I'm assuming?

**Comment by vaidehijoshi** [comment]
Tagging this as EOY since it can be done in isolation and will be helpful to bizdev when setting up new Forem creators.

**Comment by vaidehijoshi** [comment]
I addressed this in the most "straightforward" way in https://github.com/forem/forem/pull/11700, but as I wrote on that pull request, this will probably need to be a "larger", more holistic change:

> Ultimately, I think we probably need to do something more far-reaching in order to give every superadmin the benefits of being a trusted user (as described in #11569), but I didn't want to go through the whole codebase adding a bunch of conditionals without thinking through other alternatives first. In the meantime, adding trusted as a role for all new Forem creators will be helpful for bizdev + @pkfrank.

I think this actually needs to be converted to a RFC...but I might brainstorm on what the best implementation for this is, first.
