### ISSUE TITLE
Feed navigation does not initialize if the first article is not 100% visible

### ISSUE THREAD

**Issue by reobin** [forem/forem#11566]
**Describe the bug**
When entering a page, and pressing `j` or `k`, the list navigation shortcut looks for the first visible article that appears on the screen, and focuses on that.

A problem that occurs is that if the first article in the list is longer than the window's height, it is not considered "visible", so the navigation does not start.

That is because the `isInViewport` function used by the navigation shortcut checks if the element's bounding rectangle is 100% visible in the current window.

_Note_: Perhaps now would be a good time to replace `isInViewport` with the Intersection Observer API, as mentioned by Nick in #10468.
[See comment](https://github.com/forem/forem/pull/10468#discussion_r520201058)

**To Reproduce**
1. Navigate to [/top/infinity](https://dev.to/top/infinity)
2. Make sure your browser's window is not big enough to fit the entire first article
3. Try to initialize the article feed navigation (pressing `j` and `k`)
4. Notice nothing is happening

**Screenshots**
Notice that the first article is longer than the current window.
![Screen Shot 2020-11-23 at 08 19 10](https://user-images.githubusercontent.com/5920450/99967509-ff1d7700-2d65-11eb-8c1f-dbaff152cf2e.png)

**Expected behavior**
When no article is focused on, the first article that is visible should be focused on.

We might want to have a similar behaviour to the current one: we look for the first article that is fully visible, and then fall back to any that is partially visible if nothing is found.

In a case like the following, we would not want the `Announcing Word Wrap Podcast` (partially visible) to be focused on first, but rather the `11 reasons` one:
![Screen Shot 2020-11-23 at 08 37 21](https://user-images.githubusercontent.com/5920450/99968549-422c1a00-2d67-11eb-8f14-209a6e9dbe7b.png)

**Desktop (please complete the following information):**
- OS, version: macOS 11
- Browser, version: Safari 14

**Additional context**
- Original PR for article feed navigation: #10468
- [List navigation hook](https://github.com/forem/forem/blob/cc4a17992adc898a1490223506b7eb636fb3ce34/app/javascript/shared/components/useListNavigation.js#L45)
- [`isInViewport` function](https://github.com/forem/forem/blob/cc4a17992adc898a1490223506b7eb636fb3ce34/app/javascript/utilities/viewport.js#L13)

**Comment by gowtham2095** [comment]
Hello @reobin,

Can I pick this up?

I understood the problem we are facing here. Which is, checking for an element within the rectangle(Viewport) might not always work. As per your suggestion, using the partially covered block as a fallback when there is no first element that fully fits inside the viewport seems good to me as well. I have read about the Intersection observer. Have not worked with it in my projects. I can read and see how to incorporate that here. Let me know if I could take this up. Thanks!

**Comment by rhymes** [comment]
Hi @gowtham2095, all bugs are open to contribution, I'll let @reobin add further info if that's needed as they graciously helped spearheading feed navigation the past few weeks but I think you can start in the meantime. I'll assign the issue to you

**Comment by reobin** [comment]
Hey @gowtham2095 !

So here is how the feed navigation initializes right now:

1. Load article feed
2. Press `j` or `k`
3. Focus on first article that is _completely_ visible

The problem here is with the _completely_ word.

As mentioned in the issue, if no article is fully visible, like when the article's height is bigger than the window's height (see first screenshot), then no article is focused on. That makes the feed navigation broken until you scroll down where there are articles that are fully visible.

The fix might something around these lines:

1. Load article feed
2. Press `j` or `k`
3. Focus on first article (from the top) that is _completely_ visible
    1. If there are none, look for the first partially visible article from the top

I think that's what you had in mind already. Doing so will fix all the potential issues that I mentioned above in the issue. There are surely more ways to attack this, but verify that all the potentially problematic situations are solved (like the one in _expected behaviour_ above).

Something else to consider is [Nick's comment in my initial PR](https://github.com/forem/forem/pull/10468#discussion_r520201058). I used boundingClientReact to check if an article is visible. It would be preferable to use the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to do the job. If you can get that in, I'm sure the team will appreciate it.

Don't hesitate if you have any questions! I don't have the time myself to work on it, but when you open a PR (draft if not ready) I'll take a look for sure.

Have a good day!

**Comment by reobin** [comment]
Oh and we talked a lot about the `isInViewPort` function, but the function with the fallback logic will probably be [this one](https://github.com/forem/forem/blob/cc4a17992adc898a1490223506b7eb636fb3ce34/app/javascript/shared/components/useListNavigation.js#L220): `getFirstVisibleElement` in `useListNavigation` which uses `isInViewport`.

**Comment by gowtham2095** [comment]
Hello @reobin!

Thanks for the detailed explanation. The solution mentioned above is what I had in my mind, too. I will comment here if I face any hiccups while working. Your comments are clear and helpful :)

**Comment by reobin** [comment]
Another case when that can happen I've encountered today:

![Screen Shot 2020-12-10 at 17 22 38](https://user-images.githubusercontent.com/5920450/101837004-611f0000-3b0c-11eb-97f8-3e4661d119d4.png)

We can test out this case too when doing the QA on the pull request.

**Comment by gowtham2095** [comment]
Hey @reobin,

I have drafted my fix here at https://github.com/forem/forem/pull/11874/files. Please have a look when you find the time. If this approach seems fine I shall add the tests for the same and push.

Below mentioned flow is how I am trying to fix it here. The order is maintained. 

1 ) Select the first element from the list which is completely visible in the viewport.

2) If not, select the first partially visible element if there is no completely visible element. There are some subcases here
    *  If the top part of the first element is above the viewport top boundary and the bottom lies within the viewport. 
    *  If the element covers the entirety of the viewport. (case: User has scrolled a bit and the element is large enough to extend outside both boundaries)
    *  If the element's top lies within the viewport and the bottom goes out of the viewport. (case: Banner covering the top portion leaving space only for one element) 
3) If not, see if there are articles present but none is visible in the viewport, select the first element from the list (Could be the case where the banner covers the entire viewport)

I have avoided using Intersection observer since I felt it will be a little overhead. Intersection Observer will be listening to the viewport and callbacks will be triggered when articles come in and leave the viewport. I felt that is not what is required here. What we need is when 'j' and 'k' key events happen, we have to let the user select some element based on what is visible in the viewport. I think the requirement here is to select from what is present in the viewport rather than observing what comes in and leaves the viewport. So felt the Intersection API might not be necessary. Correct me if I'm wrong. Any suggestions/help is really appreciated. Cheers!
