### ISSUE TITLE
Unable to Access Settings or Edit Profile Photo

### ISSUE THREAD

**Issue by adamfearnall** [forem/forem#11568]
**Describe the bug**

I'm unable to access the settings or the edit profile photo portion of my account on www.clusteremployment.com. I receive an error page when I attempt. 

**To Reproduce**

1. Login
2. Go to "settings" 
3. Receive error  message

**Expected behavior**

Go to the settings page. 

**Screenshots**

<img width="680" alt="Screen Shot 2020-11-23 at 10 10 47 AM" src="https://user-images.githubusercontent.com/74915777/99971945-47dc2c80-2d74-11eb-98f9-0a3414f1856d.png">

**Desktop (please complete the following information):**

- OS, version: 10.15.7
- Browser, version: Firefox 82.0.3 and Safari

**Comment by rhymes** [comment]
Hi @adamfearnall, thanks for informing us of the issues. what's your DEV's username?

**Comment by adamfearnall** [comment]
I'm actually not entirely sure - how would I figure that out (new to all of this!)?

Adam Fearnall (he/him)
Interim Executive Director
5516 Spring Garden Road, Suite 202
Phone: (902) 444-5885
adam@heartwood.ns.ca

**Comment by rhymes** [comment]
@adamfearnall when you login at the top left of the page there's your username:

![Screenshot_2020-11-23 DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/99979461-69a2d700-2da7-11eb-9839-10142ac40c1c.png)

**Comment by AdekunleA** [comment]
Hello @rhymes , he's experiencing this difficulty on the Cluster Employment Community. His username is @adamfearnall

**Comment by rhymes** [comment]
@AdekunleA sorry! Somehow I thought they were asking on DEV. I'll forward this internally. Thank you for the clarification.

**Comment by adamfearnall** [comment]
Thanks to both of you for helping me figure this out!

Adam Fearnall (he/him)
Interim Executive Director
5516 Spring Garden Road, Suite 202
Phone: (902) 444-5885
adam@heartwood.ns.ca

**Comment by cmgorton** [comment]
Hey @adamfearnall wanted to follow up here. Is this still an issue or was this resolved?
