### ISSUE TITLE
"Draft Posts from RSS Feed" broken - no longer creating drafts from RSS entries

### ISSUE THREAD

**Issue by markerikson** [forem/forem#11570]
**Describe the bug**

I used the "Drafts from RSS Feed" feature a couple times a few years ago.  When I added my RSS feed link to my profile settings, several of my posts correctly showed up as drafts in the Dev.to dashboard.

I'd now like to republish a couple more of my posts using that feature, but in looking at my dashboard, none of my posts since 2017 are showing up as drafts in the dashboard.  I've tried updating the RSS feed link in the settings panel a couple times, and it says that it's pulled the RSS feed recently, but no updates to the list of drafts in the dashboard.

**To Reproduce**

Not sure I can give specific reproduction steps here, beyond:

- Already had an RSS feed URL in the system for the last few years
- At some point, the "Drafts from RSS" feature stopped adding RSS posts as drafts

**Expected behavior**

All new posts from my blog would be showing up as drafts in the dashboard.

**Screenshots**

![image](https://user-images.githubusercontent.com/1128784/99983204-8de7bf00-2d79-11eb-8075-444bff68588c.png)

**Desktop (please complete the following information):**

- OS, version: Win10
- Browser, version: Not browser-specific, although I'm currently using FF80

**Additional context**

- dev.to account: `@markerikson`
- RSS feed URL: https://blog.isquaredsoftware.com/index.xml

![image](https://user-images.githubusercontent.com/1128784/99983319-b4a5f580-2d79-11eb-808f-1a933260eda6.png)

**Comment by cmgorton** [comment]
Hey @markerikson . Trying to follow up on issues that haven't had a response yet. Can you confirm this is still an issue for you. If so I can ping an engineer to see if they can give us any more info on why this might be occurring. Thanks!

**Comment by markerikson** [comment]
Can definitely confirm this is still an issue.  The settings panel says that the feed was fetched as of today (Feb 1), but the latest auto-created draft is from 2019 (and I put up some new posts within the last couple weeks).

**Comment by cmgorton** [comment]
Thank you for confirming @markerikson . 

@forem/squad anyone have any ideas on why this might be happening. I have seen this issue come up before in support as well.

**Comment by cmgorton** [comment]
This older issue might be related #3996

**Comment by maestromac** [comment]
@markerikson It's because all the URLs in your feed's `<link>`, guide, and image href are missing the http/https schemes. Try searching for `//blog.isquaredsoftware.com` in your https://blog.isquaredsoftware.com/index.xml and you should see it.

**Comment by markerikson** [comment]
Hmm. Okay, yeah, will try poking at that and see what happens.

**Comment by markerikson** [comment]
Bingo, that was it!  Fixed the URL in my blog settings, republished, and re-fetched the feed, and now I see the new posts as drafts:

![image](https://user-images.githubusercontent.com/1128784/106535458-45105d00-64c4-11eb-986a-b5cf4f899d53.png)

So apparently this was all my fault :)  Appreciate you investigating the issue!

Will look at trying to edit some of these and publish them in the near future.  Thanks!
