### ISSUE TITLE
(UX Issue) User IDs are wrapping round in table within `/admin/users`

### ISSUE THREAD

**Issue by msarit** [forem/forem#11577]
**Describe the bug**

For some IDs that are double digits, the numbers appear stacked on top of one another (ie wrapped). See the screenshot below:

![Screen Shot 2020-11-23 at 11 52 28 AM](https://user-images.githubusercontent.com/32520970/99991197-bfb15380-2d82-11eb-8ef5-049b141343e9.png)

**To Reproduce**

1. Navigate to `localhost:xxxx:/admin/users` as a user with `:super_admin` role.
To add `:super_admin` role to your localhost user, in the rails console, run `User.find(<ur-user-id>).add_role("super_admin").save!`
2. If there are users whose IDs are double-digits, you should see the individual digits of these IDs stacked

**Expected behavior**

The individual digits of the users' IDs should appear adjacent to each other, like normally-appearing numbers.

**Desktop (please complete the following information):**

- OS, version: macOS Catalina 10.15.7
- Browser, version: Chrome Version 87.0.4280.67 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
Did not test on mobile

**Additional context**

As a potential solution, one could apply the CSS property `white-space: nowrap` to the IDs column.

**Comment by ludwiczakpawel** [comment]
@Ridhwana wasn't that fixed by one of your PRs? (can't find the link :()

**Comment by rhymes** [comment]
@ludwiczakpawel it was https://github.com/forem/forem/pull/12076

can confirm it's working
