### ISSUE TITLE
BUG: Email Links in Admin to Email Messages 404

### ISSUE THREAD

**Issue by mstruve** [forem/forem#11578]
In our admin area, we have links that allow admins to view email messages sent to users.  Currently, these links throw a 404 which you can see in my development environment below. 
![Screen Shot 2020-11-23 at 12 24 52 PM](https://user-images.githubusercontent.com/1813380/99994474-ab6b5780-2d7e-11eb-95f7-1a22a2879ff1.png)
![Screen Shot 2020-11-23 at 12 25 08 PM](https://user-images.githubusercontent.com/1813380/99994478-ac03ee00-2d7e-11eb-99f1-e8113ea5955b.png)

We currently moved from `resource_admin` to `admin` which is likely why a bunch of these have broken. We need to update our routing to ensure those links return an actual page and not a 404. 

@michael-tharrington feel free to weigh in on this.

**Comment by michael-tharrington** [comment]
That's right!  We renamed `/admin` to `/resource_admin` some time ago, but didn't update the way these links work. If we can update this, then they should be easily reachable again.
