### ISSUE TITLE
Prevent duplicate charges when purchasing credits

### ISSUE THREAD

**Issue by mstruve** [forem/forem#11588]
A user recently wrote in about accidentally purchasing more credits than they intended. They said the button didn't appear to register when they tried to purchase 5 credits, so they hit it multiple times and purchased 15 credits by mistake.

We should lock this button or put a warning near it to prevent users from hitting it multiple times.

**Comment by cmgorton** [comment]
@mstruve do you know if this is still an issue? If so, we should probably add it to `issues to be reviewed` for next planning period.

**Comment by mstruve** [comment]
Yes, it looks like you can still hit the purchase button twice, we should prevent that.
