### ISSUE TITLE
Automatically resize profile images that are > 2MB instead of failing during sign up

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11585]
**Is your feature request related to a problem? Please describe.**
As a Forem community member, I want to upload a profile photo without it failing due to size limits.  Currently, I'm getting the "Error: Profile image File size should be less than 2 MB" error.

**Describe the solution you'd like**
It doesn't fail.  Maybe it accepts the upload and resizes in the background or something.

**Additional context**
This is especially problematic when it impacts users in the `/users/sign_up?state=email_signup` flow.

cc @maestromac who has worked on similar issues

**Comment by maestromac** [comment]
2MB is fairly standard for the user's profile image. For reference, here are other sites and their size limit

Gravatar: 1MB
Twitter: 2 MB
Stackoverflow: 2MB
Github: 1MB
Facebook & Google: much larger(>10 MB?) because they have the infrastructure in place that handles it.

It seems like this is rarely an issue in the past because we would just grab the already optimized images from Twitter or Github. Can you explain further what you mean by `/users/sign_up?state=email_signup`? This is when users decide to upload it themselves?

**Comment by pkfrank** [comment]
> Can you explain further what you mean by `/users/sign_up?state=email_signup`?

I mean it's a bigger issue when it prevents someone from even **registering** IE [here](https://the.community.club/users/sign_up?state=email_signup), as opposed simply updating their profile image via `/settings` (after already being registered).

**Comment by maestromac** [comment]
@pkfrank ah I misunderstood the problem. It's a weird flow to require the user to upload a profile image just to register an account but it's also unacceptable that we show the error after they click `sign up`.

the quick fix I can think of is to update the field to say max 2MB or have some kind of script that quickly checks their file size. I think the more ideal solution would be to remove the image requirement on sign up.  Even if we have a resizing solution in place, I would only allow authenticated users to access it.

**Comment by pkfrank** [comment]
> I think the more ideal solution would be to remove the image requirement on sign up. Even if we have a resizing solution in place, I would only allow authenticated users to access it.

I'd agree with this as the ideal flow.  This is probably a question for Product about whether we'd be okay with moving that profile photo upload step into the onboarding flow.

**Comment by thevinitgupta** [comment]
I would like to contribute on this issue.

**Comment by maestromac** [comment]
We updated this to 8 MB recently which made this issue slightly irrelevant.
