### ISSUE TITLE
Update styling on /admin/tags/{tag-id} to add visual clarity to fields

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11582]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin modifying a tag, it's a bit difficult to quickly visually scan which input fields are associated with each field name.

**Describe the solution you'd like**
More padding/margin around the fields, so that it's visually easier to know which input field is associated with each field name.

**Additional context**
Visible on `/admin/tags/{tag-id}`

Screenshot:
![page example](https://p241.p3.n0.cdn.getcloudapp.com/items/z8u4J5nr/Image%202020-11-23%20at%2012.28.53%20PM.png?v=af6fa4ef3cf13c30fae7c89cf0934d71)

**Comment by katiedavis** [comment]
Hi @pkfrank! It looks like this one has already been completed. Just wanted to confirm you're seeing the same on your end now before I close.
<img width="781" alt="Screen Shot 2021-01-14 at 3 04 02 PM" src="https://user-images.githubusercontent.com/15366319/104643157-f8322700-5679-11eb-9488-4c0778428278.png">

**Comment by pkfrank** [comment]
Thanks, @katiedavis, looks great.  I'll go ahead and close this issue.
