### ISSUE TITLE
Refactor magic numbers for `/comments` rendering

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#11594]
**Describe the Issue**

As mentioned in [this PR comment](https://github.com/forem/forem/pull/11199#discussion_r515696051), right now, we have some hardcoded "magic numbers" in the `/comments` route when it comes to deciding how many comments to render. Other Forem instances might want to change this down the road, and this might become configurable. Even if it doesn't, right now, we have to change it in a couple of places -- it's easy to update the controller and accidentally forget to update the view.
**Ideal Solution**

We should probably extract these into a single constant to start, which will enable us to easily make this something we can configure fairly easily down the road.

**Additional Context:**

Relevant context lives in this [controller](https://github.com/forem/forem/blob/5d9d1525d25c283f461878a5b147ff5b9bcbb574/app/controllers/stories_controller.rb#L310) and this [view](https://github.com/forem/forem/blob/997d5c1b885b5d23e6dd16e4a4684c8959548154/app/views/users/_comments_section.html.erb#L40).

**Comment by cyrillefr** [comment]
Hello, I would like to work on this one.

**Comment by rhymes** [comment]
@cyrillefr please go ahead and thank you!

**Comment by djuber** [comment]
I think this is okay to close after https://github.com/forem/forem/pull/12323
