### ISSUE TITLE
Due to no fingerprinting in development, our current approach to cache in serviceworkers doesn't match production.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#11606]
We now cache assets in service workers because we need something more consistent than the memory cache due to purging assets on deployment with Forem Cloud.

But without fingerprinting it doesn't behave the same way in dev and prod.

This PR fixes the issue in a very straightforward way...

https://github.com/forem/forem/pull/11605

I suspect we could alternatively do this by examining the headers of the assets so they don't cache if they are not instructed to cache as they would in the typical memory cache.

Caching is, across the board, the #1 problem with mismatches between dev and prod, so this is not unlike other caching issues we face— However fixing this with an `if Rails.env.production?` conditional is particularly inelegant.

**Comment by mstruve** [comment]
Given we have greatly reduced our service worker usage I am assuming this can be closed.
