### ISSUE TITLE
Followup to renaming "banned" as "suspended" in Admin

### ISSUE THREAD

**Issue by msarit** [forem/forem#11602]
Re: Michael's suggestion [here](https://github.com/forem/forem/pull/11581#issuecomment-732534235), this issue seeks to complete the work started in [this PR](https://github.com/forem/forem/pull/11581).

Tasks to be completed in code:
- Update `banned` to `suspended` in `role.rb`
-  Update all usages of `banned` to the new term `suspended` throughout codebase

In production, would need to update all roles as follows:

```ruby
Role.find_by(name: "banned").update(name: "suspended")
Role.find_by(name: "comment_banned").update(name: "comment_suspended")
```

**Comment by msarit** [comment]
need to update this loop in `app/views/admin/users/_activity.html.erb`:

```ruby
<% @user.roles.each do |role| %>
   <% if role.name == "banned" %>
      <li>suspended</li>
   <% else %>
      <li><%= role.name %> <em><%= role.resource_name.to_s %></em></li>
   <% end %>
<% end %>
```

**Comment by msarit** [comment]
I made several attempts to tackle this issue, but kept getting overwhelmed with testing all touched functionality and ensuring nothing broke 😓

**Comment by jacobherrington** [comment]
I'm going to take a crack at this! Thanks for getting it documented and getting the ball rolling @msarit :+1:
