### ISSUE TITLE
Let's give /events some crayons, sidebar and generalisation love.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#11600]
I am beginning to use events to list out all the scheduled bouts across many MMA promotions within my Forem. I understand listing came along to replace events and now there are more requests from other Forem's to use events again. Yipee!

**Describe the solution you'd like**

Full sidebar left and right. If someone comes to an events page from a google search, I want them to get the whole Forem experience.
Generalisation of the categories for events.
Crayons on the HTML elements, a nice card for the image, maybe similar to what posts look like.
I think allowing comments per event would also be a great feature.

**Describe alternatives you've considered**

I haven't considered any  🙈

**Comment by ludwiczakpawel** [comment]
I've assigned myself to this issue - I'll try to tackle it with baby steps starting with at least some crayons love for now.
