### ISSUE TITLE
Article action overlapping the `Dev` icon

### ISSUE THREAD

**Issue by RehmatFalcon** [forem/forem#11610]
**Describe the bug**

When we scroll to the end of a page (article page), the article actions overlap with the `Dev` icon.

**To Reproduce**

1. Go to any article page
2. Scroll to the end of the page.

**Expected behavior**
The article action slips under the dev icon.

**Screenshots**
![bug](https://user-images.githubusercontent.com/28915667/100185927-22cef180-2f0d-11eb-8894-db68ed746498.jpg)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 86.0.4240.198

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by Link2Twenty** [comment]
It's because they're both `--z-sticky`

https://github.com/forem/forem/blob/81dfded1fc1356e976ea9d55ab55a71b26881027/app/assets/stylesheets/components/header.scss#L3-L9

You could do something like

```CSS
z-index: calc(var(--z-sticky) + 1);
```

**Comment by ludwiczakpawel** [comment]
(just for the record)

https://github.com/forem/forem/pull/11649#discussion_r532464082
