### ISSUE TITLE
My account marked as spam, even-though I'm legit user

### ISSUE THREAD

**Issue by empeje** [forem/forem#11612]
I just active again in dev.to from 1 year off, and when I export my post from medium & my blog site, my post got some likes and reactions, but *BOOOM* suddenly I marked as spam, how do I recover? This is bad experience.

my account https://dev.to/empeje

<img width="1579" alt="Screen Shot 2020-11-25 at 12 48 02" src="https://user-images.githubusercontent.com/11813607/100188274-76950700-2f1c-11eb-9376-508479ad3202.png">

**Comment by citizen428** [comment]
Sorry for the inconvenience, please email yo@dev.to, thanks!

**Comment by empeje** [comment]
@citizen428 emailing to yo@dev.to doesn't work, got no reply emailing for the past 4 days.

**Comment by citizen428** [comment]
@empeje Sorry to hear that. I'll let someone now, but Github is not the place for this type of issue.

**Comment by empeje** [comment]
Is there any dedicated support @citizen428? I tried multiple times but no reply.

**Comment by citizen428** [comment]
Please note that our support team was a bit less reachable due to the Thanksgiving holiday, somebody will hopefully get back to you soon.
