### ISSUE TITLE
Unable to save customization settings

### ISSUE THREAD

**Issue by HaveSpacesuit** [forem/forem#11616]
**Describe the bug**

Customization settings are not saved

**To Reproduce**

Navigate to https://dev.to/settings/customization and make some change (e.g., theme, editor version, experience level).
Click save at bottom of page.
There is no UI indication of anything happening.
If you reload the page, the settings are not saved.

**Expected behavior**

There should be an indicator that the settings are saved, and they should remain set when refreshing the page or navigating to the site later on.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 87

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
Hi @HaveSpacesuit, thanks a lot for notifying us. We were aware of the issue and just deployed https://github.com/forem/forem/pull/11615 - I'll notify you when that's live :-) 

Closing this in the meantime

**Comment by rhymes** [comment]
@HaveSpacesuit it's definitely live now, thanks for the patience!
