### ISSUE TITLE
Validate payment pointer in /settings/extensions

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11620]
**Is your feature request related to a problem? Please describe.**
As a user, I might typo or have another issue with my "payment pointer" and have it "fail silently" after adding it via `/settings/extensions`.  

**Describe the solution you'd like**
We validate the syntax of the payment pointer; either in the form somehow or upon saving the page.

**Additional context**
Here is guidance on the [Payment Pointer Syntax](https://interledger.org/rfcs/0026-payment-pointers/#payment-pointer-syntax).

This has impacted at least one person where the page wasn't WM streaming due to a leading space in the payment pointer input.

**Comment by kuei0221** [comment]
Hi @pkfrank , I would like to handle this issue 😄 

I have read the guidance you provided, and I want to check does the following validation make sense to your requirement:
1. invalid if contains any non-printable ASCII characters
2. invalid if not start with `$`

I will then add another before_save action to clean the leading space and trailing space.

**Comment by rhymes** [comment]
thank you @kuei0221, I've assigned you to the issue!
