### ISSUE TITLE
Add autocomplete mention for users while writing articles

### ISSUE THREAD

**Issue by Kvaibhav01** [forem/forem#11635]
**Is your feature request related to a problem? Please describe.**

When I want to add a post of another DEV user, currently I have to copy their profile link and make it look like the person is actually tagged. Like this in markdown:

> There is this wonderful post written by [@ vaibhavkhulbe] (https://dev.to/vaibhavkhulbe).

**Describe the solution you'd like**

I want that we should have the following feature while we tag others in a post or a comment etc:

1. As soon as I type '@' and type in a few letters of a username, a list should pop-up of a similar username from which I can pick the one I want.

2. The tagged person should be notified.

3. When someone clicks the tagged username, they should be redirected to their profile link.

**Describe alternatives you've considered**

N/A

**Additional context**

Here's something similar:
<img width="363" alt="Screenshot 2020-11-26 at 11 21 05 PM" src="https://user-images.githubusercontent.com/11731837/100381027-10a0a080-303e-11eb-8393-77fafe260d2d.png">

Or this:
<img width="287" alt="Screenshot 2020-11-26 at 11 21 47 PM" src="https://user-images.githubusercontent.com/11731837/100381072-2b731500-303e-11eb-84e1-43551b7393ab.png">

**Comment by rhymes** [comment]
Hi @Kvaibhav01, thanks for the request. I'm going to keep this open and rename it for articles, as we do have this previous one for comments https://github.com/forem/forem/issues/354

**Comment by cmgorton** [comment]
Hey @Kvaibhav01  
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. This particular feature is currently being put through the RFC process and should be on the pipeline to work on here in the near future. As we currently have this feature requests in an internal repo as well I am going to close this one here. Thanks for opening this and spurring a discussion.
