### ISSUE TITLE
Allow Forem admins to set a short description in forem.com/discover

### ISSUE THREAD

**Issue by leewynne** [forem/forem#11634]
**Describe the solution you'd like**

In site admin, a text area that allows a Forem admin to enter and update a short description about their Forem so it displays on forem.com/discover as not all Forems will have a descriptive logo.

**Additional context**

Current forem discover page. 

<img width="1919" alt="Screenshot 2020-11-26 at 17 24 57" src="https://user-images.githubusercontent.com/12694270/100379430-c81cbf00-300c-11eb-8a6e-189beaf09c24.png">

**Comment by cmgorton** [comment]
Looks like this may be resolved with the new layout. There are descriptions added to each Forem.
![forem discover page](https://user-images.githubusercontent.com/21039864/140995696-aaae68dc-b2f8-4dcc-9b80-bca38cae5e2b.png)
