### ISSUE TITLE
Filter out blocked users' posts from the feed and from the recommended articles

### ISSUE THREAD

**Issue by nobitagit** [forem/forem#11636]
**Is your feature request related to a problem? Please describe.**

If I block a user I would expect their posts not to appear on my feed or in my recommendations.
This doesn't happen currently.

Try this. 

1. Pick a very prolific user that always shows up in your feed and block them

![image](https://user-images.githubusercontent.com/2051152/100391663-6ec88600-3034-11eb-9c21-9c01f2d0710a.png)

2. Go to the homepage and look for a post of such user. This might need a few tries, but look, in this case it's even featured as the first one.

![image](https://user-images.githubusercontent.com/2051152/100391716-9e778e00-3034-11eb-8e06-62b10ebc2849.png)

**Describe the solution you'd like**

As per title, filter out posts from that user from the feed and from the "read next" recommendations at the bottom of an article.

**Describe alternatives you've considered**

None? Maybe blocking is a crude way to influence the recommendation algorithm, but still the basic idea applies I guess. If I block, I shouldn't see posts of that user.

**Additional context**

This _might_ be somewhat relevant to the discussion raised in Ben's article [Improving the way DEV elevates the good stuff](https://dev.to/devteam/improving-the-way-dev-elevates-the-good-stuff-39an).

By filtering unwanted content hopefully a person's preferences will get more "weight" when aggregating the feed.

**Comment by karnett** [comment]
This should also be taken into account with user notifications.

If user A blocked user B, user B should not show up in their notifications as a reply to the thread.
