### ISSUE TITLE
Publish button disappear on draft

### ISSUE THREAD

**Issue by Eomm** [forem/forem#11637]
**Describe the bug**

A saved draft post with some meta-markdown, doesn't have the "publish" button and the `publish: true` meta doesn't work as well.

**To Reproduce**

- create a draft post with this content:

```
---
title: Demo
series: Demo
---

Hello
```

- save it
- edit it to publish but the button is missing

**Expected behavior**

The publish button should appear as well

**Screenshots**

Draft with meta

![Immagine 177](https://user-images.githubusercontent.com/11404065/100393486-13999200-303a-11eb-871b-0244d2acd432.png)

Draft without meta (after saving)

![image](https://user-images.githubusercontent.com/11404065/100393529-3deb4f80-303a-11eb-8682-1250a64df6ef.png)

**Desktop (please complete the following information):**

- OS, version: win 10
- Browser, version: chrome 86

**Additional context**

The draft demo post

**Comment by rhymes** [comment]
@Eomm the publish button is only present in v1, if you want to publish a draft articles that doesn't have the publish attribute, you must add `published: true` (not `publish`) in its front matter. So something like:

```markdown
---
title: Demo
series: Demo
published: true
---

Hello
```

Let me know if that works

**Comment by Eomm** [comment]
Oh! I was using `publish: true` instead of `published: true`

Sorry for that
Thank you for your time!
