### ISSUE TITLE
New liquid tag for events

### ISSUE THREAD

**Issue by leewynne** [forem/forem#11631]
**Describe the solution you'd like**

When I am writing an article especially a newsletter, I would like to be able to include a liquid tag for an event that I may have created.

**Describe alternatives you've considered**

Image links 🙈

**Comment by cmgorton** [comment]
Hey @leewynne for context is this for the event listings [like these](https://dev.to/listings)?  Or a different kind of event?

**Comment by cmgorton** [comment]
Oh I see, it is for events like Ben mentioned [here](https://github.com/forem/forem/pull/10837) right? 

We do have a liquid tag for listings but I do not believe we have one for events yet. I will add this to a feature backlog so we can keep track of this. Thanks for the feature request.

**Comment by cmgorton** [comment]
Hey Lee! As you have probably seen recently we have a new process for feature requests.  
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
