### ISSUE TITLE
Disable auto parameter wrapping for JSON

### ISSUE THREAD

**Issue by rhymes** [forem/forem#11645]
**Describe the bug**

Forem has been running with this feature on for a while but we explicitly require the root object, eg, `{"article": {"title": ""}}` in most of our incoming payloads. Having this enabled means that a user can send a payload like `{"title": ""}` (without the root object) and that will still be accepted, because Rails will auto wrap that in the root object, see https://api.rubyonrails.org/classes/ActionController/ParamsWrapper.html

The problem here is that autowrapping doesn't seem to be working correctly with all kinds of parameters, leaving the object created by the payload in an unknown state, see https://github.com/forem/forem/pull/11638

Thus it'd be best to disable auto wrapping (or leaving it enabled and disable it in those JSON routes where we explicitly request the root object)

**To Reproduce**

1. create an article with the following payload:

```json
{
        "title": "A test post again",
        "description": "Testing article creation bug again",
        "body_markdown": "## Some content",
        "tags": ["javascript"]
}
``` 

1. load the article from the DB and notice how it doesn't have any tags

**Expected behavior**

Sending the following payload should result in an error:

```json
{
        "title": "A test post again",
        "description": "Testing article creation bug again",
        "body_markdown": "## Some content",
        "tags": ["javascript"]
}
```

because it's not in the correct format, it should be:

```json
{
  "article": {
        "title": "A test post again",
        "description": "Testing article creation bug again",
        "body_markdown": "## Some content",
        "tags": ["javascript"]
  }
}
```

**Additional context**

This requires a bit of investigation server side, because it might lead to other errors if there are any internal requests that wrongly rely on this automatic wrapping. We should also investigate if we receive many API requests that silently succeed though they are in the wrong format.

**Comment by citizen428** [comment]
> This requires a bit of investigation server side, because it might lead to other errors if there are any internal requests that wrongly rely on this automatic wrapping. 

I thought no internal code relies on routes in `/api` anymore, I remember working on this a few months ago.

**Comment by rhymes** [comment]
@citizen428 auto wrapping is enabled from any route that sends JSON data, so not only the public API but the internal JSON routes as well, that's why we need to be careful in case some send "malformed" data

**Comment by citizen428** [comment]
Gotcha, I misunderstood what you meant originally.
