### ISSUE TITLE
Sticky Header Banner

### ISSUE THREAD

**Issue by ZoeDreams** [forem/forem#11644]
**Is your feature request related to a problem? Please describe.**

It would be pretty rad to make the header sticky so when you scroll down on long articles you always have access to to the header. I find myself having to scroll to the top a lot to click on the dev icon to get to the home. I also think this would make the UI much more fluid with very little overhead

**Describe the solution you'd like**

super simple to implement sticky header
https://www.w3schools.com/howto/howto_js_sticky_header.asp

**Describe alternatives you've considered**

N/A

**Additional context**

Thank you! Also maybe add in a smooth fade or something with css3 @keyframes. This can be done with very little if any script at all.

Also maybe having the search box fluid so it stretches over to the write post button. this would make it much easier to click onto the search box and tighten up the design.. The header area of browsers employ this look and feel.

If I get some time over the next week, ill try to look into contributing this feature. ~2hour of work.

**Comment by rhymes** [comment]
Hi @ZoeDreams - it's already available, in https://dev.to/settings/customization in the section "Site Navbar", if you change the setting, it will remain sticky. Hope this helps!
