### ISSUE TITLE
Broken UI on firefox #bug

### ISSUE THREAD

**Issue by shiling** [forem/forem#11641]
Hi there, 

Been a while since I've popped into dev.to, but was disappointed to find bugs viewing dev.to on Firefox (MacOs, 82.0.2 (64-bit)). I've captured screenshots of what I see on Firefox, vs. what it should look like based on Chrome, and annotated the screenshots below to highlight the issues. 

![dev-to-firefox-bugs](https://user-images.githubusercontent.com/2376845/100409768-b3413980-30a7-11eb-932c-c836cf058c60.png)

Issues: 
1. heart, unicorn reactions and bookmark counters are not displayed, instead showing a grey box
2. follow button for the author is missing text (I think this is pretty severe)
3. What's going on with the "add to discussion" controls?
4. Layout of article comment's is broken, e.g. no padding, author's profile image is squished, layout of the top and bottom controls are broken

For reference - I was reading this article:
[The importance of software testing](https://dev.to/karllhughes/the-importance-of-software-testing-5gn8)
😅

**Comment by citizen428** [comment]
I use dev.to daily in Firefox on macOS and cannot reproduce this. 

![Screen Shot 2020-11-27 at 11 53 17](https://user-images.githubusercontent.com/47985/100412422-3ca43c00-30a7-11eb-9200-395e7d42c2cf.png)
![Screen Shot 2020-11-27 at 11 53 21](https://user-images.githubusercontent.com/47985/100412426-3dd56900-30a7-11eb-995a-982e63557fdb.png)
![Screen Shot 2020-11-27 at 11 53 44](https://user-images.githubusercontent.com/47985/100412428-3e6dff80-30a7-11eb-960f-daaed94eb749.png)

Can you please do a hard refresh to make sure this is not some asset caching issue?

**Comment by shiling** [comment]
Oh, you are right. I opened dev.to in Firefox's private window, and the issues when away. Thank you!

Perhaps my regular FF session was loading some outdated assets because it's been a while since I've visited the dev.to.
