### ISSUE TITLE
`Beloved Comment` link takes me to someone else's comment

### ISSUE THREAD

**Issue by carmenhchung** [forem/forem#11651]
**Describe the bug**

I noticed that on my profile page, I've been awarded the Beloved Comment badge. When I click on the blue "This is the comment..." link (shown below), it originally took me to someone else's comment on a different post (one that I've never commented on/seen before: https://dev.to/siy/comment/pobn). Today it took me to an entirely different comment (https://dev.to/robole/comment/18530).

<img width="1438" alt="Screen Shot 2020-11-18 at 9 46 30 am" src="https://user-images.githubusercontent.com/30306087/100537795-99f2e580-327f-11eb-9ba4-c670cdc06242.png">

**To Reproduce**

1. Go to Notifications page.
2. Click on `_This is the comment_ for which you are being recognized.`

**Expected behavior**

For me to be taken to the comment that I was awarded the Beloved Comment badge for.

**Screenshots**

See above.

**Desktop (please complete the following information):**

- OS, version: Mac OS Catalina 10.15.7
- Browser, version: Chrome Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by carmenhchung** [comment]
Apologies, I just saw that this issue has already been reported here! https://github.com/forem/forem/issues/11646

**Comment by rhymes** [comment]
No worries @carmenhchung, I'm going to close this in favor of #11646
