### ISSUE TITLE
Upgrade “username is taken” message by offering link to username

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#11686]
**Is your feature request related to a problem? Please describe.**

Sometimes when a user signs up to a community and tries to claim a username they receive the message:

`Whoops we found 1 problem - Username is taken.`

**Describe the solution you'd like**

I think it'd be great if we could provide a link to the taken username within the error message.

`Whoops we found 1 problem - Username: [x](https://dev.to/x) is taken.`

**Describe alternatives you've considered**

N/A

**Additional context**

This isn't high priority, but I think would make for a nice enhancement.

**Comment by VictorSNA** [comment]
Hey, I would like to work on this one please!

**Comment by juliannatetreault** [comment]
Thanks for taking this on! I've assigned this issue to you @VictorSNA. 😄

**Comment by VictorSNA** [comment]
Hi, sorry can you unassign that issue please. I tried to setup with docker and podman but it's not working properly and taking too much time. I only have half of mondays to contribute open-source projects in my enterprise and the idea was fast and easy issues. Thank you and sorry for the incovenience.

**Comment by juliannatetreault** [comment]
No worries and thanks so much for the update, @VictorSNA! I've unassigned the issue. Thank you so much for being a part of our awesome Forem community. 😄

**Comment by meaganewaller** [comment]
Hi! I'd like to pick this issue up, thanks! 😄

**Comment by vaidehijoshi** [comment]
Hi @meaganewaller! 👋🏽 

Thanks for your work on this so far, and apologies for jumping in late here :) I wanted to chime in here from a product perspective. I think we should not link to the username's profile as a part of this change. There are some privacy implications here (and linking to a user's profile could actually open up a user to harassment in some cases!), and I think in some scenarios, linking to a user's profile could also result in broken links/404's. 

Let's re-scope this task such that we don't link to the user's profile when we tell a potential new user that the username is unavailable. This will ensure that we don't inadvertently expose people's profiles to people who aren't a part of a community yet :)

Apologies for the last-minute change here, and thank you for taking this on!

**Comment by meaganewaller** [comment]
@vaidehijoshi Completely understandable, and I appreciate that insight. I definitely want to err on doing the least potential harm to the community members, and thinking about vectors for harassment is so important, so thank you for that thoughtfulness. 

What are the implications of that for this feature? Do we want to display a new error message instead of 

```
Whoops we found 1 problem - Username: [x](https://dev.to/x) is taken.
```

We will have the display be something like this?

```
Whoops we found 1 problem - Username [username] is taken.
```

**Comment by vaidehijoshi** [comment]
@meaganewaller Yeah, I think we could keep the error message but just without the link. 

So, for my username, it would read:
`Whoops we found 1 problem - the username vaidehijoshi is taken.`

**Comment by meaganewaller** [comment]
@vaidehijoshi Gotcha! Will push up this change this evening after work ✨

**Comment by vaidehijoshi** [comment]
> @vaidehijoshi Gotcha! Will push up this change this evening after work ✨ 

No rush at all! Take your time :)
