### ISSUE TITLE
RSS Feed is.. ugly

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#11688]
**Describe the bug**
The [RSS Feed](https://dev.to/feed) is very ugly. Can't read correctly the text 😶

**To Reproduce**

1. Go to dev.to/feed
2. Expect the ~~beautiful~~ ugly design

**Desktop (please complete the following information):**

- OS, version: —
- Browser, version: —

**Additional context**

Good day! 🎀🕺

**Comment by rhymes** [comment]
Hi @thomasbnt, the feed is meant to be consumed by parsers, so I'm not exactly sure what you mean here.

I checked and it's served correctly:

```shell
~ curl -I https://dev.to/feed | rg content-type
11:content-type: application/rss+xml; charset=utf-8
```

I'm going ahead and close this as there are no actionable as well.

**Comment by thomasbnt** [comment]
Hello @rhymes, I use RSS Feed with the simple URL and IFTTT. For read the content manually and check if in input is available, isn't good 😄

**Comment by rhymes** [comment]
@thomasbnt cool, but that's the official RSS content type. It also depends on the browser. Firefox downloads it, Safari tells me I have to install a RSS reader application, Chrome and Edge render the XML inline 🤷 

I know some servers use `application/xml` which is a bit more browser friendly but if you install a RSS reader extension you should be able to check it nonetheless.

**Comment by thomasbnt** [comment]
Yeah of course! I understand that, this issue was created because for me it's not effective to read this (under Chrome) and pick up some data's or tags. I use that to one of app and I pick some tags, not all 😄
