### ISSUE TITLE
User sign up error on Forem Community

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#11697]
**Describe the bug**

Users are unable to sign up on the Cluster Employment Platform - https://www.clusteremployment.com. After filling in the required details and clicking sign up, the site loads an error page and the user is shown as signed up (but with no confirmation email/instructions).

**To Reproduce**

1. Open https://www.clusteremployment.com
2. Click Create Account
3. Click Sign Up with Email
4. Fill in the required fields
5. Click Sign Up

**Expected behavior**

The usual behavior - users fill in the required fields, click sign up and are told they have received confirmation instructions. Upon confirmation of account, user signs up and is taken through the platform.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Microsoft Windows 8.1 64-bit
- Browser, version: Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

This is the second time the error is occurring on the Cluster Employment Community.

**Comment by AdekunleA** [comment]
Just following up on this problem :)

**Comment by rhymes** [comment]
Hi @AdekunleA, I've notified the team internally, we'll get back to you as soon as possible, thank you!

**Comment by AdekunleA** [comment]
Thanks! @rhymes
