### ISSUE TITLE
Images don't always show in Forem Cloud hero campaign banners.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#11694]
**Describe the bug**

When creating a HTML variant for the campaign hero banner, if you insert an image from a URL - sometimes the image shows, sometimes it doesn't and instead it shows just the alt text.

**To Reproduce**

Login to forem.dev or another FSS hosted forem.
Go to admin then html_variants
Create a new campaign banner and insert an image from a url.
Approve and publish the HTML variant
Under config > campaign insert the name of the HTML variant so it shows on the home page as a hero banner.

During refreshes (it takes time) observe that sometimes the image is displayed, sometimes it isn't.

**Expected behavior**

Image to be displayed consistently

**Screenshots**

<img width="586" alt="Screenshot 2020-12-01 at 14 37 25" src="https://user-images.githubusercontent.com/12694270/100754284-cecb7d80-33e2-11eb-9da4-0a68dff65667.png">

**Desktop (please complete the following information):**

- OS, version: MacOS BigSur
- Browser, version: Chrome, latest stable release

**Smartphone (please complete the following information):**

- Device: iPhone
- OS, version: iOS14
- Browser, version: Safari

**Additional context**

**Comment by leewynne** [comment]
this might be related to the size of the image being used, will report back.

**Comment by maestromac** [comment]
Thanks for reporting this issue @leewynne ! I will look into it.

**Comment by leewynne** [comment]
This is now fixed

**Comment by leewynne** [comment]
https://github.com/forem/forem/pull/11917
