### ISSUE TITLE
Fully blocked: 404 when trying to edit/create a post

### ISSUE THREAD

**Issue by Offirmo** [forem/forem#11690]
**Describe the bug**

From the dashboard or the blogpost itself, I can't edit my blogposts anymore. I get a 404:

<img width="793" alt="Screen Shot 2020-12-01 at 16 25 50" src="https://user-images.githubusercontent.com/603503/100700717-30471880-33f2-11eb-9b67-f7300d2d4c60.png">

It started to happen around last Saturday, I waited to see if the bug would disappear, still here.

I disabled all extensions and cleared the site data, no success.

**To Reproduce**

1. Log in
1. Go to your dashboard
1. pick any blogpost (draft or published) and click "edit"

**Expected behavior**

I should see the editor

**Screenshots**

<img width="793" alt="Screen Shot 2020-12-01 at 16 25 50" src="https://user-images.githubusercontent.com/603503/100700717-30471880-33f2-11eb-9b67-f7300d2d4c60.png">

**Desktop (please complete the following information):**

* macOS Catalina latest
* chrome latest, all extensions disabled

**Additional context**

I started using "dev-to-get" following the instructions of those blogposts:
-  https://dev.to/maxime1992/manage-your-dev-to-blog-posts-from-a-git-repo-and-use-continuous-deployment-to-auto-publish-update-them-143j
-  https://dev.to/beeman/automate-your-dev-posts-using-github-actions-4hp3

Could that have messed up things?

**Comment by cmgorton** [comment]
The edit functionality is working for me on both draft posts and already published posts. I have tried on Chrome and Firefox and can't reproduce the bug. 

@Offirmo Have you tried editing posts since you started using "dev-to-get"? Did this only start happening after you started using that or have you been able to edit before while using the "dev-to-get" you mentioned?

**Comment by Offirmo** [comment]
@cmgorton It worked previously.
I started using dev-to-git on a single existing post, it worked I could edit the draft.
I extended my usage of dev-to-git to a second post, freshly created, then I could no longer edit any post.

Yes, my suspicion is the API calls messed up something or triggered a bug in dev.to.

**Comment by Offirmo** [comment]
I'm still completely blocked.

Could someone look into it?

I have nothing secret on dev.to and can share my credentials if needed.

**Comment by Offirmo** [comment]
Btw none of my previous public blogposts can be accessed anymore:
* https://dev.to/offirmo/learn-javascript-in-2020-a-refreshed-list-of-resources-44o0
* https://dev.to/offirmo/heroku-pipelines-easy-free-580g

In short, my account is completely broken.

**Comment by fdoxyz** [comment]
Hi @Offirmo, I can see something is off on your posts. I just saw your recent comment and I'm getting redirects and the pages of your posts fail to load.

I'll try to investigate bit more what may be causing this. 

Quick question: Does https://dev.to/dashboard and https://dev.to/settings load correctly for you?

Also to confirm: You're not experiencing any problems logging out and then back in, right?

**Comment by Offirmo** [comment]
@fdoxyz I tested what you suggested:
- dashboard: OK
- settings: OK
- loggin out: OK
- loggin in: OK
- dashboard and logging still ok

**Comment by Offirmo** [comment]
@fdoxyz not sure it's you, but it works again!
