### ISSUE TITLE
Too many redirects, 301 errors, but /GET says "OK" when making the request. 

### ISSUE THREAD

**Issue by Montana** [forem/forem#11699]
Hey fellow Developers, 

When I click on my post: https://dev.to/Montana/a-short-journey-into-source-control-branching-and-release-patterns-5e05, it just hangs, on further inspection it says "too many redirects". This is also true on another post (that used to work).  It also says when I click "manage" "it does not exist" and I receive a `404` with a variant of `timeout` and `ERR_TOO_MANY_REDIRECTS`. 

This would also happen to be true with: https://dev.to/Montana/encrypting-sensitive-data-using-the-travis-cli-tool-2eff

It makes no sense, as other things I have posted work just fine, and I know the above link worked until Sunday. Upon further investigation with the dev console, I get:

```javascript
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
```
This is for the `git` branching tutorial, and with the article about Encrypting Sensitive Files, it has 6 likes, so it's obvious at one point in time it was accessible. While running a test on that particular article using the dev console, I also got: 

```javascript
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
```
So it's a little difficult to determine the nature of the redirect loop, or why it's happening. Checking it again with `httpstatus.io` I just get `status code: Error`. 

Things I've done before asking: 

- Cleared my cache
- Delete relevant cookies 
- The classic "restart browser" 

Thanks any help is appreciated, for reference I've attached some relevant screenshots:

<img width="755" alt="console" src="https://user-images.githubusercontent.com/20936398/100862870-952d5d80-3448-11eb-8d62-bd52a50a9efd.png">
<img width="738" alt="console2" src="https://user-images.githubusercontent.com/20936398/100862876-978fb780-3448-11eb-8f2c-4fba620466fb.png">
<img width="721" alt="Screen Shot 2020-12-02 at 3 47 11 AM" src="https://user-images.githubusercontent.com/20936398/100868895-1983de80-3451-11eb-97ef-f5f6bea52052.png">

For reference, the first two are the initial redirect error, the third photo is the traffic trying to figure out what it's redirecting to. There's no _real_ clues. So right now I'm currently making a request, and this is what's happening via the `301`'s error you see next to the waterfall (in the dev console): 

```http
GET /directory HTTP/1.1
https://dev.to/Montana/a-short-journey-into-source-control-branching-and-release-patterns-5e05
```
Then returning something like:

```http
HTTP/1.1 301 Moved Permanently
```

What confuses me the most is when it makes a request, it succeeds with a `200`. Semantically speaking, `200 OK` is the standard response for successful HTTP requests. I'm aware the meaning of a success depends on the HTTP request method, but it appears `/GET` is being used, rather than say `POST` or something. 

The way to trouble shoot this type of problem (or at least I do usually) is to actually watch the requests your browser is making to the server. You should be able to see multiple individual requests before this error comes up, and in this particular case, as per usual after taking a second look, I do see multiple requests being made.

**Comment by Montana** [comment]
The fix for this (at least for now) for whatever reason is archiving the post, then unarchiving. Strange.

**Comment by rhymes** [comment]
Thank you @Montana, it's weird indeed. I wonder if it has something to do with caching

**Comment by Montana** [comment]
Thanks @rhymes! That's what I was leaning towards as well. Have a wonderful weekend.

**Comment by cmgorton** [comment]
Hey @Montana wanted to follow up on this bug. Is this still an issue for you? Or something you have seen again on DEV? Asking because we have made a lot of changes to caching recently.

**Comment by Montana** [comment]
Hey @cmgorton, 

I have not experienced this in awhile - thank you so much. I really appreciate it.

**Comment by cmgorton** [comment]
Thanks for the follow up. I am going to close this issue for now since it appears to be resolved. If you see if happen again in the future please let me know and we will open this back up!

**Comment by Montana** [comment]
Perfect, and again thank you for being so helpful @cmgorton!
