### ISSUE TITLE
Generalize social image for /pod

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11708]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin, when I use my `/pod` link, it is showing DEV-specific imagery.

**Describe the solution you'd like**
A generic "social image" for `/pod`.

**Additional context**
It might be good to do a little "audit" of any outstanding social images that are DEV-specific on various pages around the app.

Example screenshot:

![screenshot of sharing /pod in slack](
https://p241.p3.n0.cdn.getcloudapp.com/items/ApuGOW8x/Image%202020-12-02%20at%2012.40.36%20PM.png?v=68b591e74a6d055d05e84a4d756a2c1c)

**Comment by jessleenyc** [comment]
Noticing that this is still an issue on the CodeNewbie Forem: https://community.codenewbie.org/pod

**Comment by benhalpern** [comment]
Fixed here. https://github.com/forem/forem/pull/12280

**Comment by vaidehijoshi** [comment]
Closing this since https://github.com/forem/forem/pull/12280 seems to address it. Please feel free to reopen if it appears that this issue has not been resolved!
