### ISSUE TITLE
Support "Anyone with the link" style view-only options for posts on private Forems

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11716]
**Is your feature request related to a problem? Please describe.**
As an author publishing posts in a private Forem, I am not able to share those posts with someone that isn't part of the community.  That's certainly _intended behavior_, given that if you don't have access to the community, you shouldn't be able to read a post in that community.

With that said, plenty of applications provide a mechanism to provide an "Anyone with the link" view-only option to an otherwise-private document.  Off the top of my head... Google Docs, Notion, Figma, etc.

**Describe the solution you'd like**
An option to share a view-only version of my post using an "Anyone with the link" option.  The recipient should be able to see the original post, but not the surrounding content (suggested articles, comments, etc).

**Describe alternatives you've considered**
On public forems, authors are able to send a "Preview" link that exposes an un-published draft.

On private forems, this method won't work, as the content is (by design) private.

**Additional context**
I think this would actually be a pretty powerful feature.  A few use-cases:

- A creator in a "Subscribers Only" Forem wants to offer a teaser of the content one can expect from the inside.  The reader is motivated to join the community in order to read more, and to participate in the comments.

- Having outgrown Slack, a company has adopted Forem for internal purposes.  People are sharing helpful write-ups that they'd like to send to their co-workers.  Right now, there's extra friction, as those co-workers would need to be part of the community in order to read the article.

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
