### ISSUE TITLE
Add ability to "pin" post to the top of feed

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11713]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin, I don't have the ability to "pin" a post to the top of the feed.  I can mark it as Featured and take some other incremental steps, but it won't strictly "pin" the post to the top.

This is very common in classic internet forums — oftentimes called a "sticky."

**Describe the solution you'd like**
An ability to pin posts to the top of the feed.

Ideally, this would be possible for both the main feed, along with the feed on tag pages.

**Additional context**
Authors can already pin posts to the top of the profile page.  Maybe we could use the same style / technical approach?  The feed probably has a whole different set of considerations...

I think a cool related feature would be giving tag moderators the ability to pin posts in their own tag.  That could be a separate follow-up consideration if/when we were to take this on.

**Comment by vaidehijoshi** [comment]
This is on track to be worked on by [RFC #25](https://github.com/forem/rfcs/pull/25), so I think we can close this issue out :)
