### ISSUE TITLE
Account for "Primary brand color" and the impact on link colors

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11719]
**Is your feature request related to a problem? Please describe.**
As a Forem admin, I can set my "Primary brand color" via `Config > User Experience and Brand`.  This color is applied to links across my Forem.

If I choose a very dark color, then `<a>` links might not have enough contrast relative to normal text.

**Describe the solution you'd like**
I'm not sure what the best solution here is.

Maybe _another_ color field for links?  That seems sub-optimal.

I do think it's a _very legitimate_ use-case that a Forem wants to use a very-dark primary brand color so we need to be thinking about this.

**Additional context**
Here's a live example from the [Code of Conduct page at Flowstate](https://www.flowstate.to/code-of-conduct).  These bullets are all links.

![links without enough contrast](https://p241.p3.n0.cdn.getcloudapp.com/items/wbuKmJ7K/Image%202020-12-02%20at%207.34.45%20PM.png?v=bed7a933348fde5db5671da0b54eeacf)

**Comment by rhymes** [comment]
Hi @pkfrank, I'm closing this in favor of the analysis that @marcysutton wrote down in https://github.com/forem/forem/issues/11504

I'll refer to your comment there as well
