### ISSUE TITLE
Canonical URL problem

### ISSUE THREAD

**Issue by CodeWithBishal** [forem/forem#11727]
few days ago I have started posting on Dev To and while posting I choose Canonical URL and put my blog post's URL now after few days when I have opened my search console, in most of the posts i am getting this error "URL is not on Google
This page is not in the index, but not because of an error. See the details below to learn why it wasn't indexed. Learn more"
and my website URL was not on google which is seriously creating a problem, now I have removed the Canonical URL and updated my sitemap but google search console is not updating it and "request indexing" option is not available. now please update your sitemap or whatever so that my URL will be live on google

**Comment by rhymes** [comment]
Hi @CodeWithBishal, is this related to this? https://github.com/forem/forem/issues/9509#issuecomment-732259221

Could you provide us with the two URLs?

Thank you

**Comment by CodeWithBishal** [comment]
actually its a total of 7 URLs

1st: https://www.codewithbishal.com/post-5959
2nd: https://www.codewithbishal.com/how-to-change-the-background-color-onclick-using-js
3rd: https://www.codewithbishal.com/how-to-get-the-current-time-javascript
4rd: https://codewithbishal.com/example/pure-html-budget-calculator-cwb
5th: https://www.codewithbishal.com/example/validate-email-address-using-javascript
6th: https://www.codewithbishal.com/example/create-a-sortable-list-with-draggable-items-using-javascript
7th: https://codewithbishal.com/example/javascript-countdown-timer

and if you want Dev post link you can find it from here : https://dev.to/codewithbishal  the first 7 links I am talking about 
note: I have told earlier again I am saying I have removed my blog links from the Canonical URL section

**Comment by rhymes** [comment]
@CodeWithBishal according to https://dev.to/codewithbishal/how-to-create-count-down-timer-using-javascript-code-with-bishal-28k2 that's your canonical URL. Can you force Google to refresh the canonical URLs? 

Also, if I search "How to Create Count Down Timer using JavaScript - Code With Bishal" on google.com the first result is DEV, the second is your blog. 

I think it was just a matter of time?

Let me know if there's anything else, I'm going to close this in the meantime as I'm not sure there's anything to be done here.

**Comment by CodeWithBishal** [comment]
![Screenshot_2020-12-04-18-05-46-13](https://user-images.githubusercontent.com/69814108/101164700-73f08b00-365b-11eb-8548-97788cb564f5.jpg)
I don't see my blog in the second position

**Comment by CodeWithBishal** [comment]
![Screenshot_2020-12-04-18-05-46-13](https://user-images.githubusercontent.com/69814108/101164891-bdd97100-365b-11eb-9e18-4c92b1507e2e.jpg)
I don't know where you found my blog in the second position

**Comment by rhymes** [comment]
@CodeWithBishal sorry, I mistakenly took the dribble url from your blog. I'm not sure what we can do on our side. The searche engine is behaving correctly: if the canonical result for that it's DEV, then it's normal that the first result is DEV's.

Also, I'm not sure where is the identical version of https://dev.to/codewithbishal/how-to-create-count-down-timer-using-javascript-code-with-bishal-28k2

**Comment by CodeWithBishal** [comment]
My blog is based on this topic but it's completely different from my post of Dev and i don't know why google is nit indexing it moreover there is no option for reindexing

**Comment by rhymes** [comment]
@CodeWithBishal I think you should direct your request to Google's support though from the Google console dashboard. Good luck!

**Comment by CodeWithBishal** [comment]
Okay... Thanks

**Comment by CodeWithBishal** [comment]
I had completed my Hactoberfest and have ordered a T-shirt but till now i haven't got the tracking details. Please help me
