### ISSUE TITLE
Multi-language page text support?

### ISSUE THREAD

**Issue by 0xC000005** [forem/forem#11739]
**Describe the solution you'd like**
Hi, I'm building my self-hosted forem, and I am trying to translate the text in the pages into Chinese. 
Then it occurred to me that if I translated in the main branch, it would not only help my site, but also help all developers who want to use the Chinese version of forem pages.

Is there any way I can contribute my translations to this amazing open-source project? 
If this precedent is successful, we can add more language support!

Chinese Version Welcome Page Demo: 
![Chinese Demo](https://raw.githubusercontent.com/0xC000005/image-hosting/master/20201203174700.png)
👆I made this up using f12 lol

**Comment by rhymes** [comment]
Hi @0xC000005, thanks for the inquiry. I'm going to close this as there are already two more focused issues related to i18n/l10n work: https://github.com/forem/forem/issues/304 and https://github.com/forem/forem/issues/3929

There's still some foundational work that needs to be planned before we kickstart this.
