### ISSUE TITLE
== Command ["foreman start -f Procfile.dev"] failed ==

### ISSUE THREAD

**Issue by alexanderjosepluthor** [forem/forem#11757]
1. after this: https://docs.forem.com/installation/linux/
2. then here: https://docs.forem.com/getting-started/start-app/
2.1 when run "bin/startup"

> == STARTING UP ==
10:23:23 web.1       | started with pid 1693
10:23:23 webpacker.1 | started with pid 1694
10:23:23 sidekiq.1   | started with pid 1695
00h00m00s 0/0: : 10:23:25 webpacker.1 | ERROR: [Errno 21] Is a directory: 'bin'
10:23:25 webpacker.1 | CRITICAL:root:Traceback (most recent call last):
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/dist-packages/cliapp/app.py", line 182, in _run
10:23:25 webpacker.1 |     self.settings.load_configs()
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 829, in load_configs
10:23:25 webpacker.1 |     self._read_ini(pathname, f)
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 838, in _read_ini
10:23:25 webpacker.1 |     cp.readfp(f)
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
10:23:25 webpacker.1 |     self._read(fp, filename)
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
10:23:25 webpacker.1 |     raise MissingSectionHeaderError(fpname, lineno, line)
10:23:25 webpacker.1 | MissingSectionHeaderError: File contains no section headers.
10:23:25 webpacker.1 | file: /var/www/v2/config/webpack/development.js, line: 1
10:23:25 webpacker.1 | '/* eslint-env node */\n'
10:23:25 webpacker.1 |
10:23:25 webpacker.1 | Traceback (most recent call last):
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/dist-packages/cliapp/app.py", line 182, in _run
10:23:25 webpacker.1 |     self.settings.load_configs()
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 829, in load_configs
10:23:25 webpacker.1 |     self._read_ini(pathname, f)
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 838, in _read_ini
10:23:25 webpacker.1 |     cp.readfp(f)
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
10:23:25 webpacker.1 |     self._read(fp, filename)
10:23:25 webpacker.1 |   File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
10:23:25 webpacker.1 |     raise MissingSectionHeaderError(fpname, lineno, line)
10:23:25 webpacker.1 | MissingSectionHeaderError: File contains no section headers.
10:23:25 webpacker.1 | file: /var/www/v2/config/webpack/development.js, line: 1
10:23:25 webpacker.1 | '/* eslint-env node */\n'
10:23:26 webpacker.1 | exited with code 1
10:23:26 system      | sending SIGTERM to all processes
10:23:26 web.1       | terminated by SIGTERM
10:23:26 sidekiq.1   | terminated by SIGTERM
== Command ["foreman start -f Procfile.dev"] failed ==

Server: Ubuntu 18.04 (2Core 4GB)

**Comment by rhymes** [comment]
Hi @alexanderjosepluthor, I think you're having the same issue @0xC000005 had. See the solution here - https://github.com/forem/forem/issues/11745#issuecomment-738955291 - and let us know if that doesn't work so we can re-open the issue if needed
