### ISSUE TITLE
Error: Available for is too long when you would like change the color 

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#11751]
**Describe the bug**
When I would like to change my color of my profile, I've got this error : 
`Error: Available for is too long (maximum: 200)`

**To Reproduce**

1. Go to your settings
2. Change your color
3. Click to save
4. You've got the error

**Comment by rhymes** [comment]
Hi @thomasbnt, it's not a bug per se, as the error message states, your `available_for` field is too long. The maximum is 200 chars.

Hope this helps!
