### ISSUE TITLE
Warn before blowing away an in-progress post.

### ISSUE THREAD

**Issue by FGasper** [forem/forem#11753]
**Is your feature request related to a problem? Please describe.**

I just accidentally hit the “X” in the upper-right while writing a post. (I went to look at a preview and mistook that “X” for a control to close the preview and return to the writing view.)

I’d spent some time on the post; now that post is just gone.

Usually apps like this show a confirmation before deleting data.

**Describe the solution you'd like**

Show a “Are you sure you want to delete your in-progress post?” message. It’d be nice, too, if it offered to save.

Alternatively, just _always_ auto-save the draft as it’s being written.

**Additional context**

What I’m requesting seems to be a pretty standard way of doing things in a lot of web apps.

**Comment by ludwiczakpawel** [comment]
1. 100% agree we should have this kinda of prompt.
2. It is a bit surprising your post is gone - it should be auto-saved --> even if you leave the page, it just still be in the textarea when you get back to it. So if that didn't happen it certainly seems like a bug.

**Comment by rhymes** [comment]
@ludwiczakpawel definitely a bug yes, @FGasper could you file a separate issue describing what happened there? AFAIK the client side storage should be emptied only when the previous post is published, not when you close or dismiss the page

**Comment by katiedavis** [comment]
@ludwiczakpawel Hello 👋 it looks like the issue with local storage has been fixed:
![X](https://user-images.githubusercontent.com/15366319/104645706-675d4a80-567d-11eb-8c8e-3eaa3da47ae9.gif)

But it is still likely a really good idea to have a modal that lets the user know they're leaving the post page, right? Do we have any guides on language for messaging like this?

**Comment by ludwiczakpawel** [comment]
> the issue with local storage has been fixed

@FGasper can you confirm? I don't think we have pushed ANY fix for that issue - it was always working for me. I believe it was some weird coincidence (conjunction of planets?) that it did not save the draft for you. But if it still happens to you, we should definitely dig deeper.

> But it is still likely a really good idea to have a modal that lets the user know they're leaving the post page, right? Do we have any guides on language for messaging like this?

Absolutely, I think we should proceed with this. Re language, we don't have any guidelines - maybe @lisasy can chime in. It should definitely be something simple, feel free to make a call :) 

- This is what Twitter does:
    ![image](https://user-images.githubusercontent.com/108287/104704845-709bf500-5719-11eb-81cf-aae50b3e7cc7.png)
- ...Facebook just prompts user with browser-native classic alert (`confirm()` or something..)
