### ISSUE TITLE
apache2 config sample

### ISSUE THREAD

**Issue by alexanderjosepluthor** [forem/forem#11758]
any chance you can provide the apache2 config sample? below seems throwing error,

> <VirtualHost *:443>
    ServerName temp.com
    DocumentRoot /var/www/temp.com/public
    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/temp.com/cloudflare.pem
    SSLCertificateKeyFile /etc/apache2/ssl/temp.com/cloudflare.key
    <Directory /var/www/temp.com/>
        Options -Indexes +FollowSymLinks -MultiViews
        AllowOverride All
        Require all granted
    </Directory>
    <FilesMatch \.php$>
        # Apache 2.4.10+ can proxy to unix socket
        SetHandler "proxy:unix:/var/run/php/php7.4-fpm.sock|fcgi://localhost"
    </FilesMatch>
</VirtualHost>

error

> AH01276: Cannot serve directory /var/www/temp.com/public/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive

**Comment by rhymes** [comment]
Hi, I think that's incorrect, it looks like an Apache configuration for a PHP app, which we're not. Going ahead and closing this
