### ISSUE TITLE
Clicking "Write a post" shows my previous post

### ISSUE THREAD

**Issue by masakudamatsu** [forem/forem#11754]
**Describe the bug**

Clicking "Write a post" button shows my previous post in the editing mode. 

**To Reproduce**

1. Visit dev.to
2. Click the "Write a post" blue button on the top bar, or hover the profile photo icon on the top-right corner and click the "Write a Post" menu item
3. My previous post appears in the editing mode, instead of a blank post, like this:
<img width="1368" alt="Screenshot 2020-12-05 at 11 57 59" src="https://user-images.githubusercontent.com/36348559/101232214-a352d680-36f3-11eb-869a-c01b98b5b285.png">

**Expected behavior**

After clicking "Write a post", a blank post should appear in the editing mode

**Screenshots**

See above

**Desktop (please complete the following information):**

- OS, version: Mac OS 10.14.4
- Browser, version: Chrome 87.0.4280.88

**Additional context**

I published my first post a week ago (Nov 30). Now I cannot post my second post... Maybe erasing everything will work, but I'm scared that it might delete my previous post (which took a lot of time to write up).

My dev.to username is @masakudamatsu

**Comment by LE-HU** [comment]
Hello @masakudamatsu, is it possible to reproduce the issue in different browser?
Does the problem still persist?
Thank you,

**Comment by cmgorton** [comment]
Since we can not currently replicate this issue I am going to close it. @masakudamatsu if this issue persists please let us know and I will reopen the issue. Thanks.
