### ISSUE TITLE
environment variable name ... may not contain whitespace

### ISSUE THREAD

**Issue by ty-schnoor** [forem/forem#11777]
**Describe the bug**
when trying to `docker-compose run bin/container-setup`, i get this error: `ERROR: In file ./.env: environment variable name 'export SKIP_SERVICEWORKERS' may not contain whitespace.`

**To Reproduce**
simply run `docker-compose run bin/container-setup` (going back, it looks like this command is wrong, but this issue is still needed, i presume)

**Expected behavior**
expected to run forem in docker-compose.

**Screenshots**
![image](https://user-images.githubusercontent.com/75553731/101286420-6f8db480-37b8-11eb-826b-e499c389e318.png)

**Desktop (please complete the following information):**

- OS, version: linux 20.04

**Comment by rhymes** [comment]
Hi @ty-schnoor, have you created the `.env` file? See the installation guide https://docs.forem.com/installation/containers/#setting-up-forem

**Comment by ty-schnoor** [comment]
> Hi @ty-schnoor, have you created the `.env` file? See the installation guide https://docs.forem.com/installation/containers/#setting-up-forem
> 
> Also, you only need to run `bin/container-setup` without `docker compose` in front of it

i have

**Comment by rhymes** [comment]
@ty-schnoor is `bin/container-setup` working now?

**Comment by ty-schnoor** [comment]
> @ty-schnoor is `bin/container-setup` working now?

yes it is, just running into ip and port issues.

**Comment by rhymes** [comment]
Thank you for the update! Closing this now.

**Comment by nafaabout** [comment]
This still happens. I just followed the installation guides for containers and I'm getting this same error. I'm running with `bin/container-setup`.

**Comment by nickytonline** [comment]
@nafaabout, did you create a `.env` file? I just can `bin/container-setup` for Docker and did not run into this issue.

**Comment by rodolfobandeira** [comment]
If you're having issues, just remove all `"export "` from the `.env` file and it should work.

```
export FOO="bar"
```

to:

```
FOO="bar"
```
