### ISSUE TITLE
Bulk tag creation

### ISSUE THREAD

**Issue by jaredpalmer** [forem/forem#11780]
**Is your feature request related to a problem? Please describe.**

As an admin migrating from an existing community, I want to be able to bulk create tags.

**Describe the solution you'd like**

Bulk create Tags in Admin panel

- MVP: A textarea (one tag per line) in a modal, this would just generate the names
- v2: CSV upload of a template. Forem would make this template downloadable.
  - Notes: In broswer, should validate the columns and maybe first line. Admin should get an email when it completes. If csv processing is a sync/blocking behavior in Ruby (idk if it is), then tag creation should be put in worker async process and not prevent other actions taking place.
- v2+: Import tags from other community exports or via an integration script.

**Describe alternatives you've considered**

**Additional context**

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
