### ISSUE TITLE
Add "Save and Create New" to new tag form

### ISSUE THREAD

**Issue by jaredpalmer** [forem/forem#11781]
**Is your feature request related to a problem? Please describe.**

As admin creating multiple tags at once, I want to be able to create another tag after making one. 

**Describe the solution you'd like**

Add a button  at the bottom of the Tag form to "Save and Create New." This could also be placed in a button group dropdown menu. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
