### ISSUE TITLE
Moderator Experience Rating

### ISSUE THREAD

**Issue by Daniel-ltw** [forem/forem#11793]
**Describe the bug**
I was trying to rate an experience level for an article and encountered the following issue. 

Here are some of the technical details:
Request: 
POST https://dev.to/rating_votes
Request Body: 
{"user_id":"230161","article_id":"527891","rating":"1","group":"experience_level"}

Alert box message:
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**To Reproduce**
1. You must be a moderator
2. Go to an article
3. Open the moderator panel
4. Select an experience level

**Expected behavior**
Should complete the rating request and mark the experience level for the article.

**Desktop (please complete the following information):**
- OS, version: Microsoft Windows 10 Pro, Version 1909
- Browser, version: Firefox 83.0

**Comment by musps** [comment]
Earlier this day I had an error from the api "404 bad request" but now I got the same error as daniel gotten

The `https://dev.to/rating_votes` endpoint does not exist. He returns a blank response

**Comment by Daniel-ltw** [comment]
Maybe they are still working hard to resolve the bug. 

Previously I only had a bad request in the alert box message.
