### ISSUE TITLE
Unlink Twitter account

### ISSUE THREAD

**Issue by Kaffesumpen** [forem/forem#11798]
**Describe the bug**

When I created the account I linked it with Twitter, I have since removed my twitter but there is not way to unlink that Twitter account to my DEV account

**To Reproduce**

**Expected behavior**

To be able to remove the Twitter email from my account

**Comment by rhymes** [comment]
Hi @Kaffesumpen, first and foremost: what is your DEV username?  :-D 

Is Twitter the only means of authentication to DEV?

DEV allows you to remove an OAuth link only if you have at least another mode of authentication. 

I think you can either link GitHub or set a password in https://dev.to/settings/account - then you should be able to see the "Remove Twitter" button

**Comment by Kaffesumpen** [comment]
Thank you, added the Github account and the remove Twitter came up.
