### ISSUE TITLE
Deformed Navbar

### ISSUE THREAD

**Issue by harshhhdev** [forem/forem#11802]
**Describe the bug**

The navbar is deformed. It has buttons all over the place, and has no order or line whatsoever. Even reloading doesn't fix it. I have not added any custom CSS or tampered with the inspect feature.

**To Reproduce**

1. Go to 'dev.to'
2. Watch the page become deformed.

**Expected behavior**

Everything in the nav should line up. Not have a bunch of deformed elements all over the place.

**Screenshots**

![image](https://user-images.githubusercontent.com/69592270/101505367-4731c180-3942-11eb-8870-76ab9cc7d0b8.png)

**Desktop (please complete the following information):**

- Pop!_OS (Linux, Ubuntu based), version: 20.10
- Browser, version: Brave, 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)

**Additional context**

If you want, I can make a video about this also.

**Comment by harshhhdev** [comment]
A ctrl+f5 fixed this. But am still confused on why this happened and thought to bring this to your attention.

**Comment by ItzaMi** [comment]
Also facing this issue. Clearing the cache on Chrome (desktop, windows 10) fixed it.
However, having the same issue on dev.to android app on Huawei P10 Lite with version 8.0.0

![Screenshot_20201208-163000](https://user-images.githubusercontent.com/30603437/101512495-f8e8e680-3972-11eb-96ef-1cd63908c0d2.jpg)

**Comment by LE-HU** [comment]
Hello
Possible duplicate - #11827
Mentioned fix - #11806
Does the issue still persist?

**Comment by rhymes** [comment]
Thank you @LE-HU, indeed that should be fixed. Can you confirm @harshhhdev ?

**Comment by harshhhdev** [comment]
@rhymes yep. It works :+1:

**Comment by harshhhdev** [comment]
Re-opened since I have a phone which has iOS 12 therefore not compatible w/ the dev.to app. 

If someone w/ the mobile app can confirm it, like @ItzaMi, that would also be better.

**Comment by ItzaMi** [comment]
For me, it seems fine now, although I have another issue with the navbar but will open another `issue` for it

**Comment by rhymes** [comment]
@harshhhdev I just checked with the mobile app and it works, also the layout on mobile is totally different
