### ISSUE TITLE
Pressing the cog on blog post doesn't display edit options (mobile app)

### ISSUE THREAD

**Issue by ItzaMi** [forem/forem#11809]
**Describe the bug**
Pressing the `cog` (settings) inside a blog post, on mobile app, doesn't do the pretended behaviour (shows up a slight white bar on the top but that's it) 

**To Reproduce**
1. Have mobile app
2. Choose a post created by you
3. Press `cog` (settings, next to `Save Changes`) inside the post
4. See error and slight white bar on top of window

**Expected behavior**
I'm not sure what is supposed to happen

**Screenshots**
![giphy](https://user-images.githubusercontent.com/30603437/101514458-3189bf80-3975-11eb-8d4d-42fe2cca4b40.gif)

**Smartphone (please complete the following information):**

- Device: Huawei P10 Lite
- OS, version: 8.0.0
- Browser, version: mobile app

**Comment by rhymes** [comment]
Hi @ItzaMi which version of the mobile app are you using? Would it be possible for you to file this bug report in the repository for the DEV android app? https://github.com/forem/DEV-Android

**Comment by ItzaMi** [comment]
@rhymes , sorry, completely forgot that DEV has an android repo. I created [the issue](https://github.com/forem/DEV-Android/issues/117) there now, thank you for the notice!

**Comment by rhymes** [comment]
Thank you @ItzaMi, no worries :)!
