### ISSUE TITLE
Make sure Posts path are consistently using only lowercase characters

### ISSUE THREAD

**Issue by fdoxyz** [forem/forem#11815]
**Describe the bug**

We found a few Posts that are saved with a `path` that contains uppercased characters, which breaks them.

**To Reproduce**

We're not able to reproduce this yet, but think it may have something to do with API calls or the User's username being capitalized causing this issue. The following query shows some data on these articles:

https://dev.to/admin/blazer/queries/304-articles-with-uppercased-characters

**Expected behavior**

Article paths should remain without capitalized characters

**Additional context**

- #11813
- #11690

**Comment by benhalpern** [comment]
We don't have any validations on the `path` right now. It's not something the user can submit data directly to, but clearly our app logic is capable of messing this up.

**Comment by fdoxyz** [comment]
Interesting, we do have a `before_action` callback for `set_caches` [here](https://github.com/fdoxyz/forem/blob/master/app/models/article.rb#L407-L413).

I think that we can add a `.downcase` to the `calculated_path` to ensure we won't run into any other of these situations. It looks like when a user has an uppercase char in their username then the path gets stored incorrectly.

I can update #11813 to do this instead of the current approach

**Comment by fdoxyz** [comment]
Closing since #11813 was merged and the Blazer query is not showing any more results of problematic paths in Articles

**Comment by rhymes** [comment]
Great job @fdoxyz!
