### ISSUE TITLE
Pressing the cog on blog post doesn't display edit options

### ISSUE THREAD

**Issue by ItzaMi** [forem/forem#11828]
**Describe the bug**
Pressing the `cog` (settings) inside a blog post, on mobile app, doesn't do the pretended behaviour (shows up a slight white bar on the top but that's it) 

**To Reproduce**
1. Have mobile app
2. Choose a post created by you
3. Press `cog` (settings, next to `Save Changes`) inside the post
4. See error and slight white bar on top of window

**Expected behavior**
I'm not sure what is supposed to happen

**Screenshots**
![giphy](https://user-images.githubusercontent.com/30603437/101514458-3189bf80-3975-11eb-8d4d-42fe2cca4b40.gif)

**Smartphone (please complete the following information):**

- Device: Huawei P10 Lite
- OS, version: 8.0.0
- Version: 1.5.0-2

**Comment by fdoxyz** [comment]
The modal that presents the options after pressing the button does seem to appear on screen but it's positioned incorrectly (you can notice a small blip at the very top of the screen).

I think it can be fixed with some CSS changes.

**Comment by ItzaMi** [comment]
Indeed, just noticed that also happens on Chrome. Seems like it might be this `.bottom-100` class although I'm not really in sync with the stylesheet that dev.to uses

**Comment by fdoxyz** [comment]
I think the best resource for diving into the CSS classes available is this: https://storybook.forem.com/?path=/story/introduction--page
