### ISSUE TITLE
Navigation content overlapping each other

### ISSUE THREAD

**Issue by binismail** [forem/forem#11827]
**Describe the bug**

Noticed some bug earlier today, the navigation header is overlapping each other on my dev.to account this morning when I was looking for some answers, I tried some way thinking it's my computer but shows the same result.

**To Reproduce**

 1. go to dev.to 

2. Click on post 

3. Check your navigation header

**Expected behavior**

**Screenshots**
![screenshot-dev-to-prototyp-best-way-to-lazy-load-images-for-maximum-performance-27o1-1607503840184](https://user-images.githubusercontent.com/57535561/101607054-68f37d00-3a04-11eb-9616-0050e073cf5f.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Google chrome

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
Hi @binismail, do you still have this issue if you hard refresh? We've released [a fix](https://github.com/forem/forem/pull/11806) that should address that yesterday but you might need to force the cache unfortunately. Let us know, and thank you!

**Comment by binismail** [comment]
okay, let me check

**Comment by cmgorton** [comment]
@binismail since we added a fix and others have reported it has worked I am going to close this issue. However if it persists for you let me know and I will open this back up. Thanks for bringing it to our attention!
