### ISSUE TITLE
Automated mail to users upon creation of new listing or post

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#11833]
**Is your feature request related to a problem? Please describe.**

It is not related to a problem but I think it would serve our community on Forem better - the Cluster Employment Community, if there was a way to automate emails to users on the platform anytime a new listing or post is created. I believe it would assist in increasing user engagement and activity on the platform.

**Describe the solution you'd like**

A feature that can be enabled or disabled that notifies users on the community - via email - anytime a new listing or post is created.

**Describe alternatives you've considered**

None

**Additional context**

I believe this feature could be very useful for growing communities (less than 1000-10000 users) in the Forem network.

**Comment by cmgorton** [comment]
Hey @xpyxel  Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
