### ISSUE TITLE
Main site bottom menu disappears. Endless. 

### ISSUE THREAD

**Issue by erdnuesse** [forem/forem#11831]
If I want to check out the imprint, contact info or anything located in the footer menu, it disappears due to the autoload more content feature. 
While this may be a good exercise for newbies to dig through the site code to find the specific links, the bottom menu is either useless and can be removed or unecessarily hard / unable to being useful - and needs fixing..

Regards, K

**Comment by rhymes** [comment]
Hi @erdnuesse, thanks for reporting this. We do have several active discussions on the pros and cons of infinite scroll and how to deal with the footer on the feed (in other pages you can reach the footer easily):

- https://github.com/forem/forem/issues/9034
- https://github.com/forem/forem/issues/8256
- https://github.com/forem/forem/issues/5670

I'm going ahead and closing this as it's a known issue

Thank you again!
