### ISSUE TITLE
Allow for Organizations to Receive Badges

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#11845]
**Is your feature request related to a problem? Please describe.**

Not particularly, but we'd like to be able to award organizations badges that would appear on their org profile page. (e.g. https://dev.to/devteam). Also, any badges awarded to an org would appear on the org members' profiles too.

**Describe the solution you'd like**

I'd like to mirror the way badges are awarded to users. 

In other words, badges are created here - https://dev.to/admin/badges and awarded either automatically or via https://dev.to/admin/badge_achievements/award_badges. 

Badges would appear on a org profile beneath the "Meet the Team" section, somewhat similar to how they appear on user profiles.

The tricky part would be making it so that an org's badges would appear on the org members' profile pages too.

**Other concerns**

If an org member leaves an org, the org badge should likely be removed from the member. On the rare occasion that the org badge should stay there, I think we can deal with this manually.

**Comment by cmgorton** [comment]
@michael-tharrington I am going to close this issue in favor of a post in forem.dev to discuss this feature. I can write the post if you would like!
