### ISSUE TITLE
Unable to install forem using docker on macOS

### ISSUE THREAD

**Issue by nglglhtr** [forem/forem#11843]
**Describe the bug**

the logs seem to be stuck here

**To Reproduce**

1. `cp .env_sample .env`
2. `bin/container-setup`

**Expected behavior**

Forem should start running on localhost:3000

**Screenshots**

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/10832414/101744395-f57b6980-3af0-11eb-9022-bd15b4e01cd2.png">

```
sidekiq_1        | 2020/12/10 08:21:18 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
seed_1           | 2020/12/10 08:21:19 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
sidekiq_1        | 2020/12/10 08:21:19 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
seed_1           | 2020/12/10 08:21:20 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
sidekiq_1        | 2020/12/10 08:21:20 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
seed_1           | 2020/12/10 08:21:21 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
sidekiq_1        | 2020/12/10 08:21:21 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
seed_1           | 2020/12/10 08:21:22 Problem with request: Get http://rails:3000: dial tcp 172.20.0.4:3000: connect: connection refused. Sleeping 1s
```

**Desktop (please complete the following information):**

- OS, version: macOS v11.0.1

**Comment by nglglhtr** [comment]
HALP.

**Comment by rhymes** [comment]
Hi @nglglhtr could you take a look at this discussion here? https://github.com/forem/forem/issues/9532 - maybe @jdoss notes in https://github.com/forem/forem/issues/9532#issuecomment-664758203 will help

I have the feeling that even the reported message is slightly different that the root of the problem is the same: Docker being infinitely slow on Mac

**Comment by cmgorton** [comment]
@nglglhtr if you get a chance let us know if the linked issue #9532 helped at all. If not, we can discuss more how we can help.
