### ISSUE TITLE
Allow organizations to modify posts

### ISSUE THREAD

**Issue by crimson-med** [forem/forem#11857]
**Is your feature request related to a problem? Please describe.**

Recently we started using github organization to make articles by our company as we are trying to share our knowledge. If a colleague shares a link to draft then I can edit it. However when he publishes the article under the company even as an Admin of the company I can't modify it or manage it. 

**Describe the solution you'd like**

If an article is drafted or published as a organization article then other people of the organization should be able to edit and manage them.

**Describe alternatives you've considered**

Also allowing people who are part of the same organization to see draft posts under the organization in their dashboard as for now we can only see the ones we started.

**Additional context**

At the moment the organization don't seem to add much apart from a company page. I feel this could be a really good feature to help companies, institutions, etc to create content efficiently for dev.to and other platforms.

**Comment by crimson-med** [comment]
@citizen428 Sorry to bother you. Recently we are really pushing the use of organization and using the organization principle to kind of run our company blog as well ass share our knowledge with the community on dev to.

Would you have any ideas on when this would be put in the pipeline?

**Comment by citizen428** [comment]
Sorry @crimson-med, not at this time, but I'll keep you posted!

**Comment by michael-tharrington** [comment]
@crimson-med I got some good info that should help!

Org admin currently have the ability to edit any posts by members of the org, but navigating to that edit page isn't necessarily the most intuitive UX, so I do think there's something to your request here. Regardless, here is how you go about editing a feel org member's post.

0. Make sure you have admin privileges for the org!
1. Navigate to https://dev.to/dashboard
2. Use the drop down menu that is set to `personal` and change it to your org.
3. Scroll down to the post you'd like to edit and click "edit"
4. Make sure to save the post after editing.

Hope this helps!

![Image 2021-01-26 at 9 14 15 AM](https://user-images.githubusercontent.com/16007075/105856734-8c27bb00-5fb7-11eb-98c0-d7c5db1a6f6f.png)

**Comment by crimson-med** [comment]
@michael-tharrington thanks for the info that is useful! But the UX is really unpractical. I think part of the confusion is that there is no edit or manage button when visiting the post itself. usually I would just go to the post and click edit

**Comment by michael-tharrington** [comment]
Totally! I think this feature request should be adapted to improve the UX for org admins. And I agree that it would be awesome for it to work like you've described.

**Comment by cmgorton** [comment]
Please see this https://github.com/forem/forem/discussions/15331 for further discussions on this feature.
