### ISSUE TITLE
NoMethodError in Stories#show

### ISSUE THREAD

**Issue by 0xC000005** [forem/forem#11855]
**Describe the bug**

Hi, I'm having a `NoMethodError in Stories#show` error when I trying to access any article ....... 
The error message is ```ActionView::Template::Error: undefined method `brand_color1' for #<Profile:0x00005569dd8f12f8>```, so I try to access articles without logging on an account and this error occur anyways. 

- Error Page: http://yuegaoya.org/jareddvmgrant/a-many-splendoured-thing-excepturi-omnis-58p3
- Honeybadger Bug Report: https://app.honeybadger.io/fault/79424/8a09f8d40889fae03b50383b90e0d469

**To Reproduce**

![](https://raw.githubusercontent.com/0xC000005/image-hosting/master/20201210172930.gif)

**Expected behavior**

**Screenshots**
![](https://raw.githubusercontent.com/0xC000005/image-hosting/master/20201210173106.png)

**Desktop (please complete the following information):**
- OS, version: `Ubuntu 18.04`
- Browser, version: `Microsoft Edge Version 87.0.664.57 (Official build) (64-bit)`

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

I'm translating some page text into another language...... maybe I messed up (っ °Д °;)っ 
This is my project: https://github.com/0xC000005/yuegaoya

**Comment by LE-HU** [comment]
Hello,
Did the error appear after your last commit? That is -
**Merge remote-tracking branch 'origin/master' into 0xC00005/dev**
Can you undo the last commit? It shows some major changes not related to translation. Please research the web how to revert the git repository to a previous commit.

**Comment by citizen428** [comment]
Can you please check if you have all current profile fields in your DB? There should be 29 of them.

If you don't have all of them, can you please try the following in a Rails console?

```ruby
csv = Rails.root.join("lib/data/dev_profile_fields.csv")
ProfileFields::ImportFromCsv.call(csv)
```

Then restart your Rails server and see if things work.

**Comment by LE-HU** [comment]
Meanwhile I've set up my own forem instance on local ubuntu following tutorial & using bin/setup method, and encountered the same error as the author.
NoMethodError also spotted at http://localhost:3000/admin_mcadmin 
```ruby
undefined method `display_email_on_profile' for #<Profile:0x00007f01f4b69e80>
```
![image](https://user-images.githubusercontent.com/19828138/101871539-075a1c80-3b84-11eb-84a2-ef68b537e42c.png)

28 ProfileFields are present in DB including brand1_color and display_email_on_profile. I've tried running @citizen428 csv import just in case but no changes (server restart applied).

![image](https://user-images.githubusercontent.com/19828138/101871618-31134380-3b84-11eb-86ad-496c77594e09.png)

**Comment by 0xC000005** [comment]
> Hello,
> Did the error appear after your last commit? That is -
> **Merge remote-tracking branch 'origin/master' into 0xC00005/dev**
> Can you undo the last commit? It shows some major changes not related to translation. Please research the web how to revert the git repository to a previous commit.

@LE-HU Thank you for your help! I tried hard reset my project to the previous commit and the error still exists, so I restore my ubuntu server to the day I installed the unmodified forem, which was Dec 09, but the error occurs anyway.

So I reset my server and tried to reinstall the froem completely, and I run into `Command ["bin/rails app_initializer:setup forem:setup"] failed` when `bin\setup` is preparing database.

```
  4. Creating Tags.
  5. Creating 25 Articles.
rails aborted!
URI::BadURIError: both URI are relative
/root/forem/app/lib/url.rb:21:in `url'
/root/forem/app/lib/url.rb:28:in `article'
/root/forem/app/services/slack/messengers/article_published.rb:23:in `call'
/root/forem/app/services/slack/messengers/article_published.rb:14:in `call'
/root/forem/app/models/article.rb:709:in `notify_slack_channel_about_publication'
/root/forem/db/seeds.rb:225:in `block (2 levels) in <main>'
/root/forem/db/seeds.rb:207:in `times'
/root/forem/db/seeds.rb:207:in `block in <main>'
/root/forem/db/seeds.rb:26:in `create_if_none'
/root/forem/db/seeds.rb:206:in `<main>'
bin/rails:4:in `<main>'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)

== Command ["bin/rails app_initializer:setup forem:setup"] failed ==
```

I think there is some connection between the installation error and the `undefined method` since both errors are related to the `article` in the database.

**Comment by rhymes** [comment]
@0xC000005 this last error seems an issue in the environment variables, can you report what do you have in `APP_DOMAIN` ?

**Comment by 0xC000005** [comment]
> Can you please check if you have all current profile fields in your DB? There should be 29 of them.
> 
> If you don't have all of them, can you please try the following in a Rails console?
> 
> ```ruby
> csv = Rails.root.join("lib/data/dev_profile_fields.csv")
> ProfileFields::ImportFromCsv.call(csv)
> ```
> 
> Then restart your Rails server and see if things work.
> 
> Note: if you set up your local env via `bin/setup` as recommended by our installation guide this should have happened, so for the purpose of debugging, did you do that?

Thank you so much for your support! 
I ran the two commands and restarted the rails server. It shows I have 30 ProfileFields in the DB including brand1_color, but I'm still having the same error if I click any article.

**Comment by 0xC000005** [comment]
> @0xC000005 this last error seems an issue in the environment variables, can you report what do you have in `APP_DOMAIN` ?



> @0xC000005 this last error seems an issue in the environment variables, can you report what do you have in `APP_DOMAIN` ?

I forget to copy the .env_sample to create the .env file....... now the `bin/setup` is working. However even a fresh installation of forem would run into the same error as I click any article :(

**Comment by fdoxyz** [comment]
Oddly enough I'm running into the same problem. I've been using a local environment with a custom `APP_DOMAIN` (using ngrok for mobile development):

```
export APP_PROTOCOL="https://"
export APP_DOMAIN="fdoxyz.ngrok.io"

vs

export APP_PROTOCOL="http://"
export APP_DOMAIN="localhost:3000"
```

However the bug happens when I use either of the two options above. This is what I have locally after running `rake db:reset && bin/setup && bin/startup`:

![Screen Shot 2020-12-11 at 15 04 45](https://user-images.githubusercontent.com/6045239/101954903-84a48200-3bc2-11eb-8aef-c7f9764e0c4f.png)

And this is what happens to me on the first login using `admin@forem.local`:

https://share.getcloudapp.com/z8u46oo9

**Comment by citizen428** [comment]
I tested this locally now: after running `rake db:reset && bin/setup && bin/startup` I had the same error. So I inspected `Profile.attributes`, which was an empty array. Calling `Profile.refresh_attributes!` loaded them correctly and everything was working as expected.

I then ran the same combination of Rake tasks on my PR branch for #11881 which moves the `Profile.refresh_attributes!` call back into the `Profile` class from `config.after_initialize` and the fields are set up correctly.

**Comment by LE-HU** [comment]
Although running `Profile.refresh_attributes!` did not help on already bugged instance, I've added the `refresh_attributes! `(PR code) into Profile.rb then reset the app with `rake db:reset && bin/setup && bin/startup`. Worked like a charm, thank you @citizen428 !

**Comment by citizen428** [comment]
Thanks for confirming @LE-HU, that's really useful!

**Comment by rhymes** [comment]
Works for me too :)

**Comment by 0xC000005** [comment]
The code works! Now I can access articles. Thank you so much!

**Comment by cmgorton** [comment]
Glad it is working! Looks like we can close this issue now. Happy to open it again in the future if we need too.
