### ISSUE TITLE
Duplicate test file in /chat/__tests__/membership.test.jsx

### ISSUE THREAD

**Issue by LE-HU** [forem/forem#11860]
Hello,
There's duplicate jsx file containing the same code, that differs only in M/m letter case.
../app/javascript/chat/\_\_tests\_\_/membership.test.jsx
../app/javascript/chat/\_\_tests\_\_/Membership.test.jsx
link:
https://github.com/forem/forem/tree/master/app/javascript/chat/__tests__/

VSCode shows this as a warning.

I'm not sure which one (if any) should be removed. If it's intended please provide some insight how to cope with such occurences in the future. 
If it's truly an unnecessary duplicate, seems like a quick fix.
Thanks!

**Comment by djuber** [comment]
resolved by https://github.com/forem/forem/pull/11883 ?

**Comment by LE-HU** [comment]
Looks like it :) thank you for the notice.
