### ISSUE TITLE
Docs - Table of Contents nav - horizontal overflow visual bug

### ISSUE THREAD

**Issue by LE-HU** [forem/forem#11875]
**Describe the bug**
Docs side navigation "Table of contents" starts to overflow viewport horizontally after single scrolldown. It's position changes from static to fixed, causing it's nested div to change width from 130px to ~380px extending long text lines over viewport's scrollbar - preventing user from scrolling manually.

**To Reproduce**

1. Open forem docs https://docs.forem.com/
2. Go to Technical Overview -> Architecture (it has a long table of contents)
3. Locate table of contents on the right side.
4. Scroll down a little.
5. See line items overflowing scrollbar.

**Expected behavior**
I suppose line item width should stay the same after scrolling down (with standard text-overflow - ellipsis), or line item text should be wrapped - depends on desired implementation.
User should be able to scroll the page manually without line items overflowing viewport's scrollbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/19828138/101992855-6455ef80-3cb6-11eb-8d43-2d14413b2016.png)

Link to video:
https://share.getcloudapp.com/5zudYgzG

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04
- Browser, version: tested both on latest Mozilla, and latest Chrome (no add-ons)

**Comment by mikeesto** [comment]
Good suggestion but currently the docs are built with [GitDocs](https://github.com/timberio/gitdocs) which unfortunately doesn't support custom styling & is no longer maintained. There's some discussion on the future direction of the docs in https://github.com/forem/forem/issues/6922 & https://github.com/forem/forem/issues/11285

**Comment by LE-HU** [comment]
Guys I'll close this one as this will solve itself in future docs migration. Currently no action needed.

Thanks,
