### ISSUE TITLE
Github gists are not rendered

### ISSUE THREAD

**Issue by burningwave** [forem/forem#11884]
Today all github gists are not rendered: you can check in [one of my articles](https://dev.to/bw_software/invoking-and-handling-privates-and-all-other-methods-of-an-object-with-and-without-the-use-of-reflection-in-java-i1h) and in attachment I send a screenshot of the issue
![image](https://user-images.githubusercontent.com/45799507/102103955-e7e61c80-3e2d-11eb-8e66-c152d117c2fd.png)

**Comment by rhymes** [comment]
Hi @burningwave, would it be possible to see the original markdown of that post? Thank you!
You can paste it in a https://gist.github.com/ or similar

**Comment by burningwave** [comment]
> Hi @burningwave, would it be possible to see the original markdown of that post? Thank you!
> You can paste it in a https://gist.github.com/ or similar

{% gist 
https://gist.github.com/burningwave/c233257f2774b2bdbbb870f64cdc575a.js %}

**Comment by LE-HU** [comment]
I've just opened the article and gists render correctly, was that a temporary outage at github side?
![image](https://user-images.githubusercontent.com/19828138/102128048-951c5d00-3e4d-11eb-94b5-280f170e1728.png)
