### ISSUE TITLE
Liquid Tags does not respect company avatar

### ISSUE THREAD

**Issue by crimson-med** [forem/forem#11880]
**Describe the bug**

When using liquid tags on a post that was published under an organization it shows the users avatar.

**To Reproduce**

1. Create a post under an organization
2. Add it as liquid tag into a comment or another post
3. The avatar displayed will be the poster's.

**Expected behavior**

Everywhere the way a organization post's avatar is the organization's avatar and in small the poster's avatar (notification, dashboard, homepage).

When using the liquid tags it should show the avatar in the same way

**Screenshots**

Organizaiton's post avatar:

![Screenshot 2020-12-14 at 10 02 49 AM](https://user-images.githubusercontent.com/28290546/102032383-902abf80-3df3-11eb-837d-c5ec138ee7a7.png)

On the homepage the avatar is the same style:

![Screenshot 2020-12-14 at 10 03 57 AM](https://user-images.githubusercontent.com/28290546/102032446-bc464080-3df3-11eb-88e6-8433e8e336d7.png)

When using Liquid tags we don't get this behavior:

![Screenshot 2020-12-14 at 10 05 01 AM](https://user-images.githubusercontent.com/28290546/102032488-da13a580-3df3-11eb-9de3-17f31718722d.png)

**Desktop (please complete the following information):**

- OS, version: MacOS
- Browser, version: Firefox 83.0

**Comment by akashdotsrivastava** [comment]
@rhymes Hi, I'd like to give this a shot.

**Comment by rhymes** [comment]
Go ahead @akashdotsrivastava :)

**Comment by meg-gutshall** [comment]
@nickytonline Wanna do this one for the stream?

**Comment by nickytonline** [comment]
This has been inactive for three months @akashdotsrivastava so I'm going to assign this to @meg-gutshall as part of our Bug Smash event.
