### ISSUE TITLE
Clicking "more" on sidebar doesn't work immediately after clicking main logo

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11897]
**Describe the bug**
Clicking "more" in the left sidebar seems to have issues sometimes.

**To Reproduce**

1. Click the main logo
2. Immediately click the "more" button in the left sidebar
3. Notice that the "more" button doesn't expand

Refresh, and it works properly again.

**Expected behavior**

Clicking "more" expands the options every time.

**Screenshots**

[Here is a video](https://p241.p3.n0.cdn.getcloudapp.com/items/GGu2pxKk/Screen%20Recording%202020-12-14%20at%2004.19.01%20PM.mp4).

**Comment by Zhao-Andy** [comment]
My first guess is that it's an Instantclick issue, where hitting `back` will not load the Javascript that adds that click listener to the `More` button.
