### ISSUE TITLE
Use a more generic Favicon on new forems

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11899]
**Is your feature request related to a problem? Please describe.**
As a new Forem Admin, I don't want the "DEV" favicon on my forem.

**Describe the solution you'd like**
New Forems are set up with a more generic favicon.

**Additional context**
Screenshot from Admin > Config > Images on a brand new forem.

![dev favicon on new screenshot](https://p241.p3.n0.cdn.getcloudapp.com/items/Qwub5K77/Image%202020-12-14%20at%208.18.08%20PM.png?v=cfd6d19cc4d0731a02763983173472fd)

**Comment by ludwiczakpawel** [comment]
Looping in @vaidehijoshi as I believe this was something #team-creator-onboarding was looking at. 
There's a bit more context too: https://github.com/forem/InternalProjectPlanning/issues/211

**Comment by vaidehijoshi** [comment]
> Looping in @vaidehijoshi as I believe this was something #team-creator-onboarding was looking at.
> There's a bit more context too: [forem/InternalProjectPlanning#211](https://github.com/forem/InternalProjectPlanning/issues/211)

We had it on our list of tasks, but never got the time to complete it as that project was pretty big in and of itself. I think this probably can become an RFC in the new year, @pkfrank. Something to note: there is a placeholder icon that lives in `app/assets/images/icon.png`. We could probably just use that (but in the correct favicon format) as the "generic" favicon that comes with a new Forem.

**Comment by pkfrank** [comment]
> Something to note: there is a placeholder icon that lives in `app/assets/images/icon.png`. We could probably just use that (but in the correct favicon format) as the "generic" favicon that comes with a new Forem.

I think that's the optimal solution.  Just taking [this file](https://github.com/forem/forem/blob/master/app/assets/images/icon.png) and using it as the default favicon instead of any DEV-specific.

Is this worth creating an RFC?  I'm still not sure on the precise distinction vs. the RFC which will wait until January vs. a smash-able issue we could get to in EOY.

I could see this being an RFC (it's a new feature), but also could see it being an issue (an objective improvement to our committed work of generalizing away from DEV).

**Comment by benhalpern** [comment]
This should fix the problem...

https://github.com/forem/forem/pull/11962

There might be more to the overall problem that got dropped in the past that could be up for a new RFC, but in the meantime this can be patched following the established patterns.
