### ISSUE TITLE
Can't post comments with twitter liquid tag

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#11912]
**Describe the bug**

I've tried to post a comment on some instances of forem and got quota limit error even though I haven't posted any other comment in several days:

![image](https://user-images.githubusercontent.com/108287/102188323-73ef5700-3eb5-11eb-91d9-3926c192a612.png)

This issue happened on forem.team as well as forem.dev instances but it did not happen on dev.to.

**To Reproduce**

1. Go to any post on forem.dev for example
2. Try to post a comment with twitter liquid tag inside
3. Boom.

**Expected behavior**

No boom.

**Additional context**

From @citizen428:

> I may remember wrongly, but I think we don't have Twitter credentials set up on forem.team/.dev
> It seems like the error that is raised by that gets caught by an unexpected handler, which is why the error message looks like rate limiting

**Comment by joshpuetz** [comment]
Clearly the "you've posted too many comments" modal shouldn't be displaying, but what SHOULD be showing up here?

**Comment by fdoxyz** [comment]
It may be worth checking the error handlers to see if we get some response from the request. From the editor and when "previewing" a comment I see these:

<img width="988" alt="Screen Shot 2020-12-15 at 08 47 46" src="https://user-images.githubusercontent.com/6045239/102230516-9633a580-3eb2-11eb-8144-951fcd4665fb.png">

<img width="985" alt="Screen Shot 2020-12-15 at 08 49 18" src="https://user-images.githubusercontent.com/6045239/102230506-9338b500-3eb2-11eb-9c55-b4276375cfad.png">

But it's also a problem that may be handled way down in the stack, at the Liquid tag implementation: Is it really necessary to have Twitter API configured or we can respond with a better message? Example: Suggest users to reach out to the creator/support email so the Forem admin/creator is made aware that Twitter integration is missing.

I haven't followed along with the modal implementation, but can we make it so we can reuse the modal with a different error message? The UI looks amazing and it could be a great reusable tool throughout the codebase if we can pass in different error messages 😃
