### ISSUE TITLE
Error in Fetching organisation Image by Api

### ISSUE THREAD

**Issue by vimalverma558** [forem/forem#11937]
**Describe the bug**
I am Trying to fetch Organization information by Api, But image Show error `The image cannot be displayed because it contains errors` 

**To Reproduce**

 1. Go to https://dev.to/api/organizations/devteam 
 2. Click on profile_image Links 
 3. See error 

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04
- Browser, version: Firefox version 84.0

**Comment by rhymes** [comment]
Thank you @vimalverma558! It indeed looks like an odd bug, either with the API or with the `Images::Profile`/`Images::Optimizer` logic.

What's odd is the following:

- https://dev.to/api/organizations/devteam or https://dev.to/api/organizations/snyk both return an invalid image
- I've also tried with an internal Forem deployment that doesn't use neither Heroku nor Cloudinary and it doesn't work as well
- https://dev.to/api/articles?username=devteam returns articles with a valid image in the `organization` hash
- the code that renders both of them looks the same:

https://github.com/forem/forem/blob/44f73972ea4c5df64e48ff0672a4c23b123857da/app/views/api/v0/shared/_organization.json.jbuilder#L4

this works

https://github.com/forem/forem/blob/44f73972ea4c5df64e48ff0672a4c23b123857da/app/views/api/v0/organizations/show.json.jbuilder#L18

this doesn't work
