### ISSUE TITLE
"Deploy to Heroku" button

### ISSUE THREAD

**Issue by epoberezkin** [forem/forem#11933]
**Is your feature request related to a problem? Please describe.**

Simplify deployment to non-technical users (or busy technical users who don't want to spend time on it)

**Describe the solution you'd like**

Heroku supports a one-click deployment process with a manifest file in the repo - user clicks the button, gets hobby or cheap account on Heroku and has the working Forem installation in under 5 min without ever opening terminal or typing any commands - all via browser UI.

**Describe alternatives you've considered**

Alternatives are more work/effort

**Additional context**

You can also add this button here: https://elements.heroku.com/buttons/ - didn't see this catalogue before...

The docs describing how to do it are here: https://www.heroku.com/elements/buttons

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
