### ISSUE TITLE
Navbar - Deformed navbar when pressing 'Notifications' on mobile view and android app

### ISSUE THREAD

**Issue by ItzaMi** [forem/forem#11949]
**Describe the bug**
When clicking the `notifications` icon, the navbar increases its width (probably due to the 'greyish' circle that appears around the selected icon) and it increases the entire page width

**To Reproduce**

1. Open dev.to on `android app` or `mobile view`
2. Click on the `Notifications` icon
3. See the increase in width

**Expected behavior**
Navbar should keep the same size

**Screenshots**
_Desktop - Mobile view_
![devToNavbarMobile](https://user-images.githubusercontent.com/30603437/102500969-caef5a80-4074-11eb-9e30-d6269424c818.gif)

_Android app view_
![ezgif com-gif-maker](https://user-images.githubusercontent.com/30603437/102501383-4b15c000-4075-11eb-9729-d9466e2ba480.gif)

**Desktop (please complete the following information):**

- Device: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- OS, version: macOS Catalina 10.15.5
- Browser, version: 87.0.4280.88 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device: Huawei Mate P10 lite
- OS, version: 8.0.0
- App, version: 1.5.0-2

**Additional context**
Added both `Desktop` and `Android` since both face the same problem

**Comment by narender2031** [comment]
I would like to work on this bug

**Comment by cmgorton** [comment]
@ItzaMi there have been new updates to mobile. Is this issue still appearing for you?
