### ISSUE TITLE
Add online events functionality

### ISSUE THREAD

**Issue by thospfuller** [forem/forem#11948]
I would like the ability to add an event (either online or in-person), for example, from [meetup.com](https://meetup.com).

See also [LinkedIn events](https://www.linkedin.com/help/linkedin/answer/98189/linkedin-events-overview?lang=en) for ideas regarding what this could look like.

Many events have moved almost entirely online due to the pandemic and are now being held over Zoom. This opens the door for anyone to attend irrespective of their location.

As this is date/time specific I suspect adding an "event" hashtag will not be an adequate solution for this idea.

Adding events would give users the benefit of expanding their network and would make the platform more valuable overall. LinkedIn allows event organizers to invite connections, which could be helpful here as well.

**Comment by cmgorton** [comment]
Hey @thospfuller we have the ability to add event listings. Is this what you had in mind or was it different?
https://dev.to/listings/events

**Comment by thospfuller** [comment]
Oh excellent! It would appear that I've missed that somehow so we can close this.

**Comment by cmgorton** [comment]
Sounds good. I think the listings often get over looked! We need to do a better job making them a little more known :)

**Comment by thospfuller** [comment]
I did not see the event show up when searching for something so you might consider allowing the search functionality to cover events too, possibly.

**Comment by cmgorton** [comment]
Good to know! I'll mention this to the team internally. We could potentially create a feature request for that instead.

**Comment by thospfuller** [comment]
See the attached image.
<img width="1159" alt="DevToSearchResultsAddEvents-11948" src="https://user-images.githubusercontent.com/736686/102542676-22df8e80-4080-11eb-9e9f-d2e4c478c3f6.png">
