### ISSUE TITLE
Contacts page is missing DEV email

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#11959]
**Describe the bug**

The contact page (https://dev.to/contact) currently lists `Email: 😁`.

**Expected behavior**

The contact page should say `Email: yo@dev.to`.

**Screenshots**

![Image 2020-12-17 at 4 54 13 PM](https://user-images.githubusercontent.com/16007075/102548376-91284f00-4088-11eb-94ca-e92348f6f0f3.png)

**Additional context**

This issue may be related to this PR - https://github.com/forem/forem/pull/11848.

**Comment by narender2031** [comment]
The reason behind the issue is env file don't have the value for `DEFAULT_EMAIL` on prod. To fix this we need to add the value to the key.

**Comment by Ridhwana** [comment]
Contact email now appears on /admin/config and is set across the site :)
