### ISSUE TITLE
Post comment subscription component is not loaded

### ISSUE THREAD

**Issue by glinda93** [forem/forem#11980]
**Describe the bug**

Post comment subscription component is not loaded in the first load.

**To Reproduce**

- Click any post in home page.

- Scroll down to comment section.

- You will see the following message:

> Unable to load Comment Subscription component.
> 
> Try refreshing the page.

**Expected behavior**

Comment subscription component should be loaded in the first place.

**Screenshots**

![image](https://user-images.githubusercontent.com/72871001/102666233-61309700-41c1-11eb-9832-9262e883a4eb.png)

- OS, version: **macOS** Catalina version 10.15.5
- Browser, version: Chrome Version 87.0.4280.88 (Official Build) (x86_64)

**Additional context**

If I refresh the page, subscription component is loaded correctly.

**Comment by cmgorton** [comment]
Hey @glinda93 I can't replicate this. Do you know if this is still an issue for you?
