### ISSUE TITLE
Auto Subscribe from RSS Feed Option

### ISSUE THREAD

**Issue by shadowtime2000** [forem/forem#12004]
**Is your feature request related to a problem? Please describe.**

Every time I cross post I have to click the subscribe to comments button. 

**Describe the solution you'd like**

An option by the RSS feed settings that allows me to auto subscribe to the comments of posts that get cross posted.

**Describe alternatives you've considered**

None.

**Additional context**

> Just because I cross post from Hashnode doesn't mean I don't care about what DEV users think

The option should go somewhere here:
![image](https://user-images.githubusercontent.com/66655515/102846168-25b1ea80-43c4-11eb-9c85-42c9436fe530.png)

**Comment by cmgorton** [comment]
Hey!  Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
