### ISSUE TITLE
Bug Found [UI responsiveness broken on the Opera Browser]

### ISSUE THREAD

**Issue by shravan20** [forem/forem#12000]
**Describe the bug**
The UI is distorted and broken in the Opera Browser.

The complete top part of the UI is completely broken and not in usable format.

**To Reproduce**

1. Open Opera Browser
2. Go to dev.to 
3. See error 

**Screenshots**
![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/nsnf2oanipsffu4oh87t.png)

**Desktop (please complete the following information):**

- OS, version: Linux Ubuntu 18.04
- Browser, version: Opera

**Comment by cmgorton** [comment]
Hey @shravan20 thanks for opening this issue. This is a known caching issues due to service workers. We have implemented a fix but you will still need to do a hard refresh of the browser or clear your cache. Can you let me know if that fixes it? Thanks.

**Comment by shravan20** [comment]
I cleared the cache, it's working fine now.

**Comment by cmgorton** [comment]
Great! Sorry for the inconvenience but I am glad that works for you know. 🎉
