### ISSUE TITLE
Net::OpenTimeout in registrations # create

### ISSUE THREAD

**Issue by stampylongr** [forem/forem#12014]
**Describe the bug**

Whenever I try to sign up, it immediately shows me that the account already exists, even though the database was just setup. I cannot log into the account, either. Whenever I try to access any other page, it just redirects to the admin account creation page.

**To Reproduce**

1. Sign up for an initial admin account.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/42777835/102940818-2f4c5880-447f-11eb-8a9a-1245b7732aa6.png)

**Desktop (please complete the following information):**

- OS, version: Chrome OS 87.0.4280.109
- Browser, version: Chrome 87.0.4280.109

**Additional context**

**Comment by cmgorton** [comment]
@forem/backend anyone able to take a look at this and help @stampylongr out?

**Comment by fdoxyz** [comment]
Hi @stampylongr, is this a local environment you're running? If yes, could you try pulling the latest from master (depending on your local setup you'll have to run `bin/setup` as well before trying again).

If the app is redirecting you to the admin account creation page it seems like it there aren't any users yet which makes this situation a bit odd.

**Comment by stampylongr** [comment]
Okay, I forgot to post an update.

@fdoxyz, this is a local instance running in production. I eventually found a workaround by running the command that is supposed to seed fake data (?), `MODE=starter rails db:seed`, and it would finally let me sign up, and it would let me access the admin panel and log in.

BTW, a lot of the source code's `ApplicationConfig` needed to be replaced with `SiteConfig` in order to get everything to work.

I have a bunch of changes on my hard drive that I will be pushing to GH, then creating a pull request that includes NGINX & systems config files.

**Comment by citizen428** [comment]
> BTW, a lot of the source code's ApplicationConfig needed to be replaced with SiteConfig in order to get everything to work.

Can you elaborate on this a bit? Did you have your environment variables set up correctly, e.g. via a `.env` file?

**Comment by stampylongr** [comment]
@citizen428 yes, it was set up correctly. It still wouldn't read from it most of the time, so I had to change a few references.

**Comment by fdoxyz** [comment]
I'm closing this issue since the original problem was solved. For reference, the "Starter Mode" and other DB configs are documented here: https://docs.forem.com/getting-started/db/

@stampylongr if you have any issues with the ENV variables or any other setup please feel free to open an issue and we'll be happy take an in-depth look at it.
