### ISSUE TITLE
Add "manage" button to any post that I can manage

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#12011]
**Is your feature request related to a problem? Please describe.**
As an organization admin, I can "manage" posts in my organization by doing the following:
- Go to `/dashboard`
- Select the organization dashboard in the drop-down
- Click the "manage" button

This is in contrast to the easy button that allows me to "manage" my own posts directly from the post itself.

**Describe the solution you'd like**
The "manage" button appears on all posts that I have the permissions to manage.

For most users, just their own posts.

For org admins, their own posts + posts in their organization.

**Additional context**
For illustration, given that both posts are within the `DEV Team` organization, I'd like the "manage" button to show up on both.  Currently, it only shows up on my personal post as I'm the OP.
<img width="692" alt="example with the manage button" src="https://user-images.githubusercontent.com/9434801/102912077-9ef02280-4442-11eb-8ef7-82e17b03bf6a.png">
<img width="744" alt="example without the manage button" src="https://user-images.githubusercontent.com/9434801/102912095-a1eb1300-4442-11eb-949e-d07632bde518.png">

**Comment by claracavalcante** [comment]
Hey, I would like to work on this one. Is it possible?

**Comment by nickytonline** [comment]
@claracavalcante, assigning this to you.

**Comment by cmgorton** [comment]
Hey @claracavalcante 👋
Thanks so much for volunteering for this issue. 
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. Given this process I am going to unassign you from this issue for now. 

In the meantime if you see any bugs you want to squash let me know and we can assign them to you!
