### ISSUE TITLE
Stuck user/group selector in connect

### ISSUE THREAD

**Issue by xpyxel** [forem/forem#12028]
**Describe the bug**

When selecting a user or group when on a small screen in connect, after the sidebar has been hidden, the currently selected item stays in view despite the sidebar being now hidden from view. 

**To Reproduce**

1. Open connect and tap the "back" button to open the sidebar
2. Select a different user or group than the current one that is selected
3. Observe that the selected item is still visible

**Expected behavior**

After an item has been selected, the item should be hidden from view along with the sidebar and list it belongs to.

**Screenshots**

[Screenshot_20201223-233336.png](https://user-images.githubusercontent.com/46457601/103061028-f5ab4880-4577-11eb-9b2f-aafeea15ddaf.png)

**Desktop (please complete the following information):**

Not applicable to this specific bug.

**Smartphone (please complete the following information):**

- Device: Google Pixel 2
- OS, version: Android 11 (RP1A.201005.004.A1)
- Browser, version: DEV Community Android App, as well as Firefox Android Preview 85.0.0-beta.3

**Additional context**

Not applicable to this report.

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
