### ISSUE TITLE
Disable the "moderator panel" notice after dissmissal

### ISSUE THREAD

**Issue by xpyxel** [forem/forem#12024]
**Is your feature request related to a problem? Please describe.**

Currently when viewing the moderator/trusted user panel on mobile it pops up a notification that it's better to use it on desktop, while this is perfectly fine, it currently repeatedly pops up, even after dismissal, which is both kind of annoying and frustrating especially when said user does not have access to a desktop or laptop at the current point in time. 

**Describe the solution you'd like**

After dismissing the notification, it should be "opted-out" and no longer appear. This could be done with a browser cookie, or a value stored in local storage, checked against it, and if it's a certain value, such as `hide-panel-notice: true` disable the notification.

**Describe alternatives you've considered**

Currently the only alternative to this is to use a desktop computer or enable "desktop mode" on the mobile browser if using the web version instead of the app, however on the app there is no possible way to get rid of this notification.

**Additional context**

You can see an example of this notification [here](https://fk.ci/9v6XMgp.png). The screenshot is not directly posted due to the size of it. It currently obstructs the view of the moderator panel on the mobile application and when using a mobile web browser.

**Comment by cmgorton** [comment]
Related #393

**Comment by cmgorton** [comment]
Related to https://github.com/forem/internalEngineering/issues/393

@xpyxel thank you for bringing this up. we have an internal issue with the same information that is currently going to be worked on this cycle. I am going to close this issue in favor of that one.
