### ISSUE TITLE
"Copied!" text wraps when an image is uploaded and the copy button is clicked in the post editor

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#12020]
**Describe the bug**

The "Copied!" text wraps when an image is uploaded and the copy button is clicked in the post editor.

**To Reproduce**
1. Upload an image for the body of a post by clicking on the Upload image button.

![image](https://user-images.githubusercontent.com/833231/103007737-eee1ee80-4501-11eb-9366-9ada8ca47b60.png)

2. Select an image from the native file system selector.

![image](https://user-images.githubusercontent.com/833231/103007787-06b97280-4502-11eb-9a2d-2498da7258d3.png)

3. Click the Copy button and notice the "Copied!" text wraps.

![image](https://user-images.githubusercontent.com/833231/103007826-1b960600-4502-11eb-8ea8-dde986e2e21b.png)

**Expected behavior**

The **Copied!** text should not wrap.

**Screenshots**

![Text wraps for the copied when image is uploaded in the body and the markdown is copied](https://user-images.githubusercontent.com/833231/103007559-9d396400-4501-11eb-90ae-62ef1be3fcd0.png)

**Desktop (please complete the following information):**

- OS, version: Mac OS 10.15.7
- Browser, version: Firefox Developer Edition 85.0b4 (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by ryy** [comment]
I want to work on this:laughing:

**Comment by ryy** [comment]
I'd like to fix this:laughing:

**Comment by Mandihamza** [comment]
Hello, I'd love to fix this bug. I just got the project running on my machine, and I think this will be perfect for my first contribution! 😎

**Comment by rhymes** [comment]
Thank you @Mandihamza, please go ahead. I've assigned the issue to you

**Comment by ludwiczakpawel** [comment]
@Mandihamza oh myyy... I've missed that you've been assigned to this issue and made a PR that fixes it :((( Sorry for this terrible mistake. Let me know if you have already started working on that, then I'll close my PR.

**Comment by Mandihamza** [comment]
Hey @ludwiczakpawel, no worries I'll find another bug to solve 😅
