### ISSUE TITLE
Question : How to register a webhooks which requires additional headers

### ISSUE THREAD

**Issue by chiubaca** [forem/forem#12038]
I've created a webhook for a Github action which I want invoked everytime I've created or updated a dev.to article.  However this webook requires some additional headers to be passed to it for security purposes. if I'm invoking this manually it looks like this:

```
curl -X POST https://api.github.com/repos/chiubaca/dev-blog/dispatches \
-H 'Accept: application/vnd.github.everest-preview+json' \
-H 'Authorization: token my-secret-token' \
--data '{"event_type": "webhook_test"}'
```

**To Reproduce**

This issue is that when registering a new webhook via a POST to `https://dev.to/api/webhooks`. There is only the `target_url` property where I can pass in the URL of the webhook. How do I provide the additional headers which is required to authenticate the webhook?

**Additional context**

This related to the DEV API

**Comment by chiubaca** [comment]
I was able to work around this by using a Netlify Function as a proxy which invokes my github action.

 - https://github.com/chiubaca/dev-blog/commit/a7b5b53bb5ed29cade31917f19e166993cfbd94e

**Comment by rhymes** [comment]
Hi @chiubaca! The webhook mechanism we have in place is pretty "barebones". Currently it is not possible to forward it headers to send upstream.

**Comment by chiubaca** [comment]
ok no probs, thanks for confirming. I was hoping there were some "secret" features that was'nt documented yet. I'm quite happy with my workaround.

**Comment by selenecodes** [comment]
Are there any plans to add this in the future?
