### ISSUE TITLE
The content of <code> tags is parsed as Markdown

### ISSUE THREAD

**Issue by kenbellows** [forem/forem#12046]
**Describe the bug**

Special characters within `<code>` tags are still parsed by the Markdown rather than being treated as literal characters. For example, pairs of asterisks can produce italics and, perhaps most problematic, comments starting with a hash (`#`) as in Bash, Ruby, Python, etc. are turned into `<h1>` tags and can even prematurely close the `<code>` block, such that the rest of the block is rendered as normal paragraph text.

**To Reproduce**

1. Go to https://dev.to/new
2. Enter the following in the post body:
  ```html
<code>
echo 'the below should render as a simple regex'
grep '^.*\w* bar$' myfile.txt

# test comment

echo 'Is this still rendered in monospace or is it paragraph text?'
</code>
   ```
3. Click on "Preview"
4. Note the aforementioned symptoms

See also this post, which initially alerted me to the problem: https://dev.to/chriss/git-hooks-and-huskyjs-13gb

**Expected behavior**

All code within the `<code>` tags should be rendered in a monospace font with all text preserved literally exactly as the user entered it.

**Screenshots**

![image](https://user-images.githubusercontent.com/657118/103218681-b9fede80-48e9-11eb-9f5a-a86e8d743dc6.png)

![image](https://user-images.githubusercontent.com/657118/103218697-c5eaa080-48e9-11eb-87ae-5a4406ff84a7.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10 OS Version 1909 (Build 18363.1256)
- Browser, version: Chrome 87.0.4280.88 (Official Build) (64-bit)

**Additional context**

One thought: this is definitely not the standard way to enter code in Markdown. Typically an author should enter code using triple backtick fences (\`\`\`), and I get that. However, as seen in the linked post (https://dev.to/chriss/git-hooks-and-huskyjs-13gb), there are definitely still authors who use `<code>`. Anyway, if Forem's official approach is to not handle  `<code>` tags the same way as triple backticks (which may be the right choice for various reasons), I think this should be called out in the formatting help text, maybe even displaying a warning when `<code>` tags are detected, e.g. "It looks like you are using  `<code>` tags. It is recommended to use Markdown's triple backticks instead, as some code elements may not render corrctly within `<code>` blocks."

Just my thoughts; you folks do a great job, so I'm sure your solution will be great, whatever it is!

**Comment by cmgorton** [comment]
Thanks for opening this issue. I definitely like the work around you mentioned and agree adding a warning here could be useful if we continue not to support <code> tags. I'll let others weigh in on how we want to approach this in the future but really appreciate the added context you provided.

**Comment by Miguel-Enrique13** [comment]
@cmgorton - Could you assign this issue to me

**Comment by Miguel-Enrique13** [comment]
@cmgorton - Was there a decision as to how we should move forward with this issue? Should I make the code tag work or should I work on displaying a warning when a user uses the code tag?

**Comment by cmgorton** [comment]
@Miguel-Enrique13 let me ping our OSS rotation engineers to see if they have any additional feedback on this before you get started. Thanks for asking for clarification. 

@rhymes @katiedavis Miguel is an MLH fellow working on some of our markdown bugs. Could either of you guide him a little on this issue before he creates a PR. Would the proposed additional context in the original issue be a good way to tackle this bug?

**Comment by rhymes** [comment]
Hi @Miguel-Enrique13, thanks a lot for volunteering on this!

I checked the issue and the MDN documentation of the [<code>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code) tag. 

Though technically code is an inline element, I wonder if we've been treating it as it was a substitute for `<pre>`. 

MDN explicitly states:

> To represent multiple lines of code, wrap the <code> element within a <pre> element. The <code> element by itself only represents a single phrase of code or line of code.

I wonder if the algorithm we should use is the following:

- if a `<code>` tag is inline, leave it be
- if a `<code>` tag contains at least a newline and its parent is a `<pre>`, leave it be
- if a `<code>` tag contains at least a newline and its parent is not a `<pre>`, wrap it into a `<pre>`

How does this sound?  If you manually take the example in the initial comment and wrap it in a `<pre>`, everything works.

I'd start looking into this from the following two places in the code:

https://github.com/forem/forem/blob/66e4747d3fb01bf354123763bed9dd80fb390bf8/app/services/markdown_processor/parser.rb#L132

https://github.com/forem/forem/blob/66e4747d3fb01bf354123763bed9dd80fb390bf8/app/services/html/parser.rb#L1-L2

Hope this helps.

cc @ludwiczakpawel in case we need special styling but I think this should be enough
