### ISSUE TITLE
docker-compose.yml error

### ISSUE THREAD

**Issue by ygpark2** [forem/forem#12064]
**Describe the bug**

I found two errors in docker-compose file by trying to start the docker images.

First, .bundle_finished file seems to be wrongly configured.

Secondly, the "yarn install --dev" command cannot be found

**To Reproduce**

./bin/container-setup

**Expected behavior**

It should show the rails server ready message.

**Comment by cmgorton** [comment]
@msarit was this issue fixed? We had some one else add a similar issue today. #12068

**Comment by msarit** [comment]
@cmgorton Hi Christina. To be honest, I am not sure. I deployed this PR yesterday and there were no build errors. However I did not verify this in production. I will attempt to do so today.

**Comment by cmgorton** [comment]
Great! Thanks @msarit . I realized after I sent the comment that the issue was probably closed because the PR had been merged.
