### ISSUE TITLE
CommonMark conformance

### ISSUE THREAD

**Issue by dtinth** [forem/forem#12061]
**Is your feature request related to a problem? Please describe.**

`dev.to` uses Redcarpet which is [not conformant](https://github.com/vmg/redcarpet/issues/429) with [the CommonMark spec](https://spec.commonmark.org/0.29/). This leads to frustration when publishing Markdown written in other editors that follows CommonMark, especially when I always use Prettier to format my Markdown.

The following discrepancy exists which I find particularly annoying:

1. **List item indentation.** From the CommonMark spec:

   > The most important thing to notice is that the position of the text after the list marker determines how much indentation is needed in subsequent blocks in the list item. If the list marker takes up two spaces, and there are three spaces between the list marker and the next non-whitespace character, then blocks must be indented five spaces in order to fall under the list item.

   In Dev.to, the Markdown parser requires **at least 4 spaces** to successfully put subsequent blocks inside the list item. However, Prettier only indents list items by the minimum amount of spaces required, so it uses 3 spaces. To keep my existing workflow I would need to add `<!-- prettier-ignore-start -->` before creating list whose items contain multiple blocks.

2. **Starting an ordered list from other numbers.** From the CommonMark spec:

   > If the list item is ordered, then it is also assigned a start number, based on the ordered list marker.

   In Dev.to, the Markdown parser resets the numbering to 1 on the 2nd list.

These issues are illustrated in this example:

<table><thead><tr><th scope="col">Markdown</th><th scope="col">CommonMark</th><th scope="col">dev.to</th></tr></thead><tbody><tr><td><pre>1. Do this<br><br>   ```<br>   ls<br>   ```<br><br>2. Do that</pre></td><td><ol><li><p>Do this</p><pre><code>ls</code></pre></li><li><p>Do that</p></li></ol></td><td><ol><li>Do this</li></ol><pre><code>ls</code></pre><ol><li>Do that</li></ol></td></tr></tbody></table>

**Describe the solution you'd like**

Use a CommonMark-compliant parser.

- [GitHub Flavored Markdown](https://github.github.com/gfm/) is based on CommonMark spec.
- [Prettier is compliant with CommonMark](https://prettier.io/blog/2017/11/07/1.8.0.html#markdown-support).
- [StackOverflow and all Stack Exchange sites are using CommonMark](https://meta.stackexchange.com/questions/348746/were-switching-to-commonmark) now.

**Describe alternatives you've considered**

To use CommonMark there are many approaches:

1. Allow specifying Markdown parser to use #1492. Easier than approach 2 but can lead to lots of configuration.
2. Convert existing Markdown entries to be CommonMark compliant. Maybe using Hast and Mdast. Cleaner overall but harder than approach 1.

**Additional context**

N/A

**Comment by cmgorton** [comment]
Thanks for opening this issue. I plan to compile the several markdown feature requests we have here and bring them up to the team in the new year.

**Comment by cmgorton** [comment]
Hey @dtinth we currently have some people working on the Markdown bugs in our repo. This is a bigger feature and features tend to be subjective while spurring some debate 😄
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. 

If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it.

**Comment by AlexFreik** [comment]
Is there any news? It would be really nice to be able to use CommonMark

**Comment by mihneasim** [comment]
issue #575 was closed in favour of #1492 which was closed in favour of current #12061, which consequently was closed in favour of a forem.dev discussion which i failed to find.

@cmgorton i think according to [this post here](https://forem.dev/foremteam/heads-up-github-discussions-and-feature-requests-54ff) on 15h of Nov 2021, we should reopen this issue for discussion, here on Github. What do you think?

If we do not get any answer in a reasonable time, i will politely ask @dtinth to resubmit this discussion on Github. Personally, I believe non-conformance to standards, should be treated as bugs, as all users expect Markdown formatting to behave in a uniform way. Thank you!

**Comment by dtinth** [comment]
@mihneasim I’m not using dev.to as much now… you can go ahead and create a discussion on GitHub.

Once it’s posted, you can put the link to that discussion here, and then I’ll go and upvote it. 😃
