### ISSUE TITLE
Sometimes clicking an internal link leads me to the empty search result page

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#1206]
**Describe the bug**
This happens randomly and inconsistently, but sometimes clicking a link that is a `https://dev.to` link will lead to empty search result page: https://dev.to/search?q=

**To Reproduce**
1. Go to https://dev.to
2. Click on a link, like https://dev.to/latest
3. See that you're landed in https://dev.to/search?q= instead of https://dev.to/latest . Note that the URL is correctly linked to /latest, but the page rendered is the empty search page.

**Expected behavior**
Links properly work and correctly navigate to the location.

**Desktop (please complete the following information):**

- OS: macOS 10.13.5
- Browser Firefox Developer Edition version 64.0b9

**Additional context**
I'll try to attach a screenshot if I can reproduce it.

**Comment by yafkari** [comment]
Here is a screenshot of the issue :
![error](https://user-images.githubusercontent.com/41365655/50179881-750e3d80-0308-11e9-8d09-6260a5218c58.png)

I also encountered this problem, but as you can see on the screenshot, the url is the one of the home page.

**Comment by yafkari** [comment]
@Zhao-Andy, I have this issue when I click on the DEV button on the top-left corner from my dashboard page.

As you said, it happens randomly.

I just checked and effectively the URL is the one of the home page.
It means that the button redirects me to the right place but the page doesn't generate the home page.

**Comment by maestromac** [comment]
not stale

**Comment by mstruve** [comment]
Testing all the links on the homepage and they all seem to be behaving properly. Since this bug is really old and a lot has changed since then I am going to assume it is resolved and close it. If anyone in the future comes across this issue please feel free to explain your situation and open it back up!!!
