### ISSUE TITLE
Sidebar does not close when visiting login link

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#12067]
**Describe the bug**

When you visit login link from the sidebar in mobile it does not close

**To Reproduce**

1. Go to dev.to in mobile
2. Open sidebar
3. Click on login link
4. The sidebar won't close even-though  the url has changed.

**Expected behavior**

The sidebar should close when you visit login link from the sidebar

**Screenshots**

https://user-images.githubusercontent.com/8092120/103300032-efa7e280-4a23-11eb-9c44-3df69a5119ad.mp4

**Smartphone**

- Device: readmi note 6 pro
- OS, version: 10
- Browser, version: 1.17.75

**Comment by cmgorton** [comment]
Thanks for opening this @Rafi993 ? Does it go away if you hit the X on top?

**Comment by Rafi993** [comment]
> Thanks for opening this @Rafi993 ? Does it go away if you hit the X on top?

Yes it does.

**Comment by Rafi993** [comment]
Other links in the sidebar also does causes the sidebar to stay opened after navigation.

**Comment by Rafi993** [comment]
Hi there. If this issue is not taken up I can help.

**Comment by aitchiss** [comment]
Closing as I believe this was fixed in #12723 - please do re-open if you're still seeing this bug though!
