### ISSUE TITLE
Improve retry intervals for dockerize commands in docker-compose

### ISSUE THREAD

**Issue by mjobrien** [forem/forem#12099]
**Is your feature request related to a problem? Please describe.**

I just started getting forem up and running to see how I might contribute. I stumbled a bit on the issue in #12068, and that stumble was exacerbated by the flood of retry messages from the various Docker containers trying to connect to each other. The error message flowed off screen quickly due to the volume of retry messages.

**Describe the solution you'd like**

I found that there is a `-wait-retry-interval` argument available to the `dockerize` command. I set that to 10s on a couple of the services in `docker-compose.yml` and found that drastically reduced the noise in the output when running `bin/container-setup`. That made it easier to understand what is happening as the services start up.

All developers could benefit from less noise in the outputs when using the Docker environment. I'd like to set appropriate `-wait-retry-interval` values across services that balance potential delays in startup time with noise in the outputs.

**Describe alternatives you've considered**

As noted in the discussion of #9532, the initial setup time is much slower compared to subsequent runs. Depending on the user's computer, whether it's their first time running forem, etc., it's possible that the default 1s retry interval is appropriate. I've not found that to be the case on my 2017 MacBook Pro.

**Additional context**

N/A

**Comment by rhymes** [comment]
Hi @mjobrien, great find! Would you like to submit a PR to adjust to a sensible retry interval? Thank you!

**Comment by mjobrien** [comment]
Thanks for the invitation, @rhymes. PR submitted.
