### ISSUE TITLE
Internal Server Error?

### ISSUE THREAD

**Issue by workpebojot** [forem/forem#12095]
When I write an article, this always happens? But I don't believe this is a bug, but I am missing something?

![Annotation 2021-01-01 223740](https://user-images.githubusercontent.com/38276345/103440671-9093d900-4c82-11eb-87f6-d8c25fdc6add.png)

**Comment by workpebojot** [comment]
I can't post an article in dev.to and always receiving this error:
![Annotation 2021-01-02 112836](https://user-images.githubusercontent.com/38276345/103450204-c9b56300-4ced-11eb-8e59-9e9e64e010b2.png)

And also, I can't update my my article?

**Comment by rhymes** [comment]
Hello @workpebojot, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
