### ISSUE TITLE
"More" side nav does not expand after navigation

### ISSUE THREAD

**Issue by cpluta** [forem/forem#12102]
**Describe the bug**
Navigating around my forem and forem.dev I noticed when you click "More..." it will not expand. This works only on the initial page load. This seems to work on a mobile phone.

**To Reproduce**
1. Go to forem.dev
2. Click "Home"
3. Click "More..."

**Expected behavior**
More will expand.

**Screenshots**
No screenshots to show.

**Desktop (please complete the following information):**

- OS, version: Windows  10
- Browser, version: FireFox 84.0.1

**Smartphone (please complete the following information):**

- Device: Pixel 4
- OS, version:  Android 11
- Browser, version: Chrome 87.0.4280.101

**Additional context**

N/A

**Comment by ludwiczakpawel** [comment]
1. Can you try to clear your cache? 
2. If it still happens, can you check if there are any errors in the console?

**Comment by cmgorton** [comment]
It didn't work for me either until I cleared my cache. Works for me now.

**Comment by nickytonline** [comment]
Thanks for reporting @cpluta! I'm going to close this as it is a caching issue. I had the same problem and refreshing fixed the issue.

Caching issues like this are something we're looking to improve.
