### ISSUE TITLE
Netlify docsdevto build fails due to no content change

### ISSUE THREAD

**Issue by BogDAAAMN** [forem/forem#12108]
**Describe the bug**

[Netlify docsdevto](https://app.netlify.com/sites/docsdevto/deploys) is built on every [github.com/forem/forem](https://github.com/forem/forem) PR and fails if there is no content change.

```
10:54:33 AM: No changes detected in base directory. Returning early from build.
10:54:33 AM: Failed during stage 'checking build content for changes': Canceled build due to no content change
10:54:33 AM: Finished processing build request in 19.336942253s
```
_snippet from master@[e41c995](https://github.com/forem/forem/commit/e41c9954d6dfa887de78229b47e33c44822caa47) build_

**To Reproduce**

- List of Netlify builds: https://app.netlify.com/sites/docsdevto/deploys
- Log of master@[e41c995](https://github.com/forem/forem/commit/e41c9954d6dfa887de78229b47e33c44822caa47) build: https://app.netlify.com/sites/docsdevto/deploys/5ff2e5c4d7e5dc0007293c9a

**Expected behavior**

While this is not an real issue (Netlify builds do suceed when changes are pushed) I am just thinking if the build status influence other parts of the system (I first noticed the README [Netlify tag](https://api.netlify.com/api/v1/badges/e5dbe779-7bca-4390-80b9-6e678b4806a3/deploy-status)). 

Or open up a discussion about the possibilities of strategically building the docsdevto to reduce the no-content builds – or if it's worth the effort to change it.

**Comment by nickytonline** [comment]
Thanks for reporting this @BogDAAAMN. I believe we'll need to change the Netlify config to avoid getting this error. cc: @Zhao-Andy.

**Comment by Zhao-Andy** [comment]
Thanks for bringing this up! The current setup is to cancel a Netlify build for docs.forem.com or storybook.forem.com in a PR. However, in Netlify cancelling a build does trigger a failed status. Theoretically this is all we need, but it is annoying to have it send the failed state over. I'm not sure if there's anything in Netlify's configuration that we can change to account for that.

**Comment by vaidehijoshi** [comment]
Note: whoever picks this up will need to obtain access to Netlify!

**Comment by Zhao-Andy** [comment]
Awaiting response from Netlify since I couldn't find an option to configure this.

**Comment by vaidehijoshi** [comment]
@Zhao-Andy Since you've started investigating/reaching out to netlify and assigned yourself to this issue, can we add this to in progress? :)

**Comment by Zhao-Andy** [comment]
Unfortunately Netlify support has told me this is an issue on their end, and not something we can configure. :(

Related Netlify community post: https://community.netlify.com/t/status-badge-incorrectly-shows-failing-when-deploy-is-auto-cancelled/7316

We can remove the badge and any related commit statuses from the repo, or continue as we currently have until it is fixed by Netlify.

**Comment by BogDAAAMN** [comment]
Thank you for the heads-up @Zhao-Andy ✨
