### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by zplusfour** [forem/forem#12134]
i want to read dev.to's awesome posts, why I cant?

**Comment by nickytonline** [comment]
Closing as the https://dev.to site is up  and running.

**Comment by zplusfour** [comment]
I don't think so:
![image](https://user-images.githubusercontent.com/73612690/103760321-9c362580-501d-11eb-89d3-ad6fad4d9892.png)

**Comment by rhymes** [comment]
@zplusfour can you refresh your cache? Do you have any errors in the javascript console? Can you see the website wen you're not signed in in incognito mode?
