### ISSUE TITLE
Saving unpublished blog post after fixing validation error makes it published

### ISSUE THREAD

**Issue by DonKarlssonSan** [forem/forem#12131]
**Describe the bug**
When saving an _unpublished_ blog post after fixing validation error it becomes _published_

**To Reproduce**

- Create a new blog post
- Add something that is validated, for example: `{% codepen https://codepen.io/DonKarlssonSan/pen/dyMaRJN default-tab=result %}`
- "Save draft"
- Edit the blog post
- Change the content to something that is not valid, for example: `{% codepen https://codepen.io/DonKarlssonSan/pen/dyMaRJN default-tab="result" %}`
- Click "Save draft"
- An error message is displayed: "Whoops, something went wrong: base: Invalid Options"
- Fix the error (remove the "" around result)
- The only option is to click "Save changes" 
- The blog post is _published_

**Expected behavior**

- In the last step: the blog post is saved and kept un-published

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10, MacOS 11.1
- Browser, version: 84.0.1 (64 bit)

**Additional context**

**Comment by nickytonline** [comment]
I exhibited this the other day myself. Thanks for reporting @DonKarlssonSan!

**Comment by vaidehijoshi** [comment]
@citizen428 Was this issue fixed by https://github.com/forem/forem/pull/12288, or is there still more work to be done on this front? Just want to confirm before closing it out :)

**Comment by citizen428** [comment]
No, it's done, apparently this whole cycle I forgot add "Closes" in front of the PR numbers and lost automation. 🤦‍♂️
