### ISSUE TITLE
Profile generalization: Elasticsearch

### ISSUE THREAD

**Issue by citizen428** [forem/forem#12158]
So far I only did [some basic work](https://github.com/forem/forem/pull/10313) around indexing the new profile fields in Elasticsearch. we need to figure out the full migration path from what we did before to how profiles are implemented now. Some additional context can be found in this [Slack thread](https://forem-team.slack.com/archives/C0186BE65TN/p1599118718041800).

Note: Before picking up this task it's advisable to check in with the progress of our [Postgres FTS spike](https://github.com/forem/forem/pull/11985) as this may render this task obsolete.

**Comment by mstruve** [comment]
Given we are moving forward with Postgres this is no longer needed 💃
