### ISSUE TITLE
Ability to change colors on themes

### ISSUE THREAD

**Issue by xpyxel** [forem/forem#12156]
**Is your feature request related to a problem? Please describe.**

The current color schemes are nice, but the ability to change the accent colors would give people the ability to give their ui a bit more "personality" talored to them in a sense, an example of this is the Night and Ten X Hacker themes, while they are nice, the ability to change the accent color, for example the green on the Ten X Hacker theme, and the blue (on the buttons, etc) on the Night theme, would add a bit more customization.

**Describe the solution you'd like**

A color picker or selection of colors to choose from when choosing themes that allows you to choose the accent color on themes, or perhaps the ability to change the colors of the website per-use completely? Such as choosing background color, etc, this would however have to be on a select-from-available basis as you don't want people choosing color schemes of for ex, white on white.

**Describe alternatives you've considered**

Only possible alternative (currently) is either using the current themes with their default accents/colors, or using a third party extension such as stylish/stylus to change the theme of the website externally. 

**Additional context**

An example of what i mean is changing the green used in [this screenshot/theme](https://fk.ci/4tLP8zi.png).

**Comment by cmgorton** [comment]
Related to #11504

**Comment by cmgorton** [comment]
Hey @xpyxel  Thank you for opening this request.
As I mentioned in another request, features tend to be subjective and might spur some debate. I think this is a cool idea and would love if you'd propose this new feature, on [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
