### ISSUE TITLE
Can't change profile info

### ISSUE THREAD

**Issue by ascii-naut** [forem/forem#12168]
**Describe the bug**

When I try to change any of my account information, I receive an error stating "Error: Available for is too long (maximum: 200)". My email for Twitter and GitHub is the same.

**To Reproduce**

1. Log into your account
2. Go to Settings
3. Choose profile
4. Change something
5. Click 'Save profile information'

**Expected behavior**

I expect my profile information to be changed.

**Screenshots**

![0cda8a59863ca7405827b353e870e5dd](https://user-images.githubusercontent.com/40846846/103911673-f95dd400-510e-11eb-9ea6-f38a42eb9330.gif)

![error-dev](https://user-images.githubusercontent.com/40846846/103911726-0da1d100-510f-11eb-83b9-264dc9af6434.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome - Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone 12 Mini
- OS, version: iOS 14.2.1
- Browser, version: Safari - latest

**Additional context**

I assume this has something to do with me not approving my email change if that helps.

**Comment by rhymes** [comment]
Hi @ascii-naut, I think your "available for" section contains too much text, can you check

![Screenshot_2021-01-07 Settings - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/103912635-d3810100-5107-11eb-94ef-62a80119e0bb.png)

in https://dev.to/settings/ ?

**Comment by ascii-naut** [comment]
You've got an eagle eye! That fixed it, thanks.
