### ISSUE TITLE
Absence of Scroll Back To Top

### ISSUE THREAD

**Issue by AswinBarath** [forem/forem#12206]
No "Scroll Back To Top" link is present at the end of the README.md file.

**Comment by AswinBarath** [comment]
I am working on it.

**Comment by AswinBarath** [comment]
I have submitted my pull request:
[https://github.com/forem/forem/pull/12208](Absence of Scroll Back To Top #12206)

**Comment by cmgorton** [comment]
Looks like your PR was merged. 🥳
Thanks for time and your contribution! I will go a head and close this issue now.
