### ISSUE TITLE
Punctuation mistakes

### ISSUE THREAD

**Issue by AswinBarath** [forem/forem#12207]
There are certain punctuation mistakes in README.md file.

**Comment by AswinBarath** [comment]
I'm working on it

**Comment by AswinBarath** [comment]
I have submitted my pull request:
[https://github.com/forem/forem/pull/12209](Punctuation mistakes #12207)

**Comment by cmgorton** [comment]
Looks like your PR for this one was merged as well. 🎉
Thanks again for your time and contributions. I will go a head and close this issue.
