### ISSUE TITLE
ERROR :You have encountered an error.

### ISSUE THREAD

**Issue by Anjan50** [forem/forem#12214]
### **Describe the bug**
Whenever I click on  Write Post button It shows error like: 

" **Ooooops...**
You have encountered an error.
Our team has been notified.
We apologize for any inconvenience. "

### **To Reproduce**
I already mail my bug in **yo@dev.to**. But I didn't get reply. 

### **Screenshots**
![Error](https://user-images.githubusercontent.com/49095535/104270096-ab095600-54bd-11eb-9902-e19d618996ca.png)

### **Desktop (please complete the following information):**

- OS, version: **Windows 10**
- Browser, version: **Chrome**

### **Smartphone (please complete the following information):**

- Device: **Mi Note 5**
- OS, version: **Android**
- Browser, version: **Chrome**

### **Additional context**

Dev Account:
Username: Anjan50
Email: anjanjee11@gmail.com

**Comment by rhymes** [comment]
Hello @Anjan50, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by Anjan50** [comment]
> Hello @Anjan50, thanks for notifying us of this problem, this looks an issue specific to your account.
> 
> Please email [yo@dev.to](mailto:yo@dev.to) for more help.

I already mailed yo@dev.to but I did't get reply. can you please help..
