### ISSUE TITLE
When I click any link on site , that error is raising.

### ISSUE THREAD

**Issue by ErhanCetin** [forem/forem#12235]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by cmgorton** [comment]
Hey @ErhanCetin could you provide more context here? What error are you seeing and what browser are you using? Could you provide any screenshots?

**Comment by cmgorton** [comment]
Hey @ErhanCetin . I am going to close this issue since there isn't any context. Feel free to add more and we can reopen it. Thanks!
