### ISSUE TITLE
Email list does not allow 2-character domains

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12269]
This came up in trying to validate domains in `allowed_domains_include_improper_format`.

Reproduce:

Go to `/admin/config` follow steps to add authentic-able domains for email auth. `me.com` will not work.

**Comment by fdoxyz** [comment]
@benhalpern given that #12268 was merged, can we consider this closed?

**Comment by benhalpern** [comment]
@fdoxyz yep, oops meant to close it.
