### ISSUE TITLE
Links to articles in digest email don’t work

### ISSUE THREAD

**Issue by gonsie** [forem/forem#12261]
Clicking a link to an article in the weekly email digest doesn’t work on IOS with the app installed. Clicking a link will switch to the app, but the linked article is not brought up. 

1. On iOS with the app installed
2. Click on an article link in the weekly digest email
3. The DEV app is brought forward, but the linked article is not. 

- Device: iPhone 
- OS, version: iOS 14.2
- Browser, version:

**Comment by cmgorton** [comment]
@fdoxyz pinging you on this mobile issue in case you have any thoughts on this.

**Comment by cmgorton** [comment]
Got another report about this today:

_"For some time, links that I receive from the newsletter are not opening in the app.

Today I tried opening a Google search result and it’s the same.

When I click the app opens, but it displays the home page, it does not open the link."_

**Comment by fdoxyz** [comment]
Thanks for the heads up @cmgorton, this one is a recurring issue indeed. Here's the `DEV-ios` [original issue tracking this](https://github.com/forem/DEV-ios/issues/242#issuecomment-743441380) but I'm okay with keeping this open until we can ship the fix.

**Comment by cmgorton** [comment]
Great! Thanks for letting me know @fdoxyz .

**Comment by fdoxyz** [comment]
DEV iOS version `1.5.1` was released earlier today. Thank you everyone for the patience with this issue and some of the other smaller bugs fixed by this release. 

I'm closing now but if the issue persists after updating the app feel free to reopen or create a new issue for it :)

**Comment by gonsie** [comment]
Works great! Thank you so much @fdoxyz  for the fix.
