### ISSUE TITLE
All Profile Updates are Lost When 1 Field is Invalid

### ISSUE THREAD

**Issue by mstruve** [forem/forem#12284]
**Describe the bug**

When you go to update your profile you can fill in multiple fields at a time. If you fill in many of those fields and then submit form, if 1 field is invalid you will receive an error message and none of the fields will have been saved. This can be very frustrating if you spent a lot of time filling them all out and only 1 was wrong. 

Error:
![Screen Shot 2021-01-14 at 2 22 23 PM](https://user-images.githubusercontent.com/1813380/104638581-f6616700-566b-11eb-984b-69c2318d748c.png)

Fields I had previously all filled out:
![Screen Shot 2021-01-14 at 2 25 34 PM](https://user-images.githubusercontent.com/1813380/104638626-0da05480-566c-11eb-830e-d32b0036b338.png)

**To Reproduce**

1. Go to edit profile page
2. Fill in multiple fields but make the summary very long.
3. Click save profile information at the bottom
4. You should receive an error that your summary was too long but nothing else was saved.

**Expected behavior**

We should save what we can and only skip saving those fields that are invalid.

**Comment by rna** [comment]
Hi @mstruve, I would like to work on this.

**Comment by mstruve** [comment]
@rna sounds great! I will assign you. If for some reason you get busy and can't get it done please let us know! Thank you!!!
