### ISSUE TITLE
Refactor spec/requests/admin/configs_spec.rb

### ISSUE THREAD

**Issue by mstruve** [forem/forem#12283]
Per @atsmith813's great suggestion in https://github.com/forem/forem/pull/12281, in an effort to make the specs in spec/requests/admin/configs_spec.rb more resilient to changes in our default SiteConfig values we should update them to remove the hardcoded defaults. 
 
For example, we have

```ruby
it "updates rate_limit_feedback_message_creation" do
  expect do
    post "/admin/config", params: { site_config: { rate_limit_feedback_message_creation: 3 },
                                    confirmation: confirmation_message }
  end.to change(SiteConfig, :rate_limit_feedback_message_creation).from(5).to(3)
end
```
We should update this to check the default value rather than the hardcoded 5
```ruby
it "updates rate_limit_feedback_message_creation" do
  expect do
    default_value = SiteConfig.get_field(:rate_limit_feedback_message_creation).dig(:default)
    post "/admin/config", params: { site_config: { rate_limit_feedback_message_creation: 3 },
                                    confirmation: confirmation_message }
  end.to change(SiteConfig, :rate_limit_feedback_message_creation).from(default_value).to(3)
end
 ```

There are multiple specs that behave like this. To complete this task you should update all of them.

**Comment by shilpi230** [comment]
@mstruve I would like to take this one. Thanks! And I assume this is the only one file `spec/requests/admin/configs_spec.rb` which needs change right?

**Comment by shilpi230** [comment]
There are few things in file which I noticed, in which are just directly checking `.to eq("value")` instead of `from(default_value).to eq(new_value)` Is that fine or we should change it?

**Comment by shilpi230** [comment]
@mstruve I raised the [PR](https://github.com/forem/forem/pull/12315) but some of the test case failed. I wonder how, I didn't change anything in code. Just one test case file I changed. Can you please help me with it. Thanks!
