### ISSUE TITLE
Add Crayons to the "Destroy your account" page

### ISSUE THREAD

**Issue by rhymes** [forem/forem#12296]
**Describe the bug**

Right now the "Destroy your account" page looks like this:

![Screenshot_2021-01-15 Screenshot](https://user-images.githubusercontent.com/146201/104748582-2d11ad00-5752-11eb-9fb4-0645cfe4b0b4.png)

**To Reproduce**

1. Turn on caching with `bundle exec rails dev:cache`
2. Go to http://localhost:3000/settings/account
3. Click on "Delete account"
4. Check the logs and copy the URL, it should be something like `http://localhost:3000/users/confirm_destroy/$DESTROY_TOKEN` (the token lasts 12 hours)
5. Go to said URL and see the page

**Expected behavior**

Something more pleasing to the eyes :D

**Comment by narender2031** [comment]
can I work on this issue?

**Comment by ludwiczakpawel** [comment]
@narender2031 Go for it!

I belive we could reuse similar design/layout to what we have for comment editing/deleting:

https://user-images.githubusercontent.com/108287/105031322-736a5300-5a55-11eb-9d38-07f778af9dd5.mov

**Comment by narender2031** [comment]
@ludwiczakpawel  Can you please confirm that UI is what you required?

<img width="1440" alt="Screenshot 2021-01-20 at 11 35 18 AM" src="https://user-images.githubusercontent.com/25151772/105134008-ba1e8280-5b13-11eb-99fc-4afbaaad11a6.png">

**Comment by ludwiczakpawel** [comment]
I think this is a really good start. If you open a PR, I could add some suggestions in the code itself 👍

**Comment by narender2031** [comment]
@ludwiczakpawel Please take a look at the PR.
