### ISSUE TITLE
Images as a user profile banner

### ISSUE THREAD

**Issue by xpyxel** [forem/forem#12303]
**Is your feature request related to a problem? Please describe.**

Not related to a issue or problem. Simply just would be a nice addition.

**Describe the solution you'd like**

Currently on user profiles the background/banner is based on the brand colors. It would be a nice addition to DEV and Forems in general if you were able to have per-user profile banners as images as an option as well. To be clear I am talking about [this](https://fk.ci/3gBwMXC.png) part of profiles specifically. 

**Describe alternatives you've considered**

There is no real alternatives to this as of currently, unless you were to have some type of styling browser extension to manually set it, but even then, it's private to you and you only, and no one else can see it. So this is a downside.

**Additional context**

I could see a few problems with this from a few standpoints. From a moderation standpoint, this would be more to moderate and manage, as trolls / spam accounts could do things such as upload inappropriate or crude images as their banners, this is already a concept with say profile pictures, article banners, but it doesn't seem to be prevalent if at all, so adding something like profile banner images, shouldn't cause too much chaos.

**Comment by cmgorton** [comment]
Hey @xpyxel  Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
