### ISSUE TITLE
Refactor Fastly purge calls to use PURGE instead of POST

### ISSUE THREAD

**Issue by atsmith813** [forem/forem#12326]
**Is your feature request related to a problem? Please describe.**
A while ago, [Fastly soft-deprecated their original method for purging endpoints via their API](https://github.com/fastly/fastly-ruby#efficient-purging). We are still using the old method.

**Describe the solution you'd like**
While the old method still works, we should update to the new method in case Fastly discontinues support for this old method. Also, the new method is the same method we use for NGINX purging and is quite common with "today's purging practices". We should explore refactoring the purge calls for Fastly.

As noted in the [README of the `fastly-ruby` gem](https://github.com/fastly/fastly-ruby#efficient-purging), [the old method of purging consists of sending a `POST` request to `https://api.fastly.com/purge/path_to_purge`](https://github.com/forem/forem/blob/master/app/services/edge_cache/bust/fastly.rb).

The new method is to send `PURGE` request to the path we're trying to purge - noted in the [README](https://github.com/fastly/fastly-ruby#efficient-purging) and the [documentation](https://developer.fastly.com/reference/api/purging/).

To send a `PURGE` request, we can do it similar to [how the `fastly-ruby` gem does it](https://github.com/fastly/fastly-ruby/blob/159ae26e4fe41bcdef2fc8f45c25d7dd4f0a5cbe/lib/fastly/client.rb#L180-L185) which is also the same as [how we currently do it with NGINX](https://github.com/forem/forem/blob/b9d50a77f0ad8fe8770729fa2d530f4327a48519/app/services/edge_cache/bust/nginx.rb#L40-L47). The TLDR is that it creates a custom method using `Net::HTTP`:

```ruby
class Net::HTTP::Purge < Net::HTTPRequest
  METHOD = "PURGE".freeze
  REQUEST_HAS_BODY = false
  RESPONSE_HAS_BODY = true
end

http = Net::HTTP.new(uri.host, uri.port)
response = http.request Net::HTTP::Purge.new(uri.request_uri)
```

**Describe alternatives you've considered**
Caching has been discussed at length in several contexts. The most recent conversation can be found over [here](https://github.com/forem/forem/issues/12265). We've talked about alternatives such as leaving it as is, moving to purge by key, etc.

**Additional context**
- We want to make sure we keep [authentication on URL purge requests via the API](https://github.com/forem/forem/blob/b9d50a77f0ad8fe8770729fa2d530f4327a48519/app/services/edge_cache/bust/fastly.rb#L12) ([documentation](https://docs.fastly.com/en/guides/authenticating-api-purge-requests)).
- A friendly reminder that these HTTP libraries and calls are _not_ thread-safe. That shouldn't be an issue for this refactor.
- This will be "difficult" to test as Fastly is only configured in production on 2 specific instances of Forem.

**Comment by vaidehijoshi** [comment]
Whoever picks this up will need to ensure that they have access to the Forems that are currently running with Fastly enabled
