### ISSUE TITLE
Text inside post out of the post content(above the author profile)

### ISSUE THREAD

**Issue by BevilaquaBruno** [forem/forem#12337]
**Describe the bug**
The text inside a post is above the author information.

**To Reproduce**

1. Go to [this post](https://dev.to/ubahthebuilder/creating-a-family-list-app-with-vanilla-javascript-1n1j)
2. Scroll down to the code above the "JAVASCRIPT" subtitle(second card of code).

**Expected behavior**
The text stay inside the post content cutted  or with a scroll option

**Screenshots**
![Image example](https://user-images.githubusercontent.com/34351545/105064667-cf37da80-5a5b-11eb-9730-57f52056aaae.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10 Pro(last build)
- Browser, version: Brave Software Version 1.18.78 Chromium: 87.0.4280.141 (Official Version) 64 bits

**Additional Information**

In the android app and in the browser accessing with a phone the same happens.

[Android App](https://user-images.githubusercontent.com/34351545/105073422-d1069b80-5a65-11eb-9a28-a0b25ce3873a.jpeg)
[Page with phone](https://user-images.githubusercontent.com/34351545/105073452-da900380-5a65-11eb-9677-29aabcf0c225.jpeg)

**Comment by cmgorton** [comment]
Good catch. Thanks for opening this issue!

**Comment by cmgorton** [comment]
I copied the code and tried to reproduce this but when I use the same code inside an html code block I get a scroll bar as expected instead of the code overflowing like in the example you posted. 
[Test post](https://dev.to/coffeecraftcode/testing-4p68-temp-slug-6177072?preview=fc97847fcbd4c2a21073a740bfe27bb53c3b2986abf8e2e2b766bddfac0aabf8d3ae8d9d52d95d2d81019bfee02bf2d467d3b3f452b479b2d63af2f1)

**Comment by BevilaquaBruno** [comment]
Your test post is correct, the scroll bar appears, so maybe is something specifically of the post?

**Comment by cmgorton** [comment]
Yeah, I think we would need to know how they are using code blocks and if they are missing anything in them. I tried using the wrong language for the code blocks and leaving out closing my code block and I still was able to see a scroll bar.

**Comment by BevilaquaBruno** [comment]
Yes, i notice the unique code block that has the scroll bar is the first, the last is out of the code block too, and of course the code block of that huge html.

I am trying to reproduce the code [here](https://dev.to/bevilaquabruno/test-post-1-2dip-temp-slug-5918547?preview=cef908f89d7b86cf5081ff94bbcb61444c029953539e7b5b1ac2be0ebe3bac7008d5cbd3bda85d0cfc09cea1ad9d6ae601c9cf68665fbded48ef5d4d), but i am not being succefull

**Comment by yogeshktm** [comment]
Hey @BevilaquaBruno  i have tried reproducing the same in a new post.  like others i have the code block with scroll. 

i suggest to validate your markdown once and confirm everything is fine. thanks

**Comment by cmgorton** [comment]
Thanks for trying to reproduce this @yogeshktm . 
This was from a post that @BevilaquaBruno read and didn't write. 
I think at this point the original author would need to validate their markdown like you suggested. I am going to close this issue for now. If we see any other articles with a similar issue we can open it back up :)

**Comment by BevilaquaBruno** [comment]
Ok, if i encounter a similar issue reading or writing posts i will come back here.
Thanks for the help !
