### ISSUE TITLE
Make the option to also block a user part of the Connect report abuse form

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#12333]
**Is your feature request related to a problem? Please describe.**

We've introduced functionality to report a message in Connect in #12229. After submitting the report form (and before any confirmation of submission is shown), a `window.confirm` is used to popup a small dialog asking the user if they would also like to block the person who wrote the message.

These confirm dialogs are limited for customisation, and so the user after pressing to 'report abuse' sees a dialog with 'OK'/'Cancel' options and may think they're related to the report abuse form, rather than this optional block step. In any case, pop ups are probably best avoided if we don't strictly need them, and I think the option to also block could just be a part of the original form and remove any potential confusion.

**Describe the solution you'd like**

Change the Connect report abuse form to have an additional radio select:
- Would you also like to block this user (+ the description of what blocking entails, currently included in the popup)
- Yes / No (defaulting to No)

Request to block is processed after the user submits the report, and the current popup is removed.

**Describe alternatives you've considered**

We could use a custom modal instead of the `window.confirm` which would allow us to customise the OK/Cancel to "Block" / "No thanks", but I think it's not the kind of action that really needs a popup of any kind.

**Comment by citizen428** [comment]
Related: https://github.com/forem/forem/pull/11639 & https://forem.team/citizen428/questions-around-feedbackmessage-1ojg

**Comment by cmgorton** [comment]
Hey @aitchiss do you think this is a good candidate for a potential RFC. I will add the label if you think it is :)

**Comment by aitchiss** [comment]
@cmgorton Yes! That makes sense - I'll look to raise it as a stage 0 RFC soon - thanks for picking up on this! 🙂

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
