### ISSUE TITLE
Accept article's slug in %-encoded Unicode characters

### ISSUE THREAD

**Issue by dmikurube** [forem/forem#12352]
**Is your feature request related to a problem? Please describe.**

It is one of the two proposed solutions against #12350 about slugs for non-ASCII titles.

If an article has a %-encoded Unicode characters in slug, modern web browsers render the %-encoded Unicode characters in URL in their address bar.

If a URL of the article https://dev.to/chokri/-eg9 seems like `/日本語を学ぶ：私のコツ-eg9` on their browser address bar, it's easily understood for native speakers of the language.

**Describe the solution you'd like**

As described above, modern web browsers render %-encoded Unicode characters in URL in their address bar. See https://en.wikipedia.org/wiki/Percent-encoding for %-encoding.

For example, Google Chrome's address bar for https://ja.wikipedia.org/wiki/%E3%83%91%E3%83%BC%E3%82%BB%E3%83%B3%E3%83%88%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0 is rendered like :

![Screenshot from 2021-01-21 00-31-39](https://user-images.githubusercontent.com/723722/105199346-07393d80-5b82-11eb-8066-4cd66355cfbc.png)

**Describe alternatives you've considered**

I proposed another solution in #12351.

Both this and #12351 are the best, but just one of them will mitigate this issue #12350 so much.

**Comment by cmgorton** [comment]
Closing in favor of a discussion on [forem.dev](https://forem.dev/) https://forem.dev/foremteam/non-ascii-title-makes-a-weird-url-on-forem-dev-to-2255
