### ISSUE TITLE
cursor: not-allowed should not come up in a *waiting state*

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12354]
After I click the like button on a comment:

<img width="293" alt="Screen Shot 2021-01-20 at 7 12 41 PM" src="https://user-images.githubusercontent.com/3102842/105256288-79465e00-5b53-11eb-8d5f-e9cd3c237af6.png">

I immediately get a "not allowed" cursor, until the action finishes. I believe this is because the state goes to `disabled` until the action finishes. Disabled may or may not be the correct state, but since we use `cursor: not-allowed` in that state, I think we need to change it.

It is bizarre and jarring to get "not allowed" while I'm in the middle of clicking an action I should be encouraged to click.

## Steps to reproduce
- Click comment like button on computer with mouse. (Touch screen does not apply)

The code for adding the disabled class is here: `app/assets/javascripts/initializers/initializeCommentsPage.js.erb`

If we want to keep that cursor as the default for disabled, we can add another class to override the cursor perhaps?

This should be a simple patch even if we aren't sure about the big picture.

**Comment by yogeshktm** [comment]
Hi @benhalpern 

I have noticed the issue and found weird. can we override the disabled state of reaction button like this or add and remove class while disabling the button is a better solution for this ?

```css
.reaction-button[disabled] {
    cursor: default;
}
```

Thanks
