### ISSUE TITLE
[docker] error in gem approvals when bundle install.

### ISSUE THREAD

**Issue by ryy** [forem/forem#12355]
**Describe the bug**
- An error occurs during the first setup (`bin/container-setup`)
- error in gem approvals when bundle install.

**To Reproduce**
```
bin/container-setup
```

**Screenshots**
<img width="849" alt="スクリーンショット 2021-01-21 9 42 13" src="https://user-images.githubusercontent.com/13917558/105258370-fb269d80-5bcc-11eb-9961-1cd3585256dc.png">

```
bundle_1         | Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
bundle_1         | 
bundle_1         | current directory:
bundle_1         | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/approvals-0.0.24/ext
bundle_1         | /usr/bin/ruby mkrf_conf.rb
bundle_1         | 
bundle_1         | rake failed, exit code 1
bundle_1         | 
bundle_1         | Gem files will remain installed in
bundle_1         | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/approvals-0.0.24 for inspection.
bundle_1         | Results logged to
bundle_1         | /opt/apps/forem/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/approvals-0.0.24/gem_make.out
bundle_1         | 
bundle_1         | An error occurred while installing approvals (0.0.24), and Bundler cannot
bundle_1         | continue.
bundle_1         | Make sure that `gem install approvals -v '0.0.24' --source
bundle_1         | 'https://rubygems.org/'` succeeds before bundling.
bundle_1         | 
bundle_1         | In Gemfile:
bundle_1         |   approvals
forem_bundle exited with code 5
```

**Comment by cmgorton** [comment]
@fdoxyz @atsmith813 do either of you have any thoughts on this error? Thanks.

**Comment by atsmith813** [comment]
Our Docker/container isn't quite where we want it yet. Maybe @citizen428 @rhymes or @jdoss has seen this one before.

**Comment by narender2031** [comment]
can I work on this docker container issue? It will also help me to explore docker more :)

**Comment by atsmith813** [comment]
@narender2031 sure thing, thank you! I've assigned the issue to you.

**Comment by cmgorton** [comment]
@narender2031 thanks so much for jumping on this issue. 
The Forem team is hoping to move to Rails 6.1. In order to do that we actually need to remove the approvals Gem as it a) doesn't work with Rails 6.1, and b) hasn't be updated in a very long time. 

For that reason we no longer need contributions on this particular issue. I am going to unassign you here but please let me know if you see any other issues you would like to work on.
