### ISSUE TITLE
Make article's slug configurable apart from its title

### ISSUE THREAD

**Issue by dmikurube** [forem/forem#12351]
**Is your feature request related to a problem? Please describe.**

It is one of the two proposed solutions against #12350 about slugs for non-ASCII titles.

If an article can configure a slug apart from its title, the article can have a meaningful URL even for a non-ASCII title.

For example, if the article https://dev.to/chokri/-eg9 can have a slug `/learning-japanese-my-tricks-eg9`, it's really helpful for everyone.

**Describe the solution you'd like**

I'd propose to have an additional (optional) metadata `slug:` on an article. If `slug:` exists in the front matter, `slug` is used instead of `title` to generate a slug.

For example,

```
---
title: 日本語を学ぶ：私のコツ
slug: learning-japanese-my-tricks
published: true
description: ...
tags: ...
---
...
```

**Describe alternatives you've considered**

I proposed another solution in #12352.

Both this and #12352 are the best, but just one of them will mitigate this issue #12350 so much.

**Comment by cmgorton** [comment]
Closing in favor of a discussion on [forem.dev](https://forem.dev/) https://forem.dev/foremteam/non-ascii-title-makes-a-weird-url-on-forem-dev-to-2255
