### ISSUE TITLE
Liquid Tag for Cinnamon Videos

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#12367]
**Is your feature request related to a problem? Please describe.**

Yes, folks would like to be able to embed Cinnamon videos across all Forems.

[Cinnamon](https://cinnamon.video/) is a web monetized video platform.

**Describe the solution you'd like**

I'd like it if we add a liquid tag that would allow folks to embed Cinnamon videos.

**Describe alternatives you've considered**

N/A

**Additional context**

This would be particularly helpful to the [Web Monetization Community Forem](https://community.webmonetization.org/) who's members would absolutely use this, but I could still see it being helpful across all Forems.

**Comment by vaidehijoshi** [comment]
Hi @michael-tharrington! Let's use our internal RFC process for this since it is suggesting a significant new feature :)

**Comment by cmgorton** [comment]
> Hi @michael-tharrington! Let's use our internal RFC process for this since it is suggesting a significant new feature :)

I am going to close this issue Michael. Like Vaidehi mentioned with can use the internal RFC process or create a new discussion on [forem.dev
](https://forem.dev/).

If we continue on with this request in a RFC we can open this back up!
