### ISSUE TITLE
Clicking on value for "Experience Level of Post" results in error

### ISSUE THREAD

**Issue by mcat** [forem/forem#12370]
**Describe the bug**

Selecting an experience level on a post causes the page to navigate to 

`https://dev.to/rating_votes`

where the error below is displayed.

```
{
result: "Not Upserted Successfully"
}
```

**To Reproduce**

1. Go to an organization dashboard
1. Click "Manage" next to a newly posted article
1. Scroll down to the "Experience Level of Post" section of the page
1. Click one of the experience levels
1. The browser will navigate to a new page that displays an error

**Expected behavior**

**Screenshots**

![2021-01-20 15 11 23](https://user-images.githubusercontent.com/127962/105384887-c02e6500-5be0-11eb-80d0-87b9f49ae62c.gif)

![Screen Shot 2021-01-20 at 15 09 06](https://user-images.githubusercontent.com/127962/105384911-c3c1ec00-5be0-11eb-9b8c-855aa9cffa34.png)

**Desktop (please complete the following information):**

- OS, version: Mac OS 11.1
- Browser, version: Chrome 88.0.4324.96

**Comment by narender2031** [comment]
I would like to work on this.

**Comment by ludwiczakpawel** [comment]
@narender2031 or anyone else - were you able to repro that?

**Comment by narender2031** [comment]
I'm not able to reproduce this issue locally.

**Comment by ludwiczakpawel** [comment]
I can't repro that on locally nor on prod. Let's give this issue couple more days, I'll ping folks to try to repro this as well and we will take it from there.

**Comment by ludwiczakpawel** [comment]
@mcat we were not able to repro that issue internally as well. let me know if it still happens to you or maybe it was a coincidence.

**Comment by mcat** [comment]
@ludwiczakpawel the behavior is reproduced for every post in our org account. However, on my personal account it works as expected.

**Comment by mirie** [comment]
We changed is panel / flow last fall and I wasn't able to reproduce this issue. If it's not resolved, please open a new issue! Sorry that you had trouble before 🙇
