### ISSUE TITLE
Allow admins to configure expiration settings for Listings

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#12374]
**Is your feature request related to a problem? Please describe.**
As a Forem admin, I am frustrated that I can't adjust the "expiration settings" for listings.  I'd like them to stick around forever.

**Describe the solution you'd like**
A setting that allows me to adjust the expiration length of my community's listings.  Using this new feature, I should also be able to configure it such that listings stick around forever (unless un-published).

**Additional context**
This is a feature request from a Forem Creator actively using Listings in their community.

**Comment by bigdoods** [comment]
Is there an intermediatory step that could be taken to support this user case as a part of the existing Forem feature set whilst this issue is resolved?

i.e an alternative to "Listings", for organisations and communities to provide a short summary & links, for others to see in one place

**Comment by mstruve** [comment]
Adding expirations to listings is definitely a feature that we will need to write out an RFC for and assess whether it is something we want from the product side. Because of that, I am going to remove it from the Planning Funnel and tag it with the RFC tag.

**Comment by bigdoods** [comment]
Hey guys - Any update on this? The 30 day expiry on listings make the feature unusable for our users.
