### ISSUE TITLE
Moderator Panel Crashes App

### ISSUE THREAD

**Issue by xpyxel** [forem/forem#12389]
**Describe the bug**

When using the moderator panel on the mobile application, clicking on a post sometimes results in the application crashing, resulting the app closing, this is consistent until the cache is cleared.

**To Reproduce**

1. Have moderator access on DEV
2. Go go the moderator panel on your phone
3. Attempt to click a post
4. The app crashes

**Expected behavior**

The app should show the post in the panel and allow me to thumbs up/down it, and/or flag it as usual, however the app crashes when attempting to do so.

**Screenshots**

https://photos.app.goo.gl/ak2arMCTr3VtMTpo8

**Desktop (please complete the following information):**

Not applicable.

**Smartphone (please complete the following information):**

- Device: Google Pixel 2
- OS, version: Android 11, Build RP1A.201005.004.A1
- Browser, version: Not applicable

**Additional context**

This seems to happen on both the mobile app, and (sometimes) the browser on mobile. It seems to also be consistent between browsers.

**Comment by cmgorton** [comment]
@fdoxyz tagging you so you have an eye on this issue.

**Comment by fdoxyz** [comment]
Thank you for the report @xpyxel! I wasn't able to reproduce this myself by clicking on a few links but I'll definitely investigate this problem some more.

There are some enhancements planned for the Moderator Panel since right now is not very mobile friendly but the crash is definitely unexpected. Would you mind sharing with me the app version you have installed? The latest at the moment (which added a few crash fixes) is `1.5.0-2`

**Comment by xpyxel** [comment]
I currently seem to be on 1.5.0-2, and yeah the bug sometimes appears,
sometimes doesn't. I am unsure what exactly causes it besides the fact
clearing cache seems to temporarily fix it until it appears again.

**Comment by xpyxel** [comment]
> I currently seem to be on 1.5.0-2, and yeah the bug sometimes appears,
> sometimes doesn't. I am unsure what exactly causes it besides the fact
> clearing cache seems to temporarily fix it until it appears again. It could also be patched in this version, I'll have to wait to see if it appears again.

Nevermind, I seem to still have the bug as it just appeared, however this time crashing the app as soon as I enter the moderator panel without me tapping anything.

https://photos.app.goo.gl/NuZUW7pcmMwQ6vZr6
