### ISSUE TITLE
Feed not importing

### ISSUE THREAD

**Issue by danielkellyio** [forem/forem#12396]
Could anyone help me figure out why my xml feed isn't importing to dev.to?

Feed link: https://danielkelly.io/feed.xml

I go to Settings > Extensions > Publishing to DEV Community from RSS and click "Fetch Feed Now" and it gives me a timestamp of being recently fetched but when I go to my dashboard I don't see any new post drafts. 

- OS, version: macOS Catalina
- Browser, version: Firefox Developer Edition 85.0b9

Thanks!

**Comment by rhymes** [comment]
Hi @danielkellyio, I tried manually to fetch the feed, with `curl`, a Ruby HTTP client and the browser itself and it always times out. 

Can you double check on your end?

**Comment by danielkellyio** [comment]
Whoops, looks like my hosting with Netlify was having some issues today. I can successfully access the feed now. Thanks!

**Comment by citizen428** [comment]
Glad everything is working for you now @danielkellyio, I'll close this issue.

**Comment by danielkellyio** [comment]
Oh sorry I meant I can access my feed over http. It's still not importing to dev.to

**Comment by citizen428** [comment]
Ah, gotcha, sorry for the misunderstanding.

**Comment by rhymes** [comment]
Hi @danielkellyio, sorry for the delay, the reason why you're not able to import it, it's because your feed as `<link>` tags. When I import it manually I get the following error:

```shell
feeds::import::error::ActiveRecord::RecordInvalid::{:feeds_import_info=>{:username=>"rhymes", :feed_url=>"https://danielkelly.io/feed.xml", :item_count=>7, :error=>"Feeds::Import::CreateArticleError:http://localhost:3000/blog/vue-resources-roundup"}, :error_message=>"Validation failed: Feed source url is not a valid URL"}
```

If you look at the XML content you'll see:

```xml
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/">
    <channel>
        <title>danielkelly.io blog</title>
        <link>http://localhost:3000/feed.xml</link>
        <description>A web development blog about Vue, Nuxt, Laravel, and more!</description>
        <lastBuildDate>Sat, 23 Jan 2021 22:25:25 GMT</lastBuildDate>
        <docs>https://validator.w3.org/feed/docs/rss2.html</docs>
        <generator>https://github.com/nuxt-community/feed-module</generator>
        <item>
            <title><![CDATA[Discuss on Twitter Link For Nuxt Content Blog Posts]]></title>
            <link>http://localhost:3000/blog/discuss-on-twitter</link>
            <guid>http://localhost:3000/blog/discuss-on-twitter</guid>
```

In this snippet you have both `<link>` and `<guid>` pointing to "localhost:3000" which is an invalid URL on the open web.

In this case for example I think the URL you want there is `https://danielkelly.io/blog/discuss-on-twitter`

**Comment by danielkellyio** [comment]
aha! I didn't catch that. I'll change it out and test it shortly. Thanks!

**Comment by cmgorton** [comment]
Going to close this issue. Let us know if that wasn't the fix you needed @danielkellyio and we can reopen this 😄
