### ISSUE TITLE
Follow button in notification is appears in two lines in mobile

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#12394]
**Describe the bug**

Text "Follow back" and "Following" in notification appears in a single line 

**To Reproduce**
1, Create two user accounts  user1 and user2
2. Now login as user1 and follow user2
3. Now login as user2 and look for a new notification in `/notifications`
4. Text "Follow back" should appear in a single line
5. Now follow that user and the text "Following" should appear in a single line

**Expected behavior**

Text "Following" should appear in a single line

**Screenshots**
![following](https://user-images.githubusercontent.com/8092120/105573897-ae86c200-5d86-11eb-90df-b9eda0f0eb6b.png)
![follow_back](https://user-images.githubusercontent.com/8092120/105573894-ac246800-5d86-11eb-93a4-7816777317ea.png)

**Smartphone:**

- Device: Redmi note 6 pro
- OS, version:  Android 10
- Browser, version: 1.19.86

**Additional context**

Using css  `white-space: nowrap;`  should fix this

**Comment by cmgorton** [comment]
Thanks for the issue @Rafi993 did you want to work on this one?

**Comment by Rafi993** [comment]
yes I can help @cmgorton

**Comment by cmgorton** [comment]
Great, I'll assign it to you. Thanks for the help here @Rafi993 !

**Comment by cmgorton** [comment]
That was fast! Thanks @Rafi993 🎉
