### ISSUE TITLE
Cannot respond to listings

### ISSUE THREAD

**Issue by yujiri8** [forem/forem#12393]
**Describe the bug**

The send button on listings does not work.

**To Reproduce**

Go to a listing and open the dialog to send a message. Type a message and click send. Nothing happens and a console error appears.

**Expected behavior**

Sends a message (and gives visual feedback to let me know it's sent).

**Screenshots**

![20210123_00h08m11s_grim](https://user-images.githubusercontent.com/16864184/105569422-75f7d180-5d0f-11eb-8b3b-21da979b8006.png)

**Desktop (please complete the following information):**

- OS, version: Artix Linux 5.10.6
- Browser, version: Firefox 84, and Ungoogled Chromium 87

**Comment by rhymes** [comment]
I can reproduce the issue locally, it doesn't always happen though. Might it have something to do with asynchronicity?
