### ISSUE TITLE
"Social" logins are privacy issue, provide email only sign up

### ISSUE THREAD

**Issue by ell1e** [forem/forem#12395]
**Is your feature request related to a problem? Please describe.**
The social platform based, centralized logins are a privacy and reliability issue (due to the risk of illegitimate social terminations impacting connected logins), therefore please provide email only sign up. Site-specific logins are combined with tracking blockers in browsers a great way to avoid producing a centralized data profile about yourself about what sites you use. Also, dev.to's current sign up/login forms are quite confusing since there *is* an email sign in, but no obvious way to sign up that way.

Protocols like OAuth2 are also notoriously complex and therefore a potential source of errors, future maintenance burdens, and security holes, so even from that angle a simpler email sign up may be preferred even if that puts the responsibility of storing a safe password hash on you. Just something to consider from a maintenance angle.

**Describe the solution you'd like**
Sign up via e-mail in addition to social.

**Describe alternatives you've considered**
For me the only current alternative is not using dev.to, which is what I am currently doing.

**Additional context**

> If you would like us to champion any feature requests on your behalf, please put them in forem.dev.

Just to state this in advance in case it comes up for the sake of discussng this, I would be happy to oblige if there weren't the exact issue described in this ticket in the first place.

**Comment by cmgorton** [comment]
hey @ell1e this is a duplicate of #11603 . I will keep that issue open for discussion there though feature requests made in forem.dev due to our new process will likely get priority. I could create a post there for you if you would like so you do not have to sign up.
