### ISSUE TITLE
Ability to manually reorder posts in a series

### ISSUE THREAD

**Issue by tvvignesh** [forem/forem#12400]
Hi. While series work great in Dev.to the sorting is solely based on date of the blog posts. It would be really great to have a way to manually order the posts or update existing order in a series.

This is important cause, there are some cases in which you want to post later but have an order to the series which makes more sense.

In my case, I publish 1 blog out of every 3-4 blogs in Dev.to to other platforms like The New Stack which require exclusive 2 week access. So, I have to hold publishing in Dev.to till then. But later add the post as part of the series when the window expires.

**Describe the solution you'd like**

Ability to manually reorder posts in a series

**Describe alternatives you've considered**

No alternatives available except not using the series feature in Dev.to

On a side note, I don't see an ability to delete a series.

**Comment by cmgorton** [comment]
Hey @tvvignesh we have a new process for [feature requests.](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4)
 I have seen this request come up before so I went a head and created a post in forem.dev for it. [Post is here](https://forem.dev/foremteam/ability-to-reorder-posts-in-a-series-244n)
You can add any additional thoughts there. 

Thanks for bringing this up!
