### ISSUE TITLE
Support Comment Thread Embeds

### ISSUE THREAD

**Issue by wolfhoundjesse** [forem/forem#1240]
**Is your feature request related to a problem? Please describe.**
If I want to embed a comment thread for discussion, I must include three separate comment embeds:
```
{% devcomment xxx0 %}
{% devcomment xxx1 %}
{% devcomment xxx2 %}
```
This results in three embeds with ample padding that makes them look unrelated.

**Describe the solution you'd like**
Comment threads already have permlinks. Maybe we could:
```
{% devcommentthread xxx0 %}
```

**Describe alternatives you've considered**
There are two caveats that make this somewhat complex. 

1. A comment thread may be twenty comments deeper than you intend to embed. 

2. You may want to cherry-pick comments, not for evil, but perhaps the discussion you want to highlight is between two people and not the twelve others that chimed in somewhere in the middle. 

**Additional context**
This is likely an edge case, but I'm offering it up to the community for discussion.

**Comment by benhalpern** [comment]
Makes sense.

The default could be all comments, with the option to cherrypick like

`{% devcommentthread xxx0 xxx4 xxx9 xxx12 %}`

And then the rendered version would have those displayed and maybe in between those ones there could be an indication that some are hidden.

There's a bit to talk about here, but I like this thought.

**Comment by maestromac** [comment]
not stale

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here. We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
