### ISSUE TITLE
Front page right side-bar not visible on iPad in landscape mode when logged in.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#12402]
**Describe the bug**

When using an iPad Pro (11inch) in landscape mode the right sidebar isn't rendered. This only occurs when you are logged in. When you are logged out, the right sidebar renders correctly.

**To Reproduce**

Note, I can't seem to replicate this when using dev tools to emulate an iPad on chrome or safari, it only occurs on a physical iPad.

1. Open dev.to in landscape mode (I am testing on an iPad Pro 11")
2. Note right sidebar is rendered
3. Login, note sidebar is not rendered.

**Expected behavior**

Right sidebar to be rendered in both scenarios.

![jasgocdydk0k59mqdmea](https://user-images.githubusercontent.com/12694270/105640133-33033e80-5e74-11eb-888a-c566724bc9f9.jpg)
![y8yekxqg2ucioyil6jj1](https://user-images.githubusercontent.com/12694270/105640135-35659880-5e74-11eb-841b-910a5ebfbd8a.jpg)

**Comment by ludwiczakpawel** [comment]
Hmm.. I'm having troubles reproducing this issue... So I'll be shooting blinds with some random questions so maybe I can guess the solution:

1. Does it also happen when you dismiss the hero banner?
2. When the sidebar is "hidden" can you actually check whether it has dropped BELOW the main column (you have to scroll to the bottom of everything since it's a infinite scroll :D)
3. Do you happen to know why the avatar in the header is also gone on your screen?
4. Can you check this also while browsing the site in browser? (i can see you have "pinned" your site to the home screen - so it may behave slightly different)

**Comment by leewynne** [comment]
> Hmm.. I'm having troubles reproducing this issue... So I'll be shooting blinds with some random questions so maybe I can guess the solution:
> 
> 
> 
> 1. Does it also happen when you dismiss the hero banner?
> 
> 2. When the sidebar is "hidden" can you actually check whether it has dropped BELOW the main column (you have to scroll to the bottom of everything since it's a infinite scroll :D)
> 
> 3. Do you happen to know why the avatar in the header is also gone on your screen?
> 
> 4. Can you check this also while browsing the site in browser? (i can see you have "pinned" your site to the home screen - so it may behave slightly different)
> 
> 5. Have you noticed that on any other view as well?
> 
> 6. Does this happen only on flowstate or also other sites too?

1. Yes it does.
2. It doesn't show at the bottom 
3. Nope, totally disappears!
4. This happens in a browser on an iPad Pro 11" 
5. Article view looks fine
6. On all forems.

I can't replicate it in an emulator, only when on an iPad where it exists in all flavours and on all Forems, only seems to be the front page though, post login.

**Comment by ludwiczakpawel** [comment]
Thanks, thanks very helpful. I'll try to investigate a bit more 👍

**Comment by ludwiczakpawel** [comment]
Hmm - I was able to reproduce it on emulator but only when I loaded page in the smallest breakpoint (so right sidebar was not visible) and then resized the view to accommodate space for sidebar - surprisingly right sidebar did not have any content in the markup.

@benhalpern can this be anyhow related? https://github.com/forem/forem/commit/ae7c9a4f759b9c28c86d62eadaf9d89c4c932233#diff-5da13e09c79e326438bf37ed22b60f3ebddc587c0345fda497e1edede1a2dd45R61

^ this `1023` value seems suspicious...

**Comment by ludwiczakpawel** [comment]
Even though that check with `1023` value was suspicious and should likely be replaced by something like this 
```
getComputedStyle(sidebarContainer).display !== 'none'
```
...it does look like it's not the main issue here. I still believe it's something related to this PR but I'm having troubles tracking what that is.

cc @forem/frontend

**Comment by ludwiczakpawel** [comment]
...additionally, I think this if statement will cause issues on certain devices when rotating from portrait to landscape mode – in portrait we do not show (and load) sidebar but when I rotate device to landscape mode the sidebar will still be gone because it hasn't been loaded in the first place.

cc @joshpuetz as it's also probably related to [your work](https://github.com/forem/forem-ios/pull/40) but you need to log in first.

**Comment by joshpuetz** [comment]
@ludwiczakpawel I don't think this is related to https://github.com/forem/forem-ios/pull/40: the iOS app simply displays a web view, but isn't doing anything to the contents.

I'm able to replicate this 100% on device and in the simulator in Safari (I'm not talking about the Forem iOS/iPadOS app here at all). Here's before login on a 12.9 and 11 inch iPad in horizontal mode:

<img width="1280" alt="CleanShot 2021-02-15 at 10 33 40@2x" src="https://user-images.githubusercontent.com/37842/107973175-856ae300-6f7a-11eb-8c7b-8dab970f4aac.png">

And after login:

<img width="1280" alt="CleanShot 2021-02-15 at 10 32 45@2x" src="https://user-images.githubusercontent.com/37842/107973209-93206880-6f7a-11eb-8297-5d9d0156c5cd.png">


Possibly related is that the sidebar isn't rendered EVER in portrait mode on the 11 inch iPad, regardless of the user being logged in or not:

<img width="1280" alt="CleanShot 2021-02-15 at 10 30 24@2x" src="https://user-images.githubusercontent.com/37842/107973324-b77c4500-6f7a-11eb-924f-4090f64b0c76.png">

<img width="1280" alt="CleanShot 2021-02-15 at 10 33 08@2x" src="https://user-images.githubusercontent.com/37842/107973349-bf3be980-6f7a-11eb-98c5-db8b55de1796.png">

**Comment by ludwiczakpawel** [comment]
I'm downloading xcode and will try to run simulators too.
