### ISSUE TITLE
Can't setup dev environment

### ISSUE THREAD

**Issue by harshilparmar** [forem/forem#12414]
**Describe the bug**

As discussed here https://github.com/forem/forem/issues/12190#issuecomment-766407326,
I can't set up the dev env on my machine.

**To Reproduce**
1) yarn install
2) yarn run storybook

**Screenshots**

![dev](https://user-images.githubusercontent.com/45915468/105677069-69db6200-5f11-11eb-9f13-18d5894f8b1e.PNG)

**Desktop (please complete the following information):**

- OS, version: windows 10 
- Browser, version: mozila 84.0.2, Chrome 88.0.4324.104

**Additional context**

As @rhymes said, It's only workes for the Unix-like environment we have to set up for windows.

**Comment by citizen428** [comment]
Please note that we only support Windows via WSL2 as outlined in our installation documentation:

https://docs.forem.com/installation/windows/
