### ISSUE TITLE
"Create account" button cut off in Forems with wide logos.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12426]
**Describe the bug**

The "wide logo" issue causes problems for both authenticated and unauthenticated views. This issue is in the unauthenticated view in particular:

**To Reproduce**

- Visit a "wide logo" community, such as https://community.codenewbie.org/ or https://the.community.club/
- Open Chrome dev tools, select the mobile simulator and select iPhone X

**Expected behavior**

The full button is visible, not cut off.

**Screenshots**

<img width="375" alt="Screen Shot 2021-01-25 at 2 20 09 PM" src="https://user-images.githubusercontent.com/3102842/105754860-8cbd4480-5f18-11eb-9692-48547b154358.png">

**Additional context**

Reddit uses the phrase "join" in a lot of similar places, so we could possibly co-opt that verbiage.

<img width="102" alt="Screen Shot 2021-01-25 at 2 23 26 PM" src="https://user-images.githubusercontent.com/3102842/105755145-e58cdd00-5f18-11eb-9248-51dcbd568e4c.png">

I don't think it's confusing to use both "Create account" _and_ "Join" depending on screen size, neither is critical brand copy.

To accomplish this, we could make use of `s:inline` in crayons to swap copy based on screen size.

**Comment by ohannadeziderio** [comment]
I would like to take this. Thanks!

**Comment by ludwiczakpawel** [comment]
@ohannadeziderio go ahead! 🚀

**Comment by cmgorton** [comment]
Looks like this issue was resolved with PR #12722 . I am going to close this issue. We can reopen it if the problem was not fixed.
