### ISSUE TITLE
New User Sign Up Error

### ISSUE THREAD

**Issue by ItsJustMyGit** [forem/forem#12440]
**Describe the bug**

Getting a Log in error while trying to create a new account on dev.to DEV community. The error occurs while using twitter account as the sign up option. The error message says "Log in error: Validation failed: Profile image could not download file: 404 Not Found."

The problem likely caused by due to having no profile photo/image set up by the users to their twitter account.

**To Reproduce**
 

 1. Go to dev.to  
 2. Select Create account option
 3. Choose twitter as sign in option
 4. Enter email id and password for twitter and submit.

**Expected behavior**

The expected behavior should be the process enable the users to create an account on dev.to , and let them manage/update their account info from their profile settings.

**Screenshots**
![Screenshot_ErrorSignUp](https://user-images.githubusercontent.com/77940724/105872924-f4f74d80-6020-11eb-9776-85811e838762.png)

**Desktop (please complete the following information):**

- OS, version: Windows
- Browser, version: Mozilla Firefox (Version84.0.2 (64-bit)), Google Chrome (Version 87.0.4280.141 (Official Build) (64-bit))

**Smartphone (please complete the following information):**

- Device: Smartphone
- OS, version: Android 9, Pie
- Browser, version:  

**Additional context**

Tried the same process on both dev.to android app and using dev.to website to create an account by providing twitter as a sign up option, both method ends up showing the same error. so its not device, OS or browser dependent.

the error doesn't occur while using git account as the sign up option, which was the solution i used, i  think the error could be solved by setting up a profile image, or even a placeholder image to the twitter account. however new users would not be aware of this condition beforehand. so either the account creation page could remind the users to have a twitter profile image is a mandatory condition, or the devs could add an option to generate a random profile image for the users upon creating an account.

**Comment by cmgorton** [comment]
Thanks for opening this. Investigating more into this now.

**Comment by cmgorton** [comment]
Team is working on a potential fix for this @ItsJustMyGit .

**Comment by cmgorton** [comment]
Looks like this issue should be fixed with the above PR. Please let me know if the problem persists for you @ItsJustMyGit and I will reopen this issue. Thanks.
