### ISSUE TITLE
DEV shows up as favicon on certain 404s

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#12494]
**Describe the bug**

404s on Forems show the correct favicon.  However, 404s via `/admin/asdfasdf` will show "DEV" in the favicon.

**To Reproduce**

- Visit: [https://forem.dev/admin/asdfasdfasdf](https://forem.dev/admin/asdfasdfasdf)
- Look at the favicon
- Now visit [https://forem.dev/admin/asdfasdfasdf](https://forem.dev/asdfasdfasdf)
- Notice that the proper favicon is back

**Expected behavior**

The Favicon does not show as "DEV"

This would bring it in line with other pages that 404

**Additional Context**

This isn't the biggest deal, but would be nice to clean up as part of our generalization effort.

**Comment by arwazkhan189** [comment]
Hey @cmgorton, I would like to solve this. Thanks. 🙋‍♂️

**Comment by arwazkhan189** [comment]
Hey @cmgorton, I would like to solve this. Thanks.🙋‍♂️

**Comment by cmgorton** [comment]
Awesome @arwazkhan189 ! Just assigned you to this issue. Let us know if you have any questions.

**Comment by arwazkhan189** [comment]
Hey @pkfrank, I have to just change the DEV icon with this icon?
![1](https://user-images.githubusercontent.com/48387278/117545542-d7844780-b043-11eb-97fc-b7462348fa21.jpg)

**Comment by rhymes** [comment]
Hi @arwazkhan189, from what I can see, the 404 page itself has no favicon declared - https://forem.dev/404 - so it will use https://github.com/forem/forem/blob/main/public/favicon.ico which is `DEV`

Given that the [404 template](https://github.com/forem/forem/blob/main/public/404.html) is not dynamic, I think our best course of action, on the technical side, is:

- replacing the generic favicon with a Forem favicon
- using `<link rel>` in the 404 HTML page, as specified by the W3C: https://www.w3.org/2005/10/howto-favicon

I'm going to ping the design team to double check this plan of mine and let you know ASAP.

Thank you!

**Comment by arbazkhan56** [comment]
Hi @cmgorton can you assign me this issue?

**Comment by rhymes** [comment]
Hi @arwazkhan189, are you still working on this? Let us know if you need any help, otherwise @arbazkhan56 has volunteered to take this in case you can't work on it :)

Thank you!

**Comment by arbazkhan56** [comment]
I think he is not active. now, you can assign me.
The bug smash challenge's last date is 28th May, and I want to complete it by the last date.

**Comment by arwazkhan189** [comment]
sorry I haven't seen this, @arbazkhan56  👍

**Comment by cmgorton** [comment]
Thanks for letting us know @arwazkhan189 

@arbazkhan56 I have assigned this issue to you.
