### ISSUE TITLE
Tweet action button overflow style issue

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12519]
**Describe the bug**

Tweet liquid tags have insufficient padding on bottom causing overflow.

<img width="582" alt="Screen Shot 2021-02-01 at 5 16 18 PM" src="https://user-images.githubusercontent.com/3102842/106524916-34a2b700-64b1-11eb-8bbb-926557400da9.png">

**To Reproduce**

Add a tweet liquid tag to a post.

**Expected behavior**

There should be consistent margin around the tweet action buttons, like this

<img width="495" alt="Screen Shot 2021-02-01 at 5 22 22 PM" src="https://user-images.githubusercontent.com/3102842/106525482-0d98b500-64b2-11eb-80a3-c18615858bd3.png">

**Additional context**

This can be fixed by changing `height: 40px;` to the `.ltag__twitter-tweet__actions__button` class. This is most likely best fixed via a patch and we can have a more holistic crayons approach in a future revisit of liquid tag styling in general.

**Comment by sirius93** [comment]
@benhalpern This seems more than just height issue. Please take a look at below screenshot.
![image](https://user-images.githubusercontent.com/6882879/106577699-b0aa0700-6564-11eb-8255-a137ec694e46.png)
The Dev icon (twitter profile pic) also seems to be shifted downwards. 
Looks like something to do with top bottom margin getting added to images.
Issue when margin is there :
![image](https://user-images.githubusercontent.com/6882879/106578046-1c8c6f80-6565-11eb-9b02-f5464a2479d6.png)

issue goes away when margin is removed:
![image](https://user-images.githubusercontent.com/6882879/106578259-565d7600-6565-11eb-92a0-3d5a6cdf2b7b.png)

**Comment by benhalpern** [comment]
@sirius93 good call. Yeah, I wasn't so sure about what was going on.

**Comment by sirius93** [comment]
@benhalpern  From what I understand, A quick fix would be to override margin top and bottom in images specific to `tweet liquid tag`.

**Comment by Hanaffi** [comment]
Assign to me?

**Comment by Hanaffi** [comment]
Can you assign it to me please?

**Comment by cmgorton** [comment]
@Hanaffi would you still like to work on this? If so I can assign you.

**Comment by Hanaffi** [comment]
@cmgorton Yes please.

**Comment by cmgorton** [comment]
Great, just assigned you @Hanaffi. Thank you for your help on this!

**Comment by Hanaffi** [comment]
@cmgorton Can you tell me where can I find the styles of that div??

**Comment by nickytonline** [comment]
@Hanaffi, all the styling for a Twitter liquid tag should be in https://github.com/forem/forem/blob/564f34483d5e08829eb97816ba78251635201d54/app/assets/stylesheets/ltags/TweetTag.scss

**Comment by vaidehijoshi** [comment]
@cmgorton Just checking in here as I look for some potential issues to bring up in the planning meeting -- did https://github.com/forem/forem/pull/12885 actually fix this issue (and by proxy, this larger issue https://github.com/forem/forem/issues/12772?)

If not, we can prioritize it for someone on the Forem team; if so, then we can just close this out and ignore my comment here entirely! 🤠

**Comment by cmgorton** [comment]
@vaidehijoshi it looks like #12885 did fix the Twitter liquid tag misalignment (we can close this issue) I am not sure if it fixed #12772 as well.
