### ISSUE TITLE
Inconsistent "0 comments" indicator

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#12513]
**Describe the bug**

Sometimes, when there's no comments on the post the feed card says "0 comments" and sometimes it's "Add comment".
Another times (I've noticed that on user's profile and tag page) there's no indicator for either comments nor reactions.

**To Reproduce**

Browse the /latest and some users profile and tag pages.

**Expected behavior**

To have consistent labels: 

- if comments count > 0 then show `${n} comments`
- if comments count = 0 then show `Add comment`

**Screenshots**

This is from the feed:

![image](https://user-images.githubusercontent.com/108287/106480675-f060e800-64ab-11eb-8250-27f719fd201e.png)

And this is from user's profile:

![image](https://user-images.githubusercontent.com/108287/106481718-028f5600-64ad-11eb-9356-d59721735e55.png)

**Comment by rhymes** [comment]
Caching?

**Comment by ludwiczakpawel** [comment]
:D 

Not this time I think. I tried hard refresh several times :D

**Comment by cmgorton** [comment]
Am I imagining things? Wasn't there an issue or PR recently to remove the `0 comments` display altogether?

**Comment by ludwiczakpawel** [comment]
@cmgorton probably related:
- https://github.com/forem/forem/pull/12425
- https://github.com/forem/rfcs/blob/main/text/0026-only-show-feed-reaction-count-if-more-than-zero.md

**Comment by cmgorton** [comment]
That was it! Thanks.

**Comment by vaidehijoshi** [comment]
Sounds like it could potentially be a bug related to https://github.com/forem/forem/pull/12425? (cc @msarit)

I'm not 100% sure as I haven't poked around in the code itself, but probably warrants some investigation from our end :)

**Comment by mstruve** [comment]
@ludwiczakpawel do you think the solution here should be to show comment count if greater than 0 otherwise show ""Add comment"? Want to make sure the wanted solution for this bug is clear in the issue so anyone can tackle it

**Comment by ludwiczakpawel** [comment]
@mstruve 

- if comments count > 0 then show `${n} comments`
- if comments count = 0 then show `Add comment`

(adding this to "expected behavior" section of my bug report)
