### ISSUE TITLE
Documentation Navigation Styling Issue 

### ISSUE THREAD

**Issue by saydus** [forem/forem#12521]
**Description**
On the documentation website, I am experiencing styling issue with the navigation on top of pages that have it. For example, on [installation guide with containers](https://docs.forem.com/installation/containers/). 

Here is how the page looks before scrolling down:
<img width="1680" alt="Screen Shot 2021-02-01 at 2 19 23 PM" src="https://user-images.githubusercontent.com/29519144/106542482-87886880-64c9-11eb-87e1-45b37186a4b6.png">

When scrolling down the page, the navigation assumes a fixed position (relative) and covers the page content:
<img width="1680" alt="Screen Shot 2021-02-01 at 2 19 32 PM" src="https://user-images.githubusercontent.com/29519144/106542515-98d17500-64c9-11eb-9039-f3e64aa5f22e.png">

**To Reproduce**

1. Go to [installation guide with containers](https://docs.forem.com/installation/containers/)
2. Try scroll down.

**Expected behavior**

The navigation should not cover the page context and potentially be fixed at the top position (relative to the whole document, not the screen).

**Device:**
- 15 inch MacBook Pro
- maxOS Catalina, 
- Firefox Developer Ediiton

**Comment by cmgorton** [comment]
We have found this is an issue we can not fix. However, we are currently in the process of moving our documentation to a Docusaurus site and this will no longer be an issue when everything is moved over. Thank you for taking the time to open this issue and help us improve the developer experience. I am going to go a head and close this issue. Please keep an eye out for our updated site which should be available for a better user experience soon!
