### ISSUE TITLE
New registered user. Redirected to a blank screen due to onboarding error

### ISSUE THREAD

**Issue by deivuh** [forem/forem#12540]
**Describe the bug**
I just registered to dev.to with Github and whenever I try to access to the main site it redirects me to `https://dev.to/onboarding?referrer=https://dev.to/` because the onboarding page has errors, it gives me a blank screen. The following errors where shown on Safari's JS console. 
 
```
[Error] Unable to load onboarding
TypeError: undefined is not an object (evaluating 't.attributes.length')
M — preact.module.js:1:6987
S — preact.module.js:1:6166
T — preact.module.js:1:2137
S — preact.module.js:1:5984
N — preact.module.js:1:8090
(anonymous function) — Onboarding.jsx:24
promiseReactionJob
	(anonymous function) (base-45c8fbe2d46d136491bf06fff5ef8ab0dd62f8d88074e24d6f3aa16a70ad30c5.js:4:27540)
	(anonymous function) (Onboarding-314c1670a0e11180a115.chunk.js:1:2587)
	promiseReactionJob
```

Had to disable JS so it wouldn't redirect and find where to report this issue. 

**To Reproduce**

1. Click on "Register"
2. Click on "Continue with Github" 

**Expected behavior**

Site reloads me to onboarding as a new user. 

**Desktop (please complete the following information):**

- OS, version: macOS Big Sur 11.1
- Browser, version: Safari 14.0.2

**Comment by msarit** [comment]
Hey @deivuh thanks for reporting this issue. We're on it!

**Comment by katiedavis** [comment]
Hello! There's a fix for this here: https://github.com/forem/forem/pull/12541
