### ISSUE TITLE
"Unable to load Comment Subscription component"

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#12545]
**Describe the bug**

![image](https://user-images.githubusercontent.com/108287/106653335-f253a580-6596-11eb-8ecc-3582965616a1.png)

It's been happening quite often recently for me but I can't really tell how exactly this should be reproduced. It does work after refreshing the page, but then when I go to another post it's broken again.

Also, this is what's happening in the console:

![image](https://user-images.githubusercontent.com/108287/106653573-465e8a00-6597-11eb-8ff7-03bf34f7b404.png)

**To Reproduce**

See above.

**Expected behavior**

Fo this component to work properly :)

**Screenshots**

See above. 

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Comment by rhymes** [comment]
Just had the same issue, same error.

Browser: Firefox 86beta

**Comment by aitchiss** [comment]
I'm not seeing the error in the UI (yet!) but I can reliably reproduce the error in the console:

- In a new incognito/private window, navigate to dev.to
- Open any post, observe no error in console
- Go back to the feed (either by back click or clicking the logo)
- Open any other post - error appears
- Continue opening posts - every time the error appears again


![error in console stating subscribeBtn has already been declared](https://user-images.githubusercontent.com/20773163/106905914-8f782080-66f4-11eb-87c7-e57bc8c7900d.png)

**Comment by javila35** [comment]
Hi, I'd like to claim this issue please.

**Comment by cmgorton** [comment]
> Hi, I'd like to claim this issue please.

Wonderful. Just assigned you to it. Let us know if you have any questions along the way!
