### ISSUE TITLE
Update "You used X to authenticate your account" in certain transactional emails

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#12546]
**Current Behavior**:

Certain transactional emails will include this text at the bottom:
> Reminder: You used **Twitter** to authenticate your account, so use any of those to sign in if prompted.

However, if the email is being sent to someone who authenticated with email/pass, it will just say:
> Reminder: You used to authenticate your account, so use any of those to sign in if prompted.

**Expected Behavior**:

We should probably update this to the following for email/pass users:

> Reminder: You used **Email & Password** to authenticate your account, so use any of those to sign in if prompted.

**Comment by vaidehijoshi** [comment]
This one is actually _super_ easy 😉 I think I can actually "15 minute fix" this so that it doesn't need to wait another 2 weeks 👍🏽
