### ISSUE TITLE
Post creation form bugs

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12572]
**Describe the bug**

Two things popped up here in a recent change:

### Bug 1 [Fixed]

https://user-images.githubusercontent.com/3102842/106918584-51b8cf00-66d7-11eb-9448-4332764d5e55.mov

The flash of placeholder text not mapping visually to the attached Preact component should match up well. The appropriate classes need to be there both in the server placeholder and the Preact component.

### Bug 2 [Fixed]

The title text being the smallest text on the page seems off. It seems like all the text is the same 16px or 1rem, but due to the different font families used, the title itself is pretty hard to visually spot on the page compared with everything else. The desktop width version of this page still has the "big" title text and the mobile version should probably have at least slightly bigger text than the body.

<img width="369" alt="Screen Shot 2021-02-04 at 11 09 13 AM" src="https://user-images.githubusercontent.com/3102842/106921083-a5c4b300-66d9-11eb-9b0e-2e630b2b3f10.png">

### Bug 3

I'm getting a vague and overarching "Something went wrong" when I try to hit preview.

<img width="743" alt="Screen Shot 2021-02-04 at 11 01 18 AM" src="https://user-images.githubusercontent.com/3102842/106919616-503bd680-66d8-11eb-82be-58a082baa997.png">

**To Reproduce**

Visit https://dev.to/new 

- Hit refresh to see the style bug
- Observe the text sizes to see the visual hierarchy issue
- Fill out a title and hit "preview" to see the alert issue

**Expected behavior**

For the last bug, I should be able to preview without some of these fields filled out, and if there is a legitimate problem it should be something that should result in a better warning.

**Desktop (please complete the following information):**

- OS, version: Mac 11.1
- Browser, version: Chrome 88.0.4324.96

**Comment by ludwiczakpawel** [comment]
Bug 3 seems like a separate from Bug 1 and Bug 2. I'll have a PR with fix for 1 & 2 ready in couple mins.

**Comment by benhalpern** [comment]
Great @ludwiczakpawel

**Comment by atsmith813** [comment]
Maybe a recent deploy fixed bug 3? I can't reproduce that one 🤔

**Comment by fdoxyz** [comment]
@atsmith813 did you try with empty body + tags? I was able to reproduce just now in dev.to (after clearing out local data to be sure the bug wasn't cached)

![Screen Shot 2021-02-04 at 16 13 19](https://user-images.githubusercontent.com/6045239/106962693-1c2ada80-6705-11eb-8ac0-88d5b94e171c.png)

The backend is responding without an error (an exception is not raised in `articles#preview`)

I’m not sure yet if what changed was the way this empty response is handled in Preact or if the backend used to respond differently and now this is being considered an error (the empty response)

**Comment by atsmith813** [comment]
@fdoxyz great call! It errors if the body is empty
