### ISSUE TITLE
Subscribe to discussion button does nothing if user is not logged in

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#12571]
**Describe the bug**

When a user views a post, but is not logged in currently, a "Subscribe" button is visible next to the discussion/comments section. Clicking on the button does nothing.

**To Reproduce**

1. Make sure you aren't currently logged in
2. Open any post
3. Scroll to the subscribe button and click
4. Nothing happens

**Expected behavior**

I would expect that on "Subscribe" click we trigger the same modal we do on a reaction or reply click:

![Log in to continue modal that we show on other logged out clicks](https://user-images.githubusercontent.com/20773163/106904064-a0279700-66f2-11eb-9cd6-3f3e20d93344.png)

**Screenshots**

![gif showing me clicking on a subscribe button and nothing happening](https://user-images.githubusercontent.com/20773163/106904040-9b62e300-66f2-11eb-88a8-87c9022e4a96.gif)

**Desktop (please complete the following information):**

- OS, version: Mac 10.15.7
- Browser, version: Chrome 87

**Smartphone (please complete the following information):**

- Device: Pixel 5
- OS, version: Android 11
- Browser, version: Chrome latest

**Comment by Miguel-Enrique13** [comment]
@cmgorton - Could you assign me to this issue
