### ISSUE TITLE
Account locked and no response from support

### ISSUE THREAD

**Issue by jason00111** [forem/forem#12604]
**Describe the bug**

My account appears to be locked. I'm unable to write new posts or modify existing posts.

I've sent multiple emails to yo@dev.to and received no response.

**To Reproduce**

_Writing a new post_

1. Click on the big "Write a post" button.
2. See this error:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/20765448/107133663-8bd4cd00-689f-11eb-9231-1b458dc289aa.png">

_Modifying a post_

1. Go to "Dashboard".
2. Click on "edit" next to a previously published article.
3. Modify post.
4. Click "Save changes" button.
5. See this error:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/20765448/107133777-a22f5880-68a0-11eb-8a33-99b5653674f5.png">

_Getting support_

1. Go to "Dashboard"
2. Scroll to bottom.
3. Click "Contact".
4. Follow instructions by sending email to yo@dev.to describing the issue.
5. Receive no response.
6. Repeat steps 4 and 5.

**Comment by cmgorton** [comment]
Hey @jason00111 what is your DEV username? 
I can talk to the support team and see if they can give me more information here. Thanks.

**Comment by cmgorton** [comment]
Hey @jason00111 I talked to our support team. They will be emailing you to discuss why you can't currently write new posts or modify existing posts.
