### ISSUE TITLE
User menu broken for touch devices

### ISSUE THREAD

**Issue by jfbrennan** [forem/forem#12635]
**Describe the bug**

On iPhone, tapping the user menu briefly opens and closes it. It’s impossible to access links like Dashboard. 

**To Reproduce**

Tap the user menu, see it flash open then close. 

Note: this works fine on desktop

**Expected behavior**

Tapping the user menu would open the menu and I’d be able to access those links

**Smartphone (please complete the following information):**

- Device: iPhone 12 mini
- OS, version:
- Browser, version: Safari

**Additional context**

But seemed to have been released within the last 7 days

**Comment by cmgorton** [comment]
Thank you for reporting this @jfbrennan.

**Comment by cmgorton** [comment]
Confirmed this is an issue on mobile iOS. Team is looking in to a fix for this now. Thanks again for reporting this.

**Comment by vaidehijoshi** [comment]
Hi @jfbrennan! Thanks so much for flagging this and bringing it to our attention. 


We deployed a fix for this a few hours ago, so this issue should hopefully not be happening anymore. Please do let us know if it is and we'll hop right on it!

Thank you again for alerting us to this, we really appreciate it :)

**Comment by jfbrennan** [comment]
working again 👍
