### ISSUE TITLE
Update self-hosting Documentation 

### ISSUE THREAD

**Issue by mstruve** [forem/forem#12671]
## Motivation

As we prepare to engage with folks on our waiting list, we should have a great resource available for people who intend to self-host Forem.  Currently, we have https://docs.forem.com/self-hosting/ but it hasn't been updated with the latest and greatest information. We should update that information with the most recent route for self hosting. 

In addition to updating the docs we should also [make sure to add server specs as requested in this Issue](https://github.com/forem/forem/issues/12386)

**Comment by akhil-naidu** [comment]
It's a long wait, but still have my hope, that one day I can have my own Forem.

**Comment by vaidehijoshi** [comment]
Given that we're gearing up to get FOSS rolling soon and working towards unblocking ourselves on that front, seems like it might be a good time to do a quick audit of the self-hosting docs and update them with any new info/remove outdated info. This could be a first step towards our larger FOSS goal.

This update wouldn't need to be major -- it would just be a copy change -- so this issue could move forward (and doesn't need to be a RFC). We'd just need to make sure we get the relevant info as copy to update the docs with. Was just thinking that this could be a great quick win for next cycle.

cc @mstruve

**Comment by mstruve** [comment]
I am not sure if a dev would be able to do this. I think this might need the systems team's input and help and I would rather have them focused on the FOSS work rather than updating these docs which will be out of date in a couple of months when the FOSS offering is ready.

**Comment by vaidehijoshi** [comment]
> I am not sure if a dev would be able to do this. I think this might need the systems team's input and help

Oh! Okay -- from the issue description I thought it would be a straightforward copy change that any dev could tackle quickly. If it's not and if it requires systems help, then I agree that we shouldn't do this now (especially if it's going to take more than a negligible amount of time given that we plan to overhaul it with FOSS). Mostly was thinking we could do this as as stop-gap, but it looks like I misunderstood how much coordination it would require :)
