### ISSUE TITLE
Add OpenID Connect Authentication

### ISSUE THREAD

**Issue by TheMysteriousVincent** [forem/forem#12678]
Hi there!

First of all, thanks for the great software. I like it.

Now, I saw that forem supports some OAuth2 flows such as those for GitHub, Facebook, e.g.. Wouldn't it be a good idea to also add a custom OpenID Connect provider (OIDC), to also support custom identity providers other than GitHub or Facebook?

So, feature request for OIDC as an authentication flow.

Sincerely,
Vincent

**Comment by cmgorton** [comment]
Hey @TheMysteriousVincent Thank you for opening this request. 
Features tend to be subjective and might spur some debate. The Forem core team uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature.

I recently brought up sign in with email and other providers to our team and I know it is something they want to have a discussion on again so [forem.dev](https://forem.dev/) is definitely a great place to get that started!
