### ISSUE TITLE
Bug in the dates of posts

### ISSUE THREAD

**Issue by Afif13** [forem/forem#12683]
Here is a screenshot to illustrate: <a href="https://ibb.co/rykvNs6"><img src="https://i.ibb.co/ZTdN7m8/bug.png" alt="bug" border="0"></a>

I think it's self-explanatory. Either both dates should show 12 Feb or 13 Feb or the edited date should always be bigger than the published date.

**Comment by deepakmahakale** [comment]
Hi @forem/oss @forem-team @citizen428 ,

I tried to take a look at the issue 

```ruby
# app/views/dashboards/_dashboard_article_row.html.erb
<% if article.published %>
  <p class="fs-s color-base-60 js-dashboard-story-details">
    <strong class="fw-medium">Published:</strong>
    <%= local_date(article.published_timestamp, show_year: article.displayable_published_at.year != Time.current.year) %>
    <% if article.edited? %>
      <strong class="fw-medium pl-2">Edited:</strong> <time datetime="<%= article.edited_at.utc.iso8601 %>"><%= article.readable_edit_date %></time>
    <% end %>
    # ...
<% end %>
</div>
```
As per my understanding:
It seems that converting the `article.edited_at` to `local_date` should fix the issue.

Let me know if my understanding is correct and if converting the edited_at date is ok.

**Comment by deepakmahakale** [comment]
Proposed solution:
```diff
        <%= local_date(article.published_timestamp, show_year: article.displayable_published_at.year != Time.current.year) %>
        <% if article.edited? %>
-          <strong class="fw-medium pl-2">Edited:</strong> <time datetime="<%= article.edited_at.utc.iso8601 %>"><%= article.readable_edit_date %></time>
+          <strong class="fw-medium pl-2">Edited:</strong>
+          <%= local_date(article.edited_at, show_year: article.edited_at.year != Time.current.year) %>
         <% end %>
 ```

**Comment by citizen428** [comment]
@deepakmahakale Since you already made a local commit, could you please open a PR and we have the discussion there?

**Comment by Afif13** [comment]
No really, it's probably related to my browser that is set to French in the
language setting

Le mar. 9 mars 2021 à 10:35, Deepak Mahakale <notifications@github.com> a
écrit :

**Comment by deepakmahakale** [comment]
Thanks @rhymes ,
Just changed the language setting and tested.
