### ISSUE TITLE
XML page showing in the subscribe button - codenewbie

### ISSUE THREAD

**Issue by AthulMuralidhar** [forem/forem#12684]
**Describe the bug**

The subscribe button [here](https://www.codenewbie.org/podcast/what-are-the-skills-you-need-to-go-from-developer-to-entrepreneur) is not working. It is showing some wierd xml page now 

**To Reproduce**

1. Go to [this link](https://www.codenewbie.org/podcast/what-are-the-skills-you-need-to-go-from-developer-to-entrepreneur)
2. Click on the `subscribe` button
3. You just see the rendered xml page

**note** this one could be critical as i can see the resource urls for the page rendering (and no https to boot)

**Expected behavior**
it should not be showing the xml page

**Screenshots**
![xmlerror](https://user-images.githubusercontent.com/35686547/107878650-792c4a80-6ed4-11eb-9b45-97f2b1dee1a9.png)

**Desktop (please complete the following information):**

- OS, version: Kali GNU/Linux ver: 2020.4

- Browser, version:  firefox, 78.7.0

**Comment by Zhao-Andy** [comment]
Hi @AthulMuralidhar! Thanks for the report. I think this is intended because generally you can add that XML link to any podcast app, or to an RSS feed that you have.

There should be HTTPS, but thankfully it's not a big concern since there is no private data on `feeds.codenewbie.org`.

**Comment by AthulMuralidhar** [comment]
So close the issue ? @Zhao-Andy
