### ISSUE TITLE
[potential RFC] [Api Dev.to] Yaml spec

### ISSUE THREAD

**Issue by EwertonJordao** [forem/forem#12698]
**Describe the Feature**

Hello everyone! how are you ?

Can you implement specification of API Forem in .yaml file for donwload?
I'm try to valid an idea and I can't use .json spec.

Best Regards, 

**To Reproduce**

**Expected behavior**

Yaml or Json option

**Screenshots**

![image](https://user-images.githubusercontent.com/12378570/108007066-cd6e2200-6fdb-11eb-81e3-baafc76ef9af.png)

**Comment by rhymes** [comment]
Hi @EwertonJordao, the YAML spec is here: https://github.com/forem/forem/blob/master/docs/api_v0.yml

You'll find the latest downloadable version at https://raw.githubusercontent.com/forem/forem/master/docs/api_v0.yml

Let me know if this covers your request.
