### ISSUE TITLE
Importing RSS feeds has stopped, without changes to output/availability

### ISSUE THREAD

**Issue by lukeocodes** [forem/forem#12708]
**Describe the bug**

(forwarded from Twitter DM as the request of the DEV Twitter peeps)

hey lovely DEV folks :) hoping you can help. I suspect an account somewhere is importing our main RSS feed, because all of a sudden all our RSS imports have stopped. Can you help?

We individually use our own feeds (i.e. https://learn.vonage.com/feeds/authors/lukeoliff/rss.xml)

But posts are also available from a feed here: https://learn.vonage.com/feeds/blog/rss.xml 

We've had the issue in the past where posts haven't been imported on one account because it was imported by the central feed being incorrectly added by someone on another account (the unique canonical URL issue). We've been pretty good staying on top of this, but we're unable to find out what is causing it now.

Is there any chance you can help identify why these aren't importing?

**To Reproduce**

1. Go to settings/extentions
2. Scroll down to RSS feeds
3. Enter one of our learn.vonage.com RSS feed URLs

**Expected behavior**

Post gets imported

**Comment by cmgorton** [comment]
Thank you for opening this Luke. I am adding it to the list of RSS issues I mentioned in our communication.

**Comment by lukeocodes** [comment]
Thanks @cmgorton, if it resolves (like it was a server-side issue) I will update you here.

**Comment by rhymes** [comment]
Hi @lukeocodes, sorry for the delay, I did some investigation and it looks like the [DEV user sudipto](https://dev.to/sudipto) has assigned https://learn.vonage.com/feeds/blog/rss.xml to themselves without having published any of the posts.

Given a known issue we have with `canonical_url`s and unpublished posts the result is blocking your ability to publish.

Before passing it on to support to correct this, we need to confirm that `sudipto` is not part of your organization, can you confirm?

cc @cmgorton and @Zhao-Andy

**Comment by lukeocodes** [comment]
He isn't internal to our organization but I believe he is one of our ambassador programme members. I can reach out to him before having to escalate to support. Thanks so much for the help team!

**Comment by rhymes** [comment]
@lukeocodes thank you! they'd basically need to remove the feed from their settings and delete the unpublished posts (or remove the canonical URL from each of them). Let us know if you still need help

**Comment by lukeocodes** [comment]
All resolved! Thanks, @rhymes and @cmgorton :)
