### ISSUE TITLE
Revamp failure handling in workers

### ISSUE THREAD

**Issue by citizen428** [forem/forem#12713]
For context: [PR discussion thread](https://github.com/forem/forem/pull/12686#discussion_r576083158)

We currently swallow errors in workers, e.g.:

```ruby
article = Article.find(article_id)
return unless article
```

We do this in order to avoid futile retries, but we also lose insight into errors because of this.

An alternative pattern could look like this:

```ruby
def perform(some_id)
  some_model = SomeModel.find(some_id)
  # code working on some_model
rescue ActiveRecord::RecortNotFound => e
  # Notify Honeybadger or other service
end
```

This would ensure that we're notified about the error, while still avoiding the retry.

Additionally, we should look into the way we're currently using retries: in many workers we have them set to a value (e.g. `retry: 10`) but use the above pattern to avoid retrying. Many of our jobs won't fail in retry-able ways, so in some recent ones I set `retry: false` and let them raise.

**Comment by vaidehijoshi** [comment]
Hm, I feel like this is a straightforward optimization that will give us much more insight into our errors than what we already have. I would be fine keeping this as an issue rather than writing up a RFC for it (cc @mstruve)

**Comment by mstruve** [comment]
I am good letting this remain an issue bc the only detail here that needs to be figured out is where to send the alert of the failed job. From an SRE perspective, this data is not immediately actionable so Honeybadger would not be the place to send it since that is where we want actionable failures to go. That leaves Datadog(via logging) and Honeycomb and I would honestly be fine with either or both. 

@citizen428 what are your thoughts?

**Comment by citizen428** [comment]
@mstruve I'm tempted to say both: a DataDog counter for seeing trends and Honeycomb for keeping a log of the error. It's probably best to wrap this up in some service, so we can standardize on how we monitor non-actionable errors, e.g.

```ruby
module Errors
  class LogNonActionable 
  # or LogWorkerError if we want to scope more narrowly
    def self.call(key, exception)
      ForemStatsClient.increment(...)
      # log to Honeycomb
   end
end
```
