### ISSUE TITLE
Low quality / non-constructive comments are not grayed out

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#12751]
**Describe the bug**

Previously, low quality / non-construcitve comments were faded / had grayed out text to signify that they're less visible. I think this was removed by accident, so we can add it back in. This might also be an opportunity to update the design a bit to make it more clear.

**To Reproduce**
1. Write a comment
2. Refresh the page
3. If you are a `trusted` user, you should be able to click three dots menu and mark the comment with a thumbs down and vomit reaction
4. Go back to the article and comment's link
5. See that it is marked as low quality / non-constructive

In article's comment's section:
![Screen Shot 2021-02-19 at 11 53 32 AM](https://user-images.githubusercontent.com/17884966/108535395-4bb31880-72a9-11eb-9c1b-48a3c95b5783.png)

In comment's show page:
![Screen Shot 2021-02-19 at 11 52 55 AM](https://user-images.githubusercontent.com/17884966/108535436-57064400-72a9-11eb-8680-eed212dc2c7e.png)

**Comment by lisasy** [comment]
@lisasy tagging myself to look at this later.

**Comment by lisasy** [comment]
Hi @Zhao-Andy, here is proposed design for how to improve this — included why this is a user problem that impacts our business. Does this look good? If so, let's do this! 

Solution-wise:
1. We use the Crayons component for this `notice`
2. We update the comment body to `base-60`
3. We check to see it renders well across all of our themes. 

![2021-01-23_Low-Quality-Comments_Issue](https://user-images.githubusercontent.com/816402/108888578-7dd1bc80-75c0-11eb-9f1c-845048922190.jpg)

**Comment by Zhao-Andy** [comment]
This looks great! I'm happy to implement it. cc @pkfrank @michael-tharrington if you two have any thoughts.

**Comment by pkfrank** [comment]
I don't want to bike-shed too much, but I do think the Red highlighting here might unintentionally draw _more attention_ to the post (which we don't want).

I think the `base-60` faded adjustment is great.  That grayed out text, along with the message above, might be enough IMO.

**Comment by michael-tharrington** [comment]
Good point about the red text @pkfrank, I think the grayed out text + messaging would work great.

**Comment by Zhao-Andy** [comment]
Re: the `danger` / red notice. If not red, we can go for the [`warning` / yellow notice](https://storybook.dev.to/?path=/story/components-notices-html--warning), or maybe the [default notice](https://storybook.dev.to/?path=/story/components-notices-html--default)?

**Comment by michael-tharrington** [comment]
I think my vote would be the default notice paired with the faded adjustment to the message.

**Comment by lisasy** [comment]
@Zhao-Andy Warning/yellow would be great :) Thanks for the feedback! @pkfrank 

![2021-01-23_Low-Quality-Comments_Issue](https://user-images.githubusercontent.com/816402/108918129-b9cb4880-75e5-11eb-84aa-2688013496c6.jpg)

**Comment by michael-tharrington** [comment]
@lisasy I'm fine if we decided to us the yellow, but to @pkfrank's point doesn't this draw more attention to the comment that we're trying to make less noticeable?  I think yellow and red will draw attention whereas grey will not.

**Comment by lisasy** [comment]
@michael-tharrington If you see the problem statement in the mock, here is how it is stated:

> When someone looks at a “low-quality” message, it’s not clear to them that this message might be low quality and/or offensive. Because of this, they might think Forem allows low quality content like this to propogate on our platform, when that isn’t the case.

We want to make clear to someone that Forem is positioned to take action on low-quality content like this, and it is appropriately to use the "warning" label here to visually communicate our position. Let's commit to `warning` (yellow) since we will also have the grayed out text as well.

**Comment by michael-tharrington** [comment]
@lisasy That makes sense! You're totally right that we don't want our low quality message to be overlooked. Plus thinking about it all more critically now, when we mark something with the overlay it does knock the comment down the list + the author has the ability to hide messages if they want.
