### ISSUE TITLE
Dialog styles not removed when going back from listing

### ISSUE THREAD

**Issue by rdasselaar** [forem/forem#12771]
**Describe the bug**

When you are not authenticated and go to a listing, then go back to the previous page, the page is not scrollable anymore due to a `.dialog-open` class on the body.

**To Reproduce**

1. Go to dev.to
2. Click on a listing, see a dialog. Don't close!
3. Navigate back to the previous page (back-button in your browser, or any shortcut)

Please note; I only experience this when I am not authenticated.

**Expected behavior**

You can scroll again when navigating back from an open dialog.

**Desktop (please complete the following information):**

- OS, version: Microsoft Windows 10
- Browser, version: Chrome Version 88.0.4324.182 (Official build) (64-bits)

**Comment by aitchiss** [comment]
Thanks for raising this issue - I've been able to replicate the same locally. 
It looks like the changes in #12511 (Improve keyboard accessibility of modals) will fix this bug, so hopefully we'll have this corrected soon 👍

**Comment by rdasselaar** [comment]
Nice, glad that it will be fixed soon :-)
