### ISSUE TITLE
YAML markdown not rendering correctly. 

### ISSUE THREAD

**Issue by onlyutkarsh** [forem/forem#12783]
**Describe the bug**
I have a yaml code snippet in the post, but it is not rendering correctly. My yaml
![image](https://user-images.githubusercontent.com/2685029/108832259-31d44700-75c3-11eb-9b11-570120deed2f.png)

What I see: 

![image](https://user-images.githubusercontent.com/2685029/108832300-457fad80-75c3-11eb-840f-929916971243.png)

**To Reproduce**

NA

**Expected behavior**

Correctly syntax highlighted YAML

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Edge latest

**Additional context**

This post has been imported from rss feed and I am correcting the markdown myself.

**Comment by cmgorton** [comment]
Hey @onlyutkarsh can you paste the code here that you put in the editor. This is what I see when I put the code in a yaml code block. 
![Screen Shot 2021-02-23 at 8 29 03 AM](https://user-images.githubusercontent.com/21039864/108858008-50c9dd80-75b1-11eb-862a-8f2c0c0d8b27.png)

**Comment by onlyutkarsh** [comment]
Hello @cmgorton - This is a long blog post, so I created the gist [here](https://gist.githubusercontent.com/onlyutkarsh/555c22af60d1a6f920b925f4b561a85d/raw/ad6f4d31645624518084e1b4f2cdb069cfebdc9c/yaml-issue-blog.md)

**Comment by cmgorton** [comment]
Took me a little while to find it but you have a left over open backtick that is causing the yaml code not to be in code blocks. If you remove the backtick after permissions your code blocks work. It is in the  **Creating scope maps** section.
<img width="1632" alt="Screen Shot 2021-02-23 at 4 00 31 PM" src="https://user-images.githubusercontent.com/21039864/108914027-68748680-75f0-11eb-9579-35f60c9af1fd.png">

**Comment by onlyutkarsh** [comment]
Oh that was it! Really sorry fire the trouble. Appreciate you taking a look. Thanks a ton! I'll close this issue now!

**Comment by cmgorton** [comment]
No trouble! Glad we could figure it out 😄 I had a hunch because I've done this so many times on my own posts 😆
