### ISSUE TITLE
Mobile pull to refresh shows "Skip to Content" button in custom theme

### ISSUE THREAD

**Issue by fdoxyz** [forem/forem#12786]
**Describe the bug**

When pulling down to refresh (mobile) in any custom theme (not the default theme) the "Skip to Content" button (accessibility) is visible instead of the expected label.

**To Reproduce**

1. Log in to a Forem instance in mobile
2. Activate a custom theme (i.e. Dark mode)
3. Pull down to refresh

**Expected behavior**

It should behave the same way it does in the default mode (label that says "pull to refresh")

**Screenshots**

https://user-images.githubusercontent.com/6045239/108848508-b06ebb80-75a6-11eb-9818-ee92fdc888a2.MP4

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS, version: 14.4
- Browser, version: Chrome but also reproducible within `ForemWebView`

**Comment by aitchiss** [comment]
Interestingly I've not been able to reproduce this on my android device (or in the iOS simulator) 👀

This has likely been a side effect of #12694 so could be considered a "current cycle" issue rather than waiting til next cycle - I would look at fixing it (since I caused it 😅) but seems like someone with an iOS device would need to take it on

**Comment by fdoxyz** [comment]
Interesting thank you for the context @aitchiss! Since it's a "current cycle" issue I just moved it to that board instead of waiting to process it through the funnel.

I just took a look at the PR but wasn't able to figure out why it only happens in custom themes and not the default theme. It could be a WebKit specific issue.

This is a video of how it looks in the dev tools in Chrome (macOS 11.2): https://share.getcloudapp.com/7Kup60oz

I'm happy to assist debugging this with anyone who wants to tackle this 😄

**Comment by aitchiss** [comment]
@fdoxyz very strange - I just tried to replicate in chrome dev tools and I don't see the skip link:


https://user-images.githubusercontent.com/20773163/108853549-c5ffd780-75de-11eb-8572-ea00d6a60d16.mp4

All I can think that's different in our set ups is I'm still on Catalina 🤔

**Comment by fdoxyz** [comment]
@aitchiss oh yeah it's probably the WebKit version that has some sort of difference. Out of curiosity what do you get from [this check](http://browserspy.dk/webkit.php)? I get the following:

<img width="903" alt="Screen Shot 2021-02-23 at 08 01 55" src="https://user-images.githubusercontent.com/6045239/108854421-781eab80-75ad-11eb-8f27-f788adeaea48.png">

From what I understand this is the logic behind the button:

1. "Skip to Content" is always visible (never `display: none` or something like that)
2. It uses [this translate](https://github.com/forem/forem/pull/12694/files#diff-3df0c9a01d1009d34b9cbf6fad2508a639fba80dcb7bd9d93f6b6264384ec9dfR135) so it lives off the screen by default (to make it invisible)
3. The only way for it to appear it is when it gains focus (via tabs or screenreader) and when that happens [this transform](https://github.com/forem/forem/pull/12694/files#diff-3df0c9a01d1009d34b9cbf6fad2508a639fba80dcb7bd9d93f6b6264384ec9dfR141) makes it drop back into the visible screen
4. When pull to refresh is dragged down, the "Skip to Content" button doesn't move because **its position is absolute**

Even though I found no difference in their computed CSS ([pic1](https://user-images.githubusercontent.com/6045239/108856835-13188500-75b0-11eb-8d02-360e0b984671.png) & [pic2](https://user-images.githubusercontent.com/6045239/108856819-101d9480-75b0-11eb-96b3-f221d2648eb0.png)) I think the detail lives in point 4 from above

This _could be_ a bug/regression in WebKit that causes absolute elements to move when siblings or parents are being dragged down.

[A simple fix I just sent in](https://github.com/forem/forem/pull/12790) consist of moving the button upwards 200% instead of 100%, that way the drag from "Pull to Refresh" doesn't go far enough to show the button on the screen. However, this might not be an ideal solution since something else could be happening that we're not aware of, since it only happens in custom themes it could be related to how we "merge" these CSS.

**Comment by fdoxyz** [comment]
> @fdoxyz my webkit version from that check is 537.36 also 🙃

Oh wow 😂
