### ISSUE TITLE
No way to found bookmarks in mobile version

### ISSUE THREAD

**Issue by suther** [forem/forem#12810]
Maybe I am only blind, but I didn't found where the bookmarks are, if open the page dev.to on Mobile-Service, installed as webapp.
I do searched for more then 10 minutes without results.

I can mark an article as 🦄, ❤️ or bookmark it, but there are no area to thee all my book arks.

Happens on Android device.

In my opinion it should be something like an bottom tapbar menu

**Comment by cmgorton** [comment]
Hey @suther You should be able to see the articles you bookmarked if you click the link called Reading List. You can navigate there from the main hamburger menu. 
![Reading list on DEV](https://user-images.githubusercontent.com/21039864/109058980-4be85500-76a9-11eb-8540-3f985ee8bb2c.jpg)

**Comment by cmgorton** [comment]
Let me know if that is not what you were looking for Samuel. I can reopen this issue if that didn't help. Thanks.

**Comment by xstable** [comment]
Ah, yes, like I said... I'm blind ^^
Maybe it would be a good Idea to use the same Icon in front of the menu which is used to place the bookmark. This way users see, that "Reading List" means the "bookmarks" section here.
