### ISSUE TITLE
Remove disambiguatingDescription from user profile (generalization bug)

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12818]
**Describe the bug**

The property of `disambiguatingDescription` is described as this in schema.org:

> A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.

And we implement that like this:

```ruby
  def user_disambiguating_description
    [@user.mostly_work_with, @user.currently_hacking_on, @user.currently_learning].compact
  end
```

Of course these fields are not generalized and cause bugs we may run into if people start using profile generalization fully.

I _believe_ that `disambiguatingDescription` is a _nice to have_ and not likely contributing to SEO in any massive way. In my opinion we could just chop this out of the codebase to further solidify the profile generalization foundation. This is not a user-facing feature or one that is explicitly exposed in a supported API. It _may_ help SEO but not in a substantial way.

**Comment by citizen428** [comment]
@mstruve I took the liberty to do it as a 15-minute fix during my current OSS rotation, because I was already familiar with this and because it literally took less than 10 minutes from start to finish, so I thought there's no need to spend time on this during the next cycle planning.

**Comment by mstruve** [comment]
Rockin! Thanks!
