### ISSUE TITLE
I can't scroll down

### ISSUE THREAD

**Issue by siemah** [forem/forem#12813]
**Describe the bug**
When i visited [this link](https://dev.to/listings/collabs/fail2ban-enable-it-prevent-ssh-brute-force-attacks-255j) and then i clicked on the link: `https://dev.to/mrturkmen/fail2ban-block-ssh-bruteforce-attacks-40np` to read the whole article and when i tried to reach the section below the fold by scrolling down i found that i can't do that because the body tag still has the `overflow: hidden;` from the previous page(when modal was open)

**To Reproduce**

1. Go to [this link](https://dev.to/listings/collabs/fail2ban-enable-it-prevent-ssh-brute-force-attacks-255j)
2. Click on `https://dev.to/mrturkmen/fail2ban-block-ssh-bruteforce-attacks-40np`
3. Scroll down to reach the section below the fold
4. Bingo, you can't scroll down

**Expected behavior**
The possibility to scroll down and reach the whole article

**Desktop:**

- OS, version: macOS Catalina version 10.15.7
- Browser, version: Firefox 85.0.2 (64-bit), Google Chrome 88.0.4324.182 (Official Build) (x86_64) and Safari Version 13.1.3 (15609.4.1)

**Comment by cmgorton** [comment]
I am not having this issue. I can stroll down and see the full article. I tried on Chrome, Firefox, and Safari. I am also on macOS. Can you try another browser or try once more to see if this is still an issue? Thanks!

**Comment by aitchiss** [comment]
I think this bug may have been resolved yesterday by #12511 🙂

**Comment by cmgorton** [comment]
Thanks @aitchiss !
