### ISSUE TITLE
outlook.in domain not whitelisted for signups

### ISSUE THREAD

**Issue by thenamankumar** [forem/forem#12840]
**Describe the bug**

`outlook.in` domain is not whitelisted for signups.

**To Reproduce**

- Go to https://forem.team/users
- Fill any example@outlook.in email.
- Submit

**Expected behavior**

It shall create a new account and move to next step.

**Screenshots**

<img width="776" alt="Screenshot 2021-03-01 at 8 15 05 AM" src="https://user-images.githubusercontent.com/22571395/109445717-3cc92480-7a66-11eb-942e-467a507be157.png">

**Comment by citizen428** [comment]
Hi @thenamankumar: forem.team is our private Forem and not open for public signups, so this is intended behavior. However, you might interested in joining https://forem.dev/, our community collaboration platform.
