### ISSUE TITLE
Bug for infinite views

### ISSUE THREAD

**Issue by DevLorenz0** [forem/forem#12878]
**Description**

I started blogging on dev.to around a month ago and founded it very cool and well done.
I'm writing this report because I think I founded a bug that allows a blogger to add fake views on a post. The writer (or another user) just has to create another user of chrome and then copy/paste the link indefinitely. It works only by opening the page in a new tab (not refreshing).
So a malicious user could just leave the pc open for a night with an auto clicker (Doing around 5000 fake views per night with a 4/5 seconds refresh rate). 

**To Reproduce**

Go to a forem article (like at dev.to) 
Copy the link
If you are the author open the link with a new account (different chrome user)
Open multiple times the link on a new page
Views are added to the article

**Expected behavior**

Views are not counted as the same user is opening the article. 

In my humble opinion, I think that is fair that a content creator is rewarded for every view so that if the same user returns 5 times on the same article the creator is more recompensed than an article you read once. So a good limit would be 10 views for each user (or even better 10 for computer, don't know but maybe with IP addresses). It would block the bug (10 views are nothing compared to 5000) but also continue rewarding the writer for his multiple views (and no one will ever notice the limitation).

**Desktop:**

- OS, version: Microsoft, Windows 10
- Browser, version: Chrome, latest (88.0.4324.190) --> I used two different users on the same machine to perform the trick

**Smartphone:**

I don't think it works on smartphone (my tests failed) - However, it would be considerably less efficient (slower) than on pc.

**Additional context**

It also worked on another form community (other than dev.to): https://www.theelastic.guru/
With all the respect the elastic guru is not a very big community. And I think it's impossible that I had 200 views in 10 minutes with an article composed of just "Hello!". Also because I haven't had any other likes than mine, and when I stopped to use the trick the views stayed the same for more than three weeks.

I also tried it in my first dev.to post - who after two weeks of being stable at 100 views had 30 when I did the trick exactly 30 times. I didn't use the trick after that. 

**Screenshots**

![image](https://user-images.githubusercontent.com/78320052/109715423-e95cf080-7ba3-11eb-80dc-cc92aae1cb9d.png)

* 6 likes are mine
* 209 views are mine (all done in less than a 1 - other 3 views in the following three weeks)

Regards

**Comment by citizen428** [comment]
Thanks for opening an issue here @DevLorenz0. While I understand your concerns, there's no direct reward associated with page views, so I'm not sure what exactly an author would gain from engaging in this behavior.

**Comment by DevLorenz0** [comment]
It's true, even if the author could always easily simulate 10/30 thousand views per article as to be able, by sending photos, to find a sponsor and earn even with a few real views.

Also, it can be used for getting a lot more attention than the author deserves. For example, if they write to me to collaborate and I see that they have an average of 10 thousand views per article, I don't think twice. 
Maybe I have a thousand views per article, all real, he not even have 100 real. He makes a lot of views and I got fooled, thinking I have made a good trade (and obviously I do not receive views). It may not seem a lot but if he does it many times (and even with external blogs) he can gain a considerable advantage.

Or maybe, but I don't know, the ranking algorithm also considers views when creating my feed? If yes, it can be used as an advantage to kickstart articles.

**Comment by rhymes** [comment]
@DevLorenz0 one tiny detail that might not have been clear after @citizen428's comment: other people can't see your statistics on Forem websites. Which means that the only way for someone to know how many views you accrued (with or without tricking the system) is for you to share it with them or screenshot your dashboard. That's why @citizen428 said there's no direct reward.

It can be inferred how popular a person is via the number of likes and comments but those can't be inflated, they actually need users to like and comment your content.

**Comment by DevLorenz0** [comment]
Ok, thanks
