### ISSUE TITLE
Issue : background box of the button on profile via chat section

### ISSUE THREAD

**Issue by surajondev** [forem/forem#12879]
**Describe the bug**

There is a background box on the profile when accessing the profile via the chat section.

**To Reproduce**

-  Go to the chat section
- Enter into a chat 
- View their profile by clicking on the name

![Caffpture](https://user-images.githubusercontent.com/67496096/109755414-f8778900-7c0b-11eb-8a56-25bf419a89ba.PNG)

**Expected behavior**

I think there should not be any background around it as it covers the profile picture.

**Screenshots**
![Caffpture](https://user-images.githubusercontent.com/67496096/109755446-05947800-7c0c-11eb-9da3-23e9f6094005.PNG)

**Comment by citizen428** [comment]
Thanks for the report @surajondev! Here's another screenshot in a lighter theme, that shows a bit more clearly how the buttons overlap the profile image and how their labels are not properly centered on them:

![image](https://user-images.githubusercontent.com/47985/109765505-8ad95600-7c27-11eb-8a40-d8e97e990d46.png)

**Comment by surajondev** [comment]
Yes, that's the issue. So who is assigned to do that?

If no one is in your mind right now.

I would love to solve the issue.

**Comment by citizen428** [comment]
Thanks for volunteering @surajondev, I assigned you the issue now.

**Comment by surajondev** [comment]
Thank you😀
