### ISSUE TITLE
Rubocop Style guide link to thoughtbot repo is broken

### ISSUE THREAD

**Issue by djuber** [forem/forem#12875]
**Describe the bug**

Documentation only.

In https://docs.forem.com/getting-started/committing/#style-guide, the link to https://github.com/thoughtbot/guides/blob/master/style/ruby/.rubocop.yml should be to https://github.com/thoughtbot/guides/blob/main/ruby/.rubocop.yml instead (replacing the path `style/ruby` with `ruby/` and relabeling the trunk branch from master to main).

This is a result of a reorganization in the target repo in https://github.com/thoughtbot/guides/pull/615 

**To Reproduce**

1. Visit https://docs.forem.com/getting-started/committing/#style-guide
2. Follow the link labeled "thoughtbot's Ruby Style Guide"
3.  Observe 404 page from Github

**Expected behavior**

The rubocop.yml file should be shown in thoughbots repo.

**Comment by cmgorton** [comment]
Thanks @djuber. Would you like to create a PR for this? If not, no worries. I will let the team know we need to get this sorted out 😄

**Comment by djuber** [comment]
yes - PR to follow (looks like a one line change right now).

**Comment by cmgorton** [comment]
Great. Thanks for your help here 🙌

**Comment by citizen428** [comment]
PR has been merged, thanks @djuber. Closing.
