### ISSUE TITLE
Cannot change canonical url after it has been set

### ISSUE THREAD

**Issue by dword-design** [forem/forem#12922]
**Describe the bug**

First set of canonical url for a post works, but when going back to edit mode and changing the url, then hitting Done, you can quickly see that client side the url is set back to its saved value. Thus, it is not possible to change the url anymore.

**To Reproduce**

1. Open a blog post
2. Hit "Edit"
3. Hit "Post Options"
4. Set the option "Canonical URL"
5. Hit "Done"
6. Hit "Save changes"
7. Hit "Edit"
8. Hit "Post Options"
9. Set the option "Canonical URL" to something else
10. Hit "Done"
11. Hit "Save changes"

**Expected behavior**
The canonical url is the new url.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by nickytonline** [comment]
Hi @dword-design. I just tested this out and I see the new canonical URL reflected after it being originally set to another canonical URL. Here's a video of the test. Let me know if you are still experiencing the issue.

https://user-images.githubusercontent.com/833231/111789639-bf8c1500-8897-11eb-9eb6-cffd33d4c4c4.mp4

**Comment by dword-design** [comment]
Hey @nickytonline, seems to be working now. Thanks!

**Comment by nickytonline** [comment]
Awesome @dword-design! I'm going to close this.
