### ISSUE TITLE
Remove approvals Gem ✂️✂️✂️

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#12955]
## Description

Closing the loop on a discussion in the [Rails 6.1 upgrade thread](https://github.com/forem/forem/pull/11333#issuecomment-781475076), we've decided to remove the [Approvals gem](https://github.com/kytrinyx/approvals) as it a) doesn't work with Rails 6.1, and b) hasn't be updated in a very long time. There are around 10 tests that currently use the Approvals gem: these should be rewritten to just include the objects/information they are looking for inline.

**Note** This was originally approved as a [Stage 0 RFC](https://github.com/forem/rfcs/issues/135), but given the limited scope and refactoring focus of it, I'm opening it as an issue instead of a full fledged RFC.

## Related PRs

[Rails 6.1 Upgrade](https://github.com/forem/forem/pull/11333#issuecomment-781475076)
resolves https://github.com/forem/forem/issues/12355
resolves https://github.com/forem/rfcs/issues/135

**Comment by citizen428** [comment]
@joshpuetz Should we open this up for potential community contributors or would we rather get this over with ASAP?

**Comment by cmgorton** [comment]
@joshpuetz will this issue make the work needed on issue #12355 irrelevant?  I am not sure if the contributor that is assigned to it is still working on it but I want to make sure I let them know the work is no longer needed if this issue completely removes the Gem,

**Comment by joshpuetz** [comment]
> @joshpuetz will this issue make the work needed on issue #12355 irrelevant?  I am not sure if the contributor that is assigned to it is still working on it but I want to make sure I let them know the work is no longer needed if this issue completely removes the Gem,

It absolutely will! I'll add that to the issue text here, and if you can get in touch with https://github.com/forem/forem/issues/12355 's contributor I'd appreciate it!

**Comment by cmgorton** [comment]
Great. I will reach out to them on that issue. Thanks!

**Comment by vaidehijoshi** [comment]
I started poking at this today and ended up actually starting the process of removing `approvals` locally, so I'm going to go ahead and assign myself to this 😂 I might need some help figuring out how to "un-Approval" some of our specs, but I'll at least open up a draft PR with what I whipped up so far in the last 15 minutes :)

**Comment by vaidehijoshi** [comment]
@mstruve I added the `actual_size:S` label here because the estimation for this ticket was a bit off -- instead of 10 tests, it was 30 tests, so this took a bit more time (plus there was the added "time" of learning how the `approvals` gem worked so we can undo it). Just wanted to put a note of it here so that you have it for your metrics records!
