### ISSUE TITLE
Secondary Image (and possible other images) broken

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12987]
**Describe the bug**

The image derived from this method:

`optimized_image_url(safe_logo_url(SiteConfig.secondary_logo_url))` appears to be broken everywhere in the Forem fleet

**To Reproduce**

Visit home page of http://the.community.club/ and scroll down

**Expected behavior**

Logo should exist. This problem is not occuring on DEV, which uses Cloudinary instead of imgproxy.

I also noticed a broken image on the badge notification in one community. Not sure if related bug?

**Screenshots**

<img width="569" alt="Screen Shot 2021-03-12 at 5 26 07 PM" src="https://user-images.githubusercontent.com/3102842/111005097-2cfbeb00-8358-11eb-858e-fc5d9262c6c3.png">

<img width="595" alt="Screen Shot 2021-03-12 at 5 28 11 PM" src="https://user-images.githubusercontent.com/3102842/111005178-53ba2180-8358-11eb-9d68-2893e3fa1869.png">

<img width="679" alt="Screen Shot 2021-03-12 at 5 27 35 PM" src="https://user-images.githubusercontent.com/3102842/111005136-3edd8e00-8358-11eb-859b-0ea7e6cb0c8a.png">

**Comment by Zhao-Andy** [comment]
Hmm @maestromac possibly related to imgproxy?

**Comment by maestromac** [comment]
yeah pretty sure it is, taking a look now.

**Comment by rhymes** [comment]
Is this related by any chance @maestromac ? https://github.com/forem/forem/issues/12992

**Comment by maestromac** [comment]
@rhymes no I don't think so. Lee doesn't use imgproxy so that has to be something else.

**Comment by michael-tharrington** [comment]
Could this be affecting badges too @maestromac?

This is what things look like on [jess.lol.forem](https://jess.forem.lol/michaeltharrington2):

![Image 2021-03-17 at 11 15 04 AM](https://user-images.githubusercontent.com/16007075/111491227-11a32e00-8712-11eb-9d63-c6cba95d4d0a.png)
 
Also, on the [Web Monetization Community](https://community.webmonetization.org/michaeltharrington):
 
![Image 2021-03-17 at 11 16 26 AM](https://user-images.githubusercontent.com/16007075/111491424-3b5c5500-8712-11eb-9506-82ba28b0e20a.png)

**Comment by maestromac** [comment]
Thanks for the report @michael-tharrington 

It's along the same vain but this time it's a caching problem :facepalm:. Badge content cached by the following
```
<% cache "user-profile-sidebar-additional-#{@user.id}-#{@user.github_repos_updated_at}-#{@user.badge_achievements_count}-#{@user.organization_info_updated_at}", expires_in: 2.days do %>
```

This means that saving the user alone won't invalidate the cache and that it will naturally resolve itself in a day. So I'm not sure what's a good way to about this :thinking:

**Comment by maestromac** [comment]
I believe the issue resolved itselves
