### ISSUE TITLE
Implement a StackEdit like side preview mode in MD the editor

### ISSUE THREAD

**Issue by Chemah** [forem/forem#12989]
It would be nice to have an optional side preview in the MD editor like in [StackEdit](https://stackedit.io) to see how the content looks like in realtime and detect format errors quickly.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
