### ISSUE TITLE
How to remove undesired ( unwanted ) posts from the feed?

### ISSUE THREAD

**Issue by MenaiAla** [forem/forem#12981]
One of the most important **Design Heuristics** is giving users __Freedom & Control __ when they interact with their UI.

When I check my feed and scroll the page, I want ( sometimes ) remove undesired posts that do not match my interest. 

I expected to find a **•••** button that allow me to remove the posts from the feed, based on my **mental modal** with other social blogging websites.

I'd recommend adding **more button** to all users handle the **posts** in the feed.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏

**Comment by woodalexa** [comment]
Hi,
Wood here,
Facing same problem like this issue when I check my feed and scroll the page[,](https://purolatortracking.com/purolator-burlington-branches/#more-690) I want ( sometimes ) remove undesired posts that do not match my interest.
If you get correct answer plz mention me.
Thanks.
