### ISSUE TITLE
Individual scroll for Feed, left & right menu section

### ISSUE THREAD

**Issue by vivek7405** [forem/forem#12991]
Can we have individual scroll for the left and right menu section so that we don't need to scroll the feed/post to access the menu items at the bottom.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
