### ISSUE TITLE
Ability to provide a Auto-Save for any new Draft post

### ISSUE THREAD

**Issue by jayendranarumugam** [forem/forem#13002]
It's more kind of a feature here

I'm writing my post in dev.to , which is still in draft mode. Accidently I forget to click the save button the next day when I saw my yesterday's contribution was gone and the draft has only the version which I saved so earlier. 

It would be great if you can provide an auto-save feature for any draft version on the post. So that it won't be a big shock like me for others in the future!

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
