### ISSUE TITLE
Disable rule for no default exports in Storybook files

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#13031]
**Describe the bug**

While reviewing a PR with Storybook files, I notice the linter complaining about default exports in Storybook stories which are required in a story. We should keep the rule, but disable it for Storybook stories. As well, we can disable this rule for Stimulus controllers and remove the eslint disable comments for Stimulus controllers.

**To Reproduce**

For Storybook files:

1. Open a Storybook story file in your editor, e.g. VS Code that shows red lines under lint errors.
2. Open up any file ending in `.stories.jsx`
3. Go to the default export which is most likely near the start of the file and notice the editor complaining about a lint error for default exports.

**Expected behavior**

Default exports should still error out by the linter, but not for Storybook files or Stimulus controllers.

**Screenshots**

![image](https://user-images.githubusercontent.com/833231/111538727-6c08b280-8743-11eb-89ee-21d0ce9a9e9d.png)

![image](https://user-images.githubusercontent.com/833231/111541453-e5ee6b00-8746-11eb-84bb-9f22c9f4c4a7.png)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

N/A

**Additional context**

**Comment by rhymes** [comment]
@nickytonline is this solved by https://github.com/forem/forem/pull/13032 ?

**Comment by nickytonline** [comment]
@rhymes, it is. I forget to added the magic word "closes" in the PR.
