### ISSUE TITLE
Next Js badge looks bad / Suggestion

### ISSUE THREAD

**Issue by tuliocll** [forem/forem#13047]
**Describe the bug**
The nextjs badge has a white background.

**To Reproduce**
Open the badge page or see on my profile:
https://dev.to/badge/next-js
https://dev.to/tuliocalil

**Expected behavior**
A badge with transparent background.

**Screenshots**
![](https://i.imgur.com/9zxClKa.png)

I have two suggestion:
original logo.
![](https://i.imgur.com/BpdzRiX.png)

or with a white border (looks better).
![](https://i.imgur.com/d9g1iWZ.png)

[here is the logo with border link](https://imgur.com/a/EK9yyQl)

**Comment by cmgorton** [comment]
Thanks for the report. I will mention this to the design team. 🙂

**Comment by tuliocll** [comment]
so beautiful 😍
![image](https://user-images.githubusercontent.com/22357579/111907810-bc2e9000-8a35-11eb-919d-cc7d924a523c.png)
