### ISSUE TITLE
Fix language detection

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#1308]
**Describe the bug**
Our service for detecting what language a post is written is isn't working properly. How we serve the non-language posts is also broken so this entire feature needs to be fixed.

**Comment by alebruck** [comment]
Hello @jessleenyc, do you have examples of posts where the language detection failed?

Looks like the gem used for language detection([CLD](https://github.com/jtoy/cld)) is not active anymore, I would propose switching to a different solution.

**Comment by cmgorton** [comment]
@jessleenyc do you know if this is still an issue? I see this has be inactive for a long time.

**Comment by jessleenyc** [comment]
I'm not sure if this was ever addressed. @benhalpern would have a better idea.

**Comment by joshpuetz** [comment]
There is some possible overlap with https://github.com/forem/forem/pull/12103, as that PR is working on replacing the `cld` gem
