### ISSUE TITLE
Cannot use Home/End buttons while writing a message in Welcome thread

### ISSUE THREAD

**Issue by quantuumsnot** [forem/forem#13097]
After the registration decided to say hello in the Welcome thread, typed something and noticed that cannot move the cursor to the beginning or the end of the text with Home/End buttons

- OS, version: Win 8.1 x64
- Browser, version: Chrome x64 v87

**Comment by cmgorton** [comment]
This should be fixed with the above Revert PR and will soon be permanently fixed with https://github.com/forem/forem/pull/13126
