### ISSUE TITLE
Bio field is reflecting the Summary field data in Settings page

### ISSUE THREAD

**Issue by rna** [forem/forem#13119]
**Describe the bug**
When the user tried to edit the profile thru the settings page, the summary is getting updated in both bio and summary fields. But when the user updated the bio, that's not getting updated and it still shows the summary field data, irrespective of the success message.

**To Reproduce**
1. Visit the Profile Settings page
2. Try to change or fill the summary data and click on Save Profile Information
3. Now you can see, the user bio will reflect the summary field data
4. Also, try to change or fill the bio field data and click on Save Profile Information
5. Still, The user bio will reflect the same as summary field data.

**Expected behavior**
The summary and bio fields should update as it's own fields.

**Desktop :**

- OS, version: MacOS BigSur
- Browser, version: Chrome Version 89.0.4389.90 (Official Build) (arm64)

**Comment by rhymes** [comment]
As we discussed in https://github.com/forem/forem/pull/12633#issuecomment-805659850 I've assigned this to you @rna, thanks again 🙌

**Comment by mirie** [comment]
Removing assignment.

**Comment by mirie** [comment]
Also @lboogie04 not sure if these are related? https://github.com/forem/forem/issues/13084#issuecomment-1332597187 but if the PR addresses both, that would be good to note

**Comment by mirie** [comment]
@lboogie04 does it make sense to close as Won't Fix?
