### ISSUE TITLE
When I wanna edit my comment, the old content didn't shown

### ISSUE THREAD

**Issue by L4znet** [forem/forem#13127]
I don't know if it's a bug, or something desireed, but when I edit a comment, my previous comment didn't be displayed in the textarea field.

![image](https://user-images.githubusercontent.com/1903341/112478387-40ee1680-8d74-11eb-85ef-87e79f4fe2ab.png)

**Comment by mimatn** [comment]
I can confirm the bug. Happens to me, too. Setup: win10, firefox latest.

**Comment by cmgorton** [comment]
@nickytonline @aitchiss not sure if this is related to the recent changes with the autofill.

**Comment by cmgorton** [comment]
Oh looks like it is related! @L4znet Thanks for reporting this. It is a known issue from a new feature we added and will hopefully be resolved soon. 🙏

**Comment by nickytonline** [comment]
Fixed by #13116
