### ISSUE TITLE
[Web monetization] Payment pointer not updated

### ISSUE THREAD

**Issue by catalinpit** [forem/forem#13125]
**Describe the bug**

I was wondering for a while why I don't make any earnings with my Dev.To articles.

It seems that the payment pointer is not mine even though I set it to my pointer.

**Expected behavior**

It should be my payment pointer.

**Screenshots**

![screenshot-1](https://i.ibb.co/3ybk0gR/Screenshot-2021-03-25-at-10-44-33.png)
![screenshot-2](https://i.ibb.co/fdrh8xj/Screenshot-2021-03-25-at-10-44-25.png)

**Comment by rhymes** [comment]
Hi @catalinpit, I can't find any user in our DB with that other pointer, If I go to https://dev.to/catalinmpit I can see yours in the HTML:

<img width="1017" alt="Screenshot 2021-03-25 at 10 23 59 AM" src="https://user-images.githubusercontent.com/146201/112450071-46d3ff80-8d54-11eb-968c-c81f6b635fa8.png">

Can you verify?

**Comment by catalinpit** [comment]
I still don't see mine. I keep seeing `$ilp.uphold.com/24HhrUGG7ekn`.

Why would that happen on my end?

**Comment by spences10** [comment]
Can confirm it's the same on my posts with dev.to

![image](https://user-images.githubusercontent.com/234708/112603209-9a098900-8e0c-11eb-8f70-4a116213ba55.png)

**Comment by cmgorton** [comment]
Thank you both for bringing this up! Going to escalate this internally so we can try to fix this soon.

**Comment by nickytonline** [comment]
> I still don't see mine. I keep seeing `$ilp.uphold.com/24HhrUGG7ekn`.
> 
> Also, I don't really care about the profile page as not many visit it. I care about the pointer in the articles because that's what people read.
> 
> I also asked other people to verify to make sure it's not just me. They see the same pointer.

Hi @catalinpit. I'm looking into this and the pointer you mentioned doesn't render. I'm seeing, your payment pointer. This is what I pulled out of your site, `"wmPaymentPointer":"$ilp.uphold.com/gjKDYDabPeeB"` and this is what I'm seeing on DEV.

![image](https://user-images.githubusercontent.com/833231/112886537-110a8000-90a0-11eb-9ed7-5fb1d7f767bd.png)

Let me know if you're still experiencing issues.

**Comment by nickytonline** [comment]
Alright I have the full picture, now. If you view the page source, the payment pointer rendered is the one for DEV.

Below is the view page source from https://dev.to/spences10/build-a-coding-blog-from-scratch-with-gatsby-and-mdx-2h31.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Build a coding blog from scratch with Gatsby and MDX - DEV Community 👩‍💻👨‍💻</title>
      <meta name="last-updated" content="2021-03-29 19:08:14 UTC">
      <meta name="user-signed-in" content="true">
      <meta name="head-cached-at" content="1617044894">
        <!-- Experimental web monetization payment pointer for micropayments -->
        <!-- It lets readers make micropayments to websites they visit. -->
        <!-- This is step 1: Get live in production to test for platform-wide payment pointer. -->
        <!-- Step 2: Allow authors to set their payment pointer so they can directly monetize their content based on visitors. -->
        <!-- Step 3: Enable further functionality based on what we learn from this experimentation and how the ecosystem evolves. -->
        <meta name="monetization" content="$ilp.uphold.com/24HhrUGG7ekn">
      <meta name="environment" content="production">
...
```

So my first question is, did you view source or inspect the page in the browser dev tools @spences10 @catalinpit ?

Next up, we have this function that runs when a page loads

https://github.com/forem/forem/blob/64c28c6c2c619d4b24ed7a07481ee5a5c6809cc7/app/assets/javascripts/initializers/initializePaymentPointers.js#L1-L11

So what happens is if you are on a user's page or their content, the payment pointer gets updated. Here it is in action.

https://user-images.githubusercontent.com/833231/112887817-9cd0dc00-90a1-11eb-9a75-29436fd25712.mp4

So from what I can tell, things are behaving properly, but I'm not sure how the payment pointers are read. I'm assuming that it can detect changes on the client-side. cc: @citizen428 as I noticed you worked on some of this according to git.

On a side note, I've got a payment that has been pending for at least a week, maybe longer. Just mentioning that in case there's issues in the Interledger network.

**Comment by citizen428** [comment]
@nickytonline I remember being confused about this once myself. To be honest I never quite had time to dig into this as I only restructured the code, I didn't originally implement it. You're correct that we're performing some JS switcheroo here and I think these client-side changes should be detected, Web Monetization is a JS API after all.

**Comment by spences10** [comment]
@nickytonline yah, view source:

```html

<html lang="en">
--
  | <head>
  | <meta charset="utf-8">
  | <title>Build a coding blog from scratch with Gatsby and MDX - DEV Community 👩‍💻👨‍💻</title>
  | <meta name="last-updated" content="2021-03-31 14:29:17 UTC">
  | <meta name="user-signed-in" content="true">
  | <meta name="head-cached-at" content="1617200957">
  | <!-- Experimental web monetization payment pointer for micropayments -->
  | <!-- It lets readers make micropayments to websites they visit. -->
  | <!-- This is step 1: Get live in production to test for platform-wide payment pointer. -->
  | <!-- Step 2: Allow authors to set their payment pointer so they can directly monetize their content based on visitors. -->
  | <!-- Step 3: Enable further functionality based on what we learn from this experimentation and how the ecosystem evolves. -->
  | <meta name="monetization" content="$ilp.uphold.com/24HhrUGG7ekn">
  | <meta name="environment" content="production">
  | <link rel="stylesheet" media="all" href="https://dev.to/assets/minimal-ceb46d3c51f19ac8dfd9eb352c6793202a11e0bd8eca02896d069ba999778b00.css" id="main-minimal-stylesheet" />
  | <link rel="stylesheet" media="all" href="https://dev.to/assets/views-4300239712540c4615e04151e1decbed367cf7f012f4967ef4341f465d350da0.css" id="main-views-stylesheet" />
  | <link rel="stylesheet" media="all" href="https://dev.to/assets/crayons-db346751d21e011e9b30fd24fe1d06dc1cc327df0e3630be6a60c2d869007582.css" id="main-crayons-stylesheet" />
```

So the `monetization` meta tag is used not for my pointer but the one detailed in the above snippet.

My pointer (`$ilp.uphold.com/bzPBWkMBzLmN`) is in there but not with a `monetization` meta tag:

```html
<div id="base-payment-pointer" data-payment-pointer="$ilp.uphold.com/24HhrUGG7ekn"></div>
  | <style>.app-shell-loader {display: none;}</style>
  | <div id="page-content" class="wrapper stories stories-show" data-current-page="stories-show">
  | <div id="page-content-inner">
  |  
  | <div id="author-payment-pointer" data-payment-pointer="$ilp.uphold.com/bzPBWkMBzLmN"></div>
  |  
```

**Comment by nickytonline** [comment]
@spences10, if you watch the video I attached, you'll see that the inspected DOM (not view page source) shows the updated meta tag with a community member's payment pointer. It does this by reading the payment pointer data attribute in the markup snippet you shared via the `initializePaymentPointers()`.m function.

**Comment by cmgorton** [comment]
Thank you for diving in to this Nick. @catalinpit @spences10 if you look at the video Nick posted you will see things are actually behaving properly so I am going to go a head and close this issue.
