### ISSUE TITLE
UX/UI feedback on article draft share options

### ISSUE THREAD

**Issue by fralps** [forem/forem#13134]
**Describe the bug**
-
When user click on the three dots in order to share article draft the content is hidden behind the navbar. This occurs on web and PWA installed on macOS.
See screenshot below ⬇️ ⬇️ ⬇️  

**To Reproduce**
-

1- Write an article
2- Save as a draft
3- And open the share options

**Expected behavior**
-

User should be able to see all the share options

**Screenshots**
-

![Capture d’écran 2021-03-25 à 12 11 34](https://user-images.githubusercontent.com/48285890/112525353-1a92a000-8da1-11eb-9230-0cd80a55d1c9.png)

**Desktop (please complete the following information):**

- OS, version: macOS 11.2.3
- Browser, version: Chrome 89

**Smartphone (please complete the following information):**

It works fine on mobile devices

Thanks guys 🤩

**Comment by aitchiss** [comment]
Closing as I believe this was fixed by #14236 where the dropdown was changed to always show below the three dots button 🎉
