### ISSUE TITLE
Comment templates not inserting as expected

### ISSUE THREAD

**Issue by ellativity** [forem/forem#13171]
**Describe the bug**
When inserting a moderator template response into a comment (not selecting `Send as Mod`), no text appears in the comment text box. 

When attempting to insert the response again, users are prompted `Are you sure you want to replace your current comment draft?` (there is no current text).

**To Reproduce**
1. Log in as a tag moderator
2. Scroll to the Discussion of any article and create a new comment
3. Select `Templates` 
4. Select a `Moderator` template and click `Insert'

Repeat to view dialogue box

**Expected behavior**
Usually, template text appears in the comment text box, which can be edited or posted as-is.

**Screenshots**
![Screenshot 2021-03-29 at 17 11 03](https://user-images.githubusercontent.com/76786132/112860993-ab74be80-90b4-11eb-847b-7f0766370e96.png)
![Screenshot 2021-03-29 at 17 11 27](https://user-images.githubusercontent.com/76786132/112860999-aca5eb80-90b4-11eb-8857-3375ad6e2ae5.png)
![Screenshot 2021-03-29 at 17 11 41](https://user-images.githubusercontent.com/76786132/112861003-add71880-90b4-11eb-9daa-16083a2f82c2.png)

**Desktop (please complete the following information):**

- OS, version: MacOS Mojave 10.14.6
- Browser, version: Chrome Version 89.0.4389.90

**Additional context**
This was first reported by a community moderator and I was able to replicate (see screenshots).

**Comment by cmgorton** [comment]
Thanks for reporting! I think this is a known issue. @nickytonline is this PR related? https://github.com/forem/forem/pull/13149

**Comment by ellativity** [comment]
Oops, yep, looks exactly the same. Mb!

**Comment by nickytonline** [comment]
It's the same issue. The fix is ready, just needs to be reviewed.
