### ISSUE TITLE
Text not clearing after submission of top-level comment

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#13175]
**Describe the bug**

After submitting a top level comment, the text is not cleared away from the composer.

**To Reproduce**

- Visit an article
- Leave tp-level comment
- Observe that text is still in the comment box.

**Expected behavior**

Text should clear upon submission.

**Comment by benhalpern** [comment]
I put this in support tasks, but maybe something to be aware of during ongoing work on this area @nickytonline @aitchiss ?

**Comment by nickytonline** [comment]
This should be fixed by #13149.

**Comment by benhalpern** [comment]
Ah great stuff @nickytonline
