### ISSUE TITLE
Button text doesn't update after submitting comment from Preview

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#13182]
**Describe the bug**

When commenting on a post, if I submit the comment from the "Preview", then start to add another comment, the text on the 'Preview' button still reads "Continue editing" (even though the correct action takes place if I click it).

NB: I have done a bit of time travelling in the git history and can confirm this issue existed before any of the autocomplete work was added to comments.

**To Reproduce**

- View an article
- Start adding a comment
- Click on 'Preview'
- While viewing your preview, click 'Submit' to submit the comment
- Start adding a new comment
- Notice the button says "Continue editing" instead of "Preview"
- Click the 'Continue editing' button 
- Notice it does show you the Preview, it's just the text is wrong

**Expected behavior**

When I add a new comment, the 'Preview' button should always say 'Preview'.

**Screenshots**

https://user-images.githubusercontent.com/20773163/112971048-be37d380-9146-11eb-8d07-0deb77602783.mp4

**Comment by Rafi993** [comment]
Hi there, if this bug is not worked on I can help.

**Comment by cmgorton** [comment]
Sure @Rafi993 !  I will assign it to you. Thank you.

**Comment by ppalone** [comment]
Will this fix it?
https://github.com/forem/forem/blob/2534a8aa5fa5a647bcdc4605c6bf719a360fbcde/app/assets/javascripts/initializers/initializeCommentsPage.js.erb#L270-L272
```js
var preview = document.getElementById("preview-div");
+ var togglePreview = document.getElementsByClassName('preview-toggle')[0];
preview.classList.add("preview-toggle");
preview.innerHTML = "";
+ togglePreview.innerHTML = "Preview";
```

**Comment by Rafi993** [comment]
> Will this fix it?
> https://github.com/forem/forem/blob/2534a8aa5fa5a647bcdc4605c6bf719a360fbcde/app/assets/javascripts/initializers/initializeCommentsPage.js.erb#L270-L272
> 
> ```js
> var preview = document.getElementById("preview-div");
> + var togglePreview = document.getElementsByClassName('preview-toggle')[0];
> - preview.classList.add("preview-toggle");
> preview.innerHTML = "";
> + togglePreview.innerHTML = "Preview";
> ```

Thank you @ppalone the fix worked.
