### ISSUE TITLE
Markdown not processing correctly

### ISSUE THREAD

**Issue by maarteNNNN** [forem/forem#13189]
```js
// HTTP request handling loop.
(async () => {
  for await (let requestData of httpServer.listener('request')) {
    expressApp.apply(null, requestData);
  }
})();
```
is processing as this
![image](https://user-images.githubusercontent.com/14275291/113036346-8cd0ff00-916a-11eb-9bc3-8a0f9cce3433.png)

```js
for await (let { socket } of agServer.listener('connection')) {
...
  for await (let request of socket.procedure('test')) {
    console.log(request.data);
    request.end({ message: 'Data received, thanks client!' });
  }
...
}
...
```

is processing as this:
![image](https://user-images.githubusercontent.com/14275291/113036381-9b1f1b00-916a-11eb-84f2-a0d59343db66.png)

- OS, version: Ubuntu 20.10
- Browser, version: Brave v1.22.70

link to the draft: https://dev.to/maartennnn/socketcluster-the-most-underrated-framework-o7l-temp-slug-638306?preview=e9c463240309a14ee845454288c4bdfec0f2425dadcb1faf03500beea192f4bfdf8c524cc465683c5991a002d8e8a130198ac13a6e32519944742e4c

**Comment by cmgorton** [comment]
Hey @maarteNNNN.  This is actually a little error in your article. If you remove the lone backtick in your quote after the word SocketCluster your code blocks work fine. 
![Screen Shot 2021-03-30 at 12 45 18 PM](https://user-images.githubusercontent.com/21039864/113040304-e1b64a80-9155-11eb-8425-1f916ae03639.png)

Can you please confirm for me that this works on your end once the backtick is removed?

**Comment by maarteNNNN** [comment]
It worked! I went over it a couple of times but I didn't see anything wrong, It worked in my editor and GitHub. I'm so sorry! Thank you!

**Comment by cmgorton** [comment]
No worries @maarteNNNN. This has come up before so I knew what to look for. 😄
Thank you for confirming and closing the issue!
