### ISSUE TITLE
Modal appears under the navbar

### ISSUE THREAD

**Issue by aurelieverrot** [forem/forem#13195]
**Describe the bug**

The modal triggered by the three dots on the left of an article appears stuck under the navbar of the website, it is not readable entirely.

**To Reproduce**

After submitting an article but before publishing.
Click on the three dots on the top left of the article.
The modal will show up but a part of it is hidden behind the navbar

**Expected behavior**

The modal should appear entirely to see all the links.  It can appear under the navbar, or on top of it.

**Screenshots**

![image](https://user-images.githubusercontent.com/50857179/113064409-c6eed080-916b-11eb-80a0-9425a733ac65.png)

**Desktop (please complete the following information):**

- OS, version: MacOS Catalina 10.15.7
- Browser, version: Chrome Version 88.0.4324.192 (Official Build) (x86_64)

**Additional context**
button id="article-show-more-button"

**Comment by Link2Twenty** [comment]
Adding z-index 100 to `crayons-layout__sidebar-left` would fix the overlay issue (though the dropdown still goes off the screen) but I think there should be logic added to `crayons-dropdown` to detect if the element goes off screen and reposition it accordingly.

**Comment by nickytonline** [comment]
Related to this issue is the member navigation menu renders under banners.

![image](https://user-images.githubusercontent.com/833231/113338482-2a593980-92f7-11eb-8943-973d5e7a8500.png)

The banner has a `z-index: 100;`, whereas the member menu has a `z-index: 400;`. This leads me to believe it's not just a z-index issue but also relates to [stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

**Comment by jgaskins** [comment]
@nickytonline I think you're right. The popover has `z-index: 100`, but its great-grandparent element has `z-index: 1`.

![screenshot of the DOM structure and style properties of the menu dropdown](https://user-images.githubusercontent.com/108205/113931601-ab657480-97c0-11eb-8685-ca55a4140460.png)

If I'm reading the link you posted correctly, it looks like the `z-index` of the descendant element is relative only to other elements underneath the ancestor with a `z-index`, which very much seems to align with what's going on here, and when I manually set the `z-index` of the ancestor element to something higher than that of the header (which is what I believe is what @Link2Twenty pointing out) it does work.

**Comment by DevCoder0x0** [comment]
I would like to take this issue.

**Comment by cmgorton** [comment]
Great! Assigning it to you now. Thanks for helping out. let us know if you have any questions!

**Comment by DevCoder0x0** [comment]
Hello Christina, I am very sorry but I will not be able to complete that
task. Unfortunately something came up and I am not going to have any free
time for the next few weeks. Good luck to you and everyone who contributes.
I am a huge fan!

**Comment by noviicee** [comment]
I cannot find the file to which the changes are to be made. Can anybody help me..?
I believe I can do this one.

**Comment by msarit** [comment]
@noviicee Hey Anamika! 👋🏾 

Instead of just answering your question, I thought it might be helpful to show you how I went about finding the relevant page(s).

Here is the video: https://www.loom.com/share/616d4af69fb84ebe8d7f25c2ddb3b809

Please reach out to us if you need more support. Thank you for contributing to Forem! ❤️ 

cc: @cmgorton

**Comment by noviicee** [comment]
> @noviicee Hey Anamika! 👋🏾
> 
> Instead of just answering your question, I thought it might be helpful to show you how I went about finding the relevant page(s).
> 
> Here is the video: https://www.loom.com/share/616d4af69fb84ebe8d7f25c2ddb3b809
> 
> Please reach out to us if you need more support. Thank you for contributing to Forem! ❤️
> 
> PS: the file I identified in the video is `app/views/articles/show.html.erb`
> 
> cc: @cmgorton

Hey! Thanks a lot!!

**Comment by noviicee** [comment]
I am able to setup forem locally on my machine. But, I am unable to login to the local dev.to. What needs to be done in this case..?
I am using ubuntu 20.04  and on using github to login to Dev(local), It redirects to: [here](https://github.com/login/oauth/authorize?client_id=Optional&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fauth%2Fgithub%2Fcallback&response_type=code&scope=user%3Aemail&state=62cb1391639629c35bfb0d9f863b81b6149af7093b1dc462)

**Comment by rhymes** [comment]
@noviicee by inspecting the link I think what's missing is the correct setup of the GitHub credentials in the `.env` file.

You can find the necessary details here: https://docs.forem.com/backend/auth-github/

**Comment by noviicee** [comment]
> @noviicee by inspecting the link I think what's missing is the correct setup of the GitHub credentials in the `.env` file.
> 
> You can find the necessary details here: https://docs.forem.com/backend/auth-github/

okay. Trying to do that!

**Comment by noviicee** [comment]
> > @noviicee by inspecting the link I think what's missing is the correct setup of the GitHub credentials in the `.env` file.
> > You can find the necessary details here: https://docs.forem.com/backend/auth-github/
> 
> okay. Trying to do that!

I did that and it's still the same. I added the client id and client key in the .env file as mentioned, re-run the container setup, just in case it was needed, but still not able to login.
Btw, I am running Forem with Docker via docker-compose -> [**link**](https://docs.forem.com/installation/containers/#running-forem-with-docker-via-docker-compose)

**Comment by maestromac** [comment]
@noviicee do you mind wiping your database and try signing up again and let us know the exact error you are seeing?

**Comment by veerreshr** [comment]
Hello, **If someone is not working on this, I would like to work on this.**
This is what I have analyzed:

1. This is only occurring for device sizes with resolution more than 768px width
2. One fix could be to show dropdown in the downward direction for devices width more than 768px

I have added 2 **utility classes**(not custom css) to the element's class, this is how its looking on making the dropdown downwards
![image](https://res.cloudinary.com/dcgefz04y/image/upload/v1626096101/Screenshot_288_ut6wmm.png)

Few alternative ways I could apply the fix

- Make dropdown work same way for both draft page and non draft article view
- Make the changes only to draft view and let non draft view appear the same as before

If changes are only for draft page, this is how it could look (just change in position of modal):
![image](https://res.cloudinary.com/dcgefz04y/image/upload/v1626096280/Screenshot_289_lyoeoz.png)


If we apply dropdown changes to even non draft pages, this is how it may look

![image](https://user-images.githubusercontent.com/59141533/125290942-79732980-e33e-11eb-82f0-c1f1aa977d6e.png)

I need a confirmation on which alternate way should I proceed if given a chance to work on this issue.

**Comment by cmgorton** [comment]
Thank you for offering to work on this @veerreshr and all of your great suggestions. We are asking our product team their thoughts on your suggestions and will let you know which one they think you should go with.

**Comment by cmgorton** [comment]
@veerreshr I am going to assign you to this issue. Our product team said they like the solution you have proposed. And out of the options they "think the left-most solution works for what should be accomplished here".

**Comment by veerreshr** [comment]
Hey I am having trouble setting up forem locally. I am using Ubuntu 20.04.2 LTS and I tried setting up using docker compose. 
Error is something related to authorizing the admin, I am not sure what to do here, could some one help me in setting up.
![Screenshot from 2021-07-13 04-20-31](https://user-images.githubusercontent.com/59141533/125365787-84f04000-e392-11eb-98a3-e60595e6ed5a.png)

**Comment by jgaskins** [comment]
@veerreshr If you're able to bring up a Rails console, you can run `User.first.add_role(:super_admin)` to give your user account access to everything

**Comment by veerreshr** [comment]
thanks @jgaskins , Now I am able to set it up and running. Now I am left with few more douts? should I implement the feature so it only effects the draft page. What I mean is, the dropdown is common for both draft articles and non draft articles, so if I change the dropdown layout, it will change for both draft and non draft articles. **Should I change it only for draft pages(can be achieved with a small tweak)? or for both?**

This is how it looks when changes are applied to both draft and non draft articles 
**Draft Article :**
![Screenshot from 2021-07-14 06-37-27](https://user-images.githubusercontent.com/59141533/125544868-870f6008-e7fd-4065-b658-6cc98bb7fa66.png)
**Non Draft Article:**
![Screenshot from 2021-07-14 06-37-07](https://user-images.githubusercontent.com/59141533/125544860-f2dab182-1f1a-4a85-8d11-746c382185d2.png)

**Should I proceed to apply changes for both the pages? or just for draft page?** and sorry if I am asking too many questions 😅.

**Comment by veerreshr** [comment]
@cmgorton @rhymes please look into the above confusion

**Comment by rhymes** [comment]
@veerreshr I think it's necessary for both! I don't think there's a distinction in the CSS between the two types of posts
