### ISSUE TITLE
Analytics: Infinity time window produces JS error in Safari

### ISSUE THREAD

**Issue by jaredcwhite** [forem/forem#13217]
I'm trying out the new Analytics feature for my account jaredcwhite on Dev.to. The Week and the Month time windows work fine, but when I select Infinity, I get a "RangeError: Invalid Date" error. The offending code seems to be `toISOString` in this block:

```js
function callAnalyticsAPI(path, date, { organizationId, articleId }, callback) {
  let url = `${path}?start=${date.toISOString().split('T')[0]}`;
```

This is when using Safari for Big Sur, Version 14.0.2 (16610.3.7.1.9)

I logged in with Firefox 87 and Infinity does work there.

**Comment by jgaskins** [comment]
@jaredcwhite @cmgorton I found the bug. We count April 1, 2019 as the beginning of time, but [it's specified as `2019-4-1`](https://github.com/forem/forem/blob/e3ff582c993255a11641e5f50692fd782be14833/app/javascript/analytics/dashboard.js#L226). I tested this expression in Firefox and and it works. It seems to have permissive datetime string parsing. However, Safari's appears to more strictly adhere to [the ECMAScript standard](https://262.ecma-international.org/11.0/#sec-date-time-string-format) for it.

<img width="330" alt="Examples of the broken JavaScript date expression and the fix" src="https://user-images.githubusercontent.com/108205/113617563-78867980-9624-11eb-8a75-43448d74a350.png">

PR incoming with the fix.
