### ISSUE TITLE
`/new` composer page broken on iOS

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#13223]
**Describe the bug**

The composer page is broken in iOS... Noticed on Safari and within Forem app

**To Reproduce**

- Visit DEV on mobile
- Sign in
- Go to top-left menu and select "Write a Post"

**Expected behavior**

Page should load properly

**Screenshots**

Safari:

![Image from iOS](https://user-images.githubusercontent.com/3102842/113311171-0259de00-92d7-11eb-9976-f457afd1c559.png)

Within Forem app webview:

![IMG_0045](https://user-images.githubusercontent.com/3102842/113311327-303f2280-92d7-11eb-9c5d-91a73fb3b47f.jpeg)

**Smartphone (please complete the following information):**

Observed by multiple iPhones.

Mine is v 14.4.2 and Forem app build 39.

**Additional context**

- This is not present on Forems that are not on the edge build (aka have not been deployed yet)
- Composing a post on DEV on mobile is most definitely not _primary behavior_ so we won't get as many reports on this as if it were desktop-wide.

**Comment by nickytonline** [comment]
Going to look at this. It looks like an infinite redirect loop, but not sure what's causing it yet.

**Comment by nickytonline** [comment]
I'm digging into this and it looks like some JS might be lopping for some reason as I do not see infinite redirects happening in the devtools when connected to my iPhone. 🤔

Not sure if it's related, but the file `https://unpkg.com/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js` is unable to load on iPhone for some reason. I also noticed that that file does not load on desktop. cc: @fdoxyz 

![image](https://user-images.githubusercontent.com/833231/113333827-f11dcb00-92f0-11eb-87b4-05056f315c16.png)

**Comment by nickytonline** [comment]
It also looks like Google Analytics is throwing, but this might tracking protection on WebKit.

![image](https://user-images.githubusercontent.com/833231/113334437-b0728180-92f1-11eb-9051-01ca4782ab98.png)

**Comment by fdoxyz** [comment]
@nickytonline I'm not seeing that error related to `https://unpkg.com/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js`. I think that you could be seeing that because the webpage crashed before being able to fetch it and not necessarily because it's related to this problem, maybe?

I do see the following error in the console (though at first glance it doesn't seem related either):

<img width="779" alt="Screen Shot 2021-04-01 at 10 59 20" src="https://user-images.githubusercontent.com/6045239/113337302-d5142c80-92e4-11eb-8b02-79e6f5c36596.png">

In an attempt to narrow the source of this down I did a checkout of `master` before and after #13101 was merged and it does seem like the problem was introduced there. Maybe there's some sort of incompatibility with webkit on iOS?

**Comment by nickytonline** [comment]
I did some more digging and this appears to only affect the v2 editor on iOS Webviews. Stil investigating.

**Comment by nickytonline** [comment]
Alright, I did some digging and it looks like it's a race condition of some sort. If I add a `debugger` statement and it pauses the Safari debugger for my local Forem running on my iPhone, it works. Just digging into what that race condition is.

**Comment by nickytonline** [comment]
So the culprit is https://github.com/forem/forem/blob/95571df8b31c9d4b37a0d0dcd73724f7f2b668c0/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx#L320-L332 when it's loaded right away in Safari/Webviews on iOS.

Getting closer. 😎

**Comment by nickytonline** [comment]
So the real issue @aitchiss is when the component gets focus. Adding a `setTimeout` to do the focus fixes the issue, but seems like a bandaid solution. Maybe good enough for now. For the editor, it keeps the focus even with the `setTimeout`, but for the comments, it causes the element to lose focus on the first focus.

https://github.com/forem/forem/blob/009c14653ab84da91cf278400350503e056bef29/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx#L198-L199

https://github.com/forem/forem/blob/009c14653ab84da91cf278400350503e056bef29/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx#L302-L305

**Comment by aitchiss** [comment]
> So the real issue @aitchiss is when the component gets focus. Adding a `setTimeout` to do the focus fixes the issue, but seems like a bandaid solution. Maybe good enough for now. For the editor, it keeps the focus even with the `setTimeout`, but for the comments, it causes the element to lose focus on the first focus.
> 
> https://github.com/forem/forem/blob/009c14653ab84da91cf278400350503e056bef29/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx#L198-L199
> 
> https://github.com/forem/forem/blob/009c14653ab84da91cf278400350503e056bef29/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx#L302-L305

It's interesting that this problem doesn't surface in the comments area, given the manual focusing still happens there 🤔 
I guess in the case where we don't have a "replaceElement" we actually don't need to focus on line 304 - since the plain text area is presented from the get-go, and the user has clicked into it?

**Comment by benhalpern** [comment]
@nickytonline @aitchiss I see that there is an _autofocusing_ happening on `/new` on page load which is different than the comment area, where nothing is focused _right on page load_. Maybe that is a difference?

Either way, I'd definitely be cool with a bandaid for now if we aren't very close to figuring it out.

**Comment by JaneJeon** [comment]
+1 for a quick bandaid patch to deploy, I’m totally biased because I use an ipad as daily driver and I can’t write on dev.to xP

**Comment by nickytonline** [comment]
> +1 for a quick bandaid patch to deploy, I’m totally biased because I use an ipad as daily driver and I can’t write on dev.to xP

I even do post s on my iPhone sometimes. 🙃 Gonna see about getting this resolved tomorrow. 😎
