### ISSUE TITLE
Changing size of textarea outside its bounds.

### ISSUE THREAD

**Issue by abenerd** [forem/forem#13230]
**Describe the bug**
When changing the width of a textarea outside of its wrapping component it changes the width of the other inputs inside the same box and they can all move outside their wrapping component. 

**To Reproduce**

Go to: https://<forem instance>/settings
Change width of textarea input

**Expected behavior**
To be constrained to the bounds of my wrapping component. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7523903/113408132-1a049580-93af-11eb-92f9-6b45dc5b0da5.png)

**Desktop (please complete the following information):**

- OS, version: Linux Manjaro
- Browser, version: Firefox 87.0

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by Link2Twenty** [comment]
I think there are 2 solutions for this either,  set a `max-width` on the text area which would have to be calculated or lock resize to vertical `resize: vertical;` which might be a better solution.

**Comment by Freshchris01** [comment]
I'd like to work on this issue :slightly_smiling_face:
