### ISSUE TITLE
Title box on /new view is too high (by default)

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#13268]
**Describe the bug**

The title field on /new view is supposed to be autoresized depending on its content. So by default it should be _1 line_ height but it's 2 lines at the moment. It's likely this is due to some [update](https://github.com/forem/forem/pull/13234) we've just introduced. 

**To Reproduce**

1. Go to `/new`
2. See title field being taller than one line of text.

**Expected behavior**

Default height should be equal to 1 line of text.

**Screenshots**

n/a

**Desktop (please complete the following information):**

- OS, version: macOS latest
- Browser, version: Chrome latest.

**Comment by ludwiczakpawel** [comment]
cc @aitchiss

**Comment by aitchiss** [comment]
woops! thanks @ludwiczakpawel - I'll take a look at this
