### ISSUE TITLE
Reduce HTML errors

### ISSUE THREAD

**Issue by jmau111** [forem/forem#13289]
**Describe the bug**

Multiple HTML errors

**To Reproduce**

Use the w3c validator to validate HTML: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev.to%2F

**Expected behavior**

no error

With this PR https://github.com/forem/forem/pull/13288 some of those HTML errors could be fixed. There are still errors that can be tricky to resolve.

I've noted this one 👍🏻 

> Error: An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.

> From line 1120, column 88; to line 1120, column 494

> r-pack-1"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--pVCMYZWJ--/c_limit%2Cf_auto%2Cfl_pr…ntent-lga3-1.cdninstagram.com" style="margin-top:15px;border:1px solid transparent;" loading="lazy"></a><h

but it looks like it's a dynamic HTML widget, there's a missing alt on img

**Comment by cmgorton** [comment]
Hey thanks for your help here! With the PR merged would you consider this closed @jmau111 ?

**Comment by jmau111** [comment]
Hi, you're welcome. In short, I'd say no.

In details, the PR does not remove all HTML errors, just some of them, like a "safe remove" with no unwanted side effects. I think the missing alt can be fixed directly in the admin interface, as far as I know, it's like a dynamic widget.

I'm not sure I fully understand the defer attribute on inline scripts, as it's for external js only. I'm afraid removing them would introduce some bugs.

**Comment by jmau111** [comment]
I will send some PRs to remove other errors @cmgorton

**Comment by jmau111** [comment]
https://github.com/forem/forem/issues/13389

**Comment by jmau111** [comment]
https://github.com/forem/forem/pull/13407

**Comment by jmau111** [comment]
@aitchiss Hello, I don't know if you can access to this widget, the `img` tag inside misses  an `alt` attribute. I can't find it in the source code so I think it's manually inserted.

Can you modify it easily?

``` 
<img src="https://res.cloudinary.com/practicaldev/image/fetch/s--pVCMYZWJ--/c_limit%2Cf_auto%2Cfl_pr…ntent-lga3-1.cdninstagram.com" style="margin-top:15px;border:1px solid transparent;" loading="lazy">
```

<img width="280" alt="widget-forem-error-html" src="https://user-images.githubusercontent.com/6878027/122096546-f928d980-ce0e-11eb-803e-c0f84563ff48.png">

**Comment by aitchiss** [comment]
@jmau111 I think an admin on DEV will have access to this - I'll find out and get it updated!

**Comment by jmau111** [comment]
@aitchiss thanks a lot. There might be multiple widgets in this case.

**Comment by jmau111** [comment]
<img width="860" alt="screen-dev-home" src="https://user-images.githubusercontent.com/6878027/125057139-34829500-e0a9-11eb-89ac-b0e47cdcd0c0.png">

@aitchiss @nickytonline  Hello, there are some issues with those widgets, but it cannot be controlled with the codebase. It's manual HTML, so it may appear from time to time, depending on the widget's content.

Most of HTML errors in codebase have been fixed now \o/. An error with `<style>` inside body remains, but I think I have the time to fix it. Maybe I'm wrong, but it looks like a big PR to do, and I'm not sure it's worth it. Fixing wrong tag or markup can have little impact, e.g. for accessbility, but inline styles inside `<body>` is palatable I guess.

If that's ok for you, and HTML errors can be fixed inside manual HTML widgets, I think we can close this issue.

I will contribute this PR https://github.com/forem/forem/issues/13389

**Comment by aitchiss** [comment]
That's awesome @jmau111! Nice work!

I see what you mean about the `<style>` error - I agree it might be a little involved and our efforts might be better spent elsewhere. Happy to leave this for now.

I've raised the issue around the ad widgets internally so hopefully we'll see those errors reduce in due course too 😄  

Thanks for all of your work on this issue - great to see it looking so much better ✨

**Comment by jmau111** [comment]
great @aitchiss I think it's there for widgets (display_ads): 
<img width="274" alt="widgets-admin" src="https://user-images.githubusercontent.com/6878027/125068533-e031e200-e0b5-11eb-83ae-8ec9dab08395.png">
