### ISSUE TITLE
Tab layout shift

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#13296]
**Describe the bug**
When a `crayon-tab` becomes active it sets its text to bold, this causes the size of its container to change and things to shift around. When this coincides with a page reload you can't really notice but on analytics (where this change is triggered by JS) you can see the shift.

**To Reproduce**
- Go you [analytics}(https://dev.to/dashboard/analytics)
- Click around on the tabs
- See them shift slightly

**Expected behaviour**
There should be no shift

**Screenshots**
![dev__bold--shift](https://user-images.githubusercontent.com/3534427/113883880-7522f780-97b6-11eb-8fba-0defe4c9035e.gif)

**Potential solution**
We can fake bold by doing something like this.

```scss
.crayons-tabs__item--current {
  text-shadow: 0 0 0.075em currentColor;
}
```
I don't think this causes and A11y issues (CC: @aitchiss)

And the result, I think, looks almost identical just without the jumping about.

![dev__bold--fake](https://user-images.githubusercontent.com/3534427/113884268-bd421a00-97b6-11eb-9e52-22ccee4e5a1c.gif)

**Desktop (please complete the following information):**

- OS, version: windows 10
- Browser, version: Chrome 89.0.4389.114

**Additional context**
This probably doesn't both anyone but it just feels like something that is easy to fix and adds a layer of polish.

**Comment by cmgorton** [comment]
Thanks @Link2Twenty . I think this is something worth fixing and I like your suggestion. Is this something you would want to work on?

**Comment by cmgorton** [comment]
If you have time and want to then go for it! We always appreciate your contributions @Link2Twenty. 
I can assign it to you for now. If you can't get to it just let me know and we can unassign you :)
