### ISSUE TITLE
Display view/reaction/follower increases on the dashboard page

### ISSUE THREAD

**Issue by james-wallis** [forem/forem#13299]
Hopefully, this is the right place for this.

This feature request was sparked by [a comment](https://dev.to/madza/comment/1d74g) on [one of my posts](https://dev.to/jameswallis/i-built-a-dev-to-analytics-dashboard-to-track-historic-post-data-2c7o). I've recently completed implementing my own Dev.to analytics dashboard by creating a store of historical data in Azure Cosmos DB.
My take: https://devto-analytics.wallis.dev/

## Overview stats
It'd be great if Dev.to users were able to see stat increases in the overview stats on the dashboard page. Such as:
* Page view / reaction increase over the past 24 hours, 7 days and 30 days
* Comment increase over the past 7 days and 30 days
* Follower increase over the past 24 hours, 7 days and 30 days
* Number of posts published in the past 30 days / current weekly streak (which would partially resolve https://github.com/forem/forem/issues/9210)

Something like:
![overview stats](https://user-images.githubusercontent.com/17385115/113885315-a8b25180-97b7-11eb-9366-42bdfc035cea.png)

## Individual post stats
Additionally, it would be good to see the view, reaction and comment increases for each post again over a 24 hour, 7 days and 30 day period.

I'm aware that we're able to see stats for an individual post using the `stats` option that has been added next to `edit` and `manage` - this is a great addition btw. However, IMO adding it to the main dashboard screen will increase the analytics usability as users will able to see the changes at a glance.

Something like:
![post stats](https://user-images.githubusercontent.com/17385115/113885536-d5666900-97b7-11eb-91a9-26013c1e24f2.png)

## Other

This is sort of an aside (might be another issue entirely). If a view/reaction increase breakdown could be added to the https://dev.to/dashboard/analytics page that would help users understand what posts have been most popular for a given day.

I attempted to implement this feature on my Dev.to analytics dashboard but it became a bit messy when there are lots of posts: https://devto-analytics.wallis.dev/graphs/breakdown

![breakdown graph](https://user-images.githubusercontent.com/17385115/113887716-a4873380-97b9-11eb-8c31-efdba3f7d1a3.png)

Thanks for taking the time to read this request.

**Comment by madzadev** [comment]
I second this, would love to see Dashboard features extended! 😉

**Comment by cmgorton** [comment]
Hey all, we have a newer policy where we take feature requests over at [forem.dev]( https://forem.dev/). We already have some discussion around the dashboard happening over there. Please feel free to start a post there for these features. Our product team no regularly checks forem.dev for feature requests. Thanks!

**Comment by cmgorton** [comment]
James I am going to go a head and create a post for you in forem.dev with this feature request. I think we can have a good discussion over there about this. Thanks.

**Comment by cmgorton** [comment]
Here is the post if you would like to add any more comments to it @james-wallis 
https://forem.dev/foremteam/discuss-analytics-dashboard-features-31h9

**Comment by james-wallis** [comment]
Cool, thanks for taking the time to look at this @cmgorton. I’ll keep an eye on the Forem.dev post!
