### ISSUE TITLE
Error show when i write a article

### ISSUE THREAD

**Issue by hostinggs** [forem/forem#13308]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/45525893/113966064-10b27780-984c-11eb-891e-a8e8f583fcec.jpg)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by hostinggs** [comment]
Error show when i write a article

Ooooops...
You have encountered an error.
Our team has been notified.

We apologize for any inconvenience.

email.id gaganjot44@gmail.com

**Comment by cmgorton** [comment]
Hey @hostinggs thanks for following up here. Our team let me know they have reached out to you one already and would be happy to follow up with you by email.

**Comment by hostinggs** [comment]
problem not solved

**Comment by hostinggs** [comment]
plz remove my all post  next time i will not post copy content

**Comment by cmgorton** [comment]
Hey @hostinggs this is not an area I or the other engineers can help you with. You will need to read the email the community success team sent you and communicate with them there. They have the proper permissions to help you with your current issue. Thanks!
