### ISSUE TITLE
Feature Request- "experience level" variable in front matter

### ISSUE THREAD

**Issue by jeikabu** [forem/forem#13316]
Would be nice to be able to set the [experience level](https://dev.to/devteam/set-your-experience-level-for-a-more-tailored-feed-4e73) of a post in the [front matter](https://dev.to/p/editor_guide#front-matter) similar to `series:`.

I'm forever forgetting to do that since it's an additional step beyond the authoring process.

**Comment by cmgorton** [comment]
Thank you for opening this request.😃
Features tend to be subjective and might spur some debate. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
