### ISSUE TITLE
Spam Score issue

### ISSUE THREAD

**Issue by CodeWithBishal** [forem/forem#13330]
Hey, a few days ago I have noticed that the spam score of Dev to increased due to which the spam score of my website also got increased. Now I have drafted most of the posts and kept 2 posts posted with canonical URLs please recrawl all the posts of mine using the google search console. Thanks 

Update: I have waited for 1 months now, and the issue is still not fixed please help me

**Comment by cmgorton** [comment]
Hey Bishal
We don’t manually assign or adjust scores on DEV. Instead, our scoring system adjusts automatically according to the engagement on your posts. For example, if you get a lot of likes and saves your article will have a higher score, while if it’s reported as spam to our report system it will have a lower score. All we can recommend to improve your score is continue to share high-quality content with our community and be a positive contributor to discussions!

**Comment by CodeWithBishal** [comment]
which score you are talking about? I am talking about Moz spam score for a domain
