### ISSUE TITLE
Mentions in liquid tags inside comments shouldn't trigger notifications

### ISSUE THREAD

**Issue by rhymes** [forem/forem#13348]
**Describe the bug**

If an embedded liquid tag renders to text that contains a `@mention`, it will send notifications to those users.

**To Reproduce**

1. Ask someone to leave a comment that uses `{% comment ID }%` where `ID` is the ID of a comment that contains a mention
2. Receive notification because of the embedded context

**Expected behavior**

`@mentions` should not take into account embedded content via liquid tag

**Screenshots**

If I post this, I'm going to send a notification to those users:

![Screenshot_2021-04-10 Discussion of Top 5 DEV Comments of the Past Week](https://user-images.githubusercontent.com/146201/114269844-5ff1d700-9a09-11eb-86c7-20d1035a276f.png)

**Additional context**

After a quick check I think it's because `Mentions::CreateAll.call`  simply parses the HTML, without taking into account embedded content:

https://github.com/forem/forem/blob/1f52ebf3026af6e53e5c8f8431274b77c5befcb1/app/services/mentions/create_all.rb#L38-L44

**Comment by vaidehijoshi** [comment]
Started investigating this today since it is so closely tied to the work I've been doing with @-mention comments! 👀 🕵🏽‍♀️

**Comment by rhymes** [comment]
@vaidehijoshi I did a quick test, with an article that has both a mention and embeds a comment with a mention:

![Screenshot 2021-04-27 at 09-11-02 test mentions and liquid tags](https://user-images.githubusercontent.com/146201/116200390-91bcaa80-a738-11eb-83e8-eb5a7c91509b.png)


The HTML is something like:

```html
<p>Hey <a class="mentioned-user" href="http://localhost:3000/gottlieb_jody">@gottlieb_jody</a>
 </p>

....

<div class="liquid-comment">

....    

    <div class="body">
      <p>hey <a class="mentioned-user" href="http://localhost:3000/batzarmando">@batzarmando</a>
 </p>

    </div>
</div>
```

With Nokogiri you can do something like:

```ruby
# return all `.mentioned-user`
> doc.css('.mentioned-user').map(&:text)
=> ["@gottlieb_jody", "@batzarmando"]

# A: return only `.mentioned-user` tags not in a `.liquid-comment`
> doc.css('.mentioned-user').select { |tag| tag.ancestors('.liquid-comment').none? }.map(&:text)
=> ["@gottlieb_jody"]

# B: return the difference of the two sets
> (doc.css('.mentioned-user') - doc.css('.liquid-comment .mentioned-user')).map(&:text)
=> ["@gottlieb_jody"]
```

**Comment by vaidehijoshi** [comment]
Thank you, @rhymes! I knew about the `ancestors` bit but I hadn't put together last night that the `tag` itself was a node that I could call `ancestors` on 😅 I appreciate the extra context, that made it a bit easier to whip up my quick fix :)
