### ISSUE TITLE
Authors Can't Easily Access Hidden Comments on Their Post (to unhide them)

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#13360]
**Describe the bug**

If a user hides a comment and wants to unhide it, they must have access to the hidden comment's permalink to unhide it. Accessing a hidden comment via permalink is too difficult because the permalink isn't easily accessible (especially when a comment is hidden).

Authors should be able to easily access hidden comments on their post so that they can unhide them/report them to us when necessary.

**To Reproduce**

1. Write a post on dev.to using Account A
2. Use Account B to comment on that post
3. Use Account A to hide Account B's comment
4. Try to find a way to access and unhide Account B's comment within the interface

**Expected behavior**

If you hide a comment as an author, you should be able to easily access and unhide it.

**Additional context**

I wrote this as a bug instead of a feature because I think this is a crucial ability for this feature to have.

Admin can easily access an author's hidden comment by appending `/mod` to an author's post, scrolling down to hidden comments, and clicking in to see them. Perhaps this functionality can be replicated by appending `/manage` to the post which would allow the author to access hidden comments and unhide them if desired.

**Comment by vaidehijoshi** [comment]
Hm, this seems like a good quick win but I wonder what the design for this solution might be? 🤔 

@michael-tharrington any chance you could provide a screenshot of the current interface to exemplify the _lack_ of this functionality? I wonder if we just need a button to hide/unhide the comment

**Comment by michael-tharrington** [comment]
@vaidehijoshi Oh awesome! It'd be nice to get this one sorted.

So, the answer is kinda two part... to get to a hidden comment, an admin can append `/mod` to an article which will present them with a variety of things they can do. Interface looks like this:

![Image 2021-04-21 at 4 14 58 PM](https://user-images.githubusercontent.com/16007075/115615361-de2d6380-a2bc-11eb-854b-f054cbc6ecea.png)

There's no way for the author to access this page though! So, once they hide the comment it basically disappears from their post and they can't easily get back to it.

Rather than 1 image, here's [a loom video of me looking around as an author for a way to unhide the comment from my post](https://www.loom.com/share/4d3f85a9204043c09a6c29af8e5598c3). I think this will help to put it in perspective!

**Comment by Link2Twenty** [comment]
Maybe we could add a page similar to this 

<https://forem.dev/foremteam/let-s-discuss-3-a-roundup-of-feature-requests-5e2e/comments>

but that includes, or solely contains, hidden comments (already in their closed state).

Updating "Some comments have been hidden by the post's author" or adding something to Manage both make sense to me.

**Comment by Link2Twenty** [comment]
He's just a mock up I threw together 

![Simple mockup](https://user-images.githubusercontent.com/3534427/116720783-7f5e9d00-a9d4-11eb-92b9-be8f39975eb8.png)

Where the closed comments are hidden

**Comment by michael-tharrington** [comment]
Oooo I love this implementation @Link2Twenty. I think what you're describing is smoother than putting the unhide feature on `/manage`. I'm so down with us going this route!

**Comment by nickytonline** [comment]
Hi @Link2Twenty, would you like to work on this?

**Comment by Link2Twenty** [comment]
I think it requires some Ruby changes too (based on my digging). I wouldn't mind working in tandem with someone but my Ruby knowledge is non-existent 😅

**Comment by akashdotsrivastava** [comment]
@nickytonline I'd like to give this a shot.

**Comment by cmgorton** [comment]
Thanks @akashdotsrivastava . I have assigned you to the issue 😄

**Comment by akashdotsrivastava** [comment]
@cmgorton Thank you. A bit late, but I've added a PR for this. #14018

**Comment by akashdotsrivastava** [comment]
This was solved in #14018, so this issue can be closed.
