### ISSUE TITLE
Some deferred and async scripts are not deferred/async

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#13389]
**Describe the bug**

It was identified in PR #13350 that we have a lot of `script` tags in the codebase with the attributes `defer` or `async`, but without the `src` attribute.

Without the `src` attribute defer/async have no effect - see the [MDN docs for details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script):

> This attribute must not be used if the src attribute is absent (i.e. for inline scripts), in this case it would have no effect.

To fix this, we would need to move the JS script content into it's own file, and then reference it e.g. `<script defer src="scriptContent.js">`

Whoever takes on these fixes, I would suggest that we update each tag one by one in separate PRs so that we can minimise regression risk / review more easily

**Comment by jmau111** [comment]
Let's go down the rabbit hole ^^ , I'm taking this. Will do several PRs.

**Comment by jmau111** [comment]
@aitchiss hello, it seems if attribute type is specified with value module the async or the defer attribute becomes valid for inline scripts. Do you think it's better to extract code in separate files or should we use that type "module" ?

The only possible inconvenience is that the code would be executed in strict mode in that case.

**Comment by aitchiss** [comment]
Great point @jmau111! I don't see any problem with making these scripts type "module" if it doesn't affect their behaviour 👍

**Comment by jmau111** [comment]
ok @aitchiss, thanks.
