### ISSUE TITLE
Latest Episode of DevNews Not Showing Up

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#13420]
**Describe the bug**

@ellativity brought up earlier that she received a notification for "Today's podcasts" in her feed with a DevNews episode, but when clicking it, it sends a 404. (see image below)

**Expected behavior**

When I go to https://dev.to/devnews/s4-e1-platforms-as-utilities-archiving-yahoo-answers-and-companies-rescinding-accepted-offers I expect to see season 4, episode one. And navigating here - https://dev.to/devnews the podcast episode should appear at the top of the list. 

I also wouldn't expect for a notification to go out for a podcast episode that isn't live.

**Screenshots**

![Screenshot 2021-04-15 at 15 53 01](https://user-images.githubusercontent.com/16007075/114925141-b8a3e400-9dfc-11eb-9b2b-281fbb98fb90.png)

**Additional context**

This happened previously. Our feed reader was reading a previous episode of DEVDiscuss and blocking a newer one that was trying to come in — I think because their naming conventions were similar?

**Comment by fdoxyz** [comment]
It appears as if the episode is set as `reachable = false` in the DB. Maybe it was reachable but then modified to not-reachable but it appears as cached?

[Query here](https://dev.to/admin/blazer/queries/419-devnews-s4e1)

![Screen Shot 2021-04-15 at 13 46 00](https://user-images.githubusercontent.com/6045239/114929625-48439580-9df1-11eb-9518-457300dccb34.png)

**Comment by michael-tharrington** [comment]
The issues with DEVNews was fixed, so I'm closing this issue. It's possible that we still need to solve the underlying issue.
