### ISSUE TITLE
Organization secret code not copied to clipboard

### ISSUE THREAD

**Issue by DevLorenz0** [forem/forem#13434]
**Describe the bug**

When copying the organization secret code with the special button, it says "Copied to clipboard!" but doesn't work in reality. 

**To Reproduce**

1. Go To Edit Profile 
2. Go to Organization
3. Create an org (or switch to an existing one)
4. Under Grow the team - Your secret code is: --> Copy Button 
![image](https://user-images.githubusercontent.com/78320052/115156677-b6a08600-a085-11eb-84bf-39a23ccc78d1.png)
5. It does not copy the secret code

**Expected behavior**

Clicking on the button just copy the secret code. Or select it if it's not possible to copy. 

**Screenshots**

![image](https://user-images.githubusercontent.com/78320052/115156649-907ae600-a085-11eb-9c72-216e288c1861.png)
*Not copied in reality

Desktop (please complete the following information):

OS, version: Microsoft, Windows 10
Browser, version: Chrome, latest (88.0.4324.190)

Smartphone (please complete the following information):

Not specific to smartphones.

**Additional context**

I add that we can copy the secret code, just the special button doesn't work.

**Comment by djuber** [comment]
I can replicate this with Firefox and Chrome on linux in a local dev environment (so doesn't seem to be limited to windows/chrome, doesn't seem to be limited to https://dev.to/, probably applicable anywhere we expected to be writing to the clipboard).

https://github.com/forem/forem/blob/main/app/views/users/_org_admin.html.erb#L52-L68 seems to be the relevant view (the `clipboard-copy` element, specifically, is the question). 

The on-click handler to show "Copied to clipboard!" is registering on click, the clipboard event does not appear to be happening?

Is https://github.com/forem/forem/commit/2c54add4b853eb9414c672b2506f77cf66c969bc related? I see we removed an import for clipboard-copy-element which sounds startlingly like the behavior not happening here.

**Comment by cmgorton** [comment]
You got it @rafaVls . Assigning it to you now. Let us know if you have any questions as you start working on this. And thanks!

**Comment by cmgorton** [comment]
Hey! So sorry I missed your comment here. Are you still working on this issue and having trouble @rafaVls ?

**Comment by rafaVls** [comment]
Hi @cmgorton ! Yes, I'm still working on it. I managed to login using my github account.
I was able to fix the issue, but i'm not entirely sure it doesn't break anything. 

Like @djuber saide, the problem seemed to be related to 2c54add / #6815. So, what I did was uncomment that line and now the organization code is copied as expected.

Is there a way to check if this breaks anything or can I start the pull request?

**Comment by rafaVls** [comment]
> I was able to fix the issue, but i'm not entirely sure it doesn't break anything.

I say this because the PR states that these lines were "causing problems in production".

**Comment by cmgorton** [comment]
Hey @rafaVls Thanks for asking. I think the best course of action is to create the PR then it can be reviewed and our team can help you with any tests you may need to check that there is no breaking code 😄

You could also make it a Draft PR and ask for help there too.

**Comment by aitchiss** [comment]
@rafaVls I've unassigned you from the issue as per our discussions over here - https://github.com/forem/forem/pull/13878

If you'd like to pick it back up again in future just let us know, but otherwise thanks so much for your work on it so far. Whoever does pick this up later can refer to the discussions and work already explored in the linked PR 🙂

**Comment by cmgorton** [comment]
For anyone who may work on this issue in the future please see the discussion in #13878 for a potential solution.

**Comment by crhaugen** [comment]
Hello! I'd love to give it a go if it's still open. :)

**Comment by cmgorton** [comment]
Hey! Thanks @crhaugen . I have assigned you to the issue. Please be sure to read the discussion from #13878 before getting started on this and let us know if you have any questions.
