### ISSUE TITLE
Missing read time from GET articles endpoint

### ISSUE THREAD

**Issue by hadiidbouk** [forem/forem#13436]
I am building a multiplatform application for DEV that will run on iOS, iPad OS, and macOS using SwiftUI ([here](https://github.com/hadiidbouk/DEV)).
The problem is that [GET articles endpoint](https://docs.forem.com/api/#operation/getArticles) doesn't contain the "read time" property.

The "3 min read" is added just for testing purposes.

<img width="1365" alt="Screen Shot 2021-04-09 at 2 54 03 PM" src="https://user-images.githubusercontent.com/19314956/115161520-da27f880-a0a6-11eb-8b4a-38f3d824c94f.png">

**Comment by djuber** [comment]
it looks like `reading_time` would be the item missing from [`Api::V0::ArticlesController::INDEX_ATTRIBUTES_FOR_SERIALIZATION`]( https://github.com/forem/forem/blob/main/app/controllers/api/v0/articles_controller.rb#L14-L20 )

Not sure if this is the right thing to do (if there was a reason reading_time was left out), but I think that's _where_ to start adding it.

**Comment by djuber** [comment]
@hadiidbouk I'm adding this now (if you're only using the api from https://dev.to, articles should include a `reading_time_minutes` value in an hour or so, some hosted Forem instances may not have this field present until later this week). The [api documentation](https://docs.forem.com/api/) should update to version 0.9.6 about the same time the additional field is present.

**Comment by hadiidbouk** [comment]
@djuber I can confirm that it works as expected thank you!
