### ISSUE TITLE
How to create dynamic query of graphQL from schema

### ISSUE THREAD

**Issue by renu944** [forem/forem#13438]
Hi ,
I have a requirement to generate dynamic query of GraphQL from schema. I need to create dynamic schema and its query by passing table name from the database. I am able to create schema dynamically. Can anyone help me to create dynamic queries on it?

Thanks

**Comment by rhymes** [comment]
Hi @renu944, I think you might have opened this request in the wrong repository. Forem doesn't have a GraphQL schema.
