### ISSUE TITLE
Deprecation Warning: sidekiq-unique-jobs middleware configuration

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#13447]
Seeing a deprecation warning after running `bundle`.

```
Post-install message from sidekiq-unique-jobs:
IMPORTANT!

Automatic configuration of the sidekiq middleware is no longer done.
Please see: https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/README.md#add-the-middleware

This version deprecated the following sidekiq_options

  - sidekiq_options lock_args: :method_name

It is now configured with:

  - sidekiq_options lock_args_method: :method_name

This is also true for `Sidekiq.default_worker_options`

We also deprecated the global configuration options:
  - default_lock_ttl
  - default_lock_ttl=
  - default_lock_timeout
  - default_lock_timeout=

The new methods to use are:
  - lock_ttl
  - lock_ttl=
  - lock_timeout
  - lock_timeout=
  ```
  
  Seems like a fairly straightforward find and replace fix.

**Comment by Zhao-Andy** [comment]
I didn't use the bug report template because I think this is probably an easier way to describe the issue. 😅 Maybe this is `ready-for-dev` and a `good-first-issue` @cmgorton?

**Comment by djuber** [comment]
@Zhao-Andy I suspect we're already okay here after this commit:

https://github.com/forem/forem/commit/e6883ea63b11779bc3d6bf3a4201fce765404809 

 It looks like we might already be configuring this explicitly, and the warning is not applicable (but bundle doesn't know what we do at app boot and the deprecation warning presents itself).

If there's something in scope more than "silence unneeded deprecation" I might have misread something.

**Comment by rhymes** [comment]
I think as well we don't need to do anything, as we're not using those params that need to be renamed.

I believe the post install message is meant as a generic notice for the people using the gem, luckily we are not using that specific combination of params.

I've also tried to submit a job twice (to trigger locking) and I saw no deprecation messages:

```ruby
[2] pry(main)> Emails::SendUserDigestWorker.perform_async(1)
=> "8faca17e67144c81b7ffb5ad"
[3] pry(main)> Emails::SendUserDigestWorker.perform_async(1)
2021-04-20T07:55:15.640Z pid=46503 tid=29kv uniquejobs=client until_executing=uniquejobs:e7a25cfa0563baaa4b3c759bcba32ad8 WARN: Timed out after 0s while waiting for primed token (digest: uniquejobs:e7a25cfa0563baaa4b3c759bcba32ad8, job_id: d71ec471b28c52e2d686e6e8)
=> nil
```

I'm going to close this @Zhao-Andy 🙌
