### ISSUE TITLE
Sometimes I'm getting Error while trying to access dev.to

### ISSUE THREAD

**Issue by Devangprajapati1997** [forem/forem#13448]
Sometimes it is showing Error compiling css asset while accessing dev.to

**To Reproduce**

1. Go to https://dev.to

**Expected behavior**

- It must open without any error

**Screenshots**
![Screenshot 2021-04-20 at 9 47 22 AM](https://user-images.githubusercontent.com/14945579/115337276-4ba69a80-a1be-11eb-8818-8b14757e41ac.png)

**Desktop:**

- OS, version: macOS Big Sur, 11.2.3
- Browser, version: Safari, 14.0.3

**Comment by Ridhwana** [comment]
Hi @Devangprajapati1997, thank you for bringing this to our attention. 

I'm unable to replicate the issue and so I was wondering can you possibly please clarify thee following for us to be able to help: 

1. Is it happening repeatedly and you're unable to use the site at all, or is it just happening sometimes when you access the site? If it happens only sometimes can you give us more detail on the frequency?
2. How do you then access the site after the error occurs? Does a hard or a soft refresh clear the error for you? 
3. Also, are you experiencing the error on any other browsers, or has this only been happening with Safari?

**Comment by krishnadevz** [comment]
Hi @Devangprajapati1997 try to clear cache of your browser try to open it in another browser if that issue still comes then ping here if not then close the issue

**Comment by Devangprajapati1997** [comment]
Refreshing page loaded dev.to.
Closing issue.
