### ISSUE TITLE
User directed to 404 on Password Reset

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#13463]
**Describe the bug**

User received a 404 page after requesting a password reset on Dev.to

**To Reproduce**

- Log into your account
- Navigate to Settings -> Account
- Request a password reset
- Enter your email
- Note you've been redirected to https://dev.to/users/update_password, but it's a 404/Page does not exist page

**Expected behavior**

I'm not sure, but I'm certain it's not a 404 page!

**Screenshots**

![CleanShot 2021-04-21 at 08 37 47@2x](https://user-images.githubusercontent.com/37842/115563169-dea60a00-a27c-11eb-9bde-9ee51c961cc4.png)

**Desktop (please complete the following information):**

- OS, version: Mac OS 11.2.3
- Browser, version: Safari 14.0.3

**Additional context**

I **did** receive the password reset email, so this is just a page routing issue.

**Comment by citizen428** [comment]
Hmm, I just tried this locally and was redirected to http://localhost:3000/settings/account which seems ok. Then I tried on dev.to and it also worked just fine there. Does this still happen for you?

**Comment by joshpuetz** [comment]
Yup, this is a just me issue: I had some VERY borked cookies in both Chrome and Safari locally. Sorry!
