### ISSUE TITLE
Should be able to update all followed tags with one click

### ISSUE THREAD

**Issue by 2lach** [forem/forem#1346]
**Problem/ feature request:**
On the [Followed tags page](https://dev.to/dashboard/following) the user can only submit a single new value for follow weight per submit.

Current page:
![following page current](https://user-images.githubusercontent.com/11457600/50086369-1ad48600-01fd-11e9-85cc-3088c65127da.jpg)

**Proposed solution**
Since i suppose most users of dev.to (myself included) update several topics at the same time, I suggest a `update all` button. 
This way there is no need for several clicks when updating follow weights = () => which makes happier users and also less data traffic with fewer requests.

Solution illustrated:
![following page proposal](https://user-images.githubusercontent.com/11457600/50086740-3ee49700-01fe-11e9-8f99-3e4336d0109f.jpg)

**Alternatives**
Keep it as is or maybe just save all edited values in localStorage so the input doesn't loose it on Submit. 
Not as awesome as with an update all button. but still the follow weight is a nice feature in an already awesome community. 

Have an awesome day!

**Comment by Zhao-Andy** [comment]
Hey @2lach, thanks for the feature request! This definitely can be improved, and I think we'll want to discuss which option is best to resolve the UX here.

**Comment by 2lach** [comment]
Glad to it @Zhao-Andy 👍 

IMHO there are two main ways to go about the UX:

**Option 1**: Would be to do as in the image above  in the feature  request -> `Solution illustrated` which is basically adds a new button and keeps the existing submit buttons.
The new button can be added at the top or bottom of the page. The bottom of the page feels more natural than placing it at the top as in my illustration.

**Options 2**:
Remove all existing submit buttons and only keep the  `Update all` this would give the user less options but also make the UI clearer and cleaner.

**Comment by Link2Twenty** [comment]
While we're looking at this they should be number inputs really.

```html
<input type="number" step="0.1" />
```

**Left field:**
Thought I'd throw in a totally random idea, how about importance sliders, 0 to 10, that update on change?

**Comment by jessleenyc** [comment]
For whoever wants to grab this, I think option 2 makes a lot of sense here.

**Comment by 2lach** [comment]
Hey @jessleenyc, hope all is well! 
I totally forgot about this 😋 cool that you brought it up again 👍 I could take some time and fix the UI/UX part.

However, being honest i don't see that i will have the time to get into and fix the backend parts (been a couple of years since i wrote a line of ruby).

So if thats cool i can fix the front-end.

Have a good one 😎

**Comment by jessleenyc** [comment]
Cool, want to give me a ping when you have something and we'll finish it up?

**Comment by xanderyzwich** [comment]
I'd also offer an alternative that maybe have the submit button not require a reload. I understand that this will likely not allow for the element to move into order, but I feel in the bulk update scenario that is acceptable. The biggest headache about this to me is in the page reload and having to scroll back down to where I just was and doing this a few dozen times when editing my weighting scheme.

**Comment by 2lach** [comment]
If @xanderyzwich feels like you have a suitable solution feel free to take over this issue.

I have not been able to find the time to do this task for some time and most likely will not now either.

**Comment by cmgorton** [comment]
Looks like this feature request was addressed in PR #11454. Going to go a head and close this issue!
