### ISSUE TITLE
Remove `/partnerships` page ✂️ 

### ISSUE THREAD

**Issue by mstruve** [forem/forem#13468]
The Partnerships functionality and the associated https://dev.to/sponsors page are not currently priorities (we have no active partners). Partnerships are pretty much hard-coded in to _every single Forem_.  

We want to give this entire set of functionality fresh eyes at some point, but we thought that we could immediately simplify the starter pack if we can at least remove the `/partnerships` page to avoid confusion. Despite removing the `/partnerships` page we want to still maintain the sponsor functionality on the backend. 

- [ ] remove `/partnerships` HTML Page
- [ ] Remove `/partnerships` route (controller method and routes.rb file)

Related Stage 0 with product sign off: https://github.com/forem/rfcs/issues/193

**Comment by citizen428** [comment]
The issue mentions both https://dev.to/sponsors and `/partnerships`, should both be removed? Partnerships are not just a simple page, it's a separate `ParnershipsController`. Just want to make sure if both need to be removed or only `/partnerships` in which case the checklist may not be 100% accurate.

**Comment by mstruve** [comment]
Great question! I updated the issue to only address `/partnerships` since that is what the original Stage 0 explicitly states. Following up with @pkfrank to see if we want to add in sponsors while we are here.
