### ISSUE TITLE
Random posts showing up on profile page

### ISSUE THREAD

**Issue by technoglot** [forem/forem#13494]
**Describe the bug**

I noticed random posts appearing on my profile. These posts are NOT mine. When visiting other users' profiles, I see these exact same posts appearing as well.

**To Reproduce**

Go to your profile page, and scroll past the section with all your submitted comments. You should start seeing posts appearing there that are NOT your own. 

**Expected behavior**

I expect to see ONLY my posts on my profile. Profiles of users that have not written any posts, should be empty (i.e. no posts should show here). 

**Screenshots**

![image](https://user-images.githubusercontent.com/36389797/115978855-6aa38480-a550-11eb-9d97-0c2761ec1fa7.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10 Pro
- Browser, version: Chrome (Version 89.0.4389.128)

**Smartphone (please complete the following information):**

- Device: Samsung Tab S6 Lite
- OS, version: Android 11
- Browser, version: N/A (DEV mobile app)

**Additional context**

Visit my [profile](https://dev.to/technoglot) (or anyone's profile for that matter) , and see for yourself.

**Comment by thibaultduponchelle** [comment]
Hello,

With no surprise I have the same issue as @technoglot on my profile but in addition I noticed the same problem in "tag view". Example with [#python](https://dev.to/t/python) or [#perl](https://dev.to/t/perl) where usually **only** the articles with the correct tag appear but now the first posts have the correct tag then below it's random.

**Comment by rhymes** [comment]
Hi! Thanks for notifying us! Can you double check now? It should be solved

**Comment by thibaultduponchelle** [comment]
Hello @rhymes I confirm 👍🏼 😃

**Comment by technoglot** [comment]
Hello @rhymes , issue is fixed indeed. Thanks for looking into it! 😁
