### ISSUE TITLE
Long comments with @-mentions cause rendering issues

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#13513]
**Describe the bug**

The @-mention autocomplete component does not render in the correct location when typing a long comment and using an @-mention further "down" in the comment.

**To Reproduce**

1. Go to a Forem, and type a comment. Input enough text in the comment such that it is "long" enough to trigger the scroll bar on the side.
2. Towards the bottom of the comment's text, @-mention any user; in the process of typing the @-mention, you'll notice the the list of users renders significantly _below_ the comment's input box, and not near where your cursor is.

Some examples of this occurring:
*On DEV:*
<img width="782" alt="Screen Shot 2021-04-26 at 9 23 42 AM" src="https://user-images.githubusercontent.com/6921610/116118126-d8939d00-a671-11eb-93a2-5eb38c11879c.png">

*On Forem.team:*
<img width="1007" alt="Screen Shot 2021-04-26 at 9 19 33 AM" src="https://user-images.githubusercontent.com/6921610/116118157-e0534180-a671-11eb-916a-7b80aab08e88.png">
<img width="743" alt="Screen Shot 2021-04-26 at 9 21 40 AM" src="https://user-images.githubusercontent.com/6921610/116118169-e47f5f00-a671-11eb-9b0c-9399c9e2eeee.png">

**Expected behavior**

The expected behavior would be that the layout/location of the @-mention list of suggested users appears directly below the cursor, just as it does for "short comments", like this:

<img width="676" alt="Screen Shot 2021-04-26 at 9 28 40 AM" src="https://user-images.githubusercontent.com/6921610/116118091-d3cee900-a671-11eb-89dd-0de175157913.png">

**Desktop (please complete the following information):**

- Browser, version: Chrome 90.0.4430.85

**Comment by aitchiss** [comment]
I have a suspicion that this is going to be related to how a comment textarea expands in height vs the post editor (which is where we first found this bug and implemented the fix). The post editor auto-resizes to take up the full height of its content, whereas I can see in the screenshot above the comments section seems to have a max-height and then starts scrolling. The dropdown is being positioned as if the comment box height expands like the post editor.

I'll need to have a quick check whether this is a regression in the comment box resizing or in the dropdown positioning - I thought it dynamically resized in height too 🤔

**Comment by cmgorton** [comment]
Is this related at all to https://github.com/forem/forem/issues/13298 ?

**Comment by aitchiss** [comment]
@cmgorton I think only in that it's related to the autocomplete component - I'm pretty sure they'll need two separate fixes

**Comment by Link2Twenty** [comment]
Is this open for dev? I have a hunch.

**Comment by cmgorton** [comment]
I would say yes. I can assign you to it @Link2Twenty . And thank you! 
@aitchiss let me know if there is any reason this shouldn't be opened up for contributors yet.

**Comment by aitchiss** [comment]
> I would say yes. I can assign you to it @Link2Twenty . And thank you!
> @aitchiss let me know if there is any reason this shouldn't be opened up for contributors yet.

Go for it! Let me know if you have any questions around the autocomplete component @Link2Twenty - it's kinda weird in there 😆
