### ISSUE TITLE
400 response from CDN on valid image (GIF) upload

### ISSUE THREAD

**Issue by andyrichardson** [forem/forem#13535]
**Describe the bug**

The CDN returns a 400 when a GIF is uploaded to a post.

> Note: Upload and source URL both work fine - just CDN returning 400 

[GIF URL](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/6p65j4e27ayfz5iqn5iq.gif)
[CDN URL](https://res.cloudinary.com/practicaldev/image/fetch/s--QkUqQ87b--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/6p65j4e27ayfz5iqn5iq.gif)
[Draft URL](https://dev.to/andyrichardsonn/test-page-1agj-temp-slug-9786075?preview=cba35c99ca242921a9b49ba576f5cec9748b5eb36dff394b94f342454da4ed8db06571fccf2e6a0ee244880a4fa6554bc9c27fc95401b92fab55821c)

**To Reproduce**

 - Upload a gif
 - Preview draft

**Expected behavior**

CDN generated URL points to valid asset.

**Actual behavior**

CDN url returns 400

**Screenshots**

![Kapture 2021-04-27 at 10 29 06](https://user-images.githubusercontent.com/10779424/116219444-8753de00-a743-11eb-8c4b-a0baab5fc7c6.gif)

**Comment by atsmith813** [comment]
@andyrichardson I believe the gif may be too large

![Screen Shot 2021-04-27 at 10 30 04 AM](https://user-images.githubusercontent.com/15987080/116259204-9aff4480-a743-11eb-9b9a-a45feb647a6e.png)

Does it work for you if you try a smaller/simpler gif?

**Comment by andyrichardson** [comment]
@atsmith813 thanks for getting back to me on this 🙏 

I ended up resizing the GIF to get around this after seeing this message in the response headers 

>  Maximum total number of pixels in all frames/pages is 200 Megapixels. Requested 215.56 Megapixels

R.E. The [docs here](https://dev.to/p/editor_guide#markdown-inline-images) - it looks like the wording is a little off as it's actually the accumulated number of megapixels can't be more than 200 (rather than per frame/page).
