### ISSUE TITLE
Excessive pull-down to refresh in private messages

### ISSUE THREAD

**Issue by foresthoffman** [forem/forem#13560]
**Describe the bug**
When attempting to scroll up in the Messages view, the "pull down to refresh" event activates when that is not the desired behavior. 

There appears to be multiple points (as you scroll down) after which scrolling up is prevented by the "pull down to refresh" freature. I've noticed this behavior in the Messages side bar, where you can see the list of users and groups. I've also noticed this behavior in the Direct Message view for an individual user or group.

**To Reproduce**
Open the DEV.to app, then:
1. Tap the messages icon in the nav bar at the top of the screen.
2. From the messages sidebar or from the Direct Message view:
  a. Scroll down at least a screen length.
  b. Scroll up to see the refresh feature activate.
  c. Repeat a & b if necessary. If the bug is present, you should end up stuck further and further down the view.

**Expected behavior**
I expected to be able to scroll down and up without the refresh activating, unless I'm at the top of the view and cannot scroll up any further.

**Screenshots**
Here is a [YouTube recording of the bug in action](https://youtube.com/shorts/Y-2DHTGoMxk?feature=share).

Here is a screenshot: ![screenshot of the refresh feature activating](https://user-images.githubusercontent.com/2442905/116275880-9f2e6080-a749-11eb-950e-9f18825518e6.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android
 - Version: 10

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
