### ISSUE TITLE
Remove footer mascot image ✂️ 

### ISSUE THREAD

**Issue by mstruve** [forem/forem#13587]
## Summary

Remove all fields related to the footer mascot image (on DEV it's the sloan hanging from the top edge of footer). Even though it brings some fun and element of delightfulness, its value is doubtful especially when you think that probably 99% of communities will never have their own mascot (or actually anything to put there).

![Screen Shot 2021-04-29 at 12 38 38 PM](https://user-images.githubusercontent.com/1813380/116586858-835cc300-a8df-11eb-848f-43f6baf344aa.png)

It appears there are 4 related fields that need to be removed as well as the code that relates to them
```ruby
  # TBH I don't even see this used anywhere so lets remove it. 
  field :mascot_image_description, type: :string, default: "The community mascot"

  field :mascot_footer_image_url, type: :string, validates: { url: true }
  field :mascot_footer_image_width, type: :integer, default: 52
  field :mascot_footer_image_height, type: :integer, default: 120
```
Once this is done make sure to communicate this change via the changelog so other admins are aware of it. 

## Additional Context

It is "inspired" by the the rough [roll out plan for Starter Pack](https://docs.google.com/document/d/1facy0-UXlUPrzpll8TAM-MNjZiwVbO1vepphuE6a-ek/edit).
Product Approved Stage 0: https://github.com/forem/rfcs/issues/209

**Comment by rhymes** [comment]
For whomever takes this: we have recently migrated to `Settings::Mascot`, see https://github.com/forem/forem/pull/13451 and https://github.com/forem/forem/blob/main/app/models/settings/mascot.rb

**Comment by citizen428** [comment]
I really wish we had decided on this a bit earlier. If we remove all these settings from `Settings::Mascot` there are only two left, so it doesn't really make sense to keep this separate settings model around and they should probably move back into `SiteConfig`.

**Comment by citizen428** [comment]
@mstruve I'm on FOSS duty this week and this aligns with some of the work I've been doing over the past few week so I think it's easiest if I just take care of it.

**Comment by citizen428** [comment]
Can someone please let me know if https://github.com/forem/forem/pull/13451 has already been deployed across the fleet? cc @maestromac

**Comment by Zhao-Andy** [comment]
@citizen428 should be deployed! BTW I handle deploying to fleet :)

**Comment by citizen428** [comment]
I knew that but somehow ended up mentioning Mac, sorry for that. And thank for the answer :-)

**Comment by Ahnaf780** [comment]
Lol tf is this shit xd

**Comment by cmgorton** [comment]
Did you have a concern with something in this issue @Ahnaf780 ?

**Comment by maestromac** [comment]
all good @citizen428 !

Did you mean to ping someone else @cmgorton ? or you meant to comment that somewher else?

**Comment by cmgorton** [comment]
> all good @citizen428 !
> 
> Did you mean to ping someone else @cmgorton ? or you meant to comment that somewher else?

I think their comment was deleted.
