### ISSUE TITLE
The latest tab is not loading the post correctly

### ISSUE THREAD

**Issue by Afif13** [forem/forem#13581]
I am having this behavior since a few days ago now.
The latest tab only show few posts correctly then jump to display random posts very old:

![image](https://user-images.githubusercontent.com/14073250/116554863-fa07b980-a8fb-11eb-86ba-cf92e23ffae6.png)

This is having a negative impact on the visibility of many posts (I noticed that the reactions of many good posts are very low)

Filtering by tag shows only the 6 last posts (ex: https://dev.to/t/css/latest)

**Comment by rhymes** [comment]
Hi @Afif13, we're going to look into it and let you know. Thanks for your patience :)

**Comment by rhymes** [comment]
Hi @Afif13, I located the bug in our new search backend, I deactivated it while we investigate a fix. I'll let you know when that's done.

**Comment by Afif13** [comment]
@rhymes but now all the posts of DEV show under any tag .. the tag filtering is no more working with latest.

**Comment by rhymes** [comment]
Hi @Afif13, it should be fine now! I checked both https://dev.to/t/css/latest and other tags :-)

**Comment by rhymes** [comment]
Closed by #13577

**Comment by KhorenGrig** [comment]
Mentioned today. Only this one was wrong result. Rest results were correct.

![4C57E408-DB31-4C08-9762-51415DC47DEC](https://user-images.githubusercontent.com/26667922/116844967-a47e2600-abf5-11eb-8ef3-ee4052f38856.png)
