### ISSUE TITLE
Remove shop_url from SiteConfig and Related Code

### ISSUE THREAD

**Issue by mstruve** [forem/forem#13583]
## Summary
The Shop URL is just another link in navigation but it has some special treatment in code. Since we introduced dynamic navigation links, Admin can specify navigation links in that area. We believe this one doesn't deserve to be a special snowflake anymore since it's just a regular nav item.

Remove "Shop URL" field from admin's config as well as the related code. Steps to complete this task include:
- [x] remove the shop_url and related code
- [x] Add a navigation link for DEV that points to the shop via admin (you may need to recruit a DEV admin to help with this)
- [ ] Ensure this is marked for the changelog so other creators are aware of the change. 

## Additional Context

It is "inspired" by the the rough [roll out plan for Starter Pack](https://docs.google.com/document/d/1facy0-UXlUPrzpll8TAM-MNjZiwVbO1vepphuE6a-ek/edit).
Stage 0 Product approved Issue: https://github.com/forem/rfcs/issues/210

**Comment by citizen428** [comment]
@mstruve I'm done with step 1 now. 

I'm a bit unsure about the follow-up tasks as the navigation link already exists. Seems like it was created by `lib/tasks/add_navigation_links.rake` which was added in October in https://github.com/forem/forem/pull/10754. We probably ran it manually afterward, maybe @Ridhwana remember and can confirm. I confirmed via Blazer that a `NavigationLink` for the shop already exists and the current sidebar on DEV perfectly matches the Rake task.

This means I'm also not quite sure about the changelog entry as it seems we haven't had a hard-coded shop link in a while so I'm not quite sure what to document (if anything).

**Comment by mstruve** [comment]
> This means I'm also not quite sure about the changelog entry as it seems we haven't had a hard-coded shop link in a while so I'm not quite sure what to document (if anything).

I think the changelog entry would just be to address the change in the Config area in admin and I also think for other creators mentioning the nav links could be used in its place might be useful. Not sure if any other Forems have even made use of that shop_url but can't hurt to throw a changelog label on the PR so it's included.
