### ISSUE TITLE
Remove `/search/users` endpoint

### ISSUE THREAD

**Issue by atsmith813** [forem/forem#13590]
**Describe the bug**
We no longer use the `/search/users` endpoint, we can go ahead and remove the endpoint and all related specs.

https://github.com/forem/forem/blob/22eaecba1ff9dac81846e2ef06651394e821e6fe/app/controllers/search_controller.rb#L96-L98

https://github.com/forem/forem/blob/22eaecba1ff9dac81846e2ef06651394e821e6fe/config/routes.rb#L275

**Comment by Ayushsunny** [comment]
Hello @atsmith813 I would like to work on this issue, could you guide me with that

**Comment by citizen428** [comment]
@Ayushsunny  Thanks for volunteering, I assigned you this issue. What you'd have to do is 

1. remove the `search` method from `forem/app/controllers/search_controller.rb`
2. remove the route ` get "/search/users", to: "search#users"` from `config/routes.rb`
3. remove any specs related to that route

**Comment by rhymes** [comment]
Thank you @Ayushsunny!

**Comment by atsmith813** [comment]
Hey @Ayushsunny! I'm going to reassign this issue to myself. We discovered this endpoint needs to be removed right away as it's blocking another PR that I'm working on. I'm actually in the code right next to it so I'll include this issue in my PR. I'm sorry about that, I didn't realize we'd need this so quick when I originally made the issue - that's my fault. We really appreciate you stepping to volunteer to take this on.

There are other issues as well and we'd be happy to help however we can!

Thanks again!

**Comment by Ayushsunny** [comment]
> Hey @Ayushsunny! I'm going to reassign this issue to myself. We discovered this endpoint needs to be removed right away as it's blocking another PR that I'm working on. I'm actually in the code right next to it so I'll include this issue in my PR. I'm sorry about that, I didn't realize we'd need this so quick when I originally made the issue - that's my fault. We really appreciate you stepping to volunteer to take this on.
> 
> There are other issues as well and we'd be happy to help however we can!
> 
> Thanks again!

Ohh, No problem Sir. @atsmith813 
you can assign me on some other issues if you think I can work on.

**Comment by rhymes** [comment]
Hi @Ayushsunny! We have a few issues you can choose from, those labeled [ready for dev](https://github.com/forem/forem/labels/ready%20for%20dev) :-)

Thank you again! Let us know if you need further help in choosing

**Comment by Ayushsunny** [comment]
> Hi @Ayushsunny! We have a few issues you can choose from, those labeled [ready for dev](https://github.com/forem/forem/labels/ready%20for%20dev) :-)
> 
> Thank you again! Let us know if you need further help in choosing

Sorry @rhymes Sir, as I am new to Open Source and also in this org I have no idea which one to pick.
could you help me with that

**Comment by citizen428** [comment]
Sure, we can help you @Ayushsunny :smiley: Would you prefer to work with Ruby or Javascript?

**Comment by Ayushsunny** [comment]
> Sure, we can help you @Ayushsunny 😃 Would you prefer to work with Ruby or Javascript?

Hello @citizen428 Actually I'm okay with Javascript but I'm trying to shift to Ruby.

**Comment by citizen428** [comment]
@Ayushsunny Removing some of our current deprecation warnings could be a good Ruby learning experience: https://github.com/forem/forem/issues/11282
