### ISSUE TITLE
Storybook for `crayons-tabs` redirects off page

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#13601]
**Describe the bug**

Currently the story for tabs doesn't really show what the tabs do. You can see the default state but can't click on a tab.

**To Reproduce**

1. Go to [storybook](https://storybook.forem.com/?path=/story/components-navigation-tabs-html--default)
2. Click on a tab
3. You are redirected off the page

**Expected behavior**

Clicking a tab should update which tab is marked as current but should not navigate away.

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

The code is located here
/app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.html.stories.jsx

I'd probably update the `href` to `#` and add some JS to handle the active state.

**Comment by aitchiss** [comment]
> I'd probably update the href to # and add some JS to handle the active state.

I think that will be a good solution 🙂 

Our "Tabs" component is more of a group of navigation links than a classic "tab panel", so you're right, the links need to go _somewhere_. I agree, using "#" as the href would allow us to stay on the same page and we can track the current tab with some JS in the story itself.

**Comment by payapula** [comment]
Hi @cmgorton  

I would like to pick this up 😄

**Comment by rhymes** [comment]
@payapula I've assigned it to you, thanks!

**Comment by payapula** [comment]
This should be fixed by https://github.com/forem/forem/pull/14491
