### ISSUE TITLE
Remove extra space from readable_publish_date

### ISSUE THREAD

**Issue by hadiidbouk** [forem/forem#13612]
I am using the GET latest articles endpoint in [my project](https://github.com/hadiidbouk/DEV).

The `readable_publish_date` property added an extra space between the day and the month, this could be fixed on the front end, but if it's a readable publish date why not be better readable 😅

<img width="259" alt="Screen Shot 2021-05-02 at 6 42 01 PM" src="https://user-images.githubusercontent.com/19314956/116818941-858c7f00-ab76-11eb-9776-e5f60946054b.png">

**Comment by citizen428** [comment]
Thanks for the issue. The problem here is that Ruby pads `%e` with whitespace. This can be prevented by changing the format specifier to `%-e`:

```ruby
Date.today.strftime("%b %e")
#=> "May  5"
Date.today.strftime("%b %-e")
#=> "May 5"
```

**Comment by Arun-kc** [comment]
Can I help? @citizen428

**Comment by rhymes** [comment]
@Arun-kc I've assigned this to you! Thank you!

**Comment by Arun-kc** [comment]
> @Arun-kc I've assigned this to you! Thank you!

Thank you! @rhymes 😇. This is my first time doing a major PR. Hope what I did is correct 🤞
