### ISSUE TITLE
Remove too granular “emails” from SiteConfig

### ISSUE THREAD

**Issue by mstruve** [forem/forem#13628]
## Summary

Admins can currently define email addresses for very specific cases. The idea is to drop all of them in favor of one email address for all scenarios.

**Admin » Config » Emails** --> This entire section contains a bunch of email fields that were created AFAIK only for DEV as we thought it would make sense to be able to customize them. We believe that assumption wasn’t valid, especially since these email addresses are used mostly on static pages, where an admin can literally enter anything. On top of that, we don’t think we have to be as granular as we are with providing different types of emails to be used across codebase… Right now there are “default”, “contact”, “business”, “privacy” and “members”.

- [ ] Keep the default email address and replace **all other email addresses** with it.
- [ ] Set a proper "Reply-To" header using the default email address via `ActionMailer` -> [solution idea from](https://github.com/forem/rfcs/issues/176#issuecomment-813158217) @citizen428 
- [ ] communicate this change via the changelog and forem.dev

## Additional Context

It is "inspired" by the rough [roll out plan for Starter Pack](https://docs.google.com/document/d/1facy0-UXlUPrzpll8TAM-MNjZiwVbO1vepphuE6a-ek/edit).
Product approved Stage 0 RFC: https://github.com/forem/rfcs/issues/207

**Comment by lightalloy** [comment]
Done with #13853 and #13958
