### ISSUE TITLE
Unable to embed a github gist with highlighted lines

### ISSUE THREAD

**Issue by tusharsadhwani** [forem/forem#13651]
**Describe the bug**

Github lets you highlight parts of your gist by the following syntax

`gist.github.com/username/123456#file-filename-L7`, to highlight line 7 for example.

Real example: https://gist.github.com/Untrusted-Game/2a36648c4c673a3927511184246b7a17#file-untrusted-lvl5-solution-js-L14-L16

![highlighted lines 14-16](https://user-images.githubusercontent.com/43412083/117068524-04391600-ad49-11eb-9235-45d207dce2af.png)

Trying to embed a file with lines highlighted doesn't seem to work with forem, both with and without the `file=filename` syntax.

It would be nice if a `lines=...` attribute could be added to the gist liquid tag, for example:

`{% gist https://gist.github.com/Untrusted-Game/2a36648c4c673a3927511184246b7a17 file=untrusted-lvl5-solution-js lines=L14-L16 %}`

**Comment by cmgorton** [comment]
Hey @tusharsadhwani this looks like a feature request if I am not mistaken? Would you mind adding this to[ forem.dev](https://forem.dev/) instead. We want to keep mostly bugs here in the repo. In [forem.dev](https://forem.dev/) I can bring the feature requests up to our product team for greater visibility. 

You can see some examples of feature requests in forem.dev in this [round up post. ](https://forem.dev/foremteam/let-s-discuss-3-a-roundup-of-feature-requests-5e2e)

Thanks!
