### ISSUE TITLE
Badge title is unreadable when long

### ISSUE THREAD

**Issue by alvaromontoro** [forem/forem#13652]
**Describe the bug**

The title of the badges is too small to read in some cases. In particular, the title of the DigitalOcean App Platform Hackathon on DEV Badge is unreadable on smaller screens.

**To Reproduce**

1. Go to the [Digital Ocean Hackathon badge page](https://dev.to/badge/participant-e2-80-94-digitalocean-app-platform-hackathon-on-dev)

**Expected behavior**

The title of all badges should be readable.

**Screenshots**

<img width="893" alt="Screenshot of the DigitalOcean App Platform Hackathon on DEV Badge" src="https://user-images.githubusercontent.com/2205212/117087707-e69e8900-ad15-11eb-92b5-55ce90c3b4e4.png">

**Desktop (please complete the following information):**

- OS, version: MacOS Catalina
- Browser, version: All browsers.

**Smartphone (please complete the following information):**

- Device: iPhone/Android
- OS, version: All
- Browser, version: All

**Additional context**

The size of the badge title is calculated dynamically based on a fixed value (`1.66vw`) and another value based on the badge title length:

https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/views/badges/show.html.erb#L5

The badge-specific value for the DigitalOcean App Platform Hackathon on DEV Badge translates into a negative number:

1. "Participant — DigitalOcean App Platform Hackathon on DEV" = 56 characters
2. 56 / 1.1 = 50 (rounded down)
3. 34 - 50 = -16

And that causes the title to have a size of zero or lower for screens smaller than 964px (also, it isn't easy to read on larger screens).

One option would be to make the badge-title size fixed for all the badges instead of depending on their length... but that should be a design decision and not my call :)

**Comment by SiddharthShyniben** [comment]
Can I work on this?

**Comment by SiddharthShyniben** [comment]
It looks like the problem is that there is a calculation of `1.66vw + -16px`. When I changed the `-16px` to `16px` (using devtools), the issue was solved.

And also, if this is available for the bug smash, can I work on this?

**Comment by SiddharthShyniben** [comment]
I guess making it absolute would fix the problem. I don't know ruby, But i guess it would look something like: 

```erb
  <h1 style="text-align: center;font-size:calc(1.66vw + <%= (34 - (@badge.title.size / 1.1).to_i).abs %>px);max-width:96%;margin: 30px auto;padding-top:8px;">🏅 <%= @badge.title %> Badge 🏅</h1>

```

**Comment by alvaromontoro** [comment]
@SiddharthShyniben that would definitely solve the problem.

To be honest, I don't fully understand why the font size needs to change from badge to badge. Why not the same for all? It seems it is so all the titles occupy (more or less) the same space, but it results in tiny titles for long badges ([the DigitalOcean hackathon badge](https://dev.to/badge/participant-e2-80-94-digitalocean-app-platform-hackathon-on-dev)) and huge titles for short ones ([the CSS badge](https://dev.to/badge/css)). It may not have a big impact on bigger screens, but the difference is considerable on smaller screens.

**Comment by SiddharthShyniben** [comment]
You are right @alvaromontoro . 

It looks like this is there for the bug smash. Can you assign me for this?

**Comment by rhymes** [comment]
@SiddharthShyniben done :)

**Comment by Link2Twenty** [comment]
Variable font size is fine but I don't think calculating it this way makes much sense. Basing it on screen width  in a `calc` seems a little odd.

That being said if you wanted to keep it fancy you could clamp the values something like 

```erb
 <h1 style="text-align: center;font-size:calc(min(max(1.5em, 1.66vw), 2em) + <%= 34 - (@badge.title.size / 1.1).to_i %>px);max-width:96%;margin: 30px auto;padding-top:8px;">🏅 <%= @badge.title %> Badge 🏅</h1> 
```

Even with this approach though once a title reaches 64 characters long the issue will come back.

___

I think the best approaches are either have a fixed size for all titles or have 3 sized depending on the length of the title.

0 - 12 _characters large font_
13 - 32 _characters medium font_
33+ _small font_

**Comment by SiddharthShyniben** [comment]
I just did a bit of math and I think hardcoding the `font-size` is OK. Something like `min(3em, 7vw)` looks good. I'll test it on a bunch of screen sizes and badge lengths and report here.

**Comment by SiddharthShyniben** [comment]
My solution looks good, expect a PR soon

**Comment by alvaromontoro** [comment]
@Link2Twenty I like the idea of clamping, but would go with [`clamp`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()) instead of combining `min` and `max`. To solve the issue with the negative values, we could move the `clamp`/`min`/`max` outside the `calc`. For example, Instead of doing this:

```
font-size:calc(min(max(1.5em, 1.66vw), 2em) + <%= 34 - (@badge.title.size / 1.1).to_i %>px)
```

you could do something like this:

```
font-size:clamp(1.5em, calc(1.66vw + <%= 34 - (@badge.title.size / 1.1).to_i %>px), 2em)
```

If the result of the `calc` is negative, the font size will be 1.5em; if the result is positive, the largest it will be is 2em.

**Comment by cmgorton** [comment]
@alvaromontoro I know you had wanted to work on this too. Just noticing it was assigned already. If this gets solved, I will make sure you get awarded for the bug smash too. Thanks for opening this issue.

**Comment by alvaromontoro** [comment]
@cmgorton it's fine. There are more tickets :)

**Comment by cmgorton** [comment]
> @cmgorton it's fine (thanks!). I'll find another ticket :)

If you find another bug in the repo not yet labelled bug smash let me know. We can probably add the label to it 😄

**Comment by Ahnaf780** [comment]
Thanks
