### ISSUE TITLE
"Follow" text missing from Podcast Liquid tag display. 

### ISSUE THREAD

**Issue by cmgorton** [forem/forem#13667]
**Describe the bug**

When using the podcast liquid tag in an article the button that should have "Follow" no longer displays the text. I tested this with several podcasts and none of them display the "Follow" text. 

**To Reproduce**
1. Navigate to the editor to create a new post. 
2. Use the podcast liquid tag to render any of the podcasts on DEV `{% podcast url-for-episode-here %}` 
3. click preview to preview the liquid tag
4. Scroll down to the rendered podcast liquid tag; it will be displayed with an empty button that should contain "Follow" 

**Expected behavior**
Follow text inside of the empty button

**Screenshots**
![Screen Shot 2021-05-05 at 9 30 24 AM](https://user-images.githubusercontent.com/21039864/117168445-631c8080-ad85-11eb-8d22-2470f1704451.png)
![Screen Shot 2021-05-05 at 9 30 57 AM](https://user-images.githubusercontent.com/21039864/117168460-657eda80-ad85-11eb-8e49-c457f8feb6cd.png)
![Screen Shot 2021-05-05 at 9 31 35 AM](https://user-images.githubusercontent.com/21039864/117168469-6879cb00-ad85-11eb-8f81-00bc5a6c2fe4.png)

Here you can see the text is not rendered at all in the HTML
![Screen Shot 2021-05-05 at 9 33 59 AM](https://user-images.githubusercontent.com/21039864/117168477-6a438e80-ad85-11eb-91bf-bc48db140c46.png)

**Comment by oryanmoshe** [comment]
I'd like to take this one as well

**Comment by cmgorton** [comment]
Great! Just assigned it to you. Thanks for the help😄

**Comment by snyntakk** [comment]
i would like to take this one

**Comment by meg-gutshall** [comment]
Looks like line 39 in your `views/podcast_episodes/show.html.erb` file is a good place to start!

**Comment by erenlerfirat** [comment]
do Bug smash have discord channel ?
