### ISSUE TITLE
Editor guide links to repl.it instead of replit.com

### ISSUE THREAD

**Issue by SiddharthShyniben** [forem/forem#13665]
**Describe the bug**

[Editor guide](https://dev.to/p/editor_guide) mentions `repl.it` instead of `replit.com` [here](https://dev.to/p/editor_guide#repl-it-embed) (The url was changed some time ago). Trivial issue but still posting it.

**To Reproduce**

Go to [The repl.it part of the liquid tags guide in the editor guide](https://dev.to/p/editor_guide#repl-it-embed)

**Expected behavior**

URL is `replit.com` instead of `repl.it`.

**Screenshots**

![repl it](https://user-images.githubusercontent.com/76640268/117157120-ef599280-addb-11eb-89e9-0f8c0121249a.png)

**Desktop (please complete the following information):**

- OS, version: All
- Browser, version: All

**Smartphone (please complete the following information):**

- Device: All
- OS, version: All
- Browser, version: All

**Additional context**

The link is also wrong in the [new post editor](https://dev.to/new)

The related file is [/app/views/pages/_editor_liquid_help.html.erb](https://github.com/forem/forem/blob/355d510f8841029e69af3a03b04c6bd282629c80/app/views/pages/_editor_liquid_help.html.erb#L230)

```erb
<h3>repl.it Embed</h3>
<p>All you need is the URL after the domain name:</p>
<code>{% replit @WigWog/PositiveFineOpensource %}</code>
```

If this is there for the bug smash, Could you assign me?

**Comment by cmgorton** [comment]
Hey @SiddharthShyniben thanks for opening this issue. repl.it will take you to replit.com. 
In the guide the wording repl.it is just a reference to creating a repl.it liquid tag and isn't meant to link to replit.com. I think having repl.it as it currently is in the guide is intentional but I will double check with the team before closing this issue. Thanks

**Comment by cmgorton** [comment]
@SiddharthShyniben talked to the team and we decided the copy can be updated. Is this something you would like to work on? If so, I can assign the issue to you.

**Comment by SiddharthShyniben** [comment]
Sure @cmgorton
