### ISSUE TITLE
Help running forem

### ISSUE THREAD

**Issue by idkwhattoputhere121** [forem/forem#13670]
I've decided to challenge myself by completing this challenge on a chromebook... yes a **chromebook** Is it possible to run this in repl.com? Sorry if I am bugging anyone about this.

**chromebook is cancer don't use it**

**Comment by citizen428** [comment]
While it's not possible to run this whole application in repl.it (I assume that's what you meant) you can run it in Gitpod which gives you a full VSCode experience in the browser while running the app in a container:

https://docs.forem.com/installation/gitpod/

**Comment by idkwhattoputhere121** [comment]
Ah thanks, hopefully you will find a bug!

**Comment by idkwhattoputhere121** [comment]
Woah thanks I never knew gitpod.io existed! Now it's running I guess I will focus on unicode bugs but thanks for the help!

**Comment by cmgorton** [comment]
Thanks for the help here Michael. I will go a head and close this issue.
