### ISSUE TITLE
Bugs in the "Copy article URL to clipboard" feature

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#13679]
When you view an article, there's an overflow menu which includes a "copy URL to clipboard" function:

![screenshot of the menu which includes the URL in a input field and a clipboard icon](https://user-images.githubusercontent.com/20773163/117275367-e0afc180-ae55-11eb-8a8c-46ecf0b059a9.png)
![screenshot of the same menu but with the message 'copied to clipboard'](https://user-images.githubusercontent.com/20773163/117275362-df7e9480-ae55-11eb-84d1-30fd28708d7c.png)

**The feature currently poses some problems for accessibility in that:**

- The URL is displayed in an unlabelled input field (readonly)
- The clipboard icon is just that, an icon. It's not a button and therefore not surfaced to keyboard users or assistive technology

**Added to this is an additional bug:**

As a mouse user, if you open the overflow menu, and click on the readonly input instead of the "copy to clipboard" button, the menu closes. If you re-open the menu, you see the notice "Copied to clipboard!" (and the text has indeed copied to the clipboard):

https://user-images.githubusercontent.com/20773163/117276488-db9f4200-ae56-11eb-9198-2fdb5aac0740.mp4

**What I suggest we do:**

I think we should remove the readonly input completely. I'm not sure there's a benefit to having it here and we would remove the accessibility issues and the above mentioned mouse-user bug if we simply made "Copy Post URL" its own option in the list, same as "Share to Twitter". We could keep the same dynamic confirmation that the URL has been copied:

![screenshot of same menu but the input has been replaced with the text "copy post URL"](https://user-images.githubusercontent.com/20773163/117277196-89125580-ae57-11eb-98d4-9814413e3146.png)

![screenshot of the same suggested menu change but the confirmation message displays below the 'copy post URL' item](https://user-images.githubusercontent.com/20773163/117277412-c4ad1f80-ae57-11eb-80e9-6d22668bef3d.png)

**Comment by sbappan** [comment]
Hi. Could I try to smash this bug?

**Comment by cmgorton** [comment]
Sure @sbappan ! I will assign it to you now. Let us know if you have any questions 😄

**Comment by sbappan** [comment]
Thanks! Will do.

**Comment by sbappan** [comment]
> Sure @sbappan ! I will assign it to you now. Let us know if you have any questions 😄

Thanks! Will do.

**Comment by cmgorton** [comment]
Hey @sbappan. Wanted to check in and see how things are going with this issue. Do you have any questions or need any help with anything?

**Comment by sbappan** [comment]
Apologies for the delay. Currently in the process of setting up forem on my local machine. I will ask for help in case I get stuck. Appreciate your patience. Thanks for checking in with me.

**Comment by sbappan** [comment]
I was able to complete the setup successfully. I started working on the issue. I will try to complete it asap.

**Comment by cmgorton** [comment]
No rush @sbappan . Just wanted to make sure you were getting help if you needed it. Thanks for helping out on this issue.

**Comment by zeotuan** [comment]
since this issue is about Bugs in the "Copy article URL to clipboard" feature, i will post this here instead of opening a new issue. Might not be a big issue since most people click away after copied to clipboard anyway. 

**Describe the bug:**

For some screen resolution, The Dynamic Confirm the message button go under the top header 
![image](https://user-images.githubusercontent.com/48720253/125573673-32a1c3b8-d756-4c02-b710-b0252e31850d.png)
my screen resolution is 1920x1080

**Comment by zeotuan** [comment]
Also i am happy to help with this issue if no one is currently working on it.

**Comment by BackendDev-Auction** [comment]
If no ones on this, I'd like to give this a shot

**Comment by vishaldeepak** [comment]
If no ones on this, I'd like to give this a shot

**Comment by sbappan** [comment]
I haven't been able to work on this issue. Sorry, @cmgorton.

**Comment by rhymes** [comment]
@vishaldeepak I've assigned to you

@sbappan thanks for trying! :)

**Comment by zeotuan** [comment]
I actually made a quick fix for this yesterday while i was looking into some other UI problem. should i create a pull request and we can work up from there?

**Comment by vishaldeepak** [comment]
@zeotuan I dont mind, but are you planning to finish the entire Issue?

**Comment by zeotuan** [comment]
@vishaldeepak I have only fix the main problem that was addressed by @aitchiss. i am going to make some test before opening the pull request for review.

**Comment by vishaldeepak** [comment]
If thats the case you might as well solve the entire thing
