### ISSUE TITLE
Hashtag "#" color is missing from flareTag 

### ISSUE THREAD

**Issue by hadiidbouk** [forem/forem#13687]
I am using `latest` API, the `flareTag` object doesn't contain the hashtag "#" color, you can see it's not the same as the `text_color_hex`.

It seems that the class that changes the color in HTML is `crayons-tag__prefix`.

```
        "flare_tag": {
            "name": "watercooler",
            "bg_color_hex": "#D0ECFF",
            "text_color_hex": "#130074"
        }
```

<img width="263" alt="Screen Shot 2021-05-06 at 11 03 56 PM" src="https://user-images.githubusercontent.com/19314956/117359494-286b3300-aec0-11eb-888f-b975b4d42f7a.png">
<img width="263" alt="Screen Shot 2021-05-06 at 11 03 39 PM" src="https://user-images.githubusercontent.com/19314956/117359496-299c6000-aec0-11eb-8b3c-bf059ed9d19a.png">
<img width="247" alt="Screen Shot 2021-05-06 at 11 03 19 PM" src="https://user-images.githubusercontent.com/19314956/117359498-2a34f680-aec0-11eb-8c1b-f044ad8b0217.png">

**Comment by rhymes** [comment]
Hi @hadiidbouk I'm not sure there's anything we can do on our part here :) The prefix is defined as:

```css
  &__prefix {
    opacity: 0.4;
    font-weight: normal;
  }
```

but that could change tomorrow, based on our design changes. You're not bound to the colors nor how DEV or other Forems style them. Given that thet hashtag itself is not even included in the name, if you're creating a presentation over the data returned from the API you're free to change the color of the hashtag as you see fit.

Let me know if this clarifies it

**Comment by Link2Twenty** [comment]
>tomorrow, based on our design changes.

Slight tangent, is that a real tomorrow or a figurative one?

**Comment by Link2Twenty** [comment]
Here's a quick formula for working out what colour is produced with opacity.

Some of the code is modified from [css-tricks](https://css-tricks.com/converting-color-spaces-in-javascript/).

```js
const bg_color_hex = "#D0ECFF";
const text_color_hex = "#130074";

const calcColor = (overlay, background, opacity) => Math.round(opacity * overlay + (1 - opacity) * background);

// modified from https://css-tricks.com/converting-color-spaces-in-javascript/#hex-to-rgb
function hexToRGB(h) {
  let r = 0,
    g = 0,
    b = 0;

  // 3 digits
  if (h.length == 4) {
    r = "0x" + h[1] + h[1];
    g = "0x" + h[2] + h[2];
    b = "0x" + h[3] + h[3];

    // 6 digits
  } else if (h.length == 7) {
    r = "0x" + h[1] + h[2];
    g = "0x" + h[3] + h[4];
    b = "0x" + h[5] + h[6];
  }

  return [r, g, b];
}

// modified from https://css-tricks.com/converting-color-spaces-in-javascript/#rgb-to-hex
function RGBToHex(r, g, b) {
  r = r.toString(16);
  g = g.toString(16);
  b = b.toString(16);

  if (r.length == 1)
    r = "0" + r;
  if (g.length == 1)
    g = "0" + g;
  if (b.length == 1)
    b = "0" + b;

  return "#" + r + g + b;
}

const bg_color_rgb = hexToRGB(bg_color_hex);
const text_color_rgb = hexToRGB(text_color_hex);
const hash_color_hex = RGBToHex(
  calcColor(text_color_rgb[0], bg_color_rgb[0], 0.4),
  calcColor(text_color_rgb[1], bg_color_rgb[1], 0.4),
  calcColor(text_color_rgb[2], bg_color_rgb[2], 0.4),
);
```

**Comment by rhymes** [comment]
> > tomorrow, based on our design changes.
> 
> Slight tangent, is that a real tomorrow or a figurative one?

What I'm actually saying is don't think the API should contain presentational info :)

**Comment by hadiidbouk** [comment]
> What I'm actually saying is don't think the API should contain presentational info :)

I totally understand, but the `flareTag` object itself contains a background and text colors, these are also presentational information 🤔, maybe the `flareTag` could be just a string? and the front end will decide how to present it?

**Comment by Link2Twenty** [comment]
> > What I'm actually saying is don't think the API should contain presentational info :)
> 
> I totally understand, but the `flareTag` object itself contains a background and text colors, these are also presentational information 🤔, maybe the `flareTag` could be just a string? and the front end will decide how to present it?

I think rhymes just means in this instance where the colour is defined with the use of opacity (which can change from theme to theme) it's not worth pushing that data in the API. Because the hash actually is `text_color_hex` just slightly translucent.

**Comment by hadiidbouk** [comment]
Thank you for clarifying 👍🏻
