### ISSUE TITLE
Installation on Docker DigitalOcean HTTP Origin header didn't match request.base_url 

### ISSUE THREAD

**Issue by edimanlmp** [forem/forem#13696]
**Describe the bug**

When installing forem using docker on digitalocean i am getting the following error:

`HTTP Origin header (http://64.227.102.95:3000) didn't match request.base_url (http://64.227.102.95:3000)`

**To Reproduce**

1. Install Forem on digitalocean following the guide for container setup
2. After installation Forem works correctly in almost all page except for login and register
3. Try to login with default username and password
4. And empty page is displayed
5. Logs shows this error:

`HTTP Origin header (http://64.227.102.95:3000) didn't match request.base_url (http://64.227.102.95:3000)`

**Note:** the URL is exactly the same from Origin header and request.baseurl

**Expected behavior**
To show login successfully or at least show error in authentication.

**Additional context**

I have tried different things but not able to solve the issue. Also i setup an nginx rever proxy with a domain however the same is issue is showing in the logs. The urls are the same with for Origin header and request base with https both

`HTTP Origin header (https://mydomain.com) didn't match request.base_url (https//mydomain.com)`

The issue seems to be only when deploying using docker, i tried the manual setup and was able to install forem and login successfully.

**Comment by djuber** [comment]
Hi @edimanlmp - I think I have a fix under review for this, I've seen the same issue when trying to use the container setup and believe it's tied to the APP_DOMAIN specified in the docker-compose.yml file (I've linked the PR to this issue).

I'm also seeing this described in https://forem.dev/manuel/forem-blank-page-after-login-using-docker-221d with what looks like the same situation (blank page after login, origin header says mismatch but gives the same url on both sides).

**Comment by djuber** [comment]
Hi @edimanlmp 

I merged #13792 yesterday 

If you wanted to pull the `main` branch and restart the `docker-compose` - I believe the issue you were seeing is resolved.
