### ISSUE TITLE
Forem.com Homepage Error

### ISSUE THREAD

**Issue by khloeabrown** [forem/forem#13695]
**Describe the bug**

Going to https://www.forem.com/ via a link on Dev.to or typing it in manually, I get a "Error compling CSS asset". I'm not familiar with what's in motion on this project nor if this is a known problem.

I've viewed the site on Chome, Firefox and Opera all without extensions to only see the same problem.

**Expected behavior**

I expect to see the homepage of the https://www.forem.com/ website. I haven't been there before so I am unsure what it looks like for reference.

**Screenshots**

Chrome & Opera:
![screenshot](https://user-images.githubusercontent.com/10980711/117579658-ec072500-b0c1-11eb-9a64-4f1c2264d123.PNG)

FireFox:
![screenshot2](https://user-images.githubusercontent.com/10980711/117579678-fe815e80-b0c1-11eb-9670-3433a3c4d647.PNG)

**Desktop:**

- OS, version: Windows 10 Home
- Browser, version: Chrome - Version 90.0.4430.93 (Official Build) (64-bit) // FireFox Developer Edition - Version 89.0b3 (64-bit) // Opera - Version 75

**Comment by cmgorton** [comment]
Hey @khloeabrown Thanks for reporting this! I believe the issue is resolved now. The site should look like this when you navigate to https://www.forem.com/ .
![Screen Shot 2021-05-10 at 8 26 27 AM](https://user-images.githubusercontent.com/21039864/117675034-7191e000-b169-11eb-8b5d-d1b47f1b8043.png)

Can you confirm it is working for you now?

**Comment by khloeabrown** [comment]
Hello @cmgorton 
Yes I can comfirm that the homepage is now working on Chrome, Opera and FireFox.
Chrome: 
![new-screenshot--chrome](https://user-images.githubusercontent.com/10980711/117675713-d0138a00-b17a-11eb-827d-4e25d09d5c76.PNG)

FireFox:
![new-screenshot--firefox](https://user-images.githubusercontent.com/10980711/117675714-d0ac2080-b17a-11eb-8eaa-5651c68d5f3c.PNG)

Opera:
![new-screenshot--opera](https://user-images.githubusercontent.com/10980711/117675717-d144b700-b17a-11eb-94a6-b08ff5a165a4.PNG)
