### ISSUE TITLE
Unable to click on the 3 dots button in the post

### ISSUE THREAD

**Issue by Starboy-Sharma** [forem/forem#13690]
**Describe the bug**
Unable to click on the 3 dots button in the post

**To Reproduce**
Open any post on the dev.to and try to click on the three dots on the right-hand side of the page

**Expected behavior**
It should show me the option of share articles and other share options.

**Screenshots**

![image](https://user-images.githubusercontent.com/31812684/117406191-5be2a780-af2a-11eb-9d5a-6c48979042a1.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Hi @Starboy-Sharma, we have a PR up that should fix it: https://github.com/forem/forem/pull/13688

Thank you for the report!
