### ISSUE TITLE
pulltorefresh issue with chat

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#13726]
**Describe the bug**
When in a long chat you may want to scroll back to a previous message but if you do this `ptr` is activated (even though you're scrolling)

**To Reproduce**
1. go to a `forem` on mobile
2. open connect
3. select a conversation with a few messages
4. try and scroll up the tread
5. see issue

**Expected behaviour**
When there is space to scroll `ptr` should not be activated

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**

- Device: Pixel 5
- OS, version: Android 11
- Browser, version: Chrome 90.0.4430.91

**Additional context**
Here is the `ptr` [code](https://github.com/forem/forem/blob/main/app/assets/javascripts/lib/pulltorefresh.js),

**Comment by itsjzt** [comment]
Came here create this issue

**Comment by dekelb** [comment]
Any update on this issue?

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
