### ISSUE TITLE
Bug: Comments dropdown open when arriving on page

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#13744]
**Describe the bug**
The comments dropdown seems to automatically open when I press back after looking at a users profile. It's always the first comment and seemingly only when I'm coming back from looking at a profile.

![image](https://user-images.githubusercontent.com/3534427/117956271-cde33400-b310-11eb-9895-cbdfeb404f1e.png)

**To Reproduce**
1. go to a post with comments
2. click on any user's profile picture
3. go back using browser navigation
4. see the menu is open.

**Expected behaviour**
Then menu should only open when I actively open it.

**Screenshots**
![forem__back-bug](https://user-images.githubusercontent.com/3534427/117956543-0c78ee80-b311-11eb-9580-1e9017e3775b.gif)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 90.0.4430.212

**Smartphone (please complete the following information):**
N/A

**Additional context**
A very minor thing in the grand scale of things but I noticed it so I'm sure others have too.

**Comment by aitchiss** [comment]
This is a really good spot - thanks @Link2Twenty!

I've double-checked and the changes I've made under #13868 will fix this (I wasn't aware of the bug before, so it's mostly a happy accident 😄 )
