### ISSUE TITLE
Styling Issues With Response Templates Buttons

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#13747]
**Describe the bug**

The moderator templates button under response templates is not styled.

**Expected behavior**

The buttons should be styled so that you can see when you click on one!

**Screenshots**

![Image 2021-05-12 at 9 28 42 AM](https://user-images.githubusercontent.com/16007075/117997048-a68c6700-b310-11eb-8148-dd425b3b01f9.png)

**Comment by cmgorton** [comment]
Adding this to the engineering planning funnel to see if someone on the frontend team should take this issue or if we should open it up to the community to work on.

**Comment by thomasbnt** [comment]
Hello ! Can I have this issue?

**Comment by cmgorton** [comment]
Assigning you to it @thomasbnt . Thanks for your help!

**Comment by thomasbnt** [comment]
Youhouuuu! Don't hesitate to notify me for this kind of modifications 👌🏼
