### ISSUE TITLE
Tags not working from RSS feed

### ISSUE THREAD

**Issue by flimzy** [forem/forem#13753]
**Describe the bug**

From the Publishing from RSS Guide (https://dev.to/p/publishing_from_rss_guide), I understand that I can include tags in my RSS feed:

> `<category>`: **tags**, comma separated. Since only 4 tags can be used in a post on DEV Community, only the first four tags will be used from the RSS item

However, the tags are consistently malformed in my posts. For example, from this XML:

    <category>scrum,extremeprogramming,practices,agile</category>

Dev.to shows me this:

> tags: scrumextremeprogramm

**Comment by rhymes** [comment]
Hi @flimzy! I think we support the `<category>` tag but according to RSS 2 spec it should be one tag per HTML element:

```

<category> sub-element of <item> 

<category> is an optional sub-element of <item>.

It has one optional attribute, domain, a string that identifies a categorization taxonomy.

The value of the element is a forward-slash-separated string that identifies a hierarchic location in the indicated taxonomy. Processors may establish conventions for the interpretation of categories. Two examples are provided below:

<category>Grateful Dead</category>

<category domain="http://www.fool.com/cusips">MSFT</category>

You may include as many category elements as you need to, for different domains, and to have an item cross-referenced in different parts of the same domain.
```

see also https://github.com/forem/forem/issues/5566#issuecomment-600840857

our publishing guide is incorrect :( 

I'll re-view it and update it. Thanks!

**Comment by flimzy** [comment]
Thanks for the prompt reply, and doc fix. I've updated my RSS feed accordingly.  :tada:
