### ISSUE TITLE
Stats API blocked by UBlock Origin

### ISSUE THREAD

**Issue by TastefulElk** [forem/forem#13804]
Stats page for an article doesn't work since the API calls are being blocket by uBlock Origin 

**Prerequisites**
1. Chrome with uBlock Origin extension installed

**To Reproduce**

1. Open an article
2. Go to "Stats"
3. All graphs empty, no error messages

**Expected behavior**
Stats to be showing even if uBlock Origin extension is active

**Screenshots**

![Screenshot 2021-05-19 at 16 45 44](https://user-images.githubusercontent.com/5831347/118833419-b6341e80-b8c1-11eb-9630-a632445a7203.png)

**Desktop (please complete the following information):**

- macOS, version: 11.3
- Chrome, version: 90.0.4430.93

**Additional context**

Although this isn't strictly a bug in the dev.to app, it's a common enough extension that I assume lots of people are going to run into this.

**Comment by TastefulElk** [comment]
I'm guessing the simples solution would be to add an exception to the [uBlock "unbreak" list](https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt)

**Comment by cmgorton** [comment]
This has been mentioned in [forem.dev](https://forem.dev/abenettt/stats-analytics-api-endpoint-blocked-by-adblocker-2f7b) as well. I am adding this issue to our engineering planning project to determine if this is something the team should work on or if we should open it up to the community.

**Comment by juliannatetreault** [comment]
@tnir `@forem-team` _should_ ping the whole team, but you could also always ping a specific portion of our team, such as `forem/javascript` or `forem/ruby` instead.

**Comment by tnir** [comment]
@TastefulElk Hi. I improved the error handling with the message in #17570 3 months ago. Could you check it out?
@Ridhwana I think we can close this by #17570 and you can close this regardless of feedback from @TastefulElk.

**Comment by TastefulElk** [comment]
The error handling is indeed improved!

**Comment by tnir** [comment]
Thanks for your confirmation.
