### ISSUE TITLE
Blog post share button is showing some of the options outside of view

### ISSUE THREAD

**Issue by hilleer** [forem/forem#13802]
**Describe the bug**

Post share button is showing the popup outside of the screen.

**To Reproduce**

1. Create a draft post (unsure if it persists for published posts as well)
2. In the left side of the screen, click on the three dots to share the post externally
3. Notice some of the selections are hidden because the top of the bar is shown "out of the screen".

**Expected behavior**

You should be able to see all the links in the popup. 

**Screenshots**

<img width="429" alt="Screenshot 2021-05-19 at 08 34 55" src="https://user-images.githubusercontent.com/9430821/118767220-c32f1e80-b87d-11eb-85b8-4ff82099df97.png">

**Desktop (please complete the following information):**

- OS, version: Big Sur 11.3.1 (20E241)
- Browser, version: Firefox 88.0.1 (64-bit)

**Comment by Link2Twenty** [comment]
I think this is a duplicate of #13195

**Comment by hilleer** [comment]
@Link2Twenty sounds correct, yes. Sorry for not finding that issue before opening a new one.
