### ISSUE TITLE
Improve the navigation admin section on mobile Safari or Forem iOS app

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#13826]
**Describe the bug**

On Dev.to with the Forem iOS app OR mobile Safari, I can't navigate to any menus within the Admin section: only the admin landing page is shown.

**To Reproduce**

- Visit `dev.to/admin` with Safari on an iPhone
- Note the admin section navigation is hidden

**Expected behavior**

Users should be able to navigate admin sections on mobile web browsers

**Screenshots**

![CleanShot 2021-05-03 at 13 44 28@2x](https://user-images.githubusercontent.com/37842/116918575-b243a380-ac15-11eb-83b0-c830a2c588ad.png)

![CleanShot 2021-05-20 at 11 13 42@2x](https://user-images.githubusercontent.com/37842/119013278-72422780-b95c-11eb-86d2-6e307de2e372.png)

**Smartphone (please complete the following information):**

- iPhone 12 Pro, iOS 14.5.1, Safari
- iPhone 12 Pro, iOS 14.5.1, Forem iOS App 1.0.1

**Additional context**

This bug was originally reported in https://github.com/forem/forem-ios/issues/54, moved to the `forem/forem` repo as it's an issue with CSS, not the iOS app per se.

**Comment by lisasy** [comment]
I'm attaching this design and this is ready for implementation. @mstruve @Ridhwana how shall we update this issue to classify this as ready for development?

![2021-05-24_Admin Portal Mobile Navigation](https://user-images.githubusercontent.com/816402/119434624-6beddb80-bccd-11eb-8689-bc2938eeb39b.jpg)

**Comment by Ridhwana** [comment]
I'll default to @mstruve on this one. Would we add it to the current Cycle work or does it need to be prioritised still? It seems like a pretty big bug to not navigate the admin at all on mobile.

**Comment by mstruve** [comment]
I added it to the board! We had prioritized the original one, this was just replacing it with one the OSS community can see :)

**Comment by cmgorton** [comment]
@fdoxyz can this issue be closed or are there more fixes to add first?

**Comment by fdoxyz** [comment]
At the time the 15min fix was merged we didn't have the building blocks to implement the design above, but we are now able to do this with the MobileDrawer.

I'm moving it to our pod's board to wrap it up and close when fully implemented the fix. Thanks for the ping @cmgorton

**Comment by joshpuetz** [comment]
Closing as this bug has been fixed.
