### ISSUE TITLE
Unable to edit or write new post on dev.to

### ISSUE THREAD

**Issue by sukhsukhpinder** [forem/forem#13822]
When I try to edit an existing post or write a new post, I get the following error in the console.

**Steps**
1. Visit dev.to click Write a Post; at first, it will allow you to copy the markdown in the post editor.
2. Once you copied, I cannot point the cursor and start writing in the post editor a second time. In a nutshell, the screen is frozen, and I am unable to do any modifications.

![image](https://user-images.githubusercontent.com/66723473/119040101-a1937b80-b9d2-11eb-84bb-9281348a481f.png)

**Comment by Link2Twenty** [comment]
This is an issue with grammarly in chrome, as a quick fix you can disable grammarly in your settings. 

Ref: #13814

**Comment by cmgorton** [comment]
Since this is a duplicate issue I am going to close this issue. Thanks.
