### ISSUE TITLE
Using triple backticks within a fenced codeblock does not work consistently

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#13823]
**Describe the bug**
When writing a fenced codeblock to show triple backticks like the following:

````
~~~
hello
```
whatever
```
~~~
````

Our markdown parser will run into the first set of triple backticks under `hello` and see that as the end of the fence, instead of going to the set of triple tildes `~`. For example, here's a screenshot of a preview:

![example of our current codeblock parsing situation](https://user-images.githubusercontent.com/17884966/119048598-720e5000-b98d-11eb-920c-97e99e0d7ebe.png)

The main issue stems from how we handle parsing the fenced codeblock ([file and lines based on `main` branch](https://github.com/forem/forem/blob/main/app/services/markdown_processor/parser.rb#L115-L126)):
https://github.com/forem/forem/blob/b3e55331428953bd517fa6f90adf48d50b7d7dfd/app/services/markdown_processor/parser.rb#L115-L126

We search for the codeblock, and then we replace the start and end markers (three backticks) with the Liquid tag `{% raw %}` and `{% endraw %}`. This conflicts a bit with our native Markdown parser gem [redcarpet](https://github.com/vmg/redcarpet) a bit, because we have the configuration option to parse fenced codeblocks enabled.

**To Reproduce**
Use the code block example above.

**Expected behavior**

We are able to parse triple backticks within "alternative" codeblock fencing options, such as:
- four spaces
- triple tildes `~`
- 4 or more backticks `` ` ``

GitHub handles the three options above pretty well. We could aim to do it in a similar manner.

Related issues:
#10421
https://github.com/vmg/redcarpet/issues/208

**Comment by aitchiss** [comment]
@Zhao-Andy just checking if I can close this following #13810? Or is there more to do?

**Comment by djuber** [comment]
@aitchiss I think there's more to do (the test case for #13810 includes a "should fail when fixed" situation) - basically while we permit triple-tilde code blocks right now, we don't effectively distinguish them from triple-backtick blocks (we're not looking for a matching closing fence delimiter, just a closing fence delimiter).

I've self-assigned since I think I understand the issue well enough to take a stab at it.

**Comment by aitchiss** [comment]
Awesome - thanks @djuber!

**Comment by djuber** [comment]
https://github.com/vmg/redcarpet/issues/208#issuecomment-52182751 it might be an underlying issue in the upstream library we're using (which may or may not ever fix it). 

Still looking.
