### ISSUE TITLE
Can't change social media links on dev.to

### ISSUE THREAD

**Issue by dylanesque** [forem/forem#13827]
**Describe the bug**

The option to edit links to GitHub and Twitter (and possibly other social links) on my dev.to profile are gone: I can see the links on my dashboard, but the option to change them in the profile via `https://dev.to/settings` is gone.

**Expected behavior**

I expect that I'm able to view and change these links in my 'Edit Profile' page.

**Comment by cmgorton** [comment]
Thanks for reporting. Our engineer that has most recently worked with this code is gone for the weekend but I will be sure to ping them on Monday to get more information on this issue.

**Comment by Zhao-Andy** [comment]
Not sure where some other profile fields went, but for GitHub and Twitter specifically those are related to whether you have connected them to your account via OAuth. To add those links, you'll have to add the OAuth connection through https://dev.to/settings/account

**Comment by dylanesque** [comment]
> Not sure where some other profile fields went, but for GitHub and Twitter specifically those are related to whether you have connected them to your account via OAuth. To add those links, you'll have to add the OAuth connection through https://dev.to/settings/account

Was this a change that occurred over time? I feel like a) I remember explicitly adding my Twitter account without using OAuth, and b) It's really annoying to not be able to easily paste visible links on a site like that.

**Comment by cmgorton** [comment]
Hey, thanks again for reporting this issue. After talking to the team it looks like this was an intentional change. You can read more about the change in [this PR](https://github.com/forem/forem/pull/13252#issuecomment-818390414) and why the team removed these profile links.
