### ISSUE TITLE
Post title and body areas are not editable

### ISSUE THREAD

**Issue by Jarjanazy** [forem/forem#13846]
I am on Windows 10, Chrome browser.
When I try to write a title or content for my post, the areas to do so are not editable. 
I can write a single letter and then it's disabled. A screenshot is attached.

<img width="925" alt="dev" src="https://user-images.githubusercontent.com/29263797/119398303-0ce59200-bce0-11eb-9b6c-6aa1ed63bc49.PNG">

**Comment by Link2Twenty** [comment]
There is currently a bug with Grammarly (and I would guess you have it installed) we are looking into. Until we have a patch out you can disable the plugin write your post then enable it again?

**Comment by Jarjanazy** [comment]
@Link2Twenty Yes that was the issue! I disabled Grammarly and it works now.
Thanks a lot. Now I can go back to blogging :)

**Comment by atapas** [comment]
> There is currently a bug with Grammarly (and I would guess you have it installed) we are looking into. Until we have a patch out you can disable the plugin write your post then enable it again?

Thanks @Link2Twenty. Disabling the grammarly plugin temporarily solves the problem. Looking forward to get the fix. Thanks a lot.

**Comment by rhymes** [comment]
Hi @atapas, thanks for the report! If you want to follow the bug I recommend you this issue https://github.com/forem/forem/issues/13846

I'm going to close this not to "disperse" the effort!

Thank you again (and thanks @Link2Twenty for the tip!))
