### ISSUE TITLE
[openapi] Settings::General is not a valid component name

### ISSUE THREAD

**Issue by MikeRalphson** [forem/forem#13843]
**Describe the bug**

Commit 6dfabd5 renamed `SiteConfig` to `Settings::General`. This name appears as a `components` `schemas` key in the OpenAPI definition. This isn't a valid component name according to the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-6):

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: `^[a-zA-Z0-9\.\-_]+$`

The character `:` cannot appear in a schema component name.

**To Reproduce**

1. `npm i -g swagger2openapi`
2. `boast api_v0.yml`

**Expected behavior**

The OpenAPI definition should validate OK.

**Comment by citizen428** [comment]
Thanks for the report. We have recently decided to remove this endpoint. While we generally do try to keep the API stable it is still v0 and this endpoint no longer makes sense in its current form. It will eventually come back once the requirements have solidified a bit.

**Comment by rhymes** [comment]
Closed by https://github.com/forem/forem/pull/13934

**Comment by rhymes** [comment]
Hi @MikeRalphson, we've removed that section from the documentation and its related code, let us know if everything works now!

**Comment by MikeRalphson** [comment]
@rhymes looking good!
