### ISSUE TITLE
Unable to edit articles

### ISSUE THREAD

**Issue by Gosev** [forem/forem#13852]
**Describe the bug**
When I try and edit an article (or create a new one) I'm unable to edit. I've tried under Chrome or Brave (which does not have any extensions).

**To Reproduce**
1. Press Create article or Edit article, 
2. try to edit/type => fail. (no cursor, no effect of typing)

**Expected behavior**
Being able to write an article :D

**Desktop (please complete the following information):**

- OS, version: Mac OS 
- Browser, version: Chrome (90.0.4430.212 ) & Brave
Haven't tried on mobile

**Comment by Link2Twenty** [comment]
Hello @Gosev we're currently having an issue with Grammarly, do you have that installed?

If you do you can disable it while you write your post then enable it again while you're done.

To track the issue subscribe to #13814

Thanks for bearing with use 😊

**Comment by rhymes** [comment]
Thanks @Link2Twenty, going to close this as a duplicate!
