### ISSUE TITLE
Cannot unfollow tag that has an alias

### ISSUE THREAD

**Issue by web2033** [forem/forem#13874]
![2021-05-28_134138](https://user-images.githubusercontent.com/11320080/119972119-83bdac00-bfba-11eb-8af4-be4fa8add6a4.png)

https://dev.to/t/tailwind now an alias of https://dev.to/t/tailwindcss
I probably followed it before these two were merged, now I can't unfollow `#tailwind` since it redirects to `#tailwindcss`

**Comment by lsparlin** [comment]
Is this available for new contributors to work on?
