### ISSUE TITLE
Right Sidebar disappear on the home page

### ISSUE THREAD

**Issue by Afif13** [forem/forem#13873]
When we are loggued and we navigate through the "week","month" or "year" tab, the right sidebar is no more visible:

![image](https://user-images.githubusercontent.com/14073250/119958007-e60ab280-bfa2-11eb-82ff-a40d85b6ee4d.png)

It's fine when we visit the site as guest.

**Comment by Link2Twenty** [comment]
Interesting it just deletes the entire content

**Comment by ellativity** [comment]
This is happening for me as well, across all Forems I'm active on. 

I use a different theme for each of my regular Forems (so I can tell where I'm at), so this doesn't appear to be theme-related either, just to eliminate that possibility.
