### ISSUE TITLE
Basic detail in profile not reflecting once updated

### ISSUE THREAD

**Issue by Pratap22** [forem/forem#13879]
**Describe the bug**
I encountered a bug while updating my profile. It's in the basic section. I added all the fields and submitted. After submission, the fields are still empty.

**To Reproduce**

1. Go to 'https://dev.to/settings'
2. Go to the Basic section
3. Add the fields. Website URL, about, etc.
4. Save the details

**Expected behavior**
It should save my basic details and be reflected in the textbox too.

**Screenshots**

![Screenshot 2021-05-29 at 10 14 23 AM](https://user-images.githubusercontent.com/19977758/120057914-cb017680-c066-11eb-81d9-5689ee03336e.png)

**Desktop (please complete the following information):**

- OS, version: macOS Big Sur
- Browser, version: Chrome, Brave

**Comment by stephfh** [comment]
I encountered the same bug just now and came here to report it. :D 

I was uploading a profile picture, and after saving my profile, the »basic profile information« section was emptied out. 

When I try to reenter the information (browser autofill or manually) again and after save the profile it's empty again.
