### ISSUE TITLE
Editor v2 upload image overlay breaks layout with small screen on upload

### ISSUE THREAD

**Issue by rhymes** [forem/forem#1389]
**Describe the bug**

Opening the upload image overlay in the v2 editor with a 13" inch screen and trying to upload an image, breaks the layout.

The content (the section direct url) also disappears below the bottom toolbar

**To Reproduce**

0. Resize the browser window (my screen is 13" with 1280x800 resolution)
1. Go https://dev.to/new with the v2 editor
2. Click on "browse" and select an image
3. See error

**Expected behavior**

The overlay should enlarge with the new content added

**Screenshots**

![noscroll](https://user-images.githubusercontent.com/146201/50351688-3d3f0a00-0543-11e9-9225-dd6db5e985bd.gif)

**Desktop (please complete the following information):**

- OS: macOS 10.14.2
- Browser: Firefox
- Version: 64

**Comment by maestromac** [comment]
Thank you for reporting this @rhymes !

**Comment by rhymes** [comment]
unstale my heart

**Comment by cyberShaw** [comment]
Can I work on this issue?

**Comment by rhymes** [comment]
Hi @cyberShaw, sure! I'm going to assign it to you :-)

**Comment by cyberShaw** [comment]
Is there any Slack or Discord for Dev.To for communication and asking for help? I'm a little new to open source :D

**Comment by ludwiczakpawel** [comment]
Fixed.

**Comment by rhymes** [comment]
@ludwiczakpawel so it can be closed?

**Comment by ludwiczakpawel** [comment]
Yes sir!
