### ISSUE TITLE
Going back to feed via home page "select" doesn't work.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#13901]
**Describe the bug**

Using the mobile select to go to "week" and then back to "feed" does not work.

**To Reproduce**

Go to "week" and then back to "feed". Nothing happens.

**Expected behavior**

It goes back to feed.

**Additional context**

I know what's causing this and will toss up a one-character fix.

**Comment by maestromac** [comment]
Resolved with https://github.com/forem/forem/pull/13902
