### ISSUE TITLE
Can't add cover image to a post

### ISSUE THREAD

**Issue by ckim328** [forem/forem#13917]
**Describe the bug**
When trying to add a cover image by clicking 'Add a cover image' to an unpublished post, or when trying to click on 'Upload image', you can't upload an image.

**To Reproduce*
1. Go to _Create Post_
2. Click on _Add a cover image_ or _Upload image_ 
3. Nothing happens

**Expected behavior**
Ability to upload image (no popup shows up)

**Desktop (please complete the following information):**

- OS, version: MacOS 11.2.3
- Browser, version: Chrome 90.0.4430.212

**Additional context**
Not sure if it's related, but when you initially click _Create Post_, it pre-populates the template with the latest post draft that you have. The behaviour before was that it would be an empty template.

**Comment by Zhao-Andy** [comment]
Thanks for reporting this issue @ckim328! I've made a fix and this issue will auto-close once https://github.com/forem/forem/pull/13919 is merged. It should work after the deployment.
