### ISSUE TITLE
Saved and shareable curated lists of saved articles

### ISSUE THREAD

**Issue by chiangs** [forem/forem#1391]
**Is your feature request related to a problem? Please describe.**
I would love to create several reading lists, or dynamically filter them and share that filtered list via a unique link to my colleagues and mates in topic specific group.

**Describe the solution you'd like**
Example use case:
 
I’m the admin for ngStavanger and would like to post up a link in our slack channel or fb group. A member clicks on it and immediately gets the curated reading list of my saved / filtered articles of Angular subjects from dev.to.

**Comment by pkfrank** [comment]
Hey @chiangs thanks for the request.  This seems related to #710.  The use-case makes a lot of sense.  Adding the "Feature Request" tag.

**Comment by jessleenyc** [comment]
Awesome. This is approved anyone who wants to jump on it.

**Comment by chiangs** [comment]
No don't close it :)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
