### ISSUE TITLE
Auto like in Comments under a Post.

### ISSUE THREAD

**Issue by maanuanubhav999** [forem/forem#13920]
**Describe the bug**
seems like whenever I try to comment on some **Post** it gets auto like, I have tried it with chromium(extensions present) and firefox(extensions absent), and in android mobile

**To Reproduce**
1. Open any post in dev.to
2. Comment On the Post
3. wait for the page to reload
4. comment appears with auto liked comment

**Expected behavior**
The comment should not contain any likes of its own.

**Screenshots**

**This is how some of my comment appear**

![image](https://user-images.githubusercontent.com/26630009/120903330-3b118d00-c663-11eb-80ec-7f5b4888c31d.png)

**This is how they should appear**

![image](https://user-images.githubusercontent.com/26630009/120903338-482e7c00-c663-11eb-9cd3-b2a3b8d2ad91.png)

**Desktop (please complete the following information):**

- OS, version: arch Linux 5.12
- Browser, version: Chromium( 91.0.4472.77), Firefox(88.0.1)

**Smartphone (please complete the following information):**

- Device: Realme Narzo 20
- OS, version: Android , 11
- Browser, version: Chrome(90.0.4430.210)

**Please Feel free to remove the issue if this was intended**

**Comment by Link2Twenty** [comment]
All comments have your like by default, it's by design. (Similar to how all Reddit posts and comments start at 1 like because the authors is implied)

**Comment by maanuanubhav999** [comment]
Okay thanks, @Link2Twenty. Then I will close this issue.
