### ISSUE TITLE
Strikethrough markdown within a link is not rendered in live comments (but works fine elsewhere)

### ISSUE THREAD

**Issue by andygeorge** [forem/forem#13935]
**Describe the bug**
While using [Strikethrough markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#emphasis) within [link text](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#links), I discovered the strikethrough is not rendered **in live comment views only**; this appears to work elsewhere (comment previews, posts, and post previews).

**To Reproduce**

Add strikethrough text within a link to a comment:
```
[~~strikethrough~~](https://www.example.com)
```

This looks fine in posts, post previews, and comment previews:
![image](https://user-images.githubusercontent.com/10601857/121033652-fe808700-c771-11eb-9471-1acd53275530.png)
![image](https://user-images.githubusercontent.com/10601857/121033703-08a28580-c772-11eb-9a5f-bbd6272c9f6a.png)
![image](https://user-images.githubusercontent.com/10601857/121033744-10622a00-c772-11eb-9205-50bf2a4f5608.png)

...but not in a submitted comment:
![image](https://user-images.githubusercontent.com/10601857/121033804-1b1cbf00-c772-11eb-95c8-f66c94ae0eef.png)

**Expected behavior**

Strikethrough markdown within link text is rendered correctly.

**Desktop (please complete the following information):**

- OS, version: Fedora Core 33
- Browser, version: Firefox 88.0.1 and Chromium 91.0.4472.77

**Comment by joshpuetz** [comment]
@cmgorton Might this be a candidate for the community or fellows?

**Comment by cmgorton** [comment]
@joshpuetz Yeah I think this would be a good one for the MLH fellows to investigate a little and work on. Because we love labels 😜 I am going to add an MLH label so I can keep track of issue like this that would be good for them to work on. Thanks for pointing it out.

**Comment by cmgorton** [comment]
@squarebat make sure you request to be assigned to this issue so our other engineers know you have been approved to work on it when they review your PR 😄

**Comment by squarebat** [comment]
I raised the PR #14103 that fixes this issue.
