### ISSUE TITLE
my request

### ISSUE THREAD

**Issue by Alexander-kdev** [forem/forem#13956]
Hello!
I can't write new posts, can you please help me???

**Comment by Link2Twenty** [comment]
Hi, couple of questions to help us track down the issue.

- do you get any errors?
- is this on dev.to or somewhere else?
- what is your username on that platform?
- When you say you can't post, do you mean you can't publish, there's not 'create post' button, you can't type into the box or something else?

**Comment by ellativity** [comment]
Hey @Alexander-kdev, please email yo@dev.to with your DEV user support query.

**Comment by cmgorton** [comment]
Closing this in favor of emailing as suggested by Ella for support issues. 

Thanks for trying to help out here @Link2Twenty
