### ISSUE TITLE
Filter user posts in profile page by tag

### ISSUE THREAD

**Issue by rhymes** [forem/forem#1396]
**Is your feature request related to a problem? Please describe.**

Some users have many posts on their profile pages, it would be nice to be able to filter those by tag.

**Describe the solution you'd like**

I envision this feature split in two sub features:

* a "tag cloud" in a box on the right side of the profile page
* when a tag is clicked the profile page reloads/refetches ony with the posts belonging to such tag

Not sure about the UX of going back to the unfiltered list

**Comment by pkfrank** [comment]
Added the `feature request` label, and look forward to discussing with the team.  Also not sure about the UX here, but this definitely makes sense — especially for authors who are particularly prolific.

**Comment by benhalpern** [comment]
I agree with this in every way except I'm unsure about the "tag cloud" part. But I wouldn't mind having that built as an MVP and then we adjust from there if needed.

**Comment by benhalpern** [comment]
@ilonacodes Yeah that makes a lot of sense!

That's an area where I feel like we could adjust some of the styling _in both places_, but it definitely makes sense to use the same UI in both places.

I think ultimately @aspittel should have a good say in this, but it's starting to make sense to me at this point.

In terms of how we use the left and right sidebars, it might make more sense on the left sidebar. And possibly start collapsed and be expandable.

**Comment by ilonacodes** [comment]
@aspittel @benhalpern 

Thank you for the feedback! 

I'd like to implement this feature. Does it make sense to start it now or should I wait?

**Comment by aspittel** [comment]
Yeah, I definitely think it looks consistent with the rest of the site. I also agree with @ben that maybe in the future we can spruce both up, but if we reuse the CSS that shouldn't be difficult to do. For profiles that are more built out, what order would this go in? Before or after badges and the other features?

**Comment by jessleenyc** [comment]
Would this also make sense as an additional search box? Or if we supported searching with specific parameters? `user: aspittel tag: ruby`?

**Comment by cmgorton** [comment]
This looks like the type of feature that would be both useful on DEV and Forem in general. I am going to add this to the feature backlog project board.

**Comment by cmgorton** [comment]
@rhymes do you think this one should be labelled with a `potential RFC` label? 
It has been around for awhile with little traction so wondering if we should either highlight this or go a head and close it. Thoughts?

**Comment by rhymes** [comment]
Mmm I don't think it's RFC material, unless the product team thinks otherwise or the design team is actually planning on revamping the profile page so that a change like this might be done in the context of a larger redesign.

**Comment by cmgorton** [comment]
This issue has gone stale. With the backlog of feature requests we currently have and are prioritizing I am going to close this issue. Maybe we can revisit it in the future. Thanks.
