### ISSUE TITLE
Disable "Locked screen" prompt if Forem is public.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#13964]
We recently shipped the ability for private Forems to set a "locked screen"— i.e. a landing page that shows up when someone lands on the site, to override the default of "sign in page"...

It only applies to private Forems, so I think it should be faded if the Forem's current config is public.

### What it currently looks like

<img width="601" alt="Screen Shot 2021-06-11 at 1 20 17 PM" src="https://user-images.githubusercontent.com/3102842/121726040-00bb4c00-cab8-11eb-992c-3741b2afc887.png">

### What it could look like if Forem is public

<img width="515" alt="Screen Shot 2021-06-11 at 1 21 39 PM" src="https://user-images.githubusercontent.com/3102842/121726076-0c0e7780-cab8-11eb-9269-fee8b2e3eb38.png">

***

We could consider hiding it all together, but if we're not sure of the holistic UX here, this small change of fading and disabling the element would bring more clarity IMO.

**Comment by citizen428** [comment]
Hmm, how about just hiding it completely for public Forems? Our admin area already can be a bit complicated at times, is it really useful to display options admins cannot interact with instead of just hiding them?

**Comment by citizen428** [comment]
@benhalpern 

> We could consider hiding it all together

In the end, that's the option I went with because based on the reactions to https://github.com/forem/forem/issues/13964#issuecomment-860342977 it seems people were in favor of a simpler admin area and only showing things admins actually can interact with.
