### ISSUE TITLE
Member nav menu should remain visible when opened by click

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#13987]
## Current behaviour

Currently, the member nav menu is visible when:

- Hovered on desktop using a mouse/trackpad
- When opened by keyboard by activating the button

https://user-images.githubusercontent.com/20773163/122029651-f43f3800-cdc4-11eb-88a1-4bf17b4092de.mp4

This is slightly different to our other crayons dropdowns which open and close on click only.

## Desired behaviour

The current implementation is pretty accessible. We communicate the dropdown open/close state, and it is operable by keyboard, handling focus as it opens and closes. However, it would be better for mouse users if it was possible to click the menu button and have the menu **stay open** until they decide to close it (by `Escape` press, click outside, or by clicking the button again).

This would particularly benefit users who might struggle with the fine motor skills required to continually hover within the dropdown area as they select a link. It would also help make sure that our dropdowns reliably conform to similar behaviours, which generally makes an interface more user-friendly for everyone.

## Considerations

- We have a helper for initializing dropdowns (`initializeDropdown`) which this menu does not currently use. In its current form, the helper won't work with this use case, as it does not expect a hover to also control the visible state of a dropdown. 

- The 'hover' behaviour isn't actually controlled by `:hover` in the CSS. The reasons for this are documented in the code, and it adds a layer of complexity to the proposed refactor - for example: if the dropdown is opened by a click on the button, we don't want the mouseout event to close it

- Whenever we do this work, we need to be sure we test on iOS touch devices and also test navigating between pages and using the menu features again. Both InstantClick and iOS native touch handling have caused bugs in this menu previously

**Comment by Link2Twenty** [comment]
This is the function where the magic happens

https://github.com/forem/forem/blob/4aebfb62f25f825fa6fc235a5e56535d4121c0ca/app/javascript/topNavigation/utilities.js#L47-L125

Looks like we could add a data attribute to say ignore mouse out (though we'd need to add click outside and esc support).

**Comment by mstruve** [comment]
@aitchiss can you put a size tag on this based on what size you think it would be? Please!

**Comment by cmgorton** [comment]
@aitchiss @nickytonline is the frontend team working on this issue? Wondering if I can give it to the MLH fellows. They have been very active this term and I think they could handle an **xs** task.

**Comment by aitchiss** [comment]
@cmgorton neither of us are working on this issue, so yep happy for it to be passed over to the MLH fellows 🙂

**Comment by zeotuan** [comment]
@aitchiss I actually did this. i will create pull request

**Comment by nickytonline** [comment]
@zeotuan, assigning this to you.
