### ISSUE TITLE
Footer links should not show up in unauthenticated private Forems

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#14005]
**Describe the bug**

In private Forems, the nav links section of the footer should be hidden.

**To Reproduce**

- Visit a private forem
- Scroll to footer and see nav section
- 
**Expected behavior**

This part of the footer is hidden.

**Screenshots**

<img width="1014" alt="Screen Shot 2021-06-16 at 6 51 18 PM" src="https://user-images.githubusercontent.com/3102842/122304855-e75d3a00-ced3-11eb-9ff9-ac2517c9d6ae.png">
**Desktop (please complete the following information):**

**Additional context**

This should be a tiny `<% if` statement. Quick fix.

The content of these links, if they are within the Forem, will not be public, but the title of the links should not be public either. It's bad UX and possible leaking of content which is expected to remain private.

**Comment by citizen428** [comment]
I hope this is ok but I was looking for a 15-minute task for the end of my work day and this caught my attention so I decided to pick it up.
