### ISSUE TITLE
Clicking `Check Invitation` in an email shouldn't automatically add user to Connect channel

### ISSUE THREAD

**Issue by ellativity** [forem/forem#14009]
**Describe the bug**

When community members are invited to join a Connect channel, they receive an email with the subject line "You are invited to the NAME channel." or "You are invited to the NAME channel as moderator." 

Within the email body there is a small amount of text with a GIF and a button labeled `Check Invitation` (see screenshots). The expected result when clicking the `Check Invitation` button would be to view a landing page that shares some info about the channel the user is invited to and provides an option to accept or decline the invitation. Instead, the user is automatically added to the channel and their entrance is announced to all other members of the channel.

**To Reproduce**

Either
1. open a sent email from the User Admin of a user who has received one (e.g. me, ellativity) 
2. click on `Check Invitation` 

Or 
1. add someone to a Connect channel via `admin/apps/chat-channels` 
2. follow steps 1-2 above.

**Expected behavior**

Either view a landing page that with info about the channel and provides an option to accept or decline the invitation, or include explicit `Accept invitation` and either `Decline invitation` button or instructions that clearly explain to click the `Accept invitation` button to accept and do nothing to decline.

**Screenshots**

![Screenshot 2021-06-17 at 15 31 22](https://user-images.githubusercontent.com/76786132/122409016-18e10e80-cf83-11eb-8b98-848745f1f616.png)
![Screenshot 2021-06-17 at 15 38 31](https://user-images.githubusercontent.com/76786132/122409021-1aaad200-cf83-11eb-91b6-a867c5c7b5ec.png)

**Additional context**

This is the Connect invitation template for all Forems, so will be affecting all users.

**Comment by cmgorton** [comment]
Since we are deprecating Connect do you think we should close this issue @ellativity ?

**Comment by cmgorton** [comment]
Never mind. I talked to Ben and we agreed all issues labeled connect should be closed. 

[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
