### ISSUE TITLE
Code blocks in embedded comments

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#14008]
**Describe the bug**
I'm not really sure how to explain this bug, it seems that code blocks in embedded comments go a little strange (display the content incorrect and have multiple expand buttons).

**To Reproduce**
1. Go to a comment with an embedded comment containing a code block ([here's](https://dev.to/nickytonline/comment/1fe8b) on I prepared earlier).
2. See that it looks wrong

**Expected behaviour**
Code blocks in an embedded comment should look the same as code blocks in a normal comment

**Screenshots**
Base comment:
![Base comment](https://user-images.githubusercontent.com/3534427/122393120-74ec6880-cf6c-11eb-91ce-1d63fe936cb8.png)

Embedded once:
![Embedded once](https://user-images.githubusercontent.com/3534427/122392877-2e970980-cf6c-11eb-88f0-ce9af64f8421.png)

Embedded twice:
![Embedded twice](https://user-images.githubusercontent.com/3534427/122393074-669e4c80-cf6c-11eb-9f5f-5b5e181cd54a.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 91.0.4472.106

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by atsmith813** [comment]
This looks similar to https://github.com/forem/forem/issues/12976

**Comment by Link2Twenty** [comment]
Right you are
