### ISSUE TITLE
Can't load more posts in reading list

### ISSUE THREAD

**Issue by dimitrov-d** [forem/forem#14016]
**Describe the bug**
I have about 230 posts saved in my reading list. I notice that initially, 80 posts are loaded and available until the bottom, where there's a "load more" button. After clicking the button, it disappears, my reading list now shows 0 posts, the previous posts remain where they were but no new posts were loaded.

**To Reproduce**

- Go to reading list
- Have at least 80 posts in reading list (I suppose)
- Click the "load more" button at the bottom of the section

**Expected behavior**

More posts are loaded and appended to the list of post

**Desktop (please complete the following information):**

- OS, version: macOS Big Sur 11.4
- Browser, version: Brave Version 1.25.73, Chromium: 91.0.4472.106 (Official Build) (x86_64). Also tested on latest version on safari, same behaviour.

**Comment by rhymes** [comment]
Can reproduce in Firefox :(

**Comment by rhymes** [comment]
@dimitrov-d should be working now 🙌

**Comment by dimitrov-d** [comment]
Sure does! Thank you for the quick fix
