### ISSUE TITLE
Swiping down in Connect channel in Android refreshes the latest view

### ISSUE THREAD

**Issue by ellativity** [forem/forem#14014]
**Describe the bug**

Instead of scrolling through the channel's chat history, swiping downwards in Connect on Android refreshes the view and resets to the most recent messages.  This was picked up by a DEV mod recently, and I'm pretty sure it's a new bug.

**To Reproduce**

1. Open DEV (version 303) or CodeNewbie (version 1) in Android
2. Open a Connect channel
3. Swipe down, as if to scroll through history

**Expected behavior**

Swiping down scrolls up through chat history.

**Smartphone (please complete the following information):**

This was initially reported by a DEV moderator, and I was able to replicate using both DEV (Version 303) and CodeNewbie (Version 1) in Android 10 on my Nokia 6.1 - both installed from Google Play Store.

**Comment by Link2Twenty** [comment]
I think this is the same as #13726 ?

**Comment by ellativity** [comment]
I think you're right, @Link2Twenty  - that did not show up in any of my searches but it's the same issue
