### ISSUE TITLE
Typo in Editor Guide

### ISSUE THREAD

**Issue by supzi-del** [forem/forem#14010]
**Describe the bug**

SlideSare should be SlideShare.

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot (210)](https://user-images.githubusercontent.com/78655439/122424970-c61c4c80-cfac-11eb-8484-b20ace8b2116.png)

**Desktop (please complete the following information):**

- OS, version: 
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by Link2Twenty** [comment]
This is where it is in the code.

https://github.com/forem/forem/blob/521bb09394b28c86e492946f912b604329dcc31f/app/views/pages/_editor_guide_text.html.erb#L273

**Comment by supzi-del** [comment]
Can I work on this?
