### ISSUE TITLE
`Liquid syntax error: Unknown tag 'endraw'` when content is placed in a certain manner

### ISSUE THREAD

**Issue by SiddharthShyniben** [forem/forem#14028]
**Describe the bug**

When I create a post content with content in the form of ``[code block] [link which contains `javascript:code` (meant to be a bookmarklet)] [code block]``, I get the following error: `Liquid syntax error: Unknown tag 'endraw'`

**To Reproduce**

Visit this [post], which already has the content, or add the following content to a post:

````markdown
```
code block
```

<a href="javascript:(()=>{})();">Bookmark me</a>
```
code block
```
````

**Expected behavior**

The code blocks and the link render properly

**Screenshots**

There is no output, just the error

**Desktop (please complete the following information):**

- OS, version: macOS 10.12.6
- Browser, version: 91.0.4472.106 (Official Build) (x86_64)

**Additional context**

None

[post]: https://dev.to/siddharthshyniben/test-bookmarklet-49pc-temp-slug-9829785?preview=22f5035a0aa16cfac0fa79e35cc052ba01f92a18143cd45ff72902d237b12a417bf70331899c565e7b249efe869175046b7f5126716e5a370e1f62ca

**Comment by cmgorton** [comment]
Hey @SiddharthShyniben . Are you trying to put the link inside the code block like this?
![Screen Shot 2021-06-21 at 12 37 07 PM](https://user-images.githubusercontent.com/21039864/122811212-6adca980-d28d-11eb-800b-b4ef628e4c9f.png)

Or did you want to add html to your post outside of a code block?

**Comment by SiddharthShyniben** [comment]
@cmgorton I was trying to put it outside.
