### ISSUE TITLE
Dropdown click outside and keyup listeners are not being properly detached

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#14030]
**Describe the bug**

Dropdowns initialized with `initializeDropdown` in `dropdownUtils.js` are intended to detach click outside and keyup listeners when the dropdown is closed. However, this isn't happening as expected, causing additional listeners to continue to be added and active between page views.

For the most part, the impact is minimal apart from creating a strange visual effect where the dropdown button is focused on returning to the page. For screen reader users and user utilising keyboard navigation however, the impact is more critical as focus is stolen, preventing the page change being announced fully and the keyboard focus position being reset properly.

**To Reproduce**

- Go to a post which has comments
- Open and close the dropdown on one of the comments
- Go back to the home page
- Return to the same post
- Notice that if you scroll down to the comment, the dropdown menu button is focused

**Expected behavior**

Click outside and keyup listeners should be removed:

- when the dropdown is closed
- when the user leaves the page (if the dropdown is open when they leave)
- focus shouldn't be 'stolen' when a user arrives back on a page they previously visited

**Screenshots**

https://user-images.githubusercontent.com/20773163/122730780-86868680-d272-11eb-90dc-da486bc980ce.mp4

**Comment by Link2Twenty** [comment]
I think this is another symptom of #11458

Similar to how keyboard shortcuts don't unmount.

**Comment by Link2Twenty** [comment]
Actually I was jumping to conclusion 😅

The problem is actually related to remove event

https://github.com/forem/forem/blob/af517bc5aaa140893ae6ddef8f3a11ce4d3d3b17/app/javascript/utilities/dropdownUtils.js#L125-L133

You can only remove the exact function so even though the functions being created by `clickOutsideListener` and `keyUpListener` are the 'same' they're different enough to not work with `removeEventListener`;

Here's a simple demo showing it not working.

https://jsfiddle.net/link2twenty/L4uzqkr2/

**Comment by aitchiss** [comment]
Yep 100% @Link2Twenty we need to make sure we have a solid reference to a named function to remove it properly.

It turns out this is causing some major headaches with the Profile Preview Card we just merged, as the preview card trigger has the same ID on every article page (so once you open one dropdown, the listeners are causing issues on every subsequent article view) 🙁  Given it's causing such a headache with current cycle work, I'm going to go ahead and fix this one asap.
