### ISSUE TITLE
X on Create A Channel Form Does Not Close the Form

### ISSUE THREAD

**Issue by cmgorton** [forem/forem#14035]
**Describe the bug**
When I clicked the Create A Channel Form I could not exit the form with the `X` button. When you click the X the form does not close. Clicking outside the form model does not close the form either. There is no way to leave the form other than to completely leave the page. 
**To Reproduce**
1. Go to https://dev.to/connect
2. Click on  the plus symbol(+) to create a new Channel
3. Instead of filling out the form try to click the X to leave the form model. 
4. You will be unable to escape the form with the X button. 

**Expected behavior**

I expect when I click on the X that the form model will close. 

**Screenshots**
![Screen Shot 2021-06-21 at 12 22 09 PM](https://user-images.githubusercontent.com/21039864/122810274-6663c100-d28c-11eb-8b35-1a8d8dac56a4.png)

https://user-images.githubusercontent.com/21039864/122810345-7bd8eb00-d28c-11eb-92b4-14fc145109e3.mov

**Desktop (please complete the following information):**

- Mac OS, version: Big Sur version 11.2
- Tried on Chrome and Firefox

**Comment by cmgorton** [comment]
@nickytonline @aitchiss I found this bug yesterday while researching a different bug that had been reported. Would it be ok if I let the MLH fellows work on this? I am assuming it is a frontend issue but wanted to confirm with you first.

**Comment by aitchiss** [comment]
@cmgorton sounds good to me. I am pretty sure this modal has somehow been missed when we implemented the focus trap behavior - whoever picks up might find it useful to checkout https://github.com/forem/forem/pull/12511 where we updated the others 👍

**Comment by cmgorton** [comment]
Awesome. Thank you for the extra info there too.

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
