### ISSUE TITLE
Profile preview card triggers too many follow requests

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#14069]
**Describe the bug**

The user preview card (#14056) has functionality which triggers a follow request on page load _for every comment on the page_. This can create a huge surplus of extra comments.

**To Reproduce**

Go to this post
https://dev.to/devteam/what-was-your-win-this-week-10c6

Open network tab of dev tools and filter for requests with `follow` and observe that it will map to how many follows there are.

**Expected behavior**

This should make use of a single bulk request. We have a bulk endpoint and a JS function which calls it. I'm not entirely certain of the ins and outs of this functionality, but re-implementing this to use that functionality shouldn't be a big problem.

**Screenshots**

<img width="209" alt="Screen Shot 2021-06-25 at 11 36 49 AM" src="https://user-images.githubusercontent.com/3102842/123450127-61fc1880-d5aa-11eb-9396-b8cc670162b3.png">

**Comment by aitchiss** [comment]
This was closed in https://github.com/forem/forem/pull/14085
