### ISSUE TITLE
shorten_urls causing link text in comments to not render correctly

### ISSUE THREAD

**Issue by squarebat** [forem/forem#14114]
**Describe the bug**
In issue #13935, @andygeorge reported that strikethrough text within links was rendered as normal text in live comments. I found out that the method `shorten_urls` in `models/comment.rb` was causing the issue and raised PR #14103 fixing it. However, I later discovered that no text formatting (bold, italics etc) is rendered within [link text](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#links) in comments.  

**To Reproduce**
Add text formatting within link text in comments:
```
[__bold-text__](https://www.example.com)
[~~strikethrough~~](https://www.example.com)
[_italic_](https://www.example.com)
[___bold-italic___](https://www.example.com)
```
This looks fine in posts and comment previews:
![preview](https://user-images.githubusercontent.com/59063821/124055478-986de380-da41-11eb-868c-f2fad3f0bba5.png)

But isn't rendered in comments (Only strikethrough works because #14103 got merged): 
![live-comment](https://user-images.githubusercontent.com/59063821/124055512-ad4a7700-da41-11eb-89b7-f4fe5d4c9cc3.png)

**Expected behavior**
Text within links should be formatted correctly in comments.

**Desktop (please complete the following information):**

- OS, version: POP_OS! 20.10
- Browser, version: Firefox 

**Additional context**

The bug occurs because `shorten_urls` in `models/comment.rb` strips out all html tags within anchor tag in the html text processed from markdown. The method is used to truncate URLs longer than ~37 characters. 

In my opinion, the best way to fix this issue is to limit `shorten_urls` to only truncate URLs and not custom link text. Doing so will also prevent any useful text from getting truncated.

**potential bug**: comment preview looks different from the final comment, because URLs aren't shortened in previews. This could be raised as another issue.

**Comment by andygeorge** [comment]
Great catch!

**Comment by squarebat** [comment]
I will take this up.
