### ISSUE TITLE
Mobile feed filters not working

### ISSUE THREAD

**Issue by reikrom** [forem/forem#14126]
**Describe the bug**

Using dropdown Feed filters (Feed, Weekly, Monthly...) throws an error and does not render results.

**To Reproduce**
*  Chrome dev tools =>  media width < 640px
* switch feed to Week, Month or Year

or

*  Dev.to android app
* switch feed to Week, Month or Year

**Expected behavior**

* show top results by selected filter.

**Desktop (please complete the following information):**

- OS, version: MacOS Big Sur
- Browser, version:  Latest Chrome, Firefox, Safari

**Additional context**

Chrome
```
issues-71092cca.js:5 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at c (issues-71092cca.js:5)
    at T (issues-71092cca.js:5)
    at v (issues-71092cca.js:5)
    at XMLHttpRequest.y (issues-71092cca.js:5)
    at XMLHttpRequest.O.e.___hb.e.___hb (issues-71092cca.js:4)
c @ issues-71092cca.js:5
T @ issues-71092cca.js:5
v @ issues-71092cca.js:5
y @ issues-71092cca.js:5
O.e.___hb.e.___hb @ issues-71092cca.js:4
XMLHttpRequest.send (async)
(anonymous) @ VM17:1
(anonymous) @ issues-71092cca.js:4
k @ issues-71092cca.js:5
(anonymous) @ issues-71092cca.js:2
O.e.___hb.e.___hb @ issues-71092cca.js:4
VM17:1 POST https://api.honeybadger.io/v1/notices/js 429 (Too Many Requests)
```

Additional errors in Safari & Firefox
```
Failed to load resource: the server responded with a status of 429 (Too Many Requests)
```
```
Uncaught TypeError: URL constructor: /top/week is not a valid URL.
```

**Comment by nickytonline** [comment]
Creating a new [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) when using a relative path requires a base parameter to be added.

You can do

```javascript
new URL('/top/week', window.location.origin)
```

instead of

```javascript
new URL('/top/week') // throws an error
```

**Comment by keshavbiswa** [comment]
I can take this up if no one's working on this
