### ISSUE TITLE
Update wording on User Account Settings page /settings/account

### ISSUE THREAD

**Issue by ellativity** [forem/forem#14120]
`/settings/account` on all Forems contain the following text:
> Set new password
As an alternative to signing in via linked social accounts, you may create a password. If you signed up with a social media account, please reset the password for your primary email address (ella@forem.com) first.

This is somewhat misleading, as even if a user creates a password for email login, an account created using authentication (e.g. all DEV accounts) will continue to be linked to the account. 

Since this is unclear for users, it causes frustration when they can't disconnect their social accounts, resulting in additional support work for Forem Admins.

**Expected behavior**

On behalf of Community Success and Forem Admins, I'm requesting an update to the wording, along the lines of:

> If your account was created using social account authentication, you may prefer to add an email log in.  If you signed up with a social media account, please reset the password for your primary email address (ella@forem.com) in order to enable this. Please note that email log in is in addition to social log in rather than a replacement for it, so your authenticated social account will continue to be linked to your account.

I actively welcome suggested edits to this.

**Comment by citizen428** [comment]
I was looking for a quick task for the end of my work week, so I did this as a 15-minute fix. It's good to go if we want to keep the current wording if people want updates I'll make them on Monday.
