### ISSUE TITLE
Article deletion times out if there are existing comments/reactions

### ISSUE THREAD

**Issue by hieptl** [forem/forem#14140]
Dear DEV Team, 

I am trying to delete my post on dev.to. However, I cannot delete it. The following error will be appeared.

Error 503 backend read error
backend read error

Guru Mediation:
Details: cache-den8245-DEN 1625503878 1223615997

Varnish cache server

This is my account https://dev.to/hieptl

In order to reproduce the bug, please following the below steps:

Step 1: Access to the dashboard.

Step 2: Find the post with the following link: https://dev.to/hieptl/learn-next-js-by-building-dev-to-57p0?preview=ae2e3e94ab0784ffb5c757cc5aa85a983735d1d0076739791bec1466958e4e1e02405670f2d7ed2ed32fa6dd113e4144b926515cde4ec38ebc76dd58 

Step 3: Click on 'Delete' button.

Step 4: Click on confirm button.

**Actual Behavior**

- The post could not be deleted.
- 503 Backend read error will be appeared.

**Expected behavior**

- The post should be deleted successfully.

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Google Chrome (latest)

**Comment by Nilomiranda** [comment]
If no one is working on this, I would like to take a look

**Comment by hieptl** [comment]
Dear Danilo,

Please help check it. I am facing this issue frequently when I want to
remove my articles.

Thanks and Best Regards,
Hiep

Vào Th 5, 8 thg 7, 2021 vào lúc 03:40 Danilo Miranda <
***@***.***> đã viết:

**Comment by Zhao-Andy** [comment]
Hey @hieptl, I believe this is timing out because you have some comments on your post. Can you try deleting your post again? I'd like to follow the request to see where the delays are happening.

**Comment by hieptl** [comment]
Hi @Zhao-Andy , I deleted my post on 23:33 pm GTM+7. Please help me check it. Thank you so much!

**Comment by hieptl** [comment]
> Hey @hieptl, I believe this is timing out because you have some comments on your post. Can you try deleting your post again? I'd like to follow the request to see where the delays are happening.
> 
> Let me know the approximate timestamp when you submitted the delete article request.

**Comment by Zhao-Andy** [comment]
@hieptl thank you! Adding this error backtrace for context:
https://app.honeybadger.io/fault/66984/6a4d48021cd0b59a5c7f3abcc58b9c91

I think we have a cascading callback issue here, where we are performing some unnecessary actions like busting caches in this context (destroying an article). Will continue to take a look into it!

In the meantime I can delete your article for you if you'd like.

**Comment by hieptl** [comment]
@Zhao-Andy: I am so glad to hear that. Please help me delete the post. Thank you for supporting me!

**Comment by Zhao-Andy** [comment]
@hieptl deleted your post :)

**Comment by hieptl** [comment]
> @hieptl deleted your post :)

Hi @Zhao-Andy , thank you so much!

**Comment by jeremyf** [comment]
@hieptl have you experienced this recently?  I believe it may be resolved in PR #15442

**Comment by jeremyf** [comment]
Closing as I haven't heard back and it appears #15442 resolves this.
