### ISSUE TITLE
Editor Guide is not available from Post Editor

### ISSUE THREAD

**Issue by ellativity** [forem/forem#14159]
**Describe the bug**
On the FAQ for every Forem ([see DEV's here](https://dev.to/faq), there's a Frequently Asked Question **Is there a guide for how to use DEV's editor?**

The answer given in the FAQ is "Yes! Here is our [editor guide](https://dev.to/p/editor_guide), you can also find it by clicking the "?" page in the [editor](https://dev.to/new)." 

![Screenshot of FAQ answering a question about an editor guide](https://user-images.githubusercontent.com/76786132/124753351-2ad22380-df29-11eb-96f0-64038f97d767.png)

Except, in the editor, there is no "?" page, and no way to access the editor guide. While there are 2 guide pages that can be accessed from the editor (Markdown and Liquid tags respectively), neither of them cover the full range of information available in the editor guide. In particular, recommended dimensions for a cover image.

![Screenshot of guides available from editor](https://user-images.githubusercontent.com/76786132/124753533-61a83980-df29-11eb-9943-227ab983c45a.png)

**To Reproduce**

1. [Open the editor](https://dev.to/new) to create a new post
2. Look for a "?" or some guidance on the dimensions for a cover image in the linked guides (markdown and liquid tags)

**Expected behavior**

- There is information available in the post editor itself to guide authors to upload their cover image successfully and tag their posts effectively.
- There would be a way to access the [editor guide](https://dev.to/p/editor_guide) from the editor, not only from the FAQ.

**Additional context**

This may require product eyes on the editor interface, to determine where the link should live. However, a short term solution could be to include a small note about cover image dimensions in the space next to the button to upload the cover image.

**Comment by rhymes** [comment]
@ellativity The FAQ is a customizable page, for example https://dev.to/faq and https://forem.dev/faq and https://community.codenewbie.org/faq are totally different pages. We should fix the FAQ for DEV sure, I think only admins can. The information about clicking `?` is probably a remnant of a previous version of the editor. We should mention any of that in the FAQ.

Regarding the editor: the guide appears as you shown appears when a user clicks in the editor's text area, if you click on "markdown" and "liquid tags", those sections will appear as a modal

**Comment by ellativity** [comment]
Thanks, @rhymes!

From what I could see, neither of those modals (markdown or liquid) fully cover the information available in the editor guide linked to in the FAQ (e.g. the cover image dimensions or [image width limit](https://community.codenewbie.org/p/editor_guide#markdown-inline-images). 

![Info not covered in either alternative guide](https://user-images.githubusercontent.com/76786132/124760310-e6e31c80-df30-11eb-9320-07e4528472a4.png)

If indeed, the FAQ on DEV is the only way to access the editor guide (which also happens to exist on every Forem, whether or not their FAQ links to it or not see [forem.dev](https://forem.dev/p/editor_guide) and [CodeNewbie](https://community.codenewbie.org/p/editor_guide)) then there should be a way for users to access it or the information it contains.

**Comment by rhymes** [comment]
Agreed, this probably requires some thought by @forem/product as the editor guide sits at `/p/editor_guide` for all Forems, like https://dev.to/p/editor_guide - https://community.codenewbie.org/p/editor_guide and that's the same for all, apparently the only way to get to the full editor guide is through the editor to leave a comment:

![Screenshot 2021-07-07 at 14-42-35 DEV Community](https://user-images.githubusercontent.com/146201/124761425-134b6880-df32-11eb-823f-1896d781e565.png)

**Comment by ellativity** [comment]
Oh wow... Raising this with Product to investigate if it is intentional, and if not what can be done about it. If it's intentional, it might be good to consider adding some guidance into the editor regarding image sizes, at the absolute minimum!

**Comment by aitchiss** [comment]
I'm going to close this issue because the editor guide now _is_ linked from the markdown toolbar in the editor (the '?' icon in the overflow menu) 🙌
