### ISSUE TITLE
Follow button creating cumulative layout shift

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#14164]
**Describe the bug**

This is a new bug showing up. This is both a user issue but also an SEO issue Google will ding us on if we don't make a quick fix. This could be a one-line fix (described below in "additional context").

More context into this kind of thing in general: https://dev.to/ben/fixing-cumulative-layout-shift-41ja

**To Reproduce**

Visit DEV post on desktop width and observe a jump in content due to follow button changing height quickly.

**Expected behavior**

Button stays the same height.

**Screenshots**

## This is what it used to look like

https://user-images.githubusercontent.com/3102842/124812659-e5662400-df31-11eb-83b1-83eb96576b0a.mov

## This is what it looks like now

https://user-images.githubusercontent.com/3102842/124812661-e5662400-df31-11eb-906d-62586e7ac2db.mov

**Additional context**

This happens because we load the text async, and we used to have a blank space in this area. There is probably a cleaner way to deal with this, but as a quick fix I'd be in favor of re-introducing this blank space.

I believe this is where it was introduced:

#14130

<img width="909" alt="Screen Shot 2021-07-07 at 2 57 52 PM" src="https://user-images.githubusercontent.com/3102842/124814206-b8b30c00-df33-11eb-8d36-1ef1bd23c242.png">

**Comment by jmau111** [comment]
@benhalpern  Hi, sorry for this, the text seems added with js :/, would it possible to add a temporary text like ";)" or even "Follow" instead of reverting?

![](https://user-images.githubusercontent.com/6878027/124820683-16644a00-df6e-11eb-8816-9a61565cce44.gif)

The former markup was commented "#yikes"

If it's possible, the fix is quick.

**Comment by juliannatetreault** [comment]
Closed via PR #14165
