### ISSUE TITLE
Post reaction buttons should make use of 'aria-pressed'

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#14182]
When reacting to a post by pressing the heart/unicorn/bookmark buttons, there's currently no feedback provided to screen reader users. When the state of the button changes we change the button label e.g. from "Like" to "Unlike". This is OK, but a screen reader user won't know that the button name has changed unless they Tab away from it, and then Tab back to it.

It would be a better user experience if we made use of the [`aria-pressed` attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#associated_aria_roles_states_and_properties) to communicate whether the reaction is currently selected or not.

To implement this change we need to:

- Keep the labels for these buttons static - e.g. 'Like' button never changes name to 'Unlike'
- Add `aria-pressed="false"` to unselected reactions
- Add `aria-pressed="true"` to selected reactions

**Comment by Link2Twenty** [comment]
For anyone that want's to tackle this here are some places to start your investigations.

https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/views/articles/_reaction_button.html.erb#L1-L16

https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/assets/javascripts/initializers/initializeArticleReactions.js#L31-L51

**Comment by keshavbiswa** [comment]
I can take a look at this if no one's looking 👀

**Comment by aitchiss** [comment]
Hey @keshavbiswa - thank you so much for adding the `aria-pressed` attributes to these buttons! There's one final part of this issue to complete before we close it off:

> - Keep the labels for these buttons static - e.g. 'Like' button never changes name to 'Unlike'

Are you keen to add this final fix too? No worries if you don't have time, just since you've already got your head around this code 😄

**Comment by keshavbiswa** [comment]
Yes Yes definitely 😄

**Comment by aitchiss** [comment]
> Yes Yes definitely 😄

Awesome - thank you! 🙌

**Comment by aitchiss** [comment]
Closed by @keshavbiswa in #14211 and #14192 - nice work! 🎉
