### ISSUE TITLE
Issue with the "work" field on the user card at the right sidebar

### ISSUE THREAD

**Issue by Afif13** [forem/forem#14188]
I think the below screenshot is self-explanatory:

>![Screenshot from 2021-07-10 01-25-26](https://user-images.githubusercontent.com/14073250/125144314-ba402800-e11d-11eb-9f89-806925a34aa1.png)

The "at XXX" is repeated twice.

after checking my profile setting I found that the field was changed to contain the extra text. I didn't do this

>![Screenshot from 2021-07-10 01-28-08](https://user-images.githubusercontent.com/14073250/125144428-2a4eae00-e11e-11eb-81aa-320c79d4f6cc.png)

I also see the same issue in many other profiles:
https://dev.to/michaeltharrington
https://dev.to/nickytonline

**Comment by Afif13** [comment]
I tried to update the field and now I have two "work" on my profile

![Screenshot from 2021-07-10 01-39-26](https://user-images.githubusercontent.com/14073250/125144900-b7463700-e11f-11eb-9d8e-664521874847.png)

**Comment by justinenz** [comment]
I have the same thing as @Afif13 :

> <img width="995" alt="Screen Shot 2021-07-11 at 5 52 20 PM" src="https://user-images.githubusercontent.com/40444785/125210974-e61ff280-e270-11eb-8ebc-0b51a725b3b8.png">

 If I go edit my profile and completely remove my work information:

> <img width="711" alt="Screen Shot 2021-07-11 at 5 55 33 PM" src="https://user-images.githubusercontent.com/40444785/125211010-39924080-e271-11eb-8789-3e24637e3905.png">

The Work section still displays on the left:

> <img width="995" alt="Screen Shot 2021-07-11 at 5 52 52 PM" src="https://user-images.githubusercontent.com/40444785/125210988-fd5ee000-e270-11eb-9d88-ebbe4baca2f8.png">

**Comment by citizen428** [comment]
Sorry for this, it should all be fixed when we merge this: https://github.com/forem/forem/pull/14206

**Comment by citizen428** [comment]
As a quick fix, we are running a script that will remove the extraneous "at <employer name>".

**Comment by citizen428** [comment]
We now deployed another quick fix so the duplicated information is no longer shown on the profile.

<img width="1038" alt="Screen Shot 2021-07-15 at 17 59 33" src="https://user-images.githubusercontent.com/47985/125777521-901f8df4-f16c-4b89-a655-e387709b6549.png">

I should have done this earlier but I didn't expect the proper fix to take as long as it did.

I'll close this issue now.
