### ISSUE TITLE
Optimise comment reaction buttons for accessibility

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#14220]
We could optimise the accessibility of our comment "Like" buttons by making them [toggle buttons](https://inclusive-components.design/toggle-button/). Currently if a screen reader user clicks the like button, there is no feedback to let them know that the state of the button is now "on", and a toggle button would solve that.

We also have very verbose label text for these buttons - they are announced to screen reader users as e.g. "Favorite heart outline button 1 like, button". We don't really use the terminology "favorite" elsewhere, so I would suggest we update this to "Like comment: 1 like". It looks like the SVG title is where we are setting this.

_As a small aside, I'm not keen about keeping the "1 like" in the button text, because 
- it will not update for screen reader users unless they move away from the button after liking it and back again
- it doesn't strictly relate to the function of the button
However, I think that's an issue for another day, as it's not immediately obvious to me how we'd want to solve that 😄_ 

When picking up this issue we can refer to the work done in #14182, but as a summary of what we need to as part of this issue:

- Change the accessible name of the comment like button to "Like comment: {number of current likes}"
- Add the `aria-pressed` attribute, with the value of 'false' when a user has not liked a comment and 'true' when they have

**Comment by keshavbiswa** [comment]
Looks a lot similar to #14182, you can assign this to me as well.

**Comment by aitchiss** [comment]
Yep definitely super-similar. Thanks for taking it on @keshavbiswa!
