### ISSUE TITLE
No UI Feedback when submitting comments that result in an HTTP 503 error.

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#14227]
**Describe the bug**

While investigating the cause of #14183, I discovered that we were not handling the case when the server returns an [HTTP 503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) error code.

https://github.com/forem/forem/blob/e50db312fb5181c674a80b0c0e86f06752be8afc/app/assets/javascripts/initializers/initializeCommentsPage.js.erb#L293-L300

If the `response.status`  is `503`, the Promise `response.json()` on line 294 will fail resulting in the member of a Forem having no idea what happened when they submitted their comment.

![image](https://user-images.githubusercontent.com/833231/125508299-4e9fedbd-3c4d-4897-9014-cac4ba4df0d8.png)

**To Reproduce**

1. This can't be produced unless the server returns an HTTP 503 error, but you can see in #14183 how it happened.

**Expected behavior**

A member of a Forem submits a comment. If there is a server error when they submit the comment, they should receive some feedback that the comment submission failed.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: N/A
- Browser, version: N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS, version: N/A
- Browser, version: N/A

**Additional context**

**Comment by zeotuan** [comment]
@nickytonline Hi! I'm pretty new and i have a question.
Doesn't the else statement of  the callback function ParseError also capture the 503 response status and show it with showUserAlertModel?
If that is not the case then is the response.json() promise get rejected without being caught?

**Comment by Link2Twenty** [comment]
@zeotuan here's a demo that might make what is going on a little clearer

<https://jsfiddle.net/link2twenty/r1a48xdk/>

**Comment by zeotuan** [comment]
@Link2Twenty Ah i got it! Thank you!
 I would like to work on this issue. can i get assigned?

**Comment by nickytonline** [comment]
I've assigned it to you @zeotuan. 😎
