### ISSUE TITLE
Old content model field for learning and hacking on fail validation

### ISSUE THREAD

**Issue by nerdfiles** [forem/forem#14235]
**Describe the bug**

Two fields with old content under the user profile fail new validation rules in form submission

**To Reproduce**

1. Go to /profile settings (I guess?)
2. Try to save data for my profile content (notice i have a timestamp update older than your changeset relating to the offending validation rule (max-length on the textarea element).

**Expected behavior**

Expects to save a profile without changing any field contents.

**Screenshots**

![Screenshot_2021-07-14-13-46-44~3.png](https://user-images.githubusercontent.com/102306/125677374-eb62a692-6ef7-4f7d-9486-d7191baa5d88.png)

**Desktop (please complete the following information):**

- OS, version: 
- Browser, version: 

**Smartphone (please complete the following information):**

- Device: G6? Android 7?
- OS, version: eh
- Browser, version: Chrome (recent)

**Additional context**

Nope

**Comment by rhymes** [comment]
I don't think this is a bug @nerdfiles, we introduced these limits a while ago (at least October 2020, but I think it predates that change). Can you alter the content of those fields to stay within limits? Thank you!

**Comment by cmgorton** [comment]
Since this looks like it is intentional on our part with the limits Rhymes mentioned I am going to go a head and close this issue. Please let us know if the validation fails while within the limits that have been set.  Thanks.
