### ISSUE TITLE
Homefeed sponsorship image bug

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#14291]
**Describe the bug**

Uploading organization images (in edit profile) works fine but when sponsors are displayed on the homefeed, a placeholder image is being used instead of the organizations images.

**Expected behavior**

Adding a sponsor to the homepage should use the sponsor's image (that they set from their org) and not a placeholder image.

**Screenshots**

![wqtqvirr8bgpe2yo6g24](https://user-images.githubusercontent.com/16007075/126386895-d49afc04-8778-4dfb-ad58-0bb68d49f862.png)

**Additional context**

Props to @leewynne who flagged this issue on forem.dev here - https://forem.dev/lee/homefeed-sponsorship-image-bug-29k2

**Comment by squarebat** [comment]
I'll take this

**Comment by zeotuan** [comment]
@squarebat i don't think there are seed data for sponsor or organization. I think the file where this is done is ```app/views/articles/_sidebar.html/erb```

**Comment by maestromac** [comment]
@squarebat to create a sponsor feature, you'll need to your own instance's super_admin (`user.add_role :super_admin`) and head to `/admin/advanced/sponsorships/new`. Let me know if anything else needs clarification.

**Comment by squarebat** [comment]
Apologies for the delay on this issue, I started tackling it and tried reproducing the bug. I created a user and an organization and used the UI to create a new sponsorship on the new org's name. The sponsorship gets created successfully with the status 'live', however I can't see it on the homefeed. The sponsors page won't display it either -
<img src="https://user-images.githubusercontent.com/59063821/129020436-452dabfa-21bb-4611-948f-b3b5d2074339.png" width=200 height=200/>
could someone help me figure this out?

**Comment by leewynne** [comment]
Hey @squarebat do you still need some help with this?

**Comment by squarebat** [comment]
@leewynne yeah, can't quite figure out a way to reproduce the bug :sweat_smile:

**Comment by leewynne** [comment]
Have you added the images to the org that you are admin of?

**Comment by squarebat** [comment]
Yes I did, however I can't see the new sponsor on the homefeed, so there's no way to see what image is being display. There's probably a setting that I am missing, but can't find it.

**Comment by leewynne** [comment]
okay, i'll share the screenshots of what I have configured 😎

**Comment by squarebat** [comment]
Update: I couldn't figure how to feature the sponsorships on homefeed, however I found out that the same bug occurs in the /sponsors page as well, so trying to fix that. The fix would probably be the same for this as well.

**Comment by leewynne** [comment]
Not sure if it helps but this is where I have them configured:

admin > customization > sponsors
<img width="1039" alt="Screenshot 2021-08-16 at 16 00 12" src="https://user-images.githubusercontent.com/12694270/129586768-a887f258-f68a-4cca-8655-733ac93bc589.png">

admin > advanced > sponsorships
<img width="1304" alt="Screenshot 2021-08-16 at 16 03 37" src="https://user-images.githubusercontent.com/12694270/129586824-6244e21d-b2e0-4c7a-8e65-689261b62305.png">

and lastly where I configure the images, my profile > edit profile > organisations

<img width="1260" alt="Screenshot 2021-08-16 at 16 05 20" src="https://user-images.githubusercontent.com/12694270/129586910-6e738f4b-8152-4c10-924d-9aada08c3f72.png">
