### ISSUE TITLE
Brand color1 is not a valid hex color and Brand color2 is not a valid hex color

### ISSUE THREAD

**Issue by AdsickTechnoholic** [forem/forem#14299]
Browser: Firefox 90
OS: Pop!_OS 21.04

when I try to switch theme I see this: 
![image](https://user-images.githubusercontent.com/87697982/126547776-6a1ea850-4be6-43c9-b3d2-8499a6960888.png)

**Comment by Link2Twenty** [comment]
What are your brand colours?

**Comment by Pkcarreno** [comment]
Browser: Chrome 91
OS: Windows 10 21H1

Same here
![image](https://user-images.githubusercontent.com/34664891/126571584-bb8499c4-e162-463e-aeb4-bed44e35c259.png)

**Comment by citizen428** [comment]
Ok, the reason for this is that the brand colors are `nil` for both of you and the validation doesn't have the `allow_nil: true` option set. IIRC we use default values if the brand colors are missing, I'll double-check that and should have a fix up soon.

**Comment by citizen428** [comment]
Update: allowing `nil` accidentally got dropped 6 days ago when we moved some code around, the above PR fixes this and will hopefully be merged soon.

**Comment by thomaslevesque** [comment]
I'm getting the same error message when trying to update any setting on the "Customization" page (or even if I just click "Save" without making any change)

**Comment by thomaslevesque** [comment]
Choosing a brand color in the profile fixes it, but I had no idea what the "brand color" was before seeing the error, so it was confusing...
