### ISSUE TITLE
This email has failed its domain's authentication requirements

### ISSUE THREAD

**Issue by dsanchezseco** [forem/forem#143]
# _Improper email forwarding_
### Current Behavior
Using Protonmail as mail server the emails coming from dev.to are marked as 

`This email has failed its domain's authentication requirements. It may be spoofed or improperly forwarded!`

As far as I know it doesn't happen on Gmail/Outlook

### Expected Behavior
Don't prompt this error.

### Additional Info (steps to replicate, device/browser, helpful links)
[Protonmail](https://protonmail.com/)
[info on reddit about similars](https://www.i.reddit.com/r/ProtonMail/comments/6g398w/emails_from_valid_domains_are_said_to_be_spoofed/)

### Screenshots
![screenshot from 2018-01-17 09-31-11](https://user-images.githubusercontent.com/20790609/35033178-eb8b9ebe-fb69-11e7-9cfa-fe098db267e1.png)

**Comment by jessleenyc** [comment]
Thanks for alerting us to this, we'll look into it.

**Comment by get2it** [comment]
Dear all,
same problem for me. Any update until now?

**This email has failed its domain's authentication requirements. It may be spoofed or improperly forwarded!**

Thanks!

**Comment by jessleenyc** [comment]
Hey! Which email did this get flagged for? Was it a "someone followed you/comment on your post", a recommended article, or our weekly newsletter (most popular posts from last week)? And was it also protonmail?

**Comment by pilot86** [comment]
I have a newsletter hosted on a domain that I own. Since I am trying out ProtonMail, I added my PM address to the subscribers, to see how it would fare, and it was delivered with the same red-bar warning as shown in the image attached above. I don't think I have any PM subscribers, but I too would like to get rid of that red flag.

**Comment by Zhao-Andy** [comment]
Hey there, we changed some email settings. Let me know if this is still an issue for you! If it's not, feel free to close the issue.

@pilot86 you might have to set up your SPF records via your DNS and domain host properly to work with either your own domain or your third party newsletter domain (like Mailchimp or something). I personally might write a post on this so I'll let you know if I do.

**Comment by milezzz** [comment]
Still happening here, this was on an email I sent out to subscribers via sendinblue.com.

**Comment by TinBuzan** [comment]
has anyone fixed this yet? My domain settings are properly hooked up &still getting the red bar

**Comment by jdoss** [comment]
@TinBuzan What exact errors are you seeing? When you say your domain settings are properly hooked up, what does that exactly mean? Are you self hosting Forem?

**Comment by milezzz** [comment]
I believe I have proper SPF and DMARC setup for my domain but this problem persists. Emails are being sent via Amazon AWS or Gmail. 
![](https://i.gyazo.com/7cd91f454de7204d9797e8f55a2bc98b.png)

**Comment by cmgorton** [comment]
This issue went stale a long time ago. I am going to go a head and close this but if anyone is still experiencing this issue please let me know and we can reopen it. Thanks.
