### ISSUE TITLE
Website URL 404 bug

### ISSUE THREAD

**Issue by FSipiano** [forem/forem#14300]
☑️Still present after disabling extensions.

**Describe the bug**

When following the link to my personal site in my Dev portfolio 'www.fayesipiano.co.uk', user is redirected to 'https://dev.to/www.fayesipiano.co.uk' which displays a 404

**To Reproduce**

Chrome browser, www.fayesipiano.co.uk in the website URL section of the header. Hit save, click on the link in the dashboard. Unexpected redirect to 404 occurs. 

**Expected behavior**

My portfolio opens in a new page

**Screenshots**

![image](https://user-images.githubusercontent.com/67593261/126552348-58e29436-13d3-4f9b-b3f1-448899cdf314.png)
![image](https://user-images.githubusercontent.com/67593261/126552416-610f4ac9-12c3-4b0b-9ec8-7c945215d3a0.png)

- OS, version: Big Sur, 11.2.2
- Browser, version: Chrome, Version 91.0.4472.114 (Official Build) (arm64)

**Additional context**

My site is built with Vue and hosted on Netlify

**Comment by FSipiano** [comment]
Extra info - the URL redirect works with the full URL set out like this, although it still doesn't feel like expected behaviour at all 
![image](https://user-images.githubusercontent.com/67593261/126553395-964f9e33-5e12-44eb-bb23-40836623e1f3.png)

**Comment by Zhao-Andy** [comment]
Thanks for this bug report! At a glance, I think the issue is because we're rendering the link as a relative link.

As you mentioned feel free to update it to the full URL for now on your profile since that is currently working.

**Comment by djuber** [comment]
@Zhao-Andy I think the issue is we're not validating (in the https://dev.to/settings page) the website url is a url (we accept any string and render links that were paths without a scheme/host as local links). 

The suggested text is "https://yoursite.com" but nothing prevents users from accidentally adding any string there (and this is automatically used to create a link, with no "fixup" to make it an external url). We can probably catch this by validating the url provided is a url and not just a string.

Just to rephrase my proposal "when a user enters a non-url string in their profile, reject input and require that it be a valid url" (this will prevent the local links based off of dev.to when we build the links).

**Comment by djuber** [comment]
Hi Faye,

I pushed out a change today that did two things:

- users are required to give a full url (including http:// or https://) when adding a website url to their profile, this prevents future confusion. The input field has hinting for this (prior to submitting the profile update) and the backend does additional checks, both will give a response indicating the url is not well formed.

- existing website urls that were relative (like yours) have been moved to include an https:// prefix (fixing the links for existing users). Website urls that were not fixable by just adding a prefix (for example if someone had added an email address in the url field) were cleared.

I confirmed your profile in dev links back to your site (and your site links to your dev.to profile). I had added an invalid website url to my own profile as well and verified that updated to be valid. 

One cosmetic change (which seems like it would be a separate issue) is that the full url is both present in the link target and the link text shown on the user profile page, I could see an argument that you only want to show "www.fayesipiano.co.uk" while still linking to https://www.fayesipiano.co.uk - right now the link looks different than it did (but works correctly, this is in line with your work-around in the comment).

![updated-link](https://user-images.githubusercontent.com/1237369/126703410-47c5e8ff-ca54-4286-bd4d-a8f2853eeda6.png)

I'm marking this issue resolved for now - but if the link presentation excluding the https part were something  you felt strongly about, feel free to open a second issue or reopen this one.
