### ISSUE TITLE
The articles endpoint is not returning the reading_time_minutes property

### ISSUE THREAD

**Issue by jbc7ag** [forem/forem#14316]
The endpoint `/articles/me` is not returning the `reading_time_minutes` property in the body as the documentation describes.

**To Reproduce**
1. Go to `/articles/me` endpoint.
2. Get the data
3. Notice the `reading_time_minutes` property is not there

**Expected behavior**
The property `reading_time_minutes` should be in the response 

**Screenshots**
![image](https://user-images.githubusercontent.com/25750639/126886982-d885f287-9257-40e8-a09b-011e52f3ccc4.png)

**Comment by rhymes** [comment]
Great catch @jbc7ag, thank you!
