### ISSUE TITLE
Admin Welcome Thread  NameError: uninitialized constant Admin::Settings::Community

### ISSUE THREAD

**Issue by omenking** [forem/forem#14315]
**Describe the bug**
I cannot create a Welcome Thread

**To Reproduce**

When attempting to create a Welcome Thread

<img width="1049" alt="Screen Shot 2021-07-24 at 9 28 13 AM" src="https://user-images.githubusercontent.com/7776/126869916-d07b4c7e-752c-4c30-9c67-a7e5fb0ba1d6.png">

I get NameError: uninitialized constant Admin::Settings::Community
<img width="643" alt="Screen Shot 2021-07-24 at 9 18 54 AM" src="https://user-images.githubusercontent.com/7776/126869899-c11d2627-a968-4c6c-8b39-d4885cabb1be.png">

The code in question
<img width="540" alt="Screen Shot 2021-07-24 at 9 24 25 AM" src="https://user-images.githubusercontent.com/7776/126869947-2d90ff0a-68a7-4e6f-9251-cff7497f8826.png">

Proof I have my community name set:
<img width="1016" alt="Screen Shot 2021-07-24 at 9 24 52 AM" src="https://user-images.githubusercontent.com/7776/126869950-16793d11-2244-4b40-adae-d33ded7f9642.png">

Proof that this file does exist on my production server

<img width="825" alt="Screen Shot 2021-07-24 at 9 26 55 AM" src="https://user-images.githubusercontent.com/7776/126869956-73011729-f5a1-4b87-af2d-8dc2cf10ae1c.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

I am running the latest version of the forem server via selfhost setup. I am not using a custom image, its base image.

Last Deployed
2021-07-24T13:16:59Z

Latest Commit ID
9303e1f

**Comment by omenking** [comment]
So this is happening locally as well.

Taking a bit more time to look at the code its pretty simple what its doing.
I don't fully understand how welcome threads work buts its my assumption that it works based off the convention of the Article title the user being set as the dev_account and being unpublished.

**Comment by omenking** [comment]
I just used Rails console to create the welcome thread. 
 Not working just yet still.
 
<img width="1038" alt="Screen Shot 2021-07-24 at 6 55 53 PM" src="https://user-images.githubusercontent.com/7776/126882848-3581ac87-c72a-48b0-be61-fc92af11c592.png">


<img width="869" alt="Screen Shot 2021-07-24 at 6 55 56 PM" src="https://user-images.githubusercontent.com/7776/126882847-40350af8-038c-4371-a1d3-10d716142a23.png">

**Comment by omenking** [comment]
I flipped to published. So I guess I just need to make a welcome thread that follows a particular title? 
<img width="935" alt="Screen Shot 2021-07-24 at 6 59 29 PM" src="https://user-images.githubusercontent.com/7776/126882893-f3f63081-c287-4bbe-a2f1-c98aa52327fd.png">

**Comment by citizen428** [comment]
Thanks for the report @omenking, let me try something real quick.

**Comment by citizen428** [comment]
The problem was the constant lookup, it should be `::Settings::Community` (start constant lookup from the root, not relative to the `Admin` namespace. PR incoming.

**Comment by citizen428** [comment]
Closing this since the PR has been merged. If you still have issues after you updated please feel free to reopen @omenking.
