### ISSUE TITLE
Create the admin confirmation email template

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#14376]
## Descripton

As part of the admin onboarding, an admin onboarding email template needs to be created. It's possible that it's currently the same email template for non-admin users.

# Related Issues & Documents

- [Admin Onboarding. Experience](https://github.com/forem/rfcs/blob/a8d843d9a37c4105850f575f6e51faac7377a474/text/0190-admin-onboarding.md#email) (email section)
- [Figma](https://www.figma.com/file/VRmjMjAbRWmNzyzLZWS77q/Admin-onboarding)

## Investigation (from Slack convos)

@nickytonline:  I've never worked with emails in the project, but I dug a bit, and it looks like account_ownership_verification_email.html.erb and account_ownership_verification_email.txt.erb is what's used for anyone that onboards? Confirm their email, then start onboarding? Is that correct? I wasn't able to find anything admin specific in terms of onboarding, which is very possiblw as @Ridhwana wasn't sure if it was a separate template or not.

@Zhao-Andy: account_ownership_verification_email is actually for a one-off case when we have a user claiming to be someone, and we send this out via /admin/users to verify they own the account (and associated email address) in question.

For confirming emails in general (ie. changing emails, first signing up via email) this happens through the Devise gem, and because we don't have any custom HTML or styling for that email, we use the default email.html.erb and email.txt.erb that's done by the gem -- and therefore, no file for it within app/views/mailers.

If you're trying to make a brand new email for admins to welcome them with an onboarding email, I would look into the classes in app/mailers and follow some code patterns there. IMO, Rails' docs are pretty good at explaining how the email backend works in general: https://guides.rubyonrails.org/action_mailer_basics.html

**Comment by citizen428** [comment]
@nickytonline "actual confirmation email"? Do you maybe mean "admin confirmation email"? Also, should we add a "form team" label here, it doesn't seem like this is an issue meant for external contributors.

**Comment by nickytonline** [comment]
> @nickytonline "actual confirmation email"? Do you maybe mean "admin confirmation email"? Also, should we add a "form team" label here, it doesn't seem like this is an issue meant for external contributors.

Ahh, yeah, I generated this issue from a card on our board. I'll make the changes you mentioned.
