### ISSUE TITLE
[API] "tags" and "tags_list" property switched when request article as list and/or as single article

### ISSUE THREAD

**Issue by remshams** [forem/forem#14396]
Hi,

while using the API I noticed that the `tags` and `tags_list` properties are switched when requesting a list of articles and a single article.
Here is the list version:

![article-list](https://user-images.githubusercontent.com/10899354/127763926-310123d7-28a5-42ef-8351-cbb419e5a701.png)

Here the same article requested by `articleId` or `path`

![article-single](https://user-images.githubusercontent.com/10899354/127764086-b5df1a54-0a92-4776-a191-ac16a9cf817f.png)

As visible in the screenshot, in case of the list `tags` contains the tags as comma separated list and `tag_list` as string array. For the `articleId` and `path` version `tags` contains the array and `tag_list` the comma separated version.

Just wanted to know if this is on purpose as I now/then have to perform different conversions into domain models depending on whether a single or a list of articles is requested.

As probably expected the issue does appear independent of any query parameters and can therefor reproduced by requesting any list of articles and then a single article from the list.

Thanks

**Comment by rhymes** [comment]
Hi @remshams, unfortunately it's a known bug that can't really be fixed without breaking the API, so in v0 it'll have to remain as it is :)

You can find further details here: https://github.com/forem/forem/issues/4637

Thank you for the report!

**Comment by remshams** [comment]
I already worked around it ;)

Thanks for replying and sorry for missing the already created issue.
