### ISSUE TITLE
Follow button in "full discussion" mode doesn't work

### ISSUE THREAD

**Issue by dekelb** [forem/forem#14415]
**Describe the bug**
When on a post - it's possible to follow an author of a comment by hovering it's name and clicking on the "Follow" button.
When on the full discussion page - clicking on the "follow" button does nothing.

**To Reproduce**
1. Find a post that has a lot of comments.
2. Scroll down and click on the "View full discussion" button.
3. Find a commenter that you are not following yet.
4. Hover it's name and click on the "Follow" button.

**Expected behavior**
1. Button should change from "Follow" to "Following".
2. The user should be added to the list of the users you follow.

**Screenshots**
![screencast 2021-08-04 12-28-12](https://user-images.githubusercontent.com/6668575/128157753-af43546b-8a1f-4f90-808a-3f8f73a662d9.gif)

**Desktop (please complete the following information):**
- OS, version: MacOS Big Sur
- Browser, version: Chrome 92.0.4515.107 (latest to date)

**Comment by aitchiss** [comment]
Nice catch @dekelb - thanks for opening this issue! I did some refactoring recently on follow buttons, and it seems I neglected this page - I'll have a fix ready very shortly 👍

**Comment by dekelb** [comment]
@aitchiss thanks for the fast reply and fixing this issue 😀.
Another question - what is the deployment process to dev.to?
 Now that it's fixed & merged - how much time till we can see this in production?

**Comment by aitchiss** [comment]
@dekelb the change is already deployed to dev.to, so it should all be good to go now 🚀  Sometimes caching causes individual pages to take a moment to update though 🙂

**Comment by dekelb** [comment]
If it still doesn't work (after hard-refresh), can I assume there is still some bug there? Or should I wait a few more hours?
