### ISSUE TITLE
Listing details modal doesn't close on navigation event triggered from it

### ISSUE THREAD

**Issue by fyodorio** [forem/forem#14459]
**Describe the bug**

⚠️ _This might be a feature not a bug, though it's quite confusing so I'm reporting it anyway to figure out if the described behavior expected or not_

When a user goes to the Listings page and opens a modal for one of the available listings, they can click a category link at the bottom to navigate to the corresponding listing category (filter the list out in fact). This action should close the modal to actually communicate that the navigation event has happened, but the modal stays open and the navigation (including the URL change) happens on the background which is hardly distinguishable. 

**To Reproduce**

1. On the main page (dev.to) click `See all` in the Listings block to navigate to the Listings page
<img width="1786" alt="Screenshot 2021-08-10 at 16 29 37" src="https://user-images.githubusercontent.com/19417873/128860688-b201a1cc-06e3-41f4-af3d-67dff5aea708.png">

2. Click on the title of some of the displayed listings to open the details modal
<img width="1782" alt="Screenshot 2021-08-10 at 16 30 10" src="https://user-images.githubusercontent.com/19417873/128860779-8b8e3aee-7cd3-4382-865f-0b8f8d4c5d03.png">

3. Click on the category link at the bottom of the modal 
<img width="1791" alt="Screenshot 2021-08-10 at 16 30 56" src="https://user-images.githubusercontent.com/19417873/128860921-c28b759b-f11d-4f90-a01a-28d74820c403.png">

4. Navigation happens, URL changes (correctly), **_modal stays open_**

**Expected behavior**

_Modal window should close on the navigation event and user should be navigated to the route they expected to get to (the clicked listing category)._

**Desktop (please complete the following information):**

- OS, version: macOS 10.15.7
- Browser, version: (browser-independent) Brave, Chrome, Safari, Firefox

**Smartphone (please complete the following information):**

- Device: iPhone
- OS, version: iOS 14.7.1
- Browser, version: (browser-independent) Brave, Safari

**Additional context**

When user has the modal opened and navigates using browser controls (back/forward) the URL change doesn't follow the actual route/page change. So this issue probably requires some additional attention in terms of router behaviour.

_The issue is especially blocking on mobile devices - as the modal is full-screen there, clicking the category link doesn't lead to anything visually distinguishable at all._

Also, talking about the mobile behaviour, for some reason I needed to click a listing title twice to navigate to the corresponding listing (probably this needs to be reported separately though).

**Comment by cmgorton** [comment]
@forem/frontend this does seem like a weird UI interaction but wanted to check to see if this is intentional behavior.

**Comment by aitchiss** [comment]
Nope definitely not intentional - I think this is a bug and the modal should close 👍

**Comment by gertay** [comment]
I'll sort this bug if that's grand?

**Comment by fyodorio** [comment]
@nickytonline would be happy to try 🙂
