### ISSUE TITLE
Reading list is not reactive

### ISSUE THREAD

**Issue by SiddharthShyniben** [forem/forem#14469]
**Describe the bug**

The reading list item count (in the title) isn't reactive. If I archive a post, the count won't change.

Before:
![before](https://user-images.githubusercontent.com/76640268/128962302-bf65e61b-44dc-4128-8e31-c6d6f2209fd0.png)

After:
![after](https://user-images.githubusercontent.com/76640268/128962209-b9ea50bb-6839-4704-9e3b-74cac6e99dcb.png)

**To Reproduce**

0. Add a few items to your reading list
1. Go to your [reading list](https://dev.to/readinglist)
2. Archive an item
3. See the mistake

**Expected behavior**

The number of items decreases when an item is removed

**Screenshots**

![screen](https://user-images.githubusercontent.com/76640268/128962209-b9ea50bb-6839-4704-9e3b-74cac6e99dcb.png)

**Desktop (please complete the following information):**

- OS, version: MacOS Sierra (10.12.6)
- Browser, version: Chrome 92.0.4515.131 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device: Vivo V2029
- OS, version: FunTouch OS PD2034BF_EX_A_1.70.17 (Basically android)
- Browser, version: Chrome 92.0.4515.131

**Additional context**

NA

**Comment by haoxilu** [comment]
It's going to be fixed in the ticket https://github.com/forem/forem/pull/14471.
