### ISSUE TITLE
Code blocks get breaks added between each line

### ISSUE THREAD

**Issue by abraham** [forem/forem#1446]
**Describe the bug**
Code blocks sometimes get breaks `<br>` added between each line. You can see it in the one codeblock on [A month of Flutter: a look back](https://dev.to/abraham/a-month-of-flutter-a-look-back-1j1a#annotatedregion). It appears to be related to having headers following the code blocks.

**To Reproduce**

Go to [create a new post](https://dev.to/new) enter the following markdown and hit "preview".

```
~~~
function hello() {
  console.log('hello');
}
~~~

~~~
function goodbye() {
  console.log('goodbye');
}
~~~

# header
```

**Expected behavior**

The code blocks should not have any blank lines between each line of code.

**Screenshots**

Correct display when `# header` is not included:

![screenshot from 2019-01-02 14-17-11](https://user-images.githubusercontent.com/3341/50610638-50ce6700-0e99-11e9-9fc1-6fe4c6d80770.png)

Incorrect display when `# header` is included:

![screenshot from 2019-01-02 14-17-00](https://user-images.githubusercontent.com/3341/50610645-562bb180-0e99-11e9-8a51-54eecd27f333.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.10
- Browsers: 
  - Chrome 72.0.3626.28
  - Firefox 64.0

**Additional context**

The broken display only appears to happen when a header follows the code blocks. If I move it between or before the code blocks the breaks don't happen. I'm using v2 of the editor and have not tested with v1.

**Comment by jessleenyc** [comment]
Interesting, had no idea `~~~` was another way of creating code blocks. We'll look into this. But for now, you might want to try the ` ``` ` syntax for creating code blocks. Seems like the back ticks don't create that additional space when a header is included.

**Comment by abraham** [comment]
Still an issue.

**Comment by redencion** [comment]
Hi guys! I would like check it, May I?

**Comment by citizen428** [comment]
Sure, I'll assign you the issue @redencion, thanks for volunteering! 😃

**Comment by redencion** [comment]
Is it normal?  when I'm running bin/spring rspec, I got a fail test. I just cloned twice repository and again fail the test. I followed this flow https://docs.forem.com/getting-started/workflow/

**Comment by redencion** [comment]
I did PR but something is wrong, added option draft.

**Comment by alicenstar** [comment]
Is this still an issue? If so, I would like to take a crack at it.

**Comment by cmgorton** [comment]
Yes it is @alicenstar . I will assign it to you. Let us know if you have any questions and thanks for your help here!

**Comment by alicenstar** [comment]
@cmgorton I am running into an issue setting up the project. I followed all install and setup instructions, but after running `bin/startup` and running the project locally, I get a `URI::BadURIError at /. Both URI are relative` error when visiting `localhost:3000/`. I looked in `.env_sample` and `APP_DOMAIN` is set to `localhost:3000`, so I'm not sure where to go from here.

It cites the error as happening in `app/lib/url.rb` on the `URI.parse` line:
```
  def self.url(uri = nil)
    base_url = "#{protocol}#{domain}"
    return base_url unless uri
    URI.parse(base_url).merge(uri).to_s
  end
```

I am new to Ruby so any assistance or nudge in the right direction is greatly appreciated. (I am running the project on Ubuntu 20.x on WSL2 if that helps.)

**Comment by cmgorton** [comment]
Hey! I'm away from my computer until the morning but I pinged our OSS devs to see if any can offer assistance. I'll follow back up in the morning if you haven't received a response before then 😁

**Comment by alicenstar** [comment]
I managed to fix the issue - I'll work on this tomorrow now that I have my environment set up. :)

**Comment by cmgorton** [comment]
Awesome! If you run in to any more issues just let us know.

**Comment by alicenstar** [comment]
Well, unfortunately I am running into more issues. I'm on a Windows machine and my motherboard apparently can't handle having virtualization enabled without shutting down randomly multiple times a day, so I tried to switch to GitPod, but I can't get the project to run locally. I get `Command ["foreman start -f Procfile.dev"] failed` (which I was also getting in Ubuntu/WSL2) in the first terminal, and `Awaiting port 3000... ` in the second terminal (it just stays frozen there).

**Comment by cmgorton** [comment]
@alicenstar Thanks for sticking with this through all the errors. I think this might be similar to what another contributor encountered. Here is there comment and if you read below that there is a solution from one of our engineers. Can you let me know if that helps at all?
https://github.com/forem/forem/issues/13298#issuecomment-833590511

**Comment by alicenstar** [comment]
Thanks for pointing me to that comment - it helped!

**Comment by alicenstar** [comment]
Trying to log in as the default admin user in my local environment (so that I can create a comment and test some things) and I am getting this error:
```Started POST "/users/sign_in" for 10.138.0.20 at 2021-05-06 18:10:13 +0000
18:10:13 web.1       | Cannot render console from 10.4.11.9! Allowed networks: 127.0.0.0/127.255.255.255, ::1
18:10:13 web.1       | Processing by Devise::SessionsController#create as HTML
18:10:13 web.1       |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"admin@forem.local", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Continue"}
18:10:13 web.1       | HTTP Origin header (https://3000-white-carp-g4fs8ci6.ws-us03.gitpod.io) didn't match request.base_url (https://3000-white-carp-g4fs8ci6.ws-us03.gitpod.io)
18:10:13 web.1       | Completed 200 OK in 4ms (ActiveRecord: 0.0ms | Allocations: 2977)```

**Comment by cmgorton** [comment]
Asking in our internal dev channel to see if anyone can help.

**Comment by msarit** [comment]
are you logging into `localhost` or `127.0.0.1`?

**Comment by Link2Twenty** [comment]
Looks like it's gitpod?

>Open your .env and change APP_DOMAIN to "your own Gitpod Forem URL without https". Change APP_PROTOCOL to "https"

<https://forem.dev/akhil/aftermath-on-clicking-open-in-gitpod-581b>

**Comment by alicenstar** [comment]
I was attempting to login through GitPod, so maybe that was the issue. I'm trying to recompile now, it's just taking a minute. Things keep freezing.

**Comment by Zhao-Andy** [comment]
Hi @alicenstar, I'm using Ubuntu 20.x and WSL2 as well! I followed our [Windows guide](https://docs.forem.com/installation/windows/) to setup, and it seems like you were most of the way there since you got to run `bin/startup`. If you find that GitPod is not working out that well, happy to help you triage your Windows setup.

The error message  `Command ["foreman start -f Procfile.dev"] failed` usually is indicative of the server failing to boot -- if you want to post the full error message we'll be able to help you see what's going on.

**Comment by alicenstar** [comment]
@Zhao-Andy I had to switch to GitPod because my motherboard apparently can't handle having virtualization enabled without shutting down randomly multiple times a day. I got the project to run fine otherwise, but the random shut downs weren't going to work for me.

I think GitPod's servers might be slowing down this `bin/startup` process because I've been waiting for it to finish compiling for about an hour now (it's still not done). I'll be able to evaluate any other errors once that's done loading.

**Comment by Zhao-Andy** [comment]
@alicenstar gotcha, thanks for the clarification!

**Comment by alicenstar** [comment]
I think I may possibly have fixed this issue. I am trying to run tests now to be sure, but I am running into an error when trying to run any test (using `bundle exec rspec spec/relevant_test_folder`): `FATAL:  database "Forem_test" does not exist`.

I tried changing my `.env` file to this (hard-coding the database name since that was a problem for me before), but I still get this error.
`.env`:
```
DATABASE_NAME_TEST=Forem_test
DATABASE_URL_TEST=postgresql://localhost:5432/Forem_test
```

**Comment by rhymes** [comment]
Hi @alicenstar, can you create the DB manually in the GitPod console? I can think of two options:

1. `createdb Forem_test`
2. `psql Forem_development` and then you issue `CREATE DATABASE Forem_test` in the PostgreSQL console

Let us know if that helps, and thank you!

**Comment by cmgorton** [comment]
@alicenstar thanks again for pushing through all these set backs. 
You are doing a wonderful job and we are definitely here to help however we can.

**Comment by cmgorton** [comment]
Hey @alicenstar wanted to check in and see how you are doing with this issue. Did you have any questions or need any help?

**Comment by alicenstar** [comment]
Hey, sorry! Got a little busy the past couple weeks! I'll try to test my solution tonight just to verify it works

**Comment by cmgorton** [comment]
No worries! We all get busy. Take your time and test it whenever you get a chance. Thanks again for your help.

**Comment by alicenstar** [comment]
I unfortunately think I'm going to have to pass issue this to someone else for now. I'm low on time because of my new job, and I'm running into some issues with GitPod.

That's something I want to try to work on (the docs and possibly augmenting the GitPod setup). Hopefully someone can test the work I've done here or use it as a starting point possibly.

**Comment by cmgorton** [comment]
Thank you for the work you have done so far @alicenstar . We really appreciate it. 🙏

**Comment by ThirashaPraween** [comment]
There a another way to add this. try ` ``` ` instead of ` ~~~ `.  Also, combine them together with one code block.

```
function hello() {
  console.log('hello');
}
function goodbye() {
  console.log('goodbye');
}

```
