### ISSUE TITLE
bin/startup fails in production

### ISSUE THREAD

**Issue by yheuhtozr** [forem/forem#14484]
**Describe the bug**

`.env`:
```
...
RAILS_ENV="production"
NODE_ENV="production"
...
```

terminal:
```
$ bin/startup
== STARTING UP ==
18:43:02 web.1       | started with pid 22360
18:43:02 webpacker.1 | started with pid 22361
18:43:02 sidekiq.1   | started with pid 22362
18:43:04 webpacker.1 | webpack dev_server configuration not found in /home/username/forem/config/webpacker.yml[production].
18:43:04 webpacker.1 | Please run bundle exec rails webpacker:install to install Webpacker
18:43:05 webpacker.1 | exited with code 1
18:43:05 system      | sending SIGTERM to all processes
18:43:05 web.1       | terminated by SIGTERM
18:43:05 sidekiq.1   | terminated by SIGTERM

== Command ["foreman start -f Procfile.dev"] failed ==
```

**To Reproduce**

As above.

**Expected behavior**

Not sure. I expected a file in the repo to contain a right configuration to start up the app in the production mode, but:

- `bin/startup` (Procfile.dev)
  As described above, no dev server ought to run.
- Procfile
  Contains a `bin/start-pgbouncer` which I found no trace of in the repo.
- Docker files
  I am not good at reading them, but as I understand is that they run rails without sidekiq?

Currently I generate a daemon from Procfile.dev without the `webpacker: ./bin/webpack-dev-server` and it runs with no big issues, but not felt optimized either.

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04

**Comment by cmgorton** [comment]
Hey @yheuhtozr before helping you here can you clarify a few things for us? 

Are you trying to set up Forem for local development to contribute to the Forem codebase? 
or
Are you trying to set up a Forem for production like you can with our [Self-host](https://github.com/forem/selfhost) repo?

**Comment by yheuhtozr** [comment]
Hi,

> Are you trying to set up Forem for local development to contribute to the Forem codebase?
or
Are you trying to set up a Forem for production like you can with our Self-host repo?

On the latter side. I'm building an instance based on Forem code base, with some necessary extension for our community. It's not intended to be another new software, at least I expect users to use them mostly in the same way as on DEV.TO.

**PS**

Yes I did borrow some useful things from the selfhost repo, such as the nginx config, but when I read its instruction I assumed that the app itself is for running a fixed Forem image, rather than allow me to edit the code with trials and errors (feel free to correct). And while I mentioned "production mode", I have to admit that I am still unsure if I haven't been able to figure out the correct button, or the app has not much room for optimization and the performance mostly comes from the optional plugins.

**Comment by cmgorton** [comment]
Hey @yheuhtozr if you are trying to use Forem to create a Forem for your community (feel free to correct me if I am wrong here) I would suggest using forem/self-host. Forem is the software that runs DEV. 

If you would like to understand more about customizing your Forem for your communities needs, I would suggest checking out[ forem.dev](https://forem.dev/) if you haven't already. There are a lot of Forem creators there. Andrew Brown for instance has [several posts](https://forem.dev/andrewbrown) on setting up his Forem and extending it for his communities needs.

**Comment by yheuhtozr** [comment]
I see, thank you for the pointer. As I can log in forem.dev normally now, I'll try to find any information and ask something there.
