### ISSUE TITLE
Duplicate "Display email on profile" checkboxes in user settings

### ISSUE THREAD

**Issue by AlexanderGenin** [forem/forem#14497]
**Describe the bug**

There are two identical checkboxes "Display email on profile" in User Settings: one in "User" section and another in "Basic" section. The "User" checkbox seems to control the state since toggling it also changes the state of the second checkbox (when the page is reloaded). However the second checkbox (in the "Basic" section) returns to the previous state after toggling when the page is reloaded.

**To Reproduce**

1. Go to User Settings
2. Open Profile Tab (opens by default)
3. Try toggling the checkbox in the "User" section and reloading the page (the state will change)
4. Scroll down and do the same in the "Basic" section (the state won't change)

**Expected behavior**
I presume the checkbox in the "Basic" section was initially meant for showing/hiding user's website's LINK on user's profile (not email)

**Screenshots**

- First checkbox

![screenshot](https://user-images.githubusercontent.com/55929549/129392244-32f77d5d-b42a-45b8-b4ae-b623ebd85413.png)

- Second checkbox

![screenshot2](https://user-images.githubusercontent.com/55929549/129392266-23e90463-f5b8-479b-bde2-99cc01fbf244.png)

**Desktop:**
- Browser, version:
Google Chrome
Версия 92.0.4515.131 (Официальная сборка), (64 бит)

**Comment by cmgorton** [comment]
Yes I agree. I think  "Display email on profile" in the **Basic** section should correlate with the Website URL so like you mentioned the text should read "Display website on profile".

Thanks for opening this issue.

**Comment by diegocasmo** [comment]
@cmgorton 

I took a look at the code, and the `users_settings` table doesn't seem to have a `display_website_on_profile` column (only a `display_email_on_profile`). So, I was wondering if the goal of this issue is just to remove the checkbox that's shown below the Website URL (as it doesn't have anything to do with the user's website), or to actually implement a feature that supports showing/hiding a user's website depending on their preferences?

**Comment by citizen428** [comment]
> So, I was wondering if the goal of this issue is just to remove the checkbox that's shown below the Website URL input (as it doesn't have anything to do with the user's website), or to actually implement a feature that supports showing/hiding a user's website depending on their preferences?

This seems like the most sensible approach to me. I don't think we need to add a hide feature for website URLs, if a user doesn't want to show it, they just don't enter it. For emails that's not the case as we also use them for things like password recovery.
