### ISSUE TITLE
Cannot edit the post

### ISSUE THREAD

**Issue by ufukeskici** [forem/forem#14535]
**Describe the bug**

I cannot edit my post: https://dev.to/ufukeskici/my-meachine-learning-journey-2e5n
After I click "publish" it remains in "publishing" state.

**To Reproduce**

Edit the post and try

**Expected behavior**

**Screenshots**

Attached to he post.

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Opera (Version:77.0.4054.277) & Chrome (Version 84.0.4147.135 (Official Build) (64-bit))

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

<img width="650" alt="Capture1" src="https://user-images.githubusercontent.com/17970139/129898245-545bebf5-239d-44c2-a62a-446f0d2ce582.PNG">
<img width="654" alt="Capture2" src="https://user-images.githubusercontent.com/17970139/129898253-82474f37-d1d8-45ff-840b-82ef5dabb08b.PNG">

**Comment by rhymes** [comment]
Hi @ufukeskici, do you have any sort of error in the browser console when you do that?

**Comment by ufukeskici** [comment]
No, it's still in publishing state. If I close the window, and re-login, I see the update on markdown page but not on the published page  (I mean I see the old post online, but I see the new post in "edit" markdown page".

Somehow publishing is not being reflected to the post but reflected to markdown page only. Weird...

**Comment by rhymes** [comment]
@ufukeskici can you try to publish without extensions enabled or from another browser? Sometimes extensions get in the way. Though I see you tried with both Opera and Chrome already.

**Comment by ufukeskici** [comment]
Yes, indeed. :(

Please check the attached screenshot files. The markdown page is the edited one. But it still does not reflect the changes to the public page.  Public page has still the old version of the post.

<img width="516" alt="markdown_page" src="https://user-images.githubusercontent.com/17970139/129914967-ad471812-5991-489d-b463-5e08be0787d0.PNG">
<img width="517" alt="online_post" src="https://user-images.githubusercontent.com/17970139/129914978-e278d3d4-064a-4944-906d-71a9c13fb445.PNG">

**Comment by ufukeskici** [comment]
It worked with Chrome after disabling extension as you suggested before. 

Will this be investigated further or should I close the case for now?

**Comment by rhymes** [comment]
@ufukeskici if it's an extension I'm not sure we can do much on our side but maybe you can try enable them one at a time to figure out which one it is and report back, this can help others if they run in the same issue

**Comment by ufukeskici** [comment]
I enabled all extensions on Chrome but now everything works fine.

**Comment by rhymes** [comment]
I'm going to close this then! Thanks @ufukeskici
