### ISSUE TITLE
Email is not displayed properly in the User Profile

### ISSUE THREAD

**Issue by madzadev** [forem/forem#14541]
**Describe the bug**

Email is not displayed properly in the User Profile

**To Reproduce**

Open User Profile (dev.to/username)
See email displayed as `true`

**Expected behavior**

The User email from dev.to/settings is displayed

**Screenshots**

![1629324288_538x47](https://user-images.githubusercontent.com/42511917/129978555-9573b816-9cf6-4b65-be88-4dba5384b473.png)

**Desktop (please complete the following information):**

- OS, version: Win10, x64
- Browser, version: Chrome, 92.0.4515.131

**Comment by djuber** [comment]
I can confirmed - this happens to me as well on the profile page after showing email.

the mailto link is correct (hovering over the envelope icon shows my email address) but the text shown is "true".
