### ISSUE TITLE
Podcast page's follow button not showing text

### ISSUE THREAD

**Issue by maestromac** [forem/forem#14553]
**Describe the bug**
The podcast button on any podcast's page is not showing any text. I can't tell whether or not I am following a podcast.

**To Reproduce**
visit any podcast's page, _signed in or signed out_, ie https://dev.to/practicaloperations

**Expected behavior**
Should be showing me status

**Screenshots**
Notice that the button is just empty.
![image](https://user-images.githubusercontent.com/15793250/130122548-b8ca4cf9-b63f-4203-8c80-0dbd66cbbe75.png)

**Desktop (please complete the following information):**
It's happening on all browsers and all operating systems.

**Additional context**
/a

**Comment by djuber** [comment]
Possibly related to https://github.com/forem/forem/pull/14246 ?

**Comment by aitchiss** [comment]
> Possibly related to #14246 ?

I think this is exactly what it is - the button doesn't have text, but it's also not triggering the follow action. I think I can 15-min-fix this
