### ISSUE TITLE
Errors when posting posts and editing + DM msgs don't send

### ISSUE THREAD

**Issue by Yuma-Tsushima07** [forem/forem#14567]
**Describe the bug**

When posting a post and/or editing posts the 500 and 502 error comes up.
Also DM messages don't send.

**To Reproduce**

**When Editing**
 1. Go to your dashboard and click on any post
 2. Click on edit
 3. Edit your posts
 4. You will see the 502 error.
 
 **When Posting**

1. Go to create posts
2. Make a post
3. Then it redirects you and gives 500 error

**When DMing someone**

1. Go to dm 
2. Type a message
3. Message won't send

**Expected behaviour**

**When Editing**
When editing a post the post which has been edited should be updated.

**When Posting**
You should be able to make a post.

**When DMing**
You should be able to dm someone.

**Screenshots**
![image](https://user-images.githubusercontent.com/63207324/130448198-27b7b382-c161-4833-8008-d2caece4d411.png)

![image](https://user-images.githubusercontent.com/63207324/130448648-0b667110-2439-4d6d-98c2-d484b8582345.png)

https://user-images.githubusercontent.com/63207324/130449873-81f06d61-47ac-4f1d-bb09-c1203ba615c5.mp4

**Desktop (please complete the following information):**

- OS, version: OS, version: Windows 10
- Browser, version: Firefox (latest)

**Smartphone (please complete the following information):**

- Samsung Note 9
- OS, version: Dev.to App (Current Version)

**Comment by rhymes** [comment]
Hello @Yuma-Tsushima07, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
