### ISSUE TITLE
Trying to change username results in a 503 error.

### ISSUE THREAD

**Issue by simskij** [forem/forem#14615]
**Describe the bug**

Trying to change username results in a 503 error.

**To Reproduce**

1. Go to the settings page
2. Change your username to something else
3. Press save
4. See 503 error below

**Expected behavior**

Username to change. In my case from `0x12b` to `simme`.

**Screenshots**

![Screenshot 2021-08-28 at 22 18 56](https://user-images.githubusercontent.com/1596025/131230110-612eb2af-3d4a-4329-b5d5-8d7abfa8e65b.png)

**Desktop (please complete the following information):**

- OS, version: MacOS Big Sur
- Browser, version: Chrome, evergreen

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by simskij** [comment]
Been discussing this with @michael-tharrington in the dev.to chat prior to posting here.

**Comment by mirie** [comment]
I'm not sure what caused this, but this looks like a very old issue. I tried to replicate this on two different Forem instances and didn't experience this problem.

Please feel free to re-open if the issue still persists for you with more information to help us diagnose. Thanks!
