### ISSUE TITLE
Unable to view Stats for posts in my organization 

### ISSUE THREAD

**Issue by eldadfux** [forem/forem#14669]
**Describe the bug**

I'm unable to watch stats for posts in the organization where I'm the administrator. I can only view stats for post I'm the author of. When clicking on the `Stats` button for posts in my organization, I get an 404 page.

**To Reproduce**

1. Go to your dashaboard
2. Switch to your organization
3. Go to a post you didn't write
4. Click on the `...` button, and then `Stats`
5. You get an `404` page

**Expected behavior**

I expect to see the posts stats.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Mac, latest
- Browser, version: Chrome, latest

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by aitchiss** [comment]
Thanks for opening this issue - I was able to reproduce the same behaviour 👍 

It makes sense that the admin of an organization should be able to see the stats for all posts on their dashboard, not just the ones they've authored themselves.

**Comment by twinsfan421** [comment]
I can work on this

**Comment by citizen428** [comment]
Thanks @twinsfan421, I assigned you the issue now.
