### ISSUE TITLE
seeds.rb occassionally generates listings which fail validation

### ISSUE THREAD

**Issue by djuber** [forem/forem#14683]
**Describe the bug**

`Faker::Markdown.random` (used in the `Listing.create!` section of the seeder) sometimes generates bodies that exceed 12 newlines:

```
pry(main)> 10_000.times.map { Faker::Markdown.random.lines.count > 12 }.tally
=> {false=>9986, true=>14}     
```

We validate this in [`Listing#restrict_markdown_input`](https://github.com/forem/forem/blob/main/app/models/listing.rb#L81-L86) to ensure 12 or fewer newlines are allowed.

If bin/setup is called on an empty database, and this error is encountered - the seeds will stop (and any execution after this step will have failed to execute).

**To Reproduce**

This relies on the "random" output of faker, but the case above shows it happens about 1 time in 1000.

**Expected behavior**

Generated seed data is valid, bin/setup does not fail when building listings.

**Comment by citizen428** [comment]
Maybe easiest if we just update `seeds.rb` with something like this:

```ruby
Faker::Markdown.random.lines.take(10).join
```
