### ISSUE TITLE
Clicking "Follow" [a tag] does nothing

### ISSUE THREAD

**Issue by paul-j-lucas** [forem/forem#14704]
**Describe the bug**

Clicking the **Follow** [tag] button does nothing, i.e., does _not_ add a tag to the set of tags I follow.

**To Reproduce**

1. Go to a tag's page, e.g., `https://dev.to/t/cpp`.
2. Click the **Follow** button.

**Expected behavior**

`#cpp` would be added to the set of tags I follow.

**Desktop (please complete the following information):**

- OS, version: macOS 11.5.2
- Browser, version: Safari 14.1.2 and Chrome 93.0.4577.63

I've tried _both_ browsers: same (non)behavior.

**Additional context**

This must have worked sometime in the past since I follow `#c` and `#go`.

**Comment by djuber** [comment]
@paul-j-lucas I'm able to replicate this (the cpp tag cannot be followed on dev). 

I'm seeing there's a syntax error reported from followButton.js (in the function that adds the event listeners to the follow button) - this appears to be a bug in our handling of user supplied usernames which are not escaped for json serialization (so we're sending json data that's not handled correctly by the front end - and actions that relied on processing this data are not completed)

https://github.com/forem/forem/blob/42c9a10f577a0a43673b6eafff5853d20f058240/app/javascript/packs/followButtons.js#L316 is the location where the error is reported. 

This appears to narrow down the problem on the page:

```javascript
buttons = document.querySelectorAll('.follow-action-button.follow-user:not([data-fetched])');

Array.from(buttons, (button) => { 
  console.log(button.dataset.info);
  [JSON.parse(button.dataset.info)]
})
```

the console log showed a few users in order, but [one](https://dev.to/acc3ssd3n13d) (with a cpp tagged article) had a name "Error401: "Name not authorized"" which was causing a parse error for the button - this led to the tag's follow button having no action (it doesn't respond to the click, which is what you reported). I checked that the php tag does permit follow actions, and the 100daysofcode tag (also used by this user) does not - this narrows it down to bad input handling on our end.

**Comment by djuber** [comment]
To widen/specify this a little further:
- the broken follow functionality also applied to user pages where the user name has a quote in it, like https://dev.to/andyj115 (user name is "mi" and the follow button is broken).

**Comment by mrsantons** [comment]
May I be assigned to this issue?

**Comment by cmgorton** [comment]
You have been assigned to the issue @mrsantons . Let us know if you have any questions and thanks for helping out!

**Comment by djuber** [comment]
This still happens if you scroll down far enough (for me it was page 14 - articles from September including https://dev.to/acc3ssd3n13d/first-day-of-learning-c-nb6 retrigger the original condition.

When this was reported the post was in the first page of results in the feed, so impacted the initial load.

Currently - visit /t/cpp - click follow - button works.
Scroll down through several loads of additional feed content until the linked article is loaded

Click follow at the top of the page - button no longer works, and a JSON parse error (unhandled syntax error) is shown in the console.

**Comment by jeremyf** [comment]
I believe #16067 closes this issue.
