### ISSUE TITLE
Include search term in search results page title and heading

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#14735]
While going through some accessibility tutorials on Deque, I came across some best practice guidance for page titles (i.e. the name shown in the browser tab for the given page). For the most part, our page titles tick all the boxes, but our search results page could benefit from some tweaks.

![Screenshot of course materials stating "If a page is the result of a user action or scripted change of context, the text of the <title> SHOULD describe the result or change of context to the user". The example given is to include the search term in the search results page title.](https://user-images.githubusercontent.com/20773163/133392058-ddaab982-5e63-4fd5-98b6-701680ad0fd0.png)

Currently our page title for search results is "Search results - {community name}". Following this guidance we should update on search term change to e.g. "{search term} - Search results - {community name}".

The course materials also stated the importance of the `<h1>` element reflecting the topic of the page acccurately. In this case that would include restating the search term and the "search results":

>The page <title> SHOULD match (or be very similar to) the top heading in the main content.
Both the title (<title>) and the top heading in the main content (ideally marked with `<h1>`) serve essentially the same purpose: to give the page a title. With this in mind, it usually makes sense to match the page title and the top heading with identical text, or at least very similar text. There is some room for slight variations. For example, you might put the website brand at the end of the page title but not in the main heading for the content. Redundancy is a good thing in this case, because it allows users to see the page title whether they're viewing the tabs in a browser, listening to a page load with a screen reader (the title is the first thing screen readers read), or reading through the main content.

Our `<h1>` on this page is "Search results". We should update to include the search term, e.g. "Search results for '{search term}'". This reduces the cognitive load required to understand the current search results page, and also more accurately reflects the page purpose to screen reader users checking the `h1` for context.

## Summary

Let's change:
- The `<title>` of the search results page to include the search term:  "{search term} - Search results - {community name}"
- The `<h1>` of the search results page to include the search term:  "Search results for '{search term}'"

**Comment by metamoni** [comment]
Hi! I have a wee PR ready to go for this one ☺️

**Comment by aitchiss** [comment]
Just an update here that we now have an `h1` with the full context for the search results page (🎉 ), but we can still usefully change the `<title>` element to include the search term too  🙂
