### ISSUE TITLE
Updating authentication configs causes a redirect to a JSON response

### ISSUE THREAD

**Issue by fdoxyz** [forem/forem#14749]
**Describe the bug**

When editing Authentication configs in `/admin/customization/config` I get redirected to a JSON response from `/admin/settings/authentications`

**To Reproduce**

1. Open local development environment and enable social authentications.
2. Save the changes
3. You'll end up in `/admin/settings/authentications` with a JSON response (the update is successful to edit the configs)

**Expected behavior**

We possibly want to see a confirmation modal for these changes and then a refresh of the page or modal (Snackbar) message that the changes were successful (or display errors).

**Screenshots**

The bug that I see:

https://user-images.githubusercontent.com/6045239/133675361-1be68540-4b91-4eac-bb33-ef2740e1fee4.mov

**Desktop (please complete the following information):**

- OS, version: MacOS 11.5.2
- Browser, version: Chrome 93.0.4577.63 (Official Build) (arm64)

**Additional context**

I debugged a bit and I'm getting to `enabledProvidersWithMissingKeys()` in the `ConfigController` where were trying to access the value of a `null`:

<img width="691" alt="Screen Shot 2021-09-16 at 13 41 58" src="https://user-images.githubusercontent.com/6045239/133676073-3c88b00d-d131-43e6-9177-b6e18478675e.png">

<img width="1440" alt="Screen Shot 2021-09-16 at 13 42 17" src="https://user-images.githubusercontent.com/6045239/133676338-83b7da77-7418-4b26-af6e-55f64145fb60.png">

**Comment by djuber** [comment]
I've seen this as well. Thanks for reporting this!
