### ISSUE TITLE
Error when removing tags from post using moderator panel: "TypeError: window.parent.document.getElementsByClassName(...)[0] is undefined" 

### ISSUE THREAD

**Issue by ellativity** [forem/forem#14754]
**Describe the bug**

Error when removing tags from post using moderator panel: 

"TypeError: window.parent.document.getElementsByClassName(...)[0] is undefined" 

**To Reproduce**

1. Go to a post on DEV that needs to have a tag removed
2. Open the moderator tools panel by clicking on the purple shield icon in the bottom-right corner
3. Scroll down to **OTHER THINGS YOU CAN DO > Adjust tags**
4. Click the ⛔️ icon beside a tag to select it for removal and enter a removal reason in the text box below
5. Click the **Submit** button
6. Modal appears with the following error: "TypeError: window.parent.document.getElementsByClassName(...)[0] is undefined" and tag is removed

**Expected behavior**

Tag is removed without an error modal appearing

**Screenshots**

![Screenshot 2021-09-17 at 13 15 43](https://user-images.githubusercontent.com/76786132/133774287-a514b45b-5a2c-4fd6-b2e2-ed8b6cad23b3.png)

**Desktop (please complete the following information):**

- OS, version: macOS Big Sur 11.5.2
- Browser, version: Firefox 92.0

**Additional context**

This has happened with same OS/browser combo on dev.to (see above screenshot from 17 September) and forem.dev (see following screenshot from 13 September):

![Screenshot 2021-09-13 at 18 42 12](https://user-images.githubusercontent.com/76786132/133774390-08810a3c-16a4-49bd-a184-92c8d4d4fb91.png)

**Comment by citizen428** [comment]
@aitchiss Maybe you have an idea about this: I think the problem arises in `renderTagOnArticle` where it tries to look for an `ariticle-iframe` class which it can't seem to find. Could it be that the fix introduced [here](https://github.com/forem/forem/pull/14566) for `/mod` and `/mod/<tagname>` is the reason this no longer works from the modcenter?

**Comment by aitchiss** [comment]
> @aitchiss Maybe you have an idea about this: I think the problem arises in renderTagOnArticle where it tries to look for an ariticle-iframe class which it can't seem to find. Could it be that the fix introduced here for /mod and /mod/<tagname> is the reason this no longer works from the mod center?

Yes I think that's exactly what's going on 🙈  I think I can sort a quick fix for this
