### ISSUE TITLE
Top bar always black in Safari 15

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#14783]
**Describe the bug**

On Safari 15, the top bar is jet black regardless of a Forem's accent color and user's light/dark mode setting.

**To Reproduce**

- Visit https://dev.to (or any other forem)
- Note the top bar is black.

**Expected behavior**

We should be using either the Forem's accent color or the header color from a user's theme to set the color of the Safari browser top chrome.

Safari 15 [added support for the theme-color meta tag](https://developer.apple.com/documentation/safari-release-notes/safari-15-beta-release-notes) to change the tab bar background and over-scroll area in macOS and iPadOS, and the status bar in iOS. We should utilize it!  

**Screenshots**

Mac OS 11.6:
![CleanShot 2021-09-21 at 08 58 52@2x](https://user-images.githubusercontent.com/37842/134192630-061a2f04-2328-4b44-b1d4-35fc40c59cec.png)

iOS 15.0
![IMG_0893](https://user-images.githubusercontent.com/37842/134193017-ee614737-55f1-4857-9d76-5e1e69360076.jpeg)

**Desktop (please complete the following information):**

- OS, version: Mac 11.6
- Browser, version: Safari 15

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro
- OS, version: iOS 15.0
- Browser, version: Safari 15

**Additional context**

Apple docs on "theme-color" meta tag: https://developer.apple.com/documentation/safari-release-notes/safari-15-beta-release-notes

WWDC session (with bonus CodeNewbie cameo!) https://developer.apple.com/videos/play/wwdc2021/10029/?time=125

**Comment by wheezykw** [comment]
@joshpuetz Can you verify that the black bar you are seeing on Safari 15 isn't from something else like a bookmarks bar in Safari? I have a Vanilla version of Safari 15 and I'm not seeing the black bar when going to https://dev.to.

**Comment by rhymes** [comment]
@wheezykw I have Safari 15 which I never use and I'm not even logged in on DEV and I see the black bar:

https://user-images.githubusercontent.com/146201/135979027-9e277794-23e4-432a-b0fd-d3ba719f3672.mov

**Comment by joshpuetz** [comment]
I've confirmed it on a fresh install of Mac OS 11.6 without any extensions or plugins.
