### ISSUE TITLE
Reading list doesen't update when a post unpublished (Deleted also ?)

### ISSUE THREAD

**Issue by Posandu** [forem/forem#14796]
**Describe the bug**
The reading list doesn't update when a post deleted

**To Reproduce**

Make a post.
Save it to the reading list.
Delete that post.
Go to the reading list.
The saved post is still there, but when clicking it this page comes (Because the post was deleted)

**Expected behaviour**
The item should be removed when the post is deleted/unpublished.

**Screenshots**
![image](https://user-images.githubusercontent.com/76736580/134468026-812b2942-1022-41f4-9281-d96b82a4066d.png)
![image](https://user-images.githubusercontent.com/76736580/134468036-44bf19c0-0f70-4a75-abc1-ece807c44862.png)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by metamoni** [comment]
I was going to pick this up, but I can't reproduce it.

https://user-images.githubusercontent.com/22390758/134821192-5819ee35-c374-49c2-9dd4-b70e419a9357.mov

**Comment by Tronic247** [comment]
See this https://www.awesomescreenshot.com/video/5386431?key=cb61f6991b16636a11926a7bc3860db7

**Comment by metamoni** [comment]
I see. So in your video the post isn't deleted, it's unpublished. I'm guessing it's still on the Reading List because it's your own post and you can view your own unpublished posts. Will wait for someone to confirm the expected behaviour. If this is a bug I'd be happy to take it on.

**Comment by cmgorton** [comment]
Thanks for testing this @metamoni . I'll try to test it out with a coworker tomorrow so we can see if they save my post and I delete my post if it will disappear from their reading list. I think your assumption about why @Tronic247 is still seeing the post in their reading list is correct but will try to confirm and let you know!
