### ISSUE TITLE
Right Sidebar Not Able To Scroll On PC

### ISSUE THREAD

**Issue by egoTr** [forem/forem#14806]
**Describe the bug**
On my computer, when I'm in a post with a sidebar on the right which shows **User profile** and **More articles**
👉 I can not scroll the sidebar to view more.

**To Reproduce**
1. Go to a post
2. Navigate to the right sidebar
3. Try to scroll
4. Can not scroll

**Expected behavior**
The sidebar should scroll for showing more info.

**Desktop (please complete the following information):**
- OS, version: Windows 10 | macOS Big Sur
- Browser, version: Microsoft Edge 94.0.992.31 (Official build) (64-bit) | Safari 15.0 (16612.1.29.41.4, 16612) | Google Chrome 93.0.4577.82 (Official Build) (arm64)

**Additional context**
The sidebar is fully shown in narrow width or on mobile.

**Comment by citizen428** [comment]
This is indeed a bit unintuitive, the sidebar does not scroll independently. If you scroll down far enough it will eventually catch up with the main content.

**Comment by lyqht** [comment]
would like to give this a try!

**Comment by cmgorton** [comment]
Thanks @lyqht ! I assigned it to you. Let us know if you have any questions.

**Comment by lyqht** [comment]
hello @cmgorton, wondering if this suffices for the fix!

![scroll-whole-sidebar](https://user-images.githubusercontent.com/35736525/135895008-cd669ca1-fd33-48f8-91a4-f6a9733cb8bf.gif)

the scrollbar won't appear for sidebars that do not exceed the length. 

Or would Forem prefer the scrollbar to only appear for the article card section below the author information card?

**Comment by ludwiczakpawel** [comment]
I believe, the ideal solution in our case would be replicating behavior of Twitter which you can preview in video below:

https://user-images.githubusercontent.com/108287/135900909-2cd11f62-352f-42ca-a71d-f17767f5c9ab.mov

(Ignore the sticky search bar) 
Whenever necessary (small viewport height), it basically scrolls WITH entire viewport for the initial part of scrolling event and then it just sticks - no matter which direction. Unfortunately I believe it's not just CSS but also JS however it's way better than providing a separate scroll for sidebar.

**Comment by aitchiss** [comment]
@lyqht I've unassigned you from this issue following our discussion on https://github.com/forem/forem/pull/14917 - thanks again for all your hard work on this tricky issue!

Whoever picks this up next, please see the conversations and work in progress detailed on https://github.com/forem/forem/pull/14917.

**Comment by PhilipHow** [comment]
Working for me now.
