### ISSUE TITLE
Flag user text in Moderator modal is DEV-specific

### ISSUE THREAD

**Issue by ellativity** [forem/forem#14836]
**Describe the bug**

When moderators on all Forems click on **Flag user** at the bottom of the moderator panel, a modal appears to confirm the user action that reads

>**Flag User**
>Thanks for keeping DEV safe. Here is what you can do to flag this user:

>**Make all posts by this author less visible**
This author consistently posts content that violates DEV's code of conduct because it is harassing, offensive or spammy.

This should display the individual Forem's name, rather than DEV on all Forems.

**To Reproduce**

1. Ensure you have moderator privileges enabled
2. Navigate to a post and click on the Mod Panel button in the bottom-right
3. Click on **Flag user** at the bottom of the Mod Panel
4. Modal opens with text that needs to be updated

**Expected behavior**

>**Flag User**
>Thanks for keeping *Forem name* safe. Here is what you can do to flag this user:

>**Make all posts by this author less visible**
This author consistently posts content that violates *Forem name*'s code of conduct because it is harassing, offensive or spammy.

**Screenshots**

![Screenshot 2021-09-23 at 12 34 06](https://user-images.githubusercontent.com/76786132/135071132-69da309d-6e5f-428b-ada9-3a0ec6ac6df0.png)

**Comment by citizen428** [comment]
For anyone picking this up, it's in `app/javascript/packs/flagUserModal.jsx`.

**Comment by leonyangela** [comment]
Hello, is this task still open?? can I take this task? Thank you

**Comment by Mr-DG-Wick** [comment]
I had a doubt, won't it be fine for dev too that a flagged user will be less promoted on its platform. 
Or are we simply just considering it for the individual forem? Please guide me on this.

**Comment by cmgorton** [comment]
Asking about it now @Mr-DG-Wick. Will let you know how to proceed as soon as I get a response :)

**Comment by cmgorton** [comment]
Hey @Mr-DG-Wick after talking to one of our engineers they said:  "It's not that we don't want this to also be available on DEV only that we want other Forems to show their community name (rather than DEV) in the moderation dialog" 

As you can see in the screenshot above when a moderator on DEV, CodeNewbie, Forem.dev or any other Forem, flag a user they see the name "DEV" like "Thanks for helping to keep DEV safe" instead of their specific Forem name. So we are looking to find a way to generalize this so that each Forem's name is added to the modal instead of only DEV

Dose that make sense? Do you have any other questions?

**Comment by Mr-DG-Wick** [comment]
> Dose that make sense? Do you have any other questions?

Sure it does. Thanks. What is the tech stack required to solve this issue?

**Comment by msarit** [comment]
Hello @Mr-DG-Wick! 👋🏾 
Here is some guidance for you (or another) in approaching this issue:

As @citizen428 said, the Flag User modal is generated in the file [flagUserModal.jsx](https://github.com/forem/forem/blob/main/app/javascript/packs/flagUserModal.jsx) as a Preact component. The word `DEV` is hardcoded in the `FlagUserModal function` around lines [125](https://github.com/forem/forem/blob/8b96f32f95f2020407ecf8abfde722ecb3e3160b/app/javascript/packs/flagUserModal.jsx#L125) and [148](https://github.com/forem/forem/blob/8b96f32f95f2020407ecf8abfde722ecb3e3160b/app/javascript/packs/flagUserModal.jsx#L148).

To change the word `DEV` to the forem's name, we need to pass the global variable `community_name` from the article's [show page](https://github.com/forem/forem/blob/main/app/views/articles/show.html.erb) (`app/views/articles/show.html.erb`). I suggest you add another `data-attribute` called `community-name` around line [83](https://github.com/forem/forem/blob/8b96f32f95f2020407ecf8abfde722ecb3e3160b/app/views/articles/show.html.erb#L83) and set it equal to the forem's community name: `<%= community_name %>`.

Next, head over to the [Article Moderation Tools javascript pack]( app/javascript/packs/articleModerationTools.js), add the `communityName` to the dataset destructuring around line [6](https://github.com/forem/forem/blob/8b96f32f95f2020407ecf8abfde722ecb3e3160b/app/javascript/packs/articleModerationTools.js#L6), then pass it in to wherever `initializeFlagModal` is called further down the same file.

Next, search for where `initializeFlagModal` is used in the codebase. You will need to pass `communityName` into this function. From there, figure out how to pass the `communityName` to the actual `<FlagModal />` component, so you can replace `DEV` with it.

Please reach out if you need more help or context! 🙏🏾  Thank you for contributing to Forem!

**Comment by Mr-DG-Wick** [comment]
Thanks @msarit 😄.This sounds a bit difficult, but I'm up for it :). Please assign me to the issue.

**Comment by Mr-DG-Wick** [comment]
Hey @msarit !!, I'm really sorry I haven't started working on this issue yet cuz I'm attending a 5 day conference right now (Kubecon) and can't find much time. Will it be fine if I can start  working on it from 16th of this month?. I realized that I should've informed about this before.

**Comment by zoeyyandi** [comment]
hey everyone, I'm new to Forem 👋  would love to contribute, is this issue up for grabs again?

**Comment by cmgorton** [comment]
Hey @zoeyyandi welcome! Yes this is up for grabs. If you would like to work on it I can assign you to the issue. If you have any questions about it please let us know. The team may be a little slower to respond over the next few days as many of us are off on vacation for US Thanksgiving.

**Comment by zoeyyandi** [comment]
Thanks @cmgorton! Yes please assign it to me, I'll take a stab at it and let you know how it goes!

**Comment by zoeyyandi** [comment]
hey @cmgorton! I created a [PR](https://github.com/forem/forem/pull/15505) for this bug. Could I trouble you for a review? I was also wondering if you could point me to a better way of accessing the community name in [this file](https://github.com/forem/forem/pull/15505/files#diff-ed63474f5aadc3b472dcf81d0a6274bf787ea4e3b4ad9abb0eb82e4264749d01R9), accessing the dom node is definitely not the best solution 😬

**Comment by aitchiss** [comment]
Closed by https://github.com/forem/forem/pull/15505
