### ISSUE TITLE
Dashboard pages shouldn't have two banner landmarks

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#14840]
**Describe the bug**

On the user dashboard there are two "banner" landmarks:

- The `<header>` at the top of the page (with logo, search, etc)
- The `<header>` containing "Total post reactions", "Total post views" etc

The same issue is observable across the other dashboards also (e.g dashboard/following_tags).

On each dashboard, [we should only have one banner landmark on the page](https://dequeuniversity.com/rules/axe/4.3/landmark-no-duplicate-banner?application=AxeChrome). While the wrapper for the "total post reactions" etc can just be changed to a `div`, this content should also be moved to live inside the `<main>` element, and this change might need a little bit of CSS tweaking to make sure everything continues to look consistent.

**To Reproduce**

- Log in to the app
- Go to `/dashboard`
- Open up the dev tools and run the axe extension
- Notice the error "Document should not have more than one banner landmark"

**Expected behavior**

- The error should not appear in the axe report
- Visually everything should remain the same
- The same should apply to the other dashboard pages

**Screenshots**

![Screenshot of the dashboard with the axe error highlighted and the header area highlighted](https://user-images.githubusercontent.com/20773163/135100163-a2601407-ed75-4459-86dc-f11064ccb636.png)

**Additional context**

Each dashboard page could be tackled in separate PRs if this keeps things more manageable.

**Comment by MohamedAsan** [comment]
I would like to work on this issue. Kindly assign it to me

**Comment by aitchiss** [comment]
Awesome! Assigned that to you now @MohamedAsan 😄

**Comment by MohamedAsan** [comment]
@aitchiss Did my best to fix this issue. Kindly check the PR and let me know if it needs any improvements 🙌
