### ISSUE TITLE
Fix the character limit on all inputs on the edit profile page

### ISSUE THREAD

**Issue by shawn-fetanat** [forem/forem#14866]
Sounds like you have a bug in the `handleSubmit` function that's supposed to evaluate if `input.value <= max_chars` because it doesn't work for any of the input prop values on that page. The max character limit you guys set is 200. I will show you in my Microsoft word that I clearly have 194 characters and there's no possible way microsoft word is giving me the wrong character count, but if you doubt it pause the video and count my characters. I will copy and paste my 194 characters using Ctrl+A and Ctrl+C then paste them into all fields under the "Coding" section on that page using Ctrl+V. Then I will click the `Save Profile Information` button and you will see that instead of my `/post` going through and getting returned the JSX at the top of the page with the whiteish background color that says `Your profile has been updated`, I get returned the JSX with the red background color at the top of the page that says `Error ${textFieldName} is is too long (maximum is 200 characters)`. Keep in mind I will ONLY have two extensions on. One is extensify which is to disable all other extensions and the other is loom which I use to record.

**Here is the video of the bug:** 
https://www.loom.com/share/3780523326c540048f81582b239a4248

**Here is the video showing the inputs work with just `"Hello World"` values:** https://www.loom.com/share/b3459821e5964df5a85e29756b10af58

Just a reminder

```js
let max_chars = 200;
(194 <= max_chars) // true
```

**Comment by citizen428** [comment]
The MS Word count says "Characters including spaces". It doesn't say anything about including newlines, "\n" are characters too.

![image](https://user-images.githubusercontent.com/47985/135403583-3d6a1be9-7b9d-4a01-bef9-6aae2d5a5fa1.png)

The above screenshot says 7 for "Characters (with spaces)" but including the newline after the "f" it's actually 8:

![image](https://user-images.githubusercontent.com/47985/135403801-109b2848-550f-421b-900c-4b60afd89dc1.png)

There doesn't seem to be a straightforward way to get MS Word to include the newlines in the count, only workarounds:

https://answers.microsoft.com/en-us/msoffice/forum/all/microsoft-word-newline-character-count/52e279e0-2de5-4c57-95c4-b35c4c926242?auth=1

I just added a string of 200 "x" characters in my profile, which works as expected:

![image](https://user-images.githubusercontent.com/47985/135404354-d6df5633-f012-4aab-b049-628a825f3fec.png)

You can check it out here: https://dev.to/citizen428

If I add a single line break after 100 characters I'm no longer able to save it.

![image](https://user-images.githubusercontent.com/47985/135404578-a3bb278f-aa55-447f-97fd-b1fe9158a767.png)

**Comment by shawn-fetanat** [comment]
Ohhhh yeah that's right newlines makes it over 200 for sure

**Comment by citizen428** [comment]
Unless I miscounted you may just be a single character over, try going to the end of the last text line and removing the final newline with a forward delete (the Del key). Otherwise, you'll have to make the text a bit shorter.

**Comment by shawn-fetanat** [comment]
no you didn't miscount. you're right.
