### ISSUE TITLE
Found Broken Link for Test in Documentation

### ISSUE THREAD

**Issue by yobee333** [forem/forem#14874]
**Describe the bug**
If you click on the link under Please Include Tests, the link to the testing guide is broken.

Here is what it goes to
![image](https://user-images.githubusercontent.com/69943959/135542175-c812cd95-50f2-4445-8dbe-8499e3b0b77e.png)

**To Reproduce**

1. Go to 'https://developers.forem.com/contributing-guide/forem/#please-include-tests'

![image](https://user-images.githubusercontent.com/69943959/135542081-35798dc1-41d3-4da3-a0dc-da5e2dd3c4e7.png)
2. Click on 'testing guide' hyperlink

 See error 'https://developers.forem.com/tests/'
![image](https://user-images.githubusercontent.com/69943959/135542175-c812cd95-50f2-4445-8dbe-8499e3b0b77e.png)

**Expected behavior**

Testing guide link should go to a testing guide, specifically this page: https://developers.forem.com/tests/types/frontend-tests.

**Comment by yobee333** [comment]
Could I please take this for Hacktoberfest?

**Comment by rhymes** [comment]
@yobee333 I've assigned it to you, thanks!

**Comment by CBID2** [comment]
I'll work on this for Hacktoberfest
