### ISSUE TITLE
Allow users to configure markdown rendering

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#1492]
**Is your feature request related to a problem? Please describe.**
Markdown can be handled in a few ways and some people will have preferences for certain things. Makes sense to let people choose how they want their markdown handled. 

**Describe the solution you'd like**
To start, let's add the option for our markdown parser to ignore certain line-breaks. See #575 for more info. This is a setting users should be able to toggle through their settings page.

**Comment by abraham** [comment]
I would recommend against customization of markdown. Having a number of options will add a lot of code paths in an area that is already difficult to test. I would suggest using a standardized markdown implementation that aligns with [CommonMark](https://commonmark.org/) plus the liquid tags. Maybe offering an escape hatch were authors can disable markdown and switch to HTML for advanced features.

**Comment by dguo** [comment]
CommonMark specifies how both [hard line breaks](https://spec.commonmark.org/0.28/#hard-line-break) and [soft line breaks](https://spec.commonmark.org/0.28/#softbreak) should be treated. The problem in #575 is that dev.to's parser seems to generate hard line breaks (`<br>`) no matter what. 

Though CommonMark does say: "A renderer may also provide an option to render soft line breaks as hard line breaks."

**Comment by bwl21** [comment]
Note that Github has a different behaviour with respect to line breaks for Issues and other places. I find this pretty strange and annoying.

 see: https://github.community/t5/How-to-use-Git-and-GitHub/Why-does-markdown-in-issues-respect-line-breaks/m-p/18637

**Comment by arian** [comment]
A workaround for this is to use `prettier` with the `--prose-wrap` option set to `never`:

```bash
prettier post.md --prose-wrap never
```

That way you don't need to manually remove the newlines, and can write the post as you want.

**Comment by cmgorton** [comment]
I am going to leave #12061 open and close this issue since they are similar but this one has been around for awhile with no traction. I think we should collect and highlight all of the markdown issues we have in the repo that are ready for dev. I am adding #12061 to a list to highlight.

**Comment by insidewhy** [comment]
> A workaround for this is to use `prettier` with the `--prose-wrap` option set to `never`:
> 
> ```shell
> prettier post.md --prose-wrap never
> ```
> 
> That way you don't need to manually remove the newlines, and can write the post as you want.

Thanks so much for this. I added the following script to my repo to make it easier to copy and paste articles into dev.to:

```json
{
  "copy-dev-to-article": "prettier --prose-wrap never readme.md | wl-copy"
}
```
