### ISSUE TITLE
Only two My Tags are showing in left nav

### ISSUE THREAD

**Issue by robertandrews** [forem/forem#14937]
As of this week, only two tags are showing under My Tags. I have more than two. More than two were previously showing.

This is the same across multiple browsers - Chrome Mac OS, Safari iOS.

At least, for my account - robertandrews

The first time I have gone to look at tag weighting, all are 1.0. But making an arbitrary change for one (eg. to 4) does not result in more tags showing.

**Comment by robertandrews** [comment]
Just saw this is the Forem repo specifically, not Dev. Possibly a Dev support issue, not Forem codebase. Sorry if so.

**Comment by cmgorton** [comment]
Hey @robertandrews. Forem is the software that runs DEV so adding this issue here is fine 😄

Could you take a screenshot for me of what you are seeing. On my account I see multiple tags under My Tags
![Screen Shot 2021-10-05 at 8 33 23 AM](https://user-images.githubusercontent.com/21039864/136044091-ce53735b-f05a-4aa6-b3aa-251ab64f1b4f.png)

**Comment by robertandrews** [comment]
Six becomes two...

<img width="1046" alt="Screenshot 2021-10-05 at 18 16 20" src="https://user-images.githubusercontent.com/3158787/136071439-027e673e-f6e8-492c-a502-ec381408fc37.png">
<img width="617" alt="Screenshot 2021-10-05 at 18 16 09" src="https://user-images.githubusercontent.com/3158787/136071448-0a9c1ca5-e316-44d4-8547-105e7fc8d3ef.png">

**Comment by rhymes** [comment]
I think I figured it out. The sidebar in the homepage shows cached followed tags:

https://github.com/forem/forem/blob/7ffb5aa0fde65c10f7540d46fbba4803f5ddab70/app/controllers/async_info_controller.rb#L45

These followed tags are in a cache populated each 20 hours:

https://github.com/forem/forem/blob/7ffb5aa0fde65c10f7540d46fbba4803f5ddab70/app/decorators/user_decorator.rb#L24-L27

this key depends on the user id, which never changes, the number of followed tags and the last time something has been followed.

@robertandrews I think you encountered a caching issue. I'm going to mark this as a bug

**Comment by robertandrews** [comment]
Hi. Any update? Still can't get this resolved.
New test -
Following a tag for the first time successfully adds it to the left-hand column.
But, even if I unfollow and re-follow an existing tag, it still doesn't appear on the left-hand column.

**Comment by nickytonline** [comment]
@robertandrews, I've messaged the team to see if someone can dig into this more.

**Comment by jeremyf** [comment]
Quick question, @robertandrews, what's your username on DEV?  I want to see about building the query that we then cache from user data.

**Comment by jeremyf** [comment]
Reading Notes:

When I run the following, I see that the reporting user is currently following 7 tags:

```sql
SELECT tags.*, "followings"."points" FROM "tags" INNER JOIN "follows" "followings" ON "followings"."followable_type" = 'ActsAsTaggableOn::Tag' AND "followings"."followable_id" = "tags"."id" WHERE "followings"."follower_id" = :user_id AND "followings"."follower_type" = 'User' ORDER BY "tags"."hotness_score" DESC
```

**Comment by jeremyf** [comment]
Further Reading Notes:  

For myself, I'm following 13 tags.  Only 7 show up in my left navigation.

Here's a portion of the JSON from https://dev.to/async_info/base_data:

```json
"followed_tags": [
    {"id":112,"name":"productivity","bg_color_hex":"#2A0798","text_color_hex":"#C8F7C5","hotness_score":1195340,"points":4.09104245335832},
	{"id":630,"name":"career","bg_color_hex":"#2A2566","text_color_hex":"#FFFFFF","hotness_score":756277,"points":6.2188758248682},
	{"id":342,"name":"github","bg_color_hex":"#191919","text_color_hex":"#ffffff","hotness_score":322683,"points":0.817072806887547},
	{"id":1,"name":"ruby","bg_color_hex":"#CC342D","text_color_hex":"#FFFFFF","hotness_score":73097,"points":4.87120101090789},
	{"id":47,"name":"rails","bg_color_hex":"#cc0000","text_color_hex":"#ffffff","hotness_score":69929,"points":8.79088607528108},
	{"id":5305,"name":"todayilearned","bg_color_hex":"#ffedc9","text_color_hex":"#820000","hotness_score":25507,"points":0.709321766180646},
	{"id":303,"name":"vscode","bg_color_hex":"#1c1c1c","text_color_hex":"#8cb8ff","hotness_score":22752,"points":0.9604},
	{"id":32214,"name":"devjournal","bg_color_hex":"#820000","text_color_hex":"#ffffff","hotness_score":19894,"points":5.05570542169248},
	{"id":76,"name":"postgres","bg_color_hex":"#ED1556","text_color_hex":"#FFFFFF","hotness_score":10092,"points":4.2233663078147},
	{"id":185,"name":"documentation","bg_color_hex":null,"text_color_hex":null,"hotness_score":337,"points":0.723797720592496},
	{"id":530,"name":"emacs","bg_color_hex":null,"text_color_hex":null,"hotness_score":151,"points":5.85831171728237},
	{"id":260,"name":"osx","bg_color_hex":null,"text_color_hex":null,"hotness_score":0,"points":0.753641941474902},
	{"id":7454,"name":"regexp","bg_color_hex":"#000000","text_color_hex":"#ffffff","hotness_score":0,"points":0.769022389260104}
],
```

In looking and comparing on my page:

| Name          | Points are Above 1 | In Nav |
|---------------|------------------|--------|
| career        | yes              | yes    |
| emacs         | yes              | yes    |
| devjournal    | yes              | yes    |
| ruby          | yes              | yes    |
| postgres      | yes              | yes    |
| productiviity | yes              | yes    |
| rails         | yes              | yes    |
| vscode        | no               | no     |
| github        | no               | no     |
| todayilearned | no               | no     |
| documentation | no               | no     |
| osx           | no               | no     |
| regexp        | no               | no     |


The points come from the calculations on the Follow table.  Which will require more sleuthing.  And my conjecture is that the left navigation is intended to show you tags for which you frequently interact.  But what is that interaction?  I don't know.

**Comment by jeremyf** [comment]
We process the JSON information here:

https://github.com/forem/forem/blob/06f65734363469382208ee0641e62d691b8084e6/app/javascript/packs/homePage.jsx#L23-L48

Then render here: 

https://github.com/forem/forem/blob/06f65734363469382208ee0641e62d691b8084e6/app/javascript/leftSidebar/TagsFollowed.jsx#L6-L29

Importantly, we skip rendering on tags that have "points" of less than one.  Which aligns with my observation.

When I run the query to see what the points are for your followed tags, there are 3 that have 1.0 or more points.

**Comment by robertandrews** [comment]
I think you figured out my username. Following your theory, I assume the number of items shown on the left recently upped from two to three (#airtable) because I bookmarked some #airtable posts in the last few days.

I'd never have guessed that this kind of surfacing logic would be controlling the visibility here in the background. Rather, I'd probably assume "My Tags" would show all tags - or, if the user has too many to elegantly fit, that the top N would show and then a user could click through to the full tags page, or expand the list in situ.

If I have a low engagement score, it's probably down to my lowly status as a not-quite developer. Certainly consuming more than posting.

**Comment by jeremyf** [comment]
@robertandrews I'm checking in with our product team to see how we want this to render.  It definitely surprised me.

**Comment by jeremyf** [comment]
It looks as though PR #14782 introduced the change.  I'll dig a bit further.

**Comment by jeremyf** [comment]
I did some further digging and there's these values (tag names deliberately hidden).  I assume that you have one tag that you've bumped to a 4.0 value.

| Calculated Points | Explicit Points |
|-------------------|-----------------|
|              0.98 |             1.0 |
| 0.850763022581786 |             1.0 |
|               1.0 |             1.0 |
|  8.18035305299828 |             4.0 |
|  0.62834728215212 |             1.0 |
|  5.97786909926772 |             1.0 |
| 0.641170696073592 |             1.0 |

**Comment by robertandrews** [comment]
I guess so. When I put it back to 1.0 like the others, still only three show on the home page.
