### ISSUE TITLE
Only able to pin 4 articles instead of 5

### ISSUE THREAD

**Issue by surajondev** [forem/forem#14965]
**Describe the bug**

As the documentation said, we can pin 5 posts to our profile. I already pinned 4 posts and when I try for another which is 5th one to pin to my profile it shows the alert "Uh Oh! You can only have five pins 😬". 

**To Reproduce**

- At least have 4 pinned post
- Try to pin another post through the "manage" post.
- It will show the alert "Uh Oh! You can only have five pins 😬"

**Expected behavior**

We should be able to pin at least 5 pins.

**Screenshots**

### 4 Pins already
![DevPinPost](https://user-images.githubusercontent.com/67496096/136138122-13484e5c-380e-41ee-a055-9f16c9b463dc.PNG)

### Trying to pin 5th one
![PinPostLimit](https://user-images.githubusercontent.com/67496096/136138153-2f5d8b4d-3de0-4416-9319-2e5481289bdb.PNG)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by citizen428** [comment]
Update: I just checked in our database, you do in fact have 5 pins, one of which is unpublished.

![image](https://user-images.githubusercontent.com/47985/136153752-f3bb5d9e-2d51-4494-8ed6-4375f5645096.png)

**Comment by rhymes** [comment]
I guess we should only count published posts, so this is technically a bug

**Comment by viniciusarre** [comment]
Could I get assigned to this? I'd love to contribute!
