### ISSUE TITLE
Text overflow not properly handled in preview cards

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#14971]
**Describe the bug**

Check out the URL in this preview card forcing this overflow bug:

<img width="574" alt="Screen Shot 2021-10-06 at 4 51 24 PM" src="https://user-images.githubusercontent.com/3102842/136281327-6e8c7577-ed89-40a9-b914-f7cc5f598f3e.png">

**To Reproduce**

Add a long word (like a URL) to a summary and then open it in a feed card like shown.

**Expected behavior**

Next to an article, this same content displays like this:

<img width="315" alt="Screen Shot 2021-10-06 at 4 59 57 PM" src="https://user-images.githubusercontent.com/3102842/136282322-748558b1-8f24-487d-b426-c4be2931d467.png">

**Comment by superspike7** [comment]
can I work on this?

**Comment by loganom** [comment]
Thanks @rhymes !

**Comment by rhymes** [comment]
@manojnaidu619 let me check with @superspike7 one sec, for priority's sake, thank you :)

@superspike7 given that you asked to work on this earlier, are you still available?

**Comment by superspike7** [comment]
@rhymes  yes i would love to work on this issue

**Comment by aaishikasb** [comment]
Hey @rhymes, I'd like to work on the issue if there are no active contributors assigned.

**Comment by citizen428** [comment]
@aaishikasb Since this issue hasn't seen any activity since last October I assigned it to you now, thanks for volunteering!

**Comment by ludwiczakpawel** [comment]
Re-assigning as it seems to be inactive.
