### ISSUE TITLE
Cannot update article to unpinned intuitively

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#14974]
**Describe the bug**

In the /admin/content_manager/articles/## interface there appear to be two ways to unpin an article and one doesn't seem to work.

**To Reproduce**

1. Go to an articles admin page — '/admin/content_manager/articles/##'
2. Check "pinned" + click submit to pin the article
3. Refresh the page
4. Uncheck "pinned" + click submit to unpin the article
5. This doesn't appear to work
6. Click the "unpin post" button at the top of the article widget
7. This does work

**Expected behavior**

You should be able to uncheck "pinned" + click submit to unpin the article (the same action that you take to pin the article)

**Screenshots**

https://www.loom.com/share/4b49b2455518470f92d575d499820b7c

**Additional context**

It's not too urgent of a bug since there is a way to unpin articles. This just feels odd and likely should be fixed.

**Comment by benhalpern** [comment]
> Uncheck "pinned" + click submit to unpin the article

Yeah, definitely more than unintuitive, even though you can technically do the other way, this is a definite bug.

Since we have the button, seems like we don't _also_ need the checkbox.
