### ISSUE TITLE
Impossible to disable a registration option?

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#14975]
**Describe the bug**

It seems impossible to disable an registration option. Removing the keys and clicking disable does not, in fact, disable anything.

**To Reproduce**

- Go into admin
- Add a twitter account keys
- Try to remove and disable
- It still shows on auth page

**Expected behavior**

This is disabled and removed from page

**Screenshots**

<img width="949" alt="Screen Shot 2021-10-07 at 12 14 34 PM" src="https://user-images.githubusercontent.com/3102842/136423708-2fe2b79c-e32b-46f0-a2e9-47148576a988.png">

**Comment by lsparlin** [comment]
I'd be happy to work on this issue. I see that it's labeled high-priority and I don't want to hold anything up. So full disclosure: I won't be able to work on it until this evening (GMT-5)

**Comment by cmgorton** [comment]
That's ok @lsparlin ! This is high priority but not "This has to be done this second" priority if that makes sense 😄 
Getting to it soon would be helpful but you don't need to feel like you have to rush. I'll assign this to you. Let us know if you have any question.
