### ISSUE TITLE
Unified Liquid Tag, aka Embed

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#15099]
- [Related pod issue ](https://github.com/forem/forem/issues/15099)
- [Working doc](https://docs.google.com/document/u/1/d/1bGY_SLIo93y0BG9jFQrgRBJoBIpN0VddT8A7P3ywdh0/edit#)

**Comment by Posandu** [comment]
Okay. No problem @ludwiczakpawel

**Comment by msarit** [comment]
My current approach with this Epic is to implement `{% embed url %}` for all Liquid Tags, BUT leave the original `{% liq-tag-name input %}` syntax in place.

For example, for the YoutubeTag, I am implementing `{% embed https://www.youtube.com/embed/fhH5xX_yW6U %}` but leaving the original `{% youtbe fhH5xX_yW6U %}` in place.

In the near future, pod-CE will decide how to deprecate the original LiquidTag implementations.

= = = = = = = = =

Here is a list of all the Liquid Tags that I will be modifying:

### LiquidTags without a Unified Embed:
-  [ ] Blogcast
-  [ ] Codesandbox,
-  [ ] Comment
-  [ ] Details
-  [ ] GitPitch _(has been shut down permanently)_
-  [ ] GitHub & GitHub Issue Comment Pull Request _(weird; first takes username/repo-name and the latter takes the full URI)_
-  [ ] Glitch
-  [ ] Instagram
-  [ ] Katex
-  [ ] Kotlin
-  [ ] Link _(which appears to cover both Forem “links” and “posts")_
-  [ ] ListingTag
-  [ ] NullTag
-  [ ] OrganizationTag
-  [ ] PodcastTag
-  [ ] PollTag
-  [ ] Replit
-  [ ] RunKit
-  [ ] Slideshare
-  [ ] Speakerdeck
-  [ ] Spotify
-  [ ] Stackblitz
-  [ ] Stackery
-  [ ] StackExchange/StackOverflow
-  [ ] Tag
-  [ ] Twitter
-  [ ] Twitch
-  [ ] UserSubscription
-  [ ] User
-  [ ] Vimeo

LiquidTags with a non-working/half-working UnifiedEmbed:
-  [ ] DotNetFiddle
-  [ ] Jsitor
-  [ ] Medium (the image is broken in both production and embed)
-  [ ] Parler (embed returns fallback url, parler returns `{"message": "Internal server error"}`)
-  [ ] Wikipedia

### LiquidTags with a working Unified Embed:
- [X] Asciinema
- [X] Codepen
- [X] GithubGist
- [X] JSFiddle
- [X] NextTech
- [X] Reddit
- [X] Soundcloud
- [X] TwitterTimeline

**Comment by ludwiczakpawel** [comment]
I'm suuuuper excited and pumped about this project! So glad to see you working on this and can't wait for this to be shipped! 🤩 🤩 🤩 

Couple questions/notes:

1. Leaving the original liquid tag format for now is definitely a good approach. Will be easier for users to transition to new format while we can still have some time to deprecate the old one.
2. Looking at your list above, what does it mean when you say that some liquid tag are "without a unified embed" and some are "with a working unified embed"?
3. Is [this](https://docs.google.com/document/d/1bGY_SLIo93y0BG9jFQrgRBJoBIpN0VddT8A7P3ywdh0/edit#heading=h.5ll4m2uwbw93) something you're thinking about by any chance? Not saying this needs to be implemented right away but having some sort of strategy here would be very helpful in our future work, so it's probably worth looking into while we're on this task. Also cc'ing @jeremyf here.
4. Correct me if I'm wrong but weren't we aiming for `{ http://example.com }` format instead of `{% embed http://example.com %}` (so no `%` and no `embed` keyword)? At least that's what we [spec'd](https://docs.google.com/document/d/1bGY_SLIo93y0BG9jFQrgRBJoBIpN0VddT8A7P3ywdh0/edit#).
5. You don't mention that [generic embeds idea](https://docs.google.com/document/d/1bGY_SLIo93y0BG9jFQrgRBJoBIpN0VddT8A7P3ywdh0/edit#heading=h.aj957he6ozey) for the rest of the URLs (that we currently **not** support) - is this still something on the radar? I'm sure it is, just making sure we're all on the same page :)))

**Comment by jeremyf** [comment]
> Correct me if I'm wrong but weren't we aiming for { http://example.com } format instead of {% embed http://example.com %} (so no % and no embed keyword)? At least that's what we spec'd.

That's a good question.  In the liquid parsing the implementation of the `embed` tag follows the current other tag implementations.  So, while it might be possible to get to `{ embed }` I suspect that we're going to have to store `{% embed %}` (but that's based on now decade old memories of last working with Liquid).

**Comment by msarit** [comment]
Hey @ludwiczakpawel thanks for your comments and questions

> Correct me if I'm wrong but weren't we aiming for { http://example.com } format instead of {% embed http://example.com %} (so no % and no embed keyword)? At least that's what we spec'd.

Hmmm I missed this in the specifications file. Hmmm I would need to discuss with @jeremyf about the `{ url }` approach. My current approach is to unify all tags to be of the form `{% embed url %}`. Perhaps after this incremental change, we could explore not needing the `embed` keyword.

This project is a huge one, and will require a gradual, incremental rollout, as well as ensuring that existing tags are not broken. Jeremy is working with me, so we shall certainly fulfill all spec requirements.

**Comment by ludwiczakpawel** [comment]
All good, just wanted to rise my concerns/questions before it's too late :) 

![](https://media.giphy.com/media/l3q2Wl7Wpz09Z5hfi/giphy.gif)

**Comment by jeremyf** [comment]
> You don't mention that generic embeds idea for the rest of the URLs (that we currently not support) - is this still something on the radar? I'm sure it is, just making sure we're all on the same page :)))

I'm glad your helping us keep this salient.  And I think I'm going to spend some time articulating the larger roll out plan.  I know we have a google doc, but we're heading into a checklist kind of effort.

What Arit's doing is to shore up the interface, so we can reduce immediate overhead.  Then in quick order, look into using OpenGraph (or Twitter Cards or what have you) to see about doing a more generalized approach for embeds.

**Comment by ludwiczakpawel** [comment]
@jeremyf great. I just wasn't aware of that (sorry, I might have missed a doc or something). So thank you for quick explanation!

**Comment by msarit** [comment]
I'm closing this issue as the work for thies iteration of streamlining rich-content embeds has been completed. 🎉

**Comment by ludwiczakpawel** [comment]
What about [Generic Embeds](https://docs.google.com/document/d/1bGY_SLIo93y0BG9jFQrgRBJoBIpN0VddT8A7P3ywdh0/edit#heading=h.aj957he6ozey)? It's been part of this issue and I don't want it to be forgotten.

**Comment by justin-schroeder** [comment]
This is a great upgrade! Thanks for everyone’s hard work (especially @msarit). I'm not super familiar with the forem -> dev.to  pipeline, but I'm pretty sure dev.to articles dont support this _yet_ even though the docs indicate they do. Is that possible? I'm getting errors over there trying to do things like this:

```
{% embed https://stackblitz.com/edit/intro-example-a?embed=1&file=src/App.vue&hideExplorer=1&hideNavigation=1&view=preview %}
```
🙏

**Comment by ludwiczakpawel** [comment]
@justin-schroeder hmm, interesting - that very URL does work for me on dev.to... Could you try to clear your cache and if it's still broken --> [report an issue](https://github.com/forem/forem/issues/new?assignees=&labels=&template=bug_report.md)?
