### ISSUE TITLE
Add "Tags" category to Search Results

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#15151]
The idea is to add "Tags" category for our search results.

Quoting @citizen428:

> we do index tags for search. There's just no dedicated filter for them on the search results page. It shouldn't be too hard to add that in there

![image](https://user-images.githubusercontent.com/108287/138298879-ffb4071a-9abd-471a-9d4a-38e15fec063a.png)

### Related:

- [Forem.dev post](https://forem.dev/andyv/feature-request-add-search-to-tags-page-al9)
- [Internal: Slack thread](https://forem-team.slack.com/archives/C02BP4UG2N9/p1632925089168400)

**Comment by jeremyf** [comment]
Closed by #16265
