### ISSUE TITLE
Move expand/collapse ticks into comment cards

### ISSUE THREAD

**Issue by Arteneko** [forem/forem#1518]
**Is your feature request related to a problem? Please describe.**

When I first saw the expand/collapse ticks, I didn't understand the original purpose of them.

After hovering them, and seeing that it was not simply a bug in the website, but an actual action, I understood its purpose.

I think that the tick's not explicit, and its positioning wrong: it changes the comment card's state, I'd expect to find it *in* the card.

**Additional context**

For nested comments, maybe the parent card could contain child cards in design?

Finally, here's a screenshot of an example of ticks and nested comments:

![](https://pix.watch/4FLEuZ/HdAGM7.png)

**Comment by cmgorton** [comment]
Hey @Arteneko !

Thank you so much for opening this issue/discussion! Our design team is in the process of changing the UI for the comment cards and this will no longer be an issue with the new design. 
I am going to go a head and close this issue. 

We couldn't do what we do without awesome community members like yourself, thank you so much for being a part of our awesome Forem community 🤗
