### ISSUE TITLE
Tag/Mention Users in Post

### ISSUE THREAD

**Issue by jorgeRafaelSJ** [forem/forem#152]
# _TASK or Feature_
### Request or User Story
I write an article about knowledge I exchange with someone that was inspiring. I want to be able to tag/mentions the user to create more engagement and be nice to the person that I learned from. I can type their username and they will be notified when the article is public, people will be able to link to their profile from my posts and see their posts
### Definition of Done
Maybe implementing something like @(username)? It tags the person with a link to their profile.

**Comment by jessleenyc** [comment]
Thanks for the feature request, added to backlog 😸

**Comment by maestromac** [comment]
Sorry this missed us. This is a good feature request we might want to implement soon.

**Comment by maestromac** [comment]
not stale

**Comment by rembrandtreyes** [comment]
@rhymes Is this still up for grabs?

**Comment by rhymes** [comment]
@rembrandtreyes not anymore, now it's assigned to you :D

**Comment by rembrandtreyes** [comment]
Just clarify the acceptance criteria. 

- Be able to @someone in a post 
- Tagging the person in a post will send them a notification.

**Comment by rhymes** [comment]
@rembrandtreyes exactly! the only check I can think of is to not send the notification if the article's creator somehow tags themselves.

**Comment by Link2Twenty** [comment]
@rembrandtreyes are you still working on this?

**Comment by cmgorton** [comment]
Hey, since this has gone a bit stale I think we might want to revisit whether this is a feature we want to implement. 

 I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!

**Comment by cmgorton** [comment]
Team let me know we have a plan in place for this particular feature so I am going to reopen it! 🥳

**Comment by Link2Twenty** [comment]
I think this can be closed?

**Comment by cmgorton** [comment]
Yep! Thanks Andrew.
