### ISSUE TITLE
incompatible model definition in API:  get list of article & get article by id

### ISSUE THREAD

**Issue by SrikanthYashaswi** [forem/forem#15236]
**Describe the bug**
GET  _https://dev.to/api/articles_ returns list of articles, 

in the above api, in model Article:  **_tags_** returns `string` and **_tag_list_** returns `Array of strings`

where as in GET _https://dev.to/api/articles/articleId_ returns a single article

In this api **_tags_** returns `Array of strings` and **_tag_list_** returns `string`

the type is interchanged in both apis

**Expected behavior**

The type should be consistent in both apis.

**Comment by jeremyf** [comment]
@SrikanthYashaswi thank you for reporting this.  As someone new-ish to the Forem Core team, I did some digging.  

This is a long reported bug in the v0 API, and to fix would be a breaking change.  For more context please see https://github.com/thepracticaldev/dev.to/issues/4206.

I'm going to close this issue as it's known and something we'll account for as we look towards a v1 release.  Though from my perspective, I wonder if v0 APIs are semantically versioned such that we can break things in v0?
