### ISSUE TITLE
Angle bracket characters in Community Name may prevent email delivery

### ISSUE THREAD

**Issue by andygeorge** [forem/forem#15274]
Seen in a Forem Cloud customer instance: having `<` and `>` characters in the Community Name may prevent email delivery. For example:

```
irb(main):049:0> Settings::Community.community_name
=> "<example>NAME"
```

The 'from' email string is generated [here](https://github.com/forem/forem/blob/a8c75fb0e8a0f45afca5dd00afdfb331316ab515/app/mailers/devise_mailer.rb#L8), which results in this:

```
irb(main):058:0> "#{Settings::Community.community_name} <#{ForemInstance.email}>"
=> "<example>NAME <noreply@forem.com>"
```

...which can lead to the `<example>` string being interpreted as the sender address. SendGrid, for example, returns the following, if `<example>` is not configured as a "verified Sender Identity" (not to mention, it's not an email at all!):

> Net::SMTPFatalError: 550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sende...

**Comment by michael-tharrington** [comment]
Thanks so much for writing this one up! I've subscribed to this issue so that I can keep apprised and keep any Forem Creators that this is affecting informed once a fix is in so they can adjust their names accordingly.
