### ISSUE TITLE
Hover card of post author doesn't looks well styled

### ISSUE THREAD

**Issue by kerimcet** [forem/forem#15290]
**Describe the bug**

The hover card of post author doesn't looks well when it is near the bottom of browser window. I think, it breaks down due to insufficient space.

**To Reproduce**

1. Go to 'dev.to' (or any other website which uses Forem)
2. Scroll down and stop on any post author near bottom of browser window
3. Hover on 'post author name'
4. See bug

**Expected behavior**

The hover card of post author should looks like as expected.

**Screenshots**

<img width="1440" alt="screenshot-hovercard" src="https://user-images.githubusercontent.com/41960283/140639935-17f74d3b-9aca-4412-a5be-dbc5be36af6f.png">

**Desktop:**

- OS, version: MacOS Monterey, 12.0.1
- Browser, version: Google Chrome, 95.0.4638.69

**Additional Context:**

Also here: (https://community.devocate.com/)

https://user-images.githubusercontent.com/41960283/140640366-bdda99d4-296a-4218-b151-4fb0d2edb9d4.mov

**Comment by kerimcet** [comment]
@cmgorton I mean it breaks when it is near bottom of the browser window and it doesn't fit because of there is not enough space for the card content.

**Comment by cmgorton** [comment]
@kerimcet thanks for the clarification. I was able to recreate the issue when hovering at the bottom of the screen.

**Comment by jeremyf** [comment]
This appears to be a Safari specific bug.
