### ISSUE TITLE
_terms_text.html does not update when /terms is overwritten

### ISSUE THREAD

**Issue by ellativity** [forem/forem#15296]
**Describe the bug**

When a Forem Admin overwrites the default page `/terms`, they would expect that this would be update the Terms of Use  displayed during the New User Onboarding (on the modal page that new users are requested to confirm they have read and agreed to the Terms, they can click on linked text to view the Terms):
![New User Onboarding modal showing link to Terms](https://user-images.githubusercontent.com/76786132/140757843-6b6a2142-4d08-4115-8b79-7df33289275e.png)

However, the Terms displayed during onboarding are pulled from `_terms_text.html` which doesn't update when `/terms` is overwritten, so the updated Terms of Use for the Forem aren't available to a new user before they sign up.

**To Reproduce**

1. Overwrite default `/terms` page on a Forem
2. Navigate to `/onboarding` or sign up as a new user
3. Click on **Terms of Use** link text (as seen in screenshot above)
4. Review **Terms of Use**

**Expected behavior**

The previewed Terms of Use that new users read prior to confirming their sign up match the latest `/terms` text.

**Additional context**

This was reported to us by a Forem Cloud partner who updated their contact email address in the Terms and other pages on their site, due to all Forem Cloud partners defaulting to the same email address. In this situation, it's important but not vitally urgent. 

Typically, this bug might be more problematic if someone has deviated extensively from the default Terms - in which case there could be legal implications for not providing new users with the true Terms of Use that they're consenting to.

**Comment by ellativity** [comment]
https://github.com/forem/forem/blob/main/app/views/pages/_terms_text.html.erb <-- this

**Comment by lsparlin** [comment]
I'd be happy to work on this
