### ISSUE TITLE
Creator Settings: Add a logo preview to the creator settings form

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#15348]
## Description

Add a logo preview when a creator uploads a logo in the creator settings form.

![image](https://user-images.githubusercontent.com/833231/141308561-ea4dd11f-2db5-467b-ac04-1aabd3c995b1.png)

Use the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) API to load the image a creator selects (not uploads) to render the logo preview

Estimate:	1 day

**Comment by nickytonline** [comment]
@anujbhavsar96 @Ridhwana, what are the expected dimensions for the loo? Looking at DEV and the CodeNewbie Community, one none of the logos are square and two they are definitely smaller that 300px x 300px.

**Comment by Ridhwana** [comment]
> @anujbhavsar96 @Ridhwana, what are the expected dimensions for the preview logo?

@nickytonline is this related to the question in [Creator Settings: Add validation for logo size](https://github.com/forem/forem/issues/15350) or are you referring to the dimensions of the actual preview on the page?

**Comment by anujbhavsar96** [comment]
CC'ing @ludwiczakpawel here as well, 

I'm not sure if he had planned to keep it dynamic or static in one bounding box

**Comment by Ridhwana** [comment]
I think displaying it at the same dimension that we would display it on the navbar would be an option or maybe previewing it at the recommended size? 

@ludwiczakpawel will be jumping on this thread in a bit and can verify 😊

**Comment by ludwiczakpawel** [comment]
So for the preview: max size would be whatever space is left to keep logo preview and button "Change logo" in one line (which I guess could be achieved with `flex-1` class). But we should add some sensible max-height (80px?) too for that image.

Does that make sense to all of you?
