### ISSUE TITLE
404 on tag page

### ISSUE THREAD

**Issue by daroga0002** [forem/forem#15359]
**Describe the bug**

Getting 404 when reviewing tag assigned articles and there was is no article with such tag for last period which I want to sort.

**To Reproduce**

1. Open a some tag which doesnt have frequently created articles. For example https://dev.to/t/oci
2. Click a period of `week` which will redirect you to 404 page

**Expected behavior**
I should be still on tag page and there should be some notification `No articles found` or etc. and allowing me choose other period

**Screenshots**

![image](https://user-images.githubusercontent.com/20227477/141442952-1da82268-a4bc-476c-879e-c5f5f2f5e0c6.png)

![image](https://user-images.githubusercontent.com/20227477/141443037-f8d4ae0c-b03a-4ae7-bf10-05e2565d424a.png)

**Desktop (please complete the following information):**

- OS, version: any
- Browser, version: any

**Comment by benhalpern** [comment]
Ah, you're right. We recently switched "empty" tags to 404, as the technical existence of a tag that is not supported and/or has no posts shouldn't be an empty page, but the sub-filters of a tag that otherwise has posts should return the page with a proper empty list graphic.

**Comment by cmgorton** [comment]
This appears to be fixed now. Can you confirm if you are still seeing this bug @daroga0002 ?

**Comment by cmgorton** [comment]
Ok! I see it. Thanks @daroga0002

**Comment by jeremyf** [comment]
The following PR introduced partial fixes https://github.com/forem/forem/pull/14864.

My understanding is that the logic should be as follows:

 - If the tag is supported, never render 404.
 - Else if the tag is not supported and we're on page 1:
   - If the tag requires approval
     - If there is at least one published and approved article (even if it's not in the timeframe), don't render a 404.
     - Else render a 404.
   - Else if the tag does not require approval
     - If there is at least one published article (even if it's not in the timeframe), don't render a 404.
     - Else render a 404.
