### ISSUE TITLE
Update the "Upload an image..." Button on the Creator Settings Page

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#15353]
**📖  As a Forem Creator, I want my experience to be as UI pleasing as possible, so that I feel motivated to continue with the journey.** 

_(Format:  As a [persona], I [want to], [so that])_

![](https://user-images.githubusercontent.com/108287/116532347-6d033700-a8e0-11eb-8dae-88bf6164f682.png)

**🐣TASKS**
https://github.com/forem/rfcs/blob/a8d843d9a37c4105850f575f6e51faac7377a474/text/0190-admin-onboarding.md

- [ ] Update the logo's "Upload an image..." button's styling to reflect the design's styles for the logo field on the form

**Comment by juliannatetreault** [comment]
👋  @nickytonline are you currently tackling this issue? From your quick video on Slack it looked like you might be!

**Comment by nickytonline** [comment]
Yeah I needed to style it to get the preview working size wise:

**Comment by juliannatetreault** [comment]
Great! I've assigned the issue to you and moved it to the "In progress" column on the project board, @nickytonline. 😊

**Comment by nickytonline** [comment]
After some feedback from @ludwiczakpawel, we're going to put this on hold while design revisits this. For context, see https://github.com/forem/forem/pull/15363#discussion_r752078216

**Comment by juliannatetreault** [comment]
> After some feedback from @ludwiczakpawel, we're going to put this on hold while design revisits this. For context, see [#15363 (comment)](https://github.com/forem/forem/pull/15363#discussion_r752078216)

The above comment link doesn't navigate to the discussion as expected, so for reference, here's the text from the comment that it should link through to:

> Hey, random idea/thought... And it might be too late for this now... Buuuut gonna say it anyway :D... Do we need to style this input at all? It clearly causes some troubles and a need to do workarounds with label and all kinds of pseudo classes etc... What if we just kept standard style for input[file] and show logo preview below it and that's it? I know it won't be that aesthetically pleasing anymore but at least it will be much simpler and it will rely on pretty standard UX patterns.

**Comment by nickytonline** [comment]
Given what we discussed @ludwiczakpawel, I imagine we're keeping this as the native file input button?

**Comment by juliannatetreault** [comment]
Seems like it for the time being, but maybe @Ridhwana has more information? If we're holding off on this for now, we could probably add this to the "High Impact, Low Effort" board so that we can pick it up post-Creator Onboarding release.

**Comment by ludwiczakpawel** [comment]
> I imagine we're keeping this as the native file input button?

In my opinion, yes.

> "High Impact, Low Effort" board

If anything, it would be "Low Impact, High Effort" :D

**Comment by Ridhwana** [comment]
> I imagine we're keeping this as the native file input button?

Correct, I think we can close this and don't need to add a follow up issue for it. There were good reasons why we used the native button and I don't think its valuable to tackle a "Low Impact, High Effort" task (as Pawel put it) with all our current backlog.
