### ISSUE TITLE
Add a Required Description Field to Display Ads

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#15410]
📖  **As a Forem admin, I want to be able to be to add a description to display ads so that I am able to better understand which display ad I am currently looking at without having to click directly into the display ad.**

(Format: As a [persona], I [want to], [so that])

**🐣TASKS**

- [ ] Add a required `description` field to display ads
- [ ] Display the required `description` field for each display ad on the display ad `index` page

**Comment by JennieOcken** [comment]
Given that we are actually going to overhaul this section entire (cc: @ludwiczakpawel ) let's wrap this into that.
