### ISSUE TITLE
Add an Expiration Date to Display Ads

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#15411]
📖  **As a Forem admin, I want to have an automatic expiration date set for my display ads so that I am able to publish display ads without having to worry that I will forget to unpublish outdated display ads.**

(Format: As a [persona], I [want to], [so that])

**🐣TASKS**

- [ ] Add an automatic "expiration date" to display ads (see HTML Variants for inspiration)

**Comment by JennieOcken** [comment]
Given that we are actually going to overhaul this section entire (cc: @ludwiczakpawel ) let's wrap this into that.
