### ISSUE TITLE
When starting Gitpod - foreman fails to start, so web-application is not served.

### ISSUE THREAD

**Issue by omenking** [forem/forem#15428]
**Describe the bug**

**To Reproduce**

Press Gitpod button, see it waiting on port 3000, switch to first tab.

<img width="799" alt="Screen Shot 2021-11-18 at 3 22 02 PM" src="https://user-images.githubusercontent.com/7776/142491032-f2ac8ffd-4546-461a-8a53-31392bb28a9f.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by djuber** [comment]
@omenking I see the same thing - it looks like re-running bin/startup on that shell tab brings the app up correctly.

Error observed when opening gitpod (did not happen the time I ran bin/startup manually):

```
20:26:42 web.1       | Exiting
20:26:43 web.1       | /workspace/.rvm/ruby-3.0.2/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client': FATAL:  the database system is starting up (ActiveRecord::ConnectionNotEstablished)
20:26:43 web.1       |  from /workspace/.rvm/ruby-3.0.2/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
```

My assumption from this error is the postgresql service was running, but not yet accepting connections, when we tried to connect/start the app.

**Comment by djuber** [comment]
This appears to be reproducible by stopping, then reopening/restarting a workspace, rather than creating a new branch, where the setup actions take some time to complete - though it's likely waiting for the prebuilt image and then opening the workspace is equivalent (and probably how you got to this point).
