### ISSUE TITLE
Fix Positioning of the "Admin Help Button" on the Display Ad Edit Page

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#15438]
**📖  As a Forem Creator, I want my experience to be as UI pleasing as possible, so that I feel motivated to continue with the journey.** 

_(Format:  As a [persona], I [want to], [so that])_

![Screen Shot 2021-11-19 at 8 39 42 AM](https://user-images.githubusercontent.com/32834804/142650081-2a3aa5e1-e669-43f9-a3c9-9236929b2a82.png)

**🐣TASKS**
- [ ] Adjust the positioning of the admin "help" button so that the "help" button appears in the bottom righthand corner of the screen rather than in the lefthand corner 

**_Note:_** this appears to be the only location where this is happening.

**Comment by ludwiczakpawel** [comment]
This should no longer be an issue. I believe it was "accidentally" fixed :).
