### ISSUE TITLE
Can't edit my blog after trying to add it to a series

### ISSUE THREAD

**Issue by abbeyperini** [forem/forem#15446]
**Describe the bug**

I tried to add https://dev.to/abbeyperini/accessibility-auditing-my-portfolio-site-part-4-omb to a series. Now I can't save any edits even after reverting new changes.

I also can't find a way to remove blogs from series or delete a series while this is messed up? Very irritating.

**To Reproduce**

1. Go to edit blog
2. Click on save changes
3. See "Whoops, something went wrong:" in red at the top of the page

**Expected behavior**

To be able to edit my blog, add it to a series, remove it from a series, or delete a series.

**Screenshots**

<img width="838" alt="Screen Shot 2021-11-22 at 11 49 14 AM" src="https://user-images.githubusercontent.com/68071056/142902113-8623e7c8-1ad0-437d-bd18-5cecdbb3112b.png">

**Desktop (please complete the following information):**

Safari, chrome, chrome incognito tab, and on multiple machines.

**Smartphone (please complete the following information):**

Also in chrome on mobile.

**Comment by cmgorton** [comment]
Hey Abby. I am sorry you are having this experience. I would like to help you debug this issue. Can you tell me how you are turning your post into a series? 
![Screen Shot 2021-11-22 at 1 01 13 PM](https://user-images.githubusercontent.com/21039864/142919952-670fdec8-6340-4cf9-b91a-33e86207135c.png)
Are you using the built in series we have  or are you trying to do it manually? 

In the past when I have seen the `Whoops something is wrong` error it was usually because of something I added to the post. (We should probably look at adding a more descriptive error depending on what caused this. ) Can you tell me what changes you added to our post? That might help me debug the issue for you. Thanks.

**Comment by abbeyperini** [comment]
I didn't add anything to the post. I used the form in your screenshot. It worked for the other 4 parts of the series, and when I selected the existing series on this one, clicked done, and clicked save, I started getting "Whoops something is wrong:". I've tried the "Revert new changes" button several times, but it always comes back. I tried to add it to a different series, tried adding something to the post, and have tried all these things in two browsers on two machines and mobile.

I would also take instructions on how to remove blogs from a series/delete a series.

**Comment by cmgorton** [comment]
Hey @abbeyperini this has been brought up a few times over the last 2 days so I think it is a site wide bug others are experiencing as well. I am going to ping our engineers to get some help on this bug. In the meantime I will see if I can get information for you on how to remove blogs from a series/delete a series.

**Comment by abbeyperini** [comment]
I appreciate it!

**Comment by Zhao-Andy** [comment]
Hey @abbeyperini! Sorry about that bug. There was an incorrect reaction on it and I've manually removed it. You shouldn't have any problems with updating the article or adding a series moving forward. Feel free to reopen this issue if you do have problems though.

**Comment by abbeyperini** [comment]
Thank you! It is fixed. Is there a way to remove blogs from a series/delete a series? If not, I'm happy to put in a feature request.

**Comment by cmgorton** [comment]
Hey @abbeyperini I was investigating that for you. As far as I can find right now the only way to delete a series or remove an article from a series is to go to the widget and remove the series name from the article/ each article in the series. There is no way to remove the series from the dropdown in the widget after it is created. 
![Screen Shot 2021-11-23 at 9 10 13 AM](https://user-images.githubusercontent.com/21039864/143072876-67b90bb2-18ef-44a3-8ff8-7b39e56b1d8a.png)

I think a feature request to more easy delete series or articles from series would be great. You could start a feature request in our GitHub discussions https://github.com/forem/forem/discussions
Let me know if you have any questions or would like me to put the feature request in for you. Thanks!

**Comment by abbeyperini** [comment]
Ahhh I was trying to use the select. Didn't think about clearing the series name and clicking done! Thanks!

Would be great to have clearer instructions about this and a way to delete series, but I feel much better knowing there is a way to remove the widget now.
