### ISSUE TITLE
Posting problem

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [forem/forem#15463]
**Bug Report**

 I can't post anything
Showing like this 👇👇
![Screenshot_20211123-135726](https://user-images.githubusercontent.com/85288261/142988306-bbeb3615-fcd4-460e-9ff4-a75248979b27.jpg)

**Comment by cmgorton** [comment]
Thanks for this bug report. I have seen this issue pop up a few times over the last 2 days. I haven't been able to replicate it but I have pinged our engineers since this seems to be happening to more than one person.

**Comment by Zhao-Andy** [comment]
Hey @MohammadTaseenKhan, I believe this is fixed. Sorry about that bug! Feel free to re-open if you're still having issues.

**Comment by MohammadTaseenKhan** [comment]
Thanks 😊
