### ISSUE TITLE
dev.to site won't let me update - "revert new changes"

### ISSUE THREAD

**Issue by softchris** [forem/forem#15460]
**Describe the bug**
Just published an article to dev.to, changing something in it, press save and I get this red message at the top "Whops something went wrong"

**To Reproduce**

- Produce a new article
- Change anything + Save
- See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by cmgorton** [comment]
I believe #15446 and #15463 are related issues.

**Comment by Zhao-Andy** [comment]
Hey @softchris, I believe this is fixed. Sorry about that bug! Feel free to re-open if you're still unable to update your post.
