### ISSUE TITLE
Again posting problem

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [forem/forem#15477]
It is a matter of great sorrow that I am still seeing the same problem during posting.
You can see the time in my screenshot down given below 👇👇

![Screenshot_20211123-235501](https://user-images.githubusercontent.com/85288261/143078770-498bcff2-2828-4970-b6e3-27910e7a716b.jpg)

**Comment by cmgorton** [comment]
Previous mention of this issue @jeremyf https://github.com/forem/forem/issues/15463

**Comment by cmgorton** [comment]
Hey @MohammadTaseenKhan after looking in to this a little more with our team this looks an issue specific to your account.

Please email yo@dev.to for more information and help.🙏
