### ISSUE TITLE
Weird Flickering in Feed

### ISSUE THREAD

**Issue by carrotfarmer** [forem/forem#15485]
**Describe the bug**
- When I open DEV.to in my browser (Safari), my feed won't load and when I scroll down the whole feed section starts flickering a lot.

**To Reproduce**
I am not sure if this is an issue with everyone but here's what I did:
- Open `dev.to` in Safari
- Scroll down 
- Feed starts flickering

**Expected behavior**
Feed to load **or** the flickering of the feed section doesn't appear.

**Screenshots**

https://user-images.githubusercontent.com/66675022/143258364-796ca206-5598-4669-95a6-1ce0619342c3.mov

**Desktop (please complete the following information):**

- macOS Monterey 12.1
- Safari 15.1

**Additional context**
When I go to my Dashboard, it gives me a 503 error (No healthy IP available for the backend)

**Comment by cmgorton** [comment]
@jeremyf do you think this is related to #15290? Or did that end up not being a Safari specific bug?

**Comment by jeremyf** [comment]
@cmgorton alas, that referenced bug was not a Safari bug.  I'm testing now (though I don't have Monterey installed)

**Comment by jeremyf** [comment]
I switched to Dark Mode (but not Monterey) and things work.  However, in rewatching the video I saw "There was a problem fetching your feed."  And I believe the flickering is because the JS is continually trying to refetch the feed.

So I think we need to figure out why the feed is failing.

**Comment by jeremyf** [comment]
@carrotfarmer Do you have other browsers installed on your machine?  I'm wondering if Firefox or Chrome have the same issues.

Second, I'm wondering what your comfort level is around the Web Inspector tool?  When I was working on a yet to be released Feed update, I broke the Feed, and the behavior looked similar to what you're experiencing.  When I opened Web Inspect and went to the Network tab, I saw lots of JS calls that were failing.

**Comment by carrotfarmer** [comment]
@jeremyf This issue doesn't occur in Brave Browser (based on Chromium), I don't have Firefox installed but I can test it out if you need me to.  Even I saw the failed XHR requests in the network tab and I **guess** it's because the JSON data wasn't reachable at that point? Because I also got 503 errors when I opened my dashboard.

**Comment by jeremyf** [comment]
@carrotfarmer please re-check Safari, and let me know if it's still a problem.  If it is, we'll need to check if it's Monterey OS X or if there's a competing extension or some odd brokenness.

**Comment by carrotfarmer** [comment]
@jeremyf Sure

**Comment by carrotfarmer** [comment]
It's working perfectly right now
