### ISSUE TITLE
Markdown toolbar: browser shared shortcuts

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#15507]
**Describe the bug**

If a shortcut is shared between a browser and the toolbar the js function will run and the browser will also run its shortcut. `e.preventDefault()` will fix this.

**To Reproduce**
1. open chrome to the editor page
2. press ctrl/cmd + U
3. see the issue.

**Expected behavior**
only the forem function should run

**Additional context**

I think you just need to add it here.

https://github.com/forem/forem/blob/d0dea2228c3a9a481bedd78e42ff48cb70e3d4b1/app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx#L78

CC: @aitchiss

**Comment by aitchiss** [comment]
Nice one @Link2Twenty - fix incoming!
