### ISSUE TITLE
`ltag-github-readme-tag` hiding `article-show-more-dropdown`

### ISSUE THREAD

**Issue by Infinity-Intellect** [forem/forem#15500]
**Describe the bug**
When you've scrolled to any pretty embed of a post, and click the `Show More` icon below the save button, the pretty-embedded element seems to overlap the drop-down menu.

**To Reproduce**
1. Go to [this post](https://dev.to/infinityintellect/more-willpower-to-developers-5f6o) on dev.to.
2. Scroll down to the pretty embed in the `Yaml or Link to Code` section
3. Click the `Show More` (3 dots icon) below the `Save` button on the right.
4. You can see that there is a visibility issue.

**Expected behavior**
The pretty embed should not appear on top of the drop-down menu, rather the drop-down menu should appear above the pretty embed.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/49329642/143422966-16bc25b7-c317-4936-9a7c-0eb71a9afa73.png)

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04.2 LTS
- Browser, version: Firefox version 94.0(64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

- **Possible fix:** Remove the z-index from [this line of code](https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/assets/stylesheets/ltags/GithubReadmeTag.scss#L3) would possibly work. I tried this from the developer console and it seemed to work.

If this is an acceptable fix, I would be elated to raise a PR.

**Comment by jeremyf** [comment]
This looks related to #15290.

**Comment by Infinity-Intellect** [comment]
Hi @jeremyf , would the below proposed solution be an acceptable fix or do you anticipate anything else to break on implementing the below ?
> **Possible fix:** Remove the z-index from [this line of code](https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/assets/stylesheets/ltags/GithubReadmeTag.scss#L3) would possibly work. I tried this from the developer console and it seemed to work.

I played around in the browser's developer console and discovered that removing the `z-index` property works.
![Screenshot (1)](https://user-images.githubusercontent.com/49329642/143576662-0cf98cfc-f64e-4be3-ac99-7fcf556a1fec.png)

**Comment by jeremyf** [comment]
I believe @ludwiczakpawel has a fix that's cooking up for the other bug which may well include a `z-index`.

**Comment by ludwiczakpawel** [comment]
@jeremyf thanks for pinging me!

FWIW, this _should_ not be related to #15290. 

@Infinity-Intellect I think you're spot on with that z-index. I'm not sure why we have it there in the first place 🤷‍♂️ 
There're couple other liquid tags with that z-index that should probably be removed:

- [TwitterTimelineTag.scss](https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/assets/stylesheets/ltags/TwitterTimelineTag.scss)
- [GithubReadmeTag.scss](https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/assets/stylesheets/ltags/GithubReadmeTag.scss)
- [GithubTag.scss](https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/assets/stylesheets/ltags/GithubTag.scss)

**Comment by Infinity-Intellect** [comment]
Can I work on this @ludwiczakpawel ?

**Comment by ludwiczakpawel** [comment]
@Infinity-Intellect Absolutely! I'm assigning you to this one. Let me know if you have any questions or need some help!
