### ISSUE TITLE
First onboarding screen is squished on mobile

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#15594]
**Describe the bug**

I hadn't _created_ a user account on mobile before, and going through that flow on onboarding showed me a first screen that was out of whack

**To Reproduce**

- Sign up for new Forem on narrow screen or mobile device
- View checkbox styling on first page is off.

**Expected behavior**

The checkboxes should show up without being messed up as they are. You'll know "correctness" when yo see it.

**Screenshots**

<img width="332" alt="Screen Shot 2021-11-30 at 2 25 46 PM" src="https://user-images.githubusercontent.com/3102842/144114544-a4c02a46-0ec5-47ce-aaa0-eecbd0021d21.png">

**Smartphone (please complete the following information):**

- Device: iPhone X
- OS, version: 15.1
- Browser, version: Forem app

**Comment by squarebat** [comment]
I'd like to take this up!

**Comment by benhalpern** [comment]
Go for it @squarebat!

**Comment by cmgorton** [comment]
Thanks for working on this bug @squarebat 🥳 Let us know if you need any help.

**Comment by squarebat** [comment]
Thanks @cmgorton ! I'll be able to look into this soon and let you know!

**Comment by ktmouk** [comment]
I tried to fix this problem, but apparently this problem has already been fixed. I've attached a screenshot that I took in my local. Probably we can close this issue.  
And I created a PR (https://github.com/forem/forem/pull/20013) to make these lines more readable. Cloud someone review this PR?

<img width="200" alt="スクリーンショット 2023-08-30 21 40 59" src="https://github.com/forem/forem/assets/17381979/1eb35f51-cbfd-4108-b7f9-a1ed0ea6e9ad">

**Comment by rt4914** [comment]
https://github.com/forem/forem/pull/20013#issuecomment-1699638654
