### ISSUE TITLE
There is no "create post" button on a tag landing page when the tag page is empty

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#15633]
**Describe the bug**

There is no "create post" button on a tag landing page when the tag page is empty.

**To Reproduce**

1. Visit an empty tag page and see the lack of "create post" button
2. Visit https://dev.to/t/shecoded and see the "create post" button in the lefthand sidebar

**Expected behavior**

There should be a "create post" button on a tag landing page whether or not the tag page is empty.

**Screenshots**

Empty tag page, no create post button
![Screen Shot 2021-12-01 at 3 58 26 PM](https://user-images.githubusercontent.com/16007075/144313019-52f9a40d-b108-48f5-8c50-8738e7bfcb6a.png)

Tag page with create post button
![Screen Shot 2021-12-01 at 3 59 52 PM](https://user-images.githubusercontent.com/16007075/144313132-bf0e46c3-6fc2-4e7e-81bf-ee3538bb7076.png)

**Additional context**

A Forem creator pointed this out.

**Comment by djuber** [comment]
It looks like the tag being empty (no posts, no description) is not the factor controlling the create post button - https://dev.to/t/rails/ for example does not show the Create Post in the sidebar, only in the top (user) navbar. 

It looks like the difference is the presence of a non-empty "Rules markdown" (configurable in the tag admin area) - putting any string there populates a create post button.

![tag-admin](https://user-images.githubusercontent.com/1237369/144316250-c2b21139-2bb5-43ba-9509-3bf8097d70fd.png)

![tag-show](https://user-images.githubusercontent.com/1237369/144316317-9d0f0c48-69e7-4b64-8029-a8bd11282e49.png)

**Comment by jeremyf** [comment]
I don't think this is related but it's in the neighborhood: https://github.com/forem/forem/issues/15359

**Comment by ellativity** [comment]
I came here to write what @djuber already beat me to writing.

**Comment by djuber** [comment]
@ellativity brought up a good point - this is a documented behavior in the admin guide

https://admin.forem.com/docs/forem-basics/tags#editing-a-tag

> Rules Markdown: Displayed on tag page + in drop-down of rich editor. Filling out this field adds a "Create Post" button to the tag page, taking users straight to a new post in their Post Editor with this tag prefilled.

If this is a request to add a create post to every tag's page we can treat it as a feature request, but it's expected and documented behavior.

@michael-tharrington would you prefer to keep this open (as a suggested improvement), or close the issue?

**Comment by michael-tharrington** [comment]
I don't feel strongly about it and don't believe that it would add very much benefit, so going to close this one.
