### ISSUE TITLE
Loading SVG codes on to screen

### ISSUE THREAD

**Issue by OhDylan** [forem/forem#15646]
**Describe the bug**

Dev.to logo is rendered as SVG codes instead of the SVG itself.

**To Reproduce**

1. You can see it everywhere as it is in the navbar and blocking the content.

**Expected behavior**

Showing the SVG icon instead of the codes.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by OhDylan** [comment]
![Screenshot_2021-12-02-16-41-34-057_com.android.chrome.jpg](https://user-images.githubusercontent.com/49362324/144387550-f0868797-5016-4e72-8637-fb014ead51c3.jpg)

**Comment by iamandrewluca** [comment]
Related https://github.com/forem/forem/pull/15643

**Comment by InHuOfficial** [comment]
> Related #15643

Line 3:  `<%= logo_svg %>` should be `<%= Settings::General.logo_svg %>` I think?

**Comment by iamandrewluca** [comment]
@OhDylan can be closed, was fixed

**Comment by aitchiss** [comment]
Thanks for reporting this issue! It's now been resolved (by https://github.com/forem/forem/pull/15643), but if you see it popping up again, please do let us know
