### ISSUE TITLE
bug homepage

### ISSUE THREAD

**Issue by jmau111** [forem/forem#15645]
**Describe the bug**

bg markup html svg

**To Reproduce**

homepage

**Screenshots**

<img width="1375" alt="screen-devto" src="https://user-images.githubusercontent.com/6878027/144384974-fdfb9553-2e8f-4aaa-9e2f-d51087c8c2c3.png">

**Comment by iamandrewluca** [comment]
Related https://github.com/forem/forem/pull/15643
