### ISSUE TITLE
BUG: Error trying to create or update a post

### ISSUE THREAD

**Issue by dwwhalen** [forem/forem#15642]
Logged in as myself (dwwhalen) I can't save an existing post or create a new post.  I've been aware of this problem since 11/21/2021.

I've tried this with different browsers and different machines(macbook and iPhone) and the behavior is the same.  

I've tried resetting my password and changing authentication but also no luck.

I'd appreciate some help.  Here are some screenshots.  THANKS!

clicking Create Post button:
![image](https://user-images.githubusercontent.com/11508437/144351812-036afb2d-0361-4672-b576-263371f2c0b6.png)

Trying to save an existing post:
![image](https://user-images.githubusercontent.com/11508437/144351881-bbaea46c-b440-4420-b843-4169b384ea26.png)

**Comment by citizen428** [comment]
Hello @dwwhalen, thanks for notifying us of this problem, this looks an issue specific to your account. Please email yo@dev.to for more help.

**Comment by ellativity** [comment]
@dwwhalen I stumbled across this issue while creating one of my own. I've made the required change to your account, so you don't need to email us anymore. I'm closing this issue.
