### ISSUE TITLE
Logo in main site navigation disrupted.

### ISSUE THREAD

**Issue by jeton-th** [forem/forem#15648]
**Describe the problem**

The main website logo is gone. Instead of the logo, some part of the svg code is 
visible, stretching over the page.

**To Reproduce**

Just open [dev.to](dev.to).

**Screenshots**
![Screenshot_20211202-103034](https://user-images.githubusercontent.com/5147537/144395071-fae4a11b-344c-401b-ba59-d22dad52bee6.png)

**Comment by aitchiss** [comment]
Thanks for reporting this issue! It's now been resolved (by https://github.com/forem/forem/pull/15643), but if you see it popping up again, please do let us know
