### ISSUE TITLE
Broken ui - Garbage numbers overlapping main content of website

### ISSUE THREAD

**Issue by amiteshhh** [forem/forem#15655]
Load the page in mobile or desktop in google chrome https://dev.to/codesphere/10-things-you-didnt-know-you-could-do-with-javascript-3k2l
You will see garbage numbers. 
![Screenshot_2021-12-02-22-30-26-902_com android chrome](https://user-images.githubusercontent.com/11266423/144469542-d4bc83ec-3755-498e-a7c3-84d80954bbd1.jpg)

**Comment by nickytonline** [comment]
This should be sorted. There was an issue with the SVG header icon that has since been resolved. Thanks for reporting!
