### ISSUE TITLE
The app shuts down after ~30 seconds

### ISSUE THREAD

**Issue by solution-loisir** [forem/forem#15652]
**Describe the bug**
I installed the dev.to on the home screen of my Pixel 2 xl phone some times in 2019, as a progressive web app. It used to work fine, but in the last month, maybe a little more, it started to behave oddly. When I tap on the dev.to icon, it opens the app and I navigate a little bit, and after about 30 seconds it closes. I usually reopen the app and then it works fine. I'm always logged in. It's consistent for the last month or so. I don't know if anyone eard of that behavior before. It might prove difficult to reproduce.

**To Reproduce**
This might be hard as I just open the app and it does as describe.

**Expected behavior**
To not shut down after 30 second for apparently no reason.

**Desktop (please complete the following information):**

- OS, version: Android recent
- Browser, version: Chrome recent

**Smartphone (please complete the following information):**

- Device: Google Pixel 2 Xl

**Additional context**
Progressive web app installed.

**Comment by nickytonline** [comment]
@solution-loisir, we removed our ServiceWorker earlier this year which is why the PWA no longer works on your phone. We know some folks appreciated having the PWA, but the ServiceWorker had become problematic for us. 

You can read about it on this post on DEV, https://dev.to/devteam/goodbye-offline-page-5d98

**Comment by solution-loisir** [comment]
Thank you @JennieOcken and @nickytonline, for your quick response. That explains everything. I'll go read the issue when I have a minute. Is this bad news for PWA in general. Is there a hope for this feature to be revisited? Thanks for all! 😊

**Comment by JennieOcken** [comment]
For right now, it's bad news for PWA in general. We really want to focus in on the native app experience especially as folks start using multiple Forems and want to move between them (e.g. from DEV to Codenewbie).  In addition, the PWA was creating some technical overhead and burden for our team to maintain and was relatively lightly used.  We have so many awesome things we want to do for DEV and with Forem we have to focus our attention.

Sorry to disappoint. 🙂
