### ISSUE TITLE
UI BUG

### ISSUE THREAD

**Issue by ishaquee** [forem/forem#15668]
**Describe the bug**

This is the UI related Bug ... Like the Text over-floated to the main content 

**To Reproduce**

  https://dev.to/exwhyzed/15-free-reactjs-templates-for-your-next-project-313m 
You can see this bug in above url .... 

**Expected behavior**

Actually the content  is not displaying properly ... 

**Screenshots**

<img width="1680" alt="Screenshot 2021-12-03 at 12 02 19 PM" src="https://user-images.githubusercontent.com/62430742/144556663-03499fb6-48e0-4837-befc-fd291d3ecc9f.png">

**Desktop (please complete the following information):**

- Browser, version: Version 96.0.4664.55 (Official Build) (x86_64). 

**Smartphone (please complete the following information):**

- Device: Redmi Note 9 pro
- OS, version:  miui 12
- Browser, version:

**Additional context**

**Comment by nickytonline** [comment]
This was an issue with header logo that's since been fixed.
