### ISSUE TITLE
Application on Android platform stops abruptly whenever opened for the first time.

### ISSUE THREAD

**Issue by thakur-mohit** [forem/forem#15660]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device: Galaxy S9
- OS, version: Android 10
- Browser, version: NA

**Additional context**

**Comment by nickytonline** [comment]
Can you provide some more information in regards to the issue? Thanks!

**Comment by thakur-mohit** [comment]
When I open app for the first time, it opens and crash abruptly . Second time it works fine. I am experiencing this behaviour from last 1-2 months.

**Comment by thakur-mohit** [comment]
@nickytonline kindly look into this.

**Comment by citizen428** [comment]
Pinging @rt4914, maybe he has something to say on this matter.

**Comment by rt4914** [comment]
I am closing this here as I have filed it in android repo: https://github.com/forem/forem-android/issues/85

I will also check for additional details in crashlytics.
