### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by jsoref** [forem/forem#15669]
**Describe the bug**

Like all projects, this project has typos

**To Reproduce**

1. Add https://github.com/check-spelling/spell-check-this/tree/prerelease/ to forem
2. Adjust excludes (guided by feedback from the workflow)
3. Adjust patterns (guided by the examples)

**Expected behavior**

No typos

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

https://github.com/jsoref/forem/commit/a3e5c1b0991e0384dd0acc3194a07facd44844f5#commitcomment-61290927

<details><summary>Unrecognized words (122)</summary>

```
Acccount
acesss
Activ
addtional
adminsitrative
Advertisments
agregate
assigments
assignes
atrributes
Autcomplete
bacause
beetween
boostrap
caluclating
CATPCHA
chacter
choosen
Collaspe
Columnns
Colums
commentor
competetor
COMPONENTIZE
componetize
conjuction
constrast
contast
correseponding
currrent
defautl
delimeter
descripton
destrous
destroyes
dicussion
eigth
elvaluates
episde
epsecially
esacped
explicitely
exxpired
Facbook
fragement
funcationality
HMTL
identation
impproper
Indentities
insentive
Intdex
intefere
Lastest
locahost
lozalization
messahe
messsage
minumum
modertor
mousover
mutal
nonexistant
notifiaction
notificaton
occasionnally
occurence
occurrs
ocktokit
offest
ommitted
OMNIUATH
onkeykup
opactity
oranization
organizaiton
orgnaizations
Overide
overridding
overriden
prefil
presesented
previos
profilge
programatically
pseudonomization
recyling
registerd
reponse
repositorioes
rescueing
retrns
Scret
secons
SEPERATOR
seprator
servics
slighlty
subcribed
Subcription
submmitted
subsciber
succesfully
successsful
sucess
Sucessfully
Supress
susbcription
Sychronizes
TESET
uknown
Unproductice
unrechable
unsuccesful
Usename
utilitities
utlity
vaild
volountarily
vomitted
Webiste
witholding
```
</details>

**Comment by Ridhwana** [comment]
Hi @jsoref 👋 Has all typos been addressed in the PR's that were merged, can I close this this issue?

**Comment by jsoref** [comment]
Hi @Ridhwana, the tool has the following thoughts:
```
CXgz
dscott
fakeoption
fakeoptionvalue
foucs
gsub'ing
hywlv
idempotently
nocredits
notificaton
nouser
ondemand
retriable
submmitted
withchude
Xro
yheuhtozr
```

So, offhand, I'd imagine the following typos have been added since:

* foucs
* notificaton
* submmitted
