### ISSUE TITLE
Unexpected notifications behaviour #1: notifications persist when post is unpublished

### ISSUE THREAD

**Issue by ellativity** [forem/forem#15675]
**Describe the bug**

If a post author publishes a post and then unpublishes it immediately (e.g. they accidentally published when they intended to save), any user receiving a notification about the publication of the post will continue to see the notification on their `/notifications` page after the post has been unpublished. If they click on the notification, they're greeted with a 404 error.

**To Reproduce**

1. follow a user or organization
2. publish a post under that user or org
3. confirm notification has been received on `/notifications` page
4. unpublish post
5. confirm notification is still displayed on `/notifications` page 
6. click on the notification and get a 404 page

**Expected behavior**

If a post is unpublished, all notifications about that post need to disappear as well. 

It's probably way more work, but if following links from a user's `/notifications` page added something to the url, it could be possible to display a more specific error page in the event a post was removed?

**Comment by jeremyf** [comment]
@ellativity I've been trying to verify this bug, and here's how I'm going about testing on my local machine.  I have two browsers, one for Admin and one for Author.  I have set the Admin to follow the Author.

As Author I write a post and publish it.  As Admin, I see the notification.  Then as Author, I unpublished the post (using the Danger Zone > "Unpublish post" button).  That removes the notification from the Admin's Notifications > Posts.

With the above steps, I cannot duplicate the bug.  However, I did unearth the bug that with the given scenario, if the Author re-publishes the post, the Admin does not get a notification.

**Comment by Glennmen** [comment]
I experienced the same thing.
Notification was still listed but gave a 404 error after opening it.
After that I heard on Discord that the post was unpublished.

@jeremyf The only reason why I think you are not experiencing this on your local machine is because of heavy caching DEV/Forem does and probably doesn't happen on your local machine.
That is only my theory 🤷🏼‍♂️

**Comment by jeremyf** [comment]
I agree @Glennmen , that caching and or the background worker's getting around to their task are the two likely culprits.  And at this point, I can't prioritize more time on resolving this; though I do need to dive further into our caching ecosystem.

**Comment by lightalloy** [comment]
I looked into this issue and found out that when we unpublish post via `admin_unpublish` (from the "Moderate Post" side panel), we use `@article.update` and not `Articles::Updater` service where destroying related notifications is covered. So, the notifications are not destroyed in this case. 
We should also check for other places for this potential bug.

**Comment by lightalloy** [comment]
I implemented a fix in #18047

**Comment by lightalloy** [comment]
Should be resolved by #18047
