### ISSUE TITLE
Update all use of (and reference to) "vomit" to "flag"

### ISSUE THREAD

**Issue by ellativity** [forem/forem#15671]
**Describe the bug**

When the mod tools were updated to "flag" rather than "vomit on" posts, the admin side wasn't updated. Admins still see "vomits" throughout the admin portal (in `/admin/moderation/reports`, user admin views, in `/admin/moderation/privileged_reactions`, etc)

**Expected behavior**

Admins should see "flag" in all situations.

**Screenshots**
In `/admin/moderation/reports`
 ![Screenshot 2021-12-03 at 15 22 23](https://user-images.githubusercontent.com/76786132/144618273-317c9c1e-099b-4a77-9879-dfd0d6ad550a.png)

**Comment by TerabyteTiger** [comment]
I think this is just a specific location to update this, but let me know if this should be filed as it's own bug: 

![hovering the 🧐 reaction shows a "vomit" tooltip](https://user-images.githubusercontent.com/16465776/147942058-5beeaab9-ca6e-4e67-a67b-8788b8eb7b3f.png)


I noticed this on a CodeNewbie Comment Notification - hovering the 🧐 reaction shows a "vomit" tooltip.

**Comment by ellativity** [comment]
Thanks for adding this, @TerabyteTiger - I hope that this would also be switched out with this issue, but maybe one of Forem's engineers would be able to weigh in with more knowledge!
