### ISSUE TITLE
Stackbit blog extension doesn't work on non-DEV Forems

### ISSUE THREAD

**Issue by ellativity** [forem/forem#15700]
**Describe the bug**

At the end of the User Extension Settings page (`/settings/extensions`), there's an option for users to set up their own Stackbit blog with one click:

![Stackbit blog extension on a non-DEV Forem](https://user-images.githubusercontent.com/76786132/144898168-6cfc15c1-caa4-4db1-8b0b-cb62e3188a4b.png)

Clicking on this on DEV returns [`https://dev.to/connecting-with-stackbit`](https://dev.to/connecting-with-stackbit) but since this page doesn't exist on any other Forem, it simply returns a 404 error page.

**To Reproduce**

1. go to any Forem except DEV
2. navigate to `settings/extensions` and scroll down to **Generate a personal blog from your Forem posts** 
3. click `Get Started` to see the error

**Expected behavior**

Either this opens a pre-loaded page like [`https://dev.to/connecting-with-stackbit`](https://dev.to/connecting-with-stackbit) with full functionality, or the section doesn't appear in the User Extension Settings at all.

**Comment by jeremyf** [comment]
In conversations, it sounds like this feature never quite worked.  In consultation with @JennieOcken we're removing the feature.

**Comment by alexandrudanpop** [comment]
This feature worked quite well in the past, my blog was generated using Stackbit from DEV.to

**Comment by citizen428** [comment]
@alexandrudanpop Yes, but it only worked on DEV.to, not the wider Forem-verse. Also, Stackbit disabled this extension on their end, which is why we removed it too. See: https://dev.to/devteam/heads-up-stackbit-integration-removal-2m11
