### ISSUE TITLE
Landing page after Admin actions on User accounts is inconsistent

### ISSUE THREAD

**Issue by ellativity** [forem/forem#15707]
**Describe the bug**

- After clicking “Unpublish all posts” from **Manage User** (e.g. `/admin/users/1/edit` - I'll give example urls for user ID 1), the admin user is shown `/admin/users/` page rather than staying on the **Manage User** page.
- After clicking "Submit note" from a User Admin (either **Admin Profile** or **Manage User** page), the admin user is always shown the **Admin Profile** page (`/admin/users/1`) rather than staying on whichever page they clicked "Submit note" on.

All other User Admin actions return admin users to the User Admin page they were clicked on, so it’s unexpected to be taken elsewhere. 

**To Reproduce**
1. go to `/admin/users/1` or another User Admin page
2. navigate to **Recent Notes** to write a note and click "Submit note" to save it to the User Admin. Notice that the page you're on doesn't change
3. click on "Manage User" to access `/admin/users/1/edit` (or append "edit" to the url)
4. select a new User Status and leave a reason for your change, click on "Update User Status" to save it to the User Admin. Notice that the page you're on doesn't change
5. navigate to **Recent Notes** to write a note and click "Submit note" to save it to the User Admin. Notice that you're returned to the Admin Profile page (or `/admin/users/1` without the "edit")
6. click on "Manage User" to access `/admin/users/1/edit` (or append "edit" to the url)
7. navigate to **Semi-Destructive Actions** to "Unpublish all posts". Notice that you arrive on `/admin/users/` with a confirmation banner at the top of the page
8. hit your back button or go to url `/admin/users/1/edit` to return to **Manage User** page
9. navigate to **Destructive Actions** to "Banish User for Spam!". Notice that the page you're on doesn't change but you still see a confirmation banner at the top of the page

**Expected behavior**

As an admin user, I would expect to stay on the current User Admin page after all actions. 

In particular, I would expect to remain on **Manage User** after "Unpublish all posts" rather than be taken to the `/admin/users/` page. 

**Screenshots**

Expected behaviour: a confirmation banner at the top of the same page I started on

![Confirmation banner at the top of the same page I started on](https://user-images.githubusercontent.com/76786132/145100064-fd645f2b-c274-4d6b-ada6-a19bbf7b040b.png)

**Additional context**

Unpublishing all posts is often clicked as part of a process of suspending a user and removing their published content, so in some admins' workflows, the suspension hasn't even been activated yet. This means they need to return to the User Admin page themselves.

**Comment by juliannatetreault** [comment]
Quick thought: I think that we should hold off on addressing this particular issue since the [Admin Member View work](https://github.com/forem/forem/pull/16174) is underway and the work that has been done so far both changes and standardizes these redirects for the Member view. What do y'all think, @Ridhwana and @ellativity?

**Comment by juliannatetreault** [comment]
Hey @ellativity and @Ridhwana 👋 I'm going to go ahead and close this issue since the official launch of the Admin Member Detail View (launching in the very near future!!) should resolve these inconsistent landing pages. If need be, we can always reopen the issue. 😊
