### ISSUE TITLE
Adding Matrix link to Navigation results in 500 "Ooooops"

### ISSUE THREAD

**Issue by q9f** [forem/forem#15719]
**Describe the bug**

Adding a link to a public matrix community to the left navigation results in a 500 error page:

> **Ooooops...**
>
> You have encountered an error.
> 
> Our team has been notified.
> 
> We apologize for any inconvenience. 

**To Reproduce**

1. Go to Admin  > Customization > Navigation Links
2. Create a new Navigation Link
3. Give it some name, Icon, and weight
4. Add the following URL: `https://matrix.to/#/#state-d:tchncs.de`
5. _Ooooops_

**Expected behavior**

A link should be added to the navigational bar.

**Desktop**

- OS, version: Archlinux, kernel 5.15.6-arch2-1 x86_64 GNU/Linux
- Browser, version: Mozilla Firefox 94.0.2

**Additional context**

Might be a long shot but I had issues with Matrix links before (because of that `/#/#` structure).

* `https://matrix.to/#/#state-d:tchncs.de` ---> 500
* `https://matrix.to//#state-d:tchncs.de` works but invalid link
* `https://matrix.to/#state-d:tchncs.de` works but invalid linkk
* `https://matrix.to/#/state-d:tchncs.de` works but invalid link

**Comment by djuber** [comment]
https://app.honeybadger.io/projects/72638/faults/82978320 I can see the error logged on our end - it looks like a problem accepting the url (probably because of the `#` characters)?

```
URI::InvalidURIError: bad URI(is not URI?): "https://matrix.to/#/#state-d:tchncs.de"

navigation_link.rb 21 allow_relative_url(...)
app/models/navigation_link.rb:21:in `allow_relative_url'

  # still going through the normal validation process.
  def allow_relative_url
    parsed_url = URI.parse(url)
    return unless parsed_url.relative? && url.starts_with?("/")

navigation_links_controller.rb 26 update(...)
app/controllers/admin/navigation_links_controller.rb:26:in `update' 
```

**Comment by q9f** [comment]
Indeed. It fails also in a bare IRB shell:

```ruby
irb(main):001:0> require 'uri'
=> true
irb(main):002:0> URI.parse 'https://matrix.to/#/#state-d:tchncs.de'
/home/user/.gem/ruby/3.0.0/gems/uri-0.11.0/lib/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://matrix.to/#/#state-d:tchncs.de" (URI::InvalidURIError)
	from /home/user/.gem/ruby/3.0.0/gems/uri-0.11.0/lib/uri/rfc3986_parser.rb:72:in `parse'
	from /home/user/.gem/ruby/3.0.0/gems/uri-0.11.0/lib/uri/common.rb:188:in `parse'
	from (irb):2:in `<main>'
	from /usr/lib/ruby/gems/3.0.0/gems/irb-1.3.7/exe/irb:11:in `<top (required)>'
	from /usr/bin/irb:23:in `load'
	from /usr/bin/irb:23:in `<main>'
```

It fails the RFC 3986 regex.

https://github.com/ruby/ruby/blob/master/lib/uri/rfc3986_parser.rb#L67

I will escalate this to the Matrix devs for discussion.

**Comment by djuber** [comment]
The issue seems to be the grammar in RFC 3986 specifies `#` as a gen-delim, but only permits the more limited sub-delim set in fragment components - https://datatracker.ietf.org/doc/html/rfc3986/#appendix-A

I think the ruby regex implementation here is valid based on a quick reading.

**Comment by q9f** [comment]
Yeah, I just recalled, this is actually the second context where I run into this issue.
