### ISSUE TITLE
Forem processing codeblock content as standard content, leading to errors when attempting to share code

### ISSUE THREAD

**Issue by ellativity** [forem/forem#15736]
**Describe the bug**

A Forem Partner shared that they were struggling to publish a post containing a codeblock with 
`<img src="data:image/gif;base64,${this.hidden ? ghostHide : ghost}" />` 
as part of it. They received the error message:

>Whoops, something went wrong:
    base: Invalid markdown detected!

Tests revealed that having the string `src="data` in a codeblock triggers this issue. Removing the `data` in the string above removes the alert.

**Expected behavior**

@maestromac says this is "a security mitigation to remove questionable property from HTML but since that's in the code block it should've been ignored. It's a bug in our Markdown parser."

**Comment by kimesf** [comment]
This seems to still be an issue, can I work on this?

The error (`invalid markdown detected!`) seems to be raised here [(see code)](https://github.com/forem/forem/blob/main/app/services/markdown_processor/parser.rb#L97):

```ruby
def catch_xss_attempts(markdown)
  return unless markdown.match?(Regexp.union(BAD_XSS_REGEX))

  raise ArgumentError, I18n.t("services.markdown_processor.parser.invalid_markdown_detected")
end
```

Those are the regular expressions used for the union [(see code)](https://github.com/forem/forem/blob/main/app/services/markdown_processor/parser.rb#L3):

```ruby
BAD_XSS_REGEX = [
  /src=["'](data|&)/i,
  %r{data:text/html[,;][\sa-z0-9]*}i,
].freeze
```

My approach will be to try to improve the `MarkdownProcessor::Parser::BAD_XSS_REGEX`.
