### ISSUE TITLE
Getting forbidden bots error message on Nodejs web server

### ISSUE THREAD

**Issue by SivaPriya03** [forem/forem#15822]
Hi, I am developing a small portfolio project where I need to fetch my own posts from dev.to via API. It was working fine for the last 2 weeks but I'm getting the following error message from the API now. 
```
{statusCode: 403,statusMessage: "Forbidden Bots"}
```
It seems my web server is getting identified as a bot kindly help me in resolving this issue.

**Comment by citizen428** [comment]
Hi, could you please share the user agent your API client is using for making requests? We recently did some work regarding blocking bots that cause too much traffic and you may have accidentally been caught by that.

**Comment by SivaPriya03** [comment]
Hi @citizen428, am using a NodeJS server hosted in Heroku cloud (http://sivapriya-v.herokuapp.com/)

**Comment by djuber** [comment]
@SivaPriya03 - we recently made a change to our system requiring a non empty user agent header be sent (we had in place the rule that the header should be non-empty, this last week we added a rule saying the header should be sent) - this was to address traffic patterns from problematic bot access to the site.

If you send a user agent header in each request this should fix itself. If you're using the https module in node (`require('https')`) this should be as straigtforward as adding this to the request options 

```javascript
  headers: {
   'User-Agent': 'Node HTTPS', // the value here doesn't matter, but the header is required now
  }
```

**Comment by SivaPriya03** [comment]
@djuber , yeah it works after mentioning the user-agent header. Thank you
