### ISSUE TITLE
Rails 7 update

### ISSUE THREAD

**Issue by citizen428** [forem/forem#15825]
Upgrade the app to Rails 7. This is currently still held back by several gems:

* ✅ `acts-as-taggable-on`
* ✅ `redis-actionpack`
* ✅ `rails-i18n`
* `hair_trigger` has no released version for Rails 7 yet, we're temporarily using my fork

Gems holding back the update which we managed to remove:

* `redis-rails`
* `storext`

**Comment by maestromac** [comment]
resolved with https://github.com/forem/forem/pull/15908
