### ISSUE TITLE
Installing Forem on macOS

### ISSUE THREAD

**Issue by sachinjain007** [forem/forem#15876]
**Describe the bug**

Following this [link](https://developers.forem.com/getting-started/installation/mac) to setup Form at my local.
Issue arise when I execute command `bin/setup` 

**To Reproduce**
- `bin/setup` 

**Expected behavior**
- `bin/setup` command has to be successfully executed.

**Screenshots**

**Desktop (please complete the following information):**

- macOS, BigSur:

**Additional context**
Logs 
```
== 20211209225729 AddMobileMentionNotificationToUserNotificationSettings: migrating
-- add_column(:users_notification_settings, :mobile_mention_notifications, :boolean, {:default=>true, :null=>false})
   -> 0.0033s
== 20211209225729 AddMobileMentionNotificationToUserNotificationSettings: migrated (0.0034s)

Dumping schema

== Performing setup tasks ==
rails aborted!
URI::BadURIError: both URI are relative
/Users/sanjain/Desktop/forem/forem/app/lib/url.rb:19:in `url'
/Users/sanjain/Desktop/forem/forem/lib/tasks/add_navigation_links.rake:29:in `block (2 levels) in <main>'
/Users/sanjain/Desktop/forem/forem/lib/tasks/forem.rake:6:in `block (2 levels) in <main>'
/Users/sanjain/Desktop/forem/forem/lib/tasks/app_initializer.rake:9:in `block (2 levels) in <main>'
/Users/sanjain/Desktop/forem/forem/bin/rails:5:in `<top (required)>'
/Users/sanjain/Desktop/forem/forem/bin/spring:10:in `block in <top (required)>'
/Users/sanjain/Desktop/forem/forem/bin/spring:7:in `<top (required)>'
Tasks: TOP => navigation_links:create
(See full trace by running task with --trace)

== Command ["bin/rails app_initializer:setup forem:setup"] failed ==
```

Didn't change anything in .env_sample and create another file .env with same content of .env_sample

**Comment by djuber** [comment]
This happens to me if I forget to copy .env_sample to .env in the repository before calling setup... since the APP_DOMAIN and related url variables are then empty, and [URL.url](https://github.com/forem/forem/blob/main/app/lib/url.rb#L2-L20) tries to build an absolute url based on a missing host/protocol.

Did you copy the file `.env_sample` to `.env`? It's possibly unclear in the setup guide you followed that even if you're not making any changes to "real keys" you still need to copy the file to provide the base domain information.

I think we can both improve the documentation here and allow for development safe defaults (localhost, http, port 3000) when there's no environment provided.

**Comment by sachinjain007** [comment]
@djuber Thanks, your solution works.

Earlier copied .env file after executing `bin/setup` command. This create issue. Seems like it is required to copy file first then executing further command.


Yeah, I would love to improve the documentation and required further changes. Please let me know the action plan.

**Comment by citizen428** [comment]
I think when running `bin/setup` it should check if `.env` exists and if not copy over `.env_sample` by itself. This already contains workable defaults:

```yaml
APP_DOMAIN="localhost:3000"
APP_PROTOCOL="http://"
```

I think I'll add this tomorrow.

**Comment by djuber** [comment]
@sachinjain007 thanks for letting us know this fixed it for you.

The setup script now checks for the .env file (or creates it from the sample) after #16005, and the documentation has been updated to clarify this  in https://github.com/forem/forem-docs/commit/157c545711d8e5435ced9a956f521fac5a99b2ae - I'm going to close this as completed.
