### ISSUE TITLE
✂️ Remove "Community Emoji" field in /admin/customization/config

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#15877]
## Why
As our work on [admin settings overhaul](https://miro.com/app/board/o9J_lnfhbyo=/?moveToWidget=3458764514917293717&cot=14) continues, we will be removing unnecessary and/or confusing features or tweaking the confusing wording on the interface along the way. This is one of these attempts - expect more to come sporadically.

For this issue specifically, we are removing the "Community emoji" field in `Community Content` under `/admin/customization/config`. Reasons being: 
1. We have gotten quite a few questions on what it does; quite unnecessarily confusing.
2. The function of this field can be easily replaced by adding an emoji directly after "Community name" (see more in current behavior)
   <img alt="Screen Shot 2021-12-27 at 12 08 22 PM" src="https://user-images.githubusercontent.com/11730007/147433414-0c832427-e6f1-404d-a563-620f7ab91b80.png">

## Current behavior 

The joint use of "Community name" and "Community emoji" results in 4 different titles:

1. No emoji used: appending a "🌱" by default   
   <img width="980" alt="1-empty" src="https://user-images.githubusercontent.com/11730007/147433934-955d0658-4e8f-4e8a-a7e1-009c6bf4b215.png">
   <img width="314" alt="1-empty-result" src="https://user-images.githubusercontent.com/11730007/147433935-988c4427-2adf-44da-9245-2a1313471025.png">

1. emoji used: replacing "🌱" with the specified emoji
   <img width="957" alt="3-using an emoji in emoji field" src="https://user-images.githubusercontent.com/11730007/147433966-1863064d-e8e7-4ef2-8c9a-2ecf0c846caa.png">
   <img width="437" alt="3-using an emoji in emoji field-result" src="https://user-images.githubusercontent.com/11730007/147433962-8ef4f581-4567-42de-bc17-6c7d4e90510a.png">

1. emoji not used + appending an emoji in "Community name": showing both the emoji in "Community name" and the default "🌱"
   <img width="974" alt="2-appending an emoji to the name field" src="https://user-images.githubusercontent.com/11730007/147434010-5b001ec9-e44a-4d81-a99e-f5f3ea78559f.png">
   <img width="456" alt="2-appending an emoji to the name field-result" src="https://user-images.githubusercontent.com/11730007/147434007-2123ff16-ffee-49f7-87eb-78147432c072.png">

1. emoji not used + appending an emoji in "Community name": showing both (not screenshot but verified)

## New behavior
1. Remove the "Community emoji" field
2. Remove the behavior of adding "🌱" emoji by default
2. (Nice to have, one-time migration) If detecting "Community emoji" being used, appending used emoji at the end of "Community name"

## Notes
1. We should involve community success team to notify our clients and self-hosters (referred to as "Forem owners" below) when this is going on production. Form of communication TBD. Potentially a short post on forem.dev.
2. If we decide to not to migrate for existing Forem owners, then the communication needs to go out beforehand. This is rather a small change, but it is still nicer to notify the change beforehand.

**Comment by Ridhwana** [comment]
- https://github.com/forem/forem/pull/16896
- https://github.com/forem/forem/pull/16902
- 
@amywtlin I'm trying to close off these work in progress PR's and want to clarify the following please: 

Currently, the community emoji is used for the purpose of appearing after the community name just on the page title ( and nowhere else in the app).  When we display the community name in other places like emails, modals, onboarding etc., we do not place the community emoji after the community name. 

> The function of this field can be easily replaced by adding an emoji directly after "Community name" (see more in current behavior)

Hence, if we alter the code as per the requirement above, we're going to start seeing the emoji (which will now be part of  the name once we remove the actual `community_emoji` field) in every place where we print the `community_name` including these modals, emails etc. which will be a change from what we previously had. 

Hence, I want to clarify if this is okay and if its still the route we want to go?

**Comment by amywtlin** [comment]
@Ridhwana I think that is okay. I think I will write a quick heads-up post on forem.dev and let Creators know how they can remove the emoji if they want to. Changing the `changelog` for this one...

**Comment by amywtlin** [comment]
@Ridhwana got it, thanks for the heads-up!
