### ISSUE TITLE
✂️ Remove duplicate sign in/up link in Nav menu for non-logged-in users

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#15921]
Right now, for non-logged-in users, we have a a sign up/in modal on top of the nav bar, and another text link to sign up/in below. 

It is quite a duplicate for the second one in the nav menu. Let's remove it and only keep the modal on top.

<img width="526" alt="Zrzut ekranu 2021-12-30 o 13 27 31" src="https://user-images.githubusercontent.com/11730007/147898801-fa88cc74-bc6d-46f6-a9ae-82d869478e17.png">
_Photo credit: @ludwiczakpawel _

**Comment by citizen428** [comment]
Adding a special case for a single navigation link is not something I'm super fond of since they are rendered automatically from a data structure. We can do it though.

**Comment by amywtlin** [comment]
@citizen428 I actually think this link should be removed altogether. I specified for non-logged-in users only because I am not sure if this is used in any other scenario that might still make sense.

Can we see if there's any other scenarios that we show this link from the code base, to decide if it's safe to remove it altogether? I am aware this does not show up when users are signed in.

**Comment by citizen428** [comment]
Sure @amywtlin, I can have a quick look.

**Comment by citizen428** [comment]
@amywtlin To me it seems like this could easily be removed. I forgot that the "Home" and "Sign In/Up" links are already special cased, as they exist for every Forem instance. The releant codenis in `app/views/layouts/_main_nav.html.erb`:

```ruby
    <li>
      <% unless user_signed_in? %>
        <a href="<%= sign_up_path %>" class="c-link c-link--block c-link--icon-left fw-bold">
          <%= inline_svg_tag("twemoji/handshake.svg", class: "crayons-icon crayons-icon--default c-link__icon", aria_hidden: true) %>
          <%= t("views.main.signup") %>
        </a>
      <% end %>
    </li>
```

From what I can see we could just delete these few lines and be done with it.
