### ISSUE TITLE
Code of Conduct, Privacy Policy, and Terms of Use Nav Links Keep Coming Back After Being Deleted

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#15960]
**Describe the bug**

A number of non-DEV Forems are hoping to remove the default navigation links for Code of Conduct, Privacy Policy, and Terms of Use. They are able to successfully delete these links, but the links eventually come back. We're thinking this is likely happening when a Creator updates their cloud instance to the latest version of Forem.

**To Reproduce**

Here's [a video](https://www.loom.com/share/362b6914a7fd4eddb32f82355a481791) that shows how to remove the nav links.

Here's a more recent screenshot of jess.forem.lol (our Forem for testing) that shows the nav links have returned:

![Screen Shot 2022-01-05 at 9 44 23 AM](https://user-images.githubusercontent.com/16007075/148236590-977e491b-2756-4501-b7b8-381f767ff5fb.png)

**Expected behavior**

Deleted nav links should be removed permanently unless they are added back. Updating the Forem should not revert any removed nav links.

**Comment by citizen428** [comment]
So, the problem here seems to be this:

* We have a Rake tasks called `navigation_links:create` which adds all the default navigation links.
* This tasks is called from the `forem:setup` tasks
* The `forem:setup` task is called from the `app_initializer:setup` tasks
* `app_initializer:setup` is called on every deploy (`release-tasks.sh`) and container build (`scripts/entrypoint.sh`)

That last step means that all navigation links from the default set will reappear since this tasks is completely unconditional. We either have to find a better way to only run this task on initial Forem creation only or make it conditional in some way (which might be brittle).

**Comment by citizen428** [comment]
@ludwiczakpawel It definitely can be fixed. How exactly may need some discussion but nothing major I think.

**Comment by jeremyf** [comment]
Thank you @citizen428 for some way finding. I self assigned this to look at tomorrow and lay out a game plan.

**Comment by jeremyf** [comment]
## Information Gathering

The `rake` invocation chain:

-   The [navigation_links:create](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/lib/tasks/add_navigation_links.rake#L26) task loads several URLs.
-   The [forem:setup](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/lib/tasks/forem.rake#L5) task invokes `navigation_links:create`.  At present the only task for `forem:setup` is `navigation_links:create`.

The places we invoke `forem:setup`:

-   The [app_initializer:setup](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/lib/tasks/app_initializer.rake#L3) task invokes `forem:setup`.
-   The [bin/setup](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/bin/setup#L38) script explicitly invokes `app_initializer:setup` (which invokes `forem:setup`) and then explicitly invokes `forem:setup`.

The places we invoke `app_initializer:setup`:

-   The aforementioned [bin/setup](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/bin/setup#L38) script.
-   The [scripts/entrypoint.sh](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/scripts/entrypoint.sh#L42) script.
-   The [forem/release-tasks.sh](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/release-tasks.sh#L18) script.

Callers/references to `bin/setup`:

-   [gitpod-init.sh](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/gitpod-init.sh#L8)
-   [forem-docs:docs/getting-started/start-app.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/getting-started/start-app.md)
-   [forem-docs:docs/getting-started/installation/linux.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/getting-started/installation/linux.md)
-   [forem-docs:docs/getting-started/installation/windows.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/getting-started/installation/windows.md)
-   [forem-docs:docs/getting-started/workflow.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/getting-started/workflow.md)
-   [forem-docs:docs/getting-started/installation/mac.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/getting-started/installation/mac.md)
-   [forem-docs:docs/getting-started/syncing.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/getting-started/syncing.md)
-   [forem-docs:docs/troubleshooting.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/troubleshooting.md)
-   [forem-docs:docs/backend/data-update-scripts.md](https://github.com/forem/forem-docs/blob/4c5b78ff2d58620735f4fc720bdf4741926ffd7b/docs/backend/data-update-scripts.md)

Callers/references to `scripts/entrypoint.sh`:

-   [forem/docker-compose.yml](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/docker-compose.yml#L27)
-   [forem/container-compose.yml](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/forem/container-compose.yml#L27)
-   [forem/Containerfile](https://github.com/forem/forem/blob/3253ba2c7a03594a9064abf2aa4c3fba085099f5/Containerfile)

Callers/references to `forem/release-tasks.sh`:

None.

## PlantUML Diagram

### Diagram

![navigation_links-create](https://user-images.githubusercontent.com/2130/149540199-2bce5012-1fbe-40a7-809b-9791b6b7484a.png)

### Text

Below is a [PlantUML](https://plantuml.com/) textual representation of the relationship graph.

```plantuml
@startuml
  !theme amiga
  
  title "Call and documentation graph for navigation_links:create task."
  footer "See https://github.com/forem/forem/issues/15960"
  
  ' This is the task that we call which is creating the issue.
  
  "navigation_links:create task" as nlc
  agent  note right of nlc
  Note: finds or creates
  side links
  end note
  
  ' This section defines the reference points
  agent "forem:setup task" as fs
  agent "app_initializer:setup task" as ais
  file "bin/setup script" as bs
  file "scripts/entrypoint.sh script" as se
  file "forem/release-tasks.sh script" as frt
  file "gitpod-init.sh script" as gi
  package "forem-docs" as foremDocs {
    artifact "getting-started/start-app.md" as dgssa
    artifact "getting-started/installation/linux.md" as dgsil
    artifact "getting-started/installation/windows.md" as dgsiw
    artifact "getting-started/workflow.md" as dgsw
    artifact "getting-started/installation/mac.md" as dgsim
    artifact "getting-started/syncing.md" as dgss
    artifact "troubleshooting.md" as dt
    artifact "backend/data-update-scripts.md" as dbdus
  }
  file "forem/docker-compose.yml" as fdc
  file "forem/container-compose.yml" as fcc
  file "forem/Containerfile" as fc
  
  ' This section describes the relationships
  fs --> nlc : "calls"
  ais --> fs : "calls"
  bs --> ais : "calls"
  bs --> fs : "calls"
  se --> ais : "calls"
  frt --> ais : "calls"
  gi --> bs : "calls"
  foremDocs -l-> bs : "documents\nusage of"
  fdc --> se : "calls"
  fcc --> se : "calls"
  fc --> se : "calls"
@enduml
```

**Comment by jeremyf** [comment]
My instinct is to say that we should have a conceptual separation between an initial setup and a synchronization.  The setup would run the link task.  The synchronization would not.
