### ISSUE TITLE
Add ability for admins to override/remove a TagAdjustment from an article

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#16044]
When a moderator removes a tag (known as a `TagAdjustment`), sometimes it was done in error or by accident. As an admin, there is currently not any way to remove that adjustment.

Ideally, we should list all the `TagAdjustment`s on an article, and then show it to only the admin. The admin should then see an option to remove the adjustment. Some other things we might want to consider adding is:
- automatically sending a notification to the author and the moderator who added the adjustment (possibly out of scope)
- caching

**Comment by mirie** [comment]
Superseded by [Allow tag moderators to override other tag moderators actions#19824](https://github.com/forem/forem/issues/19824)
