### ISSUE TITLE
Add a mobile view for the Preact modal component

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#16049]
## Description

Provide a mobile view for the modals in the application. Here are designs proposed by @anujbhavsar96:

### Modals (all screens sizes at the moment)

![image](https://user-images.githubusercontent.com/833231/148952496-fdc752f7-20f9-4956-8ebf-8bf8bccd16ee.png)

### Mobile View of Modals (proposed)

![image](https://user-images.githubusercontent.com/833231/148952569-4f5f6d71-384f-4f73-a820-d0a2178f3c7b.png)

Anuj, for clarification, I imagine the mobile modal view would cover the entire screen?

**Comment by aitchiss** [comment]
Is this specific to the admin area? I was just wondering because we already have this fullscreen mobile modal layout in the main app:

<img width="412" alt="DEV login modal on mobile" src="https://user-images.githubusercontent.com/20773163/149768341-c5236a1f-0cbd-4f49-ad45-15a551d8a6ca.png">

**Comment by nickytonline** [comment]
Ahh good to know. No this was for the app in general. I'll go ahead and close this.
