### ISSUE TITLE
Incorrect label for profile field

### ISSUE THREAD

**Issue by zcdunn** [forem/forem#1607]
**Describe the bug**
The profile field 'Mastodon URL' is incorrectly labeled.

**To Reproduce**

1. Go to 'Settings'
2. Scroll down to 'Mastodon URL'
4. See label

**Expected behavior**
The label should be more general, e.g. 'Fediverse URL' or 'Fediverse Handle'. 

**Additional context**
Mastodon is only one software that connects to the network known as the 'Fediverse'. Others include Pleroma, Micro.blog, Microblog.pub, Friendica, Osada, Hubzilla, and Kroeg. See [fediverse.network](https://fediverse.network) or [fediverse.party](https://fediverse.party) for more info.

**Comment by benhalpern** [comment]
Hmmmm I know what you mean, but is Mastodon not still its own special case within the fediverse? Folks have a Mastodon logo associated with this url when it is displayed on their profile, and sort of identify as that being a network they belong to and have a presence in as opposed to thinking of the fediverse more broadly.

Happy to have the conversation and we can settle on any changes that should happen if appropriate. 🙂

**Comment by zcdunn** [comment]
Mastodon is the largest implementation, but it's not a special case. Any AP implementation is on the same level. I have an account on a Pleroma instance and it seems odd that it would be displayed as a mastodon link. You can be a part of that network without using mastodon or interacting with any mastodon user.

**Comment by zcdunn** [comment]
> Login or use your Fediverse account to interact with this article

To show prior art, [this](https://baptiste.gelez.xyz/~/Tests/hey-hey) is a link to a [Plume](https://github.com/Plume-org/Plume) article. You can see in the comment section it uses 'fediverse' to describe the network.

> fediverse.space is a tool to visualize networks and communities on the fediverse.

This is how [fediverse.space](https://fediverse.space/) describes itself in it's about modal.

**Comment by benhalpern** [comment]
Circling back here. We'll consider this the next time we modify this functionality or implementation in any way (right now, the initial implementation of "Mastadon URL" is probably incomplete either way since we rely on a hardcoded allowed list.)

I don't know the answer but we'll consider this argument in the next cycle.

**Comment by zcdunn** [comment]
not stale. As stated in https://github.com/thepracticaldev/dev.to/issues/2617#issuecomment-492322189, the UI will be updated to resolve this issue

**Comment by zcdunn** [comment]
not stale. There's is an [open PR](https://github.com/thepracticaldev/dev.to/pull/4551) to fix this issue, but it hasn't been merged.

**Comment by mstruve** [comment]
Hey @zcdunn! Thank you for opening this issue! Since the related PR has been closed and we are in the process of completely overhauling our profile fields I am going to go ahead and close this. Thank you so much for being a part of the Forem community and feel free to reach out if you have any questions!

**Comment by zcdunn** [comment]
@mstruve Hi could you reopen this one. The PR above wasn't merged and this was never fixed. There's still a field labeled _Mastodon URL_, which, according to https://github.com/forem/forem/issues/2617#issuecomment-492322189, was supposed to be updated.

**Comment by mstruve** [comment]
Hi @zcdunn,

Thanks so much for the feedback! We are going to stick with Mastodon URL for now when it comes to dev.to. With our profile field generalization work, we will then have the ability to add more URLs for different Fediverse networks in the future but currently, we are going to keep what we have as is. The code and implementation of these fields are changing quickly and now is not a good time to be updating the field names themselves as it would add a lot of complexity. 

If you would still like to include a URL to a different Fediverse I would suggest maybe putting it in your Bio so others can find it and click on it. 

Thanks so much for your understanding and patience as we work to make Forem a great place for users and creators alike!
