### ISSUE TITLE
Remove hardcoded "Home" link from sidebar navigation

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#16076]
Right now the "Home" link in the main navigation is hardcoded so Admins can't customize or remove it.

It's been reported by admins several time that they would like to be able to do something about it. Hence this issue.

The idea is to:
1. Remove [hardcoded Home link](https://github.com/forem/forem/blob/main/app/views/layouts/_main_nav.html.erb#L6-L11).
2. Add it back as a dynamically created link in admin's _Navigation_ section `/admin/customization/navigation_links`, on the 1st position.
3. Make sure freshly setup Forems come with that link being added/prepopulated in _Navigation_.

Even though step 2 might seem weird (i.e. _adding what we've just removed?!_) it is the way to not harm those who still want it while at the same time leaving a door to edit/remove if anyone needs to.

---

**FYI**

- We've recently [done similar thing for "Signup" links](https://github.com/forem/forem/issues/15921).
- Related Slack convos:
    - [#pod-admin-experience thread](https://forem-team.slack.com/archives/C01S4QZUDNC/p1641913128078900).
    - From private channel for @Amy: https://forem-team.slack.com/archives/C02DKQ56GU9/p1641373341126500?thread_ts=1641336411.122200&cid=C02DKQ56GU9

cc'ing @Ridhwana @amywtlin @JennieOcken @nickytonline

**Comment by citizen428** [comment]
So what you're saying essentially is "Remove the hardcoded Home link and add it to the default navigation links so it can be removed/customized?", correct? In this context I want to point out the following issue that shows that removal might actually not work:

https://github.com/forem/forem/issues/15960

I think I also know why, see this comment:

https://github.com/forem/forem/issues/15960#issuecomment-1007109101

**Comment by ludwiczakpawel** [comment]
> "Remove the hardcoded Home link and add it to the default navigation links so it can be removed/customized?", correct?

Correct. 

> the following issue that shows that removal might actually not work

That's clearly a bug, but probably not blocking, or depending on, this issue, right?
Nevertheless, definitely worth pointing out. And even fixing :D

**Comment by citizen428** [comment]
> That's clearly a bug, but probably not blocking, or depending on, this issue, right?

Well, we are making this change so that creators can potentially remove the Home link but they won't actually be able to remove it in a way that stays removed past deploys. But sure, the two issues can be tackled independent of each other.
