### ISSUE TITLE
Series count on dashboard includes empty series

### ISSUE THREAD

**Issue by Anshuman71** [forem/forem#16129]
**Describe the bug**

The Series link on the dashboard shows "3" series on my account [anshuman_bhardwaj](https://dev.to/anshuman_bhardwaj) but when I open the link it shows only two because on the Series page it shows nonempty series. I read the #9658 issue and the corresponding PR #11227.

**To Reproduce**

1. you can create an article, add a series to that article. Save the Series/article, and create another article and a new series.

2. After saving the new series/ article, replace the second article series with the first series created.

3. There should now be one series without any articles.

4. Go to the dashboard index view, the series count shown will be 2 while on the series index view only 1 series is shown.

**Expected behavior**

It should show "Series 2" and not "Series 3"

**Comment by Anshuman71** [comment]
@juliannatetreault thanks for taking a look. Can you please help me with #16130? @citizen428 wrapped the PR but didn't merge yet, anything I can do to help?

**Comment by juliannatetreault** [comment]
👋  @Anshuman71 

I will review the PR today! PRs require two approvals in order to be merged, which is why @citizen428 hasn't merged the work yet.

Thanks so much for your contribution!

**Comment by Anshuman71** [comment]
The issue seems to be fixed.
