### ISSUE TITLE
Add guides for size requirements to the Logo Upload Fields

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#16134]
Add a minimum size guideline to the wording as per
See https://forem-team.slack.com/archives/C01S4QZUDNC/p1641898734063400

**Comment by mirie** [comment]
@PhilipHow I think we only have 1 logo field, but seems a small update for Hacktoberfest as long as we provide the copy. What do you think?

**Comment by mirie** [comment]
Ah, nevermind! Was looking org pages. Looks like we've already done this work!
