### ISSUE TITLE
Add bulk GET for tags

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#16162]
This issue is to allow data for multiple tags to be fetched in one call.

## Additional context

The new tags autocomplete in the editor requires a tag's `bg_color_hex`, `short_summary` and badge URL to be able to show the enhanced UI for options and selections. The `/search` and `tags/suggest` endpoints were previously updated to provide this information, however when we edit an existing post, we need to fetch the tag information for 1 - 4 tags to display them correctly as default selections in the tags field.

https://github.com/forem/forem/pull/16025 currently works around this by making separate calls to `/search/tags` for each of the post's tags. It would be great to replace this with a single network call, and it would also be great if that call only returned tags with an exact matching name (rather than the current `search` endpoint which will return e.g. both `java` and `javascript` for search term `java`.

## Related to 

https://github.com/forem/forem/pull/16025
https://github.com/forem/forem/issues/14845

**Comment by jeremyf** [comment]
I'm inclined to think about amending the `tags/suggest` to allow for handling a `params[:names]`.  When given `params[:names]` you'd further scope the query with `.where(names: params[:names])`.

**Comment by aitchiss** [comment]
> I'm loath to make a new end-point, but definitely want to add the ability to pass the tag names to the end-point.

At the moment a straightforward 'get me this tag' doesn't _really_ fit conceptually with the endpoints we currently have though... `/tags/suggest` is only used to return supported, popular tags, and feels very different in purpose to me than "get me the details for X tag". I'd usually expect the proposed kind of fetch to happen at `GET /tags` 🤷‍♀️ 

As a small aside, the current source of specific tag data is `/search/tags` which also doesn't feel like the right fit for what we need, because it (rightly) returns partial matches.

At the end of the day though I'm happy to go with whatever the person working on this thinks is right 🙂
