### ISSUE TITLE
Video upload not working on Dev and other Forems

### ISSUE THREAD

**Issue by leewynne** [forem/forem#16186]
**Describe the bug**

When navigating to /videos/new and attempting to upload a video the response in the Chrome JS console returns:

Failed to load resource: the server responded with a status of 403 (Forbidden)
s3.amazonaws.com/dev-to-input-v0/:1 

Failed to load resource: net::ERR_CONNECTION_RESET

**To Reproduce**

1. Navigate to your dashboard
2.  Hit upload video
3. Attempt to upload video
4. Open Chrome dev tools, view console response.

**Expected behavior**

Video uploads progress begins and completes, creates a new article, transcoding occurs, backend is notified of details, article ready for edit / publish

**Desktop (please complete the following information):**

- OS, version: MacOs
- Browser, version: Chrome Version 97.0.4692.71 (Official Build) (x86_64)

**Additional context**

Tested against Safari, same result.

Seems to have only occurred within the past 2 weeks. I use video upload with the same backend AWS transcoding configuration on thismmalife.com, I came across the issue there first and then tested and got the same result on Dev.

**Comment by whykay** [comment]
> **Describe the bug**
> 
> When navigating to /videos/new and attempting to upload a video the response in the Chrome JS console returns:
> 
> Failed to load resource: the server responded with a status of 403 (Forbidden) s3.amazonaws.com/dev-to-input-v0/:1
> 
> Failed to load resource: net::ERR_CONNECTION_RESET
> 
> **To Reproduce**
> 
> 1. Navigate to your dashboard
> 2. Hit upload video
> 3. Attempt to upload video
> 4. Open Chrome dev tools, view console response.
> 
> **Expected behavior**
> 
> Video uploads progress begins and completes, creates a new article, transcoding occurs, backend is notified of details, article ready for edit / publish
> 
> **Desktop (please complete the following information):**
> 
> * OS, version: MacOs
> * Browser, version: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
> 
> **Additional context**
> 
> Tested against Safari, same result.
> 
> Seems to have only occurred within the past 2 weeks. I use video upload with the same backend AWS transcoding configuration on thismmalife.com, I came across the issue there first and then tested and got the same result on Dev.

I can confirm that this is happening to me also on latest version of Chrome. I was going to log a bug when I saw this. Will use the embed video for now instead of upload video, and I do appreciate that this is a beta feature, so bugs can happen.

**Comment by mmafrar** [comment]
I'm also facing the same problem. Here's the link: https://github.com/forem/forem/issues/5519#issuecomment-1019413231

**Comment by maestromac** [comment]
This issue is resolved. Please give it a try! one side note is that the frontend code is a bit buggy and the redirect may not be working right now but I'm working on it.

**Comment by leewynne** [comment]
You LEGEND

Working like a charm 🥳
