### ISSUE TITLE
Support Codepen Prefill Embeds

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#1620]
**Is your feature request related to a problem? Please describe.**
As a user I'd like to be able to embed codepen snippets without having to leave my DEV editor context.
Codepen has a cool new feature which supports this:

https://blog.codepen.io/2019/01/17/introducing-prefill-embeds/

**Describe the solution you'd like**
I imagine this would work similarly to how we do the `runkit` tag.

Something like

```
{% codepen %}
this is the code
{% endcodepen %}
```

We get something like that, we'd wrap it with the right html tags as the blog post specifies. I imagine the tag could know the difference between `{% codepen appropriate_id %}` and the kind with the executable body, similar to how Runkit already works with preamble.

Related, I believe the issue with Runkit not working properly in comments is still going on. Could be simultaneously investigated.
https://github.com/thepracticaldev/dev.to/issues/1163

For info on how to work with liquid tags: https://docs.dev.to/liquid-tags/

**Comment by shshaw** [comment]
That would be a lovely feature to have added!

The recommendation from the CodePen team would be syntax akin to this, replacing instances of two backticks with three backticks, as per typical markdown code blocks.

```
{% codepen height="500" default-tabs="html,result" scripts=["url.js"] styles=["url.css", "secondurl.css"] %}
``html 
<div>Hello World</div>
``

``css
body { background: red; }
``

``js
console.log('Hello world');
``
{% /codepen %}

```
The biggest requirement would be adding the `data-lang` attribute to the `<pre>` code blocks generated by the markdown, and supporting the preprocessors available ( `scss`, `markdown`, `babel`, etc.). If that's not possible then perhaps additional Liquid Tags like `{% js preprocessor="babel" %}` would be needed.

Documentation for the Prefill Embeds and acceptable parameters are written up here:
https://blog.codepen.io/documentation/prefill-embeds/

**Comment by mstruve** [comment]
Given this is a very DEV-centric feature and we have other options for embedding code I would propose we forgo this and the added complexity it brings to our base codebase. I think in the future adding a feature like this in a plugin would be great but for now I propose we close this issue.

**Comment by cmgorton** [comment]
I agree with Molly. I am going to go a head and close this issue.
