### ISSUE TITLE
Remove requirement of "name" from user invitation/creation flow

### ISSUE THREAD

**Issue by JennieOcken** [forem/forem#16226]
**Why**
Right now the invitation flow is a barrier to some of our new Creators.  While it is easy to invite a handful of users, it is difficult to do mass invites.  This is because we require both a `name` and `email address` for each user.  If we reduced the requirement to only 'email address' that would open us up to allowing bulk load of users through the UI or allowing the import of users through an API.  I have had requests for both from Creators.

**Background**
Right now we use `name` to generate the username.  Usernames are unique and are used for tagging, searching, and the profile URL.  The user can change their username in settings as of [the RFC to set username during onboarding](https://github.com/forem/rfcs/blob/f25e5562e8179a4acd89384f24e31726769613f3/text/0000-set-username-onboarding.md).  However we are still using the `name` to create the `username`...

```  username = "#{name.downcase.tr(' ', '_').gsub(/[^0-9a-z ]/i, '')}_#{rand(1000)}"```

The addition of random characters is because username is unique.  This is the only use of the name in the system.  Email address is used throughout and is required for notifications.

**What**
Eliminate the need to have a 'name' in the invitation flow and only use 'email address' as the only required field to invite a user. To do this, we would need to change the logic of how the username is built to use the part of the email address before the @.

**Comment by JennieOcken** [comment]
This would resolve this RFC: https://github.com/forem/rfcs/pull/48

**Comment by aitchiss** [comment]
I've been working on this issue in https://github.com/forem/forem/pull/17438, but came up against an issue - when a user accepts their invitation, they can't progress past setting their password as the "Name" field is failing validation:

![Name is too short](https://user-images.githubusercontent.com/20773163/165493441-70dde963-4c2c-459e-8e7b-18d2c1256e86.png)

I'm thinking the solution here would be to allow/require the user to set their name in this same form, and update the header to something more general like "Finish setting up your account". Does this sound acceptable @JennieOcken / @Ridhwana ?

**Comment by Ridhwana** [comment]
> I've been working on this issue in #17438, but came up against an issue - when a user accepts their invitation, they can't progress past setting their password as the "Name" field is failing validation:
> 
> ![Name is too short](https://user-images.githubusercontent.com/20773163/165493441-70dde963-4c2c-459e-8e7b-18d2c1256e86.png)
> 
> I'm thinking the solution here would be to allow/require the user to set their name in this same form, and update the header to something more general like "Finish setting up your account". Does this sound acceptable @JennieOcken / @Ridhwana ?

This seems like the most natural route to me and is probably like the ideal place for a user to set their "Name" field. I think changing the header is a nice touch too. Let's wait for @JennieOcken's confirmation as well as this relates to product.

**Comment by JennieOcken** [comment]
I feel like where we want to end up is removing the requirement to have a name so this solution actually feels like it is moving in the wrong direction.  What am I missing? Is this a short term solution to remove this problematic interaction and we will come back later and remove the name requirement entirely later?

**Comment by Ridhwana** [comment]
> 

@JennieOcken this moves the name requirement from having the admin fill it out to having user set their name naturally when they sign up.

**Comment by JennieOcken** [comment]
Ahhhh!  That was what I was missing.  Yes, I agree with this approach.  Thank you for filling in the dots for me.
