### ISSUE TITLE
Expect bin/setup to clear cache on developer machine

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16251]
**Describe the bug**

When I run `bin/setup` on my machine, I would expect that this would clear the `Rails.cache`.  There is a logged message saying `== Bust Caches ==`.

**To Reproduce**

This assumes you're running a local Redis instance, and your Rails app is using Redis for it's application cache:

1. Open a Rails console (e.g. `rails console`)
2. In the Rails console add something to the cache (e.g. `Rails.cache.write("My Key", "My Value")`)
3. Verify that it's in the cache (e.g. `Rails.cache.read("My Key")`)
4. In another shell, run `bin/setup`
5. Check the cache (e.g. `Rails.cache.read("My Key")`), it's still there.

**Expected behavior**

When I run `bin/setup` on my local machine, I would expect to clear my application cache (based on the messages in the output).

**Comment by jeremyf** [comment]
@aitchiss Does this capture your expectation?

**Comment by citizen428** [comment]
> When I run `bin/setup` on my machine, I would expect that this would clear the `Rails.cache`.

This assumption is wrong. Though I can see how it's confusing, the message isn't super clear about what's happening.

1. `== Bust Caches ==` is printed from `lib/tasks/app_initializer.rake`
2. This does indeed enqueue a job for clearing caches (`cache:enqueue_path_bust_workers`) so it assumes Sidekiq is running. In all fairness, it should be, we recommend running the app through `Procfile.dev` (e.g. with overmind or with `foreman start -f Procfile.dev, see `bin/startup`) which will start Sidekiq workers.
3. Looking at the tasks in `lib/tasks/cache.rake` you'll notice it calls `BustCachePathWorker`
4. This worker is __not__ about clearing the local Rails cache but the edge cache (it class the `EdgeCache::Bust` service.

Anyway, I added a new task to clear the app cache and updated `bin/setup` accordingly, PR incoming.
