### ISSUE TITLE
Can't create a post

### ISSUE THREAD

**Issue by UWA-Ally** [forem/forem#16351]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by UWA-Ally** [comment]
Hello Support team,

The system always show my account issue which is not allow to access to the system and can't create content.

Thanks so much.

**Comment by citizen428** [comment]
Hello @UWA-Ally, thanks for notifying us of this problem, this looks like an issue specific to your account.
Please email yo@dev.to for more help.
