### ISSUE TITLE
It would be great if forem could embed peertube

### ISSUE THREAD

**Issue by siberkolosis** [forem/forem#16393]
It would be great if forem could embed peertube, even use embed code from peertube is not work, PeertTube is the free and decentralized alternative to video platforms, providing over 400,000 videos published by 60,000 users and viewed over 15 million times

_Originally posted by @siberkolosis in https://github.com/forem/forem/discussions/16240_

**Comment by citizen428** [comment]
Closing this since feature requests are handled through discussions and you created one of those too: https://github.com/forem/forem/discussions/16240
