### ISSUE TITLE
Error posting comment (PG::UniqueViolation)

### ISSUE THREAD

**Issue by Posandu** [forem/forem#16392]
**Describe the bug**

Something went wrong while I was posting a comment on dev.to.
![image](https://user-images.githubusercontent.com/76736580/152092836-c2e69661-cbac-46c1-aa2c-a9f173d4a73e.png)

**To Reproduce**

It just randomly happened but the comment was posted.

**Expected behavior**

No errors

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Firefox latest

**Additional context**

I found some SQL?
```
Your comment could not be posted due to an error: There was an error in your markdown: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_comments_on_body_markdown_user_ancestry_commentable" DETAIL: Key (digest(body_markdown, 'sha512'::text), user_id, ancestry, commentable_id, commentable_type)=(\x0d0d9fba3b725a6f973ef6dea9b270ee69ab02f58fab8b310ff8692f6d8e2ca44a3ffc7fa5763d685122c38d7df69a3768de062c30f87033524e006eaf84e16a, 655383, 841001/841110, 974838, Article) already exists.
```

**Comment by citizen428** [comment]
> It just randomly happened but the comment was posted.

This seems to indicate that the form accidentally got submitted twice. The first request went through and created the comment, the second one then failed the uniqueness validation. I'm inclined to close this issue unless it happens frequently.
