### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16440]
**Describe the bug**

In our Cypress tests I noticed the following exception:

```
Hiding/unhiding comments on an article
  Admin visits the article authored by them 
    "after each" hook: onFailed for "has report-abuse link  when showing hiding comment modal":
    SyntaxError: Unexpected token u in JSON at position 0
```	

I tracked this down to [here](https://github.com/forem/forem/blob/75ae759465180498697773f338932bb2657f494d/app/javascript/utilities/getUserDataAndCsrfToken.js#L16-L24)

```js
const csrfToken = getCsrfToken(document);
    const { user } = document.body.dataset;

    if (user && csrfToken !== undefined) {
      const currentUser = JSON.parse(user);

      resolve({ currentUser, csrfToken });
      return;
    }
```

**To Reproduce**

I'm a bit uncertain, but suspect it's a case where the `data-:attribute`
element is including a non-escaped character&mdash;`"` being the likely
culprit.  This is also something likely breaking in some of our other Forem
instances.

**Expected behavior**

Less flakey tests?

**Comment by nickytonline** [comment]
I'm pretty sure we've discussed this before in the context of the site, but not tests. `Unexpected token u in JSON at position 0` is because the `data-user` attribute has a string value of `"undefined"`, not `undefined`. And this is related to the backend not hydrating the user data for some unknown reason at the moment.

**Comment by jeremyf** [comment]
What do you mean "not hydrating" the user data?

**Comment by nickytonline** [comment]
> What do you mean "not hydrating" the user data?

Got too fancy there. The backend is not rendering the data attribute correctly in some scenarios. Sometimes the backed renders the word undefined instead of JSON.
