### ISSUE TITLE
Invalid Github Liquid Tag for repositories with . character

### ISSUE THREAD

**Issue by Markkop** [forem/forem#16465]
After https://github.com/forem/forem/pull/16422, embbeding github liquid tags with repositories that contain the dot character "." throws `base: Invalid GitHub issue, pull request or comment link` error

**To Reproduce**

1. Start a new blog post
2. Use one of the following github liquid tags:
`{% github https://github.com/discordjs/discord.js/issues/6798 %}`
`{% github https://github.com/ethers-io/ethers.js/issues/2658 %}`
3. Click on `Preview`
4. See `base: Invalid GitHub issue, pull request or comment link` error message on the top of the page

**Expected behavior**

It should embed the Github issue, PR or comment link correctly as it was working the day before the pull request merge.

**Screenshots**

![image](https://user-images.githubusercontent.com/16388408/153007289-8cb217df-32d8-46f7-8b75-b946dd66a08f.png)

**Desktop (please complete the following information):**

- OS, version: MacOS Big Sur 11.6 
- Browser, version: Firefox 96.0.3 

**Additional context**

It was working the day before this pull request merge: https://github.com/forem/forem/pull/16422

**Comment by Markkop** [comment]
@msarit You might want to take a look on this. Nice PR you did previously, by the way!

**Comment by jeremyf** [comment]
Closed via #16551
