### ISSUE TITLE
Ensure "My posts" section is hidden for non-admin

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16486]
Hide the "My posts" section if the user does not have the right to create an article.

**Comment by Jenietoc** [comment]
Hi @jeremyf I am new and would like to collaborate on this issue could you assign me? also can you send me a video of exactly which option is the one you want to hide. thank you very much.

**Comment by jeremyf** [comment]
@Jenietoc I just now saw your message.  At this point, I'm holding "authorization" issues rather close.  I'm looking to factor towards some consistent interfaces, and need to understand the implementation details.

**Comment by jeremyf** [comment]
Based on conversations, I believe we can close this issue for Use Case 1-1.
