### ISSUE TITLE
Co-authors will have to be admins (handlings around it)

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16489]
This requires product to answer:

- Should an administrator be able to assign co-authors to an article?
- Should a co-author have rights to edit the article?  If yes, how does this interplay with showing a user's dashboard?

At present, it appears that administrators are the ones who can assign co-authors.

**Comment by jeremyf** [comment]
As I look at the Authorization System, I wanted to consider this odd edge case that we have.  There’s a field for assigning co authors.  It appears that this “feature” is something only admins can apply.  Also, it’s not frequently done.  So we need an answer regarding this rarely used feature:

In DEV this is rarely used:

```sql
select published_at from articles where co_author_ids != '{}' order by published_at desc limit 10 ;
```

```sh
2021-12-14 20:38:48 UTC
2021-06-02 11:21:53 UTC
2020-09-10 18:05:05 UTC
2020-09-02 10:08:56 UTC
2020-09-01 16:41:08 UTC
2020-08-04 16:27:45 UTC
2020-07-30 23:52:23 UTC
2020-05-14 15:34:21 UTC
2020-02-06 18:34:32 UTC
2019-11-07 13:19:15 UTC
```

**Comment by jeremyf** [comment]
```sql
select count(id) from articles where co_author_ids != '{}'
```

61

**Comment by amywtlin** [comment]
Based on our understanding of co-authors:
1. As co-authors are just metadata of a post, I don't think we need to handle this explicitly. Namely, I don't think we have to prevent admins to assign a non-admin as a co-author, as co-authors won't be able to change anything to the post anyway. Worst case scenario, it's probably slightly confusing to have a general user shown as a co-author, but nothing more harmful than that can be done. 
2. From the perspective of the use case of an announcement-only Forem, I don't imagine it to be very useful for admins to assign a co-author either. This feature is more useful in a guest-posting scenario, if there are collaboration between multiple authors. Still, as we don't really have any functionalities on collaboration yet, I am not too concerned about it.
3. I don't plan on getting into collaboration just yet, so, no. No editing for co-authors in 1-1.

I would say preventing non-admins to be assigned as co-authors is a nice-to-have, certainly not a must-have.

cc @JennieOcken @anujbhavsar96 my take on co-authoring in an announcement-only Forem.

**Comment by anujbhavsar96** [comment]
> I would say preventing non-admins to be assigned as co-authors is a nice-to-have, certainly not a must-have.

Totally agree with this. And I just tried that, being a co-author doesn't change anything in the dashboard _(you don't own the post, so no statistics)_. So this won't harm anything for our announcement-only use case.

**Comment by jeremyf** [comment]
For this we can close the issue, as we're not modifying any behavior around co-author.
