### ISSUE TITLE
Ensure article v0 API create end point is behind authz

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16488]

**Comment by jeremyf** [comment]
Reading notes:

In a local branch, I naively put `authorize(Article)` into the `Api::V0::ArticlesController#create` and `Api::V0::ArticlesController#update` action.  The results were lots of request failures.

The culprit is that we never set the expected `current_user` for the Pundit authorize call.  Even though we know the user based on their api-token, we never set the application's assumed `current_user`, which happens is `nil` and as per [ApplicationPolicy#initialize](https://github.com/forem/forem/blob/a313d8ad386d85dd8bfbeb32c16e1e1664def052/app/policies/application_policy.rb#L62-L67) raises a `ApplicationPolicy::UserRequiredError` which bubbles up as a `:not_authorized` error.

My plan is to wire in setting the current user.  We need to ensure that our ApplicationPolicy is our source of truth regarding authorization.

**Comment by citizen428** [comment]
I think issues like this were the "subtle bugs" mentioned in https://github.com/forem/forem/issues/6255. Looking at `Api::V0::ApiController#authenticated_user` (which is used in `authenticate` and `authenticate_with_api_key_or_current_user`), I wonder if we still even need this behavior:

```ruby
      def authenticated_user
        if request.headers["api-key"]
          authenticate_with_api_key
        elsif current_user
          current_user
        end
      end
```

I think we had the `current_user` check for internal use cases (as exposed to external consumers of our API), but as discussed yesterday, at one point we decided to keep the two APIs separate. 

So maybe what you're trying to achieve here shouldn't actually go through an API controller at all.
