### ISSUE TITLE
To decide: when are we sending the auth-z once a user signs in?

### ISSUE THREAD

**Issue by dscottS3** [forem/forem#16494]
once roles and permissions are built out a bit more we need to either send the claims as part of authentication for identity resolution or have a specific followup endpoint to retrieve the logged in user's roles/permissions.

there are pros and cons to each:

the pros for sending them back as part of auth via JWT (or something similar) is the client side will already have access to them via the session. outlined some high level pros and cons below

|          | pros                                                             | cons                                                                                                            |
|----------|------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| JWT      | * claims stored in JWT <br>* JWT is a fairly standard implementation | * could take a while for changes to take affect after revoking a permission <br>* can become bulky depending on ACL |
| endpoint | * more flexibility for scale <br>* easier implementation             | * storing/caching roles client side <br>* lots of requests depending on implementation and ACL                      |
|          |                                                                  |                                                                                                                 |

**Comment by jeremyf** [comment]
This is a useful analysis for future use cases, for the present project scope I believe that we will not need this work.  I'm closing this but am open for further conversation.
