### ISSUE TITLE
Admin side related API endpoints

### ISSUE THREAD

**Issue by dscottS3** [forem/forem#16495]
some things to think through but doesn't necessarily affect the data model would be:
- can permissions be added directly to a user?
- if so what takes precedence? a user's permission or role?
- how do we handle self-inflicted permission issues where an admin creates a user group and puts themselves in it and can no longer post for example. this would assume some permissions are more elevated than others.

need endpoints to support role based access control (RBAC):

**users**

- add role
- remove role

**roles (user groups)**

- add permission to role
- remove permission from role

**content groups**
- add permission to content group
- remove permission to content group
- add role to content group

**Comment by jeremyf** [comment]
At present this is more than we need to deliver the feature.  With forem/forem#16897 we have the UI necessary for this feature.  Going forward, we'll want to reference this for Use Case 1-2
