### ISSUE TITLE
Ensure that the Admin Member Detail View is Accessible 

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#16504]
**📖  As an Admin, I want my experience to be as accessible as possible, so that I feel motivated to use the Admin Member Detail View.** 

_(Format:  As a [persona], I [want to], [so that])_

🐣 TASKS

- [ ] Address accessibility concerns in the Admin Member Detail View

**Comment by aitchiss** [comment]
All issues addressed - tested with keyboard-only navigation, zoomed text, and VoiceOver on Safari 🚀
