### ISSUE TITLE
Add a Full Test Suite for the Admin Member Detail View 

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#16503]
With the work that has been done to improve the Admin Member Detail View, it is crucial that we have tests in place to fully test the feature.

🐣 TASKS

- [x] Add a full E2E test suite to test the Admin Member Detail View

**Comment by nickytonline** [comment]
I have a branch with a good chunk of E2E tests. I'll Create a PR and tag this issue.

**Comment by juliannatetreault** [comment]
Closed via PR #16513
