### ISSUE TITLE
Add Internationalization to the Admin Member Detail View (/admin/member_manager/users/<:id>)

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#16506]
The updated `/admin/member_manager/users/<:id>` needs to be updated to use i18n. We can introduce locale files for this admin section and add the necessary translations for all the tabs and modals on this page.

**Comment by saksham-jain** [comment]
Is this issue taken up? If not, can I take this and fix?

**Comment by wotta** [comment]
Hi @juliannatetreault,

Could you provide a bit more insight on this issue?
Is this still an issue that can be picked up?
