### ISSUE TITLE
Issue with suspended users' comment and reaction policy

### ISSUE THREAD

**Issue by InHuOfficial** [forem/forem#16537]
**Describe the bug**
If a user is banned from posting articles it means that:
- they cannot post (correct)
- cannot edit articles (correct)
- cannot add reactions (seems incorrect)
- can edit an old comment (seems incorrect)
- cannot follow people (seems incorrect)

**To Reproduce**

1. Apply a ban to a user. 
2. Try and edit a comment for that user, it will save correctly, allowing a banned user to deface old comments.
3. Try and leave a heart or unicorn reaction - it will result in a server error (including bookmarks, so a user cannot even bookmark an article), meaning a user cannot even support authors this way and keep articles for later reference.
5.  Try and follow someone - it will result in a server error

**Expected behavior**

I do not know the full intentions of how far a ban should affect the system, but at the very least I would expect to be able to heart, unicorn and bookmark and not be able to edit an old comment (assuming that not being able to post a comment is the correct behaviour).

**Desktop (please complete the following information):**

Windows, all current versions of Chrome, Firefox etc. (it is not a browser specific bug)

**Smartphone (please complete the following information):**

- Device: Iphone
- OS, version: Latest
- Browser, version: App

**Additional context**
I would imagine that there are two things to address:
- the first is displaying a server error instead of a message similar to the one seen when you try to save a post (informing you of a ban and contact info).
- the second is the consistency, if the intention is to prevent a user from doing further harm to the site, being able to edit comments seems incorrect, not being able to bookmark, heart and unicorn seems incorrect (they should still be able to support other authors).

**Comment by fdocr** [comment]
Thank you @InHuOfficial for bringing this up. Taking a look at these every now and then is a good thing to do IMO.

We heard back from community and product folks on the team and the consensus is that we agree with you that `suspended` users should be able to follow other users and add reactions, and they also shouldn't be allowed to edit existing comments.

Right now these are managed by policies on the code that are failing with `Pundit::NotAuthorizedError` (i.e. [CommentPolicy](https://github.com/forem/forem/blob/main/app/policies/comment_policy.rb#L1-L4)). I'm going to slightly edit the issue title and mark this as ready for dev.
