### ISSUE TITLE
Slight CLS on Gif play-pause button loading

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#16535]
**Describe the bug**

There is a slight jump in the content on gifs now that we have the play/pause functionality load in. This results in "cumulative layout shift" — not great for users or search engines.

https://user-images.githubusercontent.com/3102842/153486695-343fe4c2-9bbe-4969-8df9-dd958230f72c.mov

**To Reproduce**

Visit a page with a gif, observe that content _jumps_ a bit.

I.e. https://dev.to/thepracticaldev/welcome-thread-v163-2n3p

**Expected behavior**

No flashing, no content jump, smooth loading.

**Comment by aitchiss** [comment]
Relates to https://github.com/forem/forem/pull/16314
