### ISSUE TITLE
Confirm your email address during signup seems broken

### ISSUE THREAD

**Issue by leewynne** [forem/forem#16542]
**Describe the bug**

When choosing to create an account using email, the 'confirm your address' doesn't go out stopped successful sign-up. Can't reproduce this on Dev as sign up with email isn't available

**To Reproduce**

Goto flowstate.to or metapunk.to and attempt to sign up with email.

**Expected behavior**

Email appears shortly after signup which can be used for confirmation.

**Additional Context**

I have managed to reproduce on all my forems across multiple devices and browsers.

**Comment by athifbinu** [comment]
yes it is correct add in a signup page and email system

**Comment by Ridhwana** [comment]
Hi @leewynne thank you for bringing this to our attention, I have a couple of questions that will help us debug this:

1. I'm curious to know if **all** emails are not going through, or is this scoped to only confirmation emails?
2. This will probably be answered based on your response to the above, but do you have your SMTP section in /config configured correctly?
3.Was it working at some point and then it stopped working for your Forem?

**Comment by leewynne** [comment]
I shall report back!

**Comment by leewynne** [comment]
Hey @Ridhwana 🤩

No emails are coming through (just tested with a comment on one of my posts).

All my smtp details are configured, these haven't changed for months (is there a way to easily test this?)

Emails stopped working over the past month or so (no changes to smtp)

I tried to replicate this on Dev but the sign up with email option isn't available. At the moment I am experiencing it on all my Forems.

**Comment by athifbinu** [comment]
What is The problem is dint understant

**Comment by jdoss** [comment]
Does sending mail through that SMTP account manually still work with a different client?

**Comment by leewynne** [comment]
Hi again. All working again now since I reconfigured with sendgrid. I'll close this issue now, thanks for all the responses.

**Comment by Ridhwana** [comment]
Thanks Lee, I'm glad that its solved.
