### ISSUE TITLE
Could not post to the welcome forem...error when posting

### ISSUE THREAD

**Issue by Yankeeland** [forem/forem#16605]
**Describe the bug**

HI all, I was trying to post to the welcome forum the following message, but received an error(see screenshot attached) and could not create the post. 
**To Reproduce**

https://community.codenewbie.org/welcome

"Add to discussion"
entered my message
clicked on "submit"

Error posting comment

Your comment could not be posted due to an error: Body markdown has already been taken
screenshot: https://pasteboard.co/kTLFUrv0eLIK.png
**Expected behavior**

My comment would be posed. :)
**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome

**Additional context**

**Comment by djuber** [comment]
Hi @Yankeeland - that error is triggered by a duplicate submission guard (to prevent accidentally sending the same comment twice we don't permit the same content in two comments from the same user on the same article). 

When I look at https://community.codenewbie.org/yankeeland I see 4 comments added to that thread - some look like general introductions and one looks like a reply, is it possible you were editing in some cases and accidentally created new comments in another?

![comment thread](https://user-images.githubusercontent.com/1237369/154166702-20d26123-9338-4b8c-a6e9-c10256e36e08.png)
