### ISSUE TITLE
Blocking @shakuroinc account on the platform DevTo

### ISSUE THREAD

**Issue by Kate38429475** [forem/forem#16609]
Hello,

For 2 years we have been publishing our articles on DevTo's website with the account @shakuroinc.
Most recently, we noticed that our account was blocked; it does not display any of our works anymore, as well as the information about the company. Letters in the mail about the reason for the absence of an account and the removal of our works were not found.
We attach a screenshot below, which shows that our account and works on it are missing.

We would like to continue to work with the DevTo site, and hope to have the account restored soon.
Please help us understand this situation.

Best regards, Shakuro team.

<img width="1286" alt="Снимок экрана 2022-02-16 в 16 56 48" src="https://user-images.githubusercontent.com/58697151/154280704-bd1d9507-9b47-4211-bb7e-3e0a08eb8f4b.png">

**Comment by fdocr** [comment]
Hello @Kate38429475, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
