### ISSUE TITLE
Missing embed keyword results in error

### ISSUE THREAD

**Issue by andypiper** [forem/forem#16639]
**Describe the bug**

I'm trying the new embed content blocks for the first time.

When I forget to add the keyword "embed" ahead of the URL, I'm still able to submit and publish the post, but the post shows up with the message:

```
Liquid syntax error: Tag '{% https://github.com/andypiper/fivebyfive %}' was not properly terminated with regexp: /\%\}/
```

This is fair - I got it wrong, I should have typed `{% embed <url> ... %}` - but the error message is confusing, and the post is broken. It would be nicer to have the post rejected and the error flagged as a missing liquid tag (embed) rather than breaking the post.

**To Reproduce**

1. Create a new post
2. Enter a liquid tag with a URL you expect to generate an embed, but omit the word `embed`
3. Submit the post as published.

**Expected behavior**

An error on posting, not a published but broken post.

**Comment by Jenietoc** [comment]
I will try to solve this issue

**Comment by mirie** [comment]
Resolved via https://github.com/forem/forem/pull/16704
