### ISSUE TITLE
GIF Button of picture in blog has higher z-index than navbar

### ISSUE THREAD

**Issue by youngnishant** [forem/forem#16643]
**Describe the bug**

**To Reproduce**

Go to any blog having gif image
There is a gif label or button on that. 
Try to scroll 
And find it hover above navbar

**Expected behavior**

It should have less zindex

**Screenshots**

![Screenshot_20220218-194400](https://user-images.githubusercontent.com/47674286/154702513-8ca01160-ee65-45de-8b99-0e86b942dbe2.png)
![Screenshot_20220218-194415](https://user-images.githubusercontent.com/47674286/154702527-66115c87-331a-4876-8a28-f046520073ab.png)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by citizen428** [comment]
For anyone trying to reproduce this, here's the link to the post mentioned in the report: https://dev.to/this-is-learning/resumable-javascript-with-qwik-2i29


@youngnishant Could you please provide some details on your browser, OS, and their versions? I could not repro this on Chrome/macOS.

**Comment by youngnishant** [comment]
@citizen428 
Phone: Moto g5 plus
Browser: Chrome, brave browser
Android: 8.1.0

**Comment by youngnishant** [comment]
@citizen428 got the same issue with my ubuntu distro, screen shot attached
tested in brave and chrome

![Screenshot from 2022-02-21 10-10-30](https://user-images.githubusercontent.com/47674286/154890466-8126a1a2-e624-4977-8d8d-99d56ea3af83.png)

![Screenshot from 2022-02-21 10-10-10](https://user-images.githubusercontent.com/47674286/154890461-e21de632-0d6f-446a-9991-3ba1e622c52d.png)

**Comment by citizen428** [comment]
Thanks @youngnishant!

**Comment by youngnishant** [comment]
@citizen428 get some good sleep 😁
