### ISSUE TITLE
Add richer error messaging as to why an embed fails

### ISSUE THREAD

**Issue by msarit** [forem/forem#16687]
Consider checking for valid URL via `Net::HTTP` (or something similar) to determine if the URL being used is in fact a valid URL. This is not to be confused with checking if the URL is a supported/registered service in the registry.

Error messaging can take the form: "URL does not appear to be accurate/valid. Please check again."

**Comment by djuber** [comment]
https://github.com/forem/forem/issues/16639 is this related (tag missing a name results in hard to decipher error message)?

**Comment by amywtlin** [comment]
@msarit Adding you as the assignee so that we have the clarity that this issue is being worked on actively (please let me know if that is not the case, though!)
