### ISSUE TITLE
Add a toggle for "Listings" as an Extension

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#16698]
## Why

As we are [putting Listings behind a feature flag for all Forems except DEV](https://github.com/forem/forem/pull/16437), we need a way for admins to toggle this feature flag if they intend to keep using Listings for their Forems. In this [discussion thread](https://forem-team.slack.com/archives/CAA200SH5/p1645636659240279?thread_ts=1645635120.725449&cid=CAA200SH5), we came to the conclusion that we will take the following approach to enable it described below in "What."

## What

We are adding a section called "Extensions" under Developer tools, with Listings as a toggle that can be turned on.

## Additional context
This is blocking #16423 from being merged.

**Comment by amywtlin** [comment]
Hey @Ridhwana 👋 Assigning this to both you and me for us to work together to move this forward, before we can put an engineer's head here 😀 

On a side note, I put this issue under Small Wins board for now, because I am unsure which of Admin Ex's board to put this. Please feel free to move it around where appropriate!

**Comment by Ridhwana** [comment]
@amywtlin do we want to call this new tab under "developer tools" feature flags or something different?

**Comment by Ridhwana** [comment]
@amywtlin I looked through what this would possible look like and here are some thoughts: 
1. We'd add a new tab called Feature Flags (or we could call it something else if you'd prefer) along with a new route `admin/advanced/feature_flags`. It would look something like this: 
<img width="1680" alt="Screenshot 2022-02-25 at 10 07 41" src="https://user-images.githubusercontent.com/2786819/155687890-d8544464-e7f9-41de-80e2-e0502c6d3a16.png">
2.. We'd show a list of "user facing" feature flags and display them in a list with a checkbox on whether the user wants the feature flag to be displayed on not
3. We'd want to add a description of what will happen if you enable the feature flag. 
4. And finally maybe an "Are you sure you want to enable these feature flags" when the user clicks the save button (although this is optional)

What do you think?

We can wing this design or if you'd prefer we can have a designer work on it beforehand? I'll take guidance from you. 


Regarding [the slack message](https://forem-team.slack.com/archives/C01S4QZUDNC/p1645759903210749) :

> can you let me know when we will get to this (or when we would have clarity on this information) so I can plan the decommission communication beforehand with admins? Thanks!

This is not a huge task, however myself and Nick are away next week, and Julianna is focussed on wrapping up the admin member view. I can tackle it on the week of the 07 March when I'm back online or if someone in an the CE pod or another pod has capacity to work on this, we can drop it their way :) You can let me know :)

A side note is that any javascript introduced with this feature (if any) should be added to a packs file and not through stimulus as we are trying to move away from using Stimulus.

**Comment by amywtlin** [comment]
Hey @Ridhwana, thanks for the quick turn around! 

What you have outlined sounds good to me. Re: naming, I am actually thinking, we could call it "Extensions" or "Add-ons" as we do expect to move more things behind the feature flag that can be turned if wanted, as the first step of moving these types of plug-ins to a marketplace. 

Maybe we can leave this one on the Small Wins board (so CE team members can grab it if they can), otherwise for you to tackle or help assign someone to tackle when you are back? What do you think?

**Comment by Ridhwana** [comment]
> Maybe we can leave this one on the Small Wins board (so CE team members can grab it if they can), otherwise for you to tackle or help assign someone to tackle when you are back? What do you think?

Happy for the CE team to grab it or I can when I'm back, whichever happens first 😊

**Comment by amywtlin** [comment]
@Ridhwana Thanks! I also just updated the issue for clarity based on our discussion. Also I don't think we need a designer for this. Making sure it looks consistent with other components on the page is good enough.

**Comment by Ridhwana** [comment]
@amywtlin I've just started working on this, can you please provide me with a description of what the listing feature flag will do if a user enables it?  This is for the copy on the page when the user enables the feature flag.  I'm not super familiar with the feature else I'd have taken a first stab at it.

**Comment by Ridhwana** [comment]
This is a preview of what the page will look like: 

<img width="1680" alt="Screenshot 2022-03-09 at 15 52 27" src="https://user-images.githubusercontent.com/2786819/157455167-8e25e034-3a66-4889-b0f1-de0c1d1660d2.png">

We'll only have listing on there at the moment.

**Comment by amywtlin** [comment]
@Ridhwana Sure! Here's the description:

> Once turned on, Listings can be accessed via {community url}/listings and members will be able to add listings. Learn more about Listings [here](https://admin.forem.com/docs/advanced-customization/listings).

**Comment by JennieOcken** [comment]
Hi friends.  I am only intervening with this plea

Let's call this "extensions" instead of "feature flags".  The term "feature flags" has technical meaning and weight here at Forem that I don't want to imply in what we are trying to do.  While we might use a feature flag in our implementation of how we are setting up these extensions in code, what should be user facing is "extensions" in order to allow us to reserve the term "feature flags" to our internal discussions.  Fair?

(Amy, let's also change that language in our /admin IA conversations please)

**Comment by amywtlin** [comment]
@JennieOcken that's definitely where we are heading, as mentioned [here](https://github.com/forem/forem/issues/16698#issuecomment-1050692737): 
>Re: naming, I am actually thinking, we could call it "Extensions" or "Add-ons" as we do expect to move more things behind the feature flag that can be turned on if wanted, as the first step of moving these types of plug-ins to a marketplace.

@Ridhwana Let's make sure we use "Extensions" for the tab label - thanks!

**Comment by Ridhwana** [comment]
Sounds good to me 👍

**Comment by amywtlin** [comment]
Hmm - `/settings/extensions` seems user-facing, and looking at the functionalities there, it looks like advanced functions some power users might make use of. Are you saying that Creators might also want to control if they offer these functions, through `/admin/advanced/extensions`?

**Comment by Ridhwana** [comment]
No I'm just saying that it could potentially confuse admins that the two routes are named the same but are not related, but if we think thats not the case then its okay :)

**Comment by amywtlin** [comment]
Ah. I think if that's the case, it should be alright then!

**Comment by Ridhwana** [comment]
@amywtlin can I deploy this or do I have to wait for anything else before merging and deploying it?

**Comment by amywtlin** [comment]
You can deploy this! After this is deployed, I will write a post on forem.dev to instruct Creators to turn on the toggle if they want to keep Listings, and then I can schedule a time with @jeremyf to deploy this: #16423 

Thanks!

**Comment by Ridhwana** [comment]
Merged and deployed to dev.to. It will make its way to other Forems on Monday with the next scheduled deploy.
