### ISSUE TITLE
Inconsistent published date on Posts

### ISSUE THREAD

**Issue by divyamojas** [forem/forem#16744]
**Describe the bug**

The comments post-time is before the actual article post time.

**To Reproduce**
- Go to https://dev.to/aniket762/getting-into-software-testing-with-jest-2ca0

-  Check the article post time just below Aniket's name.
-  Check the time when the comments are posted.

**Expected behavior**
The comments post time for some comments is 1 March while the article is posted on 2 March.

**Screenshots**
Article post time:
![Screenshot_2022-03-02-02-03-25-19_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/55374764/156245975-c22b4745-6349-4a95-8519-7f631ec90751.jpg)

Comment post time:
![Screenshot_2022-03-02-02-03-38-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/55374764/156246005-18e8f882-53d8-4a59-8b67-d3bc1f7ea6c5.jpg)

**Desktop (please complete the following information):**

- OS, version: NA
- Browser, version: NA

**Smartphone (please complete the following information):**

- Device: Realme 5 Pro
- OS, version: Android 11
- Browser, version: Chrome 98.0.4758.101

**Comment by fdocr** [comment]
There's a good chance UTC time was used when publishing the post to generate these dates. Just my initial hunch on the origin of this.

This seems like it has come up before from time to time but I didn't find these conversations on a first search through the repo. There's a chance this is happening for a reason (technical difficulty) but I don't have enough context on this area at the moment.

In any case, if possible, there may be a way to use the local time of the request being made so it's consistent throughout the app.

It will be useful to do some more research on this to identify why this is happening. It was reported elsewhere that social previews are using this incorrect date as well, just sharing it in case that helps the debugging.

**Comment by thejwuscript** [comment]
I'd like to work on this issue.

**Comment by fdocr** [comment]
Hi @thejwuscript, thanks for volunteering to work on this. I assigned the issue to you.

I remember taking a look at this a few months ago but I didn't land on an exact root cause. If you need any help or direction feel free to ping me here or on a PR.
