### ISSUE TITLE
Gif pause button disappears after pausing

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#16759]
**To Reproduce**

- visit a post with a gif
- click the pause button
- notice it disappears
- click the image
- notice the gif resumes and the button re-appears

**Expected behavior**

The play/pause button should remain visible

**Additional context**

I suspect this was introduced in https://github.com/forem/forem/pull/16649, and that we have an issue with the z-index of the freezeframe library's static image (`canvas` element) versus what we changed it to in that PR. If that's the case, it might be best resolved by overriding the freezeframe library's z-index CSS 🤷‍♀️

**Comment by aitchiss** [comment]
Great! I've assigned to you - let me know if you need any assistance!

**Comment by Jenietoc** [comment]
> Great! I've assigned to you - let me know if you need any assistance!

@aitchiss , you think is fine?

https://user-images.githubusercontent.com/89233604/157475970-1e52c247-d704-4e3b-a009-f66338e58971.mp4

**Comment by Jenietoc** [comment]
> It looks good @Jenietoc! I'd just test with a long post too, and check that if you scroll the gif beyond the page header, that the gif button goes _under_ the header. This is the problem that prompted the last change 😄

it works good

https://user-images.githubusercontent.com/89233604/157485528-73d7e4de-62b5-4b8e-8d3e-d4b8f0b0ef11.mp4

**Comment by nickytonline** [comment]
Seems to look good @Jenietoc! Go ahead and create a PR. 😎

**Comment by miguelnietoa** [comment]
This PR should be closed since PR #16846 is already merged 😃

**Comment by aitchiss** [comment]
Closed in https://github.com/forem/forem/pull/16846

Thanks @miguelnietoa for spotting this needed closed, and thanks @Jenietoc for the fix!
