### ISSUE TITLE
To check: Pawel's documents on UI related tasks

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#16750]
This is for us to cross-check if we have covered all the UI related tasks: 
https://docs.google.com/document/d/1-uXi7066MUFfw5Bwl1H4pIJZwC8NF77ZcHpDfjtaiVE/edit#

**Comment by jeremyf** [comment]
I have reviewed the document and updated each point with issues.  From this point forward I'm considering that document "frozen"
