### ISSUE TITLE
Always hide "Save" button on a user's own posts when it's shown on a list

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#16767]
# Why
It doesn't make sense for a user to save their own posts.

# What
We hide "Save" button on the post entries throughout the site if the post is authored by the viewing user.

**Comment by aitchiss** [comment]
Do we want to do this in all places where a user sees their own posts (e.g. home feed and tag page too)?

**Comment by amywtlin** [comment]
That actually would be even better. I would love to know if that is also the part of conditionally rendering that we are struggling with a bit, so I can see if we should handle this even more holistically.

**Comment by amywtlin** [comment]
Thanks for the clarification. Yes, I would rather have all `save` buttons disappeared everywhere if the posts are written by the user. Let me update the issue instead!

**Comment by msarit** [comment]
@amywtlin Do we want this work to extend to the flag-looking icon that appears under the "heart" and "unicorn" icons on the individual post page?

**Comment by amywtlin** [comment]
Yea, that would be nice. I'd say it is a good-to-have, as it is not as obvious as the `save` button on the list view. However, for consistent behavior, it'd be better to also hide it with another PR.
