### ISSUE TITLE
Posts with various "blank" characters break headers

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16772]
**Describe the bug**

The following post: https://dev.to/inhuofficial/i-am-warning-you-dont-click-42im breaks some places in the UI.

The title includes many "Braille Pattern Blank" characters (see [Unicode Character 0x2800 - "⠀" from Unicode Map](https://unicodemap.org/details/0x2800/index.html)).  Note, there are plenty of other "blank" characters, so we need not consider just this one character.

The places that I've found thus far are:

- /:username/comment/:comment-id (showing a single comment's response to the post), (Reading notes: I think this is handled by the `comments#index` action)

Based on [PR #16771](https://github.com/forem/forem/pull/16771), I believe we may need a more general audit and response to these kinds of user inputs.  I did apply Suzanne's fix (via Inspector) to the heading tag of the above mentioned page, and that appeared to resolve the issue.

This particular problem appears isolated to Safari 15 on MacOS.

**Comment by aitchiss** [comment]
> This particular problem appears isolated to Safari 15 on MacOS.

This makes me suspect it's another case of `overflow-wrap: anywhere` not being applied as it's not supported in Safari. I'll do a search in the codebase for any similar instances as a starting point 🙂
