### ISSUE TITLE
Add Embed icon to Editor toolbar

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#16780]
# Background
Now that the generic embeds is in place, I think we are ready to add the icon to the toolbar.

# Definition of Done
Implement the embed icon to the editor toolbar and also the associated keyboard shortcut to it. 

# Specs
The icon:

```
<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M13 9h8L11 24v-9H4l9-15v9Zm-2 2V7.22L7.532 13H13v4.394L17.263 11H11Z" /></svg>
```

Save it as `lightning.svg` in `app/assets/images`. More instructions on icons usage and exporting [here](https://storybook.forem.com/?path=/docs/components-icons--default).

Let's add it between "Code block" and "Upload image" buttons. 

## Behaviours

**1. If the user currently has no text selected, clicking it should insert following snippet:**

```
{% embed https://... %}
```

with `https://...` part being highlighted so user can paste a URL from clipboard right away. 

**2. If the user already has text selected, clicking should insert the following snippet:**

```
{% embed text-the-user-has-selected %}
```

with `text-the-user-has-selected` still selected

**3. If the user has a whole embed syntax selected, e.g.**

```
{% embed some-url-text %}
```

Clicking the button should remove all of the embed syntax, and leave only the link text e.g.

```
some-url-text
```

The remaining text should be selected

**4. If the user has the link inside an embed syntax selected, e.g. the they have `some-url-text` selected, inside the following syntax:**

```
{% embed some-url-text %}
```

Clicking the button should remove the embed syntax, leaving only the `some-url-text` which should continue to stay selected

---

Keyboard shortcut: `CMD/CTRL+Shift+K`

**Comment by amywtlin** [comment]
@aitchiss @ludwiczakpawel I don't think I have seen one in other applications, but is there a keyboard shortcut for "embeds" that are commonly used that you are aware of though?

**Comment by aitchiss** [comment]
The only one I'm aware of is Medium, who use a code symbol (not gonna work for us 😄 ):

![medium embed icon](https://user-images.githubusercontent.com/20773163/156736424-4c2fb358-0810-4f2a-9559-cb5c1a30209c.png)

**Comment by ludwiczakpawel** [comment]
> but is there a keyboard shortcut for "embeds" that are commonly used that you are aware of though?

Nothing pops in my mind...

**Comment by aitchiss** [comment]
Was there not some discussion a while ago of calling them "magic embeds" or something, and using like a sparkly icon like ✨

I might be just making this up though I don't remember 🤣

**Comment by ludwiczakpawel** [comment]
Follow up: I still haven't seen too many apps offering this "add embed" functionality especially as a keyboard shortcut. BUT! Figma lets you include components (which I guess we could consider our "embeds" in a way) by hitting `Shift+I`...

I've just figured it's pointless note as `Shift+I` makes capital `i` in text editors... :D

**Comment by aitchiss** [comment]
> I've just figured it's pointless note as `Shift+I` makes capital `i` in text editors

We could consider e.g. `cmd + shift + i` but I guess if it doesn't match existing shortcuts elsewhere we could just make one up ourselves 😄 Maybe `cmd/ctrl + e` for embed?

**Comment by amywtlin** [comment]
If it is uncommon then we probably don't have to add it. I was trying to make sure there's a prevalent keyboard shortcut for embeds that I am not aware of. 😂  What do you think?

**Comment by aitchiss** [comment]
From a selfish POV I would love a keyboard shortcut for the embeds 😄 , but yeah it seems like it's more of an 'added bonus' than something users would necessarily expect.

Thinking about it... an embed is like a super-charged link, right? And link shortcut is `cmd + k`... so maybe we could have `cmd + shift + k` (if we wanna add a shortcut at all)

**Comment by msarit** [comment]
Hello all! Is this issue scoped and ready to go? I see it has been prioritized on ContentEx board. Do we have an icon design, or is the dev working on this to come up with that? Also, what’s our decision on the shortcut? Thanks! 🙏🏾

**Comment by ludwiczakpawel** [comment]
I like @aitchiss suggestion for Cmd+Shift+K - I think it makes sense. adding new keyboard shortcuts is, AFAIK, fairly easy right now so if it doesnt cost us much we could go with this one :) 

@msarit seems like this needs ~one more day of going back-and-forth before being ready to pick up.

**Comment by amywtlin** [comment]
I replied yesterday via email on my phone but it looks it didn't come through: 

> I love the idea of a super-charged link!! It makes much more sense to me than cmd + e, plus it is for code on GitHub editor…
> I am sold. Let’s do this.

@ludwiczakpawel I do think we have the button icon ready in some figma file though, no? I remember seeing it, or was it not finalized?

**Comment by ludwiczakpawel** [comment]
@amywtlin yes, we do - it just hasn't been added to the codebase. Here's SVG (adding it also in this issue description) for whoever gonna pick it up:

```
<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M13 9h8L11 24v-9H4l9-15v9Zm-2 2V7.22L7.532 13H13v4.394L17.263 11H11Z" /></svg>
```

Save it as `lightning.svg` in `app/assets/images`. More instructions on icons usage and exporting [here](https://storybook.forem.com/?path=/docs/components-icons--default).

**Comment by aitchiss** [comment]
I've updated the comment with fuller behaviours for what happens when you click the button, so that the functionality mirrors the other formatter buttons

**Comment by amywtlin** [comment]
@jeremyf I noticed that @rt4914 submitted a PR and he left a comment in a PR. Can you help take a look and see if that's something you can help with?

@rt4914 Assigning this issue to you and move this issue to in progress so others will not pick this one up :-)

**Comment by rt4914** [comment]
@amywtlin Thanks.

**Comment by amywtlin** [comment]
I love the idea of a super-charged link!! It makes much more sense to me
than cmd + e, plus it is for code on GitHub editor…

I am sold. Let’s do this.
