### ISSUE TITLE
Conditionally render "My Posts Only" section of search results

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16837]
See

https://github.com/forem/forem/blob/ffc65bed81d66a2a18d2b5d00ba2d3157a78486e/app/views/stories/articles_search/_nav_menu.html.erb#L17-L19

Note: the response for doing this will depend on our decision around https://github.com/forem/forem/issues/16821

Namely, we want to account for the scenario in which a person has published articles but is (at present) not allowed to create articles.  We likely want to render that section.

I have verified that the above is rendered server side without aggressive caching.  So once we decide on our approach, we'd need:

- [x] Write the query that we check for conditions (we should frame this as a policy question)
- [x] Adjust the above code to render based on query results

**Comment by amywtlin** [comment]
For my posts only, I am thinking the same way as "Posts" - using the same logic whether a user has any posts to decide if we are going to show this tab at all. What do you think?

**Comment by jeremyf** [comment]
Per discussions, we are proceeding with this feature.
