### ISSUE TITLE
To confirm: do we need to handle Campaign button, calling for post submission?

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#16907]
<img width="378" alt="Screen Shot 2022-03-18 at 11 58 41 AM" src="https://user-images.githubusercontent.com/11730007/158934969-a63f5dd9-d819-4e7c-a600-c78a00dcf4e4.png">

**Comment by amywtlin** [comment]
Did some preliminary investigation and need to confirm with folks on how it works: https://forem-team.slack.com/archives/CAA200SH5/p1647845349332059

cc @jeremyf

**Comment by jeremyf** [comment]
@amywtlin any updates?  I need from you to say "Leave it as it is" or "There's work to do"

**Comment by amywtlin** [comment]
Thanks for poking back. I think we need to hide the running campaign from the sidebar, which is to turn the value of `Sidebar enabled` in Campaign to false under `admin/customization/config`. 

I however think this needs to be a prompt or something after someone attempts to turn on comment-only. @anujbhavsar96 What do you think in terms of the interaction here?

**Comment by anujbhavsar96** [comment]
> I however think this needs to be a prompt or something after someone attempts to turn on comment-only.

Totally agree with this. So here is what I think, we should disable that check box `Sidebar enabled` if comment-only is turned on. We educate them about this change in the Uncategorized post section, same as we are communicating about Organization. I change the text formatting a bit. We also communicate the same in our confirmation modal.

Does it make sense?
![Hide bottom card](https://user-images.githubusercontent.com/84626054/160379174-6348e1a4-1eea-44f9-b2ec-3575643d392c.png)

**Comment by amywtlin** [comment]
As we have confirmed that we will handle this, we'll continue the discussion on approaches in #17032 and close this one.
