### ISSUE TITLE
Post/comment embed not working on DEV

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#16917]
**Describe the bug**

Currently the "embed" syntax is not working on DEV.

**To Reproduce**

- Go to a DEV post and copy the URL
- Go to `/new` and copy it in as `{% embed [url] %}`
- Click preview.
**Expected behavior**

Post or comment link embeds

**Screenshots**

<img width="843" alt="Screen Shot 2022-03-18 at 12 15 35 PM" src="https://user-images.githubusercontent.com/3102842/159041425-d5792745-30e9-4540-a31e-acf421ab3ba1.png">

**Additional context**

We had this problem on _other_ Forems, but it seems like it broke for DEV now in fixing elsewhere?

**Comment by djuber** [comment]
reproduced on DEV using a randomly selected article, confirmed this works on forem.dev

> We had this problem on other Forems, but it seems like it broke for DEV now in fixing elsewhere?

I suspect the change to [URL.domain](https://github.com/forem/forem/blob/main/app/lib/url.rb#L6-L19) might be related? The easiest confirmation would be to check (in a production console) the output of both URL.domain and ForemTag.REGISTRY_REGEXP, both should indicate dev.to as the domain.

Using `{% post [url] %}` works as before, only the unified embed tag (apparently failing to find the ForemTag when given a dev.to url) is failing.

**Comment by msarit** [comment]
@djuber Thanks for this Dan. I did have an Instagram-related PR merge this morning that could also be the culprit, I'm reverting it now to see.
https://github.com/forem/forem/pull/16904
