### ISSUE TITLE
Series counts are not showing on all dashboard pages

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16914]
```gherkin
Given I'm logged in
When on `/dashboard/user_followers`
Then there is no series counter
```

```gherkin
Given I'm logged in
When on `/dashboard/`
Then there is series counter (it is 0)
```

The attached screenshots demonstrate the above examples

## Expectation

I would expect that we would consistently render the counter (if 0).  Note, I haven't started any series, so it's possible that a 0 count is the bug.

**Comment by amywtlin** [comment]
Agree with the expectation that the counter should always be shown, on all pages under `/dashboard`, even if the count is zero.

**Comment by jeremyf** [comment]
The following view renders the count:

https://github.com/forem/forem/blob/25404a9f34ffb9976859423bb1701d124715aa00/app/views/dashboards/_actions.html.erb#L12-L19

The problem is that only the `dashboards#show` action provides the `@collections_count` (in other cases we have a `nil` object which we coerce to a string.

https://github.com/forem/forem/blob/25404a9f34ffb9976859423bb1701d124715aa00/app/controllers/dashboards_controller.rb#L28

**Comment by msarit** [comment]
@amywtlin This issue good to go?
