### ISSUE TITLE
Add/Update the Columns and Values for the Members Index View

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#16911]
**📖  As an Admin, I want to only see the most important columns on my initial member index view, so that I can get a useful overview of data** 

_(Format:  As a [persona], I [want to], [so that])_

<img width="943" alt="Screenshot 2022-03-18 at 16 54 20" src="https://user-images.githubusercontent.com/2786819/159026379-dba605ae-b730-474c-bcc0-98e8df1b3b48.png">

🐣 TASKS

**[Tentative] PR 1: Bare-Bones Columns:** (Worked on by @juliannatetreault )
- [x] Add a "Member" column
- [x] Add a "Status" column
- [x] Add a "Last activity & joined" column
- [x] Add an "Organizations" column

**[Tentative] PR 2: Fleshed-Out Columns:** (Worked on by @juliannatetreault )
- [x] Add member's full name to the "Member" column
- [x] Add member's username to the "Member" column
- [x] Add member's profile picture to the "Member" column
- [x] Add a member's roles (Super Admin, Admin, Resource Admin, Moderator) to the "Member" column
- [x] Add a member's status (no need to add the icon at this point) to the "Status" column
- [x] Add a member's "last activity" date to the "Last activity & Joined on" column 
- [x] Add a member's "joined on" date to the "Last activity & Joined on" column 
- [x] Add a member's organizations (without pictures) to the "Organizations" column
- [x] Add tests to ensure that the columns appear as expected and provide the expected data 

**[Tentative] PR 3: Bare-Bones Organizations:** (Worked on by @juliannatetreault )
- [x] Add organization profile pics to the "Organizations" column

**[Tentative] PR 4: Kebab Menu:** (worked on by @aitchiss)
- [x] Add a kebab menu as the last column in the Member Index View table 
- [x] Add a menu item to the kebab that gives Admins the ability to copy a member's email address
- [x] Add tests to ensure that copying a member's email address works as expected 

**[Tentative] PR 5: Status Icons:** (Worked on by @juliannatetreault )
- [x] Add a colorful, circular status icon next to the left of the member's status that maps to the member's status (ex: "Good standing" is represented with a grey circular icon)
- [ ] Add tests to ensure that the colorful status indicators work as expected

**[Tentative] PR 6:  Organizations Build-Out:** (Worked on by @juliannatetreault )
- [x] Show the first 3 organizations with their image 
- [x] Do a calculation on the remaining organizations and display it as +x
- [x] Show a “-” in the table when there is no organization
- [x] When we hover over an organization it should show the organization names as per the design
- [x] Add tests to ensure that the organization build-out (calculations and expansion) works as expected

**[Tentative] PR 7: Tooltip Refactor:** (Worked on by @juliannatetreault )
- [x] Alter role tooltips so that they not only show "Resource Admin," but so that they also show the resource associated with the role, e.g. "Resource Admin: Resource" (Refer to [this](https://github.com/forem/forem/pull/17033#discussion_r840377603) comment for more info)

**[Tentative] PR 8: Partials Refactor:** (Worked on by @aitchiss)
- [x] Pull repetitive code (user status, for example) into a partial and render that for the desktop and mobile views within the Member Index View (Refer to [this](https://github.com/forem/forem/pull/17033#discussion_r840380740) comment for more info)

**[Tentative] PR 9: Query Refactor:** (Worked on by @juliannatetreault )
- [x] Move user/organization eager loading queries within `_member_index_view.rb` to the `Admin::UsersController` (see [this](https://github.com/forem/forem/pull/17033#discussion_r843735326) comment and [this](https://github.com/forem/forem/pull/17033#discussion_r843738982) comment for more details)

**[Tentative] PR 10: Empty role bugfix:** (Worked on by @juliannatetreault )
- [x] Fix an [issue where a user with no special roles shows with an empty grey dot next to their username](https://github.com/forem/forem/pull/17033#discussion_r844962241)
**To do: remove the role badges completely from the UI from now**

**Comment by juliannatetreault** [comment]
_**Note:**_ issue #16935 should follow this issue, issue #16911, once all tasks are completed.
