### ISSUE TITLE
Conditionally redirect from /dashboard to /dashboard/following_tags

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#16913]
```gherkin
Givena user does not have permission to create posts nor has any existing posts
When they visit `/dashboard`
Then then we redirect them to `/dashboard/following_tags`
```

By default the Dashboard shows post related information, and given that they have none, nor can create any, we shouldn't show them the `/dashboard` page as currently envisioned.  Were we to hide the various elements regarding their posts, we'd have a left navigation and nothing else.

I'm open for different approaches (e.g. repurposing the `/dashboard` page to not assume posts)

Dependent on #16908
Inter-related with #16913

**Comment by amywtlin** [comment]
We have plans to [revisit `/dashboard`](https://github.com/forem/forem/issues/16931) within Product team, and I agree making the default page for `/dashboard` more generic so it can make sense to members of different permissions make sense. This is something we will take into consideration when we get there, but for now, let's stick to redirecting `/dashboard` to `/dashboard/following_tags` until we have further fleshed out what we want to do with our dashboard. 

cc @anujbhavsar96
