### ISSUE TITLE
Importing foremURL/feed/username to a Forem via RSS doesn't behave as expected

### ISSUE THREAD

**Issue by ellativity** [forem/forem#16924]
**Describe the bug**

I would expect the process of importing `foremURL/feed/username` to work the same every time, whichever Forem I'm importing from/to. This isn't what I'm currently observing, as can be seen in [this Notion file](https://www.notion.so/forem/5c98d6134cc0471690d2d2eb49ffe930?v=76e1b391d5ec4125b4f8cb10434f5edd) and [this internal Slack discussion](https://forem-team.slack.com/archives/CAA200SH5/p1647033442926649).

"Importing" as used in this issue describes filling the Feed address in the above format into **User Settings > Extensions >  Publishing to `Forem Name` from RSS**

What I'm seeing is that importing from non-DEV Forems (e.g. `https://forem.dev/feed/ellativity` or `https://forem.dev/feed/community-success` via) into all Forems (including DEV) works as expected. That is to say, all posts published under that feed import into my Dashboard on the Forem. It doesn't appear to matter whether the imported feed is from a user or organization (the org feed imports all posts by all users as new drafts in my Dashboard attributed to me).

However, [as seen in this table](https://www.notion.so/forem/5c98d6134cc0471690d2d2eb49ffe930?v=76e1b391d5ec4125b4f8cb10434f5edd), things don't exactly work smoothly every time. 

**Additional context**

[Lots of chat in this internal Slack discussion](https://forem-team.slack.com/archives/CAA200SH5/p1647033442926649).

**Comment by djuber** [comment]
```ruby
[14] pry(main)> feed_url = 'https://dev.to/feed/spacelift/'
=> "https://dev.to/feed/spacelift/"

[15] pry(main)> Feeds::ValidateUrl.call(feed_url)
=> false

[16] pry(main)> xml = HTTParty.get(feed_url, timeout: 10)
=> #<HTTParty::Response:0x2a5a58 parsed_response=nil, @response=#<Net::HTTPForbidden 403 Forbidden Bots readbody=true>, @headers={"connection"=>["close"], "content-length"=>["0"], "server"=>["Varnish"], "retry-after"=>["0"], "accept-ranges"=>["bytes"], "date"=>["Fri, 18 Mar 2022 20:43:57 GMT"], "via"=>["1.1 varnish"], "x-served-by"=>["cache-pwk4979-PWK"], "x-cache"=>["MISS"], "x-cache-hits"=>["0"], "strict-transport-security"=>["max-age=31557600"]}>
```

This could be bad-bots detection (which is part of the fastly config so wouldn't impact other forems than DEV) blocking the default "Ruby" user agent, this is very close to what happened with forem embed tags this morning.
