### ISSUE TITLE
Tag page Create Post button doesn't appear as expected

### ISSUE THREAD

**Issue by ellativity** [forem/forem#16978]
## Current behavior

It's not intuitive that **Rules markdown**/`submission guidelines` is the trigger field for the `Create Post` button to appear on the tag page. Example: this tag [#programming](https://dev.to/t/programming) doesn't have Rules markdown set up, and the `Create post` button disappears.

The `Create Post` button is the only way that members can use a **Submission template** for a new post pre-tagged with the tag name. This button should appear if the **Submission template** field is completed, whether or not the **Rules markdown** field is completed. 

An exception to this should be https://github.com/forem/forem/issues/16490 (and then it seems to me that limitation is subject to external logic, in contrast to the internal logic of the tag page itself).

## Expected behavior

`Create post` should always show up, independent of whether the submission template is set up. If the submission template is set up, then this button should lead to a `/new` new post editor view with the template pre-populated; otherwise, it should bring up a normal `/new` new post editor. Under the circumstances of #16490, when comment-only is on, the expectation is the button would never show up whether a template is set up.

**Comment by amywtlin** [comment]
@ellativity I added "Expected behavior" in the body - can you help confirm if that looks right?

**Comment by msarit** [comment]
@amywtlin @ellativity In my understanding, there are ambiguous expectations in this issue:

> This button should appear if the Submission template field is completed, whether or not the Rules markdown field is completed.

> `Create post` should always show up, independent of whether the submission template is set up.

Please clarify? 🙏🏾

**Comment by amywtlin** [comment]
I think Rules markdown & submission template is actually the same thing in our code, but are named differently in admin-facing interface and user-facing interface. I remember @ellativity has an issue written on aligning the different names as it causes confusion (like right now) but I can't find it right now. Can Ella confirm these two are actually the same thing?

**Comment by amywtlin** [comment]
On user-facing interface, it's called `Submission template` (https://dev.to/t/ux)
![Screen Shot 2022-04-19 at 4 26 22 PM](https://user-images.githubusercontent.com/11730007/163959232-50280e35-3875-42eb-bc12-239edf5c3e54.png)

When you edit it, it is called `Rules Markdown` (https://dev.to/t/ux/edit):
![Screen Shot 2022-04-19 at 4 27 07 PM](https://user-images.githubusercontent.com/11730007/163959388-b3f8937f-92c6-42d8-9c3b-02ef47e1695e.png)

On the admin page, the same field is also called `Rules Markdown` (https://dev.to/admin/content_manager/tags/353/edit)
![Screen Shot 2022-04-19 at 4 28 15 PM](https://user-images.githubusercontent.com/11730007/163959653-6adbbfb9-323b-4618-be3f-02d663a5ef18.png)

**Comment by amywtlin** [comment]
@msarit Assigning back to you as the ambiguity has been clarified - feel free to unassign yourself if you are focusing on other tasks though.
