### ISSUE TITLE
What to show for the organization's dashboard when current user is org admin but not site admin

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17008]
This builds on https://github.com/forem/forem/issues/16893

Here's the background: User A is part of Org 1.  User A is not a site-wide admin nor super admin.  However, User A is an admin of Org 1. 

At present, the organization's dashboard shows post, series, followers (same as a user, and in fact using the same view).  

In the above scenario User A's personal dashboard would not show the posts, series, nor followers.  Should the dashboard for the organization when User A visits it show or hide the organization's posts, series, and followers?

**Comment by amywtlin** [comment]
So this is what I see right now as an org admin on forem.dev:

![Screen Shot 2022-03-25 at 4 43 54 PM](https://user-images.githubusercontent.com/11730007/160086422-78a1d962-00c5-45d5-a563-c9d28cd2f02f.png)

It feels to me that it still makes sense for org admins to still be able to access analytics of orgs they manage, even though they can't create new posts. I can imagine they might want to see data in the past. I think the dashboard treatment for org admins when they are not also site-wide or super admins should be very similar to community members, just that they also get to keep org analytic tabs. If an org admin is also a site-wide or super admin, then the restriction being an org admin gets overridden by their admin roles.

Does this make sense?

**Comment by jeremyf** [comment]
<img width="1333" alt="Screen Shot 2022-03-25 at 10 22 02 AM" src="https://user-images.githubusercontent.com/2130/160139760-b765a053-8864-46c0-b70c-0a32ce9c8ff1.png">

I have uploaded a screenshot of an organization's "dashboard".  The "blue" section are what is the "organization's" information.  The red sections are user specific information.  Note, the counts on the left are **not** the organization's counts but instead the user's count.

**Comment by jeremyf** [comment]
I realize in my response, I didn't confirm your perspective.  But want to highlight that we might want to step back and ensure the data for a given page is coherent.  Based on the above screenshot, the data is not coherent.  With coherent data we can then talk about permissions.  (The logic is already labyrinthine so I don't want to add more conditionals)

**Comment by amywtlin** [comment]
How did you enter `dashboard/organization/1` from the interface??? I realized from that screenshot I was looking at my own user dashboard, which the only change is that addition of `Analytics for Forem Core Team`. And as I look again, I don't seem to be able to find an entrance leading to said org dashboard in your screenshot...

**Comment by ellativity** [comment]
When you're on your personal dashboard `/dashboard`, **_if you're an admin of an org_** you'll see the org listed in a drop-down menu above the right-hand side of the list of posts. It is set to "Personal" by default, as seen in your top screenshot.

In your most recent screenshot, this reads "Forem Core Team" because you're on your org dashboard via the address.

**Comment by amywtlin** [comment]
Thank you, @ellativity ! I completely ignored it as I thought those were post filters....... which I think @ludwiczakpawel would fix with his /dashboard work.

@jeremyf I now see the discrepancies you meant. I didn't see your description at the bottom...and this is a bug. On org dashboard I'd expect to see all areas are relating to this org, including those you circled in red.

**Comment by jeremyf** [comment]
@amywtlin it's a bug that requires a clear statement of what's expected on each page.  I also believe that this is a bug not related to the AuthN/AuthZ project and aligns with Admin Experience.

My recommendation is to remove this issue from the AuthN/AuthZ project and also from Content Experience.  Then move this back to TODO and hand it to Admin Experience.

**Comment by amywtlin** [comment]
Re: the bug, I agree that we should remove it from the Auth project, but, on second thought, I think this should belong to content experience, as the dashboard is part of the content experience though? 

Org administration is definitely on the fence though...... I am going to create the bug issue first and then ping Jennie about it.

**Comment by jeremyf** [comment]
With the reported bug do we close this issue?  I'm unclear what's actionable.

**Comment by amywtlin** [comment]
I think that's a question for you if we need to change any code to achieve the desired `/dashboard` for org admins. If nothing else needs to change, then yes let's close this.

**Comment by ludwiczakpawel** [comment]
FWIW I'm currently working on updated Dashboard which should solve discrepancy and confusion between Personal and Org dashboards. 

That being said, I'm not sure what the "quick action item" to fix issue above would be, but if it ends up being expensive then I'd recommend putting this on hold and wait till we have updated designs with Product's Seal of Approval.

**Comment by amywtlin** [comment]
Closing this one as we will handle this with the Dashboard updated design.
