### ISSUE TITLE
Following / Not Following status icon is confusing

### ISSUE THREAD

**Issue by deyshin** [forem/forem#1701]
**Is your feature request related to a problem? Please describe.**
During the signup process, suggested people to follow had `+` mark next to them. Selecting them changed it to a check mark. 
To me, personally, opposite status of `+` is `-`, and opposite of checked is unchecked. 
It took me more than enough to make a decision of my own to say what is selected and what is not. 

Now I realized that all the profile pages follow the same pattern of `+` and checked. Can we reconsider this design choice? 

**Describe the solution you'd like**
I think it should either be `+`, `-` pair or check, unchecked pair.
Also, `+` being san serif, while the check mark is serif style is a bit confusing as well. 

**Describe alternatives you've considered**
Just get used to it? Profile page doesn't seem confusing since it says `following` right next to the icon. It still is confusing unless otherwise noted though. 
![image](https://user-images.githubusercontent.com/8847894/52072530-2385df00-2553-11e9-9a48-7805c3124790.png)
![image](https://user-images.githubusercontent.com/8847894/52072557-33052800-2553-11e9-9d5a-e1423219b54e.png)

**Additional context**
n/a

**Comment by mariocsee** [comment]
Throwing out an alternate solution: whenever you hover over the "√ following" button, it changes to "- unfollow". (Like how when you hover on following on Twitter, it changes to unfollow). Would that make the symbol use in "+ follow" / "- unfollow" clearer?

**Comment by deyshin** [comment]
Let me elaborate further on this: 
- `+` & `-` are actions. They show what clicking **will** do. 
- `☐` & `☑`is a status. They show what the current status **is**.
So, action button turning into show the status as the result (when the action is reversible) is somewhat awkward without further description in the signup flow. If I understood `+` as an action, it turning into a status is not straight forward. Will clicking on `☑` perform the action to check, or does it show it is checked? 
Since profile pages discribe it further, it becomes clearer. 

I think @mariocsee's suggestion would help the signup flow a lot. 
`+ Follow` & `☑ Following` seems pretty clear since the words clarify if it is the action or a status. 
so `+ ` & `☑` having some form of hover-over tooltip, that may clarify the signup flow where there is no action attached to it currently.

**Comment by Link2Twenty** [comment]
Looking to twitter for inspiration

**Not following:**
![image](https://user-images.githubusercontent.com/3534427/52132235-9ddb5f80-2636-11e9-94a8-984e3cc5a438.png)

**Following:**
![image](https://user-images.githubusercontent.com/3534427/52132249-a5026d80-2636-11e9-92cb-e01f34ffe323.png)

**Following hover:** (really this should be on focus too, come on twitter! 😉)
![image](https://user-images.githubusercontent.com/3534427/52132280-b6e41080-2636-11e9-9ce7-f61ff8d549ce.png)

**Comment by jessleenyc** [comment]
I think following the twitter pattern here makes sense. @benhalpern thoughts on this design?

**Comment by deyshin** [comment]
While I think the twitter's pattern is good, I also see a value in having an 'icon only (textless)' alternative that's not confusing. That may be too ambitious though.

**Comment by maestromac** [comment]
not stale

**Comment by rhymes** [comment]
unstale

**Comment by mstruve** [comment]
Hey @deyshin! Thank you so much for submitting this issue! We have recently redesigned our Follow buttons so I am going to go ahead and close this issue since we no longer have checkmarks and +/- signs. Thank you so much for being apart of the Forem community!
