### ISSUE TITLE
Can't update any Config > Onboarding settings without uploading an onboarding background image

### ISSUE THREAD

**Issue by ellativity** [forem/forem#17034]
Even though Forems aren't provisioned with an **onboarding background image** at startup, Admins are unable to change **Suggested Tags** and **Suggested Users** for New Member Onboarding from `/admin/customization/config` without adding an **onboarding background image**.

The following snackbar error is returned when attempting to save **Suggested tags/users** without also uploading an onboarding background image:

![Onboarding image error](https://user-images.githubusercontent.com/76786132/160471082-062ec64e-64e7-4423-a662-df1d30126727.png)

If Forems are required to have an onboarding bg image, then one should be supplied at installation (see Social Preview Image). If not, **Suggested tags/users** should be editable without uploading one.

**Comment by amywtlin** [comment]
The expected behavior here is to not require a background image to set up suggested tags and suggested users.
