### ISSUE TITLE
Admin analytics should end *yesterday*

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#17043]
**Describe the bug**

The current admin analytics accurately show the last 7 or so days ending *today*, but today is incomplete, so they always show a "drop-off".

**To Reproduce**

- Go to `/admin
- Observe that last day is today.

**Expected behavior**

On similar services, they typically show results up to yesterday, for this reason: Complete days. Showing part of today's data is confusing.

**Comment by metamoni** [comment]
Hey, @benhalpern 👋
I'd like to work on this one, if that's OK

**Comment by metamoni** [comment]
There's a draft PR for this here: https://github.com/forem/forem/pull/17064/files, with some questions

**Comment by miguelnietoa** [comment]
This has been resolved here https://github.com/forem/forem/pull/17064, so I guess this PR should be closed

**Comment by djuber** [comment]
@miguelnietoa thanks for the follow up! closed.
