### ISSUE TITLE
Update deprecated ransack functionality

### ISSUE THREAD

**Issue by jgaskins** [forem/forem#17074]
As I pointed out in [this review](https://github.com/forem/forem/pull/17068#pullrequestreview-928072836), the `ransack` gem is deprecating a specific method signature for `sort_link`. From their [changelog for v3.0.0](https://github.com/activerecord-hackery/ransack/blob/main/CHANGELOG.md#300---2022-03-30):

> * Deprecate passing two trailing hashes to `sort_link`, for example:
>
>     ```ruby
>     sort_link(@q, :bussiness_name, "bussines_name", {}, class: "foo")
>     ```
>
>     Pass a single hash with all options instead. PR [1289](https://github-redirect.dependabot.com/activerecord-hackery/ransack/pull/1289)

As far as I can tell, this is [only used in `app/views/admin/tags/index.html.erb`](https://github.com/forem/forem/blob/2a127477e702c056070475e63b7b300744168f0e/app/views/admin/tags/index.html.erb#L36-L39).

**Comment by vishaldeepak** [comment]
please assign this to me

**Comment by zhangted** [comment]
I can take up this one if its still up for grabs :)

**Comment by ktmouk** [comment]
This issue can be closed as it has already been fixed by #17845.

**Comment by maestromac** [comment]
Thanks @ktmouk
