### ISSUE TITLE
Following users showing -1

### ISSUE THREAD

**Issue by saketh-kowtha** [forem/forem#17087]
if i follow users and unfollow them (all the users) then followers count is showing as -1. Here is the screenshot

**Expected behavior**

It should show 0

**Screenshots**

<img width="251" alt="Screenshot 2022-04-03 at 6 18 03 PM" src="https://user-images.githubusercontent.com/29446105/161428896-01413bab-834b-415b-845d-62dce7161270.png">

- Browser, version: Chrome, safari, Brave and Edge haven't tested in other browsers.

**Comment by fdocr** [comment]
Thank you for the report @saketh-kowtha.

Does this follower count appear the same (as `-1`) even after you refresh the page? I'm trying to understand the issue a little better and see if this is a JS bug or if it happens deeper in the stack

**Comment by saketh-kowtha** [comment]
Yes even after reload the behaviour is same not only that even if I change device or browser it is same

**Comment by kamil7x** [comment]
I am following 2 users, and this counter shows `1`. I tested it by unfollowing, and as expected, when I had 1 user, it showed `0` and after unfollowing last one, it was `-1`.

So it looks like simple calculation issue.

**Comment by jaw6** [comment]
:wave: Hey folks -- I have tried to replicate this today across three forem instances plus local and the count has been correct in every case. I'm going to close the bug for now, but if it's still happening, please re-open with more details, especially _which page_ is showing the negative following count (it's possible we have counts in multiple places that aren't in sync with each other!)
