### ISSUE TITLE
Comments area not paying attention to comments_order

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#17084]
**Describe the bug**

In addition to the _edge cache_ bug here: https://github.com/forem/forem/issues/17080, there appears to be a fragment cache issue where we are not passing down.

The bug is that comments are not refreshing, so I don't want to continue to be overly presumptive about the problem, but that appears to be the case.

This is _somewhat_ of a duplicate of the other bug, but circumstantially different, so I feel like this can be a new issue with the other one closed.

**To Reproduce**

Same as https://github.com/forem/forem/issues/17080

**Additional context**

This fragment wraps the whole area:

```ruby
<% cache("whole-comment-area-#{@article.id}-#{@article.last_comment_at}-#{@article.show_comments}-#{@discussion_lock&.updated_at}", expires_in: 2.hours) do %>
```

But without passing `@comments_order` _into_ that cache key, it is effectively ignored _within_... Except if it is passed, then it is trapped as the result, meaning we could "cache" latest as "top".

Extremely relevant post on the subject: https://dev.to/devteam/the-three-caches-of-forem-492p

**Comment by vishaldeepak** [comment]
@benhalpern I am trying to resolve this , I don't understand this statement
```
Except if it is passed, then it is trapped as the result, meaning we could "cache" latest as "top".
```
Is it not possible to just cache it as follows by adding comments order. I tried in my local dev and seems to be working as expected.

<% cache("whole-comment-area-#{@article.id}-#{@article.last_comment_at}-#{@article.show_comments}-#{@discussion_lock&.updated_at}-**_#{@comments_order}_**", expires_in: 2.hours) do %>

Followed by this as well

<%= render partial: "articles/comment_tree", collection: Comment.tree_for(@article, @comments_to_show_count, @comments_order), as: :comment_node, cached: proc { |comment, _sub_comments| [comment, @comments_order] } %>

**Comment by benhalpern** [comment]
This has been fixed
