### ISSUE TITLE
Color display over "Save profile information" button in settings

### ISSUE THREAD

**Issue by apollo79** [forem/forem#17160]
**Describe the bug**

The color displays in the settings are showing over the "Save profile information" button

**To Reproduce**

Go to settings page, change something so the button to save the changes shows sticky on the button of the viewport, then scroll down to "Branding" section. The color displays (small rectangles, that show the selected color) show over the button. 

**Expected behavior**

The color display should disappear behind the button. 

**Screenshots**

![IMG_20220407_140449](https://user-images.githubusercontent.com/90517340/162194607-c61c9fef-f782-49df-be2a-4bf0edcd994a.jpg)
![IMG_20220407_140420](https://user-images.githubusercontent.com/90517340/162194613-bdfc8c43-2421-408c-891a-86a96d205e1b.jpg)

**Smartphone:**

- Device: Xiaomi Redmi  8 Pro
- OS, version: MIUI Global 12.5.6
- Browser, version: Firefox mobile 98.3.0

**Comment by miguelnietoa** [comment]
Hi, I would like to work on it!
