### ISSUE TITLE
Rate limit for Listings created in `/admin/customization/config` should disappear when Listings is turned off

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17175]
# Context
This is one of the bugs after [going through steps](https://www.notion.so/forem/Amy-Apr-8-Steps-to-verify-Listings-as-an-Extension-56128c2adcd145529b8c8f8b06c2207c) to verify if Listings turning into an extension works as expected.

# Current behavior

The Rate limit for Listings in `/admin/customization/config` doesn't show/hide according to the on/off status of Listings as an extension.
<img width="1294" alt="Screen Shot 2022-03-29 at 2 30 27 PM" src="https://user-images.githubusercontent.com/11730007/162394729-93288e8b-f5e3-41d8-b547-dd1df1e25872.png">

# Expected behavior

The Rate limit for Listings in `/admin/customization/config`  should show/hide according to the on/off status of Listings as an extension. When turned on, the configuration should be visible; when turned off, the 
configuration should disappear.

# Steps to recreate

Follow the `Before you start` section [here](https://www.notion.so/forem/Test-plan-Hiding-Listings-7c8141d6cfff46cb908dc3366c7f0a98), and then turn Listings off and on using Canary 1 to see current behavior.

**Comment by jeremyf** [comment]
Reading notes for those that follow, the item is rendered via:

https://github.com/forem/forem/blob/bd097bca25586a502c954224e66d35ac0c9bd2d0/app/views/admin/settings/forms/_rate_limit.html.erb#L17-L29

Which is populated here:

https://github.com/forem/forem/blob/bd097bca25586a502c954224e66d35ac0c9bd2d0/app/helpers/rate_limit_checker_helper.rb#L7-L106
