### ISSUE TITLE
Banner not visible in android mobile browsers and DEV android app

### ISSUE THREAD

**Issue by rt4914** [forem/forem#17186]
**Describe the bug**

Banner not visible in android mobile browsers and DEV android app

**To Reproduce**

1. On Android Device, open chrome browser and open any forem, example dev.to
2. Banner should be visible at bottom, but its not.

1. On DEV android app
2. Banner should be visible at bottom, but its not.

**Expected behavior**

In android browsers, banner should be visible at bottom so that "Forem android" app can be opened or installed via a click.

**Comment by fdocr** [comment]
Hi Rajat, I can't reproduce this on a Samsung A21s with Android 11. On Chrome web browser I do see the banner:

![PHOTO-2022-04-08-10-20-07](https://user-images.githubusercontent.com/6045239/162483399-cd23063d-bda8-4fbe-bdd0-7f4764b67398.jpg)

Do you have the details of the device where this happens? (model, OS, browser)

Also, the banner **shouldn't be visible** inside the mobile apps. The banner is meant to exist on web browsers or external embedded web views (within Twitter, Reddit, etc) to help users jump into the apps themselves where they have all their Forems (or install and get started with the apps).

**Comment by fdocr** [comment]
I forgot to mention that we don't currently support Firefox on Android because of a bug they have when opening Intents

https://github.com/forem/forem/blob/main/app/javascript/runtimeBanner/RuntimeBanner.jsx#L99-L102

**Comment by rt4914** [comment]
Thanks @fdocr 
Actually I have checked it on multiple emulators and devices and it does work correctly and somehow its just not working on my device. For now I will close this issue as it seems to be a problem on my end. Will file a detailed issue once I am able to investigate with a valid reason.
