### ISSUE TITLE
Label the repo as rails

### ISSUE THREAD

**Issue by tnir** [forem/forem#17203]
**Describe the task**

Label the repo as [rails](https://github.com/topics/rails) to list Forem as one of Rails applications to gain traction for contributions.

# Current repo profile

![github com_forem_forem](https://user-images.githubusercontent.com/10229505/162651024-2bb2ed31-6c8a-4f63-9914-abd97779fa87.png)

# Expected results

forem/forem listed at https://github.com/topics/rails?o=desc&s=stars next to [devise](https://github.com/heartcombo/devise) ranking 5th.

**Comment by tnir** [comment]
@benhalpern @Zhao-Andy What do you think?

**Comment by jeremyf** [comment]
Definitely think `rails` makes sense

**Comment by tnir** [comment]
Any person from @forem can do this in less than 1 min? @jeremyf

**Comment by jeremyf** [comment]
Done.  And thank you @tnir for the ping.  I've been doing a lot of scattered work.

**Comment by tnir** [comment]
Thanks @jeremyf.

Here is the screenshot (768x3000px resolution) at topics/rails:

![github com_topics_rails](https://user-images.githubusercontent.com/10229505/165001491-c4d3b023-e5fc-4416-9d4b-b9b44c5b79c6.png)

## Star History

Also this is star history of discourse, gitlabhq, and forem (top 3 rails-based app on GitHub):

[![Star History Chart](https://api.star-history.com/svg?repos=discourse/discourse,gitlabhq/gitlabhq,forem/forem&type=Date)](https://star-history.com/#discourse/discourse&gitlabhq/gitlabhq&forem/forem&Date)

<details>
<summary>Snapshot 2022-04-24</summary>

![star-history-2022425](https://user-images.githubusercontent.com/10229505/165001627-52f902eb-b80b-4cd9-9ed0-bad231563de7.png)
</details>
