### ISSUE TITLE
Revisit the `comment_count_by_those_followed_factor`

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#17233]
Revisit the following factor

https://github.com/forem/forem/blob/e2618c50f5e7e48ebdcaa5c85b5c3045ac9be639/app/services/articles/feeds/weighted_query_strategy.rb#L101-L104

The clause and cases are intended to say that as the more people I follow are conversing on an article, it should show up in my feed.  As I reflect on the intention, the reason for the backing off (e.g. going from 0.99 to 0.93) is to reduce the chances of creating an echo chamber.  However that might be in error.

**Comment by mirie** [comment]
@pkfrank have we already addressed this concern? I know we've made a number of changes to the feed algorithm since April.

**Comment by pkfrank** [comment]
Let's close this one for now.  We can always re-open if appropriate, but this specific issue has gone a bit stale relative to our other feed improvements that are more directly in motion.
