### ISSUE TITLE
Embed link image broken on Forem-to-Forem links for Cloudinary

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#17238]
**Describe the bug**

On DEV, when I post _link embeds_ to other Forems, we get this error for the logo:

<img width="588" alt="Screen Shot 2022-04-11 at 4 12 08 PM" src="https://user-images.githubusercontent.com/3102842/162823885-0099c807-f00f-4c70-9c26-ff777c609510.png">

**To Reproduce**

- Go to https://dev.to/new
- Add this to a new post and preview:

```
{% embed https://www.metapunk.to/ %}

{% embed https://community.codenewbie.org %}
```

**Expected behavior**

The Forem logo shows up instead of broken link

**Additional context**

This is an image I get:

https://res.cloudinary.com/practicaldev/image/fetch/s--aAw_MI3y--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://res.cloudinary.com/practicaldev/image/fetch/s---ZJRRwJ2--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_48/https://www.metapunk.to/images/LpR64kRp1dojjJl8tgJ8aB-YRzbilNTj8zVTNUJcIT0/w:32/mb:500000/ar:1/aHR0cHM6Ly93d3cu/bWV0YXB1bmsudG8v/cmVtb3RlaW1hZ2Vz/L3VwbG9hZHMvYXJ0/aWNsZXMvYzFkdTJn/dmt1OXZ0c3doN2Jv/bHQuanBn

It looks like the Cloudinary prefix is applied twice.

If I take _the second part of the URL, it works:

https://res.cloudinary.com/practicaldev/image/fetch/s---ZJRRwJ2--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_48/https://www.metapunk.to/images/LpR64kRp1dojjJl8tgJ8aB-YRzbilNTj8zVTNUJcIT0/w:32/mb:500000/ar:1/aHR0cHM6Ly93d3cu/bWV0YXB1bmsudG8v/cmVtb3RlaW1hZ2Vz/L3VwbG9hZHMvYXJ0/aWNsZXMvYzFkdTJn/dmt1OXZ0c3doN2Jv/bHQuanBn

**Comment by jeremyf** [comment]
Just a quick guess, does this embed OpenGraph have a relative URL?  If it does,  we may need to adjust our OpenGraph rendering to include prefix the image url with the host URL.

**Comment by msarit** [comment]
@jeremyf @benhalpern 
The broken favicon images render correctly on local 🤔 

To generate the favicon images in the OpenGraph embed, we first check that the OpenGraph tags have a `favicon` url, then we use `Images::Optimizer` to generate the `src` value:
```
 <div class="color-secondary fs-s flex items-center">
    <% if page.images.favicon %>
      <img
        alt="favicon"
        class="m-0 mr-2 radius-0"
        src="<%= Images::Optimizer.call(page.images.favicon, width: 48) %>"
        width="24" height="24" loading="lazy" />
    <% end %>
    <%= url_domain %>
</div>
```

I'm not sure if the problem is coming from use of `Images::Optimizer`? Thoughts?
