### ISSUE TITLE
Menu item isn't highlighted when on a tab

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17240]
**Describe the bug**

When you first land on `/admin/advanced/tools`, the `Developer Tools` menu item to the left stays highlighted, so you get a sense of where you are in the application. 

However, if you move on to any of the tabs on top (`Vault Secrets`, `Data Update Scripts`, `Extensions`), the highlighted status on the menu item is gone, which causes confusion and disorientation. 

**To Reproduce**

1. Go to `/admin/advanced/tools`
2. Click on any of the tabs on top that you are not currently in (any of `Vault Secrets`, `Data Update Scripts`, `Extensions`)
3. You'll see that highlighted status on the menu button disappear

**Expected behavior**
The `Developer Tool` menu item should stay highlighted, no matter which tab you are on.

**Screenshots**

![Screen Shot 2022-04-12 at 3 47 32 PM](https://user-images.githubusercontent.com/11730007/162908461-6f46bb0d-f47f-47a1-b50a-29b9b8dad695.png)

![Screen Shot 2022-04-12 at 3 46 17 PM](https://user-images.githubusercontent.com/11730007/162908208-804ffb61-364c-4cc7-886f-6e839d67275c.png)

**Desktop (please complete the following information):**

- OS, version: macOS 12.3.1 
- Browser, version: Chrome Version 93.0.4577.63

**Additional context**

This inconsistency was originally discovered by @ellativity.

**Comment by juliannatetreault** [comment]
Thanks, @miguelnietoa! I’ve assigned the issue to you. 😊
