### ISSUE TITLE
Provide some loading indication when Previewing your post

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17291]
# Background
I noticed when testing a PR with multiple generic embeds that sometimes the embed fetching process can really slow down the time to process the markdown and show the preview:

https://user-images.githubusercontent.com/20773163/163410941-0dfef245-2fc1-4f8a-ab5b-40aadf557da0.mp4

(In the example above, I'd previously clicked preview before too, so I think the embed URLs should be cached?)

Unlike when you publish a post, there's no visual indication of a "loading" state when you click to Preview, but I think we need it now. Otherwise it kinda looks like nothing is happening / the button is broken.

# Definition of done (expected behavior)
Implement the required changes to make the expected behavior specified below happen based on the design [here](https://www.figma.com/file/PIPeiiVSADmcpCbiZTdJm9/Composer-%E2%80%93-First-redesign?node-id=1975%3A965).

# Expected behavior

We are inserting a loading state when writers switching over to the `Preivew` tab. 

When this feature is done, writers should see a loading state when they move to the `Preview` tab, while the preview is still rendering. Once it's done rendering, the preview then replace the loading state.
![Screen Shot 2022-05-16 at 3 56 12 PM](https://user-images.githubusercontent.com/11730007/168545648-75dccc47-d310-4708-8d2e-3b882490d168.png)

**Comment by ludwiczakpawel** [comment]
I think it would make the most sense if we start async fetching/pinging given URL once it's literally entered (behind the scenes / under the hood). So once you click "Publish" button it would happen immediately. 

Another idea is to NOT fetch it at all while publishing the article and instead do so when displaying the article. There were couple places this idea was mentioned in the spec doc but seems like it's been forgotten.

**Comment by aitchiss** [comment]
> if we start async fetching/pinging given URL once it's literally entered (behind the scenes / under the hood)

Hmm I get what you mean but it feels wrong to me for the frontend to be constantly checking the entered text for `{% %}` and pinging off network requests as/when it finds them. Also AFAIK those embed URLs I ping in the video above _should_ have already been cached (since I'd been in and out of the preview window a few times). So I feel a bit unconvinced early network pings/caching is the way forward.

> Another idea is to NOT fetch it at all while publishing the article and instead do so when displaying the article 

Yeah I think this is the more elegant approach, but would be a pretty significant change 😅 

I would suggest in the meantime that we get some kind of loading indicator in the 'preview post' flow, because at the moment the button feels broken when there's this delay. And even without any embeds in the article, some kind of delay could happen just due to poor network coverage etc.

For the 'publish' post flow we do have a loading state (the "Publish" button turns into "Publishing...") so I think although it could be better UX, it doesn't feel broken when it's slow.

**Comment by ludwiczakpawel** [comment]
> for the frontend to be constantly checking the entered text for {% %} and pinging off network requests as/when it finds them

I'm not an expert here so obviously leaving decision to others but just want to point out that this seems to be a solution used by others (e.g. Twitter or Slack) so I'm sure there must be some efficient/smart way of doing so.

**Comment by aitchiss** [comment]
> this seems to be a solution used by others (e.g. Twitter or Slack) so I'm sure there must be some efficient/smart way of doing so

Yeah you're right, I'm sure we don't need to reinvent the wheel here 😄

**Comment by amywtlin** [comment]
I am hearing two solutions here: front-loading embeds earlier than it is now (potentially when it is entered) or having a embed placeholder while it loads.

I think the biggest issue here is the cumulative layout shift (@ludwiczakpawel I learned it from you!) can get pretty annoying while you scroll. So to solve that, we'll have to know the height of each embed, which I am not sure if it changes depending on the images or the types of embeds. If the embeds are of the same height, then I feel ok just having a placeholder while they load. However, if we have to load the image to decide the height, then I'll vote for front-loading.

Can @aitchiss or @ludwiczakpawel help find out if the height of embeds is dependent on anything to help make a decision?

**Comment by aitchiss** [comment]
@amywtlin although this conversation has gone down the path of 'optimising the loading of generic embeds', I'd like to steer things back to just adding a loading indicator. I think the optimisation of loading the embeds generally could be a separate issue (if we don't already have one).

Although we're referencing embeds here as an example, _any_ post preview requires a network fetch. For users on slow connections this could take a bit of time, even if there aren't any embeds in the post. So we should let users know that something is loading in case they have to wait a while for the preview to be shown.

**Comment by amywtlin** [comment]
That sounds good to me. I think it's always a good thing to have this loading indicator anyways, as even if we front-load things it is still possible for the preview page not to be ready when users visit it. Let's go ahead with a loading indicator for the preview page. Can @ludwiczakpawel help with the support?

**Comment by ludwiczakpawel** [comment]
<img width="3000" alt="image" src="https://user-images.githubusercontent.com/108287/165247454-76dfc115-c683-4787-851d-600cb32a1487.png">


Thoughts on this https://www.figma.com/file/PIPeiiVSADmcpCbiZTdJm9/Composer-%E2%80%93-First-redesign?node-id=1975%3A965 ?

Idea is to switch to the "Preview" tab immediately and show loading skeleton we also show on the Feed ( https://storybook.forem.com/?path=/story/app-components-article-loading--default-article ).

Additionally:
- disable the buttons in action bar at the bottom
- change the page title from "Create post" to "Loading preview" just for better a11y (any thoughts on this @aitchiss ?)

**Comment by aitchiss** [comment]
This looks awesome to me! So much better that there's some immediate feedback 😍 

For a11y, we can also make the "Loading preview" an `aria-live` so it's announced to screen reader users 😄

**Comment by amywtlin** [comment]
Yes!! That is looking great ❤️‍🔥

**Comment by rt4914** [comment]
I am working on this @aitchiss 

I am confused about the loading state, what exactly is this:
1. An image
2. [Shimmer Effect](https://www.google.com/search?q=shimmer+effect&rlz=1C5CHFA_enIN928IN929&oq=shimmer+effe&aqs=chrome.0.0i512l2j69i57j0i512l7.1992j0j7&sourceid=chrome&ie=UTF-8) 
3. ... or should be drawn with css/html?

**Comment by aitchiss** [comment]
Hey @rt4914 👋  I am guessing it should look & have similar effect to the loading state of the home feed - check out `app/javascript/articles/LoadingArticle.jsx` 🙂

**Comment by rt4914** [comment]
Self-assigned this issue.
