### ISSUE TITLE
Can't comment on dev.to

### ISSUE THREAD

**Issue by yaseralnajjar** [forem/forem#17304]
"Error posting comment" error message appears when commenting on dev.to

**To Reproduce**

1. Write some comment (I wrote thanks to Taxman972 [here](https://dev.to/ben/how-long-do-you-sit-for-at-a-time-1aak)):
Wrote simply: "Thanks"
2. Click on Submit
3. The error message will appear with some weird text (with some vulgar text):
```
Your comment could not be posted due to an error: There was an error in your markdown: premature end of char-class: /(care number|homework.+assigment|assignment.+homework|I am new person ready to learn developing softwares...
```

**Screenshots**

![image](https://user-images.githubusercontent.com/10493809/163577616-73c89833-65b0-4932-b1e7-ef0e72d5aa63.png)

**Desktop**

- OS, version: Windows 10
- Browser, version: Opera, 85.0.4341.60

**Additional context**

I tried multiple times to submit a comment getting the same message.

**Comment by aitchiss** [comment]
Hi there @yaseralnajjar! Thank you for flagging this issue up to us so quickly. It should now be resolved and should be able to post comments again. We're looking at longer-term fixes too to make sure this doesn't happen again.

Let us know if you have any further difficulties!
