### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by GalinaLK** [forem/forem#17303]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

![Screenshot_20220415-155458](https://user-images.githubusercontent.com/28838436/163573297-9ee1b9f6-dd96-471b-be0e-13e576e43567.png)

**Comment by aitchiss** [comment]
Hi there @GalinaLK!  Thank you for flagging this issue up to us so quickly, and so sorry for the inconvenience. The issue should now be resolved and should be able to log in again. We're looking at longer-term fixes too to make sure this doesn't happen again.

Let us know if you have any further difficulties!
