### ISSUE TITLE
Self-hosting jQuery instead of delivering from public CDN

### ISSUE THREAD

**Issue by tnir** [forem/forem#17318]
cc @pavelloz

> For performance reasons I would highly recommend self-hosting everything, especially javascripts that are in the Time To Interactive path. jQuery might be one of those scripts that is needed for navigation to work.

_Originally posted by @pavelloz in https://github.com/forem/forem/issues/17205#issuecomment-1100921929_

**Comment by tnir** [comment]
@pavelloz Do you want to work on this? I do not think delivering (jQuery) script from self-hosting than public CDN makes site faster, but can you rationalize it? If not, I am inclined to close this.

jQuery is only used on (1) video uploader and (2) `/admin`.

**Comment by pavelloz** [comment]
Self-hosting:
1. eliminates SSL handshake to 3rd party domain (speed)
2. removes the risk of it being replaced by malicious script (security)
3. does not interact with 3rd party host, so doesnt allow CDN to track your visitors (privacy)

In general everything that can be self-hosted, should be self hosted. :)

I can try tackling that one :)

**Comment by pavelloz** [comment]
Ok i give up.

I dont have time to fight with rails archaic mechanisms to include js and css, i hope its easy to see what needs to be done and how to do it safely based on my try: https://github.com/forem/forem/pull/17672

**Comment by tnir** [comment]
@pavelloz I really appreciate your trial 🎉 . As far as we use webpack/webpacker, bundling time would be slower, which causes bad developer experience compared with performance gain. In-browser caching will be skipped, I think

**Comment by pavelloz** [comment]
Compiling those 100KB wont be noticed. Look at your builds, if it goes up by 1 second its top.
Im 100% its worth it, you do you. Good luck. xo
