### ISSUE TITLE
Sort "Recently Published" on Dashboard show unpublished articles on top

### ISSUE THREAD

**Issue by Anshuman71** [forem/forem#17316]
**Describe the bug**

Unpublished articles are shown on top while doing the sort "Recently Published" on the dashboard.

**To Reproduce**
- Create two articles
- Publish one of them
- Go to Dashboard
- Select "Recently Published" sort
- Unpublished articles will come first 

**Expected behavior**

It should show the published post in descending order and the unpublished posts at the bottom.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Ubuntu 16.04
- Browser, version: Chrome Latest

**Comment by Anshuman71** [comment]
I'm working on this bug. 😃

**Comment by jeremyf** [comment]
@Anshuman71 thanks for the contribution.  I'm looping @amywtlin into the confirmation to confirm that the behavior described above is a bug.  We don't have a "My drafts" select so I can see a case where having a list of drafts at the from might be useful, but perhaps unexpected.

**Comment by Anshuman71** [comment]
@jeremyf thanks for the quick turnaround. I create drafts whenever I've an idea so when I use "Published by" sorting, my drafts are shown up top while I only want to see the latest ones. Adding a **Draft** section would help.

**Comment by amywtlin** [comment]
I agree with @jeremyf that this is not a bug but a feature request. @Anshuman71 Can you turn this into a [GitHub discussion](https://github.com/forem/forem/discussions/new) for feature requests instead? Thanks!

**Comment by Anshuman71** [comment]
@amywtlin I have no problem turning it into a feature request but sorting by "Published" should show "drafts" at the bottom and not the top. This is a quick fix in the sorting logic.

**Comment by amywtlin** [comment]
@Anshuman71 I spent a bit of time thinking about what the behavior should look like. If we were to touch this part, I don't think it makes sense for drafts to show up in `Recently published` at all. `Recently published` should not even include drafts, because, drafts aren't published. What do you think?

I am kind of curious how you are using this though. Do you tend to have lots of drafts? Is that why you would go to recently published to check how your published posts perform, sorting by publish time desc, and wanted the drafts to be down below so as not to have to scroll down? Would filtering out drafts in `Recently published` help you do what you want to do easier?

**Comment by Anshuman71** [comment]
Hi @amywtlin yeah, you're absolutely right about it. The problem is two parts (_as you addressed_)
1. I've like 40 drafts at this moment, there's no way for me to filter them out 
2. To see the stats of the latest published article, I use the "Recently Published" filter but it shows me drafts instead 

Solution:
1. Create a new **Drafts** section on the dashboard (seems like a lot of work)
2. Update the sort logic to make it work for the time being (less work comparatively)

That's why I suggested #2. Hope this helps.

**Comment by amywtlin** [comment]
@Anshuman71 I had a chat with @ludwiczakpawel and he's going to jump in and provide some guidance. Stay tuned!

**Comment by ludwiczakpawel** [comment]
I think this is spot on. Let's **filter out** drafts when "Recently published" sorting is selected. This sorting indicates that posts are **published**. And drafts are **_not_ published** by definition. We can still see drafts in default sorting ("Recently created") which makes sense to me. 

If "filtering out" is hard in terms of implementation then I think we could push them (drafts) to the bottom of the list (only for "Recently published" sorting) for sake of simplicity.

Does that make sense @jeremyf and @amywtlin? If yes, I'll leave the final decision to you.

---

FWIW we're working on some Dashboard updates in general that should solve this problem by providing additional filters (and _sections_) for Drafts. But I'm unable to tell where that is on the timeframe.

---

Btw. @Anshuman71 can you finally publish these 40 posts?! :D

**Comment by amywtlin** [comment]
Yup, I would highly prefer to **filter out drafts** in `Recent published` completely, instead of pushing them down to the bottom, if that doesn't require a significant amount of effort. It is less desirable to push the drafts down, but acceptable. 

@Anshuman71 Do you want to try submitting a PR for filtering out drafts?

**Comment by Anshuman71** [comment]
thanks, @ludwiczakpawel for the quick reply. I'm publishing one per week, as a newbie writer 😄 .

 @amywtlin, I'd love to create a PR but I don't know any Ruby. I'd created #17317 PR but it wasn't accepted. 
Not sure if I'll be able to help 😞

**Comment by jeremyf** [comment]
@Anshuman71 I went ahead and added a commit to your PR, which should remove the draft's from the recently published list.

Thank you for helping us make the Forem codebase better.

**Comment by Anshuman71** [comment]
thanks @jeremyf

**Comment by amywtlin** [comment]
Thanks @jeremyf <3 

And thank you, @Anshuman71 for bringing this up and your PR. I appreciate it. Keep up the good work!
