### ISSUE TITLE
Create space - button/link styling

### ISSUE THREAD

**Issue by anujbhavsar96** [forem/forem#17326]
Create space button/link looks floating right now because of styling. 

We can use the button with an outline or with a bg to make it not look like floating randomly. 

In 1-2, it’ll be activated and will have similar styling to what we have for Create post on the top bar.

[Reference how will it look like in 1-2 when activated](https://www.figma.com/file/SeTWMa3E7F7fieVKm2wvCt/Roles-and-Authorization-System?node-id=306%3A7208)

<img width="666" alt="Screenshot 2022-04-18 at 12 46 11 PM" src="https://user-images.githubusercontent.com/84626054/163788694-ae5a4cce-cd94-4a72-b976-01db448f9e55.png">

**Comment by jeremyf** [comment]
@anujbhavsar96 what is your preference regarding styling?  Do you have a CSS class you'd like us to apply to this button?

**Comment by amywtlin** [comment]
@anujbhavsar96 Which one is the latest button design we want to use eventually? If they are roughly the same effort, let's just get there once.

**Comment by anujbhavsar96** [comment]
I've talked with @ludwiczakpawel. Once he is online, he will point us to the storybook button component.

**Comment by anujbhavsar96** [comment]
I just had a chat with Pawel regarding this issue. And we currently don't have a component for this disabled action _(similar to designs)_. And introducing a new component in code will take much more time and effort at this point.

So we decided to keep this as it is assuming not too many active Forem admins will visit this page until we come to use-case 1-2. 

Anyway, it was good to have not a must-have. So I'm closing this issue.
