### ISSUE TITLE
Toggle component doesn’t look as expected in the mobile and desktop view

### ISSUE THREAD

**Issue by anujbhavsar96** [forem/forem#17325]
1. Desktop ON state toggle seems a bit off
2. In mobile view, the toggle is squeezed. 

In all views, this component should stay the same

<img width="683" alt="Screenshot 2022-04-18 at 11 31 34 AM" src="https://user-images.githubusercontent.com/84626054/163788261-4185434a-3652-488b-8ba7-11e8cd01af4f.png">

**Comment by ludwiczakpawel** [comment]
I'll look into it!
