### ISSUE TITLE
Follow on user liquid tag is unreadable on Dark mode

### ISSUE THREAD

**Issue by codercatdev** [forem/forem#17389]
**Describe the bug**

Follow on user liquid tag is unreadable on Dark mode

**To Reproduce**
Add `{% user mhevery  %}`

**Expected behavior**

white text (or something with better A11y)

**Screenshots**
![C7DBCC35-D7C8-4DA6-A692-EDB395DE666B](https://user-images.githubusercontent.com/3102249/164459113-600a230d-4995-4c6a-a9ab-e66dfef208ca.jpeg)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS, version: 15.3.1
- Browser, version: chrome

**Additional context**

**Comment by msarit** [comment]
Thank you @codercatdev for opening this issue.

It is possible that the user you referenced chose brand colors with low contrast in their Settings.

@JennieOcken @amywtlin I know that during Creator Onboarding and also in Admin, we use a Contrast Validator to ensure an appropriate contrast between brand colors (app/javascript/utilities/color/contrastValidator.js).

Would we want to incorporate the same check in the user Settings? This ticket would need to be updated with the recommended approach and other related information. Thanks! 🙏🏾

**Comment by ludwiczakpawel** [comment]
@msarit probably both: validator in the user settings AND also fixed button in the liquid tags.. Some liquid tag buttons are still "outdated" using pre-crayons era styling (when we used to incorporate user's brand colors into "Follow" buttons). But updating liquid tags is tricky hence this one still uses the old one 🤷 

The fix could technically be as simple as removing liquid tag -specific styling for `.follow-action-button` elements buuuuut I guess it's more tricky than that :)

**Comment by amywtlin** [comment]
It's also broken when on light mode:

![Screen Shot 2022-05-04 at 9 49 03 AM](https://user-images.githubusercontent.com/11730007/166613229-06cb560c-024e-4d49-a33f-f69475d8a698.png)

@msarit Yes. I think using the same check for contrast is a good idea. Can you create an issue for that and link to this one?

@ludwiczakpawel Can you log the fix for liquid tag button as a separate issue and link to this one?

**Comment by ludwiczakpawel** [comment]
@amywtlin https://github.com/forem/forem/issues/17564

**Comment by msarit** [comment]
@amywtlin Done! https://github.com/forem/forem/issues/17574

**Comment by amywtlin** [comment]
Thank you both! I have labelled the issues accordingly. As for this issue, I am thinking we can leave it open until we closed the 2 newly created issues (also to check if the bug brought up originally has been resolved with our remedy). @msarit What do you think?

**Comment by msarit** [comment]
Closing this issue as taken care of here: https://github.com/forem/forem/pull/17602

**Comment by amywtlin** [comment]
@codercatdev Hey - after @msarit fixed #17564, I tried embedding again your `user` embed. It is now accessible and using the new styling (we are moving away from branded `follow` buttons):

![Screen Shot 2022-05-18 at 10 16 49 AM](https://user-images.githubusercontent.com/11730007/168943671-1ce56d83-afd4-4239-9dfd-f3d1455a81b6.png)

The one you had in [your original post](https://dev.to/builderio/hydration-is-pure-overhead-33g7) still has accessibility issues as these embeds need to be resaved to be updated. You can update it simply by heading over to that post and resaving it again. Hope it helps!
