### ISSUE TITLE
Spaces toggle button is not looking good

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#17386]
Attached are the UI of the two buttons (on and off).  This is rendered this way in both Safari and Chrome:

<img width="1013" alt="Screen Shot 2022-04-20 at 2 38 57 PM" src="https://user-images.githubusercontent.com/2130/164300665-411ce3ba-8ee2-4b4d-9e91-49251968299f.png">

<img width="1025" alt="Screen Shot 2022-04-20 at 2 38 52 PM" src="https://user-images.githubusercontent.com/2130/164300674-864789a7-647b-4c90-8507-509a97656446.png">

To duplicate and test:

Pull down `jeremyf/issue---forem/forem#17161` branch, login as admin and go to http://localhost:3000/admin/content_manager/spaces

**Comment by jeremyf** [comment]
I revisited, and it's looking good.

Very weird.

**Comment by ludwiczakpawel** [comment]
Cache.... :D
