### ISSUE TITLE
When visiting /admin/moderation/reports, text styles are overridden

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17418]
**Describe the bug**

When you visit `/admin/moderation/reports` the text styles of the page change. As soon as you leave this page, styles revert to normal.

It seems the style is being injected directly onto the `body` tag:

![style attribute on body tag shows a font family different to our default](https://user-images.githubusercontent.com/20773163/165045374-afabf660-18cf-4b94-b751-1d82abc042d1.png)

**To Reproduce**

Click around the admin area pages, including `/admin/moderation/reports` and notice the difference

**Expected behavior**

Fonts should stay consistent

**Screenshots**

https://user-images.githubusercontent.com/20773163/165045475-79a290d4-ba7c-4260-b060-1c5f4abf4109.mp4

**Comment by mirie** [comment]
Looks looks resolved!
