### ISSUE TITLE
`...` button on user profile page doesn't always show up as expected

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17441]
**Describe the bug**

On Canary 1, there's a 3-dot button on the user profile, and for some others, there aren't. This doesn't happen on dev.to though, hence marking this issue for the core team only for now.

Users we are seeing with the `...`:
- Super admin: https://canary1.forem.wtf/andygeorge
- Regular user: https://canary1.forem.wtf/jeremyf
- Super admin & trusted: https://canary1.forem.wtf/andy

Users without `...`:
- single_resource_admin: Badge, https://canary1.forem.wtf/amynopost_420 (I then removed the role, and it still doesn't show up)
- Super admin & trusted: https://canary1.forem.wtf/amy
- Super admin & trusted: https://canary1.forem.wtf/anujbhavsar96

An interesting side note (which will complicate things): a few mins later, Anuj is now seeing all 6 profiles with the button, while I am still seeing the same specified above. Now it starts to feel like a cache refresh issue, but I still don't get why I see some but not all. Seeing all or none seems to make more sense if it's a cache thing.

**To Reproduce**

1. Go to any of the profiles listed under "withouth `...` button" provided above, you should be able to see the button not showing up. 

**Expected behavior**

As @pawel & @lightalloy confirmed, it should only disappear if a user is viewing their own profile. Otherwise it should always be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/11730007/165483342-472e674b-57e8-40a7-9d0f-6cd862dfc84d.png)
![image](https://user-images.githubusercontent.com/11730007/165483397-d75ff74b-a526-402a-bf6b-5c9b55614c84.png)

**Desktop (please complete the following information):**

OS, version: macOS 11.6.4
Browser, version: Chrome 99.0.4844.84

**Additional context**

It was first brought up [here](https://forem-team.slack.com/archives/C7GE84DEJ/p1651038959829619).

**Comment by aitchiss** [comment]
This is also happening for some users on forem.team, so constitutes a production issue we can assume is likely happening in other Forems.

The root cause is the requested `profileDropdowns` webpacker chunk returning a 404. The user profiles where this fails are trying to pull a _different_  (incorrect) version of the `profileDropdowns` chunk to all the other users. The user profiles where all is working as expected are all pulling the same (correct) version of the `profileDropdowns` chunk.

I'm not currently sure why some pages are pulling the a version that no longer exists.

**Comment by amywtlin** [comment]
@aitchiss does that mean that deprecated version might still exist somewhere that we are unaware of, and we need to find it and clear it? How would you recommend us for going about this?

**Comment by amywtlin** [comment]
It looks like as the cache expires, the issue is gone. I am closing this one, and starting another [thread](https://forem-team.slack.com/archives/C7GE84DEJ/p1651822340260619?thread_ts=1651038959.829619&cid=C7GE84DEJ) to discuss whether we need such extreme caching on this.
