### ISSUE TITLE
GDPR Delete Requests: Remove the Users Namespace on GDPR Delete Requests

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17454]
I changed the task "Invited Members: Change Invitations Route" to "Remove the Users Namespace on GDPR Delete Requests" and moved it to the GDPR epic for the following reasons outlined below. ~ Ridhwana

~~📖 **As an Admin, I want my experience with invitations to be as pleasing and straightforward as possible, so that I feel motivated to use them.**~~

📖 **As an Admin, I want my experience with gdpr_delete_requests to be as pleasing and straightforward as possible, so that I feel motivated to use them.**

✅ Tasks to complete:

~~- [ ] Change Invitations route to `/admin/users/invitations`~~

- [ ] Remove the `users` namespace for GDPR Delete Requests. 

**Context:**
In an upcoming PR we will be placing the gdpr_delete_requests and invitations route under the member manage scope. 

Prior to this PR, the urls looked as follows: 
- Invitations: http://localhost:3000/admin/invitations
- GDPR: http://localhost:3000/admin/users/gdpr_delete_requests

Now you can see that there is a bit of inconsistency above with one of these routes being namespaced under Users and the other not. My initial reaction was to namespace the  invitations under Users. However on further reflection I've decided to remove the User namespace on GDPR instead for the following reasons: 

1. Previously these tabs lived on the Users page, hence a Users namespace made more sense. In an upcoming PR that will be moved to the sidebar, hence perhaps they don't need to be so closely correlated anymore. 
2. In the sidebar we will be grouping these routes under a scope called `:member_manager`, hence if we kept the users namespace the URL would have read `http://localhost:3000/admin/member_manager/users/gdpr_delete_requests`, with `member_manager` in the URL `/users` seems redundant. 

<img width="219" alt="Screenshot 2022-05-02 at 09 30 20" src="https://user-images.githubusercontent.com/2786819/166199725-4f4eaad0-454b-4fc4-8f17-dc2803c2fb26.png">

**Comment by juliannatetreault** [comment]
It looks like this issue should have been closed via #17536 -- is it safe to close this issue out?

cc @Ridhwana
