### ISSUE TITLE
Invited Members: Rename "Invited Member" to "Username"

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17452]
📖 **As an Admin, I want my experience with invitations to be as pleasing and straightforward as possible, so that I feel motivated to use them.**

✅ Tasks to complete:
- [x] Rename "Invited Member" as the column header to "Username"

**Comment by juliannatetreault** [comment]
Heads up: This issue seems dependent upon the completion/merging of [this PR](https://github.com/forem/forem/pull/17438#issuecomment-1110804719).
