### ISSUE TITLE
Member Index View Actions: Reusable Modals 

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#17479]
📖 **As an Admin, I want my experience using the Member Index View to be as pleasing and straightforward as possible, so that I feel motivated to use it.**

✅ Tasks to complete:
- [ ] Make the modals from the Member Detailed View reusable within the Member Index View
⚠️ Can this be re-used for bulk actions?

**Comment by aitchiss** [comment]
By way of documentation, [here's a Loom walking through what changes I made to make the modals reusable](https://www.loom.com/share/96985356c7334cf3aa54465d7b9e1ec7), and here's [another one where I walk through an example adding functionality to the member index add role modal](https://www.loom.com/share/b34416c4adaf44609d657da4e93513b3)
