### ISSUE TITLE
Member Index View Actions: "Banish user"

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#17486]
📖 **As an Admin, I want my experience using the Member Index View to be as pleasing and straightforward as possible, so that I feel motivated to use it.**

✅ Tasks to complete:
- [x] Build Action "Banish user" (use reusable modal)

**Comment by Ridhwana** [comment]
Closing this issue as per this comment https://forem-team.slack.com/archives/C7GE84DEJ/p1657564157625299?thread_ts=1657531192.719549&channel=C7GE84DEJ&message_ts=1657564157.625299
