### ISSUE TITLE
Member Index View Filters: Display Selected Filters

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#17489]
📖 **As an Admin, I want my experience with filtering the Member Index View to be as pleasing and straightforward as possible, so that I feel motivated to use it.**

✅ Tasks to complete:
- [x] #17945
- [x] Show selected "statuses" filters on the index page, and allow user to remove them
- [x] #17976
- [x] Show selected "joining date" filter on the index page, and allow user to remove it

Descoped:
- [ ] Show selected "last activity" filter on the index page, and allow user to remove it

**Comment by aitchiss** [comment]
All filters confirmed for phase 2 have been implemented; closing this issue
