### ISSUE TITLE
Member Index View Filters: Date Range Selector Component

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#17493]
📖 **As an Admin, I want my experience with filtering the Member Index View to be as pleasing and straightforward as possible, so that I feel motivated to use it.**

✅ Tasks to complete:
- [ ] Create a crayons date range picker we can use in the admin area

## Background

Inspiration for the date range picker functionality comes from [LitePie](https://litepie.com/), but since this library requires Vue & Tailwind, and has some accessibility issues, we are going to instead rely on `react-dates` under the hood. This will require a level of customisation, and this issue covers creating a wrapping crayons component that implements the desired functionality.

## Design

Please see ["Version 1" design in Figma](https://www.figma.com/file/Ejc7VELuN00n1SZrkUTBcQ/Member-List-View?node-id=1237%3A6396)

## Required features

A user should be able to:
- Select a start and end date of a range either by mouse, by keyboard
- Type their start and end date without worrying about the calendar widget (if they prefer)
- Jump to a particular year`*`
- Jump to a particular month`*`
- Navigate backwards and forwards between months

The component should also:
- Accept a "minimum date" - i.e. the earliest date the user may select 
- Accept a "maximum date" - i.e. the latest date the user may select
- "Quick select" from a set of pre-defined time ranges (e.g. "Last 30 days")`*`  (see below)
- Only display "quick select" ranges if they fall within the min/max dates`*`

NB: Items marked with a `*` do not come by default with this library and will require dev to implement

## Localization

- When a user's locale is `en-US`, they should see dates in format MM/DD/YYYY
- All other users should see dates in format DD/MM/YYYY 

## Responsive

`react-dates` will not adjust layout based on screen size "off the shelf". When in a 'small screen', our component should dynamically reconfigure the calendar layout so it works well for users.

## Quick select date ranges

As shown in the designs, some "quick select" options should be provided to the user. 

NB: each option should only be shown if its start and end dates fall within the min and max dates for the input.

**- This month**
All dates from 1st of the current month til today

**- Last month**
The last full calendar month - e.g. if today is 5 May - it selects 1 April - 30 April

**- This quarter**
The available quarters are:

1 January - 31 March
1 April - 30 June
1 July - 31 September
1 October - 31 December

This button should select the current quarter's start date, and end with today's date

**- Last quarter**
Same quarters above but picks the quarter before the one the current date falls in. e.g. if it's 5 May it selects 1 January - 31 March

**- This year**
Everything from 1 January to today's date

**- Last year**

The last full calendar year. e.g. if I pick this today, it selects everything from 1 January 2021 to 31 December 2021

**Comment by aitchiss** [comment]
@anujbhavsar96 is the above enough information for you to look at defining what we want this picker to look like design-wise?

**Comment by anujbhavsar96** [comment]
@aitchiss Yes that's enough for me to start working on the designs. I'll prepare designs for this component tomorrow so it gets easier for you to reference.

**Comment by anujbhavsar96** [comment]
@aitchiss  :wave:

[Here are the date picker component designs](https://www.figma.com/file/Ejc7VELuN00n1SZrkUTBcQ/Member-List-View?node-id=1237%3A6396). I tried not to make any significant changes. Still, give it a look and let me know if I’ve missed any of the points or are there any issues in terms of accessibility. Feel free to drop comments in Figma.

**Comment by aitchiss** [comment]
This looks great @anujbhavsar96! I take it it's 'version 1' in that doc?

I just want to make sure I definitely understand the 'quick select' options -

## This month

All dates from 1st of the current month til today

## Last month

If today is 5 May - it selects 1 April - 30 April?  Or does it select 5 April - 5 May?

## This quarter

If quarters are based on calendar year from Jan 1, then these would be:

1 January - 31 March
1 April - 30 June
1 July - 31 September
1 October - 31 December

And we select whichever quarter's start date is closest to current date, and end with today's date. So if today is 5 May, it would select 1 April - 5 May.

## Last quarter

Same quarters above but picks the quarter before the one the current date falls in. e.g. if it's 5 May it selects 1 January - 31 March?

Or is this button expected to just select the last 3 months from today's date - e.g. if it's 5 May it selects 5 February - 5 May?

## This year

Everything from 1 January to today's date

## Last year

e.g. if I pick this today, it selects everything from 1 January 2021 to 31 December 2021? Or would it select everything from 5 May 2021 to 5 May 2022?


Also - when any of those selectors contain dates that are older than the Forem's start date, should we visibly disable the buttons, or should we remove the buttons completely?

**Comment by anujbhavsar96** [comment]
**Last month**
> If today is 5 May - it selects 1 April - 30 April? Or does it select 5 April - 5 May?

 It selects 1 April - 30 April
 
 ---
 
 **This quarter**

> And we select whichever quarter's start date is closest to current date, and end with today's date. So if today is 5 May, it would select 1 April - 5 May.

Yes, you are right

---

**Last quarter**

> Same quarters above but picks the quarter before the one the current date falls in. e.g. if it's 5 May it selects 1 January - 31 March?
>
> Or is this button expected to just select the last 3 months from today's date - e.g. if it's 5 May it selects 5 February - 5 May?

 It selects 1 January - 31 March
 
 ---
 
 **Last year**
 

> if I pick this today, it selects everything from 1 January 2021 to 31 December 2021? Or would it select everything from 5 May 2021 to 5 May 2022?

It selects everything from 1 January 2021 to 31 December 2021

---

> when any of those selectors contain dates that are older than the Forem's start date, should we visibly disable the buttons, or should we remove the buttons completely?

I think, removing the button is a good option, why let them explore the months if they can't do anything. The same applies to Future months/dates. 

@aitchiss let me know if you still have any confusion✨

**Comment by aitchiss** [comment]
Thanks @anujbhavsar96! I've updated the issue description to link the designs and flesh out the detail 🙂
