### ISSUE TITLE
Heart, Unicorn and Bookmark button number mismatch

### ISSUE THREAD

**Issue by josuebustos** [forem/forem#17539]
**Describe the bug**

The button number ticks display differently. Whether you're logged in or not the behavior is still the same.

- Link 1:  https://dev.to/top/week
- Link 2:  https://dev.to/josuebustos/post-messages-to-slack-using-aws-lambda-function-urls-5f2a

1. Visit link 1
2. Do word search for key word "Post Messages To Slack Using AWS Lambda Function URLs" to jump to the post.
3. Then open link 2 in a separate tab to compare

**Expected behavior**

I don't know which number is the right one. The image on the left or the post image on the right. Is this a bug? 

**Screenshots**

![Screen Shot 2022-05-02 at 1 04 15 AM](https://user-images.githubusercontent.com/829764/166206231-007a0f88-dfe3-43e8-ad77-c5e09fc09125.png)

**Desktop (please complete the following information):**

- OS, version: macOS Catalina - Version: 10.15.7
- Browser, version: Microsoft Edge - Version 101.0.1210.32 (Official build) (x86_64)

**Comment by maestromac** [comment]
Hello @josuebustos , that is intended. The feed's "reactions" are the combination of all the reactions the post received. 
15+8+28 = 51

**Comment by josuebustos** [comment]
Oh! 😁😄 

I would have never of thought that! 

Thank you for the clarification.

**Comment by maestromac** [comment]
Happy to help!
