### ISSUE TITLE
Buttons in some liquid tags have inconsistent styling and occasionally look broken

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#17564]
**Describe the bug**

Some liquid tag buttons have custom styling that causes:
1. Inconsistency with other buttons we have...
2. Contrast issue (related: https://github.com/forem/forem/issues/17389 )

**To Reproduce**

See https://github.com/forem/forem/issues/17389

**Expected behavior**

Use the buttons we have defined in Crayons (probably the [Secondary](https://storybook.forem.com/?path=/story/components-buttons--secondary) one) and do not overwrite it with user's brand colors.

**Screenshots**

See https://github.com/forem/forem/issues/17389

**Additional context**

I think [the solution I suggested](https://github.com/forem/forem/issues/17389#issuecomment-1114579068) would at least partially help..

**Comment by msarit** [comment]
@ludwiczakpawel @amywtlin

Hello folks! 👋🏾 

So I started working on this issue, and my observations led me to create a short walkthrough video, to ask your thoughts on how to proceed with this bug: https://www.loom.com/share/023addfc5a754bcaa59fc258aeb08a47.

---

TL;DW
1. The follow-button for the User Embed has default styling, but it is overridden by the inline styling present in the embed's file.
2. When I removed this styling override, the default styling emerged: a light-green button with white text (see image below).

![Screen Shot 2022-05-05 at 11 22 04 AM](https://user-images.githubusercontent.com/32520970/166957114-a564b2d9-a499-438e-a4b5-bf9b7aaa7ec5.png)

3. This green-button styling appears to be the default for the follow-buttons on User, Organization and Tag embeds. **QUESTION: Do we want to leave this green-button styling as is?**
4. Pawel had suggested using generic crayons-btn--secondary styling for the User Embed follow-button. I made this work by deleting the green-button styling from the User Embed css, then passing the appropriate class into the follow-button helper. **QUESTION: Do we want to make just the User Embed follow-button secondary, or also the Organization and Tag embeds as well?**

**Comment by ludwiczakpawel** [comment]
Answer for 4. (which I believe makes Question 3. irrelevant):
We want all these follow buttons (User, Tag, Org) to use `crayons-btn--secondary` styling.

---

Btw. Am I right saying that if you change `_liquid.html.erb` code it will only affect FUTURE embeds and not already existing ones? Unless you RESAVE all of the posts in the database (which gonna be resources-expensive). That's what I meant [saying](https://github.com/forem/forem/issues/17389#issuecomment-1114579068) it's probably more tricky :)

**Comment by msarit** [comment]
> Am I right saying that if you change _liquid.html.erb code it will only affect FUTURE embeds and not already existing ones?

Yes you are right. Only if the previous embeds are re-saved will the updated styling be reflected.
