### ISSUE TITLE
[bug] - biography for user

### ISSUE THREAD

**Issue by silviuvld** [forem/forem#17644]
**Describe the bug**

When you want to update your bio and put a text that have 199 characters, you will give an error that said that is too long, but the maximum is 200 characters.

**To Reproduce**

1. Go to 'dev.to' 
2. If you re not logged in, log in with your credentials 
3. Click on your 'avatar' ( up-right ) 
 4. Click on 'settings' 
 5. Scroll down to 'Bio' 
 6. Edit your 'Bio' and put a text that have '199/200' characters 
 7. Scroll down and click on 'Save profile information' 
 8. See error 

**Expected behavior**

I'm expected to can put a text in bio that have 199 characters, 200 being the maximum.

![image](https://user-images.githubusercontent.com/102789727/168007518-c06af679-0d56-4e73-9f61-c9ca4f804f94.png)

Like you see my bio have 199/200
I press the save button and I get this error:

![image](https://user-images.githubusercontent.com/102789727/168007598-f32247a6-9a6d-49e0-8932-faf4e87ae814.png)

**Desktop (please complete the following information):**

- OS, version: macOS, M1
- Browser, version: Chrome , last version

**Smartphone (please complete the following information):**

- Device: -
- OS, version: -
- Browser, version: -

**Additional context**

**Comment by aitchiss** [comment]
I did a bit of investigation here, and it seems the issue occurs when using new lines. If you enter 200 characters of text with no new lines, everything works as expected. But if you delete a character and instead enter a new line, then you see the error message described above.

My suspicion is that the backend is validating `\n` as two characters, whereas the frontend treats it (as expected) as one

**Comment by azmy60** [comment]
I will take a look at this and keep this thread updated.

**Comment by gajananpp** [comment]
@aitchiss can i work on this ?

**Comment by aitchiss** [comment]
Sure @gajananpp! I've assigned to you 🙂

**Comment by jeremyf** [comment]
@gajananpp any updates?  I'm checking if this is something to unassign.  I'll schedule checking back on July 17th and if I hear nothing, I'll unassign the work.
