### ISSUE TITLE
Write Endpoint for unpublish all posts and comments

### ISSUE THREAD

**Issue by JennieOcken** [forem/forem#17658]
DoD:

AuthZ
AuthN
Audit Trail logging

Documentation

**Comment by mirie** [comment]
@fdocr is this issue done? I'm not sure how the auto closing (the issue is closed when the PR is merged) works in Github projects -- I'm not sure looking at your project board if there's additional steps after the issue itself is closed.

**Comment by fdocr** [comment]
Yes @mirie, when a PR has text in the description that reads _"closes #<issue_number>"_ GitHub will automatically close the corresponding issue. GitHub project will take closed issues and move them automatically to Done automatically.

<img width="892" alt="Screen Shot 2022-07-14 at 13 54 26" src="https://user-images.githubusercontent.com/6045239/179072655-62b5ff38-5d49-4d69-a5bf-3947ea2d85c6.png">

Now that these new endpoints are implemented we can start testing them on production. I'm planning to do this on [canary2.forem.lol](https://canary1.forem.lol/) or [BHC](https://community.benhalpern.com/), which are test environments but are configured as production.
