### ISSUE TITLE
SPIKE: Monitoring and Rate Limiting for API usage - what exists today

### ISSUE THREAD

**Issue by JennieOcken** [forem/forem#17651]

**Comment by fdocr** [comment]
Our existing `Rack::Attack` throttling is protecting API `read` endpoints at a limit of 3 per second and `write` endpoints at a limit of 1 per second ([reference here](https://github.com/forem/forem/blob/main/config/initializers/rack/attack.rb#L11-L27)).

We also have Datadog monitoring that allows us to monitor each endpoint performance, while Honeybadger should help for Exception handling.
