### ISSUE TITLE
Odd embed behavior for https://guides.rubyonrails.org/routing.html

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#17679]
On DEV.to, when I want to embed the https://guides.rubyonrails.org/routing.html (e.g. `{% embed https://guides.rubyonrails.org/routing.html %}`), the resolved URL is `https://dev.to/guides.rubyonrails.org`.  I would have expected  it to resolve to `https://dev.to/guides.rubyonrails.org`

**Comment by W3NDO** [comment]
What would be a solution to this?

**Comment by jeremyf** [comment]
> What would be a solution to this?

I pushed up #17680
