### ISSUE TITLE
Don't convert SVGs with Cloudinary

### ISSUE THREAD

**Issue by qm3ster** [forem/forem#1767]
**Is your feature request related to a problem? Please describe.**
I used a vector svg image as a `cover_image` of a post today.
It got "optimized" by Cloudinary, and served with automatic format (`f_auto`).
This resulted in not only making it a 6.2KB `webp` (and even larger `png`) but also [making it blurry](https://res.cloudinary.com/practicaldev/image/fetch/s--usNnnoz8--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://svgshare.com/i/B6d.svg).
The [original image](https://svgshare.com/i/B6d.svg) was 781 bytes on the wire.

**Describe the solution you'd like**
If possible, we'd serve sanitized svgs.

**Describe alternatives you've considered**
I suspect if I convert it to png myself it might be less blurry, I may try that later.
(Also with white background instead of transparent, since that causes a gray background on DEV.to)

**Comment by qm3ster** [comment]
Nah, manually converting isn't distinguishably better than just setting `background-color:#fff`.
Actual `background-color:#fff;background-image:url(https://svgshare.com/i/B6d.svg)` is excellent  though, the left text is much more readable.

Offtopic, but the default background, `#dddddd` can be written as `#ddd` :rofl:

**Comment by maestromac** [comment]
Thank you for reporting this @qm3ster

**Comment by Zhao-Andy** [comment]
I think the main issue with this is the sanitization process. An SVG being processed by Cloudinary acts as sanitizer itself.

Any ideas on how to sanitize an SVG @qm3ster?

**Comment by qm3ster** [comment]
@Zhao-Andy I did some research now.
I already knew there are significant differences in svg behavior when used as `<img src=` or a css property vs embedding them in the document, but it seems that it goes further than I thought:
[SVG as an Image - MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image)
As such, it seems they are inert when used as images, not just in terms of JS but even in terms of making network requests.
However, this makes it act as an image in the page, and adds such options as "Open image in new tab" in the context menu.
If you load the image in the root of a tab, the scripts and requests will execute.
Why is that potentially not a problem? Because if they are served from an external domain, it doesn't give any more access and control over DEV.to user data than following any other link to a malicious page.

However, if we proxy them to improve performance / enforce our own caching, someone going directly to the URL would be catastrophic.
The reasonable mitigation would consist of two redundant parts:
1.  Making sure to have the `Content-Disposition` header set to `attachment`, this way if someone opens it in the browser it won't render but bring up a save file dialog instead. Once they save it locally, we don't care if they open it, because `file://` urls are very sandboxed in general, and give no access to our domain in particular.
2. Sanitizing the files on the saving-to-cache stage, using for example [Loofah](https://github.com/flavorjones/loofah) (I picked this one because the `language-color` bar on their repo is similar to this one, so it is probably the language used here :v)

Each of those alone should make it safe to navigate to the `https://dev.to/**/*.svg` url with a browser, but it's better to use both in case either the browser disrespects the header/sending the header breaks or there's a bug/misconfiguration in the sanitizer.

**Comment by qm3ster** [comment]
a comment

**Comment by johannesvollmer** [comment]
I'd like to add that __I would love to see real SVG images in the articles themselves too, not just in the banner__. Currently I am converting schematics and graphics to JPG, which is certainly not made to display vector graphics. Storing SVG images could also save dev.to some bandwidth. Of course, sanitization will have to be taken care of, I guess.

**Comment by ludwiczakpawel** [comment]
Closing, since we no longer support SVGs for `cover_photo`.
