### ISSUE TITLE
account.forem.com is marked as phishing by Microsoft

### ISSUE THREAD

**Issue by MichalBryxi** [forem/forem#17671]
**Describe the bug**

account.forem.com is marked as phishing by Microsoft Edge.

**To Reproduce**

1. GOTO: https://account.forem.com/ in MS EDGE
2. See that the page is marked as:

> This site has been reported as unsafe
> Hosted by account.forem.com
> Microsoft recommends you don't continue to this site. It has been reported to Microsoft for containing phishing threats which may try to steal personal or financial information.

**Expected behavior**

Site is not marked as phishing.

**Screenshots**

<img width="952" alt="Screenshot 2022-05-13 at 14 51 52" src="https://user-images.githubusercontent.com/847473/168287746-d59fbd8c-c0fa-4ad7-92b9-550d03d3dc11.png">

**Desktop (please complete the following information):**

- OS, version: OSX Monterey, 12.3.1 (21E258)
- Browser, version: Microsoft Edge, Version 101.0.1210.39 (Official build) (x86_64)

**Comment by joshpuetz** [comment]
Thanks for bringing this to our attention @MichalBryxi! Please feel free to report the site as safe in your browser

**Comment by fdocr** [comment]
I was able to reproduce (only came up after email confirmation redirect after registration) and requested the correction in behalf of us (Forem) to the Microsoft Team. I'm unsure about their response times but will be keeping an eye out and will drop an update when we hear back from them.

**Comment by mirie** [comment]
Checked and no longer an issue
