### ISSUE TITLE
`Trusted user` role can't be really removed

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17689]
# **Describe the bug**

When an admin removes the role of `Trusted user`, it didn't really remove it and the privileges that come with it. The observed, unexpected behaviors include: 
1. The green `Trusted` status wasn't gone
2. The user can still see the shield icon on a post, and access the mod panel

# **To Reproduce**

You need two user accounts with different roles: one with admin role and another with none to start with.
1. As an admin, go to /admin/members and grant someone a `Trusted user` role
2. Remove the role from the said user.
3. As the said user, you should be able to 
   1. see the green `Trusted` status is still there, even after refreshed (see screenshot; the green label is present, with no roles assigned)
   ![Screen Shot 2022-05-16 at 4 26 49 PM](https://user-images.githubusercontent.com/11730007/168550972-e967ef25-2b99-4bb4-bb8e-7720d0147c55.png)
   1. navigate to any post, you should be able to see the shield icon for moderation still visible 
   ![Screen Shot 2022-05-16 at 4 33 13 PM](https://user-images.githubusercontent.com/11730007/168552140-325686c4-4e6c-4744-8972-4dae0a62bccd.png)
   https://www.loom.com/share/f2b658a1498a44ac9809712537c34cc8

# **Expected behavior**

All privileges come with the `Trusted user` role should be revoked once the role has been removed from a user. In the observed unexpected behaviors, the expected behaviors are:
1. The green `Trusted` status should be gone
2. The user should not be able to see the shield icon on a post and lose access the mod panel

# **Additional context**

[Slack thread 1](https://forem-team.slack.com/archives/C7GE84DEJ/p1650354587472149); [Slack thread 2](https://forem-team.slack.com/archives/C7GE84DEJ/p1652161245948819)

**Comment by amywtlin** [comment]
cc @Ridhwana Here's the bug issue for trusted users - please feel free to put it on appropriate boards!

**Comment by jeremyf** [comment]
We are caching the "trusted?" query for 200 hours, with no test on `user.updated_at` to help expire the cache earlier.

https://github.com/forem/forem/blob/8a4e1ebeba92c29dbf7cf2bf292c5516cd29b687/app/policies/authorizer.rb#L136-L142
