### ISSUE TITLE
NameError: undefined local variable or method `unpublish_listing`

### ISSUE THREAD

**Issue by jeremyf** [forem/forem#17683]
The following code calls methods that don't exist in the controller:

https://github.com/forem/forem/blob/8a4e1ebeba92c29dbf7cf2bf292c5516cd29b687/app/controllers/admin/listings_controller.rb#L51-L54

This is likely related to work done in forem/forem#16221

Referenced in https://app.honeybadger.io/projects/66984/faults83837532

There exists a [app/controllers/concerns/listings_toolkit.rb](https://github.com/forem/forem/blob/8a4e1ebeba92c29dbf7cf2bf292c5516cd29b687/app/controllers/concerns/listings_toolkit.rb) which used to be mixed into the Admin::ListingsController but is no longer.  It is still mixed into the [app/controllers/listings_controller.rb](https://github.com/forem/forem/blob/8a4e1ebeba92c29dbf7cf2bf292c5516cd29b687/app/controllers/listings_controller.rb)

The impact appears limited to an admin; they are not able to unpublish a listing.

**Comment by MdSahil-oss** [comment]
@jeremyf  I would like to work on this issue

**Comment by jeremyf** [comment]
Thank you for the offer, let me share what I'm thinking.

I have raised this to @amywtlin to determine our internal priority; my suspicion is that it isn't too urgent.  If it is, this is something that may need to have a core member dive into.  So consider that you may be working on it, and someone may come along asking for status and even looking to close it out.  (I don't know what that would look like but I suspect it could be a pairing session)

With all of that, I'd love to here what kind of time frame you're thinking in regards to working on it?

This will definitely involve some git history sleuthing and ideally some tests (which are obviously missing).  In my quick examination, you'll also want to look at the related `publish_listing`.  I hope I put forward enough clues to adequately follow.

With all of that, are you (@MdSahil-oss) still in?  If you say "yes, I'll assign the ticket to you and me".

**Comment by MdSahil-oss** [comment]
yes, I'm in.

**Comment by MdSahil-oss** [comment]
@jeremyf I have attached a PR, check that and let me know if there is any error.
