### ISSUE TITLE
Remove unused brand color field

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17686]
# Background
We have 2 brand color fields in `/settings/profile` but we are using only one which is causing confusion. See discussion in https://github.com/forem/forem/discussions/17163
![image](https://user-images.githubusercontent.com/7629808/162216205-62f4dcc8-0b70-467b-8882-acc44dc40631.png)

# Definition of done
There should be only one brand color left. Our backend should use that color for the background color of the upper section of a user's profile. Such as the screenshot shown here:
![image](https://user-images.githubusercontent.com/11730007/168536138-1d626330-9c7a-4adb-8f05-d220d9c24db6.png)

# To do 

- [ ] 1. Remove `Brand color 2` 
- [ ] 2. Rename `Brand color 1` to `Brand color`

**Comment by amywtlin** [comment]
@ludwiczakpawel I created an issue for this discussion: https://github.com/forem/forem/discussions/17163 Does it look fine to you?

**Comment by ludwiczakpawel** [comment]
Yeap, this description seems to be accurate. Do we want to include/mention color contrast verification that should happen there too (similarly to how we do that in Admin facing side)?

**Comment by amywtlin** [comment]
For consistency, I think we should, but what is the current behavior when the color doesn't pass the color contrast verification? Do we use some default color code instead?

**Comment by KirtanSoni** [comment]
i can take up this issue

**Comment by jeremyf** [comment]
@KirtanSoni Sorry about the delay in getting to this, but I've assigned this to both you and me so we can both track it.

**Comment by maestromac** [comment]
I'm going to remove the assignment @KirtanSoni but if you would like to pick this up again please let us know!.

**Comment by rt4914** [comment]
From user perspective this issue has been solved and merged. Keeping this issue open because in next PR I will work on database migration to remove `brand_color_2` from database too.

**Comment by mirie** [comment]
Created a new issue for the DB migration task: https://github.com/forem/forem/issues/18434. Closing this
