### ISSUE TITLE
Add a new template to custom pages

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17701]
# Background

Custom pages is a feature that is used quite often by our Creators for various purposes. However, the current templates we offer are not including the nav bar to the left, making it hard to navigate once a member gets on a custom page (see screenshots of examples below). Hence we are adding a new template where the left nav bar is preserved. 

## `contained`
[Example](https://dev.to/discussion-focused-orgs) | [Configure page](https://dev.to/admin/customization/pages/280/edit
)
<img src="https://user-images.githubusercontent.com/11730007/168719515-65ba0c0b-3ce8-4f3a-be70-1ef47838e961.png"  width="400" />

## `full-within-layout`
[Example](https://dev.to/connect) | [Configure page](https://dev.to/admin/customization/pages/241/edit)
<img src="https://user-images.githubusercontent.com/11730007/168719511-43706672-cd91-4353-ab24-756d9cb58e0a.png"  width="400" />

# Definition of done
When this issue is complete, admins should be able to choose this new template when creating a custom page, to provide custom pages that are more easily navigable with the same nav bar to the left.

# Specs
- Name of the new template: `nav-bar-included`
- Design: we are using the same layout as Home feed, but using the content container to fill the width of feed + right-hand rail.
    ![Screen Shot 2022-05-17 at 1 09 09 PM](https://user-images.githubusercontent.com/11730007/168733568-a546af83-f377-45a7-afa7-3878db856bb4.png)

**Comment by amywtlin** [comment]
@ludwiczakpawel as mentioned in DMs - let me know your thoughts on this! If it looks fine, feel free to just assign it back to me.

**Comment by ludwiczakpawel** [comment]
👍 I think this makes sense.

**Comment by mirie** [comment]
@aitchiss assigning this one to you, but if this makes more sense for someone else to work on then please reassign!
