### ISSUE TITLE
Markdown toolbar: Overflow indication for mobile screen

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17714]
The markdown toolbar scrolls horizontally on small screens (e.g. mobile size). How obvious this functionality is depends no the exact size of the mobile screen - e.g. if a button gets 'cut off' in the middle, and therefore shows that it's scrollable.

When we launched the toolbar, several users questioned 'missing' buttons in the mobile viewport, because they weren't aware of the scroll. Therefore we'd like to introduce some UI that makes the "scrollability" (totally a word) a bit more obvious.

There is also the issue that it's possible to trigger the "small" viewport on a mouse-operated screen (e.g. inside the moderator centre iframe, or if the user requires to zoom for accessibility), and without a scroll bar it's not intuitive how to access the scrolling items. See https://github.com/forem/forem/issues/18131 also.

## Solution

Instead of scrolling in smaller screens, we are going to instead toggle how many items appear in the overflow menu. See [the figma designs here](https://www.figma.com/file/PIPeiiVSADmcpCbiZTdJm9/Editor?node-id=2185%3A8563)

**Comment by amywtlin** [comment]
@ludwiczakpawel Any preferences on the design? I have seen the fade effect more, but honestly, having either is good enough for me. If you also don't have a preference, I'll just make a call.

**Comment by mirie** [comment]
@aitchiss Can you confirm if you're looking to wrap this up this week?

**Comment by aitchiss** [comment]
Yep that's my plan @mirie!
