### ISSUE TITLE
Mod Panel Updates: "Feature Post" action

### ISSUE THREAD

**Issue by msarit** [forem/forem#17710]
Regarding the "Feature Post" action in the Mod Panel:

| Mod Role | Admin + Trusted | Tag Mod | Trusted Only
| ----------- | ----------- | ----------- | ----------- |
| Does Not Appear | Move to Post Actions | Does Not Appear | Does Not Appear |

Mockups: https://www.figma.com/file/yhg9HTZDFIeWuvBt9ygrss/Moderation?node-id=597%3A528

[ ] Update Community Moderation guide
[ ] Create ticket to add ModRole flow to postModerationTools cypress spec

**Comment by michael-tharrington** [comment]
Ooo might I have permission to look at that figma file? Interested how this will work in regards to a convo/request I was making earlier today - https://forem-team.slack.com/archives/CFNNH3BFA/p1653055217359409

**Comment by michael-tharrington** [comment]
I think you may be solving the problem I brought up! 🙌
