### ISSUE TITLE
Website lags when I open the sidebar (each one) 

### ISSUE THREAD

**Issue by Jeoxs** [forem/forem#1771]
I recently wrote an article about this particular issue asking people if they had the same problem: https://dev.to/jeoxs/is-it-just-my-phone-or-devto-is-heavy--1h9l

The site starts freezing when I open a sidebar. I have a Samsung Galaxy S5 mini with Android 6.0.1 and latest Chrome and Android web view versions. At first I though it was my phone but others users have confirmed the issue on their devices, too. 

Thank you in advance for your support :)

**Comment by shindakun** [comment]
![devto-lag](https://user-images.githubusercontent.com/319128/52527211-ccca8480-2c79-11e9-8354-fc82d93a77af.gif)

Seems to be something with how the sidebar works.

**Comment by Jeoxs** [comment]
Thank you for the info. On the phone, it doesn't work after some time. it lags more. I have to swipe back and wait some seconds (like 10) in order to close the sidebar.

**Comment by ryan3E0** [comment]
I think this may have something to do with the service worker making a huge amount of requests. On the standard desktop view it only triggers network requests when hovering over a link. Shrinking down the browser then opening the sidebar makes it go out of control.
![image](https://user-images.githubusercontent.com/1578766/52529765-e2659b80-2cc5-11e9-85fd-c34b17e09f61.png)

**Comment by Link2Twenty** [comment]
It gets crazy busy as soon as you open the side panel

![image](https://user-images.githubusercontent.com/3534427/52553705-6316bb80-2ddc-11e9-9784-eda9dc8c847e.png)

**Comment by Link2Twenty** [comment]
I feel like it's this section

https://github.com/thepracticaldev/dev.to/blob/dd32580ab1757edc5f6bef20d6b5f9354edd31e6/app/assets/javascripts/initializers/initScrolling.js.erb#L5-L41

**Comment by Link2Twenty** [comment]
Reference: #1787, #1746

**Comment by maestromac** [comment]
not stale
