### ISSUE TITLE
Minor bugs in PR Template

### ISSUE THREAD

**Issue by rt4914** [forem/forem#17731]
**Describe the bug**

In PR template there are two links at the top which can be improved:
1. https://github.com/forem/forem/blob/main/CONTRIBUTING.md#create-a-pull-request - This link is no longer valid.
2. https://github.com/forem/forem/blob/main/CODE_OF_CONDUCT.md. - This link has a full-stop at the end of the link which can be removed for easy selection if needed.

**To Reproduce**

1. Go to this link - https://github.com/forem/forem/blob/main/.github/PULL_REQUEST_TEMPLATE.md
2. Check the content in edit-mode or in any code-editor
3. Check the above mentioned links.

**Expected behavior**

- This `https://github.com/forem/forem/blob/main/CONTRIBUTING.md#create-a-pull-request` should be updated with correct one.
- For all other links there should not be full-stop at the end for easy access.

**Comment by KirtanSoni** [comment]
can i work on this?

**Comment by KirtanSoni** [comment]
[https://developers.forem.com/contributing-guide/forem#create-a-pull-request](https://developers.forem.com/contributing-guide/forem#create-a-pull-request) 
This is the link that is available currently and,
will replace ~~https://github.com/forem/forem/blob/main/CONTRIBUTING.md#create-a-pull-request~~

**Comment by rt4914** [comment]
Thanks @KirtanSoni . Feel free to create a PR for this issue.

**Comment by Link2Twenty** [comment]
Can this be closed?

**Comment by rt4914** [comment]
This was finished in #17756
