### ISSUE TITLE
Cover images in feed have a grey border

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17730]
I didn't notice this when reviewing the recent PRs around feed cover images, but it became more visible when I saw a post on DEV which had a predominantly white background:

![post from Ben with cover images featuring a mostly white background; a grey border surrounds it](https://user-images.githubusercontent.com/20773163/169538872-a78d9b91-f18e-4f6f-a90d-db634f3c57f1.png)

You can see there's a grey border top/bottom that shouldn't be there, as the cover image should occupy the full area. Hopefully just needs a small CSS tweak somewhere.

**Comment by Link2Twenty** [comment]
This is caused by `object-fit: scale-down;` it's not actually a border but the image has a background colour and that is becoming visible.

https://github.com/forem/forem/blob/dbeb4a5acab200fcde40963868dafab5809f4a98/app/assets/stylesheets/views/article.scss#L30-L37
