### ISSUE TITLE
Give contrast guidance on user profile background/text color

### ISSUE THREAD

**Issue by bigblind** [forem/forem#1774]
**Is your feature request related to a problem? Please describe.**

Looking at [this profile], the contrast for the text on the follow button is quite low. These colors come from the text color and background color settings. Could we give some guidance to users to pick contrasting colors? 

**Describe the solution you'd like**

When the user enters two colors, we measure their [contrast ratio](https://contrast-ratio.com/) and give feedback to the user.

**Describe alternatives you've considered**

We could even disallow combinations under a certain contrast ratio. It might also be useful to just give a preview. While we're at it, why not make these fields `input type=color`?

**Comment by Link2Twenty** [comment]
Reference: #735

**Comment by jessleenyc** [comment]
I'm going to add this to our list of things we hope to accomplish by the end of Q1 because I think it can be tackled while we look into #735.

**Comment by cmgorton** [comment]
Hey! Thanks for opening up this issue. Since this issue is similar to #735 and has become stale I am going to go a head and close it for now.
