### ISSUE TITLE
€ character is removed from the post title

### ISSUE THREAD

**Issue by jnv** [forem/forem#17780]
**Describe the bug**

When creating a post with "€" symbol in the title, the symbol disappears after saving the article.

**To Reproduce**

1. Click "Create Post"
2. Enter the following title: "Test €€€"
3. Click "Save draft"
4. Wait until the page reloads
5. The post title is "Test"

**Expected behavior**

The post title remains unchanged.

**Screenshots**

Entering the title:

![image](https://user-images.githubusercontent.com/616767/170706434-44d847e2-7e4d-4498-a5fa-9958884cbddc.png)

After saving the draft:

![image](https://user-images.githubusercontent.com/616767/170706489-6088314c-ca16-43d5-891f-9d1bd1e9168f.png)

**Desktop (please complete the following information):**

- OS, version: Fedora Linux 36
- Browser, version: Firefox 100.0.2

**Additional context**

I believe this is related to #16787. If Forem (still) uses an allowlist of characters, symbol for EUR is missing in that list. While GBP symbol and various emojis are allowed, EUR seems to be an omission.

**Comment by joaoGabriel55** [comment]
Hello @jnv. I can take a look at it.

**Comment by juliannatetreault** [comment]
Closed via #17790

**Comment by jnv** [comment]
Thank you @joaoGabriel55!
