### ISSUE TITLE
Allow existing V0 endpoints to be access via V1 URIs, require authentication

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#17800]
Existing endpoints, when accessed via `/v1` URIs, should require authentication with a user's API key.

**Keep in mind**: accessing these endpoints via their existing legacy URIs should **not** require authentication (see https://github.com/forem/forem/issues/17819)

**Comment by fdocr** [comment]
This is now possible if `:api_v1` feature flag is enabled and `Accept` header is provided with `application/vnd.forem.api-v1+json`. Ongoing work will wrap up making v1 fully accessible without the feature flag once v1 is ready for production use.
