### ISSUE TITLE
"Comment hidden by author"

### ISSUE THREAD

**Issue by sylwiavargas** [forem/forem#17832]
**Describe the bug**

The UI description of when a comment is hidden by the author of the post reads as if it was hidden by the author of the comment.

At first, I thought I had clicked on my comment by accident but then I realized that the author of the post just hid the comments that he didn't like. Another user reached out to me and said:

> I'd like to say sorry you had to hide your comment on [http://dev.to](https://t.co/vqKtNmzkUb). I have the impression you've done that because you were predicting the thread would degenerate.

Clearly, this phrasing doesn't confuse only me!

**Expected behavior**

You could use the same phrasing as [on the page of the very comment](https://dev.to/sylwiavargas/comment/1p7g5): "Comment hidden by post author" or make it even more specific: "Comment hidden by the original post author"

**Screenshots**

[An example of the confusing phrasing](https://dev.to/afif/a-plagiarism-case-involving-css-tricks-and-smashing-magazine-your-thoughts-22m8):
<img width="717" alt="Comment hidden by author" src="https://user-images.githubusercontent.com/45401242/172206747-e09eefc4-2c8b-4dae-9aad-cb455ac0e1a9.png">

[An example of a better phrasing](https://dev.to/sylwiavargas/comment/1p7g5):
<img width="943" alt="Screen Shot 2022-06-06 at 5 53 17 PM" src="https://user-images.githubusercontent.com/45401242/172207981-b7b59792-73cd-4dda-bb5f-385749269555.png">

**Additional context**

I'm happy to submit a PR for this fix 💕

**Comment by jeremyf** [comment]
@sylwiavargas thank you for this write-up and yes, please submit feel free to submit a PR.  I'll assign this to both you and me so we don't lose track of it.
