### ISSUE TITLE
Wrong title on tag page

### ISSUE THREAD

**Issue by dinozavrix** [forem/forem#17851]
**Describe the bug**

Every tag has _pretty name_, but for _title_ on the tag page used tag name insted of pretty name. So google use this _not pretty_ tag name

**To Reproduce**

_Example 1:_
https://dev.to/t/webdev has name "Web Development" but for title used <title>Webdev - DEV Community</title>

_Example 2:_
https://ux.pub/t/designsystem has name "Дизайн-системы" but for title used <title>Designsystem - UXPUB 🇺🇦</title>

**Expected behavior**

Use for <title/> pretty name instead of tag name

_Example 1:_
for https://dev.to/t/webdev  use <title>Web Development - DEV Community</title>

_Example 2:_
for https://ux.pub/t/designsystem use <title>Дизайн-системы - UXPUB 🇺🇦</title>

This will be very useful for searching site content from google

**Comment by juliannatetreault** [comment]
I've assigned this issue to you, @joaoGabriel55! Please let our team know if you run into any issues. 😊

**Comment by joaoGabriel55** [comment]
@juliannatetreault I am using `<% title(@tag.pretty_name) %>` to set the page title but for some reason, the custom title is joined with the default title. Do you know why this happens?

![image](https://user-images.githubusercontent.com/23138717/173940136-fb31553d-511b-4089-b307-5e41814a8f21.png)

**Comment by joaoGabriel55** [comment]
I found the solution!

**Comment by dinozavrix** [comment]
@joaoGabriel55 thank you a lot!
