### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#17865]
**Describe the bug**
We have an error when we confirm the email address on any Forem.

**To Reproduce**

1. Register to any Forem like [the latest named Tidelift](https://community.tidelift.com/) (with GitHub in my case)
2. Go to your inbox to confirm your address email
3. Click on the link to confirm
4. See the error on the page, "Email was already confirmed, please try signing in"

**Expected behavior**
Have a confirmation message without errors like this when this is the first time I created my account on this Forem.

**Screenshots**
![image](https://user-images.githubusercontent.com/14293805/172708477-61cfc5e3-c2cd-4ac1-b193-93ae897d41a9.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 102

**Comment by fdocr** [comment]
Thank you for the report @thomasbnt!

This is interesting. I'm going to ask other team members to double check, but we should only require email confirmation when registering via email (not with OAuth service providers).

To solve this we need something like `.skip_confirmation!` or include `confirmed_at: Time.current.to_i`, but we do in fact have this in the [Authenticator service object](https://github.com/forem/forem/blob/main/app/services/authentication/authenticator.rb#L55-L62) already, which makes me wonder why this email is even sent in the first place.

**Comment by BobbyMcWho** [comment]
Can confirm I also experienced this.
