### ISSUE TITLE
Change Save button with Bookmark icon

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17880]
We have Save/Bookmark article feature, which adds articles to the Reading List.

Currently, we are using the Save button on the feed-page, and on the Post page, we have the Bookmark icon. So, to keep it consistent, we can change the Save button with the Bookmark icon on feed-page.

**Icons - 24x24px**
[Default State](https://github.com/forem/forem/blob/main/app/assets/images/small-save.svg)
[Filled State](https://github.com/forem/forem/blob/main/app/assets/images/small-save-filled.svg)

![Image](https://user-images.githubusercontent.com/84626054/172992909-e4872e3c-afd8-44c9-84c0-a1adda09902a.png)

**Comment by amywtlin** [comment]
@anujbhavsar96 Thanks for the write-up! 

Can you also specify the image url of the icon and the size of the icon? After we have them we can mark this one up ready for contribution :-)

**Comment by anujbhavsar96** [comment]
Updated the write-up🚀 @amywtlin

**Comment by Link2Twenty** [comment]
If the new button is a filled or not filled icon. Should we set it up like a toggle button?

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#toggle_buttons

**Comment by amywtlin** [comment]
@jeferson-sb It appears that you are working on this issue so I am assigning this to you so others know this one is taken :slightly_smiling_face: 

Next time please leave a comment to let us know you'd like to work on this before you submit a PR.

**Comment by amywtlin** [comment]
@Link2Twenty Bringing your suggestion to the PR to this issue to make sure folks are aware of it!

**Comment by amywtlin** [comment]
@mirie I saw that Suzanne is actively guiding the contributor in a PR (https://github.com/forem/forem/pull/17893) for this issue, so I assigned this issue to Suzanne (and I would to @jeferson-sb, too, but to no avail) and moved this one to `In progress` so it reflects the correct status on the board.

**Comment by mirie** [comment]
Assigning to @maestromac for a final review -- looks like we're almost there to closing this one out
