### ISSUE TITLE
Make comment box in focus when entering by clicking "xxx comments" from home feed

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17883]
# Current behavior & problem
While browsing posts on the feed-page, when the user clicks on the **Add comment** / **3 Comments**, it redirects users to the post-page comment area. 

At that time comment box is not focused, so the user has to click that comment box to start writing the comments. 

# New behavior
Idea is to make that comment box focused when you click **Add comment** / **3 Comments** on feed-page. 
This small interaction will improve the comment writing experience.

I believe we should also include what @aitchiss suggested in the [comment](https://github.com/forem/forem/issues/17883#issuecomment-1155023624) below:

> When we do this, can we please change the story cards (that appear on the various feeds) `aria-label` to make sure the link is accessible as something like "Add a comment to post - ${post_name}", to avoid any confusion for screen reader users 🙂

![Image](https://user-images.githubusercontent.com/84626054/172989905-50b5fff4-e2c3-4c79-b23a-7b2d4df8537d.gif)

**Comment by aitchiss** [comment]
When we do this, can we please change the story cards (that appear on the various feeds) `aria-label` to make sure the link is accessible as something like "Add a comment to post - ${post_name}", to avoid any confusion for screen reader users 🙂

**Comment by amywtlin** [comment]
@aitchiss Included your accessibility improvement recommendation in the body!

**Comment by amywtlin** [comment]
Hi @jhonatan-kmt - just realized you submitted a PR to this. Thank you! I have flagged your PRs for our team to review.

Next time please make sure you leave a comment on the issue requesting to work on it first, so we can be of help and guide you through it.

**Comment by jhonatan-kmt** [comment]
Hi @amywtlin, I had to open a new PR pointing to the main branch, can you check it?
