### ISSUE TITLE
Add copy/paste images in comment editor

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17881]
📖 As a commenter, when drafting/editing a comment, I can paste an image into a comment I am editing (i.e. where the cursor is focused) using the keyboard shortcut cmd/ctrl+v I copied somewhere else. 

Some additional context which may be helpful:

- We achieve this functionality in the editor with the `pasteImage` Preact hook, and `handleImagePasted` helper
- Comment text areas are _not_ initially rendered in Preact, but once focused, they are replaced by the Preact `CommentTextArea` and this is where we can add the desired funtionality

**Comment by aitchiss** [comment]
Looks good to me - I've added a couple of code pointers too 🙂

**Comment by jhonatan-kmt** [comment]
Hi, I would like to contribute to this
