### ISSUE TITLE
Add drag/drop image uploading function in comment editor

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17882]
📖 As a commenter, when drafting/editing a comment, I can drag & drop an image into a comment I am editing (i.e. where the cursor is focused). The dropped image should be uploaded and inserted for me into the comment without me having to manually format further. 

Some additional context which might be helpful:

- We achieve this functionality in the editor by using the `useDragAndDrop` Preact hook
- Comment text areas are _not_ initially rendered in Preact, but once focused, they are replaced by the Preact `MentionAutocompleteTextArea` using `window.Forem.initializeMentionAutocompleteTextArea`

**Comment by amywtlin** [comment]
@aitchiss And this one, too!

**Comment by aitchiss** [comment]
Looks good! Essentially we just want same behaviour as in the editor 🙂  I've added a couple of bits of context about the code too to get folks started

**Comment by Link2Twenty** [comment]
Don't forget image paste too 😊

**Comment by JakenHerman** [comment]
Need help? 🙋🏻‍♂️

**Comment by aitchiss** [comment]
Hi @JakenHerman, thanks for looking into this one! I've assigned it to you - please don't hesitate to leave a comment here if you need any more context or have any questions ❤️

**Comment by JakenHerman** [comment]
@aitchiss Perfect, thanks!

**Comment by aitchiss** [comment]
Hi @JakenHerman 👋  How is it going with this issue?

**Comment by rt4914** [comment]
> Looks good! Essentially we just want same behaviour as in the editor 🙂 I've added a couple of bits of context about the code too to get folks started

@aitchiss 
@amywtlin 

I am unable to use DragAndDrop in editor for posts. 
Is there some place where I can test this already existing feature?

https://user-images.githubusercontent.com/9396084/183384166-1303e331-b32c-49bd-925f-07d74cca203d.mov

**Comment by aitchiss** [comment]
Hmmm it shoud be working? One thing I will say is that it can be quite slow, and there is no loading state - is it possible it popped up after a longer wait? e.g.:

https://user-images.githubusercontent.com/20773163/183385659-48c12317-2737-422c-984e-352c2d9b0042.mp4

**Comment by Link2Twenty** [comment]
Also worth looking the console just in case the upload failed. In the live version if you upload an invalid file type you get a 422 though you're not told as a user.

**Comment by rt4914** [comment]
@aitchiss For live version it worked correctly with small file but for local environment it gave `Unexpected end of JSON input` error.

**Comment by aitchiss** [comment]
> @aitchiss For live version it worked correctly with small file but for local environment it gave `Unexpected end of JSON input` error.

What happens if you upload the same image via the image upload button in the toolbar? It sounds like the drag/drop is working correctly, but for some reason the image upload flow isn't working for you - any error in the console/network tab that's more helpful?

**Comment by Link2Twenty** [comment]
`Unexpected end of JSON input` to me sounds like its response is probably html, I'd guess a 404.

**Comment by rt4914** [comment]
@aitchiss @Link2Twenty Thanks. Drag&Drop image upload is working locally too.

**Comment by amywtlin** [comment]
It works - how exciting! I do notice the lack of loading state when a larger image is uploading is a bit confusing, as comments mentioned above. @rt4914 do we have an issue capture this already?

**Comment by rt4914** [comment]
@amywtlin I was unable to find any previous issues and therefore I have filed this issue: https://github.com/forem/forem/issues/18339

Can you have a look at details + tags + projects + milestones ?

**Comment by amywtlin** [comment]
@rt4914 Thanks for flagging, and it's looking good!
