### ISSUE TITLE
Reply button shows even when conversation is locked

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17891]
**Describe the bug**

When a conversation is locked, no new comments or replies are permitted. We hide the main comment box but "reply" buttons on existing comments are still visible, clickable, and the reply form appears. If a user attempts to submit a reply, they see an error and the comment is appropriately not posted, but the form shouldn't be there in the first place.

Given the sensitivity of locked discussion threads, the reply button should not appear to make sure authors have confidence the comments are fully locked.

**To Reproduce**

- Create a post
- Add some comments
- Lock the conversation
- Observe that the reply buttons are still visible

**Expected behavior**

Reply buttons should not be visible

**Screenshots**

Check out [this post on DEV](https://dev.to/alvaromontoro/lgbtq-flags-coded-in-css-3k1k) for an example

**Comment by Link2Twenty** [comment]
The reply buttons are not there for me when I look at the comments on a post but they are there when I look at a comment thread directly.

https://dev.to/alvaromontoro/lgbtq-flags-coded-in-css-3k1k#comments
https://dev.to/taneros/comment/1p92g

**Comment by thejwuscript** [comment]
I would like to work on this issue if it's still available.

**Comment by aitchiss** [comment]
That's great @thejwuscript! I've assigned the issue to you - please do let us know if you have any questions 🙂
