### ISSUE TITLE
Update deprecated Storybook code

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17910]
In the upgrade to storybook 6.5.x there are a few deprecations that we need to non-urgently address. These can be tackled in separate PRs depending how large the scope is:

- [x] [Importing from '@storybook/addon-docs/blocks' is deprecated, import directly from '@storybook/addon-docs' instead](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports) (finished in #18559)
- [x] [CSF .story annotations deprecated; annotate story functions directly](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#hoisted-csf-annotations)
- [x] ['control.options' is deprecated and will be removed in Storybook 7.0. Define 'options' directly on the argType instead, and use 'control.labels' for custom labels.](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-controloptions) - No usage of `control.options` found in code

These tasks are taken directly from warning output running `yarn storybook`, and may be added to as further storybook packages are bumped

**Comment by Rafi993** [comment]
I have been busy for a while and have not worked on this issue. I am removing myself from this issue so that others could take it up.

**Comment by noviicee** [comment]
I can take this!

**Comment by ANURAG-PATHAK** [comment]
please assign this issue to me i want to work on it thank you

**Comment by rt4914** [comment]
Closing this now as two issues are solved and third one is not applicable for our code anymore.
