### ISSUE TITLE
honeybadger error 429 in console

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#17941]
**Describe the bug**
When I have the console open on dev.to I see an error about api.honeybadger.io every time I do, seemingly, anything

```
POST https://api.honeybadger.io/v1/notices/js 429
[Honeybadger] Error report failed: unknown response from server. code=429
```

**To Reproduce**
1. open the console
2. do something
3. see the errors

**Expected behavior**
the api shouldn't be firing quite to often.

**Screenshots**
![errors](https://user-images.githubusercontent.com/3534427/174064917-0d403ddd-0d29-4c10-989a-77566eacfeb7.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 102

**Additional context**
I see this issue was raised over a year ago and closed as fixed I'm not sure if it's the same route cause but I guess that's somewhere to start.

**Comment by jeremyf** [comment]
@Link2Twenty could you provide a URL to one of the page's that's causing this issue?  I have not been able to duplicate this error, so am looking for more concrete guidance.  Also, if you happen to know the issue # that says this was fixed, that too would be a great help.

**Comment by Link2Twenty** [comment]
It's not doing it now, maybe it was a temporary issue.

**Comment by jeremyf** [comment]
@Link2Twenty I've informed our DevOps team of this error; mostly to provide a data point if there was something else.

Again, thank you for reporting the issue.
