### ISSUE TITLE
Change all tooltip texts on heart/like reactions to `like`

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17967]
## Context

Right now, we have different SVG title texts on heart/like reactions: 

1. Heart reaction on a post: `Heart`
   ![Image](https://user-images.githubusercontent.com/11730007/174953337-29caa16a-d37f-42c9-9dc9-abcf33b484c7.png)
1. Like reaction on a comment, on post view & in notifications: `heart`
    ![Image](https://user-images.githubusercontent.com/11730007/174953251-f3dc8e4c-fd52-4c75-892c-5554c963607d.png)
1. The notifications when someone liked your post or comment: `Like`
   ![Image](https://user-images.githubusercontent.com/11730007/174954054-8d566a31-a82a-452a-af35-ec29c00d71b5.png)

## To do

1. For consistency, we are changing all of them to `Like`
2. We are currently relying on SVG `<title>` but we'd like to instead use crayons buttons with tooltips so that this is styled nicer. [See an example of our "button with tooltip" design system component here](https://storybook.forem.com/?path=/story/components-buttons--with-tooltip).

Please note that the accessible name of the button should not change as a result of this work.

**Comment by amywtlin** [comment]
@aitchiss Please feel free to add code instructions in the body!

**Comment by amywtlin** [comment]
Hi @jhonatan-kmt - just realized you submitted a PR to this one, too. Thanks again! Also flagged your PR for our team to review.

Next time please make sure you leave a comment on the issue requesting to work on it first, so we can be of help and guide you through it.

**Comment by jhonatan-kmt** [comment]
Hi @amywtlin, I had to open a new PR pointing to the main branch, can you check it?
