### ISSUE TITLE
Missing details on setting up Google reCAPTCHA

### ISSUE THREAD

**Issue by logankilpatrick** [forem/forem#17961]
**Describe the bug**

This page: https://admin.forem.com/docs/advanced-customization/config/google-recaptcha says to "Please add them to your Forem's config section in the Email section of [Config > Authentication](https://admin.forem.com/docs/advanced-customization/config/authentication)." but it is not clear what this means. There is no email section, there's an "Email address" section. Is that what is meant? 

**To Reproduce**

Go to https://admin.forem.com/docs/advanced-customization/config/google-recaptcha

**Comment by Zhao-Andy** [comment]
Hey @logankilpatrick, thanks for raising this! In general our documentation is a bit out of date. I've updated it since it's a small issue here, and is a bit confusing to find out how to add the keys appropriately.
