### ISSUE TITLE
Quotations break response templates

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#17972]
**Describe the bug**

When creating a comment template (canned response), anything you put after a quotation disappears from the message. 

Note: response templates can be created by individuals from `/settings/extensions` and created by admin (most often for mods) from `/admin/advanced/response_templates`

**To Reproduce**

1. Go to '/settings/extensions`
2. Create a response template that uses quotations
3. Go use it in the comments section of a test post
4. See missing content

**Expected behavior**

Quotations should be usable in response templates without issues.

**Videos**

https://www.loom.com/share/338ebdf33f03491997319b577ca8432c

**Additional context**

This bug was first brought to my attention by an admin of one of our Forem communities.

**Comment by michael-tharrington** [comment]
Realize I was a tad late on this one, but I think I got ya via DMs in Slack. Just gonna drop my explanation here for others just in case.

If you write a response template and use quotations, then all of the words after you use your first quotation mark (`"`) do not appear in the template.

So, if my response template is:

> The terms state:
> 
> “stop that mess”
> 
>
> and we hope that you all will stop that mess.

Then all that would appear in my response template is:

> The terms state:

**Comment by jeremyf** [comment]
Reading Notes: I did some investigation, and I believe that we're encountering unescaped characters in JS data. 

I believe we'll need to change the following:

https://github.com/forem/forem/blob/5579f3360c02a0adddeeeee22e89fcfb5e70df87/app/javascript/responseTemplates/responseTemplates.js#L40

**Comment by jeremyf** [comment]
Reading notes: I think a helper function akin to what was added in #16067 would make sense.
