### ISSUE TITLE
Multiple Users Report Not Receiving Confirmation Email Upon Signup

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#18027]
**Describe the bug**

Several new users have reported that they didn't receive the confirmation email when trying to sign up to DEV.

**Expected behavior**

Upon signing up to DEV, you should receive a confirmation email with a link to confirm your account.

**Screenshots**

![Screen Shot 2022-07-01 at 10 19 33 AM](https://user-images.githubusercontent.com/16007075/176912620-f66df144-1997-4594-b886-c16f1ff80d4e.png)

![Screen Shot 2022-07-01 at 10 19 43 AM](https://user-images.githubusercontent.com/16007075/176912766-ff72e1bf-61c6-4f22-a439-c4a104d93e4e.png)

![Screen Shot 2022-07-01 at 10 19 52 AM](https://user-images.githubusercontent.com/16007075/176912897-1bafcd3f-97df-43e4-8936-b934a7430f5d.png)

**Additional context**

If you need to know who was affected here, I've created a private issue to list the users who experienced this issue - https://github.com/forem/pii/issues/116.

**Comment by fdocr** [comment]
We shipped an update to our authentication logic and ran a fix on the affected users. 

@michael-tharrington could you please email those that wrote in with the report mentioning their accounts should be confirmed and working as expected? 

If they don't have any issues with this we can consider this problem solved IMO, although we must tackle another related issue separately regarding a subset of accounts that used Twitter for sign up.

**Comment by michael-tharrington** [comment]
Woohooo! Good deal. 🙌

I chatted with @maestromac about this earlier and he gave me a heads up that y'all had grouped on this and ya figured it out. Awesome sauce!

I can confirm that I've hit everyone back with the following message:

> Hey there,
> 
> We realized that the reason you didn’t receive our confirmation email is related to your settings in Twitter — it appears that your Twitter account is set such that your email is not shared with us even though you joined DEV via OAuth with Twitter.
>
> We need to look into the underlying issue more thoroughly to prevent this from happening in the future, but for now, we’ve gone ahead and confirmed your account on your behalf so that you may access your account.
>
> Please let us know if you have any issues and we’ll be happy to look into things further!
>
> Sincerely,
> DEV Team
