### ISSUE TITLE
Open in Gitpod icon still rendering in old color

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#18033]
**Describe the bug**

We should update the icon for "Open in Gitpod"

**Expected behavior**

This icon should be orange and white

**Screenshots**

![Screen Shot 2022-07-03 at 8 51 16 AM](https://user-images.githubusercontent.com/16007075/177040577-4d15abdf-5ba2-42f8-84ab-894e889977cf.png)

**Additional context**

A trusted user flagged this to us.

**Comment by ageddesi** [comment]
I would like to take a look at this however, how do you get the app to show this?

**Comment by mirie** [comment]
@michael-tharrington where did you see this? On https://developers.forem.com/?
