### ISSUE TITLE
Comment toolbar overflow and tooltip

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#18119]
**Describe the bug**
I noticed the comment toolbar is always scrollable (vertically), I did a little investigation and discovered the tooltip appears in the space that can be scrolled into.

**To Reproduce**
1. Go to a comment
2. Start writing a new one
3. Scroll down on toolbar
4. See issue

**Expected behaviour**
Tooltips should appear outside of the parent container, maybe using a position fixed portal?

**Screenshots**
![toolbar overflowing](https://user-images.githubusercontent.com/3534427/179007469-5ba244af-429c-45ea-9ca4-3c3a8a3b2d5c.gif)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome

**Smartphone (please complete the following information):**
N/A

**Additional context**
Here is airbnb's implementation for... Inspiration.
https://github.com/airbnb/visx/tree/master/packages/visx-tooltip

Here is the code that makes the tooltip
https://github.com/forem/forem/blob/878c27f9b03939e74b1094256379e2a821efeb82/app/javascript/crayons/Buttons/Button.jsx#L58-L67

**Comment by aitchiss** [comment]
Hey @Link2Twenty thank you for logging this bug! The fix was recently merged and should be live soon 🙏  https://github.com/forem/forem/pull/18113
