### ISSUE TITLE
Document new APIs

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#18122]
Endpoints to document:

- [x] /api/articles/:id/unpublish
- [x] /api/users/:id/unpublish
- [x] /api/users/:id/suspend

**Comment by mirie** [comment]
@joshpuetz Who's best to QA this (if needed)?

**Comment by joshpuetz** [comment]
That would be @fdocr on the associated PR: https://github.com/forem/forem/pull/18187

**Comment by fdocr** [comment]
Whoops, this one slipped through my reviews last week. Just left a comment/question there but otherwise LGTM 🙌🏼
