### ISSUE TITLE
Mod panel and markdown toolbar in comments

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#18131]
**Describe the bug**

**To Reproduce**

1. Go to [/mod panel](https://dev.to/mod)
2. Click on any post
3. Scroll down to comments
4. See the problem

**Expected behavior**
Have a problem on /mod with the **markdown toolbar**.

**Screenshots**

![Example of the problem](https://i.thomasbnt.dev/i/fnrj3.gif) 

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 103.0.5060

**Additional context**

Good weekend !

**Comment by Link2Twenty** [comment]
As a quick "fix" you can hold shift and use your scroll where to move along the bar.

**Comment by aitchiss** [comment]
Thanks for flagging this up! Yes it seems that rendering it inside the iframe reduces the container enough to trigger the mobile/horizontal scrolling layout 🤔 

I'll definitely look into it!

**Comment by aitchiss** [comment]
Adding the `needs product` tag as @anujbhavsar96 and I have been chatting about solutions that would also resolve https://github.com/forem/forem/issues/17714

**Comment by Link2Twenty** [comment]
A possible solution, I thought about, would be to move all off screen buttons into the ellipse menu this would require some js to run a render time and a resize event listener.

**Comment by aitchiss** [comment]
That's exactly what we've decided to do @Link2Twenty 😄 This issue will be addressed alongside https://github.com/forem/forem/issues/17714
