### ISSUE TITLE
When adding OAuth, the UI acts screwy

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#18184]
**Describe the bug**

When adding a new OAuth method to my DEV account, instead of getting a success message that is consistent with the UI when removing an OAuth account, I get sent to this page https://dev.to/new?i=i&signin=true which looks broken.

**Expected behavior**

When I successfully add OAuth to my account I expect to see a message like:

> Your X account was successfully added.

**Videos**

https://www.loom.com/share/26a57c6ec7244b3ebe6394c95b3805f9

**Comment by mirie** [comment]
@fdocr not sure with the OAuth upgrade this will go away, so assigning this to you for another look.
