### ISSUE TITLE
Replace webpacker gem with jsbundling-rails

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18189]
Due to the [webpacker gem](https://github.com/rails/webpacker) being deprecated we should replace it with [jsbundling-rails](https://github.com/rails/jsbundling-rails) instead.

We can continue to use webpacker as the bundler for our code, but we should ensure its tooling (i.e. `webpacker-dev-server`) are up-to-date.

**Comment by mirie** [comment]
@fdocr I remember you brought this up to me last week -- is this something you have bandwidth to tackle once you wrap up negative behavior API work?

**Comment by fdocr** [comment]
Sure, I can timebox this to one day worth of work and see how far that gets me. The problem with this upgrade is that I don't know the type of errors I'll run into. Hopefully none, or easy to fix errors that can be solved within that timeframe, but I don't want to be overly optimistic when it comes to refactoring frontend tooling 😅  so I may end up getting stuck at some point along the upgrade.

I'll put this on my todo list after those other priorities are out of the way if that sounds alright.

**Comment by mirie** [comment]
@fdocr Are you looking to wrap this up today or do we have to return this to a paused state to pick up later?

**Comment by fdocr** [comment]
@mirie I do think it's best to return to a paused state. I managed to get some good progress with this (exploration + getting the upgrade to work partially in development) but the migration of all our webpack settings is complex and I wasn't able to wrap this up completely. We're on Webpack v5 (not lagging behind) so it's not critical that we immediately upgrade our current setup IMO

**Comment by mirie** [comment]
@lboogie04 would it be beneficial to get some initial feedback on a draft PR from the team?

**Comment by mirie** [comment]
We are deprioritizing this for now again because we need to move everything over to webpacker first. We might even want to consider using es-build instead of jsbundling-rails

**Comment by mirie** [comment]
This is superseded by [Introduce JSBundling with ESBuild#19335](https://github.com/forem/forem/issues/19335)
