### ISSUE TITLE
Marketing URL for pypi/importlib-resources is a 404

### ISSUE THREAD

**Issue by jaraco** [forem/forem#18204]
I recently enrolled importlib-resources in Tidelift, but today I clicked on the Lifted badge to be met with a 404, so I returned to the Marketing task for the project and clicked [the URL there](https://tidelift.com/subscription/pkg/pypi-importlib-resources?utm_source=pypi-importlib-resources&utm_medium=referral&utm_campaign=enterprise) and it's also a 404.

![image](https://user-images.githubusercontent.com/308610/180581057-7b7ed00d-8cf6-4053-9728-3c1b1d99d1cb.png)

I'm unsure the cause. It may be related to the name normalization. The project name is `importlib_resources`, but the "normalized" name is `importlib-resources`. In any case, Tidelift should probably advertise a URL that's reachable.

**Comment by fdocr** [comment]
Hi @jaraco, this seems to be a Tidelift specific issue (https://tidelift.com) that doesn't relate to Forem or Tidelift's community site (https://community.tidelift.com).

Filing an issue on a [Tidelift GitHub org](https://github.com/tidelift) repository, like [tidelift/lifter-stuff](https://github.com/tidelift/lifter-stuff) would likely be better.

I'm closing now, but please feel free to share more details in case I didn't understand your problem correctly.

**Comment by jaraco** [comment]
Oops. I don't know why I filed the bug here. Sorry for the mistake.
