### ISSUE TITLE
Backticks inline produces expansion of template

### ISSUE THREAD

**Issue by dennistobar** [forem/forem#18201]
**Describe the bug**
I started a block code with triple backticks (`) to create a code area. I closed before the new line and appears a template markup.

**To Reproduce**
1. Create a new post
2. Add this text (it's an image because GitHub is using markdown too)

![image](https://user-images.githubusercontent.com/1218182/180456694-552ae0ed-5d9d-47bb-9a68-4491c7132cd7.png)

3. Preview the page

**Expected behavior**

Liquid error or rendered block.

**Screenshots**

![image](https://user-images.githubusercontent.com/1218182/180455975-3c907ecd-d01c-4ffe-8581-3028bc7ce4cf.png)

**Desktop (please complete the following information):**

- OS, version: Fedora 36
- Browser, version: Chrome 103.0.5060.114

**Additional context**

It appears in the comment zone too.

**Comment by fdocr** [comment]
Thank you for the report @dennistobar.

I can replicate this problem but I don't feel like this is an actual bug. Codeblocks in Markdown aren't intended to live inside other codeblocks. This isn't supported here in GitHub or in StackOverflow to name a couple other platforms that support markdown.

If you want triple backticks inside a codeblock [check out this similar question in SO](https://stackoverflow.com/a/67904421/3462026), which comes down to using `<pre><code>test```</code></pre>`. In this case the `pre` and `code` tags will work as the codeblock and the triple backticks won't trip up our Markdown preprocessor.
