### ISSUE TITLE
Editor Toolbar is not sticky for long paragraph post

### ISSUE THREAD

**Issue by f2k2game** [forem/forem#18205]
From recent update, Editor Toolbar is not sticky for long paragraph post, So Its is not user friendly and very hard to create a post.

https://user-images.githubusercontent.com/45148319/180590649-a8d2de65-34a8-4f11-81a8-62d0dc166289.mov

**Comment by Link2Twenty** [comment]
This is caused by the body having the `h-100` class meaning the body ends and so does the sticky element.

https://github.com/forem/forem/blob/75d6e60a957b4296dd9eddbf8f0628781dc5cd56/app/javascript/article-form/components/EditorBody.jsx#L72-L75

**Comment by aitchiss** [comment]
Thanks for logging this bug, and thank you @Link2Twenty for quickly identifying the fix! I'm not totally sure why I slipped that class in there 🙃
