### ISSUE TITLE
Search is missing results

### ISSUE THREAD

**Issue by dylankenneally** [forem/forem#18206]
**Describe the bug**

When I search for the term `Portfolio`, I see that there are articles missing from the results list.

**To Reproduce**

In a browser, on a desktop, do the following:

1. Go to [dev.to](https://dev.to/)
2. Once loaded, enter the term `Portfolio` into the search field in the header and press <kbd>enter</kbd> to start the search
    - Alternatively, visit https://dev.to/search?q=Portfolio instead of steps 1 & 2.
3. Once the results are back, see if you can find the articles I've listed in the _Expected behavior_ section below

See the error here: search results are missing articles that have the search term in their title.

Additional details:

- The case of the search term (`Portfolio` vs `portfolio`) makes no difference
- I am not logged in to [dev.to](https://dev.to/) (shouldn't matter?)

**Expected behavior**

The following articles each have the word `Portfolio` in the title, they should be listed in the search results:

- [How To Build A Great Technical Portfolio](https://dev.to/emmabostian/how-to-build-a-great-technical-portfolio-53bb)
- [10 Minimal Portfolio Examples for Web Developers Who Aren’t Good at Design](https://dev.to/scrimba/10-minimal-portfolio-examples-for-web-developers-who-arent-good-at-design-40gj)
- [15 Creative Web Dev Project Ideas for Your Portfolio (That You Can Finish in a Weekend)](https://dev.to/code_jedi/15-creative-web-dev-project-ideas-for-your-portfolio-that-you-can-finish-in-a-weekend-3bi2)

There are others missing which I've not listed here, but you can see them via a [Google site search](https://www.google.com/search?q=Portfolio+site%3Adev.to).

**Desktop (please complete the following information):**

- macOS, Big Sur, version: 11.6.7 (20G630)
- Chrome, version: 103.0.5060.134 (Official Build) (x86_64)

**Comment by Link2Twenty** [comment]
The search functionality only returns the top 60 results.

**Comment by dylankenneally** [comment]
> The search functionality only returns the top 60 results.

Oh, that seems odd - should that limit exist? We kinda presume search tools will return all the results, paginated or with infinite scroll, or something. 

Do you know if there are plans to support search via [the API](https://developers.forem.com/api) too? 

If it is to stay (not my preference) could the user be made aware? Would also be good to know what 'top' means? Is it the most recently added or edited, or the most viewed, or ...?

**Comment by aitchiss** [comment]
Linking this issue to https://github.com/forem/forem/issues/16297

**Comment by lightalloy** [comment]
I looked into this problem and found out that we have the page number hardcoded here:
https://github.com/forem/forem/blob/cb2214a3ac512bcf35a9fbfc0e8f594eebc4ea2b/app/javascript/packs/searchParams.js#L136

I suppose we should implement something similar to https://github.com/forem/forem/blob/main/app/assets/javascripts/initializers/initScrolling.js , or should  initScrolling.js also apply to search results (but it doesn't)?

**Comment by thomasbnt** [comment]
Hello, I repost here for adding more content to this issue.
About the search bar on DEV directly, it's not working correctly. With the same query on DuckDuckGo🦆, I find great posts on DEV.
![Two search with the same query "upgrade your node js", at the left on DEV, at the right on DuckDuckGo.](https://user-images.githubusercontent.com/14293805/219051922-4b07c41e-c38d-4092-955f-0ec684d0ac24.png)
_Two search with the same query "upgrade your node js", at the left on DEV, at the right on DuckDuckGo._

**Comment by PhilipHow** [comment]
Closing this as dupe to #16297
