### ISSUE TITLE
Reactions API: Read reaction

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#18267]
Reactions API requirements: https://docs.google.com/document/d/1O8YG8moIMUHi5_A-VHVWDmdIaYeHFEpeBEFGRyxc-PQ/edit#bookmark=id.z6jwzd5e5y70

Description: create an endpoint to read a Reaction.

**Authorization**: api key

**Permissions**: limited to users with `Admin` or `Super Admin` role

**Path**: GET `/api/reactions/:id`

**Body params**:
none

**Return body**:
id: integer
reactible_type: enum[article, comment, user]
reactible_id: integer
category: enum[like, readinglist, unicorn, thinking, hands, thumbsup, thumbsdown, vomit]

**Return codes**:
200 OK
401 Unauthorized
403 Forbidden
404 Not Found
429 Too Many Requests

**Comment by jaw6** [comment]
@joshpuetz I'm a little confused on this one? 🤯 I was expecting that an individual reactable would potentially have many, many reactions, and that we'd be more interested in the aggregates than in an individual reaction (how many likes/unicorns/etc?) If we retrieve an individual reaction, wouldn't we want more detail? (`user_id` and/or `username` maybe?) If we're just returning the reactable ident and the category... it just feels to me like this is an unusual endpoint. Can you elaborate a bit on how this endpoint is likely to be used?

**Comment by joshpuetz** [comment]
That's a great point @jaw6, the use case for reading a single reaction is pretty flimsy right now (and we'd discussed that in the requirements doc). We know we'll want to create and delete reactions as part of our spam mitigation tools, but there's not a clear use case for reading a single reaction right now.

I think a strong case could be made for not writing this endpoint right now! @pkfrank: do you have a use case for this endpoint, so can we skip it for now?

**Comment by pkfrank** [comment]
@joshpuetz @jaw6 let's skip it for now 👍

**Comment by Ridhwana** [comment]
Based on the above discussion + [this](https://forem-team.slack.com/archives/C7GE84DEJ/p1661170530296619) conversation and [this one ](
https://forem-team.slack.com/archives/C7GE84DEJ/p1660746217526249) we've decided to not implement the "Read" action. Hence, I'm closing this issue.
