### ISSUE TITLE
Reactions API: Delete reaction

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#18266]
Reactions API requirements: https://docs.google.com/document/d/1O8YG8moIMUHi5_A-VHVWDmdIaYeHFEpeBEFGRyxc-PQ/edit#bookmark=id.z6jwzd5e5y70

Description: create an endpoint for deleting a Reaction.

**Authorization**: api key

**Permissions**: limited to users with `Admin` or `Super Admin` role

**Path**: DELETE `/api/reactions/:id`

**Body params**:
none

**Return body**:
none

**Return codes**:
204 No Content
401 Unauthorized
403 Forbidden
404 Not Found
429 Too Many Requests

**Comment by Ridhwana** [comment]
Based on [this](https://forem-team.slack.com/archives/C7GE84DEJ/p1661170530296619) conversation and [this one ](
https://forem-team.slack.com/archives/C7GE84DEJ/p1660746217526249) we've decided to not implement the "Delete" action, and instead just have the "Create" action change to POST to `/reactions/toggle`. This covers both a create and delete together.
