### ISSUE TITLE
Reactions API: Create reaction

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#18263]
Reactions API requirements: https://docs.google.com/document/d/1O8YG8moIMUHi5_A-VHVWDmdIaYeHFEpeBEFGRyxc-PQ/edit#bookmark=id.z6jwzd5e5y70

Description: create an endpoint for creation Reactions.

**Authorization**: api key

**Permissions**: limited to users with `Admin` or `Super Admin` role

**Path**: POST `/api/reactions/`

**Body params**:
reactible_type: enum[article, comment, user], required
reactible_id: integer, required
category: enum[like, readinglist, unicorn, thinking, hands, thumbsup, thumbsdown, vomit], required

**Return body**:
id: integer
reactible_type: enum[article, comment, user]
reactible_id: integer
category: enum[like, readinglist, unicorn, thinking, hands, thumbsup, thumbsdown, vomit]

**Return codes**:
201 Created
400 BadRequest
401 Unauthorized
403 Forbidden
422 Unprocessable Entity
429 Too Many Requests

**Comment by mirie** [comment]
@jaw6 I noticed that [this](https://github.com/forem/forem/pull/18377) was merged in today --> I think we're done with this issue now right?

**Comment by jaw6** [comment]
@mirie Yep! If we find that there's more that needs doing, we can re-open, or open a new issue.

**Comment by joshpuetz** [comment]
Closing as per https://github.com/forem/forem/issues/18263#issuecomment-1232712693
