### ISSUE TITLE
Public Reactions Score Feed relevancy lever

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#18271]
Description:

Create a new home page feed relevancy level patterned after the `public_reactions` lever for an article (see https://github.com/forem/forem/blob/main/app/models/articles/feeds.rb#L314), but with the following changes:

- Instead of public reactions count, use a `public_reactions_score` calculated as _to be determined_

Related Blazer query: 

https://dev.to/admin/blazer/queries/832-article-reactions-where-points-1

```sql
select * from hypershield.reactions
where category = 'like'
and reactable_type = 'Article'
and points > 1
order by created_at desc
limit 100;
```

**Comment by joshpuetz** [comment]
@pkfrank I'm a little unclear on how exactly this works: can you explain the desired calculation?

**Comment by pkfrank** [comment]
Our current `relevancy_lever(:public_reactions,` looks at `articles.public_reactions_count`

I'd like a new relevancy lever that looks not at `articles.public_reactions_count`, but rather `articles.score` (which we're already generating / storing)

```
select * from hypershield.articles
where score > 10
order by created_at desc
limit 1;
```

[Related Blazer query](https://dev.to/admin/blazer/queries/835-articles-with-score-10)

Note that we also have `comments_score` available here for our other/related relevancy lever.

**Comment by mirie** [comment]
@pkfrank this is QA stage just fyi for your review.
