### ISSUE TITLE
Bookmark button for my own posts is momentarily visible before disappearing

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#18285]
**Describe the bug**

We fairly recently made a change so that an author can't bookmark their own post, and the bookmark button doesn't appear on their feed story cards. The way this is working introduces a small 'flash' of the save button before it disappears from view.

Since it only applies to a user's own post, this is mostly only noticeable if a user views their own profile page. Given this is probably rare, I'm not sure this is a very high priority to fix. 

**To Reproduce**

- Visit your own profile page
- See a flash of content before save buttons disappear
- Refresh the page and see the same again

**Expected behavior**

- No flash of content / the save button is never presented

**Screenshots**

(you might want to slow it down 😄)

https://user-images.githubusercontent.com/20773163/183378631-a92785e5-f7ce-437a-b5a8-dee9960660df.mp4

**Additional context**

Came up during discussions on https://github.com/forem/forem/pull/17893

**Comment by KarthikRaju391** [comment]
Hey @aitchiss, can I have a try at this??

**Comment by KarthikRaju391** [comment]
@benhalpern, I see that this issue is not resolved yet, can I have a look at this?
