### ISSUE TITLE
When hitting the submit button on replying to posts I get an error message:

### ISSUE THREAD

**Issue by aarondreese** [forem/forem#18283]
**Describe the bug**
When  pressing the SUBMIT button on replying to posts I get an error message popup: 
Error Posting Comment
Your comment could not be posted due to a server error [OK]

**To Reproduce**

1. Go to any post
2. Scroll down to the Discussion section
3. enter some text into the response box
4. press [SUBMIT]
5. Error message modal pops up.

**Expected behavior**

I expect the post to be accepted, moderated and presented as part of the conversation.

**Screenshots**

**Desktop (please complete the following information):**
This is happening on both my laptop (Win 11, Chrome 103) and my Phone (Motorola G50, Andriod 12, Chrome 103)
- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device: Motorola G50
- OS, version: Andriod 12
- Browser, version: Chrome 103

**Additional context**

**Comment by Ridhwana** [comment]
Hi @aarondreese, thank you for logging this issue. I'm unable to replicate this issue as of yet. Can you confirm that you're still experiencing it? If you are could you provide more information on the error message please, perhaps a screenshot if possible? Can you also confirm that you're logged in on dev.to when you're trying to comment on the post?

**Comment by Ridhwana** [comment]
@aarondreese can you also provide me with your username on dev.to if you don't mind please? I'd like to double check that all is okay with your account.

**Comment by aarondreese** [comment]
Thanks Ridhwana,


My account ID is: aarone4<https://dev.to/aarone4>

email address is: ***@***.***


Aaron.

________________________________

**Comment by Ridhwana** [comment]
Thanks for the info @aarondreese - I'm looking into this.

**Comment by Ridhwana** [comment]
Hi @aarondreese, thank you for your patience whilst we've investigated this issue ✨. We've looked into your account and the community team at DEV will be reaching out to you via email with further information. In the meantime, since this issue is related specifically to your account, I will be closing this issue on the repo.
