### ISSUE TITLE
Notification count continually going up, not marking as read

### ISSUE THREAD

**Issue by erinb223** [forem/forem#18291]
**Describe the bug**

This bug was surfaced on Twitter by community member [jonrandy](https://dev.to/jonrandy) in the following tweet: https://twitter.com/jonrandy/status/1556675606271574016

The text of the tweet reads "The notification count is continually going up. Nothing is getting marked as read. Seeing the issue both on mobile and desktop."

**Additional context**

This is the extent of the context that I have at this time. If more is needed, Community (@michael-tharrington) may need to reach out via email.

**Comment by jonrandy** [comment]
The issue now appears to have either been resolved or has gone away (it is possible it may have been a bug on Firefox Nightly)
