### ISSUE TITLE
Need loading state/indicator when uploading images in comments editor + post editor

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18339]
Reference: https://github.com/forem/forem/issues/17882#issuecomment-1214634544

When uploading image to post editor or comments editor, if the file is big it does not show any indicator whether its uploading image or not. To fix this we should show some form of loading indicator.

**Suggested Solution** (Needs confirmation from @amywtlin)
As soon as the image is dropped in the editor we can show below text:
`![Uploading <image_name>…]()`
and as soon as the the image gets uploaded it will change to
`![Uploading <image_name>…](https://uploaded_image_path.jpg)`

- In this solution the cursor position is not important as we will need to check for the above pattern and based on that the URL will be placed.
- If user stops after dropping the image, in that case the cursor position will be at `![Uploading <image_name>…](<cursor_position>)` otherwise they can continue typing text.

**Comment by amywtlin** [comment]
@rt4914 The suggested solution looks good to me! I'll add this to the board and into relevant milestone(s).

**Comment by rt4914** [comment]
I am interested in working on this issue. Self- assigning.
