### ISSUE TITLE
Missing translation key on comment page

### ISSUE THREAD

**Issue by ccoVeille** [forem/forem#18332]
**Describe the bug**

Here is what can be seen on comment page

![image](https://user-images.githubusercontent.com/3875889/184209168-c31d9194-6e6a-49e4-9d7a-929f57603a7e.png)

**To Reproduce**

Open this link https://dev.to/ccoveille/comment/20om3 

then click on the "ellipsis icon to open the menu"

Then you can see the missing translation

**Expected behavior**

Get a translated text, and not something that make people think there could be an error.

**Screenshots**

![image](https://user-images.githubusercontent.com/3875889/184209422-5d30b36d-336b-4be8-8474-d97a2a704206.png)

![image](https://user-images.githubusercontent.com/3875889/184209558-4cb50cf0-ad41-476f-9bbd-5c75f9f74e64.png)

**Desktop (please complete the following information):**

- OS, version: Linux, Ubuntu 22.04
- Browser, version: Firefox 103.0.1

**Comment by aitchiss** [comment]
Hi @ccoVeille - thanks for submitting this bug report! I'm not able to reproduce the UI you're seeing, either in a logged in or out state. Sometimes when we make changes to i18n keys there can be a small amount of time while the change propagates through caching etc. I'm wondering if that's what's happened here 🤔  Are you still seeing this 'missing translation' text? Do you still see it if you visit the page in a private browsing window?

**Comment by ccoVeille** [comment]
thanks for the context and info, it's indeed sorted.

here is what I get now

![image](https://user-images.githubusercontent.com/3875889/184386392-969cbc2d-865f-41a1-be52-a790748b07f1.png)
