### ISSUE TITLE
BUG : Comment like count is getting negative that is -1

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [forem/forem#18338]
**Describe the bug**

When we reply to someone's comment and try to like the same comment then the count becomes negative is `-1`.
For more please watch the screen recording.

https://user-images.githubusercontent.com/59080942/184609325-7cb05273-04e2-46a8-a8f1-d4d09e728b78.mov

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: MAC OS
- Browser, version: Chrome

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by jaw6** [comment]
Steps to replicate:
1. Create a new comment, do not refresh the page.
2. Like and unlike the new comment

Once the page is refreshed, the component behaves normally, I suspect there's some weird initial state in the frontend when handling the results of a new comment POST.

**Comment by joshpuetz** [comment]
I'm pretty sure this is related to what I consider a longstanding bug: posts and comments get "auto liked" by their author upon creation. Looks like something changed recently with the like/heart button display to show zero, but it's still highlight upon comment creation:

I can't get this to happen every time, but here's what it looks like when you create a comment:
![Image](https://user-images.githubusercontent.com/37842/184910403-d4ab0feb-24a2-48b9-8345-61b68b65387d.png)

Refreshing the page shows the real status of 1 like:
![Image](https://user-images.githubusercontent.com/37842/184910490-565a0e9e-6fdd-4a72-8d24-2ba1779adfd0.png)

Clicking the 'zero heart' before refreshing the page gives you a -1 unhighlighted heart:
![Image](https://user-images.githubusercontent.com/37842/184910666-7d92c058-71d5-4e98-bff0-12cb5fb278fc.png)

And refreshing with a 'zero heart' properly shows the comment has zero likes:
![Image](https://user-images.githubusercontent.com/37842/184910840-1167e442-4563-482a-b70b-7e9c724dd62f.png)

**Comment by Ridhwana** [comment]
Removing myself as an assignee of this task in case anyone feels they want to assign themselves to it this sprint, there was some [investigative work](https://forem-team.slack.com/archives/CAA200SH5/p1661357179857209) that was done but we didn't end up implementing anything.

**Comment by jaw6** [comment]
I think I found [the commit](https://github.com/forem/forem/pull/11283/files#diff-527847849e37cfe72fb546cdb42a74764727b84c666c55e648880b4f98a460f9L100) where the bug was introduced. Basically, prior to #11283, we were handling `newly_created` as a special case, hard-coding `1 like`, but that big cleanup PR removed the special treatment. I'll have a go at restoring the special treatment.

**Comment by jaw6** [comment]
Should be fixed by https://github.com/forem/forem/pull/18438
