### ISSUE TITLE
Update Error on Dev.to - "updating published_at for articles that have already been published is not allowed"

### ISSUE THREAD

**Issue by app-generator** [forem/forem#18341]
**Describe the bug**

While editing old articles on Dev, without any exception, I got always the same error and the new content is not saved:

![image](https://user-images.githubusercontent.com/51070104/184930820-af8f41e3-1443-489f-9d1b-75e4a9e46ada.png)

**To Reproduce**

Not sure this issue is related to my account https://dev.to/sm0ke

- Click on any existing article
- Start the edit mode
- Change the content
- Save
  - on save action I got the error `updating published_at for articles that have already been published is not allowed`

**Expected behavior**

Following the above scenario, the save action should be successful. 

**Screenshots**

![image](https://user-images.githubusercontent.com/51070104/184931338-b2945bee-2d05-4668-83bf-a050a91e3642.png)

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Chrome latest version
  - Same problem n Firefox    

**Smartphone (please complete the following information):**

**NA**

**Additional context**

**NA**

**Comment by app-generator** [comment]
Hello guys!

Ty for the fix. The patch is scheduled to go LIVE any time soon? 

10x

**Comment by maestromac** [comment]
@app-generator it went live
