### ISSUE TITLE
Reading list displays wrong count on sidebar

### ISSUE THREAD

**Issue by jmau111** [forem/forem#18359]
**Describe the bug**

When a post is **deleted**, the reading list does not take it into account. It happens on the sidebar but not in the dedicated page https://dev.to/readinglist where the count is correct.

**To Reproduce**

A bit hard to reproduce (you probably need a local instance), but just add a post to your reading list and then delete the post.

**Expected behavior**

The total count should be updated when the post is deleted.

**Screenshots**

**correct count on /readinglist**
![](https://user-images.githubusercontent.com/6878027/185797491-e1771d29-4616-4979-836f-c0dcd50b3c4a.png)

**wrong count on other pages**
![](https://user-images.githubusercontent.com/6878027/185797493-8d62e09b-2c60-4709-b468-f382af7a337d.png)

**Comment by jmau111** [comment]
bump up :)

**Comment by jmau111** [comment]
hello @joshpuetz, do you think it can be fixed?

**Comment by jaw6** [comment]
:wave: @jmau111 thanks for reporting this. I am looking into the bug, but I am having a little difficulty replicating locally. Can you confirm if this is still happening now? Is the count still incorrect even after you refresh the page?

**Comment by jmau111** [comment]
@jaw6 yes, it happen when you fav a post, and the post is deleted by the author.

**Comment by jaw6** [comment]
:wave: @jmau111 I made a Loom video of the behavior I experience, can you help me understand how it differs from what you're seeing? 

https://www.loom.com/share/12fb7a488636454bad6f97630990a876

**Comment by jmau111** [comment]
@jaw6 hey, very nice support. I have 0 archive, 3 on reading list, but the home page keeps saying me "6".

Very weird. How do you handle that in code? SQL query + cache, I guess. Is that so? Would it be different if you create post with a non-admin user?

**Comment by jaw6** [comment]
@jmau111 :ok: I did a little more spelunking today and I can now replicate the issue. Technically speaking, it isn't deleting a post that causes this; it's when someone uses `unpublish`. That is, when a post is **deleted**, we have a little cascade that removes any `Reaction` made against that post (`readinglist` is a kind of `Reaction`). When a post is **unpublished**, any `Reaction` remain as-is, but the `readinglist` view (and associated counters) do not show (or count) posts that have been unpublished. 

It's going to take a little thought to figure out how we want to resolve this bug.

**Comment by jmau111** [comment]
@jaw6 nice catch!!! Thanks for letting me know. Indeed, it seems _a bit_ intricate :(
