### ISSUE TITLE
Snackbar not visible image upload errors in comment editor

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18368]
**Describe the bug**

Snackbar not visible image upload errors in comment editor

**To Reproduce**

1. Go to any post/article as logged-in user
2. Go to comment editor area
3. Upload a very big image
4. There will be no visible error.

**Expected behavior**

Error snack bar should be visible similar to what happens when same steps are followed in `Create Post`

**Notes**
- For `Post Editor` the [handleImageFailure](https://github.com/forem/forem/blob/4cddc0bc22ee4d78596f00f510cea9f40796833d/app/javascript/article-form/components/EditorBody.jsx#L51) is getting called and is working correctly
- For `Comment Editor` the  [handleImageFailure](https://github.com/forem/forem/blob/3f6cc95f79d6520cc289a0916904615f394e0222/app/javascript/packs/CommentTextArea/CommentTextArea.jsx#L56) is also getting called but is not working correctly.
- We don't need to worry about the error message as it will be handled by `handleImageFailure` function.
- Just focus on making sure that error message is visible.

**Comment by amywtlin** [comment]
@rt4914 What is the error here? Is the image size too big, or something? Do we have a copy written already?

**Comment by amywtlin** [comment]
This is related to #18339 as they are in the same area

**Comment by rt4914** [comment]
@amywtlin I have added some notes to the description. In practice the error message is not important in this case, making sure that the function gets called correctly is important.

**Comment by amywtlin** [comment]
Ah I see. Then I think it's good to go!
