### ISSUE TITLE
After login preferred theme settings are not getting applied till a refresh or page navigation

### ISSUE THREAD

**Issue by iarmankhan** [forem/forem#18361]
**Describe the bug**

On Dev.to, after user login it doesn't change the theme according to user's preference. For example, if I have set dark mode for my user, then I browse the website without login on light mode, once I login to the website it won't change the theme instantly, I would have to refresh the page or navigate to some article to make it change theme for me.

**To Reproduce**

1. Go to Dev.to 
2. Login to your account
3. Set the theme as dark
4. log out
5. Browse dev.to in light mode from any browser
6. Log in to your account again
7. Check the theme not being changed till next refresh

**Expected behavior**

Ideally, it should instantly change theme once I login to my account according to my preference.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04.4 LTS
- Browser, version: Microsoft Edge Latest for Linux, Chrome stable

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by mirie** [comment]
Thanks for reporting! Unfortunately, I was unable to reproduce. Please open a new issue if you are still experiencing this issue.
