### ISSUE TITLE
Quality of life improvements on the Admin side of Display Ads

### ISSUE THREAD

**Issue by mirie** [forem/forem#18379]
**Is your feature request related to a problem? Please describe.**
As an admin using `/admin/customization/display_ads`, there are a few rough edges.

* Success Rate is displayed as a number instead of a %
* I can't filter based on Published / Approved
* Search doesn't work

These are not show-stoppers that prevent us from leveraging the user-facing functionality, but we should look to address these rough edges as quality of life improvements.

**Describe the solution you'd like**

- [ ] Success rate is displayed as a % (easier to read)
- [ ] Filter / search against Published vs. Approved
- [ ] As a quick win, we can probably use the filters > search (and just remove search)

**Additional context**
Ridhwana likely have the best sense of the implementation considerations given the great work they've been doing in other areas of the `/admin` panel.

We seem to have a few different approaches on how to filter/search results depending on the page:

* `/admin/customization/html_variants?state=mine`
* `/admin/member_manager/users?utf8=✓&search=&role=admin&commit=Filter`

**Comment by mirie** [comment]
@pkfrank is this issue irrelevant with forem tools?

**Comment by pkfrank** [comment]
@mirie Yeah, no longer a priority really given the improvements via Forem Tools.
