### ISSUE TITLE
Onboarding flow redesign technical assessment

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#18387]
# Background

[PRD](https://www.notion.so/forem/Forem-Product-Roadmap-78f05719899f495dbabb089bbc3f40ef?p=4a40f246ad0f4e95987e80f342f7a3b3&pm=s) 
As a part of effort to improve acquisition, @anujbhavsar96  looked at the current experience and have found quite a few things we can improve. We are at a point where we are almost ready to involve engineering to gauge effort.

# To do
1. Review the low-fidelity wireframes of redesign and give estimated effort
   -  walkthrough [Loom video](https://www.loom.com/share/6318c9645a1543aaa0ee9b42ea4f3603) 
   -  [Figma File](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?node-id=1803%3A52502)
3. Milestones: how engineering might slice the project into different milestones that deliver values to our users

After the above is done, Amy will review it and create appropriate issues for implementation.

**Comment by amywtlin** [comment]
@anujbhavsar96 Here's the issue that we'll use for a technical assessment!

**Comment by anujbhavsar96** [comment]
Here is the wireframe walkthrough [Loom video](https://www.loom.com/share/6318c9645a1543aaa0ee9b42ea4f3603) and [Figma File](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?node-id=1803%3A52502). Drop your comments in Figma if you have any doubts or suggestions ✨

**Comment by mirie** [comment]
@joshpuetz to take a look tomorrow [Friday] and provide feedback here so that we can understand what is achievable [and order of operations for changes] / what has some complexity because of xyz (what are alternatives that can be considered instead)

**Comment by joshpuetz** [comment]
Our current onboarding flow is set of preact slides located at `app/javascript/onboarding/Onboarding.jsx`, displayed by `OnboardingsController.show`, and update for each slide are routed through `OnboardingsController.update`. `app/javascript/onboarding/Onboarding.jsx` defines the onboarding slides and their order, so an option for developing this new onboarding flow would be to use a feature flag to route users into a new set of onboarding slides that align with @anujbhavsar96's design.

Regarding the design itself: I didn't see anything in it that made me worried. I'm not sure if we'd want to continue using a preact/slideshow flow as the number of 'slides' in this design is greatly reduced. I think the task breakdown would end up looking like this:

- introduce feature flag and create new 2-screen flow
- 'Welcome to <forem>' feed header component
- 'Welcome to <forem>' feed sidebar component

**Comment by amywtlin** [comment]
> One open question I have is the 'Follow tags of your interest' task: where does it lead?

I think @anujbhavsar96 's idea is to create a modal for it - alternatively, we can also just link to `/tags`.

I created a board for onboarding redesign scoping: https://www.figma.com/file/ZPUiojnX4UwLvtSfy9jzgo/Onboarding-scoping?node-id=0%3A1

Here's an overview of the changes in this project:
1. Sign up page redesign
   1. Sign-up page
   1. Set-up page
1. Secondary optional onboarding module + popup modals (position TBD?)
   1. Module (note: this should be configurable in the future)
   1. Complete profile modal (alternative: link to https://dev.to/tags)
   1. Follow tags modal (alternative: link to https://dev.to/settings)

I am inclined to scope out #1 for MVP, and leave #2 for a later stage. @joshpuetz Do you feel like this scope can be contained within our 2-week cycle, or does it need to be even smaller?

**Comment by mirie** [comment]
Closing as we will revisit this
