### ISSUE TITLE
Badge page redesign

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#18382]
# User story
📖 As a user, I want to understand which badges I can potentially earn and how to do so for each one.

![Image](https://user-images.githubusercontent.com/11730007/186809998-07183106-8be3-478f-b661-9ff1cfbc49cb.png)

# To-do

To update the `/badge` layout as the new design [here](https://www.figma.com/file/ecvlal5QFT01C1idbO3Ljx/Badges-%F0%9F%8E%96?node-id=801%3A860)

Check this [Prototype](https://www.figma.com/proto/ecvlal5QFT01C1idbO3Ljx/Badges-%F0%9F%8E%96?page-id=801%3A860&node-id=801%3A861&viewport=432%2C891%2C0.49&scaling=scale-down&starting-point-node-id=801%3A861)

![Image](https://user-images.githubusercontent.com/11730007/186809844-42b8bd9f-222c-48c8-b345-32df6a145faf.png)

Product point person: @amywtlin.

**Comment by rt4914** [comment]
@amywtlin Either both the figma links are incorrect or the permissions needs to be updated. PTAL.

**Comment by amywtlin** [comment]
@rt4914 Just invited you - try again?

**Comment by rt4914** [comment]
Thanks @amywtlin Worked.

**Comment by mirie** [comment]
Hey @rt4914, Saw your [slack thread](https://forem-team.slack.com/archives/C7GE84DEJ/p1661959945849919), and checking in to see if you were making progress. I had a related question about Tailwind [here](https://github.com/forem/forem/issues/18392#issuecomment-1235624888), although that's more in the admin display context.

**Comment by rt4914** [comment]
@mirie The main details of page has been finished and works really great. I am currently working on showing the `dialog` which appears on item click. Its a bit tricky as it needs ERB and ruby skills.
