### ISSUE TITLE
Buggy realignment of narrow GIF's in Firefox

### ISSUE THREAD

**Issue by redbar0n** [forem/forem#18428]
### **Screenshots**

Before buggy realignment:

![image](https://user-images.githubusercontent.com/459282/188654971-d9db778e-b7ca-4078-a60c-f1b03042ad16.png)

After buggy realignment:

![image](https://user-images.githubusercontent.com/459282/188655005-3f5179d0-8342-48bb-8ed0-7b31195f087d.png)

###  **Expected behavior**

The GIF should stay centered, even when the Play/Pause feature is added.

### **Describe the bug**

In dev.to, certain narrow GIFs in a blog post gets suddenly left-aligned in Firefox. Even though they are centered in Safari.
Seems to do with the pause/play canvas being inserted into the page.
Possibly related to this PR: **[Place gifs correctly regardless of center tag #16404](https://github.com/forem/forem/pull/16404)**

Surrouding the GIF with  a `<center>` tag will center it, but another problem is that the `<center>` tag is undocumented in the dev.to editor...

Wide GIFs that fill the entire width of the blog post column doesn't have this problem, as far as I can tell.

###  **To Reproduce**

OS: macOS
Browser: Firefox 91.13.0esr (64-bit)
- Bug persists even when all browser extensions in Firefox are disabled.
- Bug is not observed in Safari.

Example GIF:
```
![marko-full-hydration](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/39vekfbmxzquqnzbfrw9.gif)
```

1. Create a new post
2. Paste in Example GIF code
3. Click Preview
4. Confirm it is center aligned initially

Inspect element - Before buggy realignment:

```html
<div class="crayons-article__main">
  <div class="crayons-article__body text-styles spec__body" data-article-id="1186122" id="article-body">
    <p>dwqdwq</p>
    <p><a
        href="https://res.cloudinary.com/practicaldev/image/fetch/s--jIo2Iyfc--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/39vekfbmxzquqnzbfrw9.gif"
        class="article-body-image-wrapper"><img
          src="https://res.cloudinary.com/practicaldev/image/fetch/s--jIo2Iyfc--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/39vekfbmxzquqnzbfrw9.gif"
          alt="marko-full-hydration" loading="lazy"></a></p>
  </div>
</div>
```

5. Refresh the page,  and confirm it gets left aligned, with a Play/Pause option.

Inspect element - After buggy left-alignment:

```html
<div class="crayons-article__main">
  <div class="crayons-article__body text-styles spec__body" data-article-id="1186122" id="article-body">
    <p>dwqdwq</p>
    <p>
    <div class="ff-container ff-ready ff-active"><button type="button" class="c-btn gif-button fs-s gap-2"
        aria-label="Pause animation playback" aria-pressed="false"><svg class="crayons-icon gif-play" width="24"
          height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10ZM10.622 8.415a.4.4 0 0 0-.622.332v6.506a.4.4 0 0 0 .622.332l4.879-3.252a.4.4 0 0 0 0-.666l-4.88-3.252h.001Z">
          </path>
        </svg><svg class="crayons-icon gif-pause" width="24" height="24" viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg">
          <path
            d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10ZM9 9v6h2V9H9Zm4 0v6h2V9h-2Z">
          </path>
        </svg>GIF</button>
      <canvas class="ff-canvas ff-canvas-ready" width="421" height="512">
      </canvas><img
        src="https://res.cloudinary.com/practicaldev/image/fetch/s--jIo2Iyfc--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/39vekfbmxzquqnzbfrw9.gif"
        alt="marko-full-hydration" loading="lazy" data-animated="true" id="animated-0" class="ff-image" width="421"
        height="512">
    </div>
    </p>
  </div>
</div>
```

**Comment by wojtekxtx** [comment]
True,v can only confirm this.
