### ISSUE TITLE
negative hearts/likes on replies to comments

### ISSUE THREAD

**Issue by Jonyk56** [forem/forem#18427]
**Describe the bug**
negative hearts count on replies to comments

**To Reproduce**
reply to a comment
un-heart it
get negative hearts

**Expected behavior**
nothing should happen on unreact or re-reaction

**Screenshots**
![image](https://user-images.githubusercontent.com/44901605/188633506-fd472535-5ee6-46bd-9f1c-d3a7951e705b.png)

**Desktop (please complete the following information):**

- OS, version: ChromeOS 104.0.5112.83 
- Browser, version: 

**Additional context**

**Comment by Wjplatformer** [comment]
@Jonyk56 , should you or I delete the issue? Cos duplicates, you know :|

**Comment by amywtlin** [comment]
Hey @Jonyk56 - this is a known issue and we are addressing this with the PR attached to this issue. Hence closing this issue, and thank you for reporting!

**Comment by jaw6** [comment]
Should be fixed by https://github.com/forem/forem/pull/18438
