### ISSUE TITLE
-1 and 0 hearts on comments

### ISSUE THREAD

**Issue by Wjplatformer** [forem/forem#18420]
**Describe the bug**
When I post said comment, heart is 0. When I click the heart button, Heart goes to -1. It might be a reload or cache issue.

**To Reproduce**

1. Post a comment in DEV anywhere
2. See the heart button counter turn to 0
3. click the heart button
4. see it go to... -1.

**Expected behavior**
When posted a comment, heart counter should be 1 as DEV automatically sets you to heart the comment.

**Screenshots**
![image](https://user-images.githubusercontent.com/82447031/188349100-60488768-997d-4bd8-be30-ff561829ce17.png)

![image](https://user-images.githubusercontent.com/82447031/188347991-c34ff4b6-5cb8-45c5-8e38-caf354795c3d.png)

**Desktop (please complete the following information):**

- Windows 10 Home, Version: 10.0.19043, Build: 19043
- Chrome, Version: 104.0.5112.102 (Official Build) (64-bit) (cohort: Stable) 

**Smartphone (please complete the following information):**

- nil

**Additional context**
This issue started some time ago. It seems to be fixed when refreshed. So maybe someone removed refreshing the page once a comment has been posted.

**Comment by wojtekxtx** [comment]
Ive also noticed this.
BTW: fuck kde

**Comment by Jonyk56** [comment]
lol i didn't notice this bug report so i just made another kekw

**Comment by wojtekxtx** [comment]
First question: why does flarum give 1 heart as soon as you commit a comment? Dackrise behavior
Second question: why this exists?

**Comment by Wjplatformer** [comment]
Bruh. What is KDE?

**Comment by wojtekxtx** [comment]
@Jonyk56 good. The more similar bugs the better visibility.

**Comment by Wjplatformer** [comment]
@wojtekxtx , I feal that having one should be enough. I got the attention of one of the FOREM members, I'm sure they'll eventually reach this ISSUE

**Comment by amywtlin** [comment]
Hey @Wjplatformer  - this is a known issue and we are addressing this with the PR attached to #18312. Hence closing this issue, and thank you for reporting!

**Comment by jaw6** [comment]
Should be fixed by https://github.com/forem/forem/pull/18438

**Comment by Wjplatformer** [comment]
thanks :)
