### ISSUE TITLE
Profile page broken

### ISSUE THREAD

**Issue by Posandu** [forem/forem#18442]
**Describe the bug**

The profile page is broken and shows 2 rows instead of 2 columns

**To Reproduce**

Go to https://dev.to/posandu (or any DEV profile)

**Expected behavior**

There should be two columns.

**Screenshots**

![image](https://user-images.githubusercontent.com/76736580/189845718-f30f1c79-ba41-4c4c-ab80-05df4671c442.png)
![image](https://user-images.githubusercontent.com/76736580/189845757-6ce3afe5-a345-43cd-aa46-ffc97f5bdd84.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Brave, Latest

**Comment by amywtlin** [comment]
@Posandu Thank you for reporting - I have raised this with the team and we are looking into it.

**Comment by Posandu** [comment]
I guess this is fixed now 😄

**Comment by maestromac** [comment]
Yup this was resolved.
