### ISSUE TITLE
Comments sort not centered

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#18449]
**Describe the bug**
_Hmmm I'm triggered!_ 

Not centered content in comments section with the sort.

![image](https://user-images.githubusercontent.com/14293805/190003137-7f6795e3-9702-43d1-b617-26fd029ba2fb.png)

**To Reproduce**

1. Go to any post
2. Scroll to the comments section like [here](https://dev.to/devteam/top-7-featured-dev-posts-from-the-past-week-4phi?comments_sort=latest#comments)

**Expected behavior**
Not centered content.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Chrome 105
- Browser, version: Windows 10

**Additional context**

💚💚💚

**Comment by fdocr** [comment]
Thanks for noting this @thomasbnt!

I'm submitting a quick fix that should ideally improve the alignment 🙏🏼
