### ISSUE TITLE
Square box issue in Safari Version 14 and below

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18452]
**Describe the bug**

Whenever we use responsive square boxes, we generally use `aspect-ratio: 1/1` in css styles. Safari Version 14 and below does not support. Safari Version 15 does support it.

This issue can be noticed on smaller iOS devices, Safari 14 Version on following links: https://dev.to/pod and https://dev.to/badges
(Check below screenshots for the same)

**To Reproduce**

1. Open Safari version 14 or below 
2. Open https://dev.to/pod or https://dev.to/badges
3. If in smaller screen the issue should be noticeable that the expected image backgrounds are not square or else make your browser smaller in size.

**Expected behavior**

The grey-background of badges or pods should be square in shape as shown:

<img width="600" alt="Screenshot 2022-09-14 at 3 18 55 PM" src="https://user-images.githubusercontent.com/9396084/190121870-00fcb20d-b691-47dc-b1fd-4028fe050fb7.png">

**Error Screenshots**

- Pods
<img width="600" alt="Screenshot 2022-09-14 at 3 20 20 PM" src="https://user-images.githubusercontent.com/9396084/190122166-4f94d9c2-e711-4c60-ac99-c824b916c3ac.png">

-Badges

<img width="600" alt="Screenshot 2022-09-14 at 12 59 30 PM" src="https://user-images.githubusercontent.com/9396084/190122292-15f8a8e5-7e8f-40f7-af00-012586b61438.png">

**Desktop (please complete the following information):**

- OS, version: macOS / iOS
- Browser, version: Safari Version 14

**Comment by rt4914** [comment]
cc: @amywtlin

**Comment by mirie** [comment]
Closing as fixed
