### ISSUE TITLE
Uploading a file type except images causes infinite loading state

### ISSUE THREAD

**Issue by ahmedDev20** [forem/forem#18454]
**Describe the bug**

In the editor, when trying to choose any file except images, the app is stuck in the loading state.

**To Reproduce**

1. Go to https://dev.to/new
2. Click on `add a cover image`
3. In your explorer, choose any file type either than the image
4. The app goes in an infinite loading state

The app should handle this exception properly by displaying an alert indicating that any file except images is not supported for the upload.

**Screenshots**
![image](https://user-images.githubusercontent.com/62652609/190139119-8c292ab6-8c26-4e0e-827b-ed1894273b8f.png)

**Desktop**

- OS, version: Windows 10 Pro, 21H2
- Browser, version: Chrome,105.0.5195.126

**Comment by jaw6** [comment]
:wave: @ahmedDev20 Thanks for reporting this! I think I understand what's happening.

We actually send an instruction to the browser that should _only_ permit uploading files with the mime-type `image/(any)`. There's generally broad support for this in modern browsers -- some mobile browsers do not support file-extension limitations but almost *all* support this broader mimetype instruction.

```html
<input data-testid="cover-image-input" id="cover-image-input" type="file" accept="image/*" class="screen-reader-only" data-max-file-size-mb="25">
```

I was curious what would happen if this was disabled -- if, say, a bug in Chrome caused the browser to ignore this instruction. What happens is a pop-up in the lower-right corner of the page that instructs you that the file-type is incorrect. 

<img width="500" alt="Screen Shot 2022-11-01 at 14 47 28" src="https://user-images.githubusercontent.com/2077/199249482-2640b74e-e179-4646-95a2-2a23440c1cd6.png">

This pop-up disappears in a few seconds -- it was a bit challenging to actually capture the screenshot above -- it might be more useful if this stayed visible _longer_. Also, the form control, which flips to say "Uploading...", stays on the screen. What ought to happen _next_ is that the "Uploading..." text should flip back to the form control when an error is encountered during form processing.

Let's see if we can make that happen :+1:

**Comment by ahmedDev20** [comment]
Hi, @jaw6 thanks for taking the time and trying to fix this issue.

As you mentioned, the pop-up does indeed show indicating the wrong file type that was uploaded by the user, but in some cases, it's showing an empty type. I tried uploading a **.psd** file but It's not indicating that type correctly.
In my opinion, I think it's not necessary to show to the user the file type or use a generic type, a warning message like the one used is all needed. And about the loading state, yes, as you said it's still persisting after the error, I'm hoping that you could fix that in the future.

Thanks again for your time, and I'm glad to be a part of **dev.to** community and do the least I could to help give the users a very good experience using this service. 😊

I'm attaching a screenshot to show the issue. 📎

![image](https://user-images.githubusercontent.com/62652609/199311172-88a4b6da-49e3-4eb6-9989-127cf36702b8.png)
