### ISSUE TITLE
Remove “latest articles” from /reports

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#18484]
## Context

The top of `/admin/moderation/reports` displays “Latest Articles” which were originally introduced to help admins scan their Forem for recent articles.

However, **this functionality is not appear to be used much by our own team, and is not useful for other Forem creators,** and removing it can simplify the application in a healthy way.

*This is one of two boxes we’re removing from this view*. So these could be tackled together most likely. (https://github.com/forem/forem/issues/18485)

## Desired Outcome

- The view display and all related code is removed.

**Comment by ChaelCodes** [comment]
Should this issue be closed? Looks like @Ridhwana completed this in https://github.com/forem/forem/pull/18500 .
