### ISSUE TITLE
Remove “Vault Secrets” from /admin

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#18487]
## Context

At one point, we had a thought of allowing Admins to see/adjust certain configurations in `/admin/advanced/secrets`.  However, we abandoned those plans and this page is no longer useful.

As such, we can look to remove complexity and reduce confusion by removing this page.

**One final sanity check** that this is not needed code under any circumstance could be warranted, but this is not known to be useful at all.

## Desired outcome

- Display code and relevant internal logic is removed.

**Comment by maestromac** [comment]
I've confirmed with Andy that it is safe to remove
