### ISSUE TITLE
Remove “possible spam/abuse” from /reports

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#18485]
## Context

The top of `/admin/moderation/reports` displays “Possible Spam/Abuse” which was originally introduced to help admins scan their Forem for problematic behavior.

However, **this functionality does not appear to be used much by our own team, or other Forem creators,** and removing it can simplify the application in a healthy way.

We have related projects for monitoring potential spam/abuse, so removing this reduces the overall surface area and different ways of accomplishing a similar action.

*This is one of two boxes we’re removing from this view*. So these could be tackled together most likely. (https://github.com/forem/forem/issues/18484)

## Desired Outcome

- The view display and all related code is removed.

**Comment by maestromac** [comment]
Resolved with https://github.com/forem/forem/pull/18499
