### ISSUE TITLE
Remove dead code related to “tracking” html variants

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#18481]
## Context

We currently have logic in our codebase related to “tracking” the performance of HTML variants.

**However, we simply don’t use this functionality anymore and don’t intend to in the future.**

***This is being entirely replaced by Display Ads*** as the singular building block in our application for tracking performance and optimizing the display of these sorts of units.

You may see references to the “Badge” landing page at [https://dev.to/badge](https://dev.to/badge), but that’s not related to the code that actually runs the page, which has been moved to a more standard page.

We still have some of the code technically running, and it can all be removed. We will be consolidating around the behavior provided by Display Ads.

## Desired Outcome

- Remove the dead and unused code related to tracking “trials” and “successes” for HTML Variants
- Remove associated data tables (**`html_variant_successes`** and **`html_variant_trials`)**
- We don’t have to worry about historical data

This is purely code removal as far as we know, there should be no need for adjusted behavior.

**Comment by lightalloy** [comment]
I see that the task is about removing tracking of `HtmlVariant` performance, but for more context: do we plan to remove `HtmlVariant`s entirely? (replacing with `DisplayAds`)

**Comment by pkfrank** [comment]
Hi @lightalloy sorry for the delay.

> do we plan to remove HtmlVariants entirely? (replacing with DisplayAds)

The answer is **yes, but not right now**.

Various Forem still rely on HtmlVariants to accomplish certain behavior — whether that's launching a Hackathon on DEV and using "Campaign Mode," or just leaving it "always on" to improve navigation, such as on Forem.dev.  So, while we will remove HtmlVariants in the future, doing so here is out of scope for this particular issue.

Looking ahead to eventually taking on that work work, we'll need to: 1) communicate with Forem Creators, and 2) ensure that Display Ads has new placement / creation options that help achieve a similar function.
