### ISSUE TITLE
Remove remaining unused “social preview” view code

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#18483]
## Context

@jaw6  has begun work to remove code related to social previews in https://github.com/forem/forem/pull/18118

However, some of the unused **view** code is still in place.

## Desired outcome

- The rest of the view code is removed.
- We are still using social previews **on articles**, so that code should stay in place.

**Comment by jaw6** [comment]
@pkfrank I'm worried I'm misunderstanding something here, so just to confirm -- is the idea here that we want to remove *all* of the card/opengraph `meta` tags *except* for `article#show` ?

**Comment by benhalpern** [comment]
Hey @jaw6, that is correct.

We already removed most of these in that prior PR. This is just clean up on the _view code_ that was missed as part of that.

So files like `app/views/social_previews/tag.html.erb`, `app/views/social_previews/comment.html.erb` — pretty tiny task.

Unless there is additional context _we're_ missing here.
