### ISSUE TITLE
Found a glitch in DEV dashboard.

### ISSUE THREAD

**Issue by wiseaidev** [forem/forem#18509]
**Describe the bug**

Hey fellas. While I was tinkering around the DEV website exploring the dashboard panel, i noticed a glitch there when switching back and forth between the [following users](https://dev.to/dashboard/following_users) tab and the [following organizations](https://dev.to/dashboard/following_organizations) tab. Sometimes, the following user list gets appended to the following organizations list.

**To Reproduce**

1. [Log into your DEV account](https://dev.to/enter).
2. Go to the [main dashboard](https://dev.to/dashboard).
3. Click on [following users](https://dev.to/dashboard/following_users).
4. Then, Click on [Following organizations](https://dev.to/dashboard/following_organizations).
5. Click back and forth until you notice that the following users' list is appended to the following organizations' list.

**Expected behavior**

The following users' list shouldn't be added to the following organizations' list.

**Screenshots**

![glitch](https://user-images.githubusercontent.com/62179149/192603147-5535bad2-a466-489f-bdc4-53a73fe260f7.gif)

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04
- Browser, version:  Chromium, Version 105.0.5195.125 (Official Build) snap (64-bit)

**Smartphone (Didn't test it on mobile):**

- Device: Any
- OS, version: Any
- Browser, version: Any

**Additional context**

That's pretty much it.

**Comment by narender2031** [comment]
I would like to work on this

**Comment by mirie** [comment]
@narender2031 assigning it to you! 😄

**Comment by mirie** [comment]
@neerajkrbansal1996 It hasn't been worked on, so I can update the assignment. We would welcome your contribution on this issue!

**Comment by tomalexhughes** [comment]
I'd like to pick this up if it hasn't been worked on. Thanks!

**Comment by mirie** [comment]
@tomalexhughes sorry for the delay and thank you for your interest! I will re-assign to you. Thanks!!
