### ISSUE TITLE
Typo on Account Activation Email Page

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#18534]
**Describe the bug**

A community member kindly wrote in and pointed out a typo on the account activation page (upon signup). From their email:

> Just wanted to let you know there's a typo on the account activation page: "instuctions" ("We sent you an email with the instuctions to activate your account.")

**To Reproduce**

Sign up to DEV with a new account and check out the account activation page that appears after signing up.

**Expected behavior**

Just need to correct the spelling of "instuctions" to be "instructions"

**Additional context**

I know this isn't really a bug, but I figured this is the best place to communicate this kind of correction as it needs to be corrected in the codebase versus the admin section.

**Comment by mirie** [comment]
@fdocr can I pass this to you for a quick fix?

**Comment by heliocola** [comment]
@mirie : I did a search on this repo, devise, and devise_invitable and I could not find the typo word `instuctions`.
Perhaps is this coming from a different repo?

**Comment by fdocr** [comment]
Thanks for mentioning this @heliocola. You're right, there's no such text in the repo. This is a typo that exists in the account.forem.com repo, which will be addressed in a PR there.
