### ISSUE TITLE
Cannot connect to GitHub; unstyled page on redirect

### ISSUE THREAD

**Issue by HughxDev** [forem/forem#18553]
**Describe the bug**

On redirect from attempting to connect to GitHub:
  - HTTP 400 Error in console
  - CSS does not load
  - GitHub account is not connected

**To Reproduce**

1. Go to Profile Image Menu → Username
2. Click on “Edit Profile”
3. Click on “Connect GitHub Account”
4. Approve if not done already
5. Wait for redirect

**Expected behavior**

- Styled page
- Connected GitHub account

**Screenshots**

https://user-images.githubusercontent.com/229232/194649235-8a7340cc-a079-47e3-ad09-b2a8516f65e8.mp4

**Desktop (please complete the following information):**

- OS, version: macOS Monterey Version 12.6
- Browser, version: Chrome Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by danhuynhdev** [comment]
Confirmed that this is reproducible. I can happily work on this.

**Comment by maestromac** [comment]
I believe this was resolved with https://github.com/forem/forem/pull/18824. Please let us know if this issue still persists.
