### ISSUE TITLE
Canned Response Template Disappeared

### ISSUE THREAD

**Issue by carolineschettler** [forem/forem#18574]
**Describe the bug**

A super mod, Andy Piper, pointed out via our mod Discord that the canned mod responses on DEV have disappeared. After a check, they've disappeared for both myself and @michael-tharrington. Personal response templates still populate, but Sloan's moderator messages do not. 

**To Reproduce**

1. Start writing a comment
2. Click on the three dot kebab menu
3. Click on the bookmark icon
4. If you're a moderator, the Sloan canned responses _should_ populate here

**Expected behavior**

The expected behavior is inputting the Sloan responses as comments and posting them in a thread to correct user behavior.

**Screenshots**

![image](https://user-images.githubusercontent.com/78865475/195366188-9cb0b01c-bd7f-4533-add9-0fc1546935e6.png)

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Firefox 105.0.1

**Additional context**

These response templates are integral to our work on the community team, and we definitely need them back up and running soon.

**Comment by michael-tharrington** [comment]
Appreciate ya raising this one! So strange that access to these templates went missing.

**Comment by ChaelCodes** [comment]
Are the "Sloan responses" trusted user templates?
![image](https://user-images.githubusercontent.com/8124558/196056016-c3939d0f-dd7f-49ef-89d5-2364e3751650.png)
I'm able to create new trusted user templates, and send them as comments when logged in as admin@forem.local.

Can you describe how to create a mod user who doesn't have access to these templates?

**Comment by michael-tharrington** [comment]
Heyo @ChaelCodes!

Really appreciate you looking into this. The Sloan responses are indeed trusted user templates!

We have a bunch of these templates that we created on DEV which should be available to all trusted users and tag mods. However, these responses disappeared and are no longer available there.

That said, I was just able to create a new trusted user template on DEV, so maybe it's not so much that this feature is broken, but that something (or somebody) mistakenly deleted all of our trusted user templates. 🤔

**Comment by michael-tharrington** [comment]
Update: I think there was actually a manual error that led to these messages being deleted rather than a bug. It turns out that more folks can create/delete trusted user templates than I realized. I'll be writing up a feature request to make these messages a bit more secure!

Thank you for your help on this @ChaelCodes, your message above led to this discovery.
