### ISSUE TITLE
ActionView::Template::Error when admin trying to view confirmation instructions emails

### ISSUE THREAD

**Issue by yheuhtozr** [forem/forem#18585]
**Describe the bug**

When I try to read **confirmation instructions emails** sent to users in the admin view (`/admin/member_manager/users/****/email_messages/****`), it never shows up and instead returns the following error:

```
ActionView::Template::Error (undefined method `+' for nil:NilClass):
    40:     <h2>Email content</h2>
    41:     <p><em>The content is previewed below without formatting</em></p>
    42:     <div class="crayons-card my-5 p-5">
    43:       <%= @email.html_content.html_safe %>
    44:     </div>
    45:   </div>
    46: </div>
```

I reported it [on forem.dev](https://forem.dev/yheuhtozr/are-confirmation-instructions-emails-really-sent-with-tag-1dif) and another user was able to reproduce it.

**To Reproduce**

1. Open admin → member manager → specific user → emails → click any **confirmation instructions** email
2. See 404 in production
3. An error recorded as above

**Expected behavior**

You can display those emails correctly.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

As described in [the original article](https://forem.dev/yheuhtozr/are-confirmation-instructions-emails-really-sent-with-tag-1dif), the cause is the `html_content` method expect `<html>` tag in an email but ordinary confirmation instructions emails don't contain it.

https://github.com/forem/forem/blob/d230eb97c17321f14be054bc64774f7a53d54220/app/models/email_message.rb#L4-L8

https://github.com/forem/forem/blob/9bb5b81fc53a23e0001218794bdd6599ef1ea37b/app/views/devise/mailer/confirmation_instructions.html.erb#L1-L9

**Comment by kaysiz** [comment]
I can confirm the above issue, if right tags are added I can pick it up

**Comment by mirie** [comment]
Assigned it to you 😄

**Comment by kaysiz** [comment]
@mirie may you kindly add a hacktoberfest tag to the issue :)
