### ISSUE TITLE
Replace comments box on non-signed-in User profile page with signup CTA

### ISSUE THREAD

**Issue by mirie** [forem/forem#18608]
## Problem Statement

We currently display a “**Recent comments**” box part-way down the user profile page. We want to remove this and replace it with a CTA to sign in for full member details, including recent comments. While this will act as a CTA to join the site (help with **Activation goals**), one motivator is ongoing SEO improvements. We want to reduce the number of internal backlinks to comments (which hurts our crawl efficiency), and more to articles with comments on them.

Example: As an anonymous/logged in user go to [this page](https://dev.to/nevodavid). When you scroll down, you can see:

![Image](https://user-images.githubusercontent.com/896728/196766333-d365fbf0-f3f8-4e16-b67e-f376c399a137.png)

^ The display of this Recent comments block is what we want to change

## Requirements
When an anonymous visitor views a user profile page, instead of the “Recent Comments” block like the one above, they should see:

**Mobile**
![Image](https://user-images.githubusercontent.com/896728/196772828-a9356ae2-8212-4ece-9186-00ea0dd3c7b8.png)

**Desktop**
![Image](https://user-images.githubusercontent.com/896728/196767218-7d58eba8-ccb6-48cb-961b-922521420c60.png)

Figma mock: https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Miscellaneous?node-id=810%3A1992

- Reuse existing styling/components as much as possible, however there will be likely some adjustments -- if unsure bring for discussion before making additional customizations
- The logged in user should see the Recent Comments block (no change in their experience).
- Add event tracking to the Create Account button and Sign in link:
  - Event tracking details (see link to additional info on tracking below):
    - name: "Clicked on Create Account" 
    - source: user_profile_card
    - version: 0.1
- Just like our other CTA flows: 
  - If a user clicks signs in (and signs in successfully), they should be returned to the user page they were just viewing. (There is no behavior to auto-scroll them to the comments component)
  - If a user clicks create account (and finishes the account creation flow), they should be returned to the homepage after completing the onboarding flow

### Additional Information:
- https://forem.team/ridhwana/tracking-of-registration-workflow-clicked-on-create-account-1cee

**Comment by haszankauna** [comment]
hello @mirie can I please be assigned this issue?

**Comment by mirie** [comment]
@haszankauna Thank you for your interest! We actually have this one tagged for our internal team to take on :)
