### ISSUE TITLE
DisplayAd should render consistently with other site content

### ISSUE THREAD

**Issue by jaw6** [forem/forem#18625]
Previously, DisplayAds have had slightly different rendering procedures than Articles or Comments. We'd like to streamline this, so that "content blocks" on the site behave in nearly identical ways. ("Nearly" = Articles will still have "calculate reading time".)

DisplayAd should copy:

- [ ] LiquidTags
- [ ] Allowed Attributes (add `colspan` `data-lang` `em` `id` `ref` `rel` `rowspan` `size` `span` `start` `strong` `title` `value`)
- [ ] Allowed Tags (remove `abbr` `add` `figcaption` `hr` `kbd` `mark` `rp` `rt` `ruby` `source` `sub` `video`)
- [ ] Enrich Image Attributes
- [ ] Catch xss attempts
- [ ] wrap all images in links
- [ ] add fullscreen button to panel
- [ ] wrap all tables
- [ ] remove empty paragraphs
- [ ] Escape liquid tags in codeblock
- [ ] add control class to codeblock
- [ ] escape colon emojis in codeblock
- [ ] unescape raw tag in codeblock
- [ ] wrap all figures with tags
- [ ] wrap mentions with links

Background:
* [Discussion in Notion](https://www.notion.so/forem/Use-the-same-markdown-parser-for-display-ads-as-Articles-Only-for-below-comments-for-now-98d88baee2bb4c04bd204ce0e3f1ecff)
* [Exploratory gist](https://gist.github.com/jaw6/9585c5bc62e7bffe3e5981211f937405)

**Comment by mirie** [comment]
@jaw6 do you think it makes sense to ask the team for a re-estimate of this work now that the requirements are clearer?

**Comment by jaw6** [comment]
@mirie Yeah, that makes sense to me. I also think we should be having a discussion about possibly breaking this story into sub-stories -- there are some bits that are more effortful than others, and could potentially ship separately, but the story makes less sense in pieces, and it _might_ be less work _overall_ if we approach it as one unit.

**Comment by Ridhwana** [comment]
I'm curious to know when we say "DisplayAd should copy:" are we hoping to implement  all the functionality above into our text area within the Display Ad page or are we hoping to re-use the Editor that we use on the user facing side?

**Comment by jaw6** [comment]
> I'm curious to know when we say "DisplayAd should copy:" are we hoping to implement all the functionality above into our text area within the Display Ad page or are we hoping to re-use the Editor that we use on the user facing side?

@Ridhwana In the short-term, I think we're **not** looking to port the Editor, per se, but I'm less confident about how that might go in the longer-term. My understanding was, short-term, wherever it's possible to enter html/markdown/liquidtags, we want to have consistent expectations about what's allowed and how that renders out. (And, while it's being treated as a separate issue -- #18392 -- the goal would be to also have consistent CSS/styling.)

**Comment by jaw6** [comment]
Closing this issue in favor of https://github.com/forem/forem/milestone/9
