### ISSUE TITLE
Fix spacing issue in display ads, and bring under-comment ads to parity with comment CSS

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18626]
**Describe the bug**

Currently display ads have an issue where there is no spacing between blocks.

This leads to awkward visualization, like this:

![Image](https://user-images.githubusercontent.com/896728/196751593-cc11f7fd-a0e3-432c-a74f-a8e148294d42.png)

and

![Image](https://user-images.githubusercontent.com/896728/196751776-475e62d3-31ab-4e29-a154-362983d9cd4d.png)

We work around this issue sometimes by adding `<br/>` in the following `<p>` but that is really bad practice. This isn't the only issue, but for example, there should be more space between the header `h2` tag ("Need better DEV posts?" or "Browsing with dark mode...") and the `p` tag below it. 

**To Reproduce**

1. Go to any Article and scroll down to under comments. It shouldn't matter if you're logged in or not.
2. Look at the Display ad just underneath the comments section and inspect (find one that has multiple lines of content to see the issue). If you inspect, you'll see the `<br>` workaround

## Desired outcome

Spacing on all display ads is fixed to be in sync with our general styling across site. The below-comments CSS should be the same as the CSS used in the comment component above.

**Comment by benhalpern** [comment]
I'm re-opening this to fix a small issue related to this implementation
