### ISSUE TITLE
Dev.to site not working

### ISSUE THREAD

**Issue by RehmatFalcon** [forem/forem#18621]
**Describe the bug**

When I open the dev.to site on my firefox browser, the site does not load properly. I dont know why this is happening.

![image](https://user-images.githubusercontent.com/28915667/197323141-ec94b178-80d8-4326-a184-ea90571e75b2.png)

The site looks like above. I should be logged in, but somehow nothing shows up. If I open the site in incognito mode, it works as expected.

From the console logs, it looks like cookie issue.

[console-export-2022-10-22_11-50-21.txt](https://github.com/forem/forem/files/9843688/console-export-2022-10-22_11-50-21.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Ubuntu 22.04.1 LTS
- Browser, version: Firefox105.0.3

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by RehmatFalcon** [comment]
I pressed sign out link and confirmed it as well, it still seems to be stuck in the same place.

**Comment by Moayed-Ellah** [comment]
The same thing happened to me, but after downgrading firefox it worked well. firefox version 
105.0.1

**Comment by maestromac** [comment]
Closing since this was resolved.
