### ISSUE TITLE
Render hidden “mobile menu” asynchronously, and associated adjustments

### ISSUE THREAD

**Issue by mirie** [forem/forem#18639]
## User Story (Who / What / Why)

As a Forem admin, I want to improve SEO by increasing crawl efficiency through adjustments to the way Forem renders the "mobile menu."

## Context

For user-oriented performance, and SEO crawl efficiency, we have a major inefficiency in that we render the “mobile menu” (behind the hamburger icon) inline with the rest of the HTML, even though it is not visible right away.

This part of the HTML is very heavy in total characters and accounts for around 13kb AFTER gzip. This is a lot of unnecessary code in the streaming process of the HTML request *especially* because it is located at the top of the document. It effectively creates *an extra packet trip* just to see any content on the page.

On some pages, this hidden menu accounts for ***more than half* of the data** we send over the wire. This will have an immediate impact on perceived page load time and SEO. If this is async, it's not a problem. But this data is blocking of first rendering.

A number of our URLs have a “needs improvement” warning in Google Search console with regards to “first contentful paint”, and this should help a lot.

![Mobile menu](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/04uWzDyn/055976df-090b-4088-81b4-247a07a21b1c.jpg?v=c32b5d82de8a91adda9267fb7cac5254)

This menu is generally not visible, but is very costly to page loads.

As a component of removing the nav links from the synchronous HTML, we will add all the nav links to the footer in addition to being present in this area. This will ensure they still get fully crawled by bots which might not load async content.

One final thing: We are also going to remove the little flower icon in the footer. It’s technically an optimization, but it is there because we don’t want the true Forem logo in the open source code, but we also don’t need this icon. We can do without it for now.

## Definition of Done

- [x] The HTML that is currently rendered inline in the hamburger area is changed to be loaded async as HTML sent over in a fetch with no layout, etc.
    - There could be further optimizations on whether we need to even load it async in many contexts, but that can be a potential follow-up optimization.
-  [x] Optimize the rendering with caching.
- [ ] All the nav links currently present in the sidebar are added to the second line of the footer.
    - Like this: `Home • Reading List • Listings • Videos • Tags • FAQ • ….`
- [x] Remove the flower icon in the footer.

With the navigation links added in the described format, and the icon removed, it will ultimately look like this:

![Footer](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/d5unQkyd/93a35b9c-39c9-4688-9f92-843dacef3e45.jpg?v=10784511c6f5bb07fc6a2eee4934f540)

**Comment by mirie** [comment]
@Ridhwana : When you have a moment, can you provide an update here on this issue? I have lost track of the Slack conversation and want to better understand the status of this issue and if any additional support is needed

**Comment by Ridhwana** [comment]
@mirie we're going to go with HTML over the wire (instead of the JSON implementation [here](https://github.com/forem/forem/pull/18735)). I've created a [PR](https://github.com/forem/forem/pull/18760) but then got sick, I'll finish up this PR this week.

**Comment by Ridhwana** [comment]
@mirie I'll be tacking the caching aspect of this ticket today i.e. "There could be further optimizations on whether we need to even load it async in many contexts, but that can be a potential follow-up optimization.", do you want me to create a new ticket to track this or just add it as an item on this one?

**Comment by mirie** [comment]
@Ridhwana Q: are you planning on deploying them separately or together? I see the https://github.com/forem/forem/pull/18760 has approvals but wasn't sure where the conversation actually landed.

**Comment by Ridhwana** [comment]
Update on this task: We've deployed the PR that implements the caching to benhapern-community and the plan is to test it today.

**Comment by benhalpern** [comment]
@Ridhwana the [current PR](https://github.com/forem/forem/pull/18818) is passing tests and marked as `merge by any core` — do you think we're good to merge and deploy this step? Just checking in because this got delayed. What are your latest feelings here?

**Comment by Ridhwana** [comment]
I separated the "default" links and the "other" links on two lines, especially because we wouldn't want the one line to get too long. Let me know if we'd prefer not to do this and rather do all on one line.

<img width="805" alt="Screenshot 2022-12-20 at 21 32 50" src="https://user-images.githubusercontent.com/2786819/208751967-bff00335-036c-45ba-afdb-ce4099084d6e.png">

**Comment by mirie** [comment]
PR in review: https://github.com/forem/forem/pull/18886
