### ISSUE TITLE
Add "type" to Display Ads

### ISSUE THREAD

**Issue by mirie** [forem/forem#18640]
## User Story (Who / What / Why)

As an admin, I'd like to be able to categorize Display Ads by "type" in order to stay more organized around the different categories of display ads that I'm running on my Forem.

## Definition of Done

- [ ] Dropdown for "Type" added to `/admin/customization/display_ads/new`
- [ ] The initial options for "Type" are:
    - [ ] In-House
    - [ ] Community Ad
    - [ ] Advertiser Ad
- [ ] Tests (updated/added): Ruby: validate the addition of this type, update Cypress tests re: Display Ads

## Additional Context

This is thematically similar to https://github.com/forem/forem/pull/18396, which also improved the administration of Display Ads.

_In the future_, we might leverage this "type" information for other purposes.  For instance, we might want to build logic that defines how many impressions we serve to individual display ads within a specific type.

## Meta 

_(capturing for future @pkfrank /@benhalpern discussions but not needed to be sorted out for this particular issue)_
* Do we want to provide the default naming convention for the types "under the hood" ?
* Are these the right types?  If we wanted to be more specific, I could also see these as possible "types"...
    * House ad
    * Boosted content
    * Platform mechanic
    * etc.

**Comment by benhalpern** [comment]
> Are these the right types? If we wanted to be more specific, I could also see these as possible "types"...

I think we could officially consider this _still under review_, and it shouldn't stop us from doing the work, but I think we should have one final discussion about this before we deploy.

Reminder that `type` is a reserved word, and the actual attribute will probably need to be `type_of` or the like.

**Comment by rt4914** [comment]
👍

**Comment by Ridhwana** [comment]
Quick clarification on this task, how does the "type" affect the display ad on the user facing side of Forem? Is there any logic to change there?

**Comment by mirie** [comment]
Surfacing from estimation form: What tests should be expected as part of this work to satisfy definition of done?

**Comment by benhalpern** [comment]
@jaw6 We are good to unblock this. 👍
