### ISSUE TITLE
Update UI for Create Account/ Login CTA on home feed

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18646]
For a logged-out user, on home page, after scrolling a bit, user can see following CTA screen

<img width="1277" alt="Screenshot 2022-10-27 at 5 27 45 PM" src="https://user-images.githubusercontent.com/9396084/198279581-73e6602d-8ae6-4256-a42f-2917ee7bc240.png">

In above image the background of the entire CTA is similar to that of the screen-background.

**Suggestion**: Should this UI be changed so that the CTA looks like a card similar to that of comments. Also it will resonate with the UI which appears on profiles too, implemented in #18608

**Note**: This is just a suggestion and needs finalisation from team, so currently this issue is blocked.

**Comment by rt4914** [comment]
@anujbhavsar96 Any thoughts on this UI change suggestion (mentioned in description)?

**Comment by anujbhavsar96** [comment]
I agree with your suggestion  @rt4914 . We should use a similar UI we used for the profile page. So it'll look something like this,

<img width="1223" alt="Screenshot 2022-11-02 at 11 05 06 AM" src="https://user-images.githubusercontent.com/84626054/199406829-ae29ffc7-cba6-433c-a42f-cac3155f032b.png">

**Comment by rt4914** [comment]
Thanks @anujbhavsar96 If you have created figma file, please share it, otherwise its fine, I can use these screenshots to write code.

**Comment by anujbhavsar96** [comment]
Here is the [Figma link](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Miscellaneous?node-id=915%3A2131) @rt4914
