### ISSUE TITLE
Left/Right sidebars on org page can have similar UI as that of profile-page

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18645]
## Current Situation

**Org Page**

[Reference](https://dev.to/devteam)
<img width="800" alt="Org page" src="https://user-images.githubusercontent.com/9396084/198275658-e7e90ec4-cac2-4ada-a2fa-e7be694265b9.png">

**Profile Page**

[Reference](https://dev.to/ben)
<img width="800" alt="Profile Page" src="https://user-images.githubusercontent.com/9396084/198275760-1fc10070-a145-4a73-b84c-09f1193853d8.png">

The difference between both the screens is that the left/right side bar content on profiles is wrapped in a card-container and on org page they are not.

**Suggestion**: We should wrap content on org pages on left/right sidebars in card-containers similar to that of profile page.

**Note**: This is just a suggestion and has not been finalised internally yet.

**Comment by anujbhavsar96** [comment]
Sounds good ✨. 

And apart from that, we can keep all the information cards for the org page on the left side the same as a Profile page to keep the reading pattern consistent.

**Comment by rt4914** [comment]
@anujbhavsar96 Great, in that case only ordering needs to be finalised from top-to-bottom.
We have `Out Story`, `Our Stack`, `Meet the Team` and finally posts + members stats.

Any opinion on what should be the order of these items?

**Comment by anujbhavsar96** [comment]
@rt4914 I feel we should display `Meet the Team` first and below all other static information. 

We have the same pattern for the Profile page where we display the `Organisations` first _(Interactive information)_ and then all other information.
