### ISSUE TITLE
Add email login

### ISSUE THREAD

**Issue by agonzalezio** [forem/forem#1865]
**Is your feature request related to a problem? Please describe.**
Current account login methods aren't the most suitable for keeping our account access safe.

Using GitHub or Twitter it's ok, but we must remember that they are communities separated from dev.to, they have their own rules and guidelines to determine which accounts must be deleted or suspended.

Also, as they are tech giants it might be hard to contact their support for any issue regarding our account, so losing access to our account in one of those services could mean to lose access to our dev.to account too.

**Describe the solution you'd like**
Adding the possibility to login using an email address, this way we can keep our account access safe and separated from possible issues with any third party OAuth provider.

**Describe alternatives you've considered**
Adding another OAuth provider like Google, for example, a non community oriented service, it's more unusual to have your account suspended, deleted or lost. _(This is being discussed in #1595)_

Another solution could be to have the possibility to unlink my current Twitter/GitHub account and then linking a new one before logging out from dev.to.
But it's not useful if you get your account suspended and can't login to do so.

**Additional context**
I've been experiencing issues with my Twitter account, I have tried to reach out their support but got no response.
The best solution I have found is to delete my account and start a new one.

It means that if I didn't change the Twitter account associated with my dev.to account I will lose access to dev.to's account too. (Emailing Dev team for this, since it's not possible from dashboard).

**Comment by jessleenyc** [comment]
Thanks for the request. We revisit this idea every few months so it's helpful to get the feedback on this.

**Comment by ypkuby** [comment]
I'd also like to see this option. Perhaps, having once registered, you can set a password for yourself, if locked out of the OAuth'd account, using said password will restore and allow you to change your OAuth provider?

**Comment by jwedel** [comment]
I also know people that value their privacy but would like to join the community. For those it would be great to have an email based login.

**Comment by jsntn** [comment]
I'd also like to see this email login option.

**Comment by michael-tharrington** [comment]
Hey folks, I'm a Community Coordinator at DEV and am posting a relevant argument on behalf of a potential DEV user that recently contacted us via our support channels. Here's what they had to say:

"Howdy,

I am interested to join the dev.to community. Yet when I try to log in, I am met with:

Great to have you
Sign In with Twitter Sign In with GitHub

We require social login to prevent abuse.

To prevent abuse, I require that my identity is not linked to surveillance platforms like Twitter or GitHub. I would hope that, to foster a self-empowered community of developers, dev.to would welcome people like this.

Joining the dev.to community should not have as a precondition that we must maintain an account at data-collection corporations. Can you allow login with only information held by the dev.to site?"

They do not have GitHub, so I agreed to share this on their behalf.

**Comment by fredddier** [comment]
In addition to this issue I'd like to point out recent problems Pakistan users are having with GitHub.

GitHub is restricting access to certain features and locked their private repos. As I have described in the initial issue, depending on third party organizations is also a risk for our accounts on DEV, we could get our accounts suspended not just by infringing their guidelines, but for US Administration.

**Comment by jasonsturges** [comment]
Likewise, I dislike authorizing 3rd party apps to my organizations and private repos. Modern trends are email authentication based. 

Would join this community if email authentication was provided. Thanks.

**Comment by rhymes** [comment]
@jasonsturges currently you can sign in with a social login for verification and then set a password but I agree we should add "pure" email login as well once we have a verification system in place.

BTW It's funny calling "email authentication" a modern trend as it definitely predates social logins but it's true they are making a come back.

**Comment by jasonsturges** [comment]
@rhymes Ha ha, I more meant that sites are trending away from passwords altogether, such as Medium or Notion.so where you receive a two-factor code via email when you sign in, and never use a password.

**Comment by rhymes** [comment]
@jasonsturges personally I find Notion sending me an email each time I sign in in either my personal or work account not an improvement, I'd rather use a password and be done with it, but that's just me. Fortunately Notion allows the user to set a password to close the loop :)

**Comment by agonzlezr** [comment]
Hey @jasonsturges , DEV now allows us to set an account password once registered. You still need to use social media to create an account, but you can unlink your accounts on DEV (and GitHub/Twitter) after signing up and just keep the email-password login.

You're welcome to join this community.
