### ISSUE TITLE
unable to upload video from macOS

### ISSUE THREAD

**Issue by trusktr** [forem/forem#18659]
**Describe the bug**

unable to upload video from macOS

**To Reproduce**

1. in macOS
2. hit `cmd+shift+5` to bring up the built-in screen recorder
3. record a short video
4. after finished recording, it will automatically save to desktop as a `.mov` file
5. start writing a dev.to post
6. drag and drop the `.mov` file into the post
7. dev.to says `Image has an unsupported type`
8. 🙏 

**Expected behavior**

Standard workflows in macOS work out of the box.

**Screenshots**

<img width="424" alt="Screen Shot 2022-10-29 at 11 01 16 AM" src="https://user-images.githubusercontent.com/297678/198846466-e69c6661-8072-4e4c-b2de-af773c640a85.png">

**Desktop (please complete the following information):**

- OS, version: macOS 12.6
- Browser, version: Chrome 107

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maestromac** [comment]
@trusktr unfortunately the upload is for images only. For videos, you should see an "upload a video" button on the lower left corner of your profile dashboard.
