### ISSUE TITLE
Python Script and Running Sublime Text Editor Extension "Combiner"

### ISSUE THREAD

**Issue by happygregory** [forem/forem#18658]
### Discussed in https://github.com/forem/forem/discussions/18657

<div type='discussions-op-text'>

<sup>Originally posted by **happygregory** October 28, 2022</sup>
Not sure best place to start this discussion, so if a moderator or other user has an idea about getting the small bit of help I need, please do let me know.

The person responsible for the repository specific to the application, the Combiner extension in Sublime Text Editor, has not been active over the past year. When I presented the problem as an Issue, a moderator suggested I take it to a Discussion as being more appropriate. Especially since it involves Python, and that is such  a popular approach to extending an application such as Sublime Text, I thought I would set up my own Discussion, here.

I am unable to get Combiner to work. I am using the following script based on how I as a non programmer, interpreted the readme examples.

I don't understand how to use the various parts of the script: Path, To, File and maybe the script is not working because the use of the Path variable is not what it should be or stated properly.

BTW I did get the Package set up and it appears in the Tools menu, ready to run with a click. The script is in its own text file. Anything else you need to know to help me, please ask. I have all the files specified in a single local directory on C: drive.

Made a few seemingly obvious changes. Did not have the "/" in front of Path variable. Also took a guess at putting the header as Combiner_TXT. My questions remain the same.

{
"Combiner_TXT":{
combine: "/path C:\Users\AlterMedX.net\Documents\Sublime Stuff/to/file1.txt",
combine:"/path C:\Users\AlterMedX.net\Documents\Sublime Stuff/to/file2.txt",
combine:"/path C:\Users\AlterMedX.net\Documents\Sublime Stuff/to/file3.txt",
output:"/path C:\Users\AlterMedX.net\Documents\Sublime Stuff/to/output.file.txt"
},

Anyone with knowledge of Python, please answer, and if you know Sublime Text Editor, even better. Thanks in advance for any help. I started my repository to help my kid learn Python, but she was not interested. I really don't have a lot of interest in Python, but I would like to get this extension of Sublime Text which relies on Python, to work. Thanks in advance to anyone who responds.</div>

**Comment by maestromac** [comment]
This is not related to Forem.
