### ISSUE TITLE
Refactor: DisplayAd should use rendering service

### ISSUE THREAD

**Issue by jaw6** [forem/forem#18651]
After #18649, `DisplayAd` should use the newly extracted rendering service.

Confirm:

* [ ] `DisplayAd` can include `LiquidTags`
* [ ] Same `AllowedAttributes`
* [ ] Same `AllowedTags`

**Comment by mirie** [comment]
Double assigning this one -- @lightalloy you can lead on the work with @jaw6 overseeing. One of the concerns @jaw6 noted was that we would want to heavily QA this one and give ample heads up on progress/QA/when going live to the community team.

@noah-brinker we will likely start working on this sometime next week. What this work involves is a change in how the content for Billboards are rendered, for example allowing for liquid tags. One thing we'll want to pay close attention as part of QA is that the billboards look as expected :)

**Comment by mirie** [comment]
@lightalloy [this work](https://github.com/forem/forem/pull/19091) is related to [this issue](https://github.com/forem/forem/issues/19099), which we decided to skip in refinement.

Can we figure out next steps for some of the open questions in #19091? I want to make sure we're aligned on approach/next steps for the work. @jaw6 / @lightalloy if it makes sense for y'all to connect to chat first before updating here with a summary.
