### ISSUE TITLE
Refactor: Comment should use rendering service

### ISSUE THREAD

**Issue by jaw6** [forem/forem#18650]
After #18649, `Comment` should be refactored to use the newly extracted, unified rendering service.

**Comment by mirie** [comment]
Blocked until https://github.com/forem/forem/pull/18754 is merged

**Comment by mirie** [comment]
@lightalloy even though ^, please connect with @jaw6 regarding starting on this work. Thanks!

**Comment by mirie** [comment]
@lightalloy just a heads up that @jaw6 will be OOO from Fri through next week, so please connect this week if you haven't already to discuss any concerns/questions

**Comment by mirie** [comment]
@mirie QA - let's check on embedding same things in Comments as in Articles.
