### ISSUE TITLE
.env configuration nerver works on forem installed in docker

### ISSUE THREAD

**Issue by richmonde** [forem/forem#18663]
Hi, forem team:
After installing forem in docker according to the official docs(just fork, clone, cp .env_sample, and execute bin/container-setup).
I got blank page when I wanted to log in with default Admin authentication.
I tried to modify the .env file to change the APP_DOMAIN as I saw a post on forem.dev saying people should not change the docker-compose.yml.
But any changes in .env made no difference (including the 'production' status, it alway shows 'development')until I modified the APP_DOMAIN item in docker-compose.yml.
Also I found that the APP_DOMAIN of .env cannot overwrite the item of docker-compose.yml after running the command env in the container of forem_rails.
By the way, the static resources also cannot be loaded properly.

**To Reproduce**

Install the forem with default configurations.

**Expected behavior**

behave like forem.dev

**Screenshots**
![image](https://user-images.githubusercontent.com/19168163/199219250-e5f31dd2-b57b-4dc5-8876-847efe6f1930.png)

![image](https://user-images.githubusercontent.com/19168163/199218536-6c9cbf66-9484-4877-b394-687ebb7397cf.png)

- Device:
Debian 4.19.194-3
- Microsoft Edge latest

**Additional context**

**Comment by maestromac** [comment]
Hello @richmonde , we recently revamped our setup options and highlighted them in [this post](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49). Will you please give it a try and let us know? Since it's been awhile, I would suggest starting with a fresh repo clone.
