### ISSUE TITLE
dev.to zoomed in on Twitter webview 

### ISSUE THREAD

**Issue by erinb223** [forem/forem#18684]
**Describe the bug**

We received [this report via Twitter from user @StephenGFriend](https://twitter.com/StephenGFriend/status/1587827507461513216):

"This has been happening for many many months. Well before I upgraded to 16. And over multiple Twitter app updates. I usually just view from other devices (when I remember)."

**To Reproduce**

I was not able to reproduce this behavior on my device (iPhone 11, iOS 15.7.1, Twitter v9.34.1). Suggested steps are listed anyway.

1. Open Twitter app on smartphone
2. Select dev.to link ([this is the particular Tweet + link that raised the issue](https://twitter.com/ThePracticalDev/status/1587818611372089346))

**Expected behavior**

Here is what a user should see:
![erin bug report](https://user-images.githubusercontent.com/66445787/199831225-bd3d6b90-ae04-47dd-98fc-168a01b5f82e.jpeg)

**Screenshots**

Here is the bug that prompted the report:
![stephen bug report](https://user-images.githubusercontent.com/66445787/199831339-7d1a20c6-7812-4c65-a62a-519ea6e136a6.jpeg)

**Smartphone (please complete the following information):**

IPhone 11 Pro Max
16.0 iOS
9.34.1 Twitter

**Comment by mrpaulishaili** [comment]
This can possibly be a bug related to iOS devices specifically.

**Comment by rt4914** [comment]
I have tested it on following configuration and it working correctly.

**Real Device**
iPhone 8 
14.7.1 iOS
9.34.7 Twitter

**Simulators**
iPhone SE 3rd generation
15.5 iOS 
9.34.7 Twitter

Unfortunately I was unable to test it on iOS 16 because of device/simulator constraints.

**Comment by mirie** [comment]
Assigning to myself to try to replicate next week

**Comment by PhilipHow** [comment]
Working for me.
