### ISSUE TITLE
Description for badges are appearing twice

### ISSUE THREAD

**Issue by surajondev** [forem/forem#18680]
**Describe the bug**

In the badge section of the profile, when we click on it to see it in focus. The description of the tag is repeated twice instead of just on time. 

**To Reproduce**

1. Go to any dev.to any profile that has at least one badge
2. Scroll down to the badges section 
3. Click on any badge to have it in focus
4. In the description of the badge. the description is repeated twice.

**Expected behavior**

It should not be repeated two times. It should display descriptions only once.

**Screenshots**

![bug image](https://user-images.githubusercontent.com/67496096/199660203-563663f7-c203-43a8-bca5-b917f050c483.png)

**Comment by Ridhwana** [comment]
This was closed by https://github.com/forem/forem/pull/18723
