### ISSUE TITLE
Can't submit my comment on the welcome thread

### ISSUE THREAD

**Issue by ZB333ZB** [forem/forem#18693]
I tried different on Firefox and Chrome browsers.

**Describe the bug**

I tried to submit my comment on the [welcome thread](https://dev.to/welcome). 

My comment: 

> Hello everyone! I am a simple mid 20's worker. Coding is my new hobby. I started my journey just a month ago with Responsive Web Design from [freeCodeCamp](https://freecodecamp.org). I already got my first certificate in life and created my [web page](https://zb333zb.github.io). I like it. It’s cool. I plan to continue on.

First, it was submitted. But when I reloaded the page, it disappeared. I tried to submit the same comment again, but got a popup message:

> Error posting comment. Your comment could not be posted due to an error: Body markdown has already been taken

**To Reproduce**

Go to [dev.to/welcome](https://dev.to/welcome)

Write a comment and submit

After your comment appears among other comments, reload page. The comment disappears. Or you might see the error message:
> Error posting comment. Your comment could not be posted due to an error: Body markdown has already been taken

**Expected behavior**

The comment does not disappear after reloading the page. You should get any error messages

**Screenshots**

https://imagizer.imageshack.com/img922/3100/3Rcr79.png
https://imagizer.imageshack.com/img923/5227/8Ci4qd.png

**Desktop (please complete the following information):**

- OS, version: Windows 10 Pro 21H2
- Browser, version: Firefox 106.0.5 (64 bits), Chrome 107.0.5304.88 (64 bits)

**Smartphone (please complete the following information):**

no

**Additional context**

no

**Comment by mirie** [comment]
Closing as we unfortunately haven't been able to replicate this issue :(
