### ISSUE TITLE
Pages API

### ISSUE THREAD

**Issue by mirie** [forem/forem#18713]
## User Story (Who / What / Why)

As an admin (or super admin), I’d like to be able to CRUD pages via the API in order to improve my ability to administrate pages on my Forem.

## Definition of Done

- [ ]  Users with admin privileges or higher (IE including superadmins) are able to use the Pages API
- [ ]  Pages API supports:
    - [ ]  Creating new pages
    - [ ]  Reading existing pages
    - [ ]  Updating existing pages
    - [ ]  Deleting pages
- [ ]  Page attributes to support:
    - [ ]  body_html
    - [ ]  body_json
    - [ ]  body_markdown
    - [ ]  description
    - [ ]  is_top_level_path
    - [ ]  landing_page
    - [ ]  processed_html	(Read Only)
    - [ ]  slug
    - [ ]  social_image
    - [ ]  template
    - [ ]  title

**Comment by rt4914** [comment]
I am not sure what this "pages" feature is, can anyone link where I can see this or mainly experiment with this?

**Comment by pkfrank** [comment]
> I am not sure what this "pages" feature is, can anyone link where I can see this or mainly experiment with this?

Hey @rt4914 , you can use this feature via `/admin/customization/pages`.

**Comment by rt4914** [comment]
Thanks @pkfrank 

I have following queries:
- Our of all the page attributes I was unable to find `landing_page` on `admin/customization/pages/new`
- Is there any specific place where we write documentation of such APIs, for example this issue tracks task for pages-API, if we have created some similar API in past, it is mentioned in some documentation?

**Comment by jaw6** [comment]
@rt4914 

* `landing_page` might not be visible if you are not a "private Forem" -- there are some details in [the PR that introduced this here](https://github.com/forem/forem/pull/13819)
* Our API documentation lives [here](https://developers.forem.com/api/v1), our V1 API is a [`swagger`](https://swagger.io/) API, the docs are generated automatically via the `rswagger` gem, out of [this sub-folder](https://github.com/forem/forem/tree/main/spec/requests/api/v1/docs) -- the process is a bit opaque, the coverage is not at 100%, and my understanding of it is rather cargo-culty, but as I understand it, our goal is to get more (eventually _all_) of the V1 API into this form of documentation over time.

**Comment by jaw6** [comment]
@pkfrank @benhalpern For understanding the context of this issue and our organization goals, how does `Pages API` fit into `Reach`, `Activation`, `Retention`, and `Engagement` ?

**Comment by pkfrank** [comment]
Hey @jaw6, thanks for the question.  Here's how we're thinking about this initiative in the context of our priorities:

Some of the projects represented on the Prod/Eng board are features that are **directly in support of a defined company initiative**.  For instance, we've taken on an array of "Display Ads" work that has been immediately put to use by our Community team to highlight different features of the platform.  Oftentimes we'll describe a priority by contextualizing how it supports our RARE goals (Reach, Activation, Retention, Engagement).

Some of the projects represented here fit more into the bucket of **core building block** that moves us towards a higher degree of system extensibility and flexibility.  They'll likely play an important part of our future goals (happy to talk through how this Pages API may impact RARE goals), but are less directly connected to an immediate priority.  This second bucket is where I'd classify this Pages API project.

It's our goal to ensure that the Prod/Eng board represents a menu of available work in both buckets.  Doing so hopefully puts us in a place where Engineers feel empowered to pick up projects as it makes sense based on our other priorities, personal bandwidth, interest, related work, etc.

As such, I think we can officially move out of the "Next" (Priority Column), and into "Ready for Dev" to better represent this as something on our backlog as available work, vs. something that needs to hop to the front of the line.

Hope that helps.
