### ISSUE TITLE
[API v1 docs] Organizations

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18745]
We are using [rswag](https://github.com/rswag/rswag) to implement API V1 docs and are missing the following Organizations endpoints:

- [x] [An organization](https://developers.forem.com/api/v0#tag/organizations/operation/getOrganization)
- [x] [Organization's users](https://developers.forem.com/api/v0#tag/organizations/operation/getOrgUsers)
- [x] [Organization's listings](https://developers.forem.com/api/v0#tag/organizations/operation/getOrgListings)
- [x] [Organization's Articles](https://developers.forem.com/api/v0#tag/organizations/operation/getOrgArticles)

rswag files are added as `spec/requests/api/v1/docs/<file>_spec.rb` files. Check out this example if you need inspiration on how these look like.

**Comment by indrajith-007** [comment]
Hi  @fdocr , i like to work on this issue. Can you please assign the issue to me

**Comment by fdocr** [comment]
Thank you for offering to help with this issue @indrajith-007! I just assigned this issue to you

**Comment by indrajith-007** [comment]
Thank you @fdocr

**Comment by mirie** [comment]
@indrajith-007 Excited to see you interested in working on this issue! Please let us know if you have any questions or would like feedback on a draft PR :)

**Comment by mirie** [comment]
@indrajith-007 Just checking in one more time -- it's totally fine if you're unable to work on this right now. If I don't see a message from you by tomorrow, I will un-assign.
