### ISSUE TITLE
[API v1 docs] Tags

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18748]
We are using [rswag](https://github.com/rswag/rswag) to implement API V1 docs and are missing the following Tags endpoints:

- [ ] [Followed tags](https://developers.forem.com/api/v0#tag/tags/operation/getFollowedTags)
- [ ] [Tags](https://developers.forem.com/api/v0#tag/tags/operation/getTags)

rswag files are added as `spec/requests/api/v1/docs/<file>_spec.rb` files. Check out [this example](https://github.com/forem/forem/pull/18797) if you need inspiration on how these look like.

**Comment by mirie** [comment]
@rt4914 curious if you already have a branch going? If not, I can open it up to community contribution

**Comment by rt4914** [comment]
Unassigned myself since I am not actively working on this.
