### ISSUE TITLE
[API v1 docs] Podcast Episodes

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18746]
We are using [rswag](https://github.com/rswag/rswag) to implement API V1 docs and are missing the following Podcast Episodes endpoints:

- [ ] [Published podcast episodes](https://developers.forem.com/api/v0#tag/podcast-episodes/operation/getPodcastEpisodes)

rswag files are added as `spec/requests/api/v1/docs/<file>_spec.rb` files. Check out [this](https://github.com/forem/forem/pull/18797) example if you need inspiration on how these look like.

**Comment by mirie** [comment]
@lightalloy I added you to this one! See here for a little more context: https://forem-team.slack.com/archives/C7GE84DEJ/p1669909421021339
