### ISSUE TITLE
Replace Bootstrap in Admin with Crayons

### ISSUE THREAD

**Issue by mirie** [forem/forem#18756]
# User Story (Who / What / Why)
As a developer, I want a consistent styling approach on Admin and the main application so that it is easier to develop and there's consistent look and feel.

## Additional Context

At some point we were using a library called [Bootstrap](https://github.com/forem/forem/blob/1cb86b973ad5ee44438489c284b636ded60fc824/app/views/layouts/admin.html.erb#L20) to do the styling on the admin. However, we then built our own design system and started using that on the main application but didn't completely remove Bootstrap from the Admin app. As a result, it is still impacting some of the styles on the admin and causing inconsistent in preview and the end-user output.

Back in March, Pawel had tried to remove a ton of legacy Bootstrap dependant code from our admin app by converting it to use Crayons, however priorities changed and we had to switch gears. He has removed most of the bootstrap with a small portion of work still remaining to get rid of the entire library. 

More from the same issue: https://github.com/forem/forem/issues/18392#issuecomment-1238955086

This will involve some investigative work where we identify all the places that bootstrap is applying intentionally or unintentionally on the interface and updating to Crayons. After removing Bootstrap, we will need to go through the UI and ensure that we style with Crayons in the cases where Bootstrap was unintentionally styling the UI.

### Replace Bootstrap classes with Crayons and fix styling in admin

- [x] admin/badge_achievements
- [x] admin/badges
- [x] admin/broadcasts
- [x] admin/comments
- [x] admin/consumer_apps
- [x] admin/data_update_scripts
- [x] admin/feedback_messages
- [x] admin/listing_categories
- [x] admin/listings
- [x] admin/moderator_actions
- [x] admin/mods
- [x] admin/navigation_links
- [x] admin/organizations
- [x] admin/pages
- [x] admin/podcasts
- [x] admin/privileged_reactions
- [x] admin/profile_fields
- [x] admin/response_templates
- [x] admin/settings
- [x] admin/shared
- [x] admin/tags
- [x] admin/tools
- [x] admin/users
- [x] admin/welcome

### Final Cleanup
- [ ] Revisit all the PRs created for this issue, gather the glossary of bootstrap classes which were removed, and then recheck all those classes in entire codebase and update those too.
- [ ] Remove Bootstrap library

## QA Coordination:

- [ ] @anujbhavsar96 to participate in Design QA for this so loop in so we can QA on either Canary 1 or 2

**Comment by mirie** [comment]
Notes from refinement meeting: 
- may need to check for JS dependencies and then we can remove JQuery as well
- Potential to break user facing stuff — we need to go through every page to check that everything is looking fine. Testing portion on this will be tedious

How are we committed to Crayons at this stage?
- Do we want to maintain Tailwind ?
- How much does it diverge?
- Crayons library is not well-documented
- Pawell had actually tried to move to Tailwind, but faced some challenges on implementation and feedback 
https://github.com/forem/rfcs/pull/51

**Comment by mirie** [comment]
@rt4914 since this is a multi-part issue that will not just be worked out with a single PR, do you mind linking PRs in the issue so we can track progress/what's remaining? Can you also note when the checkboxes (see description) for the definition of done are completed? Thanks!

**Comment by rt4914** [comment]
> * admin/

@mirie Update:

I have updated the issue description to track more granular progress.
There are 25 folders/pages which contains bootstrap and right now **17** folders are fixed+merged, **5** and in PR review and **3** are pending.
