### ISSUE TITLE
[API v1 docs] Videos

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18750]
We are using [rswag](https://github.com/rswag/rswag) to implement API V1 docs and are missing the following Videos endpoints:

- [ ] [Articles with a video](https://developers.forem.com/api/v0#tag/videos/operation/getArticlesWithVideo)

rswag files are added as `spec/requests/api/v1/docs/<file>_spec.rb` files. Check out [this](https://github.com/forem/forem/pull/18797) example if you need inspiration on how these look like.

**Comment by Benmuiruri** [comment]
HI @fdocr, I see there are several issues related to the **[API v1 docs] Tags**.  I'd like to work on them, but could you please clarify something? When you say, "Check out this example if you need inspiration on how these look like." which example are you referring to?

**Comment by fdocr** [comment]
Hi @Benmuiruri, thank you for volunteering to help with this effort!

The link on "**this** example" (on the issue description) should redirect you to a PR that was merged already. That PR adds a new endpoint to a spec file that uses rswag to define the docs for one endpoint in particular (in that example it's implementing `GET /articles/me/all`).

Some more pointers for clarity:
- Rswag docs live in `spec/requests/api/v1/docs/<controller>_spec.rb`
- As you can see in the example PR you execute a command in the terminal and the OpenAPI definition JSON is generated based on it
   - `SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag PATTERN="spec/requests/api/v1/**/*_spec.rb"`

Let me know if you have any other questions and if you want me to assign you this issue to start off 🙂

**Comment by Benmuiruri** [comment]
Thanks Fernando. I will work on it this week. In case of any clarification or questions along the way, I will ping you.

**Comment by mirie** [comment]
Hey @Benmuiruri how's this going? Do you have any questions?

**Comment by mirie** [comment]
I'm unassigning this for now. Please let us know if you're still interested in working on it!

**Comment by Luke-kb** [comment]
@mirie I'd be happy to work on this one :)
