### ISSUE TITLE
Can't access to admin dashbord 

### ISSUE THREAD

**Issue by melakhvision** [forem/forem#18765]
I deployed the forem with docker but http://localhost:3000/admin shows 404, page not found

**Screenshot**

![Screenshot_3](https://user-images.githubusercontent.com/45154979/203297397-7e8baf38-a773-4ad0-a70a-1b1e481679be.png)

How can please help ?

**Server (please complete the following information):**
- Device:
- OS, Linux:
- Browser, Firefox:
- Deployement, Docker

**Comment by oscarnancy78** [comment]
Hi,
Oscar here,
Facing same problem like this[,](https://teertoday.net/) issue when I check dashbord this message showing (can't access to admin dashbord).
If you get correct answer plz mention me.
Thanks.

**Comment by alexandersalt78** [comment]
Hi,
Alexander here,
The same issue is happening to me as well; when I check my [site](https://boundown.com/can-vr-headset-replace-monitor/) dashboard, I get the message (can't access the admin dashboard).
I would be grateful if you could let me know if the answer is correct.
Thank you.

**Comment by churchillsonm95** [comment]
Hi,
Churchillson Markus here,
I'm experiencing the same problem; when I go to my [site](https://thecourtdirect.com/east-fishkill-town-court/) dashboard, I receive the message (can't access admin dashboard).
I would appreciate it if you could let me know if the answer is correct.
I appreciate your help.

**Comment by mirie** [comment]
Closing as I wasn't able to replicate with a few new fresh installs
