### ISSUE TITLE
Unable to set up forem using docker

### ISSUE THREAD

**Issue by KarthikRaju391** [forem/forem#18766]
I am trying to set up Forem on my local machine. I am using WSL with windows and used the docker method to set up the application as shown in the [forem docs](https://developers.forem.com/getting-started/installation/containers) but when I am trying to set up the docker container, I get the following error. 
Is there something that I am doing the wrong way? It would help me a lot if someone can help me with this. Thanks!

![Screenshot_20221117_110049](https://user-images.githubusercontent.com/67912316/203352365-f5247a31-424c-46c6-bfc0-5476d4148a10.png)

**Comment by mirie** [comment]
We have re-vamped our local dev options/steps so closing for now. If there's still a continued issue, please open up a new issue! Thank you so much
