### ISSUE TITLE
Dark mode design issues

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18786]
This issue is focused on design issues related to dark mode.

## Bookmark icon Org page
On any organisation page, the bookmark-icon is not clearly visible on article-items. (check bottom right corner in screenshot, right next to `1 min read`)

<img width="500" alt="Screenshot 2022-11-28 at 1 13 05 PM" src="https://user-images.githubusercontent.com/9396084/204234250-98f9f5c9-82ac-4d14-9f8d-d8a9d47ca60f.png">

## Background color for set level of experience

While setting the experience level for any post there are 3 stages: selected, not-selected, hover. In selected and hover state the background is not clearly visible because of dark theme. (In screenshot notice how background of 3 and 5.)
<img width="360" alt="Screenshot 2022-11-28 at 1 16 48 PM" src="https://user-images.githubusercontent.com/9396084/204234656-28378885-f232-440d-8955-79165f5a0913.png">

**Comment by BhuvanAde** [comment]
Hello, I'm Bhuvan Ade, a UI/UX Designer. I believe I can work on this issue.

**Comment by unmeates234** [comment]
Hi,
Meates here,
I was also facing the same problem on my website (https://testgriffor.net/) but when i update latest version of wordpress the issue resolved automatically. Update latest may be your issue be resolved.
