### ISSUE TITLE
Round Robin Improvements: Notifications

### ISSUE THREAD

**Issue by mirie** [forem/forem#18796]
## User Story (Who / What / Why)

As an admin, I’d like to adjust the “Round Robin Notification” system in order to improve my ability to nudge certain actions via this platform mechanic.

We will have bigger changes later, but starting with a couple small adjustments to send only to recently active trusted users, and to send to a few more of them. (I.e. fewer notifications buried with inactive trusted users)

We will also adjust the copy within config, but this does not have code changes necessary at the moment.

## Definition of Done V1

**Targeting Logic**:

- [x]  Only send to users with `last_reacted_at` within the last week — otherwise keep same query.
- [x]  Adjust number of sent from 2 to 4

**Copy Change**:
- [ ]  Admin to directly add new copy to `welcome_html` within language config. TBD on exact copy.

This is to be done / sorted out closer to deployment.

## Additional Context

You can check out these notifications in Metabase here: [https://forem.metabaseapp.com/question/305-notifications-where-action-is-moderation](https://forem.metabaseapp.com/question/305-notifications-where-action-is-moderation)

The notifications looks like this:
![Image](https://user-images.githubusercontent.com/896728/204904129-b46cbacb-9e49-4669-9efd-107d78926e56.png)

**Comment by mirie** [comment]
@pkfrank:

Question:

These appear to be just in app notifications (based on the screenshot), but I want to confirm if the change will apply to in-app (web) notifications, mobile notifications, and email notifications? OR just app (web) notifications?
2. This is what the user notifications setting page looks like:

![Image](https://user-images.githubusercontent.com/896728/204906526-31d67889-29f7-4190-8cf3-63eb71cdddae.png)

The settings page implies certain cadences for notifications (weekly, immediately, or occasionally). How does this user expectation square with this change?

Are we prioritizing certain types of notifications? (comments, follows, badges) or does the change apply to any type of notification?

**Comment by jaw6** [comment]
I'm still learning my way around the codebase, but here's how I am unpacking this:

* I initially had a hard time locating a "round robin" notification
* There is a setting, though, called `mod_roundrobin_notifications` which is also aliased as [`subscribed_to_mod_roundrobin_notifications?`](https://github.com/forem/forem/blob/main/app/models/users/notification_setting.rb#L14) (ironically, this alias is not actually used -- all calls to this attribute appear to use `mod_roundrobin_notifications` directly)
* This setting is used to select [`available_moderators`](https://github.com/forem/forem/blob/main/app/services/notifications/moderation.rb#L7-L9) (and a specific moderator is [selected randomly](https://github.com/forem/forem/blob/main/app/workers/notifications/moderation_notification_worker.rb#L8-L22))
* If we send a notification, we update [`last_moderation_notification`](https://github.com/forem/forem/blob/main/app/services/notifications/moderation/send.rb#L32) - creating a "round robin _ish_" moderation cycle

So, I _think_ the idea here would be to tweak [`available_moderators`](https://github.com/forem/forem/blob/main/app/services/notifications/moderation.rb#L7-L9) to only return users who have been active in the last week. (If this set is empty, the `ModerationNotificationWorker` is no-op.)

I don't understand this part though:

> Adjust number of sent from 2 to 4

**Comment by benhalpern** [comment]
Yes, @jaw6, we should be able to adjust the query in `available_moderators`.

In `app/workers/notifications/moderation_notification_worker.rb` we have this line of code:

`random_moderators = Notifications::Moderation.available_moderators.order(Arel.sql("RANDOM()")).first(2)`... which specifies that from the query, we select 2 "available moderators", and we want to bump this to 4.

So _of_ the query, we want to send to 4 people if there are 4 qualifying, instead of 2.

If you want to refactor anything given the difficulties finding where to look, based on the language, definitely support that if you feel it's worthwhile!

**Comment by benhalpern** [comment]
@mirie This change shouldn't affect the expectations for notifications at all.

The language of "occasional" is still appropriate, as the fundamental algorithm still balances the distribution approximately the same way, with the biggest adjustment being to not bother sending stuff to inactive qualifying members.

**Comment by mirie** [comment]
Why do this? Basically this round round improvement addresses: Who do we send to and what do we send

Who do we send to is limited to trusted users (2-3K who may or may not be active). We want to change  this so that it's not so limited. Hypothesis is more tools to our disposal around community engagement / tools on the platform and to open it up beyond this.

What is the message we send?
- User X just added a comment, please send them some love or check for spam
- Goal is to help support/moderate engagement for incoming user interactions/content

Other Technical Considerations:
Refactoring would be good to do - naming conventions / making it clearer what is happening in the code -- Let's do this as a fast follow to this issue. @mirie to create the issue. @jaw6 I'll create the issue / can you add some more thoughts on what specific refactoring should be addressed.

**Comment by Ridhwana** [comment]
@benhalpern the issue says to use:

> Only send to users with `last_reacted_at` within the last week — otherwise keep same query.`

Is there a reason why we want to use `last_reacted_at` property to determine active users? 

Unless I'm reading the code wrong, it looks like `last_reacted_at` is only updated when a user goes to `http://localhost:3000/readinglist` and toggles the archive state of an item on the reading list. 

https://github.com/forem/forem/blob/c24e227f559dc42aa0c259db62404950aca0063c/app/javascript/readingList/readingList.jsx#L112-L115

https://github.com/forem/forem/blob/c24e227f559dc42aa0c259db62404950aca0063c/app/controllers/reading_list_items_controller.rb#L13

**Comment by benhalpern** [comment]
Yeah @Ridhwana, we could use any other reasonably equivalent "recent activity metric" — and it seems like what you're saying is that `last_reacted_at` is not, in fact, giving us what we'd expect to be "last reacted at".

I'd say you could go about finding an alternative implementation here — and anything close enough to a simple measure for recent activity is fine — _or_ update the behavior of `last_reacted_at` to better reflect the expectation here.

**Comment by Ridhwana** [comment]
Moved this back to In Progress because the copy changes are still required.

**Comment by mirie** [comment]
@pkfrank can we get the copy changes for the last requirement?

**Comment by Ridhwana** [comment]
It was determined that there was no copy change needed for the moment.

 https://forem-team.slack.com/archives/C02C32DLPJP/p1675313978225489?thread_ts=1675255185.434149&cid=C02C32DLPJP

Closing this issue and moving it to complete.
