### ISSUE TITLE
Can't reassign author/reattribute a post under organization page

### ISSUE THREAD

**Issue by ellativity** [forem/forem#18800]
**Describe the bug**

When attempting to reattribute a post via the Org Dashboard, the dropdown menu with different org member names is functional and changes can be saved on the Org Dashboard. However, the changes aren't reflect in the post itself, which continues to be attributed to the previous author.

**To Reproduce**

1. Navigate to `/dashboard` and select relevant organization from the drop-down menu at the top-right of the table.
2. Expand the **More Options Menu** for the relevant post, by clicking on the three dots to the far right-hand side of the row.
3. Select the relevant author from the list of org members and save changes.
4. Open or refresh the post to review changes.
5. The post has not been assigned to the selected author.

**Expected behavior**

The post should be assigned to the selected author, and this should be reflected at the top of the post.

**Screenshots**

[Video here](https://www.loom.com/share/66e55391715042328a0d7a1fd7efb425)

**Desktop (please complete the following information):**

- attempted on both MacOS and Windows 
- using Firefox, Chrome, Safari, Brave

**Comment by mirie** [comment]
@maestromac Do you think this is due to caching, or is this a known bug?

**Comment by mirie** [comment]
@maestromac / also cc @fdocr : Just noting that I setup some test data on Canary 1 and was able to switch authors of a post attributed to an author without issue. Check out https://canary1.forem.lol/pets/testing-changing-owner-of-post-4o7n

**Comment by michael-tharrington** [comment]
Just to note that a DEV member reported this issue recently as well so it does appear to be affecting multiple folks from different Forem communities.

**Comment by maestromac** [comment]
The original request was resolved but given that this was due to a lack of proper error messages when reattributing a post that belongs to a series, I'm going to supersede this with a new bug report
