### ISSUE TITLE
Refactoring fast follow for Round Robin Improvements: Notifications

### ISSUE THREAD

**Issue by mirie** [forem/forem#18809]
The "round-robin notifications" system could be clearer.

This is a fast follow for #18796. [Over there](https://github.com/forem/forem/issues/18796), the focus is on tweaking the system to produce better outputs. But, in the course of refining that issue, [we noticed](https://github.com/forem/forem/issues/18796#issuecomment-1335348579) that the names and methods involved in this sub-system could be clearer.

> * @jaw6 initially had a hard time locating a "round robin" notification
> * There is a setting, though, called `mod_roundrobin_notifications` which is also aliased as [`subscribed_to_mod_roundrobin_notifications?`](https://github.com/forem/forem/blob/main/app/models/users/notification_setting.rb#L14) (ironically, this alias is not actually used -- all calls to this attribute appear to use `mod_roundrobin_notifications` directly)
> * This setting is used to select [`available_moderators`](https://github.com/forem/forem/blob/main/app/services/notifications/moderation.rb#L7-L9) (and a specific moderator is [selected randomly](https://github.com/forem/forem/blob/main/app/workers/notifications/moderation_notification_worker.rb#L8-L22))
> * If we send a notification, we update [`last_moderation_notification`](https://github.com/forem/forem/blob/main/app/services/notifications/moderation/send.rb#L32) - creating a "round robin _ish_" moderation cycle

**Comment by Ridhwana** [comment]
@mirie is this issue ready to work on? I've been working on https://github.com/forem/forem/issues/18796 and could start on this next if has been estimated already.
