### ISSUE TITLE
Flaky test: Sign in test helper failed to sign in user before/during test

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18839]
**Describe the bug**

```
`cy.request()` failed on: http://localhost/users/sign_in - 500 error from test server
```

We are seeing the sign in Cypress helper fail across a few different tests:
- https://buildpulse.io/@forem/forem/tests/5122085700
- https://buildpulse.io/@forem/forem/tests/5122085969
- https://buildpulse.io/@forem/forem/tests/5122086032
- https://buildpulse.io/@forem/forem/tests/5122160367
- https://buildpulse.io/@forem/forem/tests/5122085855

**Expected behavior**

The sign in helper should be a reliable way to work with across the test suite and not fail ocassionally

**Comment by mirie** [comment]
@fdocr I have forgotten -- are we waiting until end of this week to see if we can move to closed?

**Comment by mirie** [comment]
Buildpulse reported this occurring again: https://buildpulse.io/@forem/forem/tests/5122085914, moving back to in progress

> The first fix added a delay on the retry, but we could try up to 3 (or a higher number too) retries before it fails (keeping the small delays between retries) and maybe that will fix the issue

**Comment by maestromac** [comment]
I'm going to leverage the "cy.sessions" feature in the [latest cypress version](https://github.com/forem/forem/pull/19119). It will allow the test browser to store session cookies and avoid signing in (POST) during test setup. I am very hopeful this will speed things up and cut down flaky changes.
