### ISSUE TITLE
Flaky test: Timed out retrying after 4000ms: Unable to find an accessible element with the role

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18838]
**Describe the bug**

We are seeing a few flaky tests failing due to an element not being visible (perhaps outside the screen or invisible). The Buildpulse reports are the following

- https://buildpulse.io/@forem/forem/tests/5122085937
- https://buildpulse.io/@forem/forem/tests/5122085991

**Expected behavior**

These tests should be reliable instead of failing occasionally

**Comment by maestromac** [comment]
CI artifact implemented https://github.com/forem/forem/pull/18980

**Comment by maestromac** [comment]
Still investigating :(

I'm also going to separate this into 2 issues because I think they are unrelated.

**Comment by mirie** [comment]
@maestromac should we close this issue in favor for the two you are planning to create?

**Comment by maestromac** [comment]
No need, I will edit this issue and open another one.

**Comment by maestromac** [comment]
https://github.com/forem/forem/commit/670d82ac3be638f81877092d46866d2bdc85b77f
