### ISSUE TITLE
Development Approach and Standards

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#18836]
Work on aligning our shared understanding of development approach and standards to ensure engineering excellence. This will entail:

- Discussion and documentation of coding principles that we hold high
- Alignment on coding standards, testing philosophy, what are Rails patterns we want to stick to, CSS, accessibility, etc
- Logging/Monitoring practice

Some priorities to document:

- [ ] Diagram of Architecture of the application
- [x] Service Objects
- [x] Testing/QA section
- [ ] Caching
- [x] Javascript
- [x] Feature Flag pages
- [ ] Things could be generally grouped better in developer documentation. 
- [ ] Add a Community post (dev.to) as an announcement / increase awareness that documentation has been updated and what's coming next.

For the future: 
-  Tools that we use in production and what they’re used for: DataDog (January), Honeybadger (chat to Mac about possibly adding these once he does his snack and study)
- Current state of localization (will only probably be added in 2023 once more decisions are made)

**Comment by Ridhwana** [comment]
PR list:

- https://github.com/forem/forem-docs/pull/98
- https://github.com/forem/forem-docs/pull/97
- https://github.com/forem/forem-docs/pull/96
- https://github.com/forem/forem-docs/pull/95

**Comment by Ridhwana** [comment]
@mirie I've sent PRs for what I think are the biggest pain points thus far. I'll wait for the reviews and adjust accordingly. 

I will be holding off on updating the caching docs this week. I'll schedule a session with @benhalpern when we get back in the new year to chat through the caching strategy a bit more. I feel like I could use a bit more understanding and knowledge transfer on the topic before attempting to write up about it. I'll also complete the architecture diagram alongside the caching docs since the outstanding part on the diagram is caching. 

In the meantime @mirie is the plan still to create a notion page that links to the developer docs? If so, I can add a Development Approach and Standards page that just links to https://developers.forem.com/ or I could just add it to the "how we work" section.

**Comment by mirie** [comment]
Added a link to developers.forem.com to Notion on Engineering > How we work > "Expectations" section

**Comment by mirie** [comment]
@Ridhwana How can I help with the caching strategy conversation?

**Comment by mirie** [comment]
@Ridhwana caching sounds like a large lift? How do you feel about splitting this one out from this issue? Additionally, does it make sense to close this issue with an architecture diagram? Is there anything else that you think is important to document as this initial first pass?

**Comment by Ridhwana** [comment]
> caching sounds like a large lift? How do you feel about splitting this one out from this issue?
It is a much bigger lift and this is a good idea. I'll close it and create another issue for caching.

> close this issue with an architecture diagram?
I think the architecture diagram fits in with the caching, because the caching parts are the parts on that diagram that need more clarity.
