### ISSUE TITLE
Prevent users from changing the author when a post is part of a post series

### ISSUE THREAD

**Issue by maestromac** [forem/forem#18851]
**Describe the bug**
Posts that are part of a post series are unable to have different authors - this is because the post series belongs to a single author. When changing the author of a post that belongs to a series from one author to another author, the change fails, but the user does not receive an error explaining why there is an issue.

**To Reproduce**

1. Navigate to /dashboard and select the relevant organization from the drop-down menu at the top-right of the table.
2. Expand the More Options Menu for the relevant post by clicking on the three dots to the far right-hand side of the row.
3. Select a different author from the list of org members and save changes.
4. Open or refresh the post to review changes.
5.  The post has not been assigned to the selected author.

See [Loom](https://www.loom.com/share/036258f939ca4d78a21fae241b1ee2ad?t=98&sid=45f783a2-88ed-40e5-a414-4d8313916d7d) from @michael-tharrington showing this issue.

**Expected behavior**

- The "Author" drop-down list in the "More Options Menu" should be disabled when the post is part of a series with a note above the author drop-down list stating, "Unable to change the author of a post that is part of a series".

## Designs

**Current**

![image](https://github.com/forem/forem/assets/1628871/8f7d8be2-5e27-40e6-8a3d-2f72b25f7482)

**Expected**

![image](https://github.com/forem/forem/assets/1628871/d75c6c37-7995-4298-9509-0c5bd4d74829)

**Comment by mirie** [comment]
@michael-tharrington Just curious -- have you received more reports on this? I still have been unable to replicate this problem by following the steps listed above.

**Comment by michael-tharrington** [comment]
Hmmm... I really don't remember this one and I don't think we've seen this one reported @mirie. I could test it though if you'd like!

**Comment by michael-tharrington** [comment]
Here's a video that replicates the issue at hand (I timestamped it at the good bit):

https://www.loom.com/share/036258f939ca4d78a21fae241b1ee2ad?t=98&sid=45f783a2-88ed-40e5-a414-4d8313916d7d
