### ISSUE TITLE
Developer Tools become inactive when clicked on Extensions

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18863]
**Describe the bug**

Developer Tools become inactive when clicked on Extensions

**To Reproduce**

1. Sign in as admin locally
2. Visit `/admin/advanced/tools`
3. Notice how `Developer Tools` option on left-side-menu is highlighted/active.
4. Now click on `Extensions` tab
5. Notice that `Developer Tools` is not active anymore.

**Expected behavior**

If `Tools` or `Extensions` are selected the `Developer Tools` should remain highlighted.

**Screenshots**

<img width="796" alt="Screenshot 2022-12-15 at 2 13 50 PM" src="https://user-images.githubusercontent.com/9396084/207813396-ed8a10d5-d0cf-4336-b281-4cd90564db30.png">

**Comment by dancristianb** [comment]
hey @rt4914 👋 I can pick up this one 😀

**Comment by rt4914** [comment]
@dancristianb Sure. I am assigning this to you.

**Comment by dancristianb** [comment]
@mirie yep still interested 😀 will try to send out the PR today / tomorrow 😀
