### ISSUE TITLE
Bad view style in post for Gists files

### ISSUE THREAD

**Issue by chef88val** [forem/forem#18893]
**Describe the bug**
When i open a post with gists file i see this:
![image](https://user-images.githubusercontent.com/7094117/209301463-89cc98b3-a090-44eb-a0b0-097c12ae5a8f.png)

**To Reproduce**
Go to this URL https://dev.to/qarunqb/tdd-in-angular-dependency-injection-and-mocking-4jnh

**Expected behavior**

**Screenshots**

**Desktop:**
Google Chrome, Microsoft Edge
- OS, version: Windows 11
- Browser, version: Google Chrome, Microsoft Edge

**Smartphone (please complete the following information):**

- Device:
**Additional context**
I fixed whit this code => document.querySelectorAll('td[id*="LC1"').forEach(el=>el.style.setProperty("width", "500px", "important"))
![image](https://user-images.githubusercontent.com/7094117/209302474-965bb6fa-4b7a-4c52-bf8a-95549b25cac5.png)

**Comment by esponges** [comment]
Apparently this issue doesn't happen in Safari. But Chrome (tested in 108.0.5359.125) and Edge (108.0.1462.54) present this issue (more info [here](https://github.com/forem/forem/issues/18931)). 

Hopefully this could be adressed soon, gists embedding is a awesome way of presenting readable code in the articles.

**Comment by suntong** [comment]
> Apparently this issue is present in older versions of Chrome, not only `108`.

And much older than 106 as well, as mine is 100: 

`Version 100.0.4896.127 (Official Build) (64-bit)`

and it renders the following blog with exact same problem as reported in OP:
https://dev.to/suntong/are-you-still-coding-go-cli-handling-by-hand-5g2h

It was working fine when the blog was originally posted on Oct 15, 2020.

**Comment by esponges** [comment]
>   I fixed whit this code => document.querySelectorAll('td[id*="LC1"').forEach(el=>el.style.setProperty("width", "500px", "important"))

As per mentioned by @chef88val , the issue lies in the `<td>` elements width property from the `.ltag_gist-liquid-tag` embed gist.

![td-fix](https://user-images.githubusercontent.com/68973307/211208986-72ce26a8-3b6d-45ec-960a-8e265d9ada39.png)

**Comment by maestromac** [comment]
Resolved with https://github.com/forem/forem/pull/18933
