### ISSUE TITLE
Blocked IPs for RSS feeds

### ISSUE THREAD

**Issue by MichaelSolati** [forem/forem#18920]
**Describe the bug**

I use MeetEdgar for some social posts and want it to automatically read my dev.to posts. I'm using my RSS feed `https://dev.to/feed/USERNAME`, but the feed can't be ingested. Reaching out to their dev team they said their IP is being blocked by the dev.to firewall and recommended we asked for their IPs to not be blocked.

54.173.229.200
54.175.230.252

**To Reproduce**

Submit RSS feed to MeetEdgar.

**Expected behavior**

RSS is digested.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by maestromac** [comment]
Thank you for creating this issue @MichaelSolati 

Interesting. Our RSS feed is publicly available and we don't block anyone from access it. How url are you using and exactly what error are you/they getting?

**Comment by mirie** [comment]
As we haven't received additional information for this issue we can't proceed so will close for now. You're welcome to re-open with additional information if this is still an issue. Thanks!
