### ISSUE TITLE
Migrate Article initializers to Pack tags

### ISSUE THREAD

**Issue by lboogie04** [forem/forem#18972]
In an effort to migrate away from asset pipeline, the current initializers need to be migrated to pack tags via Webpacker and initialized in the perspective view/page.

The `initializeArticleDate()` and `initializeArticleReactions()` should be migrated to a pack tag and added to the perspective views in which this code should be initialized.

**Comment by TechSlugz** [comment]
Hi superstar Devs! My name is David. I am an extremely noobie rookie level self taught Dev. I have completed freecodecamps JS cert and have coded a few websites to become interactive and created some basic apps and so on. I'd like to get involved in helping out with bug fixes and adding new features to apps or even creating a project from scratch! I am really eager to learn more and use my coding skills and gain a bit more experience if there are any of these pull requests that are not too complicated for me to get started on? I'd really appreciate being allowed to get involved in anything code orientated at all no matter how small so please let me know if there are any areas that I can assist
