### ISSUE TITLE
Migrate BaseTracking initializer to Pack tag

### ISSUE THREAD

**Issue by lboogie04** [forem/forem#18971]
In an effort to migrate away from asset pipeline, the current initializers need to be migrated to pack tags via Webpacker and initialized in the perspective view/page.

The `baseTracking` initializer should be initialized globally(`application.html.erb`) when moved to a pack tag.

**Comment by mirie** [comment]
@lboogie04 is it possible to aim to wrap this up this week? I'm not sure how large of an effort this is.
