### ISSUE TITLE
Verify our identity on Mastodon using `rel=me` attribute

### ISSUE THREAD

**Issue by mirie** [forem/forem#18978]
### Discussed in https://github.com/forem/forem/discussions/18822

<div type='discussions-op-text'>

<sup>Originally posted by **erinb223** December  7, 2022</sup>
Hey team! Got a Mastodon-related quick win for ya today: profile verification.

The most effective way to verify our identity on Mastodon is to add a link with a `rel=me` attribute to both our site homepage (dev.to) and our GitHub repo (github.com/forem/forem). [Mastodon has documentation on how to do it and how it works](https://docs.joinmastodon.org/user/profile/#verification).

This is what our profile looks like currently:
![A screenshot of our Mastodon profile, with all our links boxed in standard gray.](https://user-images.githubusercontent.com/66445787/206271752-c33ab8c0-c613-4f47-b915-22f5b672c440.png)

Once we have verified our ownership of our domain and our repo using the above method, they will look like these:
![A screenshot of Scott Hanselman's Mastodon profile, which shows three of his links boxed in green with a checkmark.](https://user-images.githubusercontent.com/66445787/206272056-03dd0523-71c3-45b6-be9c-c33179345b93.png)

One way to incorporate this on the dev.to homepage, while also encouraging Mastodon users to engage with us on their social media platform of choice, could be to add a Mastodon icon to our social media icon selection here:
![A screenshot of our homepage with the social media icons circled in red](https://user-images.githubusercontent.com/66445787/206273141-953f248a-eb99-4609-824f-02633f285700.png)

Verification on Mastodon is key for the following reasons:
- It proves that we are the real dev.to, not a mirror
- It makes our audience more likely to trust us on the platform
- Users can safely, confidently follow verified links off the platform and onto our sites

Thanks for your consideration! I think this could be something of a quick win and I appreciate your work on it.</div>

**Comment by mirie** [comment]
@fdocr can we prioritize this one as I think this will be a quick one to address? Thanks!

**Comment by mirie** [comment]
Re-opening because we can see the field on Canary1 but not on dev.to: https://forem-team.slack.com/archives/C7GE84DEJ/p1677168036334199

**Comment by mirie** [comment]
@maestromac I'm going to assign to you first to see if there's an issue with code deployment (since the functionality works on one instance and not another). If you don't see anything in that respect, please let me know and I'll have a product eng take a look at the code itself

**Comment by jaw6** [comment]
Sorry, this feels like a dumb question, but does `dev.to` have anything in the `mastodon` social media settings area?

This is Canary1:

<img width="895" alt="Screen Shot 2023-03-01 at 16 38 21" src="https://user-images.githubusercontent.com/2077/222188196-3c7dcb63-fa32-4f8e-bde6-4e00ab788260.png">

After I went to this form and put in a mastodon URL here, I _then_ had a `rel="me"` link to mastodon (the 'https://fosstodon.org/@thepracticaldev' part in this screenshot is _placeholder_ text, not a "real" setting).

If we _have_ something set in this form and it _still_ isn't showing up, then I'll give caching a :eyes:

**Comment by mirie** [comment]
Unfortunately this is what is on dev.to:

<img width="1065" alt="Screen Shot 2023-03-01 at 11 02 49 AM" src="https://user-images.githubusercontent.com/896728/222194624-3f0c976a-b835-411a-a534-61162bf48b72.png">

and latest commit is: `09291b420515d265eca031b431a5937bc63c3bb3` which is why I feel baffled

**Comment by jaw6** [comment]
I _might_ have figured this out: https://github.com/forem/forem/pull/19191

**Comment by erinb223** [comment]
The Mastodon icon is now functional and links to our Fosstodon profile — yay!

However, the input doesn't allow me to use a `rel=me` attribute, which was the driving force for opening this issue. I tried adding the `rel=me` tag into the input and it attempted to direct to `https://dev.to/<a rel="me" href="https://fosstodon.org/@thepracticaldev">Mastodon</a>`.
![Screen Shot 2023-03-08 at 2 46 45 PM (2)](https://user-images.githubusercontent.com/66445787/223830283-13b525d0-2dca-41f3-84ad-b1e541c63d33.png)

Is there a way to use this feature to incorporate a `rel=me` attribute? If not, what is the best course of action for me to pursue in order to get this set up and verify our identity on Fosstodon?

**Comment by jaw6** [comment]
@erinb223 The way this has been set up, you should not need to include `rel=me` in the link. If there's _any_ link in the `mastodon` field, it will get the `rel=me` treatment. (_Technically_, all the socials media links [get the `rel=me` treatment](https://github.com/forem/forem/blob/276a53b5b43327038dfaf111479ab28ff3b34ec5/app/views/layouts/_social_media.html.erb#L10).)

**Comment by erinb223** [comment]
Ok, good to know! The verification change hasn't taken yet, if it doesn't
take after a few days what's my next troubleshooting step?

**Comment by jaw6** [comment]
Maybe try editing the link on fosstodon and see if that forces an update?

**Comment by erinb223** [comment]
It worked!!! We are all set. Thanks a million for all your support on this
issue.
