### ISSUE TITLE
Update link for dark-mode settings used in Display ad

### ISSUE THREAD

**Issue by rt4914** [forem/forem#18974]
**Describe the bug**

Technically it's not a bug but an improvement.

On article page, under `comments` and above `read next` we show various display ads to user so that they can understand more things about dev.to

For one such instance, I was shown to use `Dark mode` settings. When I click on that link it redirects to https://dev.to/settings but I think it would be better to redirect it to https://dev.to/settings/customization where user can direct change dark/light mode settings.

<img width="1512" alt="Screenshot 2023-01-18 at 12 19 58 PM" src="https://user-images.githubusercontent.com/9396084/213105406-f3ff9c5e-1400-4872-a552-4565d036d639.png">

**Comment by rt4914** [comment]
@mirie I think the display ad needs to be updated with correct link as mentioned in description. Who is the correct person who can make this change?

**Comment by mirie** [comment]
cc @noah-brinker to check in on the links / feedback for this particular billboard. I'm going to assign this as well

**Comment by noah-brinker** [comment]
Good catch and I made the change on the dark mode ads to the more accurate URL.

cc: @rachelfazio2 FYI
