### ISSUE TITLE
Migrate Notification initializer to Pack tag

### ISSUE THREAD

**Issue by lboogie04** [forem/forem#18998]
In an effort to migrate away from asset pipeline, the current initializers need to be migrated to pack tags via Webpacker and initialized in the perspective view/page.

The `initNotifications()` should be migrated to a pack tag and added to the perspective views in which this code should be initialized.

**Comment by Ridhwana** [comment]
Correct me if I'm wrong but from my understanding these pack files are not tested. If they aren't, would we want to add some tests for them as we migrate them?  cc @mirie @lboogie04

**Comment by Ridhwana** [comment]
Also curious to get @maestromac's perspective on this as he works on increasing test coverage.

**Comment by mirie** [comment]
@lboogie04 / @maestromac what are your thoughts on this? I added some buffer to include testing

**Comment by maestromac** [comment]
Yes, I think this is a ripe opportunity to also add test along with the migration and I apologize for the additional work this may put on @lboogie04
