### ISSUE TITLE
Migrate CommentPreview initializer to Pack tag

### ISSUE THREAD

**Issue by lboogie04** [forem/forem#19000]
In an effort to migrate away from asset pipeline, the current initializers need to be migrated to pack tags via Webpacker and initialized in the perspective view/page.

The `initializeCommentPreview()` should be migrated to a pack tag and added to the perspective views in which this code should be initialized.

Upon completion of this migration, initializeCommentDate in [intializeCommentsPage](https://github.com/forem/forem/pull/19025/files#r1090117632) can be removed.

**Comment by mirie** [comment]
@lboogie04 since you'll be picking this one up when you have bandwidth (after multiple reactions, billboards), can you add an estimate on this one?
