### ISSUE TITLE
Old articles doesn't indexing

### ISSUE THREAD

**Issue by dinozavrix** [forem/forem#19039]
**Describe the bug**

All old atricles removed from indexing
Example: https://ux.pub/editorial/kak-sozdat-bolshoie-razmytoie-izobrazhieniie-v-photoshop-illustrator-ili-sketch-4mod

We have moved all of the old content to the forem and we have articles with old post dates. Google start removing them from indexing after forem was updated

**To Reproduce**

1. Change "published at" of any article to a date prior to 2016.
2. Noindex added to article

![image](https://user-images.githubusercontent.com/2471773/215805816-714fbd94-2aba-48bc-ac5c-9fa9f60fdd40.png)

**Expected behavior**

All articles, even old ones, are indexed

**Additional context**

Maybe caused by this commit
https://github.com/forem/forem/commit/c57acc25ea9814c1ba29e986673e26bf463eccaf#diff-24503fd25ed68e6ebceee4951bc4f9b255b197278d4aa9d86ef9d5afe3f26bea

All articles published before 14 July 2017 doesn't indexing? 
https://github.com/forem/forem/blob/main/app/models/article.rb
```
def skip_indexing?
    # should the article be skipped indexed by crawlers?
    # true if unpublished, or spammy,
    # or low score, not featured, and from a user with no comments
    !published ||
      (score < Settings::UserExperience.index_minimum_score &&
       user.comments_count < 1 &&
       !featured) ||
      published_at.to_i < 1_500_000_000 ||
      score < -1
  end
```

Thank you for your help!

**Comment by dinozavrix** [comment]
Hi @fdocr ! Can you please check `published_at.to_i < 1_500_000_000 ||` condition, maybe it is not needed and can be removed? Most likely it is this that leads to the fact that a huge number of articles with old dates are not indexed by Google. Thank you in advance!

**Comment by Xwixpacer** [comment]
https://www.copy.ai/?via=maryann

**Comment by Xwixpacer** [comment]
https://www.copy.ai/?via=maryann

**Comment by Xwixpacer** [comment]
https://www.copy.ai/?via=maryann
