### ISSUE TITLE
Couldn't "Sign up with Apple"

### ISSUE THREAD

**Issue by aebone** [forem/forem#19045]
I'm trying to sign up with my Apple account but keep receiving the same error:

> _Could not authenticate you from Apple because "Nonce invalid"._

Apparently, there's no problem with the requests. When trying to sign up for the first I choose the "hide my email" option in the Apple screen.

**To Reproduce**

1. Go to https://dev.to/enter?state=new-user
2. Click on 'Sign up with Apple' 
3. Type your credentials

NOTE: The same error happens when trying to [log in ](https://dev.to/enter)clicking on "Continue with Apple"

**Screenshots**

<img width="1362" alt="Screen Shot 2023-02-01 at 13 09 32" src="https://user-images.githubusercontent.com/2421827/216098684-4dd7e481-c7b3-4b1d-9263-c4fc46543f99.png">

**Comment by maxmousee** [comment]
Happening to me as well :(
