### ISSUE TITLE
Update Forem Docs

### ISSUE THREAD

**Issue by lboogie04** [forem/forem#19052]
Upon completion of all initializers being migrated, current Forem documentation needs to be updated to reference those changes. 

The [Initializers page](https://developers.forem.com/frontend/javascript-approaches/initializers) should be deprecated and the [Webpack page](https://developers.forem.com/frontend/javascript-approaches/packs) should be updated with any corresponding changes.

**Comment by mirie** [comment]
@lboogie04 I moved this to Ready for Dev. It would be great to close this out by Friday, of course after priority product work is completed~!
