### ISSUE TITLE
Page unique_cross_model_slug seems misconfigured

### ISSUE THREAD

**Issue by jaw6** [forem/forem#19117]
I noticed while working on #19009 and reviewing #19024 that our `Page` model doesn't seem properly configured for `unique_cross_model_slug`. 

That is to say: when one creates a new page that duplicates a slug from a non-page object (a username, organization or podcast slug, say), `UniqueCrossModelSlugValidator` is fine. However, if one tries to create a page that duplicates a slug from a _page_, `UniqueCrossModelSlugValidator` does not check the other pages. The effect is that we wind up raising a Postgres exception, from attempting to violate the db constraint.

I'm not sure, but it seems as though `UniqueCrossModelSlugValidator` assumes that the model will handle its own uniqueness -- that _may_ be true for other models (I have not rigorously checked), but was _not true_ for pages prior to #19009.

I patched in a [quick-fix](https://github.com/forem/forem/pull/19009/commits/86230b99ad2bc87278d556909864267f871bc4dc) in #19009 but we ought to figure out a proper fix, including tests (and, if properly configured, that quick fix might become unnecessary), and possibly we should consider updating `UniqueCrossModelSlugValidator` to handle "own model" case, as well.

**Comment by gorangorun** [comment]
Can i work on this?

**Comment by jaw6** [comment]
@gorangorun Oh, I am sorry! I had not seen your message this morning. I don't _need_ to be the one working on this issue, this just happened to be the next issue in our queue. I will take a look at your PR next!
