### ISSUE TITLE
Leftmost icon should be on top when there are multiple, stacked reactions on Index page

### ISSUE THREAD

**Issue by mirie** [forem/forem#19137]
In below image, the icons are in form of stack and the right most icon is on top but instead the leftmost icon should be on top and right most icon should be at bottom.

![Image](https://user-images.githubusercontent.com/9396084/217456353-d9e85bcc-c705-48cf-bfcb-fb694bf754e0.png)

^ This happens on index page view and is blocked by [#19135](https://github.com/forem/forem/issues/19135)

**Comment by jaw6** [comment]
This _was_ an issue, at one time, but I believe it's been addressed at this point `cc` @rt4914 

<img width="627" alt="Screen Shot 2023-02-17 at 11 35 30" src="https://user-images.githubusercontent.com/2077/219620982-ed772ee7-479c-4d9b-b759-d2e3f808d651.png">

**Comment by mirie** [comment]
Ah! it could be that because it was unchecked in the other issue, I thought it was still pending :) @anujbhavsar96 can you confirm that this can be closed?

**Comment by anujbhavsar96** [comment]
The above mocks look perfect @mirie ✨. You can close this issue.

**Comment by rt4914** [comment]
@mirie @jaw6 @anujbhavsar96 This is still pending. I haven't finished it yet. Also I checked it on latest `main` code and I able to see that it has not been solved.
<img width="756" alt="Screenshot 2023-02-20 at 6 48 17 PM" src="https://user-images.githubusercontent.com/9396084/220119820-ae73f227-a3f1-49de-a138-c1e225080411.png">

**Comment by rt4914** [comment]
Just created this PR https://github.com/forem/forem/pull/19157
