### ISSUE TITLE
Update posts on index page to display the multiple reactions

### ISSUE THREAD

**Issue by mirie** [forem/forem#19135]
This is a followup (post-launch) issue for Multiple reactions to address the following inconsistency:

### Problem

On index pages, there was an inconsistency on how reactions are displayed on the list of Posts. This was first noticed https://github.com/forem/forem/issues/19064#issuecomment-1421240035 and https://github.com/forem/forem/issues/19064#issuecomment-1424891619.

The following [issue](https://github.com/forem/forem/issues/19134) made a change so that the previous/old heart icon + reaction count displayed on Posts on index pages.

### Requirement
This issue is focused on resolving the display discrepancy so that we can show the selected multiple reactions, like this:

![Image](https://user-images.githubusercontent.com/896728/219492832-f9eab325-578f-4c72-be39-c3a635e3a9f9.png)

Other notes: 
Please also see this comment on a closed issue: https://github.com/forem/forem/issues/19064#issuecomment-1434294365

**Comment by mirie** [comment]
@jaw6 does this also address: https://github.com/forem/forem/issues/19144 ? 

Basically my question is: Does this PR update the display so that multiple reactions are displayed consistently everywhere a reaction would appear (all index pages)?

**Comment by mirie** [comment]
We talked yesterday and @jaw6 confirmed that it does. However, additional QA would be appreciated. @maestromac can you deploy to a Canary instance (I guess Canary 1?) and then @anujbhavsar96 can you assist with QA? We are concerned that we are missing all the index places (profile, homepage, tags).

**Comment by anujbhavsar96** [comment]
Let me know once it's deployed to Canary. I'll do the QA @mirie

**Comment by jaw6** [comment]
@anujbhavsar96 It's been deployed to canary1

**Comment by jaw6** [comment]
There's an issue with loading image assets that I'm looking into already:
<img width="611" alt="Screen Shot 2023-03-01 at 16 55 29" src="https://user-images.githubusercontent.com/2077/222192743-a02ce5a8-7c41-4a8e-a0ce-75bf8c111b21.png">
