### ISSUE TITLE
Multiple reaction Post launch: Cleanup feature flags

### ISSUE THREAD

**Issue by mirie** [forem/forem#19132]
* [ ] NotificationsHelper
* [ ] NotificationDecorator
* [ ] `app/views/articles/_actions.html.erb` & re-integrate `app/views/articles/_multiple_reactions.html.erb`
* [ ] `app/views/articles/_multiple_engagements.html.erb`
* [ ] `app/views/articles/_single_story.html.erb`
* [ ] `app/views/articles/_reaction_button.html.erb`
* [ ] `app/models/reaction.rb`
* [ ] Remove `app/views/articles/_original_reactions.html.erb`, `app/views/notifications/_original_aggregate_reactions.html.erb`, `app/views/notifications/_original_single_reaction.html.erb`
* [ ] `spec/helpers/notifications_helper_spec.rb`

**Comment by jaw6** [comment]
I'll also note that this may change, depending on how things rollout — for example, I suspect we might re-wire `index` templates after "launch" but before removing the feature-flag, due to issues [described here](https://github.com/forem/forem/issues/19064#issuecomment-1434294365)

**Comment by jaw6** [comment]
I have [a branch](https://github.com/forem/forem/compare/jaw6/enable_multiple_reactions_index...jaw6/multiple_reactions_flag_cleanup?expand=1) _almost_ ready for this, but [multiple reactions #index](https://github.com/forem/forem/pull/19169/) needs to merge before it's ready to go.
