### ISSUE TITLE
The hover state is missing for reaction inside the reaction drawer

### ISSUE THREAD

**Issue by mirie** [forem/forem#19140]
- [ ] The hover state is missing for reaction inside the reaction drawer. Just a little gray highlight.
<img width="1084" alt="SCR-20230216-ihu" src="https://user-images.githubusercontent.com/84626054/219301629-3f0e5fdc-be87-4872-97eb-5f58aebcaf57.png">

- [ ] Dark mode - Active reaction style adjustment. And the hover state is missing. Similar to issue above
<img width="966" alt="SCR-20230216-ia6" src="https://user-images.githubusercontent.com/84626054/219299165-8f1be25b-43ed-4300-bf7f-df6c054e3ef2.png">

**Comment by dancristianb** [comment]
Hey @mirie 👋 I can have a look at this one 😀
