### ISSUE TITLE
Add user status from profiles to the report section

### ISSUE THREAD

**Issue by mirie** [forem/forem#19211]
## Problem

Admins would like to streamline their workflow on the reports page so that: 
- They can more easily identify potential new mods
- Better support trusted members reporting spam by directing them to a faster spam reporting workflow via the mod panel _(as opposed to https://dev.to/report-abuse)_

Currently when admins review the reporting page, they cannot immediately tell if someone is already a trusted member. Admins would like to be able to see the user status (trusted, warned, suspended, etc) next to the reporter's name in the list of reports on `/admin/moderation/reports`.

### Stakeholders
This is a feature request from the Community team, specifically: @michael-tharrington 

## Requirements

- [Figma link](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?node-id=1500%3A5744)
- Add user status (used on the user profile page) to the report on the list of reports on `admin/moderation/reports` 

## Definition of Done
- [ ] The user's current status is displayed to the right of the reporter name for each report on `/admin/moderation/reports`
- [ ] The same look and feel for the user-status component can be used here (see [trusted](https://canary1.forem.lol/admin/member_manager/users/54), [good standing](https://canary1.forem.lol/admin/member_manager/users/50), [warned](https://canary1.forem.lol/admin/member_manager/users/42), [suspended](https://canary1.forem.lol/admin/member_manager/users/41) as examples of what these user statuses look like)

### More detail on why this matters/admin workflows

- We often look to folks who have sent in valid abuse reports as good potential moderators. There’s no way to filter by amount of valid abuse reports sent in on `/admin/member_manager/users`. But if we notice a reporter sent in a valid report and they aren’t trusted, we could potentially upgrade their role.
- Occasionally, when reviewing a long-form report, it is helpful to have additional context on other statuses as well (example, if the reporter has already been warned for inciting arguments/disingenuous reports)

### Reference links: 
- https://forem-team.slack.com/archives/C02BP4UG2N9/p1677082085211969
- https://forem-team.slack.com/archives/C02C32DLPJP/p1678084103350309

**Comment by rt4914** [comment]
@mirie The PR review did not took a lot of time. The mistake was from my end, in that PR there was before/after image which was basically needed to approve the PR correctly. In this I made a mistake of adding "before" image twice and therefore there was no visual change. Because of this @jaw6 had to revisit this PR after I updated the PR with correct image.
