### ISSUE TITLE
Update DisplayAd.for_display to better support community-type ads

### ISSUE THREAD

**Issue by jaw6** [forem/forem#19224]
## User Story (Who / What / Why)
We want to further modify the "display rules" to better support community-type ads and Pro Tools Organizations.

## Requirements:
* [ ] A post that has a non-nil `organization_id` should **only** show `in-house` and _matching_ `community`-type ads.
* [ ] A post that has a non-nil `organization_id` should show matching `community`-type ads if any exist (that is:_only_ show `in-house`-type ads if there are no matching `community`-type ad)

It's likely this will require changes in `DisplayAd.for_display` and `FilteredAdsQuery` to support two query passes — one to find any matching `community`-type ads, a second to find `in-house`-type ads if no ads were found in the first query. Both types of ads should continue to use the `success` prioritization and random sampling. Other constraints (user opt-out, tag targeting, placement areas, etc.) continue to apply.

### Related PRs:
* Initial work updating `FilteredAdsQuery` to support `community` and `external`-type ads [19189](https://github.com/forem/forem/pull/19189)
* Update to support ad opt-out settings and fix a bug with nil `organization_id` [19208](https://github.com/forem/forem/pull/19208)

### Considerations: 
* This allows us to have no `external`-type ads on an organization's content without adding a dependency between `forem-tools` and `forem-core` (ie, `forem-core` does not know which organizations are paying for Pro Tools accounts, but can still guarantee that no `external` ads appear on those posts). The trade-off is that we won't serve `external`-type ads on some organization content that could _potentially_ have been available.
* The idea is that Pro Tools organizations have the ability to "completely control" the billboards appearing adjacent to their content (with a fall-back to an in-house ad if they haven't created any billboards yet).
* :link: There's more background discussion on the need for "extremely clear display rules" in 📝 [this document](https://docs.google.com/document/d/1hSmgjXpqqHeWH3L2g70rosMm4lGCAgX5HXVJvyMIHzE/edit#)

**Comment by Xwixpacer** [comment]
https://trafficadbar.com/Maryannbustamante

**Comment by Xwixpacer** [comment]
https://trafficadbar.com/Maryannbustamante

**Comment by Xwixpacer** [comment]
https://trafficadbar.com/Maryannbustamante
