### ISSUE TITLE
Add an article exclusion list to Billboards

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#19226]
## User Story (Who / What / Why)

We're adding new functionality that allows us to explicitly add article IDs to a per-billboard “exclusion list,” ensuring that this specific Billboard never appears on or alongside articles with matching IDs.

**_Why is this important? What’s the bigger impact?_**

We’re continuing to incrementally improve Billboards, and we will be accomplishing precise user recommendations with the [recommendation list model](https://docs.google.com/document/d/1cjvcQ31Yi-86m9mgghDTeUX5r30RGkZ5RQbBzTjC1nE/edit#heading=h.jlg0fhnrgskt). There is, however, some content targeting which will immediately unlock the broader usefulness of billboards, and the article exclusion list is one.

The reason this is important: **The most important use case for all billboard types is promoting other posts, and we do not want to promote a post next to itself.**

That is: we don’t want [this article](https://dev.to/lydiahallie/javascript-visualized-promises-async-await-5gke) to display [this billboard](https://p-dgfrwr8y.t2.n0.cdn.getcloudapp.com/items/kpuAYBGr/ce922f6e-b8f8-4bbd-98d0-ff456afc44b7.jpg?v=18230f9f30876a369f0a0f8bdd009fca).

First and foremost, billboards should be useful, and not annoying. This cleans up a major functionality gap to role out content billboards maximally.

**_What do we hope to accomplish?_**

We want to build functionality for an explicit “exclusion list”.  When article IDs are added into that list, the billboard should never appear alongside those articles.

## Requirements

We want to add functionality that allows us to explicitly add article IDs to a per-billboard “exclusion list,” ensuring that this specific Billboard never appears on or alongside the articles with matching IDs.

We need to complete the following tasks to achieve the following:

- [ ] Add a new Column on display_ads/billboards called `excluded_article_ids`. It should take an array of article IDs. 

- [ ] This field should be added to the CRUD API for Billboards + update the API documentation accordingly.

- [ ] Update the filter query: This will require changes in `DisplayAd.for_display` and `FilteredAdsQuery`. The filter query will need to have access to the article id it is serving. We'll update the filter query to check if that article id is part of the `article_exclusion_ids`. If it then we want to exclude the billboard from displaying on that article.  This filtering query is only applicable for billboards on the article #show page where there will be an article id present. 

- [ ] Add this field to the “basic” Billboard builder on /admin/customization/display_ads/new. It can be a plain text field with comma-separated article IDs. (This keeps parity where anything achievable via API is possible via “Basic” and vice-versa, and will also be useful for testing).

- [ ] Consider the efficiency of the query, see considerations for more information.

## Considerations:

- For our first use case, Forem Tools will use the API to pass through the `excluded_article_ids`.

- While we are only accounting for contexts where we might pass a single article id into the filter query for reference against a list, there could be use cases in the future for multiple article ids passed into the filter and we want to compare an intersection.

**Comment by Xwixpacer** [comment]
https://www.copy.ai/?via=maryann

**Comment by Xwixpacer** [comment]
https://www.copy.ai/?via=maryann

**Comment by Leobl** [comment]
Hello, is that something I could claim? :thinking:

**Comment by mirie** [comment]
Hi @Leobl Thank you so much for reaching out to raise your hand on this issue. This one is actually for our internal team to work on -- updated the label on this one 😄. 

If you're looking for issues, ones labeled as [ready for dev](https://github.com/forem/forem/issues?q=is%3Aissue+is%3Aopen+label%3A%22ready+for+dev%22), are good ones for community contributions. 

This is more FE, but we have an [open engineering initiative](https://dev.to/devteam/asset-pipeline-js-migration-48ki) that we are hoping to work with external contributors to move forward. Please take a look at this (or the ready for dev tagged issues) and see if there's an issue that looks interesting to work on. 

Again, we appreciate you reaching out and also your contributions~!

**Comment by Ridhwana** [comment]
Hey folks 👋 So I spent some time investigating this a bit more and also chatting through it with Joshua to talk through some options. 

I'm proposing the following: 
The `article_exclusion_ids` can be an `array` datatype that contains integers with an empty array default. Something like below:
```
class AddExcludedArticleIdsToDisplayAds < ActiveRecord::Migration[7.0]
  def change
    add_column :display_ads, :excluded_article_ids, :integer, array: true, default: []
  end
end
```

Some notes: 
- The use case feels similar in the way that its a list of items but also different to tags: Firstly, We'll be storing integers, and integer comparison on an array is faster than string comparison which we use in the tags instance. A point Joshua mentioned in our call is that we're building an exclusion list and not an inclusion list so that changes the dynamics too. 
- Whilst using an array instead of a string introduces different pattern to the `cached_tags_list` it may makes more intuitive sense to use an array and could be a better fit for the problem at hand. 
- Using an `array` type binds us to postgres further but it feels like we're already bound to postgres in other ways and past the point of easily migrating to a different database. 
- With our current purpose (especially with the assumption that we do not plan on adding millions of items to the exclusions list) it feels like this approach + an efficient query in `FilteredAdsQuery` can be sufficient. As a recommendation, we could monitor this queries further and then complete optimizations.

I would love to hear other folks thoughts on this and if they have any further concerns with this approach?

**Comment by benhalpern** [comment]
@Ridhwana That all seems spot on. I'm all for this approach.

> Using an array type binds us to postgres further but it feels like we're already bound to postgres in other ways and past the point of easily migrating to a different database.

Absolutely confirming this. Postgres is our _most_ core technology. _If_ we were to ever port to any new DB, this would be the least of our worries. We should be using any Postgres features which make sense.

> assumption that we do not plan on adding millions of items to the exclusions list

This is correct. The near-term use cases are for this list to generally be _one_ item long, or maybe up to 10 or so items. If we were to find ourselves wanting even hundreds of items in this list, it's likely we'd want to solve that problem in another way.

This is all great from my perspective. I suspect if this is how we roll, this implementation will go smoothly.

**Comment by benhalpern** [comment]
Merged today, working well, already being used via Pro Tools.

We can move this to done, eh @jaw6 ?

**Comment by jaw6** [comment]
@benhalpern :+1:
