### ISSUE TITLE
Allow developer to optionally generate pull-request-specific seed data for a preview environment

### ISSUE THREAD

**Issue by mirie** [forem/forem#19264]
## Summary

We have a bare minimum integration with [Uffizzi](https://www.uffizzi.com/) thanks to external contributions. We currently have Canary 1 and Canary 2 (currently 500-ing) for internal QA. The process for deploying code changes to a Canary instance is manual and requires coordination, and the test data is not refreshed (or cleaned up) on these internal QA environments.

We'd like to take more advantage of the ephemeral preview environments Uffizzi provides for verification and QA per PR.

## Design / Description / Implementation

For the next integration setup, we want to allow developer to generate pull-request-specific seed data for the preview environment.

### Proposed technical approach

Add a special seed file called something like `uffizzi_seeds.rb` which can be included in `seeds.rb` similar to what we have in `if ENV["MODE"] == "STARTER"` in the current `seeds.rb` file.

So along the lines of 

```
if ENV['UFFIZZI_URL']
  load(Rails.root.join('db', 'seeds', 'uffizzi_seeds.rb'))
end
```

`uffizzi_seeds.rb` can _always_ include "default" considerations for uffizzi itself, but any developer can modify the file to include data and/or instructions (which could be displayed as a modal uffizzi always shows).

And then the file will always be scrubbed upon merge, by adding those instructions to the `.gitattributes`, always giving the next developer a clean `uffizzi_seeds.rb` to work off of.

```
db/uffizzi_seeds.rb merge=ours
```

## Definition of Done

- [x] Uffizzi account setup is complete (see this [comment](https://github.com/forem/forem/issues/19264#issuecomment-1489115855))
- [ ] The preview environment uses PR-specific seed data

**Comment by mirie** [comment]
@maestromac is our Uffizzi account fully setup?

Steps I took:
1. I clicked on [View Application Logs etc.](https://app.uffizzi.com/projects/4723/deployments/20637/containers) link on [this PR](https://github.com/forem/forem/pull/19275)
2. I was prompted to login via Github and enter my work email
3. I confirmed my email (I was sent a confirmation email to verify my identity)
4. I see a message banner to complete account setup (Action required)

![Image](https://user-images.githubusercontent.com/896728/228636307-6d704a33-6554-45cc-9c9f-0f5e99734683.png)

I am assuming this means we have to update the requirements to finish setting up our integration but didn't know if the message I'm seeing simply means I needed to be added to the organization already setup.

**Comment by maestromac** [comment]
@mirie yeah it is not yet setup.

**Comment by mirie** [comment]
@maestromac do you need any support for the setup portion? I think you have Github admin perms right?

**Comment by maestromac** [comment]
I won't need any additional permission

**Comment by mirie** [comment]
Adding the blocked label as it's on me to close the loop on this ask
