### ISSUE TITLE
Styling adjustment to billboard dropdown

### ISSUE THREAD

**Issue by mirie** [forem/forem#19292]
Design feedback/QA on the billboard dropdown from @anujbhavsar96: 

- The separator line is a bit darker. It should be gray-500
- The report billboard Flag icon looks a bit larger than the other two.

[Here is the Figma reference](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?node-id=1477-5915&t=2RPaGWJOeN7fbr4q-4)

**Comment by Ridhwana** [comment]
@anujbhavsar96 

> The separator line is a bit darker. It should be gray-500

Based on the figma it looks like the separator should be grey-200 not grey-500 right?

**Comment by Ridhwana** [comment]
@anujbhavsar96 does this look better?


![Image](https://user-images.githubusercontent.com/2786819/231432577-f9b46399-ba9e-4227-8bed-4bd1d14a0ab3.png)

**Comment by anujbhavsar96** [comment]
Sorry🤦🏻‍♂️, I meant it should not be grey-500. Right now, it's dark. So yes, it should be grey-200 instead. 

Yes @Ridhwana , the icons and all look perfect. Just want to make sure that the separator line is 1px height right?

**Comment by Ridhwana** [comment]
No probs, and yip the line is 1px now.
