### ISSUE TITLE
Small Round Robin Design and Copy Tweaks

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19296]
## Is your feature request related to a problem? Please describe.

As an Admin, I want to ensure that the “Round Robin” notifications that are sent to `trusted` users effectively convey the “ask” with a clear CTA.

Currently, “at a glance” it is a bit confusing to understand and differentiate this notification from other types of notifications — and therefore a lot of mental overhead to understand and take action.

As a Trusted Member, when I receive a “Round Robin” notification, I want to understand what is being asked of me, and understand how I can opt out of these notifications if I choose to.

## Describe the solution you'd like

Our “Round Robin” functionality currently sends “Trusted” members an occasional notification that asks them to engage with a comment published by a “new user” (as measured by a user making one of their first few comments).

This initiative should start as a **design exploration** around making this notification more aesthetically pleasing and clear.

The updated design should also make the recipient aware that they can opt out of these notifications in their settings.  (The “Moderator Notifications” at the bottom of `/settings/notifications` ).

There are two identical options here, except option 2 has a waving hand illustration. We will go with option 1. [Figma Designs](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?node-id=1720-5869&t=y4mhEp57e84XPCHG-4)

![Final](https://user-images.githubusercontent.com/84626054/232375296-4e36d514-77be-4c56-9ec9-3326c9f0ce49.png)

## Additional context

The _current notification_ [looks like this](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/9ZuKDmrP/b954e66c-9d54-402d-9513-0c74bcadd94b.jpg?v=2627d6256d68fe629b92895a1018bed4).  

Here is a separate notification we send on DEV which [may serve as inspiration](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/jkuAmvLy/129123a3-018d-4a6d-8000-eed2dfbfbc5f.jpg?v=ef55f14a3522e0c514bac10bdaace02b).

The “Round Robin” notification currently uses the “staff user” profile picture which is configurable in `/admin`.  On DEV, our staff user is [https://dev.to/thepracticaldev](https://dev.to/thepracticaldev).  That means that if we wanted to use Sloan on DEV as the associated “user” with the Round Robin notifications, we’d be able to simply change the assigned “staff user” to that account.

Once we’ve improved the design, we’ll have a separate issue related to 1) adjusting the frequency with which we send these, and 2) adding in Round Robin notifications that encourage trusted members to review published posts from new users.

**Comment by pkfrank** [comment]
Discussion from Refinement:

* We'll estimate even though the designs aren't quite yet ready
* There are potentially some gotchas related to caching
* Our view on the caching front is that it's likely okay based on the fact that Notifications are fairly _ephemeral_

**Comment by pkfrank** [comment]
Removing the "needs design" label.  Let's go with Option 1 👍 👋

**Comment by filleduchaos** [comment]
@pkfrank @anujbhavsar96  I'm working on this and I just noticed that the new design doesn't have the moderation actions (thumbsdown & "vomit") as part of the notification while the old one does - is this intended?

**Comment by filleduchaos** [comment]
@pkfrank Thanks! I'll go ahead with removing that then
