### ISSUE TITLE
Received welcome email after email address change

### ISSUE THREAD

**Issue by victoriadrake** [forem/forem#193]
# _BUG_
### Current Behavior

Updated my email to a new address in my dev.to profile. A few minutes later I received an email to the new address with subject "Welcome to dev.to!"

### Expected Behavior

No new welcome email should be sent for an email address update.

**Comment by Zhao-Andy** [comment]
Hey Vicky, thanks for the heads up! We'll fix this soon.

**Comment by jessleenyc** [comment]
@maestromac is this resolved? I thought you had looked into this a little while ago.

**Comment by maestromac** [comment]
I thought I solved it ☹️. It's relatively tricky since it's an async job. I'll take a jab at it again in due time

**Comment by alex-bender** [comment]
Hey guys, any updates on this?
I'm still getting doubled emails, the newsletter ones.

**Comment by jessleenyc** [comment]
This issue isn't fixed yet but I just unsubscribed your old email address from the newsletter list, @alex-bender!

**Comment by alex-bender** [comment]
Whoa! Thanks, great news!

**Comment by jessleenyc** [comment]
@vickylai lmk if you want me to do the same for you!

**Comment by vickylai** [comment]
I’m not getting duplicate emails currently (I think I unsubscribed myself already). Thanks Jess!

**Comment by maestromac** [comment]
not stale

**Comment by Glennmen** [comment]
I am also experiencing this, I changed my email address and it triggered "new account". I thought that I have been active enough on DEV to not be a "new member" anymore 😅

![image](https://user-images.githubusercontent.com/11406433/71312498-f0c72c80-242b-11ea-9e11-fb02c66732cd.png)

![image](https://user-images.githubusercontent.com/11406433/71312506-04729300-242c-11ea-9470-9bd56a7cbd5a.png)

**Comment by Glennmen** [comment]
I am also getting news letters on both email addresses now, changing it doesn't auto unsubscribe the old one. I will manually unsubscribe now.

**Comment by mvsde** [comment]
This is issue is still ongoing. It doesn't really break anything. But it's a bit irritating if I get an email geared towards new users.

**Comment by mstruve** [comment]
I just updated my email and I got a confirmation instruction email. It does have the words "Welcome" in it so I am wondering if that is what people are seeing. I did not get any other new user emails.
<img width="387" alt="confirm_instructions" src="https://user-images.githubusercontent.com/1813380/98417073-e6af1c00-2045-11eb-8044-b7717f959ee0.png">

I am going to go ahead and close this. Please let us know if anyone is still experiencing this issue and if you are please include a screenshot of the email you are receiving, that will help us track down the bug.
