### ISSUE TITLE
Update "Tag Mod" email

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19328]
**Is your feature request related to a problem? Please describe.**

As a Forem Admin, I want to update the email that new tag moderators receive.

**Describe the solution you'd like**

Update the copy as found in [this GDoc](https://docs.google.com/document/d/1XDzPQhnCBoMbiTrr0ue3VEHd115WBq4NXK3bQVdWHTc/edit?usp=sharing).  _Note: visible to Forem Core Team only_.  (As a result, I'm reserving this issue for Forem Team only).

**Additional context**

Relevant files:
* `tag_moderator_confirmation_email` files in [`/forem/tree/main/app/views/mailers/notify_mailer`](https://github.com/forem/forem/tree/main/app/views/mailers/notify_mailer)

Remember that this will apply to _all Forems_, so we can't link to anything that is `dev.to` specific.  Instead, we can link to the `/community-moderation` page.

As outlined in the GDoc, there is one section (at the very end) that is DEV specific.  We can only include this if we have logic that ensures that the section is included only if it's on the DEV instance.

**Comment by Ridhwana** [comment]
![Image](https://user-images.githubusercontent.com/2786819/232067300-017f8127-08f7-45f9-83e0-41e8d88c5a52.png)
