### ISSUE TITLE
Introduce JSBundling with ESBuild

### ISSUE THREAD

**Issue by lboogie04** [forem/forem#19335]
As we submerge on consolidating our Javascript code and compile processes, we want to introduce more efficient and performant solutions for compiling our Javascript. As Webpacker is currently deprecated, in comes ESBuild. ESBuild is a compilation of build tools that makes bundling, compiling and serving Javascript a lot faster and efficient.

**Description**
Install [jsbundling](https://github.com/rails/jsbundling-rails) into the Forem project and initiate it with ESBuild as the bundling option.
```bin/rails javascript:install:esbuild```

The installation script provides the default esbuild configuration which includes:

- Updates to the .gitignore file
- A procfile for running multiple processes with foreman
- A app/assets/builds directory
- Updates to the manifest.js
- A app/javascript/application.js entry point file
- A javascript include tag
- A bin/dev script
- Updates to the package.json dependencies

We need to add the build script to our package.json if it was not added by the installation script. So we add the following to the package.json file.
```
"scripts": { "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds"  }
```

This default build script will make it possible to compile our js assets by running yarn build.

### IMPORTANT!! Must do prior to prod deployment.
**First deploy to a Canary instance **prior** to prod rollout to do some additional QA** 

**Definition of Done**
- JSBundling is successfully installed in our `Gemfile.lock`
- Build script successfully builds in our output directory.

**Expected behavior**
This installation process should not affect any JS rendering or functionality across pages. However, as this is introducing new JS tools that introduce new paradigms, we want to test functionalities across the core domains of the application(admin, articles/post, billboards, etc.) to assure nothing is broken or inoperable.

**Comment by mirie** [comment]
Synced with @dukegreene this afternoon who will add their thoughts by end of day in terms of what's been done/what's next.

**Comment by mirie** [comment]
I'm going to deprioritize and unassign for now in favor of some product work we want to move forward. I'll work with @dukegreene and others on the team to figure out when we have bandwidth to pick this up again as it is a good deal of work and now after chatting with Duke, we have some i18n errors popping up.
