### ISSUE TITLE
notifications/reads not always being fetched when visiting notification center

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19337]
**Describe the bug**

It appears that when I visit notification center lately, most of the time the notification is not clearing for me.

**To Reproduce**

- Visit home page when you have a notification
- Open dev tools
- Click into `/notifications` and observe that `/reads` is not being fetched as it should

**Expected behavior**

This endpoint should fetch and the notifications should clear.

**Additional context**

This may have been caused here:

https://github.com/forem/forem/pull/19124

I believe I am also seeing this behavior on the loading of the "shield" icon on posts when clicking in from the home page. Seems this may be related to how the code now listens for page changes.

**Comment by jaw6** [comment]
For what it's worth, I **do** see `/reads` locally:

<img width="1276" alt="Screen Shot 2023-04-17 at 16 30 14" src="https://user-images.githubusercontent.com/2077/232517561-58abf9f0-70cf-4dbf-bc16-ce5c71ba5a97.png">

**Comment by jaw6** [comment]
Hmmm, I am _also_ seeing it when I replicate on `dev.to`, wonder what I'm doing different?

<img width="1269" alt="Screen Shot 2023-04-17 at 16 32 10" src="https://user-images.githubusercontent.com/2077/232518017-80a0310f-07bd-47ec-a08d-3d4235dea6cb.png">

**Comment by jaw6** [comment]
Trial & error: I don't see `/reads` if I click on the bell, I _do_ see it if I navigate directly to `/notifications`. Guessing it might have something to do with `InstantClick`?
