### ISSUE TITLE
Allow developer to optionally enable relevant feature flags for a preview environment

### ISSUE THREAD

**Issue by mirie** [forem/forem#19342]
## Summary
After  #19264 is completed, we would like to be able to configure the enabled feature flags for a preview environment/ PR. 

## Definition of Done

- [ ] A developer can optionally configure for a given PR the enabled feature flags

**Comment by maestromac** [comment]
Feature flags are already available. They will need to navigate to `/admin/feature_flags/features` and it will be available to enable.

**Comment by mirie** [comment]
@maestromac so it sounds like we should do the manual method -- meaning there's not a way to automate this piece as part of our Uffizzi flow

**Comment by maestromac** [comment]
@mirie yeah I would advocate for the manual method. It is not cumbersome and a good idea for the team to be familiar with the essential feature.
