### ISSUE TITLE
Make embed (liquid tag) border style consistent, and align embed styling to system where possible (Within constraints)

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19343]
## Is your feature request related to a problem? Please describe.

The platform has embeds of varying styles, which are inconsistent and ugly.

As an author or an admin making use of these features in posts, billboards, comments, I'd like these to be of a consistent style that seems native to the current design.

<img width="540" alt="Screen Shot 2023-04-17 at 3 16 29 PM" src="https://user-images.githubusercontent.com/3102842/232588445-d64d49e6-db8f-456a-80be-3b4b0e256d77.png">

The biggest problem is **border**, and that will be the focus of this issue, but along the way other small improvements to fix visual bugs and get any style on par with platform expectations are encouraged along the way.

More on this below in the constraints section, but we need to accomplish these adjustments _purely within the css, and not the markup_, as we cannot reasonably modify embed markup in the current setup. This is a baby step towards a larger overhaul of how we render embeds.

The objective here is to restore some quality control in the overall aesthetic and usability of this functionality in order to continue investing in it as a tool for UX.

## Describe the solution you'd like

All embeds _which have a border_ should have the following styles:

```css
border: 1px solid var(--form-border);
box-shadow: var(--border-smooth);
border-radius: var(--radius-auto);
```

Depending on the classes involved, this may already be partially achieved, or not.

## Requirements / Constraints

The overall "liquid tag" functionality is in a tough state as far of ease of change. We cannot make adjustments to the markup without re-saving posts, and we do not want to approach doing that _until we have a plan of action_, but in the meantime we can dive into the separate SCSS files in order to begin making progress here.

**That is to say, we _can_ modify this file:**

```
app/assets/stylesheets/ltags/UserTag.scss
```

**We _cannot_ easily modify this file:**

```
app/views/users/_liquid.html.erb
```

## Additional context

We have not modified embed style in some time, and have let styles decay. Only changing the SCSS files is not the ideal solution, but it is a step towards better overall health of this functionality, which can be followed on by broader re-evaluation of how we can handle data fetch, data storage, and rendering of embeds.

## [There is still more to do, but here is an example of a PR beginning to address this, feel free to follow and do similar work to clean up other tags](https://github.com/forem/forem/pull/19348)

**Comment by mirie** [comment]
@benhalpern I see there are PRs merged with this issue referenced. Is this issue complete?
