### ISSUE TITLE
Improve “subscribe-to-comment” functionality in notifications

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19350]
## Is your feature request related to a problem? Please describe.

As a member, I want to keep up with the comment threads I care about by having an intuitive experience to manage my comment subscriptions via the `/notifications` page.

## Describe the solution you'd like

We already have the functionality to support subscribing to a comment thread, but we don’t make that functionality very visible.  When you do subscribe, it is unintuitive to _unsubscribe_.

We will be exploring further ways to expand and improve this functionality, but we are first **starting with improvements within the notification area**.

****Requirement 1**: Subscription Indicator / Toggle on Comments**

Comments in `/notifications` should have an indication / toggle that displays the current state of a subscription.

The indication should be full text to help people understand the context of their subscription (see designs).

Note: this feature relates to the existing functionality where users either automatically or explicitly subscribe to comments (found in `notification_subscriptions` ).

****Requirement 2**: Subscription Indicator / Toggle on Articles** 

Articles in `/notifications` should have an indication / toggle that displays the current state of a subscription.

When creating a new comment subscription from one of these Articles in `/notifications`, it should default to creating a subscription for `all_comments`.  (We won’t present the more advanced subscription functionality around all comments vs. top-level vs. author — which does exist on the article page — in this `/notifications` context).

## Requirements / Constraints

The page must not reload when using these toggles.

With regards to older notifications, we either need to:

1) apply this functionality to existing notifications, or
2) guard against this functionality to prevent errors

Remember that Notifications are ephemeral in the system and only stick around for a limited period of time (90 days) before being removed.

## Additional context

Designs (from @anujbhavsar96 )

https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?type=design&node-id=1868-6043&t=pKMa6W7YI8PMGwyK-4

**Comment by anujbhavsar96** [comment]
> We already have the functionality to support subscribing to a comment thread, but we don’t make that functionality very visible. When you do subscribe, it is unintuitive to unsubscribe.

@pkfrank This is an auto-subscribe function, right? And there is no way to opt out of this?

![Frame 4](https://user-images.githubusercontent.com/84626054/233002401-6bf82d6d-8a25-4aa1-81fc-67b361528d23.png)

**Comment by anujbhavsar96** [comment]
> Requirement 1: Subscription Indicator / Toggle on Comments
> 
> Comments in /notifications should have an indication / toggle that displays the current state of a subscription.
> 
> The indication should be full text to help people understand the context of their subscription, so it should be one of these options:
> 
> “Subscribed to my replies” (this applies to commenters receiving replies in that thread) 

@pkfrank Should we have the same options for the comment thread on the post page? Probably under dropdown? E.g. In the case of our own thread, it's auto-subscribe, so we are giving visibility of unsubscribe in /notification and n comment area.

**Comment by PhilipHow** [comment]
@jaw6 

We've aligned on this work in the form of @anujbhavsar96's designs.

Please note that I've highjacked this issue and edited Peter's words to better fit where we landed in the designs - please let me know if the ticket detail doesn't align with the designs and I can update.

**Comment by benhalpern** [comment]
@jaw6 One bug I see: When I change a state, it changes initially but the old state persists upon refresh. The action seems to be applying correctly and this seems specifically a matter of updating the notification.

https://github.com/forem/forem/assets/3102842/3bbe302d-b0ec-4c7a-82e1-59b9d7ade675

This is the only thing I see, and generally everything else so far is behaving as I would expect.

**Comment by jaw6** [comment]
#19739 is deployed now and it's _better_ but it still takes a few seconds for the update to fully "stick", too long to feel "right". I'll take another look at it tomorrow, but right now I'm drawing a blank on what other options we might have.

**Comment by mirie** [comment]
Reopened and moved to PR review column per https://forem-team.slack.com/archives/C7GE84DEJ/p1689344329149429
