### ISSUE TITLE
Comment preview not working

### ISSUE THREAD

**Issue by TracyGJG** [forem/forem#19379]
When preparing a comment to a post there is a 'Preview' button, which try to use to review my comment as would be seen of a reader before saving it. I have noticed for a little while now the button does not appear to do anything.

**To Reproduce**

1. Enter some text and formatting in a comment box.
2. Press the 'Preview' button - nothing happens.

**Expected behavior**

When the Preview button is pressed the comment should be presented as the read would see it, but it does not.
This also the case when editing a comment.

**Screenshots**

![image](https://user-images.githubusercontent.com/4346753/233830764-052e1086-7dac-4bfb-9b32-8a62af606b3c.png)

**Desktop (please complete the following information):**

- OS, version: Window 11 Home
- Browser, version: Google Chrome 112

**Comment by filleduchaos** [comment]
Initial investigation: I can fairly reliably reproduce this on both Safari & Chrome, on both dev.to & my local dev environment - visiting any article page the first time has a broken comment preview button, and reloading the page fixes it. The same for any subsequent article pages you visit

There's a click handler that doesn't get attached on the first visit that does get attached when you reload the page - I'll have to chase down what's responsible for attaching it and what's causing it to fail.

![Chrome DevTools showing the click event listeners for the button (first visit)]("https://user-images.githubusercontent.com/29291843/234382410-40c93a52-09b7-4e8d-bcb9-aadcc003864c.png")

![Chrome DevTools showing the click event listeners for the button, with one extra (reloaded)]("https://user-images.githubusercontent.com/29291843/234382391-705182ec-baad-485d-85b9-ddae97067093.png")
