### ISSUE TITLE
Rename `display_ads` to `billboards`

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#19372]
## User Story (Who / What / Why)

Across the codebase, we refer to a billboard as a "display_ad". Whenever possible we like to see the language in the code and the language in the user facing product match. It makes it easier to have conversations and to collaborate when we are all using the same ubiquitous language.

We want to consolidate the language across the codebase and use the term "billboard" instead of "display_ad". This includes our user facing language, internal variable names, controllers, routes etc. as well as the user facing API.  

The change will favor long-term quality and stability of the core.

## Requirements

**:rotating_light: Let's create smaller PR's implementing iterative changes rather than a big PR implementing all the changes. If there are no tests for something you're changing, let's implement the tests. :rotating_light:**

Our preferred approach would be to do this methodically and possibly maintain an alias, i.e. `class DisplayAd < Billboard; end` where appropriate during the transition.

As a starting point we can:

- [x] Admin::DisplayAdsController
- [x] Rename DisplayAdsController to BillboardsController. While it's customary that controller and model names match, they don't have to and at least this way we'd communicate the same name externally in both UI copy and routes. 
- [x] Amend the routes.
- [x] rename DisplayAdHelper
- [x] Update the API (controller + routes) We can have two separate routes "display_ads" and "billboards" which point to the same controller.
- [x] Rename the `DisplayAdEventsController` and routes
- [x] Rename the DisplayAdEvent model
- [x] Update the variables across the codebase
- [x] Update i18n keys
- [x] Update any UI language
- [x] Update css names/stylesheets
- [x] Update code comments, tests descriptions (if needed)
- [x] Rename role constants and related locales (`"Resource Admin: DisplayAd"`)
- [x] Rename the model (this can be done incrementally and we can maintain an alias at first whilst tackling the controller)
- [x] Do not change the table name but we may have to explicitly tell Rails which table to look for by referencing `self.table_name = "display_ads"` in the model. 
- [x] Change accessed api paths in [forem-tools](https://github.com/forem/forem-tools/)
- [x] #20024
- [x] update [docs](https://admin.forem.com/docs/advanced-customization/display-ads)

This is some of the tasks that I can think of offhand but it will be useful to do a grep like below: 

![Image](https://user-images.githubusercontent.com/2786819/233616792-bcb286c4-6aaa-41fb-99ff-9282f5e80ade.png)

## Considerations

While not quite of the same magnitude, a [similar refactor](https://github.com/forem/forem/pull/7910/) for "Classified Listings" and "Listings" was done previously. One thing that kept the amount of work reasonable was NOT changing the table name, which is why you'll see self.table_name = "classified_listings" in listing.rb and things like this in related models:

```
  has_many :listings, inverse_of: :listing_category,
                      foreign_key: :classified_listing_category_id,
                      dependent: :restrict_with_error
```

This strikes an ok balance between being able to use a single domain name more consistently while reducing the surface area of changes. The obvious downside is a drift between domain model and database table names, but that is the smaller evil compared to using different names in frontend and backend (or rather user-facing and developer-facing) code.

**Comment by mirie** [comment]
@Ridhwana I realized I forgot to catchup with you on how we might break this one down into smaller bits. I'm looking at the checklist but not sure what is intertwined / can't do separately. Can we sort out breaking out just the first task early next week?

**Comment by mirie** [comment]
@Ridhwana talking with @PhilipHow and I chatted and identified this as an issue that @lightalloy can take on. Do you mind connecting with Anna when she returns next week on the plan you've thought of thus far / give some direction on the remaining bits to sequence and think through? Thanks!

**Comment by lightalloy** [comment]
Closing as done, feel free to reopen if you find something else.
