### ISSUE TITLE
Broken styling on Billboard with long organization name

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19408]
**Describe the bug**

When the organization name is on the longer side, it is breaking the styling expectations.

**To Reproduce**

1. Create an organization with a long name
2. Create a promoted billboard under that organization
3. View the billboard in the sidebar context on an article
4. Observe the broken style

**Expected behavior**

The style fits appropriately without squashing images or breaking onto new lines.

**Screenshots**

![example of broken style](https://p-dgfrwr8y.t2.n0.cdn.getcloudapp.com/items/p9ueyXe8/4e2d2f0f-20b8-4dad-98b3-78c1adb34336.jpg?v=37a5f51c39dc50c7761448338d17684c)

**Additional Context**

"Assigning" @benhalpern on this issue so that it's on his radar, but that doesn't _necessarily_ mean he'll jump in to fix it.

**Comment by benhalpern** [comment]
This was fixed
