### ISSUE TITLE
Fix add only one reaction per post

### ISSUE THREAD

**Issue by tejas-gk** [forem/forem#19409]
**Describe the bug**
you can add multiple reactions to one post

**To Reproduce**

1. goto any post
2. goto reactions
3. you can add multiple reactions

**Expected behavior**

A user must be able to give any 1 reaction per post.

 I have already tried it with multiple accounts on multiple devices and received the same behavior.

**Screenshots**
![add multiple reactions](https://user-images.githubusercontent.com/66897829/235492454-1b408318-715c-4b15-b1b5-dc37afe13f52.jpeg)

**Desktop (please complete the following information):**

- OS, version: windows 11

**Smartphone (please complete the following information):**

- Device: Samsung A70 s

**Comment by pkfrank** [comment]
Hi @tejas-gk -- the _expected behavior_ is that a single user can add multiple reactions.

You can read the announcement post [here](https://dev.to/devteam/some-new-features-to-look-forward-to-on-dev-5jk).

With that said, I'm going to close this issue 😄
