### ISSUE TITLE
Secret informations Leaks

### ISSUE THREAD

**Issue by armagiddon7** [forem/forem#19410]
There is same secret informations leaks in the codes 

https://github.com/interledger/testnet/blob/c9bd5573ab9b5dfa9665dd732ec193ee18989d98/docker/dev/docker-compose.yml#L31

    AUTH_SERVER_GRANT_URL: http://rafiki-auth:3006
      AUTH_SERVER_INTROSPECTION_URL: http://rafiki-auth:3007
      ILP_ADDRESS: test.net
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      ADMIN_KEY: admin
      PUBLIC_HOST: http://rafiki-backend
      OPEN_PAYMENTS_URL: http://rafiki-backend
      REDIS_URL: redis://redis:6379/0
      PAYMENT_POINTER_URL: https://rafiki-backend/.well-known/pay
      # Testnet urls - not implemented
      WEBHOOK_URL: http://wallet-backend:3003/rafiki/webhooks
      WEBHOOK_TIMEOUT: 60000
      EXCHANGE_RATES_URL: http://wallet-backend:3003/rafiki/rates
      QUOTE_URL: http://wallet-backend:3003/rafiki/quote

**Comment by pkfrank** [comment]
This seems to relate to a separate repo @ https://github.com/interledger/testnet

As such, I'm closing this issue but encourage you to create an issue in that repo if you believe they should be made aware.
