### ISSUE TITLE
Update logic for “Suggested Tags” in /onboarding

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19414]
## Is your feature request related to a problem? Please describe.

As an admin, I want a more intuitive and effective way to present the most relevant “Suggested Tags” to new users in `/onboarding`.

### Element 1: Suggested Tag Logic

The **current behavior** is that the app strictly looks for the tags that were manually set in Admin > Config > Onboarding > Suggested Tags.

The requested **updated behavior** should use the following logic:

* Tags manually marked as “Prioritize in Onboarding” appear in first (in order of taggings_count)
* Then “supported” tags appear in descending order of popularity (by `taggings_count`)
* We return a max of 45 tags, unless more than 45 are explicitly marked as “Prioritize in Onboarding”, in which case we show all of them.

### Element 2: Marking Tags as Suggested

The **current approach** for marking a tag as “suggested in onboarding” is to add it in the comma separated text field in Admin > Config > Onboarding > Suggested Tags.

The requested **updated approach** is to add a “suggest in onboarding” checkbox to the Tag’s management page in `/admin`.  The checkbox should be added in the same style/location as the current “Supported’ checkbox.  

### Element 1: Suggested Tag Logic

- [ ] New boolean is added to tags table for `suggest_in_onboarding` to be used for the logic
    - [ ] Data is migrated to these elements from the existing config setting
- [ ] Suggested tag logic has been updated to reflect new behavior
- [ ] We provide users with a max of 45 tags, unless more than 45 tags have been manually marked as "Prioritize in Onboarding" in which case we show all of them with that flag

### Element 2: Marking Tags as Suggested flow

- [ ] Text field has been removed from Admin > Config > Onboarding > Suggested Tags
    - [ ] New checkbox has been added to `/admin/content_manager/tags/{tag-id}/edit` near the current “Supported” checkbox
    - [ ] Use the following copy:
        - [ ] **Prioritize Tag in Onboarding**
        - [ ] Adds tag to the list of suggestions in part of new user onboarding

### Element 3: Remove old config data

- [ ] Remove the underlying settings logic

## Additional context

We have a separate issue that will improve the design of this screen in `/onboarding`.

**Comment by Ridhwana** [comment]
Should we also add some sort of data update script to move the suggested tags from the old suggested tags config to the `suggest_in_onboarding` field?

**Comment by pkfrank** [comment]
Note: this issue has been updated to fix the previously-inconsistent requirements.  It now outlines the expected behavior when there are more than 45 tags which have been marked to be prioritized in onboarding.
