### ISSUE TITLE
Background and border color adjustment for the cards

### ISSUE THREAD

**Issue by anujbhavsar96** [forem/forem#19449]
## Is this feature related to a problem? Please describe.

The sidebar cards on the index page, profile page, and article page, including all the billboards, have gray card background. And it's inconsistent with the article card styling and some other card background colors. 

Overall we will make all the card styles consistent by keeping the same background and border colors.

## Describe the solution you’d like

1. Change the background of all the sidebar cards + billboards to white _(same as article cards)_ `background: var(--card-bg)`. Changing the style of the CSS class `.crayons-card--secondary` should change all the sidebar cards's backgrounds. 
2. Change the border of the main cards _(article card, header in profile, etc.)_ to `box-shadow: 0 0 0 1px var(--card-secondary-border)`, same as the sidebar cards border. Changing the value in `.crayons-story` & `.crayons-card` should work. 

| Before | After |
| ------ | ------ |
| ![dev to_](https://github.com/forem/forem/assets/84626054/6aeb806a-fe89-4938-a72e-f92eefecd14c) | ![dev to_ (1)](https://github.com/forem/forem/assets/84626054/9b1bdd3d-f7d9-4be3-8939-6a69ddb115f0) |
| ![dev to_arafat4693_hot-css-tools-for-everyone-1b8o (1)](https://github.com/forem/forem/assets/84626054/a2e2bf8e-a41b-4731-8f9e-121d611bd1ab) | ![dev to_arafat4693_hot-css-tools-for-everyone-1b8o](https://github.com/forem/forem/assets/84626054/48d7ddc1-c1b1-4652-981d-65a221910255) |
| ![dev to_ben](https://github.com/forem/forem/assets/84626054/ff29bde8-8c3b-4ee7-b7b3-bece5148b03f) | ![dev to_arafat4693_hot-css-tools-for-everyone-1b8o (2)](https://github.com/forem/forem/assets/84626054/017482f5-e866-4b17-ba65-5d2227e403ad) |

## Definition of Done

- [ ] Make the above small CSS changes for cards and make their background and border color consistent. And changes should reflect on the index page, article page, user profile page, and org profile pages. 

## Additional Context

It's up to the engineer's best judgment about which class styling to change. The above are just suggestions from my end.

**Comment by mirie** [comment]
@benhalpern assigned this to you and added to Next column on board

**Comment by benhalpern** [comment]
This all looks good to me. Whoever takes this can gut check anything with me, but I think it should be pretty straightforward.
