### ISSUE TITLE
Org page showing wrong number of posts.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19456]
**Describe the bug**

Org pages are only showing a max of 8 posts in the sidebar count

**To Reproduce**

Go to an org page that has more than 8 posts and see that it only has 8 posts

**Expected behavior**

Should show the number related to all posts.

**Screenshots**
<img width="368" alt="Screen Shot 2023-05-11 at 8 53 52 AM" src="https://github.com/forem/forem/assets/3102842/2333c8db-2028-43fd-9ac5-e8f789ac59e4">

**Additional context**

Post here shows the fix: https://forem.dev/ternox/bug-only-8-posts-on-organization-4nmj

The problem is

**Comment by pawelborkar** [comment]
Hi,
I would like to work on this issue.

**Comment by aneshodza** [comment]
I opened a PR for this issue (#19503).
