### ISSUE TITLE
Some url embeds do not fetch metadata as expected

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19461]
**Describe the bug**

When I type `{% embed https://dev.to %}` from any Forem, I get the absolute base fallback embed.

Same with `{% embed https://www.codenewbie.org %}` (which is not a Forem, just the homepage).

I'm not sure what the pattern of which sites are broken vs not broken — but this seems like more than normal "fallback" behavior.

**To Reproduce**

- Go to DEV editor
- Type `{% embed https://thismmalife.com/ %}`
- Click preview and see that you get the fallback "nothing" embed.

**Expected behavior**

I get the fully displayed url embed — and if there is any missing meta tag data, I get a more complete fallback at the very least.

**Screenshots**

<img width="710" alt="Screen Shot 2023-05-11 at 6 31 14 PM" src="https://github.com/forem/forem/assets/3102842/f1afb9ad-bd99-4866-a80d-a6c533941d24">
<img width="733" alt="Screen Shot 2023-05-11 at 6 30 39 PM" src="https://github.com/forem/forem/assets/3102842/524e0ea2-5209-40bf-b37c-46aa269e124a">

**Additional context**

- Twitter was recently changed to load via front-end async query and is unrelated to this issue.

**Comment by Markkop** [comment]
Not sure if related, but I'm unable to embed twitter posts.
Eg. 
```
{% embed https://twitter.com/ThePracticalDev/status/1656788272134119425 %}
```

> Whoops, something went wrong:
> URL provided may have a typo or error; please check and try again

![image](https://github.com/forem/forem/assets/16388408/2732ff26-9f62-458b-b911-2647c8c9f72d)

**Comment by Markkop** [comment]
Hmm, the fix didn't work for `{% embed https://twitter.com/ThePracticalDev/status/1656788272134119425 %}`. 
Do you want me to create a new issue for that, @benhalpern?

**Comment by PhilipHow** [comment]
Please note that the Twitter embed has been changed to a front-end async request and is no longer an issue.

**Comment by PhilipHow** [comment]
Seems like the issues with Dev.to have been fixed pulling metadata but I'm [not getting any metadata on CodeNewbie](https://www.opengraph.xyz/url/https%3A%2F%2Fwww.codenewbie.org%2Fpodcast%2Fa-model-s-journey-to-software-development), which would be the cause of this.
