### ISSUE TITLE
Cannot creat accouny

### ISSUE THREAD

**Issue by ricardasjak** [forem/forem#19469]
## Definition of Done

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

## Additional Context

Hey guys, I won't cut all that crap template from my phone, but I just want to report account creation doesnt work, if I choose GitHub option. GitHub button click results in no action.

**Comment by maestromac** [comment]
If the issue still persists, I would suggest signing up with email then navigate to settings to connect to your GitHub oauth. Let us know if that works!
