### ISSUE TITLE
Whenever the history icon in header is clicked, the same url `/notifications` stacks in history

### ISSUE THREAD

**Issue by hsk-kr** [forem/forem#19471]
**Describe the bug**

Whenever the history icon in header is clicked, the same url stacks in history

**To Reproduce**

1. Click the history icon in header to navigate 'https://dev.to/notifications'
2. Click the history icon again
3. press the back button in tools of a web browser 

**Expected behavior**

The same url stacks once in history. For example, even if I press the history icon button 10 times, `/notifications` should be once in history and when press the back button, the url should be going back before I press the history icon button not the same url `/notifications`.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: MacOS Monterey 12.6.2
- Browser, version: Chrome, 112.0.5615.49

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by maestromac** [comment]
Thank you for this report! This is interesting and may have been the side effect of us using `instantClick.js` which mimics a single-page app.
