### ISSUE TITLE
`/dashboard/following_tags` continues to load and display on `/dashboard/user_followers`

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19483]
**Describe the bug**

If `/dashboard/following_tags`  is navigated to and then  `/dashboard/user_followers` is quickly navigated to, before the tags load, the tags are erroneously rendered on `/dashboard/user_followers`.

**To Reproduce**

1. Navigate to `/dashboard/following_tags` 
2. Quickly navigate to `/dashboard/user_followers` before the tags are loaded
3. When loaded, the tags will be rendered on the `/dashboard/user_followers` 

**Expected behavior**

The tags should not be rendered on  `/dashboard/user_followers` / the returned request should be ignored/squashed.

**Screenshots**

https://github.com/forem/forem/assets/1628871/57bbb21c-0b18-412e-872f-e7ed4a119c33

**Desktop:**

- OS, version:Windows 11 Pro
- Browser, version: Google Chrome Version 113.0.5672.93 (Official Build) (64-bit)

**Comment by rt4914** [comment]
cc: @PhilipHow 
A similar issue was filed by an open-source contributor: https://github.com/forem/forem/issues/18509
They also have a related PR for this: https://github.com/forem/forem/pull/19397
