### ISSUE TITLE
Add organizations to the list of suggested users to follow as part of onboarding

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19498]
## Is this feature related to a problem? Please describe.

As a new user, I want to follow organizations that are producing content relevant to my interests (posting high-quality content under tags I have indicated an interest in).

## Describe the solution you’d like

- We should append 5 organizations to the bottom of the list of 'accounts to follow' on the 'Suggested people to follow' step of onboarding.
- Organizations should be sourced in an identical way to users: organizations that are producing _recent_,  at least average quality, content under tags that the user has followed or (if no tags are followed, or not enough organizations are returned) organizations that are producing recent, at least average quality, content if 5 cannot be returned.
- We are not too concerned if users and their organizations are returned at the same time
- We need to update the copy of the page to the following:

  > # Suggested Follows
  > ## Kickstart your community
  > You're not following anyone [Select all]
  > You're following X people and Y organizations (everyone) —[Deselect All]
  > You're following X people [Select All]
  > You're following X organizations [Select All]

## Definition of Done

- [ ] Return a list of 5 organizations, determined by:
  - [ ] (1) those that have produced posts with at least an average score, within the last 3 weeks under tags that the user has followed
- [ ] If not enough organizations returned then:
  - [ ] (2) organizations that have produced posts with at least an average score, within the last 3 weeks under any tags
- [ ] Append the list of organizations to the bottom of the list of returned users
  - [ ] Allow the user to follow or unfollow organizations
  - [ ] Make the organizations work under the 'select all'/'deselect all' controls
- [ ] Change the page copy above to no longer reference only users
  - [ ] Change the page copy to dynamically update if organizations and or users are selected
  - [ ] If no organizations are returned - then the copy shouldn't refer to organizations
  - [ ] if no users are returned - then the copy shouldn't refer to users

## Additional Context

* ![image](https://github.com/forem/forem/assets/1628871/034dcf6e-56ba-4abf-bdb5-40031ba3f6b2)
*Existing step in the onboarding process*
* The logic to recommend organizations is designed to be the same as the logic used to [recommend users ](https://github.com/forem/forem/blob/main/app/services/users/suggest_recent.rb).
* Organizations are encouraged to post under individual accounts tied to the organization, and we show the "Follow" prompt to the organization in the right sidebar - encouraging the user to follow the organization and not the individual user.
* We have decided not to make this a separate step of the onboarding process to keep the onboarding length short. We may separate this out in the future if we want to elevate the process of following organizations.

**Comment by jaw6** [comment]
@PhilipHow "above average article" is a bit of a new concept, for better or worse. The way this fell together, it is sort of by default calculating "average score" in a way that's scoped to the query we're running at the time — in other words, in the mode where we're looking at articles-tagged-with-tags-you-are-following, the average is calculated among `org-owned articles with those tags` and in the other mode the average is calculated across all `org-owned articles`. 

I think this might not be our ideal behavior, and it is something we can change, but I'm inclined to go with this by-default behavior for now, but wanted to see if there's a strong preference to handle this in a different way?

**Comment by PhilipHow** [comment]
@jaw6 Thanks for the heads up on this.

1. The "above average article" was a reference to the assumed existing behavior of how users are recommended - is this behavior different to that?
2. If I'm understanding this correctly, the only risk here is, if the tags the user is following have a generally lower score, we'll be recommending organizations from this pool, rather than other potentially higher-scoring organizations?

I think this is fine in this context where we want to recommend relevance over quality.

**Comment by PhilipHow** [comment]
@jaw6 

In the interest of speed, I'm happy to keep them with slightly different behaviors for the time being.

Perhaps in the future, we can address a shared concept of "top users", "top orgs" and "top users / top orgs for tag x".

**Comment by PhilipHow** [comment]
@jaw6 

I missed this previously, but the copy's not been updated to that for the issue.

Current - ![image](https://github.com/forem/forem/assets/1628871/7ae71f96-f9e7-47f9-b201-e181e2d87161)

Should be - ![image](https://github.com/forem/forem/assets/1628871/f999abf3-2929-48e9-9846-a535eed3283f)

The copy is correct when toggling on and off users and orgs just the copy when everyone is followed should make it clear that organizations are followed (as this is the default behavior): "You're following X people and Y organizations (everyone)"

**Comment by PhilipHow** [comment]
@anujbhavsar96 

This updated step in onboarding is taking a bit too long for me to load. Do we have an established loading indicator style we could apply here?

**Comment by anujbhavsar96** [comment]
@PhilipHow we can use the similar skeleton loader we use while performing the search

![Jun-22-2023 10-13-05](https://github.com/forem/forem/assets/84626054/381d4ca1-6f6b-49df-9d1c-faac244c434b)

---

Also, buttons styling is opposite here, not an issue of this PR. It has been like this only since the start, so we can address this as well.

Ideally, `Follow` should be a primary button with a purple fill, and `Following` should be secondary with an outline style. But here, it's the opposite.

**Comment by jaw6** [comment]
@anujbhavsar96 I didn't see this thread early enough in my day and put together a loading indicator with the built-in crayons spinner. I included a gif in [the PR](https://github.com/forem/forem/pull/19622) — let me know if you want me to switch to a different loader (but we should also maybe update our documentation/storybook/something, as I was only seeing this one).

The follow button coloring was changed in [this PR](https://github.com/forem/forem/pull/19384) — something in the way this was originally setup was causing contrast problems, specifically in the `/onboarding` pages, despite the contrast-checker.

**Comment by anujbhavsar96** [comment]
@jaw6 That spinner also works ✨. Is it possible to make it vertically center to that blank space?

--

What I meant by follow button is similar to what we have inside the platform or profile page.

![Jun-22-2023 22-00-14](https://github.com/forem/forem/assets/84626054/3753a303-eacd-433b-8e8b-29f463ca3e93)

**Comment by PhilipHow** [comment]
@anujbhavsar96 

Good observation here.

I guess consistency is best and we should change this behavior but I just wanted to consider the fact as we default to "Following" in this context the styling is applied with this in mind.

If we changed it, would unfollowing users be intuitive given the secondary/outline state?

**Comment by anujbhavsar96** [comment]
@PhilipHow 

As a user, I always perceive highlighted/primary actions as important. 

I always confuse "Following" with "Follow" because I would expect Follow button to be primary. But it's the opposite here, and I realize it once I click it.

And anyway, since our default behavior is Followed state, the "Following" button should be secondary since it's unfollowing action. 

Another cleanup suggestion is to remove the BG blue OR make it more elegant, but it may be an issue for another time.

<img width="1630" alt="image" src="https://github.com/forem/forem/assets/84626054/5af69795-bdbc-4f2e-b135-fbb7ce0aa34f">

**Comment by jaw6** [comment]
I believe this has been closed by #19619.
