### ISSUE TITLE
Add ability to assign arbitrary segment ID to /display_ads API

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19496]
## Is this feature related to a problem? Please describe.

The current `/display_ads/` API accepts `audience_segment_type`, which is a nice convenient way to set a segment in the "automated segments" camp — because these are one per type and it's nice to not have to know the ID.

However, for manual segments, which we are working on the creation of via API, we'll want to take the segment and assign it to a billboard (currently named display ad)

## Describe the solution you’d like

In addition to the `audience_segment_type`, I should also be able to designate a `audience_segment_id` which could be a manual segment.

- A `audience_segment_id` can be sent without a `audience_segment_type`.
- If a `audience_segment_type` is sent that does not match with the `audience_segment_id`, we should send `422 (Unprocessable Content)`.
- `audience_segment_type` can be sent without an ID, except for type of "manual" because that could be many different segments.

## Definition of Done

- [ ] attribute added to endpoint and it sets the proper value on the billboard itself.

**Comment by jaw6** [comment]
> invalidate the response and dictate that it should be either/or

Seems to me like it should be a 422 ("Unprocessable Content")
