### ISSUE TITLE
Add more visibility and control around reactions/flags into the Admin USERS page

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19492]
## Is this feature related to a problem? Please describe.

As an admin, I need more visibility into the reactions and flags that are impacting users, in order to effectively administrate the community.

## Describe the solution you’d like

Continue the work started for Articles in https://github.com/forem/forem/issues/19314 by @rt4914 , but apply it to the Admin Users page.

We'll update the existing User "Flags" tab found at `/admin/member_manager/users/{user-id}?tab=flags`

As an admin, I need to be able to:
* View all "flags" agains the user
* Validate / Invalidate those flags

[**Figma Designs**](https://www.figma.com/file/yhg9HTZDFIeWuvBt9ygrss/Moderation?type=design&node-id=1650-3432&t=PXCdFbwesYZDQwhJ-4)

![Frame 626107](https://github.com/forem/forem/assets/84626054/a1d40f58-281a-43ad-965d-239d34522375)

## Definition of Done

Introduce parity as it relates to "Flags" as introduced by @rt4914 in https://github.com/forem/forem/pull/19375 and https://github.com/forem/forem/pull/19345, but apply it to the "flags" tab on the Users page.

## Additional Context

This will bring consistency to the work outlined in https://github.com/forem/forem/issues/19314 and  https://github.com/forem/forem/issues/19491

**Comment by mirie** [comment]
Use the existing design that was used prior
