### ISSUE TITLE
Add more visibility and control around reactions/flags into the Admin COMMENTS page

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19491]
## Is this feature related to a problem? Please describe.

As an admin, I need more visibility into the reactions and flags that are impacting comments, in order to effectively administrate the community.

## Describe the solution you’d like

Continue the work started for Articles in https://github.com/forem/forem/issues/19314 by @rt4914 , but apply it to the new standalone comments page outlined in #19490 

Just dropping the designs here. Everything is pretty much similar to what we have for #19314 

| Comment Index Page | Comment Detail Page - Flags | Comment Detail Page - Quality Reactions |
| ------ | ------ | ------ |
| ![Index page](https://github.com/forem/forem/assets/84626054/9aed70d7-33aa-4c2f-aa02-0b5d1fd42ec6) | ![Flags](https://github.com/forem/forem/assets/84626054/107a54cb-cc62-44e8-b4f5-05ceba567744) | ![Quality reactions](https://github.com/forem/forem/assets/84626054/128cf3e9-80ac-4e19-928c-3c0214d2cd8d) |

[Figma](https://www.figma.com/file/yhg9HTZDFIeWuvBt9ygrss/Moderation?type=design&node-id=1649-2637&t=PXCdFbwesYZDQwhJ-4) (see Comment page section)

## Definition of Done

Introduce parity with the functionality introduced by @rt4914 in https://github.com/forem/forem/pull/19375 and https://github.com/forem/forem/pull/19345 on the new standalone comments page.

## Additional Context

- **Blocked by creation of the new standalone comment page in https://github.com/forem/forem/issues/19490**

**Comment by anujbhavsar96** [comment]
Just dropping the designs here. Everything is pretty much similar to what we have for #19314 

| Comment Index Page | Comment Detail Page - Flags | Comment Detail Page - Quality Reactions |
| ------ | ------ | ------ |
| ![Index page](https://github.com/forem/forem/assets/84626054/9aed70d7-33aa-4c2f-aa02-0b5d1fd42ec6) | ![Flags](https://github.com/forem/forem/assets/84626054/107a54cb-cc62-44e8-b4f5-05ceba567744) | ![Quality reactions](https://github.com/forem/forem/assets/84626054/128cf3e9-80ac-4e19-928c-3c0214d2cd8d) |

**Comment by mirie** [comment]
@anujbhavsar96 can we get the Figma link on this one as well in the issue description? Thanks!
