### ISSUE TITLE
Create a standalone "admin" page for each comment

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19490]
## Is this feature related to a problem? Please describe.

* **Articles** have `/admin/content_manager/articles/{article-id}`
* **Organizations** have `/admin/content_manager/organizations/{org-id}`
* etc.
* We don’t have a “content_manager” view for comments

As an Admin, I want a standalone "admin" page for a comment, so that I can take administrative actions in an organized space.

## Describe the solution you’d like

**Create an Admin Comment Page:**
* All comments should have a standalone page in the admin section

**Add "View Details" button to each comment row in `/admin/content_manager/comments`**
* All comments in the `/admin/content_manager/comments` index view should have an "View Comment" and "View Details" button
* That button will link to the new standalone page for that comment

[Figma Designs](https://www.figma.com/file/yhg9HTZDFIeWuvBt9ygrss/Moderation?type=design&node-id=1650-2641&t=PXCdFbwesYZDQwhJ-4)

## Definition of Done

- [ ] Create a standalone page for each comment in the admin section.
- [ ] Format should be `/admin/content_manager/comments/{comment-id}`
- [ ] Update "View" button to "View Comment"
- [ ] Add a "View Details" button to each comment row in the `/admin/content_manager/comments` index view.
- [ ] Ensure that the "View Details" button links to the new standalone page for the corresponding comment.

## Additional Context

This brings consistency to other admin views, and introduces consistency around the visibility of these actions.

The only functionality we need added to the standalone page is described in https://github.com/forem/forem/issues/19491

**Comment by anujbhavsar96** [comment]
@pkfrank , Let's call the button `View Details`, as we did for the article index page. Since it's already an admin view, view details make much more sense here.

| Without `View Details` | With `View Details` |
| ------ | ------ |
| ![Comment page](https://github.com/forem/forem/assets/84626054/509030c6-e176-42a6-82be-cd6ba9102abd) | ![Comment page1](https://github.com/forem/forem/assets/84626054/f4c659d8-fe45-4e19-a9ec-13bd66cdc5bb) |

**Comment by mirie** [comment]
@anujbhavsar96 can you link the Figma in the issue description please. Thanks!
