### ISSUE TITLE
Billboards are not properly displayed to users targeted by an audience segment

### ISSUE THREAD

**Issue by filleduchaos** [forem/forem#19504]
**Describe the bug**

While trying to QA #19470 (on its Uffizzi deployment) I discovered that billboards are not getting shown to users that are in their target audience segments. I was able to replicate that locally on the main branch, but it seems like there might actually be two bugs in one. 

**To reproduce**

I created two billboards targeting all users:

<img src="https://github.com/forem/forem/assets/29291843/41e8b989-1988-4493-8273-5a80148709bf" alt="Logged-out home page showing two billboards, one for an upcoming hackathon and the other for a sale" width="400">

Then I updated the top billboard to only be shown to trusted users via the admin UI, and confirmed the users in the `trusted` audience segment's list:

```
pry(main) > AudienceSegment.find_by(type_of: "trusted").users.pluck(:email)
["admin@forem.local", "cendrillon@forem.local"]
```

However the admin and the other trusted user both did not get shown the billboard when logged in

<img src="https://github.com/forem/forem/assets/29291843/973e1993-567f-4724-b31f-1c4f21dcfcbd" alt="Admin's logged-in home page only showing one billboard" width="400">

The second problem is that whenever I made a change to the billboard's target and went to confirm its effects, I would get this weird jank where any users that were already signed in would get some extra billboard space:

<img src="https://github.com/forem/forem/assets/29291843/30ec9af0-c1f8-4d86-9075-768a10d795da" width="300">  <img src="https://user-images.githubusercontent.com/29291843/239520566-c9c1d772-022e-4e1a-a247-962509ac6d12.png" width="300">

The space wouldn't go away no matter how many times I refreshed the page, but logging out fixed it. Logging in fresh after making the billboard change also did not get the jank.

**Expected behavior**

Billboards should get shown to users in an audience segment they're targeting 

**Screenshots**

See above

**Additional context**

I also got all this on the Uffizzi deployment, but since it's also a development environment this all might still be a dev mode thing. Still worth fixing for DX in that case, but maybe lower priority

**Comment by jaw6** [comment]
My attempts to replicate locally have not succeeded. My current guess is that this might be a placement-area issue — it looks like your tests were maybe all with `sidebar_left` (mine were either with `post_comments` or `post_sidebar`).

**Comment by mirie** [comment]
Closing this and going forward with [this feature issue](https://github.com/forem/forem/issues/19577)
