### ISSUE TITLE
Long organization names mess up promoted billboard design

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19527]
**Describe the bug**

<img width="366" alt="Screen Shot 2023-05-23 at 12 13 39 PM" src="https://github.com/forem/forem/assets/3102842/8a24a90a-c967-41ed-b025-bf245e392479">

Long names smush the design

**Expected behavior**

All valid org name lengths should not mess with the design. Ideally we also don't have to truncate them either.

**Desktop (please complete the following information):**

- OS, version: MacOS 12.3.1
- Browser, version: 113.0.5672.92

**Additional context**

I think the fix can at least account first for AWS Community Builders and then follow up with perhaps a revisit of the design or how to implement it to account for arbitrary lengths.

**Comment by mirie** [comment]
This was resolved by https://github.com/forem/forem/pull/19528
