### ISSUE TITLE
Tiny style patch: Make all admin nav links full width

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19530]
## Is this feature related to a problem? Please describe.

The current style of inline width links is awkward. I can be hovering over one link and scroll directly down and not be hovering over the one below.

https://github.com/forem/forem/assets/3102842/5a61398a-b691-4a85-a03a-bb5aaf1d5a12

## Describe the solution you’d like

All these links should take up the full width of the space

## Definition of Done

- All links take up full width.

## Additional Context

This should be as simple as removing `inline-block` from these links.

**Comment by Neha** [comment]
I would like to take this issue @benhalpern

**Comment by benhalpern** [comment]
Go for it @Neha — I have assigned you

**Comment by helmihidzir** [comment]
Can I work on this?

**Comment by Neha** [comment]
unfortunately, my schedule got busy and I won't be able to pick up this issue this time. Apologies.

**Comment by aneshodza** [comment]
@benhalpern I could do it, if its still open.

**Comment by aneshodza** [comment]
> And how can I setup the project for development
[This](https://developers.forem.com/) could help you

**Comment by aneshodza** [comment]
@StarTrooper08 Maybe it would be a good idea if you tried it. If you really can't do it I can do it and tag you in the PR so you can see how I did it.
Some small tips on how I approach that:
1. On the video we can see the string "Content manager". Full text search the project for that string.
2. You will most likely end up in a translations file. In there you will see how its reference is called. Let's say its called `dashboard.content_manager`, as an example
3. Full text search for `dashboard.content_manager`. There you find the html component that renders this.
4. Change the css referenced in its classes.
Good luck :)

**Comment by aneshodza** [comment]
@StarTrooper08 did you manage? Tag me when you open a PR!

**Comment by PhilipHow** [comment]
@StarTrooper08 Any luck with this issue? If you're unable to make progress on this, please let me know and I can reassign it.

**Comment by mirie** [comment]
@filleduchaos do you mind taking a pass thru and providing some guidance to @StarTrooper08 ? Thank you!

**Comment by filleduchaos** [comment]
@StarTrooper08 First off just checking if you're still interested in working on this issue - it's been some months, and if you no longer have the bandwidth please let us know and we'll assign it to someone else.

That being said, you're on the right track so far - [app/views/admin/shared/_nested_sidebar.html.erb](https://github.com/forem/forem/blob/13f4aaa0fb9363f64ecb2944f3cdd22547300770/app/views/admin/shared/_nested_sidebar.html.erb) is where the links in question are getting rendered, and yes if you remove the `inline-block` class in that file that should fix the links :)

If you would like to see it in action and you have a local dev environment set up, you can log in as an admin account, navigate through the top right menu to the `Admin` section and expand any of the links in the sidebar

**Comment by StarTrooper08** [comment]
Thanks, I will give it a try.
