### ISSUE TITLE
Hatch-a-Dot resulting in no gained Keeper xp

### ISSUE THREAD

**Issue by Luka-Timothy** [forem/forem#19541]
**Describe the bug**
After the Hatch-a-Dot transaction is complete and the baby Dot is chosen, the Keeper card appears on the bottom right of the screen and the xp received is displayed. After navigating to Keeper card, xp remains unchanged and appears to be not awarded as expected. 

**To Reproduce**

1. click on "Hatch-a-Dot" link via Campfire to begin hatching transaction
2. click "Hatch-a-Dot" button to begin Hatch-a-Dot animation, with sundrops and nest (all traits are available)
3. after animation, in the egg choice screen, click the "Eggs Ray" icon and click button to "Use" the Eggs Ray
4. choose a Dot, click "Hatch" button
5. on the screen "Do you want to raise this new Dot", select "No" button, and then select "Try Again" button in order to re roll for different traits 
6. once satisfied with inherited traits, select "Hatch" button, and this time on the screen "Do you want to raise this new Dot", select "YES!!!!"
7. after the Dot is named, an animation begins and in the bottom right of the screen, the Keeper card is displayed with xp earned displayed
8. after this, navigate to Keeper card by clicking on the bag icon in the bottom right, "Dots & Friends" icon, and finally the "YOU" tab
9. observe Keeper xp remains unchanged

**Expected behavior**

The Keeper xp is expected to be awarded as indicated post Hatch-a-Dot animation

**Screenshots**
![IMG_1460](https://github.com/forem/forem/assets/77414507/805759c1-e34f-4193-9e9b-5bbc3640ecb2)
![IMG_1461](https://github.com/forem/forem/assets/77414507/7af2e782-591c-44b3-9a4f-ab3d2460b84e)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:iPad Air (4th generation)
- OS, version: iPadOS Version 16.4.1 (a)
- Browser, version: --

**Additional context**

**Comment by PhilipHow** [comment]
@Luka-Timothy Wrong repo :)
