### ISSUE TITLE
HTML `<a>` tag gets rendered as HTML instead ov being written as text in the notification menu.

### ISSUE THREAD

**Issue by CalinZBaenen** [forem/forem#19553]
## Bug

In [the notifications menu](https://dev.to/notifications), my post's title, *How can I remove the "padding"-like stuff on the \`\<a\>\`?*, becomes *How can I remove the "padding"-like stuff on the \`\`?*.  
![Image ov the post title being incorrectly displayed.](https://github.com/forem/forem/assets/50878485/265a4ea2-7957-4c15-a1fa-5926cb305d78)  
Here is what it looks like when viewing the post title from the inspector:  
![Image ov the menu with the inspector.](https://github.com/forem/forem/assets/50878485/7a5963c2-e4b0-4e48-a9eb-b252e2185d28)  
... and again with the relevant areas being highlighted:  
![Image ov the menu with the inspector being highlighted.](https://github.com/forem/forem/assets/50878485/aa2413b3-01ef-441f-ac6f-669a2506f104)  
However, this bug does not happen when someone is commenting on your post; for example, consider this notification for a comment left by @foxy4096:  
![Image ov the notification for Aditya's message.](https://github.com/forem/forem/assets/50878485/9b1d32e8-f537-40f4-8e30-04f14ed933ef)  
Additionally, as far as I'm concerned, it only works with the `<a>` tag, but I did not really have that many tags in my title.  
![Image ov another post with HTML tags in the title.](https://github.com/forem/forem/assets/50878485/961fcec5-e18d-494d-acb7-e81d07591c48)

## Reproduction

Go into the notifications menu after someone likes your post, I suppose; I am not sure what else I can say.
1. Make a post good enough so that at least one person will leave a reaction.
2. Make sure the syntax for a code snippet, two backticks, syntax is in your title, and in the "code-snippet", put an HTML tag like `<a>`.
3. See what it looks like in the notification menu

## Expected Behavior

I expected to see *\`\<a\>\`?*, not *\`[\`?]()*.

## System Information

Ubuntu (Jammy Jellyfish), 22.04.2 LTS, x86\_64.  
Firefox, 113.0.1, 64-bit.

**Comment by zainbinfurqan** [comment]
Can i work on this issue?

**Comment by CalinZBaenen** [comment]
I would hope that you are allowed to — someone needs to get to it, as I can't imagine this bug is pleasant, even if it isn't doing much harm.&nbsp;&nbsp;(I feel like this could be concidered an accessibility concern, though.)

**Comment by danielmbrasil** [comment]
Hey @CalinZBaenen, could you confirm if it's still an issue? 

I've tried to replicate it using exactly the same title as your post and some other alternatives using the `<a>` tag, but without success. As you can see in the following screenshot:
![image](https://github.com/forem/forem/assets/51726526/5900b0f6-e5a4-4beb-8de8-70766878802c)

Maybe this already got fixed in main or I'm simply missing something.

**Comment by CalinZBaenen** [comment]
I think it has been patched out, as your screenshot indicates.  
(Though, I'm unsure at what point it was fixed;&nbsp;&nbsp;I feel like my issue should have been closed.)

**Comment by arize99** [comment]
Recreating this may require some additional hands, since it has not been flagged again by another person I guess it has been patched out as @CalinZBaenen  pointed out.
