### ISSUE TITLE
Bulk assign user roles

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19559]
## Is this feature related to a problem? Please describe.

As an admin user, when I have identified a cohort of users I want to take action on, I want to bulk-assign multiple user roles in one go, instead of manually assigning them one by one, or relying on database edits.

## Describe the solution you’d like

- Admin users will be able to bulk assign status roles (not admin roles) to users, from the Member Manager area of the Admin area.
- The tool should work similarly to the bulk awarding of Badges
- The tool will support entering multiple usernames, to apply the selected role to
- The tool will function as if the role was manually added - the role will appear in the existing areas of the admin interface where the role is applied, including the user's notes section
- The tool will log individual users granted the new role, to the `AuditLog`.

## Definition of Done

- [ ] A new "Bulk Assign" roles area, available to the 'admin' and 'super_admin' roles in the Admin Member Manager area `/admin/member_manager/users` (e.g. `/admin/member_manager/bulk_assign_roles`)
  - Shown as a new sub-menu item in the list (after GDPR Actions)
- [ ] Admins will be able to run a new bulk assignment on the page, where admins will be required to:
  - Select a single role, from the list of "user statuses" (Warned, Comment Suspended, Suspended, Good Standing, Trusted)
    - Note that super admins are not able to assign admin permissions (or "roles") using this tool. This is to avoid abusive super admins creating large changes which take time to undo.
  - Enter a list of comma-separated user names (whitespace ignored between the commas)
  - Enter in a free-text note that is applied to the assigning of the user role
- [ ] When a new bulk assignment is run, an on-screen message will indicate that the job has been started (or queued, whatever is most appropriate here).
- [ ] Roles should be assigned optimistically - if we can't assign a role to a user for whatever reason then the user should be ignored
- [ ] When executing the bulk assignment, the tool will append a new entry into the `AuditLog` for each user added to the bulk assignment, which will include:
  - The date/time of the bulk assignment
  - The user who ran the bulk assignment
  - Role selected
  - Entered user name
  - Status of the assignment, either:
    - The role was applied successfully,
    - The user already had the role, or
    - The user didn't exist

## Additional Context

- Currently, the platform team is running a [weekly script](https://gist.github.com/maestromac/48643be02cecfb2c00bd9f403b993ff3) to batch update users to the trusted user role, with candidates identified from the Community team.
- Originally, this issue had a results screen built into the UI to allow users to see the result of past runs - this has been removed to reduce the scope of the issue - and `AuditLog` replaced to ensure results are available for scrutiny in the database.
- We should ensure that the existing data structure in the JSON blob in the `AuditLog` are re-used as much as possible as we may add a view to the `AuditLog` in the UI in the future to interrogate its actions.

**Comment by Ridhwana** [comment]
Do we have a Figma design for this? If not, I'm wondering if we should we try do a Figma design for this functionality, especially since the member manager is under the newly designed parts of the admin area?
