### ISSUE TITLE
Flag user in Moderation actions returning error

### ISSUE THREAD

**Issue by kkrypt0nn** [forem/forem#19579]
**Describe the bug**

Whenever you open the Moderation Center and click on a post you have the ability to flag the user itself, not just the post, however since a few hours (haven't tested before 10 hours ago) clicking the button does nothing.

**To Reproduce**

1. Go to the Moderation Center
2. Click on any post
3. Click on "Moderating actions" on the right side of the post
4. Click on `Flag {user}`

**Expected behavior**

The pop-up that asks for user confirmation on whether or not to flag the user should appear as it used to do.

**Screenshots**

The browser's network tab shows the following request payload being sent to the `https://api.honeybadger.io/v1/notices/js` - it may be unrelated but is the only entry showing up once the button is clicked

![image](https://github.com/forem/forem/assets/43011723/d01dcd06-33ae-46ac-b8f5-02fc049b400b)

**Desktop:**

- OS, version: Windows 11
- Browser, version: Microsoft Edge 114.0.1823.37

**Smartphone:**

- Device: Pixel 6a
- OS, version: Android 13
- Browser, version: Microsoft Edge 113.0.1774.50

**Comment by michael-tharrington** [comment]
Really appreciate ya writing this up, Krypton!

**Comment by michael-tharrington** [comment]
Just to quickly add that in case folks aren't familiar, the mod center is located here - https://dev.to/mod and looks like this.

![screenshot of dev.to/mod](https://github.com/forem/forem/assets/16007075/33267ba6-4e4f-4d4e-b30e-86347050d93b)

I'm not entirely sure, but I think flagging a user via the mod panel still works as expected.

![screenshot showing how to flag a user via the mod panel](https://github.com/forem/forem/assets/16007075/0e331201-0e28-416f-b16f-bfe8f574087f)
