### ISSUE TITLE
Two "Managed elsewhere" select options when creating a new Billboard

### ISSUE THREAD

**Issue by mirie** [forem/forem#19578]
**Describe the bug**
There are 2 "Managed elsewhere" select options in the "Users who:" dropdown when creating a new billboard.

**To Reproduce**

1. Go to https://dev.to/admin/customization/display_ads/new
2. Select `Only logged in users` for the "Display to user group" select option
3. In the "Users who:" select, you will see that there are two entries (with different numbers set for the `value`) for "Managed elsewhere" 

**Expected behavior**

There should only be one entry in this select dropdown.

**Screenshots**

<img width="895" alt="Screenshot 2023-06-02 at 1 48 45 PM" src="https://github.com/forem/forem/assets/896728/c6ae6083-c666-4996-892e-0add6b8d036e">

**Additional context**

Not sure if adding manual audience segment caused this issue.

**Comment by rt4914** [comment]
Note for anyone who is working on this: 
I tried to reproduce this locally but I am unable to see any repetition.
<img width="414" alt="Screenshot 2023-06-30 at 1 09 46 AM" src="https://github.com/forem/forem/assets/9396084/1826efb6-4f7c-48ea-8e3b-1af5d0bbbbcc">
