### ISSUE TITLE
Creating an article with a title too long for example returns a 200 on the post

### ISSUE THREAD

**Issue by maxime1992** [forem/forem#19587]
**Describe the bug**

Creating an article with a title too long for example returns a 200 on the post.
It's the same for anything that is wrong in the front matter too.

EDIT: It's the same if we're trying to update (PUT)

**To Reproduce**

1. Open dev.to
2. Create a new article with a really long title
3. Press save as draft
4. Notice that you get an error displayed

![image](https://github.com/forem/forem/assets/4950209/c859187c-d030-43ce-a94f-fdb8a949aeb2)

5. Look into the network dev tool, you'll see that even though it was returning an error, the returned status is 200 like everything was fine

![image](https://github.com/forem/forem/assets/4950209/817ea571-880b-4639-8aec-4dee06e4ba64)

**Expected behavior**

Should return an error code

**Comment by PhilipHow** [comment]
@dhurba87 All yours.
