### ISSUE TITLE
Other super admins should be able to remove super admin roles

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19580]
## Is this feature related to a problem? Please describe.

As a super admin, I may occasionally need to remove a different super admin. Currently this can only be done via the console (aka a technical request).

This is a "dangerous" activity which should not be done lightly, but it should still technically be available. In the event that it is done in a way where it cannot be reversed (i.e. losing access to the account that could reverse it) _then_ it makes sense to have the support request to manually reconcile this.

## Describe the solution you’d like

The `super_admin` role _can be_ removed _by other super admins_.

We currently display an "Are you sure" dialog.

This should be modified to say "You are removing super admin access from this account. Do this carefully and always ensure you retain access to one or more super admin accounts".

## Definition of Done

- [ ] Policy is changed
- [ ] Dialog message is changed

## Additional Context

There are additional adjustments which could be worth making to this area, such as allowing users to manage _their own roles_, but we can keep this tight and iterative as not to creep in too many changes all at once.

**Comment by benhalpern** [comment]
Go for it @dhurba87, I've assigned you.

**Comment by michael-tharrington** [comment]
Oooo very nice! I had this written up as [a feature request in GitHub discussions](https://github.com/forem/forem/discussions/16114)... happy to see it being worked on here. I'll go close that request and reference this work in it.

Thanks so much @dhurba87!
