### ISSUE TITLE
Inconsistent scroll position on the feed when pressing back in the browser

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19595]
**Describe the bug**

When you press 'back' on your browser after viewing an article, sometimes you're returned to your original scroll position, and sometimes you're returned to a scroll position higher up the page.

**To Reproduce**

1. Scroll to a position in the feed
2. Click on the top article on your screen
3. Press back in your browser
4. Check if the same article remains at the top of your screen

May need to be repeated to be triggered.

**Expected behavior**

You should always return to your old feed position when pressing back in your browser.

**Desktop:**

- OS, version: Windows 11 Pro
- Browser, version: Google Chrome Version 113.0.5672.93 (Official Build) (64-bit) 
- Mozilla Firefox 113.02

**Additional context**

- Setting `history.scrollRestoration = 'manual'` in your browser's console *seems* to fix this (with my limited testing on Chrome and Firefox), leading me to believe our own scroll restoration behavior is interfering with the browser's.
- I would like to understand why we're using our own solution here, rather than relying on the default browser implementation. This could either be a legacy implementation or more scenarios are supported using our solution, in which case disabling the browser's 'auto' behavior may be the best approach here.

**Comment by PhilipHow** [comment]
Marking this as `Forem Team` as I think it warrants a bit more excavation that just the bug fix. If any contributors are open to dig a bit deeper on this I'm happy to assign.

**Comment by jaw6** [comment]
Trying to replicate this locally, but I don't have access to Windows at the moment. I don't see the bug on the home page, but I _do_ see it when I'm viewing a tag, but then _only_ when I'm scrolled far enough that I'm into later "pages". I _think_ that suggests it's less of a bug with `InstantClick` than with our "infinite scroll" pattern. Unfortunately, that leaves me _less_ clear on what we can do about it, but I'll continue to investigate.
