### ISSUE TITLE
Blank user-name

### ISSUE THREAD

**Issue by schemetastic** [forem/forem#19617]
**Describe the bug**
Apparently, it is possible to have a user-name (person's name) that is blank.

**To Reproduce**
1 - Go to this link: https://dev.to/pas_27513 and check this user-name, or also this link https://dev.to/theaccordance/the-reddit-blackout-is-a-lesson-in-risk-k5e and checkout the comments

**Expected behavior**
Not completely sure if this is allowed, but I think it would be expected that every user had a name displayed in their profiles and where they comment, so not completely sure if it's a bug or if it's allowed.

**Screenshots**
![image](https://github.com/forem/forem/assets/16121280/c28ce42a-5933-49ce-8af0-042b98840b0c)
![image](https://github.com/forem/forem/assets/16121280/26152c75-bbf7-434f-8570-6d769d16cdab)
![image](https://github.com/forem/forem/assets/16121280/6c06f1ad-9f21-4dce-90a5-696d833909aa)

**Desktop:**

- OS, version: Linux Mint 21.1
- Browser, version: Firefox 113.0.1 (64-bit) and Google Chrome 113.0.5672.126 (Official Build) (64-bit)

**Additional context**
I use “user-name” because I refer not to the username, I refer to the person's name.

Also, I'm sending this bug as requested by the reply from the yo@dev.to where I first submitted this issue.

**Requested change**

- When a user signs up or edits their profile, we should ensure that their name field does not contain only whitespace.
- If a user tries to save their profile, and their name field contains only whitespace - we should return the existing error message stating "Name is too short"
- This could be accomplished by validating using a `trim()` method or something similar.

**Comment by jerinkc** [comment]
I'd like to work on this issue

**Comment by jerinkc** [comment]
@PhilipHow Can I take this one?

**Comment by PhilipHow** [comment]
@jerinkc 

Sure, can you make sure the validation happens on both front-end and server-side?

When do you think you could get PR ready for this?

**Comment by jerinkc** [comment]
@PhilipHow I will work on both the frontend and the backend, and will be able to create the PR in 4 or 5 days.

**Comment by jerinkc** [comment]
Hey @PhilipHow, I was trying to push my changes to remote and it fails with the following message.
`ERROR: Permission to forem/forem.git denied to jerinkc.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
I tried both the SSH and HTTPS ways, but I still have the same issue. Also, I am able to push to other repositories. Could you let me know if I missed anything?

**Comment by PhilipHow** [comment]
@jerinkc 

Have you read through the[ contributor's guide](https://developers.forem.com/contributing-guide/forem)? Please make sure you've read through it.

[Here ](https://developers.forem.com/contributing-guide/forem#how-to-contribute) is the relevant section which details how to create a pull request.

**Comment by jerinkc** [comment]
Thank you, @PhilipHow. I found the mistake.

**Comment by maestromac** [comment]
Resolved with https://github.com/forem/forem/pull/19723
