### ISSUE TITLE
Twitter API dependency should be removed in favor of frontend tweet rendering.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19640]
## Is this feature related to a problem? Please describe.

The Twitter platform is not reliably usable in the way it once was in this respect. We must move away from API-dependent server-side tweet embed.

## Describe the solution you’d like

Move to a solution similar to what we have on Instagram

## Additional Context

We are dealing with a problem related to this:

https://twitter.com/ThePracticalDev/status/1673439411059544071

But this is a long time coming in the Twitter saga. We would not make a simple decision if DEV was the only Forem potentially facing this issue. Others could/will. This is the proper choice moving forward.

**Comment by PhilipHow** [comment]
@benhalpern 

Current behavior for your [meme monday comment](https://dev.to/ben/comment/27hkd) .

https://github.com/forem/forem/assets/1628871/f97bef23-e40e-4d0b-b61b-a52a6e2e2698

**Comment by PhilipHow** [comment]
@benhalpern Yes, still happening for me on Chrome and Edge (Windows). Not on Firefox.
