### ISSUE TITLE
Change "Follow" button styling in `/onboarding` to others instances

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19643]
> As a user, I always perceive highlighted/primary actions as important. 

>I always confuse "Following" with "Follow" because I would expect Follow button to be primary. But it's the opposite here, and I realize it once I click it.

> And anyway, since our default behavior is Followed state, the "Following" button should be secondary since it's unfollowing action. 

> <img width="1630" alt="image" src="https://github.com/forem/forem/assets/84626054/5af69795-bdbc-4f2e-b135-fbb7ce0aa34f">

> _Originally posted by @anujbhavsar96 in https://github.com/forem/forem/issues/19498#issuecomment-1608607846_

We should match the style of the Follow/Following buttons on the "Kickstart your community" step of `/onboarding` to match the behavior to instances shown in other areas of the main UI. Currently, the styles are reversed from the other main areas (e.g. see https://dev.to/ben).

The main change required here is to show a 'secondary' / 'outline'  button when the user/organization is followed and a 'primary' / 'filled' button when the user/organization is not followed.

There may be other changes to the styling required to keep them matching throughout the UI but fixing the above behavior satisfies the scope of this issue.

**Comment by jss530** [comment]
Hello - if this issue is still unassigned, would love to take it on!

**Comment by jss530** [comment]
Thanks! I should be able to get it done before then. Will let you know if anything comes up!

**Comment by jss530** [comment]
@PhilipHow I'm having issues getting the app running locally. I've made it through all the instructions but running into some issues after navigating to localhost:3000 - I emailed **yo@forem.com** explaining my issue. I would like to confirm that's the correct alias to contact?

**Comment by jss530** [comment]
@PhilipHow unfortunately, I still cannot get Forem running locally on my machine. I even tried running via Docker, but the connection to the server is still failing. It may have something to do with my having an Apple Silicon chip on my machine? Anyway, sorry about this but I think this issue needs to be passed to someone else. I have some obligations coming up now and was hoping to have this closed by today :) Sorry again!

**Comment by PhilipHow** [comment]
@jss530 Thanks for much for giving this a shot @jss530, and sorry you weren't able to get setup. Could you send through your issue to philip@forem.com and I can pass it on to the team.

**Comment by CYBWEBALI** [comment]
I can fix this issue assign it to me.

**Comment by PhilipHow** [comment]
> I can fix this issue assign it to me.

Thanks @CYBWEBALI - unfortunately someone has already opened a PR for this issue.

**Comment by Kireeti-28** [comment]
@PhilipHow You assign this to me as I opened [PR #19654](https://github.com/forem/forem/pull/19654). Apologies for any inconvenience. 
TY!
