### ISSUE TITLE
Organization API endpoints — public read, admin-only write (for now)

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19650]
## Is this feature related to a problem? Please describe.

As a general API user I'd like to know which organizations exist and to query for basic info from a show endpoint.

As an admin, I'd like to be able to generate organizations via API for contexts where the org does not require being managed by an on-site org admin.

_We already have a single read endpoint for organizations in v0 _by slug_. i.e. `/api/organizations/{username}`_. We can keep these in place, but this issue is about adding the standard ID-based endpoints for v1.

This is a task to add more standard CRUD endpoints

## Describe the solution you’d like

Index and show views with the following attributes:

- name
- summary
- tagline
- slug
- url
- profile image

We may extend this interface later, but start minimal

The write endpoints should be all the "permitted" attributes.

Create, update, destroy **should be limited to admin permissions**, similar to other restricted endpoints. This could be expanded later but is more restrictive to start as we do not want to necessarily make mass creation of organizations easier.

## Definition of Done

- [ ] index and show endpoints
- [ ] restricted create, update, destroy endpoints
- [ ] Document endpoints

## Additional Context

This can integrate with Forem administrative tools like Forem Tools.

**Comment by dukegreene** [comment]
created https://github.com/forem/forem/pull/19681 to draft my work on this.

**Comment by dukegreene** [comment]
Pinging @benhalpern and @PhilipHow after a slack huddle with Joshua where we were discussing the CREATE action and the difficulty of working with the `profile_image` field over an API call. 

It might be best to break off the CREATE work into a separate issue; currently, there's a lot of friction around the required profile_image field. Our model implementation calls for the full image file with no default/placeholder image option, or else the organization cannot be validated for creation.

Questions and advice appreciated! More context at https://github.com/forem/forem/pull/19681/files#r1261332483

**Comment by benhalpern** [comment]
@dukegreene let's have that field accept a URL which can be set via `remote_profile_image_url` at the destination.

Thanks for bringing attention to this; it was sort of an oversight in the spec.

**Comment by dukegreene** [comment]
Thank you for this clarification @benhalpern, it's helping me move forward with the POST route and associated action.

I wanted to clarify that for create and update, we want to let any authorized admin use the routes (for updates, the admin is authorized as associated with the org), and that for deletion, only super admins are allowed. Is that the case, or is the whole set of CUD supposed to be locked down to super admin access?

**Comment by dukegreene** [comment]
linked #19772 above with the create action piece. It also includes a fast follow from the merged PR and can also potentially hold any needed changes that arise during QA work today

**Comment by benhalpern** [comment]
Okay @dukegreene in QA, things are behaving well, except:

- Image is not actually being set correctly — I think this is because it's assigning a `remote_profile_image_url` _attribute_, I think this actually has to be a method. So conditionally directly calling a method vs putting an attribute into the update, would be required _I think_.
- Let's allow any _site_ admin (that is to say, just the straight `admin` and `super_admin` role) access to the `create` method. We also have named the method `require_admin` in other API controllers — such as `reactions_controller` — so I'd prefer us stick to that as a convention as long as we have started it.

Those small tweaks should fully sew this up.
