### ISSUE TITLE
Broken "reaction images" on homepage index view

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19655]
**Describe the bug**

Occasionally, the images associated with reactions are broken on the home feed.  I've only ever noticed this as a logged-in user, but it may appear in all contexts.

**To Reproduce**

I haven't been able to reliably reproduce this — it seems to be fixed after a refresh.

**Expected behavior**

The reactions display properly.

**Screenshots**

![broken reaction images with console open](https://p-dgfrwr8y.t2.n0.cdn.getcloudapp.com/items/yAu9ZJ1z/e4fb7910-4dad-46f9-b538-d06660a11588.jpg?v=a805095746a9b358c7d9377960343f05)

**Desktop (please complete the following information):**

- OS, version: macOS Ventura Version 13.4 (22F66)
- Browser, version: 114.0.5735.106 (Official Build) (arm64) 

**Additional context**

Honeybadger links (team only):
* https://app.honeybadger.io/notice/5ff9395a-83a8-4cfa-bebe-5c7a60f39784
* https://app.honeybadger.io/notice/12371733-45b3-4f73-8710-786ee6d189a0

Cross-referencing the latest multiple reactions PR #19077

**Comment by mirie** [comment]
@filleduchaos are you actively working on this? If not can we unassign?
