### ISSUE TITLE
Flaky test: commentModerationTools.spec.js

### ISSUE THREAD

**Issue by mirie** [forem/forem#19667]
## Is this feature related to a problem? Please describe.

Investigate `cypress/e2e/seededFlows/articleFlows/commentModerationTools.spec.js` it seems like the whole file is prone to flaky spec. We have unfortunately experienced an increase in flakiness and identified this test as one to take a look at more closely.

## Definition of Done

 - [ ] Ideally, a fix to resolve or at least reduce the flakiness for this test
 - [ ] If a fix cannot be determined, then a recommendation on what to do going forward

## Additional Context

- We want to timebox this investigation to no more than a week max.
- @maestromac noted that he is available to pull down the screenshot from failures and pair on debugging 
- https://buildpulse.io/@forem/forem

**Comment by maestromac** [comment]
Build artifact available at the bottom of https://github.com/forem/forem/actions/runs/5423831812
