### ISSUE TITLE
Docker installation issue

### ISSUE THREAD

**Issue by amankitsingh** [forem/forem#19663]
**Describe the bug**
After running docker-compose up, the site is not visible on localhost:3000, because the bundle is stuck in an endless loop

**To Reproduce**

1. Install Docker for Mac
2. Run docker-compose up -d

**Expected behavior**

website visibility on localhost:3000

**Screenshots**

<img width="1251" alt="Screenshot 2023-06-30 at 18 29 30" src="https://github.com/forem/forem/assets/26693197/4564bafc-ebe9-4c50-9800-57b0b183928e">

<img width="1253" alt="Screenshot 2023-06-30 at 18 29 38" src="https://github.com/forem/forem/assets/26693197/b25e4449-a724-4f65-992a-3f6cf57f06d0">

**Desktop (please complete the following information):**

- OS, version: macOS Ventura 13.3
- Browser, version: Chrome v114

**Additional context**
Running on mac m1

**Comment by dinozavrix** [comment]
Hi, I have the same problem, no solution other than installing on a linux virtual machine has been found. https://forem.dev/dinozavrix/mac-m1-pro-docker-setup-issue-o77

**Comment by amankitsingh** [comment]
are you using Virtualbox? or something else.

**Comment by maestromac** [comment]
Hello @amankitsingh , we recently revamped our setup options and highlighted them in [this post](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49). Will you please give one of those options a try, and let us know? Since it's been awhile, I would suggest starting with a fresh repo clone.

**Comment by amankitsingh** [comment]
hi @maestromac 
I ran the command `Dev Containers: Rebuild and Reopen in Container` but it failed after creating some volumes and images.

**Comment by maestromac** [comment]
@amankitsingh Please start a discussion q&a with pictures or details error messages along with your dev machine's OS and spec https://github.com/forem/forem/discussions/new?category=q-a
