### ISSUE TITLE
Can't scroll after return to contents page from Enter full screen mode

### ISSUE THREAD

**Issue by iamhoonjeong** [forem/forem#19662]
**Describe the bug**

Can't scroll after return to contents page from Enter full screen mode

**To Reproduce**

1. Go to any content inside that have code
2. Enter fullscreen mode
3. Go back to content (press back in your browser)
4. Booom. Can't scroll. also go back two steps.(technically one step but user can feel like two step)

**Expected behavior**

**Screenshots**

https://github.com/forem/forem/assets/85778639/506346c2-8a69-4cf3-ae3c-0d233bf94df3

**Desktop (please complete the following information):**

- OS, version: macOS Monterey, 12.6.5
- Browser, version: Chrome, 114

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by PhilipHow** [comment]
Thanks, @iamhoonjeong  - a weird one!

I'll open this to contributors if someone feels like taking this on.

**Comment by zhangted** [comment]
Opened a PR. Can I be assigned this one?
