### ISSUE TITLE
Flaky test: filtered_ads_query_spec.rb

### ISSUE THREAD

**Issue by mirie** [forem/forem#19666]
## Is this feature related to a problem? Please describe.

Take a look at why `spec/queries/display_ads/filtered_ads_query_spec.rb:132` is flaky ~2% of the time. We have unfortunately experienced an increase in flakiness and identified this test as one to take a look at more closely. 

From @maestromac

> From what I gather `expect(filtered).to contain_exactly(community_ad)` failed because `other_community` is being returned instead. I added `:aggregate_failure` to maybe see if other portion of the test will pass. I tried running 50 times and it still pass so I'd suggestion wait and see til it appears failing in CI

## Definition of Done

- [ ] Ideally, a fix to resolve or at least reduce the flakiness for this test
- [ ] If a fix cannot be determined, then a recommendation on what to do going forward

## Additional Context

- We want to timebox this investigation to no more than a week max.
- https://forem-team.slack.com/archives/C7GE84DEJ/p1687811367183559 
- https://buildpulse.io/@forem/forem

**Comment by mirie** [comment]
@jaw6 Does it make sense to pause on this for now?

**Comment by jaw6** [comment]
@mirie I _think_ so? I'd really _like_ to have figured this one out, but I think it's time to call it.

**Comment by mirie** [comment]
Closing as a won't fix for now.
