### ISSUE TITLE
Upgrade Ruby version to 3.0.6

### ISSUE THREAD

**Issue by mirie** [forem/forem#19680]
This is the tracking issue for this upgrade. 

PRs:
Infra work:
- [x] https://github.com/forem/forem/pull/19632
- [x] https://github.com/forem/forem/pull/19633

Ruby version work:
1. https://github.com/forem/forem/pull/19651 << currently open PR
2. https://github.com/forem/forem/pull/19603
3. https://github.com/forem/forem/pull/19523

**Comment by klardotsh** [comment]
Closed with merge of #19651.
