### ISSUE TITLE
Migrate Setting initializers to Pack tags

### ISSUE THREAD

**Issue by mirie** [forem/forem#19700]
## Is this feature related to a problem? Please describe.

We have remaining initializer migration work to do in order to complete this milestone.

## Definition of Done

- [ ] Migrate [initializeSettings.js](https://github.com/forem/forem/blob/main/app/assets/javascripts/initializers/initializeSettings.js) to a pack file
- [ ] Update places where [app/assets/javascripts/initializeSettings.js](https://github.com/forem/forem/blob/main/app/assets/javascripts/initializePage.js) is being called.
- [ ] Add tests (https://github.com/forem/forem/tree/main/app/javascript/packs/initializers/__tests__) as relevant

**Comment by zhangted** [comment]
Hi! Can I be assigned this one?

**Comment by mirie** [comment]
@zhangted Thank you so much for your contribution! We will try to get that second review in early next week 🙌
