### ISSUE TITLE
Migrate DisplayAdVisibility initializer to Pack tag

### ISSUE THREAD

**Issue by mirie** [forem/forem#19704]
## Is this feature related to a problem? Please describe.

We have remaining initializer migration work to do in order to complete this milestone.

## Definition of Done

- [ ] Update [initializeDisplayAdVisibility.js](https://github.com/forem/forem/blob/main/app/assets/javascripts/initializers/initializeDisplayAdVisibility.js)
- [ ] Update places initializeDisplayAdVisibility() is called
- [ ] Add tests (https://github.com/forem/forem/tree/main/app/javascript/packs/initializers/__tests__) as relevant

**Comment by Ridhwana** [comment]
Closing this one in favor of an issue I created a few weeks ago https://github.com/forem/forem/issues/19608
