### ISSUE TITLE
Fix broken `/contact` links in email

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19710]
**Describe the bug**

Some emails incorrectly use translation files intended for main views in their emails to render links to support information which breaks when sent via email.

**To Reproduce**

1. Create an organization (which you can do on `/settings/organization`)
2. Delete an organization (which you can do on `/settings/organization/<org_id>`)
3. Try to click the "Contact us" button in the email
4. Load blank `http://contact`

**Expected behavior**

Instead of a link to a page on the platform, the link should `mailto:` the Forem's configured contact email, [as used in this email.](https://github.com/forem/forem/blob/cd9d5df963e7084a289915ae14c73d87c6770070/app/views/mailers/notify_mailer/account_deleted_email.text.erb#L3).

The full text should be something like:

`Contact us at <a href="mailto:<%= ForemInstance.contact_email %>><%= ForemInstance.contact_email %></a> if there is anything more we can help with.`

For example: "Contact us at [yo@dev.to](mailto:yo@dev.to) if there is anything more we can help with."

**Additional context**

- Email is sent [here](https://github.com/forem/forem/blob/5410f6f92c99d15584297ae56098260dcb8e3032/app/mailers/notify_mailer.rb#L100)
- Incorrect translations are defined [here](https://github.com/forem/forem/blob/5410f6f92c99d15584297ae56098260dcb8e3032/config/locales/en.yml#L3).
- You can find the offending list of emails that uses the incorrect translation file [here](https://github.com/search?q=repo%3Aforem%2Fforem+app%2Fviews%2Fmailers%2Fnotify_mailer%2F+contact_prompts&type=code).
- Ideally, the body text of the email would be kept in the translation files, but I'm unsure of the complexity of this approach re-calling Forem configuration, so this is not required for this issue.

**Comment by maestromac** [comment]
I do want to point out that you can preview email changes locally by navigating to `http://localhost:3000/rails/mailers`

**Comment by PhilipHow** [comment]
Hey @NAMAN547, I've assigned this to you. Please make sure you've read through the [contributors guide](https://developers.forem.com/contributing-guide/forem) first.

Feel free to ask any questions.

When do you think could get get a PR opened for this issue?

**Comment by bytehala** [comment]
Hi @PhilipHow @NAMAN547 can I work on this?

**Comment by SID262000** [comment]
Hi @PhilipHow,

I already see 2 developers in line ready to fix this problem. Let me know in case it takes longer than expected, would be happy to collaborate and fix the issue, Thanks

**Comment by NAMAN547** [comment]
@PhilipHow Due to personal issues, I will not be able to work on this issue at the moment. I'm really sorry for that.

Please feel free to assign it to the concerned developer
Thanks

**Comment by SID262000** [comment]
Since @NAMAN547 has decided to not move ahead with this issue, @bytehala are still actively looking to fix this issue.

Let me know your thoughts.
cc: @PhilipHow
