### ISSUE TITLE
Comment reaction interaction temporarily displaying "behind" other elements on the page

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19722]
**Describe the bug**

Upon adding a ❤️ reaction to a comment, the like interaction/animation is temporarily appearing behind other elements on the page.

**To Reproduce**

1. Be logged in
2. Navigate to a thread with multiple comments
3. Leave a ❤️ reaction on a comment
4. Observe the "Like" text box appearing behind other elements

**Expected behavior**

The box/text is consistently rendered above other elements on the page.

**Screenshots**

https://github.com/forem/forem/assets/9434801/50d624cc-4145-4012-afe6-aaeff718e736

**Desktop (please complete the following information):**

Not device specific (tested on multiple)

**Comment by ktmouk** [comment]
I've created this [PR](https://github.com/forem/forem/pull/20035) to fix this issue ✨ 
Could you review this PR when you have a time?
