### ISSUE TITLE
Update Fastly config to include client country and region as a header

### ISSUE THREAD

**Issue by filleduchaos** [forem/forem#19792]
## Is this feature related to a problem? Please describe.

As a billboard creator, I’d like to restrict billboard displays to a particular country or region where they are most relevant. And as a platform, we want to offer this service without tracking or storing users' personally-identifying information.

## Describe the solution you’d like

Fastly, our edge network, has a built-in geolocation service that can be used to determine the country and region that a request originates from (based only on its IP address, which is information we require anyway to even serve the site to them). IP geolocation accuracy varies based on the visitor's ISP and how up-to-date the geolocation service's tables are, but in general is fairly accurate (95%+ at identifying the country, and ~80% at identifying the region).

## Definition of Done

- [ ] Incoming web requests have a header (`HTTP_CLIENT_GEO`) attached with the (fairly) accurate ISO 3166-2 country and region code of the requester (e.g. `"US-NY"` for the state of New York).

## Additional Context

[Fastly resource on geolocation at the edge](https://developer.fastly.com/learning/concepts/geolocation/)

**Comment by benhalpern** [comment]
This looks good to me.

One additional consideration which I think I failed to point out in a prior communication is that the async-rendered billboard paths will also need to vary the response based on GEO here.

That is to say — the billboards controller will now need to have the geo added as a cache key consideration at the edge _or_ we need to actually just remove caching for this endpoint altogether — which will make scaling more of a challenge, but I think is probably appropriate given the trade-offs.

**Comment by filleduchaos** [comment]
Linking this discussion in https://github.com/forem/forem/issues/19793#issuecomment-1644373684 for more context; if we want to include geofencing at the edge in this, we could either re-estimate this issue or draft another one to implement region-based caching for server-rendered billboards.

Is it particularly costly (dev time, TTL) to deploy our Fastly config? If not, just getting the header to begin with might be a good start (and we can leave off implementing handling the `Vary` header until we have the backend in place)

cc @maestromac

**Comment by maestromac** [comment]
I don't think it should be too bad. This data should either already exist or be a should be straightforward to get it in place.
