### ISSUE TITLE
Basic admin UI for targeting billboards by location

### ISSUE THREAD

**Issue by filleduchaos** [forem/forem#19794]
## Is this feature related to a problem? Please describe.

As a billboard creator, I’d like to restrict billboard displays to a particular country or region where they are most relevant.

Therefore as a platform, we need to give admin users a way to enter locations that a billboard should target.

## Describe the solution you’d like

Full international location would benefit from a more complex UI (such as country and region dropdowns), but that would also introduce complications such as how to ship all of the options to the frontend as well as i18n considerations (e.g. localizing "region" to country-specific terms such as state, province, department, etc).

In the meantime however we can ship a simple comma-separated input field of ISO 3166-2 codes that's validated by the server. The code validation is already implemented in #19790, so we just need to hook up to it

## Definition of Done

- [ ] Admins can enter and save a list of valid ISO 3166-2 codes (whole countries inclusive) as target locations in the edit billboard form
- [ ] Invalid ISO 3166-2 codes (which temporarily includes valid codes for locations outside the US and Canada) get rejected with a clear error message

## Additional Context

[This issue comment](https://github.com/forem/forem/issues/19597#issuecomment-1634771257) detailing why we are only permitting targeting the US and Canada for now

**Comment by dukegreene** [comment]
Working on this in https://github.com/forem/forem/pull/19835 today

**Comment by dukegreene** [comment]
Updated the work and folded in PJ's changes on the backend, new PR for this is at https://github.com/forem/forem/pull/19855
