### ISSUE TITLE
Flaky test: spec/system/homepage/user_visits_homepage_spec.rb

### ISSUE THREAD

**Issue by mirie** [forem/forem#19799]
## Is this feature related to a problem? Please describe.

Take a look at why `spec/system/homepage/user_visits_homepage_spec.rb` is flaky 5.6% of the time. **We want to timebox this investigation to no more than 2 days max**

User visits a homepage when logged in user when user follows tags shows followed tags ordered by weight and name

```
Failure/Error: current_user.cached_followed_tag_names

NoMethodError:
  undefined method `cached_followed_tag_names' for nil:NilClass
./app/controllers/billboards_controller.rb:40:in `user_tags'
./app/controllers/billboards_controller.rb:20:in `show'
./app/lib/middlewares/set_time_zone.rb:10:in `call'
------------------
--- Caused by: ---
Capybara::CapybaraError:
  Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
  ./spec/rails_helper.rb:170:in `block (3 levels) in <main>'
```

## Definition of Done

- [ ] Ideally, a fix to resolve or at least reduce the flakiness for this test
- [ ] If a fix cannot be determined, then a recommendation on what to do going forward

## Additional Context

- https://buildpulse.io/@forem/forem
- ![Image](https://user-images.githubusercontent.com/896728/255017218-3e197632-9a0c-4ee3-a4d1-58ffb2098ae3.png)
![Image](https://user-images.githubusercontent.com/896728/255017219-5330f105-1334-4603-9776-9e37683665e1.png)

**Comment by mirie** [comment]
@Ridhwana do you think it's worth making the updates we discussed in our 1:1 or to just move to close as it hasn't been a problem since you put in a fix?

**Comment by Ridhwana** [comment]
@mirie I have not had a chance to look into this last week, let's close it as it has not been a problem since I implemented the fix. If i do get a chance to look into it this week then I'll drop a note here.
