### ISSUE TITLE
Update billboard displays to only show billboards targeting the user's location

### ISSUE THREAD

**Issue by filleduchaos** [forem/forem#19793]
## Is this feature related to a problem? Please describe.

As a billboard creator, I’d like to restrict billboard displays to a particular country or region where they are most relevant.

Therefore as a platform, we should only show users the billboards targeting their location (which we will [obtain from Fastly](#19792)). We also need an straightforward way for devs and non-devs alike to test that the location targeting is correct.

## Describe the solution you’d like

Geolocation querying is set up by #19790, most of what we need to do is update everywhere `DisplayAd.for_display` is called to take advantage of it.

In production the geolocation will be obtained from the `HTTP_CLIENT_GEO` request header, but in development injecting headers isn't easy. We can use a `client_geo` query parameter in site URLs to specify a geolocation **in development mode only**, which can then be converted to the required header by Rails middleware (for page loads) and Javascript fetch/XHR code (for async requests).

## Definition of Done

- [ ] All the billboard placement areas display only billboards targeting the user's location (list is courtesy of @/Ridhwana, and includes a note on how they are loaded to aid development):
    - [x] Sidebar Left (First Position): Currently moving to loading async (see #19577)
    - [x] Sidebar Left (Second Position): Same as above
    - [x] Sidebar Right (Home): Server side rendered (will likely be moved to loading async as well)
    - [x] Home Feed First, Home Feed Second, Home Feed Third: Loaded async when logged in, and rendered server side when logged out.
    ~~- [ ] Home Hero: Server side rendered~~
    - [x] Sidebar Right (Individual Post): Loaded Async
    - [x] Below the comment section (Individual Post): Loaded Async

Note: we will only be implementing location targeting for async-loaded boards.

## Additional Context

[This PR](https://github.com/forem/forem/pull/19757) has a prototype implementation that should prove useful

**Comment by benhalpern** [comment]
This only needs to apply to async contexts, any place where we deliver the billboard as part of the fully cached HTML doesn't need to apply to "server side rendered" locations — as this wouldn't really work since we won't vary entire HTML pages by location.

**Comment by filleduchaos** [comment]
> This only needs to apply to async contexts, any place where we deliver the billboard as part of the fully cached HTML doesn't need to apply to "server side rendered" locations — as this wouldn't really work since we won't vary entire HTML pages by location.

@Ridhwana will we be permanently server-side rendering/caching any billboard placement areas, or are all of them set to be migrated (however slowly) to async loading?

Asking mostly because if this feature applies to some placement areas (because they are cached) but not others, it might be confusing for a creator that setting target locations has no effect. We might want to disable the locations field in the admin UI for those areas (or otherwise communicate that they can't target locations). It also looks like we will not be able to support location-targeting signed-out users (since according to the plan for the left sidebar at least, the async response for a signed-out user will also be cached?) which also might need communication/documentation as well.

I did come across Fastly's support for [geofencing at the edge](https://developer.fastly.com/solutions/tutorials/geofence/) during my exploration, so we _could_ possibly cache and serve billboards targeting specific countries or regions, but I didn't look too deeply into how it affects pricing or anything like that. It looks like it can be accomplished with only VCL though - might be a decent future enhancement (cc @mirie)

**Comment by Ridhwana** [comment]
> @Ridhwana will we be permanently server-side rendering/caching any billboard placement areas, or are all of them set to be migrated (however slowly) to async loading?

I'm double checking this: https://forem-team.slack.com/archives/C02C32DLPJP/p1690189490694919

**Comment by filleduchaos** [comment]
> I'm double checking this: https://forem-team.slack.com/archives/C02C32DLPJP/p1690189490694919

Thanks! It seems the logged-out feed and home hero will stay server rendered, so we potentially need to figure out how to cache/serve those by location.

Do you think location-aware caching should be a part of this issue or a follow-up (or maybe the existing Fastly VCL update issue)? Also, do we have any non-main-prod environments that use Fastly, for QA purposes? cc @benhalpern

**Comment by Ridhwana** [comment]
> Do you think location-aware caching should be a part of this issue or a follow-up (or maybe the existing Fastly VCL update issue)? 
I think it should probably be part of this issue so that we don't end up hitting the server too much, but perhaps @maestromac can help confirm whether he thinks caching should be implemented from the get go or whether we can afford to do the requests initially without caching. I _don't think it_ will be a very heavy lift to implement from the server side rendered location aware caching since we already have caching in place (but... famous last words). 

> Also, do we have any non-main-prod environments that use Fastly, for QA purposes? 
From my understanding no we don't. We use nginx on some of the others. However,  platform ( cc @maestromac) can confirm.

**Comment by maestromac** [comment]
yes we do have an environment that uses Fastly to QA this

I agree that caching should be implemented from the get go, but only if it's not difficult to do so.

**Comment by filleduchaos** [comment]
One snag I ran into around geofencing with Fastly is that if implemented naively (i.e. Varying the cached response by country and region) then we would be caching dozens of versions of the home page (times however many variations of it we currently cache) since the home hero billboard is rendered directly into it. That would rise into a thousand plus once we expand beyond the US and Canada). I don't know if/how that affects our Fastly pricing and/or page serving efficiency. cc @benhalpern 

I did put the location filtering functionality behind a feature flag since we have lots of non-Fastly environments, and we could add an additional flag for caching location targeting so we can toggle it off if it's too much without a deploy?

**Comment by benhalpern** [comment]
@filleduchaos location targeting will only be able to apply to async locations in general — the home hero will always be an outlier in that we bake it right into the page, and any other baked-in locations won't be ripe for precise targeting of any kind.

**Comment by mirie** [comment]
@benhalpern is this good to close?
