### ISSUE TITLE
The dropdown on billboards no longer open on the logged in home page feed billboards

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#19802]
**Describe the bug**
The dropdown on billboards no longer open on the logged in home page feed billboards

**To Reproduce**
- Log in to the app
- Create a billboard for the home page feed 
- Go to the home page 
- Click on the three dot menu
- The menu does not open

**Expected behavior**

- Log in to the app
- Create a billboard for the home page feed 
- Go to the home page 
- Click on the three dot menu
- The menu should  open

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by dukegreene** [comment]
Looks good on my MacBook running Chrome

![Image](https://github.com/forem/forem/assets/7056287/de90533d-faad-4689-9de4-b2a43cb48516)
![Image](https://github.com/forem/forem/assets/7056287/8a3ff9f0-ad92-4db2-a5be-23dd317f2cda)
