### ISSUE TITLE
Bust cache of organization page when new member is added

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19811]
**Describe the bug**

After adding a new member to the organization, sometimes the "Meet the team" area on the organization profile page won't update to reflect the new user being added.

**To Reproduce**

1. Add a user to the org
2. Observe the "Meet the team" section on the Org profile page
3. Notice that the newly-added org member isn't immediately visible
4. Bust the page via `/admin/advanced/tools`
5. See that the newly-added org member is now visible

**Expected behavior**

The newly-added org member is immediately visible in the "Meet the team" section in the Org profile page.

**Additional context**
Referring to this section here on the left:

![org profile page](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/GGu5J0no/8c45c27d-382f-4eaf-8e3b-bbf5fcf07558.jpg?v=d7498b7ba677b0533703bb4c4823402c)

**Comment by rijusougata13** [comment]
Hi @pkfrank , can you help me understand what do you mean by "Bust the page via /admin/advanced/tools"

**Comment by pkfrank** [comment]
@rijusougata13 if you are logged in as an Admin, you'll be able to navigate to `/admin/advanced/tools` which provides an interface for manually busting the cache of a given path.

![UI for busting cache](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/Wnu6Z0N0/fd7e3e09-ec87-4859-97d7-0d9ef0db1c56.jpg?v=cd5dd9c8a76523b96eabddc2fec5865c)
