### ISSUE TITLE
UI changes for tag moderation

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19822]
## Is this feature related to a problem? Please describe.

- As a tag moderator, I want an intuitive means of editing the tags of an article so that I can better manage the tags I moderate and ensure articles closely align with their assigned tags.
- The existing tag moderation controls have confusing UX and do not inform the moderator of the constraints placed on tags.

## Describe the solution you’d like

- A new UI design with separate views for tag moderator and admin views.
- The tag moderation history ("Previous tag adjustments") will be handled as a separate issue
- Logic changes (to allow tag moderators to override each other's actions) will be handled as a separate issue.

## Designs 

- See [full designs on Figma](https://www.figma.com/file/yhg9HTZDFIeWuvBt9ygrss/Moderation?type=design&node-id=1895-4729&mode=design&t=pRLL1b6DLuptuDYe-4)

![image](https://github.com/forem/forem/assets/1628871/d12241ae-aa05-4466-abdb-3724baca6681)

## Definition of Done

- [ ] When a post has the maximum number of tags, clearly show this in the tag moderation area: "A post can only have four tags".
- [ ] Change tag removal UX to initially require clicking on the tag to remove before showing the optional reason input and "Remove tag" and "Cancel" confirmation buttons beneath the tag to be removed.
  - [ ] When a tag moderator cannot remove a tag (as they are not an assigned tag moderator for the selected tag), a message should appear when the tag is hovered over: "Not allowed to adjust this tag", and the removal button will not be displayed.
- [ ] Change tag addition UX to initially require clicking on a:
  - [ ] "Add new tag" button for admins, where the tag name and optional reason inputs are shown in the tag addition area, along with "Add tag" and "Cancel" confirmation buttons
  - [ ] A button for each tag that is assigned to the tag moderator (that has not already been added to the article), for tag moderators, where the tag name will be displayed with a "+" indicator. Once clicked, an optional reason input will be shown beneath the selected tag, along with the "Add tag" and "Cancel" confirmation buttons.
    - [ ] For tag moderators, the tag moderation area should show up to 5 tags (shown with the "+" indicator) without scrolling. If a tag moderator moderates more than 5 tags that can be added, the area that shows the add tags buttons will begin to scroll.
- [ ] Changes above implemented for the light theme (see designs)
- [ ] Changes above implemented for the dark theme (see designs)

## Additional Context

- Additional issues being undertaken: 
  - https://github.com/forem/forem/issues/19823
  - https://github.com/forem/forem/issues/19824

**Comment by Ridhwana** [comment]
> The tag moderation area should show up to 5 tags before scrolling the area that shows the add tags buttons (for tag moderators assigned to moderate multiple tags).

Question: Don't we only allow 4 tags to be added to a post?

**Comment by mirie** [comment]
Yes only 4 tags is the current limitation.

Questions: 

(1) I'm confused as to what "Specific add tags" means in this sentence
> Specific add tags, for tag moderators, allowing them to add an optional reason input is shown beneath the selected tag, along with "Add tag" and "Cancel" confirmation buttons.

(2) @Ridhwana do you mean adding to the Def of Done that the look and feel is updated for light and dark themes? Or is there something more?

(3) @PhilipHow currently when a mod/admin attempts to add a tag that doesn't exist, there's a little temp modal that pops up on the lower left side: `An error occurred: Failure: Tag must exist` -- Since we're displaying error messages in this UI, we should probably fold this one in too, right?
<img width="909" alt="Screenshot 2023-07-27 at 5 37 10 PM" src="https://github.com/forem/forem/assets/896728/2e2f549b-f4b1-4c29-b555-e6620451feae">

Team for async estimation, let's consider 4 tags for now and implementing the design in both light / dark theme.

**Comment by Ridhwana** [comment]
Yes only 4 tags is the current limitation.

That would indicate that this requirement may not be necessary "The tag moderation area should show up to 5 tags before scrolling the area that shows the add tags buttons (for tag moderators assigned to moderate multiple tags)."

> (2) @Ridhwana do you mean adding to the Def of Done that the look and feel is updated for light and dark themes? 

Correct.

**Comment by PhilipHow** [comment]
@Ridhwana @mirie 

I've tidied up the language. The five tags refer to "+" buttons shown to tag moderators.
