### ISSUE TITLE
#sheCoded "Latest" not descending date order

### ISSUE THREAD

**Issue by TerabyteTiger** [forem/forem#1984]
**Describe the bug**
When reviewing the posts on https://dev.to/t/shecoded/latest there are posts from March 2018 showing above posts from 2019. 

**To Reproduce**

1. Go to https://dev.to/t/shecoded/latest
2. Scroll down the list of posts and notice the dates.
3. See error

**Expected behavior**
Posts should properly be listed from newest -> oldest

**Screenshots**
Shown here, the Mar 8th & 9th posts from 2018 are above the post "Nevertheless, Ananya Coded" (Mar 5th this year).
![List of posts showing 2018 posts before a 2019 post](https://user-images.githubusercontent.com/16465776/53831935-fe223180-3f53-11e9-9fae-04d0c72d8220.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version  72.0.3626.119 (Official Build) (64-bit)

**Comment by GaganGupta19** [comment]
It's showing readable_publish_date but all the stories are sorted by descending order of published_at
after looking at the code. There's a column `crossposted_at` which might contain previous year value. 

`  def readable_publish_date
    relevant_date = crossposted_at.present? ? crossposted_at : published_at
    if relevant_date && relevant_date.year == Time.current.year
      relevant_date&.strftime("%b %e")
    else
      relevant_date&.strftime("%b %e '%y")
    end
  end`

What's crossposted at?

**Comment by rhymes** [comment]
Hi @GaganGupta19, looking at [Article#readable_publish_date](https://github.com/thepracticaldev/dev.to/blob/master/app/models/article.rb#L357):

https://github.com/thepracticaldev/dev.to/blob/a17cfe7d335cbf15fd70208e9cb6e3904cfe0a20/app/models/article.rb#L357-L364

`crossposted_at` is for imported posts from RSS. It takes precedence over `publish_date` on the first line, but then they are treated exactly the same.

Regarding the issue raised by @12vanblart, the code that determines the content of the tag's latest page, if I'm not mistaken, is in [stories_controller.rb](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/stories_controller.rb) and by a quick look I'd say around here at line 257:

https://github.com/thepracticaldev/dev.to/blob/a17cfe7d335cbf15fd70208e9cb6e3904cfe0a20/app/controllers/stories_controller.rb#L252-L261

**Comment by GaganGupta19** [comment]
Yes @rhymes, you're right 👍 
But the issue which @12vanblart has shared is related to the date which is being shown there. 

there are 2 posts.
post 1 - sowju coded
post 2 - ananya coded

post 2 is showing after post 1 which means the published_at date of post 1 is greater than post 2. 
but date which is being showed on post 2 is greater than post post 1

which means that the crossposted_at of post 1 is lesser than the published_at of post 2. 

I guess the functionality is working fine but there is some data issue

**Comment by mstruve** [comment]
The problem here was that we used to be sorting by the readable published date which was not accurate. We are now sorting by the actual datetime in Elasticsearch so this is no longer an issue. Thanks as always for reporting!!! We really appreciate it!
