### ISSUE TITLE
Store which languages users understand - backend only

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19846]
## Is this feature related to a problem? Please describe.

- As a community member where my primary language is not English, or I am able to understand languages other than English, I would like to see more posts written in my primary language or other languages I understand so that I can read more posts and contribute to a smaller non-English speaking community.
- As a community member who does not speak additional languages other than English, I would not like to see posts in languages I do not understand, so I only see content that is relevant to me.

## Describe the solution you’d like

- Keep a discrete list of "languages" within the platform and track which users can understand which language. Each item should be a single language that can have a relationship to a user (see many-to-many below).
- As the primary source of languages will be those detected by `cld3`, we should extract [this list](https://github.com/google/cld3#supported-languages), and use this as our hardcoded set of languages. We should explore whether we could use this list directly from the gem somehow.
- We will assume a "default" language for each Forem. This could use the existing "default locale" setting, but as this is tied to 'UI localization', we should add in a separate configuration for this.
- Store a many-to-many relation between users and languages as 'understood languages'. This could re-use the existing 'follow' mechanism (where a user would follow one or more than one language) if there was deemed benefit to using this approach. User-language relations will not need to be seeded as part of this issue.

## Definition of Done

- [ ] Keep a discrete list of languages in the platform/database
- [ ] Populate the list of languages from `cld3`
- [ ] Store a "default content" language for each Forem
- [ ] Track a many-to-many relation between users and languages to model which languages a user understands

## Additional Context

- We are separating out 'content localization' as a discrete topic from our wider i18n efforts. This is with the goal of encouraging more non-English content on DEV and other future Forems and increasing the feed quality for members overall.
- This work builds on the work to automatically assign languages to each post in https://github.com/forem/forem/issues/19755
- We are focussing on getting the model correct in the backend before we introduce changes/features to the frontend.
- Using the `cld3` list of languages is an initial simplification of the task. In the future, languages should be sourced from a standard list (i.e., use an existing gem, consolidate existing gems, or find a new gem). The dataset should contain the ISO 639 code for the language and the name of the language in English and in each language's own language.
- We do not need any regional variations of languages (e.g., "en-US") as we are assuming general comprehension for a single language across regional variations, and the current detection library does not support this.
- Eventually, users will be able to indicate what languages they understand as part of their profile and likely as part of some onboarding step (or shortly after). We will likely seed some of this data using safe assumptions at a later date.
- Eventually, we will feed the additional languages the user understands into the feed algorithm to return more content in a language the user understands and filter out content that the user does not understand.
- The list of understood languages is separate from any future 'UI localization'/locale setting in a user's settings.
- To keep things simple, I don't think we need to store a user's 'primary language' at this stage; all 'understood languages' will be assumed to be equal. I think a lot of sensible defaults can be assumed from the Forem's 'default language', and greater flexibility can be determined in the future to determine if platform functionality uses this 'default language' or not.

**Comment by yheuhtozr** [comment]
FYI: a past attempt https://github.com/forem/forem/pull/14564

**Comment by jaw6** [comment]
This seems straight-forward enough. I'm not fully convinced that there's a lot of value in splitting this work into separate front-end and back-end sections — for example, the "back-end" doesn't "need" a list of supported languages (at least, not as much as the front-end needs a list of selectable labels for BCP-47 codes — and, even then, if a user understands a language we don't actually support, I don't think it 'hurts' to store that anyway) — but it's probably fine ?

> We do not need any regional variations of languages (e.g., "en-US") as we are assuming general comprehension for a single language across regional variations, and the current detection library does not support this.

I'll also just remind that this bit works better in English than it does in _many_ languages. As long as we're aware, I think it's a reasonable limitation to work within (and, as mentioned, the library we're working with may not automatically detect regional differences).

**Comment by lightalloy** [comment]
The list of languages is accessible through `CLD3::TaskContextParams::LANGUAGE_NAMES`, we can also create a wrapper to isolate that depencency (in case we'll later need to modify our list/language detecting tool).

**Comment by lightalloy** [comment]
Options to store user languages:

1) Store languages in the database table, set up a many-to-many relation with users table

            pros:
            + more flexibility
            + easy to query users who know a certain language
            
            cons:
            - have to make another query (could use cache to avoid it)
            - have to store a list of languages/sync with cld3

2) Serialize language "keys" and store in the users table

          pros:
          
          + easy to access languages that are understood by a user
          + don't have to add language/users_languages models/tables
          + don't have to sync the list of languages
          + we already store language keys in articles, so won't have to change articles.language to language_id for consistency
          
          cons:
          - users table already has 100500 fields and I'm reluctant to add another one
          - less efficient query if we need to select a list of users who understand a certain language (for now it seems like we don't need it that often)

3) Store as a profile field (profile data)

          pros:
          + stored separately
          + maybe it'll be convenient to implement configuring in the profile
          cons:
          - harder to query user's language, have to get if from "users" => "profiles.data.languages"
          - hard to query users who know a certain language

4) Other way I haven't considered?

**Comment by jaw6** [comment]
What do you think about a hybrid of options 1 & 2 ? We could store language "keys" in a table, call  it something like `users_languages`, store `user_id` and the language identifier. Would still be an extra query (or a join, maybe?) but otherwise seems to me to have most of the pros and few of the cons.

**Comment by lightalloy** [comment]
@jaw6 that's an interesting idea, thank you for the input :raised_hands:
