### ISSUE TITLE
Show post language on dashboard

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19847]
## Is this feature related to a problem? Please describe.

As a post author, I would like to see what language my content has been automatically detected in, so I can manage my content better and query any erroneous detection

## Describe the solution you’d like

- On the dashboard page, if an article has been automatically detected to a language (as in https://github.com/forem/forem/issues/19755), the language should be displayed on each listed article.
- The language should be displayed using the English term for the language.

**Designs** - [Figma link](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?type=design&node-id=2582-729&mode=design&t=OkJzVzvo9wK495Mc-4)

![Frame 1](https://github.com/forem/forem/assets/84626054/6a22f848-d01e-41f3-bd27-35e09e1c02c8)

## Definition of Done

- [ ] Each article, that has its language detected, displays the detected language on the dashboard in English.

## Additional Context

- We will need to start giving visibility to automatic language detection so users can see what language their content is being produced in. This is a simple first step at achieving this.
- Initially, we will not look to localize language names.
- Image of the existing article view on the dashboard
![image](https://github.com/forem/forem/assets/1628871/c84eae6b-3441-4217-8a10-bf1fa40038a8)

**Comment by anujbhavsar96** [comment]
@PhilipHow are we displaying this information only in the dashboard? Or any other places like feed cards, post pages, and admin page?

**Comment by PhilipHow** [comment]
@anujbhavsar96 Just on the dashboard for the time being.

**Comment by narender2031** [comment]
@PhilipHow Can you please assign this task to me?  I am already doing the spike to add `lang` as attribute to articles. This task will help me gain more knowledge on articles.
