### ISSUE TITLE
Dependency Resolution Error when Installing @babel/plugin-proposal-private-methods

### ISSUE THREAD

**Issue by CodeExplorerX** [forem/forem#19860]
### Title
Dependency Resolution Error when Installing @babel/plugin-proposal-private-methods

### Description:
When trying to install the @babel/plugin-proposal-private-methods package in my Forem project using npm, a dependency resolution error occurs, leading to a failed installation.

### Expected Behavior:
I expect the @babel/plugin-proposal-private-methods package to be successfully installed, and the dependency resolution to be completed without errors.

### Versions:

- Ruby: 3.0.6
- Node.js: 16.20.1
- Yarn: 1.22.18
- npm: 8.19.4

### Steps to Reproduce:

1. In my Forem project with the above-mentioned versions installed, I run the following command to install @babel/plugin-proposal-private-methods:
`npm install --save-dev @babel/plugin-proposal-private-methods`

Actual Result:
The installation fails with an error and displays the following message:

> npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @storybook/core-client@6.5.16
npm WARN Found: webpack@5.75.0
npm WARN node_modules/@storybook/core-client/node_modules/webpack
npm WARN   peer webpack@"^5.1.0" from terser-webpack-plugin@5.3.6
npm WARN   node_modules/@storybook/core-client/node_modules/terser-webpack-plugin
npm WARN     terser-webpack-plugin@"^5.1.3" from webpack@5.75.0
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack@"*" from @storybook/core-client@6.5.16
npm WARN node_modules/@storybook/core-client
npm WARN   @storybook/core-client@"6.5.16" from @storybook/core-server@6.5.16
npm WARN   node_modules/@storybook/core-server
npm WARN   1 more (@storybook/manager-webpack4)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @testing-library/cypress@8.0.7
npm ERR! Found: cypress@12.7.0
npm ERR! node_modules/cypress
npm ERR!   peer cypress@">3.0.0" from cypress-file-upload@5.0.8
npm ERR!   node_modules/cypress-file-upload
npm ERR!     dev cypress-file-upload@"^5.0.8" from the root project
npm ERR!   peer cypress@"*" from @cypress/code-coverage@3.10.8
npm ERR!   node_modules/@cypress/code-coverage
npm ERR!     @cypress/code-coverage@"^3.10.8" from the root project
npm ERR!   2 more (@knapsack-pro/cypress, the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^2.1.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0" from @testing-library/cypress@8.0.7
npm ERR! node_modules/@testing-library/cypress
npm ERR!   dev @testing-library/cypress@"^8.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: cypress@11.2.0
npm ERR! node_modules/cypress
npm ERR!   peer cypress@"^2.1.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0" from @testing-library/cypress@8.0.7
npm ERR!   node_modules/@testing-library/cypress
npm ERR!     dev @testing-library/cypress@"^8.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/forem/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/forem/.npm/_logs/2023-07-28T09_58_25_821Z-debug-0.log### 

### Additional Information:

- The error indicates a conflict in resolving the cypress dependency required by different packages.
- The issue may be related to overriding a peer dependency, leading to dependency resolution problems.
- Attempts to use the --force flag or update dependencies do not resolve the problem.

### Logs:
Full logs of this installation are available in the file: /home/forem/.npm/_logs/2023-07-28T09_58_25_821Z-debug-0.log

> 0 verbose cli /home/forem/.nvm/versions/node/v16.20.1/bin/node /home/forem/.nvm/versions/node/v16.20.1/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/forem/.nvm/versions/node/v16.20.1/lib/node_modules/npm/npmrc Completed in 19ms
6 timing config:load:builtin Completed in 19ms
7 timing config:load:cli Completed in 12ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/forem/forem/.npmrc Completed in 1ms
10 timing config:load:project Completed in 8ms
11 timing config:load:file:/home/forem/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/forem/.nvm/versions/node/v16.20.1/etc/npmrc Completed in 2ms
14 timing config:load:global Completed in 2ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 48ms
19 timing npm:load:configload Completed in 48ms
20 timing npm:load:mkdirpcache Completed in 3ms
21 timing npm:load:mkdirplogs Completed in 3ms
22 verbose title npm install @babel/plugin-proposal-private-methods
23 verbose argv "install" "--save-dev" "@babel/plugin-proposal-private-methods"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/home/forem/.npm/_logs
28 verbose logfile /home/forem/.npm/_logs/2023-07-28T09_58_25_821Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 70ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 0ms

**Comment by CodeExplorerX** [comment]
@forem-team

**Comment by maestromac** [comment]
When setting up via bare-metal, I would suggest you follow our setup guide thoroughly. In this case, you should be using yarn, not NPM to install dependencies without issue.

May I also suggest you checkout new alternative setup options on [this post](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49).
