### ISSUE TITLE
Technical spike on filter out tags with user-assigned negative weights from the "Relevant" feed

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19867]
## Describe the solution you’d like

See #19829. This is a technical spike to allow an engineer to explore the codebase and confirm if the estimate is appropriate.

## Definition of Done

- [x] Update #19829 with findings and clear instructions for engineer taking on this issue
- [x] Remove `blocked` label on #19829 and move to "Ready for Dev"

**Comment by mirie** [comment]
@dukegreene how is this spike going? I think we wanted to timebox to about a day

**Comment by Ridhwana** [comment]
Hey @dukegreene 👋 Just wanted to check in to find out what was the outcome of the spike?

**Comment by jaw6** [comment]
I believe this can be closed now, after #19948, but please re-open if I am wrong?
