### ISSUE TITLE
Notifications on a thread are still sent from a blocked user

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19878]
**Describe the bug**

A notification to a reply on a thread still comes through, even when the user is blocked

**To Reproduce**

1. Block a user
2. Comment on a third-party's post
3. Get the blocked user to reply to your comment
4. Recieve a notification from a blocked user

**Expected behavior**

I should not receive a notification, as I have blocked the user.

**Screenshots**

![Image](https://github.com/forem/forem/assets/1628871/4fbb943f-31fc-405e-90c9-37148db4d17d)

**Desktop:**

- OS, version: Windows 11 Pro
- Browser, version: Google Chrome Version 113.0.5672.93 (Official Build) (64-bit)

**Additional context**

- [Original slack thread](https://forem-team.slack.com/archives/CAA200SH5/p1690983147278609)
- Tested on Canary 1
  - [Blocked user](https://canary1.forem.lol/philiptest1_367)
  - [Comment which triggered the erroneous notification](https://canary1.forem.lol/philiptest1_367/comment/35)

**Comment by mirie** [comment]
Re-opening as there's a remaining PR that's in  review.
