### ISSUE TITLE
Speed up creating an organization

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19881]
## Is this feature related to a problem? Please describe.

- As an organization creator, I want to create an organization quickly, so I can start interacting with the community as my organization as soon as possible.

## Describe the solution you’d like

- We should remove the required status of the "Website URL" and "Summary" fields - as organizations may want to loop back and provide that information at a later date. We should ensure organization profiles continue to operate with this missing info.
- There is currently no manual verification of the "Proof" field when creating an organization. We should remove this field from the new organization UI.

## Definition of Done

- [ ] Remove the required status of  "Website URL" and "Summary" 
- [ ]  Ensure organization profile pages (and other areas) continue to function without "Website URL" and "Summary" 
- [ ] Remove the required status of the "Proof" field and remove it from the new organization UI.

## Additional Context

- This speeds up organization creation generally but is also intended to speed up the creation when a user is signing up for Pro Tools.
- Organizations are not always physical/legal organizations and are sometimes just used to group articles together (other platforms use the term "publications"). These ad-hoc groups are harder to verify.
- We should keep "Proof" in the database as we may introduce it or start to use it at some point.
- In the future, we may add in an "verification" process to verify organizations, and display a badge on the organizations profile.

**Comment by Ridhwana** [comment]
```

  create_table "organizations", force: :cascade do |t|
    t.integer "articles_count", default: 0, null: false
    .......
    t.text "proof"
    t.text "summary"
    t.string "url"
    t.index ["secret"], name: "index_organizations_on_secret", unique: true
    t.index ["slug"], name: "index_organizations_on_slug", unique: true
  end
```

It doesn't look like we require the url, proof or summary in the database hence we shouln't need to write any scripts or amend the migrations etc. We probably want to amend the model validations for these.

**Comment by dukegreene** [comment]
PR is ready for review at https://github.com/forem/forem/pull/19952
