### ISSUE TITLE
Article Sidebar billboard should not be visible on mobile screens

### ISSUE THREAD

**Issue by rt4914** [forem/forem#19897]
**Describe the bug**

Article Sidebar billboard is currently visible on mobile screens. It should be hidden on smaller screens.

<img src="https://github.com/forem/forem/assets/9396084/59089585-0abf-4679-9915-70fc14bfe7f9" width="250" />

We have a style named `crayons-post_sidebar_display_ad ` (might be renamed to `crayons-post_sidebar_billboard` after merging #19887). This style was getting used in article-sidebar-billboards earlier but in one of the commits https://github.com/forem/forem/commit/1d60c5ff776e5085e8f15ec708d7dff3838e2d0c it was removed while updating designs.
It should be added back to article-sidebar-billboard so that the billboard is not visible on screens smaller than `breakpoint-l`.

**To Reproduce**

1. Create a article-sidebard-billboard `Sidebar Right (Individual Post)` using `/admin/customization/billboards/new`
2. Check this billboard on any article.
3. Change screen to smaller screens.
4. This billboard is still visible, it should be hidden.

**Comment by benhalpern** [comment]
IMO this is a happy little accident, and actually a pretty great implementation!

I'd chalk this up as a feature vs bug. It appears below everything else so doesn't get in the way and works out pretty well.
