### ISSUE TITLE
Remove unique body markdown validation

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19894]
## Is this feature related to a problem? Please describe.

As a post-author, who writes a lot of ritual content, I would like to write the same body content for every edition of the ritual content, so I can efficiently produce ritual content for the platform.

## Describe the solution you’d like

- We currently validate unique combinations of post `body_markdown` and `title`, ensuring repeated content is not published.
- This is a rudimentary validation and doesn't prevent any real-world spam usage (where modifications are trivial to a determined spammer but more friction to genuine users creating ritual content).
- This validation should be removed.

## Definition of Done

- [ ] Remove the unique constraint/validation against post `body_markdown` and `title`.

## Additional Context

- I believe this is set [here](https://github.com/forem/forem/blob/2689da34e7699d389a66858c26d32b5d7a21d3b1/app/models/article.rb#L152C46-L152C46)
- [More context](https://forem-team.slack.com/archives/CAA200SH5/p1689972136032719) (Forem Team Only)

**Comment by narender2031** [comment]
@PhilipHow and @rt4914 Can You guys please assign this issue to me.

**Comment by PhilipHow** [comment]
@narender2031 Go for it!
