### ISSUE TITLE
`limited` role/status for new users onto the platform

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19891]
## Is this feature related to a problem? Please describe.

- As a Forem admin, I want a clear means of establishing who a new user is, so I can manually or automatically review their profile before making their presence more widely known on the platform.

## Describe the solution you’d like

- We currently advertise new users on the platform through a number of means:
  - Round-robin notifications for new user activity for trusted users
  - "Follow" notifications, as users are encouraged to follow other users as part of onboarding
- This approach is problematic for spam accounts, as established users are made aware of a disproportionate amount of spam accounts that otherwise have their impact limited on the platform.
- We will introduce a new `limited` user status, that we can drive functionality off in future issues to limit the impact of these unverified accounts.

## Definition of Done

- [ ] Add a new `limited` user status that is displayed in the UI as "Limited"
  - The status should be appliable by users with the `admin` role
  - The status should be supported by the bulk status assignment tool 
  - When users have the `limited` status applied, the pill should appear on the Member manager in `/admin` in yellow. e.g.![image](https://github.com/forem/forem/assets/1628871/ab5a1c7d-0f66-4079-9ebb-098b32464ec9)
  - Generally, the status should be displayed in line with the existing statuses elsewhere on the platform

## Additional Context

- Although the new user context is most relevant in this situation, `limited` is a more generic name as it might be used in moderation practices in different contexts.
- We will drive functionality to stop round-robin notifications for `limited` users in https://github.com/forem/forem/issues/19892
- In the future, we may drive other functionality on this setting. For example, the posting frequency limits placed on new user accounts.

**Comment by Ridhwana** [comment]
I think this one is pretty well defined, two main aspects we touch is:

- The Settings Model, we'll add a [new setting under authentication](https://github.com/forem/forem/blob/Ridhwana/tag-page-buttons/app/models/settings/authentication.rb#L1) and we'll specify a default. 

- We'll [need to add the limited role option](https://github.com/forem/forem/blob/Ridhwana/tag-page-buttons/app/services/moderator/manage_activity_and_roles.rb) and show it in the interface wherever else we able to choose a role.

**Comment by Ridhwana** [comment]
Some follow up questions that I had for Phil that he's answered already, I'll drop them here for others incase they have the same clarifying questions as I do: 

> Am i correct in saying that we’re doing this manually? or are we trying to automate this based on the user created at date or something similar?

The platform will automatically be creating new users with the limited status, from which we will need to update them via the API. It's likely going to be a forem tools process to say whether a user is a likely spammer and either suspend them or clear their status back to good standing. This isn't confirmed yet, though.

> Am I understanding the process correctly, if we have a 50-100 new users sign up, is the team going to go through each one and change it to good standing (edited)

No, we would only use this (i.e. set the new user status configuration to `limited) once we had the automation in place.
Within this issue are we limiting the impact of limited users?
 
> Within this issue are we limiting the impact of limited users? 

No, I've logged to further issues for this. I didn't update the actual issue with those specific links - I'll do so now
https://github.com/forem/forem/issues/19892
https://github.com/forem/forem/issues/19893
[#19892 Suppress round-robin notifications for `limited` users](https://github.com/forem/forem/issues/19892)
<https://github.com/[forem/forem](https://github.com/forem/forem)|forem/forem>forem/forem | Aug 4th | Added by [GitHub](https://forem-team.slack.com/services/B01U6DYP7F0)

> Ok so right now, when we create a new user, we’ll still be giving them the status of good standing and not limited even if its enabled on the Forem?
Will update with a response once Phil confirms.

**Comment by jaw6** [comment]
My initial concern here was around introducing a change for "default users" (and, potentially impacting a _whole lot_ of tests). But I think I misunderstood something initially, so want to mostly focus on making sure I (now) understand the request here.

I _think_ the idea is that this is something _configurable_ in Admin and _not_ a change in the "default" role assigned to newly created users.

Or, to phrase that differently, I understand the request here as something like:

* If an admin setting is _true_, then newly-created users are assigned a new role, `limited`
* If the admin setting is _true_, users with the `limited` role have a visible icon in the admin member view
* If the admin setting is _true_, users with the `limited` role do not generate round-robin notifications (but this work in handled in a separate issue)

I understand the current request not to apply any "intra-role" behavior (being promoted to `trusted` or `admin` does _not_ effect `limited`).

**Comment by PhilipHow** [comment]
@jaw6 

Not quite. The limited status and the setting to control new users' default status are separate.

This issue handles the introduction of the status and its display on the platform. Other issues will drive functionality off of the status to prevent round-robin notifications, etc. There could be other uses for the status in the future outside of the new user context.

The admin setting dictates whether a new user receives this status or not. If they do, there's an assumption new users will be manually or automatically via the API moved to the good standing status once their accounts have been validated.

**Comment by mirie** [comment]
Note: Pulling out  Create a new setting in /admin/customization/config: "New user status" to a separate issue
