### ISSUE TITLE
Suppress round-robin notifications for `limited` users

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19892]
## Is this feature related to a problem? Please describe.

- As a Forem admin, I want to prevent users from seeing any potential spam accounts and minimize the impact that spam accounts have on the platform.

## Describe the solution you’d like

- Round-robin notifications about a certain user (i.e., when a new user comments or creates a post) should not be triggered if the user has the `limited` status introduced in #19891.

## Definition of Done

- [ ] Prevent round-robin notifications from being fired for users who have the `limited` status

## Additional Context

- We intended for an automated external service to set a new user's status from `limited` to "Good standing". This will likely fire relatively quickly after a new user has created an account, preserving round-robin notifications for legitimate new users.

**Comment by Ridhwana** [comment]
I stand to be corrected but I think right now [notifications are sent unless the user.comments_count > 2](https://github.com/forem/forem/blob/b6b64c5d5b2abb1ad4d3a7168bd0ba9f76daac79/app/models/comment.rb#L225-L229).  In this case we may need to add the additional restrictions like the role.
