### ISSUE TITLE
Allow trusted users to see whether a user is suspended

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19934]
## Is this feature related to a problem? Please describe.

As a trusted user, I want to see whether a user has been suspended or not so that I know that admin action has already been enacted on their account.

## Describe the solution you’d like

- Trusted Users will be able to see whether a user has been suspended or not on their profile.

## Definition of Done

- [ ] For trusted users - show the "Suspended" pill user status (that is currently used in the member manager) on the suspended user's profile page.

## Additional Context

-The [user_profile_header area is a cached area](https://github.com/forem/forem/blob/Ridhwana/following-tag-page-buttons/app/views/users/show.html.erb#L20-L121) and we may not use current_user in a cached code path. Hence, we may want to make this an async call and insert it in the DOM afterwards.
- We are getting duplicate reports on user accounts from multiple trusted users who are unaware that action has already been taken. See this [slack thread](https://forem-team.slack.com/archives/CAA200SH5/p1691422492532989) (internal Forem Team only) for more context.
- Mockup of the "Suspended" pill 
![image](https://github.com/forem/forem/assets/1628871/0712daa0-3855-497e-86dd-98d2822a5f96)

**Comment by Ridhwana** [comment]
@PhilipHow the [`user_profile_header` area is a cached area](https://github.com/forem/forem/blob/Ridhwana/following-tag-page-buttons/app/views/users/show.html.erb#L20-L121) and we may not use `current_user` in a cached code path. Hence, we cannot check `current_user` properties like whether the current user is trusted or not. 

I'm not sure what a workaround would be, I doubt we'd want to remove caching in that area, so maybe we want to show the suspended badge to all irrespective of the user_role?

**Comment by PhilipHow** [comment]
I think we want to keep this to trusted users, as its information about moderation action we have taken we don't always want that to be public.

Could we do an async call from the page?

**Comment by Ridhwana** [comment]
> Could we do an async call from the page?

Yeah that could probably work. I'll update the description and move this to ready for estimation.

**Comment by mirie** [comment]
@jaw6 I see you have a [draft PR up](https://github.com/forem/forem/pull/20061) and a potential question re: pill look and feel. 

> The "pill" looks a little different here than on the admin panel, I have not fully investigated (css-is-awesome-mug.jpg), but I think it might be close enough for the purpose here?

@anujbhavsar96 (cc @PhilipHow) I'm tagging you for input!

Anything else that would be helpful to chat through with Phil re: complexities/tradeoffs?

**Comment by jaw6** [comment]
> Anything else that would be helpful to chat through with Phil re: complexities/tradeoffs?

Just the style mis-match, at this point.

**Comment by anujbhavsar96** [comment]
> Just the style mis-match, at this point.

Yeah, we can use the same component we use on the admin side.


<img width="340" alt="image" src="https://github.com/forem/forem/assets/84626054/fd2cc518-50b1-43da-bb8a-a0f5170f89ce">

**Comment by jaw6** [comment]
In terms of HTML, it _is_ the same component, for what it's worth, but the context changes how it renders.

**Comment by mirie** [comment]
@jaw6 From my glance, it looks like the difference from what @anujbhavsar96 attached in the last comment and the screenshot on the PR is that there's less space btw the user's name and the pill. Is that correct?

**Comment by anujbhavsar96** [comment]
@jaw6 @mirie Since the pill is inside `<h1>`, it has been rendered differently with the heavy font. But we can use the same component as the admin profile and achieve consistent results.

I was experimenting with HTML, and [here is the loom video for it](https://www.loom.com/share/aacbb7f5e60d4672b022f5a3401969e1).

**Comment by jaw6** [comment]
@anujbhavsar96 the Loom was helpful, thanks!

Current status:

<img width="1037" alt="image" src="https://github.com/forem/forem/assets/2077/dce14a5a-7608-4dff-80f2-fb37300694d5">

**Comment by anujbhavsar96** [comment]
Almost close, just two more small things @jaw6 

1. Pill has margin-left of `ml-3` in admin. We should have the same here so the pill doesn't look sticky to name. And it should be horizontally center-aligned with the name, just like admin. I think it has been done with Flexbox in admin.
<img width="1285" alt="image" src="https://github.com/forem/forem/assets/84626054/a81fc1e3-e2e9-488c-a360-036a89275aaa">


2. The whole name+pill component has a margin-bottom of `mb-2` in our current implementation, so name and bio don't look cramped up.
<img width="1287" alt="image" src="https://github.com/forem/forem/assets/84626054/603ccaca-f0dc-4125-81ac-44cdaaf297c1">

**Comment by jaw6** [comment]
<img width="1038" alt="image" src="https://github.com/forem/forem/assets/2077/69e0b66c-7c67-40e7-9c77-953596e55b47">

**Comment by anujbhavsar96** [comment]
@jaw6 Just a very small nitpick, which isn't even noticeable, but the pill is not somehow center-aligned to the name just as we have for the admin profile.

<img width="732" alt="image" src="https://github.com/forem/forem/assets/84626054/6d6b7fbb-26d0-45fc-9a31-2495174dcefd">
