### ISSUE TITLE
Some versions of cloudinary profile image are zoomed in too far on dev.to

### ISSUE THREAD

**Issue by lionel-rowe** [forem/forem#19970]
**Describe the bug**

Some versions of the cloudinary-hosted profile_image are zoomed in too far on dev.to.

Example:

![image](https://github.com/forem/forem/assets/26078826/61cf71d7-f6c4-4580-970f-8ee90977997d)

* Red: over-zoomed, `src` = https://res.cloudinary.com/practicaldev/image/fetch/s--bcGifSKE--/c_imagga_scale,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/169338/1b23b783-9452-493b-adbb-6e4aff12ad7c.jpeg
* Green: expected, `src` = https://res.cloudinary.com/practicaldev/image/fetch/s--YYqb6inY--/c_fill,f_auto,fl_progressive,h_50,q_auto,w_50/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/169338/1b23b783-9452-493b-adbb-6e4aff12ad7c.jpeg

Word-diff of the `src` with newlines added:

```diff
https://res.cloudinary.com/practicaldev/image/fetch/
- s--bcGifSKE--
+ s--YYqb6inY--
/
- c_imagga_scale
+ c_fill
,f_auto,fl_progressive,
- h_90
+ h_50
,q_auto,
- w_90
+ w_50
/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/169338/1b23b783-9452-493b-adbb-6e4aff12ad7c.jpeg
```

I'm guessing `c_imagga_scale` is the problematic part, as it looks like that's Cloudinary's "smart cropping" feature. https://cloudinary.com/documentation/imagga_crop_and_scale_addon

**To Reproduce**

1. Log in to dev.to
2. Scroll down to comments on a post
3. Create a comment
4. Observe difference in zoom level between the profile pic in the top right corner/next to the comment box vs the one in the newly posted comment

Possibly the difference will only be noticeable if your profile picture contains an obvious face.

**Expected behavior**

The profile picture should consistently show as the user uploaded it, rather than "smart-zoomed" into their face.

**Comment by PhilipHow** [comment]
Thanks for this report @lionel-rowe! Great write-up.
