### ISSUE TITLE
Remove the first step of onboarding, reorder onboarding steps

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19989]
## Is this feature related to a problem? Please describe.

- As a new user, I want to complete the mandatory onboarding steps in the shortest possible number of steps, so I can take the desired action on my account as soon as possible.

## Describe the solution you'd like

- As we now implicitly accept the terms of service and code of conduct, we can remove the first step of the onboarding, in which users accept the terms of service and code of conduct manually.
- Additionally, we should move the profile edit stage as the first step, as we should allow the user to confirm their identity and public profile before allowing them to customize their feed.

## Definition of Done

- [ ] Remove the first step of the onboarding process.
- [ ] Remove the check as to whether the terms and conditions have been completed as part of checking whether users should be re-directed to onboarding. 
- [ ] Re-order the steps as follows:
  - Profile customization
  - Follow tags
  - Follow users/organizations
  - Newsletter opt-in 

## Additional Context

- We currently store whether a user checked the terms and conditions and code of conduct and validate against it in various places. We could either stop recording these items as checked and remove the validation, or continue to store `true` for the checked columns as a means of modeling the the implicit acceptance.
- There could be an issue with moving the following tags step to right before the following users step, as we use the user's tags to inform which users we should return.

**Comment by Ridhwana** [comment]
> There could be an issue with moving the following tags step to right before the following users step, as we use the user's tags to inform which users we should return.

I _think_ this should be fine as we send the requests through as individual form submits to the backend rather than as one request at the end.

**Comment by mirie** [comment]
@rt4914 I see you moved this back to Ready for Dev -- are you still planning on working on this as well, or should we un-assign?

**Comment by mirie** [comment]
Blocked by [Redesign sign-up and login pages (incorporating implicit ToU/CoC acceptance)#19988](https://github.com/forem/forem/issues/19988). Can move forward once that's merged in
