### ISSUE TITLE
Redesign sign-up and login pages (incorporating implicit ToU/CoC acceptance)

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19988]
## Is this feature related to a problem? Please describe.

- As a new user, I want to complete the mandatory onboarding steps in the shortest possible number of steps so I can take the desired action on my account as soon as possible.

## Describe the solution you'd like

- Re-design the sign-up and log-in pages and include an implicit notice to accept the terms of use, privacy policy and code of conduct.

## Designs

- [Desktop Designs](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?type=design&node-id=2853-28732&mode=design&t=AyMABDtKIPhqBkjK-4)
- [Mobile Designs](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?type=design&node-id=2953-218&mode=dev)

## Definition of Done

- [ ] Implement the redesign of the sign-up and log-pages to include the implicit notice to accept the terms of use, privacy policy and code of conduct.
- [ ] No logic changes dictating the order or skipping steps should be completed as part of this work.

**Comment by rt4914** [comment]
@PhilipHow @anujbhavsar96 
I will be finishing this issue in two parts:
(1.) where I redesign the entire UI of both the pages, keeping footer and topbar intact. This part already have a open PR and unblocks work for #19989 
(2.) hide topbar and footer on signin-signup pages.

Hope this is fine.

**Comment by anujbhavsar96** [comment]
IMO, this should be fine @rt4914
