### ISSUE TITLE
Large `manifest.json` Icons are different than main one.

### ISSUE THREAD

**Issue by bnb** [forem/forem#1999]
**Describe the bug**

With Chrome's newly shipped Desktop PWA feature, the 100% square `512x512` image in `manifest.json` is being loaded instead of the rounded `192x192`version. On desktop/macOS, the square version doesn't look as polished as the rounded version would.

![image](https://user-images.githubusercontent.com/502396/53994598-c1476d80-4100-11e9-8ce7-31a3fa8c7541.png) 

**To Reproduce**

1. Add dev.to to your desktop from the Chrome menu on Desktop:
  - Click vertical dots menu > Install DEV Community
2. Open up the app
3. See the icon 😄 

**Expected behavior**
Rounded-corners version of the image should be used for 512x512, not the square version.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 72.0.3626.119

**Comment by maestromac** [comment]
Thanks for this issue @bnb ! Should be a very quick fix for us.

**Comment by Jo-IE** [comment]
Hi! I would like to work on this if someone isn't already doing it :) Thanks!

**Comment by Glennmen** [comment]
Wasn't this fixed with PR #4220 ?

**Comment by bnb** [comment]
Doesn't seem like it @Glennmen: 
![image](https://user-images.githubusercontent.com/502396/70253927-06083f80-1739-11ea-9ae8-8771e00c7165.png)

@Jo-IE it would be super awesome if you did!

**Comment by Jo-IE** [comment]
Thank you @bnb!

**Comment by cmgorton** [comment]
Since our PWA was removed last week when we removed our service worker I am going to close this issue. You can see where it was removed in PR #12974. Thanks for all the work here everyone!
