### ISSUE TITLE
Use of Snackbars within the plain vanilla JS pack files

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#20044]
**Describe the bug**

Currently, we can use Snackbars in our Preact components and in our Stimulus code. However, the snackbars are not working within the plain vanilla JS pack files. 

**To Reproduce**

For example: We have added a Snackbar to 
https://github.com/forem/forem/blob/8d0635ff39c97f771b7a14eecaddee4f3ccd2f84/app/javascript/packs/commentDropdowns.js#L13-L15

However, when we complete the following steps the snackbar does not show up:

- Boot app locally and open Article with comments without signing in
- Click on a comment's date
- The link should redirect to the same article with an anchor tag that scrolls you down to the comment
- Open the comment's dropdown (3 dots icon) and "copy link"
- According to commentDropdowns.js the snackbar should show a message 'Copied to clipboard' when clicking on copy link.

**Expected behavior**

According to commentDropdowns.js the snackbar should show a message 'Copied to clipboard' when clicking on copy link.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by aintluks** [comment]
I would like to work on this one.

It seems like it can't access addSnackbarItem and so it needs to use `top`.
