### ISSUE TITLE
Blog Text Overflow 

### ISSUE THREAD

**Issue by ShubhamTiwari909** [forem/forem#20053]
**Describe the bug**
Some text including coding part is overflowing on x axis
When the number of words on a single line increased the text started overflowing and created a horizontal scroll for the blog

**To Reproduce**

Go to Dashboard -> First blog -> scroll down a bit -> text overflowing on x axis creating a scroll

**Expected behavior**
The text should wrap as in other blogs

The text should not overflow no matter how many words in a single line, The scroll should be inside the coding square but it is showing on the blog itself

**Screenshots**
![Screenshot_2023-09-06-21-14-12-878_com android chrome](https://github.com/forem/forem/assets/72227622/7a348792-5bb1-4fa8-99c7-87d61b484202)
![Screenshot_2023-09-06-21-14-16-317_com android chrome](https://github.com/forem/forem/assets/72227622/fd3dd4bd-ce54-46a4-a917-bc7c7d4e4597)
![Screenshot_2023-09-06-13-31-45-615_com android chrome](https://github.com/forem/forem/assets/72227622/878b9ed8-447b-4fa6-878c-0a4d0a5a83c6)

**Desktop (please complete the following information):**

- MacBook 13 pro
- Chrome

**Smartphone (please complete the following information):**

- Redmi note 8 pro:
- Android 11
- Chrome

**Comment by shree675** [comment]
@ShubhamTiwari909 I saw your post and was just about to create a new issue regarding this.

Here is the link of the post where this is happening: https://dev.to/shubhamtiwari909/react-components-gallary-3p7b

**Comment by PhilipHow** [comment]
Thanks @ShubhamTiwari909, @shree675 we will look into this.

**Comment by ktmouk** [comment]
I could reproduce this issue with simple markdown below.
I guess these blog's markdown have `<div>` text outside of the code block. 🤔 
~~~
<div>
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
~~~
<img width="429" alt="スクリーンショット 2023-09-16 21 39 47" src="https://github.com/forem/forem/assets/17381979/9874988e-a57e-4e76-bb19-07f12baa5c73">
