### ISSUE TITLE
Include country code in pageview and billboard (no need to include in rollup)

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#20062]
## Is this feature related to a problem? Please describe.

We can track country-by-country traffic high level via analytics, but don't have a great way to do so with the accuracy and apples-to-apples outcomes we need.

## Describe the solution you’d like

In order to get a cleaner first-party sense of country-by-country traffic and outcomes, we'd like to add the country code to captured  PageViews and BillboardEvents.

This is strictly adding countries (not regional info), and does not need to take into account rolling up in any way at this moment (though we could move to take country into account for rolling up in the future)

## Definition of Done

- [ ] Add country code to these two tables
- [ ] Capture country code — as sent through our established headers — upon creation

**Comment by jaw6** [comment]
@benhalpern I just want to confirm: where you say "does not need to take into account rolling up in any way at this moment", my understanding is that the new `country_code` attribute will _only_ be visible on pageview and billboard events tables _until_ rollup happens, then it will be removed and _not preserved_. (In other words, we would only have `country_code` for the last ~30 days on `billboard_events`.)
