### ISSUE TITLE
I can't comment

### ISSUE THREAD

**Issue by ShimiShimson** [forem/forem#20075]
**Describe the bug**

When I try to submit my comment I get this
![image](https://github.com/forem/forem/assets/45741410/8efef443-c0f9-428c-b401-853c79ecab9a)

**To Reproduce**

**Expected behavior**
Ability to comment

**Desktop (please complete the following information):**

- OS, version: win 10 pro
- Browser, version: Version 116.0.5845.180

**Comment by ShimiShimson** [comment]
![image](https://github.com/forem/forem/assets/45741410/ee5b1216-b34c-4f14-b5ae-61c6e4d4b7c6)

**Comment by maestromac** [comment]
Yes it looks like you got hit with our rate limit. Please give it a bit of time between writing comments.
