### ISSUE TITLE
Listings have been remove but are still linkedin Digest emails

### ISSUE THREAD

**Issue by ClJarvis** [forem/forem#20108]
**Describe the bug**

The listings feature was removed from DEV. But they are still mentioned and linked in the DEV Community Digest email. The links lead to  a 404 page or to  Posting a Job on DEV Listings page.  (https://dev.to/page/post-a-job)

This may be part of an email template and needs to be removed.

**To Reproduce**

Read the latest DEV community Digest. 

**Expected behavior**

Since Listings have been removed these link need to be removed. 

Remove the Posting a Job on DEV Listings https://dev.to/page/post-a-job page or have it forward to the "We are turning off listing post.

**Screenshots**

![DevDigest](https://github.com/forem/forem/assets/10702993/f4a7b739-c7ab-4eef-aded-3e292fa0efe3)

**Desktop (please complete the following information):**

- OS, version: MAC
- Browser, version: Email

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PhilipHow** [comment]
Thanks for this report @ClJarvis.

For anyone looking to take this on - we should just [remove this section](https://github.com/forem/forem/blob/7d1d0ff80be07ee38cb3049b5d3ff3a4ecad9061/app/views/mailers/digest_mailer/digest_email.html.erb#L14) from the email, as listings categories are configurable - so this seems something DEV specific that has kept itself in the code.
