### ISSUE TITLE
Timeboxed investigation on moderation test flakiness

### ISSUE THREAD

**Issue by mirie** [forem/forem#20115]
Recently there's been an uptick in moderation tooling test flakiness. We want to have a timeboxed (1 day) investigation to sort out the issue with the implementations of the tests. 

Related discussion: https://forem-team.slack.com/archives/C7GE84DEJ/p1694683597951589?thread_ts=1694623291.248679&cid=C7GE84DEJ

**Comment by filleduchaos** [comment]
Hmmm - I do recall reviewing [this PR](https://github.com/forem/forem/pull/19991) that changed how the article moderation button is rendered, but nothing in it stands out as potentially causing Cypress to flop on finding the button

**Comment by Ridhwana** [comment]
> Hmmm - I do recall reviewing [this PR](https://github.com/forem/forem/pull/19991) that changed how the article moderation button is rendered, but nothing in it stands out as potentially causing Cypress to flop on finding the button

Yeah it's mostly just somewhere to start looking from. Open to other ideas too. However Mac's trying something as well which seems hopeful https://forem-team.slack.com/archives/C7GE84DEJ/p1694722338045859?thread_ts=1694623291.248679&cid=C7GE84DEJ 🤞🏼

**Comment by mirie** [comment]
@Ridhwana do you want to look at this one or have someone else (if they have bandwidth take a look)? OR perhaps we should have the team pick up one of the issues from https://github.com/forem/forem/milestone/21?
