### ISSUE TITLE
Svelte Syntax Highlighting Not Working

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#20129]
**Describe the bug**

When writing a code block and trying to use syntax highlighting for Svelte, it does not work.

**To Reproduce**

1. Go to write a new post on DEV
2. Create a code block and designate it as written in Svelte (e.g. see screenshots below)
3. Preview the post
4. Notice that code block is not formatted 

**Expected behavior**

Codeblocks should recognize Svelte syntax highlighting.

**Screenshots**

<img width="929" alt="svelte-syntax-highlighting" src="https://github.com/forem/forem/assets/16007075/8b964cdc-9b88-4816-a4c6-df66142cb4c1">

<img width="922" alt="svelte-syntax-highlighting-2" src="https://github.com/forem/forem/assets/16007075/6cc67ed4-3843-4149-8384-88a86e99f6f4">

**Additional context**

This issue was raised by @Siddhant-K-code in the moderator channel.

**Comment by ktmouk** [comment]
`rouge-ruby` gem has recently supported Svelte syntax, but it seems it has not been released as a gem yet.
https://github.com/rouge-ruby/rouge/pull/1979
