### ISSUE TITLE
Can't open mod panel

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#20122]
**Describe the bug**
When we click to the button for opening the mod panel at the right, nothing happens.

**To Reproduce**

1. Go to a post 
2. Click on the mod button
3. See that, nothing happens.

**Expected behavior**
The button opening the mod panel at the right like this
![Mod panel with a DEV post](https://github.com/forem/forem/assets/14293805/82f87531-baaa-40ec-98da-7aa0c55b43fd)

**Screenshots**

https://github.com/forem/forem/assets/14293805/c70e6574-f183-4978-ac89-a5752747396e

The page in this video is [quickbill/get-organized-with-quickbill-retail-software-28l6](https://dev.to/quickbill/get-organized-with-quickbill-retail-software-28l6).

**Desktop (please complete the following information):**

- OS, version:
- Browser, version: Chrome v116 **also** Firefox v117.

**Additional context**
🎹💚

**Comment by thomasbnt** [comment]
I opened this issue, but seems working now.

When I intereact with a hearth to the post to demonstrate with a video, components/buttons works but not for the mod button, the website give me the error : 
> Error updating reaction
> Your reaction could not be updated due to a server error

And my tab reloading, and the panel can opened.

**Comment by thomasbnt** [comment]
I updated the message, the bug is always here 😞

**Comment by en4839** [comment]
We're facing the same issue, also in th mod center the sidebar that opens the mod panel shows a 404, this is happening on a self host Forem instance.

**Comment by pavelee** [comment]
I can't reproduce the bug, @thomasbnt can you?

**Comment by thomasbnt** [comment]
> I can't reproduce the bug, @thomasbnt can you?

Hello, now I can't reproduce this bug.

**Comment by thomasbnt** [comment]
Today, I can no longer have this kind of bug.
