### ISSUE TITLE
Fix visual glitch with autocomplete component

### ISSUE THREAD

**Issue by jaw6** [forem/forem#20139]
Reported by @rt4914 on [this PR](https://github.com/forem/forem/pull/20123). There's a visual glitch when interacting with autocomplete components, possibly when they layer "on top of" other UI elements. Initially seen in `UsernameInput` but likely effects tags and at-mentions as well, as it's likely an issue in the underlying component. It's hard to put into words, possibly best captured in this video:
https://www.loom.com/share/b410b5fc7829431baf1c20036eb1c1c1?sid=f6503ec0-b374-4fba-b5d3-bea3b5f35ed9

**Comment by KSSaiTeja** [comment]
i understood the issue.. so i have an idea to take down the button to bottom side a little bit. so the issue will fix..
i am intersted to work on this. Please assign this to me.

**Comment by morfenza** [comment]
Hello! I've opened a PR to fix this issue :D

https://github.com/forem/forem/pull/20611
