### ISSUE TITLE
Trusted Members Currently Cannot Use Trusted Member Response Templates

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#20138]
**Describe the bug**

Trusted Members are able to access and see Trusted Member Response Templates, but when they try to "send as mod" they receive an error. "Insert" works just fine.

Just to explain the difference:
- "send as mod" allows folks to post the message under Sloan
- "insert" allows folks to send the message as themselves and gives them the opportunity to edit the language of the message

Also, Tag Mods and Admin are able to use Trusted Member Response Templates with "send as mod" without issue.

See both videos below under the Videos section for details.

**To Reproduce**

1. Make sure you're logged into an account with the Trusted Member role (but not an Admin or Tag Mod role)
2. Find a post to leave response template on
3. Scroll down to the comments section & click into the input box as if you were writing a comment.
4. Click on the `...` in the comment's toolbar
5. Click on the icon that looks like a book
6. Select a template and click "Send as Mod"
7. See error. 

**Expected behavior**

Trusted Members should be able to use Trusted Member Response Templates via "send as mod"

**Videos**

Trusted Members Can't Currently Use Trusted Member Response Templates

https://www.loom.com/share/a69076ffb0674718a887fd9b5fa0411d

Tag Mods CAN Use Trusted Member Response Templates

https://www.loom.com/share/4f904b5fb5b544408b5a444797d27bdb

**Additional context**

Shoutout to @devarshishimpi who let me know about this one over our Moderator Discord! Appreciate ya! 🙌

**Comment by devarshishimpi** [comment]
Awesome!
