### ISSUE TITLE
Overlapping Like buttons inside of show more dropdown option

### ISSUE THREAD

**Issue by sabarivasagan** [forem/forem#20143]
**Describe the bug**
While opening show more dropdown backside comment's like was overlapping

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/forem/forem/assets/13609681/2580f399-1613-49ab-8092-ac956710cf8a)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by erik-whiting** [comment]
happens in dark mode too
<img width="458" alt="image" src="https://github.com/forem/forem/assets/47164199/0fa19f4c-d498-42f5-bde2-22d05c7d569f">

**Comment by dancristianb** [comment]
Hmmm possibly related to https://github.com/forem/forem/issues/19722 / https://github.com/forem/forem/pull/20035 ? 🤔

**Comment by thomasbnt** [comment]
> Hmmm possibly related to https://github.com/forem/forem/issues/19722 / https://github.com/forem/forem/pull/20035 ? 🤔  

Hello! Yeeep that is that!

I created a PR to resolve the problem https://github.com/forem/forem/pull/20165

**Comment by ktmouk** [comment]
oops, I'm sorry, I didn't check this. thank you for fixing this!

**Comment by maestromac** [comment]
long resolved
