### ISSUE TITLE
Make tag score minimum configurable by admins

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#20154]
## Is this feature related to a problem? Please describe.

We have a hardcoded score minimum for awarding tag badges meant to ensure that posts have to reach a particular threshold, however we may want to change that configuration. It is currently hardcoded as 100.

## Describe the solution you’d like

Change this hardcoded number into a `Settings::UserExperience` setting.

## Definition of Done

- [ ] Setting created
- [ ] Applied to award logic

## Additional Context

I think it also likely makes sense to have this further configurable on a per tag basis — but that can be a future consideration.

**Comment by kaysiz** [comment]
@benhalpern I would like to tackle this one if ready for dev

**Comment by joaoGabriel55** [comment]
I proposed a solution to the PR above ^
