### ISSUE TITLE
Issues with Ordering Coauthors

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#20152]
**Describe the bug**

Folks are having issues ordering coauthors for posts. 

It's likely that coauthors must be ordered alphabetically by default and the order in which coauthors are entered doesn't matter. If this is the case, it may not be a bug but just an update we should consider.

**To Reproduce**

0. Write and post a test post as yourself + share it under an org
1. Navigate to your user dashboard - https://dev.to/dashboard
2. Use the drop-down menu to the right of the word "Posts" to select your org
3. Navigate to the article you want to experiment with adding co-authors to and click the `...` menu
4. Use the drop-down menu to re-credit the article's author to X and save
5. Refresh the page
6. Go back to the article's menu and add coauthors. (make sure these are not ordered in alphabetical order; also note: you must type in the coauthors' usernames)

**Expected behavior**

Org managers should be able to credit coauthors in whatever order they desire.

**Videos**

Recreation of Coauthor Ordering Issue (Coauthors are Alphabetically Ordered)

https://www.loom.com/share/ba9b60cd56274a02bb2d7080466f9e34?sid=f86aa59c-1ec4-4ca2-ab81-8a229970d957

Failed Recreation of Coauthor Ordering Issue (Can't Have Multiple Authors in a Series)

https://www.loom.com/share/6efbdc2329dd425db6746e0e44e12183?sid=53f2d483-4f96-4925-ac0f-a86752ce24fc

**Additional context**

At first, when I tried to recreate this issue, I failed because multiple authors cannot author a series together. I have a related request here to allow multiple authors to write in the same series - https://github.com/forem/forem/discussions/15320

A helpful org manager pointed this one out to us. They manage posting blog articles on behalf of their team and are trying to fine-tune things so as to give their teammates appropriate credit.

**Comment by mirie** [comment]
Noting this point that this issue is more of a feature request vs a bug: https://forem-team.slack.com/archives/CAA200SH5/p1695311686359639?thread_ts=1695309661.809319&cid=CAA200SH5

**Comment by rt4914** [comment]
I have picked up this issue and created a PR for this but still I think we should confirm with the product team first.
@PhilipHow @anujbhavsar96 @mirie 
Do we want to solve this issue, i.e. do we want users to control the order in which they add/see co-authors?

**Comment by mirie** [comment]
Thank you so much for taking the initiative to take a look at this one! I tagged with `needs product` and moved this to Next. @anujbhavsar96 let know if you feel OK making this call or if we should bring it to Ben/Erin before going ahead with any change

**Comment by anujbhavsar96** [comment]
@mirie `Org managers should be able to credit coauthors in whatever order they desire` This is definitely something we can do right now since that's the natural expectation of the users for order.

> Allow multiple authors to write in the same series

This can wait a little though, it looks a bit complex.
