### ISSUE TITLE
The api docs display an incorrect url structure

### ISSUE THREAD

**Issue by idiglove** [forem/forem#20186]
**Describe the bug**

The url suggested was `https://dev.to/api/api/articles` instead of `https://dev.to/api/articles`

**To Reproduce**

1. Go to https://developers.forem.com/api/v1
2. Click the dropdown from the right side panel and see the url

**Expected behavior**

The URL should be correct

**Screenshots**

<img width="1667" alt="image" src="https://github.com/forem/forem/assets/29911508/65966501-5d07-4483-87db-2730720b9d86">

**Comment by sugan0tech** [comment]
@idiglove  issue has already been reported in forem docs: https://github.com/forem/forem-docs/issues/111

**Comment by Lymah123** [comment]
Hi, has anyone working on it? If now, please assign me.

**Comment by theperiperi** [comment]
I'd liked to be assigned if this is still open

**Comment by maestromac** [comment]
This issue was already resolved with https://github.com/forem/forem-docs/pull/124
