### ISSUE TITLE
modal 'flag user' is not openning

### ISSUE THREAD

**Issue by Lucasm4sco** [forem/forem#20188]
**Describe the bug**

The 'Flag user' button on the moderators page is not functional, I checked the problem in the console and it turns out that the javascript is not able to select the modal in the html due to iframe.

**To Reproduce**

1. Go to mod page;
2. Click on any article;
3. Click on "Moderating actions";
4. Click on "Flag {user}";
5. Error: Nothing happens.

**Expected behavior**

Show a modal to confirm.

**Screenshots**

![issue](https://github.com/forem/forem/assets/99912646/ac93d155-b758-4f67-aeb3-ef9c7392e233)

**Desktop (please complete the following information):**

- Linux mint 20;
- Browser Brave.

**Additional context**

I spent the afternoon understanding the project and I'm going to open a pull request that solves this issue.

**Comment by Lucasm4sco** [comment]
I want to get this issue

**Comment by maestromac** [comment]
Resolved by https://github.com/forem/forem/pull/20189
