### ISSUE TITLE
Icons on the Mod Menu displaying incorrect colors

### ISSUE THREAD

**Issue by mateusabelli** [forem/forem#20190]
**Describe the bug**

When opening the Mod Menu, I noticed that the icons under the "OTHER THINGS YOU CAN DO" are displaying incorrect colors, this behavior happens with the Dark and Light themes.

**To Reproduce**

1. As a Tag Moderator, open the [Mod Menu](https://dev.to/mod)
2. Click on a post
3. Hover over to the "OTHER THINGS YOU CAN DO" section on the side panel
4. See the problem as you hover through the buttons

**Expected behavior**

The colors that should be correct, in my opinion are the following:
- Light Theme: gray button with black icon | hover: blue button with white icon
- Dark Theme: gray button with white icon | hover: blue button with white icon

**Screenshots**

<table>
<td>
<img src="https://github.com/forem/forem/assets/43862225/2ec74149-b7c4-4a0d-a52b-c4a754d161ff" />
</td>
<td>
<img src="https://github.com/forem/forem/assets/43862225/508c1c74-a2d0-4a15-8dc7-2ff349ccd0cf" />
</td>
</table>

**Desktop:**

- OS: Windows 10, version: 10.0.0.19045
- Browser: Brave, version: v1.58.135

**Smartphone:**

- Device: SM-J530G
- OS: Android, version: 9.0 Pie
- Browser: Brave, version: 1.58.131

**Additional context**

I have tested with the Brave Browser running on my Desktop and Mobile device.

**Comment by mateusabelli** [comment]
If a team member validates this issue, I'd like to work on it.

**Comment by benhalpern** [comment]
Go for it @mateusabelli
