### ISSUE TITLE
[BUG] Dockerfile is not accessible 

### ISSUE THREAD

**Issue by Viveksati5143** [forem/forem#20196]
**Describe the bug**

Dockerfile is not accessible as it has been overridden by already existing Dockerfile by developer while pushing the code to the branch.

**To Reproduce**

1. Go to 'https://github.com/forem/forem' 
2. Click on 'Dockerfile'
3. Scroll down to 'https://github.com/forem/forem/blob/main/Dockerfile'

**Expected behavior**

Dockerfile should be clearly available & the contents for it!!!

**Screenshots**

![image](https://github.com/forem/forem/assets/100852245/8862327e-d5c5-4573-937b-e7626e834f5c)
<img width="960" alt="image" src="https://github.com/forem/forem/assets/100852245/84a45839-4177-44a8-98c3-63e6bf2cfc9e">

**Desktop (please complete the following information):**

- OS, version: WIndows 11
- Browser, version: Microsoft Edge

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

I would like to contribute to this issue..

**Comment by Viveksati5143** [comment]
I want to contribute to this issue, so please assign me

**Comment by mencarellic** [comment]
The Dockerfile is a symbolic link to the Containerfile ([PR#7747](https://github.com/forem/forem/pull/7747)). The world of containers is more than just Docker now, so generalizing to Containerfile is done in several places, this being one of them.

Docker should respect Containerfiles just as it does Dockerfiles.

[See more info about Containerfiles here](https://www.mankier.com/5/Containerfile)

**Comment by Viveksati5143** [comment]
> The Dockerfile is a symbolic link to the Containerfile ([PR#7747](https://github.com/forem/forem/pull/7747)). The world of containers is more than just Docker now, so generalizing to Containerfile is done in several places, this being one of them.
> 
> Docker should respect Containerfiles just as it does Dockerfiles.
> 
> [See more info about Containerfiles here](https://www.mankier.com/5/Containerfile)

I appreciate all the information that you provided but it still keeps my issue unclear.
My point is either completely remove the Dockerfile if it is replaced by Containerfiles or atleast make the [Dockerfile](https://github.com/forem/forem/blob/main/Dockerfile) accessible for developers still using them.
What is you take on this @mencarellic?

**Comment by mencarellic** [comment]
> > The Dockerfile is a symbolic link to the Containerfile ([PR#7747](https://github.com/forem/forem/pull/7747)). The world of containers is more than just Docker now, so generalizing to Containerfile is done in several places, this being one of them.
> > Docker should respect Containerfiles just as it does Dockerfiles.
> > [See more info about Containerfiles here](https://www.mankier.com/5/Containerfile)
> 
> I appreciate all the information that you provided but it still keeps my issue unclear. My point is either completely remove the Dockerfile if it is replaced by Containerfiles or atleast make the [Dockerfile](https://github.com/forem/forem/blob/main/Dockerfile) accessible for developers still using them. What is your take on this @mencarellic?

Generally, it seems like you should be using `bin/container-setup` when installing using containers ([source](https://developers.forem.com/getting-started/installation/containers)). However, specifying [the file parameter](https://docs.docker.com/engine/reference/commandline/build/#file) in your `docker build` command, such as `docker build --file Containerfile .` should work.

**Comment by Lucasm4sco** [comment]
btw when I tried to use Docker to run the application, it returned an error that port 3000 was already in use.  I think it might be a good idea to check whether it was a valid issue or whether it just occurred due to some of my settings.

**Comment by maestromac** [comment]
Yes, exactly what @mencarellic, `Dockerfile` is a symlink that allows for docker compatibility without extra tinkering.

As for the setup. `bin/container-setup` is deprecated.  Please refer to [this post](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49) for most up-to-date setup guideline.

Running docker-compose directly is not recommended because our custom services are meant to support wide array of setup and they will clash.

@Lucasm4sco there could be a couple of reason to hit the 'port 3000 was already used'. It's a common web port that is still being used or stuck running from different build. You should find [the port and kill it](https://stackoverflow.com/a/3855359).

**Comment by Viveksati5143** [comment]
> Yes, exactly what @mencarellic, `Dockerfile` is a symlink that allows for docker compatibility without extra tinkering.
> 
> As for the setup. `bin/container-setup` is deprecated. Please refer to [this post](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49) for most up-to-date setup guideline.
> 
> Running docker-compose directly is not recommended because our custom services are meant to support wide array of setup and they will clash.
> 
> @Lucasm4sco there could be a couple of reason to hit the 'port 3000 was already used'. It's a common web port that is still being used or stuck running from different build. You should [find the port and kill it](https://stackoverflow.com/a/3855359).

Thanks for clarifying!!

**Comment by Lucasm4sco** [comment]
> Yes, exactly what @mencarellic, `Dockerfile` is a symlink that allows for docker compatibility without extra tinkering.
> 
> As for the setup. `bin/container-setup` is deprecated. Please refer to [this post](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49) for most up-to-date setup guideline.
> 
> Running docker-compose directly is not recommended because our custom services are meant to support wide array of setup and they will clash.
> 
> @Lucasm4sco there could be a couple of reason to hit the 'port 3000 was already used'. It's a common web port that is still being used or stuck running from different build. You should [find the port and kill it](https://stackoverflow.com/a/3855359).

I'll see about it, thanks
