### ISSUE TITLE
Profile bio does not recognize line breaks

### ISSUE THREAD

**Issue by yheuhtozr** [forem/forem#20231]
**Describe the bug**

The "bio" profile field has a textarea input that allows you to insert newlines.

![image](https://github.com/forem/forem/assets/84892012/f7547999-5835-4823-9bdb-68a2948355fd)

But they are not rendered in the profile page.

![image](https://github.com/forem/forem/assets/84892012/1fcd200b-c10d-4060-90ce-2c253ba3bf24)

Is this intended? What makes me suspect of bug is that sidebar profile fields (currently learning, currently hacking on...) does render newlines formatted.

**To Reproduce**

As above.

**Expected behavior**

As above.

**Screenshots**

As above.

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Firefox 118, Chrome 117

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by yasirazgar** [comment]
I would like to work on this issue
