### ISSUE TITLE
Support organization `:id` routes for organization endpoints

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20237]
## Is this feature related to a problem? Please describe.

- As an API consumer, I want to reference organizations by their ID in case they decide to change their name/slug.

## Describe the solution you’d like

- Recently, the main `/api/organizations/{username}` route was updated to support access via the organization's ID (e.g. `/api/organizations/:id`), in [this PR](https://github.com/forem/forem/pull/19681).
- We should update the other two organization routes: `/api/organizations/{username}/users` and `/api/organizations/{username}/articles` to additionally support access via the organization's ID.

## Definition of Done

- [ ] Update the  `/api/organizations/{username}/users` route to also support access via the organization's ID (i.e.  `/api/organizations/:id/users`)
- [ ] Update the  `/api/organizations/{username}/articles` route also to support access via the organization's ID (i.e. `/api/organizations/:id/articles`)

**Comment by danielmbrasil** [comment]
I'd like to work on this issue!

**Comment by PhilipHow** [comment]
@danielmbrasil I meant to make this internal team only - meaning it's to be tackled by our own internal team.

If you were willing to take it on - and take some detailed feedback from our team - would you be able to get it done over the next few days?

If not - then please do take a look at our [other issues](https://dev.to/contribute-issues).

**Comment by danielmbrasil** [comment]
Hey @PhilipHow, thank you for the clarification.

>  would you be able to get it done over the next few days?

Actually, I've made the changes already and I believe it's ready for review. Should I open a PR then?

**Comment by PhilipHow** [comment]
@danielmbrasil Go for it!
