### ISSUE TITLE
The container environment with docker-compose seems to not be updated

### ISSUE THREAD

**Issue by gotasj** [forem/forem#20243]
Hello!

I have been struggeling with setting up an instance locally with the containers. I am using docker and docker-compose. I suspect it is not up to date.

**Describe the bug**

**To Reproduce**

1. Run bin/container-setup
2. It will fail since devcontainer and web are using the same port (3000). 
3. Changing the port to another available port does makes the containers run but results in an error where it complains that _rails_ cannot be found.

I found out that there are two yml files. And the container-setup is using the file called docker-compose.yml.

Decided to run with container-compose.yml instead.

1.  docker-compose -f container-compose.yml up
2.  It will complain on the following:

- dockerize cannot be found
- ./scripts/bundle.sh cannot be found

I can see that the working from the built image is "app" when /opt/apps/forum is expected. I tried a workaround with _working_dir: /opt/apps/forum_ in container-compose.yml, but it results in other errors.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: WSL2
- Browser, version: Edge

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**
Let me know if there is anything else you need from me. I would be happy in any help on this.

**Comment by maestromac** [comment]
@gotasj `bin/container-setup` is depreated, can you please give one of [these options](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49) a try?
