### ISSUE TITLE
Prevent organizations being created with just integers in their slug

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20264]
## Is this feature related to a problem? Please describe.

As we have introduced new routes to allow organizations to be queried in the API via either their slug or their ID, we need to prevent organizations from being created with just integers to avoid any unintentional collisions.

## Describe the solution you’d like

- Prevent organizations with usernames that are just integers

## Definition of Done

- [ ] When users created a new organization, they should not be able to enter in an organization username that is just integers (0 - 9). If this occurs, an error message should show, asking the user to add other characters to their username.

## Additional Context

- This is a scoped issue for organizations, based on the larger issue - https://github.com/forem/forem/issues/19758

**Comment by danielmbrasil** [comment]
Hey, is it open for external contributors? I'd like to tackle it.

**Comment by PhilipHow** [comment]
Go for it! @danielmbrasil
