### ISSUE TITLE
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/bash": stat /usr/bin/bash: no such file or directory: unknown

### ISSUE THREAD

**Issue by YuriyGavrilov** [forem/forem#20280]
**Describe the bug**

Receive such error during fresh install in docker by following this doc: https://developers.forem.com/getting-started/installation/containers

after `docker-compose up`

receive this:

```
forem-chrome-1        | 2023-10-25T19:58:36.973Z browserless:server 
forem-chrome-1        | 
forem-chrome-1        | Running on port 3333
forem-chrome-1        | 	Localhost	 ws:localhost:3333
forem-chrome-1        | 	Local network	 ws:172.27.0.4:3333
forem-chrome-1        | 2023-10-25T19:58:36.974Z browserless:server 
forem-chrome-1        | Get started at	 https://www.browserless.io/docs/start
forem-chrome-1        | Get a license at	 https://www.browserless.io/sign-up?type=commercial
forem-chrome-1        | Get support at	 https://www.browserless.io/contact
forem-chrome-1        | 
forem-chrome-1        | Happy coding!
forem-chrome-1        | 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/bash": stat /usr/bin/bash: no such file or directory: unknown
```

**To Reproduce**

**Expected behavior**

Proper server run 

**Screenshots**

Not all components run:

<img width="732" alt="Снимок экрана 2023-10-25 в 23 05 03" src="https://github.com/forem/forem/assets/44679014/3469dc29-5925-48ea-b62c-eafd9028568b">

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by maestromac** [comment]
Hello @YuriyGavrilov , the way we setup our `docker-compose.yml` doesn't support the `docker-compose up`. Instead, I'd suggestion you check out [some new local development setup options](https://dev.to/devteam/announcing-new-local-dev-setup-options-for-contributing-to-forem-2p49). Please give it a try and let me know.

**Comment by YuriyGavrilov** [comment]
@maestromac thx 🙏 it working. Just a bit confused about default login pass 😅 but I will find it. Thx again.

**Comment by maestromac** [comment]
@YuriyGavrilov it's `admin@forem.local` and `password`
