### ISSUE TITLE
Add followers count to `/api/users/me` endpoint

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20326]
## Is this feature related to a problem? Please describe.

- As an API consumer, I want to keep track of how many followers I have. So I can measure my growth/presence on the platform using third-party tools.

## Describe the solution you’d like

Add a `follower_count` value to the the `/api/users/me` endpoint, that returns how many followers the authenticated user has.

## Definition of Done

- [ ] Add a `follower_count` value to the the `/api/users/me` endpoint, that returns how many followers the authenticated user has.

## Additional Context

- Generally, broadcasting/publishing follower counts is discouraged, and so rather than adding this to any of the user endpoints, this will only be returned for the `/me` endpoint for the authenticated user.

**Comment by nfrankel** [comment]
It would be great if the statistics included not only the number of followers but all data provided on the https://dev.to/dashboard/analytics page.

* readers
* reactions
* comments
* followers

<img width="1240" alt="Screenshot 2023-11-09 at 11 39 37" src="https://github.com/forem/forem/assets/752258/c629abd1-c2ce-4c7f-ba9e-fec29dfc21b9">

**Comment by xao0isb** [comment]
Hello! Is this issue for external contributors? Can I try to do this?

**Comment by barrymichaeldoyle** [comment]
I would absolutely love this functionality...

**Comment by tq-bit** [comment]
Somebody on a recent post of mine pointed out a very fair point about the follower count:

![image](https://github.com/forem/forem/assets/69204418/cfc79ced-2438-4494-bad9-99cb89caffdf)

Perhaps it's a good idea to consider only non-disabled accounts when accumulating followers.

**Comment by nfrankel** [comment]
Hello,

When this will be deployed?

**Comment by nfrankel** [comment]
Thanks. However, I asked because I didn't see it in the [documentation](https://developers.forem.com/api/v1#tag/users/operation/getUserMe). I confirm it's there,
