### ISSUE TITLE
Add HTML body content to pages API

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20342]
## Is this feature related to a problem? Please describe.

As a Forem admin, I want a flexible means of updating page content, including HTML content, so I can automate some additional functionality that lives best as static HTML.

## Describe the solution you’d like

- Add in the option to supply HTML to the `POST` `api/pages` endpoint and the `PUT` `/api/pages/{id}` endpoints. This should be stored against the HTML for the page, as currently is available through the admin UI.
- The UI currently allows both HTML and Markdown content (with markdown being prioritized), I'm not sure whether this needs to be accounted for in the API, or we can keep the existing lack of validation.

## Definition of Done

-  [ ] Add in the option to supply HTML to the `POST` `api/pages` endpoint and the `PUT` `/api/pages/{id}`

**Comment by lightalloy** [comment]
@PhilipHow choosing when to use markdown vs html for the `processed_html` is currently done in the model, so I will keep the same logic for the api. Passed `html` will be used when no markdown will be passed.
