### ISSUE TITLE
Add link to GitHub repo on /report-abuse page

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#20361]
## Is this feature related to a problem? Please describe.

As an admin, I want bug reports funneled to GitHub instead of our abuse reports form.

## Describe the solution you’d like

Update copy on `/report-abuse`.

## Additional Context

Will submit PR to close this issue shortly.

**Comment by michael-tharrington** [comment]
Good thinking! Perhaps also a link to https://dev.to/security which has the vulnerability report form?
