### ISSUE TITLE
Unable to Preview a Reply for a Comment Before Publishing it

### ISSUE THREAD

**Issue by adiati98** [forem/forem#20389]
**Describe the bug**

I can't preview a comment that I wrote before publishing it. There is nothing happen when I click the button.

**To Reproduce**

1. Go to a post.
2. Go to a comment and click reply.
3. Write a reply.
4. Click "preview" button.
5. Nothing happens.

**Expected behavior**

**Screenshots**

![preview not working](https://github.com/forem/forem/assets/45172775/eb28c027-e90b-4de1-aa06-f6c44c3dfbca)

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Chrome, Version 119.0.6045.160 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by joaoGabriel55** [comment]
I can work on that!
