### ISSUE TITLE
Automatically validate flag on a user with `spam` role

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20400]
## Is this feature related to a problem? Please describe.

- As a Support Admin, I want to reduce the number of manual actions I need to take, so I can more efficiently deal with support queries and required actions.

## Describe the solution you’d like

- When a user is assigned a `spam` role, automatically validate any flags on their account and on all of their entities (articles and comments) (that have an unvalidated flag).

**Comment by lightalloy** [comment]
@PhilipHow could you elaborate what are flags and what's to validate? Flag = privileged reaction, validate = make their status "valid"?
I'm not familiar with the support admins flow, so it would be convinient if their actions before and after the described change would be described in more details.
