### ISSUE TITLE
Remove monetization code

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20401]
## Is this feature related to a problem? Please describe.

[Coil](https://www.coil.com/) has shut down, and there is no obvious or immediate replacement for it.

## Describe the solution you’d like

- Remove Coil/web monetization.

## Definition of Done

- [ ] Remove any entries of web monetization from any rendered pages
- [ ] Remove the configuration of web monetization from a user's profile

## Additional Context

- We will need to co-ordinate the timing of merging this work to a public post about its removal

**Comment by michael-tharrington** [comment]
Just a heads up that we received another message about this from a moderator who pointed out that this is out of date.
