### ISSUE TITLE
Match `spam` role with existing `suspended` actions

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20429]
## Describe the solution you’d like

- We should "seed" the capabilities of the spam role by re-using the existing logic for when a user is `suspended`.
- I imagine we could do this by adding `suspended_or_spam` to the existing areas where suspended logic is applied.
- The spam role will have additional limitations/actions on a user's account beyond what what a 'suspended' user has. These will be handled as additional issues.
 
## Additional Context

- Spam role defined in https://github.com/forem/forem/issues/20428
- Getting this done sooner means we can start to apply the spam role sooner, where we may currently apply the suspended role.

**Comment by lightalloy** [comment]
Should we add other restrictions related to the `spam` role as well? It seems like it will be misleading to have 2 identical roles.

**Comment by lightalloy** [comment]
@PhilipHow Do we need to allow moderators assign `spam` role similarly to `suspended`? It seems like it won't be clear what role does what at the moment.
![изображение](https://github.com/forem/forem/assets/30115/2cb8a022-f0cf-4513-9742-e2e00e4d8d77)

**Comment by lightalloy** [comment]
We also have a feature where we assign `suspended` role automatically - e.g. we're checking articles on save (`create_conditional_autovomits`) and suspend user if it seems spammy. Do we need to assign `suspended` in this case?

It seems like having 2 similar roles will be confusing at this point. It would also be nice to see the description of the "final" result: what we want roles to be and how they will be used.

**Comment by PhilipHow** [comment]
> Do we need to allow moderators assign spam role similarly to suspended? It seems like it won't be clear what role does what at the moment.

I believe only admins can suspend at the moment. We don't need this adding to this menu at the moment, but maybe in the future.

> We also have a feature where we assign suspended role automatically - e.g. we're checking articles on save (create_conditional_autovomits) and suspend user if it seems spammy. Do we need to assign suspended in this case?

Do you mean assign `spam`? Not at the moment. Again we can review this functionality once we are happy with the state of the `spam` role.

**Comment by lightalloy** [comment]
Done in #20477
