### ISSUE TITLE
Add new `spam` role

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20428]
## Is this feature related to a problem? Please describe.

- We need a non-destructive user role for spam that we are confident to more liberally apply.

## Describe the solution you’d like

- A new user role, called `spam`, that can be applied to a user by admins (similar to `suspended`).
- This is a negative role, so should remove any positive roles the user has
- Similarly, adding any positive roles should remove the `spam` role
- This role will eventually be `suspended` + other account restrictions, including making articles and comments inaccessible/hidden.
- To split this work up, this issue only pertains to creating the new role and being able to assign it to users.

**Comment by lightalloy** [comment]
Currently, admins can't remove `suspended` role from a user unless they are `super_admin`s. Should this also apply to the `spam` role?

**Comment by PhilipHow** [comment]
Yup - works for me.
