### ISSUE TITLE
Disable moderator round robin notifications

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20453]
## Is this feature related to a problem? Please describe.

We're unhappy with the state of round-robin notifications. There is some confusion as to whether they should primarily help identify spam or help users validate new content from new users (there was a change to the original language in the notification text). There was also some implementation issues meaning they were never properly implemented.

## Describe the solution you’d like

Disable round-robin notifications. We should keep the existing codebase and preferences and look to adjust in the future.

**Comment by PhilipHow** [comment]
@benhalpern

If we just need to 'turn this off' - I think I can take this on.

If we need to remove some of the plumbing, then I think I may be some assistance, but could probably do an initial pass.

Do we need to delay this until after other spam mitigations are in place?

**Comment by benhalpern** [comment]
@PhilipHow There shouldn't be any underlying changes that need to happen to just turn this off, as long as tests pass.

I think we could remove the call from this and keep everything else around to be rewritten for a future adjustment in funcytionality.
