### ISSUE TITLE
Typo in Forem API docs, "instannce" should be "instance"

### ISSUE THREAD

**Issue by barrymichaeldoyle** [forem/forem#20518]
**Describe the bug**

**To Reproduce**

Go here:

https://developers.forem.com/api/v0#tag/users/operation/postAdminUsersCreate

**Expected behavior**

"instannce" should be "instance"  where the text is "Invites a user to the Forem instannce"

**Screenshots**

![Screenshot 2024-01-13 at 14 29 18](https://github.com/forem/forem/assets/4674486/78d19d83-084e-41c0-b15f-910e3097e2d9)

**Comment by manovasanth1227** [comment]
I'd like to work on this.

**Comment by maestromac** [comment]
Resolved with https://github.com/forem/forem-docs/pull/125
