### ISSUE TITLE
Give access to spammer content for admins

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#20553]
## Is this feature related to a problem? Please describe.
Access to spammers' articles, spammers profiles, low-quality comments was limited while implementing #20525 #20541 #20515
It would be useful if the articles and profiles were still visible for admins.

## Describe the solution you’d like
Admins should be able to view spammers profiles and their articles. On spammer profile there should be a notice similar to suspended one

## Definition of Done
- [x] admins should be able to visit spammer profile
- [x] there should be a notice that a user has the spam role
- [x] spammers articles should be accessible for admins
- [ ] access to spam comments by direct link

## Additional Context
`current_user` is not accessible in the actions that "decide" whether to show profile/article (because of caching), so will need to figure this out

**Comment by Hanaffi** [comment]
@lightalloy can you please assign this to me?
