### ISSUE TITLE
Revise low-quality marker and hiding/showing comments based on their score

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#20551]
## Describe the solution you’d like
Currently low quality marker is displayed for comments with score `< -75` for signed-in users. After  #20541 is merged there will be no cases to display low quality marker because comments with low score will be hidden.
However it's useful to show that some comments were downvoted by trusted members. It was offered by @PhilipHow to display a low quality marker for comments with score from `-25` to `-75` (for signed-in users because we hide all negative comments for signed out users)

## Definition of Done
- [ ] low quality marker is displayed for comments with score from `-75` to `-25` for signed in users
- [ ] all other logic (hiding comments with score `< -75` for signed in users, hiding comments with score `< 0` for signed out users) should remain the same

**Comment by PhilipHow** [comment]
@lightalloy 

Could we update the thresholds as follows:

- <= -400 for signed in users
  - has children => show deleted + display children
  - no children => hide 
- >= -75 score
  -  signed out => hide (and hide children)
  -  signed in => show with low quality marker
- >= 0 => show for all

This is essentially keeping the old low quality marker threshold, and updating the threshold of the `spam` to -400.
