### ISSUE TITLE
`vendor/cache` using excessive space in .git repo

### ISSUE THREAD

**Issue by tonymet** [forem/forem#20567]
`forem` clones are currently 1.5G due to old vendor/cache gem's committed to the git repo.  Steps below show how to use `git-filter-repo` to reduce the repo size by 90% to 154M from 1500M

Reducing the Repo size will result in 90+% faster checkouts , deploys and other git operations. 

### A sample of the large objects that can be removed
```
f233d2f5f8648484969b7e30eaedb096d6dba9e8 17891840 vendor/cache/libv8-8.4.255.0-x86_64-darwin-19.gem
6b5b9db3d538b0756520ea8c757ff9293e5917b7 17891840 vendor/cache/libv8-8.4.255.0-x86_64-darwin-20.gem
1e2fb85c0f021cac235624f028bfcc4273f4dedd 17891840 vendor/cache/libv8-8.4.255.0-x86_64-darwin-18.gem
afae232f1470a35d9ce1264f5e7f01a0d579ce47 17031168 vendor/cache/libv8-8.4.255.0-x86_64-linux.gem
481da352f9e72c25c383e78a2ee94a0ea375903f 9598976 vendor/cache/nokogiri-1.13.1.gem
909ef2b1d253e6ba92f33a57aab01f3f5d3910bd 9597952 vendor/cache/nokogiri-1.13.0.gem
71a26fdd769cdb5847730c4ab5d58180a2c09cfc 9588736 vendor/cache/nokogiri-1.12.4.gem
5ece6d833e90ae30ef8bf50c90402594411ba21e 9588736 vendor/cache/nokogiri-1.12.5.gem
de621fa50e797eecf1f5b2b31490366b2df1cea5 9588224 vendor/cache/nokogiri-1.12.3.gem
```

### git-filter-repo commands
this removes vendor/cache from the repo
```
git filter-repo --force --invert-paths --path-glob 'vendor/cache'
```

### Before
```
du -sh .git
1.5G    .git
```
### After

```
du -sh .git
154M    .git
```

## How to Mitigate the Issue
Until the upstream is cleaned up, here's config to help forks to work without interruption
More details on "[partial clones](https://about.gitlab.com/blog/2020/03/13/partial-clone-for-massive-repositories/)"
### New Clones 
```
git clone --single-branch --branch main --filter=blob:none  git@github.com:forem/forem.git
```
#### 80% smaller
```
 du -sm * .*|sort -n  |tail -5
5       .yarn
17      app
81      vendor
82      spec
137     .git
```

### Existing Clones
update refspec in `fetch` and `partialCloneFilter`
```
[remote "upstream"]
        url = git@github.com:forem/forem.git
        fetch = +refs/heads/main:refs/remotes/upstream/main
        promisor = true
        partialclonefilter = blob:none
```

Then run `git-filter-repo`  above to clean out the old objects

## How to Update Github
Once cleaned locally, the updated refs will need to be force-pushed to github.  Other contributors would then `git reset` or `git rebase` to use the new refs.

Rewriting history takes some communication.  First github is updated. Then core contributors (with write access) .  Then forks will need to update their base ref to reset to the new `main`. 

More info on cleaning approaches here: 
https://stackoverflow.com/questions/2100907/how-can-i-remove-delete-a-large-file-from-the-commit-history-in-the-git-reposito

## Steps to Reproduce 
1. ` git@github.com:forem/forem.git; cd forem`
2. `du -sh .git`

## Expected Behavior
Git repo should be less than a few hundred megs

## Actual behavior
Git repo is 1.5G

**Screenshots**
See above code samples
- OS, version: ` uname -a
5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux`
- Browser, version: n/a

**Comment by maestromac** [comment]
Thank you @tonymet . I really appreciate this write-up and I'm going to communicate with the team to try to move this forward.

**Comment by tonymet** [comment]
> Thank you @tonymet . I really appreciate this write-up and I'm going to communicate with the team to try to move this forward.

would it help if I contributed the "existing repos" instructions to the docs? that would help existing &  new contributors reduce their clone size.

**Comment by maestromac** [comment]
@tonymet yes that would help if you are still up for it.

**Comment by tonymet** [comment]
> @tonymet yes that would help if you are still up for it.

i'm happy to help and thanks for reviewing the issue. I'll find a slot for it and tag you on the PR

**Comment by tonymet** [comment]
i addressed with some documentation for now.

**Comment by maestromac** [comment]
I was hopeful to push this, but we're not going to move this forward at the time being. We have 4,000 forks and each of our commits is a ref for our build images. We don't have the bandwidth to see through all the ramification, so it's on hold. Thanks again for all this

**Comment by tonymet** [comment]
> I was hopeful to push this, but we're not going to move this forward at the time being. We have 4,000 forks and each of our commits is a ref for our build images. We don't have the bandwidth to see through all the ramification, so it's on hold. Thanks again for all this

thanks for the serious consideration and I agree it would be difficult .  I think the docs we added will help contributors so we have a good workaround for the time being. thanks again
