### ISSUE TITLE
Fix displayed article comment counts (take into account comments hidden after the author is assigned `spam`)

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20621]
**Describe the bug**

Article comment counts are not updating when comment authors are being applied with the `spam` role.

**To Reproduce**

- Find an article with multiple comments
- Apply `spam` role to one of the comment authors
- Wait for any caches to be invalidated
- Comment is hidden, but comment count remains the same.

**Expected behavior**

The comment count should show the number of visible comments on the article (i.e. not counting those from users applied with `spam`).

**Screenshots**

![image](https://github.com/forem/forem/assets/1628871/627b88aa-6232-4b1d-b8c5-3e5d615471fe)

**Additional context**

- We may not want to update the actual comment count, but dynamically calculate the actual number of displayed comments.

**Comment by lightalloy** [comment]
I think, the count in the "View full discussion (n comments)" was not updated, so may show wrong number in some cases.
Other places should be fine.
