### ISSUE TITLE
Remove de-indexing from accounts that have no comments

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20650]
## Is this feature related to a problem? Please describe.

As a new author on DEV, I would like to publish my content without having to comment on other posts for my content to be indexed, so new users can discover my content, even though I do not wish to comment on other members' posts.

## Describe the solution you’d like

- Stop checking whether a user has any comments to determine whether their post should be indexed by search engines or not.

## Additional Context

- [Here is the check
](https://github.com/forem/forem/blob/fa24a17fd7b246646c4b5dc3907402f39b57e7e3/app/models/article.rb#L631)

**Comment by danielmbrasil** [comment]
Hey, I'd like to work on this issue! Is this open to external contributors?

**Comment by PhilipHow** [comment]
@danielmbrasil Go for it!
