### ISSUE TITLE
Ways to Remove posts from spam accounts from /mod

### ISSUE THREAD

**Issue by VincentOracle** [forem/forem#20688]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by maestromac** [comment]
If this is in reference to https://github.com/forem/forem/issues/20649. it's resolved
