### ISSUE TITLE
Password reset email ends up in Spam says Google and the reset link is invalid according to Dev.to

### ISSUE THREAD

**Issue by andrejmoltok** [forem/forem#20690]
**Describe the bug**

First password reset email didn't arrive, second arrived, but reset token was invalid, third email(with a new token) got accepted.

**To Reproduce**

I don't know if it's reproduceable.

**Expected behavior**

Even if it ends up in Spam folder in Google, the reset link should work at first try, not the second.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: MX Linux 23
- Browser, version: Chrome

**Smartphone (please complete the following information):**

- Device: Xiaomi Redmi 9T
- OS, version: MIUI 14
- Browser, version: Chrome and Firefox for Android

**Additional context**

**Comment by PhilipHow** [comment]
Thanks for creating this issue @andrejmoltok - this is an issue with our third-party email provider, Sendgrid, which we have since fixed.
