### ISSUE TITLE
Funniest bug ever

### ISSUE THREAD

**Issue by eznix86** [forem/forem#20701]
**Describe the bug**
Unable to publish

**To Reproduce**

Click on preview, and save disppear when hovering *trying* hover on it

**Expected behavior**

Ability to publish

**Screenshots**

https://github.com/forem/forem/assets/26553194/e90face3-4851-45ef-a584-1408d5ec7e10

**Desktop (please complete the following information):**

- OS, version: MacOS Sonoma 14.0 
- Browser, version: Thorium 116 and Safari 17

**Comment by GwartneyDev** [comment]
@eznix86 I will have to test this on my mac my self as well, but before I do I did want to ask is it doing it in any other browser as well? And what happens when you refresh the page and clear cache ect?

**Comment by eznix86** [comment]
> @eznix86 I will have to test this on my mac my self as well, but before I do I did want to ask is it doing it in any other browser as well? And what happens when you refresh the page and clear cache ect?

Let me give you a list where it **does not work:**
- Google Chrome Version 121.0.6167.184 (Official Build) (x86_64)
- Thorium Version 116.0.5845.169 (Official Build) (x86_64)
- Firefox 123.0 (64-bit)
- Floorp Browser 11.8.1 (64-bit)
- Brave Browser Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (×86_64)

Where it does work:
- Sigma OS Version 1.14.0 (1.14.0.9-wv)

**Comment by GwartneyDev** [comment]
@eznix86 Awesome I will check it out on my end as well, then and see if I may be able to figure it out.

**Comment by Link2Twenty** [comment]
Here's the issue

https://github.com/forem/forem/blob/main/app/javascript/article-form/components/EditorActions.jsx#L67-L67

**Comment by eznix86** [comment]
> Here's the issue
> 
> 
> 
> https://github.com/forem/forem/blob/main/app/javascript/article-form/components/EditorActions.jsx#L67-L67

Did you manage to reproduce it ?

**Comment by Link2Twenty** [comment]
Yes, mousing over the bottom bar the `switchHelpContext` function, which in turn sets the state to the commonProps which has the preview set to false.

![bottom bar](https://github.com/forem/forem/assets/3534427/545e7be7-d2bf-4a66-84d4-cf9c3a6e1107)

https://github.com/forem/forem/blob/f263e17a1f3dd64f3a538e2181aaa19ea3214828/app/javascript/article-form/articleForm.jsx#L411-L419

https://github.com/forem/forem/blob/f263e17a1f3dd64f3a538e2181aaa19ea3214828/app/javascript/article-form/articleForm.jsx#L191-L203

to fix it you need to pass in the current `previewShowing` state or prevent switchHelpContext from triggering if the preview is open.
