### ISSUE TITLE
Link to Forem gives 404

### ISSUE THREAD

**Issue by richardj** [forem/forem#20858]
**Describe the bug**

The link in the footer of dev.to links to `https://www.forem.com` which shows a 404 page. When linked to `https://forem.com` it will show the correct page.

**To Reproduce**
1. Scroll down to the footer
2. click the link `Forem` in _Built on [Forem](https://www.forem.com/) —_
3. navigates to `https://www.forem.com`  and shows 404

**Expected behavior**

Show the Forem website which is at: https://forem.com

**Desktop (please complete the following information):**

- OS, version: Arch Linux
- Browser, version: Firefox (latest)

**Comment by maestromac** [comment]
Thanks for this report. Resolved.
