### ISSUE TITLE
Markdown > code block > `diff`-format syntax highlighting: use accessible colors

### ISSUE THREAD

**Issue by glebec** [forem/forem#2087]
**Is your feature request related to a problem? Please describe.**
The `diff` syntax for language blocks in markdown uses red and green as the contrasting colors for deleted and introduced lines respectively. Over 5% of men and ~0.5% of women have difficulty distinguishing red and green, meaning that some people will struggle to tell apart such lines, relying more on the small `-` and `+` characters on each line.

Example in GitHub (which also uses red-green for many UI elements):

```diff
this is an unchanged line
- this is a removed line
+ this is a new line
this is more unchanged stuff
```

**Describe the solution you'd like**
An alternative would be to modify the CSS for highlighting diffs to use variations on orange and blue respectively, which a much higher percentage of the population can distinguish.

**Describe alternatives you've considered**
- Red-blue is an imperfect compromise, better than red-green but not as universally distinguishable as orange-blue. However, red-blue might fit in better with cultural expectations of meaning, producing less confusion overall.
- Alternatively, no action may be taken. This isn't the most accessible choice, but as long as diffs still include ± characters in them, they are technically readable.

**Additional context**
Mockup below; exact values are not literal proposals, just food for thought.

Before:

<img width="939" alt="before" src="https://user-images.githubusercontent.com/7230206/54498661-6c65dd00-48e0-11e9-94c0-6ffb31aca9a7.png">

After:

<img width="939" alt="after" src="https://user-images.githubusercontent.com/7230206/54498667-725bbe00-48e0-11e9-81b9-f50a278c2501.png">

**Comment by maestromac** [comment]
I really like this idea @glebec !

**Comment by benhalpern** [comment]
Cool, let's make this change. We have no great tie to red green. I'm not 100% sure of this implementation, but let's only commit fully if we can do it without side affects of affecting other colors in the code.

Long term: I think we'll have custom theming for code snippets available in the future, so if the short term fix doesn't fly we can definitely have more accessible themes down the road. Since we're getting into custom config it shouldn't be too long til we get here.

**Comment by mstruve** [comment]
Removed from planning funnel as this edge case is pretty DEV specific and I think our team's time would be better focused on more Forem wide improvements and fixes.

**Comment by cmgorton** [comment]
> Removed from planning funnel as this edge case is pretty DEV specific and I think our team's time would be better focused on more Forem wide improvements and fixes.

Given this I am going to close this issue for now. Thanks for taking the time to open it and bring it to our attention.
