### ISSUE TITLE
Show posts with a negative score on a user's profile

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20905]
**Describe the bug**

- Posts with a negative score are not appearing on a user's profile.

**Expected behavior**

- Posts with a negative score should not be shown in the feed, but should appear directly on a user's profile.

**Additional context**

- We have made some recent changes to how `spam` posts appear on a user's profile, which may be linked with this unintended behavior.

**Comment by lightalloy** [comment]
Post's score is not related to the display logic in the users profile.
So, any posts (articles) will be displayed on the profile page. Added a spec for that in  #21047

If user has a spam role, their profile won't be accessible for regular users (so, the posts as well). For admins spammers profiles are accessible and so are their posts.

**Comment by lightalloy** [comment]
There is a separate issue related to low score comments #20845

**Comment by lightalloy** [comment]
Closing as not relevant (negative posts are displayed on profile).
