### ISSUE TITLE
Social media icon not visible in dark mode on home page and settings page.

### ISSUE THREAD

**Issue by Darshan-Padia** [forem/forem#20926]
**Describe the bug**
detailed description of the issue 
followed by screenshots

The Twitter ( X ) icon is not visible in the dark mode on the dev.to home page. Its also not visible in the settings page ( in both dark and light modes )

Below are the screenshots of the issues.

**1.) Icon not visible in dark mode ( home page )**

![image](https://github.com/forem/forem/assets/89976375/cff792db-756a-4283-86db-cfea84b01ea3)

**2.) Icon not visible in both ( dark and light  modes ) ( settings page )**

Dark Mode ->

![image](https://github.com/forem/forem/assets/89976375/3efd6a50-e1c6-42bd-a115-4867f4600cd2)

Light Mode ->

![image](https://github.com/forem/forem/assets/89976375/4689dae4-55cc-4457-9e48-52f5df8e0af5)

**To Reproduce**

1.) Open dev.to site , on the left sidebar there will be social media icons.
2.) Open dev.to site, on the right side click on profile icon -> click on settings -> there will be 4 options to correct twitter being the last one ( 4th one )

**Expected behavior**

Expected behaviour is the clear visibility of the icon in both dark and light modes.

**Comment by alex-hammer11** [comment]
I would like to take a look at this
