### ISSUE TITLE
Is joining free, or fee?

### ISSUE THREAD

**Issue by jakeisonline** [forem/forem#20967]
Billboard being shown to logged out users contains a rather confusing typo. Appreciate this isn't really a bug for Forem, but not really abuse either, so this seemed the most appropriate place?

**To Reproduce**

Tricky to reproduce as the billboards rotate, but generally:

1. Navigate to a post
2. Scroll down to the bottom to find the "Before you go" billboard

**Expected behavior**

Presumably the copy should read:

> It takes one minute and it's free.

**Screenshots**

![image](https://github.com/forem/forem/assets/178465/1cae6269-0d16-400d-a74c-1097b2a24bed)

**Comment by benhalpern** [comment]
Fixed
