### ISSUE TITLE
Request infinite loop when searching on the page (request to dsn.algolia.net)

### ISSUE THREAD

**Issue by pavelee** [forem/forem#20961]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.to/search?utf8=✓&q=test (could be any other phrase) or just use search bar on any page.
2. Open the network tab
3. Notice the request loop to `dsn.algolia.net`

**Expected behavior**

It should request only once or at least not in a infinite loop 🙏

**Screenshots**

![Zrzut ekranu 2024-05-17 o 21 39 25](https://github.com/forem/forem/assets/68032486/7cbf423a-990a-4dca-86cf-d2b946e2b724)

**Desktop (please complete the following information):**

- MacOs
- Safar, Chame, latest

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by benhalpern** [comment]
Thanks for this, looking to patch.
