### ISSUE TITLE
X logo (formerly Twitter) is not correctly visible in dark mode

### ISSUE THREAD

**Issue by fabriziobagala** [forem/forem#21120]
**Describe the bug**

When using the dark theme within the website, the X icon within the settings is not visible.

**To Reproduce**

1. Go to '[settings](https://dev.to/settings)'
2. Go to 'Customization' section
3. Click on 'Dark Theme' radio button
4. Click on 'Save' button
5. Go back to the 'Profile' section

**Expected behavior**

[square-x-twitter](https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid)

When the link opens, click on the `Nox! icon` to see the expected behavior.

**Screenshots**

![immagine](https://github.com/forem/forem/assets/62190484/6ef26e92-16a6-4183-bd94-e9872f78aca9)

**Desktop (please complete the following information):**

- OS, version: macOS Sonoma 14.5
- Browser, version: Firefox 126.0.1

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro
- OS, version: iOS 17.5.1
- Browser, version: Safari 17.5

**Additional context**

No additional information.

**Comment by kripa-sindhu-007** [comment]
I would love to work on this issue. As this is just a UI bug any experienced rank holder developer shouldn't bother with this. Leave it for soldiers like us.

-Please assign the issue to me.

**Comment by Rajvardhan222** [comment]
Is this issue solved?
if not please assign it to me.
