### ISSUE TITLE
Wikipedia Liquid tag's "View on Wikipedia" button does not work

### ISSUE THREAD

**Issue by yheuhtozr** [forem/forem#21154]
**Describe the bug**

When you embed a Wikipedia article, the Liquid template generates a button "View on Wikipedia" which does not jump to the linked article. The article title on the top works, though.

**To Reproduce**

Example on dev.to: https://dev.to/siddharthshyniben/challenge-write-a-true-quine-4pme

**Expected behavior**

The button should open the Wikipedia article, like GitHub or other embeds.

**Screenshots**

![image](https://github.com/forem/forem/assets/84892012/e9fae2ba-e489-40ef-967e-915c0c568f91)

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: FF 127, Edge 126

**Smartphone (please complete the following information):**

- Device: Pixel 4a
- OS, version: Android 13
- Browser, version: GC 126

**Additional context**

**Comment by benhalpern** [comment]
Thanks for the issue
