### ISSUE TITLE
Can't flag accounts with DEV++

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#21246]
**Describe the bug**
As a mod on DEV, we can't flag a account. With _dennistobar_ on [Discord](https://canary.discord.com/channels/738011915866865775/738011916315787284/1279040537986596864), we discuted about this problem, we can't report any account, and both we are DEV++ member. ~~Maybe is that?~~
Edit : Confirmed by Sebastian on [Discord](https://discord.com/channels/738011915866865775/738011916315787284/1279084032293994638)
> Can confirm it does not happen on my side (without DEV++) 👀

**To Reproduce**

~~(only if you are a DEV++ member I think)~~
1. Go to https://dev.to/adela_justice_b5e8bd62850/unboxing-the-future-of-luxury-why-custom-rigid-boxes-are-the-ultimate-packaging-solution-1nej (this is a spam post)
2. Flag the account
3. See the error

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/6e480f43-8ce0-4a80-a235-08de55272b0e)

https://github.com/user-attachments/assets/9bda46e9-8f21-42a6-8b86-265f80bc7bcf

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by benhalpern** [comment]
Sorry about this, looking into it pronto.
