### ISSUE TITLE
Markdown code contribution error

### ISSUE THREAD

**Issue by borisschapira** [forem/forem#2126]
**Describe the bug**
Unable to write a post containing HTML code for an image.

**To Reproduce**
Contribute this in an new post:

	---
	title: 'Test post'
	---
	
	```
	<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" … 
	```
	
**Expected behavior**
Saving is possible.

**Screenshots**
![Capture d’écran 2019-03-20 à 16 53 14](https://user-images.githubusercontent.com/284742/54699374-2c496900-4b31-11e9-85f6-88e37f0ce5d1.png)

**Desktop (please complete the following information):**

- OS: mac os
- Browser Chrome
- Version 73.0.3683.75

**Comment by Zhao-Andy** [comment]
Hey @borisschapira, we technically don't allow `src="data` as a very rough solution to prevent XSS. For now, you can try using single quotes instead, like `src='data:image`.
