### ISSUE TITLE
Commenting on posts leads to cyclic JSON object error

### ISSUE THREAD

**Issue by ell1e** [forem/forem#21283]
**Describe the bug**

Commenting on posts leads to cyclic JSON object error.

**To Reproduce**

1. Go to an article, the one I visited was: https://dev.to/mattconn/compiling-an-sdl2-game-to-wasm-42fj
2. Try to write a comment: 
    ![Screenshot_20240917_120317](https://github.com/user-attachments/assets/38a91c7c-75fe-41a3-98ca-a1bc2d7d6922)

3. The "Submit" button doesn't visibly react, and JavaScript errors appear in the browser console:

    ![Screenshot_20240917_120147](https://github.com/user-attachments/assets/eb04f2d2-a03e-47ae-b56d-7062915fdfe9)

**Expected behavior**

I would hope that commenting works, or otherwise maybe the website tells me why I'm not allowed to comment.

**Screenshots**

See above.

**Desktop (please complete the following information):**

- OS, version: postmarketOS Edge, latest rolling release
- Browser, version: Firefox 130.0 (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by kywelch17** [comment]
Hello, 

This has worked for me? I was able to add a comment and you can see my comment posted on there. Are you still experiencing this? I only used the link you provided.

**Comment by ell1e** [comment]
Interesting, it does seem to be working now. Maybe it was fixed in some way!
