### ISSUE TITLE
403 error for article cover image

### ISSUE THREAD

**Issue by Annastacia-dev** [forem/forem#21292]
**Describe the bug**
I'm fetching articles to display in my portfolio website but the images are not showing, I get a 403 forbidden error not sure when it broke when i first implemented it  it was okay and just noticed today

**Screenshots**
![Screenshot from 2024-09-23 12-20-00](https://github.com/user-attachments/assets/b4b0b775-aad1-4334-85b3-922d6861668b)

**Comment by calumk** [comment]
dev.to

<img width="1938" alt="image" src="https://github.com/user-attachments/assets/9227c978-2be8-4582-88a7-b291c7de6be6">

I am having the same issue - it seems that externally loaded image files now return the following message : 

"This asset is blocked. Contact dev.to if this is a mistake."

**Comment by GregPetropoulos** [comment]
I have the exact same issue, I tried setting the 'api-key' and the 'Accept'  as per docs for the headers. In other words with or without the headers I am getting the same issue. 

When I loop through the fetch response I did use the decodeURI(article.social_image) and it did not resolve the issue

**Comment by manuchekhr32** [comment]
I'm facing the same issue. I was working perfectly fine but suddenly it's returning 403 error for cover image:
<img width="468" alt="image" src="https://github.com/user-attachments/assets/c0de3ff9-4a5c-403b-9672-db5bd9afe48a">

**Comment by garpunkal** [comment]
same here

**Comment by Theyashsawarkar** [comment]
i am facing the same issue

**Comment by calumk** [comment]
Update : 02/10/24 
This appears to have been fixed.

**Comment by benhalpern** [comment]
Hi, sorry for the inconvenience! We had to deploy some overly aggressive edge security to deal with some excessive bot traffic. We have since been able to roll that back and focus on more precise mitigation.

Related: https://github.com/forem/forem/pull/21301
