### ISSUE TITLE
link opening in new tab

### ISSUE THREAD

**Issue by ParvamShah1** [forem/forem#21302]
**Describe the bug**
the latest link is opening in a new tab 

**To Reproduce**
when i click on the latest in the nav bar to view it it opens in a new tab which is a hassle for the user .
It is not handy for the user as if the user wants to view multiple section, he/she will end up opening multiple tabs which is not optimal.

**Expected behavior**
The section user clicks should replace the existing section and show that section rather than opening it in the new tab .

**Screenshots**

https://github.com/user-attachments/assets/9d9e5041-68a8-425b-8d7c-55d6414f2884

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version: mac os 
- Browser, version: google chrome 

**Additional context**

I would like to work on this issue.Please assign this issue to me !

**Comment by nitinyadav2188** [comment]
I want to solve this bug as it looks something challenging

**Comment by nathfreires** [comment]
I would like to claim this issue.

**Comment by quocanhute** [comment]
The issue occurs when you click on the new navigation tab labeled 'DEV++.' After navigating to the new view, click on the 'DEV' icon in the header, which will open a new tab. If you switch back to the original tab and click the back button, an error will appear.

https://github.com/user-attachments/assets/0115876f-a2af-4196-968f-cc772e32fbcb

Hope it help xD.
