### ISSUE TITLE
Unwanted header and trailer  space added to code snippets 

### ISSUE THREAD

**Issue by mjoycemilburn** [forem/forem#21310]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, Chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

![Screenshot3](https://github.com/user-attachments/assets/36e99cc3-7f43-41e5-8412-40c97fb5f351)
![Screenshot1](https://github.com/user-attachments/assets/12bc60a5-41bb-4636-b08f-fdc1878c458d)
![Screenshot2](https://github.com/user-attachments/assets/e9a6bf7a-2d43-4d77-9a99-a6f9ef3fcd97)

**Comment by benhalpern** [comment]
Hi sorry about the issues, this has been resolved here:

https://github.com/forem/forem/pull/21316
