### ISSUE TITLE
Squished profile picture on preview

### ISSUE THREAD

**Issue by JoppeDC** [forem/forem#2137]
**Describe the bug**
When doing a post preview, the profile pic next to the publisher name is squished.

**To Reproduce**
Create a new post, preview it.

1. Go to write a post
2. Click on preview
3. See publisher image

**Expected behavior**
Normal image

**Screenshots**
https://cl.ly/8950bcf37c07

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version 72

**Additional context**
This issue might be good as a first issue or a starter issue.

**Comment by Zhao-Andy** [comment]
Hmm looks okay for me.

![Image 2019-03-20 at 6 29 58 PM](https://user-images.githubusercontent.com/17884966/54723560-52293a80-4b3e-11e9-9604-8ef8e5b3c81b.png)

You're not talking about development/`localhost` right?

**Comment by JoppeDC** [comment]
> Hmm looks okay for me.
> 
> ![Image 2019-03-20 at 6 29 58 PM](https://user-images.githubusercontent.com/17884966/54723560-52293a80-4b3e-11e9-9604-8ef8e5b3c81b.png)
> 
> You're not talking about development / `localhost` right?

No, this is on the live version for me. Just done some cache clearing etc. and i'm still squished

**Comment by Zhao-Andy** [comment]
Oh, interesting. Looks like the image was scaled down to 50 x 26 (width x height) for some reason, and the CSS is changing it to 28 x 28. I think we don't format profile images to be squares, which is why it maintained that scale.

If you want a short term solution, you could crop your original image file to square and re-upload your profile image.

**Comment by JoppeDC** [comment]
Doesn't really bother me. Its only on the preview page, not on the post itself. Its correct anywhere else on the site, just not in the preview.

**Comment by cmgorton** [comment]
Thanks for opening this issue. Since it has one stale and doesn't seem to be an issue right now I am going to go a head and close this.
