### ISSUE TITLE
Display bookmark icon inside "Save" button

### ISSUE THREAD

**Issue by kontrollanten** [forem/forem#2144]
**Is your feature request related to a problem? Please describe.**
I've used dev.to for a while now, and I like a lot. It took my a while though to understand what the bookmark icon is. For a long time I thought it was just a "reaction". So every time I found a post I'd like to save, I had to search for the hashtag and in the list click on the "Save" button, to save it for later. And many other posts I "spam" reacted to with heart, unicorn and ...bookmark. So I was a bit confused for a while.

**Describe the solution you'd like**
I'd like to make it clearer that clicking on the bookmark icon in a article detail has the same effect as clicking on "Save" button in the list view.

**Describe alternatives you've considered**
I'd like to add the bookmark button inside the Save button. I'm not a designer or UX, so I don't know if this has other effects thought.

**Additional context**
![image](https://user-images.githubusercontent.com/6680299/54739075-05ce1100-4bb7-11e9-84e1-f0aeaf4ab20b.png)

```
    width: auto;
    min-width: auto;
    margin-right: 5px;
    height: 19px;
    margin-left: 0;
    vertical-align: -4px;
```

**Comment by aspittel** [comment]
Hey @kontrollanten, thanks for this idea! I think this could make the interface clearer, will discuss further with the team!

**Comment by jessleenyc** [comment]
let's keep this open

**Comment by ludwiczakpawel** [comment]
Sorry for a bit delayed explanation why I closed it. Here it is:

1. We have slightly updated not only feed cards and how the "Save" button looks like in the feed but also the Article view and "Save" button in that view as well. So this issue felt kinda outdated when I was looking at it last week.
2. We're internally doing some work around "Save" button inside the feed card - how it looks like and how it behaves when clicked. So I didn't want anyone to spend too much time thinking through this problems until we're finished.
3. We're also working pretty hard to on updating the "Reading List" page (which is where all Saved items are) - not only in terms of UI but also its general idea. This will likely affect how people think about and use this button.
