### ISSUE TITLE
Static assets have unusually short caching period

### ISSUE THREAD

**Issue by rhymes** [forem/forem#2147]
**Describe the bug**

I was testing the homepage with [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdev.to%2F) and [WebPage Performance Test](https://webpagetest.org/performance_optimization.php?test=190321_8H_be96eb19fc13a0947df3488adf259c64&run=1) (both links lead to the reports) and they both signalled that static assets (JavaScript files, images and CSS) have short caches, ranging from 1 day to 7 days.

Since they are all versioned I was wondering if there was a reason for that otherwise I'd like to suggest to set a longer cache for those, following [Google's best practice](https://developers.google.com/web/tools/lighthouse/audits/cache-policy) and set the cache to one year.

**Expected behavior**

A longer cache period for static assets.

**Screenshots**

Google PageSpeed Insights (same as Lighthouse):

![Screenshot_2019-03-21 PageSpeed Insights](https://user-images.githubusercontent.com/146201/54743950-ec809100-4bc5-11e9-8358-94ab5da90de8.png)

WebPage Performance Test:

![Screenshot_2019-03-21 WebPageTest Optimization Check Results - Dulles dev to - 03 21 19 10 29 24](https://user-images.githubusercontent.com/146201/54743969-fbffda00-4bc5-11e9-9025-8f36aa372314.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Version: 67b3

**Comment by aspittel** [comment]
Hey @rhymes, thanks for checking in on this -- @benhalpern may have some better insights on the cache length!

**Comment by rhymes** [comment]
unstale

**Comment by mstruve** [comment]
@rhymes is this still something that would be worth doing?

**Comment by rhymes** [comment]
Yep, although it's better than March 2019, it's still unclear why we keep short caching periods on fingerprinted static assets, see https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdev.to%2F ("Diagnostics -> Serve static assets with an efficient cache policy"). It's 30 days, it could be years.

This doesn't happen on forem.dev as it uses nginx for caching IIRC.

Notice the difference (on a fingerprinted CSS file):

**forem.dev** and **the community club** and I guess the others as well:

<img width="324" alt="Screenshot 2020-11-07 at 8 06 01 AM" src="https://user-images.githubusercontent.com/146201/98434462-34706680-20d0-11eb-9875-8f5365309b14.png">

**Comment by mstruve** [comment]
Great! going to throw it on our end of year priority board. Thanks!
