### ISSUE TITLE
Ruby themes file

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#2154]
Is it worth having a ruby file that contains the theme's HTML, though we'd only have night mode in there for now?

I'm not that clued up on ruby on rails but I presume we can have a file that contains several thems but will only return the relevant HTML based on some request?

CC: @rhymes @lightalloy

**Comment by Link2Twenty** [comment]
Current implementation is for the css variables to be stored in the javascript.

https://github.com/thepracticaldev/dev.to/blob/master/app/views/layouts/application.html.erb#L82-L109

**Comment by Link2Twenty** [comment]
From a JS point of view you could do something like this.

```javascript
function getTheme(theme) {
  return new Promise(function (resolve, reject) {
    var url = 'some_url?theme=' + theme;
    var themeReq = new XMLHttpRequest();
    // Resolve promise on load
    themeReq.addEventListener('load', data => {
      resolve(data.target.reponse)
    });
    // Reject promise on error
    themeReq.addEventListener('error', err => {
      reject(err)
    });

    themeReq.open("GET", url);
    themeReq.send();
  })
}

 try {
  var bodyClass = localStorage.getItem('config_body_class');
  document.body.className = bodyClass;
  if (bodyClass.includes('night-theme')) {
    getTheme('night-theme').then(styles=>{
      document.getElementById('body-styles').innerHTML = styles;
    })
  }
} catch(e) {
  console.log(e)
}

```

**Comment by aspittel** [comment]
Hey @Link2Twenty, thanks for this idea! @benhalpern has been leading the effort here, he may have more insight on the implementation!

**Comment by benhalpern** [comment]
@Link2Twenty I see you just closed this in conjunction with the creation of `_user_config.html.erb`, which is a step in this direction, but it's still just tossing the CSS into string interpolation. I think it hides the mess a bit and is good enough for the near future, but we will want to keep this in mind as an evolution. The way we tweak the themes will need to keep changing, but I'm glad we're taking small steps rather than engineering the final solution upfront.

**Comment by nickytonline** [comment]
Just a little note about the `getTheme` function snippet. You can use `fetch` instead of wrapping `XMLHttpRequest` in a promise as fetch is already promise based, https://developer.mozilla.org/en-US/docs/Web/API/Request#Examples.

**Comment by Link2Twenty** [comment]
I was thinking about this and storing themes as CSS is fine. We could read that CSS with ~XMLHttpRequest~ fetch and do some work with it in the front end.

The only problem I've had with the theme changing is that it does not happen instantly when you press save. I think we could do something like this this.

```js
async function updateStyles(theme) {
  const css = await fetch(`https://dev.to/assets/themes/${theme}.css`);
  
  let string = await css.text();
  string = string.substring(6, string.length - 2);
  
  const styles = string.split(";");
  const root = document.documentElement;
  
  for (let style of styles) {
    const [prop, setting] = style.split(": ");
    root.style.setProperty(prop, setting);
  }
}
```

Here's it working in practice

https://jsfiddle.net/link2twenty/5nu80tph/
