### ISSUE TITLE
[Theme] Notification color

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#2156]
Do we want to theme the bell number?
If we do should it be the same as `--theme-top-bar-write-background` or perhaps a new property, `--theme-top-bar-notification-background`?

![image](https://user-images.githubusercontent.com/3534427/54752952-a92f1e00-4bd7-11e9-8269-191a1730b230.png)

**Comment by aspittel** [comment]
Hey @Link2Twenty -- thanks for all the great theme insights! Again, going to ping @benhalpern here, but this seems to make sense from my perspective!
