### ISSUE TITLE
Use only one version of CodeMirror

### ISSUE THREAD

**Issue by rhymes** [forem/forem#2165]
**Is your feature request related to a problem? Please describe.**

The codebase uses various versions of codemirror:

* `package.json` declares `^5.44.0` and `yarn.lock` is using `5.44.0`. This is the version used by the code editor:

https://github.com/thepracticaldev/dev.to/blob/a2fcbdc4a4d1de430ff3ec282b373922632a2d4d/app/javascript/chat/codeEditor.jsx#L7-L8

* `app/views/blocks/_form.html.erb` links to another version of CodeMirror, `5.26.0`:

https://github.com/thepracticaldev/dev.to/blob/a2fcbdc4a4d1de430ff3ec282b373922632a2d4d/app/views/blocks/_form.html.erb#L1-L5

* `app/views/chat_channels/index.html.erb` uses a third version of CodeMirror (only the CSS), `5.38.0`:

https://github.com/thepracticaldev/dev.to/blob/a2fcbdc4a4d1de430ff3ec282b373922632a2d4d/app/views/chat_channels/index.html.erb#L6-L7

**Describe the solution you'd like**

CodeMirror is currently at [version 5.45.0](https://github.com/codemirror/CodeMirror/blob/master/CHANGELOG.md#5450-2019-03-20). I was wondering if all three sections could use the same version from the `package.json`

**Comment by aspittel** [comment]
Great question @rhymes! Thanks for reporting this -- we should definitely look into whether it's possible to consolidate these.

**Comment by rhymes** [comment]
We don't use this library anymore
