### ISSUE TITLE
Use randomly generated IDs in the REST API

### ISSUE THREAD

**Issue by rhymes** [forem/forem#2187]
**Is your feature request related to a problem? Please describe.**

I'm opening this ticket after having read [this great article about data analysis on dev.to's articles](https://dev.to/daolf/-what-is-the-best-time-to-post-on-devto-a-data-backed-answer--1kob). 

The question I'd like to set forth, in preparation for a future "publication" of the API, is: should dev.to use randomly generated resource IDs instead of exposing "internal" autoincrementing integer primary keys or not?

A "classic" best practice in API design is not to expose internal details of your app, separating as much as possible how the data is organized from how is accessible from third parties. 

Autoincrementing primary keys are usually discouraged in public APIs (by some, not by all) mainly for three reasons:

1. they expose database IDs to the public. Today you might have data in a relational database, tomorrow that data might be elsewhere and those IDs might not mean much because autoincrementing primary keys are local to one data source.
2. by exposing incrementing IDs an onlooker (or a malicious attacker) can gather two information: size of the tables and growth rate
3. it's easier for a malicious attacker to write a script to scrape data

This is more a question of policy than a technical argument because, at least for the second of the three reasons, DEV is perhaps perfectly fine with that.

Some possible alternatives to auto incrementing integer primary keys:

* UUIDs: PostgreSQL has a [native indexable UUID type](https://www.postgresql.org/docs/9.6/datatype-uuid.html) with functions to generate default UUIDs, like pgcrypto's `gen_random_uuid()`. UUIDs though are not sortable, they kind of look ugly and they are verbose: `https://dev.to/api/articles/2d931510-d99f-494a-8c67-87feb05e1594` 
* KSUIDs: they are [quite new](https://segment.com/blog/a-brief-history-of-the-uuid/) and were "invented" by Segment. The characteristic they have is that they are sortable and time dependent: `https://dev.to/api/articles/0ujsszwN8NRY24YaXiTIE2VWDTS`
* some other random alphanumeric ID generated in the app (eg. Ruby's `SecureRandom.alphanumeric(20)`): `https://dev.to/api/articles/cDAkKyz38cqjTI1bV5lG`

My preference goes to one of the last two options

**Describe the solution you'd like**

Because the API is not public yet, and it's relatively small (only 8 controllers), I think that the transition would be doable if there's consensus on this. After publication and documentation it might be harder, especially because DEV is already a big community and developers are already jumping at the opportunity to use the API (hence the article ;))

For obvious reasons there shouldn't be a situation where both (integer IDs and alphanumeric IDs) would work at the same time. That would only strain the system (because it might result in two queries, instead of one). 

The frontend/SPA would also need to be aligned and updated.

What do you think?

**Additional context**

I did a quick tour of some public APIs (starting from [those used by DEV](https://docs.dev.to/addl-tech/) itself and this is what I've found:

* [Fastly](https://docs.fastly.com/api/purge) uses both URLs (for obvious reasons) and alphanumeric IDs (eg. `SU1Z0isxPaozGVKXdv0eY`) to identify resources, probably generated by the equivalent of Ruby's `SecureRandom.alphanumeric(21)`
* [Cloudinary](https://cloudinary.com/documentation/upload_images#public_id_the_image_identifier) uses a `public_id` which is a randomly generated string (eg. `8jsb1xofxdqamu2rzwt9q`)
* [Stripe](https://stripe.com/docs/api/charges/object) uses alphanumeric random strings prefixed by a resource identifier, for example `ch_19yUdh2eZvKYlo2CkFVBOZG7` for a charge and `cus_El7v7DRE34iBPx` for a customer

A few more: 

* [StackOverflow](https://api.stackexchange.com/docs/types/answer) uses integer IDs
* [Twilio](https://www.twilio.com/docs/sms/api/message-resource) uses string IDs with a prefix for type of resource, similar to Stripe
* [PayPal](https://developer.paypal.com/docs/api/orders/v2/#orders_get) uses alphanumeric IDs

Refs #911

**Comment by abraham** [comment]
Similar to KSUID is [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) that have been in use in MongoDB for a while.

A fun app is Twitter. They were originally based on Rails and used sequential IDs until they ran into scaling issues and needed to generate IDs on multiple servers at once. You can [read about their fix](https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake.html). (I'm not advocating this as a solution, it's just interesting.)

**Comment by rhymes** [comment]
> Similar to KSUID is ObjectId that have been in use in MongoDB for a while.

Cool, seems based on the same principle, the ability to sort and extract time information.

> A fun app is Twitter. They were originally based on Rails and used sequential IDs until they ran into scaling issues and needed to generate IDs on multiple servers at once. You can read about their fix. (I'm not advocating this as a solution, it's just interesting.)

Yeah that's a classic problem in distributed programming after passing a certain scale I guess, Snowflake is mentioned in the [Segment article](https://segment.com/blog/a-brief-history-of-the-uuid/). Although DEV is probably a little away to have those scaling issues I think it would save a lot of pain down the line to guard against that

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
