### ISSUE TITLE
Username column should be not null

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#2207]
The `user` table can sometimes have a `username = null` field. This shouldn't be allowed since we always want to ensure that users have a username. We currently have validations in the model level but not the database level.

Related to #2205

**Comment by omenking** [comment]
Something to consider:
[Adding a NOT NULL CONSTRAINT on PG Faster with Minimal Locking](https://medium.com/doctolib/adding-a-not-null-constraint-on-pg-faster-with-minimal-locking-38b2c00c4d1c)

Adding a postgres constraist is easy part.

The hidden work here is:
* [ ] Ensure whe a user signs up and updates to users work (are there specs?)
* [ ] A Migration that backfills blank usernames with a default and ensures they are unique
