### ISSUE TITLE
Add a HTML Meta tag with deployed git commit hash

### ISSUE THREAD

**Issue by eusonlito** [forem/forem#2223]
What about to add a `html` `meta` tag on header with the current git commit deployed?

On this way it's easy to contributors and developers follow website status and deployment compared with github commits.

I don't know if exists some tag for this proposse, but what about something like:

```
<meta name="git-commit" content="6e23483b9421c1e1a03d94093306badf277cc19e">
```

Regards :)

**Comment by jessleenyc** [comment]
@maestromac what are your thoughts on this??

**Comment by maestromac** [comment]
This would really be a useful feature! I'd imagine this be done automatically either via bash. We squash our PR commits though, so that complicate things a bit.

**Comment by mstruve** [comment]
I was about to grab this ticket when I realized that we actually [already have this setup in our codebase](https://github.com/forem/forem/blob/master/app/views/shell/_top.html.erb#L59) so I am going to go ahead and close it! Thanks for the great suggestion! 

```
data-release-footprint="<%= ApplicationConfig["RELEASE_FOOTPRINT"] %>"
```
