### ISSUE TITLE
Error loading images

### ISSUE THREAD

**Issue by brylie** [forem/forem#2228]
I shared a dev.to article on Reddit, and [one of the commenters said images wouldn't load](https://www.reddit.com/r/vuejs/comments/b59cbd/update_routerview_when_vue_route_changes_dev/ejc26j7/).

Here is the rest of their diagnosis:

```
These images:

https://i.imgur.com/GArpxyC.png

Errors reported in console:

manifest-36a1d0b68d1e3664106b.js:1 Uncaught SyntaxError: Unexpected token <

vendor-a16759536b738a97f545.js:1 Uncaught SyntaxError: Unexpected token <

Search-d6be81c747f6325b6aae.js:1 Uncaught SyntaxError: Unexpected token <

base-55719a78ce4c394706e03834ae49c59cddc235c3ef5dbc299c63b4edf0f0b558.js:1 Uncaught SyntaxError: Unexpected token <

webShare-1698d2d09639b4c8b299.js:1 Uncaught SyntaxError: Unexpected token <

reload-router-view-when-vue-route-changes-3cck:1 Error while trying to use the following icon from the Manifest: https://practicaldev-herokuapp-com.freetls.fastly.net/assets/devlogo-pwa-192-b92c1c02f2f63967c2889ba04a4d7bc61da640a6dbe419d65703b1282c96b46c.png (Download error or resource isn't a valid image)

serviceworker.js:1 Uncaught (in promise) TypeError: Failed to fetch


If I go to "Google chrome dev tools" --> "Application" --> "Service worker" and check "Bypass for network", and reload, everything works


After some more debugging, it seems like the XHR requests to *.freessl.fastly are blocked by the privacy settings in my browser, if I whitelist that origin for XHR requests from your domain, it works
```

**Comment by brylie** [comment]
So, it may be that using *.freessl.fastly is causing difficulties for some users.

**Comment by rhymes** [comment]
@brylie did you ask them to check without extensions? That's the first thing I could think of

**Comment by brylie** [comment]
Response in the Reddit issue:

>This is part of the privacy extension installed in my browser, UMatrix https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf

>In its default settings, it allows full access to resources on the current domain, and image and css only from other domains. Since your domain makes XHR requests from a service worker, instead of normal image requests, images show as broken

**Comment by maestromac** [comment]
Seems a bit related to https://github.com/thepracticaldev/dev.to/issues/250#issuecomment-501304147 . Which browser are you using @brylie ?

**Comment by brylie** [comment]
Again, this isn't an issue I faced directly. See the related Reddit issue.

**Comment by maestromac** [comment]
Oh right sorry I missed that that. 

Your report is very useful to us and it will make it easier to debug Service Worker.

**Comment by trasherdk** [comment]
Firefox 70.0 (64bit) on Windows 8.1 Pro.

`SyntaxError: expected expression, got '<'`
```
Pusher.ScriptReceivers[1](null, { host: 'timeline48-clientstats1.pusher.com' });
```

**Comment by maestromac** [comment]
Are you also experiencing this image loading issue @trasherdk ?

**Comment by trasherdk** [comment]
I did have some image loading issues, mostly related to tracking stuff.

An upgrade of my email client took care of active contents and tracking images in HTML email.
Also, Firefox has gotten a lot more aggressive against tracking users.

I'm not a big fan of tracking users across the web, and applause any company helping combating this.

**Comment by trasherdk** [comment]
The `SyntaxError: expected expression, got '<'` is related to embedded contents, like Codepen stuff.

**Comment by cmgorton** [comment]
Hey! Thanks for opening this bug report. We are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. If you experience this again in the future please let us know and we can open this back up.
