### ISSUE TITLE
Improve the feed using the tags picked by an user

### ISSUE THREAD

**Issue by Mte90** [forem/forem#2249]
**Describe the bug**
An user pick the tags that want to follow but there isn't any priority to them on the various feed availables.

**To Reproduce**

1. Set tags on your user
2. Check the tags of the post in your feed

**Expected behavior**
The feeds has only stuff of the tags that the user is following or else they are useless right now

**Screenshots**
![immagine](https://user-images.githubusercontent.com/403283/55291366-2def1880-53de-11e9-987d-6ee05c16481f.png)
![immagine](https://user-images.githubusercontent.com/403283/55291374-3a737100-53de-11e9-835c-df3469a0a66a.png)

**Comment by Glennmen** [comment]
I think this is related to this issue: https://github.com/thepracticaldev/dev.to/issues/1856

**Comment by Mte90** [comment]
Yes they are related but is suggesting another way, ignore the tags but is not talking about use the tags that an user chose.
Right now this feature is useless because is like a bookmark and that's it.

**Comment by jessleenyc** [comment]
@Mte90 thanks for the issue -- followed tags and users are prioritized in a feed but we do still include some other articles w/ tags you don't follow. Sounds like you're interested in having tags prioritized further which is something we can consider. 

And in case this is something you're interested in -  you can adjust the priority 'weight' of each tag you follow on https://dev.to/dashboard/following. The higher number you give the more often articles w/ those tags will appear in your feed.

**Comment by Mte90** [comment]
Thanks for the hint!

About prioritize is quite clear because I don't follow the tags of the post that are in the screen but I am getting them anyway.
So right now for me is not clear how tags are working, if I follow them I should see this tags and not others tha I don't care. 
AS example I am getting a lot of stuff about webdev or javascript but I am not following this tags.

**Comment by jessleenyc** [comment]
@Mte90 out of curiosity are you following any of the _people_ that would have published the posts w/ tags you don't follow?

**Comment by Mte90** [comment]
No I follow only 1 person that is about php stuff :-)

**Comment by jessleenyc** [comment]
OK, cool. Thanks for the feedback - I'd say this is working as intended for now but we're always making adjustments to the feed and this might make sense as something for people to customize on their own -- i.e. "I only want to see posts from tags and people I follow", "I want to see things I follow, plus other popular content", etc.

**Comment by Mte90** [comment]
Any news? This is the reason why I stopped using dev.to and also publishing new articles because I don't have anymore as pinned tab.

My feed is full of stuff that I don't care or not interesting for me (a lot about js or dev career posts).

Right now I prefer reddit because the feed is customized based on my interests...

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here. 
 We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
