### ISSUE TITLE
Dark Mode text weight/kerning

### ISSUE THREAD

**Issue by forsh3y** [forem/forem#2295]
**Is your feature request related to a problem? Please describe.**
I'm in no way visually disabled, but reading large groupings of text in nightmode makes my eyes hurt!

**Describe the solution you'd like**
A lighter font weight for regular text in dark mode. [Details here: ](https://css-tricks.com/dark-modes-with-css/#article-header-id-2)

**Describe alternatives you've considered**
Unsure, I imagine this will be far far far down on the totem pole anyhow.

**Additional context**
This showcases how the font weight is hard to distinguish and how "clumped" the text is.
![image](https://user-images.githubusercontent.com/34724411/55447298-6890b680-5580-11e9-9f77-13ec2d216afc.png)

**Comment by benhalpern** [comment]
I think this makes sense. Since we have separate controls for font and theme, I think it might make sense to offer the proposed solution here as a font variation. Users could be instructed that they may want to choose the lighter font weight alongside dark mode.

Does that make sense?

**Comment by forsh3y** [comment]
Yeah, that would make sense, makes it more adaptable for device differences. Thanks for checking this out!

**Comment by luckyguy73** [comment]
I would like to attempt to resolve this issue.  It's my first open source contribution ever.  I was brought here by Hacktoberfest.  My idea is to add a toggle on the User Settings/UX menu directly beneath the "Base Reading Font" toggle allowing user to select from Lighter, Normal, and Bold options.  If this sounds acceptable then please assign issue to me, thanks.

**Comment by cmgorton** [comment]
Since we have options to change fonts in our settings this seems like something that is no longer an issue correct?
![font choices for DEV](https://user-images.githubusercontent.com/21039864/100631954-e2e38200-32f1-11eb-8021-2563cc1fa6ef.png)
I am going to go a head and close this issue. If anyone thinks this is still a problem please feel free to open it back up.
