### ISSUE TITLE
Consider making reading times an 'opt-in' feature

### ISSUE THREAD

**Issue by jaydm** [forem/forem#2304]
**Is your feature request related to a problem? Please describe.**
People with dyslexia may find reading times unpleasant:
![image](https://user-images.githubusercontent.com/595062/55516478-f1682a80-5632-11e9-8a67-0ff40e13562b.png)

**Describe the solution you'd like**
Suggest that the reading time either be removed or provide an option to opt-in to see them (so that by default they are hidden).

**Describe alternatives you've considered**
See above - either remove reading times or provide an opt-in to enable them (cookie?)

**Additional context**
Here is one blog post showing the reading time:
![image](https://user-images.githubusercontent.com/595062/55516417-c41b7c80-5632-11e9-9fd2-629a645d4904.png)

**Comment by jessleenyc** [comment]
We've been adding more user configurations and this seems like something that would make sense but I'm not really sure how feasible on the implementation side with caching, etc.

**Comment by jaydm** [comment]
What about setting a cookie to track whether the visitor wants to see reading times? Then you could use the cookie value to trigger visibility of the reading time...
I haven't had a chance to look into the code yet so I don't know if this or anything like it would be viable. But is this or perhaps some other method available to set a session variable?

**Comment by cmgorton** [comment]
Thank you for opening this issue. We appreciate your input. Since this has gone stale and there hasn't been further discussion for over a year I am going to go a head and close this issue.
