### ISSUE TITLE
Accessibility: Allow tags to be dash-delimited or allow them to contain capital letters

### ISSUE THREAD

**Issue by kleinfreund** [forem/forem#2347]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, tags on dev.to are, from what I can tell, lowercase and may contain alphanumeric characters (more or less). For example, the following tags are not allowed:

- `#custom-properties`
- `#CustomProperties`
- `#custom_properties`

This makes tags unnecessarily hard to read, especially for user groups who find it difficult to read in the first place or who just learn reading English.

**Describe the solution you'd like**
Preferably, tags would allow the dash character (`-`) as a delimiter. The underscore is not ideal as it is potentially occluded by underlines.

**Describe alternatives you've considered**
Alternatively, characters are allowed to be uppercase which would allow users to write title-cased likes (for reference, see Twitter where this is possible).

**Comment by mstruve** [comment]
Thank you for your contributions here! Changing the way we handle tags would be a major feature request and we have a new process moving forward to address feature requests.

We have recently started using a new internal RFC process for feature requests. Going forward and in this case, any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev). For that reason, I am going to close this issue and if you would like to champion this feature further please open up a discussion on forem.dev. 

You can read more about our Internal RFC Process and forem.dev discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4). 

Thanks for being an awesome part of this community! ❤️
