### ISSUE TITLE
Via the Dashboard be able to filter Articles by "All Posts", "Draft" and "Published"

### ISSUE THREAD

**Issue by omenking** [forem/forem#2351]
**Is your feature request related to a problem? Please describe.**
Being able to filter All, Draft and Published articles are nice to have for content creators.

**Describe the solution you'd like**
A dropdown that defaults to All Posts with also Draft and Published.

**Describe alternatives you've considered**
Instead of a dropdown, I would much rather have a toggle between Draft and Published with no "All Posts" filter. The reason I suggest this is so that we position these listings to have unique features based on context.

So if published articles in the list do not share the same template partial we can have additional information at a glance for the published listing. A wild example of such an additional future feature for a unique published listing could be a ticker graph of article views/reactions. 

**Additional context**
Nada.

**Comment by matisnape** [comment]
I would like to do this. 
However, I think that having 2 dropdowns in this view is not a very good idea, UI-wise https://monosnap.com/file/B4odC8wh4EJ47iH4t2GdibfrBixZVS
I think toggle buttons like on listings dashboard would look better https://monosnap.com/file/Any6ZCy5N16EC8QGS7SRNUQyz1vTwf

@jessleenyc WDYT? Also, any tips on placement of this dropdown/toggle? And if we go for toggles - what colors they should be?

**Comment by cmgorton** [comment]
Hello Andrew! Thanks for your contributions here. 
 We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
