### ISSUE TITLE
Add Google Lighthouse to Travis CI build

### ISSUE THREAD

**Issue by rhymes** [forem/forem#2370]
**Is your feature request related to a problem? Please describe.**

[Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) is a great tool to keep an eye on the performance and quality of web pages. But, like all tools, it needs to be regularly checked. I propose to activate the [Google Lighthouse Bot](https://github.com/GoogleChromeLabs/lighthousebot) on PRs through Travis CI. 

An example output:

![](https://user-images.githubusercontent.com/238208/46586553-dfffe600-ca34-11e8-9eea-3846b41a4360.png)

**Describe the solution you'd like**

The bot can be activated and it can run in two modes:

* show the summary for human consumption
* show the summary AND fail a PR if a predefined metrics falls under a given threshold.

I'd activate the first step initially, and maybe consider failing PRs in the future once a better understanding of those metrics is acquired as all tools need to be taken with a grain of salt and weighted against specific goals.

**Comment by aspittel** [comment]
Wow! This is an awesome idea! @maestromac and @benhalpern may have more ideas, but I think this sounds so cool! Thanks for thinking of it @rhymes!

**Comment by maestromac** [comment]
I like this idea but we might have to set up a pr-staging server first.

**Comment by benhalpern** [comment]
I'm for this

**Comment by jessleenyc** [comment]
I don't think we can do this right away because of the current overhead it'll take to set up. Hopefully a headless option comes out soon that'll make it easier for us to incorporate.

**Comment by rhymes** [comment]
Hi @jessleenyc, got it :-) I thought it was headless already. It does require an API key to talk to Google servers though :(

**Comment by abraham** [comment]
There are options that don't use Google's service. I've used [lighthouse-ci](https://www.npmjs.com/package/lighthouse-ci) on Travis with just pointing it to a localhost server in the test environment.

**Comment by Glennmen** [comment]
Google has no released an official [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci)
They announced it on [Chrome Dev Summit](https://twitter.com/ChromiumDev/status/1193966926214483968?s=20).

**Comment by rhymes** [comment]
@maestromac this [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) looks cool but we'd still need to find a way to start a web server in the build, which with Rails startup speeds seems it's going to be super slooooow

**Comment by cmgorton** [comment]
@rhymes given our new process for feature request do you think this would make a good RFC or should we close this issue?

**Comment by rhymes** [comment]
I talked with SRE and we've decided to close it. Thank you @cmgorton
