### ISSUE TITLE
Feature Request: Automatically toggle themes at certain times or sunrise/sunset

### ISSUE THREAD

**Issue by mariocsee** [forem/forem#2421]
**Is your feature request related to a problem? Please describe.**
With the introduction of the night theme, perhaps down the line, there could be an automatic toggling of some light or dark theme at certain times or sunrise/sunset as an opt in feature similar to how the Reddit app or Night Shift. The night theme is still improving, so perhaps when themes become more consistent on dev.to is when to consider building a feature like this.

**Describe the solution you'd like**
Perhaps users would be able to determine their city (for sunrise/sunset times) or set certain times to toggle between two themes (currently there is default and night theme). 

**Describe alternatives you've considered**
The iOS/Android apps may be able to request some information so it is easier done on the apps? 

**Additional context**
N/A

**Comment by cmgorton** [comment]
This issue is similar to #3222 which we are currently working on implementing. Since this has gone stale and we are working on other version of this implementation I am going to go a head and close this. Thanks for opening up a discussion on this feature.
