### ISSUE TITLE
Video Player Results In Errors for Some Users

### ISSUE THREAD

**Issue by omenking** [forem/forem#2436]
**Describe the bug**
4 different DEV.to users have reported they receive an error when using the video player. Here is one comment on the [post with the video in question](https://dev.to/exampro/how-to-serve-on-demand-videos-from-aws-4fo4)

<img width="821" alt="Screen Shot 2019-04-14 at 10 04 39 AM" src="https://user-images.githubusercontent.com/7776/56093998-efa52f00-5e9c-11e9-9dca-e2e7a291edea.png">

I am going to posting lots of video content in the coming months so I think I will keep hearing issues around the video functionality 

**To Reproduce**
I have yet to be able to replicate this issue.
Uncertain if this is related to OSX and Safari. I happen to have old and new macs and cannot replicate this error.

https://discussions.apple.com/thread/8501889

```
Given I am a logged in user
and there is a post with video
When I try to play the video
Then I get an error
```

**Expected behavior**
No error should happen

**Screenshots**
I cannot provide a screenshot since I am unable to replicate the issue.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by Zhao-Andy** [comment]
We use JW Player for our video playback. I believe the error code is from JW Player and not Apple.

https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference/#media-playback-html5

**Comment by jessleenyc** [comment]
I briefly tried recreating this by spot checking various devices/os/browsers via browserstack. I can't seem to recreate the issue so I left a comment reply to the person who's getting the error code asking for more details.

**Comment by cmgorton** [comment]
@omenking have you had anyone mention this error again since originally posting this? If so I will keep this open. If not I think we can close this issue. :)

**Comment by omenking** [comment]
This is no longer valid
