### ISSUE TITLE
Iron out possible failures associated with randomized spec order

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#2483]
We recently enabled random spec ordering, which leads to better robustness in our specs longterm:

https://github.com/thepracticaldev/dev.to/pull/2466

I believe they are indeed revealing random failures based on ordering. I believe we should:

- Seek to confirm that failures are indeed due to random ordering
- Possibly temporarily switch back to non-random ordering while we get the issues resolved
- Resolve the issues related to random ordering

Thoughts?

**Comment by Zhao-Andy** [comment]
I think that makes sense. My unscientific experience with the failures is that some specs are not properly signed in when necessary.

**Comment by benhalpern** [comment]
I created a PR if we want to go that route:

https://github.com/thepracticaldev/dev.to/pull/2486

**Comment by benhalpern** [comment]
Okay, I merged the commenting-out of the `:random`, but this can definitely remain an open discussion.

**Comment by maestromac** [comment]
For future debugging
<img width="1028" alt="Screen Shot 2019-04-17 at 1 20 51 PM" src="https://user-images.githubusercontent.com/15793250/56389806-8143d200-61f8-11e9-84b8-e41922d3820f.png">

**Comment by mstruve** [comment]
How do we feel about closing this Issue in favor of this new Epic [Flaky Spec Cleanup](https://app.zenhub.com/workspaces/dev-center-57942d3f59fb02845483fe47/issues/thepracticaldev/dev.to/4884) which we can connect issues to for individual flaky specs that come up?

**Comment by rhymes** [comment]
Tip: `rspec --bisect` is quite useful in hunting down ordering issues
