### ISSUE TITLE
Reporting user in connect group chat wrong info 

### ISSUE THREAD

**Issue by mariocsee** [forem/forem#2489]
**Describe the bug**
When viewing a profile from within a group chat in `/connect/`, the report abuse button does not have updated information and when reporting, passes on the name of the group chat rather than the particular user. 

**To Reproduce**

1. Go to `/connect/General` (or any group chat on DEV)
2. Click on the group name to open up details about the group
3. Click on any user to open up user details
4. Click on report abuse
5. See wrong information, since you dont necessarily have a separate direct channel with all users in a group chat
6. Click on Yes, report abuse
7. See link field is filled with `/connect/General` or any group name rather than the particular user you were viewing

**Expected behavior**
The message should be adjusted to the proper context and the report abuse field should contain the particular user instead.

**Screenshots**
<img width="776" alt="Screen Shot 2019-04-18 at 13 53 40" src="https://user-images.githubusercontent.com/13403332/56381209-38811e80-61e2-11e9-871d-3760a86f938e.png">
<img width="760" alt="Screen Shot 2019-04-18 at 13 53 57" src="https://user-images.githubusercontent.com/13403332/56381212-3ae37880-61e2-11e9-88c2-c0b58140e8d6.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 73

**Comment by thamaraiselvam** [comment]
Not able to recreate, is it fixed?

**Comment by mariocsee** [comment]
@thamaraiselvam Nope, the bug still exists. 

To recreate locally:
1.) Add yourself and a few test users to a group chat using the rails console. 
2.) Open a few direct chats with the same test users added to the group chat.
3.) Click the group chat name to open side panel with details such as members of the group chat.
4.) Click any of those users but yourself and scroll down to see the block and report abuse buttons.
5.) Clicking report abuse with lead you to the webpage, but none of the prefilled info has the user in question but rather the direct link to the group chat. 
6.) If you return to connect, the user you reported is not blocked as well since the direct chat still loads.

Let me know if you have trouble recreating this here or reach out to me on [DEV Connect](https://dev.to/mariocsee).

**Comment by fusillicode** [comment]
Hi, I was able to reproduce the cited behavior and I would really love to work on this issue.

Unfortunately I didn't get what the actual behavior should be 😅

Right now it seems that a `FeedbackMessage` without any reference to the `offender` is created upon submitting the report abuse form.

If the `FeedbackMessage` should be indeed be linked to the `offender`, should the form be changed to make it explicit that the report is directed toward the `offender`?

If yes is there some kind of desiderata about the actual layout? 🤔

**Comment by fusillicode** [comment]
Hi, any news on this? 🤔

**Comment by mstruve** [comment]
This workflow has recently been updated so that the Report Abuse form is loaded within the chat window itself and contains the correct information. Please let us know if you are still experiencing issues. Thanks again for being apart of the Forem community!!!
