### ISSUE TITLE
Be able to set thumbnail/video image for Video Posts

### ISSUE THREAD

**Issue by omenking** [forem/forem#2494]
**Is your feature request related to a problem? Please describe.**

When you have a video post it always takes the first frame of a video.
So I have to edit the first frame to get what I want to appear. 
I always forget this and have reprocess my video just for DEV.to and re-upload.

![Screen Shot 2019-04-18 at 11 58 27 PM](https://user-images.githubusercontent.com/7776/56404694-1e712b80-6236-11e9-88be-55b4e14c8643.png)

**Describe the solution you'd like**
Be able to upload a thumbail/default image

**Describe alternatives you've considered**
Nada

**Additional context**
Nada

**Comment by rhymes** [comment]
Labeled this hard as I think it requires an "edit video" feature built from scratch (or added with a third party library) to be able to choose the initial frame

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here. 
 We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
