### ISSUE TITLE
Navbar overhangs input field on New Post page

### ISSUE THREAD

**Issue by TerabyteTiger** [forem/forem#2519]
**Describe the bug**
When on https://dev.to/new, if enough vertical space is occupied, you can use arrow keys to navigate cursor behind the navbar. 

**To Reproduce**

1. Go to https://dev.to/new
2. Add a few paragraphs of text (enough that you can scroll the "Title" input off the screen - Might I recommend https://www.lipsum.com/feed/html)
3. Scroll down as far as you can
4. click in the input and use the arrow keys to move cursor up and behind the navbar. 

**Expected behavior**
The navbar should not overlap the input box (and doesn't if page is refreshed without being saved). 

**Desktop (please complete the following information):**

- OS: Windows & Chrome OS
- Browser: Chrome
- Version: 73.0.3683.88 (Official Build) (64-bit) [Chromebook] -- Not sure on windows, but should be most recent version.

**Comment by Zhao-Andy** [comment]
Adding two gifs for each editor to depict what I think is the issue:
![gif example v1 editor](https://user-images.githubusercontent.com/17884966/56599733-2548c700-65c5-11e9-86a3-664a1ab50eac.gif)

![gif example v2 editor](https://user-images.githubusercontent.com/17884966/56599741-2aa61180-65c5-11e9-8d8a-ad2730c7e6fb.gif)

**Comment by kaushalgautam** [comment]
Hi Guys. Can you please provide some insight on how one might proceed on tackling this? I am interested!

**Comment by ajonp** [comment]
I believe this issue can be closed, the article content area is now a calculated value

```
height: calc( 100vh - var(--header-height) - var(--article-form-actions-height));
```

Therefore you never run into this issue.

@TerabyteTiger @Zhao-Andy can you confirm?

**Comment by rhymes** [comment]
cc our designer @ludwiczakpawel to confirm as well

**Comment by ludwiczakpawel** [comment]
Correct, we have redesigned this view couple months ago, this should no longer be an issue. I'm closing. Thanks!
