### ISSUE TITLE
Organization sidebar CTA may be cached incorrectly

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#2520]
As an organization, I can add a CTA to my sidebar. However, if I've previously published a post and I proceed to add a new CTA or update a previous one, it may not show up in my previous posts.

We might want something like:
```ruby
class OrganizationsController
   # ... etc code
  def update
    organization = Organization.find(params[:id])
    ActiveRecord::Base.transaction do
      organization.update(org_params) # etc etc
      cb = CacheBuster.new
      organization.articles.pluck(:path).each { |path| cb.bust(path) }
    end
  end
end
```

Or we could add `Rails.cache` timestamps to the organization sidebar.

**Comment by Zhao-Andy** [comment]
There was a strange edge case where the CTA was visible for some viewers but not all. Not sure how that could be. Might be a service worker caching issue or something else, but I think solving the caching issue with `CacheBuster` / Fastly should be sufficient.

**Comment by cmgorton** [comment]
Hey @Zhao-Andy , do you think this is a good issue to keep open or do you think this is something we can close now. It has been stale for over a year so want to double check. Thanks!
