### ISSUE TITLE
My Reading List Reminders

### ISSUE THREAD

**Issue by JRC86** [forem/forem#2547]
**Is your feature request related to a problem? Please describe.**
I love the idea of saving an article to read later, but the list grows fast and I can't keep up.
The reason for saving articles is because they are interesting and I might not have time to read it thoroughly at that moment.

**Describe the solution you'd like**
I reminder that works like a notification and asks me if I have (x minutes) free. Clicking on that reminder would take me to a saved article, with estimated reading time x minutes.
I do from time to time have x minutes, but I'd probably just save more articles to the list if manually visiting dev.to
**Describe alternatives you've considered**
Increase my self-discipline.

**Comment by jessleenyc** [comment]
Thanks for the feature request -- we really like this idea. Whoever wants to take this on: please leave more details on how you'd approach the UI and share any mockups so we're on the same page.

**Comment by cmgorton** [comment]
Hey all, this issue has gone stale. Since there has been no additional communication on this issue I am going to go a head and close it. 
If you think this will still be useful please feel free to reopen this feature request.
