### ISSUE TITLE
Please understand decentralized social networks, remove Mastodon whitelist (get Fediverse)

### ISSUE THREAD

**Issue by rugk** [forem/forem#2617]
**Describe the bug**
As [argued here](https://twitter.com/rugkme/status/1122908656482361350), you seem to whitelist Mastodon instances.

**To Reproduce**

1. Enter any not known Mastodon instance.

**Expected behavior**
It shoudl accept any Mastodon instance automatically. (if you want, verify via a ActivityPub request that it is Mastodon or so, but accept it.)

**Screenshots**

![grafik](https://user-images.githubusercontent.com/11966684/56913209-589dc100-6ab1-11e9-9f1d-3f556bfad793.png)

**Additional context**
Seriously, this is a **decentralized** network, thus any implementation of a whitelist is prone to fail.
And yes, it fails.

**Comment by jessleenyc** [comment]
For anyone who wants to take this on, we'll want a way to verify these mastodon links. Ideally we'll build this in a reuseable way so we have a general tool that scrapes other sites for link verification should that use case come up in the future.

**Comment by jessleenyc** [comment]
Hey all - we're going to move forward and update the UI to reflect 'fediverse' and allow all links. Eventually we'll want some way to verify these, which I've created a separate issue for: https://github.com/thepracticaldev/dev.to/issues/2830. Verification won't be a blocker though. This is approved if someone wants to work on it.
- update mastodon to fediverse
- add i.e. mastodon as a placeholder in the field
- remove whitelist to allow all links

**Comment by fluffy-critter** [comment]
The easy way to verify Mastodon instances is to issue a GET to /api/v1/instance and check the validity of the responses. That should also work for other Mastodon-like fediverse providers such as Pleroma.

**Comment by rugk** [comment]
@fluffy-critter exactly, I do use or for my Firefox add-on e.g.

https://addons.mozilla.org/firefox/addon/mastodon-simplified-federation/

**Comment by cmgorton** [comment]
Hey, I'm in the process of doing some Issue cleanup and since this has been inactive for over a year I am going close this. Feel free to open a new issue on this in the future if you think we should continue to consider it. Thanks.

**Comment by rugk** [comment]
Could you just reopen this? It’s still a valid issue.

**Comment by cmgorton** [comment]
Hey @rugk I am talking to the team to see if this is something we still plan to work on. Right now it doesn't look like it but I am waiting for more information on why we would or wouldn't. If I get the go ahead I will reopen this issue. Thanks.

**Comment by citizen428** [comment]
@rugk I already removed the whitelist as part of another PR a while ago, but there are some unrelated things holding it back. In a few more days the whitelist should be gone.
