### ISSUE TITLE
User's profile page includes posts from other users

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#2623]
**Describe the bug**
I clicked on the profile of one of my new followers to see their posts and noticed that only the first post was theirs.

**To Reproduce**
I'm not sure of the repro steps yet, but these are the steps I performed to get the error

1. From the main page, click on your notifications
2. Click on a follower in your recent followers
3. Notice on their profile page, that they have posts that weren't authored by them including their own posts at the beginning.

**Expected behavior**
A user's profile page should only show posts they wrote.

**Screenshots**
![wrong-feed-for-user-articles](https://user-images.githubusercontent.com/833231/56934701-02358000-6abb-11e9-9510-d25093f2cfa5.gif)

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.4
- Browser: Firefox 
- Version: 66.0.3

**Additional context**
One thing I noticed as you'll see in my screen capture is at the end I refresh the page and it's fine. So this appears to be a potential caching issue.

**Comment by tannakartikey** [comment]
@jessleenyc I'd like to help with this one

**Comment by jessleenyc** [comment]
We've seen this a few times before - I think it has something to do with caching/indexing not updating properly. Hard to reproduce. @tannakartikey if you make any headway please keep us posted!

**Comment by mstruve** [comment]
Recently confirmed that this has been fixed!
