### ISSUE TITLE
Delay save button hover transition after click

### ISSUE THREAD

**Issue by rhymes** [forem/forem#2670]
**Describe the bug**

At present, when the `SAVE` button is clicked, the `hover` effect starts immediately, which visually makes the button text seemingly transition from `SAVE` to `SAVED` to `UNSAVE` in a few milliseconds.

It's not a big deal but it looks like a weird UI quirk in some cases. 

**To Reproduce**

1. Go to 'https://dev.to/'
2. Click on 'SAVE' on any article
4. See quirk

**Expected behavior**

It would be nicer if the hover effect was triggered with a delay, either via CSS or via JavaScript

**Screenshots**

![before](https://user-images.githubusercontent.com/146201/57073187-9e8c9c00-6ce0-11e9-9a6f-46ed87eadae5.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox
- Version: 67.0b16

**Additional context**

I've found an example Codepen that shows how CSS transitions can be used to delay the hover effect when CSS `content` is involved: https://codepen.io/ironion/pen/WQbjPR

See also https://github.com/thepracticaldev/dev.to/pull/2653 and https://github.com/thepracticaldev/dev.to/pull/2597

**Comment by hcarnes** [comment]
Hi! I would like to work on this.

**Comment by ganeshraja10** [comment]
@hcarnes are you working on this issue? if not, I'd like to take this one

**Comment by hcarnes** [comment]
@ganeshraja10 I haven't been able to carve out time for this yet - please go ahead!

**Comment by ganeshraja10** [comment]
@hcarnes Thanks.

**Comment by rhymes** [comment]
Not even valid anymore
