### ISSUE TITLE
Android Firefox PWA is redirecting me to a weird website when I first open it

### ISSUE THREAD

**Issue by corjohnson** [forem/forem#2758]
**Describe the bug**
I use Firefox as my primary browser on my phone, and when I added dev.to to my home screen, it mostly works fine. However when I open the PWA from my phone, oftentimes I'll immediately get redirected to 

```
https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-71991109-1&cid=1041080169.1555458052&jid=1787368665&_gid=1947976608.1557160025&gjid=2036079894&_v=j73&z=1980226023
```

I've tried removing the pwa from my home screen and re-adding it, but it doesn't seem to make a difference. I'm also logged in, but I don't know if that'd make a difference. After I go back from this redirect I can use the PWA just fine. 

**To Reproduce**

1. Add the PWA to your home screen 
2. Open the PWA
3. If you have not opened it in a while, it will redirect to the aforementioned location

**Expected behavior**
I just view the home screen

**Screenshots**
![Screenshot_20190507-152343](https://user-images.githubusercontent.com/8900567/57336920-789a3980-70dc-11e9-93a9-97fa14ad7a7f.jpg)

**Smartphone (please complete the following information):**

- Device: OnePlus5T
- OS: Android 9.0
- Browser: Firefox
- Version 66.0.5

**Comment by Zhao-Andy** [comment]
Thanks for reporting this. I think this happens because we use Google Analytics, and the Firefox PWA must be sending the response from Google when it shouldn’t.

**Comment by jessleenyc** [comment]
@corjohnson just wanted to let you know we also have an Android app in case this issue keeps happening to you on the PWA. https://play.google.com/store/apps/details?id=to.dev.dev_android

**Comment by cmgorton** [comment]
Hey @corjohnson Do you know if this is still an issue?

**Comment by joshpuetz** [comment]
Pinging @fdoxyz to see if he can replicate this: I only have access to the Android emulator at the moment.

**Comment by corjohnson** [comment]
Just tried on my phone and it's not reproducible. So I'm tempted to say it's been fixed 😊

**Comment by fdoxyz** [comment]
Thanks for helping us confirm this @corjohnson! I can't reproduce myself either (with Chrome in the PWA) so I'd say it's no longer an issue.
