### ISSUE TITLE
Version control for pages

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#2836]
**Is your feature request related to a problem? Please describe.**
Add version control or a diffing system for new pages. We'll eventually want to do this for articles and potentially other areas with markdown but let's start with pages first.

**Describe the solution you'd like**
There should be some gems out there that can help with this.

**Comment by KDRaypole** [comment]
We could use paper_trail. It's actively maintained and has tons of cool features!

**Comment by rhymes** [comment]
There's also [audited](https://github.com/collectiveidea/audited) which is smaller in scope than papertrail

**Comment by cmgorton** [comment]
@jessleenyc do you think this should still be an open feature request? There hasn't been any activity on it for almost a year. 
If so I will add it to the feature backlog board :)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

For anyone interested in this feature you can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
