### ISSUE TITLE
Can no longer paste emojis when writing from desktop

### ISSUE THREAD

**Issue by ashleemboyer** [forem/forem#2850]
**Describe the bug**
I used to be able to copy emojis from Emojipedia, but they don't paste the same as they used to.

**To Reproduce**

1. Go to [https://emojipedia.org/white-smiling-face/](https://emojipedia.org/white-smiling-face/)
2. Click on the "Copy" button to the right of "Copy and paste this emoji"
3. Go back to the editor in dev.to
4. Try to paste the emoji
5. See what looks like the `U+263A` unicode smiley rather than the "prettier" one

**Screenshot**
Here's what the pasted emojis look like in the editor.

![image](https://user-images.githubusercontent.com/43934258/57815795-ea126180-7746-11e9-92fb-7fe332ad6813.png)

**Desktop**

- OS: Ubuntu 18.04
- Browser: Chrome
- Version: 73

**Comment by aspittel** [comment]
Hey @ashleemboyer thanks for reporting this! We'll take a look at it and get back to you soon!

**Comment by ashleemboyer** [comment]
Weird! Some emojis work, like this one: 😈

**Comment by sleepyfran** [comment]
I can't reproduce it in Safari or Chrome on macOS, maybe it's an Ubuntu issue?

**Comment by jessleenyc** [comment]
@ashleemboyer are you still experiencing this?

**Comment by ashleemboyer** [comment]
@jessleenyc sorry about the delay, I tried it and I am still getting the same issue.

**Comment by jessleenyc** [comment]
@ashleemboyer to clarify, this is only happening to you on dev.to? Where some emojis can paste while other's can't?

**Comment by cmgorton** [comment]
Hey we are working on cleaning up open issues that are stale. Since this has been inactive for over a year I am going to go a head and close this issue. If you are still experiencing this and want to continue a discussion on it please feel free to open an issue again. Thank you!
