### ISSUE TITLE
Reading List: add an option to "unsave" without having to open the article

### ISSUE THREAD

**Issue by giventofly** [forem/forem#2853]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dlionz** [comment]
Hey @giventofly I believe if you press the "archive" button on the bottom left of the card it will remove the list item. I do think the rad time would be a nice to have.

<img width="1009" alt="Screen Shot 2019-05-16 at 2 55 04 PM" src="https://user-images.githubusercontent.com/14165549/57889847-c30d6b80-77ea-11e9-953f-a1d434f0d538.png">

**Comment by giventofly** [comment]
Archive moves the item to the archive, I want to remove from the reading list entirely and not to a "read later"

**Comment by rhymes** [comment]
@giventofly FYI: I've clarified a bit your request in the title, can you kindly open a separate issue for the reading time indication? Thank you!

**Comment by giventofly** [comment]
Sure

**Comment by aspittel** [comment]
Hey @giventofly thanks for this feature request - we'll discuss and then get back to you soon!

**Comment by jessleenyc** [comment]
We haven't reached a consensus on this with the team and are going to give it some more thought. Thanks again for the request.

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. If this is a discussion you think is still valuable please feel free to open a new issue. Thanks.
