### ISSUE TITLE
Upgrade Rails to 6.0

### ISSUE THREAD

**Issue by tannakartikey** [forem/forem#2879]
**Is your feature request related to a problem? Please describe.**
The Rails 6.0 rc1 is [released](https://weblog.rubyonrails.org/2019/4/24/Rails-6-0-rc1-released/). Although it's not a final release, companies like Shopify and Github are already using it. So, we can at least start with creating the list of the tasks required to achieve the successful upgrade.

**Describe the solution you'd like**
Start slowly with the list of the things might need to change and keep working on them until the stable version is released.

**Comment by rhymes** [comment]
Hi @tannakartikey that's quick! :-) I know me and other DEVers (is DEVer a thing? ahhaa) have been keeping an eye on Rails 6 for one or another reason.

There's a lot of cool stuff (Action Mailbox, multi DB and parallel testing for example). I'm a bit bummed that Action Text (Trix) does not support Markdown but hey, maybe in the future. I'm also excited for the new autoloader to be honest :D 

Though I think the plan is to wait a bit mostly because a lot of gems take time to be upgraded I can't see why you shouldn't start making a "shopping list". Have you tried to run the code locally on Rails 6.0 rc1?

What happens if you follow the [official upgrade guide](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0) ?

**Comment by rhymes** [comment]
One thing I'd like to see happen before an eventual move to Rails 6 is a migration towards Webpack 4 (see #2034) and towards [Active Storage](https://guides.rubyonrails.org/active_storage_overview.html) which supports file and cloud storage and direct uploads to the cloud.

The migration to Webpack 4 would generate better JS chunks and open up Babel 7 to us.

Active Storage contains a lot of neat features and allow us to remove Carrierwave and the [s3_direct_upload](https://rubygems.org/gems/s3_direct_upload) that's been unmaintained for 5 years and depends on jQuery:

https://github.com/thepracticaldev/dev.to/blob/c9116f6d4ddaa0ef235fcd8f6b9bc060c137b0a6/Gemfile.lock#L659-L663

**Comment by rhymes** [comment]
This is a really good resource about neat things in Rails 6: 

[Rails 6: B-Sides and Rarities](https://evilmartians.com/chronicles/rails-6-b-sides-and-rarities)

My favorite things about Rails 6:

* multi DB support and parallel testing
* bulk inserts and upserts (!!)
* this feature about Active Job jobs:

> A new timestamp field, enqueued_at to indicate the time the job has been enqueued. That allows to measure a very important performance characteristic–how long did the job has been waiting in a queue before the execution started?

Basically you can easily track how efficient is the queue and if you have enough workers for your workload. So cool :-)

**Comment by tannakartikey** [comment]
@rhymes we can start with ActiveStorage meanwhile the work on #2034 is finished.
Right now upgrade to Rails 6 just shows a bunch of dependencies which has to be taken care of. So, it will give us some time and to those gems, we are using to catch up with Rails 6, as you suggested earlier.

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by rhymes** [comment]
@tannakartikey after we've upgraded fastly-ruby and verified everything works maybe we can synchronize of the path to Rails 6, if nothing special is required on our side, we'd be happy to have you submit the "upgrade to Rails 6 PR" :)

**Comment by tannakartikey** [comment]
@rhymes sounds good. I understand if you have to keep it reserved for the DEV team.

**Comment by etagwerker** [comment]
@tannakartikey @rhymes I went ahead and submitted a PR to find out how many failures we will find running the test suite with Rails 6.0.

**Comment by etagwerker** [comment]
Quick update from Travis CI (https://travis-ci.com/github/thepracticaldev/dev.to/jobs/326724424): 

```
Finished in 15 minutes 48 seconds (files took 8.18 seconds to load)
4,658 examples, 31 failures, 4 pending
```

**Comment by rhymes** [comment]
Closed for quite some time :D
