### ISSUE TITLE
Add more stats to user profile/author box

### ISSUE THREAD

**Issue by vnbrs** [forem/forem#2902]
**Is your feature request related to a problem? Please describe.**
A pinch of gamification is something really important when talking about community engagement. And dev.to is doing well! We have reactions (hearts, unicorns and tags) and badges. That is important to engage people into writing more, and even (w/ badges) contributing to the dev.to codebase.

**Describe the solution you'd like**
To engage people even more, adding more stats to the user profile and the post author box would be great. I was thinking about:

* Reactions given - how many reactions the user has given to other posts
* Reactions received - how many reactions the user posts have received
* Most read posts - a list of the user top posts

Just by having reactions given/received, people would be engaged not just into writing more, but reacting more. Just like YouTube, there are videos that we watch and like, but forgot to "smash" that like button.

**Comment by docljn** [comment]
I have one concern around this: would it not encourage people to post more contentious/deliberately provocative content in an effort to get more of a reaction from the audience?

**Comment by Almenon** [comment]
> would it not encourage people to post more contentious/deliberately provocative content in an effort to get more of a reaction from the audience?

That's always a temptation, even without stats.

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. If this is a discussion you think is still valuable please feel free to open a new issue. Thanks.
