### ISSUE TITLE
Change video player

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#2911]
We currently use JWPlayer for video, which is solid, but I think it would be nice to switch to something open source and possibly more extensible.

Here's one that seems to fit the bill in terms of the hls we use:

https://github.com/video-dev/hls.js/

One big motivation for me wanting to make this fix is that the `playsinline` functionality is needed for the proper experience within the iPhone app webview and I can't figure out how to do it in JWPlayer.

## Implementation:

All the functionality and scripts live in the `_video_player.html.erb` file. If we're going to import a different library, we should create a pack and then include it in the file like such:

`<%= javascript_pack_tag "videoplayer", defer: true %>`

**Comment by bdougherty** [comment]
I highly recommend [sampotts/plyr](https://github.com/sampotts/plyr). It supports hls.js.

**Comment by jessleenyc** [comment]
@benhalpern a note that we should provide some video files and instructions on how to work on this locally.

**Comment by spences10** [comment]
Do you know if either support [`.mkv`]? A container format for video and audio.

[`.mkv`]: https://www.howtogeek.com/200736/what-is-an-mkv-file-and-how-do-you-play-them/

**Comment by allanwhite** [comment]
A "Dev.to Guide to Encoding & Uploading Video" could include helpful things like encoding specs, output settings files for common encoders or video services (Adobe Media Encoder, FFMPEG, etc) and other tips on working with entries (I'm new and not sure how to create video posts). 

That might also decrease the server load if the videos don't have to be re-encoded (or at least, as many bitrates/sizes). 

I'm curious @benhalpern, what's the rationale for managing (hosting, processing, etc.) video at all, versus simply offering an embed field? I can think of some (faster load time, fewer third-party scripts, more unified UX, etc), just wondering how you arrived at that decision.

**Comment by cmgorton** [comment]
This issue has gone pretty stale and I do not think this is a feature we plan to work on any time soon. I am going to go a head and close this issue. Thanks.
