### ISSUE TITLE
Error when Writing a post with "data:text/html" in it

### ISSUE THREAD

**Issue by washingtonsteven** [forem/forem#2924]
**Describe the bug**
When creating a post, if the body of the post has the text "data:text/html" in it, the post fails to save. This is mitigated by anything breaking up that text ("data:text\/html", "data :text/html", etc.)

**To Reproduce**

1. Go to https://dev.to/new
2. Enter "data:text/html" in the body of the text
3. Attempt to save, view error.
4. Break up the text (as noted above)
5. Attempt to save, view success

**Expected behavior**
The text is allowed to have "data:text/html" in it

In my particular case, I want to show up a data URL for creating a blank, editable HTML page.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.14.4
- Browser: Chrome  74.0.3729.157

**Comment by rhymes** [comment]
Hi @washingtonsteven, that shouldn't happen, we're working on more explanatory error message to be shown in the editor, thank you for the bug report!

**Comment by washingtonsteven** [comment]
Thanks! If you're updating the messaging, does that mean that I still won't be able to publish a post with the text "data:text/html" in it? If so I will rewrite instead of waiting for the PR to be accepted.

**Comment by rhymes** [comment]
@washingtonsteven no sorry you won't be able to, we should probably think of a way to make that possible, at least if contained in backticks, like `data:text/html`. In the meantime you can put a space between `data:` and `text/html`, I know... it's ugly.

I'll keep this issue open to come up with a better solution in the future

Thank you again!

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. If this is a discussion you think is still valuable please feel free to open a new issue. Thanks!
