### ISSUE TITLE
Modify the experience of Draft sharing

### ISSUE THREAD

**Issue by ItsASine** [forem/forem#2940]
**Is your feature request related to a problem? Please describe.**
The only true problem I have is if someone shares with me their in-progress post, the header is still there. Selecting the button to edit the draft (because why not, it's there :P) causes an error (404 iirc). Attempting to comment on a draft share also results in an error, though that doesn't result in a redirect to the 404 page. 

**Describe the solution you'd like**
Enhance the sharing features of in-progress articles. Maybe I could have edited his markdown for him instead of having to say on Slack to use JS formatting (I mean, the button was there). Or maybe I could have commented on the article with suggestions that wouldn't have shown on the final publish (or showed as "beta" comments). 

**Describe alternatives you've considered**
Alternatively, discourage sharing of the draft link. Right now it says to share at your discretion but having a shared link is kind of crappy. My coworker just had the "luck" of sharing it to someone who uses dev.to often. 

**Additional context**
🎉 This isn't truly important; I just wanted to open the issue so it would be on the radar as a someone annoying instance of user experience. I doubt many people share in-progress posts enough for many people to have run into the errors that I did.

**Comment by cmgorton** [comment]
Thanks for adding this feature request. We feel like this is an issue that sits in a larger conversation about multi user editing experience and we don't currently have this on the roadmap for features. Since this has gone stale I am going to go a head and close this issue.
