### ISSUE TITLE
Allow users to add links in the projects and hacks section on the profile

### ISSUE THREAD

**Issue by FarazPatankar** [forem/forem#2943]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could add links to our projects in the `projects and hacks` section on the profile.

**Describe the solution you'd like**
I guess I mentioned the solution in the problem section itself so I'll use this space to discuss possible implementations.
- One way would be to allow Markdown in there so the users can easily create links.
- Another way would be to create a Project(?) model with a name and a url field so the users can properly link to their projects. I think this would be amazing as we could eventually add a description and even give this section its own page that the members can use to interact with each other and talk about their projects. It may even lead to our members building/improving projects together.

**Describe alternatives you've considered**
I tried to add the link itself and also tried writing Markdown but none of the methods seemed to work. Did I miss something?

**Additional context**
<img width="297" alt="Screenshot 2019-05-23 at 2 52 02 PM" src="https://user-images.githubusercontent.com/10681116/58252740-7d631c80-7d6f-11e9-9ea8-22dc3cbaca6a.png">

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. If this is a discussion you think is still valuable please feel free to open a new issue. Thanks!
