### ISSUE TITLE
Listings creation (and update) API

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#2951]
Similar to the new beta [articles API](https://dev.to/api), we should have something similar for listings.

It's a matter of creating a `listings_controller` in the API subdirectory and following the same user authentication practice we use for `articles_controller`.

I think we can copy the logic over from the current controller, ideally unifying it in `Creator` and `Updater`-type object.

I put update in parentheses in the title because create is probably the most important, but both endpoints would be ideal IMO.

**Comment by cyrillefr** [comment]
Hello @benhalpern , I'd like to work on this issue.

**Comment by maestromac** [comment]
go ahead @cyrillefr !

**Comment by cyrillefr** [comment]
Hello, anyone to help me with the following ?
I am implementing the api/listings with existing code in app/controllers/classified_listings_controller.rb
I have noticed that in create and in update method, there is a difference to figure if there is enough credit to proceed.

For the create part, there is a some org available credit, but not for the update part.
Is this intended ? I could refactor if in both 2 methods, credit available is the same.

Thanks.

@benhalpern @rhymes

**Comment by jessleenyc** [comment]
@cyrillefr I think the issue your describing has since been resolved. @mariocsee can help if it's not/if you have more questions!

**Comment by mariocsee** [comment]
Hey @cyrillefr, @rhymes opened an issue regarding that credit check and I submitted a PR for it that got merged. Feel free to ask me any questions re: listings! 

(I'm currently working on a PR for listing drafts, deletion and more dashboard controls, so there will be some new changes coming to `classified_listings_controller.rb`.)

**Comment by cyrillefr** [comment]
Hello, @jessleenyc , @mariocsee .
Thank you for the update, I think I have spotted the changes (including this one #3645 if I am correct).
I will return to this issue soon

**Comment by cyrillefr** [comment]
Hello, I did not forgot about this. I am planning to commit in a couple of days.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
