### ISSUE TITLE
Twitter polls

### ISSUE THREAD

**Issue by Glennmen** [forem/forem#2955]
**Is your feature request related to a problem? Please describe.**
Currently the Twitter liquid tag doesn't include polls.
I went through the [Twitter API docs](https://developer.twitter.com/en/docs/tweets/enrichments/overview/poll-metadata) and it seems that Twitter does return poll metadata in entities. I tried working on it myself but it seems that the free dev API doesn't return poll metadata.

Does the API that DEV uses return this data? I assume that you have a premium account. 

**Describe the solution you'd like**
Show (at least) poll options.

**Describe alternatives you've considered**
Tried working on it myself but couldn't get poll data from the free api.

**Additional context**
https://developer.twitter.com/en/docs/tweets/enrichments/overview/poll-metadata
https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#polls

**Comment by abraham** [comment]
Ya, the Twitter API only returns poll info for clients with Enterprise level access and even then it only includes the options, not the vote counts.

**Comment by jessleenyc** [comment]
I'm pretty sure we don't have a premium account, either...will look into this.

**Comment by abraham** [comment]
Twitter Labs is testing some new API formats that include poll data. Once those are finished polls will be possible to get. https://developer.twitter.com/en/docs/labs/tweets-and-users/api-reference/get-tweets-v1.html

**Comment by rhymes** [comment]
It looks like it can be done now https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#polls

**Comment by rhymes** [comment]
Never mind, I tried for a bit with the [twitter ruby gem](https://github.com/sferik/twitter) but I can't get polls:

```ruby
 tweet = tc.status("1250896975391752195", include_entities: true)
```

but there's no trace of polls. 

The documentation isn't very clear about what is part of not part of the enterprise offer...

I also tried to "hijack" the library with but I get a forbidden error (probably because Labs is opt in)

```ruby
[86] pry(main)> tc.send(:perform_get_with_object, "/labs/1/tweets?ids=1250896975391752195", {}, Twitter::Tweet)
Twitter::Error::Forbidden: Twitter::Error::Forbidden
from /Users/rhymes/.gem/ruby/2.7.1/gems/twitter-7.0.0/lib/twitter/rest/request.rb:97:in `fail_or_return_response_body'
```

All of this to say... well, we can't add polls yet :D

**Comment by abraham** [comment]
It looks like poll data is in the Labs API endpoint.

- https://developer.twitter.com/en/labs
- https://developer.twitter.com/en/docs/labs/tweets-and-users/api-reference/get-tweets-id

**Comment by rhymes** [comment]
I tried again with the new endpoint, still got Forbidden:

```ruby
[16] pry(main)> tc.send(:perform_get_with_object, "/labs/2/tweets/1250896975391752195", {}, Twitter::Tweet)
Twitter::Error::Forbidden: Twitter::Error::Forbidden
from /Users/rhymes/.gem/ruby/2.7.1/gems/twitter-7.0.0/lib/twitter/rest/request.rb:97:in `fail_or_return_response_body'
```

Maybe they have to enable you to be able to use the labs. 🤷‍♂️

**Comment by abraham** [comment]
I believe you have to join Labs and then activate the specific lab you are interested in.

https://developer.twitter.com/en/account/labs

**Comment by rhymes** [comment]
Thanks @abraham! This then has a weird interaction with how we fetch statuses which is tied to the authentication system (we're in the process of separating the two), hence we'll get there and eventually implement polls. 

Marking this as DEV Team
