### ISSUE TITLE
Font size is too big on mobile site in Chrome for Android

### ISSUE THREAD

**Issue by unixnut** [forem/forem#2960]
I created an account and logged in but there is no control for this in the settings.

**Comment by jessleenyc** [comment]
This is approved for anyone who wants to work on it. You should be able to follow the pattern we currently use for user configurations but let us know if you have any questions!+

**Comment by NikoLewis** [comment]
I'd like to give this a shot :).

**Comment by maryam-b** [comment]
@unixnut  font for each part is big? would it be great if you can post a screenshot cause I assumed that you mean the article's font and when I checked it on Android it was not too big at least for me :) so I like to know how does it look like on your test device.
@jessleenyc I'm checking your current pattern for `theme` and `font` and I assume that when you are suggesting to follow that pattern follow those configs. In current pattern on this class `body.comic-sans-article-body` the attribute font applied only on paragraph, so these font settings should be only applicable on paragraph?
And which format should it be? I mean would it be okay to use `small, medium, large` or should be number?

**Comment by maestromac** [comment]
Yes @maryam-b , that's exactly what Jess is referring to. 

While having the options of small, medium, and large is the right idea, I wonder if we should leave this functionality to the browser. I believe all (mobile) browser provide some kind of text scaling feature and they do store preference per site.

**Comment by maryam-b** [comment]
@maestromac if we go with giving the responsibility with the browser then it won't be user based setting, so then I assume adding a configuration for `font-size` won't be necessary anymore. Am I right or I missed what you've meant?

**Comment by maestromac** [comment]
Yes, I was thinking out loud and questioning the usefulness of this feature. 

Our team decided that we want to offer our users font size option build-in to the web app. These config can be first applied to the article's texts and comment's text. Other area of the app will be trickier to get right and can be implemented afterward.

**Comment by neilmayhew** [comment]
This is needed on desktop too, so please change the issue title to make it more general

**Comment by jean** [comment]
> This is needed on desktop too, so please change the issue title to make it more general

Came here to say this. 
At 150% zoom, HackerNews shows 15 items on a screen.
At 90% zoom, dev.to shows 3 or 4 items.
There are three crowded columns, and two wide borders on either side (looks like about 20cm worth of borders).

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for a little while and issue #6764 is similar to this but more descriptive I am going to go a head and close this. Thanks.
