### ISSUE TITLE
Markdown Source Link

### ISSUE THREAD

**Issue by rognoni** [forem/forem#2963]
Expose the markdown files used to build posts and articles.

Could we add a **source link** between Github link and the date info?

![markdown_source](https://user-images.githubusercontent.com/8401602/58385253-b14b7580-7fed-11e9-8d13-c66a15caf4c0.png)

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. If this is a discussion you think is still valuable please feel free to open a new issue. Thanks.
