### ISSUE TITLE
Liquid syntax error in comments returning 500 without a proper message

### ISSUE THREAD

**Issue by mkrl** [forem/forem#2964]
Whenever there is an inappropriate liquid tag in a comment you are trying to post, you get no proper error message upon submitting. 

**To Reproduce**

1. Go to any DEV post
2. Type in any invalid liquid tag starting with `{%` 
3. Click on "Submit"
4. It now looks like it's just taking a while to deliver your request to the server, but it actually already got a 500 back, However, if you click on "Preview", you can see the error message you are supposed to get straight away.

**Expected behavior**

A clear visual clue on what's wrong with the comment instead of "infinite loading".

**Screenshots**

![chrome dev tools log](https://i.imgur.com/IYxUENP.png)

![chrome dev tools log](https://i.imgur.com/sq3cyqi.png)

Clear Linux, Firefox 67.0
Debian, Chromium 73.0

**Comment by jrsam** [comment]
Hi, I would like to work on this. Can we show the same visual clue as the one shown after clicking Preview button? 

![Image of Yaktocat](https://camo.githubusercontent.com/0aad89d0af8807317596c0098b8cfbd2bcbf4773/68747470733a2f2f692e696d6775722e636f6d2f737133637971692e706e67)

**Comment by maestromac** [comment]
Hello @jrsam , yeah the visual can based it off the preview failures and it should allow user to edit the message afterward.

What I mean by that is, with preview button you can click it again to go back to the markdown. The same needs to be possible with submitting.

**Comment by jrsam** [comment]
Thanks @maestromac.

**Comment by cmgorton** [comment]
This appears to be fixed. I can add an invalid liquid tag on a comment and get an error message both in preview and when I submit. 

If this is still persisting let me know and I can reopen this issue. Thanks!
