### ISSUE TITLE
Auto Approve Posts Imported through RSS

### ISSUE THREAD

**Issue by CalvinAllen** [forem/forem#2984]
**Is your feature request related to a problem? Please describe.**
Ive already done the legwork to publish the posts I imported from my blog initially, but now with every single new post, I still need to esit the draft in dev.to, and mark it as published.

**Describe the solution you'd like**
I would love to set it up so any new posts made to my blog, and imported through RSS, are automatically set to published.  I'd prefer an automated solution, but barring that, some way of knowing when the post has been imported (email, etc) and being able to reply with "publish" would be nice.  Not having the reply functionality, I would like a simple button click to publish instead of editing the liquid tag.

**Describe alternatives you've considered**
None?

**Additional context**
I understand why you wouldnt necessarily want this for the initial import, as I've left some of those unpublished, but with that out of the way with one-off blog posts here and there, I'd like to not worry about remembering to come back and publish them, especially since there is a slight delay from me publishing on my blog, until it surfaces in dev.to.

**Comment by jessleenyc** [comment]
@pkfrank I feel like you'll have some additional thoughts here as it relates to an email flow.

**Comment by pkfrank** [comment]
@jessleenyc @CalvinAllen 

I think a pretty solid experience would be to add a checkbox on the `/settings/publishing-from-rss` that allows the member to "receive an email when new drafts are imported."

At that point, the notification email can either "just" be a link to the draft (where the author would adjust the Front Matter), or we could potentially build a button into the email that automatically flips `published:false` to `published:true.`  We'd need to scope out the technical requirements of that option (authorization, etc).

Going one step further, we could add an additional checkbox on the RSS page to "automatically publish imported posts."

Before providing that automatic publish option, we'd need a clear policy about how to manage automatically-published posts if they have clear issues.   Sometimes there is some last-mile maintenance required to clean up tags, small formatting issues, stuff like that, and we'd want to avoid confusion about how we deal with those issues.

**Comment by CalvinAllen** [comment]
@pkfrank @jessleenyc Another, albeit perhaps strange implementation, would be to check the incoming post for some "dev to" meta tag.  I use Jekyll for my blog, so it would be "easy" to add another front matter tag that outputs the proper format for dev.to to latch onto during the import process.

I don't know whether its because I already use Jekyll / markdown / front matter / etc., but I have had zero import issues, which means no last-mile maintenance for me, but I do understand the need to support a potentially unlimited number of blogging platforms (that could potentially do weird stuff :))

**Comment by jessleenyc** [comment]
Spoke with the team! We have hesitations about an auto publish feature but definitely agree that we need to find ways to make it easier for people to publish. To start, we should send an email once a new draft is pulled in from RSS. The email can embed multiple links: link to preview, edit, etc. Maybe even one to publish directly.

We'll want to make sure this email doesn't get sent for the current backlog but we can send all exiting RSS users an email about the new feature for them to opt-in.

Another thing to consider - we probably don't want to send a bunch of emails if someone is adding their RSS feed _for the first time_ and it pulls in a bunch all at once. We'll also want these emails to be opt-in so that'll need to be added to the settings.

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. If this is a discussion you think is still valuable please feel free to open a new issue. Thanks.
