### ISSUE TITLE
Add ability to sort comments by most recent

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#3001]
**Is your feature request related to a problem? Please describe.**
As a DEV commenter and thread watcher, I want to be able to more easily track new comments directly on the thread as they come in.

**Describe the solution you'd like**
An option at the top of the comment section that allows me to sort by newest.

**Additional context**
- For the scope of this request, I don't think we need to consider anything but top-level comments.

- This will make tracking super long threads, such as the Welcome thread, much easier.

**Comment by matisnape** [comment]
@pkfrank this is about /notifications/comments ?

**Comment by rhymes** [comment]
Hi @matisnape, this is about the comments under an article, and possibly the `/comments` under the article URL, for example https://dev.to/jess/what-was-your-win-this-week-dch#comments and https://dev.to/jess/what-was-your-win-this-week-dch/comments

**Comment by matisnape** [comment]
Taking this, btw @jessleenc :)

**Comment by Ridhwana** [comment]
@ludwiczakpawel and @lisasy can you weigh in on the visual/product aspect of this?

**Comment by ludwiczakpawel** [comment]
@Ridhwana this seems to be pretty outdated (1y old issue) - is this something we still need/want?

**Comment by pkfrank** [comment]
@ludwiczakpawel multiple Forem admins have raised this recently.

I also personally feel like this will make "following along" in the Forem.team threads a lot easier (as we can go by chronological order).

**Comment by ludwiczakpawel** [comment]
Okey, cool. I think there should be 3 levels of setting this up:

1. **Admin** - admin of a community should have a setting somewhere to set default sorting for their community comments.
2. **User settings** - user should be able to set/overwrite default sorting for comments. I believe this should live under `/setting/ux`
  ![image](https://user-images.githubusercontent.com/108287/97966439-21058880-1dbc-11eb-9e8d-3a8465d98722.png)
3. **Per post** - user should be able to overwrite his own preference for particular post only... So imagine, all comments are sorted by "likes" (or whatever is the current cirteria). If user decides to sort comments under **one particular post** by "latest", they should be able to do so. This setting should/could be _ephemeral_ - meaning, it can return to default sorting when you end a session or something.
  ![image](https://user-images.githubusercontent.com/108287/97968996-af2f3e00-1dbf-11eb-8622-9fae03773114.png)

**Comment by lisasy** [comment]
> Okey, cool. I think there should be 3 levels of setting this up:
> 
>     1. **Admin** - admin of a community should have a setting somewhere to set default sorting for their community comments.
> 
>     2. **User settings** - user should be able to set/overwrite default sorting for comments. I believe this should live under `/setting/ux`
>        ![image](https://user-images.githubusercontent.com/108287/97966439-21058880-1dbc-11eb-9e8d-3a8465d98722.png)
> 
>     3. **Per post** - user should be able to overwrite his own preference for particular post only... So imagine, all comments are sorted by "likes" (or whatever is the current cirteria). If user decides to sort comments under **one particular post** by "latest", they should be able to do so. This setting should/could be _ephemeral_ - meaning, it can return to default sorting when you end a session or something.
>        ![image](https://user-images.githubusercontent.com/108287/97968996-af2f3e00-1dbf-11eb-8622-9fae03773114.png)

I like these solutions! They look good to me, and I'd recommend content changes to make this clearer.

### Per post - dropdown

#### Sort by:
##### Most popular

**Comment by ludwiczakpawel** [comment]
Yeap, I'm all in for content updates and having the same language in Settings too. 

Something to clarify though is figuring out what actually is the criteria for "Top comments" since "most upvoted and relevant comments" label was something I made up..

**Comment by Ridhwana** [comment]
@ludwiczakpawel this sounds pretty good, and we can probably implement it incrementally in 3 phases if we realize that makes the most sense. So to confirm,  do we see the sorting options to be:

-  Top
-  Latest
- Oldest

across all the admin, profile settings and post?

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
