### ISSUE TITLE
Profile image for comments don't all update

### ISSUE THREAD

**Issue by JohnPhamous** [forem/forem#3008]
**Describe the bug**
When a user creates a comment, then changes their profile image, and makes subsequent comments, the old profile image is still shown on the old comments while the new comments reflect the new profile image.

**To Reproduce**
1. Make a comment
2. Change your profile image
3. Make a comment

Your first comment would have your old profile image and your second comment would have your new profile image.

**Expected behavior**
Profile image across old/new comments should be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/16027268/58661903-d980f000-82dd-11e9-8104-3ccb043424d3.png)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Firefox 
- Version: 68.0b5 

**Additional context**

- Cleared cache
- Tried on new browser instance
- Tested on desktop and mobile

**Comment by aspittel** [comment]
Hey @JohnPhamous, thanks for flagging this! We'll take a look and get back to you.

**Comment by akanshgulati** [comment]
@aspittel  can I try to debug this issue and fix it?

**Comment by jessleenyc** [comment]
@JohnPhamous do you know if the profile image ever updated? Am wondering if this is delayed or if the cache just never cleared.

**Comment by JohnPhamous** [comment]
@jessleenyc Doesn't look like it from my end, this is the post with the bug: https://dev.to/johnphamous/what-it-s-like-working-at-nasa-jet-propulsion-laboratory-2eln

**Comment by cmgorton** [comment]
@JohnPhamous this looks like it is fixed now. I am going to go a head and close this issue. If you still experience this bug let me know and I will open it back up! Thanks.
