### ISSUE TITLE
Perl6 syntax highlighter

### ISSUE THREAD

**Issue by melezhik** [forem/forem#3009]
**Is your feature request related to a problem? Please describe.**
I'd like to highlight Perl6 code snippets in my posts. Perl syntax highlighter relates to Perl5 which differs from Perl6 syntactically, so not the best solution.  

**Describe the solution you'd like**
Implement new syntax highlighter, which I can use in markdown like:

```
```perl6

# my Perl6 code here 
for i -> @foo {
  say $i
}
```

**Describe alternatives you've considered**
Perl highlighter , but it's not best solution imho

**Comment by aspittel** [comment]
Hey @melezhik, thanks for reporting this! I'm pretty sure we use a library for this. Will look into it more and get back to you!

**Comment by maestromac** [comment]
Unfortunately, Rouge, the gem we use for syntax coloring, does not have perl6 in place yet. 

ref https://github.com/rouge-ruby/rouge/issues/390

**Comment by maestromac** [comment]
not stale

**Comment by melezhik** [comment]
It is now called Raku

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here. 
We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).

**Comment by melezhik** [comment]
Hi @cmgorton  could you please post this feature request to forem.dev for me? Thanks

**Comment by cmgorton** [comment]
Yes I can. I will prioritize posting it there tomorrow.

**Comment by citizen428** [comment]
@melezhik @cmgorton This is still an issue with Rogue, see the comment by @maestromac above. Until they add a Raku highlighter there's not much we can do about this. Unfortunately both of the PRs trying to add it seem to have stalled.

**Comment by melezhik** [comment]
@citizen428  irrespectively, on Rogue issue, I'd still post it, can we?

**Comment by cmgorton** [comment]
@melezhik given the issue with Rogue I would say we keep this issue closed for now and if there are any changes with those PRs mentioned that are currently stale we can open a post on forem.dev. 
For now you may want to follow the Rogue issues(if you aren't already) and we can circle back to this if they add the necessary highlighter.

**Comment by melezhik** [comment]
hi @cmgorton , thanks, I've just pinged rogue devs in the respected ticket ...
