### ISSUE TITLE
Tag Moderator Can't Rate Experience Level of a Post

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#3017]
**Describe the bug**
We received a message(1) from a relatively new tag moderator ([https://dev.to/coreyja](https://dev.to/coreyja)) saying that they couldn't update the experience level for a post and kept getting an error with the response `{ "result": "Not Upserted Successfully" }`.

This occurred when they were trying to rate this [post ](https://dev.to/arturmartsinkovskyi/vim-in-modernity-why-and-why-not-5gad), but I couldn't recreate it. I asked them to rate another post, they chose [this one](https://dev.to/nirvana_flame/anyone-thought-of-saving-vim-editor-by-typo-smiley-2g8e), and it happened again.

I double-checked their [roles](https://dev.to/internal/users/40335)(2) and everything indicates that they are trusted and a tag moderator.

**To Reproduce**

Was unable to reproduce.

**Expected behavior**
Tag moderators should be able to rrate experience level of a post.

**Screenshots**

1) message
![https://cl.ly/9f0599f0df49/download/Image%202019-05-31%20at%203.26.15%20PM.png](https://cl.ly/9f0599f0df49/download/Image%202019-05-31%20at%203.26.15%20PM.png)

2) roles
![https://cl.ly/df1d098f3a20/download/Image%202019-05-31%20at%203.33.07%20PM.png](https://cl.ly/df1d098f3a20/download/Image%202019-05-31%20at%203.33.07%20PM.png)

**Desktop (please complete the following information):**

Didn't get specifics, but know they aren't on a mobile device. Let me know if we need more info.

**Additional context**

In conversation, they said "Potentially related, there is supposed to be a button on posts to get to the mod page right? So far I've just appended '/mod' since I haven't seen the button"

They were busy at the moment, so I didn't want to take up too much time, but I can definitely reach out for more info as necessary.

**Comment by jessleenyc** [comment]
@michael-tharrington any idea if this is still happening to them?

**Comment by cmgorton** [comment]
@michael-tharrington do you think this was a one off thing or has this happened again?

**Comment by michael-tharrington** [comment]
We are good to close this one here. 😀  They actually wrote me back and told me all was working, so I know we can close this one.

**Comment by Daniel-ltw** [comment]
Hi, 
Had issues with rating experience level a week ago. Still having this issue today. 

Every time I tried rating, clicking one of the experience level, it would come back with a bad request alert box. 

Not sure if this is a similar or a different issue.

Can't rate experience for any article at the moment.

**Comment by rhymes** [comment]
Hi @Daniel-ltw could you open a separate issue? Please fill the template also with the error message (check also the JS console to see if anything is logged there). Thank you!
