### ISSUE TITLE
Feature Request: list of commonly used/accepted tags or best practices

### ISSUE THREAD

**Issue by desithorne** [forem/forem#3051]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm writing a post and want to make sure I'm adding relevant tags to it, but do we colloquially use `#mentalhealth` or just `#health`? Maybe we use `#wellness`? Should I tag it with the language it's written in?

If we try to establish widely used tags, it might be easier for readers to find more content they're looking for!

**Describe the solution you'd like**
Maybe we could add a link or section in the Editor Guide with the commonly used/desired tags, or add some sort of documentation somewhere like "hey, this is the most used tag for _this thing_!"

**Describe alternatives you've considered**
I've considered (and probably will, just haven't had a chance yet) going through similar tags (like `#mentalhealth`, `#wellness`, etc.) and trying to see which one has the most posts in the tag, and writing an article that kind of compiles them to find what the most frequently used one is.

**Additional context**
I wonder if this sort of "best practice" might also help with newbie writers who worry about doing something "wrong" - maybe just a bit of tag guidance might help out.

**Comment by jessleenyc** [comment]
I agree that some documentation could be helpful. Just an FYI, we do combine tags that are similar -- for example if you tag 'rubyonrails' it'll show up under 'rails'.

**Comment by jessleenyc** [comment]
Some ideas: 

For v1 of the editor, lets add a button of some sort that will display commonly used tags or tag suggestions.

For v2 of the editor, let's add descriptions in the tag dropdown -- maybe including # of other posts in that tag.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here. 
 We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
