### ISSUE TITLE
Make Notifications action values more clear

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#3060]
Some notifications have `nil` `action` but this value is not very meaningful.
Usually, it means that some entity was `"Created"`, so nils could be replaced with it.

> Nil action means not reaction in this context
https://github.com/thepracticaldev/dev.to/blob/9cb40e546b4b911cf8e4fce424adfb12f9c106d7/app/controllers/notifications_controller.rb#L45-L48

It would also allow redusing the number of the unique indexes for the `notifications` table (I added them in #3012)

**Comment by danascheider** [comment]
I could pick this up if it's still up for grabs. @lightalloy you said that this "usually" means some entity was "Created"--are you aware of case(s) where it means something else?
