### ISSUE TITLE
Listing endorsements

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#3062]
I threw this idea out in our Slack a few weeks ago and @jessleenyc liked it. I still think it's a good idea and we should pursue it.

#### sloppy mockups:

![endorsement-list-view](https://user-images.githubusercontent.com/3102842/59052835-02fdc680-885e-11e9-8863-9b0a1d0f611a.png)
![endorsement-show-view](https://user-images.githubusercontent.com/3102842/59052839-05602080-885e-11e9-8232-f7f3b5aa600e.png)

Similar to a comment, but shorter and not necessarily part of a conversation. More a quick word from the community about the listing in mind. It allows listings to accrue social validation so that it makes sense to "bump" a listing as opposed to making a new one. Right now that benefit and flow is less clear.

All in all I think it adds a warm community feel, and all endorsements have a profile attached that can be clicked through to.

LinkedIn endorsements have created a somewhat cringey association, but I think this is a much more natural place to endorse a specific situation, rather than a "human". I think the endorsements can add some details and second opinions that could really add to a listing.

I think the lister should have the right to choose which endorsements get displayed. This is not a comment for general discussion, it is specifically to reinforce the value or ideas of the listing.

We should also establish a protocol for negative ratings, etc. in the future but I don't think that is such a straightforward thing to do. Any attempts to introduce a truly effective rating system or anything like that is bound to be gamed, so I think starting with a simple rating system while continuing to be diligent about responding to the `report abuse` button and working with the community to make sure listings are honest and helpful.

## Technical details.

A `ClassifiedListing` object would have a `has_many` relationship with its endorsements. The endorsements would have a `user_id` and `classified_listing_id` and all the things you'd expect. This should all be pretty straightforward.

The endorsement info will have to be stored in Elasticsearch index likely with the classified listing. 

Endorsements should have an `approved` or `displayed` boolean or something like that for the author of the listing to switch on. They should probably be able to manage it through their listings dashboard and also get a notification when a new endorsement comes in, which they can act on.

Please let me know if you intend to work on this!

**Comment by neilgreen** [comment]
@benhalpern I know you mentioned that someone should let you know if they intend to work on this feature but I didn't want to commit to doing it if I wasn't sure I could get it done, and the only way I knew to be sure I could get it done was to do it. If the feature doesn't work the way you expect, or it's not implemented correctly let me know and I'll adjust it accordingly.

**Comment by Oghenebrume50** [comment]
> A `ClassifiedListing` object would have a `has_many` relationship with its endorsements. The endorsements would have a `user_id` and `classified_listing_id` and all the things you'd expect. This should all be pretty straightforward.

Hi @benhalpern  I would like to work on this, going by this statement, I cannot find the `ClassifiedListing` model in the model folder, however, I see the `listing` model, is this what you were referring to here?

**Comment by rhymes** [comment]
Hi @Oghenebrume50! It was recently renamed to just `Listing`. They are the same thing :) I'm going to assign you to the feature
