### ISSUE TITLE
Mixed content (http) after uploading a video

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#3069]
**Describe the bug**
I uploaded a video, and after it finished uploading nothing happened. Checked my browser console to see this message:
> Blocked loading mixed active content “http://dev.to/andy/unpublished-video-my-secret-string/edit”

My guess is that it failed to redirect because of the `http`.

**To Reproduce**
1. Use Firefox Developer Edition
2. Upload a video
3. Wait for it to succeed
4. Don't get redirected
5. Open browser console and see error message

**Expected behavior**
I get redirected after uploading my video.

**Desktop (please complete the following information):**

- OS: macOS 10.13.5
- Browser: Firefox Developer Edition 68.0b6 (64-bit)

I'll probably work on this 🙃 making the issue for posterity.

**Comment by jessleenyc** [comment]
Reminds me of this issue: https://github.com/thepracticaldev/dev.to/issues/2995

**Comment by juliannatetreault** [comment]
@Zhao-Andy is this still an issue that you're encountering or has this been resolved?

**Comment by Zhao-Andy** [comment]
I think we still have this issue but I'm not sure my issue describes it well. I'll close this now and reopen if it comes up for someone.
