### ISSUE TITLE
At a minimum, document the state of analytics

### ISSUE THREAD

**Issue by rylandg** [forem/forem#3151]
**Is your feature request related to a problem? Please describe.**
There are no official statements/pages/documents describing the state of analytics. I've read through the open issues and existing PR's and think I understand the current state, but many users are not going to find this info on Github. 

**Describe the solution you'd like**
I do not believe the analytics API is currently available. Regardless, whatever does/doesn't exist should be clearly documented in the frontend UX. I think most users (including myself) assume that a site of Dev.to scale would have analytics available (more than basic views, and reactions) and it's nearly impossible to find information about that.

**Describe alternatives you've considered**
Impossible from user space.

**Additional context**
I think basic information such as

* when your content was viewed
* region/languages it was viewed from
* avg read time
* % conversion
* user entry method (linked from Twitter, Google, Direct etc...)

**Comment by flrnprz** [comment]
This could be a perfect paid feature, don't you think?

**Comment by jessleenyc** [comment]
@pkfrank do you think we could add some more info to the FAQ page about this?

**Comment by rylandg** [comment]
@flrnprz Not sure how that fits into the business model, but I would personally have no problem paying for such a service (I do earn a good bay area salary though). 

@jessleenyc any information would be an improvement over the current state.

**Comment by cmgorton** [comment]
We now have analytics open to everyone! You can read more about it in this forem.dev post https://forem.dev/foremteam/analytics-for-all-3db
