### ISSUE TITLE
Cover image and post info doesn't update on Twitter

### ISSUE THREAD

**Issue by maximelafarie** [forem/forem#3156]
**Describe the bug**

If you publish a post with any cover image, then you edit it and change the cover image again and you try to tweet the article, Tweeter only shows the first cover image you set. It's the same for the title if you changed it after first publication.

**To Reproduce**

1. Publish an article with a cover image
2. Share it on tweeter
3. Edit your post and change the cover image or the title
4. Share it on Tweeter again (error is here for title and cover image)

**Expected behavior**

Tweeter must show the latest cover image

**Screenshots**

The post's cover image and title:
![image](https://user-images.githubusercontent.com/5319267/59507271-daec1400-8eaa-11e9-8a73-c1cabe8250c1.png)

The tweet (with the initial post's cover image and title)
![image](https://user-images.githubusercontent.com/5319267/59507293-ee977a80-8eaa-11e9-8aad-1b3f313466d5.png)

**Comment by jessleenyc** [comment]
Ah, I believe Twitter caches that info on their side once they create the card image for the tweet. Even though the meta info gets updated, you'll have to manually refresh with the twitter card validator: https://cards-dev.twitter.com/validator

**Comment by maximelafarie** [comment]
Ah nice catch! Maybe it'll be possible to automate this action with the API.  🤔😜 

Here is the cURL API call (maybe you can do smth with it):
```
curl 'https://cards-dev.twitter.com/validator/validate' -H 'origin: https://cards-dev.twitter.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,la;q=0.6' -H 'x-requested-with: XMLHttpRequest' -H 'cookie: _ga=GA1.2.637240742.1522411998; eu_cn=1; dnt=1; ads_prefs="HBESAAA="; kdt=O4nN9u7rYxtmqqLeDyWNwWm2a7OMyCnPyYZUZOaH; remember_checked_on=1; auth_token=7050ffb9c5aa5ebf5a6c9deb999aefed2d8c07e4; csrf_same_site_set=1; csrf_same_site=1; syndication_guest_id=v1%3A153182388642372344; night_mode=1; __utmz=43838368.1535358259.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); tfw_exp=0; __utma=43838368.637240742.1522411998.1545301609.1547073371.4; twid=u%3D486462212; daa=1; personalization_id="v1_rta8fmaXBPpEir5m9c27aQ=="; guest_id=v1%3A155437141805772395; _twitter_sess=BAh7CSIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7ADoPY3JlYXRlZF9hdGwrCJnD7uRqAToMY3NyZl9p%250AZCIlOGZlYmJhNzJiOGJjNzM5ZmVmNmI4NjBmODdhN2MyOTQ6B2lkIiU1ODBm%250AZjNlMjNlNzNlZTUyNTgyN2VjNDM2ZTk3ODM3NQ%253D%253D--6c88bab693af6e84a5a51f644be10640edd2d4f1; rweb_optin=on; external_referer=padhuUp37zjgzgv1mFWxJ12Ozwit7owX|0|8e8t2xd8A2w%3D; csrf_id=6885bac96bb40f921e21090ca1d84751; ct0=d3dcef175bf56b092fb15fb7cccf1256; _gid=GA1.2.1387456383.1560757838; _gat=1' -H 'pragma: no-cache' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: cards-dev.twitter.com' -H 'referer: https://cards-dev.twitter.com/validator' --data 'authenticity_token=9c1c9f311fec2e3f4e5c2ff3e3f31edad0170918&url=https%3A%2F%2Fdev.to%2Fmax%2Fhow-to-enable-dark-mode-on-dev-to-4c3f&platform=Swift-12&authenticity_token=9c1c9f311fec2e3f4e5c2ff3e3f31edad0170918' --compressed
```

If you want some PR or anything else let me know I'll try to help the best I could. 🤓

**Comment by cmgorton** [comment]
Hey! Thanks for starting a discussion on this. We are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this.
