### ISSUE TITLE
Code block as first content in post causes preview to look bad

### ISSUE THREAD

**Issue by rylandg** [forem/forem#3242]
**Describe the bug**
If your post begins with a code block, the preview shows it unformatted and without `\n`. 

Oh and I noticed while posting this, that an image link in first part of a post also doesn't transfer to preview.

**To Reproduce**
Example post

````
```
// caller
function foo(callback) {
  callback('world');
}

// callback function
function myCallback(name) {
  console.log(`Hello ${name}`); // "hello world"
}

// pass callback to caller
foo(myCallback);
```
````

Create a draft and look at the preview

**Expected behavior**
Just remove the preview for now. Maybe something clever as backlog.

**Screenshots**
<img width="1093" alt="Screen Shot 2019-06-19 at 6 10 20 PM" src="https://user-images.githubusercontent.com/27736122/59811183-905d0400-92bd-11e9-9349-bdb5532ef709.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome

**Comment by cmgorton** [comment]
This bug report can no longer be reproduce. We believe this issue is fixed therefore I am going to go a head and close it. If you see something like this again in the future please feel free to open an issue again. Thanks!
