### ISSUE TITLE
Give Users the Ability to Temporarily Hide Their Accounts (Vacation Mode)

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#3252]
**Is your feature request related to a problem? Please describe.**

Users occasionally want the ability to temporarily hide / deactivate their account so that they're able to keep their content and history on DEV but if need be can take a break due to work/other online commitments.

**Describe the solution you'd like**

Perhaps a user could turn on "vacation" mode so that their account is out of view. During this mode: 

- the user wouldn't be able to comment/use reactions/write posts/make listings/message over Connect (maybe other actions?)

- their writing, profile, and comments wouldn't be visible. (anything that would identifying activity)

- they could still be logged in to view their feed, add items to their reading list,change things about their profile while it's out of view, etc.

- notifications would still be controlled under their own setting 

**Describe alternatives you've considered**
I considered a similar idea to the above where the user would have to completely be logged out during their vacation.

**Additional context**
Right now, when users have to delete their presence on the site for whatever reason, they can't get it back. They must create a fresh account.

**Comment by benhalpern** [comment]
Hmmm I love "vacation mode". I don't think it would be a good idea to wholly hide their writing because I think it would be a frustrating user experience if a post you expected to exist would sometimes exist and sometimes not.

But in terms of coming up with the right functionality to fulfill some kind of "vacation mode", I think that is definitely inline with our values.

**Comment by michael-tharrington** [comment]
@ben, that's a great point! Hmmm... I wonder if maybe it would enough to just anonymize their writing temporarily.

**Comment by MarkelFe** [comment]
I think the idea of completely hiding the author of the post is too radical. However, blocking the ability of sending messages, reacting and commenting would be helpful. As a plus, I would hide links to social media while vacation mode is active, so users cannot follow you to other social media.

**Comment by mazentouati** [comment]
I really don't see any real gain from this feature. If you're on a vacation just be and don't open dev community during the vacation. If you are concerned about your privacy deleting you account is more convenient.

Adding more options to privacy setting like disabling chat, comments per post etc. is handier in my opinion. Or, maybe add the ability to soft delete the account so it becomes reversible while assigning their content to an anonymous, as you mentioned, during that period.

**Comment by moopet** [comment]
I don't see any benefit from this feature either. At the moment the only activity you see from someone is:
* chat in connect
* recent posts on profile
* recent comments on profile
* post/comment total on profile

There could be a "stealth" mode that doesn't show any of those items and perhaps puts a warning badge on the group chats. That would cover everything wanted by the "vacation mode", but I'm not sure why it's a vacation mode. People don't come here to get regular updates from individuals so much as to browse interesting articles in their feeds and reading list.

Removing something someone's bookmarked or tagged as "read later" only to be able to put it back at some unspecified time in the future is an anti-feature.

**Comment by jessleenyc** [comment]
Hey all - just created a discuss post on this for the wider community to weigh in: https://dev.to/jess/what-would-you-expect-from-a-vacation-mode-feature-on-dev-1jml

**Comment by kodaman2** [comment]
I don't know it doesn't make much sense to me, if you are on vacation then enjoy. Site will be here when you are back. Only thing I can think of is that if you are on vacation mode and you really really love someone's content then perhaps get notifications on that, but other than that no one's forcing you to check, write, on dev.to if you feel obligated then there's a bigger problem at hand imho.

**Comment by jacobherrington** [comment]
Like most of the other users have said, I'm not sure I understand the reasoning. Perhaps this would be better described as archiving an account? I think what @michael-tharrington is describing sounds more like a soft-delete to me.

**Comment by omenking** [comment]
I'm going go against popular opinion here and see it as well-being feature.
Too many of my facebook friends have suspended their account only to return later because of social media fatigue.

I would go further to saying if you go on vacation mode for other user's to encourage your return by sending you reactions and positive messages which is then collected over a period of time and emailed to you in bulk.

It would be cool if you could event set how many days to lock out your account eg. 14 days. So we have a countdown of your return.

I'm in favour of @benhalpern thoughts on the content and profile feed should remain the same and not hidden/scrubbed.

**Comment by kodaman2** [comment]
> Too many of my facebook friends have suspended their account only to return later because of social media fatigue and needed a mental break, the alternative is they would have deleted their account in full.

I would normally agree for facebook, but I just don't see a true comparison as Dev.to is not really a social media site, is more of a blogging site.

**Comment by omenking** [comment]
Dev.to is my facebook.

**Comment by michael-tharrington** [comment]
To provide a bit more context... if I remember correctly I wrote this ticket after interpreting a request from a DEV user.

The user ended up leaving DEV, but really just wanted some time off as they were in a new job and needed to focus on that. They voiced wanting a combination of privacy + time off from the site. I _think_ they may have felt a bit overwhelmed at the idea of their new colleagues discovering their online presence and reading through their writing.

Looking back through this request, I'm thinking that "Vacation Mode" was a bad title for what I was getting at. I was thinking more about privacy when writing this up.

Offering privacy by way of hiding someone's content from view doesn't seem to be a popular option. And I can definitely see the downsides. As an alternative solve, I really like the soft delete idea proposed by @jacobherrington. This would allow people who leave for privacy reasons the opportunity to come back and regain control over their content.

I still think vacation mode may be worth thinking about more too, as a well-being feature to use @omenking's words (really love the suggested refinements to the feature above). I think the general idea of vacation mode meshes well with DEV. It seems like a cool way for DEV to promote a healthy work/life balance. And of course, it's just a personal option, so I don't think it would negatively effect others.

**Comment by kodaman2** [comment]
Thanks for providing context, this makes a lot more sense. 

+1 on the privacy idea when a user gets a new job and wants some privacy, I can definitely understand feeling overwhelmed at the idea of new colleagues reading your content. Not sure if Dev uses user id as alphanumeric but perhaps if the user wants privacy with soft deleting their account their articles would show up as written by user4527855a455jjnhh.

For the vacation mode I still don't think is a good idea, however definitely some things can be done without affecting The content while promoting wellness, I'm sure you guys will figure out something cool.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

There has been a lot of great points brought up for this feature but since it has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
