### ISSUE TITLE
RSS feed reader to follow links to fetch article

### ISSUE THREAD

**Issue by gypsydave5** [forem/forem#3254]
**Is your feature request related to a problem? Please describe.**
My blog's RSS feed (https://blog.gypsydave5.com/feeds/feed.rss) does not publish the blogs content to each item in the feed. I'm under the impression that this is what's needed to publish to dev.to via RSS.

**Describe the solution you'd like**
I'd like the dev.to RSS reader to make an HTTP request to the `<link>` in each `<item>` to fetch the article, parse it, then extract the HTML around the `<article>` tag (which seems like the appropriate tag). The reader should revert to previous behaviour should any of this fail.

**Describe alternatives you've considered**
I _could_ start putting the content in a `<content>` tag, but I feel this is wrong because
- it's not in the RSS spec
- there's already link to the content in the RSS item
- it would unnecessarily increase the size of the feed.

**Context**
I'm happy to work on this, but my Ruby is rusty.

(my Rust, however, is not ruby-y... 😜)

**Comment by maestromac** [comment]
Thanks for the issue @gypsydave5 . I don't think this feature will be feasible.

Our RSS reader are rather simple and we use what is provided from feed url much like other RSS reader. Putting the content in your post in a content tag would be the most compatible thing to do. I am not certain what is and isn't part of the RSS spec but it seems like your feed [isn't valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.gypsydave5.com%2Ffeeds%2Ffxeed.rss) and I can't properly import it through Feedly, Feeder, or FeedBro. I can understand your concern with size but I doubt wrapping content in content tag will increase the size of the feed by a big margin. 

Let me know what you think.

**Comment by cmgorton** [comment]
Hey, thanks for the feature request. We are working on cleaning up stale issues in the repo. Since this seems like a feature we will not likely be able to implement and this has been inactive for over a year I am going to go a head and close this. Thanks!
