### ISSUE TITLE
Mobile: bottom panel overlaps editor text area when keyboard is active

### ISSUE THREAD

**Issue by felippe-regazio** [forem/forem#3324]
Simple problem, think that the image tells everything

![Screenshot_2019-06-27-19-07-33](https://user-images.githubusercontent.com/31618881/60305444-ed3a6900-9912-11e9-8793-0b08733df144.png)

As the image shows, the inner view bacomes really small when the keyboard is active.

**Comment by rhymes** [comment]
@felippe-regazio can you provide model, OS and details of your mobile phone?

Basically the following information from the template:

```text

- Device:
- OS:
- Browser:
- Version:
```

thank you!

**Comment by felippe-regazio** [comment]
- Device: LG K9
- OS: Android 7.1.2
- Browser: Chrome
- Version: 75.0.3770
- Phone Dimensions: 73.2 x 146.3 x 8.2 mm

**Comment by maestromac** [comment]
This will require a bit of redesign. Depending on the editor version, users will either see 3 or 4 buttons. If I were squish 4 buttons together it would look like below.
![Screen Shot 2019-07-11 at 12 13 26 PM](https://user-images.githubusercontent.com/15793250/61067775-638ca000-a3d6-11e9-9ef6-7f5446bdcee2.png)
Doesn't seem too ideal. I think the best move here is to a toggle button to hide the buttons panel 
![Screen Shot 2019-07-11 at 11 24 53 AM](https://user-images.githubusercontent.com/15793250/61067885-ababc280-a3d6-11e9-9916-c85be5e58bd1.png)
For anyone who wishes to take this, please be sure include a screenshot on how a toggle button would look like!
