### ISSUE TITLE
feature: improve comment linking UX

### ISSUE THREAD

**Issue by thefliik** [forem/forem#3332]
**Is your feature request related to a problem? Please describe.**

When you click on a comment link in DEV.to, you are taken to a page which displays only that comment in isolation ([example here](https://dev.to/ben/comment/329n)). To me, and to the [few others I've polled](https://dev.to/johncarroll/poll-why-does-clicking-a-dev-comment-link-display-the-comment-in-isolation-2k5n), a comment is inherently contextual. There is never a time when I find viewing a comment in isolation is desirable ([ben has expressed similar feelings himself](https://dev.to/ben/comment/329n)). When clicking a comment link my workflow is always "click comment link > click `VIEW POST` > scroll back to comment".

In short, I find the current comment linking UX to be poor, and this is a request to fix it.

If in doubt, I imagine you could get more feedback on the current UX by polling DEV.to users yourself.

**Describe the solution you'd like**

I'm sure you could get fancy with fixing the UX (I'm ok with that), but, in order to address this issue, all that needs to be done is to update the UX to be inline with that of most websites: power comment links via anchor tags, so the browser simply displays the full page and scrolls to the relevant section (very intuitive). For example, this is the UX that github has.

### Thanks!!!

**Describe alternatives you've considered**

I'm not committed to a particular solution, just not the current setup.

**Additional context**

https://dev.to/johncarroll/poll-why-does-clicking-a-dev-comment-link-display-the-comment-in-isolation-2k5n

**Comment by Zhao-Andy** [comment]
Thanks for your thoughts @thefliik! We'll discuss this as a team and add additional comments.

**Comment by thefliik** [comment]
unstale-ify!

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. Thanks.
