### ISSUE TITLE
Add rubocop to the travis build.

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#3360]
New rubocop issues continue to appear in the codebase, probably, because of the `--no-verify` usage.
It would be nice to see the new violations as soon as they appear.

**Comment by cmgorton** [comment]
@maestromac did the [#3507](https://github.com/forem/forem/pull/3507) fix this issue? If so I will close this issue.

**Comment by maestromac** [comment]
@cmgorton no it didn't but thanks for checking!

**Comment by mirie** [comment]
We moved off of Travis so closing this issue.
