### ISSUE TITLE
Setting theme/font while logged out.

### ISSUE THREAD

**Issue by NickyMeuleman** [forem/forem#3379]
**Is your feature request related to a problem? Please describe.**
I'm not logged in on all browsers, but like to use dark themes when I can.
It would be great if guests could set the theme/change the font.

I don't know if it's possible already.
I tried setting the `config_body_class` key in localstorage to `night-theme default-article-body` with no result.

**Comment by jessleenyc** [comment]
Hey @NickyMeuleman! I think we'd be able to make this happen eventually but right now there isn't a simple way for us to make that available for logged out users.

The reason setting `config_body_class` doesn't work is that we don't run the script that checks for that for logged out users. If someone created a browser extension or user script that ran the contents of this script it would work: https://github.com/thepracticaldev/dev.to/blob/master/app/views/layouts/_user_config.html.erb

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here. We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
