### ISSUE TITLE
Add Link to User Notist Profile

### ISSUE THREAD

**Issue by bencgreenberg** [forem/forem#3414]
**Describe the solution you'd like**

The current user profile page has a good array of links to various platforms that the user may want to feature: Twitter, LinkedIn, GitHub, and others. What is missing is a platform to link to that contains a user's conference presentations, if that is relevant to them. [Notist](https://noti.st/) is a popular platform for hosting conference presentations and adding a `.notist_url` attribute to a user would make it available on their profile. 

It would be added to this list of icons on a user's profile page:

<img width="259" alt="Screen Shot 2019-07-08 at 17 44 47" src="https://user-images.githubusercontent.com/13892277/60819358-1b883600-a1a8-11e9-8191-921b7e84ad17.png">

**Comment by jessleenyc** [comment]
Thanks for the request! We're still trying to figure out what our requirements are in regards to adding new icons to the DEV profile. For example, should this be reserved for social links only? Should we use font awesome as a determiner? etc.

**Comment by benhayehudi** [comment]
Hi @jessleenyc, completely understand! I thought I would raise this as a possible way to enhance a person's presence on the site. For those who have delivered talks, it's always nice to be able to share those slides with those who may find them helpful! 

I'm happy to think through it more with someone if that's helpful, and of course, more than happy to make the change myself and add it as a PR for review. Just let me know. :)

**Comment by cmgorton** [comment]
Hey! Thanks for taking the time to open this discussion. We are working on thinking through the product roadmap for Forem and not just DEV and cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this.
