### ISSUE TITLE
New followed tag automatically float up to my tags

### ISSUE THREAD

**Issue by damechen** [forem/forem#3422]
**Is your feature request related to a problem? Please describe.**
When I follow some tag in the "Other popular tags" area, I won't be able to see the tag showed up in "My tags" area without a reload.

**Describe the solution you'd like**
I would like to see once I clicked some tag in "Other popular tags" area, the tag will disappear in "Other popular tags" area, and showed up in "my tags" area without a page reload.

**Comment by cmgorton** [comment]
Thank you for opening this issue. At this time we do not think this is something we have our roadmap so we will be closing this issue for now. However, we are always open to further discussion here :)
