### ISSUE TITLE
Recycle Old Content

### ISSUE THREAD

**Issue by jrg94** [forem/forem#3453]
**Is your feature request related to a problem? Please describe.**

This is mostly a selfish ask, but I think it would be cool if there was an option to discover older  content. Right now, the main homepage allows you to sort content by latest and greatest, but there doesn't seem to be any opportunities for good content to shine if it never gets seen in the first place.

In other words, unless an article gets overwhelmingly popular, I feel like it sort of disappears into the void like an old Tweet. It would be nice if articles had an opportunity to resurface as they do take a lot longer to write than a Tweet.

**Describe the solution you'd like**

I know that dev.to displays related content under articles, but I think I'd be interested in a tab or widget that allowed you to discover older articles. For instance, GitHub has this little discover repositories section on the main dashboard. I don't know how it works (probably based on trending repos), but I'd love something like that as both a reader and an author—especially if those recommendations were based on your interests. 

**Describe alternatives you've considered**

Honestly, I haven't thought a lot about how this would work, and I couldn't find any similar suggestions in the current list of issues. If anyone has any ideas, I'm welcome to them!

**Additional context**

Here's the GitHub feature I was referencing:

![image](https://user-images.githubusercontent.com/11050412/61084599-4d91d600-a3fc-11e9-9397-ad927afd83c1.png)

**Comment by rhymes** [comment]
Hi @jrg94 it's a good idea, would the existing suggested articles UI that appears at the bottom of the article page cover this?

For example, at the bottom of https://dev.to/vuejstutorial_/server-side-kotlin-with-coroutines-183g I see the following suggestions:

![Screenshot_2019-07-12 How To Become A Full Stack Developer In 2019  ROADMAP  ](https://user-images.githubusercontent.com/146201/61109006-1830cb00-a484-11e9-9e7b-577d7aa650cb.png)

I don't remember the exact algorithm for all the boxes but I think they are all based on reactions count

**Comment by jrg94** [comment]
Yeah, this is great right now! That said, I think it's a bit more indirect than I'd like. Something like the following for articles would be awesome:

![image](https://user-images.githubusercontent.com/11050412/61109984-41396780-a454-11e9-8ccc-0786c02ac5ca.png)

That said, if you think the current recommendations section already accomplishes that, no worries!

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  
 We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
