### ISSUE TITLE
Image upload jumps to the top of the editor

### ISSUE THREAD

**Issue by Beznet** [forem/forem#3602]
**Describe the bug**
When you add an image using the image upload feature at the bottom left of the editor, it will cause the editor to scroll all the way back to the top of the page. 

**To Reproduce**

- Go to one of your articles and go into the editor. This works best with articles that are long enough to cause Y overflow.

- Click on the 'Image' button.

- When the image upload modal pops up, you dont have to upload an image and just select 'done'

- After you select 'done' you will now be at the very top of the page. 

**Expected behavior**

After finishing uploading an image using the above described method, it should keep you at the place you left off in the editor instead of scrolling all the way to the top of the page. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mojave
- Browser: Chrome & Safari
- Version: 75.0 & 12.1.1

**Additional context**

Just to add reasons why I think this should be addressed, i was editing a rather long article and posting photos as I went and every time I upload a photo I would have to scroll all the way back down to where I left off writing.

**Comment by Mildred14** [comment]
Hi @Beznet I can help to solve this issue

**Comment by JSSaini07** [comment]
@Beznet Can i pick this up if this is not being worked upon? cc: @Mildred14

**Comment by JSSaini07** [comment]
Seems like the issue no longer exists, `upload image` has been moved to the top in latest version of master

<img width="875" alt="Screenshot 2019-10-05 at 10 20 55 PM" src="https://user-images.githubusercontent.com/12277214/66258081-99b3a300-e7be-11e9-86a8-f5eb7ce56f4a.png">

**Comment by Beznet** [comment]
@JSSaini07 Hm maybe they haven't pushed master to prod yet? Im still seeing the same issue where `upload image` is in the bottom left corner and it the top-page jump is still happening.

**Comment by JSSaini07** [comment]
@Beznet Yeah, it is still reproducible on the website but not in the local build of latest master, They probably haven't upgraded prod.

**Comment by mstruve** [comment]
Tested this out and with our new editor changes, this no longer appears to be a problem. @Beznet if you are still able to reproduce this please let us know! Thanks for contributing and being a part of Forem!!!
