### ISSUE TITLE
Ability to pin/unpin my posts in dashboard

### ISSUE THREAD

**Issue by idris-rampurawala** [forem/forem#3656]
**Is your feature request related to a problem? Please describe.**
If I want to pin/unpin any post of mine, there is only one way to do it i.e. by clicking on the manage post and then pin/unpin.

**Describe the solution you'd like**
If we can have pin/unpin button directly on the list presented in the dashboard then it would be very easy for me to get this work.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jessleenyc** [comment]
Totally agree the current flow has quite a bit of steps. If anyone wants to take this on, please include mockups or a thorough description on how you would approach the design. Thanks!

**Comment by bolariin** [comment]
I was thinking the pin to profile option could be added to the dropdown menu with archive post. It could look something like this

![Pin to Profile](https://user-images.githubusercontent.com/24629960/67154977-694a2980-f2d3-11e9-9c01-f310805f24a5.png)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
