### ISSUE TITLE
Issues Around Making Tags Aliases For One Another

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#3675]
@michael-tharrington commented on [Wed Jul 03 2019](https://github.com/thepracticaldev/team/issues/229)

**Describe the bug**

After making the tag `emberjs` an alias for `ember`, some of the posts that were tagged with `emberjs` (e.g. -  [this one](https://dev.to/decipherzonesoft/top-5-front-end-development-frameworks-in-2019-9ac)) have disappeared from the [`ember` tag page](https://dev.to/t/ember/ ) - (see https://dev.to/t/ember/top/infinity)

**Expected behavior**

When tag `x` is made an alias for tag `y`, `x`'s posts should all be visible on `dev.to/t/y` 

**Additional context**

I was working with the new tag mod for `ember` who noticed the inconsistencies after we made `emberjs` an alias for `ember`. Chris suggested making `ember` the dominant tag name after speaking with the Ember Steering Committee.

**SOLUTION**
From @michael-tharrington's comment below. 

> any previous posts that have been tagged #a should also transform their tag to #b... right now, they just keep the old tag and thus remain hidden.

> Until the above can be fixed, I'm hesitant to make a tag with existing content an alias for another tag because the content under the tag will be hidden from view.

**Comment by jessleenyc** [comment]
@mansona just transferred over this issue if you're still interested!

**Comment by mansona** [comment]
thanks for the heads up @jessleenyc 👍 I am happy to take a look, the only issue being that I'm not a ruby dev 😂 any guidance would be appreciated

**Comment by mansona** [comment]
So I've gotten this as far as it running on my local machine and I've found something strange 🤔 I am on http://localhost:3000/admin/tags/16 (a tag that I created locally) and I don't see any edit field for setting up an alias. I have looked at the controller and it seems like it should be showing something up because of https://github.com/mansona/dev.to/blob/master/app/controllers/admin/tags_controller.rb#L27 but I don't understand why it's not there 🤔 

Is there a reason why there is no form field being auto-generated for alias_for? Is there a different way to setup aliases?

**Comment by jessleenyc** [comment]
Ah yes, we've been slowly migrating actions away from /admin and to /internal. You should see the form at /internal/tags!

**Comment by mansona** [comment]
Perfect thanks @jessleenyc that got me unstuck so I could progress a little bit 🎉 

I was just writing a note here to tell you I couldn't figure out what was wrong and I figured out how to finally write a test to show that things are broken 🎉 the next thing is to just figure out how to move forward from here... 

I'm assuming there is some logic in the post creation function that makes sure things are categorised in the right tag. I also assume that we could put some logic in the tag update function that would go through and do the same for each of the articles.

Just an idea for now but again, any recommendations would be much appreciated

**Comment by michael-tharrington** [comment]
Speaking with @maestromac, I've learned that this issue is caused somewhat by or current design choices...

When `#a` becomes an alias for `#b` the following happens:
- `dev.to/t/a` redirects to `dev.to/t/b`
- any future posts that are posted with the tag `#a` are transformed upon posting to use the tag `#b` instead (this is done with a search and replace behind the scenes 

What we're missing is:
- any previous posts that have been tagged `#a` should also transform their tag to `#b`... right now, they just keep the old tag and thus remain hidden.

**Comment by mansona** [comment]
@michael-tharrington I'm assuming this would require some sort of background job to do the same "transformation" of all the previous tagged content? 

I tried to look into this myself but I am not a native Ruby dev 😂  so I couldn't quite figure out how to even start going about it

**Comment by michael-tharrington** [comment]
Haha, no worries @mansona I appreciate you looking into it and helping to discover this issue to begin with! 

This one has been hanging around too long, but I _think_ we now understand at least what kind of work we got cut out for us here.

I'm really hoping we can get to this soon!

**Comment by mansona** [comment]
amazing 🎉 thanks for getting this sorted! Will this be run as a background process to update older aliases?

**Comment by citizen428** [comment]
@mansona As is no, but we can kick of the background worker manually for tags that need to be processed this way if you have any mind cc @maestromac

**Comment by maestromac** [comment]
From the look of it, resaving the tag won't be enough as `tag_alias_updated?` will be false. I think we need a dedicated DataUpdateScript to update older aliases. It shouldn't be that many and we can target only tags that have a `tag_alias` column. I can work on this.

**Comment by citizen428** [comment]
@maestromac I was specifically talking about the worker I added in https://github.com/forem/forem/pull/12480. We need to find a list of tags we want to retroactively change, then run the worker for each of them. I'm not a data update script is the right way to go here, as this will be pretty DEV specific, so maybe we just kick them off in a console?

**Comment by maestromac** [comment]
@mansona Older aliases were updated.

**Comment by michael-tharrington** [comment]
So awesome to see this one completed. I'm going to go alias some tags later on today! 😀

**Comment by mansona** [comment]
omg thanks so much @maestromac 🎉 so happy that this is in place now. Thanks for all the hard work!

**Comment by maestromac** [comment]
Credit goes to @citizen428 !
