### ISSUE TITLE
Chat - Sound Effect When Messaging

### ISSUE THREAD

**Issue by omenking** [forem/forem#3682]
**Is your feature request related to a problem? Please describe.**

When someone messages I have to manually check chat which causes a delay in conversation.

**Describe the solution you'd like**

- [ ] When someone notifies me I should hear a sound.
- [ ] I should have a toggle to globally turn on and off notification sounds

**Describe alternatives you've considered**

**Additional context**

**Comment by jessleenyc** [comment]
This makes sense to me, and we definitely want to have the user setting available to opt-in/out of right away 😅.

Figuring out a sound would be fun 😁.

**Comment by theomelo** [comment]
@sarthology @jessleenyc I assume this PR fixes the issue? Do you think it satisfies as a solution?

**Comment by cmgorton** [comment]
It looks like this may be addressed in the above PR if not feel free to open up a discussion around this feature in [forem.dev](forem.dev) Andrew!

 There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
