### ISSUE TITLE
Ability to filter search results on mobile

### ISSUE THREAD

**Issue by helenanders26** [forem/forem#3688]
**Describe the solution you'd like**

Can we please have the ability to filter search results on mobile the same way we do on desktop.  This could potentially be hidden away when not in use the same way the 'reading list' when on the Home page.

**Describe alternatives you've considered**

Tested on ios and android but doesn't appear to be available on either

**Additional context**

<img width="414" alt="aws1" src="https://user-images.githubusercontent.com/17949635/62851942-f739ef00-bd3b-11e9-89d0-b3204b9682ba.PNG">

[How do I search only my own posts?](https://dev.to/1000martians/how-do-i-search-only-my-own-posts-3l7e)

**Comment by jessleenyc** [comment]
Yep, this makes sense. If anyone wants to contribute to the issue, please let us know what you're thinking design-wise first!

**Comment by JWesorick** [comment]
`notifications#index` has a nav that could be reused here. There are however more items so it would wrap to the next line. What do you think?
<img width="382" alt="Screen Shot 2019-10-06 at 3 14 23 PM" src="https://user-images.githubusercontent.com/801062/66274408-615aa600-e84c-11e9-9aa4-c346762fa8dc.png">

**Comment by benhalpern** [comment]
Hey, I think re-using the general components from notifications makes sense, but I think we should handle the overflow with a side scrolling div (with faded right-hand side to indicate scrollability)

Such as the Google to level filters...

![Image from iOS](https://user-images.githubusercontent.com/3102842/66676828-60ec5180-ec36-11e9-823e-6f21ca1dc7b7.png)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
