### ISSUE TITLE
Some Unicode characters are not shown in right format

### ISSUE THREAD

**Issue by mrm8488** [forem/forem#3705]
I created a post in Spanish some months ago. In the beginning, Spanish special characters (ñ, ó, é, á, etc) were shown in the right way. Some days ago, I went to my article and they were not shown in the proper way.

To Reproduce:
Visit:
[buggy article](https://dev.to/mrm8488/liderazgo-e-historia)

**Comment by jessleenyc** [comment]
Thanks for letting us know, we'll take a look.

**Comment by cmgorton** [comment]
Hey👋 this seems to be limited to just the article you mentioned. Other articles in Spanish can use the special characters without issue. 
Examples:
https://dev.to/amigosmaker/java-vs-python-spanish-1dgg
https://dev.to/amigosmaker/pyqt-vs-tkinter-spanish-2n4k
https://dev.to/mafermazu/3-consejos-para-empezar-a-programar-424a
