### ISSUE TITLE
Tags not Rendering on Posts

### ISSUE THREAD

**Issue by scrabill** [forem/forem#3706]
**Describe the bug**

When creating and publishing a post, the tags are not displayed on the post page. I've had this happen on some posts, but not all posts that I have made.

**To Reproduce**

1. Create a new post
2. Add tags
3. Save
4. View or Preview

**Expected behavior**

I expect the tags associated with the post to be displayed when viewing the post

**Screenshots**

Here is a screenshot of the post in edit mode.

![Screen Shot 2019-08-12 at 12 15 40 PM](https://user-images.githubusercontent.com/17805262/62880294-14020280-bcfb-11e9-9127-e209f0f052ec.png)

And here is the front matter

 ```
title: What color are your office walls?
published: true
description:
tags: discuss, watercooler
```

When previewing or viewing the published post, this is what I see

![Screen Shot 2019-08-12 at 12 17 52 PM](https://user-images.githubusercontent.com/17805262/62880371-3a27a280-bcfb-11e9-9504-6d958c49ea96.png)

Looking at the source code of the published post, the tags div is there, but without content

![Screen Shot 2019-08-12 at 12 19 01 PM](https://user-images.githubusercontent.com/17805262/62880461-6ba06e00-bcfb-11e9-8f9d-bad143f370a2.png)

For comparison, here is the front matter of a similar post (no image) where the tags do render.

```
title: Is there an art to naming projects?
published: true
description: 
tags: discuss, projects
```

![Screen Shot 2019-08-12 at 12 24 06 PM](https://user-images.githubusercontent.com/17805262/62880773-2a5c8e00-bcfc-11e9-979f-fdbc2ad12d52.png)

**Desktop (please complete the following information):**

- OS: Max OS Mojave
- Browser: Chrome
- Version: 76

**Additional context**

I had a similar issue happen on [another post](https://dev.to/scrabill/three-impactful-insights-from-codeland-2019-7if) but managed to fix it (or it fixed its self).

**Comment by scrabill** [comment]
Oddly, the tags are now showing for this post. I did not make any changes.

![Screen Shot 2019-08-12 at 2 20 43 PM](https://user-images.githubusercontent.com/17805262/62888001-68fa4480-bd0c-11e9-9da8-49f1b77671ad.png)


Should I consider this issue closed or keep it open?

**Comment by jessleenyc** [comment]
Hmm interesting. Did it show up after a refresh? Or did it just..pop up on its own?

**Comment by scrabill** [comment]
It might have popped up on its own. I had navigated to different pages within dev and on the web either way. I tested in an incognito tab before I submitted an issue too 🤔

**Comment by mstruve** [comment]
Hey @scrabill! Since this is an older issue and it looks like you were able to get the proper behavior I am going to close. If you come across this issue again please do not hesitate to reopen! Thank you so much for contributing to Forem!!!
