### ISSUE TITLE
Asciidoc support on dev.to posts

### ISSUE THREAD

**Issue by autoferrit** [forem/forem#371]
## Feature Request or Task
I have fallen in love with asciidoc to write my articles and other content. I would love to see dev.to support the use of asciidoc for writing posts. Right now, my favorite feature is [code callouts](https://asciidoctor.org/docs/user-manual/#callouts) 
![image](https://user-images.githubusercontent.com/89895/44226121-1b241e00-a144-11e8-8a95-8758c7c37a49.png)

[Asciidoc Homepage](http://asciidoc.org/)

### Definition of Done
Being able to write posts in markdown OR asciidoc

**Comment by benhalpern** [comment]
I think this would be pretty cool! If you want to start working on this, I could try and guide you.

I think we'd want to start by just making the conversion step working and then work backwards from there to get the user interface right.

Probably can't make this a big priority, but happy to help as much as possible.

**Comment by mraible** [comment]
I recently added AsciiDoc to the Okta Developer blog. It wasn't too difficult. We're using Jekyll. You can see what I had to do in https://github.com/okta/okta.github.io/pull/2321.

**Comment by maestromac** [comment]
not stale

**Comment by DrSensor** [comment]
FYI, [hugo](gohugo.io) support both markdown, asciidoc, and reStructuredText. It might worth taking a look at how they approach this.

**Comment by msarit** [comment]
@cmgorton Hi Christina! 👋🏾 

Recommending closure for this issue, due to minuscule interest.

**Comment by bcouetil** [comment]
Please reopen this 😭 Asciidoc is future-proof ! Markdown done better.

**Comment by cmgorton** [comment]
Hey @bcouetil I believe this was closed as it had been open for several years without anyone in the community wanting to work on it. I do not believe it is something on the roadmap that Forem engineers can work on any time soon but I'd be happy to have a discussion over on [forem.dev](https://forem.dev/) to see if this is something we can open back up to the community if they want to contribute to making this happen.
