### ISSUE TITLE
Bug regarding reactions

### ISSUE THREAD

**Issue by harden-ung** [forem/forem#3733]
**Describe the bug**

if I react (heart) something too quickly, I can accidentally reset the number of reactions to zero. And this affects right at the server, not just the front-end.  
**To Reproduce**

1/ Find any comment and press react (heart) quickly.
2/ Now you see the number of hearts got reduces to a negative number.
3/ Restart the browser, the number of hearts become zero 

**Expected behavior**

**Screenshots**

![negative4heart](https://user-images.githubusercontent.com/23309848/63168446-d542b400-c03c-11e9-8419-be48a05ef3fb.PNG)
![toomanyrequest](https://user-images.githubusercontent.com/23309848/63168459-e25fa300-c03c-11e9-921f-a90c2fbb3cc3.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Smartphone (please complete the following information):**

Not yet tested

**Additional context**

**Comment by mstruve** [comment]
We have spent a lot of time recently updating our frontend so I no longer think this is an issue. I was not able to reproduce it myself with the current code. If you are able to reproduce this now please let us know and we will reopen. Thank you as always for contributing to Forem!!!!
