### ISSUE TITLE
Refactor CodeClimate Issues

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#3739]
We have CodeClimate hooked up to our repo. It identifies code smells, which can be low-hanging fruit for improving the application.

Issues can be found here:

https://codeclimate.com/github/thepracticaldev/dev.to/issues

You can sort by JavaScript and Ruby and other filters.

**Comment by AnkitaSinghal** [comment]
I would like to work on this issue

**Comment by jessleenyc** [comment]
Awesome. Just a note here that this is an evergreen issue -- there will (almost certainly) always be CodeClimate issues up for grabs so anyone should feel free to submit a PR here!

**Comment by FeruzOripov** [comment]
Hi, I've just made my first PR. But I got Travis CI failure. I can't figure out the reason. Can someone review my code, #3787 . Thanks )

**Comment by FeruzOripov** [comment]
Here another one #3793

**Comment by FeruzOripov** [comment]
#3794

**Comment by Aswathprabhu** [comment]
Hi, I've made my [first PR](https://github.com/thepracticaldev/dev.to/pull/4104). Can anyone review it?

**Comment by Aswathprabhu** [comment]
Hi I've made my [first PR](https://github.com/thepracticaldev/dev.to/pull/4107), Can anyone review it?

**Comment by Aswathprabhu** [comment]
Hi I've made some PRs ([4154](https://github.com/thepracticaldev/dev.to/pull/4154))([4156](https://github.com/thepracticaldev/dev.to/pull/4156))([4157](https://github.com/thepracticaldev/dev.to/pull/4157))([4158](https://github.com/thepracticaldev/dev.to/pull/4158))([4159](https://github.com/thepracticaldev/dev.to/pull/4159)) I don't know why for some of them, Travis CI fails. I can't figure it out, Can anyone check on them?

**Comment by hoangvvo** [comment]
Hey, happy weekend everyone.

I need help with https://github.com/thepracticaldev/dev.to/pull/4241#issuecomment-538683355 if anyone is available.

**Comment by nickytonline** [comment]
There are issues in regards to OrgSettings.jsx in Code Climate. I've started work on this. This is not the same work being done in #2470 in regards to eslint issues that @ruffle1986 is addressing.

**Comment by hoangvvo** [comment]
If someone can help me review #4241, it would be great. Thanks!

**Comment by redxtech** [comment]
I've just submitted two PRs in order to address some CodeClimate issues - #4442 & #4443.

**Comment by netochaves** [comment]
Is there Anyone working on `articleForm.jsx` issues? I would like to work on this.

**Comment by rhymes** [comment]
@netochaves check https://github.com/thepracticaldev/dev.to/issues/2470 if there are people working on things, I remember @ruffle1986 had submit this PR: https://github.com/thepracticaldev/dev.to/pull/4217 which includes all article form files

**Comment by netochaves** [comment]
thanks @rhymes, I'll ask on #2470 if has work to do yet.

**Comment by JulianoGTZ** [comment]
Hi Folks. I have some doubts about this [issue](https://github.com/thepracticaldev/dev.to/pull/6992):

I'm trying to fix the code climate issues about the listing.jsx file and I have some doubts:

- Has another issue with a refactoring example on the front-end side?
- Has some tip about I can separate the parts on render in other components?
- It's possible the usage of React hooks?

Thanks for the help.

**Comment by nickytonline** [comment]
> Hi Folks. I have some doubts about this [issue](https://github.com/thepracticaldev/dev.to/pull/6992):
> 
> I'm trying to fix the code climate issues about the listing.jsx file and I have some doubts:
> 
> * Has another issue with a refactoring example on the front-end side?
> * Has some tip about I can separate the parts on render in other components?
> * It's possible the usage of React hooks?
> 
> Thanks for the help.

I gave some assistance for this in #6992

**Comment by JulianoGTZ** [comment]
Hi folks. I tried to solve some codeclimate issues on listings/listings.jsx but I failed 😭.

Anyway, I did this [pull-request](https://github.com/thepracticaldev/dev.to/pull/6992) which improves the legibility cleaning the render function.

**Comment by wyhaines** [comment]
Just FYI -- the original link in the issue (https://codeclimate.com/github/thepracticaldev/dev.to/issues) does not exist anymore.

**Comment by nickytonline** [comment]
I'm going to go ahead and close this as that project no longer exists in Code Climate.
