### ISSUE TITLE
Cursor suddenly jumps from current line to end of page (v1)

### ISSUE THREAD

**Issue by c33s** [forem/forem#3773]
**Describe the bug**
when writing an article in editor v1 (haven't tested v2), it happens to me multiple times that while i am writing the cursor suddenly jumps to the last line.

**To Reproduce**

- open editor
- select title line and write
- press backspace multiple times
- suddenly the cursor jumps to the last line and i am deleting the last characters of my last line.

**Expected behavior**

no cursor jumping

**Screenshots**

![dev-cursor-jump-error](https://user-images.githubusercontent.com/649209/63303417-13abcd80-c2e0-11e9-934b-664d604a39c1.png)

**Desktop (please complete the following information):**

- OS: Win7x64
- Browser: Waterfox 
- Version: 56.2.12

**Additional context**

please don't go with all the over-javascripting hype. its a normal form, a normal textbox where i enter multiline text.

**Comment by jessleenyc** [comment]
Strange. Thanks for reporting.

**Comment by c33s** [comment]
maybe it has something to do with https://addons.mozilla.org/en-US/firefox/addon/textarea-cache/ i can't tell for sure because this error happens at random. will have a look in my future post while i disable this addon and report back

**Comment by maestromac** [comment]
This also happens to me once every bluemoon.

**Comment by c33s** [comment]
had the bug again but without the textarea cache plugin. so this addon wasn't the cause

**Comment by cmgorton** [comment]
Hey @c33s . Is this something you have experienced lately? Happy to keep this issue open if it is and highlight it to our community to work on.

**Comment by c33s** [comment]
i reopen it if i encounter it again.
