### ISSUE TITLE
Consider Adding End to End (E2E) Testing to the Deployment Pipeline

### ISSUE THREAD

**Issue by maestromac** [forem/forem#382]
@nickytonline commented on [Thu Jul 19 2018](https://github.com/thepracticaldev/dev.to_core/issues/602)

# Story - Consider Adding End to End (E2E) Testing to the Deployment Pipeline

@benhalpern @maestromac @Zhao-Andy @jessleenyc et all.

Just wanted to open a discussion here about E2E testing.

There's a lot going on on the site. The backend has lots of unit tests, the new front-end stuff has unit tests and snapshot testing, but there is no E2E testing in place.

When I worked at McAfee, it was essential to have E2E testing in place because we were working on a password browser extension. We had to be certain the UI functioned all the time. In the case of a web site, it's a good idea as well, but a lot of times it's omitted due to lack of resources/time. Not good excuses, but that's the reality I've lived through at other jobs. There's also a burden of maintaining them.

Having said that, they help you spot regressions fairly quickly and it allows you to test full workflows, e.g. on-boarding. In terms or resources, I think we'll have those once the code is fully open sourced. I have a feeling a few people will want to contribute to the code base. 😉

I think it's a win win honestly. The site will be more stable because of the E2E tests and there will be so many tests to do that it will be an easy way for new contributors to get some PRs in (provided we onboard properly).

If we decide to go ahead with this, we'll need to decide on an E2E testing framework. I'm personally leaning towards [Cypress](cypress.io), but let's make this part of the discussion.

---

@benhalpern commented on [Fri Jul 20 2018](https://github.com/thepracticaldev/dev.to_core/issues/602#issuecomment-406684377)

Yeah let's do this. I haven't seen any reason to not go with Cypress. It's definitely been on my list of things to try and haven't seen anything better.

Rails has its own concept of E2E testing which we make some use of but it's been such a pain in the ass I've never had the patience to be good at this part. I'll leave this topic open for anyone to argue that we should stick into this world as opposed to Cypress.

Either way, yeah I'm in agreement with the approach to lead to stability, as long as we don't get too heavy-handed to the point where we need to change 10 files for every change. Let's try to walk the line the right way.

---

@nickytonline commented on [Sun Jul 22 2018](https://github.com/thepracticaldev/dev.to_core/issues/602#issuecomment-406902404)

Also, it currently only supports Chrome, but [FireFox support is on it's way](https://github.com/cypress-io/cypress/issues/1096).

---

@nickytonline commented on [Thu Aug 16 2018](https://github.com/thepracticaldev/dev.to_core/issues/602#issuecomment-413710291)

@maestromac, can you migrate this issue over? I'll put up my PR in my branch later tonight or tomorrow. Thanks.

**Comment by maestromac** [comment]
Not Stale

**Comment by nickytonline** [comment]
Not Stale

**Comment by nickytonline** [comment]
Although I am a fan of Cypress, it would be silly not to consider alternatives as discussed in https://dev.to/devteam/cypress-vs-kj, specifically, [Test Café](https://devexpress.github.io/testcafe/).

Cypress has [FireFox support on their road map](https://github.com/cypress-io/cypress/issues/310), but that still leaves out Safari.

It would be good to decide on a few flows to write, perhaps login, search and maybe creating a post and compare the experience in the two e2e test tools.

It would probably make for a great last Hacktoberfest push for anyone interested.

![OK, I'll give it a try](https://media.giphy.com/media/XdreKrQI1LjcQ/giphy.gif)

**Comment by rhymes** [comment]
I'm +1 on exploring this. I think we shouldn't take months to decide but also as any tool these take investment and switching from one to the other down the line is not going to be painless, so we might as well evaluate them now

**Comment by nickytonline** [comment]
@vikmy, since you mentioned Test Café in the post I reference above, would you be interested in writing up a few tests to show us how it would be if we were to go with Test Café?

Or maybe @chrisvasqm? I see you wrote a post about Test Café a little while back, https://dev.to/chrisvasqm/e2e-testing-with-testcafe-17jl.

Or basically, anyone else who has experience with Test Café.

Thanks in advance!

**Comment by rhymes** [comment]
@maestromac might have ideas about which areas to start focusing on for e2e

**Comment by nickytonline** [comment]
Just dropping playwright into the discussion here even though it's early days for playwright, https://github.com/microsoft/playwright/

**Comment by nickytonline** [comment]
Came across this Tweet thread tonight, https://twitter.com/bahmutov/status/1224195089062400002. Including the picture as well, but it is a screenshot from Gleb’s Tweet. Apparently multi-browser support is very close to being released for Cypress.

![650A0776-4C13-426D-9C4E-26BEEA7AA159](https://user-images.githubusercontent.com/833231/73629224-6c69eb00-4620-11ea-868e-f9b5ffe06e83.jpeg)

**Comment by rhymes** [comment]
I guess we can wait then :)

**Comment by emgoto** [comment]
I was curious where DEV is currently at with e2e testing? I can see that Cypress [current supports Chrome / Edge / Firefox (in beta)](https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers).

**Comment by maestromac** [comment]
@emgoto we're still using RSpec + capybara at the moment. We definitely want to give Cypress a try but we haven't devoted resources to it yet.

**Comment by cmgorton** [comment]
Hey @nickytonline is this something we have still in the pipeline? Wondering if I should close this issue or keep it open :)

**Comment by nickytonline** [comment]
It's still open even though it's an issue. We're looking in to getting this up and running.
