### ISSUE TITLE
Integration with Keybase.io for identity proof

### ISSUE THREAD

**Issue by f-wong** [forem/forem#3876]
In the day and age where people can be anonymous, misrepresent themselves and/or spoof other identities, it would be neat if dev.to can also integrate with keybase.io in order for people to verify that this is indeed your account and no one else's.

Would also be nice to have a special URL box designation for the keybase URL as well.

https://keybase.io/docs/proof_integration_guide

**Comment by MatteoJoliveau** [comment]
I was looking into implementing this exact feature. There is an [official gem](https://github.com/keybase/prove_keybase) that provides this flow quasi out-of-the-box. Can this be of interest for DEV? I for sure would love to add my profile as a Keybase proof and I'm willing to submit a PR for this feature.

**Comment by ssimontis** [comment]
Weird, I was looking into Keybase last night too. I know there are a lot of similarish offerings like Okta and Auth0, does Keybase offer something killer that the other solutions don't? I am most familiar with Auth0.

**Comment by MatteoJoliveau** [comment]
@ssimontis not quite. Keybase is not an authentication provider, rather it's a platform for cryptographic identities. You create a profile and link it with several other social platforms (Twitter, GitHub, hopefully DEV), domains you own, and many other ways to prove that the Keybase profile is indeed your own. Keybase's core is managing PGP keys, allowing you to upload and securely store you private key, as well as distributing your public key so that people can use the aforementioned identities to verify that something has been indeed signed or encrypted by you.

It is basically a social network-powered alternative to the web-of-trust previously used by PGP

**Comment by MatteoJoliveau** [comment]
I'm almost done with this integration, may I open a PR afterwards @Zhao-Andy?

**Comment by jessleenyc** [comment]
@MatteoJoliveau yep, feel free to open a PR whenever you're ready!

**Comment by Leopere** [comment]
Oh definitely bring this.

**Comment by rhymes** [comment]
Adding these things about Keybase:

- [hello world, except keybase](https://jenngineering.glitch.me/hello-world-except-keybase/)
- KeyBase, after they pivoted to gifting people Stellar Lumens and rebranding as a chat, seems to be harboring/fostering a toxic community: 
  - https://twitter.com/alicetragedy/status/1197482494280507393
  - https://twitter.com/anildash/status/1201196535360507904

**Comment by Leopere** [comment]
I mean Keybase is blockchain-backed, to begin with if I recall correctly.

**Comment by nealmcb** [comment]
Keybase is very well thought out. It uses hash chains / merkle trees / signature chains etc, like tons of apps over the decades, and integrates with Stellar, which is blockchain-based, but Keybase itself is not "blockchain-based" in any useful, common meaning of that term (i.e. decentralized consensus).

I think integrating dev.to with Keybase would be a good step. Thanks, @MatteoJoliveau. How's it going?

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
