### ISSUE TITLE
[RFC] Adding an issue tracker to the sidebar

### ISSUE THREAD

**Issue by jacobherrington** [forem/forem#3921]
**Is your feature request related to a problem? Please describe.**

Not really! I'd just like to find a way to direct more users to the codebase.

**Describe the solution you'd like**

I'd like to see an issue tracker added to the dev.to sidebar or as a key link:

<img width="311" alt="Screen Shot 2019-09-02 at 12 45 02 PM" src="https://user-images.githubusercontent.com/11466782/64129082-85275980-cd7f-11e9-8f3e-57f9787e00ed.png">

In particular, I think it'd be ideal to highlight issues from this repository that are marked "good first issue" or "help wanted" so that people looking for opportunities to contribute to Open Source (or dev.to specifically) will be directed to issues they can help with.

**Describe alternatives you've considered**

Just a link to https://github.com/thepracticaldev/dev.to/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 might work in the short term, but I think it'd be great if we could actually highlight individual issues with the GitHub API.

**Additional context**

I'm just looking for feedback on this before I implement something!

**Comment by jacobherrington** [comment]
I'm gonna start hacking on it 😉

**Comment by cmgorton** [comment]
Hey @jacobherrington I see this has been around for awhile now. Is this something you would like to keep open and create an RFC for?

**Comment by jacobherrington** [comment]
@cmgorton This is pretty old - either option is fine with me. I like the idea of making the open source side of Forem more visible, but I'm not sure we need to handle this right now.
