### ISSUE TITLE
Begin internationalization and localization work; establish a pattern for all g11n/i18n work

### ISSUE THREAD

**Issue by jacobherrington** [forem/forem#3929]
**Is your feature request related to a problem? Please describe.**

Virtually none of the content or text in the application is taking advantage of i18n, which leaves us in a less-than-ideal space when it comes to accessbility and the goal of allowing [self hosted instances of this application](https://docs.dev.to/self-hosting/).

**Describe the solution you'd like**

Ideally, most of the application is wrapped in some kind of i18n library that allows us to make dev.to more accessibile to people who would prefer to navigate the site in a language other than English.

Secondarily, doing this _might_ be a stepping stone to an easily customizable experience for those who wish to self-host (a la Devise).

If we plan to implement some kind of i18n/g11n tool, then it's prudent that we discuss the best approach for our implementation. This will likely have a siginifcant impact on a lot of the UI development done on the application going forward, so it's a good idea to pick an approach that is scalable and easy to mimic in new contributions.

**Describe alternatives you've considered**

I opened #3892 with the goal of wrapping all of the static pages in i18n. Based on feedback from @rhymes I'm opening this issue to facilitate a larger discussion before implementation.

Here is a version of my comment on this issue from that PR:

> This PR was motivated by a few things: language accessibility, maintainability, and customization.
> 
> _Language Accessibility and Maintainability_
> 
> I'm less concerned with ease of maintenance with this change and more concerned with the potential for language localization and felt that the static pages were the best place to begin testing an approach.
> 
> When it comes to keys, I agree with most of the points you made, but I'm ignorant when it comes to tooling/techniques to help us with maintaining these YAML files; I'd love some suggestions.
> 
> Personally, I'd like to see most of the content (excluding UGC) in the application wrapped in i18n even if there is no specific goal to support another language at the moment because it is much easier to establish a pattern early than retrofit an application with support for other languages.
> 
> Also, due to the Open Source nature of this project, implementing an i18n framework allows native speakers to add translations if they'd like to have them -- much like the ruby-lang site or https://github.com/solidusio/solidus_i18n. Later, if sufficiently skilled speakers are willing, the project can choose to support a language officially.
> 
> In terms of accessibility, a little is better than nothing... I think, right?
> 
> _Customization_
> 
> I also see this as a step towards the idea mentioned in Self hosting DEV. People who want to host an instance of the application might be able to take advantage of an i18n framework to swap content out easily, for example, if they have their own preferred CoC or want to change the text on the about page without writing too much code.
> 
> Further features around i18n would need to be built, but doing some work around i18n now would be a step in that direction.
> 
> Ultimately, as I mentioned earlier, it would probably be better to lay a foundation for g11n/i18n now. To your point, we need to make sure we are laying the right foundation now. I'd love to hear your thoughts on how I can align this PR with your perspective on this kind of feature.
> 
> If we determine closing this PR is the best course of action, I don't see it as wasted effort because it allowed me to get more familiar with the project, which was all I intended to do when I made this change.

**Additional context**

The primary goal, imo, should be to make it simple for volunteers to contribute new translations as they see fit. That would take a siginifcant amount of the responsibility off of the core team. At a later point, the core team should elect if any languages will be officially supported.

**Comment by jacobherrington** [comment]
The goal of this issue is to establish an ideal pattern to follow, which will be maintainable as the project grows. 

Personally, I've never had the opportunity to lay the groundwork of an i18n implementation, so my opinions are limited.

**Comment by 12vanblart** [comment]
Team Trash Panda (Raccoon) Mod Chat was talking a bit about possibly adding a `lang` or `language` option to frontmatter to allow users to filter their own posts to different languages.

**Comment by cmgorton** [comment]
Closing this in favor our the internal issue https://github.com/forem/internalEngineering/issues/297

Hopefully in the future we can discuss where this will fit in with our roadmap and create an RFC.
