### ISSUE TITLE
Need Contrast in Follow Option in the Dark Mode

### ISSUE THREAD

**Issue by realabbas** [forem/forem#3968]
Invisibility of the **Following Option** in the Dark Mode for Background Color **#093656**

 
![Screenshot (1082)](https://user-images.githubusercontent.com/43527087/64477981-74cc1000-d1bf-11e9-8aac-df3f7b697c03.png)

It would be great if the inner text is of White Color or of Opposite Contrast.

**Comment by Link2Twenty** [comment]
This isn't a theme thing. The user Gajus has chosen to set the button colour to #093656 and has also chosen to leave the button text colour as default which, on this page, is always #0a0a0a because of the `cta` styles.

https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/scaffolds.scss#L113-L120

 🙂

**Comment by realabbas** [comment]
Great. But I was just thinking that the default color should be set in such a way that whatever button colour is chosen, the button text should be visible.

**Comment by Link2Twenty** [comment]
I see 🙂
ref: #735

**Comment by realabbas** [comment]
Okay, that makes sense. 👍

**Comment by maestromac** [comment]
I was wondering why this is only happening on article page
![Screen Shot 2019-09-10 at 11 05 37 AM](https://user-images.githubusercontent.com/15793250/64625926-fe93fd00-d3ba-11e9-8f10-7c19a462c9c4.png)
vs
![Screen Shot 2019-09-10 at 11 05 55 AM](https://user-images.githubusercontent.com/15793250/64625944-03f14780-d3bb-11e9-95bf-0aee3fd7ae26.png)

the color property of sidebar is being overwritten by [this css property](https://github.com/thepracticaldev/dev.to/blob/master/app/views/articles/_sticky_nav.html.erb#L8) but the content of user's profile page isn't. Something else to note here is the user profile's external links are not being shown properly either in dark mode.

What your recommended approach to fix this @benhalpern ?

**Comment by ludwiczakpawel** [comment]
Fixed.
