### ISSUE TITLE
Error when uploading videos

### ISSUE THREAD

**Issue by joelvarty** [forem/forem#3994]
**Describe the bug**

When I tried to upload a video, I didn't see any message when the video was finished uploading.

**To Reproduce**

Upload a video.

**Expected behavior**

See a message that says the video was uploaded or there was an error.

**Screenshots**

![image](https://user-images.githubusercontent.com/4520625/64564685-19656380-d320-11e9-8b6e-d92f64c82d8c.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Safari
- Version: 2019

**Comment by maestromac** [comment]
Thanks for raising this @joelvarty !

I was able to reproduce this issue. I believe this issue has to deal with the redirecting as supposed to the upload process. Did you see an unpublished post with your video in your dashboard?

**Comment by joelvarty** [comment]
I did!  I ended up deleting it.
