### ISSUE TITLE
RSS feed - fetch issues

### ISSUE THREAD

**Issue by krishnadalal12** [forem/forem#3996]
**Describe the bug**

 I am experiencing issues fetching new content from my RSS feed. It says the content was last fetched September 4th but I see no new drafts in my dashboards.

**To Reproduce**

 https://dev.to/settings/publishing-from-rss
 Enter the RSS feedlink
 press refresh 
 see no new blogs in my dashboard 

**Expected behavior**

 no new blogs from the RSS feed in our dashboard. 

**Screenshots**

![image001](https://user-images.githubusercontent.com/49325219/64567421-0b5a1780-d30d-11e9-8683-5ae83b007670.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Google Chrome 
- Version: 75.0.3770.14

**Smartphone (please complete the following information):**

- Device: NA
- OS: NA
- Browser: NA
- Version: NA

**Additional context**

**Comment by Bhupesh-V** [comment]
Did clicking on **Fetch Feed Now** work?

**Comment by krishnadalal12** [comment]
Hi,
No, it did not. I just tried and I still see the same no new articles from the feed.
[cid:image001.png@01D56887.A65994E0]

Cheers,

Krishna Dalal
Developer Marketing Specialist
Krishna.dalal@okta.com
[Okta • Connect everything]<https://www.okta.com/>

**Comment by krishnadalal12** [comment]
Thank you!

Krishna Dalal
Developer Marketing Specialist
Krishna.dalal@okta.com
[Okta • Connect everything]<https://www.okta.com/>

**Comment by dennislwm** [comment]
I am having a similar issue when I click on "Fetch Feed Now". It says the content was last fetched October 6 (this date does not get updated even though its October 16).

**Comment by dennislwm** [comment]
OS: Windows 10 Pro
Browser: Google Chrome
Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by Zhao-Andy** [comment]
Hi @krishnadalal12 and @dennislwm, sorry for the late reply! Are you two still having this issue?

**Comment by krishnadalal12** [comment]
Hi Andy,

Yes, there is usually a delay and not all the content gets pulled from the RSS feed.

Cheers,

Krishna Dalal
Developer Marketing Specialist
Krishna.dalal@okta.com
[Okta • Connect everything]<https://www.okta.com/>

**Comment by aaronpowell** [comment]
Going to bump this myself, I haven't had articles sync'ed from my RSS feed in about 2 weeks. I've tried to manually fetch the feed (done multiple times over multiple days) and I've tried removing/re-adding the feed (again, multiple times).

**Comment by maestromac** [comment]
Sorry for the late response @aaronpowell . I took a look at your feed and it seems like it was synced recently. I will further investigation to see what might be causing feed not to sync.

**Comment by rhymes** [comment]
@krishnadalal12 sorry for the delay, I was able to successfully import https://feeds.feedburner.com/OktaDeveloperBlog - please check once more

![Screenshot_2021-02-19 Dashboard - Ben Halpern Community 🌱](https://user-images.githubusercontent.com/146201/108536520-d5300e00-72dc-11eb-9bec-41d64e56639c.png)

I manually checked that there are exactly 8 items in the feed and they were all imported.

@aaronpowell sorry to you as well about the delay. I checked, your feed is being imported correctly. I can both see the posts in https://www.aaron-powell.com/index.xml and on your DEV's page https://dev.to/aaronpowell - the latest time it fetched was  today. 

I'm going to close this issue as there seems not to be anything more to be done.
