### ISSUE TITLE
Chat doesn't extend to its frame on Firefox iOS

### ISSUE THREAD

**Issue by rhymes** [forem/forem#4024]
**Describe the bug**

DEV Connect doesn't occupy the entire window frame on Firefox iOS

**To Reproduce**

1. Go to https://dev.to/connect
2. Notice how the chat doesn't fully extend to the entire page, like it had a margin bottom preventing it to fully use the browser window. 

This doesn't happen on Firefox for Android 

**Expected behavior**

Expect the chat to not be restricted to the upper part of the frame 

**Screenshots**

![118F7848-E86F-4BBC-BF90-C27EF3C660F7](https://user-images.githubusercontent.com/146201/64904557-fc3be680-d6cb-11e9-858b-a207506e886a.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone 8
- OS: iOS 12.4.1
- Browser: Firefox 
- Version: 19 build 16042

**Comment by Clarity-89** [comment]
Can reproduce on Chrome in responsive mode. Not sure if it's a bug or a feature tho. There are a few containers with calc height.

**Comment by narender2031** [comment]
@rhymes I think this issue will be resolve in this PR 
https://github.com/thepracticaldev/dev.to/pull/8829/files#diff-939505ce9f76e33dcd9c7f67fc871143R717

**Comment by rhymes** [comment]
@narender2031 this is how it looks for me, where there's the red line is empty space and the chat occupies half of the screen basically :-/

![IMG_5238](https://user-images.githubusercontent.com/146201/86096259-5703ca80-bab3-11ea-8574-612384413698.png)

**Comment by BogDAAAMN** [comment]
Same here on **Safari 13** (on iOS 13.4.1) and reproduced on **Firefox 78.0.2** (on MacOS 10.14.6) on different sizes.

I kept looking to fix the problem, but can't find anything. If anyone has any pointers I would love to jump in and help.

![dev to_connect](https://user-images.githubusercontent.com/22895284/88228363-5e139800-cc6f-11ea-86a0-792b34c4e1db.png)

**Comment by sarthology** [comment]
@rhymes assign this to me.

**Comment by rhymes** [comment]
Done, thank you! @sarthology

**Comment by BogDAAAMN** [comment]
omg @sarthology that's perfect! thank youuu
