### ISSUE TITLE
Social icon color is always different from what is defined for it.

### ISSUE THREAD

**Issue by realabbas** [forem/forem#4027]
**Describe the bug**
 In the dark theme, the social icon color is always different from what is defined for it. 

In the  **app\views\users\show.html.erb**

`.night-theme .profile-details .social .icon-img path {
            fill: white;
          }`

**Expected behavior**
Now look at this image, the property is always set to white, but it is not reflecting on the social icons, they are still black. 

**Screenshots**
![Screenshot (1100)](https://user-images.githubusercontent.com/43527087/64910608-d6e3c280-d735-11e9-9d95-eecb62d90d26.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version:  76.0.3809.132 (Official Build) (64-bit)

**Additional context**

**Comment by Clarity-89** [comment]
This is actually an issue with the `HexComparer`, which in this case fails to provide an appropriate brightness adjustment for the smallest value from user's background and text colors (at least that's how I understood what it does). 

@realabbas what colors do you have in your settings for the text and background?

**Comment by realabbas** [comment]
> This is actually an issue with the `HexComparer`, which in this case fails to provide an appropriate brightness adjustment for the smallest value from user's background and text colors (at least that's how I understood what it does).
> 
> @realabbas what colors do you have in your settings for the text and background?
> 
> Edit: Sorry, my bad, this is actually using the colors from the profile, which is being viewed at the moment.

Background Color : #E23737
Text Color: #FFFFFF

@Clarity-89

**Comment by emgoto** [comment]
Looking at Chris's profile now, maybe this one has been fixed:

![image](https://user-images.githubusercontent.com/33337378/87852030-d3b2f780-c941-11ea-8cdf-ee8e2627cdcb.png)

**Comment by rhymes** [comment]
@emgoto this depends on the interaction between custom colors defined in one's profile and the theme of the visiting user. Not sure if it's completely fixed.

@realabbas can you confirm?

**Comment by realabbas** [comment]
> @emgoto this depends on the interaction between custom colors defined in one's profile and the theme of the visiting user. Not sure if it's completely fixed.
> 
> @realabbas can you confirm?

Yes @emgoto this issue has been resolved.

**Comment by rhymes** [comment]
Thanks @realabbas and @emgoto !
