### ISSUE TITLE
Allow Org Members and Admins the Ability to See Org Followers Count

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#4048]
**Is your feature request related to a problem? Please describe.**

An org member recently contacted us, asking if there is a way to view org follower count as an org member. It appears that there isn't.

**Describe the solution you'd like**

As an org member (and org admin), I think it'd be great to be able to access org follower count and total views from the user dashboard here: https://dev.to/dashboard. Or perhaps the user would access their org dashboard by typing in something like this: https://dev.to/dashboard/orgname. The org dashboard wouldn't be public, but only accessible to members of the org.

**Comment by lucianolima00** [comment]
Hey @michael-tharrington, I'd like to do this issue

**Comment by lucianolima00** [comment]
@michael-tharrington already have a dashboard for the organizations and is restrict to the admin so the dashboard should be avaliable to the members too? In that case the "followers" tab should be of the organization when the org's dashboard is showing?

**Comment by lucianolima00** [comment]
@michael-tharrington about how will be showing the followers count, I suggest to be in a sidebar instead of create a dashboard page just to show a single information. I was thinking in something like that: https://imgur.com/a/2AYkMLz

**Comment by maestromac** [comment]
Thanks for pointing that out @lucianolima00 . We should first make it easy to convey to the user browsing `/dashboard` the organization that they are apart of. @benhalpern may have more thought on this.

**Comment by jessleenyc** [comment]
Spoke with the team and we'd like to swap the placement of these two rows: posts/follower/following and personal/org. Once we do that, we'll want the numbers to be updated appropriately. 

@lucianolima00 thanks for the mock up -- i think the sidebar works for desktop but we'd have to find a way to collapse it in mobile. What I described should take care of that :)

**Comment by michael-tharrington** [comment]
@lucianolima00 I'm so sorry for missing your comments above! Just to say, really appreciate you picking this up!

**Comment by alequetzalli** [comment]
@jessleenyc do we have updated info on where this is at?

**Comment by keyuls** [comment]
What is the update on this feature?

**Comment by cmgorton** [comment]
The number of followers for an org can be seen at dev.to/dashboard/analytics/org/[org number]
