### ISSUE TITLE
Embedding dev.to comment in Dev.to results in broken HTML

### ISSUE THREAD

**Issue by shushugah** [forem/forem#4079]
**Describe the bug**

On my post a regular dev.to comment was posted (albeit with Japanese characters in their profile) but when I embed their comment in my profile it shows broken HTML 4 tags

post (broken): https://dev.to/shushugah/gitlab-hacks-28cg
comment (not broken: https://dev.to/lukeshiru/comment/e7dd 

**Screenshots**

<img width="712" alt="Screenshot 2019-09-22 at 17 54 52" src="https://user-images.githubusercontent.com/7111514/65390801-090ea900-dd62-11e9-8984-dd4fd58f26e9.png">

**Comment by Eli-Schei** [comment]
I think this might be solved? 

I tried to re-create the bug, but all comments are displayed nicely. Even the one from the original bug here. 
When I inspect the html in the original post - with the broken comment - the html structure is completely different from how it is when I add a comment in a new post today. 
Image of how it looks when I try to embed the comment today. 
<img width="667" alt="thinkItsFixed" src="https://user-images.githubusercontent.com/60283283/117276454-350b6f00-ae5f-11eb-83a6-b46d1ebc73a1.png">

**Comment by cmgorton** [comment]
> I think this might be solved?
> 
> I tried to re-create the bug, but all comments are displayed nicely. Even the one from the original bug here.
> When I inspect the html in the original post - with the broken comment - the html structure is completely different from how it is when I add a comment in a new post today.


Great! Figuring out that it is no longer a bug totally still counts! If you want to write up what you did in the template mentioned in the Bug Smash Post we will definitely still reward you for closing this bug. https://dev.to/new/devbugsmash 🐛 Thank you for helping us clean up the repo. 
![High five](https://media.giphy.com/media/l0unkiodQqmA3lPO5e/giphy.gif)

**Comment by shushugah** [comment]
Thank you! I edited my post by adding a white space, to trigger/force a new render operation and it works now.
