### ISSUE TITLE
Post editor unusable in Microsoft Edge

### ISSUE THREAD

**Issue by CAD97** [forem/forem#4105]
**Describe the bug**

Entering text in the markdown editor (both v1 or v2) causes the cursor to jump to the end of the text box in Microsoft Edge.

**To Reproduce**

1. Go to <https://dev.to/new>
2. Enter some text in the text box
3. Move the text cursor to the beginning of the text area (front matter works for v1)
4. Resume typing
5. Note that the cursor jumps to the end of the text area after a single keystroke

**Expected behavior**

The text cursor to remain in place like other text areas.

**Desktop (please complete the following information):**

- OS: Windows 10 version 1809 (OS Build 17763.737)
- Browser: Microsoft Edge 44.17763.1.0 (Microsoft EdgeHTML 18.17763)

**Comment by jessleenyc** [comment]
Hey @CAD97! We think this should be fixed now. Is it still an issue for you?

**Comment by BrianLakstins** [comment]
Once logged in with GitHub on Edge, not much works, including the process to write a new article.  I searched for issues with Edge and only found this one.  If it's just me, then no worries - I can use another browser or not be logged in.

![ApplicationFrameHost_2019-11-04_16-44-56](https://user-images.githubusercontent.com/2887390/68160904-bb6d8a80-ff22-11e9-9370-117d9d4f2b4b.png)

![ApplicationFrameHost_2019-11-04_16-45-59](https://user-images.githubusercontent.com/2887390/68160910-be687b00-ff22-11e9-9e66-8fba666f0948.png)

**Comment by CAD97** [comment]
The actual text editor box issue as described in the OP is fixed.

However, the feed does not load and the buttons at the buttons of the post editor do not appear in Edge anymore for me either (when logged in).

**Comment by nickytonline** [comment]
It sounds like it might be a Windows only issue. I’ve been using Edge Beta for Mac on Catalina and iOS for a few weeks now with no issues to the site. I think I may have experienced the editor issue briefly, but aside from that, no issues.

If you run Edge without extensions enabled or in incognito mode, do you still have the issue?

**Comment by CAD97** [comment]
@nickytonline is Edge Beta the version running on Chromium? This is specifically the EdgeHTML version. (Also, it's InPrivate mode for Edge, and it behaves the same there.)

**Comment by nickytonline** [comment]
Ahh, my bad. I thought you meant the Chromium version. I’ll see myself out. 😬

**Comment by rhymes** [comment]
@CAD97 I have a "side question": now that Microsoft Edge 79 (based on Chromium) is officially released, do you think it's still worth pursuing fixes on EdgeHTML? Do you know if Edge Windows gets automatically updated?

**Comment by CAD97** [comment]
@rhymes Edge is treated like a Microsoft Store app IIRC and gets updates through it, rather than through Windows Update. Either way, Edge will, eventually, update on all user machines.

I remember seeing [articles](https://redmondmag.com/articles/2018/12/10/edgehtml-continues.aspx) that indicate that while Edge is moving away from EdgeHTML/Chakra, those still will power UWP and PWAs installed from the Microsoft Store (though they may gain the ability to request Edgium in the future?).

My personal opinion is that the default browserlist config of `> 0.5%, last 2 versions, Firefox ESR, not dead` is a good target to target for compatibility, and is a fine balance between effort to support and benefit from being portable. That would mean putting developer effort towards making EdgeHTML work until it's dropped back below a 0.5% market usage and another "major" Edge release is out.

**Comment by rhymes** [comment]
@CAD97 thanks for the info! I think we've more or less de-prioritized issues related to Edge HTML because of Edge Chromium coming out. 

I'm going to ping @benhalpern about this

**Comment by rhymes** [comment]
@nickytonline pinging you about this, I think we should close the issue but keep in mind that we still need to declare which browsers we actually support
