### ISSUE TITLE
Separate/group articles by level 

### ISSUE THREAD

**Issue by ilicmarko** [forem/forem#4131]
**Is your feature request related to a problem? Please describe.**

Not particularly a problem but lets say a frustration. I like the idea of the "openes" dev.to brings to the table, anyone can post anything. That is great and is helpful for the community. On the other side for us "veterans" that are really not interested in 90% of the posts related to "how to position [insert element]" we would like to see some kind of a filter.

**Describe the solution you'd like**

A kind of a filter or a section even where we can get the low level stuff. Because I usually go to personal blogs to find articles like that, even if the authors have them in dev.to. I know there are tags, but they are optional and to many people put `#advances` tags because they don't remember.

This can be solved by have a chose to which section you write. Recently I applied for a conference talk and they had two options:

- normal track
- advanced track

Which is a really great idea for a conference and also would apply for dev.to.

**Additional context**

I think this will also push beginners to leap into this section as it would show them they are "advanced".

Keep up the great work.

**Comment by jessleenyc** [comment]
Hey @ilicmarko, thanks for the issue. This isn't exactly what you're asking for but could be helpful if you don't know about it already: if you visit your [settings](https://dev.to/settings/misc), you can input your experience level. The feed will showcase more advanced posts if you've indicated that you have a lot of coding experience. This also relies on users or moderators ranking their posts (which isn't being used as often as we want it to be yet) but hopefully this helps a bit.

**Comment by ilicmarko** [comment]
Hmm great option, my bad for missing that. The idea with this is to "force" users to choose what level they are writing for (red or blue pill). Because as you said people are not using it that often as it is optional or **maybe not even aware of it**. I am not sure if this will impact the user flow (UX) when a new post is being created. Looking at it personally I wouldn't mind a nice "split screen" view where I simply choose a level.

Anyways thanks for getting back.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
