### ISSUE TITLE
Framed Image liquid tag

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#4181]
**Is your feature request related to a problem? Please describe.**

As a user I might want to add an image to the site and automatically "frame" it in another image. I just think this would be kind of fun.

What I mean is that I can add an image from a URL that will then get added into another image based on existing templates.

A template like this:

![](https://placeit.net/uploads/stage/stage_image/4613/default_a10765base.png)

So if I had a picture of a puppy I could put it into that template using two liquid tag params like such...

`{% framedimage https://i.imgur.com/mygreatpuppypic.jpg iphone-in-hand %}`

I just think this could be a lot of fun.

**Describe the solution you'd like**

The implementation as I'm seeing it would actually be a pretty straightforward use of Cloudinary, which we already use all over the site for image manipulation and serving.

Details here...

https://cloudinary.com/documentation/image_transformations#image_and_text_overlays

It would plug into the Cloudinary Ruby library in some way like this...

```ruby
cl_image_tag("iphone-in-hand.jpg", :overlay=>"https://i.imgur.com/mygreatpuppypic.jpg", :width=>0.9, :gravity=>"north_east", :opacity=>70, :effect=>"brightness:50", :crop=>"scale")
```

**Describe alternatives you've considered**

Alternative to the Cloudinary API thing, it _might_ make sense to thread the two images together using HTML and CSS instead. That might be the more appropriate way to do this.

**Additional context**

The way I see this is that we could have a fun library of "frames", each of which could have an associated slug of sorts. The slug is used as the second argument for the liquid tag.

This feature could _occasionally_ be useful, but will always be fun. And it stretches the magic of our liquid tag format.

Here is an example of a recently merged liquid tag PR: https://github.com/thepracticaldev/dev.to/pull/3801 for reference on how these are created.

**Comment by eToThePiIPower** [comment]
Hi, I'd be interested in taking a look at this issue.

After taking a cursory read at the [Cloudinary Rails docs](https://cloudinary.com/documentation/rails_image_manipulation), it looks like a a "layer_apply" might be needed to offset the inner image over the "frame", and the `x` and `y` offsets will have to be customized based on the template (unless all of the templates have the frame in the same location).

So something like:
```ruby
template_image = {
  url: "iphone-in-hand.jpg",
  framex: 40,
  framey: 50
}
cl_image_tag(template_image[:url], transformation: [
  [
    { overlay: "https://i.imgur.com/mygreatpuppypic.jpg" },
    { flags: "layer_apply", x: template_image[:framex], y: template_image[:framey] }
  ]
```

My first step would involve having 2-3 hard-coded template images that can be selected by an id. Allowing users (or admins) to add additional template images to a library would make sense as a follow-up I think?

**Comment by benhalpern** [comment]
@etagwerker I think that would be a great approach! If you want to break ground with this via a WIP pull request we could iron out the details as we go.

**Comment by etagwerker** [comment]
@benhalpern I'm assuming it was a typo in the auto-complete and you meant to tag @eToThePiIPower, right? 😄

**Comment by ledestin** [comment]
Would like to take on this issue.

**Comment by cmgorton** [comment]
Hey @ledestin We are working on changing how we approve feature requests and when the Forem team or contributors will take them on. 
I am going to go a head and unassign you to this feature for now while we work through our [new RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4). Thank you fo your help here!

In the meantime if you see any bugs you want to help squash let me know and we can assign you to them!
