### ISSUE TITLE
Choosing canonical_url source for the webhooks integration

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#4194]
Earlier we discussed that we need a setting so that users could choose the canonical_url source. The source could be: post's url on DEV, post url from the integrated website or url that user specified as a canonical_url.

Currently, we provide the `processed_canonical_url` as a part of the webhook events' payload and via the API. `processed_canonical_url` is either a canonical url that user has specified when creating a post or a DEV url (if the user has not specified a canonical_url). We expect the integrated website to set this canonical url on the posts' pages.
We could have a setting so that user could set a preferred source. If a user sets DEV as a preferred canonical url source, the logic will stay the same.
If a user specifies the integrated site as a canonical url source we should somehow get the information about the user's posts' urls from that generated website, store it, and display it on DEV.

So, the questions are:
- Do we need this feature (now)?
If we need it:
- How can we get the data about the generated site and the urls?

**Comment by emTr0** [comment]
Hello. Coming from #7972.

I noticed the slug for the integrated blog post is the exact same as the slug for the dev.to blog post.

For example:
[dev.to/emtr0/stretches-and-exercises-to-relieve-upper-mid-and-lower-back-pain-2dd6](https://dev.to/emtr0/stretches-and-exercises-to-relieve-upper-mid-and-lower-back-pain-2dd6)

[emtr0-dev-stackbit-0aa86.netlify.app/posts/stretches-and-exercises-to-relieve-upper-mid-and-lower-back-pain-2dd6](https://emtr0-dev-stackbit-0aa86.netlify.app/posts/stretches-and-exercises-to-relieve-upper-mid-and-lower-back-pain-2dd6/)

If this is the expected outcome every time, maybe you can just create the "Posted on my blog" and canonical source based on that pattern where `slug` is a variable in `[Posted on my blog](emtr0-dev-stackbit-0aa86.netlify.app/posts/slug/` for the dev.to to reference.

**Comment by lightalloy** [comment]
Closing the issue, it's not relevant any more because stackbit integration was removed.
