### ISSUE TITLE
Publishing from multiple RSS feeds

### ISSUE THREAD

**Issue by daniel-werner** [forem/forem#4208]
**Is your feature request related to a problem? Please describe.**

I have multiple blogs where I write posts, and I'd like to collect all my articles to dev.to

**Describe the solution you'd like**

I'd like to have ability to add multiple rss feeds to fetch blog posts from

**Describe alternatives you've considered**

Change the RSS feed, fetch the articles from one blog, and switch back to another.

**Additional context**

**Comment by jtemporal** [comment]
I'd love to have this too.

**Comment by jessleenyc** [comment]
For now, you can pull from each feed by updating the link in the RSS field. Not an ideal flow, but should help you import those posts!
