### ISSUE TITLE
Webhooks to subscribe to organization articles

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#4230]
This issue is a part of the #3715 task

I see a couple of use cases to subscribe to the org articles:
1) A user belongs to an org and wants to subscribe both to their own articles and some (or all) of the orgs' articles they belong to
2) Org admin may want to create a site to subscribe only to the org articles

So, the webhook should be able to subscribe to the user articles, organization(s) articles or both.

Here is an approximate list of actions:

- change webhook endpoints schema
  - need to add `organization_ids[]`
  - need to add a field whether to subscribe to user own articles
- send events accordingly to the new webhooks structure
  - if an action was taken on an article which was published under an org we should choose the corresponding webhooks and send events to them
  - add organization data to the event's payload

- additional checks when managing webhooks:
  - only org members (or admins?) should be able to create webhooks subscribed to its organization_id
  - webhooks should be subscribed to the user articles, or to the orgs article (not to nothing)

- user interface
  - user should be able to specify what content they want on their site (own content, and/or org(s) content) - not sure how would it look like. Maybe a form with these optons which we could send to the integrated site instead of a link.

- changes on the integrated site side
  - the api calls to register webhooks with the `organization_ids[]`
  - I suppose that the author should be specified, if there are articles of different authors on the site (when user subscribed to the org articles)
  - information about the org if an article was published under it

**Comment by NomanGul** [comment]
any update on this?

**Comment by lightalloy** [comment]
As far as I know, there are no plans to implement it right now. Maybe, @benhalpern @jessleenyc have other information.

**Comment by cmgorton** [comment]
Hey! I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
