### ISSUE TITLE
Upgrade to Preact X

### ISSUE THREAD

**Issue by hoangvvo** [forem/forem#4243]
**Is your feature request related to a problem? Please describe.**

No. This is just a recommendation to upgrade to React X

**Describe the solution you'd like**

Upgrade to React X

**Describe alternatives you've considered**

n/a

**Additional context**

I looked at the [Upgrade guide](https://preactjs.com/guide/v10/upgrade-guide), and there is not a lot of breaking changes. Is there any plan or can I create a PR for this?

Some of the needed changes to `dev.to` I'm awaring of:

:boom: Compat has moved to core
:boom: Remove the 3rd argument to render
:boom: (possibly if there are synced this.state) async setState

**Comment by hoangvvo** [comment]
I tried to do so in a closed PR, and as expected, a lot of things break (in the tests). But I think it might be the test library that causes the problem.

For example, `preact-render-spy` is using `preact-render-to-string` of `^3.6.3`. This will not work with Preact X as only `preact-render-to-string` `^5.0.0` must be used. https://preactjs.com/guide/v10/upgrade-guide/#upgrading-dependencies

**Comment by maestromac** [comment]
Thanks for this issue and trying to implement it @hoangvvo ! It might sense for us to do this after we upgrade our Webpacker (https://github.com/thepracticaldev/dev.to/pull/3887)

**Comment by nickytonline** [comment]
Preact also offers a migration too to move to Preact X. I have not tried it yet, but it is available here if you want to take a peek, https://github.com/preactjs/migrate-preact-x

**Comment by nickytonline** [comment]
I think I'll go ahead and do this before the webpack upgrade as the webpack upgrade is more involved.

**Comment by nickytonline** [comment]
Closing as the upgrade to Preact X is complete.
