### ISSUE TITLE
Login menu is disabled for my mobile phone (Chrome 56)

### ISSUE THREAD

**Issue by melezhik** [forem/forem#4280]
Hi dev.to devs! my login page is  broken again. I can see a black circle in the right upper corner, but it's not clickable, in normal state it should be clickable and shows me submenu with login/logout options.

Regards

**To Reproduce**

1. Open dev.to site in mobile browser
2. Try to log in
3. I can't log in because upper right menu is disabled for me. Just a black none clickable circle.

**Expected behavior**

There should be a circle which one if pressed shows submenu with login ( via github/twitter/ ... )

- OS:  Adroid
- Browser: Chrome 56.092
--

**Comment by melezhik** [comment]
Hi guys! Any news here?

**Comment by melezhik** [comment]
Hi guys. Any chance to fix it? Thanks

**Comment by rhymes** [comment]
@melezhik hi, what phone do you have? have you tried with other browsers? Didn't know there was a Chromium mobile version.

**Comment by melezhik** [comment]
Hi @rhymes.

Android 7.1.1
ZTE Z971

**Comment by rhymes** [comment]
@melezhik thanks! have you tried with other browsers? can you login with the Android default browser or Firefox?

**Comment by melezhik** [comment]
Browser - Chrome 56.092****

**Comment by rhymes** [comment]
@melezhik can you successfully login with any other browser? It's helpful to understand if we can isolate the problem to a single configuration. I kindly ask if you can try with some other Android browsers and see if you can login.

Thanks!

**Comment by melezhik** [comment]
My default browser V5.35* does not work either.

**Comment by melezhik** [comment]
And I don't have a Firefox on my phone. Just these two browsers - default and chrome.

**Comment by rhymes** [comment]
Could you try with Firefox? I think they are both sharing the same rendering engine.

It might be a bug in the Chrome rendering engine.

Let me know if you can succeed with Firefox!

**Comment by melezhik** [comment]
Unfortunately not. My phone's memory is full. I can't install new software.

**Comment by rhymes** [comment]
@melezhik mmm :( it might be an error related only to Chrome 56, I've tried with Chrome 77 in mobile mode and I can login. I'll see if I can find an older version of Chrome

**Comment by rhymes** [comment]
I've downloaded an old build of Chrome 56 and it's broken also on desktop. I'm not sure how to go about on solving this but I noticed this error in the console:

```text
Uncaught ReferenceError: filterXSS is not defined
    at getInitialSearchTerm (search.js?e687:62)
    at Search.componentWillMount (Search.jsx?4977:31)
    at setComponentProps (preact.umd.js?2f7e:469)
    at buildComponentFromVNode (preact.umd.js?2f7e:653)
    at idiff (preact.umd.js?2f7e:264)
    at diff (preact.umd.js?2f7e:225)
    at render (preact.umd.js?2f7e:720)
    at HTMLDocument.eval (Search.jsx?b9cb:8)
```

It looks like it has having troubles finding a global function. Not sure if this is related to the sprockets asset pipeline or webpack or the XSS library
