### ISSUE TITLE
CodeReview

### ISSUE THREAD

**Issue by gate3** [forem/forem#4324]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**"Where programmers share ideas and help each other grow."** The first line from the about page on dev.to . I strongly believe one of the best ways to help each other grow is through assistance with code reviews. Be it just a few lines of code or an entire repository. This will help devs on dev.to do better on interviews and become better in general. Developers should be able to submit repositories of code they wish reviewed as well as snippets.

**Describe alternatives you've considered**

**Additional context**

**Comment by jessleenyc** [comment]
@gate3 there are a few different ways people can submit code snippets on DEV right now. For example, you can embed an entire github repository or any files via codepen, glitch, repl.it, and much more. Can you be more specific with the request here?

**Comment by gate3** [comment]
Hi Jess, 

While this exists, it's not targeted at the use case I described. If I embed a code snippet or Github repo it comes as a post. I'm not sure it's appropriate to create ask for reviews on posts. What I have in mind is something more dedicated or targeted at code reviewing and feedback.
