### ISSUE TITLE
Filters for search

### ISSUE THREAD

**Issue by FeruzOripov** [forem/forem#4333]
**Is your feature request related to a problem? Please describe.**
When I search posts I'll get posts that ordered by positive reactions count. The problem is what if I want to get latest posts related to search keyword. For example, I wanted to check latest posts related to hacktoberfest, but when I searched it, I got posts with most reactions.

**Describe the solution you'd like**
I think there should be filters for search. For instance, latest posts or posts with most reactions, posts by some organization, etc.

**Comment by jessleenyc** [comment]
Yeah, I agree that makes sense. I _believe_ we wanted to move things over to preact before providing additional filters on search. For the specific example you described, you can see latest hacktoberfest posts by visiting https://dev.to/t/hacktoberfest/latest
