### ISSUE TITLE
DEV View Counter Caching Issues

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#4335]
A contributor recently pointed out that the view count on one of their articles stopped increasing even though they continued to receive reactions and comments on the post:

<img width="673" alt="Image 2021-01-26 at 6 11 14 PM" src="https://user-images.githubusercontent.com/16007075/105918427-e77e9b00-6001-11eb-9bdf-00fe47d452c8.png">

I pointed out that this sounded similar to https://github.com/thepracticaldev/dev.to/issues/1765, but the user mentioned a potential issue with caching:

<img width="674" alt="Image 2021-01-26 at 6 11 45 PM" src="https://user-images.githubusercontent.com/16007075/105918507-07ae5a00-6002-11eb-982c-dc98ca43bfb9.png">

I'm thinking this is likely worth looking into.

**Comment by jessleenyc** [comment]
We might not have accounted for certain edge cases (i.e. usernames changing which leads to the path changing). Definitely a good one to investigate if anyone has ideas here.

**Comment by rpostulart** [comment]
I notice the same, my counter is not increasing :(

**Comment by maleta** [comment]
Same happening for mine article.

**Comment by rpostulart** [comment]
Any progress on this? Will it be settled later or will we miss these counts?

**Comment by maleta** [comment]
I think the counter stopped counting after I updated the article.

**Comment by rpostulart** [comment]
Yes I have noticed the same now. As soon as you have published the article and then later updates a spelling mistake or so, then counter stops working

**Comment by rpostulart** [comment]
Any updates?

**Comment by xanderyzwich** [comment]
I've just hit this issue in the last week. After getting several reactions and multiple retweets of a post the view count has remained identical.

**Comment by mstruve** [comment]
@michael-tharrington do you have pictures of the counter that is not working for this? The ones linked are not loading and I think that info might be helpful to have if we have a shot at fixing this.

**Comment by michael-tharrington** [comment]
@mstruve unfortunately I'm pretty sure I updated the issue with the correct photos. I couldn't tell for sure, but this appears to be around the same time in 2019.

**Comment by michael-tharrington** [comment]
I think this is potentially a related issue - https://github.com/forem/forem/issues/8425

**Comment by mstruve** [comment]
Closing in favor of https://github.com/forem/forem/issues/8425 which has a lot more detail about this actual problem and I think will be better used to complete and fix it
