### ISSUE TITLE
Be able to turn a regular post into a video post

### ISSUE THREAD

**Issue by omenking** [forem/forem#4354]
**Is your feature request related to a problem? Please describe.**

Many times I will draft a post, and then want to add a video after the fact. Since videos cannot be added after the fact I have to create a new post to do so.

So, for example, I am working to publish my my Free course on Dev.to and I have a video that doesn't have the best sound quality but I just want to get it out. I want to from a few days from now update that video with better sound quality.

**Describe the solution you'd like**

* Be able to add a video to turn a post into a video post
* Also be able to replace an existing video to keep my content fresh or make corrections

**Describe alternatives you've considered**

Cry profusely.

**Additional context**

<img width="458" alt="Screen Shot 2019-10-10 at 12 14 24 PM" src="https://user-images.githubusercontent.com/7776/66586965-88202180-eb57-11e9-9483-79b78fa69e1a.png">

**Comment by allanwhite** [comment]
It's not clear to me from reading the Editor guide how to even create video posts.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
