### ISSUE TITLE
Issue with Codepen embed

### ISSUE THREAD

**Issue by CalvinTaylor40** [forem/forem#4410]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

I try to share from codepen.io and get this everytime

**Comment by CalvinTaylor40** [comment]
I keep trying share from copen to here i can not i will stop trying

**Comment by jessleenyc** [comment]
@CalvinTaylor40 what's the link to the pen? And do you mind sharing your DEV username with us? If you don't want to share publicly, feel free to email yo@dev.to
