### ISSUE TITLE
Add webcomponents.dev as a liquid tag/embed

### ISSUE THREAD

**Issue by georges-gomes** [forem/forem#4412]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to embed https://webcomponents.dev editors in blog posts. Like a codepen or codesandbox.

**Describe alternatives you've considered**
The only alternative is to have a link or button(?) to the editor but it's not has nice.

**Additional context**
webcomponents.dev is a online editor/compiler of web components.
You can code online and we have a new embed format now.
You can test in on the landing page by clicking on the samples.

Thanks
Georges

**Comment by rhymes** [comment]
Hi @georges-gomes, I rewrote the title adding "liquid tag", so that we know instantly what the request is about, hope you don't mind!

**Comment by georges-gomes** [comment]
Hi @rhymes @jessleenyc 
Is there any wait we can help to make the process easy on your side?
We love dev.to and would like to show nice embed experiences.
Cheers

**Comment by georges-gomes** [comment]
I'm not familiar with ruby but I can probably learn :)
Should we try to PR a `webcomponentsdev_tag.rb` in `/app/liquid_tags/`?
Is that all what is necessary?
Thanks for you help

**Comment by georges-gomes** [comment]
OK I found this page https://github.com/thepracticaldev/dev.to/blob/626340b3c30183b5138060cf03e5541847c19ca5/docs/frontend/liquid-tags.md
Probably the way to go ;)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
