### ISSUE TITLE
🌈 Feature Request: Add linkable "id" to each Editor Guide section headers

### ISSUE THREAD

**Issue by dance2die** [forem/forem#4507]
### Description
Add an "id" field on each header section in the [Editor Guide](https://dev.to/p/editor_guide).

### Issue

We can't refer to a specific section in the Editor Guide because there is no "id" field to link to for headers on https://dev.to/p/editor_guide.

![issue](https://user-images.githubusercontent.com/8465237/67163805-49514f00-f341-11e9-97f4-28545e1c549f.png)

### Example case

e.g.) https://dev.to/dance2die/comment/gmj3

I requested user to `Editor Guide/Video Embed`, which will take the reader to the top of https://dev.to/p/editor_guide, not the "Video Embed" section.

## Describe the solution you'd like

Gatsby documentation page adds a clickable "anchor" as shown below.  
URL shown below - https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/

![gatsby documentation](https://user-images.githubusercontent.com/8465237/67163774-01322c80-f341-11e9-912c-5d778be12f1c.gif)

## Describe alternatives you've considered

As adding an anchor could increase the DOM size, we can simply embed, "id" in the header without adding `<a href="..."/>`.

## Additional context

Posts have "id" fields generated automatically for ToC. #682

**Comment by shindakun** [comment]
That's a good idea. I'll pick this one up once approved if you haven't already jumped on it. Can probably do it this afternoon, gotta take the family out to lunch. 🥘 ;)

**Comment by dance2die** [comment]
Thanks @shindakun. It's all yours if approved 😄

**Comment by shindakun** [comment]
@benhalpern is it alright if I just assume this will be approved and put up a PR? It looks like the h2 sections got the id's but the h3's were left out. It'd be nice as a mod to be able to link directly to any subheading.

**Comment by Zhao-Andy** [comment]
@shindakun oops, meant to label this and get back to you. All yours!

You might want to add a class and reuse the styles to account for the top nav bar:
https://github.com/thepracticaldev/dev.to/blob/f279315b38e16a77add7848e1b3e997656b1a006/app/assets/stylesheets/article-show.scss#L443-L450
