### ISSUE TITLE
Follow listings categories and receive notifications for new followed listings

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#4549]
If I am looking for a job, I would like to follow the job listings category. If I'm following that category I will get a notification every time a new listing is posted.

In the future I think it would also make sense to be able to limit it to just certain tags within the following, but I think that could come after the initial feature.

It should should be implemented the same as we do "follow" for tags, users, orgs (using acts as followable gem). It will likely require modifying a few places where we assume the different types of "followables".

I think we can focus mostly on the backend and notifications-oriented functionality and the decision on how to render the follow button and where to put it can come once the rest of the implementation is ready.

**Comment by CristinaRuth** [comment]
I came here to suggest this, but it's already here. 

Yes, please! 🙏

Here's a user story from my perspective, if it helps. 

>  As a user,
I want to get notified about new posts under a tag I follow,
So that I don't miss any posts I may be interested in.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
