### ISSUE TITLE
Discord liquid tag

### ISSUE THREAD

**Issue by binyamin** [forem/forem#4591]
See title. Discord does have embeds via iframe for those servers who choose to opt in.

```html
<iframe src="https://discordapp.com/widget?id=<server-id>&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0">
</iframe>
```

I envision something like {% discord \<server-id\> %}

**Comment by b3u** [comment]
@jessleenyc I foresee a possible issue. There is an open api at `https://discordapp.com/api/guilds/:server-id:/widget.json`, but it only really exposes the server name and details on online members. For more data, you need to use OAuth. Is this enough information for an embed?

**Comment by b3u** [comment]
other idea -  accept an invite link, and grab metadata and show that

**Comment by jessleenyc** [comment]
I think starting with server name and how many users is actually a great place to start. We can have the liquid tag link out to the rest. How does that sound?

**Comment by b3u** [comment]
Sounds good. Another option, which i just discovered, is this...
```md
https://discordapp.com/api/guilds/446312668823814145/widget.png?style=banner(1|2|3|4|5)
```
I like banner2 the best.

**Comment by maestromac** [comment]
I'm not sure what you are trying to share there @b3u . I see what looks like a chrome console.

What if we utilize Discord's [premade widget](https://blog.discordapp.com/add-the-discord-widget-to-your-site-d45ffcd718c6) instead? I think the advantage is that the implementation is super simple, it can follow what we're already doing with [youtube tag](https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/youtube_tag.rb), and it would come styled.

**Comment by b3u** [comment]
@maestromac That *is* discord's premade widget. `...style=banner(1|2|3|4|5)` means `style=banner1` OR `style=banner2` etc.

**Comment by maestromac** [comment]
Ah I see. Thanks for clarifying that @b3u . Lets go with banner2

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
