### ISSUE TITLE
Floating Article-Action bar in tablet mode

### ISSUE THREAD

**Issue by abenettt** [forem/forem#4605]
**Describe the bug**
When reading an article on my iPad Air 10.5", sometimes the article-actions bar floats in the middle of my screen. This does not happen every time and I have thus far only experienced this on my iPad.

**To Reproduce**
I unfortunately have found no pattern with which to reproduce this but wanted to at least document this here in case someone else had this problem. 

**Expected behavior**

**Screenshots**
![IMG_FA1827D7CD5C-1](https://user-images.githubusercontent.com/7523903/67620623-36d78980-f809-11e9-8e9c-03a5e2a55d69.jpeg)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device: iPad Air (3rd generation)
- OS: iPad OS 13.1.3
- Browser: Safari
- Version:

**Additional context**

**Comment by ludwiczakpawel** [comment]
Fixed.
