### ISSUE TITLE
Permanently Deleting Dev.to Account

### ISSUE THREAD

**Issue by pratimagautam977** [forem/forem#4608]
**Describe the bug**

Problems while permanently deleting the dev.to account.

**To Reproduce**

1. Go to 'https://dev.to/settings/profile'
2. Click on 'Account' or Go to 'https://dev.to/settings/account' 
3. Scroll down to 'Danger Zone' 
4. Type in your 'username' and 'delete my account' as instructed. 
5. Click on 'Delete Account'
6. See error

**Expected behavior**

The account should be deleted or scheduled to be deleted. 

**Screenshots**

![image](https://user-images.githubusercontent.com/33077758/67621996-41a81380-f835-11e9-86ab-c8a795139999.png)

**Desktop:**

- OS: Windows 10 Pro
- Browser: Chrome
- Version: 78.0.3904.70

**Smartphone:**
- Device: Galazy J1 Nxt Prime
- OS: Android 6.0.1
- Browser: Google
- Version: 10.77.9.21.arm

**Comment by jessleenyc** [comment]
Sorry about that - looks like you caught a bug of some sort. In the mean time, if you send an email to yo@dev.to we can handle this for you.

**Comment by jessleenyc** [comment]
@lightalloy quick ping here since you've been working on some self-delete functionality.

**Comment by pratimagautam977** [comment]
> Sorry about that - looks like you caught a bug of some sort. In the mean time, if you send an email to [yo@dev.to](mailto:yo@dev.to) we can handle this for you.

@jessleenyc My account has been deleted after emailing at yo@dev.to. Thank you! Yet, I am unknown if the issue persist on the website or not.

**Comment by Freshchris01** [comment]
When I try to delete a connected Github account by clicking the link in the email, I get a `This page does not exist`. Is this behaviour intended?

**Comment by rhymes** [comment]
Closed this as users can self delete now
