### ISSUE TITLE
Redirect to app when browsing on a mobile device

### ISSUE THREAD

**Issue by xarielx** [forem/forem#4614]
**Is your feature request related to a problem? Please describe.**
When I am browsing Twitter or some other site, and someone else has shared a link when I open it it opens a browser page instead of opening the app.

It is very frustrating that I cannot easily open articles on the app and would have to search them by author or title.
**Describe the solution you'd like**
I would like to be redirected to the ios app or android app in the event that I open a dev.to link.

**Describe alternatives you've considered**
Alternative is searching on dev.to app for the article I want to read

As example implementing something like this
`<h2><a id="applink1" href="dev//paulasantamaria/testing-node-js-mongoose-with-an-in-memory-database-32np">open devto with fallback to appstore</a></h2>
    <h2><a id="applink2" href="unknown://nowhere">open unknown with fallback to appstore</a></h2>`
**Additional context**

**Comment by jessleenyc** [comment]
Hm i thought we had this in but am also experiencing the issue. Could this be on twitter's side where it forces users to use their in-app browser? Deep linking on android works for me in other apps. For example, when someone texts me a dev.to link it'll ask me to if I want to open it in the app.

**Comment by xarielx** [comment]
Yes it might be on twitters side, but normally when in the in app browser I choose open in safari it redirects me to the app that it belongs to, just not this one

**Comment by rhymes** [comment]
Hi @xarielx, are you still experiencing this?

**Comment by maniflames** [comment]
I experience the same when  clicking on a link in twitter. However, when I click a dev.to link from the google search results the app does open but doesn't navigate to the post. (iphone, default browser: brave)

**Comment by xarielx** [comment]
Yes I'm still experiencing this

**Comment by cmgorton** [comment]
@fdoxyz tagging you just so you have an eye on this issue that users are still experiencing.

**Comment by fdoxyz** [comment]
Thank you for the heads up @cmgorton! It's definitely on the radar. We've had an idea to implement this in a few ways. An early (and similar) solution to this was [shared here](https://github.com/forem/DEV-ios/issues/209#issuecomment-623647950).

Thanks to the internal RFC process in place I'm hopeful we should be able to get the blockers for this out of the way, and therefore finally able to ship this feature in the coming weeks. I linked a draft PR that would hopefully sort this out and close this issue when merged
