### ISSUE TITLE
Inline browsable documentation

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#4641]
This is a feature I've had in the back of my mind for a while which I feel could be kind of interesting...

A sort of "meta" section on the site where from within the browser context you can open some information about how that page is constructed, which files to check to make changes in certain parts, high level ongoing tasks related to that part of the site, etc.

It could live as a button in the bottom right corner (similar to the [intercom button](https://static.intercomcdn.com/docs/docs.intercom.io/images/docs%2520notes_%2520Canvas%25203-4b4f6fbf39d9ea23b0563cd216b6c34ae870d2dd8a0f3a28c0b3b13d2a7fa6a3.png) and open up to meta info about that page and things the user might be interested in.

We could create a sort of standard `meta` tag or something such as...

```html
<meta name="inline-docs" content="This is DEV Connect, which is for chat. It touches such and such file. It is a preact app which has its highest level component located here.. app/javascript/chat/chat.jsx, on the Ruby side, go here and here and here... There is this open issue discussing the merits of such and such">
```

☝️ Anyway, the JS on the page could compile all the content in these various meta tags and have them available via a click. We could also map dynamically to GitHub issues some how, but I think starting with having it be purely a reflection of text within the code makes sense.

I also think this is the type of documentation which is less likely to get super stale and is probably a space to get more granular than docs typically get.

It is also kind of interesting content for software developers themselves. Since we are an open source community of developers, it seems very appropriate to our codebase, but I could see this becoming standardized on other sites (probably something that would default not be turned on).

Alternatively this might make sense as something we do through `console.log`, but I kind of like the idea of it being more accessible through the UI itself.

For "phase 2" communities (non-dev.to instances), of course it makes less sense for this meta section, though we might want it togglable in every instance, at least to reveal which version that community is running on.

Anyway... Just an idea.

**Comment by cmgorton** [comment]
I think this would be a great discussion post for [forem.dev](forem.dev) if this is still a feature we potentially want to add. 

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
