### ISSUE TITLE
Tombstone info of followers, via Dashboard and email notification

### ISSUE THREAD

**Issue by vgrovestine** [forem/forem#4643]
**Is your feature request related to a problem? Please describe.**

I have my account set to send a notification each time someone new follows me. While the notification works like a charm; I'm left wanting more information about the person who has followed me beyond _"Yada Yada just followed you: You now have N total followers. See all of your recent followers right here..."_

It's a nuisance to have only a name to work from: Who is this person? Do we have any skills/interests in common? Are they an established contributor, or a new member who's eagerly following anyone and everyone?

Presently, the only way to learn about one's followers is to click through their profile (either via new follower email notification, or Dashboard > Followers tab), one-by-one. Not a big deal when you have 20 followers, but pure tedium when you have 50, 100, 300, or more!

**Describe the solution you'd like**

In addition to name, consider including basic tombstone information about followers both in the Dashboard > Followers tab and new follower email notification:

- Date joined
- Date of last contribution
- Number of posts
- Number of comments
- Follow-back button
- Top (3-5) tags of most frequently contributed/commented posts
- Tags followed
- Biography (probably not practical in Dashboard > Followers given limited space, but this would be nice in the new follower email notice)

**Describe alternatives you've considered**

No alternative solution at present. :(

**Additional context**

Dashboard > Followers:

![dev_to-dashboard_followers](https://user-images.githubusercontent.com/11873315/67708971-e2184800-f99b-11e9-8687-3170c884fd1d.png)

New follower email notice:

![dev_to-new_follower_email](https://user-images.githubusercontent.com/11873315/67708979-e6446580-f99b-11e9-89b2-df3a6f931515.png)

**Comment by jessleenyc** [comment]
We're hesitant about having stats being such a first impression when connecting with members. To start, can we just include the user byline/summary in these areas (email + dashboard)? Perhaps after that we can introduce even more information.

**Comment by vgrovestine** [comment]
The user byline/summary would be a good first start.

I can understand the hesitation to include more as there exists potential for premature judgement of new followers' "influence" whether a fresh member with no history or a storied veteran of the community.

Perhaps another approach could be to borrow from the established badges concept, such that account longevity, posts count, and comments frequency are combined to label members' status without getting into specific dates and numbers. (eg. Rookie, Junior, Established, Veteran, Core Team)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
