### ISSUE TITLE
Github liquid tag does not update

### ISSUE THREAD

**Issue by binyamin** [forem/forem#4646]
**Describe the bug**
Similar to #212. GitHub tag embed does not update when repository updates.
See https://dev.to/b3u/my-first-community-project-10p7 and corresponding repository

**Desktop:**
- OS: Windows 10
- Browser: Opera
- Version: Opera 63.0.3368.107

**Comment by jessleenyc** [comment]
Right now, this only updates if the user re-saves their post. There's been some work done on the getting the Twitter liquid tag to update (#3595) that could be helpful here. We want to be resource conscious and not be checking github constantly but also still keep things fresh. Open to approaches here!
