### ISSUE TITLE
Posts published privately

### ISSUE THREAD

**Issue by seawolf** [forem/forem#4683]
**Is your feature request related to a problem? Please describe.**

I'd like to use dev.to for a series of professional journal posts, to record my thoughts on my career or what's going on. I've tried this before but only lasted a couple of posts as I was too restricted by the risk of colleagues/peers/clients reading them and this affecting me or the company.

I suppose the problem is that there is no visibility setting for a post?

**Describe the solution you'd like**

I'd like to be able to publish a post but do so privately so only those with the URL can read and comment upon it. This would record the _published_ timestamp: it is no longer a draft but published, albeit to a limited audience.

After a "safe" amount of time, I would switch the post to public. This would not affect the published timestamp.

[LinkedIn provides the feature](https://www.linkedin.com/help/linkedin/answer/85039) of providing a URL to a draft, but the timestamp is automatically set when publically publishing it.

**Describe alternatives you've considered**

* _Draft_ posts would not record the publishing timestamp accurately, as it would set to the time it was made public.

* Marking it with "Published at ..." defeats the point of having the real _published_ metadata there in the first place.

* Not writing posts that aren't safe to write would inhibit me from expressing my thoughts and feelings, especially when I have come to terms with accepting feedback on them.

**Additional context**

You all rock. It's Friday (even if it's not, it will be soon).

**Comment by jessleenyc** [comment]
This is a cool idea. There are definitely a lot to consider with this feature if anyone wants to leave more granular thoughts on how we'd build this.

**Comment by abenettt** [comment]
What about a boolean flag on the post that indicates that the post is accessible via it's generated url, this would allow one to access the post when knowing the url but not finding it via search. This field would only be considered should the post not be published already. And must take care not to allow indexing via bots etc. as it would kind of defeat the purpose.

**Comment by cesc1989** [comment]
@abenettt your approach sounds great.

> This field would only be considered should the post not be published already

Do you mean if the post was _publicly_ published then it can't be made _private_ anymore?

**Comment by abenettt** [comment]
@cesc1989 I don't actually know how the unpublishing works internally, but I imagine it works via the `published_at` field also, maybe @jessleenyc knows more? And we then can still respect our boolean flag.

**Comment by seawolf** [comment]
> > This field would only be considered should the post not be published already
> 
> Do you mean if the post was _publicly_ published then it can't be made _private_ anymore?

I'd think it would be acceptable to say that once a post is published, it can't be unpublished: there being bots or people that have already seen it means it's already out in the open.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
