### ISSUE TITLE
Mobile feed-nav-menu should not be scrolled and can be closed by tapping open space

### ISSUE THREAD

**Issue by SeasonLeee** [forem/forem#4749]
**Is your feature request related to a problem? Please describe.**

Hi there, I don't know what stated in the title is intended or just a space for improvement, either way, in my own experience, I don't think the nav with the id name `feed-nav-menu` should follow along when I have scrolling gesture over the screen on the phone.

As you can see this is how it behave in my phone:
![Screenshot_2019-11-08-06-27-54](https://user-images.githubusercontent.com/13610283/68435148-a54b1d00-01f5-11ea-870a-87e339d08c89.png)

And this is how it behave in the mobile mode of the PC browser:
![Screen Shot 2019-11-08 at 7 03 15 AM](https://user-images.githubusercontent.com/13610283/68435354-138fdf80-01f6-11ea-9bd2-ce673853aac9.png)
  

*Why would I scroll the screen when the nav is open?*
Well, in my small mobile phone, when I open the feed nav, I try to close it but fail with no such 'close' feature.

And this indicated that there's closing functionality to this `feed-nav-menu` on mobile missing, and I have to say this is not really a good UX. Well, I think...

**Describe the solution you'd like**
1. Let's make this `feed-nav-menu` fixed, shall we?
Well, this is pretty easy and straightforward😄
I just did it on the developer tool:
![Screen Shot 2019-11-08 at 7 11 16 AM](https://user-images.githubusercontent.com/13610283/68436058-db899c00-01f7-11ea-97e3-f56de789fc6e.png)

2. And also add another 2px to the top to fix that 2px gap between the `top-bar` and the `feed-nav-menu` when we make the `feed-nav-menu` from absolute to fixed position:
(The fix is showed in the above screenshot, here's just what happened if I didn't change the top value)
![Screen Shot 2019-11-08 at 7 22 01 AM](https://user-images.githubusercontent.com/13610283/68436298-99ad2580-01f8-11ea-9989-e52f0e49b219.png)

This gap is much obvious if the `feed-nav-menu` is fixed and we have scrolling gesture on the screen, because the `feed-nav-menu` is fixed and the content on the back is not. So... and this leads to another thing we need to add is

3. `overflow-y: hidden` to the body element when the `feed-nav-menu` is showed, which is to keep the content behind the `feed-nav-menu` to scroll.

4. A functionality to close the `feed-nav-menu` when it show up.

Normally, I will just tap on the open space below the `feed-nav-menu` to close it. But, now, well, I can't.

My suggestion will be, have a 'shadow' come with the `feed-nav-menu`, the 'shadow' will be covered the content behind the `feed-nav-menu`, because, well, when I open the `feed-nav-menu`, my focus will be on the `feed-nav-menu` itself, right? Hiding the content behind it with some shadow, I think it will work😄, here's my implementation, on the dev tool, obviously.
![Screen Shot 2019-11-08 at 7 39 23 AM](https://user-images.githubusercontent.com/13610283/68437376-b9921880-01fb-11ea-91af-085919770fc9.png)

And because I kind of run out of time now I have better get up and run for my work, so I just increase the y value of box-shadow to make my point. But the proper solution should be wrap the whole `feed-nav-menu` with another div and make that div to do the work... well, I think guys get that now, so... good luck😆

hmm...

Am I being a good issue maker😅 

**Describe alternatives you've considered**
Well... no? Or maybe the original UX is what you guys want, and I will be delighted to hear why😁

**Additional context**
Thanks for your reading, have an awesome day😆

**Comment by jessleenyc** [comment]
Thanks for the request. Right now, you can close the feed nav menu by selecting one of the feed options. I think what you're proposing makes sense as well but just wanted to let you know how to close it for now, in case it was getting in the way!

**Comment by SeasonLeee** [comment]
Thanks for the response! And I have told my friends about this they have advised me to close the feed nav in the same way you did😅 

Actually, if you like the tap on the open space to close the feed nav idea, I can make a pull request to give this feature a shot, even I have never try a ROR project before, but I like adventure😁

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
