### ISSUE TITLE
Embed individual files from github as sources

### ISSUE THREAD

**Issue by kirill-konshin** [forem/forem#4757]
Per editor guide https://dev.to/p/editor_guide it's possible to embed either link to repo or link to gists (incl. individual files).

But is there a way to embed exact file from the repo? Would be VERY useful to publish an article describing some demo repository.

**Comment by jessleenyc** [comment]
Thanks for the feature request. I'm just realizing that we don't have any liquid tags for GitLab right now. Perhaps whoever takes this can also add repo links for GitLab?

**Comment by kirill-konshin** [comment]
Whoaaa, I just realized that iPhone autocomplete *fixed* Github to Gitlab ))) my original intent was Github. But gitlab in addition would be nice )

**Comment by henrikwirth** [comment]
This feature would come in super handy and should be similar to the PR ( #4245 ) I guess.

As I'm working on a tutorial, where the code is hosted on GitHub it would be much easier to reference certain files or code-snippets right out of the codebase. Would make it easier for the user to jump into the code and see the exact version of the file I'm talking about in the tutorial.

**Comment by kirill-konshin** [comment]
Great news! Once landed I will rewrite some of my articles!

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. This one has been around for a while without much traction lately.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
