### ISSUE TITLE
Mark links in posts and comments as User Generated by default.

### ISSUE THREAD

**Issue by mpomery** [forem/forem#4805]
**Is your feature request related to a problem? Please describe.**

Links in posts, comments and profiles are all simple `<a href="[URL]">` with no relationship attribute.

Some links on profile pages do contain the nofollow attribute.

**Describe the solution you'd like**

Use `rel='ugc'` to mark links in posts and comments as user generated content, changing how search engines index them, and reducing the value of spam posts.

Will need to confirm that this happens no matter how you place a link into the page (i.e. using markup and liquid tags)

**Describe alternatives you've considered**
We will definitely want to figure out a way to remove the UGC relationship tag from high quality users, which means figuring out a way to determine what a high quality account looks like.

**Additional context**
Marking links as user generated content will prevent the links from influencing page rankings in search results, and should help to discourage spam.

See Also: https://support.google.com/webmasters/answer/96569?hl=en

I vaguely remember ways of marking sections as user generated content, but haven't been able to find it again.

**Comment by mpomery** [comment]
I can have a look further into what the options are for marking user generated content are tomorrow and report back here.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!

**Comment by lazidoca** [comment]
I am interested in this as well. Since there are only a few people selfhost Forem, they don't care much about SEO. However, a link without "nofollow" in the post will affect the page rank.

**Comment by citizen428** [comment]
@lazidoca Yes, if/when we implement this we'll be mindful of SEO considerations.

**Comment by lazidoca** [comment]
@citizen428 There is also a post in forem.dev: https://forem.dev/techkoool/add-nofollow-for-external-links-in-posts-4ijl

But it seems like nobody cares about it =))

@cmgorton Should we reopen this issue?

**Comment by cmgorton** [comment]
@lazidoca we are doing a little restructuring around discussions/feature requests that I will be sharing more detail on later this week. Let's keep this closed until I get those changes implemented and then we can look at converting this issue into a discussion.

**Comment by mpomery** [comment]
#15520 addresses this for the link on a users profile
