### ISSUE TITLE
Hide every header image on articles

### ISSUE THREAD

**Issue by Arteneko** [forem/forem#4808]
I'd like to be able to disable *every* header image from dev.to articles I read and browse (in the list).

Most are plain useless, slow down page load and reduce the quantity of posts I can view in a single window context.

It would be really nice to have a UI setting to disable them altogether.

**Comment by jessleenyc** [comment]
I think the spirit of this issue will be accomplished once we have a 'list view' of the home feed as a UI setting, which we plan to have eventually.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
