### ISSUE TITLE
render iframes in post

### ISSUE THREAD

**Issue by wolverineks** [forem/forem#4814]
**Is your feature request related to a problem? Please describe.**

I would like to include an iframe in a post

**Describe the solution you'd like**

i would like to use regular tag like: `<iframe src="..."></iframe>`

**Describe alternatives you've considered**

alternatives:
link to website (encourages readers to leave)
screenshot of website (not nearly as engaging)
embedded codesandbox (includes unwanted stuff, slow)

**Additional context**

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
