### ISSUE TITLE
Registration block with broken UI

### ISSUE THREAD

**Issue by ubaidisaev** [forem/forem#4833]
**Describe the bug**
Some blog post have this registration block with broken ui.

**To Reproduce**

1. Go to 
'https://dev.to/comscience/what-is-this-event-loop-that-they-speak-of-in-javascript-42mo'
'https://dev.to/nsebhastian/free-book-to-learn-javascript-532f' 

**Screenshots**

![screen](https://user-images.githubusercontent.com/38039843/68967604-a4b41700-07f1-11ea-976b-72ffe7106025.png)

- OS: Windows 10
- Browser: Google Chrome
- Version: 78

**Comment by jessleenyc** [comment]
Ah, thanks for flagging this.

**Comment by cmgorton** [comment]
@forem-team anyone know if this is still a bug?

**Comment by rhymes** [comment]
@cmgorton I don't think so, the UI for registrations is totally different AFAIK

cc @ludwiczakpawel to confirm

**Comment by ludwiczakpawel** [comment]
Confirmed. I don't think we even have that registration box in right sidebar anymore.

Closing.
