### ISSUE TITLE
Tag Embed Broken When Creating/Editing Post

### ISSUE THREAD

**Issue by torianne02** [forem/forem#4834]
**Describe the bug**

When attempting to use embedded tags for DEV within my blog post it doesn't work. When I go into preview mode it shows the text `{% tag ruby %}` as plain text. 

I attempted to see if the same was happening while commenting on the post and that seems to work properly. 

**To Reproduce**

1. Go to DEV.to 
2. Click on `Write Post`
3. In the body of the post, type `{% tag ruby %}`
4. Click on `Preview`
5. See bug (the text from step 3 remains as is without embedding the tag).

**Expected behavior**

The tag should be embedded within the post.

**Screenshots**

Bug in Preview Mode While Writing/Editing Post:

![Screen Shot 2019-11-15 at 5 17 58 PM](https://user-images.githubusercontent.com/37308853/68985740-948a4080-07cd-11ea-9dcc-2b27064d709c.png)

Embedded Tag While in Comment (working properly):

![Screen Shot 2019-11-15 at 5 26 53 PM](https://user-images.githubusercontent.com/37308853/68985725-81777080-07cd-11ea-8658-44a98e1d4edf.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.6
- Browser: Chrome
- Version: Version 78.0.3904.97

**Smartphone (please complete the following information):**

- Device: iPhone 7s
- OS: iOS 13.2
- Browser: DEV App

**Comment by jessleenyc** [comment]
Hmm...are you still experiencing this?  I'm not able to reproduce it right now.

**Comment by torianne02** [comment]
Yes I am still experiencing it. Here is another screenshot I just took:

![Screen Shot 2019-11-18 at 6 58 50 AM](https://user-images.githubusercontent.com/37308853/69063238-fff03000-09d0-11ea-9800-5225f44150e6.png)
