### ISSUE TITLE
feature to integrate Discord plugin and channels

### ISSUE THREAD

**Issue by Arconapalus** [forem/forem#4866]
**Is your feature request related to a problem? Please describe.**
No however, I've seen recently that most developers are using discord for triaging issues, errors, etc. Even seen some referred by stackoverflow to msg direct using discord 

**Describe the solution you'd like**
plugin for discord, much like twitter etc for audience to contact or connect with. 

Discord plugin 
**Describe alternatives you've considered**
no other alternative but I love how Dev.to developers team is really expanding there ideas into the developer world of problem solving. 

none
**Additional context**
none

none

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
