### ISSUE TITLE
autosuggest emojis

### ISSUE THREAD

**Issue by Bhupesh-V** [forem/forem#4870]
**Is your feature request related to a problem? Please describe.**

DEV already supports GitHub like emoji addition  #1653
It would be nice to have a auto-suggest option (just like github)

![gotiit](https://user-images.githubusercontent.com/34342551/69319042-6b056500-0c64-11ea-9898-c97aa3cbce49.png)

**Describe the solution you'd like**

This way we won't have to copy paste emojis from emojipedia :sweat_smile:

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
