### ISSUE TITLE
The app not load 

### ISSUE THREAD

**Issue by VictorSalgado** [forem/forem#4877]
**Describe the bug**

When I open the app the first time, I saw a Dev black landscape and nothing else is shown
**To Reproduce**

Open the app (android)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
@VictorSalgado are you still seeing a blank screen when you the load the DEV android app?
