### ISSUE TITLE
Convenient Markdown Cheat Sheet in Comments editor

### ISSUE THREAD

**Issue by elijah-schow** [forem/forem#49]
As someone writing a comment, the markdown cheat sheet is handy. Unfortunately, comparing markdown I've written to a cheat sheet in another tab is cumbersome. I would like the cheat sheet to display on the same page as the comment editor.

Here are some possible UI solutions:

**Popover** (and make it draggable?)
![dev to-cheatsheet_popover](https://user-images.githubusercontent.com/17830432/27139919-ddb6f4da-50e9-11e7-850f-37c13b7c7472.png)

**Sidebar**
![dev to-cheatsheet_sidebar](https://user-images.githubusercontent.com/17830432/27139929-e26bf5e8-50e9-11e7-9b14-1b864793f5eb.png)

**Comment by benhalpern** [comment]
Thanks a lot for the feedback

**Comment by GonzalezAnguita** [comment]
Just an idea but maybe recognizing the last character and displaying on the footer the "commands" that match with it.

Something like slack does.
![Slack](https://user-images.githubusercontent.com/22966862/35864747-6020e190-0b31-11e8-8742-7d86d37651ac.png)

**Comment by maestromac** [comment]
not stale

**Comment by jessleenyc** [comment]
This is approved if anyone wants to work on the popover version. Keep in mind, this will need to work on all comment boxes.

**Comment by mariocsee** [comment]
I can hop on this if no ones has opened a PR for it!

**Comment by Link2Twenty** [comment]
@rhymes the markdown editor is in a modal now, I guess this can be closed?

**Comment by rhymes** [comment]
@Link2Twenty it's not a modal though, this issue is about the markdown cheat sheet for the comment editor. I'm going to update the title

**Comment by michael-tharrington** [comment]
To @Link2Twenty's point here, I do think we could somewhat copy the way that the editor basics are presented in our editor:

![Image 2020-11-10 at 3 25 21 PM](https://user-images.githubusercontent.com/16007075/98729486-fe99df00-2368-11eb-86d6-fd4ecea94140.png)

I think it'd be nice to keep our design/the way we offer this info consistent if possible.

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
