### ISSUE TITLE
Banner misses text upon page-up

### ISSUE THREAD

**Issue by jean** [forem/forem#4900]
**Describe the bug**

While reading an article, hit the spacebar or pgdn to scroll down a page. 
The top of the next page does not match the bottom of the previous page: one line of text is missed. 

**To Reproduce**

Read an article, page down using space or the pgdn key.. 

**Expected behavior**

Scroll down so that I can continue reading on the next page, without having to scroll up to see missed text.

**Screenshots**

The first page ends with "_creating prototypes and_":

![Screenshot_20191124-174117_Brave](https://user-images.githubusercontent.com/84800/69493173-84482480-0ea3-11ea-9adc-90d3e4cdeb9b.jpg)

The next page starts with "_productive and easy_":

![Screenshot_20191124-174202_Brave](https://user-images.githubusercontent.com/84800/69493171-83af8e00-0ea3-11ea-92f4-af45f655fbb5.jpg)

The sentence starting "_PoCs and the dynamic ..._" was missed out:
![Screenshot_20191124-174243_Brave](https://user-images.githubusercontent.com/84800/69493172-83af8e00-0ea3-11ea-8132-04f28da8e4b9.jpg)

(Also, as noted on the first image, those banners waste a ton of space. If https://github.com/thepracticaldev/dev.to/issues/4901 is accepted, the problem goes away :wink:)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy Tab S6
- OS: Android 9
- Browser: Chrome 78; Brave 1.5.1 (based on Chrome 78). 
- Version: Android 9

**Note**: Firefox 68.2.1 on this device does *not* have the paging issue.

**Comment by jessleenyc** [comment]
Confirmed I am experiencing this as well.

**Comment by cmgorton** [comment]
There is a new layout to DEV with the hearts, unicorns etc on the side instead of on the bottom. I am not sure this is an issue any more. I am going to close this but if you still experience this problem let me know and we can open this back up. Thanks.
