### ISSUE TITLE
Use slack space in landscape mode, don't steal vertical space

### ISSUE THREAD

**Issue by jean** [forem/forem#4901]
**Is your feature request related to a problem? Please describe.**

In landscape mode, top and bottom banners waste a lot of space.

**Describe the solution you'd like**

In landscape mode, there is a lot of slack space to the left and right of the content. 
Instead of stealing vertical space, use this space for the furniture that is currently in the top/bottom banners.

**Additional context**

See **wasted space** for the space that I think should be dedicated to reading.
See **unused space** for the slack space to the left and right of the content that can be used for widgets.

![20191124_183014](https://user-images.githubusercontent.com/84800/69493333-a8a50080-0ea5-11ea-8c27-8fad1fc2ed63.jpg)

**Comment by jessleenyc** [comment]
Hm, we do use up those areas for certain screen sizes but it doesn't seem like your screen is wide enough to his that breakpoint. What width are you at?

![](https://p193.p3.n0.cdn.getcloudapp.com/items/nOuWGJJq/Image+2019-11-24+at+7.35.44+PM.png?v=ccaf7c221d24316234e38cd771b9e19c)

**Comment by jean** [comment]
Display
10.5” WQXGA Super AMOLED (1600X2560)
287 ppi

[Specs](https://www.samsung.com/global/galaxy/galaxy-tab-s6/specs/)

**Comment by jean** [comment]
The top banner is still taking up space, but the bottom widgets to move to the left margin, so that is an improvement.

**Comment by ludwiczakpawel** [comment]
You can turn off "sticky header" in [](https://dev.to/settings/ux) .
