### ISSUE TITLE
Tags may not be working as expected in feeds

### ISSUE THREAD

**Issue by shaneblackburn** [forem/forem#4946]
**Describe the bug**

My feeds include many posts from tags that I do not follow.

I realise there are exceptions (Latest feed, authors I follow, site-wide posts, the degenerate case of no tags) but my tagged topics don't *seem* to occur more often than their natural frequency. 

**To Reproduce**
1. Choose several _reasonably_ popular tags to follow
2. Click feed button
3. With the first 50 posts, count number of posts containing any followed tags.
4. Compare to *potentially* available posts per tag (click tag in 'my tags')
5. Assuming enough recent posts for followed tags (step 4); are any 'unwanted' posts present from step 3?

**Expected behavior**
Typically tags are used as a whitelist to filter content.  I would expect to see only content from tags I explicitly follow.

That said, it may just be the case that I don't know the rules behind feed generation; e.g. do special highlighted tags (#watercooler, #showdev, #todayilearned, #discuss, #challenge) appear sitewide in feeds? How are tags intended to work with respect to different feeds (default / time period / latest)

Before investigating further may I please ask what is the *intended* behaviour of tags with respect to feeds? @benhalpern @jessleenyc @rhymes 

**Additional context**
This issue seems directly related to:
#1856 (comments on this issue suggest tag filtering / biasing isn't working as expected for other users)

**Comment by shaneblackburn** [comment]
btw, happy to work on fix if this is confirmed as an issue

**Comment by jessleenyc** [comment]
Hey @shaneblackburn, thanks for creating this issue. We're going to revisit how tag behavior in the new year. It's a little buggy right now, and we'd also like to take in some of the additional feedback we've received in other issues (i.e. #1856).
