### ISSUE TITLE
Create a User Profile table

### ISSUE THREAD

**Issue by anthonyms** [forem/forem#4959]
Similar to #4939 and #4940, a user's profile info is split into many columns in the User table. These columns can be extracted to a UserProfile model.

The columns in question are:

- twitter_username
- github_username
- website_ur
- summary
- location
- education
- employer_name
- employer_url
- employment_title
- mostly_work_with
- currently_learning
- currently_hacking_on
- available_for
- facebook_url
- dribbble_ur
- medium_url
- stackoverflow_url
- behance_url
- linkedin_url
- gitlab_url
- instagram_url
- mastodon_url
- twitch_url
- feed_url

These columns are considered profile info in [Moderator::BanishUser#remove_profile_info](https://github.com/thepracticaldev/dev.to/blob/master/app/services/moderator/banish_user.rb#L38)

**Comment by mstruve** [comment]
Hey! Thank you so much for opening this issue! 

We chatted about this in our weekly tech meeting and decided that our first steps are going to be breaking out the columns mentioned in those other two issues first and then we will take stock and see what is left. What you have listed as columns for a UserProfile model might actually end up being the User model itself. Or, we may decide we want to split it out even further as you have suggested. 

Going to mark this for future work as we will want to get those other two issues done first. 

Let me know if you have any other thoughts or questions! 😃

**Comment by artfullyContrived** [comment]
@mstruve sounds good.

**Comment by rhymes** [comment]
@citizen428 @Ridhwana in light of the work you've been doing, should we close this?

**Comment by Ridhwana** [comment]
Yes please, closed.
