### ISSUE TITLE
"1024 views" private banner won't dismiss.

### ISSUE THREAD

**Issue by ogrotten** [forem/forem#4971]
![image](https://user-images.githubusercontent.com/8119012/69917618-7e1af080-142d-11ea-85b5-3ee6f0c13c45.png)

In this image, the banner for 1024 views on an article won't go away, and I can't manually dismiss it with an X. Tomorrow, when I come back to the site, there will be a count number "1" on the navbar notification bell, and it will be because of this banner.

Which brings up a different point...
There's a UX expectation here... an X to dismiss a single notifiction in combination with a "mark all as read" button. 

I'm curious why the choice was made to go a different route.

**Comment by cmgorton** [comment]
Hey @ogrotten is this still an issue?
