### ISSUE TITLE
Add Styling For <button> Tag in Markdown

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#4995]
**Is your feature request related to a problem? Please describe.**

We allow the `<button>` tag to be added in markdown when someone is writing a post, but it's completely unstyled so it looks pretty bad. This Issue has been opened so that we can fix that and make it look better and hopefully similar to the rest of our site styling

You can see a screenshot of what it currently look like in the body of this issue: https://github.com/thepracticaldev/dev.to/issues/4970

**Comment by mstruve** [comment]
@lisasy or @ludwiczakpawel is there a "correct way" to handle this issue now that we have Crayons? (sorry if that's a dumb question, I am not in touch with the frontend 🙈 )

**Comment by lisasy** [comment]
@mstruve 

Enable Crayons styling requires adding the relevant CSS class in the markup. In this case, it might be

```
<button class="crayons-btn`>Label</button>
```

@ludwiczakpawel can comment more on our approach to requiring calling the explicit CSS class names versus Crayons applying to `button` component generally.

**Comment by rhymes** [comment]
We could replace `<button>` with `<button class="xyz">` while parsing the content of the article. We have a [Html::Parser](https://github.com/forem/forem/blob/master/app/services/html/parser.rb) class for those operations.

**Comment by ludwiczakpawel** [comment]
Basically what @rhymes suggests makes the most sense.

We should either apply `crayons-btn` class name OR `crayons-btn crayons-btn--secondary` --> first would end up being our classic blue-ish and latter would be grey: https://storybook.forem.com/?path=/story/components-buttons--default - I'm not convinced for using primary style to this kind of buttons but this opinion isn't very strong. Flip a coin, I guess :)

**Comment by rhymes** [comment]
+1 for secondary

**Comment by mstruve** [comment]
> We could replace <button> with <button class="xyz"> while parsing the content of the article. We have a Html::Parser class for those operations.

Love that idea @rhymes! Paired with the crayons and I think we have a practical solution. Thanks everyone!

**Comment by benhalpern** [comment]
Yup, I agree with all of this. Applying crayons as defaults seems ideal.

**Comment by vaidehijoshi** [comment]
Some homework for this issue: let's get some data around how many users are actually putting buttons in their markdown

**Comment by Zhao-Andy** [comment]
To answer the data question: we have around 898 published articles that have used a button, which as of 2020 Feb 11 is about .38% of articles.

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)

**Comment by umeates12** [comment]
Update your WordPress to the latest version 9.0 which was released recently. My client is also facing this  while posting in their [llyod town court](https://thecourtdirect.com/lloyd-town-court/). The New version is awesome must try it.
