### ISSUE TITLE
Mod tooling: Templates for mod responses to maintain similar style

### ISSUE THREAD

**Issue by DarkSmile92** [forem/forem#5000]
As a moderator you have to write your own formulations for comments on a certain topic always the same.
For example, to ask the author to post the full content of the article, the post is better suited for a listing, and so on.
Having templates on certain topics has the following advantages:
- All moderators use approximately the same formulations on topics, which provides a holistic picture.
- New moderators will find it easier to moderate articles using a template.
- It gives users the impression that the moderators are a team and not everyone does what they want.

The templates should not be mandatory. They should be easily copied into the text and can then be edited.

Example how it could look when composing a new comment:
![image](https://user-images.githubusercontent.com/10928916/70078744-8c226a00-1603-11ea-8a58-783b230a3297.png)

**Comment by jessleenyc** [comment]
Thanks for creating this issue. We’ve actually been talking about something like this a bunch, we’ll do our best to prioritize these canned responses soon.

**Comment by cmgorton** [comment]
Looks like this feature has been added. 

![moderation responses](https://user-images.githubusercontent.com/21039864/105537013-e1fa1b80-5cb6-11eb-838f-18cd030b1bd3.png)

If not what you intended let me know and we can discuss opening this back up. Thanks!
