### ISSUE TITLE
Unable to Change Author on an Organization Post

### ISSUE THREAD

**Issue by CalvinAllen** [forem/forem#5006]
I am cross-posting C# Advent articles to a new csadvent organization on Dev.to.  As I add them, they list me as the author.  I am inviting the TRUE authors of those posts to be org members, so that I can make them the author (canonical links have been set, added a blurb about "first appeared on", etc), but this is kind of the "last thing" I'd like to do to make sure credit is given where its due.

HOWEVER - After they have been added to the organization, and I attempt to set them as the Author of the post using the "Manage" option, it never seems to save the change.  I receive no errors/warnings/etc., it just "doesn't take".

**To Reproduce**
1. As an Admin of an organization, I make a post.
2. The post is credited to me as the author (rightfully so, since I'm posting it)
3. Invite the *REAL* author to the Organization
4. As an admin, "Manage" the post, which provides the option to change the Author to another member of the organization.
5. Select the new author in the drop-down, and click, "Submit Author Change"

**Expected behavior**

I would expect the post to reflect the new author (either immediately, or delayed depending on architecture - however, I'm well past 12+ hours)

**Screenshots**

How bout a gif?

![error](https://user-images.githubusercontent.com/41448698/70150194-97af7880-1677-11ea-8fc2-9c2ead0df259.gif)

**Desktop (please complete the following information):**

- OS: Windows 10 / Slow Ring
- Browser: Edge (New, Chromium-based) / 80.0.345.0 (Dev Channel)

**Smartphone (please complete the following information):**

- Device: Galaxy S8+
- OS: Android 9
- Browser: Chrome 78.0.3904.108

**Additional context**
Nope :)

**Comment by jessleenyc** [comment]
Hey @CalvinAllen, thanks for reporting. We'll try to reproduce this issue on our end but if you're looking to quickly ensure the author is updated, please send an email to yo@dev.to and we can take care of that for you manually.
