### ISSUE TITLE
Check for existing email during account creation

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#5010]
**Is your feature request related to a problem? Please describe.**
As a user, I may inadvertently create multiple accounts as a result of using OAuth with both GitHub and Twitter.

**Describe the solution you'd like**
- During the account creation flow, check to see if the associated email already exists in our database
- If so, display a message ("An email with this account already exists, try signing in with your **GitHub** account.")
    - Should also have a Twitter version
- We could additionally instruct this person to add their GitHub/Twitter via `/settings/account` for redundancy and to avoid this message in the future

**Additional context**
Should we have a "Continue Anyway" message at the bottom of this "intercepting" page?

**Comment by jessleenyc** [comment]
A quick win would be be prompt new users to add their twitter/github accounts during onboarding...maybe even with an explanation/reminder that they might accidentally login with the wrong account in the future or something.

**Comment by fdoxyz** [comment]
Closing as the updates to the authentication flow now support this (authenticating with two separate OAuth providers doesn't result in multiple accounts being created)
