### ISSUE TITLE
Add inline markdown syntax highlight and keyboard shortcuts for editor

### ISSUE THREAD

**Issue by deepu105** [forem/forem#5023]
**Is your feature request related to a problem? Please describe.**

The current Editor is quite basic and is not very user-friendly on the Go, especially when you want to quickly write something up. It would be nice to have at least the below support in the editor

1. Inline Markdown syntax highlight (like in VSCode for example)
2. Keyboard shortcuts(ctrl+s, ctrl+i, ctrl+b and so on similar to [this](https://github.com/yzhang-gh/vscode-markdown) VScode plugin)

**Describe the solution you'd like**

I believe the above can be implemented as a client-side feature using existing libraries and would greatly improve the writing experience on Dev.

The VSCode plugin [here](https://github.com/yzhang-gh/vscode-markdown) can be used as inspiration as its OSS

**Describe alternatives you've considered**

Currently, I write in VSCode and copy-paste to the Dev editor, then I also use Grammarly to correct grammar, so the ability to write directly on the Dev webpage would definitely improve the workflow for anyone who has a similar process.

If there is interest I would be glad to try and implement this with a PR

**Additional context**

Here are some screenshots from the Plugin mentioned

![image](https://github.com/yzhang-gh/vscode-markdown/raw/master/images/gifs/toggle-bold.gif)

![image](https://github.com/yzhang-gh/vscode-markdown/raw/master/images/toc.png)

![image](https://github.com/yzhang-gh/vscode-markdown/raw/master/images/gifs/on-tab-key.gif)

**Comment by deepu105** [comment]
Could be related to https://github.com/thepracticaldev/dev.to/issues/3049

**Comment by jessleenyc** [comment]
Thanks for the request @deepu105, updated the title for clarity.

**Comment by mvasigh** [comment]
Is this something that we would want to use an existing solution for? And maybe this would be something that would be opt-in depending on bundle size impact?

I'd like to work on this!

**Comment by mudlabs** [comment]
This would be a good feature. I was just about to make a request for some StackOverflow style keyboard shortcuts for the markdown editor.

- Except where their `Ctrl+K` adds an indented line, we would add a ``` code block.

**Comment by Link2Twenty** [comment]
Just discovered there are actually keyboard shortcuts on that page (only one).

Pressing CTRL + SHIFT + P toggles the preview. I think the way the code is written at the moment it wouldn't be easy to add many more shortcuts and also it means the component can only be used on that one screen.

I suggest we do a rewrite making it more robust I was thinking something like

```js
import { h } from 'preact';
import { useEffect } from 'preact/hooks';
import PropTypes from 'prop-types';

export const KeyboardShortcutsHandler = ({ shortcuts, ...props }) => {
  useEffect(() => {
    const checkShortcut = (e, keys) => {
      if (keys.length <= 0) return;
      let shortcut = shortcuts;
      for (let key of keys) {
        if (!shortcut[key]) return;
        shortcut = shortcut[key];
      }
      if (shortcut[e.code]) shortcut[e.code](e);
    };

    const keyEvent = (e) => {
      const modifierKeys = [];
      if (e.ctrlKey || e.metaKey) modifierKeys.push('ctrl');
      if (e.altKey) modifierKeys.push('alt');
      if (e.shiftKey) modifierKeys.push('shift');
      checkShortcut(e, modifierKeys);
    }

    window.addEventListener('keydown', keyEvent);

    return () => {
      window.removeEventListener('keydown', keyEvent);
    }
  }, [shortcuts])

  return null;
}

KeyboardShortcutsHandler.propTypes = {
  shortcuts: PropTypes.object,
};
```

You'd then be able to import and use shortcuts on any page like so.

```jsx
const shortcuts = {
    ctrl: {
      shift: {
        KeyP: (e) => {
          e.preventDefault();
          alert("Keyboard shortcut detected");
        }
      },
      KeyK: (e) => {
        e.preventDefault();
        alert("I would do something");
      }
    }
  };

<KeyboardShortcutsHandler shortcuts={shortcuts} />
```

Here's an example of it in action <https://codesandbox.io/s/dank-meadow-hjupd>

___

If this idea gets the go ahead I guess it makes sense to convert the old functionality first. 
@nickytonline does this sort of approach make sense to you?

**Comment by nickytonline** [comment]
@Link2Twenty, see my comments in #10713.

**Comment by deepu105** [comment]
The slate.js lib could be a great fit for this

https://www.slatejs.org/examples/markdown-preview

**Comment by cmgorton** [comment]
Thank you for opening this request. 
Features tend to be subjective and might spur some debate. This one has been around for a while without much traction and appears to be more DEV specific vs Forems overall.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
