### ISSUE TITLE
Please support Chinese in https://dev.to/rly

### ISSUE THREAD

**Issue by tianzhou** [forem/forem#5032]
It would be great to spread this humor to the Chinese dev community.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
