### ISSUE TITLE
Create A Way To Differentiate Pentesters From Regular Users

### ISSUE THREAD

**Issue by mstruve** [forem/forem#5068]
### Problem
When pentesters poke around the DEV codebase they often end up causing a lot of errors as they try to break things. Most of the times these errors are not actually security vulnerabilities but rather our code breaking when it gets unexpected inputs. This can cause our error reporting to be very noisy. 

### Solution
In an effort to cut down the noise we would like to have a way to distinguish a pentester from a normal user that way we could ignore errors raised from pentesters. One way to do this would be to add a column to the user that would distinguish them as a pentester. We are also open to other ideas. Maybe Redis? Maybe a setting? 

Populating this column or attribute can be done either by the user itself or automatically using a flag during signup.  

Let us know if you have any questions!

**Comment by vaidehijoshi** [comment]
Seems like we could tag users who are pentesters. I'm planning on doing this for @thepracticaldev/delightful's work based on [this recent comment](https://github.com/thepracticaldev/dev.to/pull/7637#issuecomment-622171320).

If no one picks it up in the next few days, I could probably loop in "tagging pentester users" into my "tagging suggested follow users" work! :)

**Comment by mstruve** [comment]
@vaidehijoshi another approach option is to use roles to handle this so users would get the pentester role. [We discussed this a bit in the related PR](https://github.com/thepracticaldev/dev.to/pull/5082#issuecomment-565029115)

**Comment by rhymes** [comment]
+1 on using roles as I believe they can be managed more easily: they are one SQL query away and we can build an internal view to list them. It doesn't seem like something related to "site configuration" in my opinion

**Comment by vaidehijoshi** [comment]
I started poking at this today and have some WIP code on a branch, so I'm going to assign it to myself since it doesn't seem like anyone is currently working on it :) 

cc @mstruve

**Comment by mstruve** [comment]
THANK YOU @vaidehijoshi for chatting with me about this. Given our new Forem setup the new idea here is to send Pentesters to a Forem of their own. Here they could go absolutely nuts without the worry of disrupting other users or sending false alarms to our monitoring tools. I am going to close this for now in favor of https://github.com/thepracticaldev/security/issues/309
