### ISSUE TITLE
API: get favorite tags for a user

### ISSUE THREAD

**Issue by dennislwm** [forem/forem#5111]
**Is your feature request related to a problem? Please describe.**

I'm developing a custom feed page for my user that fetches articles by tags from Dev.to and I want to automatically get the user's favorite tags, so that I can filter the articles automatically when they are retrieved. So I'd need a way to get the favorite tags from Dev.to by username.

Is this currently possible?

**Describe the solution you'd like**

https://dev.to/api/tags/me

**Describe alternatives you've considered**

Having the user provide their Dev.to favorite tags manually.

**Additional context**

I looked in Issues for a previous feature request, but couldn't find one, so I created this request.

**Comment by Schwad** [comment]
@benhalpern A question for workflow on this issue. 

The label `type: feature request` says to wait for `approved` label to commence work. However, the `help wanted` label indicates that contributions are welcome. 

In any case where there's a `help wanted` label, should I consider that ready-for-help unless the comments indicate otherwise?

**Comment by maestromac** [comment]
Hello @Schwad , Ben is planning to leave his thought on how this feature should be tackled.

**Comment by rhymes** [comment]
We might want to make sure the list of favorite tags to be accessible only to the requesting user (via API) and _maybe_ to OAuthed apps. The reason why we might not want this info to be public is that it can be used to "profile" users

**Comment by danascheider** [comment]
Is anybody working on this? I might be able to pick it up if it's still a feature the maintainers would like to see added.

**Comment by rhymes** [comment]
@danascheider sorry for the major delay in communication. You can work on it if you're still interested! Let us know!

**Comment by danascheider** [comment]
@rhymes No worries! I'll get on it.

**Comment by danascheider** [comment]
@rhymes @dennislwm How do we want to identify favourite tags? What criteria would you like me to use to determine whether a tag is a favourite? Or are favourite tags already a thing in the app internally?

**Comment by dennislwm** [comment]
There is already a list of "MY TAGS", which are tags that you follow. In your Dashboard, click on "Following Tags", and you can "Adjust Follow Weight to make a tag show up less or more in your feed (default 1.0)".

**Comment by rhymes** [comment]
I think the list should be the list of followed tags, this is how the list is retrieved in the Dashboard controller:

https://github.com/thepracticaldev/dev.to/blob/8e0972dd330bf9464160b673e4a744897ad736c8/app/controllers/dashboards_controller.rb#L36-L39

**Comment by danascheider** [comment]
Cool, thanks!

**Comment by rhymes** [comment]
@danascheider also let's keep the "followed tags" nomenclature, instead of "favorite" I mean :)

Thank you!
