### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [forem/forem#5150]
**Is your feature request related to a problem? Please describe.**

Dev.to website is not reachable via IPv6. It would nice of you fix it.

**Describe the solution you'd like**

Enable IPv6 support for Dev.to website. Since it seems to use Fastly as CDN provider, they will happily enable IPv6 if emailed them.

**Describe alternatives you've considered**

https://docs.fastly.com/en/guides/ipv6-support

**Additional context**

It's 2019 and almost 2020 now, most of the websites are supporting IPv6. Please consider to enable IPv6 support for Dev.to too.

**Comment by jessleenyc** [comment]
Just a note here that I believe we had a fastly ticket open to discuss this issue previously -- looks like it got closed by stalebot.

**Comment by cmgorton** [comment]
@forem-team any thoughts on this issue? Wondering if I should add it to the Issues to be Reviewed?

**Comment by theoparis** [comment]
Why is this closed if dev.to does not have a AAAA record?
