### ISSUE TITLE
Need to change code to accommodate envie deprecation.

### ISSUE THREAD

**Issue by keithrbennett** [forem/forem#5152]
On running `bundle`, I got:

`DEPRECATION WARNING: Default values will be removed in the next minor-release of ENVied (i.e. > v0.9). For more info see https://gitlab.com/envied/envied/tree/0-9-releases#defaults. (called from block in load at /Users/kbennett/work/dev.to/Envfile:4)
`

I'm not familiar with this gem, but I _think_ we could just set the defaults directly into the `ENV` object instead, and will be issuing a PR with that approach.

At https://gitlab.com/envied/envied/tree/master#what-happened-to-default-values, they explain the issue. Their recommendation is that instead of setting default values in the application, create a script file that can be run on the command line to set the defaults. Do you want to do that instead? It would require a little more complexity to run.

**Comment by rhymes** [comment]
I think we should switch to use `.envrc` file as suggested in the best practices: https://gitlab.com/envied/envied/tree/master#best-practices. Many command line tools support "dotenv" files (which are just shell files that can be sourced in a Unix shell) and it's an established practice. Also, Heroku can easily export environment variables in that format.

I've always found weird how we handle default values for env variables, this would get closer to a standard that's agnostic to Ruby

**Comment by keithrbennett** [comment]
If the existing logic is correct, we don't want to use those default values in a production environment. Therefore, I think we need to handle this in the Ruby VM (so we can query `Rails.env.production?` or equivalent) and not at the shell level.

This change is small and does not change any real business logic. I am new here, but is there a risk that if we defer this change until we have debated and decided an alternate scheme, we will accomplish neither for a long time?

**Comment by rhymes** [comment]
AFAIK we haven't discussed this yet, at least not internally. I'll bring it up in the next tech meeting next year so we can give you and the community an answer that also takes under consideration our deployment process but in the meantime I don't think we are ready to commit to either option.

> If the existing logic is correct, we don't want to use those default values in a production environment.

`.env` files are not for the production environments, production doesn't even use the `application.yml` currently, it uses environent variables that are explicitly set in the Heroku build. `.env` files are never committed (as `application.yml` is never committed), what envied says is to have a `.envrc.sample` file that contains the defaults we have now in `Envfile`. The env file will be sourced at boot time by the app. 

Hope this is a clearer explanation eheh. Let me know if you have any questions

**Comment by keithrbennett** [comment]
Please see below...

> On Dec 26, 2019, at 17:23, rhymes <notifications@github.com> wrote:
> AFAIK we haven't discussed this yet, at least not internally. I'll bring it up in the next tech meeting next year so we can give you and the community an answer that also takes under consideration our deployment process but in the meantime I don't think we are ready to commit to either option.
> 
> 

I understand that we should probably change to using the environment file approach for configuration values. 

I've fixed the build errors in the PR associated with this issue in case you want to use it until we do.

It even addresses the first of several issues in Gitlab’s list of flaws at https://gitlab.com/envied/envied/tree/master#what-happened-to-default-values, since this change would put the default value in the ENV object, unlike the previous approach.

The .envrc/.envrc.sample approach would add a step for new users to make the application usable in development and test mode. It’s a very simple step, of course (`cp .envrc.sample .envrc`), but it would need to be documented and followed. Is that ok? If you like, I can create that .envrc.sample file. 

> If the existing logic is correct, we don't want to use those default values in a production environment.
> 
> .env files are not for the production environments, production doesn't even use the application.yml currently, it uses environent variables that are explicitly set in the Heroku build. .env files are never committed (as application.yml is never committed), what envied says is to have a .envrc.sample file that contains the defaults we have now in Envfile. The env file will be sourced at boot time by the app.
> 

Ok, thank you for explaining that.

> Hope this is a clearer explanation eheh. Let me know if you have any questions
> 

- Keith

**Comment by mstruve** [comment]
Since we are no longer using ENV'ied this issue can be closed 🎉
