### ISSUE TITLE
Add GitLab liquid tag

### ISSUE THREAD

**Issue by brycedorn** [forem/forem#5172]
**Is your feature request related to a problem? Please describe.**

Hi! I use [GitLab](https://about.gitlab.com/) to host my projects and would love it if I could link to them with the little preview that GitHub repos get. Could I make a PR adding a tag for it?

**Describe the solution you'd like**

`{% gitlab brycedorn/test %}`

Would look similar to GitHub repo one (and support the `no-readme` option). I wouldn't worry about adding tags for comments/issues/etc.

**Comment by jessleenyc** [comment]
I think in the past we've held off on this because we weren't sure how to go about implementing for repos that are self-hosted, but it probably makes sense to start with repos that are hosted by gitlab first.

**Comment by brycedorn** [comment]
@jessleenyc yeah I don't mean their [self-managed](https://about.gitlab.com/pricing/#self-managed) product, just public repos hosted by gitlab. I can make a note of this in the help section for the tag.

seems straightforward enough though, mind if I take a stab at it?

**Comment by jessleenyc** [comment]
Go for it @brycedorn !

**Comment by b3u** [comment]
I think that using the associated project id, instead of the user/repo, would work better (i.e. `{% gitlab project:16849821 %}`) because it requires no authentication. See <https://gitlab.com/api/v4/projects/16849821>

**Comment by fist28** [comment]
I can take it. 
@b3u  we can use user/repo for search project by API. 
endpoint `/projects/:id` allows to pas `user/repo` instead of id of project.
> :id - The ID or URL-encoded path of the project
https://docs.gitlab.com/ee/api/projects.html#get-single-project
https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding

I think that using the same convention as in Github will be better.

**Comment by davinkevin** [comment]
Very interested about this one!
