### ISSUE TITLE
notes on deploying to heroku

### ISSUE THREAD

**Issue by anle1337** [forem/forem#5188]
**Is your feature request related to a problem? Please describe.**

There's no instructions to deploy to heroku or prod

**Describe the solution you'd like**

I got the docker-compose working locally, but man deploying to prod is just not working

I'd love a writeup

**Comment by cmgorton** [comment]
Thank you for opening this request.
This one has been around for a while without much traction.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
