### ISSUE TITLE
HTTP_CLIENT_IP and HTTP_X_FORWARDED_FOR mismatch Causing IpSpoofAttackError

### ISSUE THREAD

**Issue by mstruve** [forem/forem#5223]
We are seeing a nontrivial amount of  `ActionDispatch::RemoteIp::IpSpoofAttackError` errors in Honeybadger. Most of which occur when the `/async_info/base_data` endpoint is called. When this error occurs this is what we see in Honeybadger
```
ActionDispatch::RemoteIp::IpSpoofAttackError: IP spoofing attack?! HTTP_CLIENT_IP="1.2.3.4" HTTP_X_FORWARDED_FOR="5.6.7.8"
 remote_ip.rb  136 calculate_ip(...)
[GEM_ROOT]/gems/actionpack-5.2.4/lib/action_dispatch/middleware/remote_ip.rb:136:in `calculate_ip'
134         if should_check_ip && !forwarded_ips.include?(client_ips.last)
135           # We don't know which came from the proxy, and which from the user
136           raise IpSpoofAttackError, "IP spoofing attack?! " \
137             "HTTP_CLIENT_IP=#{@req.client_ip.inspect} " \
138             "HTTP_X_FORWARDED_FOR=#{@req.x_forwarded_for.inspect}"
```

This endpoint is called in a couple of places in our javascript using the function `function fetchBaseData()` and my guess is that within those requests we are incorrectly setting the HTTP_CLIENT_IP. I came to this conclusion after reading [this stackoverflow answer](https://stackoverflow.com/a/31257295/1438582).  

The fix would be to find where this is happening and update the code to ensure there is no mismatch.

**Comment by cyrillefr** [comment]
Hello @mstruve,

I have been playing with the code and reproduced locally and got the Rails rejection:
- by curling with headers Client-ip & X-Forwarded-For (works for any page)
- by adding 2 setRequestHeader in the JS function fetchBaseData

I did not find that there is an explicit set of these 2 headers in code. (Maybe some gems/JS library is doing something behind the scene).

Could it be possible that in production, the call being made by the JS be added header(s) by a proxy or a caching device ?
Is this still happening ?

**Comment by rhymes** [comment]
@cyrillefr could you share the curl script and the code changes to the JS?

Thank you for investigating!

**Comment by mstruve** [comment]
Thank you @cyrillefr for investigating! We would love to see your script and YES it is definitely still happening.

**Comment by cyrillefr** [comment]
@mstruve , @rhymes 

`curl -H "X-Forwarded-For: 1.2.3.4" -H "Client_IP: 4.5.6.7" http://127.0.0.1:3000 > error.html `
-> you will see on the generated file : 
`IP spoofing attack?! HTTP_CLIENT_IP="4.5.6.7" HTTP_X_FORWARDED_FOR="1.2.3.4"`
One header does not raise an error, neither if the 2 headers have the same IP

To raise an error via adding headers on the JS call:
- app/views/pages//badge.html.erb
` xmlhttp.open("GET", "/async_info/base_data", true);`
 `xmlhttp.setRequestHeader("X-Forwarded-For", "1.2.3.4");     // added this line`                                                                 
 `xmlhttp.setRequestHeader("Client-IP", "5.6.7.8");                  // added this line`
 `xmlhttp.send();`

In URL: http://localhost:3000/badge
-> in Firefox, dev tools, console: is displayed: "SyntaxError: JSON.parse etc."
Problem with the line: `var json = JSON.parse(xmlhttp.responseText);`
With xmlhttp.status = 500. In the response(html), we can spot "<title>Action Controller: Exception caught</title>".
No error is generated without adding headers.

In the linked stackoverflow answer, the suggestion was that some device would add headers and raise that error.
From the call `xmlhttp.send()`, I cannot see why some headers be added to the call (I mean by the code)).

**Comment by mstruve** [comment]
This error seems to have gone away, closing!
