### ISSUE TITLE
Sort Reading List by Reading Time

### ISSUE THREAD

**Issue by CristinaRuth** [forem/forem#5237]
**Is your feature request related to a problem? Please describe.**

When I’m looking through my reading list of what to read, I typically have a specific amount of time I want to spend reading. 

It’s hard to sort through the list when there’s a lot (they pile up quick) to scan for my desired reading time. 

**Describe the solution you'd like**

I would like some sort of link/drop down/button to sort by reading time.

**Describe alternatives you've considered**

I can always scan the list for reading time, but it takes additional processing time for me as a user to do this.

**Comment by rhymes** [comment]
Love this idea :)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
