### ISSUE TITLE
Detect syntax highlighting when importing from RSS

### ISSUE THREAD

**Issue by diazgilberto** [forem/forem#5240]
**Describe the bug**

I have my personal blog with rss sync with Dev.to. I notice that the code snippets are not getting styled at all. I there anything else I need to do?

**To Reproduce**

See my [draft here](https://dev.to/gdiaz/how-to-test-throw-with-jest-53-temp-slug-8767226?preview=2a5989c9c3a91726228cdbbf00f2a46ca40c6ffeeb2438e6967cdb96684a18511bf4a6ba4e3695a4752bd8b3dff5653ac9f74e634c7b61a8d0f3bd5e)

RSS feed [here](https://gilbertodiaz.com/feed.xml).

**Expected behavior**

To have syntax highlighting on code snippets.

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS: `10.14.6`
- Browser: `Brave: Version 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)`

**Comment by amtwo** [comment]
On code snippets in DEV, you just need to add the language after the opening backticks, and it will add syntax highlighting for that language. 
Ex for SQL highlighting:
```
```sql
SELECT * 
FROM...```
```

I'm not sure how much variety there is on source blogs for Dev.to to be able to parse that detail from source RSS to automatically apply the language.

On my blog (WordPress with SyntaxHighlighter Evolved plugin), code samples are represented in the RSS as `<pre class="brush: sql; title: ; notranslate">` ... It would be fantastic if Dev.to could parse out the "brush: sql" from the `class` on the `pre` tag for RSS from WP installs using SyntaxHighlighter Evolved.  

But I know not all syntax highlighting works the same, so I would hope Dev.to could handle the most common scenarios, but wouldn't expect them to handle all of them. By contrast, the WP-GeSHi-Highlight plugin doesn't seem to expose the language in a consistent way, so parsing the language from WP-GeSHi-Highlight seems harder/impractical/impossible.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
