### ISSUE TITLE
Store user media on IPFS, and post content/user data as JSON

### ISSUE THREAD

**Issue by DaniellMesquita** [forem/forem#5242]

**Comment by rhymes** [comment]
Hi @DaniellMesquita, can you elaborate? Thank you! It's not clear what you're requesting with this feature request

**Comment by DaniellMesquita** [comment]
Alongside having user data in MySQL, it would also have it in JSON files, so user can get their files from IPFS.

Articles would be JSON files pointing to media, which also are in IPFS.
User data also as JSON files pointing to IPFS media.
The front site could also be a hosted app, with its IPFS address even using the server backend. It means, yet using the classical DB, while having a faster site running from IPFS cache.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
