### ISSUE TITLE
Go to the next post in a series

### ISSUE THREAD

**Issue by CodingDive** [forem/forem#5247]
Hey, first I'd like to thank all of you for building this wonderful platform/community 😍 

**Is your feature request related to a problem? Please describe.**
I find it difficult to navigate to the next blog post of a series.

**Describe the solution you'd like**
Add next/back options to posts in a series for binge reading 😀 

Another way to solve this is to add the upcoming post(s) of a series to the "More from @handle" section. Right now, it seems to always show the latest posts.

**Describe alternatives you've considered**

Navigating with the series menu underneath the title. If It's a longer series, the current post might even be hidden as seen in the image below (can't see post 22/23 and have to unfold first)

![image](https://user-images.githubusercontent.com/28842311/71456157-71718a00-2798-11ea-815a-61ce1e403274.png)

 
What do you think?

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
