### ISSUE TITLE
Mixture of irrelevant posts on the profile page.

### ISSUE THREAD

**Issue by joshi-chinmay** [forem/forem#525]
## Bug Report
I was scrolling through the feed, and went to the profile's page, and saw the weird list of posts. This behaviour occurred a few months back. I tried to reproduce, but it didn't happen again.
### Current Behavior
I clicked on the user's profile and scrolled through his/her profile. Once you reload the page, all the irrelevant posts to his/her profile are gone. This behaviour is hard to reproduce. 
### Steps to reproduce -
1. Open dev.to
2. As soon as the page opens, click on the profile icon.
![this-portion](https://user-images.githubusercontent.com/16207311/44763130-5a0e9680-ab7c-11e8-9cc1-80036cebf203.png)
3. Scroll the profile page. You are most likely to reproduce this behaviour.
### Expected Behavior
User's profile should contain his/her posts.
### Mobile & Desktop Screenshots/Recordings
When I clicked on the profile, I saw this - 
![full-page-with-bug](https://user-images.githubusercontent.com/16207311/44762811-eddf6300-ab7a-11e8-84b7-f2d3f8e7c917.png)

After a reload, it was auto-fixed - 
![full-page-after-reload](https://user-images.githubusercontent.com/16207311/44762821-f6379e00-ab7a-11e8-9619-63b12bede465.png)

(PS. Sorry for the poor quality of the first screenshot.)

**Comment by joshi-chinmay** [comment]
And, the same thing happened again -
![happened-again](https://user-images.githubusercontent.com/16207311/44763055-00a66780-ab7c-11e8-8691-1a15dded48f7.png)

**Comment by benhalpern** [comment]
Okay, I suspect this is possibly a race condition or something along those lines since we don't reload the page, it's possible that the pagination you triggered on the page you _were_ on is appended to the page you are now on.

We need to check for an indication that it's proper to append to this new view.

**Comment by joshi-chinmay** [comment]
Yep. I am looking at the code to see what's causing the issue.

**Comment by Zhao-Andy** [comment]
Not stale, should be looked into to make sure it's not still an issue.

**Comment by rhymes** [comment]
unstale

**Comment by mstruve** [comment]
Thanks @joshi-chinmay for bringing this to our attention! I checked a few profiles and I no longer see any issues. 

We recently overhauled our search infrastructure and during that time I found a lot of bugs in regards to filtering for articles. This was probably one of them that ended up being fixed during that overhaul so I am going to go ahead and close it.
