### ISSUE TITLE
Permanent Bookmarks in Reading List

### ISSUE THREAD

**Issue by CristinaRuth** [forem/forem#5260]
**Is your feature request related to a problem? Please describe.**

I've accumulated a lot on my reading list, but some of them I've already read and would still like to keep for future reference. I don't want to "archive" them because I don't want to lose sight of them.

Currently, it's getting more difficult to parse through my reading list on which ones I've kept for future reference and which ones I've still yet to read.

**Describe the solution you'd like**

I'd like a way to permanently "bookmark" an article on my reading list and be able to see those in a filtered view of some sort. 

**Describe alternatives you've considered**

For now, I'm just visually parsing my reading list. Not sure of other alternatives on this.

**Comment by rhymes** [comment]
I think the archive functionality is what you are looking for, a permament place to archive your items. 

In the archive they don't disappear, it's like a folder. It has the search like the regular reading list so you can find the items back. Am I missing something?

**Comment by CristinaRuth** [comment]
Where can I see the archive folder? 

I guess I see archive as I’m done reading it. I don’t want to take away the “bookmark” from an article just because I’ve already read it?

Permanent bookmarks are different in my vocabulary. “Archive” seems to indicate they are obsolete.

**Comment by CristinaRuth** [comment]
I just found the archive. It's quite hidden - I never would have found it if you didn't say it's viewable. 😂

Scrolling through my archive, I still have the same issue though. I guess I could use the archive as the "permanent" spots. 

How do I remove posts from my reading list then without taking away the bookmark tag from them and not archiving them?

**Comment by rhymes** [comment]
> How do I remove posts from my reading list then without taking away the bookmark tag from them and not archiving them?

@CristinaRuth what do you mean? You can either unbookmark an article, from its own page, or you can archive it...

**Comment by CristinaRuth** [comment]
That’s exactly my point. It’s minor and not a big deal though. The article I’ve bookmarked has earned a “reaction”. When I’m done reading it, I know I can “unbookmark” it but it takes away a reaction and I would prefer not to do that. 

Really the 3 categories in my head:
* To read 
* Done reading but don't want to keep and don't take a reaction away from article 
* Done reading and want to keep

The 2nd point is where I get stuck on. And again, it's just a minor thing. 🙂

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
