### ISSUE TITLE
Automatically add the `#firstpost` tag to make it easy to welcome first post writers

### ISSUE THREAD

**Issue by jmfayard** [forem/forem#5274]
**Is your feature request related to a problem? Please describe.**

I want to make it more likely that new writers receive early positive feedback.

**Describe the solution you'd like**

If the user click on **write a post** 
and has never published a post before, 
then automatically add the `#firstpost` tag.

![Screenshot 2019-12-28 at 16 24 36](https://user-images.githubusercontent.com/459464/71545707-9a5b7000-298e-11ea-9b6e-76208eb19abe.png)

This would make it easy for people wanting give early positive feedback to firstposters.
Just follow `{% tag firstpost %}` 
and give a nice comment when you see the tag `#firstpost`.

**Describe alternatives you've considered**

Write a post to encourage people to write their first post and tag it with `#firstpost` (I will also do it!)

Have a special view where we can see users who write their first post (but I find better to leverage existing features).

**Additional context**

Starting blogging is hard. When you write that first post, you fear to have nothing interesting to say, you are unsure about your writing skills, smarter people than you have written on the same topic as you before, ...

If you have nevertheless published that first post but the world didn't care, it's hard to continue.

If on the other hand you have received positive early feedback, that can be enough to make you want to continue,  and who knows which awesome things you will write later?

**Comment by jmfayard** [comment]
Hello @michael-tharrington 
Have you talked again about this feature?

**Comment by michael-tharrington** [comment]
Thanks for flagging this! Admittedly, I'd forgotten to bring this up. I will do very soon!

**Comment by michael-tharrington** [comment]
I know I hit you up in DMs about this but wanted to also mention here that we have a good, alternative way for mods to recognize and respond to first posters now - https://dev.to/mod?state=new-authors ... however, I still think the #firstpost tag is quite cool and allows the community (not just mods) the ability to easily recognize first time posters. But, I also think that it's cool to leave this tag as optional for first time posters.

**Comment by jmfayard** [comment]
Ah interesting.

But the #firstpost tag can be both by default and optional, right?

Put it by default when you enter the screen, let the user remove it if she
want before she submits

**Comment by michael-tharrington** [comment]
True! But, I don't think it's a priority at this time because of: [https://dev.to/mod?state=new-authors](https://dev.to/mod?state=new-authors) ... we'll let others weigh in here if they want.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
