### ISSUE TITLE
Change search bar to search button on small (240x320) resolutions

### ISSUE THREAD

**Issue by Shem-G** [forem/forem#5275]
**Is your feature request related to a problem? Please describe.**

When viewing Dev at on very small resolutions, the search bar is shrunk but still overlaid by the Connect button:
![Screen Shot 2019-12-28 at 18 30 20](https://user-images.githubusercontent.com/45176983/71548098-3f7f4400-29a1-11ea-835a-a743ddb4acba.png)

**Describe the solution you'd like**

On small devices, hide the search bar behind a magnifying glass menu item instead of displaying the search bar. Have the search bar expand when the icon is clicked. Very rough mockups:
![r1](https://user-images.githubusercontent.com/45176983/71548101-473ee880-29a1-11ea-9ac7-5a0fd3e9a8bc.png)
![r2](https://user-images.githubusercontent.com/45176983/71548104-52921400-29a1-11ea-9546-d441b8277959.png)

**Comment by maestromac** [comment]
That is a nice idea and a good to have @ShemTheDev ! Out of curiosity, which device do you own that would yield this width constraints?

**Comment by ShemTheDev** [comment]
Hi Mac. I own the Nokia 8110- a Kai OS smart featurephone:
![IMG_20200103_224157_1](https://user-images.githubusercontent.com/45176983/71753417-7ca07600-2e7a-11ea-87d6-6d1e78b806df.jpg)

**Comment by mvasigh** [comment]
I love this! I can work on it.

**Comment by ShemTheDev** [comment]
Thanks @mvasigh! It might be worth collapsing search again when the text field loses focus. Kai users can unfocus a textbox at any time to continue scrolling/moving their cursor, so leaving it open might make the other menu items less accessible.

**Comment by mvasigh** [comment]
> Thanks @mvasigh! It might be worth collapsing search again when the text field loses focus. Kai users can unfocus a textbox at any time to continue scrolling/moving their cursor, so leaving it open might make the other menu items less accessible.

Yes I like that idea! I was thinking along the same lines actually, but thanks for validating what the browser can do. 

I'm thinking, cover the entire nav bar with the search input when the icon is clicked (expanded) and hide/collapse the input when the field is blurred or submitted. Downside is you don't see your search term once you've submitted (really the search results should display something like `Displaying 99 results for "Web Workers"`) but the upside is better use of space.

**Comment by ShemTheDev** [comment]
I agree the, in terms of usability, search results take priority over pagination, headings, etc. Please let me know if I can do anything to help. I'm happy to send more photos of various elements on my Kai OS device.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
