### ISSUE TITLE
Block Feature Does Not Seem to Work as Expected

### ISSUE THREAD

**Issue by ferricoxide** [forem/forem#5342]
While filling in the bug-summary field, it popped up a related bug. In reading through that thread, I found [this response](/thepracticaldev/dev.to/issues/3145#issuecomment-503233931) that noted:

> Given above, a user you blocked would be:
> 
>  * unable to follow you
>  * unable to react and comment on your published articles
>  * unable to reply to your comments on other threads/articles
>  * unable to open a direct chat channel with you (automatically block on Connect as well)
>
> You would also be:
>
>  * unable to follow the blocked user
>  * unable to see their posts on your feed
>  * capable of un-blocking a user
>  * unable to interact with them (articles/comments/chat).

However, as near a I can tell, the only thing I've verified that blocking another user currently does is prevents notifications of the blocked-user's activities (no additional alerts on the bell icon/indicator in the upper right of the web page view). The "_unable to reply to your comments on other threads/articles_", "_unable to see their posts on your feed_" and "_unable to interact with them (articles/comments/chat)_" were not working as of a couple days ago.

**Comment by cmgorton** [comment]
@forem-team this might be a good bug to add to the Issues to Review. It seems more than one person has brought this up.

**Comment by atsmith813** [comment]
Hey @ferricoxide, thanks for this report! I tested this out and they all seem to work for me except

> unable to see their posts on your feed

Which I have a fix going up for shortly. Does this match your experience, do the other things work for you?

Thanks!
