### ISSUE TITLE
Allow configuring hardcoded Codepen embed height

### ISSUE THREAD

**Issue by web-padawan** [forem/forem#5346]
As an author, I sometimes need to embed Codepen with small examples which don't need too much space. But it turns out that `height` for the embedded pen is hardcoded:
https://github.com/thepracticaldev/dev.to/blob/de6129b29ca5b3634291429a911cf188d68ea2ad/app/liquid_tags/codepen_tag.rb#L16

I'd like to be able to change this number. In certain cases 300px is well enough.
So let me suggest to expose it as a parameter that can be passed to embed.

**Comment by nickytonline** [comment]
Thanks for the issue @web-padawan. I think height could be an additional optional parameter for the codepen liquid tag.

**Comment by cmgorton** [comment]
Thank you for opening this request.
This feature has been around for a while without much traction.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
