### ISSUE TITLE
Add Embed support for ColdFusion (TryCF.com & CFFiddle.org)

### ISSUE THREAD

**Issue by JamoCA** [forem/forem#5353]
**Is your feature request related to a problem? Please describe.**

Hi.  I'm new to DEV.to.  I've been a ColdFusion developer since 1997.  This isn't really a "problem", as much as a request to extend support to embedded fiddles for ColdFusion/CFML developers.

**Describe the solution you'd like**

TryCF.com has documentation regarding how to create links to embed GISTS.
https://www.trycf.com/help
For an example of this, check out the "run code" examples on CFDocs.org.
https://cfdocs.org/queryaddcolumn

I'm not sure how CFFiddle.org would be embedded.  Adobe doesn't provide much information, but they do have the ability to save snippets and "Try in CFFiddle" on their documentation site.  Example:
https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/queryaddcolumn.html

**Describe alternatives you've considered**

Unknown.  I'm new and not trying to hack the platform. Tumblr didn't allow any embedding (not even GIST) and I've decided to make DEV.to my new home regardless of whether this feature is added or not.

**Additional context**

I think I'd prefer to have the full-screen TryCF.com editor embeded.  Here's an example:
https://www.trycf.com/editor/gist/bc948b141eea337a1927a311e6b500e9?engine=acf2016

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
