### ISSUE TITLE
Improve DuckDuckGo Privacy Rating

### ISSUE THREAD

**Issue by abenerd** [forem/forem#5387]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but I think dev.to can improve it's privacy rating. As of now dev.to receives a still good B+ but I believe that this can still be improved. Right now the plugin complains about one tracker it found on the website and unknown privacy practices. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
The plugin I used can be found here: [https://duckduckgo.com/app](https://duckduckgo.com/app)

**Comment by Glennmen** [comment]
Can you post a screenshot of the report or the tracker it is complaining about? Just curious.

**Comment by abenettt** [comment]
@Glennmen Interestingly enough the plugin does not show me which tracker it is, even tho it tells me it is a major one.

**Comment by rhymes** [comment]
I assume it's Google Analytics, which is the only known tracker we have in the source code

This is what the DuckDuckGo Privacy report looks like:

![Screenshot 2020-01-08 at 12 13 54 PM](https://user-images.githubusercontent.com/146201/71974157-0cdf1200-3211-11ea-88c5-dc654ea15f19.png)

![Screenshot 2020-01-08 at 12 14 08 PM](https://user-images.githubusercontent.com/146201/71974190-24b69600-3211-11ea-9ff9-7698ffe67088.png)

In fact both Privacy Badger and uBlock Origin block Google Analytics by default:

![Screenshot 2020-01-08 at 12 17 32 PM](https://user-images.githubusercontent.com/146201/71974200-2bdda400-3211-11ea-9ebb-279a1fe153c1.png)

![Screenshot 2020-01-08 at 12 17 55 PM](https://user-images.githubusercontent.com/146201/71974210-313aee80-3211-11ea-91da-c355125d7d0c.png)

**Comment by Glennmen** [comment]
Also wanted to add from the Brave browser build-in blocker:
![image](https://user-images.githubusercontent.com/11406433/71974587-20d74380-3212-11ea-808e-3a0eb30cf32c.png)

**Comment by rhymes** [comment]
I feel the second one is the classic problem of naming anything with the word "ad" in its URL :D

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
