### ISSUE TITLE
Cannot unfollow some tags

### ISSUE THREAD

**Issue by flexdinesh** [forem/forem#5397]
**Describe the bug**

I've been cleaning up my account and noticed that I can't unfollow some old tags like `#databases` and `#todayigoogled`. When I open the page, the button says "FOLLOW" meaning I am not following that tag but it shows up in the list of tags I follow in my home page. Might be related, these tags seemed to be renamed sometime in the past. My OCD wants to get rid of those dead tags from my home page.

**To Reproduce**

1. Go to 'homepage'
2. Click on 'the above mentioned or tags that have been renamed in the past
3. You will be navigated to tag page
4. You will see the button say "FOLLOW" instead of "FOLLOWING". Cannot unfollow.

**Expected behavior**

Should be able to unfollow renamed tags.

**Screenshots**

tags in home page: 

![tags in home page](https://i.ibb.co/bBNJq0P/devto-tags.png)

can't unfollow:

![can't unfollow](https://i.ibb.co/ftmTQVQ/devto-tags-cant-unfollow.png)

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser: Brave
- Version: Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)

**Comment by renatamarques97** [comment]
I'd like to take care of this issue

**Comment by mstruve** [comment]
Fixed with https://github.com/forem/forem/pull/10324
