### ISSUE TITLE
Add category in reading list to group similar topics in one place.

### ISSUE THREAD

**Issue by duptitung** [forem/forem#5413]
**Is your feature request related to a problem? Please describe.**
There is a lack of proper article organization in reading list. I have a huge list of articles of various topics on my reading list all clamped in a single place. It can be very difficult to find the one you want to read later among those hundreds of articles. 

**Describe the solution you'd like**
Add a feature to add category in the reading list. For example:
<ul>
<li>A React category to save all your react related articles </li>
<li>A Python category to save all your python related articles</li>
</ul>
Users can create category as per their need so that it will be easier to find the one article they want to read in pool of reading list. If i want to read an article about CSS that i saved months ago, I will just have to look into my CSS category.

**Comment by rhymes** [comment]
Hi @duptitung, in the meantime you can use tags in the sidebar. If you click on them you'll see only items with that tag (which is basically a category). You can also search by keyword. Let me know if that works for you, a bit at least

**Comment by duptitung** [comment]
Hi @rhymes, Tag and search are both great features. I do use them but they don't provide the organization capability that category provides. And also people might add unrelated popular tags for greater reach. For example, there are many articles that have both javascript and css tag so when i use css tag filter those javascript articles also show up.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
