### ISSUE TITLE
Series: Posts disappear when giving old posts a series tag.

### ISSUE THREAD

**Issue by miku86** [forem/forem#5433]
**Describe the bug**

I updated some old posts to be in a `series`.
The normal behaviour in a series is, that the series box always shows all posts of the series, no matter which part of the series I am currently at.

**Example:**

Expected: My series has 5 posts. When I read part 3, the series box shows 5 posts and the current one (part 3) is highlighted.

Bug: My series has  5 posts. When I am logged in and read part 3, the series box shows **only 3 posts** and the current one (part 3) is highlighted. **Part 4 and part 5 (all after the current one) have disappeared.**

**To Reproduce**

1. Take at least 2 old posts and give each one the same `series` tag.
2. While logged in, go to  the last post of the series. (like you would read it)
3. While logged in, go to the series box and click on the second to last.
4. The last post in the series box disappears

**Expected behavior**

When I am logged in, I expect that every post of the series is in the series box. Logged out behavior doesn't bug.

**Screenshots**

I edited 5 posts into a series.

When logged out, it works as expected: https://www.youtube.com/watch?v=TGQaYzLdG9c

When logged in, some posts in the series box disappear: https://www.youtube.com/watch?v=TGQaYzLdG9c&t=09s

**Desktop (please complete the following information):**

- OS: Arch Linux 5.4.8-arch1-1
- Browser: Firefox Developer 73.0b2 and Chromium 79.0.3945.117

**Additional Information**

- I disabled browser extensions
- I used both Firefox and Chromium
- I deleted cache and service workers

**Comment by cmgorton** [comment]
Hey @miku86 is this still an issue for you?

**Comment by miku86** [comment]
Hey @cmgorton,

thanks for reaching out still after such a long time.
I gave this a quick test and it seems to work properly now :+1:

I will close the issue.

Thanks for your work
Michael
