### ISSUE TITLE
Feature request: Go to random post

### ISSUE THREAD

**Issue by anaschwendler** [forem/forem#5435]
**Is your feature request related to a problem? Please describe.**
It is not a problem I must say, but I would love to have this feature in case I'm just walking around the website and don't want to pick an article (I want to be surprised, let's say)

**Describe the solution you'd like**
Just a button to go to a random post

**Describe alternatives you've considered**
Going to categories and picking up one post?

**Additional context**
Maybe when in categories, pick a random post in the category?
Maybe the name could be [`I'm feeling lucky`](https://en.wikipedia.org/wiki/Google_Search#%22I'm_Feeling_Lucky%22)

Thanks a lot 🎉 🥂

**Comment by benhalpern** [comment]
I like something like this, especially in mobile where it might be a fun way to navigate and discover new stuff.

**Comment by renatamarques97** [comment]
I'd love to help with this one

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
