### ISSUE TITLE
Don't notify about already read posts

### ISSUE THREAD

**Issue by abenettt** [forem/forem#5436]
**Is your feature request related to a problem? Please describe.**
I was reading a posts when DEV suddenly notified me that this posts has been published. It feels rather redundant especially as I'm already in this very same post. Is there a way to omit the notification should the posts already be read?

**Describe the solution you'd like**
Is there some kind of history of posts, one has read, if so one could use this to omit the notification. Or when the notification arrives at the frontend one could check if the post one is currently reading matches the posts on the notification and thus omit it. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
