### ISSUE TITLE
Archiving an item in the reading list is not instantaneous and affects UX

### ISSUE THREAD

**Issue by osde8info** [forem/forem#5444]
goto https://dev.to/readinglist
click archive next to an article
click https://dev.to/readinglist/archive
the article you just "archived" doesnt appear on the list until you manually 
re-enter https://dev.to/readinglist/archive into browser nav bar

**Comment by rhymes** [comment]
Thanks @osde8info, I updated the title to make it a little bit more explicit.

**Comment by rhymes** [comment]
I don't think this is still an issue as the UI has changed since then. I tried and it seems instantaneous to me
