### ISSUE TITLE
API: endpoint to get list of user ids who reacted to an article

### ISSUE THREAD

**Issue by yashwanth2804** [forem/forem#5453]

**Comment by rhymes** [comment]
No, we don't have one

**Comment by osde8info** [comment]
yes please too

**Comment by renanbona** [comment]
I would like to take this issue. Can you give me more information about where do you want this end point? Would it be a new controller? Or just add a new action to an existing controller?

**Comment by rhymes** [comment]
Hi @renanbona, stricly speaking this issues hasn't been approved yet.

We'll discuss it internally and get back to you ASAP.

In the meantime if you want you can to contribute on already approved issues, [those labeled "help wanted"](https://github.com/thepracticaldev/dev.to/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) for example.

Thank you!

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
