### ISSUE TITLE
Editor: add a button to open the editor guide in a separate tab

### ISSUE THREAD

**Issue by osde8info** [forem/forem#5462]
would like to be able to see "Editor Guide 🤓" content in separate window tab (instead of popup) so i can create content at same time as reading doc

**Comment by osde8info** [comment]
maybe a nice little link to https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#code would be the answer :)

**Comment by rhymes** [comment]
You can find the editor guide here: https://dev.to/p/editor_guide

Let me know if that's what you're looking for

**Comment by osde8info** [comment]
brilliant thanks a button on the edit page with a link to https://dev.to/p/editor_guide would be perfect

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
