### ISSUE TITLE
Allow "New Navigation SideBar Links" to be defined by a site config or /internal admin

### ISSUE THREAD

**Issue by leewynne** [forem/forem#5475]
**Is your feature request related to a problem? Please describe.**

As a future admin of a generalised community i'd like the ability to add to the navigation sidebar links with additional community products such as books, movies etc.

**Describe the solution you'd like**

An addition to the Internal/Pages siteadmin view that allows for the creation of extra links in the navigation sidebar including:
1. Friendly name
2. Icon (the podcast icon as an example).
3. The destination page url
4. A value that sets whether the link should be shown in the sidebar 'pre auth' or not.

**Additional context**

See suggested screenshot.

<img width="209" alt="Screenshot 2020-01-13 at 09 04 15" src="https://user-images.githubusercontent.com/12694270/72243374-b3495f80-35e3-11ea-8ec7-91991ebaa1f6.png">

Similar issue here but for the key links sidebar item below it . 

https://github.com/thepracticaldev/dev.to/issues/4661

**Comment by cmgorton** [comment]
Looks like this feature was added per Ridhwana's PR. If not let me know and I will open this back up. Thanks!
