### ISSUE TITLE
using dev.to insert a link to a glitch dot file gives an error

### ISSUE THREAD

**Issue by osde8info** [forem/forem#5499]
**Describe the bug**

using dev.to insert a link to a glitch dot file such as .prettierrc (file=.prettierrc) when i click PREVIEW i get the error

**To Reproduce**

insert a link to a .file on glitch

**Expected behavior**

no error

**Screenshots**

Heads up:

base:  Invalid Options

**Desktop (please complete the following information):**

- OS:          xubuntu 18
- Browser: ff 72
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

see 
https://dev.to/osde8info/dev-to-glitch-dotfile-refs-n59

**Comment by rhymes** [comment]
Hi @osde8info, thanks for the info, could you share the markdown you used?

I saw you linked a post but if you could share its source, or at least the part that triggers the error, it would be of help.

Thank you!
