### ISSUE TITLE
Allow "onboarding images and text" to be defined by site config

### ISSUE THREAD

**Issue by leewynne** [forem/forem#5507]
**Is your feature request related to a problem? Please describe.**

As a future side admin of a generalised community, I would like to customer the onboarding intro slides with a custom background image, logo and welcome text and custom questions.

**Describe the solution you'd like**

A SiteConfig array of on boarding labels / questions. A siteconfig settings for the background image and a site config settings for the welcome text.

**Additional context**

Everything is currently hardcoded in IntroSlide.jsx, please see the attached images for further guidence.

Onboarding 1:
<img width="1424" alt="Screenshot 2020-01-14 at 13 02 50" src="https://user-images.githubusercontent.com/12694270/72347251-9db16400-36cf-11ea-8f5c-27956d265b16.png">

Onboarding 2:
<img width="1003" alt="Screenshot 2020-01-14 at 13 15 10" src="https://user-images.githubusercontent.com/12694270/72347373-ecf79480-36cf-11ea-9870-fc9fbb6bca47.png">

Onboarding 3:
<img width="993" alt="Screenshot 2020-01-14 at 13 10 41" src="https://user-images.githubusercontent.com/12694270/72347286-b02b9d80-36cf-11ea-9f41-edc107ab75aa.png">

**Comment by cmgorton** [comment]
Looks like this feature was added with #8431. I am going to close this but let me know if that is NOT the case and I can open it back up. Thanks.
