### ISSUE TITLE
devto write a post image upload popup is broken 

### ISSUE THREAD

**Issue by osde8info** [forem/forem#5542]
**Describe the bug**

click image upload icon choose a HEAD and a BODY image only the HEAD image appears in blog post see https://dev.to/osde8info/a-devto-test-post-to-test-image-upload-bug-3l0h

**To Reproduce**

click image upload icon choose a HEAD and a BODY image only the HEAD image appears in blog post see https://dev.to/osde8info/a-devto-test-post-to-test-image-upload-bug-3l0h

**Expected behavior**

expect to HEAD image and BODY image

**Screenshots**

**Desktop (please complete the following information):**

- OS: xubuntu 18
- Browser: ff 72
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @osde8info, I'm not sure I understood what's the bug, could you perhaps record how to trigger this?

I use [LICECap](https://www.cockos.com/licecap/) to record the screen as a gif when I submit PRs but it's Windows and macOS only but I'm sure there are equivalents for xubuntu or Linux in general.

Thank you!

**Comment by osde8info** [comment]
MY SCREEN IS TOO SMALL ONLY 700 PIXELS HIGH

your widget displays cut and paste code BELOW my screen so i cant see it and cant cut and paste it

https://dev.to/osde8info/another-cool-leaflet-map-example-7fo

PLEASE turn this into a feature req for "support for 700 px high screens" if you dont think think is a bug

**Comment by osde8info** [comment]
alternatively a feature req to auto insert image code instead of requiring cut and paste

**Comment by rhymes** [comment]
It's not about what I think eheh, it's about understanding what's the issue, could you at least provide a screenshot of the bug you're encountering?

**Comment by osde8info** [comment]
i think there are a few bugs and feature requests in one here

* sometimes the cut and paste button doesnt even appear on the screen win10+ff72
* sometimes the done button doesnt appear on the screen if screen height < 700 
* would be nice if it just pasted the image code for you instead of you having to CTRL-V it

i will try and create screenshots for all 3 of these asap

**Comment by rhymes** [comment]
Hi @osde8info, let me know if you can provide the screenshots. 

ps. the third poing is a feature request, that's probably out of the scope of this issue
