### ISSUE TITLE
Suggested articles: allow direct access to author profile from article preview

### ISSUE THREAD

**Issue by abenettt** [forem/forem#5641]
**Is your feature request related to a problem? Please describe.**
When showing suggested articles in the more articles preview, allow the user to go to the articles author directly via their name without having to open the article first. 

**Describe the solution you'd like**
One could probably make the article author into a link that leads to their profile page.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/7523903/72880394-1ed7af00-3cff-11ea-8df6-bf1d633e7000.png)

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
I know I have closed a few of your requests so if you want any help turning these in to forem.dev posts for further discussion please let me know. Happy to help!
