### ISSUE TITLE
Add a "View Source" button for Posts

### ISSUE THREAD

**Issue by jjant** [forem/forem#5652]
**Describe the solution you'd like**

When learning the formatting used in dev.to, it'd be really useful to be able to go to posts one likes and click a "View Source" button to understand how you can write articles that look like that.

**Describe alternatives you've considered**

I think alternatives to this is just documentation, which there is available, this feature would complement it more than being a replacement.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
