### ISSUE TITLE
search feature in followers / following section

### ISSUE THREAD

**Issue by RaiSaugat** [forem/forem#5661]
I wanted to search for the user in following page. Now I'm hitting **CTRL + F** for the search. This gets the work done but a dedicated search might be useful and handy. 
The search can be normal search that filter out the results and shows the final result. 👍

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
