### ISSUE TITLE
please remove infinite scroll

### ISSUE THREAD

**Issue by tamb** [forem/forem#5670]
I'm super frustrated when I try to access the footer of the site or see a manageable amount of articles on the homepage.  Infinite scroll keeps pushing the footer down and the throwing in new articles that make scrolling back to the top much longer.

**Describe the solution you'd like**

I would love to see pagination or "see 5 more" added to the app.  I would even be fine with horizontal scrolling.  View 1 has 5 articles you can scroll down through and then you can swipe left to View 2 and see another list of the next 5 articles.

**Comment by rhymes** [comment]
Hi @tamb, thanks for your issue, can you elaborate a little bit by filling the body of the request? What prompted you to request the removal of infinite scroll? 
What alternative solution would you like? Any alternatives to such solution?

**Comment by Defman21** [comment]
FYI, the footer is duplicated on the left sidebar

![image](https://user-images.githubusercontent.com/7100645/73338043-c2d4d380-4286-11ea-9c10-a51949cf6e56.png)

**Comment by tamb** [comment]
@Defman21 I noticed that.  But there's also a huge accessibility concern with infinite scrolling:
https://accessible360.com/accessible360-blog/accessibility-problems-infinite-scrolling/

**Comment by jacobSingh** [comment]
Yep, came here to report the same bug.  If you're going to do infinite scroll, I would just remove the footer - it only confuses people.

Otherwise make the footer fully horizontal and fixed at the bottom could work

**Comment by ardunster** [comment]
Myself I dislike infinite scroll in general as it seems like a cheap trick to trap the user's attention. Or maybe that's just because of the Facebook association.... Anyway, I'd be in favor of either a 'load more' button or pagination, infinite scroll is a loss of user control and those of us who like to control our environment are unlikely to ever enjoy it ;)

**Comment by marcysutton** [comment]
> I would just remove the footer - it only confuses people.

> Otherwise make the footer fully horizontal and fixed at the bottom could work

I would add that keyboard users may never be able to reach interactive items in the footer even with fixed CSS positioning if new items keep getting injected into the tab order before it. So I would concur that removing infinite scroll is a good idea for multiple reasons!

**Comment by marcysutton** [comment]
I did some screen reader testing recently for #11560 and infinite scrolling came up, so I'll quote my findings here:

> On the live site, from what I can tell assistive tech users can't easily get to the footer landmark content due to the infinite scroll. So whether `content-visibility` on the footer suppresses content access is kind of moot on those pages 🤷🏻‍♀️
>
> The Voiceover Rotor shows infinite article tags in the landmark inspector, so you can't ever get to the footer if it follows those elements in the DOM. TIL the rotor updates with DOM changes! Same with NVDA's Elements List.

The infinite scroll adds elements to the DOM, which impacts the accessibility tree as well. It updates live, as one would expect, but it also means you can't ever reach the end of the DOM. So the footer content is unreachable to pretty much everyone on pages with the infinite scroll.

**Comment by cmgorton** [comment]
Please see this https://github.com/forem/forem/discussions/15322 for further discussion on infinite scroll.
