### ISSUE TITLE
Add special #listing(s) tag for promotional posts

### ISSUE THREAD

**Issue by CodeMouse92** [forem/forem#5672]
**Is your feature request related to a problem? Please describe.**

Listings are, necessarily, quite short. However, many users of the DEV platform seem to feel they need more space to describe their product, service, or software, and this makes sense.

As a result, a number of users will publish promotional-focused DEV which, aside from violating the Terms of Use, also come across as "spam" to many readers.

In short, there are two problems:

* Some users need to use the long format of a Post to add detail that won't fit in a Listing.
* Said posts are annoying to many users when they appear in the normal feeds.

**Describe the solution you'd like**

1. The `#listings` tag exists, but was never given a formal purpose. I propose we repurpose it for **promotional posts**.

2. Posts under `#listings` are forcibly removed from *all feeds* except its own. That is, a post may be tagged as `listings python beginners`, but the mere presence of `listings` will ensure it does not show up in the `#python` or `#beginners` feeds, nor in search.

3. Users may include a link to their `#listing` post in their Listing: **this will be the only way that a `#listings` post can be viewed without directly having the link.

It would be important to alias `#listing` and `#listings`.

Some other things to consider, perhaps later:

* A message visible only to the post author, alerting them that listings are not shown in normal feeds, and prompting them to create a corresponding Listing.

* A canonical "read more" link field in Create Listings.

* (Possibly) the ability of any tag moderator to add the `listings` tag to a post. That way, otherwise good promotional posts can be *moved* without requiring negative actions (Vomit, Downvote).

**Describe alternatives you've considered**

We could retool the Listings themselves to support longer format. However, this would replicate a lot of work already done on Posts, so it would probably be simpler to just connect the two.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).

**Comment by CodeMouse92** [comment]
https://forem.dev/codemouse92/add-special-listing-s-tag-for-promotional-posts-56d8

**Comment by cmgorton** [comment]
Thank you @CodeMouse92! Checking out the post now.
