### ISSUE TITLE
articles in the reading list should be available offline

### ISSUE THREAD

**Issue by saurabh-codeword** [forem/forem#5692]
**Is your feature request related to a problem? Please describe.**
I'm doing a lot of travelling on sloppy and no internet connection, and it would be great If I can read my dev.to's saved articles offline. This can make the overall experience of dev.to much better

**Describe the solution you'd like**
- articles can be cached by service worker at the time of saving later,  
- offline page can be modified to show offlin'ed articles 

**Describe alternatives you've considered**

**Additional context**

**Comment by madarsbiss** [comment]
Just use Pocket for that. It does just that and even more - it allows you to access saved articles in offline mode, allowing to save them from any other site too and furthermore sync all your saved stuff across all your devices.

**Comment by b3u** [comment]
@madarsbiss pocket offline seems to be a mac-only product. This solution would be cross-platform.

Also, there should probably be an opt-in/opt-out toggle in setttings.

**Comment by ezio1404** [comment]
**Describe the solution you'd like**

I would like to suggest that there is an option that you can download them all in batch and by selected filters.

**Describe alternatives you've considered**

Feature 1 : Download all Post Content with comments
Feature 2: Download only Post Content

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
