### ISSUE TITLE
Add the ability to search and include images from unsplash.com in the image uploader

### ISSUE THREAD

**Issue by madzadev** [forem/forem#5693]
**Is your feature request related to a problem? Please describe.**

Currently the image upload modal offers upload just from users workstation. It would be nice if there was an option to browse outside sources right from it, as manually including an outside URL right in the post currently requires an outside search, copying and pasting a link,  adding  and formatting credit by user itself (if user decides to do that at all (!!!), and leaving various ways of doing it).
 
**Describe the solution you'd like**

Idea comes from medium.com. User can search for unsplash.com content right in the modal and select image to add from the results. Once published, the footer section of an image gets automatically added, including source from it's base website and proper credit to author of an image. This way each and every image would be formatted equally, making them look neat.

**Describe alternatives you've considered**

I would recommend unsplash.com cause of huge amount of images, thought-out search algo and  properly credited content. But surely there are many more sources. Maybe modal should contain multiple site options for variety in case if looked-up content is not available?

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
