### ISSUE TITLE
YouTube Subscriptions / Channels in SideBar (Identical to Podcasts)

### ISSUE THREAD

**Issue by leewynne** [forem/forem#5695]
**Is your feature request related to a problem? Please describe.**

Like Podcasts. YouTube is a critical learning platform for any community member. It was so critical to my journey and I am sure everyone else was the same. I would love to see curated YouTube subsriptions that are high quality and essential viewing when joining a new community.

**Describe the solution you'd like**

I feel the best approach would be playlist based, so very similar to the Podcast list where a channel is provided and lists recently broadcast YouTube videos, but you add the channel, then maybe specificy the playlist specific to the subscription.

I think a new model would be needed with the same task for fetching all videos that are listed within a specific channel > playlist.

The video ideally should play in the Dev app.

**Describe alternatives you've considered**

Creating a page and linking it in the sidebar menu, but it is too dynamic and requires lots of manual html.

**Comment by bigdoods** [comment]
This is exactly the feature we want too for AecHive.net. Our community is very visual and there are many YouTube channels that are tackling educational based topics that we want to share. 

We are seeing huge appetite from our community as an aggregation platform and we are using this approach to build value for our users. 

We hope this feature lands fast and we are willing to help make it happen. 

Beyond this, we would like to do the same for blog posts. However this is another topic/suggestion for another day 😁

**Comment by cmgorton** [comment]
@leewynne would you create a post in [forem.dev](forem.dev) for this feature request? That way it can get more discussion around it and if people like it I can potentially pitch it as an RFC to our engineers. 

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
