### ISSUE TITLE
Stripe. New users cannot add new credit card (on first attempt).

### ISSUE THREAD

**Issue by leewynne** [forem/forem#5726]
![5AF20E7D-8D21-4DF0-90F3-EA8FDF6C801E](https://user-images.githubusercontent.com/12694270/73120589-32d21980-3f68-11ea-8145-a0c204782f13.jpeg)

**Describe the bug**

As a new user. If you go to your settings and billing, then attempt to add a new card, you get a 404 error. If you got back and try again, eventually you receive the Stripe checkout pop up.

**To Reproduce**

Ensure you are a new user account

**Expected behavior**

Immediate pop up of Stripe element to populate credit card and the ability to edit existing.

**Screenshots**

**Desktop (please complete the following information):**

All versions

**Smartphone (please complete the following information):**

All versions

**Additional context**

HoneyBadger provides a good overview on the issue, looks initially to be related to ‘StripeCheckout’ not working correctly.

**Comment by brunojs02** [comment]
There's another issue, after u got the error, the message for add credit card is 'add another credit card', but I still don't have any

**Comment by imwra** [comment]
I just got the same issue. First time on page I wasn't able to add a card. After refreshing the page the button worked.

**Comment by imwra** [comment]
Seems like this is already being tracking on #2867.

**Comment by cmgorton** [comment]
This is a duplicate issue. Any more discussion on this can be done in issue #2867. Thanks!
