### ISSUE TITLE
Handle linebreaks in markdown

### ISSUE THREAD

**Issue by Defman21** [forem/forem#575]
## Feature Request or Task

Feature request.

### User Story / Description

I'm writing my articles in a code editor and line-break them manually at 80 chars, so I could read them anywhere without worrying about word-wrap and stuff. Markdown does not count these line-breaks as line-breaks and every markdown parser I saw join them automatically, so

```md
Hello
world
```

becomes

```md
Hello world
```

Dev.to, however, handle them as line-breaks.

### Definition of Done

```md
Hello
world
```

in a dev.to article renders as

```md
Hello world
```

**Comment by jessleenyc** [comment]
One of the concerns here is that any changes we make to the way we handle markdown rendering needs to be backwards compatible. We could probably make this work by creating a configuration that authors can tweak on their own.

**Comment by glebec** [comment]
@jessleenyc another option would be to apply the change in parsing to only new articles (with an explicit note for all new articles that that is the case). I don't know that I _like_ that idea, it feels like adding complexity and implicit behavior, but I figured it was worth noting as a possibility.

**Comment by dguo** [comment]
I have the same issue. I write posts with Vim (which I have set to automatically wrap lines at 80 characters) and add them to a repo for my personal website. I'd like to crosspost to dev.to, but this issue means I can't just copy and paste as is. I know Markdown is generally ambiguous, but I haven't encountered any other renderers with this behavior.

In the meantime, I'm using Vim to [join lines together](https://stackoverflow.com/a/5651510/1481479).

**Comment by bwl21** [comment]
Github has a different behaviour for Issues and other places. I find this pretty strange and annoying.

 see: https://github.community/t5/How-to-use-Git-and-GitHub/Why-does-markdown-in-issues-respect-line-breaks/m-p/18637

**Comment by alex-at-cascade** [comment]
Trying to publish my first article on dev.to, just ran into this and was completely confused!  Will be happy when a fix is available.

**Comment by danihodovic** [comment]
Is this going to be addressed at some point in the near future? It's super annoying to have to modify every article that is cross-posted on dev.to

**Comment by cmgorton** [comment]
Because this seems to be stale and we are now talking about markdown configuration in general in #1492, I am going to go a head and close this issue. If you have more comments on line breaks and markdown please leave them in issue #1492. I will add that issue to a project board so it gets more visibility. Thanks.
