### ISSUE TITLE
New Changes clear link is too close to Save Changes and doesn't pick up on Ctrl+Z.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [forem/forem#5763]
**Describe the bug**

There are two related issues:

1. The `New Changes (clear)` text is too close to the `Save Changes` button, and is also too small on desktop.

2. If you undo changes with Ctrl+Z, the draft still thinks there are unsaved changes.

![image](https://user-images.githubusercontent.com/19352442/73188018-414b3d00-40f0-11ea-8101-5bbd65a584c1.png)

**To Reproduce**

1. Create a post.

2. Click `Edit` to edit the post.

3. Make changes to the post's contents. Observe that the `New Changes (clear)` link appears above the blue `Save Changes` button, and that it's too close.

4. Undo all of your changes with Ctrl+Z. Observe that `New Changes (clear)` still remains.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 79

**Proposed solution**

What about introducing a separate inline button, `Cancel`, that just backs out of the editor and discards all changes?

**Comment by cmgorton** [comment]
The layout for this appears to have changed. I don't think this is an issue anymore. I am going to close this but let me know if it is and I will reopen this. Thanks!
