### ISSUE TITLE
Remove HardCoded AWS Image URLs and Download Images into /assets 

### ISSUE THREAD

**Issue by mstruve** [forem/forem#5810]
Throughout our codebase, we have a lot of hardcoded AWS image urls. [Here is an example](https://github.com/thepracticaldev/dev.to/pull/5799/files) of a few of them. There are even more examples sprinkled all over the views. 

Rather than updating the AWS bucket name everywhere which will break for many people's local integrations we should download these images and add them to the `/assets/images` directory so they can be served directly from the app. In addition, we should give those that we download pertinent names relating to what they are so when another community would like to spin up this codebase for their own purposes they can replace the images with ones that represent their use case.

**Comment by seb1441** [comment]
I will do it.

**Comment by citizen428** [comment]
Thank you @seb1441, you're on a roll 👍

**Comment by rhymes** [comment]
@seb1441 a small suggestion: it's better to have multiple PRs than one huge one, if you find yourself working on too many files :)

**Comment by seb1441** [comment]
@rhymes I will have around 30 files (mainly views) to update for this PR, but it's mostly one line changes. Would you recommend me to split that into multiple PRs like 10 files each?

Another question, is it the right way to take issues to just write "I will do it"? 😆
As you probably noticed, it's my first time working on an open source project.

**Comment by rhymes** [comment]
@seb1441 I think 30 is fine, thank you! Declaring your intentions is also fine, this way we can assign the issue to you so nobody will attempt to solve the same problem.

Thank you a lot for your contributions and.. welcome to open source I guess :-D

**Comment by mstruve** [comment]
We still have these in our docs but all have been removed from the codebase thanks to our recent generalization push 😄
