### ISSUE TITLE
Infinite scroll possible html nesting bug

### ISSUE THREAD

**Issue by pavelloz** [forem/forem#5827]
**Describe the bug**

It looks like infinite scroll is inserting new dom nodes inside a container, creating nested level. For some reason sometimes its just couple nodes, sometimes more. This might not be a big problem, but i think there is a performance penalty for that. At least thats what Lighthouse suggests.

It is also possible that normal posts are also nested unnecessairly into divs (see screenshot 2)

**To Reproduce**

1. Go to feed
2. Scroll down couple of screens
3. Inspect DOM

**Screenshots**

1. <img width="744" alt="image" src="https://user-images.githubusercontent.com/546845/73586084-e1b2b000-44a8-11ea-8980-38669fd6ebcb.png">

2. <img width="679" alt="image" src="https://user-images.githubusercontent.com/546845/73586137-6c93aa80-44a9-11ea-8e74-6db6ce617f97.png">

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: for feature requests, please wait until we add a `help-wanted` label to the issue before starting to work on it. Bugs instead are always open for contributions.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @maestromac or @rhymes or @citizen428 from the DEV team and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hey @pavelloz thank you for pointing this out. Looks like this was also mentioned [here](https://github.com/forem/forem/issues/5670#issuecomment-737647087) by Marcy Sutton. Since there is already a lot of discussion in issue #5670 including this information I am going to close this one. Any additional thoughts you have can be added to #5670.
