### ISSUE TITLE
Ignore user from a feed without having to block them

### ISSUE THREAD

**Issue by pavelloz** [forem/forem#5836]
**Is your feature request related to a problem? Please describe.**

I knew this day will happen, i just hoped someone else will have to create this issue (maybe it already exist, i couldnt find it).

Because of rules, or lack of on what people can write and share on dev.to there will be a lot of crap (subjectively, what im not interested in and want to filter out - not objectively of course :) ). There is a lot of crap. Its getting very expensive to get through self promoting 3 paragraphs articles to fish out something valuable.

In the past couple of days we have an user that is basically the only thing i see on the feed, as a result i just give up and go away, because im not interested in the topic (cannot unfollow tags, still) and especially opening the post, seeing its basically a manual forward, and going to his blog to find out if it has any value.

**Describe the solution you'd like**

Let me block users that i dont want to have anything to do with. Since i can follow them and get notified about their writing, i want to have a choice to curate what i see further.

**Describe alternatives you've considered**

Banning users who go overboard.

**Additional context**

This is my feed, its very similar, for the past couple of days.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/546845/73607646-039b5800-45b9-11ea-90ba-e647c006ac78.png">

It has 5 links to outside page per one paragraph post. Every time. If its even content its a subject for another discussion. But the point is, i (and propably a lot of other people because im not a snowflake) want to avoid seeing it in the future, i think ive seen enough.

This is whats inside every single one of those posts.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/546845/73607652-10b84700-45b9-11ea-9d8c-20dd06b4cebc.png">

Nothing personal, its just one of many people doing it, maybe first example that IMO went so far that its unbearable to use dev.to for me. On twitter its very time consuming to stay in the loop if you are not interested in drama/spam, but at least its possible. On dev.to its currently not possible at all.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: for feature requests, please wait until we add a `help-wanted` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @maestromac or @rhymes or @citizen428 from the DEV team and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @pavelloz, I understand your frustration, have you tried in the meantime to block the user directly? 

You can go on their account and block them like this:

![block feature on DEV](https://user-images.githubusercontent.com/17884966/66757833-fff98f00-ee6a-11e9-83fd-f8d73e27c8d7.png)

**Comment by pavelloz** [comment]
I havent tried that. Im not necessairly against his comments, PMs - its just the feed that im trying to clean up from posts from
a) tags that are really not in my area and i dont like,
b) people who treat dev.to as republishing / ad platform for their blog

Having said that, ill try that and see what happens - im out of options anyways :)

**Comment by rhymes** [comment]
Thanks for the details @pavelloz! I updated the title to make it more specific :)

**Comment by pavelloz** [comment]
Cant wait :)

With the bugged tag ignore it makes it very hard to use feed.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/546845/74562206-9bf6ec80-4f6a-11ea-8996-2a6f351b58ba.png">

<details>
<img src="https://user-images.githubusercontent.com/546845/74562140-723dc580-4f6a-11ea-82c9-858868622993.jpg"/>
</details>

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. This one has been around for a while with out much traction.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
