### ISSUE TITLE
Add option to tweet from specific satellites on /internal/articles

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#5838]
**Is your feature request related to a problem? Please describe.**
As a content editor, I want to syndicate articles to the appropriate Twitter satellite account.  Sometimes, a post has tags for multiple eligible satellites, but I'd prefer to send it to only one or the other.  Currently, it will syndicate to all eligible satellites and doesn't offer more granular control.

**Describe the solution you'd like**
An option in `/internal/articles` to choose which satellite(s) to share to.  Screenshots below.

**Additional context**
- This page is on `/internal/articles` and is opened after clicking "Share to Buffer" for posts that are satellite eligible
- More details on [reaching the page](https://github.com/thepracticaldev/dev.to/issues/4276#issuecomment-539179806) from a related issue
- This might be difficult to reach in development, as you'll need to establish "satellite eligible" tags that are configured with Buffer

### Current
![current satellite chooser](https://cl.ly/079930c9b2ea/Image%202020-02-02%20at%202.57.35%20PM.png)

### Desired
![desired satellite chooser](https://cl.ly/047184b69e1a/Image%202020-02-02%20at%202.45.12%20PM.png)

**Comment by cmgorton** [comment]
@pkfrank Not sure if you are still interested in this feature but wondering if I should mark it as a `potential RFC` ?

**Comment by cmgorton** [comment]
Since we recently got rid of the "Share to Buffer" functionality I am not sure this issue is something we can implement now. I am going to close it for now but let me know if you would like me to reopen it. Thanks!

**Comment by pkfrank** [comment]
> I am going to close it for now but let me know if you would like me to reopen it.

Yup, let's go ahead and close.  Thanks @cmgorton!
