### ISSUE TITLE
Allow end to end encrypted emails

### ISSUE THREAD

**Issue by abenettt** [forem/forem#5862]
**Is your feature request related to a problem? Please describe.**
dev.to does not send encrypted emails as far as I know.

**Describe the solution you'd like**
Allow the users and organisations to add their PGP Key(s) to their account and to opt in to receiving encrypted emails. That would allow the platform to send users encrypted emails and users between themselves to do so. 

**Describe alternatives you've considered**

**Additional context**
Sorry for bad wording.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: please wait until we add a `help-wanted` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @maestromac or @rhymes or @citizen428 from the DEV team and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@abenettt Thanks for the feature request. Could you elaborate on your intended use case a little bit? I don't think there are any emails sent from the DEV platform to users where encryption would be beneficial, but I could maybe see a use case for signing for certain emails.

**Comment by abenettt** [comment]
@citizen428 I think it might generally just be a good idea, but the emails could also hold potentially sensitive information like for example when the user receives an email about a direct message or a new follower. I don't know about security-related emails, as I have never received such, but these would also build a strong case for encryption in my opinion.

**Comment by citizen428** [comment]
Your followers are visible to anyone visiting your profile, so I don't think that's particularly sensitive. A point could maybe be made for private messages, *if* they contain the actual message and not just a notification that there was a message. 

The problem with GPG is that it comes with a certain overhead, which is part of the reason websites don't generally offer it as an option.

But I'm definitely open to the idea if there's enough support for it.

**Comment by abenettt** [comment]
Ok, I can see the overhead can be an issue. But if you'd allow me, I'd change tracks and say that it is also 2020 now and the question should rather be why we wouldn't implement this. The argument that it would introduce an overhead would of course still be standing but is this overhead enough not to do this?

**Comment by citizen428** [comment]
I think this question could be reversed: are enough users interested in this to be worth the effort of adding it? I'm a PGP user myself since ~2001, but I still don't see a particularly strong use case for it in regards to transactional email. Either way, this is just my personal opinion and not an official DEV one, and I'd personally be more than happy to work on this if we decide to go ahead with it.

**Comment by abenettt** [comment]
Yeah, I can see your point, but I also like to think that as DEV is a developer centred community that its users would supportive of this idea.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
