### ISSUE TITLE
Accessibility: Add keyboard navigation to feed

### ISSUE THREAD

**Issue by brycedorn** [forem/forem#596]
## Feature Request or Task

Add listeners for `j` & `k` to scroll up one or down a post in the feed. This would align it more with other feeds (Twitter, Tumblr, etc), and is a nice way to scroll through content.

This also goes along with https://github.com/thepracticaldev/dev.to/issues/121 and https://github.com/thepracticaldev/dev.to/issues/394.

### Definition of Done

Pressing `j` or `k` will initiate keyboard navigation, which will apply the `focus` state to the first fully-visible element in the feed (skipping any that are partially scrolled past/visible), and bring it to the top of the screen. Then, any subsequent presses of those keys will move one element up or down, respectively.

**Comment by AntonyGarand** [comment]
In the meantime, you can use an extension such as `Vimium` to navigate using the keyboard.
I use `u` and `d` to move `up` and `down` and it works quite well!

**Comment by brycedorn** [comment]
This is great, thanks for pointing me there @nickytonline! It'd be nice to pull out any global key listeners into a separate class, especially if anyone wants to add a new one in the future. I can help out with this, let me know if there's a good time I should tackle it & not conflict with anything else being worked on!

And yes @AntonyGarand I did try using that extension for a little while (when I tried to go full-keyboard for everything), but it's too much effort. I'd rather have it be smarter & know exactly where to scroll to 😸

**Comment by benhalpern** [comment]
I think for now, ensuring we support vimium is the best option, but in the long run I could see us trying to have a richer set of native controls, probably ones that work with vim expectations.

**Comment by Zhao-Andy** [comment]
Not stale

**Comment by maestromac** [comment]
not stale
