### ISSUE TITLE
Stackbit 'Getting Started' page doesn't scroll on iPad app

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#5972]
On the Dev.to iPad app, the Stackbit 'Getting Started' page doesn't scroll. 

To reproduce:
- On an account without Stackbit integration enabled, navigate to Settings -> Integrations
- Under 'Connect to Stackbit' tap 'Getting Started'
The page that opens can't be scrolled in the Dev.to iPad app, and must manually be opened in Safari

**Comment by cmgorton** [comment]
@joshpuetz do you know if this is still an issue?

**Comment by joshpuetz** [comment]
This is no longer an issue 🥳 Closing!
