### ISSUE TITLE
Introduce docker-sync into our Docker workflow

### ISSUE THREAD

**Issue by citizen428** [forem/forem#5977]
**Is your feature request related to a problem? Please describe.**

Docker on macOS is infamously slow in combination with volumes, due to bad IO performance (up to 60 times slower). This makes working with our app hard, as simple setup steps like `docker-compose run web rails db:setup` can take a very long time to complete.

**Describe the solution you'd like**

Add [docker-sync](http://docker-sync.io/) to our workflow to speed up the Docker-based workflow.

**Describe alternatives you've considered**

Leaving as-is. 

**Additional context**

See e.g. [this article](https://medium.com/@eduardosasso/moving-a-rails-monolith-to-docker-8da0f98d4b1e) regarding the process.

**Comment by maestromac** [comment]
I'm really excited about this! I've tried this many moons ago but I was unable to get it working.
