### ISSUE TITLE
Allow "dev account" to be safely set by an admin

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#6049]
**Is your feature request related to a problem? Please describe.**

For security and safety purposes, we recently [decided to move away](https://github.com/thepracticaldev/dev.to/pull/6009) from letting admins explicitly set the "staff user" ID from the `/internal/config` pages. For the time being, we plan to just have this be set as an ENV var directly as `STAFF_USER_ID`, with the hope that the person setting it will ensure that the ID selected will not create issues.

**Describe the solution you'd like**

However, it would be ideal to let admins change the "staff user" account, but _safely_! To that end, I propose a feature somewhere in the `/internal` routes that allows an admin to select a specific user account from a dropdown of designated "admin" users. The admin should be able to select an account, and hit a submit button to an endpoint. I'd expect that endpoint to find the appropriate user account and set that account as the "staff user account".

This is safer than just allowing admins to input any id (which could be typo'ed and end up being the id for someone who definitely shouldn't be the staff account! 😬). If we create a dropdown for this, then we can use the account/user's name + email, which is much more human-readable than an id.

This would also be scalable for communities outside of DEV! ✨

**Comment by benhalpern** [comment]
I feel like many of the configs in this area are _just about as dangerous_ as `STAFF_USER_ID` so our current strategy of _restrict access and be super duper careful_ is not a viable solution and it's very fabulous that you are raising the concern.

> For the time being, we plan to just have this be set as an ENV var directly as STAFF_USER_ID, with the hope that the person setting it will ensure that the ID selected will not create issues.

I think more people have access to env vars than this dashboard and we change those more often, so in some ways it might not be safer to go that route. I think we should immediately add better guardrails around the `SiteConfig` area.

I say we stick with `SiteConfig` and make it _way way way way_ harder to make a mistake. I can take a run at this tomorrow.

**Comment by vaidehijoshi** [comment]
@benhalpern This seems okay to me. Sorry for the back and forth, it just seemed like something we should fix immediately so I opted to remove the ability to change it from the page.

> I think more people have access to env vars than this dashboard and we change those more often, so in some ways it might not be safer to go that route.

Did not know about this!

I'm okay sticking with the `SiteConfig` as long as we have guards against Bad Things. Down the road (closer to opening up to other communities), I do think it would be great to make it possible for admins to change this without having to know the id, and just being able to select specific accounts for this kind of thing. Obviously not important/necessary at the moment, though!

There are two recent PRs that have changes you'll probably want in the process of reverting back: #6045 (specifically [this](https://github.com/thepracticaldev/dev.to/pull/6045/files#diff-15a14006185d617d9a9da06c439ae624R167) line) and #6009.

**Comment by benhalpern** [comment]
I don't think there are any perfectly right answers. I love that this is being addressed and I'm happy that decisions were made on principle even if we shift once again. This is bringing light to a situation that shouldn't have gone much longer in the current setup. Having someone accidentally change a config is probably one of my biggest nightmares. 😭

**Comment by rhymes** [comment]
> I do think it would be great to make it possible for admins to change this without having to know the id, and just being able to select specific accounts for this kind of thing. Obviously not important/necessary at the moment, though!

> Having someone accidentally change a config is probably one of my biggest nightmares. 

In addition to complicating the path to "accidental destruction", we could also rekindle the idea of adding audit logs.

There was an attempt at adding auditing to admin operations but it's implemented only for moderators I think: [Moderator audit logs](https://github.com/thepracticaldev/dev.to/pull/3449)

cc @vaidehijoshi @benhalpern

**Comment by benhalpern** [comment]
@rhymes yes, we have a small component of mod audit logs going in as part of @Zhao-Andy and @jacobherrington project so that should help ween us that way.

**Comment by vaidehijoshi** [comment]
Closing this issue out since we've added some additional safeguards to solve this. Also, with the generalization of Forem, some of the concerns from this original issue don't quite apply in the same way.
