### ISSUE TITLE
@thread mention

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#6065]
**Is your feature request related to a problem? Please describe.**

As an admin, tag mod, or author of a post, I might want to leave a comment which addresses everyone who has already commented in the thread.

It might be that I want to weigh in on a topic I am late to as a site admin and give everyone my thoughts. I might want to let the whole thread know that because things are getting heated we may need to take action. Or simply assure folks that mods are paying attention.

**Describe the solution you'd like**

If I type `@thread` (or maybe `@all`? or something else) I create a mention for all users in that thread.

The mention notification should account for it being this "type" of mention and likely have slightly different copy but otherwise I think this can run through normal mention infrastructure.

**Additional context**

There is an element of spammy abuse, but I think restricting this to authors/mods/admins makes this work. If anyone abuses this, we deal with them via warning/suspension. It might be worth codifying what this kind of abuse looks like though.

**Comment by b3u** [comment]
another alternative is `@here`
