### ISSUE TITLE
Setting for disabling autoplay

### ISSUE THREAD

**Issue by kingdamian42** [forem/forem#6067]
**Is your feature request related to a problem? Please describe.**
Auto-playing videos are not great, especially when browsing at work.

**Describe the solution you'd like**
Please provide a setting in misc to allow the disabling of auto-play videos

**Describe alternatives you've considered**
I can keep my sound off at all times I guess?

**Additional context**

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: for feature requests, please wait until we add a `ready for dev` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @kingdamian42, a question, which browser are you using?

**Comment by michael-tharrington** [comment]
First off, thanks so much bringing up this issue! I can confirm that another user recently reported this to us as a problem.

Some other considerations:

1. Autoplaying videos is also problematic b/c it may accidentally eat up bandwidth/data for mobile users. I think we should definitely turn off autoplay for mobile users.

2. One alternative we could potentially use for desktop users would be to auto-mute the video. That said, I personally don't think this is better than just pausing the video. When videos auto-play but are muted you often have to rewind them to the beginning anyway.

**Comment by vaidehijoshi** [comment]
+1 to this issue! I'd vote that we don't autoplay at all on mobile. For web browsers, I'd be okay with autoplaying as long as but videos default to being _muted_ on web. But I'm also okay with @michael-tharrington's suggestion to just not autoplay on web, either!

**Comment by fdoxyz** [comment]
+1 from me on all the feedback above as well.

[This method](https://github.com/forem/forem/blob/master/app/assets/javascripts/initializers/initializeVideoPlayback.js#L67-L86) is where the web video player is configured. We would need a PR that follows the autoplay criteria mentioned above.

**Context:** Currently the native mobile experience does not have autoplay. The caveat is that iOS currently hasn't shipped the support for this so the fallback is using the web player.

For the moment then, I think the consensus would be to change the web player to **not autoplay**

**Comment by reobin** [comment]
Good stuff! I'll work on this

**Comment by fdoxyz** [comment]
Thank you @reobin I just assigned the issue to you
