### ISSUE TITLE
Reaction count disappears after scrolling

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#6072]
**Describe the bug**

There're situations in which reaction count disappear. It happens locally as well as on prod. On page load everything looks fine, but when I scroll down the feed, some DOM elements are being refreshed (reloaded?) and they no longer contain reactions count in the feed card. Here's a video showing feed on /latest: https://d.pr/v/qTyUUU

From what I noticed, I believe that happens only on feed items that have 0 reactions.

**To Reproduce**

1. Go to [Latest](https://dev.to/latest) (although you can spot it on other listings) because it's the easiest to see posts with 0 reactions there. 
2. All feed items visible on page load should have reactions count visible.
2. Scroll down a bit...
3. Now scroll back to the top and boom - feed items that used have 0 reactions now don't show reactions at all.

**Expected behavior**
Always show reactions count.

**Screenshots**

Here's video: https://d.pr/v/qTyUUU

**Desktop**

- OS: macOS 10.15.2
- Browser: Chrome 79.0.3945.88

**Comment by mstruve** [comment]
Hey @ludwiczakpawel I was just playing around with this on DEV and the issue looks to be resolved, I could not recreate it so I am going to go ahead and close this. 

Also, HOLY COW the old UI, I am just now realizing how far we have some. 💯 thanks to you 😄
