### ISSUE TITLE
Home page that is constantly being updated

### ISSUE THREAD

**Issue by mzaini30** [forem/forem#6086]
**Is your feature request related to a problem? Please describe.**

When I opened my homepage, I saw that the posts on the homepage did not change. So, I feel confused, what I want to read because all these posts I have read.

**Describe the solution you'd like**

I want a home page like Facebook or Quora that always displays a different post every time I refresh / reload.

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: for feature requests, please wait until we add a `ready for dev` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
