### ISSUE TITLE
Add CodePen URL field to Profile page

### ISSUE THREAD

**Issue by azzcatdesign** [forem/forem#6087]
**Feature Request**

If we're talking to developers, we should include CodePen profile. So many of us use CodePen, both free version and paid. Even use this for job application/code challenges. Many of us work out reduction solutions to code problems, as well as search for others' solutions to common CSS/HTML/JS problems. Not to mention, there's some really cool CSS/JS that people share on CodePen!

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: for feature requests, please wait until we add a `ready for dev` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by osde8info** [comment]
how about DEVIANTART & PINTEREST links TOO

**Comment by rhymes** [comment]
Hi @osde8info, as this issue is about CodePen I think it'd be better to open feature requests for each service you'd like to see considered

**Comment by michael-tharrington** [comment]
Any chance this would make for a good first issue? I just spoke with another DEV user who requested this, so thought I'd tag with `good first issue` to see if someone may want to pick it up. 🙂

**Comment by Zhao-Andy** [comment]
I think we're going to hold off on adding new fields for a bit, since we're in the process of getting the profile more usable for Forem!

**Comment by michael-tharrington** [comment]
That totally makes sense. There are lots of fields in there currently and I know we've also had requests to streamline this area of settings.

**Comment by citizen428** [comment]
As one of the people driving the profile revamp, I wouldn't object to adding this field now during cooldown. It does make sense for a developer community and in the end, just becomes one more custom field we need to add to DEV when migrating profiles. I'm also ok with holding off though.

**Comment by ewaDev** [comment]
Hi folks! I would be interested in giving this a go if poss!

**Comment by rhymes** [comment]
@ewaDev thanks for volunteering, this hasn't been specifically approved yet though, so it might be better to hold off until it is. In the meantime I suggest checking issues labeled [hacktoberfest](https://github.com/forem/forem/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest) and/or [ready for dev](https://github.com/forem/forem/issues?q=is%3Aissue+is%3Aopen+label%3A%22ready+for+dev%22) or [any of the bugs](https://github.com/forem/forem/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22).

Thank you!

**Comment by cmgorton** [comment]
Hey all, there has been some good discussion here but given this is a very DEV-centric feature and we are trying to think more in terms of Forem in general, I propose we forgo this and the added clutter it will add to the profile link section. 
I love CodePen. As a potential solution I add my CodePen profile link to my "currently hacking on" section.  For now, I propose we close this issue.
