### ISSUE TITLE
Comment in a thread does not have a page but is not erased

### ISSUE THREAD

**Issue by brandelune** [forem/forem#6090]
**Describe the bug**

Rachel Soderberg's June 24 '19 comment here:
https://dev.to/espoir/how-do-you-handle-unproductive-days-at-work-2heh

does not open a page when clicking on the date.

Also, when I tried to write a comment below her's I got a "markdown error..." see attachment.

**To Reproduce**

1) click on the date of her comment → the "there is no page" page appears
2) try to submit a comment → the "markdown error" message appears

**Expected behavior**

1) I get a separate page for her comment
2) I can submit a comment on her comment

**Screenshots**

<img width="717" alt="Screen Shot 2020-02-16 at 17 25 08" src="https://user-images.githubusercontent.com/28946328/74601494-64ab4b80-50e2-11ea-9d82-282168a69995.png">

**Desktop (please complete the following information):**

- OS: macos 10.15.3
- Browser: Safari
- Version:  13.0.5

**Comment by citizen428** [comment]
Hi @brandelune!

Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: for feature requests, please wait until we add a `ready for dev` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
This appears to be an isolated incident. I am going to close this for now but we can reopen this issue if anyone else experiences this again!
