### ISSUE TITLE
Dev.to comments API does not describe when a comment was published

### ISSUE THREAD

**Issue by gajus** [forem/forem#6095]
Example:

https://dev.to/api/comments?a_id=95907

There is no information about when each comment was published.

This information is required for integration into http://gitspo.com/.

**Comment by gajus** [comment]
On a similar note, the API does not provide the numeric ID.

Related: https://github.com/thepracticaldev/dev.to/issues/6096

**Comment by citizen428** [comment]
Hi @gajus!

Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.
    
To our amazing contributors: for feature requests, please wait until we add a `ready for dev` label to the issue before starting to work on it.
    
To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.
    
For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by gajus** [comment]
For anyone who needs a workaround:

```js
import got from 'got';
import surgeon, {
  subroutineAliasPreset,
} from 'surgeon';

const x = surgeon({
  subroutines: subroutineAliasPreset,
});

/**
 * @see https://github.com/thepracticaldev/dev.to/issues/6095
 * @see https://github.com/thepracticaldev/dev.to/issues/6095
 */
const getDevtoComment = async (commentUrl: string, foreignCommentId: string) => {
  const response = (await got(commentUrl)).body;

  const datetime = x('saf #' + foreignCommentId + '+.single-comment-node .comment-date time | read attribute datetime', response);

  return {
    id: x('saf #' + foreignCommentId + '+.single-comment-node | read attribute data-comment-id', response),
    publishedAt: moment(datetime, 'YYYY-MM-DD HH:mm:ss').toDate().getTime(),
  };
};


```

**Comment by jkrsn98** [comment]
I would like to work on this issue

**Comment by rhymes** [comment]
Hi @jkrsn98, go ahead! The comments have a `created_at` field which contains the date it was published. You can take this as a reference 

https://github.com/forem/forem/blob/c18b0f1ba1ec8a2577e6f799b4cdc6d19464b8f7/app/views/api/v0/articles/_article.json.jbuilder#L22

thank you!
