### ISSUE TITLE
Add "already following" info on the dashboard's list of followers

### ISSUE THREAD

**Issue by osde8info** [forem/forem#6099]
**Is your feature request related to a problem? Please describe.**

please add IM ALREADY FOLLOWING FLAG to https://dev.to/dashboard/user_followers list

**Describe the solution you'd like**
please add IM ALREADY FOLLOWING FLAG to https://dev.to/dashboard/user_followers list

**Describe alternatives you've considered**
NONE

**Additional context**

please add IM ALREADY FOLLOWING FLAG to https://dev.to/dashboard/user_followers list

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: for feature requests, please wait until we add a `ready for dev` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
