### ISSUE TITLE
Add Pinterest URL field to Profile page

### ISSUE THREAD

**Issue by osde8info** [forem/forem#6118]
**Is your feature request related to a problem? Please describe.**

same as https://github.com/thepracticaldev/dev.to/issues/6087#issuecomment-586989462 but for PINTEREST
**Describe the solution you'd like**

same as https://github.com/thepracticaldev/dev.to/issues/6087#issuecomment-586989462 but for PINTEREST
**Describe alternatives you've considered**

**Additional context**

**Comment by maestromac** [comment]
Thanks for the issue! I went ahead and updated the title to clarify the request.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by b3u** [comment]
@maestromac the oss team seems to be defunct, as the link goes nowhere

**Comment by maestromac** [comment]
@b3u It's a private team but it will ping the proper people when you use it. Thank you though for pointing that out, I wasn't aware that it's not a public-facing link.

**Comment by cmgorton** [comment]
Hey! Since we are trying to think more in terms of Forem in general, I propose we forgo this and the added clutter it will add to the profile link section. I think in the future a proposal like #6163 could help with the need for more link options.  
For now, I propose we close this issue.
