### ISSUE TITLE
Dev Contributor Chat

### ISSUE THREAD

**Issue by binyamin** [forem/forem#6148]
I've been working on #5172, and I had trouble setting up my local DEV environment (I worked it out in the end). It was frustrating that there was no way to get in touch with other contributors without opening a formal issue.

If there was a group chat for DEV contributors, it may be easier for first-timers to contribute. Some popular, free platforms are Gitter, Discord, and Slack. A forum (discourse, et al) is another option.

**Comment by maestromac** [comment]
We do have a DEV connect group chat for contributors but it's currently not an open group. If you would like to join, feel free to send me a message on https://dev.to/maestromac

**Comment by cmgorton** [comment]
We now have [forem.dev](forem.dev) for this as well! You can ask for help, request features, etc.
