### ISSUE TITLE
Profile link settings is becoming cluttered

### ISSUE THREAD

**Issue by binyamin** [forem/forem#6163]
**Is your feature request related to a problem? Please describe.**
There are a few issues requesting more profile link fields (deviantart #6117, pinterest #6118, codepen #6087), but there is not much space in the UI to display them all without increasing the page-scroll time. I expect that there will be more requests to come.
- The current UI is easily susceptible to becoming cluttered with fields irrelevant to some users
- Requiring a full section in *settings* for each added link weighs-down the interface and, each link requires more work.

**Describe the solution you'd like**
I would like all the profile link fields to be condensed, and use a single field with an option to add more fields as needed. A good example of this in the wild is with YouTube, when editing the links displayed on the about page of a channel. The icon could be inferred by using the url and/or site metadata, and connect the brand name with <https://simpleicons.org> (which is actually the idea that spurred this issue).

**Describe alternatives you've considered**
Some other ideas I had are using a typeahead control or a dropdown menu to anticipate available websites. Or, a button with a popup menu in which displays available websites.

**Additional**
Here's a UI proposal I made in figma:
![dev-to-prototype](https://user-images.githubusercontent.com/39805353/74782107-ddd8a900-5270-11ea-9d08-ff910e1e9c81.png)

**Comment by citizen428** [comment]
Thanks for the issue @b3u! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Adding this to our feature backlog project board to get more visibility on it. Thanks for opening this issue.

**Comment by cmgorton** [comment]
@binyamin internally it looks like we are going to be working on generalizing the links so that there are less of them, they work across Forems, and people can decide what they want them to link too. For that reason I am going to go a head and close this issue. Thanks again for the request.
