### ISSUE TITLE
Ability to filter and sort posts by different criteria

### ISSUE THREAD

**Issue by trusktr** [forem/forem#6176]
**Is your feature request related to a problem? Please describe.**

Feature request

**Describe the solution you'd like**

For example

- filter by has image header
- filter by has video header
- sort by popularity
- sort by most recent
- sort by fastest rate of likes
- sort by highest bookmark, highest hearts, or highest unicorn
- sort by least liked
- filter by help questions
- etc

That would be nifty!

**Describe alternatives you've considered**

N/a

**Comment by xanderyzwich** [comment]
I'd also like to see a filter based on minimum read time.  There have been a lot of posts with no real material; just a link or video.

**Comment by citizen428** [comment]
Thanks for the issue @trusktr! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
