### ISSUE TITLE
Integrate Ahoy and other utilities in the @ankane tool suite

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#6215]
We have had internal discussions about adopting tools for improved analytics, split testing, etc.

For longterm success and a commitment to data portability, transparency, and "bundled software" we could ship in repeatable packages, I'd love for us to use open source solutions that solve our problems. And we definitely don't need to be building a lot of these things from scratch.

In terms of gems and gem ecosystems to build around, I'd love for us to consider making use of some of the really awesome @ankane utilities.

https://ankane.org/opensource

We already use several...

- ahoy_email
- strong_migrations

I think we could consider adopting several other utilities to solve some of our workflow/data/analysis needs.

- Ahoy (and ahoy.js) for tracking events and observing varied user behavior on platform. We could go deeper into this instead of Google Analytics and others and build complex flows around it.
- Blazer/Hypershield/Trend for business intelligence and internal querying while shielding sensitive data.

There are _a lot_ of good utilities here. I feel like we've been happy with what we've used thus far from Andrew's library and I would _love_ if we could lean in on these approaches where we can as opposed to external services.

When we use external services it's more around hypothetically interchangeable infrastructure as opposed to business logic tie-ins. This isn't exactly the state of things as of today, but it's been how things have been trending and I think it sets us up for a lot of longterm success if we can build on really good solutions within the Rails ecosystem that make use of our low-level utilities like Postgres/Elsatic/Redis as stores which can be spun up as a package for all future instances of our software.

Let me know what you think about all this.

**Comment by joshpuetz** [comment]
I think there's a strategic component to consider as DEV becomes more portable and re-usable. Bundling open source packages for workflow/data/analysis is great for other small and free adopters. For any corporate users, it'll be a no-go: they'll want to use paid external services (for support, SOX compliance, etc). As long as the packages we choose are modular/removable/optional, I think we'll be in a good spot! (I'm making a LOT of assumptions about DEV's future plans here.)

Regarding [@ankane](https://github.com/ankane): what's the longer term lookout for those projects? Are they really just all managed by a single person?!

**Comment by benhalpern** [comment]
@joshpuetz Really great points to bring up.

I don't think our use of any of this precludes us in any way from adding features that allow for external services to be plugged in in different places when needed. If anything we get to establish a pattern where we have our own interfaces and then we can send to wherever that organization keeps their data as we figure out those needs.

I think since we're trying to go more grass roots with early users, we sort of want the spin-up/fully-open-source version as the baseline.

Re: state of the gems, I'm not sure. We should get in touch. Some are _quite_ popular and we already use several, so it should be fairly propped up by the ecosystem.

**Comment by joshpuetz** [comment]
Great point on establishing pattern: I think that's key as we move forward!

I really, REALLY like the idea of DEV using open source wherever possible, *especially* for analytics and tracking!

**Comment by rhymes** [comment]
> I really, REALLY like the idea of DEV using open source wherever possible, especially for analytics and tracking!

Yep, can't wait to get rid of a certain famous analytics plugin :D

I think we threw around the name of [Matomo](https://matomo.org/why-matomo/) (formerly Piwik) in the past as an analytics solution. Though it's opensource and well known and supported and GDPR compliant it might be complicated for us to integrate a PHP app, unless we treat it as a black box as we're treating GA. They both have a cloud hosted and an on-premise solution.

**Comment by rhymes** [comment]
As we've since integrated ahoy for tracking and both Blazer and Hypershield I think we can close this
