### ISSUE TITLE
Add Svelte REPL

### ISSUE THREAD

**Issue by mzaini30** [forem/forem#6224]
Can we embed Svelte REPL to Dev posts?

Screenshot:

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/nji2jnira4qa5mjubpsp.png)

Link: <https://svelte.dev/repl/hello-world?version=3.18.2>

**Comment by citizen428** [comment]
Thanks for the issue @mzaini30! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
From a quick look, it seems like the Svelte REPL wasn't built with the intention of being embedded in other sites, so it seems a bit unlikely that we'll support that.

**Comment by benhalpern** [comment]
Maybe this could be a catalyst for getting it embeddable? Maybe someone can first make a feature request on their end with the awareness that we'd support it if it were?

**Comment by mzaini30** [comment]
> Maybe this could be a catalyst for getting it embeddable? Maybe someone can first make a feature request on their end with the awareness that we'd support it if it were?

In Svelte Docs, The Svelte REPL embedded with `iframe` tag.

Code:

```html
<iframe title="Simple component example" src="/repl/embed?example=blog-write-less-code" scrolling="no"></iframe>
```

Link: <https://svelte.dev/blog/write-less-code>

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/q2cuxy9kecibztey47ki.png)

**Comment by citizen428** [comment]
I see, thanks for adding this @mzaini30! My main concern was that there is no share button or something similar on the REPL page itself, so I was wondering if this is mainly for internal use in the Svelte docs, not for external consumers. See e.g. this issue, which sounds more like the former to me:

https://github.com/sveltejs/svelte/issues/2216

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
