### ISSUE TITLE
Termynal support

### ISSUE THREAD

**Issue by WaylonWalker** [forem/forem#6240]
I came across a package today that had some really sweet terminal animations, and found that they had written them all in **markdown** and simply imported termynal.js to get the animations.  I think they would be  a really cool feature in dev.to, but am not 100% sure how it would get implemented.  Just an idea I am throwing out.

![example](https://user-images.githubusercontent.com/13643239/26935530-7f4e1152-4c6c-11e7-9e1a-06df36d4f9c9.gif)

[ines/termynal](https://github.com/ines/termynal)

The mentioned library that implemented it is [typer](https://typer.tiangolo.com/)

The index page linked above is created with this [index.md](https://github.com/tiangolo/typer/blob/master/docs/index.md)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @WaylonWalker, do you mean to suggest this to be used for the scripts output?

**Comment by WaylonWalker** [comment]
Yes.

**Comment by maestromac** [comment]
I think powerbar (https://github.com/busyloop/powerbar) would be a great candidate for this

**Comment by WaylonWalker** [comment]
I should maybe clarify that I am suggesting for a way to include termynal support for posts.  It has the capability to animate pre - code blocks generated from markdown.

**Comment by rhymes** [comment]
Ok, then I didn't understand the feature request either :(

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
