### ISSUE TITLE
Embedded Codepen in post isn't show

### ISSUE THREAD

**Issue by mzaini30** [forem/forem#6241]
![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/6hgnmk1eevgtlb5h9w72.png)

Not only in one post. But it's happen in all posts (with Codepen embed)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @mzaini30, thanks for raising this issue, in the meantime can you provide the following info?

- which URL is that post from?
- what kind of errors does your browser log in the console?
- which browser?

thanks

**Comment by mzaini30** [comment]
> Hi @mzaini30, thanks for raising this issue, in the meantime can you provide the following info?
> 
> * which URL is that post from?
> * what kind of errors does your browser log in the console?
> * which browser?
> 
> thanks

- all posts
- err blocked by response
- via browser (device: realme c2)

**Comment by rhymes** [comment]
I tried with this https://dev.to/codypearce/pbs-logo-animation-with-css-14h4 and other [posts tagged codepen](https://dev.to/t/codepen) but I see no issues, do you have any specific extensions installed that might block the content?

**Comment by citizen428** [comment]
It also works for me. Can you please try another browser @mzaini30, so we can make sure it's not a Via Browser issue (maybe related to `X-Frame-Options` or similar)?

**Comment by nickytonline** [comment]
Just following up on this @mzaini30 as I am unable to replicate the issue as well.
