### ISSUE TITLE
Differentiate between Tags and Post's Topic

### ISSUE THREAD

**Issue by nonopolarity** [forem/forem#6284]
**Is your feature request related to a problem? Please describe.**

sometimes we really have 4 tags, but the "anonymous" used up one tag.
what about "discuss" or "question", can they not take up a tag too, because they are not a "topic" of tech. (like JavaScript or ReactJS)

If it is   Anonymous, Discuss, Interview, Career, and LeetCode, we have to discard one because it is 5 tags... but the question really is about interviews, career, and leetcode...

**Describe the solution you'd like**

if it is anonymous, (and/or) discuss, don't count them as one of the tag

**Comment by citizen428** [comment]
Thanks for the issue @jianlin! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @jianlin , I've updated the title to better reflect what's being asked.

Please keep in mind that you can always post anonymously by emailing sloan@dev.to

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
