### ISSUE TITLE
Make Tags mentioned in the user card clickable 

### ISSUE THREAD

**Issue by yashwanth2804** [forem/forem#6287]
![Screenshot from 2020-02-25 13-43-49](https://user-images.githubusercontent.com/8038593/75228518-33afd280-57d6-11ea-950f-2c754f8b8f00.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @yashwanth2804, as we think this is a valid request, we're going to keep this issue open for future opinions and implementation ideas.

**Comment by yashwanth2804** [comment]
I believe that is mentioned in his/her bio.so I thought it as invalid one so closed that.
Thank you
