### ISSUE TITLE
Include video_source_url in the API

### ISSUE THREAD

**Issue by BenjaminPrice** [forem/forem#6299]
**Is your feature request related to a problem? Please describe.**

Currently, the video_source_url field is not available for Videos in the API. 

**Describe the solution you'd like**

Add the video_source_url to either the Video API or Articles API. The Video API would be my preference to prevent the need to query two API endpoints. But, either is workable.

**Describe alternatives you've considered**

Scraping the article for the video_source_url. But, I don't want to go down that route...

**Comment by citizen428** [comment]
Thanks for the issue @BenjaminPrice! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by krzysiek1507** [comment]
I guess I should claim it since I submitted a PR already?

**Comment by citizen428** [comment]
I assigned you the issue, @krzysiek1507, thanks!
