### ISSUE TITLE
Data Update Scripts limitations

### ISSUE THREAD

**Issue by rhymes** [forem/forem#6332]
The Data Update Scripts System (DUSS :D ?) is a great addition to our code base and flow but it has three major limitations

### Present issues

1. doesn't store script versions and doesn't have the concept of last version
2. doesn't re-run failed scripts (failed schema migrations won't run following migrations, but now we do, kinda of invaliding the purpose of sequencing them)
3. the `development` startup check tells the user to run the data scripts even if there are schema migrations to be run before that which will eventually result in failed scripts and a migration still to run

Non priority issues:

4. doesn't store failure messages (this might not be needed TBH, schema migrations don't either)
5. doesn't tie data scripts to schema migrations (might not needed if we have a good versioning system and we solve item #3, also it introduces a dependency graph between migrations, so we'd be better off using tools like [Luigi](https://github.com/spotify/luigi))

NOTE: storing the "data migration" version would also be very important in the future to answer the question: "which data migration is my DB at?", even more important for possible multi tenant scenarios even though we're still far from those 👀

### Ideas explored

- hooking into `rails db:migrate` as a post hook, it might be an issue though as in `release_tasks.sh` the sequence is: schema, indexes, data migration (which makes perfect sense as data migrations might need the index to be there before). We could hook it to `search:setup` but it's still a hack. Let's keep it a separate step but smarter

- Replicate what the gem [rails-data-migrations](https://github.com/OffgridElectric/rails-data-migrations) does by using [ActiveRecord::Migrator](https://github.com/rails/rails/blob/fc895aa867beb3c39ea87e28813410d21b826c78/activerecord/lib/active_record/migration.rb#L1184) or use the gem itself directly (the main difference is that the gem always runs jobs inline, in our implementation we can both run the jobs inline or async), but I'm sure it wouldn't be hard to change or patch the gem itself. See https://github.com/OffgridElectric/rails-data-migrations/blob/4b893f9d2e5dd55e198f8edb9076697f004381ae/lib/rails_data_migrations/migrator.rb#L68-L76

This gem is also small enough to be understandable by us.

Note: `ActiveRecord::Migrator` though it's the key to all the migration machinery we're familiar with, it's not a public API per se, but not even private:

```ruby
[3] pry(main)> ActiveRecord::Migrator
=> ActiveRecord::Migrator
```

- Use a gem like [data-migrate](https://github.com/ilyakatz/data-migrate). It's a little different from `rails-data-migrations` as it has the concept of `up` and `down` also for data migrations (with `down` being optional). This gem has a bigger surface than `rails-data-migrations` and I don't like that its `db:migrate:with_data` scripts also load data migrations. At least for now we should be in full control of the release order.

Both gems support Rails 5 and 6 and both use `ActiveRecord::Migrator`.

### Ideas rejected

- change the data in migrations: error prone, doesn't work with polymorphic associations, slows down deployment. Big nope. It can also be ignored if you use `schema:load` or `db:reset` as I often do. Why it's hinted at in the Rails official guide is beyond me:

> The main purpose of Rails' migration feature is to issue commands that modify the schema using a consistent process. Migrations can also be used to add or modify data. This is useful in an existing database that can't be destroyed and recreated, such as a production database.

from <https://edgeguides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data>

- use temporary tasks: well, it's what we we're using before, not a good idea. Also being them temporary means they can be removed and a new developer or contributor might have data that's not valid in their DB if so. Also, they have no order.

- use seeds: bad idea, it also will work only in development and the first time one seeds the DB, not for new code carrying scripts for migrations

- use a gem like [migration_data](https://github.com/ka8725/migration_data): although it's a step forward from changing data directly in the migration, it hijacks Rails default migration system, it'll bind us to this gem forever and it's also run in process, I don't feel like we should queue jobs inside a migration. Also, it'll eventually be an issue when all the current migrations will have become old migrations and this gem might stop functioning. Also, migrations shouldn't contain business logic. So, nope.

#### Hook/monkey patch ActiveRecord::Migration

- `migration_data` gem approach:
  - <https://github.com/ka8725/migration_data/blob/master/lib/migration_data.rb>
  - <https://github.com/ka8725/migration_data/blob/master/lib/migration_data/active_record/migration.rb>

- using [ActiveRecord::Migrator](https://github.com/rails/rails/blob/fc895aa867beb3c39ea87e28813410d21b826c78/activerecord/lib/active_record/migration.rb#L1184)

### Resources

- [Change data in migrations like a boss](https://railsguides.net/change-data-in-migrations-like-a-boss/)
- [Data Migrations in Rails](https://thoughtbot.com/blog/data-migrations-in-rails)

## Related opened issues:

- [Data updates should be rerunnable](https://github.com/thepracticaldev/dev.to/issues/6175)
- [Running a rails command should notify about pending migration before notifying about scripts](https://github.com/thepracticaldev/dev.to/issues/6330)

**Comment by rhymes** [comment]
I'm going to explore the usage of the gem `rails-data-migrations` as a first step.

It has a small surface and I can quickly find out if we can tell it to either run scripts inline or async with our `DataUpdateWorker`. It's likely faster than re-writing it to fit in our current code :) After all scripts are just runnable Ruby files...

**Comment by mirie** [comment]
Closing as a Won't Fix
