### ISSUE TITLE
Cached article bodies + the Content Indexing API

### ISSUE THREAD

**Issue by jeffposnick** [forem/forem#6363]
**Is your feature request related to a problem? Please describe.**

dev.to has put a lot of effort into [their service worker implementation](https://dev.to/devteam/instant-webpages-and-terabytes-of-data-savings-through-the-magic-of-service-workers-1mkc), and it would be possible to take things one step further by caching a limitede number of article bodies so that their corresponding pages were accessible while offline.

If that happens, experimenting with using the [Content Indexing API](https://web.dev/content-indexing-api/) to let the browser know about offline-capable content could be a next step. 

**Describe the solution you'd like**

Adding in limited offline caching to the existing service worker for article bodies, either via a recipe along the lines of the [Offline Cookbook](https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook), or using a library like [Workbox](https://developers.google.com/web/tools/workbox/) (which, full disclosure, I maintain).

Following that, experiment with the Content Indexing API.

**Describe alternatives you've considered**

Just using the current service worker implementation without caching any article bodies.

**Additional context**

The [Content Indexing API](https://web.dev/content-indexing-api/) is an experimental web platform feature, currently undergoing an [Origin Trial](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md) in Chrome 80+.

Developers who ship offline-capable web apps can use this API to tell the local browser about URLs which will work offline, and then the browser can choose to surface those URLs, potentially with high prominence, when it detects that there's no Internet connection available.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here. We have a new process moving forward to address feature requests and especially those that have been in our repo without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
