### ISSUE TITLE
Add RSS Link Tag for AutoDiscovery

### ISSUE THREAD

**Issue by JamoCA** [forem/forem#6368]
There's no current way for RSS-aware software and services to discover that RSS feeds exist for a blog.

Could a link tag be added for [autodiscovery](http://www.rssboard.org/rss-autodiscovery) purposes?

### Example HTML Source

```
<link rel="alternate" type="application/rss+xml"
    title="I'm a ColdFusion web application developer."
   href="https://dev.to/feed/gamesover" />
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by JamoCA** [comment]
Too late... I think they already incorporated this feature without updating the status on this issue.

I checked out the source to my dev.to blog and saw the following code:
```
<link rel="alternate" type="application/rss+xml" title="DEV Community RSS Feed" href="https://dev.to/feed/gamesover" />
```
