### ISSUE TITLE
Allow Heroku Review apps

### ISSUE THREAD

**Issue by abenettt** [forem/forem#6388]
**Is your feature request related to a problem? Please describe.**
When reviewing a pull request one might want to see and test in a production like environment. Herokus Review Apps would allow one and others to do this. Of course creating review apps for every pull request would be undoubtable expensive but staff could create an environment for each pull request manually so they could control how many there are.  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://devcenter.heroku.com/articles/github-integration-review-apps

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
Hi @abenettt! Thank you for the great suggestion! 

Our team is currently in the process of figuring out an optimal deploy process as Forem continues to grow. We are exploring ideas such as canary environments and/or staging environments. At this time though, we are moving most of our infrastructure off of Heroku and to AWS which makes using Heroku's built-in review app feature a bit less appealing. The cost as you mentioned is also quite prohibitive. For these reasons, I am going to go ahead and close this issue. Please let me know if you have any further questions.

Thanks for being an awesome part of the Forem community!
