### ISSUE TITLE
Medium RSS feed articles are not pulled in if they have Giphy embeds

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#640]
### Current Behavior
When pulling articles via RSS feed and from Medium specifically, the posts with Giphy embeds are not created because they run into an error here:
https://github.com/thepracticaldev/dev.to/blob/9e35b25ac1471fad4497d3c25c974acf590de256/app/labor/rss_reader.rb#L126-L143

In line 133, `open` fails:
```ruby
# possible_link is https://medium.com/some-long-link-that-redirects-to-the-proper-place/href
open(possible_link)
#=> RunTimeError: redirection forbidden:
#=> "gph.is/short-code-url" -> "http://giphy.com/gif-link"
```

Basically, the short link redirects to regular HTTP, and that isn't allowed with `open`.

### Proposed Solutions
From easiest to hardest, we can:
1. have better link checking,
2. maybe try something else instead `open`,
3. support Giphy embeds. 

### Additional Notes
This is not a critical issue that affects many people since I don't imagine Giphy embeds are used all that much. Also, only the articles that do have Giphy embeds are affected; the RssReader will still attempt to pull in the rest of the articles.

**Comment by rhymes** [comment]
Maybe you can just switch to HTTParty, it's already part of the code:

```ruby
> response = HTTParty.get("https://gph.is/1BLAOkM", follow_redirects: true)
> response.request.last_uri.to_s
=> "https://giphy.com/gifs/avengers-spider-man-age-of-ultron-ZOq6VyKsSTSHm"
```

**Comment by rhymes** [comment]
unstale :D

**Comment by Zhao-Andy** [comment]
Still an issue.

**Comment by cmgorton** [comment]
@Zhao-Andy do you still feel like this is something we should implement? This issue seems to have gone stale but I can add it to the feature backlog project board to get more visibility on it. If not we should close this issue.

**Comment by juliannatetreault** [comment]
> @Zhao-Andy do you still feel like this is something we should implement? This issue seems to have gone stale but I can add it to the feature backlog project board to get more visibility on it. If not we should close this issue.

Bumping this @Zhao-Andy! 😄

**Comment by Zhao-Andy** [comment]
Ah thanks! Looks like the code has changed to use HTTParty. I don't think this is an issue anymore, so closing.
