### ISSUE TITLE
Support GitHub custom emoji

### ISSUE THREAD

**Issue by binyamin** [forem/forem#6408]
**Is your feature request related to a problem? Please describe.**
I have an `:octocat:` in the description of one of my pinned repos, and it doesn't show up as an image.

**Describe the solution you'd like**
Show github-specific emoji. GitHub's [gemoji](https://github.com/github/gemoji) gem seems promising.

**Describe alternatives you've considered**
Possibly, we could create DEV-specific custom emoji which may or may not overlap with GitHub's list.

**Additional context**
There's an official list of *all* github-supported emoji [here](https://api.github.com/emojis), and I found a repo which includes a list of all of GitHub's *custom* emoji [here](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md#github-custom-emoji)

**Comment by rhymes** [comment]
Hello @username, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @b3u, thanks a lot! We already use `gemoji` but I dug a little and it seems like it doesn't support GitHub's custom emojis since last year: https://github.com/github/gemoji/pull/158

It looks like indeed they are only available through the API.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
