### ISSUE TITLE
Inline images in blog posts

### ISSUE THREAD

**Issue by ljhaywar** [forem/forem#6414]
**Is your feature request related to a problem? Please describe.**

I'm unable to display images in line with texts in blog posts.

**Describe the solution you'd like**

I would like to be able to apply a css style that would display my images inline.

**Describe alternatives you've considered**

I could manually apply the styling to my images and the system would not remove them.

**Additional context**

Is there a way to make images display inline with the text in blog posts?  From what I can tell, the default styling is switching all images to display block.  When I add a style tag to my images to make them display inline, the style tag is removed.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @ljhaywar , can you provide us an example of what you are trying to get done?

**Comment by ljhaywar** [comment]
I'm trying to float an image to the right of my text like I do with the QuickStart logo image in this post:  https://www.mongodb.com/blog/post/quick-start-nodejs--mongodb--how-to-analyze-data-using-the-aggregation-framework#

I'm unable to figure out how to do so in my post on DEV:  https://dev.to/lauren_schaefer/how-to-use-one-of-the-most-powerful-pieces-of-mongodb-the-aggregation-pipeline-3db0

**Comment by yashints** [comment]
I think this is a good issue since it will be needed in many scenarios. For example I have this post of mine with inline images and can't do the same in Dev.to:

https://yashints.dev/blog/2020/03/19/debug-devtools

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
