### ISSUE TITLE
Connect shows two notifications when there aren't any

### ISSUE THREAD

**Issue by OmisNomis** [forem/forem#6472]
**Describe the bug**

When browsing dev.to, I always have two notifications for the connect chat service but there are none.

**To Reproduce**

I suspect this is because I was part of other "chat rooms" (moderators and open-source moderators), but now I am not so cannot get rid of the notifications.

**Expected behavior**

No notifications

**Screenshots**

![image](https://user-images.githubusercontent.com/14848394/75966469-5327b900-5ec2-11ea-943b-980806078090.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by sarthology** [comment]
@OmisNomis Do you still have this issue ?
