### ISSUE TITLE
API: allow retrieval of comments belonging to a podcast episode

### ISSUE THREAD

**Issue by rhymes** [forem/forem#6526]
**Is your feature request related to a problem? Please describe.**

Right now the API only returns all comments belonging to an article, but users can also leave comments on podcast episodes.

**Describe the solution you'd like**

Enable users to retrieve podcast episode's comments by adding a parameter to `/api/comments` that would indicate the user is requesting the comments of a podcast episode. Someting like `/api/comments?p_id=123`

**Describe alternatives you've considered**

`/api/podcast_episodes/{id}/comments` but it would look odd in the current v0 

**Additional context**

The controller `Api::V0::CommentsController` and its action `index` are the place to start. Need to make sure that the surrogate key is distinct from that of articles and that the episodes are correctly purged when updated.

No need to alter the `show` action as it's already possible to retrieve a single comment, even if it belongs to a podcast episode

**Comment by jkrsn98** [comment]
I'd like to try working on this issue

**Comment by rhymes** [comment]
Hi @jkrsn98, go ahead, I've assigned you the issue. Let us know if you need any help
