### ISSUE TITLE
[P1] Implement tile design & interaction in suggested tags

### ISSUE THREAD

**Issue by lisasy** [forem/forem#6543]

**Comment by ludwiczakpawel** [comment]
https://github.com/thepracticaldev/dev.to/pull/6410#issuecomment-597529824
> Per @lisasy request, I've pushed some changes to this PR to improve tags styling on "Follow tags" step. Here's a little preview: https://d.pr/v/0jeRAW
> Keep in mind I'm not react syntax expert so I'm pretty sure couple lines of my code could be easily optimized :)
