### ISSUE TITLE
Run travis ci tests on all supported database versions

### ISSUE THREAD

**Issue by abenerd** [forem/forem#6567]
**Is your feature request related to a problem? Please describe.**
As dev.to supportes several database versions and several such versions are in use, be it the default `9.6`, the production `11` or some maniac running on `12` \s, I think it would be prudent to run the tests against the versions that are officially support by DEV.

**Describe the solution you'd like**
Update the `.travis.yml` so that the tests are run against several postgres versions.

**Describe alternatives you've considered**

**Additional context**
https://docs.travis-ci.com/user/customizing-the-build/#build-matrix
https://docs.travis-ci.com/user/database-setup/#postgresql

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
> some maniac running on 12

ahha it's already supported by Heroku ;-) https://devcenter.heroku.com/changelog-items/1731

**Comment by rhymes** [comment]
Great idea by the way!

**Comment by citizen428** [comment]
Thanks for the report @abenettt! 

@rhymes In a similar vein we could potentially add building against different Ruby versions to the matrix, but allow it to fail on versions > than the current one we are using, something like

```yaml
rvm:
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
      - rvm: 2.7
      - rvm: ruby-head
```

**Comment by abenettt** [comment]
@citizen428 Can you run this against multiple ruby versions? I would have thought that the Gemfile prevents using any version that is not specified in it. But I love the idea!

**Comment by citizen428** [comment]
Our Gemfile re-uses `.ruby-version`:

```ruby
ruby File.read(File.join(File.dirname(__FILE__), ".ruby-version")).strip
```

So worst case we can always do a little-pre run `sed` action 😉

**Comment by maestromac** [comment]
Thank you for this issue but I don't think this is necessary as it will use up more CI resources than it is worth. Closing.
