### ISSUE TITLE
Allow RSS reader to take the cover image if it is provided

### ISSUE THREAD

**Issue by Cheukting** [forem/forem#6579]
**Is your feature request related to a problem? Please describe.**

I am trying to syndicate my blog post from my website to dev.to and it will be convenient if I can add the cover image URL as a property (e.g. <cover_image> or <image_url>) in the item from the RSS feed. I generate my own RSS feed for my website.

The only challenge would be since it is not a convention for RSS 2.0, it will not be useful if it is not a customized RSS feed for dev.to.

**Describe the solution you'd like**

A slight change in the RssrReader Assembler: https://github.com/thepracticaldev/dev.to/blob/909519c5d58ca7b613962112a8fee35ea162fcc2/app/services/rss_reader/assembler.rb#L2 would do, I can attempt a PR if it is something that everyone wants.

**Describe alternatives you've considered**

Of cause it can be achieved by using the API, however, I just think it's easier for beginner to have an option in the RSS feed and it is much easier to set up for people who host a static website on GitHub pages like me.

**Additional context**

**Comment by citizen428** [comment]
Thanks for the issue @Cheukting! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@Cheukting Note that in RSS2.0 you can use the `enclosure` attribute on the item level to attach images to posts, which I think would be preferable over a custom solution ([spec](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt)).

```
<enclosure> sub-element of <item>
<enclosure> is an optional sub-element of <item>.

It has three required attributes. url says where the enclosure is located, length says how big it is in bytes, and type says what its type is, a standard MIME type.

The url must be an http url.

<enclosure url="http://www.scripting.com/mp3s/weatherReportSuite.mp3" length="12216320" type="audio/mpeg" />
```
Some people are under the impression that this is only for attaching video or audiofiles, but according to the spec any standard MIME type is ok and I've definitely seen `enclosure` used for this purpose.
