### ISSUE TITLE
<Feed> Renders a frames whitout content on Android App

### ISSUE THREAD

**Issue by dcruz1990** [forem/forem#6584]
**Describe the bug**
When access the Android App, feed shows blank frames.

**To Reproduce**
Open Dev.To Android App and then the issue.

**Expected behavior**
Feed renders ok.

**Screenshots**
![Broken Dev.To Index](https://i.ibb.co/XszVCP5/Screenshot-20200309-110347.jpg)

**Smartphone (please complete the following information):**

- Device: HUAWEI Y7
- OS: Android 8
- Browser: 
- Version:

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @dcruz1990, thanks a lot for taking the time to report this!

**Comment by rhymes** [comment]
There might be clues here as well https://github.com/thepracticaldev/dev.to/issues/6559

**Comment by dcruz1990** [comment]
> Hi @dcruz1990, thanks a lot for taking the time to report this!
> 
> Does it happen systematically or sometimes? Do you notice any difference between logged in and logged out?

It happens when i log in.. when logout everything goes fine.

**Comment by maestromac** [comment]
I'm unable to reproduce this bug. Can you try clearing the app's storage and cache and let us know if this still persists @dcruz1990 ?

**Comment by dcruz1990** [comment]
@maestromac , tried it since i founded the issue and doesnt works, even reinstalling the app from the Google Play Store.

**Comment by cmgorton** [comment]
Hey @dcruz1990 I know we have had a lot of changes with the mobile experience recently. Is this still an issue for you?

**Comment by dcruz1990** [comment]
I updated recently and everything goes well!!! Going to close this now.
