### ISSUE TITLE
Fonts: Proposal to add "Lexend Deca" as an option

### ISSUE THREAD

**Issue by Some-Dood** [forem/forem#6587]
**Is your feature request related to a problem? Please describe.**
Given that DEV is a website known for its user-generated technical articles, it is paramount to ensure that font readability—or UX and accessibility in general—is of utmost importance. However, there are times when my eyes tire out from the default sans serif and serif fonts. I am a slow reader, and it is especially worsened when the font is rather difficult to read or designed in such a way that does not take eye exhaustion into consideration.

**Describe the solution you'd like**
A few months ago, a pull request (#5037) acted on a proposal to add the [OpenDyslexic font](https://opendyslexic.org/) to the list of font options in order to accommodate our fellow DEVs who suffer from dyslexia.

Similarly, I propose the addition of the [Lexend Deca font](https://www.lexend.com/). The team behind the font face has gone through two decades' worth of extensive research and experimentation to perfect the typography of Lexend as the most readable font face available. I must say that when I did try it out, I did find reading to be a bit easier than with Arial or Times New Roman, for example.

> **DISCLAIMER:** I am not affiliated with the Lexend research team. I am simply endorsing the font because it really did offer a better reading experience for me in most cases.

**Describe alternatives you've considered**
I have considered writing a Chrome extension that simply swaps out the font to Lexend, but I figured that such a minor feature shouldn't be too much of a bother to officially support.

**Additional context**
Below are a list of links about Lexend that are worth checking out:
* [Lexend web page](https://www.lexend.com/)
* [Google Fonts entry](https://fonts.google.com/specimen/Lexend+Deca)
* [Lexend GitHub repository](https://github.com/ThomasJockin/lexend)
* [The Font That Makes Everyone Read Faster - Cheddar Explains](https://www.youtube.com/watch?v=GIm8arSogvY)

Here is a screenshot that compares the current sans serif UI font and Lexend:

![UI Comparison](https://user-images.githubusercontent.com/39114273/76423893-6b2b9b00-63e2-11ea-85f8-4c22eabc1290.png)

Here is a comparison of an excerpt from [Nico Riedmann's](https://dev.to/unseenwizzard) article _["Learn git concepts, not commands"](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc#overview)_. As you can see, Lexend (bottom) appears significantly larger and more prominent than Palatino (top) despite having equal font sizes, which is good in the context of readability:

![Article Font Comparison](https://user-images.githubusercontent.com/39114273/76424786-a67a9980-63e3-11ea-8a13-688af508712d.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
I don't think we are ready and convinced to implement another font fact like this. Adding new font face to the system is always a perf issue because these are additional bytes that user must download. And the benefit of this font is relatively small compared to our current sans-serif solution.
