### ISSUE TITLE
Write a Graph in Mardown using the MermaidJS framework

### ISSUE THREAD

**Issue by Shosta** [forem/forem#659]
## Feature Request
Be able to write a graph using using mardown thanks to the [mermaidjs](https://mermaidjs.github.io)  framework.

### Description
Using the [mermaidjs](https://mermaidjs.github.io) framework I can write simple markdown that is going to be interpreted as a graph.

### Definition of Done
I can write a graph of the following types : 
- graph TD
- graph LR
- sequenceDiagram
- gantt

in my blog post and it is interpreted in the post, following the [mermaidjs](https://mermaidjs.github.io) framework.
##### A Top Down graph : 
![image](https://user-images.githubusercontent.com/1763733/45560350-218dde80-b845-11e8-8555-550b1fed694e.png)

##### A Left to Right graph :
![image](https://user-images.githubusercontent.com/1763733/45560367-2eaacd80-b845-11e8-9fa8-b57fd9abd465.png)

##### A Gantt graph :
![image](https://user-images.githubusercontent.com/1763733/45560381-38343580-b845-11e8-8f86-653a32de7749.png)

---

### Current Behavior
If I write a [mermaidjs](https://mermaidjs.github.io) compatible graph, it is displayed as code instead of being interpreted as a graph.

### Expected Behavior
If I write a [mermaidjs](https://mermaidjs.github.io) compatible graph, it is displayed as a graph as described in the [mermaidjs](https://mermaidjs.github.io) documentation.

### Mobile & Desktop Screenshots/Recordings
Here are some screenshots of graphs and the related markdown.

##### A Top Down graph : 
![image](https://user-images.githubusercontent.com/1763733/45560350-218dde80-b845-11e8-8555-550b1fed694e.png)

##### A Left to Right graph :
![image](https://user-images.githubusercontent.com/1763733/45560367-2eaacd80-b845-11e8-9fa8-b57fd9abd465.png)

##### A Gantt graph :
![image](https://user-images.githubusercontent.com/1763733/45560381-38343580-b845-11e8-8f86-653a32de7749.png)

### Additional Info (device/browser, helpful links)
You can see all the information of [mermaidjs](https://mermaidjs.github.io) on their [website](https://mermaidjs.github.io/)

There is a mermaidjs live editor available [here](https://mermaidjs.github.io/mermaid-live-editor/)

**Comment by Shosta** [comment]
I don't know if that can help, but the guys at [Boostnote](https://github.com/BoostIO/Boostnote) have this in their app (that's where I am actually using it), maybe they could give a hand to make this available on dev.to or share some peace of code.
I am sorry but I don't know how to make it on the Web.

**Comment by maestromac** [comment]
not stale

**Comment by benhalpern** [comment]
This is interesting. Sorry I totally missed this when it was originally brought up. (Though I was incredibly busy in September 2018 so I know why I missed it)

In general if we were to generate an SVG in this was I think we'd prefer to do it on the backend rather than regenerate each time on the frontend, but in some way I could see us using this either way if there is no solution for doing this on the server.

Definitely interesting!

**Comment by Shosta** [comment]
I think indeed that it would be easier to generate it on the Backend. So you would avoid Browser version that could mix up the "diagram rendering".
I don't know what is the better way to do that, but the mermaidjs documentation seems to be pretty good.

I would have thought as just adding this library and using it. But I'm sure it is much more complicated than that.
By the way I would be happy to beta test this if you need help testing it.

**Comment by benhalpern** [comment]
It looks like this is specifically designed for frontend—and written in JS. Looks like it uses D3, so it seems like it's 100% designed for the frontend. It _could_ be implemented on the backend, but not sure where things are with that.

Frontend might ultimately be more practical. We'll keep considering the options.

**Comment by Shosta** [comment]
As it should be designed for the Frontend and not the Backend, how could wwe move it to Frontend?
Should we evver consider to do it on the Frontend?

**Comment by maestromac** [comment]
All of our markdown processing happens in the backend so it makes sense for this to be part of `MarkdownParser`. 

Seeing that there's an [octopress integration](http://mostlyblather.com/blog/2015/05/23/mermaid-jekyll-octopress/), this can be implemented through liquid tag and should be used in the following manner.

```
---
title: Mermaid article
publish: true
...
---

{% mermaid %}
graph TD;
    A\-\->B;
    A\-\->C;
    B\-\->D;
    C\-\->D;
{% endmermaid %}
```
```

What do you think @Shosta  ?

**Comment by Shosta** [comment]
Yes, that is perfect indeed.

**Comment by jcandan** [comment]
I've used mermaid over at [StackEdit](https://stackedit.io/). I love it, and would love it to be available on dev.to.

**Comment by msarit** [comment]
@cmgorton Hi Christina! 👋🏾 

I'm recommending this issue for closure because it is relevant to a very small subset of dev.to users. If a future forem needed this capability, they would request it as a feature then.

**Comment by jcandan** [comment]
That's disappointing. Considering this is a dev community, and graphing can be a great way to communicate ideas quickly. We're not designers, so having access to a markdown-ready graphing library would be useful. Hope the team reconsiders.

**Comment by bcouetil** [comment]
Diagramming as code would be so useful and time saving, would you reconsider it now ?

**Comment by didacrios** [comment]
Hi, Interested here in this PR could we reopen?

An easy approach is to render using javascript, the docs are pretty good

Ive just installed in my bloc with a few lines of code:

```js
  <script src="https://unpkg.com/mermaid@11.4.0/dist/mermaid.min.js"></script>
  <script>
   // on document load
    document.addEventListener('DOMContentLoaded', () => {
      mermaid.initialize({
        securityLevel: 'loose',
        startOnLoad:true,
        theme: "neutral",
        look: "handDrawn",
      });
      window.mermaid.init(undefined, document.querySelectorAll('.language-mermaid'));

    });
  </script>

``
