### ISSUE TITLE
Improving statistics and reducing ghosts

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#6608]
### **Is your feature request related to a problem? Please describe.**

I've got a lot of followers, but when I post a new article, I get little interaction and few views. This is really too bad and I'm not the only one who might be frustrated... 

### **Describe the solution you'd like**

I would like two things : 

* **A upgrade of Dashboard**
	* Add a graph for statistics 
	* Triage by weeks/months 
	* Graph with colors for distinct **news followers**, **unsubscribings** and **inactives accounts**.

* **Implement a system for clear inactives followers** :
	* It would be displayed in the graph with a distinct color to see that they were inactive lost accounts.

### **Describe alternatives you've considered**

No alternatives for me, if you have a idea in concert with mine, **share it** ! 👋

### **Additional context**

I did a post to get some stats. I didn't get much feedback, but I'm happy to read it.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Kedar-K** [comment]
I guess number of profile visits along with the graph will also be an amazing feature. Just like Twitter analytics

![Twitter Analytics account overview for KodgireKedar](https://user-images.githubusercontent.com/25702901/78037347-0cc25e80-7389-11ea-9f75-4155263ac1d2.png)

**Comment by jessleenyc** [comment]
Hey @thomasbnt, we're planning on releasing some additional analytics soon. Not everything you mentioned is covered there but I'd wait on jumping on this issue until the new features are in, so we can build on that solution.

**Comment by thomasbnt** [comment]
Ooooh thank you @jessleenyc for this new ! Can't wait :+1:

**Comment by icncsx** [comment]
@jessleenyc Very excited for this feature. PS: I'd love to help on anything D3.js related :)

**Comment by thomasbnt** [comment]
Thanks @cmgorton ! 😃

**Comment by icncsx** [comment]
Fantastic, team!
