### ISSUE TITLE
Error when submitting a comment on a recently deleted post

### ISSUE THREAD

**Issue by adamkdean** [forem/forem#6610]
**Describe the bug**

Followed a link from an email, attempted to respond to a comment, received error `There was an error in your markdown: undefined method `id' for nil:NilClass`, comment not posted.

**To Reproduce**

Follow link from an email, attempt to respond to a comment.

**Expected behavior**

Comment is posted.

**Screenshots**

![image](https://user-images.githubusercontent.com/1639527/76545609-0162ce00-6482-11ea-9232-a7c318c642e0.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.3
- Browser: Chrome  80.0.3987.87

**Comment by adamkdean** [comment]
Looks like the author deleted his post. Perhaps the solution here is better messaging to explain that the post/comment thread no longer exists.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @adamkdean, thanks for the issue! I edited the title to add context :)

**Comment by saroj990** [comment]
Hi @cmgorton, I would like work on this issue.

**Comment by rhymes** [comment]
@saroj990 I've assigned this to you, thank you 🙌

**Comment by cmgorton** [comment]
Thanks @saroj990 . If you have any questions feel free to ask here or in your PR once opened. We are here to help along the way.

**Comment by saroj990** [comment]
What message do we need to display in the alert box for this issue ?

**Comment by cmgorton** [comment]
Good question. You could add some text for now that indicates the author deleted their comment. Once you have a PR in your reviewers may suggest something else. They will be able to respond more quickly in the PR itself with suggestions 😄

**Comment by saroj990** [comment]
@cmgorton created a [PR](https://github.com/forem/forem/pull/13721) for this issue.

**Comment by cmgorton** [comment]
Hey @saroj990  wanted to check in and see how you are doing with this issue. Did you have any questions or need any help? How are things going with your PR?

**Comment by saroj990** [comment]
Updated the PR with the required changes.
