### ISSUE TITLE
Is it possible to see from which post another user started to follow me?

### ISSUE THREAD

**Issue by nonopolarity** [forem/forem#6612]
I see other users starting to follow me, and wonder if they read one of my posts and started to follow me?  I just wonder which post it is.  Is it possible to find out or show us this information?  "While reading your posts about [ ... some topic ], the user followed you on dev.to"

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Hi @jianlin, thanks for the issue. From what I can tell this is not currently possible. Also keep in mind that users can follow you for other reasons than reading your posts, e.g. follow suggestions during onboarding.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
