### ISSUE TITLE
Follow button text not refreshing or invisible

### ISSUE THREAD

**Issue by roblack** [forem/forem#6616]
**Describe the bug**
Opening a user profile page while not being logged/registered follow button text is not visible. And even though it seems to be clickable, there is are no link on the button. After registering text seems to appear, but then randomly disappears and in that case it tends to be invisible, only to show up on a mouseover.

Not sure what exactly it is causing it but happened 2-3 times in few page loads.

It also activates once "block scripts" is active, so that might be what is affecting it, but sometimes it fails to load them even after script blocking is disabled.

**To Reproduce**
Open a user profile page being logged out and cache cleared out. -> Incognito.

**Expected behavior**
Text being visible all the time

**Screenshots**
![image](https://user-images.githubusercontent.com/21968377/76561367-75fa3480-64a3-11ea-8a64-b9c176e29300.png)

**Desktop (please complete the following information):**

- OS: macOSCatalina 10.15.3
- Browser: Brave 
- Version: 1.4.96

**Additional context**
I saw this bug was posted few times before but the issue persists. On the screenshot i have activated scripts block but again, it tends to happen even with the option disabled.

**Comment by citizen428** [comment]
Thanks for the issue @roblack.

>  Open a user profile page being logged out and cache cleared out. -> Incognito.

I did this with several users now, it worked in all cases (Firefox Developer Edition 75.0b2, Catalina 10.15.2). Same with he Chromium-based Microsoft Edge Beta for macOS. Could this be related to your Brave settings?

**Comment by claracodes** [comment]
I also saw this issue happening on the notifications page, see screenshots attached. There is no text on the button.
MacOs, Firefox

<img width="785" alt="Screenshot 2020-03-23 at 13 38 59" src="https://user-images.githubusercontent.com/29435293/77361161-08080580-6d0c-11ea-8795-1ae4e19da537.png">

<img width="368" alt="Screenshot 2020-03-23 at 13 40 06" src="https://user-images.githubusercontent.com/29435293/77361158-050d1500-6d0c-11ea-887c-7d5e5dab75ae.png">

**Comment by maestromac** [comment]
Are you still running into this problem @roblack ? I can't seem to reproduce this on Brave.
