### ISSUE TITLE
Add functionality for users to clear their reading list

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#6632]
**Is your feature request related to a problem? Please describe.**

Occasionally, users want to clear out their [reading lists](https://dev.to/readinglist), to start fresh.

**Describe the solution you'd like**

I think it'd be quite nice if we treated reading lists like an inbox. Perhaps we could have boxes beside each item in the list that folks could check, and then they could act to archive or remove posts in bulk.

As some folks will have particularly full inboxes and the desire to clear out everything might be strong. We should also add a "check all" function, so that they can move en masse. 

**Additional context**

I also could see folks accidentally removing something, so we likely want to add another check here, e.g. a pop window that says "Are you sure you'd like to proceed with removing the selected post(s) from your inbox?"

**Comment by rhymes** [comment]
A possible alternative would be to have an `archive all` button that moves all the inboxed reading list tems on to the archive section

**Comment by michael-tharrington** [comment]
Good alternative idea there. 🙂

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
