### ISSUE TITLE
Improvement of Reading List UI/UX: move the search bar in the right column

### ISSUE THREAD

**Issue by Olyno** [forem/forem#6647]
**Is your feature request related to a problem? Please describe.**

Currently the search bar of the Reading List is in the sidebar. So when we have a look into Reading List and we want to search one specific article that we saved, we don't find easily the search bar, or we don't understand that the search bar inside the sidebar is for the Reading List

**Describe the solution you'd like**

Move the search bar in the Reading List part. Maybe at the right of the title?

**Describe alternatives you've considered**

/

**Additional context**

/

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Design of this page has changed significantly so I'm closing this issue as it's a bit outdate. But at the same time, we move the search from to other place so I guess it's also "done" :)
