### ISSUE TITLE
Draft showing an older version in the editor

### ISSUE THREAD

**Issue by dzhavat** [forem/forem#6692]
**Describe the bug**
I have a draft article right now that I want to publish but can't because when I open it, I see it in its current form for a second then the editor jumps and shows me an older version of it. This has happened to me before but this is the first time I'm reporting it. 

I think it might be related to caching. I tried opening the draft in a new window and reloading the page with a hard refresh but the problem is still there.

I must say that at some point this problem **fixes itself** but it's annoying to have to wait for a random point in time to be able to publish an article.

**To Reproduce**
Don't know how to reproduce. What I did in this particular case is saved a draft last night hoping to publish it in the morning (now) just to come back to this issue.

**Expected behavior**

**Screenshots**

![demo](https://user-images.githubusercontent.com/1096332/76932621-a438a380-68eb-11ea-82f3-9387692b7191.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: latest

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by krishnadevz** [comment]
Temporary help Use firefox instead of chrome✔ btw i never faced this issue in firefox that's why suggesting otherwise maintainers will you with this thing .

**Comment by dzhavat** [comment]
@krishnadevz Thanks for your suggestion. I'm actually using Firefox :)

**Comment by krishnadevz** [comment]
> 
> 
> @krishnadevz Thanks for your suggestion. I'm actually using Firefox :)
i also tried same thing for draft but i am not getting that problem i am suggesting following solutions/tricks

- clear cache of your browser
- or reinstall the browser then i think this problem will fix .it is like malfunctioning of website
**Give it a try then let me know**

i think that problem is  glitch kind of thing

**Comment by krishnadevz** [comment]
> 
> 
> @krishnadevz Thanks for your suggestion. I'm actually using Firefox :)
i also tried same thing for draft but i am not getting that problem i am suggesting following solutions/tricks

- clear cache of your browser
- or reinstall the browser then i think this problem will fix .it is like malfunctioning of website
**Give it a try then let me know**

i think that problem is  glitch kind of thing

**Comment by dzhavat** [comment]
@krishnadevz Thanks for your help and tips. I think reinstalling the browser is probably a bit too far. Reinstalling the browser because a website has some problems is probably not where the root cause is. I also tried clearing the browser cache (at that point in time) but the problem was still there.

On the bright side, opening the same draft from a different computer shows the latest draft version so I think it's the website's cache that is sometimes causing the issue.

**Comment by rhymes** [comment]
Thanks a lot for all the details @dzhavat, it might be related to this bug https://github.com/thepracticaldev/dev.to/issues/4409

I'm going to keep this open as we haven't yet determined if they are the same bug indeed

**Comment by maestromac** [comment]
from @michael-tharrington 

> **Describe the bug**
> 
> A DEV user ([Rich](https://dev.to/ellisium)) wrote in to let us know that their unpublished [draft post](https://dev.to/ellisium/oh-look-it-s-the-orm-good-bad-thread-again-14jn-temp-slug-6674265?preview=3bae497ea15134d922ea1473db460bd7f5bec9085c2a3e3e818bb84a1c0ee6319ad6ef0daab4d1959dda50ece15b93e53252f4bda3b100f049342b4c) keeps reverting to an older version without any of their latest revisions.
> 
> The draft view is correct, but when they click to edit, they don't see their most recent edits.
> 
> Editing on another device (their iPad) works as expected (edits are consistent for their draft and the editing page).
> 
> **Expected behavior**
> 
> The content on the draft page and in the edit view should be the same regardless of what device they're using.
> 
> **Additional context**
> 
> This DEV user said it was fine if I included their information in this issue.
> 
> While they mentioned that editing on another device works as expected, they said they didn't think that they switched devices during the editing process.

**Comment by lancelote** [comment]
Got beaten by it as well and lost a good chunk of the work, unfortunately. Chrome showed the latest draft state, while Firefox 75 - some old one. Clicking "New Changes (clear)" link near the "PUBLISH" button restored the desired state.

Clearing the browser data initially didn't do much surprisingly.

<img width="534" alt="Screen Shot 2020-04-13 at 17 58 06" src="https://user-images.githubusercontent.com/2500320/79131394-37f97480-7db1-11ea-8857-f25207c91e99.png">

**Comment by cmgorton** [comment]
Given that there have been a lot of changes to the editor recently and we also now have a revert button in the editor I am going to close this issue. We can open it back up if anyone still experiences this issue!
