### ISSUE TITLE
The feed does not appear when visited the homepage.

### ISSUE THREAD

**Issue by anilsansak** [forem/forem#6744]
**Describe the bug**

When the homepage is visited, the feed does not appear. Other elements of the homepage are visible and interactable but the feed is not.

**To Reproduce**

Go to [dev.to](https://dev.to/)

**Expected behavior**

The feed should be visible and interactable.

**Screenshots**

<img width="1440" alt="Screen Shot 2020-03-18 at 11 25 58" src="https://user-images.githubusercontent.com/9121446/77143635-d5080c80-6a94-11ea-90ba-eb66f199aaad.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Google Chrome 80.0.3987.132
- Version:  macOS 10.15.3 - Google Chrome 80.0.3987.132 (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

I have encountered this issue many times throughout the last two months. It does not happen every time that I visited the homepage. 

I did not have a chance to test it without browser extensions. So, here is a list of the browser extensions I am using:
* uBlock Origin 1.24.4
* Grammarly 14.953.0
* Bitwarden 1.43.3

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by AlbertoMontalesi** [comment]
To add on to this issue (which i also get) this is the console. I am on the same MacOS and chrome version of @anilsansak anilsansak 
![image](https://user-images.githubusercontent.com/23130353/77163569-ee36aa80-6ae0-11ea-952e-7fd67a02042f.png)

**Comment by rhymes** [comment]
Adding a note here that this might be related to https://github.com/thepracticaldev/dev.to/issues/6584 as well

**Comment by rhymes** [comment]
@anilsansak @AlbertoMontalesi do you have any extensions installed? I tried with Chrome `Version 80.0.3987.149 (Official Build) (64-bit)` on macOS but I don't experience the issue:

![Screenshot 2020-03-20 at 1 46 51 PM](https://user-images.githubusercontent.com/146201/77164813-52417a80-6ab1-11ea-88db-c8ec4ad8de6a.png)

I tried both logged in and logged out.

I do not have anything installed on Chrome as it's not my primary browser, I only use it for testing features.

That's why I was thinking about extensions. 

Let us know, thanks!

**Comment by aviskarkc10** [comment]
@rhymes I am using Chrome on Ubuntu. And I also have this issue sometimes. It's hard to reproduce and it works fine after I refresh the page. I don't have more information on this but will look at the console for errors next time I encounter the issue.

**Comment by helderburato** [comment]
I also have this issue sometimes, I'll try to reproduce, I'm using adblock, maybe it causes some side effect.

**Comment by anilsansak** [comment]
@rhymes Copying from the issue:
 > uBlock Origin 1.24.4
Grammarly 14.953.0
Bitwarden 1.43.3

**Comment by helderburato** [comment]
> @rhymes Copying from the issue:
> 
> > uBlock Origin 1.24.4
> > Grammarly 14.953.0
> > Bitwarden 1.43.3
> 
> The difficult part is that it does not happen every time. So, it makes it really hard to reproduce the issue :(

I'll try without Grammarly, it's on my browser too.

**Comment by AlbertoMontalesi** [comment]
I'm also using grammarly and uBlock.

**Comment by cmgorton** [comment]
I think this should be fixed with the removal of the service workers we recently had done. I am going to close this issue for now but if anyone still experiences this please let me know and we can reopen this issue! Thanks.
