### ISSUE TITLE
Fix the height of new post text area and add scroll

### ISSUE THREAD

**Issue by aviskarkc10** [forem/forem#6752]
**Is your feature request related to a problem? Please describe.**
When I am writing a long post, there is a scroll bar on the entire page, and the `textarea` to write the post increases in height as I type. But at a certain point, I need to keep scrolling for the text I type to be visible.

**Describe the solution you'd like**
Maybe removing the main scroll bar, and fixing the height of the `textarea` and adding a scroll bar there instead would help.

**Describe alternatives you've considered**
Haven't done this.

**Additional context**

![scrolling_issue](https://user-images.githubusercontent.com/13309631/77215718-d5101700-6b3d-11ea-98f4-5bf938b96072.gif)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @aviskarkc10, I labeled this as a feature request since it doesn't seem to be an actual bug, more like one of two possible behavioral choices.

I might be wrong but you can either have the current behavior or an internal scroll. None of the two seems incorrect.

Let me know what you think and thanks for filing this ticket!

**Comment by aviskarkc10** [comment]
I am sorry if my gif was unclear but with the current behavior what happens is, at a certain point the text I am typing isn't visible at and I have scroll manually.

But if we added a scroll to the `textarea`, the scrolling would be taken care of automatically just like how these GitHub comments are behaving. Please let me know if my explanation or gif is unclear.

**Comment by rhymes** [comment]
Hi @aviskarkc10, I recorded a gif as well, let me know if that's what you mean:

![text](https://user-images.githubusercontent.com/146201/77224865-f2f37100-6b69-11ea-897c-c4963417a392.gif)

As you see when I scroll the page the editor scrolls as well so I can see the text that's "hidden".

**Comment by aviskarkc10** [comment]
Yeah you can see the "hidden" text if you use the main scroll bar. But it would be helpful if the text wouldn't be hidden **while you are typing the post**.

As you type you cannot see on the screen what you are typing.

Let me know if that makes it clearer? The exact example of what I am talking is can be seen if you type a long message on the GitHub comment itself.

**Comment by rhymes** [comment]
I understood, I'm going to turn this into a bug :) Thanks for clarifying!

**Comment by aviskarkc10** [comment]
Can I grab this as well?

**Comment by rhymes** [comment]
Sure! Thanks :)

**Comment by aviskarkc10** [comment]
Just so we are on the same page, I am gonna be giving the `textarea` a static height like `100vh` and then add scroll to it

**Comment by aviskarkc10** [comment]
@rhymes I finally got around working on this issue. But every time I sign into the application thru GitHub, I get this error. Can you help me with this?
![image](https://user-images.githubusercontent.com/13309631/79758666-680abf80-833d-11ea-8d4f-fa65ed13e1a1.png)

**Comment by rhymes** [comment]
It looks like a problem with image magick, what version do you have? on which operating system? can you upgrade it? I found some hints in https://stackoverflow.com/questions/10810356/carrierwave-error-msg-failed-to-manipulate-with-minimagick-maybe-it-is-not-an

Is that temporary image an actual image? You can check with `identify PATH OF THE IMAGE`

**Comment by aviskarkc10** [comment]
I am using `v7.0.10-7` on Ubuntu 19.04.

When I run `identify PATH OF THE IMAGE`. I get an error:

```
unable to open image '/tmp/mini_magick20200420-6505-1qt66wg.jpeg': No such file or directory @ error/blob.c/OpenBlob/3496.
identify: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/562.
```

So I guess the error is because I don't have that particular file?

Not sure if it is something to do with my `ImageMagick` installation

**Comment by rhymes** [comment]
Mmm it's odd indeed. It seems like it's not saving the profile image on disk. Let me look into it.

**Comment by maestromac** [comment]
Hello @aviskarkc10 , how did you install your ImageMagick? And can you try `identify` on an image on your disk that isn't in a tmp folder?

**Comment by aviskarkc10** [comment]
I will add more details tomorrow 👍

**Comment by aviskarkc10** [comment]
@maestromac i get the same error when I try it on a valid image.

I installed imagemagick thru this:
https://www.tecmint.com/install-imagemagick-on-debian-ubuntu/

**Comment by ludwiczakpawel** [comment]
Fixed.
