### ISSUE TITLE
Reading list API of an authenticated user

### ISSUE THREAD

**Issue by srebalaji** [forem/forem#6755]
**Is your feature request related to a problem? Please describe.**
Dev API doesn't have the option to list the authenticated user's reading list 

**Describe the solution you'd like**
Build an API to list user's reading list

**Comment by srebalaji** [comment]
@benhalpern What do you think? If the Dev team approves, I can start working on it.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Bhacaz** [comment]
@rhymes I would like to work on this.

**Comment by rhymes** [comment]
Cool, I've assigned this to you! Make sure the API spec documentation is also updated if you can, thank you!

**Comment by cmgorton** [comment]
Looks like this feature was added per PR #10540. I am going to close this issue. If this feature is still lacking let me know and we can discuss opening it back up. Thanks.
