### ISSUE TITLE
Show posts' difficulty level in dashboard overview

### ISSUE THREAD

**Issue by jhermann** [forem/forem#6759]
**Is your feature request related to a problem? Please describe.**

Adding a level to posts that have none, or fixing skewed levels, gets easier if you see them all at once.

**Describe the solution you'd like**

Add a display of the level to the rounded info box after the "Manage" button.
Possibly also using color (green, orange, red) to indicate level grouping, or a star level: 0, ½, 1, …, 4½, 5.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Suggest coming up with a mockup of how this should look before delving into the code :)

**Comment by cmgorton** [comment]
Hey @jhermann.  Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
