### ISSUE TITLE
‘Rich’ editor eats up liquid tags

### ISSUE THREAD

**Issue by jhermann** [forem/forem#6765]
**Describe the bug**

Liquid tags like this…

    {% github tox-dev/tox-venv no-readme %}

disappear on repeated edit using the rich editor.

**To Reproduce**

1. Add a tag like above, and save. Tag is rendered in post.
1. Open editor again. Tag is gone, including surrounding whitespace. 
1. Save, and it is gone from the rendered post, too.

**Expected behavior**

Don't gobble up my markup. :grimacing:

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
hi @jhermann, can you provide the markdown in a https://gist.github.com/ ?

I can't reproduce this. I tried:

**preview**

![Screenshot_2020-03-22 New Post - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/77252873-0e887580-6c57-11ea-8bd5-a1b8f7579e29.png)

**saved draft**

![Screenshot_2020-03-22 test github tag](https://user-images.githubusercontent.com/146201/77252879-1811dd80-6c57-11ea-9b20-fa7998ae901f.png)

**opened the editor again**

![Screenshot_2020-03-22 test github tag(1)](https://user-images.githubusercontent.com/146201/77252890-28c25380-6c57-11ea-8838-acfcf2e7524a.png)

**hit publish**

![Screenshot_2020-03-22 test github tag - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/77252896-3081f800-6c57-11ea-8f32-f7e0c65dc560.png)
