### ISSUE TITLE
Self-documenting preview shortcut

### ISSUE THREAD

**Issue by abitrolly** [forem/forem#6775]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I forget shortcuts. The information about keyboard shortcut for toggling preview on and off is hard to find. I could only find it by going to my profile, scrolling to the bottom to find About box and following to GitHub to search issues which then led to this PR https://github.com/thepracticaldev/dev.to/pull/3308 that adds `Ctrl+Shift+P`. Unfortunately, this shortcut is bound in Firefox to open a private browsing window.

**Describe the solution you'd like**

1. Use `Alt+p`.
2. Annotate Preview `<button>` with comment listing the shortcut.
3. Maybe make a popup listing the shortcut for the button.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @abitrolly, thanks for this feature request!

While reading it I thought about what happens here in github if one types `?` while browsing the app. I'm not sure about using `Alt+P` as it's the browser's printing shorcut too, but maybe it's okay if it's only active during editing after all.

**Comment by abitrolly** [comment]
It Firefox printing is `Ctrl+p`.

**Comment by rhymes** [comment]
> It Firefox printing is `Ctrl+p`.

Oh yeah, sorry! `Ctrl-P` on windows and `Meta-P` on macOS. I was mistaken :)

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around the feature! 🙏
