### ISSUE TITLE
More than one doctype on a page

### ISSUE THREAD

**Issue by pavelloz** [forem/forem#6831]
**To Reproduce**

1. Go to `https://dev.to/platformos/optimizing-font-files-for-modern-web-3jm8`
2. Open source
3. Look at first lines - it has doctype etc. - all good
4. Use find feature in your browser to find "DOCTYPE"
5. There will be another doctype, another html tag around line 218.

**Expected behavior**

Only one doctype and html tag should be on a particular webpage.

**Screenshots**

<img width="653" alt="image" src="https://user-images.githubusercontent.com/546845/77541113-7f709d00-6ea4-11ea-8b5a-4414cb148239.png">

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by corentinbettiol** [comment]
Actually I saw a triple doctype on the linked example:

![image](https://user-images.githubusercontent.com/45763865/89875738-f1305580-dbbd-11ea-93fd-250f82695373.png)

![image](https://user-images.githubusercontent.com/45763865/89875783-fe4d4480-dbbd-11ea-9417-8a50e38acc40.png)

![image](https://user-images.githubusercontent.com/45763865/89875820-086f4300-dbbe-11ea-90bf-bee89720a7a8.png)


The second one only occurs when I am connected.

**Comment by pavelloz** [comment]
`HTML 4.0 Transitional` - long time no see old bud :-)

**Comment by pavelloz** [comment]
I guess dev.to tries to make new standard: triple doctype - let me know what W3C says about that idea ;)

**Comment by cmgorton** [comment]
Hey @pavelloz this issue has been address in other issues and is also currently being addressed internally with a current accessibility audit we have in progress from an outside source. For that reason I closed this particular issue. Thanks for taking the time to bring this up. We appreciate it.
