### ISSUE TITLE
Rename mod_roundrobin_notifications + email_follower_notifications on user model

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#6892]
We have columns on our `users` table that are boolean values that we use to represent whether a user is subscribed to an email or a notification. However, these columns [don't have intuitive names](https://github.com/thepracticaldev/dev.to/pull/6852#discussion_r398669840). For example, `mod_roundrobin_notifications`, `email_follower_notifications`, and `welcome_notifications` indicate an ActiveRecord relation, not a boolean `true`/`false` value.

We should _carefully_ rename these columns to something that actually indicates the fact that these are boolean values. So, instead of `user.welcome_notifications`, the attribute could instead be: `user.subscribed_to_welcome_notifications`. 

Notably, in order to do this carefully, we'll want to:
1) add new columns with the correct names
2) update the new columns with the correct data
3) ensure that we replace the old column/attributes the new column/attributes in the correct places in the code base
4) finally then remove the old columns

**Comment by vaidehijoshi** [comment]
@thepracticaldev/delightful can take care of this task once welcome notifications are live!

**Comment by rhymes** [comment]
Adding some additional info from the `strong-migrations` gem: https://github.com/ankane/strong_migrations#renaming-or-changing-the-type-of-a-column which might become useful when this plan is set in motion!

**Comment by citizen428** [comment]
As a sort of middle ground, all boolean columns also generate predicate methods. So as a less "dangerous" alternative we could switch relevant call sites from e.g. `user.email_follower_notifications` to `user.email_follower_notifications?`

**Comment by vaidehijoshi** [comment]
Update on this: we renamed the `welcome_notifications` attribute on the `User` model by aliasing the attribute and updating its usages elsewhere (see https://github.com/forem/forem/pull/6991 for how we did this). 

We need to do the same thing with `mod_roundrobin_notifications` and `email_follower_notifications` to ensure consistency in how we name these attributes! You can refer to https://github.com/forem/forem/pull/6991 to see how we tackled this.

**Comment by matisnape** [comment]
@vaidehijoshi I see in schema that there are more boolean columns for notification subscriptions - shouldn't they all be changed?

**Comment by citizen428** [comment]
@matisnape 

> Plus I noticed that Rubocop reports some issues to be fixed - most of them about using instance_of? instead of class name comparison.

These were introduced via a recent Rubocop update, there's already a draft PR up for it by @rhymes: https://github.com/forem/forem/pull/10808
