### ISSUE TITLE
Cannot delete cover image of post

### ISSUE THREAD

**Issue by ysfaran** [forem/forem#6914]
**Describe the bug**

I'm not able to delete the cover image of my unpublished post.

**To Reproduce**

1. Create a new post by clicking "Write a post"
1. Type title
1. Click image icon
1. Select cover image
1. Click "SAVE DRAFT"
1. Click "EDIT"
1. Click image icon
1. Click "Remove Cover Image"
1. Click "SAVE DRAFT"
1. Cover image still present

**Expected behavior**

There should be no cover image anymore.

**Screenshots**

![dev-to-cover-image-bug](https://user-images.githubusercontent.com/13695230/77774311-21ca8500-704b-11ea-9368-7f2dbe8a2181.gif)

**Desktop:**

- OS: Windows
- Browser: Google Chrome
- Version: 80.0.3987.149 (64-bit)

**Smartphone :**

- Not tested

**Additional context**

Should be fixed by #5687, but for me it didn't

**Comment by vaidehijoshi** [comment]
Hi, @ysfaran! Thanks for bringing this to our attention. It looks like you're on the newer version of the editor. If you have a chance, can you let me know if this same bug happens on the markdown editor (hopefully it shouldn't!). 

I suspect that this is just happening on the newer version of the editor, but just want to check before investigating it further :)

**Comment by ysfaran** [comment]
Hey @vaidehijoshi, could you tell me how to access the old editor. That's my first post on dev.to so I really just now the new one 😕

**Comment by vaidehijoshi** [comment]
@ysfaran Of course (and welcome to DEV!). If you go to the UX option in your [settings tab](https://dev.to/settings/ux), you'll see a "Writing" section. The basic markdown editor is the one that I have selected, like the image shown here:
<img width="557" alt="Screen Shot 2020-03-27 at 9 11 28 AM" src="https://user-images.githubusercontent.com/6921610/77776272-f7f16e00-700a-11ea-99e3-13b1899e40d0.png">

**Comment by ysfaran** [comment]
@vaidehijoshi it doesn't seem to work 😟 I could also not see any effect after changing the editor?

![dev-to-cover-image-bug2](https://user-images.githubusercontent.com/13695230/77776693-b387c180-704e-11ea-8a0a-a201054cb266.gif)

**Comment by vaidehijoshi** [comment]
@ysfaran Ah, I'm sorry, I should have clarified: can you try making a new post and see if you're hitting the same bug once you've switched editors? The previous post is already associated with the rich markdown editor, so there actually shouldn't be any effect after changing which editor you're using.

**Comment by ysfaran** [comment]
@vaidehijoshi unfortunatly it's still not working. Am I still doing something wrong here?

![dev-to-cover-image-bug3](https://user-images.githubusercontent.com/13695230/77777659-29405d00-7050-11ea-9e2b-2b68b9831ae4.gif)

**Comment by vaidehijoshi** [comment]
@ysfaran Hm, this is helpful. Looks like it is occurring on both editors 😞 Our team can investigate this further. Thanks for reproducing it for us!

**Comment by LukasPolak** [comment]
same here

**Comment by jcohen-hdb** [comment]
+1 to this issue. I delete my old post and posted a new one without a cover photo.

**Comment by madhead** [comment]
One more vote for this issue is here. Doesn't work on new editor. Switching to old one seems to change nothing. Had to re-create the post.

**Comment by jeremyBanks** [comment]
Ditto.

**Comment by vaidehijoshi** [comment]
I think I finally have some bandwidth to investigate this bug, so I'll spend some time this week trying to dig into it! :)

**Comment by vaidehijoshi** [comment]
Wanted to circle back here and provide an update: I dug into this a bit a few weeks ago during our "cool down" period, and am fairly certain the issue is happening on the JS/preact side. However, it's really hard to debug exactly what the issue is without proper devtools.

I believe that @nickytonline is working on modifying the webpack config to automatically load `preact/debug`, so that the devtools should Just Work™️  in development. I think this will be easier to investigate and fix once that is completed! But for now, I had to put it aside.

**Comment by rhymes** [comment]
@vaidehijoshi are you still working on this?

**Comment by vaidehijoshi** [comment]
> @vaidehijoshi are you still working on this? 

Nope! Feel free to close or unassign me

**Comment by cmgorton** [comment]
I believe this issue has been fixed. If you still experience this problem please let me know and we can reopen the issue. Thanks!
