### ISSUE TITLE
bottom bar does not appear when editing a post

### ISSUE THREAD

**Issue by caleb15** [forem/forem#6925]
**Describe the bug**

The buttons on the bottom bar when editing a article do not appear.

**To Reproduce**

1. Edit a post or write a new post
2. Try clicking save
3. Realize the entire bottom bar is gone

**Expected behavior**

The bottom bar to be present.

**Screenshots**

https://i.imgur.com/R3Hxyvb.png

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Chrome
- Version: Version 80.0.3987.149 (Official Build) (64-bit) ~ latest version

**Additional context**

What's interesting is that the bottom bar is still there but the buttons have css visibility hidden for some reason. Also I'm not surehow to reproduce the problem - I had it happen once for two different accounts, but after that it stopped happening.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @caleb15, are you using any extensions? Do any errors appear in the console panel of the developer tools?

**Comment by caleb15** [comment]
See https://github.com/thepracticaldev/dev.to/issues/6927#issuecomment-605745957 for extensions used. I should've checked the console at the time of the error, sorry. I tried to edit again but didn't get the error.

**Comment by cmgorton** [comment]
Hey @caleb15  I am working on cleaning up issues. We haven't had any more reports about this issue but I wanted to see if this is something you have encountered again before closing it. Let me know if this is something you have run in to again. Thanks.
