### ISSUE TITLE
Accept "slug" in the front matter for titles not in the Latin alphabet

### ISSUE THREAD

**Issue by dmikurube** [forem/forem#6942]
**Is your feature request related to a problem? Please describe.**

There are not only English articles in dev.to, but also Chinese, Japaese, and else. Their titles are not in English, too, but their URL slugs cannot be generated appropriately from non-English characters.

The following article is a good example :
https://dev.to/chokri/-eg9

**Describe the solution you'd like**

How about having an additional article metadata `slug` (or else) to generate a slug? If `slug` exists in the front matter, `slug` is used instead of `title` to generate a slug.

For example,
```
title: 日本語を学ぶ：私のコツ
slug: How to learn Japanese : my hacks
# Or the author can choose, slug_title: Nihongo wo manabu : watashi no kotsu
...
```

**Describe alternatives you've considered**

I understand that generating a good slug from non-English characters is not very easy. There are options such as

* Chinese pin-yin for Chinese characters?
    * It works only for Chinese characters. How about Japanese Kana characters, Korean characters, Thailand characters, ...?
* UTF-8 `% encodings?
    * Not readable for human beings.
* Understanding each language by recognition?
    * May not always work perfectly. Unstable.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Another option would be to use [Punycode](https://en.wikipedia.org/wiki/Punycode), as used in Internationalized Domain Names:

```ruby
SimpleIDN.to_ascii('english')
#=> "english"
SimpleIDN.to_ascii('日本語')
#=> "xn--wgv71a119e"
```
It's not super readable either, but at least it's a standard that's already used on the web.

**Comment by dmikurube** [comment]
Using Punycode there is a kind of reasonable as it's one of standards, but IIUC, Punycode is used commonly in the domain name part, not in the path part.

To encode nom-ascii characters in the path part, %-encoding is used much more common. (Some recent browsers decode it and show the original characters.)

**Comment by dmikurube** [comment]
I reorganized this old issue into #12350, #12351, and #12352. Then, let me close this.
