### ISSUE TITLE
Wrong posts on top of the year / infinity page

### ISSUE THREAD

**Issue by mahalde** [forem/forem#6971]
**Describe the bug**
On the [Infinity](https://dev.to/top/infinity) and [Year](https://dev.to/top/year) pages the actual top posts are not shown, but instead just posts of the user [javinpaul](https://dev.to/javinpaul).

**To Reproduce**
1. Go to https://dev.to/top/infinity
2. Look at the posts

**Expected behavior**
Should show the top posts of the year / all times.

**Screenshots**
![image](https://user-images.githubusercontent.com/39100405/78013130-50e03f80-7346-11ea-8342-3bc188bd86bb.png)

**Desktop (please complete the following information):**

Brave | 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1809 (Build 17763.1039)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks a lot for the heads up @mahalde, we're looking into it.

**Comment by joshpuetz** [comment]
We've solved this issue in production right now by running `update_score` on articles: we suspect something is amiss with the callbacks that should be trigger that call normally.

Should this issue remain open @rhymes ?

**Comment by citizen428** [comment]
@joshpuetz Maybe keep it open for a bit until we know what happened with the callbacks?

**Comment by rhymes** [comment]
> We've solved this issue in production right now by running `update_score` on articles: we suspect something is amiss with the callbacks that should be trigger that call normally.
> 
> Should this issue remain open @rhymes ?

I'm making sure it doesn't happen to thisMMAlife and I echo @citizen428, we might want to understand what happened before closing the issue

**Comment by rhymes** [comment]
Closing this as months have passed and we're not even sure if we can reproduce it of if it was solved in the meantime. We can always reopen if this presents itself again
