### ISSUE TITLE
Generalize welcome notification flow

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#6990]
Right now, we're populating the broadcasts that correspond to the welcome notifications on `/internal/broadcasts`. We should also be thinking about new communities, and how we'll allow them to interact with this feature.

We need to think about how/if we want to pre-populate notifications, and how to give admins from other communities the ability to change those notifications. We also probably want to give admins the ability to choose their own "author" for welcome notifications (right now, we use the mascot user account to do this).

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by vaidehijoshi** [comment]
Pardon the terrible sketch (I am not a designer 🙈), but here's an idea of what we could do for this. My thought is that we can pre-populate the broadcasts, but allow their content to be edited. We also should probably display the time at which the broadcast(s) are sent out (for example: 2 hours after sign up, 5 days after sign up, etc.) The time doesn't necessarily need to be editable, but we should display it, and an admin can decide to make certain broadcasts "inactive" if they don't want them sent out.

We should also include a toggle switch to make it obvious if this feature is enabled, and we will also need to display which user is the "sending user" (should we make this editable, and if so, how will we validate that?).

![new doc 2020-04-01 11 44 06_1](https://user-images.githubusercontent.com/6921610/78174522-3ffb0100-740e-11ea-9fd3-7ef22a47f70d.jpg)

**Comment by vaidehijoshi** [comment]
Circling back on this now that https://github.com/thepracticaldev/dev.to/issues/7169 is in progress. Splitting out `WelcomeNotification`s and `Announcement`s into polymorphic associations on a `Broadcast` seems like a good first step to help us abstract this out for Forem users (this is already in progress).

Here's what I am imagining so far:

- [ ] We give Forem admin users a "create welcome flow" button, and clicking that button will hit an endpoint to create X number of notifications (if we're going based off of what we have now on production, we'd want to create 10 notifications).
- [ ] A Forem admin can activate all/none/some of those welcome notifications, based on what suits the needs of their specific community.
- [ ] Instead of finding and sending a notification based on the `name` associated with the `Broadcast`, we'd instead default to setting certain "times" on the `Broadcast`. In order to make this work, we'd need to create a concept of `send_at` on these welcome notifications. For example, we'd create a notification with a `send_at` of `3.hours`, and use the `send_at` on the notification to decide when the notification should be sent when the `Broadcasts::WelcomeNotification::Generator` calls on it. In the `3.hours` notification example, the generator would send that notification 3 hours after a user was created.

In a way, this gives us some control while retaining flexibility; we get to decide how many notifications can be created or "sent out", but Forem admins can decide which of those they want to activate, and what content they want to "populate" the notification with. We'd also be able to generalize tracking for each notification as well; imagine a Forem creator logging into the admin dashboard for `/internal/broadcasts` and being able to see how many of their users are clicking on "3 hours" notification after they've signed up.

However, what I don't have an answer to just yet is how we'll deal with the "conditional logic" of sending each notification. It's easy enough to see if a user has received a `3.hours` notification, but if we want to do any _other_ checks, I don't know how we'd abstract _that_ out?

I'm open to ideas here; this is an interesting scenario of walking the line between "super DEV specific" and "very Forem abstract". cc @thepracticaldev/delightful + @thepracticaldev/oss + @benhalpern

**Comment by vaidehijoshi** [comment]
I'm not sure when we're going to tackle this redesign, but in an effort to clean up outstanding issues before Hacktoberfest, I'm going to close this.
