### ISSUE TITLE
Improve SiteConfig editing experience

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#6996]
**Is your feature request related to a problem? Please describe.**

Our `/internal/config` form starts getting too long as the `SiteConfig` grows.

**Describe the solution you'd like**

It would be nice to be able to update sections of the `SiteConfig` separately, e.g. have separate tabs (?)

**Describe alternatives you've considered**

Keep it as is, and suffer :D

**Comment by lightalloy** [comment]
To our amazing contributors: issues labeled "type: bug" are always up for grabs, but for feature requests, please wait until we add a ready for dev before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our contributors' guide.

**Comment by rhymes** [comment]
@Ridhwana are you working on this? Otherwise I think it'd be fine to add it as a hacktoberfest issue :)

**Comment by lightalloy** [comment]
The issue is not relevant anymore (after the /admin rework).
