### ISSUE TITLE
Click to edit header appears when another user shares an unpublished post with me

### ISSUE THREAD

**Issue by Avalander** [forem/forem#6998]
**Describe the bug**

Another user shared the link to an unpublished post with me. When I go to the link, I see the header with the link _Unpublished Post. This URL is public but secret, so share at your own discretion. Click to edit._

Clicking the link sends me to a 404 Not Found, so it's not a huge problem.

**To Reproduce**

1. Create an unpublished post.
2. Open the link to the post with another account.

**Expected behavior**

I shouldn't see a link to edit the post.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/9766906/78131284-1c8a8300-741b-11ea-9d24-9df3f106c0a8.png)

**Desktop (please complete the following information):**

- OS: Linux KDE neon
- Browser: Firefox
- Version: 74.0

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by takmar** [comment]
@rhymes 
I fixed this in the [PR](https://github.com/forem/forem/pull/9511). I hope you check it!
> To claim an issue to work on, please leave a comment.

Sorry for not claiming to work on this😞
