### ISSUE TITLE
Support alignment in markdown tables

### ISSUE THREAD

**Issue by glebec** [forem/forem#703]
## Feature Request or Task

GFM tables include `:` syntax for text alignment within columns.

```
default | left | center | right
--------|:-----|:------:|-----:
x       | x    | x      | x
```

default | left | center | right
--------|:-----|:------:|-----:
x       | x    | x      | x

Dev.to doesn't appear to support this styling currently.

### User Story / Description

As an author, I expect:
- to be able to control column alignment using `:` in md tables

### Definition of Done

`:` usage in GFM tables results in visual alignment.

**Comment by jessleenyc** [comment]
Hey @glebec, sorry for the delay. This is definitely a nice feature to have but it might have some unintended side effects with markdown. This is approved if anyone would like to work on it.

**Comment by maestromac** [comment]
not stale

**Comment by glebec** [comment]
The upstream PR for redcarpet https://github.com/vmg/redcarpet/pull/605 would actually make this issue solvable by allowing Dev.to's custom renderer to define a `tablecell` callback that uses alignment information – I think. Something to try at least if and when that PR is merged.

**Comment by megapower786** [comment]
Amazing work bro

**Comment by rhymes** [comment]
This should be easy, as long as https://github.com/vmg/redcarpet/pull/605 is merged

**Comment by cmgorton** [comment]
Thank you so much for the issue and discussion around it. 
We are in the process of going through and cleaning up some of our issue history to help us better prioritize what we need to be focusing on. Given this has been inactive for quite some time I am going to go ahead and close it for now.
