### ISSUE TITLE
Move Internal Mod Searching to Elasticsearch 

### ISSUE THREAD

**Issue by mstruve** [forem/forem#7066]
When searching for users we are doing a fuzzy search in Postgres. Lets switch that search to Elasticsearch since that is what it was built for and can do it very fast. We can also use a type-ahead approach if we want. 

Recommendation from #7002

**Comment by guivinicius** [comment]
Cool. 😉

**Comment by rhymes** [comment]
Hi @guivinicius, thanks a lot for volunteering? I'm going to assign you to it, and don't worry, there's no rush at present :)

**Comment by cmgorton** [comment]
Looks like this feature was added with PR #7123. If not let me know and I will open this back up. Thanks!
