### ISSUE TITLE
Post translator

### ISSUE THREAD

**Issue by allytiago** [forem/forem#7089]
In fact, the posts published on the platform are of excellent quality and should be seen by everyone, but what about those who do not understand the language in which the publication was made? What to do? Well I believe it would be interesting to have an option where the reader could translate the content of the post and this could be done or internally, that is, the one who wrote would make other posts of the same content in other languages ​​and point to the original, or for third party api, such as Bing translator or google translator, or if a member translates, a link to the translated post is informed in the original post.

### The author did several translations for the same post:
In the tab itself to write a post there would be the option of multi-languages, where the author would choose one of the languages ​​listed in the option, and would rewrite that post in the chosen language and there would be no language limits. When the reader accesses the post, there would be before the tags an option called "translate" to show all the languages ​​translated for the post.

### By third party api
In this case, the site could offer two options, or the writer adds his own api key of the supported translator, leaving it up to the author to pay the translator's subscription, since neither google nor bing offer a sufficient monthly limit of free characters for dev.to, or the website itself add the option and bear the costs.

### Collaborative translation.
I think I've seen something similar on the site, but it was a link from the post to the original. But the request I'm making is that there is an option where there is a collaborative translation, where another member translates the post into his language, is sent for the approval of the primary author and if approved, there will be a translation option in the original post for the language that was translated collaboratively. In this case, the reader would be redirected to the post translated by the collaborator and in the translated post there would be a message stating that it is a translation of another post.

**Comment by citizen428** [comment]
Thanks for the issue @allytiago! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by abenettt** [comment]
I think translated posts are a great idea! And community translations or even creator translations are awesome too! If there is no translation for a post and one would use a third party translator if one would take #4168 into account one could choose a translator based on the original language for the best possible result. For example DeepL for all the languages they support and Google or Bing translator for the rest.

**Comment by equiman** [comment]
Duplicated [#890](https://github.com/forem/forem/issues/890)

**Comment by volanar** [comment]
I think that at an early stage of development, use 1 language, and the built-in translator should translate to the native language specified in the user settings. This is used in all known social networks.

**Comment by cmgorton** [comment]
Let's add conversation around this to #890 if this feature is still wanted. Thanks!
