### ISSUE TITLE
Allow users to move saved posts from the Reading List to a custom list

### ISSUE THREAD

**Issue by Stargator** [forem/forem#710]
## Feature Request or Task
Users are allowed to create custom named lists. Then from the Reading List are able to move a saved list to the customer list.

Additionally, from an article a user can click on the Bookmark icon and chose which list to store the saved post.

### Additional Info (device/browser, helpful links)
MacOS 10.13.1, Chrome 69

**Comment by jessleenyc** [comment]
This makes sense. We'll be giving the reading list some love early next year and we'll keep this in mind.

**Comment by cmgorton** [comment]
Hey, we are working on cleaning up stale issues in the repo. Since this has been inactive for over a year I am going to go a head and close this. Thanks.
