### ISSUE TITLE
Long name is breaking to multiple lines

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#7117]
**Describe the bug**
A user / organization with a long name will have it break onto multiple lines if it goes below a certain width.  This "problem" is more pronounced on smaller screens.

This might be a bit of an edge-cased based on the average length name and screen size, but I still think it's important to people and organizations with longer names.

**To Reproduce**
Press `CMD + minus` to zoom out on a profile with a longer name.  You will observe it spills over.  You can also view the included screenshot.

**Expected behavior**
Open to ideas.  Maybe the text could re-size before it spills over?

**Screenshots**
![sample screenshot of long name spilling over](https://cl.ly/54d7a2e71444/Image%202020-04-06%20at%204.43.41%20PM.png)

**Additional context**
I'm actually creating this issue on behalf of an organization that is having this problem / annoyance.

**Comment by vaidehijoshi** [comment]
Using an ellipsis (`...`) might also be nice here. I've seen it done on some other platforms and it seems to usually prompt people to try to shorten the name, if possible.

**Comment by rhymes** [comment]
What we're doing now is to use a CSS property that automatically breaks words, so it works if the org is named `Something Very Long With Separate Words` but not, as you noticed, `SomethingVeryLongWithoutSeparateWords`:

![Screenshot_2020-04-07 SlightlyLongerName - DEV(local) Community 👩‍💻👨‍💻(1)](https://user-images.githubusercontent.com/146201/78644959-09623200-78b7-11ea-81df-ce7cb0657cec.png)

(I added a space between `Sligthly` and `LongerName`)

An alternative is not to break the word and add ellipsis as @vaidehijoshi suggested.

I played with it a bit adding the full name as a `title`:

![Screenshot 2020-04-07 at 9 59 00 AM](https://user-images.githubusercontent.com/146201/78645038-2434a680-78b7-11ea-84a9-1245fec037b1.png)

and this is with a smaller display:

![Screen Shot 2020-04-07 at 09 59 44](https://user-images.githubusercontent.com/146201/78645120-43cbcf00-78b7-11ea-8453-4330a0277b57.png)

but it doesn't look much nicer 

(cc @ludwiczakpawel)

**Comment by JessicaG** [comment]
For those who can't shorten their name, it would be great to see a css rule to help adjust on different screen size. For example, when the width is at 1320px, the font size could reduce from 60px to 50px and it still looks nice.
