### ISSUE TITLE
Twitter Embed Doesn't Update Stats

### ISSUE THREAD

**Issue by ahmadawais** [forem/forem#712]
## Bug Report

Folks the embedded tweets do not get updated as far as the stats are concerned. If there were 10 likes when you embedded a tweet, it stays that way even when there are more likes. Is it just me or everyone?

### Expected Behavior

Twitter updated stats should be displayed.

### Additional Info (device/browser, helpful links)

Chrome/MacOS

**Comment by nektro** [comment]
This is because the code by Twitter given to embed tweets does not connect to their live updates service. It simply creates an `<iframe>` with the static data from an API call.
https://help.twitter.com/en/using-twitter/how-to-embed-a-tweet

**Comment by jessleenyc** [comment]
Hey sorry for the delay on this. This is approved for anyone who wants to work on it but we want to continue using our liquid tags for the embed and not through the official Twitter embed.

**Comment by brarnaudovski** [comment]
@jessleenyc Can I start with this? 
If I did my research correctly, I'll need some background job, which eventually fetch all tweets (from `Tweet` table, as dev.to stores all the tweets in articles), and will make call through `TwitterBot` to fetch the latest data, and update the counters...

**Comment by rhymes** [comment]
@brarnaudovski I wonder what would be the policy around that. Fetching **all** tweets everytime would probably be too much. We need to think of the right combination of how many tweets and how far back the logic has to go but the problem of "how far back" is that an old tweet might become popular again...

What do you think?

**Comment by Zhao-Andy** [comment]
@rhymes I think _way_ back then we discussed fetching tweets only for articles that have been viewed recently. When we were having that discussion, we didn't have the `PageView` model yet. Maybe in the `PageViewController` we could create a job to update that article's tweets?

**Comment by rhymes** [comment]
@Zhao-Andy That would be an interesting trick! 

I like the idea, the first user gets the "stale count", the next one (or at least the one that see the article when the async job is done) will see the updated count

**Comment by brarnaudovski** [comment]
@Zhao-Andy I beleive it's a great idea. I will try to implement this. As I am still learning the project concept, maybe I'll need help, when the `PageViewController::create\update` is called, so I can test this...

**Comment by abraham** [comment]
Something else to keep in mind is that older tweets will see a lot less activity. For example a tweet less than 24 hours old could probably be updated every hour or so while a tweet that's a couple of months old probably only needs to be updated every couple of months.

**Comment by brarnaudovski** [comment]
@abraham Great point. I can introduce some config value, which will skip update on tweet, unless X value old..

**Comment by MarkPieszak** [comment]
I was about to open an issue but saw this ones already open!

Yes it seems like Twitter embeds are still caching old values and not live-updating with the latest <3's and comments, etc.
