### ISSUE TITLE
Allow podcasts and other sidebar links to be visible without authentication.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#7159]
**Describe the solution you'd like**

Ability to allow enable / disable sidebar links such as podcasts, videos etc to be visible without authentication (excluding reading list, moderation etc)

**Additional context**

My logic here is to support smaller communities as it is not well known that these features exist unless a member logs in, also the podcast feature is getting better and better and some communities may lean more towards video content.

**Comment by Ridhwana** [comment]
Thanks for the issue @leewynne! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by benhalpern** [comment]
This looks good to me. No reason we don't need to include these navigation links in the non-authenticated view. Of course, the view shouldn't include reading list (unless we want to have it be a log-in trigger, but better just to leave it out).

So this is good to go in my opinion.

**Comment by leewynne** [comment]
This is looking great in Prod!

**Comment by emgoto** [comment]
It looks like we currently do show `Podcasts` and other links in the logged out view, is there anything left to do on this ticket?

**Comment by rhymes** [comment]
Good point and good catch @emgoto!

The current sidebar looks like this for unauthenticated users:

![Screenshot_2020-07-18 DEV Community](https://user-images.githubusercontent.com/146201/87848251-a8e38780-c8de-11ea-9785-6521515b6665.png)

@leewynne does this cover your initial request? is there anything else missing?

**Comment by leewynne** [comment]
Hi. It was updated a while ago for non auth 👍🏼
