### ISSUE TITLE
Actions Menu: Set Experience Level

### ISSUE THREAD

**Issue by lisasy** [forem/forem#7198]
### Status: Ready for implementation ✅

![take action](https://user-images.githubusercontent.com/816402/78920492-51fd2500-7a48-11ea-9861-bc4b23c8bd01.png)
**⚠️ Warning: the screenshot above is for illustration purposes only — please see Figma doc for true specs**

---

### Requirements
A mod can:
- open the "Set experience level" section of menu
- select any of the options below

If mod selects an option...
- they receive a toast confirmation, which can also give them the option to undo.
- they can only select one option at any time (radio select)

If mod undos the previous action..
- they receive a toast confirmation.

### UX details
- Interaction states: [Default, Hover, Selected]

### Design assets
- [Flow: set experience level (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=426%3A2702)
- [UI specs + states (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=419%3A8264)

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by lisasy** [comment]
@rhymes thanks for adding the tags :)
