### ISSUE TITLE
Actions Menu: Mark as Low Quality 👎🏽

### ISSUE THREAD

**Issue by lisasy** [forem/forem#7225]
### Requirements
A mod can:
- mark as low quality.
- after submission, get a snackbar confirmation.
- undo action.

A mod can both **mark as low quality** and **mark as spam**. A mod cannot mark as low quality and high quality.

### UX details
- Interaction states: [Default, Hover, Selected]
- Components: tooltips

### Design assets
- [Flow: rate post quality (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=426%3A2739)
- [UI specs + states (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=419%3A8264)

**Comment by lisasy** [comment]
I've updated this mock to reflect recent UI and interaction changes in the top section.
![Screenshot 2020-04-16 14 43 59](https://user-images.githubusercontent.com/816402/79511102-79796200-7ff3-11ea-9be2-9543c0b9cc0c.png)

**Comment by msarit** [comment]
(this comment also applies to Issues https://github.com/thepracticaldev/dev.to/issues/7348 and https://github.com/thepracticaldev/dev.to/issues/7226)

This issue has been completed 💃 However I would like to flag an aspect of the buttons' interactivity that **we need to discuss and decide on**.

Right now, all three reactions can be highlighted (showing that they have been selected) at the same time. In production, we have a _thumbsdown_ reaction and a _vomit_ reaction, which can both be selected together.

However, now that we have a _thumbsup_ reaction,  it doesn't make intuitive sense to me to have either _thumbsup-thumbsdown_ or _thumbsup-vomit_ selection pairs.

In speaking with Andy, he suggested that the model could be modified to disallow the selection of a thumbsup with any other reaction.
