### ISSUE TITLE
Actions Menu: Adjust Tags

### ISSUE THREAD

**Issue by lisasy** [forem/forem#7256]
### Requirements
A mod can:
- remove a tag
- add a tag
- leave a note to explain why (required)
- use an existing canned response
- add a new canned response
- after submission, get a snackbar confirmation (persistent)
- undo the action

### Design assets
- [Flow: adjust tags (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=426%3A3359)
- [UI specs + states (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=419%3A8264)

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
