### ISSUE TITLE
Allow roles to be granted for a certain amount of time

### ISSUE THREAD

**Issue by Zhao-Andy** [forem/forem#7288]
**Is your feature request related to a problem? Please describe.**
Sometimes we mark a user as `warned`, `banned`, or `comment_banned` for a certain amount of time (1 day, 1 week, etc). We currently keep track of this manually though, and sometimes things slip through the cracks.

**Describe the solution you'd like**
To follow our current pattern of handling time-based issues, we'd like to create a daily rake task that clears the user of their role as needed.

We will need a way to keep track of when their role should expire. We currently use the [Rolify gem](https://github.com/RolifyCommunity/rolify) to handle this, but as far as I know there's no good way of manipulating the join table the gem provides. 

Personally, I would add an `expires_at` column to that join table, and the rake task would simply check if the current date is greater than the `expires_at` date. But I don't think it's feasible with how Rolify handles this.

We'll also need to add a way to add custom times for those roles, in `/internal/users/:id/edit` where roles are granted.

**Additional context**
We use the [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler) to run rake tasks. 

For examples of tasks we have, see `lib/tasks/*`

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by majakomel** [comment]
I would like to work on this one 🙋🏼‍♀️

**Comment by rhymes** [comment]
Hi @majakomel, thanks!

I guess it'd be best to come up with a plan before starting the implementation, how would you think it's best to proceed on this?

cc. @Zhao-Andy

**Comment by majakomel** [comment]
Hi @rhymes & @Zhao-Andy,

It's indeed impossible to add additional columns to join table since it uses `has_and_belongs_to_many` association. 
There was some work done on replacing it with `has_many :through` years ago but the gem doesn't seem to be actively maintained 😕.
I found a workaround to use `has_many :through`, which could be used in this case: https://github.com/RolifyCommunity/rolify/issues/318#issuecomment-276480921

In the long run it would probably be the best to replace rolify with custom code.

**Comment by Zhao-Andy** [comment]
Hi @majakomel, thanks for researching this! I think it'll be best to hold off on this until we get some custom implementation going. That issue you linked was helpful; I'll discuss with the team to see if we want to go with that workaround.

**Comment by citizen428** [comment]
Thanks @majakomel and @Zhao-Andy. For the time being I unassigned this issue again and changed it from `ready for dev` to `type: discussion`. Once a plan has solidified we can move forward with the implementation.

**Comment by cmgorton** [comment]
Andy I am going to close this for now. Let me know if you think it would be a good RFC and we can open it back up :)
