### ISSUE TITLE
Liquid comment in notifications list bad

### ISSUE THREAD

**Issue by qm3ster** [forem/forem#7351]
**Describe the bug**

![Annotation 2020-04-17 031307](https://user-images.githubusercontent.com/10551234/79518498-e9223800-8059-11ea-8390-f0fff13d1451.png)

**To Reproduce**

1. Have a notification that shows a comment, for example a reply notification, wherein the text contains a liquid tag for another comment on dev.to
2. Have a viewport width of over `1120px`, so that `#articles-list` is no longer full-width, but fixed width instead.
3. At viewport widths of `760px` and over, `.liquid-comment` becomes `width: 620px` which kills the crab.
4. Removing that fixes notifications view but breaks the normal views.

**Expected behavior**

![Annotation 2020-04-17 031526](https://user-images.githubusercontent.com/10551234/79518496-e7f10b00-8059-11ea-8e64-ff2267a644f7.png)

**Desktop (please complete the following information):**

- OS: Classified
- Browser: Chromium
- Version: Classified

**How to actually fix**

Use flexbox for everything. Even post body. *Especially* post body.

**Comment by qm3ster** [comment]
I swear I saw a similar issue, but I can't find it in search again :(
If anyone knows how to find it, please link this there.

**Comment by citizen428** [comment]
Thanks for the issue @qm3ster! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
There might be some helpful clues in this other issue https://github.com/thepracticaldev/dev.to/issues/7170

**Comment by qm3ster** [comment]
The issue I believe I saw had the words "liquid" "comment" and "overflow" in the title, but I can't find anything with those words or their permutations. I am shooketh.

**Comment by ludwiczakpawel** [comment]
I think this should be now resolved (or at least outdated since we have updated Notifications center).
