### ISSUE TITLE
Ability to turn on/toggle flair tag on moderated tags

### ISSUE THREAD

**Issue by jonathan-irvin** [forem/forem#736]
## Feature Request 
Turn on / toggle flair tag for private tags

### Definition of Done
Users who are given mod rights to a tag should have the ability to turn on the flair tag

**Comment by jessleenyc** [comment]
Sorry, can you clarify the request?

**Comment by jonathan-irvin** [comment]
Talked with @benhalpern about this.  Right now, I prefix my articles with "Jelly Fin" and use the #jellyfin tag.  I was talking to Ben about the idea for OSS projects who have mod rights to their tag to have the ability to turn on the flair tag similar to #discuss #ama etc.

Here's an example:
![screen shot 2018-10-04 at 11 45 58 am](https://user-images.githubusercontent.com/2481437/46489496-23efb280-c7cb-11e8-8ce6-630dcea186ab.png)

**Comment by jonathan-irvin** [comment]
Instead of #showdev I would want it to say #jellyfin

**Comment by benhalpern** [comment]
Not stale

**Comment by maestromac** [comment]
not stale

**Comment by cmgorton** [comment]
Thanks for opening this issue Jonathan. Because this issue has become stale I am going to go a head and close it for now. @benhalpern if you think it is still a feature we should implement feel free to open it up again. Thanks.
