### ISSUE TITLE
Please don't let user theme settings colorize/override the original images.

### ISSUE THREAD

**Issue by PranavBhattarai** [forem/forem#7371]
As u can see in the screenshot below, the webpage looks great to read but its image in this [article](https://dev.to/lmolivera/everything-you-need-to-know-about-relational-databases-3ejl?signin=true) is completely distorted. 
![Screenshot from 2020-04-18 16-34-19](https://user-images.githubusercontent.com/32763112/79635799-c6e00580-8192-11ea-8b08-ce576c798f53.png)

But the actual image is like this:
![Screenshot from 2020-04-18 16-44-53](https://user-images.githubusercontent.com/32763112/79635962-06f3b800-8194-11ea-9fbd-0fc51139d433.png)

I think there is a way around to resolve this issue. The site doesn't colorize profile pictures and various other sections. We need to do the same for images or gifs uploaded in an article too.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @PranavBhattarai, thanks a lot for your report!

I reproduced it using [that article](https://dev.to/lmolivera/everything-you-need-to-know-about-relational-databases-3ejl).

I think I found a clue to where the bug lies: those images are transparent gifs, see [this one](https://res.cloudinary.com/practicaldev/image/fetch/s--GB6F907P--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/eery6whloy63atlybiag.gif) for example:

![](https://res.cloudinary.com/practicaldev/image/fetch/s--GB6F907P--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/eery6whloy63atlybiag.gif)

Playing with dev tools I was able to set it to a red background :-/

![Screenshot 2020-04-18 at 5 07 45 PM](https://user-images.githubusercontent.com/146201/79641344-35bf5d80-8197-11ea-88f5-cc071b9e82e7.png)

**Comment by PranavBhattarai** [comment]
@rhymes I really hope there will be a fix for this. We all love dark mode, but it comes with some price. Transparent figures/gifs don't need to be touched by the user's color preferences.

**Comment by citizen428** [comment]
@PranavBhattarai That would be negating the point of having a transparent background. If you don't want the site to influence how your image looks, the image needs to set a background.

**Comment by citizen428** [comment]
@PranavBhattarai Wouldn't that negate the point of having a transparent background in the first place?

**Comment by PranavBhattarai** [comment]
@citizen428 I don't know how to answer that apart pointing to the legit problem.

No matter what we do, how is the condition; we do need to use "exception handling" mechanism in our codes to bypass somethings which can lead to error. And this case is no different. 
Right question is, how to check and not colorize those areas which contain gifs/images.

**Comment by PranavBhattarai** [comment]
Fake:
![Screenshot_20200606-084041](https://user-images.githubusercontent.com/32763112/83934642-f1693a80-a7a1-11ea-8b11-5c9c3a7af6c0.jpg)

Vs

Real:
![Screenshot_20200606-084044](https://user-images.githubusercontent.com/32763112/83934675-38573000-a7a2-11ea-97e9-67d7463c00c1.jpg)

Theme: Built-in "Ten X Hacker Theme"

**Comment by cmgorton** [comment]
@PranavBhattarai 
I do no believe they are being colorized. I think they already had the white background on them but you don't see that in light mode. 

This has more to do with the images being loaded than with the themes themselves. 
If you took that image and put it on any dark background it would look the same. I put the same image in to Figma and added a dark background. The image itself has white around the black circles. So the image is the problem. There is not colorizing happening. 

![Screen Shot 2020-12-04 at 3 02 11 PM](https://user-images.githubusercontent.com/21039864/101214553-d341a180-3641-11eb-9f5c-4477087d9b97.png)
