### ISSUE TITLE
Add Emoticon in Documentation

### ISSUE THREAD

**Issue by vinayhegde1990** [forem/forem#7397]
**Is your feature request related to a problem? Please describe.**
When writing a new blog post, there should be a handy link to describe the syntax for **emoticons** compatible with Markdown

**Describe the solution you'd like**
Add [**this**](https://gist.github.com/rxaviers/7360908) or **[this](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md)** as possible documentation for it in the **Editor Guide** page with a heading **Markdown Emoji** (_refer highlighted part in bottom left in attached screenshot_)

**Describe alternatives you've considered**
Alternatively, members would need to search for Markdown Emoji syntax in Google

**Additional context**
Please let me know if I can pitch in with any more information describing this feature request.
![new-post-doc png](https://user-images.githubusercontent.com/19818985/79783422-4110b580-835e-11ea-83bb-cdb07d7fa257.jpg)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
For any potential contributors, please note that we're using the [Gemoji](https://github.com/github/gemoji) gem which refers to [Emoji Cheat Sheet](https://github.com/github/gemoji) for documentation.

**Comment by mapra99** [comment]
Hey @citizen428! I'm new here in dev.to codebase, Can I work on this issue?

**Comment by Ridhwana** [comment]
Hi @mapra99 yeah sure this issue is up for grabs - I'll assign you to this issue. @ludwiczakpawel cc'ing you on this issue too, as you're working on significant changes to this page.

**Comment by vinayhegde1990** [comment]
thanks @mapra99 @citizen428 @Ridhwana for taking this up, please let me know if I could share any inputs here.

**Comment by mapra99** [comment]
Hey team, sorry for my late response.
@Ridhwana, @citizen428 I made the environment setup following the instructions [here](https://docs.dev.to/installation/mac/#installing-dev), but I'm having this issue when I run http://localhost:3000.
![image](https://user-images.githubusercontent.com/27536621/82127237-954d6080-9777-11ea-8427-830086de6d24.png)
Btw, I'm pinging you guys because It seems I can't ping @thepracticaldev/oss. Is that ok?

**Comment by rhymes** [comment]
@mapra99 this should have been fixed by #7874, could you update your local branch? Let us know if you're still experiencing issues

**Comment by mapra99** [comment]
worked @rhymes, thanks! 🤘

**Comment by rhymes** [comment]
Reopened as the issue hasn't been addressed yet :-)

**Comment by singhsuryansh12** [comment]
Hey @rhymes! Can I work on this issue?

**Comment by rhymes** [comment]
Hi @singhsuryansh12, yeah, I've assigned you to the issue.

One thing though: how do you plan to tackle this? What kind of user experience are you thinking of? Supported emojis are hundreds - https://www.webfx.com/tools/emoji-cheat-sheet/ - and I'm not quite sure that we should render all of them.

cc @ludwiczakpawel which also might have ideas on how to go about this

**Comment by ludwiczakpawel** [comment]
Yea, I'm not really sure how to tackle this. One thing is whether or not we actually need this and if yes how do we display that to make it not bloat the entire help guide...

IF we need that, then here's my initial idea how to display it:

![image](https://user-images.githubusercontent.com/108287/90751136-069c3280-e2d6-11ea-9cf5-9d79ab0d7735.png)

---

Also, can someone explain me how would that work? Would we have to import all artworks into our codebase (as assets)? Another question: emojis are displayed in a different way depending on platform (operating system) - is this something we take into consideration and how would that work?

**Comment by rhymes** [comment]
I wonder how GitHub does it. They essentially show a dropdown of all supported emojis when you type `:`

**Comment by ludwiczakpawel** [comment]
@rhymes would be nice yea, but then, if we want to implement some "autocomplete within editor" functionality, I think there are better things to start off with, like autocomplete for liquid tags :)

**Comment by MishManners** [comment]
Couldn't you just have a link to all the [emojis](https://www.webfx.com/tools/emoji-cheat-sheet/) in the side bar, like this?

![Suggestion](https://user-images.githubusercontent.com/36594527/95414082-b60d9100-0978-11eb-97e8-34f894749663.png)

I've been writing lots on Dev.to and this would be super useful. What are people's thoughts?

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).


As this one already had a lot of discussion but seems like it needs more buy in from everyone I will be writing a post in [forem.dev](forem.dev) for it so we can continue the discussion there. 


You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).

**Comment by cmgorton** [comment]
Here is the[ post on forem.dev](https://forem.dev/foremteam/discuss-add-emoticon-in-documentation-5abk) if anyone would like to add any more information there. Thanks.
