### ISSUE TITLE
Create search filters (non-UI component)

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#7407]
**Is your feature request related to a problem? Please describe.**

As a user, I'd like to be able to search by types of posts, tags, etc. Currently we offer very little in this regard.

**Describe the solution you'd like**

I think we can punt on the UI and start by implementing filtering from the searchbox/url on up. This will create a solid foundation when we go to create the UI.

It should include filtering such as... Posts that include videos, posts tagged with (any of or all of variations), posts published between certain dates, posts by certain users or orgs, posts with at least x points or comments, podcasts published between certain dates, users who joined in certain dates, or have published to certain tags (only search by publicly available info such as this), etc. etc. etc.

We don't need to account for _all scenarios_, but it would be great to get us headed down a path where we have an extensible interface for defining these things.

Ideally the top level URL should be user-legible and not just gobbledygook, even if it's translated to something more machine-friendly when it hits the `/search/feed_content` endpoint.

GitHub's search might be good inspiration `is:open is:pr author:@me`.

Once we get this up and going we can also create a UI to complement it.

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by cmgorton** [comment]
As we are currently changing our search in general I am going to close this issue for now. Ben let me know if you would like to reopen it.
