### ISSUE TITLE
Word adjacency understanding in search.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#7408]
If I search `Can anyone explain how to use Ajax to connect to a C`

These are my results...

<img width="961" alt="Screen Shot 2020-04-20 at 8 38 03 PM" src="https://user-images.githubusercontent.com/3102842/79812415-d738e180-8346-11ea-8c2a-33485968f04c.png">

Adding quotations... `"Can anyone explain how to use Ajax to connect to a C"` gets me results relating to the post I knew existed...

<img width="986" alt="Screen Shot 2020-04-20 at 8 38 46 PM" src="https://user-images.githubusercontent.com/3102842/79812448-f9cafa80-8346-11ea-9568-92ebd91a9834.png">

Even though it's nice that we respect the quotations as a standard, we should do a better job at plucking out this kind of phrase in the results in the first place.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Rafi993** [comment]
Hello there, Is this issue up for grabs if so I would like to help.

**Comment by rhymes** [comment]
Sure @Rafi993, go ahead and thanks! I'm going to formally assign you to the issue :) Let us know if you get stuck or need any help.

**Comment by Rafi993** [comment]
Awesome. Thanks @rhymes

**Comment by Rafi993** [comment]
I could not reproduce this in local. It does happen in [production](https://dev.to/search?q=Can%20anyone%20explain%20how%20to%20use%20Ajax%20to%20connect%20to%20a%20C) though I even copied those articles to my local still could not reproduce it.
![article0](https://user-images.githubusercontent.com/8092120/81155400-85c55f00-8fa2-11ea-8d7a-58f4a9f005a1.png)

these articles appear much lower when I scroll down the search result

![article1](https://user-images.githubusercontent.com/8092120/81155387-8231d800-8fa2-11ea-8548-25c1347ec309.png)

Any help on how should I go about re-producing it in local would be awesome.

**Comment by Rafi993** [comment]
Is it possible these articles have lots of comments, content body that have "how to" in their comment section that makes them come at the top (ratio of number of words in the page to number of matching words?). And using Double quotes makes does exact search rather than splitting in to keyword ?

**Comment by mstruve** [comment]
The reason you cannot reproduce it locally likely has to do with the article scores. We heavily weight the articles based on their score when sorting to ensure those higher rated articles in terms of content quality show up closer to the top.

**Comment by Rafi993** [comment]
Hi there. I realised I still need to get little more comfortable with rails before taking this up. I'll unassign this issue from myself and comeback little later to it if this still around :)

**Comment by luis-novoa** [comment]
Good morning,

I have an idea on how to tackle this issue. May I work on this?

Best regards,
Luis Novoa

**Comment by rhymes** [comment]
@luis-novoa I've assigned the issue to you!

**Comment by luis-novoa** [comment]
Thank you, @rhymes :)

**Comment by luis-novoa** [comment]
Hi, @rhymes. I tried to work on this, but I'm having too many difficulties to understand how elasticsearch works. I'll unassign from this task. Thanks for the opportunity
