### ISSUE TITLE
Actions Menu: Flag user

### ISSUE THREAD

**Issue by lisasy** [forem/forem#7427]
### Status: Ready for implementation ✅

![2020-04-21_Flag-User](https://user-images.githubusercontent.com/816402/79917418-4feb7c80-83df-11ea-9dbe-6a1894a6a943.png)

⚠️ Warning: the screenshot above is for illustration purposes only — please see Figma doc for true specs

### Requirements

A mod can:
- choose one of two options to flag a user (required)
- if mod chooses to report inappropriate content, then a required open textfield appears
- if a mod takes an action, they receive a snackbar confirmation of their action
- the action cannot be undone.

### Design assets
- [Flow: flag user (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=504%3A5318)
- [UI specs + states (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=419%3A8264g)

**Comment by lisasy** [comment]
This is ready for implementation. 

@Zhao-Andy @msarit @jacobherrington

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
