### ISSUE TITLE
Drafts are not loading fully

### ISSUE THREAD

**Issue by lukeocodes** [forem/forem#7436]
**Describe the bug**

I have a saved draft that I am trying to continue writing today. The preview still shows the mostly finished article. When I click on edit, I am only getting a much earlier version.

**To Reproduce**

Go to Dashboard -> Click on mostly finished draft post -> Click on edit -> Find almost empty draft markdown

**Expected behavior**

Go to Dashboard -> Click on mostly finished draft post -> Click on edit -> Find mostly finished draft post markdown

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Version 10.14.6 (18G1012)
- Browser: Chrome
- Version: Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by lukeocodes** [comment]
@rhymes this has resolved itself, but the draft preview and the draft edit screens differed for almost an hour!

**Comment by citizen428** [comment]
@lukeocodes Would you prefer to keep this issue open for a bit to see if it happens again or do we close it now and reopen it if it becomes a problem again?

**Comment by lukeocodes** [comment]
Hmm let's leave it until early next week while I edit these other posts. We can close it if it appears to have resolved itself still by then.

I've been in and out of posts all morning again and it's not come back up. 

I'll let you all know 👌

**Comment by citizen428** [comment]
Good deal, thanks @lukeocodes!
