### ISSUE TITLE
Authentication option: Sign in with Apple

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#7445]
As we look to expand authentication options, I think [
Sign in with Apple ](https://developer.apple.com/sign-in-with-apple/) would be a good one to look at.

**Is your feature request related to a problem? Please describe.*

We are limited in the usecases we can provide with future communities by only having Twitter and GitHub right now, and in expanding our auth we need to take baby steps to get this right. I think Apple as another auth method could be a really great step.

**Describe the solution you'd like**

I think its _raison d'etre_ fits well with what we're trying to do in terms of privacy and "antifraud" features to ensure people are real users. Of course Apple is just one more giant platform and we'll want to just make this one piece of a broader evolution of our authentication menu.

I think Sign in with Apple is an option we could roll out for DEV itself while also making it immediately available for other communities.

Here is a gem we might want to use...

https://github.com/nhosoya/omniauth-apple

I haven't given this a deep dive technically so I'm not aware of any technical gotchas, but I feel like this wouldn't be an overly difficult feature to get implemented.

I'm nervous about any code we have in the codebase that _assumes_ the current state of just Twitter and GitHub but I think we'd find that pretty quickly in developing this feature and it wouldn't cause critical bugs.

***

This one has a special case that we'd only want to display it in the case of the user being on an Apple device so there's some extra considerations there. I think it might make sense to limit the areas we display the actual log in options to the modal and registration landing pages so we can reduce display complexity, especially with regards to how we are limited by how we do caching across parts of the site.

**Comment by citizen428** [comment]
> This one has a special case that we'd only want to display it in the case of the user being on an Apple device

It's possible to sign up for an Apple ID without owning a device ([docs](https://support.apple.com/en-us/HT204316#web)):

> To create an Apple ID on an Apple TV, Android device, smart TV, or streaming device, you can usually follow the steps provided onscreen and enter your full name, date of birth, an email address or phone number, and a payment method.

I know people who are not current Apple users who still have an Apple ID (either from a previous device or because they use Apple Music on Windows or Android, both of which are supported platform (https://support.apple.com/en-us/HT205365).

**Comment by citizen428** [comment]
@rhymes Do you think this is something you'd like to tackle as part of your current auth refactoring work? If not, how does someone else work on this without creating too much extra effort down the line?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
