### ISSUE TITLE
image uploads & article updates limit tracking are not expired after 30s as expected

### ISSUE THREAD

**Issue by tamcv** [forem/forem#7503]
**Describe the bug**
This issue was found from this PR: https://github.com/thepracticaldev/dev.to/pull/7444/files#r414669615

Rails version 5.2.4.2 (latest version of 5.2) does not support expires_in option for Rails.cache.increment for redis_cache_store. As a result, value will be expired after 24 hours (by default), not 30 seconds as expected.
https://github.com/rails/rails/blob/v5.2.4.2/activesupport/lib/active_support/cache/redis_cache_store.rb#L262
This was fixed in master branch( rails 6):
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/redis_cache_store.rb#L277

**Additional context**

Not sure if we can use rack-attack (https://github.com/thepracticaldev/dev.to/blob/master/config/initializers/rack/attack.rb) to throttle requests because the key needs user_id
Other possible solution is that we can clone this patch: https://github.com/kickstarter/rack-attack/blob/129e970d42f86c5c46978988c5c09b0eddaec35a/lib/rack/attack/store_proxy/redis_cache_store_proxy.rb#L13-L25

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by benhalpern** [comment]
Thanks for bringing this up. We noticed it and I adjusted our limit thinking this might be the case but never followed up. We ran into a user who tried to upload 10+ images in a single day and was disallowed, so we currently increased the limit to be more effective for daily total but the code is still buggy as you pointed out.

**Comment by maestromac** [comment]
Looks like this was resolved with https://github.com/forem/forem/pull/7515
