### ISSUE TITLE
Sort reading list by article date

### ISSUE THREAD

**Issue by angelsalazar** [forem/forem#7532]
**Is your feature request related to a problem? Please describe.**

I was looking for an article on my reading list and I notice that there is no way to sort the entries by date. this makes searching really hard in case a user forgot the article title.

**Describe the solution you'd like**

it would be great if the reading list entries could be sorted by date or at least they are displayed sorted decently.

**Additional context**

Page: https://dev.to/readinglist

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Rafi993** [comment]
Hello there, if this issue is not taken I would like to help :)

**Comment by rhymes** [comment]
Hi @Rafi993, sure, it might be better to kickstart a discussion about the UI in this case as we need to figure out where and how to put the controls for this, both in desktop and mobile

**Comment by Rafi993** [comment]
There is a dropdown to choose sort order in https://dev.to/listings/dashboard  (sort by **"Recently Created"** or **"Recently Bumped"**)

![sorting](https://user-images.githubusercontent.com/8092120/98248575-240a9f80-1f9b-11eb-9d70-73df5109dd6d.png)

**Comment by Rafi993** [comment]
There is another similar sort dropdown in https://dev.to/dashboard to sort posts

**Comment by Rafi993** [comment]
The issue might be that the search bar occupies the right most position in reading list. While in other examples mentioned above  the sorting dropdown is present there. positioning of the dropdown (is it left or right) needs to be determined.

![search_bar](https://user-images.githubusercontent.com/8092120/98249746-a0ea4900-1f9c-11eb-83af-024f3bc6ff7b.png)

**Comment by Rafi993** [comment]
But search box is present in left in most cases in the UI like the global search, search inside https://dev.to/listings etc.. search box is also present in left in **/admin/listings/categories**
![listing_categories](https://user-images.githubusercontent.com/8092120/98250746-d9d6ed80-1f9d-11eb-9f26-d057aca984b8.png)

**Comment by Rafi993** [comment]
there is another one in **/admin/organizations**

![admin_org](https://user-images.githubusercontent.com/8092120/98251493-c6785200-1f9e-11eb-84dd-a0c43bca242c.png)

I think those should provide reference for this.

**Comment by Rafi993** [comment]
Thank you @rhymes

**Comment by Rafi993** [comment]
Any thoughts on this?

**Comment by rhymes** [comment]
@Rafi993 I pinged our designers, they'll give you feedback as soon as possible :) Thanks!

**Comment by cmgorton** [comment]
Hey @Rafi993  
Thanks so much for you work on this issue so far and for all your contributions. 
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. Given this process I am going to unassign you from this issue for now. 
In the meantime if you see any bugs you want to squash let me know and we can assign them to you! 🕷

**Comment by cmgorton** [comment]
Thank you for opening this request.
I am going to close this issue here. 

Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around the feature! 🙏
