### ISSUE TITLE
Custom Domain Support

### ISSUE THREAD

**Issue by chirgjn** [forem/forem#7596]
**Is your feature request related to a problem? Please describe.**

I want to use my dev.to profile as my personal blog and still want the links to be on my own domain.

**Describe the solution you'd like**

Add a field on the settings page to setup a custom domain (blog.xyz.com, xyz.blog.com).
blog.xyz.com is easier as the user will need to add a CNAME to their domain and they're done. Whereas something like xyx.com/blog will need a bit more changes in the server configuration from the user's side.

When the user visits one of my post they see the same dev.to UI but the url would be from the custom domain. Links for anything that is not owned by me (comments by other's, other profile) would be handled as they're on dev.to

**Describe alternatives you've considered**

Cross posting or using a url shortener is solution but I'm still won't own my links.

**Comment by chirgjn** [comment]
I'd be more than happy to work on this, if we're interested in implementing it.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by davinkevin** [comment]
+1 on this, other public blog platforms allow this, and this was one of the point which could leads my company to choose medium instead of dev.to.

**Comment by jmoney** [comment]
It seems like medium is relaunching custom domains soon.    https://link.medium.com/W95FfBFjxcb

I'd love if dev.to could support this as I like the community better but there's something to be said of linking our own blogs to a domain we own.

**Comment by citizen428** [comment]
Looping in @vaidehijoshi and @benhalpern to see how they feel about this from a product perspective.

**Comment by hotheadhacker** [comment]
+1

**Comment by vaidehijoshi** [comment]
Looping in @forem/systems here to see what technical weigh-in they can provide here. At first glance, this feels like a very DEV-specific feature; I totally see why it would make sense from a technical blogging platform perspective, but I'm also considering how this would apply + impact other Forems, especially more non-technical ones :)

**Comment by benhalpern** [comment]
We've had this request in the past and generally wanted to stay away from this paradigm. IMO we can handle this overall problem set as a use-case for the broader Forem ecosystem.

A company engineering blog, for example, could be its own Forem, and provide the tools such that they can plug into DEV as needed for cross-posting and cross-functionality, but fundamentally making it clear that there is a delineation of the data and ownership between one Forem and another... And then from there they can "play nicely"...
