### ISSUE TITLE
Dropdown under profile picture disappears when cursor is diagonally

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#7606]
**Describe the bug**

Dropdown under user profile disappears when the cursor is moved diagonally 

**To Reproduce**

1. Go to dev.to
2. Move cursor diagonally from the profile picture

**Expected behavior**

The dropdown should stay there when the cursor is moved diagonally upto some distance.

**Screenshots**

![dropdown](https://user-images.githubusercontent.com/8092120/80679874-61b5d980-8adb-11ea-811d-29f7bf1513cf.gif)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Brave
- Version: 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by citizen428** [comment]
Same with Firefox on macOS. Once you're over the menu you can move to the sides, but if you do it before the menu disappears.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by icncsx** [comment]
Hello, team! If this issue hasn't already been claimed, I'd like to take a stab at it.

**Comment by Ridhwana** [comment]
Yeah sure @icncsx, I'll assign you the issue 😊
