### ISSUE TITLE
Profile summary textarea maxlength doesn't match server-side length check

### ISSUE THREAD

**Issue by outfrost** [forem/forem#763]
### Current Behavior

When I type in a profile summary that is 188 characters long, which fits within the `maxlength="200"` of the `textarea`, upon submission I'm informed that the summary is too long.

### Expected Behavior

The frontend's and backend's definitions of maximum summary length should match. I think it would be even better if the frontend would count the characters live and tell the user how many more they may type in. The `maxlength` attribute could then even be removed, since there would be a visual indication of overly long summary text and of exactly how many characters the user needs to strip.

### Mobile & Desktop Screenshots/Recordings

![2018-09-28_22-55-46_ r](https://user-images.githubusercontent.com/18421230/46233085-b3333b00-c371-11e8-9596-b09fec7a7f91.png)

### Additional Info (device/browser, helpful links)

Chrome 69.0.3497.100

**Comment by Zhao-Andy** [comment]
Hm that's strange. Our backend validation does check for 200 characters as well. Could you paste in the summary you were trying here?

If you'd rather email it in privately, feel free to send it to yo@dev.to.

**Comment by outfrost** [comment]
Sure, here goes:

```
{
	"name": "Outfrost",
	"tags": [
		"student/cs",
		"programmer",
		"gameDeveloper"
	],
	"job": null,
	"interests": [
		"gaming",
		"esports",
		"foss",
		"technology",
		"transport"
	]
}
```

It included a newline at the end.

**Comment by Zhao-Andy** [comment]
Ah, I think the tabs are messing up with the front end count and the backend count. The backend counts the tab as a character `\t\`. Here's what the length is, from the backend:
```ruby
summary = "{\r\n\t\"name\": \"Outfrost\",\r\n\t\"tags\": [\r\n\t\t\"student/cs\",\r\n\t\t\"programmer\",\r\n\t\t\"gameDeveloper\"\r\n\t],\r\n\t\"job\": null,\r\n\t\"interests\": [\r\n\t\t\"gaming\",\r\n\t\t\"esports\",\r\n\t\t\"foss\",\r\n\t\t\"tech\",\r\n\t\t\"transport\"\r\n\t]\r\n}"
summary.length
#=> 204
```

Perhaps the front end is not counting the tabs, but not entirely sure what is not being counted exactly.

For the time being, you could maybe change `technology` to `tech`, or `gameDeveloper` to `gameDev`? Both of those worked in development for me.

**Comment by outfrost** [comment]
Ah, that makes things clearer. It's not the escaped tabs. If you were to actually count escapes (`\`), you'd come up to 274 characters. It's the line endings instead - my text editor counted 188 because I use `LF`, but somewhere along the way that got converted into `CRLF`. Perhaps it was the Windows clipboard on my end? But that seems unlikely to me, because Chrome still counted it as within 200 after the text had been pasted into the textarea. Will check from Linux though.

**Comment by maestromac** [comment]
This is from Safari 12. Hmm 🤔

![](https://cl.ly/3047d149a287/Image%202018-10-02%20at%204.44.20%20PM.png)

**Comment by outfrost** [comment]
Nano thinks it's 188
![screenshot from 2018-10-04 16-55-48](https://user-images.githubusercontent.com/18421230/46483023-07696f80-c7f7-11e8-8c12-8327860594f7.png)
and so does `wc`, listing both bytecount and charcount at 188.
![screenshot from 2018-10-04 16-55-28](https://user-images.githubusercontent.com/18421230/46483022-06d0d900-c7f7-11e8-9d00-3199fa267a06.png)
Chrome lets me type this many additional characters before it doesn't allow any further input:
![screenshot from 2018-10-04 17-14-27](https://user-images.githubusercontent.com/18421230/46483967-1bae6c00-c7f9-11e8-95e3-b5194d974d94.png)
And yet ;)
![screenshot from 2018-10-04 17-18-32](https://user-images.githubusercontent.com/18421230/46484199-911a3c80-c7f9-11e8-9bf1-998d5ed395a7.png)

It's a quite minor thing but certainly interesting.

**Comment by Zhao-Andy** [comment]
I believe #1691 resolves this but not 100% sure it covers the edge case previously discussed.

**Comment by cmgorton** [comment]
This issue has gone stale and appears to be fixed. 
If that is not the case @outfrost, please feel free to open up a bug report again! 

Thanks!
