### ISSUE TITLE
User Can't Import articles from WordPress Via RSS Import Functionality

### ISSUE THREAD

**Issue by setevoy2** [forem/forem#7661]
**Describe the bug**
My DEV account stopped fetching posts from my RSS import (I've set DEV to automatically import articles posted to my WordPress blog).
I've tried re-entering the URL and clicking "Fetch Feed Now", but still can not see new draft entries added to my dashboard.

The feed URL is https://rtfm.co.ua/en/rss/ and my dev.to username is @setevoy.

The missing entries I noticed are:

- [AWS Elastic Kubernetes Service: a cluster creation automation, part 2 – Ansible, eksctl](https://rtfm.co.ua/en/aws-elastic-kubernetes-service-a-cluster-creation-automation-part-2-ansible-eksctl/)
- [Helm: Kubernetes package manager – an overview, getting started](https://rtfm.co.ua/en/helm-kubernetes-package-manager-an-overview-getting-started/)

**Expected behavior**
The post should load into their dashboard successfully.

**Additional context**

Similar to the https://github.com/thepracticaldev/dev.to/issues/3070 issue.

I suspect that happens because on the `{{ }}` tags used in the post's text - but what's the way to write about Ansible and Helm then?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by setevoy2** [comment]
Ha! 
Did a "dirty hack": as publishing from my blog to Medium works - so I've just updated my Dev.to settings from the  https://rtfm.co.ua/en/rss/ to my Medium's URL https://medium.com/feed/@setevo4
Then I was able to fetch the feed, and then set back my blog's URL.

Nice... Even more - formatting after import from Medium looks much better, then when importing from the blog itself - require much fewer updates for `code`, etc.

But still...
And the issue is that I'm posting more to Dev.to then to Medium from my blog.

**Comment by setevoy2** [comment]
But here are two other issues... Oh :-(

- some (!) posts are duplicated after import from Medium (see the screenshot, please)
- I can't archive them - after clicking on the"..." at the right corner and choosing "Archive post" - it's disappeared, but after the Dashboard page is reloaded - they're coming back to the "Drafts" list

![Screenshot_20200504_065847](https://user-images.githubusercontent.com/7965314/80935394-10586380-8dd5-11ea-8297-f2effcebd3d0.png)

**Comment by setevoy2** [comment]
Okay...
I gave up.
![Screenshot_20200504_071746](https://user-images.githubusercontent.com/7965314/80935897-6a5a2880-8dd7-11ea-9cd5-66affc6e216f.png)
Stopping publishing to Dev.to then.
Sorry, team.

**Comment by cmgorton** [comment]
@setevoy2 we believe the original issue you posted here has been fixed more recently. I am going to close this issue. If you are still having problems with the other issues you mentioned can you create separate reports for them? Thanks!
