### ISSUE TITLE
Link to your Glitch profile in your Dev.to profile

### ISSUE THREAD

**Issue by melissamcewen** [forem/forem#7697]
**Is your feature request related to a problem? Please describe.**

At Glitch we love how easy it is to add Glitch embeds to Dev.to posts. We'd love to see the ability to feature your Glitch profile in your Dev.to profile alongside the other profile links (Facebook, YouTube, Twitch etc.)

**Describe the solution you'd like**
A "Glitch profile URL" field in the links options for user settings

**Describe alternatives you've considered**
You can always add it to the free text part, but I like the UI/UX of the links section/icons

**Additional context**
Full disclosure I work at Glitch

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hey @melissamcewen Thanks for this feature request. We have plans to make profile fields more general for all Forems. You can see a little more information in this comment on why we are shying away from adding specific companies [https://github.com/forem/forem/issues/9287#issuecomment-669824825](https://github.com/forem/forem/issues/9287#issuecomment-669824825)

For now I am going to close this issue.
