### ISSUE TITLE
dev.to should have custom post's indexing by user's preference

### ISSUE THREAD

**Issue by krishnadevz** [forem/forem#7709]
**Dev.to should have custom posts indexing by user's preference**

*hello when I go to my profile section or any user go and see own post's but we can do only one 
thing means I can only **PIN** my post that is good but if I want my good post's sorted or indexed by my own preference that feature we can implement so all dev users can sort dev posts by preferable order by there own perspective and that's all for my feature request thank you.*

![image](https://user-images.githubusercontent.com/42638797/81293126-6a358380-908a-11ea-9667-29f870f7e3b8.png)

**We can add functionality like hover and select the post or sort by own preference**
![sd](https://user-images.githubusercontent.com/42638797/81293560-298a3a00-908b-11ea-9bea-eea037f6e9af.gif)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
