### ISSUE TITLE
 archive an article from the article page itself

### ISSUE THREAD

**Issue by hyphaene** [forem/forem#7756]
**Is your feature request related to a problem? Please describe.**
Not as I know of ^^

**Describe the solution you'd like**
I would like to add a way to archive an article from the article page itself. ( a simple button )

And maybe redirect to the next article / or reading list after archiving is done ( to be discussed )

**Describe alternatives you've considered**
None for now

**Additional context**
I read only from mobile and the flow is frustrating, considering I can't play with tabs or anything to read / archive quickly
After jumping from the reading list to an article, I have to go back on the list to archive the article, when it could be done from the article.

Also: I'm willing to open a PR for it if the feature is accepted, and when all the requirements are  agreed on ;)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. This one has been around a while with not much traction.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
