### ISSUE TITLE
Footnote and content on return from footnote hidden by top bar

### ISSUE THREAD

**Issue by wayofthepie** [forem/forem#7760]
**Describe the bug**
When following links to footnotes and back from footnotes the line with the anchor gets hidden behind the top bar.

**To Reproduce**
[This post](https://dev.to/wayofthepie/footnote-issue-43m6-temp-slug-580403?preview=3efd6c798b2c7cae5e4947f5fab920b339b18ba1684ee6e6cf23ea667d3a94860ae6a8d8867b7a496110656c5644d2da5c2a1ee83e20f0ad919af8f2) has a simple example and is the one used in the screenshots below.

1. Add a footnote in a post.
2. Save the post.

![image](https://user-images.githubusercontent.com/1102174/81507870-23e55c00-92f8-11ea-8774-84a7f3b93e6f.png)

3. Click the footnote link in the actual content, it will go to the matching footnote but that will be hidden - e.g. the image below should show the foot note `1. A test ↩` but it's behind the top bar.

![image](https://user-images.githubusercontent.com/1102174/81507896-53946400-92f8-11ea-898a-425101a05bbe.png)

4. Similarly try clicking the link back to the content (`↩`) the content will now be hidden behind the top bar.

![image](https://user-images.githubusercontent.com/1102174/81507929-88082000-92f8-11ea-826e-f5208fc7cda7.png)

**Expected behavior**
I would expect clicking the footnote link in the content to scroll to the footnote like this:

![image](https://user-images.githubusercontent.com/1102174/81507955-b980eb80-92f8-11ea-9397-3b7323c55ddf.png)

And I would expect clicking the back reference (`↩`) in the footnote to look like this:

![image](https://user-images.githubusercontent.com/1102174/81507970-e6350300-92f8-11ea-9ffe-90e0b55a457d.png)

**Desktop:**

- OS: Ubuntu 20.04 and Windows 10
- Browser: Latest Firefox and Google Chrome

Thanks!

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by icncsx** [comment]
Hello, team! Can I claim the issue? I'd like to take a stab at it (😀).

**Comment by Ridhwana** [comment]
Sure @icncsx - assigning you this one too 😊

**Comment by icncsx** [comment]
Yay! Great to see you again :grinning:

**Comment by icncsx** [comment]
@Ridhwana Can I get your help on something? Here is one solution I thought of, and I wanted to get your feedback on it.

In brief, listen for the `onhashChange` event, and get the window hash so that we can correctly query the element with that id. Thereafter, get the top pixel location of that element and scroll to that part in the document.

```js
function scrollToHash(){
  window.scrollTo(0, document.querySelector(window.location.hash).getBoundingClientRect().top);
}

window.addEventListener("hashchange", scrollToHash, false);
```

Not the cleanest but I'm confident it will work. By the way, is this article something I can replicate on my local env for testing? Would I go to Rails console and manually create this article, and it would just render like that?

**Comment by Ridhwana** [comment]
Hi @icncsx 😊 I seen a notification on this post before I went to bed last night, but I no longer see it here. Do you still need assistance?

**Comment by icncsx** [comment]
@Ridhwana I linked the relevant PR. Let's chat there :)

**Comment by jacobherrington** [comment]
I believe this has been closed by #8298 :+1:

**Comment by wayofthepie** [comment]
Hi @jacobherrington this still seems to be an issue on dev.to :smile:

Just wondering if it should be fixed there also by now?

**Comment by rhymes** [comment]
Closed by https://github.com/forem/forem/pull/9375
