### ISSUE TITLE
Credits for photos used on Posts

### ISSUE THREAD

**Issue by athul7744** [forem/forem#7763]
**Is your feature request related to a problem? Please describe.**

- A lot of the posts on DEV use open source photos from sites like Unsplash. I think it is correct to give credits to the photographers who took them.

**Describe the solution you'd like**

- A text under the photo showing credits, can allow hyperlinks too.
- While creating posts allowing user to add credits.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks @athul7744!

I'm leaving a comment to link this previous similar request about cover images: [Allow photo credit attribution for cover_image](https://github.com/thepracticaldev/dev.to/issues/1849)

**Comment by cmgorton** [comment]
Closing this one in favor of the conversation in #1849
