### ISSUE TITLE
Allow admin to publish articles that do not appear on the homefeed.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#7768]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

As a smaller community, to help drive initial organic growth, as an administrator I would like to be able to create posts that are there to drive traffic only, in the hope that it converts into community usage. I wouldn't want these posts to saturate the homefeed initially as the valuable community driven content will be minimal.

**Describe alternatives you've considered**

After thinking about it, I can't think of another way.

**Additional context**

I personally feel this will help smaller communities drive traffic and become more relevant in SEO.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by leewynne** [comment]
I think this can be closed now with the introduction of admin scoring thresholds for homefeed visibility
