### ISSUE TITLE
Add a podcast switcher to mobile podcast index view.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#7769]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

As a mobile user, I find it hard to discover other podcasts that are available. I think a small element at the top of the podcast index list to 'select a podcast' or something similar would really aid navigation between podcasts.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by benhalpern** [comment]
I agree with this. We can use the same element that we now have for `/notifications` etc. to accomplish this.

**Comment by leewynne** [comment]
😎

**Comment by TheRohitSharma** [comment]
I'd like to try this, though I haven't had success in getting any of the items to load at `/pod`. Any tips with that would be appreciated. For now, I _should_ be able to make do with hardcoding.

**Comment by fdoxyz** [comment]
Hi @TheRohitSharma! Sorry for the late response, I'm catching up with these issues and wanted to ask: Have you been able to sort out the problem you were having? Are you still willing to give this a try?

There's been a few important updates in the repo in the past couple of weeks so my "go-to suggestion" would be make sure you're in sync with master, then drop the DB and run a `bin/setup` again so you're working on a clean environment.

In case you need any help feel free to ping me, I'd be happy to help 🙂

**Comment by TheRohitSharma** [comment]
> Hi @TheRohitSharma! Sorry for the late response, I'm catching up with these issues and wanted to ask: Have you been able to sort out the problem you were having? Are you still willing to give this a try?
> 
> There's been a few important updates in the repo in the past couple of weeks so my "go-to suggestion" would be make sure you're in sync with master, then drop the DB and run a `bin/setup` again so you're working on a clean environment.
> 
> In case you need any help feel free to ping me, I'd be happy to help 🙂

I haven't hopped onto the project lately, but I'll actually try that tonight. Thanks! Feel free to assign me this one.

**Comment by fdoxyz** [comment]
Hi @TheRohitSharma checking in to see if you need any help in case you've run into problems while working on this.

If you can't work on this at the moment it's totally okay, let us know and maybe someone else can tackle this 🙂

**Comment by TheRohitSharma** [comment]
> Hi @TheRohitSharma checking in to see if you need any help in case you've run into problems while working on this.
> 
> 
> 
> If you can't work on it at the moment it's totally okay, let us know and maybe someone else can tackle this 🙂 


I'm sorry, @fdoxyz! I was never able to get the podcast to populate locally. Any help I can get with that would be very appreciated, and then I can hop back on this ASAP. I tried all the above, btw.

**Comment by fdoxyz** [comment]
No worries! Were you able to go through the setup process in the docs all the way to [Starting the Application](https://docs.forem.com/getting-started/start-app/)? If you're having any problems here what errors do you see in the console and what environment are you using (OS & native or Docker install)?

I'd recommend you pull `master` again so you're back in sync with the current state and try that. Once the app boots up the background jobs should kick in and they should populate the DB (otherwise try to manually run `rake db:seed`). With the app running locally you should be able to see podcasts in `/pod`

**Comment by TheRohitSharma** [comment]
@fdoxyz I'll be trying again this weekend, and I'll let you know what I can report back. Everything else had seemed to populate just fine, just not the podcasts.

**Comment by cmgorton** [comment]
Thanks so much for you work on this issue so far.
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. Given this process I am going to unassign you from this issue for now. 
In the meantime if you see any bugs you want to squash let me know and we can assign them to you!
