### ISSUE TITLE
Enhanced saving of Podcast episodes and playing progress.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#7770]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I think to really take over as a community users primary mobile podcast app, then we need the ability to save/favourite a podcast episode so it appears in 'reading list' (maybe rename that to something like 'saved' so there is space for other saved resources, rather than just posts?) and the progress of a podcast to be saved so that it always stays persistent regardless of the amount of time between listening progress, which could lay the ground work for listening where you left off across devices.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by bmitchinson** [comment]
I was really surprised I couldn't bookmark a podcast link / add it to my reading list. Would love to see this implemented!

**Comment by cmgorton** [comment]
Let's create a post for this one as well in forem.dev for discussion. Maybe we could combine some of the podcast feature requests you have Lee in to one post? Let me know if you would like me to write up something.
