### ISSUE TITLE
View top posts from last 24 hours

### ISSUE THREAD

**Issue by RobbieGM** [forem/forem#7784]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to see the top posts from the last day. Currently the smallest time interval is a week.

**Describe the solution you'd like**

I wish there were an option for "&lt;past day&gt;" as well as what's currently there.

**Describe alternatives you've considered**

Scrolling really far in the top past week feed :/

**Additional context**

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
