### ISSUE TITLE
Option to delete an organization

### ISSUE THREAD

**Issue by alsoknownasdrew** [forem/forem#7798]
**Is your feature request related to a problem? Please describe.**

I would like to delete an organization I've created and it seems there's no way to do it from its dashboard

**Describe the solution you'd like**

An option to delete the organization in settings page

**Comment by atsmith813** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by atsmith813** [comment]
@alsoknownasdrew if you'd like to delete an organization in the meantime, you can email yo@dev.to with that request and we'll be happy to delete it for you!

**Comment by cmgorton** [comment]
I believe this issue was fixed with PR #9357. I am going to close this issue but if you are still unable to delete an organization please let me know and we can reopen this issue. Thanks.
