### ISSUE TITLE
Make 'Today's Podcasts' available without authentication

### ISSUE THREAD

**Issue by leewynne** [forem/forem#7845]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I think allowing Today's podcast to be visible without authentication promotes the deeper features that a community has to offer. I think a basic metric of the most recent 3 released podcasts would be good enough.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by lightalloy** [comment]
Currently, today's podcasts section only displays episodes of the podcasts that a user is following. So, enabling this block for unauthenticated users would require rethinking the logic or/and adding configuration options.

**Comment by leewynne** [comment]
I was thinking when not authenticated, just a pick of 3 of the day, just to highlight that podcasts exist if a fresh user comes in on mobile.

**Comment by leewynne** [comment]
Hey @lightalloy what do you think of the comment above? So with no auth, it shows maybe 3 of the most recent podcasts to highlight that podcasts exist if you are on mobile, post auth it is tailored to what you follow, if you don't follow any then it reverts back to the top 3 again...

**Comment by citizen428** [comment]
I think this is a sensible approach @leewynne, similar to how we it do for the feed.

**Comment by cmgorton** [comment]
Let's open this one up as a post in forem.dev as well so product can have eyes on it and we can open it up for more discussion! Thanks.
