### ISSUE TITLE
Double footers and incorrect theme when opening Trending link

### ISSUE THREAD

**Issue by anwyho** [forem/forem#7866]
**Describe the bug**

When opening a Trending link to a new tab from [Page A](https://dev.to/n8tb1t/tracking-scroll-position-with-react-hooks-3bbj) to [Page B](https://dev.to/devanshh/learn-reactjs-with-the-best-courses-2020-3jg2), I'm directed to a page with light mode (my theme is dark mode) and double dark-background footers. 

Additionally, when hovering links on Page B, the link background color would turn dark. 

This only happens when right-click opening Page B. Directly clicking the Page B link or copying the link target and pasting it into a new tab results in a correct dark mode and only one footer. This also only seems to happen when clicking to Page B - behavior is normal with the other links in the Trending sidebar.

**To Reproduce**

1. Sign into dev.to on Chrome.
2. Make sure dark mode is set. 
3. Navigate to [Page A](https://dev.to/n8tb1t/tracking-scroll-position-with-react-hooks-3bbj)
4. Check "🔥  Trending on DEV" sidebar for [Page B](https://dev.to/devanshh/learn-reactjs-with-the-best-courses-2020-3jg2): "Learn ReactJS with the Best Courses 2020."
5. Open Page B in a new tab from the right-click menu or cmd+click.

**Expected behavior**

Opening Page B with a right-click should lead to Page B with the correct theme and only one footer. 

**Screenshots**

![Page A](https://user-images.githubusercontent.com/8869114/81964079-f7b52e00-95ca-11ea-8d36-421d42d10fe0.png)

The above is Page A with the correct theme. I opened the highlighted link in the Trending sidebar into a new tab and it resulted in Page B below. This only happens with that specific link in the Trending sidebar. All other links worked fine.

![Page B](https://user-images.githubusercontent.com/8869114/81964116-000d6900-95cb-11ea-88d3-07cf47fea281.png)

The above is Page B with the incorrect theme and two footers. My mouse was also hovering the top-left link in the related links section. 

**Desktop:**

- OS: MacOS 10.15.4
- Browser: Google Chrome
- Version: 84.0.4143.2 (Official Build) dev (64-bit)

**Additional context**

I've disabled browser extensions and tested this in incognito mode in Chrome. I couldn't reproduce it in Firefox. 

Good luck! This seems like a pretty interesting bug.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hey @anwyho we have had a lot of changes with our caching and service workers. Is this still an issue you experience?

**Comment by cmgorton** [comment]
Closing for now but let me know if you have still experienced this and I will reopen it!
