### ISSUE TITLE
Proposal: Move dev.to/api to api.dev.to

### ISSUE THREAD

**Issue by citizen428** [forem/forem#7877]
**Is your feature request related to a problem? Please describe.**

When building something on top of our API recently, I found https://dev.to/api to be a somewhat inconvenient base URL, as the existing path component makes it a bit harder to construct API URLs with something like Ruby's URI module, so I had to resort to string manipulation. 

**Describe the solution you'd like**

I propose moving our API do https://api.dev.to.

Some examples that follow the same convention:

* https://api.github.com
* https://api.twitter.com
* https://graph.facebook.com (GraphAPI)

**Describe alternatives you've considered**

![image](https://user-images.githubusercontent.com/47985/82009361-4fba6600-9699-11ea-893a-55729a706783.png)

**Comment by ChrisAchinga** [comment]
could be changed when out of beta

**Comment by Hashimlokasher** [comment]
This will be better approach

**Comment by benhalpern** [comment]
First thing that comes to mind as a concern: This is one more dependency on DNS, eh?

So to think of this as `api.anyforem.com` we need to ensure the DNS for the subdomain is set up properly.

... And maybe adding that as a step is fine, and maybe we want to make wildcard subdomain part of the generic DNS we ask for that allows us to make this work, To ensure that we _can_ add functionality that takes subdomains into account, we might want to do this anyway? But also we sometimes allow session authentication in the API path and making that work with subdomains wouldn't be something we'd get out of the box, eh? We're also now talking about somebody who sets it up like `api.community.mainsite.com` and maybe that's also fine.

That's what comes to mind for me.

**Comment by citizen428** [comment]
@benhalpern All valid concerns and I don't have a problem with leaving it as is. If you want to get a bit of an idea of the complexities involved, this is good basic writeup: 

https://blog.appsignal.com/2020/03/04/building-a-rails-app-with-multiple-subdomains.html

**Comment by cmgorton** [comment]
@citizen428 do you think this is a potential RFC?

**Comment by citizen428** [comment]
@cmgorton I'll just close this for now, I'll think about whether or not I want to revisit this thought in the form of an RFC.
