### ISSUE TITLE
Gif is not showing up in the post

### ISSUE THREAD

**Issue by nisarhassan12** [forem/forem#7889]
**Describe the bug**

Today I wrote this post today https://dev.to/nisarhassan12/free-open-source-portfolio-template-for-developers-ih

I have the following in the body of the post:
```
![Portfolio Gif](https://dev-to-uploads.s3.amazonaws.com/i/7xpbahfwejl9426olm9g.gif)
```

In the HTML that is generated src attribute values seems to be  wrong:

```
<img alt="Portfolio Gif" src="https://res.cloudinary.com/practicaldev/image/fetch/s--M_Wvyypt--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/m9db58xz17fdgdrrcrsy.gif" loading="lazy">
```

I can see the Gif I were to visit this https://dev-to-uploads.s3.amazonaws.com/i/7xpbahfwejl9426olm9g.gif

**To Reproduce**

1. Go to write a post.
2. Add a GIF of that is of a large resolution.
3. Click on "Preview". You'll notice that the GIF itself doesn't show up; only the link does.

**Expected behavior**
If I upload a GIF and render it in the post body, I expect to see the GIF rendered. 
If the GIF exceeds a certain resolution, I expect to see an error notice telling me that I need to upload a GIF of a smaller resolution size.

**Screenshots**

![Screen Shot 2020-11-23 at 1 50 05 PM](https://user-images.githubusercontent.com/816402/100019450-ebd4d080-2d92-11eb-8a22-a6d12b33c57f.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by atsmith813** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by atsmith813** [comment]
@nisarhassan12 I believe the issue is because the GIF is quite large.
>Inline Images
When adding GIFs to posts and comments, please note that there is a limit of 200 megapixels per frame/page.

It looks like your GIF exceeds this limit. I tested the functionality with a smaller GIF and it worked as expected. We'll still want to investigate a better way to communicate the error to users when this happens, but in the meantime, you can optimize your GIF to be smaller and it should work!

**Comment by nisarhassan12** [comment]
@atsmith813 Many Thanks. 

> Inline Images
When adding GIFs to posts and comments, please note that there is a limit of 200 megapixels per frame/page.

Would you please guide How do I make sure that `200 megapixels per frame/page.` is true for my gif. I have resized and the size is now smaller(both dimensions + the file size) but it does not work:

![portfolio-template](https://user-images.githubusercontent.com/46004116/82104312-d91c7780-972f-11ea-9880-96894200235d.gif)

Can you please guide me where I can find the documentation on this. Thanks :slightly_smiling_face:

**Comment by atsmith813** [comment]
@nisarhassan12 your GIF still seems slightly large. For reference, I went to https://www.giphy.com to GIFs that work in our editor. Their dimensions seem to be around 480x270 and 3mb on average.

As far as megapixels per frame, maybe https://ezgif.com/optimize can help. I've used it on personal projects in the past and found it helpful. It has options to remove frames and optimize the file in other ways.

**Comment by jaysonragasa** [comment]
![image](https://user-images.githubusercontent.com/63760343/82134646-53322680-982c-11ea-8ff0-400c291a7496.png)
  
![image](https://user-images.githubusercontent.com/63760343/82134656-752ba900-982c-11ea-8696-a017baa86f57.png)
  
Having the same thing on some of my post.  They are all properly working Github pages.

**Comment by atsmith813** [comment]
https://github.com/thepracticaldev/dev.to/issues/6595

**Comment by jaysonragasa** [comment]
still not working 
![image](https://user-images.githubusercontent.com/63760343/83106609-58765780-a0ef-11ea-911a-49c0e11bcfa5.png)
Link [https://dev.to/jarafpv/htmlagilitypack-test-be-4hhj](https://dev.to/jarafpv/htmlagilitypack-test-be-4hhj)

and one my post still not working   
![image](https://user-images.githubusercontent.com/63760343/83106795-a5f2c480-a0ef-11ea-9e3e-2194a1e8a963.png)

Link [https://dev.to/jarafpv/clear-add-vs-lookup-move-10oo](https://dev.to/jarafpv/clear-add-vs-lookup-move-10oo)

**Comment by pyGuru123** [comment]
I have added 2 gifs in my readme a year ago. But i noticed in last month they stopped displaying altogether. Here's my readme link : https://github.com/pyGuru123/pyGuru123

Kindly check out the issue once
