### ISSUE TITLE
Embed Profile

### ISSUE THREAD

**Issue by jaysonragasa** [forem/forem#7902]
A way to embed our profile? Since I use Github page as my personal "Website" I would like to be able to have some sort of a way to showcase some of my repos and I use dev.to to publish some of these.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @jaysonragasa, I'm not sure I understood correctly your request, but if you're looking for a way to showcase your GitHub repositories in your DEV profile you can already do it by linking them in https://dev.to/settings/integrations

Let me know if that you're looking for

**Comment by jaysonragasa** [comment]
![image](https://user-images.githubusercontent.com/63760343/82583728-03ee4c00-9bc6-11ea-8e80-cbbc6f73f48b.png)
Well I was kind of hoping some sort of like that in screenshot. My twitter feed is embedded in my github page [https://jaysonragasa.github.io](https://jaysonragasa.github.io/) and you can actually do that here [https://publish.twitter.com/](https://publish.twitter.com)  
  
So instead of my twitter, I could embed my posts.

**Comment by rhymes** [comment]
@jaysonragasa makes sense, thank you! I reopened the issue :)

**Comment by jaysonragasa** [comment]
> @jaysonragasa makes sense, thank you! I reopened the issue :)

![image](https://user-images.githubusercontent.com/63760343/82618503-d9bc7e80-9c05-11ea-9d50-ba676917f0ae.png)  
Thanks! I hope a header image is included as well. Just to get sense and an initial idea of what people will be reading if they decided to read.   
  
I usually have a header image in my posts.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
