### ISSUE TITLE
Right column hidden in iPad app

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#7903]
**Describe the bug**

In the native iPad app the right content column is hidden in portrait mode.

**To Reproduce**

- Open the Dev app on iPad in portrait orientation
- Note right column isn't displayed
- Rotate iPad to landscape orientation
- Note right column content is displayed

**Expected behavior**

Either the right column should display, or there shouldn't be some way to access this content (this is done via a move on the iPhone version of the app)

**Screenshots**

![IMG_0225](https://user-images.githubusercontent.com/37842/82146531-9a122300-9810-11ea-8c5d-9ad24b627ef3.png)

![IMG_0226](https://user-images.githubusercontent.com/37842/82146537-a39b8b00-9810-11ea-9339-44f30636727b.png)

**Smartphone (please complete the following information):**

- Device: 2018 iPad Pro 12.9
- OS: iPadOS 13.4.1
- Browser: Safari
- Version:

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Hello sir, this should be fixed now.
