### ISSUE TITLE
Markdown as not valid when appears 'data:text/html' on code

### ISSUE THREAD

**Issue by aralroca** [forem/forem#7905]
**Describe the bug**

I recently wrote an article (https://dev.to/aralroca/from-node-to-deno-5gpn) and I did a workaround to fix a "Not valid Markdown error" when there was `data:text/html` inside a ` ```js ``` ` code.

**To Reproduce**

Add an article with some markdown like this:

![image](https://user-images.githubusercontent.com/13313058/82154413-f9eae700-986d-11ea-9690-034c6e166a64.png)

**Expected behavior**

I expected as correct markdown...

To workaround it, I need it to do this:

```js
const contentType = 'text/html'
const fixedContentType = `data:${contentType}`
```

**Screenshots**

![image](https://user-images.githubusercontent.com/13313058/82154447-50f0bc00-986e-11ea-86ca-a852d1748c53.png)

**Comment by aralroca** [comment]
I think is caused by this:

* https://github.com/thepracticaldev/dev.to/blob/dea823b6eccd945fad973b57a3e6295160d4f78a/app/labor/markdown_parser.rb#L143

It's detected as **xss** when is shared code.

**Comment by ferminhg** [comment]
Hi, do you have the expected solution? 
IMO maybe it's not good to allow that markdown, maybe you'll open the door to XSS infections. 
I proposed two possible solutions:
- Check if `data:text/html` don't have more code at the right side to execute XSS [`,` or `;` ], if you have data code, you don't allow it.
- Provide a better error message like and don't change the behaviour:
`To avoid XSS injections the markdown 'data:text/html` is not allowed`

**Comment by aralroca** [comment]
For me it make more sense to check if is inside a code block or not. For me the expected solution is to throw this error (maybe with a better message) only if the text is not inside a code block.
