### ISSUE TITLE
Buffer API is no longer available to new communities.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#7916]
**Is your feature request related to a problem? Please describe.**

Buffer API is no longer available to new communities.

**Describe the solution you'd like**

The functionality to buffer directly from the dashboard looks great. I have done some initial research but have not yet found an alternative that will offer the same functionality.

**Comment by atsmith813** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by atsmith813** [comment]
@leewynne I'm less familiar with Buffer and the dashboard off the top of my head. Can you clarify, is this more of a bug or a feature request? Thanks!

**Comment by rhymes** [comment]
@atsmith813 apparently [the Buffer API](https://buffer.com/developers/api) has been shutdown for new users since October 2019 - see also 

![Screenshot_2020-05-18 Buffer API - Developers](https://user-images.githubusercontent.com/146201/82233235-ffa90100-992f-11ea-9972-39e7a588a738.png)

from https://buffer.com/developers/api/logs

**Comment by atsmith813** [comment]
@rhymes Oh wow! Just ice cold, goodbye. So then this is a feature request for a replacement.

**Comment by benhalpern** [comment]
I think our answer here is that we should loop the functionality of "scheduling" into our app itself, essentially doing the Buffer side through our platform itself.

(This probably means renaming the model away from `BufferUpdate`, of course)

But as it stands, I could see adding a `schedule_for_tweet_at` datetime attribute and then run scheduler to tweet via the Twitter API at the scheduled time...

I actually don't think that's an overly complex feature, and it just means one less dependency on our end. We'd need to make sure we maintain compliance with any Twitter terms of service around automation, and make it clear how new communities can also maintain compliance.

**Comment by rhymes** [comment]
@benhalpern the result of this will likely also build the groundwork to import scheduled tasks that now run through Heroku scheduler to run through our Sidekiq infrastructure so we are less dependant on that as well

**Comment by akhil-naidu** [comment]
@rhymes , any idea how to configure this?

Heroku build is getting an error and there is no support from the buffer.

Can you give a lead on configuring this?

**Comment by rhymes** [comment]
@akhil-naidu not sure exactly, our code is pretty tied to Buffer for now, probably by transforming 

https://github.com/thepracticaldev/dev.to/blob/fde4d3f189552dd587bab64bacf2d689da91c551/app/models/buffer_update.rb#L35

in a no op that doesn't do anything and returns an empty string?

**Comment by citizen428** [comment]
@benhalpern I assigned you this issue because it fits within the scope of the next cycle. If Buffer is no longer available to new communities, we need to find a solution for this.

**Comment by cmgorton** [comment]
@citizen428 @benhalpern @rhymes there is still no alternative for this right? Would it be fair to label this as a potential RFC?

**Comment by citizen428** [comment]
@cmgorton RFC#17 talks about deprecating this in the future, but we don't have a dedicated RFC for it yet.

**Comment by cmgorton** [comment]
I am assuming this can be closed now that we have removed Buffer all together. @benhalpern let me know if that is not the case and we can reopen this!
