### ISSUE TITLE
Onboarding enhancement that offers some topics for new community members to write about

### ISSUE THREAD

**Issue by leewynne** [forem/forem#7917]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Now that we have a new element that provides a new community member with 3 actions post onboarding, maybe we can somehow help them a bit further with some topic suggestions when they choose to write an article.

**Comment by atsmith813** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
I know I am sounding like a broken record today Lee😅 But could we open up a post in forem.dev on this one as well if you still think it is a good feature.
