### ISSUE TITLE
Missing RSS Feed Stories due to liquid variable

### ISSUE THREAD

**Issue by shawnwildermuth** [forem/forem#7938]
My RSS Feed integration is missing stories. Feed is:

https://wildermuth.com/rss

Story Missing:
http://wildermuth.com/2020/05/11/Where-Did-Filters-Go-in-Vue-3

It is in the RSS feed but doesn't get pulled. 

**To Reproduce**
Add my RSS Feed to an account.
See the Drafts and published versions and see that the story is missing. 
**Expected behavior**
It should include all the stories.

**Desktop (please complete the following information):**
Doesn't seem to be client-side, but server side issue. 

- OS: Win10 
- Browser: Chrome 
- Version: Latest

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @shawnwildermuth , the reason that your article is not imported is that it contains liquid variable syntax (`{{ something }}`), a feature we disabled. Since that is a valid code within a code-block, it should be ignored. We currently don't have that logic in place yet but it can be on our upcoming roadmap.

**Comment by shawnwildermuth** [comment]
Thanks, I dove into the source to figure out how to fix it, but I'm not a ruby guy so I gave up. Unfortunately this means all my Vue talks are going to be missing from your platform. My guess is that I'm not nearly the only one running into this (which is why Vue is so sparse I would guess).

**Comment by cmgorton** [comment]
Hey @shawnwildermuth . One of our engineers tested out your RSS feed. This is what they said:
 I was able to import their feed on community.benhalpern.com and some of the posts contains the "{{ variable }}" string that the author is mentioning in their report.

You can check in this draft that was imported with the RSS feed (last code block) https://community.benhalpern.com/rhymes/vue-3-and-validation-with-the-class-validator-2iik-temp-slug-487908?preview=e4d1de46d55c8ae702e17b9663a354b833f19f857d89a0a4702a35c5cc7d4da557f16b7902ab3dbeef6c9649c4f570e3bd892ccf9de5cc13cbf67a5e 

It looks like this has been fixed. Could you confirm if this is still an issue for you?

**Comment by shawnwildermuth** [comment]
It's not picking up the old stories, but i'll re-test when I publish a new Vue article.
