### ISSUE TITLE
Allow filtering of what gets synced to stackbit blog

### ISSUE THREAD

**Issue by emTr0** [forem/forem#7971]
**Is your feature request related to a problem? Please describe.**

Every post you make on dev.to gets synced to the stackbit blog.

**Describe the solution you'd like**

You should be able to choose tags that won't get synced to the stackbit blog. At least for me, a help post isn't something I'd like synced, for example.

**Describe alternatives you've considered**

There are none.

**Additional context**

N/A

**Comment by lightalloy** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled "type: bug" are always up for grabs, but for feature requests, please wait until we add a ready for dev before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our contributors' guide.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. This one has been around a while with not much traction.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
