### ISSUE TITLE
Slow main feed, when signed in.

### ISSUE THREAD

**Issue by madzadev** [forem/forem#8005]
I've been experiencing some very slow **Home section** load times lately (in all tabs: feed, week, month, year, infinity). The problem occurs only when I'm signed in (via GitHub). When I am signed out, problem is gone and home section works as expected.

Note, that only the first 7 articles gets delayed every time. 
Delay might be from 1 to 10 secs. See the GIF below. 

![ezgif com-optimize (3)](https://user-images.githubusercontent.com/42511917/82567288-d71a4480-9b85-11ea-9f68-374e108dab47.gif)

If I choose **Tags section** instead, and do the same, the feed works fine. See GIF below.

![ezgif com-optimize (2)](https://user-images.githubusercontent.com/42511917/82568190-201ec880-9b87-11ea-9b87-b230bf8c1c79.gif)

I'm using Google Chrome (Version 81.0.4044.138 (Official Build) (64-bit)) and I did disable all the extensions.

Even further I did clean installs of latest Firefox and Opera and the problem still persists: once I sign in, I get long delay of first 7 articles being loaded in the main feed.

**Edit:** Another thing I noticed is, when Im signed out, the articles in Home section don't get sorted each time I refresh, but once I'm signed in they are sorted by reactions, comments, etc. That's why I was thinking there might be some optimization to do with an **algorithm that calculates the order** of top articles being displayed!?

**Comment by mstruve** [comment]
Hi @madzadev! Thank you so much for submitting the issue. This looks to me to be an issue with a slow database since those first articles are loaded from Postgres. Seeing as we have beefed up our database recently and improved our queries I am going to go ahead and close this. If you continue to experience this let us know!
