### ISSUE TITLE
Distinguish when a post has been updated in the notifications feed

### ISSUE THREAD

**Issue by fletcher-greg** [forem/forem#8031]
**Describe the bug**
Old posts appear daily in my notification feed. These posts range from a month old to 1 year.  They all come from one user. I have screenshots I'll post below with personal details removed.

#### Example
This morning I clicked on my notification feed and noticed a post from a user that was made 5 hours ago. Right next to that notification were 3 notifications from a user who made their posts ranging from a few months to a 1 year ago.  

**Screenshots**

![example_3](https://user-images.githubusercontent.com/45293706/82666663-a6461800-9c36-11ea-91ad-6f6f23473352.jpg)
![dev_to_old_posts_notifications_feed](https://user-images.githubusercontent.com/45293706/82666664-a7774500-9c36-11ea-9d72-752875763109.jpg)
![example_2](https://user-images.githubusercontent.com/45293706/82666667-a80fdb80-9c36-11ea-8123-39d8bcee2b27.jpg)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Ridhwana** [comment]
Hi @fletcher-greg. Thanks for the issue, however, the reason that these posts are appearing in your timeline is because the author has updated the posts recently. 

For example:
- https://dev.to/helenanders26/sql-201-6-ways-to-search-with-system-tables-h0 was Updated on May 18, 2020. 
- https://dev.to/helenanders26/aws-series-why-a-vpc-is-like-the-london-underground-k7p was Updated on May 21, 2020. 

You're able to see the updated date in the header with the authors name and initial creation date.

**Comment by Ridhwana** [comment]
Perhaps it would be valuable to show the updated date in the notifications when there is one instead of the creation date.

**Comment by joshpuetz** [comment]
Agreed @Ridhwana. This would be something perfect for a contributor to work on if they have the inclination!

**Comment by fletcher-greg** [comment]
Hi @Ridhwana. Thanks for the information. 😀

Yeah, I think it would make more sense to see an **update** notification rather than **made a new post** for older posts.  It's very odd to see the words **[user] made a new post 1 year ago**. I think readers are more likely to be interested if they see **[user] updated their [post name]**.

**Comment by joshpuetz** [comment]
That's a wonderful suggestion @fletcher-greg!

**Comment by gaganlokesh** [comment]
Hi @Ridhwana @joshpuetz! 
I'm new to this codebase. Can I take this up as my first issue?

**Comment by Ridhwana** [comment]
Hi @gaganlokesh 😊 Welcome 🎉 Yes sure you can, I'll assign you to the issue.

We should show `updated at <new date>` for posts that were updated in the notifications.

**Comment by gaganlokesh** [comment]
@Ridhwana Thanks for assigning! 😊

I needed a small clarification on this...
Looking at the screenshots below, could you please suggest which UI I should implement?

**Original Post:**

<img width="572" alt="Screenshot 2020-05-26 at 2 22 41 AM" src="https://user-images.githubusercontent.com/22362677/82843955-6c0d9c80-9efc-11ea-9b5b-dbcc1a5f5569.png">

**Updated Post:**
**[1]** As you suggested
<img width="572" alt="Screenshot 2020-05-26 at 2 35 06 AM" src="https://user-images.githubusercontent.com/22362677/82844718-31f1ca00-9eff-11ea-9399-582c30b2ad3a.png">

**[2]** As @fletcher-greg  suggested
<img width="573" alt="Screenshot 2020-05-26 at 2 23 59 AM" src="https://user-images.githubusercontent.com/22362677/82843813-0a4d3280-9efc-11ea-8d80-edc0ca7f15ed.png">

**Comment by Ridhwana** [comment]
Thanks @gaganlokesh! I like @fletcher-greg's suggestions better 😁

**Comment by gaganlokesh** [comment]
Great! I'll go ahead and implement this. Thanks!

**Comment by cmgorton** [comment]
Looks like this is already a feature we have now. 
![Screen Shot updated article](https://user-images.githubusercontent.com/21039864/112903677-16b69480-90a5-11eb-89ec-fcfe2cdfad6e.png)
