### ISSUE TITLE
Focus mode for writing posts

### ISSUE THREAD

**Issue by steveblue** [forem/forem#8034]
**Is your feature request related to a problem? Please describe.**

When writing a post for dev.to I would like the ability to completely focus on writing. On desktop the "Write a Post" button feels redundant here, the header and footer are just distractions I have precious moments in the day to write, so I want to be completely focused on writing. On smaller screens the additional real estate for writing would be welcome. The footer feels like its in the way when I'm making corrections to posts on a mobile device and I've accidentally hit "publish" a couple times when I didn't mean to. Focus mode could solve that problem, making it so the user has to knowingly toggle back to see the footer.

**Describe the solution you'd like**

The ability to hide the header and footer to maximize screen real estate when writing a post. Perhaps the Fullscreen API is a solution here or just alternative styling that allows the user to switch between a "focus mode" and "default". The user should be able to toggle the mode. It's possible this setting should persist so focus mode is activated by default, but I'd be fine with just the ability to toggle the mode.

**Describe alternatives you've considered**

Writing the post in another editor. This is problematic when using images you want hosted on the platform.

**Additional context**

I am keen on volunteering to contribute this feature.

<img width="1680" alt="Screen Shot 2020-05-22 at 10 39 37 AM" src="https://user-images.githubusercontent.com/1171943/82695367-d03d1180-9c19-11ea-88cc-1d7640e59415.png">

**Comment by maestromac** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@steveblue what this be solved by the no-chrome mode we have in https://dev.to/new ?

Open https://dev.to/new and press `0`

the editor buttons don't disappear but the bar at the top does

**Comment by steveblue** [comment]
I don't think that goes far enough @rhymes. I would prefer the editor to be the entire screen, only thing in the view. What I am after is something that mimics the experience of popular writing apps like Ulysses.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
