### ISSUE TITLE
App Store icon on Downloads page incompatible with dark themes

### ISSUE THREAD

**Issue by Amorpheuz** [forem/forem#8039]
**Describe the bug**
The Apple App Store icon on [Downloads](https://dev.to/downloads) page has a transparent fill for icon and letters which make it difficult to see on the page if the user has a Dark theme, i.e. Night Theme or Ten X Hacker theme.

**To Reproduce**
1. Switch to Night or Ten X Hacker theme via Settings -> UX -> Save
2.  Open [Downloads](https://dev.to/downloads) page

**Expected behavior**
The App Store icon is clearly visible on the page, like the Google Play button.

**Screenshots**
- **Ten X Hacker Theme**
![image](https://user-images.githubusercontent.com/22113778/82726864-89781600-9d04-11ea-8ceb-40c2de4d4532.png)
- **Night Theme**
![image](https://user-images.githubusercontent.com/22113778/82726866-8a10ac80-9d04-11ea-9f0f-c6601478c244.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge Chromium 
- Version: 81.0.416.77

**Smartphone (please complete the following information):**

- Device: Nokia 6.1
- OS: Android 10
- Browser: Edge
- Version: 45.03.4.4955

**Additional context**
Having a similar white fill with a white border should solve the issue if it is allowed as per the App Store Design Guidelines.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hey @Amorpheuz. The App Store icon appears correct on both my phone and my browser in dark mode and Ten X. 

I am going to close this issue but if it still appears for you let me know and we can reopen it. 

![143849592_245571837132273_5398549679581784243_n](https://user-images.githubusercontent.com/21039864/106193159-c1c4d380-6172-11eb-8bf5-a23885c2ed6c.jpg)
![143744815_921126535326074_1766552823969458150_n](https://user-images.githubusercontent.com/21039864/106193170-c5585a80-6172-11eb-8f64-6419560b13d9.jpg)
![Screen Shot 2021-01-28 at 2 12 32 PM](https://user-images.githubusercontent.com/21039864/106193256-e1f49280-6172-11eb-8eef-3c6d797afac1.png)
