### ISSUE TITLE
Create a new page type to dynamically render /welcome and /challenge

### ISSUE THREAD

**Issue by atsmith813** [forem/forem#8075]
**Is your feature request related to a problem? Please describe.**
This feature is a re-scoping of #7267. As an admin, sometimes we set up recurring threads such as the Welcome and Challenge threads. The latest of these threads can be accessed at...

https://dev.to/welcome
https://dev.to/challenge
These redirects are currently hardcoded into the app.

**Describe the solution you'd like**
Ideally, the `/welcome` page would understand which welcome thread data to render and do that instead of redirecting to so we can improve our SEO. Or, at the very least, don't do dynamic redirects to accomplish this goal.

**Describe alternatives you've considered**
Adding an ability to dynamically redirect #7267, but that approach hurts SEO.

**Additional context**
We'll be using this as part of a new recurring thread soon, and it seems like a good time to build the functionality.

As mentioned, searching for /welcome and /challenge in the code should highlight how we're doing this currently.

https://github.com/thepracticaldev/dev.to/issues/7267#issuecomment-632091133

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by jonathanyeong** [comment]
Hi! First time contributor. Can I take this PR? I think I have an idea of where to `render` instead of `redirect` (pages_controller#welcome and pages_controller#challenge).

**Comment by nickytonline** [comment]
I've assigned the issue to you @jonathanyeong.

**Comment by jonathanyeong** [comment]
Dang sorry @nickytonline I have a question already. Do you know why hitting publish on a post does nothing? Am I missing some sort of setup. I'm also having issues with the links on the `internal/welcome` page. I've added a couple of videos below showing what issues I'm facing.

https://www.loom.com/share/39217194cfc0462ab3481a853e2280ad
https://www.loom.com/share/3907477c61bc4e15aee05e8273ccce9a

**Comment by jonathanyeong** [comment]
I have a possible solution, move the `welcome` method (and maybe the challenge) into Stories Controller. Like:

```ruby
# Routes.rb
# get "/welcome" => "pages#welcome"
get "/welcome" => "stories#welcome"

# StoriesController
  def welcome
    daily_thread = Article.admin_published_with("welcome").first
    if (@article = daily_thread&.decorate)
      handle_article_show
      # redirect_to daily_thread.path
    else
      # fail safe if we haven't made the first welcome thread
      redirect_to "/notifications"
    end
  end
```

Does that seem like a viable approach? I don't have enough context about why the `welcome` method is in `PagesController` originally.

**Comment by cmgorton** [comment]
Hey! @jonathanyeong 
Thanks so much for you work on this issue so far.
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. Given this process I am going to unassign you from this issue for now. 

In the meantime if you see any bugs you want to squash let me know and we can assign them to you!🕷

**Comment by cmgorton** [comment]
@atsmith813 do you think this would be a good potential RFC? If so we can add the label. If not, we may want to consider closing this feature request for now.

**Comment by atsmith813** [comment]
@cmgorton closing this - I believe the requirements have changed a bit. If BizDev/Admins needs something like this then we can open an RFC to meet their needs.
