### ISSUE TITLE
Post Signatures

### ISSUE THREAD

**Issue by IamFlowZ** [forem/forem#8094]
**Is your feature request related to a problem? Please describe.**
After searching the issues with a combination of keywords and tags, I don't see anything of this ever mentioned.

Whenever you select the "Write a post" button the front matter is populated with the most basic properties needed to submit an article. Something I personally try to do, is to leave something like a signature at the end of my posts that contain my social links. I know that those are available in the sidebar but the core issue here is "signing-off"

**Describe the solution you'd like**
It would be nice if we could save a signature (kinda like when texting signatures were popular) that could be auto-appended anytime you start a new post.

**Describe alternatives you've considered**
Another thought I had was allowing users to create post templates. It would possibly be a much larger change, but could be extremely useful. Particularly in conjunction with series posts.

**Additional context**
Love the platform =)

**Comment by citizen428** [comment]
Thanks for the issue @IamFlowZ! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
