### ISSUE TITLE
Post too close to edge of ipad screen

### ISSUE THREAD

**Issue by ensigma** [forem/forem#8101]
**Describe the bug**
While visiting the dev.to homepage, as well as posts page, post elements touch the side of the website aka ipad screen.

**To Reproduce**

Go to dev.to on ipad (I used an iPad 7th gen running safari and ipados 13.5). I'm sure you can reproduce on any 10 in ipad.

**Expected behavior**

The rule of thumb is to have at least 15px or 1rem on both sides of a website.

**Screenshots**

![screenshot](https://i.imgur.com/DVFPl9j.png)

**Tablet (**

- Device: ipad 7th gen 10.1 in
- OS: ipad OS 13.5
- Browser: Safari
- Version: not sure, current?

**Comment by citizen428** [comment]
Thanks for the issue @ensigma! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
@ensigma can you try to refresh? this seems to me like some caching issue.. im not sure how to hard refresh cache on ios browser, but you try to open that in Private/Incognito mode of your browser and let me know if it still happens there?
