### ISSUE TITLE
Disable Ctrl+S on New Post page

### ISSUE THREAD

**Issue by kouul** [forem/forem#8154]
**Is your feature request related to a problem? Please describe.**
It gets a little annoying when pressing Ctrl + S and the 'save html page box'  pops up from the browser.

**Describe the solution you'd like**
It would be good to save our content when writing a post **at the time of writing** and then, **disable the Ctrl + S feature**.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by madarsbiss** [comment]
@kouul Drafts already have been auto-saved. You don't need to do Ctrl + S.
If you close New Post page with a content, get power cut, or even log out and log back in, the content you wrote will still be there.

**Comment by kouul** [comment]
@madarsbiss Ok. My point was mostly on Ctrl + s part. After writing a lot, we have the tendency to press Ctrl + s to save it(in my case at least). So, it could be disabled; when user press Ctrl + s, instead of opening the save html page box, it could notify the user that their content is already saved. 
Could bring better user experience  imho..

**Comment by madarsbiss** [comment]
@kouul I feel you, it's more about breaking habits :)
