### ISSUE TITLE
Real-time push notifications

### ISSUE THREAD

**Issue by madzadev** [forem/forem#8155]
**Is your feature request related to a problem? Please describe.**

Currently the new notifications are not shown in real-time.
I have to refresh the page to get them ASAP.

**Describe the solution you'd like**

- User gets notified **even if inactive in DEV**.

![notif](https://user-images.githubusercontent.com/42511917/83236795-c593f680-a19c-11ea-9d75-6815b70e0af8.png)

- User sees notification **while working on other tabs**.

![bar](https://user-images.githubusercontent.com/42511917/83236990-23c0d980-a19d-11ea-93b6-f1684fe0a9c4.png)

> It's best if you could even make the tab's text flashing as soon as there is new notification pushed, to make it more eye-catching.

**Describe alternatives you've considered**

**Additional context**
YouTube, for example, currently use this functionality.

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
