### ISSUE TITLE
Reading list count in the homepage should reflect only non archived items

### ISSUE THREAD

**Issue by abhisheksurve45** [forem/forem#8164]
**Describe the bug**

Reading list count is not updating!

The reading list count is showing 7.

![image](https://user-images.githubusercontent.com/36799020/83291167-8948b080-a205-11ea-9650-08369124f505.png)

However I have only 2 items in the list!

![image](https://user-images.githubusercontent.com/36799020/83291276-b6955e80-a205-11ea-8ff8-fd5ac1f5bcce.png)

Not sure if it a cache issue though! Yet have tried empty cache and hard reload, still the issue persists. 

**To Reproduce**

1. You can add n number of posts to the reading lists.
2. Delete some of them.
3. Check if the count matches on homepage (/) and reading list route (/readinglist)

**Expected behavior**

Count should matche on homepage (/) and reading list route (/readinglist)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

The posts were there in my reading list for several days (approx 10-15). Also posts weren't removed at once, last update in reading list was couple hours ago.

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by jacobherrington** [comment]
It seems like, if the posts were in your reading list for quite some time, it might *not* be an issue with our caching.

I'm not experiencing this issue on my machine (Ubuntu + Firefox/Chrome),

**Comment by abhisheksurve45** [comment]
@jacobherrington  Didn't notice the posts were archived by me! 
However the Reading list count shouldn't consider the archived list count is what I feel.

![image](https://user-images.githubusercontent.com/36799020/83292793-5b18a000-a208-11ea-8dda-f96c7b127e3f.png)

**Comment by nickytonline** [comment]
That's a good point @abhisheksurve45. I agree that the list count should be just non-archived posts in the reading list.

**Comment by abhisheksurve45** [comment]
@nickytonline Yeah. Do I need to create a seperate issue for the same, or edit the title for this one?

**Comment by abhisheksurve45** [comment]
@nickytonline @jacobherrington  If you guys think this could be a potential improvement to the interface, I would like to work on this 😄

**Comment by rhymes** [comment]
@abhisheksurve45 I'm going to tag our designers @lisasy and @ludwiczakpawel to gather their opinion on this matter, before you start working a feature we might not end up including :D

**Comment by ludwiczakpawel** [comment]
Yea, I 100% agree. The number should be only about non-archived articles on the _Reading List_. I think you can definitely start working on this 👍

**Comment by thomasbnt** [comment]
Oh good news !

**Comment by 31piy** [comment]
May be related to #8900
