### ISSUE TITLE
Save Button doesn't behave as expected

### ISSUE THREAD

**Issue by jacobherrington** [forem/forem#8167]
**Describe the bug**

Sometimes the save button text doesn't reflect the status of the article. For example, when the article is saved sometimes the button text reads: `Save`. Other times, the article has been unsaved, but the text reads: `Saved`.

It seems like this has to do with the `onMouseout` action in `SaveButton.jsx`, but I haven't investigated it much beyond that!

**To Reproduce**

1. Click "Save" or "Unsave" on an article
2. Move your mouse off of the button quickly
3. Button text is incorrect, but will update if you mouse over the button.

**Expected behavior**

The button text should reflect the status even if the mouse quickly exits the button.

**Screenshots**

![Peek 2020-05-29 13-46](https://user-images.githubusercontent.com/11466782/83294415-e5ceb000-a1b2-11ea-85bd-51005b4efc79.gif)

**Desktop (please complete the following information):**

- OS: Ubuntu 
- Browser: Chrome + Firefox (Seems to happen more frequently in Firefox)
- Version:

**Comment by nickytonline** [comment]
I think this is somehow related to the `onBlur` and `onFocus` (for a11y) events.

**Comment by hanishaDRaheja** [comment]
Hello team, I am new to dev.to and this issue seems to be a good start for me to contribute, is this issue claimed? If not, I would like to solve it.

**Comment by rhymes** [comment]
@hanishaDRaheja please go ahead, I'm going to assign you to the issue

**Comment by dengaku12** [comment]
Hello, I see that this issue hasn't been addressed in a while, so I went ahead and decided to work on it. I submitted a pull request.

**Comment by nickytonline** [comment]
@hanishaDRaheja, did you have any work done for this issue? @dengaku12, can you link this issue to your PR? Thanks!

**Comment by dengaku12** [comment]
@nickytonline i dont know why i wasnt able to link the pull request to this issue. I'm not able to click on 'Linked Issues.' You can look at it here though:
https://github.com/thepracticaldev/dev.to/pull/9238

**Comment by redencion** [comment]
Hi guys, may  I work with this issue ?

**Comment by nickytonline** [comment]
@redencion, @dengaku12 is working on this.
