### ISSUE TITLE
Scaling issue of .user-profile-header

### ISSUE THREAD

**Issue by simskij** [forem/forem#8188]
**Describe the bug**

The sizing units used for the user profile header breaks the box as the window grows horizontally. At 1600xN and less it looks as I assume the design intends it to look, but as the window width grows, it becomes more and more broken, until it breaks in the middle of words (in this case, my surname).

Attaching a few different window widths below that illustrate the issue:

1. Make your browser window 2048xN or wider.
2. Go to any profile with a medium-length or long surname.
3. Make the window wider and narrower to see the difference.

**Expected behavior**

The profile box to look roughly the same at all widths, or at least not break words when there's plenty of room left. 

**Screenshots**

![Screenshot 2020-05-30 at 19 18 11](https://user-images.githubusercontent.com/1596025/83335186-2c9fd100-a2ab-11ea-9417-e0b7fa9cca0c.png)
![Screenshot 2020-05-30 at 19 18 17](https://user-images.githubusercontent.com/1596025/83335182-2c073a80-a2ab-11ea-9479-99a98cb659dc.png)
![Screenshot 2020-05-30 at 19 18 24](https://user-images.githubusercontent.com/1596025/83335180-290c4a00-a2ab-11ea-99b7-e1a79beeeaf8.png)

The only difference in these three cases is the window width.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**

This is somewhat similar to #7117, although in this case it's not about the name length, but rather how the media queries and floats affect the layout.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by simskij** [comment]
I can look at it myself. 👍

**Comment by rhymes** [comment]
@simskij thanks, I've assigned you to the issue

**Comment by simskij** [comment]
Have not gotten around to this yet, but it's still on my todo list. Got the dev env running a couple of days ago, so the biggest obstacle has already been conquered.
