### ISSUE TITLE
Updated Twitter user name not getting reflected in the profile

### ISSUE THREAD

**Issue by vigneshwaran-natarajan** [forem/forem#8208]
**Describe the bug**
I have renamed the twitter user name, but I couldn't see that change in my dev profile, so removed my twitter connection with dev & revoked the application access from the twitter settings & re-authenticated the dev app with the twitter to log in, but still I don't see my updated twitter username in the profile page. (Please let me know if there is any other way to update the user name)

**To Reproduce**

**Expected behavior**
The Twitter user name needs to be get updated in the profile page.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome 
- Version: 83.0.4103.61

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @vigneshwaran-natarajan are you still having this problem? If so, would you mind sharing your dev username and your twitter?

**Comment by vigneshwaran-natarajan** [comment]
hi @maestromac  sorry forgot to update here, actually, my twitter name got updated after few days in dev, it got resolved, can I close the ticket?

**Comment by rhymes** [comment]
Closing the ticket, thanks @vigneshwaran-natarajan
