### ISSUE TITLE
Introduce Vault

### ISSUE THREAD

**Issue by citizen428** [forem/forem#8243]
Add the [vault-rails gem](https://github.com/hashicorp/vault-rails) for secret management with [HashiCorp Vault](https://www.vaultproject.io/).

**Comment by mstruve** [comment]
https://github.com/forem/forem/pull/8891

**Comment by qojrag-muCroj-4demru** [comment]
#[![image](https://user-images.githubusercontent.com/68495777/89201431-7cd33200-d57f-11ea-9d1e-6e4c12809f96.jpeg)]()
