### ISSUE TITLE
Main page <footer> element "Problem".

### ISSUE THREAD

**Issue by ogrotten** [forem/forem#8256]
Because of continuous loading, the footer runs away whenever you get there.

**_Except . . ._** the problem is that the links and info in the footer are not available anywhere else on the `/` page.

For example: To get here to make this report, I manually entered `/about` into the address bar, so I could get the footer element to click "Contact".

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ogrotten** [comment]
I see now that those links are in the `More` of the userblock in the upper left, but I obviously missed it. 

If it were me/my site, I'd probably start by trying the links `About`   `Privacy Policy`  `Terms of Use`   `Contact`   `Code of Conduct` in a small block (small text, no more than 3 lines height) between that `More` element and the Tags block.

**Comment by Ridhwana** [comment]
Hmm it's definitely not first instinct to click on the `More`, thanks for the suggestion @ogrotten!

**Comment by ludwiczakpawel** [comment]
Yea it sometimes drives me crazy too... One pattern I've seen elsewhere is actually stopping infinite scroll at certain point and add "load more" button instead.. so you can reach the footer eventually. but we better think it through since this may impact engagement. infinite scroll is _infinite_ for a reason i guess..

**Comment by rhymes** [comment]
Possible related issue: https://github.com/thepracticaldev/dev.to/issues/5670

**Comment by ardunster** [comment]
@ogrotten I had a similar issue looking for a place to contact over another bug. I did look at the sidebar but there was nothing to indicate that the information I wanted would be there, I ended up googling to find useful links.
