### ISSUE TITLE
Automatic spam/junk remover

### ISSUE THREAD

**Issue by madzadev** [forem/forem#8292]
**Is your feature request related to a problem? Please describe.**

By using DEV quite often, once in a while I came across some useless posts.
Like this, for example:
![Untitledrrr](https://user-images.githubusercontent.com/42511917/83870582-30ae7180-a737-11ea-9ac7-7b7ccca8e0e2.png)

I understand we can report them and they would get reviewed/deleted.
Tho, it would take some time, as it was not the only one as it turned out :)

![captured (6)](https://user-images.githubusercontent.com/42511917/83870730-6bb0a500-a737-11ea-9f55-4ff09368e3e7.gif)

A method to catch them out automatically would be nice.

**Describe the solution you'd like**

You should implement some type of grammar + technical terms checker during post phase.
When user click post, the content gets evaluated and posted/denied based on recognized words in text percentage like (95%) or something similar.

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
