### ISSUE TITLE
Be able to fetch article from API with slug instead of ID

### ISSUE THREAD

**Issue by emilpriver** [forem/forem#8313]
**Is your feature request related to a problem? Please describe.**

Be able to fetch article from API with slug instead of ID.

**Describe the solution you'd like**

Be able to fetch article via slug from api.

**Comment by Muhimen123** [comment]
Why do you want to use slug instead of ID? Anyway, you can use web scraping. Like this.
```
URL = "https://www.dev.to/" + slug_path
```

The website is pretty well-formatted. You shouldn't have any problem scraping the web.

**Comment by emilpriver** [comment]
> Why do you want to use slug instead of ID?

Mainly as it a more prettier link that using an ID. Instead of /post/123123 would I be able to use /post/hello-world which is a more prettier link and also more SEO friendly :D

**Comment by nolleto** [comment]
Use slug still a desirable feature? If so, I can try to implement it.

**Comment by rhymes** [comment]
Hi @nolleto, I think so in theory, have you thought about the API interface?

Right now we have `/articles/:id` to get a published article. How would "get by slug" fit in the API?

**Comment by Oghenebrume50** [comment]
@rhymes so I was looking at this, just curious,  this is  (https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/api/v0/articles_controller.rb) the file where the implementation is made I guess. 
Also is there an extra setup to make the API work in my local environment, because I tried running the get all with curl `curl localhost:3000/articles` but it threw an error. There is nothing in the docs with regards to this

**Comment by rhymes** [comment]
Hi @Oghenebrume50, good questions! the API docs is https://docs.dev.to/api/

The API locally is reachable at `curl localhost:3000/api/articles` and similar URLs but refered to the documentation.

The documentation is auto generated from this file: https://github.com/thepracticaldev/dev.to/blob/master/docs/api_v0.yml

Here's how you can view it and edit it locally: https://docs.dev.to/contributing_api/

**Comment by rhymes** [comment]
Solved by https://github.com/forem/forem/pull/8929
