### ISSUE TITLE
Gitpod errors building Ruby 2.7.1

### ISSUE THREAD

**Issue by snackattas** [forem/forem#8334]
**Describe the bug**
I've been seeing this error in Gitpod lately. This is what it looks like in Gitpod
```
building base image

initializing base image context
UGit operations complete                       location=/workspace/init
running base image build
Step 1/8 : FROM gitpod/workspace-postgres
latest: Pulling from gitpod/workspace-postgres
Digest: sha256:67a7bab86f00f8cf6e8157a3925d9ff119a4eecc734ce72fb94acb0771439246
Status: Image is up to date for gitpod/workspace-postgres:latest
 ---> 88ad1868771f
Step 2/8 : ENV RUBY_VERSION=2.7.1
 ---> Using cache
 ---> 7bcc1c18b350
Step 3/8 : RUN bash -lc "rvm install ruby-$RUBY_VERSION && rvm use ruby-$RUBY_VERSION --default"
 ---> Running in baa285d6f3b2
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.7.1.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system.....
Installing required packages: gawk, bison, sqlite3......
Requirements installation successful.
ruby-2.7.1 - #configure
ruby-2.7.1 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.3M  100 21.3M    0     0  16.6M      0  0:00:01  0:00:01 --:--:-- 16.6M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.7.1 - #validate archive
ruby-2.7.1 - #extract
ruby-2.7.1 - #validate binary
ruby-2.7.1 - #setup
mkdir: cannot create directory ‘/workspace’: Permission denied
ln: failed to create symbolic link '/workspace/.rvm/ruby-2.7.1@global': No such file or directory
mkdir: cannot create directory ‘/workspace’: Permission denied
Gemset '' does not exist, 'rvm ruby-2.7.1 do rvm gemset create ' first, or append '--create'.



build failed: cannot build base image: The command '/bin/sh -c bash -lc "rvm install ruby-$RUBY_VERSION && rvm use ruby-$RUBY_VERSION --default"' returned a non-zero code: 2

Error: build failed: cannot build base image: The command '/bin/sh -c bash -lc "rvm install ruby-$RUBY_VERSION && rvm use ruby-$RUBY_VERSION --default"' returned a non-zero code: 2

```

I get a similar error when I try to build the .gitpod.dockerfile on my local
```
❯ docker build . -f .gitpod.dockerfile 
Sending build context to Docker daemon  555.5MB
Step 1/7 : FROM gitpod/workspace-postgres
 ---> 88ad1868771f
Step 2/7 : ENV RUBY_VERSION=2.7.1
 ---> Using cache
 ---> 2d8899f4c32b
Step 3/7 : RUN bash -lc "rvm install ruby-$RUBY_VERSION && rvm use ruby-$RUBY_VERSION --default"
 ---> Running in 76644e9eccaa
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.7.1.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system.....
Installing required packages: gawk, bison, sqlite3......
Requirements installation successful.
ruby-2.7.1 - #configure
ruby-2.7.1 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.3M  100 21.3M    0     0  9143k      0  0:00:02  0:00:02 --:--:-- 9139k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.7.1 - #validate archive
ruby-2.7.1 - #extract
ruby-2.7.1 - #validate binary
ruby-2.7.1 - #setup
mkdir: cannot create directory ‘/workspace’: Permission denied
ln: failed to create symbolic link '/workspace/.rvm/ruby-2.7.1@global': No such file or directory
mkdir: cannot create directory ‘/workspace’: Permission denied
Gemset '' does not exist, 'rvm ruby-2.7.1 do rvm gemset create ' first, or append '--create'.
The command '/bin/sh -c bash -lc "rvm install ruby-$RUBY_VERSION && rvm use ruby-$RUBY_VERSION --default"' returned a non-zero code: 2
```
**To Reproduce**
Open  a new gitpod workspace that's been built recently, or try to build the docker image yourself on your local

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Hi @snackattas: I just started a brand new DEV workspace on GitPod and it seems to be working okay. 

<img width="1114" alt="Screen Shot 2020-06-08 at 10 50 17" src="https://user-images.githubusercontent.com/47985/83991081-e49d4000-a975-11ea-8f09-556e8c1747bf.png">

I remember 1 or 2 instances in the past where I just deleted my DEV workspace from GitPod and started over with https://gitpod.io/#https://github.com/thepracticaldev/dev.to, maybe try that?

**Comment by snackattas** [comment]
I think the build working on master must have to do with caching of some sort?

I just created a fake commit (https://github.com/thepracticaldev/dev.to/pull/8335) touching the gitpod dockerfile, and was able to see the same error reported here. I imagine you'd be able to see that error if you built Gitpod off that branch

The error seems to have to do with where rvm is installing ruby, its trying to write and install stuff to `/workspace`, which maybe it can't?

On my local I played around with this, and it worked, not sure if it's safe, or what I'm doing really, but having it install to `/home/gitpod` seemed to work

```
RUN rm /home/gitpod/.rvmrc && touch /home/gitpod/.rvmrc && echo "rvm_gems_path=/home/gitpod/.rvm" > /home/gitpod/.rvmrc
```

**Comment by citizen428** [comment]
Yes, I just made an unrelated PR to modify something in our GitPod config and ran into the same issue.

What you're doing works from an RVM perspective. In GitPod's Discourse the developers seem to recommend running the installation via `sudo`, but there's nothing wrong with your approach as long as the app can find Ruby and the gems:

https://community.gitpod.io/t/error-on-installing-older-ruby-version-with-rvm/1090/2

**Comment by snackattas** [comment]
Cool! I'll make a PR for this tonight (or if you beat me to it, feel free to PR it)

**Comment by maestromac** [comment]
I believe this is no longer an issue.
