### ISSUE TITLE
Fix teeny tiny moderation panel close button.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#8365]
On iOS the moderation close button has a _teeny tiny_ icon. It's cute but should probably be changed.

![FullSizeRender](https://user-images.githubusercontent.com/3102842/84158454-e3cde200-aa39-11ea-9c69-3337ee32842f.jpeg)

I suspect this has to do with native button styles on iOS.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
