### ISSUE TITLE
My feed not being fetched

### ISSUE THREAD

**Issue by kadnan** [forem/forem#8373]
**Describe the bug**

I am unable to fetch RSS feeds on my profile (https://dev.to/kadnan). The RSS feed which was being fetched is: http://blog.adnansiddiqi.me/

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 83.0.4103.97 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by AshV** [comment]
I'm also facing the same issue

**Comment by nickytonline** [comment]
> **Describe the bug**
> 
> I am unable to fetch RSS feeds on my profile (https://dev.to/kadnan). The RSS feed which was being fetched is: http://blog.adnansiddiqi.me/
> 
> **Desktop (please complete the following information):**
> 
>     * OS: MacOS
> 
>     * Browser: Chrome
> 
>     * Version: 83.0.4103.97 (Official Build) (64-bit)

Hi @kadnan . Thanks for opening an issue!

I'm curious what the steps were that you took to try and get your feed loading. From what I can tell, your blog does not have an RSS feed. I tried to load http://blog.adnansiddiqi.me/feed.xml and http://blog.adnansiddiqi.me/rss.xml, but they both result in a page not found. Also, take note that importing your RSS feed does not automatically publish them and add them to your profile. They appear as drafts in your dashboard until you publish them.

These are the steps to add your feed to your account on DEV:

1. navigate to https://dev.to/settings/extensions and scroll to the *Publishing to DEV Community from RSS* section.

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/833231/103582492-f020fd00-4eab-11eb-86b4-60a99fe3bbeb.png">

2. Enter the URL to your RSS feed, e.g. http://blog.adnansiddiqi.me/feed.xml 
3. Click on the *Submit Feed Settings* button
4. Once this is done, in might take a minute or two, but then you will see blog posts from your RSS feed appear as drafts in your dashboard on DEV, https://dev.to/dashboard.

Let me know if the issue still persists after following these  steps.

**Comment by kadnan** [comment]
Interesting. So actually Feed URL was not found. I would further check into it. Thanks for reporting as this was not the issue before. The workaround I had done was to put the MEDIUM.com RSS feed as I also mirror posts there.
