### ISSUE TITLE
Design issue in "JOIN NOW" box at home page due to the margin bottom of that box

### ISSUE THREAD

**Issue by siemah** [forem/forem#8398]
**Describe the bug**

Design issue in `JOIN NOW` box due to the margin bottom

It would be great if it has proper margin like it was before, however there is a margin bottom attributed to the first child with `.cta-container` but it not affect the parent.

**To Reproduce**

1. Go to [dev.to home page](https://dev.to/#cta-content)
2. See the bottom of that box `bottom edge`

**Expected behavior**
To give a margin bottom to `JOIN NOW` box to separate it from bottom story section

**Screenshots**

*Current behavior*
![current](https://user-images.githubusercontent.com/28986331/84349063-70011600-abae-11ea-9264-8693f6a48a0b.png)

*Expected behavior*
![expected](https://user-images.githubusercontent.com/28986331/84349115-88713080-abae-11ea-96cb-fd989ccce95a.png)

**Desktop:**

- OS: macOS High Sierra
- Browser: Firefox, Chrome and Safari
- Version: 76.0.1 for firefox, 83.0.4103.97 for chrome and 13.0.5 for safari

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Oghenebrume50** [comment]
Great I would like to work on this @rhymes

**Comment by rhymes** [comment]
thanks @Oghenebrume50! assigned :D

**Comment by AlbertoPdRF** [comment]
As #8420 has been merged already, can't this issue be closed now?

**Comment by nickytonline** [comment]
Also, these screenshots do not reflect the current look of these buttons. Can you confirm that this is still an issue with the latest of the codebase @Oghenebrume50? Thanks!

**Comment by Oghenebrume50** [comment]
@nickytonline yes this was fixed by #8420 and the current live platform reflects such,  this shouldn't be an issue anymore.

**Comment by rhymes** [comment]
@Oghenebrume50 if you add "Closes #number" or "Fixes #number" in the description, the issues will automatically close when the PR is merged.

Thank you for unearthing this issue :)
