### ISSUE TITLE
Make the post editor resizable 

### ISSUE THREAD

**Issue by Muhimen123** [forem/forem#8681]
I don't know if I am being too much neat picky or not, it would be great to have the ability to resize the post editor. It sometimes helps to see more content without scrolling. I think the editor if fine for those who have bigger monitors. But for those who use a laptop like me, things get too much dense soon. 

So, to wrap stuff up, the current editor isn't harming that much but it would be better to have the ability to control the size of the editor.

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
This would also be helpful for mobile (iPhone 8, most likely similar size screens as well). Currently, you cannot do much in the body of a post when editing because of this.

**Comment by Kristina370** [comment]
Jual Obat Aborsi Tuban 081390298631 Obat Penggugur Kandungan Asli Tuban, Jual Obat Cytotec Gastrul Gynaecosid Tuban,Cara Menggugurkan Kandungan Di Tuban, Apotik Jual obat Telat Bulan Di Tuban, Toko Atau Apotik Jual Obat Pelancar Haid Di Tuban, 

images
![images](https://user-images.githubusercontent.com/66870870/84589156-f8a1df80-ae56-11ea-97e8-a5dbb0ad5afc.jpeg)


WEB: https://konsultasimedical.com

MENU:
Hubungi KamiApakah Anda terlanjur hamil? Anda belum siap menjadi seorang ibu? Kami bisa memberikan bantuan untuk Anda. Silahkan hubungi kami, konsultasikan gratis.

Kami konsultasimedical.com menjual cytotec asli kami jual di website resmi kami ini adalah obat cytotec misoprostol 200mcg yang di produksi oleh PFIZER yang berasal dari Amerika.

Bagi wanita atau pria yang ingin mencari obat aborsi sangat lah gampang untuk mendapatkanya disini, jika ada yang serius ingin order obat di kota lainya se ibu kota anda bisa langsung browsing menggunakan android anda untuk mencari
konsultasimedical.com
anda akan menemukan situs kami dan kami akan melayani sepenuh nya dari pemesanan sampai kami pandu proses pengguguran kandungan anda sampai tuntas dan bersih.Obat penggugur kandungan yang kami jual tidak memberikan resiko tinggi terhadap wanita yang ingin menggugurkan kandungan, bisa dibilang minim efek samping.

Keunggulan melakukan aborsi dengan menggunakan obat.

. Efektif tingkat keberhasilan mencapai 97%.
. Minim efek samping.
. Proses cepat.
. Tidak perlu melalukan tindakan berat yang menguras tenaga.
. Jaminan barang asli 100%.

Tidak melayani pembelian atau penjualan obat aborsi cytotec gastrul gynaecosid COD di tuban...!!!

**Comment by Muhimen123** [comment]
Seriously?! More spams!

**Comment by ludwiczakpawel** [comment]
I think we can close it now, since we now have "full-height"  editor now. Let me know if I'm wrong.
