### ISSUE TITLE
Move Oauth-related keys to SiteConfig

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#8697]
**_This is one specific issue, but can be a stand-in for a larger effort of moving a bunch of stuff out of ENV and into somewhere more easily modified._**

Currently we put the `GITHUB_KEY`, `TWITTER_KEY` etc. in `ENV`, but these are technically end-user config, so we should move them to `SiteConfig`.

Since Devise uses them in the `initializer` where I believe `SiteConfig` will not yet be ready, we'll have to work around that.

**Comment by citizen428** [comment]
So far the distinction between `SiteConfig` and environment variables was not strictly driven by whether or not something is end-user config, but also by where a value is needed. We just recently had to move a value over (see https://github.com/thepracticaldev/dev.to/pull/8246) for exactly this reason and the solution we came up with was showing it in the internal config, but pointing out that it needs to be set via the environment:

<img width="1078" alt="Screen Shot 2020-06-04 at 14 02 07" src="https://user-images.githubusercontent.com/47985/83726542-dbf2f400-a66d-11ea-905c-6d0dcfd38cf6.png">

I'm not saying there are no better solutions and we can't work around that, let's just make sure the workaround doesn't require keeping this value in sync between two different places.

**Comment by rhymes** [comment]
A side note: I'm a bit wary of having secrets in `SiteConfig` but I might be wrong about this obviously :D

**Comment by benhalpern** [comment]
I might be _wildly offbase_ here, but here are some thoughts to further this conversation about individual instance config in general:

We could really store some of this stuff _anywhere_....

This seems to get the job done if I want the GitHub Key to equal `<html+lang`

```ruby
  @github_key ||= HTTParty.get("https://forem.com").first(10)
  @github_secret ||= HTTParty.get("https://forem.com").last(10)
  config.omniauth :github, @github_key, @github_secret, scope: "user:email"
  config.omniauth :twitter, ApplicationConfig["TWITTER_KEY"], ApplicationConfig["TWITTER_SECRET"]
```

`SiteConfig` happens to not be available before initialization, but as pointed out above we could probably store this stuff _somewhere_, eh?

And if that _somewhere_ happens to be super secure and is its own simple app maybe that will work for our needs?

_Also, `SiteConfig` can be accessible anywhere if it's in `readonly` mode because that seems to take the value provided during boot and _not_ create a database row.

So this works...

```ruby
  field :github_key, type: :string, default: HTTParty.get("https://forem.com").first(10), readonly: true
  field :github_secret, type: :string, default: HTTParty.get("https://forem.com").last(10), readonly: true
```

And then you plop those in the `Devise.rb`, in fact that's the demo on their readme:

> Sometimes you may need to use Setting before Rails is initialized, for example config/devise.rb
```ruby
Devise.setup do |config|
  if Setting.omniauth_google_client_id.present?
    config.omniauth :google_oauth2, Setting.omniauth_google_client_id, Setting.omniauth_google_client_secret
  end
end
```

This doesn't solve the problem of not having to reboot for some of this because this stuff has to run through config as a basic first step, but at least we could store it in a secure remote location and let our users modify via a GUI (or CLI)

It probably technically necessary that any of this happen _on initialization_ as we mostly just have to modify the `Devise.omniauth_config` before it's used I'd think, and that's the case for most of this. But that's such a convention that we may want to think about it.

The general issue here is that a user won't be able to call @jdoss to make some of these changes.

**Comment by citizen428** [comment]
> And if that somewhere happens to be super secure and is its own simple app maybe that will work for our needs?

@jdoss, @mstruve, and I have been talking about adding [Vault](https://www.vaultproject.io/) for Forem, so maybe let's wait and see how that plays out? From what I gather your main concern is that changing certain values may require app re-initialization, which is good to keep in mind.

**Comment by mstruve** [comment]
I dont think we should be scared about needing to reinitialize the app for _some_ changes, I think that is something we can easily workaround for a small number of variables. I also think that those variables belong in the hands of users. Same way you hook up integrations with services like Datadog by entering secrets and API keys that is what users will need to do for Forem. Vault seems like an ideal spot since SiteConfig is a little finicky about the bootup stuff.

**Comment by mstruve** [comment]
ALSO this might be useful! https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#reloading

**Comment by benhalpern** [comment]
I think as long as there is good communication between everyone in this thread, I'm cool to gradually figure this out and not rush. @citizen428 if you and @jdoss can make something work for a while that sounds good.

Eventually it only makes sense that _users_ would modify these values through a GUI and there are probably not inherent reasons why the app needs to initialize. It's just the default Devise and other Rails gems give us.

But we're building the plane as we fly so we'll tackle this one thing at a time.

**Comment by rhymes** [comment]
I think we solved this by moving the secrets in the `SiteConfig` and initializing Devise at runtime

See #9899
