### ISSUE TITLE
Typeahead liquid tag dropdown in new editor

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#872]
**Is your feature request related to a problem? Please describe.**
As a user, it can be hard to remember what exactly the commands for liquid tags in the editor are. In the way I might use this feature in my code, I'd like to type `{% ` and get a list of options for autocomplete.

**Additional context**
The editor is built in Preact, and ideally this could be done without new dependencies, but if we need to use [preact-compat](https://github.com/developit/preact-compat), we could.

I believe the editor will need to be written as a content-editable div, and we'd listen for the typing etc.

Ultimately it should work similarly to how I use typeahead in VSCode etc. 🙂

This is what it might look like:
![](https://thepracticaldev.s3.amazonaws.com/i/kftuy3gk6rvt9p6tgl70.png)

**Comment by bigblind** [comment]
Would there be an endpoint where the client can ask the server for a list of liquid tags, or would the list on the front end be updated manually whenever a new tag is added?

**Comment by benhalpern** [comment]
@bigblind For the purpose of the dropdown we'd probably ship it from the server with the page since there are only about a dozen.

So something like `<div data-liquidtags="[github,glitch,link,etc]"></div>`

And then we'd `JSON.parse` it to start playing with it.

**Comment by theoutlander** [comment]
This is cool. I had made a similar request on the comment box thread (https://github.com/thepracticaldev/dev.to/issues/354). I could tackle this one after the @ mention auto-suggest feature.

In addition, these features will need to be ported over to the editor. Ideally, we should be able to reuse what I'm building, but first we will need to turn it into a reusable library.

**Comment by cmgorton** [comment]
Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
