### ISSUE TITLE
Code blocks display strangely in comment preview

### ISSUE THREAD

**Issue by kewbish** [forem/forem#8741]
**Describe the bug**
Codeblocks in article comment previews display with a black border around it.

**To Reproduce**
1. Go to feed
2. Scroll to article with comment previews
3. Find a comment with codeblock.
4. A black border shows around the code.

**Expected behavior**
The code displays without the black border.

**Screenshots**
![image](https://user-images.githubusercontent.com/45278276/84927880-58300300-b082-11ea-9e76-dae1e422d9df.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: v83

**Smartphone (please complete the following information):**

- Device: n/a
- OS: n/a
- Browser: n/a
- Version: n/a

**Additional context**
n/a

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Should be fixed now.
