### ISSUE TITLE
Podcast episodes not processing HTML

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#8757]
`processed_html` for recent podcast episodes is `nil`.... The `body` which is the raw content returned from the RSS, is present. So something is wrong with our pipeline.

Example...

https://dev.to/devdiscuss/s1-e6-little-known-productivity-tools-big-productivity-gains

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by michael-tharrington** [comment]
Seemingly related to this, a DEV user wrote in just recently to point out that the info in their podcast was not being processed. The show notes are not visible on their show, for example - https://dev.to/startupengineering/signalai-why-startups-with-academics-build-great-products.

_NOTE: They gave me permission to share this info._

**Comment by michael-tharrington** [comment]
I don't want to make the call here because I'm not a developer and could be wrong 😅, but @Eli-Schei I think you are correct that this might've been fixed. It does look like show notes are appearing now.

**Comment by cmgorton** [comment]
@Eli-Schei you are finding all the bugs that are no longer bugs.😄 Thanks for your investigative work here. 🕵️‍♀️ One of our engineers confirmed this is no longer a bug so we can officially call this smashed and close this issue 🐛
