### ISSUE TITLE
Features of saving: reading list

### ISSUE THREAD

**Issue by ezio1404** [forem/forem#8760]
**Is your feature request related to a problem? Please describe.**

It's time consuming if you save the post/content 1 by 1 within the list. You will click each post/content to save.
**Describe the solution you'd like**

- A separate button that can save a chaining list(E.g Playlist in youtube)
- can download a chaining list 

**Describe alternatives you've considered**

**Additional context**

**Comment by citizen428** [comment]
Just to clarify, you're talking about post series like this and would like to be able to add every post in the series to your reading list with a single click, correct?

<img width="534" alt="Screen Shot 2020-06-18 at 14 27 50" src="https://user-images.githubusercontent.com/47985/84990808-e504ba80-b16f-11ea-9e1c-861bd1a16b5e.png">

**Comment by ezio1404** [comment]
Yes Sir, Thank you for understanding my request issue.

>

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
