### ISSUE TITLE
"Subscribe" component state

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#8763]
**Describe the bug**

Sometimes when I go to a post, the "Subscribe" button above the comments does not reflect my current state. Even though I'm already subscribed to a discussion, the button still says "Subscribe". After I refresh, the button state is correct.

**To Reproduce**

1. Go to Notifications.
2. Click one of the notifications re post you're subscribed to.
3. Check the "Subscribe" button state

**Expected behavior**

Subscribe button to always reflect the actual state.

**Screenshots**

[Video](https://d.pr/v/9zJLD3).

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Browser: Chrome 83.0.x

---

Assigning @nickytonline because I know you're the best person to mention this to :)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
Is this still an issue @ludwiczakpawel ?

**Comment by ludwiczakpawel** [comment]
Nope, it does not seem to be an issue anymore. Closing.
