### ISSUE TITLE
Code blocks within block quotes are centered

### ISSUE THREAD

**Issue by wayofthepie** [forem/forem#8767]
**Describe the bug**
Code blocks within `blockquote`s are now centered. This was not the case before the latest UI update, and they look a bit odd.
![image](https://user-images.githubusercontent.com/1102174/85025364-352f4d00-b16f-11ea-945a-9af7cc9ce0c1.png)

Note too that the font size is different than code blocks outside a blockquote, it's a few pixels smaller. This was the case before the latest UI update, but should probably also be consistent across the page.
![image](https://user-images.githubusercontent.com/1102174/85025900-e59d5100-b16f-11ea-8fe0-d9f0c58a0abe.png)

**To Reproduce**

See [this simple example](https://dev.to/wayofthepie/quoted-code-blocks-561e-temp-slug-2354539?preview=aa0a7a80a9b2dd2fc0bf4ce32fdac7641939611c032da3e99a4604c61fe152be4417c01de507b01da86460cc007a65d7f7abba60a49afbcf6576f41b).

**Expected behavior**
Code in code blocks has consistent alignment, left aligned, anywhere in the page.

**Desktop (please complete the following information):**

- OS: Ubuntu 
- Browser: Firefox
- Version: 77.0.1

Thanks!

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Should be fixed now, I think.
