### ISSUE TITLE
Duplicated author information in posts

### ISSUE THREAD

**Issue by madarsbiss** [forem/forem#8777]
**Is your feature request related to a problem? Please describe.**
When user opens an article, the author info is duplicated (areas under the article and on the right side).

![aaa](https://user-images.githubusercontent.com/42511917/85066855-608a5a00-b1b8-11ea-94ab-0fc28ec28e22.gif)

**Describe the solution you'd like**
Bio is already displayed under the article and I don't think Work, Location, Education and Joined is crucial info.
I would use that right panel for 'More from user' and list the most popular/recent articles from the author, instead.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@madarsbiss We're currently in a big redesign, so this is a bit of a moving target. If I look at one of my articles now, it only shows location and joined date and a "More from ..." section.


<img width="356" alt="I_joined_the_DEV_team" src="https://user-images.githubusercontent.com/47985/85093349-3e272980-b216-11ea-8321-215ce65ea76a.png">

**Comment by madarsbiss** [comment]
@citizen428 that was my initial thought :) anyways, great to see DEV evolving :)
