### ISSUE TITLE
Leaving rating with podcast on is not visible

### ISSUE THREAD

**Issue by Donaatas** [forem/forem#879]
**Describe the bug**
If you turn on podcast on the website leaving a rating (ex: heart) is hidden under podcast player/

**To Reproduce**

1. Go to 'any thread/post with availability to listen it'
2. Click to 'play podcast'

**Expected behavior**
podcast player appears in bottom of the screen, and rating menu jumps on top (box beside box, not in the podcast player) of it slightly so it would be visible

**Screenshots**
https://imgur.com/a/NxFGp0M

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox Developer edition
- Version: 63.0b13 (64-bit)

**Comment by Zhao-Andy** [comment]
Hey @Donaatas, thanks for the heads up. My gut reaction is to stack either the reactions bar on top of the podcast player or vice versa. @benhalpern probably has some thoughts on the design though.

**Comment by Donaatas** [comment]
well, if it will be stacked - reactions should be always on top. Because podcast is like 20-60minute thing, and if you continue to browse the site to other post, you want to see the reaction bar (at least in my case) and to go to the bottom of the page (if you need to configure something in the podcast) it takes few seconds and the reaction bar disappears in that space.

**Comment by rhymes** [comment]
@jessleenyc now that the reaction bar has been moved to the left side, does this still apply?

**Comment by Zhao-Andy** [comment]
@rhymes that only happens in large screens. :)

**Comment by jessleenyc** [comment]
Maybe we can add a small button that minimizes/collapses the player to the left side?

**Comment by ludwiczakpawel** [comment]
I'm closing since this should no longer be an issue - we've redesigned the article page so the player should NOT overlap with actions bar.
