### ISSUE TITLE
Connect input should grow with content

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#8842]
We changed the input in `/connect` from multiple lines by default to one, but when text spans more than one line the content gets hidden.

![](https://im4.ezgif.com/tmp/ezgif-4-8d5f0829d41b.gif)

Expected behavior: Content grows, similar to how it does in the `Title` component (where we use `preact-textarea-autosize`

From that file:

```jsx
import Textarea from 'preact-textarea-autosize';

export const Title = ({ onChange, defaultValue, switchHelpContext }) => {
  return (
    <div data-testid="article-form__title" className="crayons-article-form__title">
      <Textarea
        className="crayons-textfield crayons-textfield--ghost fs-3xl s:fs-4xl l:fs-5xl fw-bold s:fw-heavy lh-tight"
        type="text"
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by adfaris** [comment]
Can I start working on this?

**Comment by rhymes** [comment]
@adfaris sure! Assigned you to the issue

**Comment by nickytonline** [comment]
@narender2031, does #9025 close this?

**Comment by citizen428** [comment]
@nickytonline I think you linked to the wrong issue. #10378 should indeed resolve this, so @adfaris please don't start working on this, it would be duplicated effort.

**Comment by narender2031** [comment]
@nickytonline Please close this.

**Comment by citizen428** [comment]
Closing now @narender2031
