### ISSUE TITLE
Change UX for marking a post as draft or published in the rich text editor

### ISSUE THREAD

**Issue by omenking** [forem/forem#8886]
**Is your feature request related to a problem? Please describe.**

I was debugging a different issue because since the new editor changes I was only ever to have one draft with the basic editor. I switched over to test the Rich Text editor which allowed me to have multiple drafts but what I discovered was a UX issue that caused me to publish a draft article.

You can see my mistake here:
https://dev.to/andrewbrown/rich-draft-3lgg

Due to the legacy editor or using the basic editor, I always assume my article is draft unless I changed them to be ready for publication. The Rich Text Editor just has a Draft and Publish button. 

**Describe the solution you'd like**

Instead of having two buttons "Draft" and "Publish" button. Have a checkbox that determines published, and have a save button. I think this is how most publishing tools work.  eg. wordpress

DEV is marketed as a forum, but the format of posts feels like a blog. With forums, I don't expect a draft button just a publish button buts it's hard for me change my perceptive since the history of forums and blogs and how DEV worked previously.

**Additional context**

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Veggier** [comment]
I will try to work it on this issue.

**Comment by rhymes** [comment]
@Veggier I've assigned you the issue, what do you propose?

cc @ludwiczakpawel @lisasy that might have suggestions

**Comment by ludwiczakpawel** [comment]
Sorry I don't quite understand the issue... So what we have right now is two buttons "Publish" and "Save as draft". This is  exactly how Wordpress, Reddit, Tumblr, Blogger and few other players handle it - I feel like this is kinda standard. So the primary CTA is to Publish something, and the secondary CTA is to optionally Save draft.. 

Could you maybe explain me more clearly what the issue was? I'm keen to learn more.

**Comment by Veggier** [comment]
I think that we can add a prop out confirmation to check is the user ready want to publish their Post. To avoid the misclick.

**Comment by ludwiczakpawel** [comment]
Lets not add it just for sake of having this. I'd really like to dig deeper into this problem and understand it better, especially why that was an issue in the first place and what was real cause of it. "Write a post" view is pretty crucial experience for DEV, making any changes there must have a sensible cause. For _publishing_ & _saving as draft_ actions we really are pretty in line with established standards among other platforms.
