### ISSUE TITLE
Improve visual legibility of `crayons-btn--ghost-warning'

### ISSUE THREAD

**Issue by lisasy** [forem/forem#8898]

**Comment by PrimeNoodles** [comment]
Hello I would like to work on this issue

**Comment by lisasy** [comment]
@PrimeNoodles hey there! when it comes to these color mods, they belong to our larger design system, and it's modifiable only by the DEV internal staff. however, we always welcome feedback :) thanks!

**Comment by PrimeNoodles** [comment]
oh okay, I see, I was just going to reduce the overall visuals by 10% for each color but feel free to work on it
