### ISSUE TITLE
Reading list badge doesn't disappear

### ISSUE THREAD

**Issue by 31piy** [forem/forem#8900]
**Describe the bug**

The **Reading list** navigation item on the left sidebar gets a badge when there is any new item added to it. After removing all the added items, the badge doesn't disappear.

**To Reproduce**

1. Ensure the **Reading list** is empty.
1. Add a new post to the reading list by clicking the **bookmark** icon in the reactions pane.
1. Go to home page by clicking on the app logo on the top left.
1. Observe that the **Reading list** navigation item has a badge with count 1.
1. Visit the reading list, open the containing post, and remove it from the reading list by clicking again on the **bookmark** icon in the reactions pane.
1. Go to home page by clicking on the app logo on the top left.
1. Observe that the **Reading list** navigation item still shows the badge with count 1.
1. Try removing the cache and refresh the page (hard refresh). The page still shows the badge.
1. In my case, I removed the post yesterday, but the badge is shown even today as well.

**Expected behavior**

The badge must disappear when the count of the reading list posts are 0.

**Screenshots**

![image](https://user-images.githubusercontent.com/3369637/85645481-7bc50000-b6b7-11ea-910d-26005f85f3d5.png)

**Desktop:**

- OS: macOS Catalina 10.15.5 (19F101)
- Browser: Microsoft Edge 
- Version: 83.0.478.54 (Official build) (64-bit)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by AlbertoPdRF** [comment]
I believe this one should be easy to fix, changing [this line](https://github.com/forem/forem/blob/master/app/assets/javascripts/initializers/initializeReadingListIcons.js#L94) to:

```javascript
document.getElementById('reading-list-count').innerHTML = newCount > 0 ? newCount : '';
```

I'm happy to submit a PR with the change!

**Comment by rhymes** [comment]
@AlbertoPdRF I've assigned you the issue
