### ISSUE TITLE
GitHub repositories in settings bug: status quo and explorations

### ISSUE THREAD

**Issue by rhymes** [forem/forem#8904]
This is mostly a summary of the status quo and and explorations as to why we're having issues with the feature "fetch repositories from GitHub to display them in your profile" reachable at https://dev.to/settings/integrations (it requires to be logged in with GitHub).

As of today 25th of June around 11am UTC+2 it's working, but it does so intermittently. It always works locally.

The odd thing is that it took 20 seconds to work (which is under the 30 seconds limit):

<img width="1783" alt="Screenshot 2020-06-25 at 11 09 29 AM" src="https://user-images.githubusercontent.com/146201/85691177-8f329400-b6d4-11ea-96ce-299cadd2d5b0.png">

We have had [the first report on May 27th](https://github.com/thepracticaldev/dev.to/issues/8076) with a user that was receiving 503 errors from our server.
We had confirmed that by opening the network tab in the development tools of the browser, the call timed out after a couple of minutes (Heroku has a hard timeout at 30 seconds IIRC) the browser was bailing out after receiving a 503. 

<img width="1785" alt="Screenshot_2020-06-05_at_11 55 56_AM" src="https://user-images.githubusercontent.com/146201/85689242-c1db8d00-b6d2-11ea-87d3-8143f3c186b2.png">

We have had additional reports [on May 28th](https://github.com/thepracticaldev/dev.to/issues/8104) and [on May 29th](https://github.com/thepracticaldev/dev.to/issues/8172). It also has happened multiple times at random since. A couple of days ago again at the latest.

Our Datadog instance labeled it as a timeout error

![Screenshot_2020-06-05_Trace_3929027_(env_production)_Datadog](https://user-images.githubusercontent.com/146201/85689423-e7689680-b6d2-11ea-9109-f1322e105568.png)
 
I since raised the timeout to increase the chances of receiving the real HTTP error from GitHub upstream but with no luck:

https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/services/github/oauth_client.rb#L126-L133

I also tried to debug it with 

```bash
curl -H "Fastly-Debug:1" -svo /dev/null --cookie "_Dev_Community_Session=YOUR_COOKIE_VALUE" https://dev.to/github_repos
```

as the browser, in the network tab, after the 503 error is finally received says `Timed out while waiting on cache-lcy19221-LCY`

but I can't find a meaningful clue in our Fastly configuration. It might have something to do with Fastly caching as it's the biggest difference between local and production configuration related to this matter but I can't prove it yet.

**Where to find the code**

1. https://dev.to/settings/integrations loads [packs/GithubRepos.jsx](https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/packs/githubRepos.jsx) which calls https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/javascript/githubRepos/githubRepos.jsx#L18

1. the server (or the edge?) is hit and https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/controllers/github_repos_controller.rb#L9-L11 comes into play

1. the `fetch_repositories_from_github` creates a Octokit client using the previously store user's `access_token` (we get it from our stored GitHub identity): 

https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/controllers/github_repos_controller.rb#L40-L43

https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/services/github/oauth_client.rb#L12-L15

https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/services/github/oauth_client.rb#L7-L10

https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/services/github/oauth_client.rb#L49-L53

When the server responds with the data, the data is then rendered and life goes on

* this is how Octokit/Faraday is configured:

https://github.com/thepracticaldev/dev.to/blob/ab4753079c3849730729256c22c774f25172d604/app/services/github/oauth_client.rb#L108-L123

I also debugged manually to make sure we're indeed using the user's own token an I confirmed it:

```ruby
[8] pry(#<GithubReposController>)> client.instance_variable_get("@target").inspect
=> "#<Octokit::Client:0x00007f8666e9f518 @access_token=\"************************************cff6\", @api_endpoint=\"https://api.github.com\", @auto_paginate=true, @bearer_token=nil, @client_id=nil, @client_secret=nil, @connection_options={:headers=>{:accept=>\"application/vnd.github.v3+json\", :user_agent=>\"Octokit Ruby Gem 4.18.0\"}, :request=>{:open_timeout=>5, :timeout=>5, :read_timeout=>30}}, @default_media_type=\"application/vnd.github.v3+json\", @login=nil, @management_console_endpoint=nil, @management_console_password=nil, @middleware=#<Faraday::RackBuilder:0x00007f8666e85258 @adapter=Faraday::Adapter::Patron, @handlers=[Faraday::HttpCache, Faraday::Request::Retry, Octokit::Middleware::FollowRedirects, Octokit::Response::RaiseError, Octokit::Response::FeedParser, Faraday::Response::Logger]>, @netrc=false, @netrc_file=\"/Users/rhymes/.netrc\", @per_page=nil, @password=nil, @proxy=nil, @ssl_verify_mode=1, @user_agent=\"Octokit Ruby Gem 4.18.0 (http://localhost:3000)\", @web_endpoint=\"https://github.com\">"
````

**Comment by VladimirMikulic** [comment]
@rhymes I am experiencing a similar issue. It just keeps loading and never loads. What are you fetching guys ;)

![infinite](https://user-images.githubusercontent.com/35997844/87850146-4a260a00-c8ee-11ea-8f7c-3df4d3b18753.png)

**Comment by ExpressGradient** [comment]
Hi, I'm still having the issue with fetching the github repos of the user under the integrations section of user settings. Thanks.

![image](https://user-images.githubusercontent.com/59659961/89812651-18573a80-db5e-11ea-9ab6-f7966cac4d02.png)

**Comment by shelbyspees** [comment]
Hey folks, I just noticed this in the dev.to Honeycomb data as well, I'm glad there's already an issue open. Here's the query result where I noticed it: https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/J7cL62KTkKd

Here's some relevant performance data from the past 24 hours (and [query results](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/cCNLa9kUMJt)):
![Honeycomb query results showing P50, P90, P95, and P99 of paths matching github_repos](https://user-images.githubusercontent.com/5217772/90608343-5506df80-e1b7-11ea-9e08-1f0363ad164f.png)

(Note that these links will only work for members of ThePracticalDev Honeycomb team.)

**Comment by rhymes** [comment]
As this seems to have been solved, I'm going to close this meta issue, we can regroup if this happens again. Thanks to everyone involved in the investigation!
