### ISSUE TITLE
Additional Admins in a  DEV Organization should be able to see article basic stats

### ISSUE THREAD

**Issue by omenking** [forem/forem#8920]
**Is your feature request related to a problem? Please describe.**

I have a DEV Organization that I manage. I added a few different admins, some to help edit draft content, others to view statistics. The Admin I added to view the statistics cannot see any articles. I don't know if this was a recent change since I think previously admins who did not account owner could see stats. 

**Describe the solution you'd like**

* Admins should be able to see articles and stats.
* You should be able to download a CSV of the stats
* You should be able to see who was the publisher of the article 
* You should be able to transfer ownership to another Admin if you made the DEV Organization on behalf of someone else

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I marked this as both bug and feature request because I believe it contains both...

**Comment by rhymes** [comment]
Hi @omenking, thanks for the request, would you mind splitting this up so we don't have both the bug report and the feature request under the same ticket? 

Thank you!

**Comment by omenking** [comment]
When a user has been invited to a DEV Organization and made an Admin if they have never created a post they will not see the dropdown to switch to another Organization. Also when attempting to create their first post, and I watched them do it, we had an obscure javascript so I had to switch them to the basic markdown editor. After that, the DEV Organization unlocked.

@rhymes please do me the favour of breaking these up into new tickets. Unforently I don't have much time to format tickets.

**Comment by michael-tharrington** [comment]
Hey y'all! (@rhymes & @omenking) 

I'm gonna hop in here and help break this thing up.

**Comment by cmgorton** [comment]
I believe this issue is resolved. I can see all of the analytics from each org I am an Admin of. If that is not the case let me know and I will re-open this.
