### ISSUE TITLE
Support the GoLang Playground as a liquid tag

### ISSUE THREAD

**Issue by ghostsquad** [forem/forem#8923]
I was wondering if there is anything on the roadmap to support the GoLang Playground as a liquid tag?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by eclectic-coding** [comment]
I would love to start working on this item @nickytonline

**Comment by rhymes** [comment]
@eclectic-coding you've been assigned to it :) thank you!

**Comment by rhymes** [comment]
As we review our integration with external services to be less DEV specific and more mindful of the diverse array of users in the Forem ecosystem, I went ahead and removed the `ready for dev` label in the meantime
