### ISSUE TITLE
#augeas tag is empty

### ISSUE THREAD

**Issue by raphink** [forem/forem#8937]
15 days ago, I tagged a post with the `augeas` tag.  However, the https://dev.to/t/augeas page does not list any posts.

**Comment by raphink** [comment]
Same for `cfgmgmt`, `puppetize` and probably many others

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Interesting!

I found the article https://dev.to//raphink/configuration-surgery-with-go-structure-tags-12a4 which clearly has the tag but as you noticed it doesn't appear in https://dev.to/t/augeas

**Comment by raphink** [comment]
I don't know if something was done. The article now appears in the list, but the total still says `0 Posts published`:

![image](https://user-images.githubusercontent.com/650430/85920109-449a4e80-b871-11ea-9fe5-d41d8c3ce57c.png)

**Comment by raphink** [comment]
I added the `puppetize` tag to https://dev.to/raphink/add-puppet-tag-142l yesterday and it doesn't appear on the `puppetize` tag page either.

**Comment by nickytonline** [comment]
This appears to still be an issue.

**Comment by cmgorton** [comment]
I can see the article tagged with `augeas`. I do not think this is an issue any longer. https://dev.to/t/augeas
