### ISSUE TITLE
Add /feed/latest to RSS feeds

### ISSUE THREAD

**Issue by todsac** [forem/forem#8940]
**Is your feature request related to a problem? Please describe.**

The only way to ensure you’re getting the latest articles right now is to increment the API

**Describe the solution you'd like**

https://dev.to/feed/latest

**Describe alternatives you've considered**

None

**Additional context**

See email thread from [https://pipedream.com](url) team

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ccozkan** [comment]
Hey :wave: Is this issue still available? I would like to work on this

**Comment by citizen428** [comment]
Teşekkür ederim for volunteering @ccozkan, it's all yours! 😃
