### ISSUE TITLE
Auto Scan Messages for Content Violating Code of Conduct

### ISSUE THREAD

**Issue by foxnic** [forem/forem#8949]
**Is your feature request related to a problem? Please describe.**

It's great that DEV has a clear code of conduct, and a mechanism for reporting violation, to help to ensure DEV is an inclusive community. Sometimes targets of harassment/other violations of code of conduct are reticent to report violations in case of harmful repercussions. For example, what if the person violating the code of conduct is a powerful influencer in the community?

**Describe the solution you'd like**

Make use of text mining techniques to scan posts, comments and direct messages for text that may potentially violate the code of conduct and use the information to proactively guard community members against harassment. For example, if the software finds a term that implies harassment in a direct message/comment, the author could be notified and reminded of the Code of Conduct. This would not rely on reporting by the target of harassment/code of conduct violations, it would be a gentle, kind way of helping potential perpetrators to modify their behaviour, and would not increase the workload of the platform moderators/administrators. 

Example:

- author writes "Are you single?" and clicks the button to send the message
- software finds that this potentially violates the Code of Conduct regarding harassment
- before sending the message the software displays a message to the message author to tell them that their message potentially violates the Code of Conduct, provides a link to the Code of Conduct and asks them to review it then review their message and edit it if required. 
- author can choose to ignore the message or can review the Code of Conduct, review their message, edit their message and try to send the updated message, or abandon the idea of sending the message

The potential target of harassment/violation of Code of Conduct is never impacted and the DEV community admin team doesn't have to do any additional work to protect the community.

**Describe alternatives you've considered**

The software could block the message from being sent / comment being posted if it contains potential violations of the Code of Conduct, but the algorithm to find potential violations would have to be very good and this is difficult to achieve.

**Additional context**

N/A

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Please not that I tagged this as `difficulty: hard` since false positives would be fairly disruptive to the publishing experience, so whatever solution one comes up with for this issue needs to be pretty airtight.

**Comment by citizen428** [comment]
@foxnic As a data science MSc, do you have any input re models you'd consider using for this as this looks like something that would require a somewhat sophisticated approach to be solved properly. I could see us achieve reasonable results with generating word vectors (embeddings like used in word2vec for example) on the corpus of manually moderated posts, but I have no idea if said corpus would be big/diverse enough.

**Comment by foxnic** [comment]
There's no single best model. It would require experimentation (which I would LOVE to do after I have finished my MSc project) with classifiers suitable for a classification task. Logistic Regression may be enough (and often is). The hard part of pre-modelling i.e. data analysis and pre-processing. 

TBH I think a simple keyword/phrase approach would be an easy starting point though. Perhaps a time-boxed trial of this feature with feedback from the community to use as input to deciding whether to keep it/try to improve it? We could even ask the community for examples of phrases they've seen in messages that they have felt violate the code of conduct and use those (along with some phrases extracted from messages that users have reported as violating the Code of Conduct) as a starting point, and perhaps update the list of phrases upon reviewing user reports of Code of Conduct violations? I wouldn't be surprised if there are some very common harassment phrases.

**Comment by foxnic** [comment]
I'd be happy to do some exploratory data analysis on anonymised text violating the code of conduct, identify any key phrases/patterns and write up a summary if that would help get us started? I would be reticent to commit to a particular deadline due to my MSc project work but I would aim to do it within a few days. How many instances of violations do you currently have?

**Comment by citizen428** [comment]
Thanks, @foxnic! I think we agree in principle that a proper solution to this will take time and be fairly hard. As you say in your original post:

> the algorithm to find potential violations would have to be very good and this is difficult to achieve

That's not to say we can't iterate from simpler solutions and any help you're willing to contribute to that effort would be appreciated.

> TBH I think a simple keyword/phrase approach would be an easy starting point though and needn't have a big impact on user experience provided the notification can be ignored and has links to the rationale behind it with examples.

I have had decent results in the past with phrase/keyword matching for simple classification tasks, so this could indeed work as long as we only display an informative message and don't outright stop people from posting. One of the main caveats here is that CoC violations are not necessarily simple classification tasks since context matters a lot. For example, "This sucks!" as a response to a post titled "I lost my job" is totally different from the same comment on an article called "Look what I built". 

I'll loop in @jessleenyc and @michael-tharrington (support) to see what they have to say on this issue.

**Comment by foxnic** [comment]
> I have had decent results in the past with phrase/keyword matching for simple classification tasks, so this could indeed work as long as we only display an informative message and don't outright stop people from posting. One of the main caveats here is that CoC violations are not necessarily simple classification tasks since context matters a lot. For example, "This sucks!" as a response to a post titled "I lost my job" is totally different from the same comment on an article called "Look what I built".

I'm currently trying to build a hate speech detection model which has the same issue with context and nuance. Texts containing key phrases and offensive words help with classification but can also hinder - e.g. if a journalist is reporting on a hate speech story its not hate speech in itself, even though the text contains a hate speech phrase. Also, some offensive words have been reclaimed by the people the words were initially intended to oppress. I'm investigating ways to try to combat these issues at the moment (e.g. synthetic data augmentation).

**Comment by citizen428** [comment]
This is very interesting @foxnic! I've worked on a project in the past where we used a similar approach (data augmentation and training over the combined set) but for a much more restricted domain with less nuance. Good luck with your MSc project and very much looking forward to any further input you can provide on this issue 😃

**Comment by michael-tharrington** [comment]
Hey y'all!

@foxnic this sounds really cool.

I like that your proposed solution is proactive without actually limiting folks' abilities. This way there are ways for folks to follow through with contextually permissible situations like y'all mentioned above:

> For example, "This sucks!" as a response to a post titled "I lost my job" is totally different from the same comment on an article called "Look what I built"

I also feel like hate speech detection tooling could be useful in a number of ways. We could use this same mechanism to flag potentially abusive content for admin/moderators to review.

Lots to dig into here! I'll make sure to discuss this one with the team.

**Comment by citizen428** [comment]
As further input: for one of my private projects I'm using [retext](https://github.com/retextjs/retext) with the [retext-profanities](https://github.com/retextjs/retext-profanities) and [retext-equality](https://github.com/retextjs/retext-equality) plugins. Since these are JS libraries we may be able to include them in the editor and flag (e.g. by underlining) certain things non-intrusively right away).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
