### ISSUE TITLE
shadow of crayons-notice class feels out-of-place in flat design

### ISSUE THREAD

**Issue by thorstenhirsch** [forem/forem#8969]
The design of dev.to has made huge progress, I really like it. One thing I just stumbled upon is the shadow of the crayons (like the red "Unpublished Post. This URL is public but secret, ..." box).

```
.crayons-notice--danger {
  background: var(--accent-danger-a10);
  border: 2px solid var(--accent-danger));
  box-shadow: 2px 2px 0 var(--accent-danger));
  color: var(--card-color);
  border-radius: var(--radius);
}
```

It seems out of place now. Please remove the 2px 2px shadow of the crayons-notice class. In the code I've seen that there's a mixin that takes care of setting the shadow: generate-box() with $level as the 1st argument. I'll provide a PR with the easiest solution: calling generate-box() with $level=0 when generating all crayons-notice boxes. However you might think of removing $level completely in generate-box(), as there seems to be no place in the new design anymore for boxes with shadow, I guess.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
