### ISSUE TITLE
Add manage series

### ISSUE THREAD

**Issue by khatibomar** [forem/forem#9008]
I recently start a series in dev.to I forget to add an Introduction to the series , So if I need to add it it will be in the last , while it should be in The top of the series list.

My solution is to create a drag and drop so we can manage series parts.
or Author add manual number to the start of every part of the series and they will get sorted based on those numbers.
Example : 
Part 1
Part 3
Part 2    

after sort : 
00 Part 1
01 Part 2
02 Part 3

![Capture](https://user-images.githubusercontent.com/35725554/86078379-d60cea80-ba42-11ea-9194-b19f73ad2956.PNG)

I need to add an #000 What is DevOps , but if I need to add it now it will be the last in the list.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
