### ISSUE TITLE
Reader Tag Insights (Dashboard Feature)

### ISSUE THREAD

**Issue by foxnic** [forem/forem#9012]
**Is your feature request related to a problem? Please describe.**

I'd like to know which tags are followed by the people who (a) read and (b) react to my posts so that I can better understand the interests of people who find my posts useful. For example, do most of the people who react to my posts follow the 'beginners' tag? Do most of the people who *read* my posts also follow the 'beginners' tag? What percentage follow the 'python' tag?

**Describe the solution you'd like**

For a particular post, and for all my posts as a whole, I'd like to be able to view statistics and data visualisations about the tags followed by users who (a) read (b) react to my posts. Similar to "Your Readers Interests" on Medium.

One way this could be implemented:

(i) **By POST**: I go to Dashboard > I click 'manage' on a post > I see a "Reader Insights" section which shows me a list of tags that are followed by the users who have read/reacted to **_this particular post_** and next to each tag I see the % of those readers/readers who reacted who follow that tag

(ii) **OVERALL** (User Level): I go to Dashboard > I see a "Reader Insights" section which shows me a list of tags that are followed by the users who have read/reacted to **any of my posts** and next to each tag I see the % of those readers/readers who reacted who follow that tag

Example:

**Tag,               % Readers,                % Readers Who Reacted**
beginner,      75 ,                            80
python,         100,                           100
tutorial,         50,                             25

A data visualisation (e.g. bar chart) could be displayed instead / as well so that its easy to see which is the key tag of interest to my readers.

**Describe alternatives you've considered**

A simpler, less informative version of this may be to show the most popular tag followed by my readers / people who react to my posts e.g. _"You are most popular amongst users who follow the **_beginners_** tag"_

A future extension to this feature that may be useful is insights about from where readers clicked on my post e.g. from within DEV / from Twitter / from a Google search

**Additional context**

Similar to the information available, by post, on Medium:

<img width="1200" alt="Screenshot 2020-06-30 at 07 03 07" src="https://user-images.githubusercontent.com/39113566/86089257-cc65a000-ba9f-11ea-9900-1ee1b0da35cf.png">

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Hey!
Features tend to be subjective and might spur some debate 😄. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it. Given Pawel's response and our current roadmap I am going to close this request here but again feel free to start a conversation in forem.dev around this issue! Thanks.
