### ISSUE TITLE
Make default of [Feed, Week, Month..] configurable

### ISSUE THREAD

**Issue by xerosanyam** [forem/forem#9045]
**Is your feature request related to a problem? Please describe.**
When I visit dev.to, I want to see what happened in the past week. I usually check dev.to once a week, hence If instead of Feed, week option is my default it would be better ux wise.
Reddit also allows such kind of functionality, where you choose whether you want hot/trending topic

**Describe the solution you'd like**
In settings, there can be an option to configure it

**Describe alternatives you've considered**

**Additional context**
Current option - Default
![image](https://user-images.githubusercontent.com/3167278/86205364-4c1a6a00-bb87-11ea-9af8-27c0efe15c63.png)

After I have update my setting(Should be like this)
![image](https://user-images.githubusercontent.com/3167278/86205409-681e0b80-bb87-11ea-8307-9981726eb9e6.png)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by thomasbnt** [comment]
I have as shortcut "https://dev.to/latest" and not "https://dev.to" because I prefer to look at the last posts and then after the most noticed ones. It doesn't bother on computer, but on phone or even on the application it's very slightly annoying. It's just a question of speed, nothing more.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
