### ISSUE TITLE
No option to Publish an RSS imported article

### ISSUE THREAD

**Issue by colbyfayock** [forem/forem#9055]
**Describe the bug**

After importing posts from my RSS feed, I'm unable to find a Publish button on those drafts.

The imported posts are marked as unpublished as a Draft in the UI.

When visiting the Edit page, I notice that the Publish button shows on first load, but when the Javascript kicks in (im guessing) it changes it to Save. Just for fun I tried turning off Javascript and clicking Publish but it doesn't do anything, guessing it's JS required there.

![Screen Capture on 2020-07-01 at 10-03-36](https://user-images.githubusercontent.com/1045274/86263343-1b3e3300-bb8f-11ea-894e-3d7402b34ea4.gif)

I'm on Chrome Version 83.0.4103.116 (Official Build) (64-bit)

I also tried opening this up in Firefox to make sure it wasn't a browser or extension issue, but it's the same thing

**To Reproduce**

1. Go to dashboard
2. Select draft post
3. No Publish button available

**Expected behavior**

Expect to be able to publish the draft

**Screenshots**

![Screen Capture on 2020-07-01 at 10-03-36](https://user-images.githubusercontent.com/1045274/86263343-1b3e3300-bb8f-11ea-894e-3d7402b34ea4.gif)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version:  83.0.4103.116 (Official Build) (64-bit)

**Additional context**

If it's helpful, here's the post: https://dev.to/colbyfayock/how-to-use-pure-css-to-create-a-beautiful-loading-animation-for-your-app-je4-temp-slug-1885368?preview=e591dc13a6ceb94a5d174a9bda3212dfa1671b79f7dbebdc8331032c627ba470d26ad74b670bdfe4b81109259fe6084af10e297d6c47e31c2a4dd51c

However, it seems like it's not the only imported one having the issue

RSS I imported from:
https://www.freecodecamp.org/news/author/colbyfayock/feed/

**Comment by colbyfayock** [comment]
As soon as I mentioned this I saw someone note in their own case the frontmatter had `published: false` which I totally didn't notice.

I'll leave this open in case that's something to consider improving the experience on? Maybe even just a note, I would imagine it could confuse others too 🤷

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
I think this might be an issue with imported articles being v1 editor and possibly a user has the v2 editor running? https://github.com/forem/forem/blob/4786cbddfc1c59cc0b63405ebc5ca9f2001f54d0/app/javascript/article-form/components/EditorActions.jsx#L67-L68

![image](https://user-images.githubusercontent.com/833231/91604951-9f1d5d00-e93d-11ea-8f78-19929fbb4fae.png)

**Comment by hvitis** [comment]
+1

**Comment by cmgorton** [comment]
Hey @colbyfayock is this still an issue for you? One of our engineers tested this out and said it seems that it's more related to the fact that RSS posts use v1 and for that we do not have a publish button. We have the published: false like you mentioned in this issue.

**Comment by colbyfayock** [comment]
hey @cmgorton seems like it's still happening but it's what's expected, it just would be a little more straightforward from a UX perspective for those not expecting it in there (like me before I figured it out :) )

**Comment by rhymes** [comment]
@colbyfayock to be clear, are you still experience the "disappearance" of the buttons lik in the GIF? Because that shouldn't happen.

The "basic editor" should look like this:

![Screenshot_2021-02-25 New Post - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/109130919-8f4ace00-7752-11eb-8858-e32df39b44e7.png)

The "rich editor" should look like this:

![Screenshot_2021-02-25 New Post - DEV Community 👩‍💻👨‍💻(1)](https://user-images.githubusercontent.com/146201/109130999-a2f63480-7752-11eb-9828-f4f706e4b2ec.png)

**Comment by colbyfayock** [comment]
ah no, that issue appears to be fixed now. thanks
