### ISSUE TITLE
Pro Analytics should be downloadable in CSV form

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#9067]
**Is your feature request related to a problem? Please describe.**

Not exactly, but at least on organization has requested to have their stats downloadable in CSV form. 

I imagine this would be useful for other orgs too and individuals who want to be able to pull this info into analytics systems to analyze. 

**Describe the solution you'd like**

It'd be awesome to be able to submit a data request for stats in CSV form similar to how you can export your content from DEV (see the bottom of this page - https://dev.to/settings/misc). I'd imagine this request would appear on the page with the report - https://dev.to/dashboard/pro, but perhaps this could appear somewhere else.

Ideally, you could pull this data for your own personal account. But also if you were an admin for an org, you could pull org analytics.

**Additional context**

This request originally came from [this multipart issue](https://github.com/thepracticaldev/dev.to/issues/8920).

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
