### ISSUE TITLE
Feature to enable users and organisations transfer credits to each other

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#9075]
**Is your feature request related to a problem? Please describe.**

For our use case of DEV's platform, it would be essential for users/organisations to have the ability to transfer credits to each other, as some of the services being rendered require joint payment. Additionally, it would support our marketing strategy of having users sponsor other users onto the platform.

**Describe the solution you'd like**

A credits transfer feature that lets you pick a user and organisation to send credits to. 

Best situation would be for users to be able transfer credits from their credits account, and purchase credits into another user/organisation's account. Either approach also works.

**Describe alternatives you've considered**

A different approach to joint payment; one user makes payment, the other users are notified to complete their own payments.

**Additional context**

To reiterate, the primary motivation behind the feature request is to enable joint payment for services. The secondary motivation is to enable users sponsor other users' activities in our use case. This ability to sponsor other users onto the platform is something I think could also benefit DEV.to directly.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
