### ISSUE TITLE
Add XState Viz embed liquid tag

### ISSUE THREAD

**Issue by kellyjandrews** [forem/forem#9076]
**Is your feature request related to a problem? Please describe.**

I recently published an article on XState. There is a visualization tool here - https://xstate.js.org/viz 
Unfortunately, it requires an iFrame, which is not currently possible. 

**Describe the solution you'd like**

I would say adding `{% xstate [ID] %} would solve it. 

**Describe alternatives you've considered**

I've looked for a generic iframe tag, but not sure that would be the right solution, as it would open the door to all sorts of things.

**Comment by kellyjandrews** [comment]
I have no problem making a PR for this, and can start right away if it's approved :)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by kellyjandrews** [comment]
Thanks @rhymes - I'll claim this once `ready for dev` is applied. Thanks!

**Comment by maestromac** [comment]
@kellyjandrews this is approved!

**Comment by kellyjandrews** [comment]
I'll get it going tonight - thanks!

**Comment by nickytonline** [comment]
@kellyjandrews, I've assigned this to you. Thanks for contributing!

**Comment by kellyjandrews** [comment]
@rhymes @maestromac @nickytonline  

I tried the OSS team link above but got a 404 response. 

I am currently using the container installation guide, and I have things working so far.  I created a new github oauth app to create my user and write the new tag to verify it works as well.

However, I am getting a lot of 404 errors with the javascript chunks - 

```
GET http://localhost:3000/packs/js/vendor-9dd3f11d90bd76809942.chunk.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/packs/js/Search-d98cfeb3094ddbcee915.chunk.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/packs/js/runtime~onboardingRedirectCheck-ccde4e0aede50224f862.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/packs/js/1-2e718901f9ccb73f2700.chunk.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/packs/js/onboardingRedirectCheck-e7a5f9628806a6995ef2.chunk.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/packs/js/contentDisplayPolicy-dc03917475fc4a57885a.chunk.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/packs/js/vendor-9dd3f11d90bd76809942.chunk.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/packs/js/homePage-ce7ce77b16ebbddc49c1.chunk.js net::ERR_ABORTED 404 (Not Found)
```

What am I missing to get this working?

**Comment by kellyjandrews** [comment]
Ok - I have things written, but just cannot get anything to run in my environment.  Tried to commit, and husky fails every time. Installed the bundle, but still isn't quite functional for me.  Is using containers less than ideal here, and I need to completely build out my environment?

**Comment by nickytonline** [comment]
I haven't worked in the docker setup (sounds like I need to spin it up to see what's up), so I'm not sure why you're getting all those 404s on the code split chunks that webpack generates. If you run `bin/webpack` does it run successfully?

Also, what errors are husky giving you?

**Comment by kellyjandrews** [comment]
The install indicated to run `bin/container-setup` and it appears as though the `webpacker` service is running webpack, but I can't be sure.  The logs produce a lot of noise at the present.

```
✖ bundle exec rubocop --require rubocop-rspec --safe-auto-correct:
bundler: command not found: rubocop
Install missing gem executables with `bundle install`

✖ bundle exec erblint --autocorrect:
bundler: command not found: erblint
Install missing gem executables with `bundle install`
husky > pre-commit hook failed (add --no-verify to bypass)
```

I would assume this is from not having the local environment working.  Hopefully we can find a way around it with containers 🤷‍♂️

**Comment by rhymes** [comment]
Hi @kellyjandrews, as this conversation has been dormant for a while and as we review our integration with external services to be less DEV specific and more mindful of the diverse array of users in the Forem ecosystem, I went ahead and removed the `ready for dev` label in the meantime

**Comment by kellyjandrews** [comment]
@rhymes sorry for never getting to this - I could not get the local instance running.

**Comment by rhymes** [comment]
@kellyjandrews no worries, we're working on improvements to our containerized setup to help onboarding

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
