### ISSUE TITLE
Company Size field validation

### ISSUE THREAD

**Issue by sebdeckers** [forem/forem#910]
**Describe the bug**

Company Size org meta field is not intuitive.

- Only accepts unsigned integer.

- Maximum length is 64 characters.

- Label should be "Team Size" or "Organization Size" since not every org is a company.

**To Reproduce**

1. Go to Organization -> Company Size
2. Enter non-numeric value, e.g. "Small but feisty"
3. Submit

**Expected behavior**

It should either accept text, or have smaller max length and UI hint of only accepting integers.

**Screenshots**

![screen shot 2018-10-15 at 11 09 17 am](https://user-images.githubusercontent.com/78718/46928148-ae59d100-d06b-11e8-84c5-b110b2a7e46a.png)

![screen shot 2018-10-15 at 11 09 29 am](https://user-images.githubusercontent.com/78718/46928141-a9951d00-d06b-11e8-8788-d4aa1debc8e7.png)

**Desktop (please complete the following information):**

- OS: macOS High Sierra
- Browser: Safari
- Version: 12.0

**Additional context**

V2 features enabled in profile.

Organization: https://dev.to/organizations/204

**Comment by aalises** [comment]
I can take this one if you let me. I don't quite know which would be the best way to validate this. Allowing a string seems a little bit over the top.

Maybe allowing an integer but also a range delimited with a hyphen **-**, such as **25-70** people. A UI hint would also be nice, but specifying it in the placeholder  

`'Limit of 64 integer characters or hyphenated range (e.g 45 or 30-50)` 

maybe is overloading it?

**Comment by sebdeckers** [comment]
An integer limit of 64 digits is ridiculous.

Personally I prefer removing the integer restriction. Free text field to allow creativity/expression.
