### ISSUE TITLE
No notification for a direct message

### ISSUE THREAD

**Issue by negue** [forem/forem#9114]
**Describe the bug**

While chatting with people by direct messages, I don't receive any email (which is listed only for inactive, I don't know what the period of that is) and also no badge at the chat icon (in header) , do these maybe work only together?

For example even on a full refresh I dont get any badge there, but when I open the messages, there is a new message that I didn't know I received. 

This happens already multiple times.

But its not broken all the time, like I had sometimes a badge there to see that I have 1 new message. 

**To Reproduce**

Direct message someone, wait for a response and you may or may not have a notification badge at the chat icon.

**Expected behavior**

To see the badge all the time.

**Screenshots**

**Desktop (please complete the following information):**

- OS:  Mac
- Browser:  Vivaldi
- Version:   3.1.1929.40 (Stable channel) (64-bit)

- OS:  Windows
- Browser:  Firefox
- Version:  (probably the newest version, too, will update when im at this computer)

**Smartphone (please complete the following information):**

- Device: OnePlus 3T
- OS: Android
- Browser: Chrome with `Add to Homescreen`
- Version: 81.0.4044

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @negue, could you fill in the details about your browser and operating system? Especially your browser. Do you notice any issues in the developer console?

Thank you!

**Comment by negue** [comment]
Updated the Browsers, but for the developer console, no issues / errors listed :(

**Comment by rhymes** [comment]
@negue does this happen also on your desktop browsers? trying to understand if it's related to your user or the device

**Comment by negue** [comment]
Every browser , every device, I had like once or twice a badge at the chat icon, all other times there was no badge.

Today again, I just open dev.to , no badge / notification (by mail) availabe, when I opened direct message, I had 2 new messages.

**Comment by negue** [comment]
Just happened, on my phone, I received a badge on the chat icon when I pulled to refresh.

So I guess just opening and going through articles wont trigger an "is there a new message"-api call ?

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
