### ISSUE TITLE
Remove or pause listing

### ISSUE THREAD

**Issue by kbariotis** [forem/forem#9117]
**Is your feature request related to a problem? Please describe.**

As a listing is primarily made for promotion, I think it would be valuable to be able to remove or pause a listing to limit that promotion.

**Describe the solution you'd like**

Remove or pause a listing at will. Resume at any time.

**Describe alternatives you've considered**

Expiry date works great if you know the duration you want upfront. But not if you don't.

Thank you, great work!

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I think removing the listing here is enough, pausing might be a tricky concept

**Comment by shilpi230** [comment]
@rhymes I see we already have expire date and deleting feature for listings. Is it something else ? Thanks!

**Comment by citizen428** [comment]
@shilpi230 Listings are valid for a certain amount of time, which can be extended ("bumped") by spending more credits. That's the expiry date. This whole logic is also what makes introducing the concept of pausing a listing somewhat unfeasible with the current implementation. And you're right about deletion, listings already can be removed by either their authors or an admin.

**Comment by shilpi230** [comment]
Thanks! @citizen428 so, where are we with this request then?

**Comment by rhymes** [comment]
I'm going to close this then as listings can already be removed by the author and we don't want to implement "pause" 

Thanks @shilpi230
