### ISSUE TITLE
Automatically save drafts in comment responses

### ISSUE THREAD

**Issue by waynevanson** [forem/forem#9121]
**Is your feature request related to a problem? Please describe.**

I might write a lengthy response on a comment in a post.
If i accidentally press back on my phone or in the browser, the response  i was writing is now gone.
I would now have to rewrite this.

**Describe the solution you'd like**

I feel like storing the values on the user's client in localStorage would be sufficient.

**Describe alternatives you've considered**

+ Local storage. 
+ In database. It could be kept for a short amount of time like 4 days before it's deleted.
+ How does GitHub handle it in issue responses? Their implementation feels transparent.

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
