### ISSUE TITLE
Documentation for Production

### ISSUE THREAD

**Issue by akhil-naidu** [forem/forem#9154]
> Is there any documentation on production?

I would like to have my own production environment, and at least write one post in it. 

### Why I am eager to have a production instance?

1. I have a working development instance.
2. I don't know rails to check in between the code.
3. I like dev.to, it is a good looking platform.
4. It will motivate me to invest more time on dev opensource to replace my ghost blog -(It cost me a lot, 79$ per month)
5. Yes, that price, I mention above was high to me, I am a graduating student who earns nothing, classic Indian :p

### What I would like to know?

1. Is it possible to have a production instance of my own, without having the expert knowledge on ruby
2. If (1) is yes, what are the pre-requisites I need to gather, other than filling up the Envfile
3. If anything else, mention them, I knew nothing more than this.

Also, as I already have a working development instance, is there a way to convert it into a production environment?

**My instance info:**

- Ubuntu 20.04
- VM hosted at Vultr.com
-  4GB RAM, 80GB DISK

> I am willing to provide more information if required.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by wassim-elbhm** [comment]
You have done well!

**Comment by akhil-naidu** [comment]
People still wait for this.
https://github.com/forem/forem/issues/12671

**Comment by citizen428** [comment]
@akhil-naidu Would you mind if we close this issue in favor of the one you just linked? It was opened by our Head of Engineering and will hopefully be picked up in the not too distant future.

**Comment by cmgorton** [comment]
I think we should close this in favor of #12671 and I will add the potential RFC label to it as well to get more visibility on it. Thanks for opening this in the first place Akhil.
