### ISSUE TITLE
[New Instance] can't create a post or write article

### ISSUE THREAD

**Issue by akhil-naidu** [forem/forem#9160]
I have a working instance but I was not able to create or write a post.

Url of working instance: http://dev.leewardslope.com/
you can log in with  Github or Twitter, but unable to create an article.

I am not sure what is happening with my instance, I am ready to provide any information if someone can guide me to make a working instance.

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by kirananto** [comment]
I am also having similar issues #9465  
I think it might be due to the pack/js/* assets not being loaded.

**Comment by citizen428** [comment]
@akhil-naidu If I remember correctly, you're running this on Heroku. Can you please do `heroku logs --tail`, try to create a comment and post the error message (if any) here?
