### ISSUE TITLE
Editing seems completely broken now.

### ISSUE THREAD

**Issue by cfjedimaster** [forem/forem#9165]
**Describe the bug**
I went to my dashboard, clicked to edit an article, and got this:

![image](https://user-images.githubusercontent.com/393660/86613770-a7799d00-bf77-11ea-87f6-16d139f7d5b2.png)

This is an existing post with content, but only the top two lines are shown. If I use my keyboard and click down a few times, I can "scroll" in that area, but only two lines are shown.

- OS: Windows
- Browser: Edge
- Version:  83.0.478.58 (Official build) (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @cfjedimaster, do you have any errors in the developer tools's console?

**Comment by nickytonline** [comment]
Also, is this on the old Edge or the new Edge (Chromium) @cfjedimaster ?

**Comment by rhymes** [comment]
@nickytonline it's the new one, Edge pre Chromium goes up til 44. Edge Chromium follows Blink's numbers and it's currently at 83

**Comment by cfjedimaster** [comment]
It seems better. I noticed the list of articles looked a bit weird. Now when I reload on the list it looks back to normal. (I didn't think it was a bug, just oddly designed. ;) As for editing an article, it seems perfect now. I'm at work on a VPN and it's possible it was just a network snafu. I did reload a few times before I filed the report though. :)

**Comment by nickytonline** [comment]
@cfjedimaster, it could be a server side caching issue . We cache partial HTML and in some cases, the cache might be referencing old JS files which are cached in the browser causing weird behaviour. Only until that part of the cache is invalidated does the new *.js file get pulled down. That’s my hunch. Thoughts @rhymes ?
