### ISSUE TITLE
Users can't login b/c of error: "Validation failed: Employer url is not a valid URL"

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#9184]
**Describe the bug**

A few users have written in because they can't log onto DEV and are receiving the error message:

"Something went wrong: Log in error: Validation failed: Employer url is not a valid URL
Please try again below, or contact yo@dev.to if this persists."

This appears to happen when there's a typo in the user's website URL.

**To Reproduce**

I'm unsure exactly how to reproduce this one. When I try to pop in an invalid URL into my test account's profile, I receive the error message:

_1 error prohibited your profile from being saved:
Website url is not a valid URL_

![Image 2020-07-07 at 11 22 20 AM](https://user-images.githubusercontent.com/16007075/86803630-2b995680-c044-11ea-8a89-5b66e2715025.png)

**Expected behavior**

A typo in the user's website URL should not prevent the user from logging in.

**Comment by Veggier** [comment]
I will work on this issue

**Comment by Zhao-Andy** [comment]
@Veggier thanks for wanting to work on this! We've tagged this with `Forem team` though because it's an issue in our database records, and needs to be resolved manually there.

**Comment by akourtis98** [comment]
I have the same problem too. I just contacted yo@dev.to and now I'm waiting for a response. Is there any other way to solve it?

**Comment by michael-tharrington** [comment]
@akourtis98 thanks for the heads up! I can confirm that we received your email and are looking into it. I'll hit you back when we have a fix in place.

If I'm not mistaken, the message you received was just slight different correct?

_Validation failed: **Website** url is not a valid URL_ rather than _Validation failed: **Employer** url is not a valid URL_ ... seems like it's pretty much the same issue, but just a different endpoint.

**Comment by sabarish98** [comment]
Hey folks, I too received this validation error, while trying to update my employer URL field under profile settings. URL is accurate though.
Now I'm unable to change the existing value given previously as well. 
 The error message :

`1 error prohibited your profile from being saved:
  Employer url is not a valid URL`

**Comment by antonrhein** [comment]
I am receiving this error too, when trying to update the URL to my personal website. Furthermore, it doesn't seem to be possible to "empty" this field. There is the same error `Website url is not a valid URL` ...

**Comment by hamzashahab1610** [comment]
I have the same problem too. I just contacted yo@dev.to I can not login to my dev.to account now.

**Comment by hamzashahab1610** [comment]
Can you guys please confirm if you have received my mail?

**Comment by Zhao-Andy** [comment]
Hi all, this should be resolved. Let us know if you have this issue again!
