### ISSUE TITLE
Basic markdown editor removes cover_image 

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#9193]
**Describe the bug**

When creating an article in the v1 basic markdown editor, you can add an optional `cover_image` and save the article (without necessarily publishing it). However, if you return to that same article at a later date and view it in the editor, the `cover_image` seems to be overwritten/disappears.

**To Reproduce**

1. Ensure you're using the v1 markdown editor and create an article with a title and a cover image.
2. Save the article, and navigate away from it, without publishing it.
3. Return to that same article and click on the `Click to edit` link.
4. You will see the `cover_image` appear momentarily in the markdown title, only the suddenly disappear again. Try refreshing, and you'll see this same intermediary flash of the `cover_image`'s value rendering in the markdown, and then disappearing again 😢 

![2020-07-07 15 57 20](https://user-images.githubusercontent.com/6921610/86853149-d1f85280-c06a-11ea-908a-67690c57c952.gif)

**Expected behavior**

I'd expect the `cover_image` to render in the markdown if it exists on the article.  You can see in the gif above how I refresh the page multiple times but the `cover_image` continues to disappear.

**Screenshots**
I suspect there's a JS bug here, since the article _does_ have the cover image on it from what I can tell. It doesn't appear in the markdown:
<img width="1318" alt="Screen Shot 2020-07-07 at 4 04 51 PM" src="https://user-images.githubusercontent.com/6921610/86853679-d4a77780-c06b-11ea-9f5f-62f504b1d4f0.png">

...but it _does_ render in the preview:
<img width="1318" alt="Screen Shot 2020-07-07 at 4 04 43 PM" src="https://user-images.githubusercontent.com/6921610/86853682-d7a26800-c06b-11ea-8c8e-36711fefb200.png">

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.5
- Browser: Chrome
- Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by vaidehijoshi** [comment]
Ok, I think I've narrowed down where this happens in the `articleForm` component, for anyone who picks this up: it looks like `previousContent.bodyMarkdown` is [eventually](https://github.com/thepracticaldev/dev.to/blob/30bfe1adfddf0a23d741e4ea3ba5fa90e6c8b5bd/app/javascript/article-form/articleForm.jsx#L78) [overriding](https://github.com/thepracticaldev/dev.to/blob/30bfe1adfddf0a23d741e4ea3ba5fa90e6c8b5bd/app/javascript/article-form/articleForm.jsx#L107) the `article.body_markdown`, which contains [the original markdown](https://github.com/thepracticaldev/dev.to/blob/30bfe1adfddf0a23d741e4ea3ba5fa90e6c8b5bd/app/javascript/article-form/articleForm.jsx#L91).

Another issue to note here is that the `mainImage` is correct and seems to always exist...but the `bodyMarkdown` doesn't always have the `cover_image` in the markdown, so the divergence between `cover_image` and `mainImage` seem to be another issue here.


I'm not sure what is the best fix for this, since I don't have the full context for why we check the [previous content and local storage](https://github.com/thepracticaldev/dev.to/blob/30bfe1adfddf0a23d741e4ea3ba5fa90e6c8b5bd/app/javascript/article-form/articleForm.jsx#L73) when deciding what the markdown and cover image should be. Maybe someone on @thepracticaldev/hells-bells or @nickytonline knows what is the best approach here...

**Comment by nickytonline** [comment]
@vaidehijoshi, we check local storage because there is a feature that was implemented that retains your most recent changes in local storage. If the date of what was stored in local storage is newer than the last saved date of am article, it will load instead of the original content that is in the article object. Maybe there is a scenario where in the v1 editor where the local storage feature makes things go wonky.

**Comment by rhymes** [comment]
cc @maestromac on this as well

**Comment by nickytonline** [comment]
@vaidehijoshi, I've tried this locally and with the given steps, I am unable to reproduce the error. Is this still an issue for you?

**Comment by eclectic-coding** [comment]
@nickytonline and @vaidehijoshi , I have been thinking about this issue today. I am wondering if the recent #9285 `local_date` helper as it was integrated had the residual effect of fixing this open issue. With the time stamp in the localstorage object this might be hypothetically possible. 
Just pondering.

**Comment by vaidehijoshi** [comment]
@nickytonline @eclectic-coding Just catching up on this now! Looks like this issue no longer happens! I am 99% sure that since the design of the editor changed significantly since I first logged this problem, something fixed it inadvertently along the way. I'll close the issue out :)
