### ISSUE TITLE
Base Reading Font not working for some options.

### ISSUE THREAD

**Issue by dante-calderon** [forem/forem#9194]
**Describe the bug**

Fonts `serif` and `open dyslexic` for **Basic Reading Font** configuration not working.

**To Reproduce**

1.- Go to [UX Setting](https://dev.to/settings/ux)
2.- In  **Basic Reading Font** section and select  `serif` or `open dyslexic` option.
3.- Reload the page and go to one post.
4.- The selected font is not applied.

**Expected behavior**

Should use the selected font.

**Screenshots**

> My configuration
![image](https://user-images.githubusercontent.com/63823505/86857902-27415d80-c085-11ea-91f3-a6ac75622a56.png)

> `serif` font is not applied
![image](https://user-images.githubusercontent.com/63823505/86858200-d67e3480-c085-11ea-810e-c1023af7f265.png)

**Desktop (please complete the following information):**

- OS: Tested on Windows 10 and Ubuntu 20
- Browser: Google Chrome
- Version: Version 83.0.4103.116 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser: 
- Version:

**Additional context**

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rehanGH** [comment]
Hi @rhymes can I be assigned to this issue?

**Comment by rhymes** [comment]
@rehanGH done! :D

**Comment by cmgorton** [comment]
This no longer appears to be an issue. I am going to close this but please let me know if you still experience this bug and we can reopen it. Thank you.
