### ISSUE TITLE
Automatically add enviroment details at bug reports (feature request for github reporting)

### ISSUE THREAD

**Issue by ioana-chiorean** [forem/forem#9199]
**Is your feature request related to a problem? Please describe.**
While logging bugs, there is a request for environment details ( os, browser etc) which can be populated by default with the user agent ones. I do understand some people will manipulate for testing purposes that data but they will be able to correct it if needed. 

**Describe the solution you'd like**
Auto import of this details will safe time and make it more consistent between tickets (will be able to label them easier for ex) 
(firefox browser will be nightly, mozilla, fx etc as users will be using it) 

**Describe alternatives you've considered**
- none needed

**Additional context**
- I've used this while reporting bugs for webcompat.org and i find it useful.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Great idea @ioana-chiorean, but is it technically feasible? A few things:

1. The reporting browser might not be the one they encountered the bug with
1. I don't think people want their full user agent to be automatically filled in
1. Does GitHub even support this?

**Comment by ioana-chiorean** [comment]
Hey @rhymes we are using something similar here https://webcompat.com/issues/new 
<img width="1095" alt="Screen Shot 2020-07-08 at 14 26 58" src="https://user-images.githubusercontent.com/1391451/86913373-3d9ff580-c127-11ea-8a35-42967d4ce55e.png">

Source code (it is open source too) 
https://github.com/webcompat/webcompat.com/blob/fbaba42888d046e109008a56a18c41f7ba5f90a4/webcompat/form.py 
they do create a different form but as it is based on github i think it could be added here too.

**Comment by rhymes** [comment]
@ioana-chiorean I'm still not sure how this can fit in the [pull request template](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) workflow in GitHub though :-(
