### ISSUE TITLE
Heroku deploy; NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by Emaah** [forem/forem#9206]
***Hello Dev Community***,

I decided to install the Dev project on my computer locally for learning the stacks and manipulating it. But installation was not successful (many errors) and also on gitpod it did not work truly for me.

I tried a more real scenario, Heroku. Deploying on Heroku is quite straightforward, but I got into some problems:

**1) First error was related to timber api:**

```
Running: rake assets:precompile
rake aborted!
ArgumentError: The api_key parameter cannot be blank
/tmp/build_2974408f22f12294894b0b13045df22a/vendor/bundle/ruby/2.7.0/gems/timber-3.0.1/lib/timber/log_devices/http.rb:82:in `initialize'
/tmp/build_2974408f22f12294894b0b13045df22a/config/environments/production.rb:112:in `new'
```

I commented some lines in [production.rb](https://github.com/thepracticaldev/dev.to/blob/master/config/environments/production.rb) file (line [111 ](https://github.com/thepracticaldev/dev.to/blob/master/config/environments/production.rb#L111)to [115](https://github.com/thepracticaldev/dev.to/blob/master/config/environments/production.rb#L115)) related to timber configuration, and the error went away ... 

**2) Second error is:**

```
Running: rake assets:precompile
rake aborted!
NoMethodError: undefined method `+' for nil:NilClass
/tmp/build_d95dd90babaefeea7421f49d780cdb82/config/environments/production.rb:124:in `block in <main>'
```
It's related to line [124](https://github.com/thepracticaldev/dev.to/blob/master/config/environments/production.rb#L124) in production.rb file: 
```ruby
config.action_mailer.default_url_options = { host: ENV["APP_PROTOCOL"] + ENV["APP_DOMAIN"] }
```

For this, I manipulated some of the parameters in the [Envfile](https://github.com/thepracticaldev/dev.to/blob/master/Envfile),  **APP_DOMAIN** and **HEROKU_APP_URL**, I set them to the app address that Heroku assigned to the app. But, the problem is not resolved ....
Perspicuously, should we set this parameter,  **APP_DOMAIN**?? or maybe this error is related to [sprockets ](https://github.com/rails/sprockets)version??

I also found this error in other issues like https://github.com/thepracticaldev/dev.to/issues/1205 and https://github.com/rails/sprockets/issues/683.

After one week challenge, I couldn't get to an instance of Dev Project. Thank you so much in advance.

**Comment by akhil-naidu** [comment]
Hello @Emaah 

I too faced similar problems and managed to fix some but I don't have a production level instance of dev.

But I can give you a view how things work, from my understanding.

1. You should have a local instance

Note: local here -doesn't mean only in your own machine, it can be a VPS or a Gitpod instance.

Why?
Because Dev works in way such that you will have a Deployment instance to check if your Dev is working or not and then make it a production instance in Heroku.

Why most people prefer their own machine?
To save the extra cost of VPS.

2. Dev prefer using node 12.16.3 and Gitpod default is 12.18.3

This is the main reason your Dev instance is not working.

How to solve this?
It's simple.
When you enter into your Gitpod you can see 4 workspace running simultaneously.
- redis-server
- elastic search server
- foreman server or rails (which is installing stuff, is gems)
- finally open ports viewer.

Now open the foreman server workspace.
`ctel +c`and stop it
Use this command `npm use 12.16.3`
Now double tap upper arrow key and run the previous command which was supposed to execute. `bin/setup && bin/startup`

That's it, wait for 10 mins.

3. Now, how to use Heroku

Before using Heroku, configure the last 4 variables in the  **Envfile** in **config/application.yml**
Starting from, **SECRET_KEY_BASE** to the HEROKU Domain.

Hope, I gave you some insights to work further. There are some minute details, if you have any doubts, you can nudge me.

Also, I was not able to make this a better looking guide as I was on bed with mobile 😂😉. Have fun. Don't mind typos and few errors.

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Emaah** [comment]
>
> 
>3. Now, how to use Heroku
> 
> 
> Before using Heroku, configure the last 4 variables in the **Envfile** in **config/application.yml**
> Starting from, **SECRET_KEY_BASE** to the HEROKU Domain.
> 

Hello @akhil-naidu,

Thank you for your detailed answer,
For deploying to Heroku, I applied the changes-configuring the application.yml file, but things did not go well and I encountered with the previous error:

```
Running: rake assets:precompile
WARNING: Skipping key "SECRET_KEY_BASE". Already set in ENV.
rake aborted!
NoMethodError: undefined method `+' for nil:NilClass
/tmp/build_4b7f22eea3b4722b6914235d2ec5cdce/config/environments/production.rb:124:in `block in <main>'
```

Maybe it is related to dependency packages versions inconsistency (I think [sprockets](https://github.com/rails/sprockets)) ......

I'm eager for further ideas .... 
Thank you.

**Comment by rhymes** [comment]
I think it's basically because `ENV["APP_PROTOCOL"]` and `ENV["APP_DOMAIN"]` are not defined

https://github.com/thepracticaldev/dev.to/blob/ffc96db209f03c0efc02acacb4c2b42718965ab1/config/environments/production.rb#L124

**Comment by Emaah** [comment]
> 
> 
> I think it's basically because `ENV["APP_PROTOCOL"]` and `ENV["APP_DOMAIN"]` are not defined
> 
> https://github.com/thepracticaldev/dev.to/blob/ffc96db209f03c0efc02acacb4c2b42718965ab1/config/environments/production.rb#L124
> 
> If you check the [Envfile](https://github.com/thepracticaldev/dev.to/blob/master/Envfile) you can see what they are for


Hello @rhymes,
Thank you for your respone,

I previously set those parameters directly in [Envfile](https://github.com/thepracticaldev/dev.to/blob/master/Envfile), But I got the above error,

Now, I set the **APP_PROTOCOL**  (to "http://")and **APP_DOMAIN** (to "the app address of Heroku")in the application.yml in the [config ](https://github.com/Emaah/dev.to/tree/master/config)file besides other keys, But again I got similar error:

```
Running: rake assets:precompile
WARNING: Skipping key "SECRET_KEY_BASE". Already set in ENV.
rake aborted!
TypeError: no implicit conversion of nil into String
/tmp/build_2bab460a7412929497fb4b15fe35de50/config/environments/production.rb:124:in `+'
/tmp/build_2bab460a7412929497fb4b15fe35de50/config/environments/production.rb:124:in `block in <main>'
```

No Idea .....

**Comment by rhymes** [comment]
@Emaah I think you need to set them as Heroku variables: https://devcenter.heroku.com/articles/config-vars#managing-config-vars

**Comment by akhil-naidu** [comment]
@Emaah 

> I am not sure how you are setting variables. please elaborate if possible.

### Here are some Best Practices

First, get your instance locally. It can be your own machine, Gitpod or VPS. Secondly, Install HEROKU. If you are using Gitpod, let me know, the process for installing Heroku needs to be done using .gitpoddocker file which is in the master root folder.

Next: You change your variables accordingly, you are familiar with it, all you need to do is- modify the application.yml file.

### Important steps that are not supposed to be Neglected

1. Heroku login in the dev root folder
2. It is always a better practice to use `heroku create` command after login, within the root folder
3. Use the git initially commands `git config --global user.name "John Doe"` and `git config --global user.email johndoe@example.com`
4. Before pushing your files to Heroku, check the `git status`, if it is not up to date. Using the below mentioned commands
5. `git add .` and `git commit -m "My Edits"`
6. Now push to Heroku by using the command: `git push heroku master`, now you can see the build log. Hope you will not get any errors
7. You can also manually migrate your database: `heroku run rake db:migrate`

I am in my way to create a detailed guide for beginners, but for that purpose, I am in search of some assistance. Also, let me know if these are helping you. Any doubts are appreciated, it will improve my guide too.

> Remember, there are no such doubts as silly doubts.

**Comment by akhil-naidu** [comment]
> I previously set those parameters directly in [Envfile](https://github.com/thepracticaldev/dev.to/blob/master/Envfile), But I got the above error,
> 
> Now, I set the **APP_PROTOCOL** (to "http://")and **APP_DOMAIN** (to "the app address of Heroku")in the application.yml in the [config ](https://github.com/Emaah/dev.to/tree/master/config)file besides other keys, But again I got similar error:

Is there any reason? For you to set most of the variables as `123456789dd`.
Or is it just a way of letting us know that you filled them?

**Comment by mstruve** [comment]
Hi @Emaah, since this issue has not been active for a while and seems to be related to an external environment variable issue on Heroku I am going to go ahead and close it. Please let us know if you have any questions! Thank you!
