### ISSUE TITLE
Invalid height for READ POST button

### ISSUE THREAD

**Issue by ianandhum** [forem/forem#921]
**Describe the bug**
The height of the **READ POST** button is incorrect and the text is broken taking two lines for the text 'read post'. 

This bug is observed in the **Related Posts** section

**To Reproduce**
1.Go to any post 
2. Scroll down to "Additional Posts" section

**Screenshots**

![screenshot_20181015_174012](https://user-images.githubusercontent.com/38727945/46950405-3b1f8180-d0a2-11e8-8733-1b7bbfa850e8.png)

**Desktop :**

- OS: Linux
- Browser Firefox Quantum
- Version 62.0.3

**Comment by anandhumanoj** [comment]
The same behaviour is observed in Chrome (on Linux ) too. So it is not only FF only problem

**Comment by aalises** [comment]
@anandhumanoj Fixed that (hopefully) on #922 just adding a little bit more width to the button.

**Comment by anandhumanoj** [comment]
:wave:
