### ISSUE TITLE
Give users an easy way to track badge progress

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#9210]
**Is your feature request related to a problem? Please describe.**

Yes, users cannot easily track their progress on [badges](https://dev.to/badges).

**Describe the solution you'd like**

I think it'd be great if folks could click to view their progress on different badges from a badge specific page like https://dev.to/badges. Folks should be able to easily navigate to this page from their user profile (perhaps with a prompt where their badges are posted). On dev.to/badges, it'd be ideal if you could easily tell what badges you've already obtained and which ones you haven't (the badges you haven't obtained would be greyed out). When you click on a greyed out badge, it would provide a progress bar or percentage score, and let you know the details of what you've left to do in order to get the badge.

**Describe alternatives you've considered**

We could also show the user's badge progress to them via settings or notifications.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
@michael-tharrington another one I am wondering if you think should be an RFC? Thanks.

**Comment by michael-tharrington** [comment]
Absolutely! We actually wrote up an internal support request related to this today so I'm going to cc' @andy here.

**Comment by james-wallis** [comment]
Hope this is ok to add. 

I've built a free tool that calculates your current writing streak in lieu of the feature being added into the core Forem code.

https://devto-writing-streak-calculator.wallis.dev

**Comment by michael-tharrington** [comment]
That's so awesome @james-wallis! Just curious, have you written a post on DEV about this?

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)

**Comment by james-wallis** [comment]
Hey @michael-tharrington

Sorry, I didn’t see your reply! Yes I wrote an article on Dev.to! https://dev.to/jameswallis/i-made-a-free-dev-to-writing-streak-calculator-that-anyone-can-use-4m07

@cmgorton in leu of a Forem implementation, would you want to link to the streak calculator tool? I can modify it to support more Forem projects if needed.

**Comment by cmgorton** [comment]
@JennieOcken any thoughts on this? The tool James created is useful.
