### ISSUE TITLE
Label Follow Weight Scale for Tags in Dashboard >> Following Tags

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#9211]
**Is your feature request related to a problem? Please describe.**

Yes, as a user it's a bit unclear how the follow weight scale for tags via https://dev.to/dashboard/following_tags is meant to be interpreted. It's not clearly stated that a greater number makes it so that a tag appears more in your feed while a smaller number makes it appear less; folks occasionally misinterpret this.

**Describe the solution you'd like**

We can update the language at the top of https://dev.to/dashboard/following_tags to say:

_"Adjust **Follow Weight** to make a tag show up less or more in your feed (default 1.0). Raising the number will make it so that a tag appears more in your feed, while lowering the number will make a tag appear less. Note that you can even make the follow weight negative for tags that you want to avoid seeing."_

**Additional context**

Here's a comment that back ups that idea of negative follow weight making it so you don't see a tag - https://dev.to/andy/comment/aa8o.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Veggier** [comment]
I will be working on this issue.
