### ISSUE TITLE
Query organization on dev.to/api

### ISSUE THREAD

**Issue by gixxerblade** [forem/forem#9212]
## Feature Request

Currently there in no way to query an organization on dev.to/api

**Describe the solution you'd like**

It would be nice to query https://dev.to/api/organization/articles, https://dev.to/api/organization/users, https://dev.to/api/organization/listings where organization is e.g., https://dev.to/api/vetswhocode

The description could read: 
>This endpoint allows the client to retrieve an organization .
>
>"Organizations" is all the data that an organization creates on DEV that typically show up in the feed and a user is connected >to. They can be a blog post, a discussion question, a help thread etc. but is referred to as an organization within the code.
>
>By default it will return featured, published articles ordered by descending date of publication
>
>It supports pagination, each page will contain 30 articles by default.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I think the URL structure should be something like:

`dev.to/api/organizations/{org_username}/articles` and so on

**Comment by twinsfan421** [comment]
I can work on this

**Comment by rhymes** [comment]
I've assigned you the issue, thanks @twinsfan421 !

**Comment by twinsfan421** [comment]
@rhymes I am working on it and have couple questions.  
In addition to the articles, users and listings, should I make a show action like dev.to/api/organizations/{org_username} for just the organization's info?
Should there be any authentication for these endpoints?
Thanks

**Comment by citizen428** [comment]
> In addition to the articles, users and listings, should I make a show action like dev.to/api/organizations/{org_username} for just the organization's info?

Yes, that's probably a good idea. It should mirror https://docs.dev.to/api/#operation/getUser.

>  Should there be any authentication for these endpoints?

Rough rule of thumb that the current API seems to follow: if it's public information, no authentication is needed. Best to follow similar API endpoints for now, the API docs are a good reference for this: https://docs.dev.to/api/

**Comment by cmgorton** [comment]
Hey @twinsfan421 thanks so much for all the contributions to this so far. Given the current PRs that have already been merged is there anything else left for this issue? 
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. 

I don't want to pull you off of this issue if you are close to finishing up any other tasks.

**Comment by twinsfan421** [comment]
> Hey @twinsfan421 thanks so much for all the contributions to this so far. Given the current PRs that have already been merged is there anything else left for this issue?
> We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request.
> 
> I don't want to pull you off of this issue if you are close to finishing up any other tasks.

This issue is completed.   Thank you

**Comment by cmgorton** [comment]
Thanks for the confirmation and thanks again for all the work you did on this. We really appreciate it 🙏🎉
