### ISSUE TITLE
Safari: dev.to pages will randomly grab an absurd amount of CPU

### ISSUE THREAD

**Issue by ardunster** [forem/forem#9228]
**Describe the bug**

Sometimes, while using my MacBook Pro while I have a dev.to page open in Safari in the background, whether I'm using Safari or not, but have only noticed it while not active in a dev.to page,  the page I have open will suddenly start using enormous amounts of CPU (over 100% according to Activity Monitor, which means it's grabbing multiple cores), causing my fans to turn on (usually why I notice it), and my battery to drain quickly. Reloading the page seems to stop the problem. Probably related: often when I come back to a dev.to tab, I'll have a note from Safari saying "this page was reloaded because it was using too much battery" (paraphrased).  I haven't noticed any pattern of when or why this happens.

**Expected behavior**

Pages to behave normally and not take massive amounts of CPU and battery, especially when I'm not actually focused on them, they're just in a tab in the background.

**Screenshots**

I don't have one but I'll try to get some next time I notice the problem.

**Desktop (please complete the following information):**

- OS: OSX Catalina 10.15.5, it was happening in 10.15.4 also. 
- Browser: Safari
- Version: 13.1.1

No extensions.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ardunster** [comment]
Thanks! I should mention that the pages I've seen it on have been articles (posts) I've left open to read later, in case that matters. There's a chance it has something to do with getting a notification, I'll keep an eye out and see if that's a consistent connection.

**Comment by rhymes** [comment]
@ardunster does Safari have a CPU profiler? Something like https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler ? Maybe that can be of help

**Comment by ardunster** [comment]
Oh yeah it looks like the timeline feature in the develop menu will do something like that. I'll see if I can get something useful out of it. (It's a problem that tends to occur after an hour or two of using the computer for other stuff with the window open in the background - so we'll see.)

**Comment by ardunster** [comment]
I was able to export some Safari Timelines:
[dev.to_safari_timelines.zip](https://github.com/thepracticaldev/dev.to/files/4905990/dev.to_safari_timelines.zip)

the first two files were while I was using the computer in the am, reloaded the page a couple times, the problem did not occur (the second one is about an hour of recording), providing them as a baseline. 

Then, before setting the computer aside on the charger while I ran some errands, I refreshed the page again, then started the third recording, but it looks like the recording stopped after about 50 minutes. It was on the charger so I didn't get a battery error, but it does look like some significant CPU usage occurred starting about 46 minutes (2793 seconds) into the recording, so maybe there will be something helpful in there. Safari can import and export the data, I'm not sure if there's anything else that can read it satisfactorily.

**Comment by rhymes** [comment]
Thank you @ardunster?

Embedding this screenshot that gives a good idea on how the CPU goes up!

<img width="1904" alt="Screenshot 2020-07-15 at 3 34 05 PM" src="https://user-images.githubusercontent.com/146201/87551880-3e99cf80-c6b1-11ea-8387-b97f28a9a40b.png">

**Comment by nickytonline** [comment]
No technical information in this post, but interesting that high CPU usage was reported a year ago in Safari, https://www.reddit.com/r/mac/comments/9hy92g/what_is_safari_service_worker_and_why_is_it_using/

**Comment by mstruve** [comment]
Since the service worker has been removed this should no longer be a problem. Please feel free to reopen if it still is. Thanks!
