### ISSUE TITLE
Connect channel invitation emails not sending consistently

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#9233]
**Describe the bug**
I recently created a chat channel and invited about 20 people. There are still a few 'pending invitations' and I'm no longer confident these members received all their email invite because I know one of them specifically did not (someone from our team, Gracie). 

**To Reproduce**

Not sure how to produce this consistently.

**Expected behavior**

Everyone invited to a channel should receive an email invitation.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
