### ISSUE TITLE
Non-chat channel users should not see chat channel details

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#9234]
**Describe the bug**

When a connect channel invitation did not get emailed to a member (#9233), I asked them to go to dev.to/connect to see if they could see their invite there. They could, but they could also see the details of the group -- such as their pending status.

**To Reproduce**
If a user has not accepted an invite yet, the chat channel details (such as who is in that channel) should stay hidden from them.

**Screenshots**

![](https://p193.p3.n0.cdn.getcloudapp.com/items/X6uovN5Q/Image%202020-07-09%20at%202.34.39%20PM.png?v=dc3f40d228584b9f5fba939f2fcc8068)

This is a screenshot from Gracie's experience.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
