### ISSUE TITLE
[Settings] reduce scrolling for saving

### ISSUE THREAD

**Issue by MenaiAla** [forem/forem#9240]
### Issue description

In the Settings page, all sections are expanded by default ( no show more options ) which makes the length too long.

**Case :**
I want to change just username and save it. Why do I need to scroll the whole page to click `save`?.

### Issue Solution
Case :

Move `save` button to the left side with fixed-position.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
Thanks for opening the issue @MenaiAla. I'm ccing our product designers, @lisasy and @ludwiczakpawel, as well. I did a quick mockup of what you I think you mean. Let me know if this is what you were thinking.

![image](https://user-images.githubusercontent.com/833231/87154741-bfa73000-c287-11ea-9a62-8c4f3963993b.png)

**Comment by MenaiAla** [comment]
@nickytonline , exactly but just make sure that users will not be confused by adding a line between items and button. I don't know how the back-end devs handle updating requests but I GUESS according to the design they did one request that updates all the fields even those who will not change by users. I'm not an EXPERT by you could ask BACK-END DEVS, is it better to have SAVE for each section.

**Comment by ludwiczakpawel** [comment]
I'm not sold on this one to be honest. Having Submit button in the sidebar is pretty confusing to me and I have initially missed it when I first saw the proposed mockup without actually reading the entire issue description.

BUT I do think this is a valid issue. Another potential solution that IMO makes a bit more sense in terms of UI and UX is having save button as it is right now (so below the form) but once you change any value of any form field (in other words: `form.onChange`) we should make it sticky, attached to the bottom of the screen, like this: https://d.pr/v/eaWwFf

**Comment by nickytonline** [comment]
@MenaiAla, yeah that was just a quick mockup, so there works be more space between the button and menu items.

Having said that, I find it confusing on the side as well. @ludwiczakpawel, I like the idea of the save button going sticky once there are changes.

**Comment by rhymes** [comment]
Wow, love the sticky idea!

**Comment by ludwiczakpawel** [comment]
Honestly it's a matter of applying one or two CSS classes on form change... soooo... who wants to take it for a ride? :D

**Comment by MenaiAla** [comment]
@ludwiczakpawel , yes  I agree with you.

**Comment by ludwiczakpawel** [comment]
@MenaiAla let me know if this is something you'd like to work on or should I try to assign this to someone internally :)

**Comment by MenaiAla** [comment]
@ludwiczakpawel , I could not promise you right now. It's better to assign this to someone.

**Comment by ludwiczakpawel** [comment]
Sure thing! We'll try to handle
it :)
