### ISSUE TITLE
Can't accept a  Connect invitation on mobile

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#9243]
**Describe the bug**

Unable to accept an invite to a Connect group on mobile. I mentioned this to @jessleenyc as it relates to Codeland since we are using Connect for Codeland.

**To Reproduce**

1. Click on your invite link in the email you received (in my case Codeland Volunteers Connect channel)
1. DEV opens Connect with the last channel you were connected to.
1. Visually, it appears that the invite did not work.

I did the same thing on my laptop and the first two steps are the same, but then I see a sidecar component on the right to accept my invitation. The issue appears to be that on mobile (not tablets), that the sidecar does not display.

**Expected behavior**

1. Click on your invite link in the email you received (in my case Codeland Volunteers Connect channel)
1. DEV opens Connect with the sidecar to accept the invitation to the Connect group.
1. Accept the invitation and you end up in the new Connect group.

**Screenshots**

Other sidecars are displayed, just not the invitation sidecar.

<img width="375" alt="DEV Connect 👩‍💻💬👨‍💻" src="https://user-images.githubusercontent.com/833231/87157240-f3845480-c28b-11ea-9fcf-9aa69a1241a2.png">

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

- Device: iPhone 8
- OS: iOS 13.5.1

The invite link deep linked me to the DEV iOS app, but I also tried in

- Browser: Edge
- Version: 45.5.0

**Additional context**

I don't think this is a browser specific issue, it's just Connect invitations not handling mobile.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@nickytonline Is it complentary of this? https://github.com/thepracticaldev/dev.to/issues/9233 - maybe these people haven't seen the invite

**Comment by nickytonline** [comment]
#9233 seems like an issue as well, but in my case I did receive the invite and ran into the issue above.

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
