### ISSUE TITLE
User have ability to remove following tag in the dashboard

### ISSUE THREAD

**Issue by Veggier** [forem/forem#9248]
**Is your feature request related to a problem? Please describe.**

When I do working on issue #9211, I realize that we can't remove the following tag from the dashboard

**Describe the solution you'd like**
Add the feature that we can click a delete button to remove the following tag that we don't want to follow

**Additional context**

![image](https://user-images.githubusercontent.com/47649859/87173960-7f09df80-c2a4-11ea-96b1-407d2b4a03c1.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by PrimeNoodles** [comment]
Will attempt to work on this issue

**Comment by nickytonline** [comment]
Oops, I thought this was ready for dev @PrimeNoodles. We'll get back to you on this.

**Comment by PrimeNoodles** [comment]
Oh sorry, I didn't notice that I thought this was a bug problem my bad too

**Comment by iamjoross** [comment]
@PrimeNoodles , are you working on this? I would want to work on it since it is unassigned @nickytonline :)

**Comment by FreakLevel** [comment]
Hi, I would like take this issue 😁

**Comment by rhymes** [comment]
Hi @FreakLevel, I've assigned you to it!

**Comment by fyodorio** [comment]
@cmgorton I would suggest a couple of options here (I mean I could work on possible implementation, of course).

First, more consistent one - add a menu button, which would trigger drop-down menu with a single `Unfollow` option inside:

<img width="1347" alt="Screenshot 2021-08-09 at 01 01 57" src="https://user-images.githubusercontent.com/19417873/128644668-c15f4135-e0f2-4a04-aeea-2eb83112fe70.png">

That is, the same way it's currently done in listings:

<img width="1297" alt="Screenshot 2021-08-09 at 01 03 00" src="https://user-images.githubusercontent.com/19417873/128644676-44b3fbf1-81af-43ce-93fa-04cce0b7c40c.png">

Alternatively, one could just add a small dimmed `Unfollow` button itself:

<img width="1455" alt="Screenshot 2021-08-09 at 01 16 28" src="https://user-images.githubusercontent.com/19417873/128644690-ef23fe39-5653-4736-b85d-8925277b97bc.png">

I personally like the latter more, as it's quicker (less clicks) and quite obvious.

In terms of behaviour (for both suggested options), I would suggest to follow (no pun intended) the twitter way - unfollow the tag when user clicks the button the first time, and follow the tag back (the button text changes to `Follow` by this moment) if the user changes their mind.

WDYT?

Additionally, I think this issue looks more common from the first sight - probably all the "Following..." lists would benefit from having the unfollow flow.

<img width="1371" alt="Screenshot 2021-08-09 at 01 31 24" src="https://user-images.githubusercontent.com/19417873/128644875-a2ae0552-a911-4c2a-9acc-8bdea9a0d41c.png">

**Comment by mirie** [comment]
Addressed by https://github.com/forem/forem/issues/19675
