### ISSUE TITLE
Can't invite or remove user in the connect page.

### ISSUE THREAD

**Issue by Veggier** [forem/forem#9249]
**Describe the bug**
When I want to invite someone or delete the member from the group chat in https://dev.to/connect page, It will show an error  "User not authorized"

**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/47649859/87176183-c04fbe80-c2a7-11ea-89d0-5cf61b3fc698.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome 
- Version:  83.0.4103.116 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by narender2031** [comment]
@Veggier are you the owner of the channel. What is your role type in this channel?

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
