### ISSUE TITLE
New posts/users have their published/joined date a day ahead

### ISSUE THREAD

**Issue by rembrandtreyes** [forem/forem#9269]
**Describe the bug**
I was looking through some user-profiles and noticed that some have a date that is in the future. Found users that have a joined date of July 12, 2020. And investigating further looks like this applies to posts and comments.

**To Reproduce**
Create a post and see if the published date is 1 day ahead

**Expected behavior**
Users should have posts and join dates of the current day

**Screenshots**

![Screen Shot 2020-07-11 at 6 11 22 PM](https://user-images.githubusercontent.com/15057964/87236775-0ee18380-c3a2-11ea-99a0-4b01ebed16a5.png)

![Screen Shot 2020-07-11 at 6 05 45 PM](https://user-images.githubusercontent.com/15057964/87236749-bdd18f80-c3a1-11ea-8969-75c3a0ff3758.png)

![Screen Shot 2020-07-11 at 6 24 02 PM](https://user-images.githubusercontent.com/15057964/87236930-47825c80-c3a4-11ea-845a-5649e4c52a0a.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Safari, Firefox, Chrome
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

I believe the issue is coming from the additional day we get this year.

### Users join dates
current   ->  actual
Feb 28, 2020 -> Feb 28, 2020
Mar 1, 2020 -> Feb 29, 2020
Mar 2, 2020 -> Mar 1, 2020
...
Jul 12, 2020 -> Jul 11, 2020

**Comment by PavelTkachenko** [comment]
> I believe the issue is coming from the additional day we get this year.

No. This is because the time zone is not taken into account.

 Here is `articles/_user_metadata.html.erb` for example:

```html
<div class="value">
 <%= @user.created_at.strftime("%b %e, %Y") %>
</div>
```

So the current day is calculated based on app timezone. It's not good. I can take this issue and fix all occurrences.

**Comment by rembrandtreyes** [comment]
> > I believe the issue is coming from the additional day we get this year.
> 
> No. This is because the time zone is not taken into account.
> 
> Here is `articles/_user_metadata.html.erb` for example:
> 
> ```
> <div class="value">
>  <%= @user.created_at.strftime("%b %e, %Y") %>
> </div>
> ```
> 
> So the current day is calculated based on app timezone. It's not good. I can take this issue and fix all occurrences.

👏

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
This should be fixed on the client side, for example with 

https://github.com/thepracticaldev/dev.to/blob/5094f6be9c1d6065b233654def953dbf3dad650e/app/assets/javascripts/utilities/localDateTime.js#L15

**Comment by PavelTkachenko** [comment]
Cool! I see labels are set, I’ll take this issue.
