### ISSUE TITLE
Need help in configuring HEROKU_POSTGRES

### ISSUE THREAD

**Issue by akhil-naidu** [forem/forem#9288]
`remote:        I, [2020-07-13T12:02:37.768240 #11563]  INFO -- honeybadger: ** [Honeybadger] Success ⚡ https://app.honeybadger.io/notice/ff036682-bcec-46be-8343-546ad2723682 id=ff036682-bcec-46be-8343-546ad2723682 code=201 level=1 pid=11563
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !     Attempted to access a nonexistent database:
remote:  !     https://devcenter.heroku.com/articles/pre-provision-database
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to devtrial.
remote: 
To https://git.heroku.com/devtrial.git
 ! [remote rejected]     master -> master (pre-receive hook declined)`

I have been facing this error. I have added these addons **redis** and **postgres**

Are there any extra configurations or config variables I am supposed to add?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@akhil-naidu  Regarding `Attempted to access a nonexistent database`: did you set up your database on Heroku, e.g. `heroku run rails db:migrate`?

**Comment by akhil-naidu** [comment]
@citizen428 when I tried that command it gives me an error: `rails:  command not found `

Any other way of doing this? Using Heroku web UI?

**Comment by citizen428** [comment]
@akhil-naidu Are you following Heroku's guide? https://devcenter.heroku.com/articles/getting-started-with-rails5

**Comment by akhil-naidu** [comment]
Hello @citizen428 

As I am facing such an issue with Linux installation, I converted into a container-based local instance. Everything is fine in local deployment.

But when I was trying to have a production deployment in HEROKU, I am facing a single error and realized it is because of port 9200 and confirmed- my error is related to elastic search. 

I would like to know, how to configure an elastic search in Heroku. RightNow I am having my trials through bonsai-elastic search add-on in Heroku. If there is any other preferred method please suggest.

**Comment by citizen428** [comment]
Make sure you have an `ELASTICSEARCH_URL` set in your environment variables. It can point to the same value as `BONSAI_URL`.

**Comment by citizen428** [comment]
Hi @akhil-naidu, any progress on this? Can we close this issue now?
