### ISSUE TITLE
Sending a message triggers message alert for the sender

### ISSUE THREAD

**Issue by Amorpheuz** [forem/forem#9307]
**Describe the bug**
Occurs on sending a message to a user via Connect. If you have multiple tabs open (side-by-side), you get a new alert for yourself.

**To Reproduce**
1. Login to [DEV](https://dev.to).
2. Open two windows of dev, in a side-by-side config.
![image](https://user-images.githubusercontent.com/22113778/87451826-09906d00-c61e-11ea-8ce8-43a94dccf973.png)
3. Send a message to someone who has chat open, [myself](https://dev.to/amorpheuz) for e.g. ;) 
4. Alert pops-up in other window.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22113778/87451089-03e65780-c61d-11ea-9474-25631655b381.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge 
- Version: 83.0.478.61

- Couldn't find a way to successfully test on mobile.

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by narender2031** [comment]
@Amorpheuz This works fine for me locally. Can you please check again is this issue is still there?

**Comment by Amorpheuz** [comment]
Hi! I have been unable to reproduce it on local machine too. I am not sure, the other person (with whom I noticed the issue) might be comfortable getting a random dm for testing on live. 😅

**Comment by narender2031** [comment]
😅 I created my dummy account and tested locally. It works fine. I think we can close this issue now.

**Comment by narender2031** [comment]
@rhymes we can close this issue.
