### ISSUE TITLE
Profile pages where the username in the URL is not all lower case do not display properly (double footer, wrong colour mode, images and links missing).

### ISSUE THREAD

**Issue by SuzeShardlow** [forem/forem#9322]
**Describe the bug**

When I visit a profile where the username is not all in lower case in the URL, the following happens:

+ switches to default (light) mode if UX preferences are set to dark;
+ there are two footers at the bottom of the page;
+ the avatar is not showing top right and the grey circle which replaces it is not clickable.

If I then click a link on that page, for example a link to a blog post, then the blog post page has the same issues as above.

If I hit refresh on that blog post, it is restored to normal.

The issue is only fixed by visiting a profile page where the username is all lower case in the URL.

**To Reproduce**

Visit my profile at https://dev.to/SuzeShardlow or https://dev.to/Suzeshardlow or https://dev.to/SuZeShArDlOw or any profile where the username is not all lower case.

You will see all the issues listed above.

Then click on one of my blog posts from my profile.  You will see the same errors on the blog post page.

Get back to normal by visiting https://dev.to/suzeshardlow or by hitting refresh on the blog post page.

**Expected behavior**

I expected to see my profile as it looks at https://dev.to/suzeshardlow , in dark mode, with one footer block, my avatar in the top right corner etc.  When I click through to one of my blog posts, I expect to see it in dark mode with one footer block and my avatar in the top right.

**Screenshots**

My profile at https://dev.to/suzeshardlow:

![dev to_suzeshardlow (1)](https://user-images.githubusercontent.com/6759411/87488668-e2936480-c638-11ea-8c8a-e7a53d25d530.png)

My profile at https://dev.to/SuzeShardlow or https://dev.to/Suzeshardlow or https://dev.to/SuZeShArDlOw or any profile where the username is not all lower case:

![dev to_SuzeShardlow](https://user-images.githubusercontent.com/6759411/87488708-f50d9e00-c638-11ea-971f-5e16c3678daa.png)

**Desktop (please complete the following information):**

- OS: MacOS High Sierra
- Browser: Chrome
- Version: 83.0.4103.116

**Smartphone (please complete the following information):**

- Device: Google Pixel 4
- OS: Android 10
- Browser: Chrome
- Version: 74.0.3729.186

**Additional context**

Correct profile view: https://dev.to/suzeshardlow
Profile URLs where you will see the above issues: https://dev.to/SuzeShardlow , https://dev.to/Suzeshardlow , https://dev.to/SuZeShArDlOw etc

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Hey @SuzeShardlow does this still happen to you?

**Comment by SuzeShardlow** [comment]
> Hey @SuzeShardlow does this still happen to you?

No idea @ludwiczakpawel, I haven't used the site for several months now. Feel free to try and reproduce the issues using the steps I documented above.

**Comment by ludwiczakpawel** [comment]
Thanks! I couldn't repro it, so I'm closing the issue.

Thanks again and I hope to see you on DEV again! :)
