### ISSUE TITLE
Settings: Elements in content customization box leaking outside the container

### ISSUE THREAD

**Issue by icncsx** [forem/forem#9324]
**Describe the bug**

The text elements area leaking outside of the container.

![Screenshot from 2020-07-15 00-24-56](https://user-images.githubusercontent.com/60417145/87503287-cfc96180-c631-11ea-93ce-ce7c63e1d4af.png)

**To Reproduce**

Visit the [settings/ux](https://dev.to/settings/ux) endpoint and look at the coding experience boxes.

**Expected behavior**

Text should be contained in the box.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by PavelTkachenko** [comment]
I can take this issue and provide png images to approve design before coding.

**Comment by rhymes** [comment]
@PavelTkachenko go ahead, thank you!

**Comment by benhalpern** [comment]
@PavelTkachenko We can think of the text as optional, so we could hide it for smaller breakpoints.
