### ISSUE TITLE
Typo in in folder/file path in frontend#webpacker doc

### ISSUE THREAD

**Issue by oyeyipowale** [forem/forem#9328]
Could not readily find issue template/guide for documentation typos. Here goes:

Reading through the documentation at [frontend guide -> webpacker](https://docs.dev.to/frontend/webpacker/), found two references to a `app/javascripts`  folder. However, only the folder `app/javascript` was currently available.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@oyeyipowale thanks a lot! 

Would you like to submit a patch for it? The file with the typos is https://github.com/forem/forem/blob/master/docs/frontend/webpacker.md :-)

**Comment by oyeyipowale** [comment]
Yes! on the way.
