### ISSUE TITLE
Broken link to code path in documentation (dynamic imports)

### ISSUE THREAD

**Issue by oyeyipowale** [forem/forem#9330]
## Description
The link to a code sample file in the documentation on **Dynamic Imports** has changed in the repository.

## Steps to reproduce
[Dynamic imports](https://docs.dev.to/frontend/dynamic-imports/). the codeEditor.jsx#L11 file no longer exists.
https://github.com/forem/forem/blob/master/app/javascript/chat/codeEditor.jsx#L11

second link in the examples of dynamic import usage on DEV.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Yeah, I think we should replace those links with permalinks.

- onboarding: https://github.com/forem/forem/blob/0633d85b6b0e083bb7b21b11642b2b17d3fe9de6/app/javascript/packs/Onboarding.jsx#L21
- connect code editor: doesn't exist anymore, maybe we can replace it with the homepage https://github.com/forem/forem/blob/0633d85b6b0e083bb7b21b11642b2b17d3fe9de6/app/javascript/packs/homePage.jsx#L59 or pusher connect https://github.com/forem/forem/blob/0633d85b6b0e083bb7b21b11642b2b17d3fe9de6/app/javascript/utilities/connect/pusher.js#L4

@oyeyipowale you know what to do if you want to take this on :D 

the file is https://github.com/forem/forem/blob/master/docs/frontend/dynamic-imports.md
