### ISSUE TITLE
Error when attempting to access unfinished/unpublished post & Profile showing spam_966114

### ISSUE THREAD

**Issue by iverve** [forem/forem#9332]
### Describe the bug

My account is showing **spam_966114** and unable to see my **published blog links** & 404 bio not found.

**Can someone help me how to resolve it** 

To Reproduce

Go to my Dashboard
Click on the title or Edit button of any one of the last three of four unpublished posts
See error
Expected behavior
View and/or edit post

Desktop (please complete the following information):

Browser: Mozilla
Version : 66.0.2 (64-bit)

![screencapture-dev-to-spam-547864-2020-07-15-19_53_20 (1)](https://user-images.githubusercontent.com/6126082/87557673-d3aebf80-c6d5-11ea-9705-dfc3fe0e7df9.png)

**Comment by rhymes** [comment]
Hello @iverve, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by iverve** [comment]
Hello Dev.to team,

Why I am facing this problem ofter? Can you plz resolve asap you can
