### ISSUE TITLE
Convert the <ImageUploader /> component to use hooks

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#9338]
**Is your feature request related to a problem? Please describe.**

This is not a feature, but a refactor of a currently working Preact component to use hooks.

The reason for the refactor is to demonstrate how anyone contributing to the codebase can use new features of Preact.

This issue is part of the live code pairing sessions on DEV. @sophi-li was our first guest to pair.

**Describe the solution you'd like**

Convert the component to use hooks.

**Describe alternatives you've considered**

**Additional context**

**Comment by sophi-li** [comment]
I'll take this issue!

**Comment by nickytonline** [comment]
Thanks for the refactor Sophia!
