### ISSUE TITLE
Boilerplate acknowledgement text for Forem GitHub Issues needs to be updated following the switch to the Forem organisation.

### ISSUE THREAD

**Issue by SuzeShardlow** [forem/forem#9339]
**Describe the bug**

The boilerplate text for the GitHub Issues acknowledgement contains reference to @thepracticaldev/oss which no longer seems to exist following the switch to the Forem organisation on GitHub.  It previously hyperlinked to [https://github.com/orgs/thepracticaldev/teams/oss](https://github.com/orgs/thepracticaldev/teams/oss) which now leads to a 404, presumably as a result of the move to using the Forem naming on GH.

**To Reproduce**

Open [any issue](https://github.com/forem/forem/issues) which has been acknowledged by Forem staff and had the boilerplate acknowledgement posted as a comment.

**Expected behavior**

A boilerplate which links to contact information.

**Screenshots**

In the third paragraph of the acknowledgement boilerplate you will see a reference to @thepracticaldev/oss which doesn't link to anywhere.

<img width="881" alt="Screen Shot 2020-07-15 at 22 42 33" src="https://user-images.githubusercontent.com/6759411/87601212-8a1d9f00-c6ec-11ea-91d1-45e4c4a0e258.png">

**Desktop (please complete the following information):**

+ OS: MacOS High Sierra
+ Browser: Chrome
+ Version: 83.0.4103.116

**Smartphone (please complete the following information):**

+ Device: Google Pixel 4
+ OS: Android 10
+ Browser: Chrome
+ Version: 74.0.3729.186

**Comment by citizen428** [comment]
Thanks, @SuzeShardlow, I updated our response templates now. Here's an example:

Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).
