### ISSUE TITLE
Typo/missing word in forem/README.md

### ISSUE THREAD

**Issue by cmgorton** [forem/forem#9340]
**Describe the bug**
There is a word missing in the main Forem README.md.

**To Reproduce**
Go to forem/README.md
Scroll down to this paragraph:

_dev.to (or just DEV) is hosted by Forem. It is a community of software developers who articles, take part in discussions, and build their professional profiles._

**The error is in this sentence:**
It is a community of `software developers who articles`, take part in discussions, and build their professional profiles.

**Expected**
Sentence should read like:
It is a community of software developers who **write** articles, take part in discussions, and build their professional profiles.

Could also use **create** instead of write.

**Screenshots**
<img width="1095" alt="Screen Shot of missing word" src="https://user-images.githubusercontent.com/21039864/87618609-83d0f800-c6d7-11ea-8a2e-8092f78f337d.png">

**Comment by citizen428** [comment]
Thanks for the issue @cmgorton! Would you like to fix this yourself? :-) The word that was accidentally removed was "write" btw.

**Comment by cmgorton** [comment]
Sure. I'd be happy to tackle this one. Should I follow the steps in the developer documentation? :) https://docs.dev.to/

**Comment by citizen428** [comment]
Thank you for volunteering @cmgorton! 💯 

Since this is a README change, you can even do it easily via the Github web app:

1. Go to https://github.com/forem/forem/blob/master/README.md
2. Hit the edit button
    <img width="1262" alt="forem_README_md_at_master_·_forem_forem" src="https://user-images.githubusercontent.com/47985/87622850-3479de80-c74e-11ea-9176-6c61103835e9.png">
3. Make your changes and create a PR from there. The branch name follows the following structure: `username/topic-issue` number, in this case, `cmgorton/fix-readme-9340`.

**Comment by cmgorton** [comment]
Awesome, thanks for the great explanation. Will create the PR now.

**Comment by cmgorton** [comment]
Submitted pull request here: https://github.com/forem/forem/pull/9341
