### ISSUE TITLE
Reading list rendering twice on repeated navigation

### ISSUE THREAD

**Issue by cainwatson** [forem/forem#9342]
**Describe the bug**

The reading list renders a second time under its self when repeatedly navigating from the home page to the reading list page. It 

**To Reproduce**

1. Go to home page
2. Click on 'Reading list'
3. Click on Dev logo to go back to home
4. Repeat last two steps 2 more times
5. See reading list and tags rendered twice

**Expected behavior**

Expected reading list to show up once.

**Screenshots**

![](https://user-images.githubusercontent.com/23223956/87627023-6873e600-c6f3-11ea-91c6-6f424389840e.gif)

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Browser: Brave
- Version: 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I can reproduce this as well :-(

**Comment by nickytonline** [comment]
I'm able to reproduce this as well. It looks like the Preact component is rendering twice for some reason. It could be related to InstantClick.

![image](https://user-images.githubusercontent.com/833231/87675300-34291580-c745-11ea-890a-25edf81f60bf.png)

**Comment by nickytonline** [comment]
Looks like the reading list was missed during the Preact upgrade somehow.

In the file https://github.com/forem/forem/blob/master/app/javascript/packs/readingList.jsx#L10

```jsx
      render(
        <ReadingList
          availableTags={followedTagNames}
          statusView={root.dataset.view}
        />,
        root,
        root.firstElementChild,
      );
```

should be

```jsx
      render(
        <ReadingList
          availableTags={followedTagNames}
          statusView={root.dataset.view}
        />,
        root,
      );
```

**Comment by nickytonline** [comment]
Do you want to take this on @cainwatson? It's just the one line change mentioned above. Tests are not required here.

**Comment by nickytonline** [comment]
For more information on this see the [Preact Upgrade Guide](https://preactjs.com/guide/v10/upgrade-guide/) under the part about `render()`.

**Comment by cainwatson** [comment]
@nickytonline Sure! I'll get on it shortly.
