### ISSUE TITLE
Move away from `master` as main branch

### ISSUE THREAD

**Issue by abenerd** [forem/forem#9343]
**Is your feature request related to a problem? Please describe.**
Following the example of #7147 I'd like to propose moving away from naming the main branch `master`.

**Describe the solution you'd like**
I propose using terms such as `leader`, `main` or even `distinguished` as obviously this would be the most awesome and serious branch. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a Forem team member and is not up for grabs.

**Comment by rhymes** [comment]
I'm +1 on `main` as it's going to be the default in GitHub anyway

**Comment by cmgorton** [comment]
This is currently being worked on internally. We have an open issue in our internalForem repo for this so I am going to close this one here. Thanks again for opening this and starting the discussion here!
