### ISSUE TITLE
Include 'more sign in options' on the front page

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9346]
Can we add the 'more sign in options' option to the full desktop view, to the top right logon box where the social options are immediately displayed?

<img width="528" alt="Screenshot 2020-07-16 at 10 15 34" src="https://user-images.githubusercontent.com/12694270/87653368-57f05980-c74d-11ea-886b-3ce5e0474c75.png">
displayed?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).
