### ISSUE TITLE
Allow members to invite other members

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9348]
As part of the new invite devise functionality, for smaller communities it would be great if we could allow members to invite new members. I was thinking of clearly displaying this to them either in the feed or the sidebar as a quick action, just fill the field in for email and name inline with the element and then hit send, as turnkey as possible.

Thanks!

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
