### ISSUE TITLE
Connect pending requests sidecar on iOS small screens

### ISSUE THREAD

**Issue by fdoxyz** [forem/forem#9358]
**Describe the bug**

There's a problem with the way the pending requests are displayed in the sidecar for small screens on iOS. This does not happen on an Android phone or in the responsive mode for the dev tools on Safari for Desktop. I can only see these problems in Safari & other browsers in iOS, where the background is mixed with the chat itself

**To Reproduce**

1. Open web browser or native app in iOS
1. Navigate to connect
1. Open sidecar from "pending requests" button
1. Once the problem is visible, if you scroll up and down a bit the layout is "fixed" on it's own

**Expected behavior**

The background chats shouldn't be visible once the sidecar is presented

**Screenshots**

Here's is what I see:

![connect-request-panel-small-screens](https://user-images.githubusercontent.com/6045239/87702241-64c57b00-c756-11ea-89ef-36f96891a264.gif)

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS: iOS
- Browser: Safari, Firefox & Native iOS app
- Version: 13.5.1

**Additional context**

I'm unsure why is this fixed as soon as you scroll a bit. I'll continue to try and debug this to add more context if I get to figure any more information.

**Comment by sarthology** [comment]
It's fixed.
