### ISSUE TITLE
Redirect docs.dev.to to docs.forem.com

### ISSUE THREAD

**Issue by Arun4033622** [forem/forem#9365]
Right now, the docs are available in both [docs.dev.to](https://docs.dev.to/) and [docs.forem.com](https://docs.forem.com). Why not redirect [docs.dev.to](https://docs.dev.to/) to [docs.forem.com](https://docs.forem.com)?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
@Zhao-Andy or someone who has access to the Netlify dashboard will have to handle this.

**Comment by Zhao-Andy** [comment]
Resolved via #9618 and #9622
