### ISSUE TITLE
Allow a new Forem to toggle suggested users to follow on or off. When on, then it over rides the default algorithm.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9367]
This feature request is related to the amazing work completed in PR #7637
https://github.com/forem/forem/pull/7637

At the moment, the platform over rides the default user list when there has been some user activity, then switches over to the automated follower list, problem is that then that list can display just a single user.

I have suggested that for now there is a simple toggle switch that always overrides the system generated list, and it is up to the site admin to decide when the platform is busy enough to switch over.

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by sidemt** [comment]
Hi. I'm interested in working on this. Can I take this issue?

**Comment by citizen428** [comment]
@sidemt I assigned you the issue now, thanks for volunteering! If you have further questions please post them here on a draft PR.
