### ISSUE TITLE
Can not write post

### ISSUE THREAD

**Issue by imdhruv99** [forem/forem#9368]
Dear sir, 

I can not create any blog post using Dev.to website or mobile application. Kindly resolve as soon as possible

![Screenshot (113)](https://user-images.githubusercontent.com/60540925/87801358-40a88d80-c86d-11ea-842c-678ff27b3f76.png)

**Comment by rhymes** [comment]
Hello @imdhruv99, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by imdhruv99** [comment]
I have e-mailed on yo@dev.to before 3 days, and i was waiting that my issue will be resolved but i did not resolved yet. Even i did not received any response email from your end. I want to write some new blogs and you are now resolving my issue. 
Sir, very poor service by your end. I am disappointed ☹️
