### ISSUE TITLE
Text overflows in the article page

### ISSUE THREAD

**Issue by mzaini30** [forem/forem#9374]
**Problem**

![Screenshot_2020-07-18-07-35-49-88](https://user-images.githubusercontent.com/7939342/87838380-74190580-c8c9-11ea-9346-d58bd0a02d63.png)

![Screenshot_2020-07-18-07-32-43-03](https://user-images.githubusercontent.com/7939342/87838392-7b401380-c8c9-11ea-8b12-3c99f3d4057b.png)

**Dev post url**

<https://dev.to/kevinast/responsive-svelte-exploring-svelte-s-reactivity-5cen>

**My device**

Realme C2 
Chrome browser

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by djsiddz2** [comment]
I did some quick investigation on the link provided by @mzaini30: There are a few code blocks `<pre class="highlight">` which do not have a parent `<div class="highlight">`. Those are the ones where the text overflows generally. This should help anyone starting to work on this issue.

**Comment by mzaini30** [comment]
![Screenshot_2020-07-23-18-22-11-14](https://user-images.githubusercontent.com/7939342/88276402-91a6fe80-cd11-11ea-895a-050f4b3779ff.png)

I got it again.

I think, it's great to add this CSS:

```css
* {
 word-wrap: break-word;
}
```

**Comment by caleb15** [comment]
I also ran into this issue on chrome on the desktop. See https://github.com/forem/forem/issues/9475

**Comment by aitchiss** [comment]
Closing this issue as it was fixed under #10782 (I've double-checked the post referenced above and it's now formatting correctly). If you find this is still an issue, please let us know!
