### ISSUE TITLE
Add more oauth providers

### ISSUE THREAD

**Issue by abenettt** [forem/forem#9397]
**Is your feature request related to a problem? Please describe.**
With forem being a platform that enables all kind of communities and not just DEVelopers anymore I think it is a good idea to enable login with more providers than just twitter and github. Although many people have twitter, github is more developer centric.

**Describe the solution you'd like**
I'd like to propose adding more oauth providers such as discord and apple.

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Hi @abenettt, thanks for the feature request.

I'm going to close this as we are already working on adding "sign in with Apple" - see https://github.com/forem/forem/issues/7445 and https://github.com/forem/forem/pull/7952

and there's already an open ticket about adding login options: https://github.com/forem/forem/issues/7087

Please add your comment there, thank you!
