### ISSUE TITLE
Connect invite not visible w/ all nav bar settings 

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#9412]
**Describe the bug**
When a user has the UX setting for the nav bar to be 'static at top of page' their chat channel invites get covered up.

**To Reproduce**

**Screenshots**
![](https://p193.p3.n0.cdn.getcloudapp.com/items/8Lu7Lowg/Image%202020-07-20%20at%208.33.43%20PM.png?v=dcd03907aa763a65261d9b10d233e0d4)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS: Mac
- Browser: Chrome
- Version:

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).
