### ISSUE TITLE
Back button in the search results page is broken when filters are used

### ISSUE THREAD

**Issue by rhymes** [forem/forem#9433]
**Describe the bug**

After searching for a results, and filtering the results, the back button is broken

**To Reproduce**

1. Go to https://dev.to/search?q=python
1. Choose one of the filters
1. Hit the browser's back button
1. The browser will land back on the homepage, not on the non filtered results page

**Expected behavior**

I expect the back button not to be broken and going back resulting in going in each of the filtered results page

**Screenshots**

![back_button](https://user-images.githubusercontent.com/146201/88166633-d8b0c900-cc17-11ea-9ad2-79b52183b2e2.gif)

**Additional context**

I think the issue lies in how we build filters on click handlers and the usage of `window.replaceState` instead of `window.pushState`. See 

https://github.com/forem/forem/blob/b84f04baa5a061790b5a48c48554ceca6392cb0b/app/views/articles/_search.html.erb#L85-L98

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by PrimeNoodles** [comment]
@rhymes, I looked at the issue at it's pretty much exactly as you mentioned. Using pushState instead of replaceState on line 86 
`window.history.replaceState(null, null, "/search?q=" + query + "&filters=" + filters + sortString); ` 
to
`window.history.pushState(null, null, "/search?q=" + query + "&filters=" + filters + sortString); `
allowed me to go back to the last search filter as opposed to the home page. I don't know if you already made a pull request for it but I can push mine if need be.

![FilterBackButton](https://user-images.githubusercontent.com/35935438/88592954-d346ea80-d02c-11ea-909e-f890481f9454.gif)

**Comment by rhymes** [comment]
@PrimeNoodles no PR, I'm going to assign you the issue! note there are other `replaceState` in the file so make sure each path works corretly, thank you!

**Comment by PrimeNoodles** [comment]
I initially tried replacing all the replaceState with pushState, however it gave me a weird bug where it requires me to click back twice for every filter switch I click on in order for any changes to happen. Messing around with replaceState and pushState on all 5 places in the file, it seems like this works the best, but I'll try messing with it some more.

**Comment by nickytonline** [comment]
The replaceState is the way to go. I did this a couple of hours ago locally and it works, but I encountered the same issue as you with ha hbd to click back twice. Having said that the browser history is correct, so my guess is we have some custom code causing the double click to go back.
