### ISSUE TITLE
Unable to login from Twitter

### ISSUE THREAD

**Issue by SoluLab-Blockchain** [forem/forem#9434]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @SoluLab-Blockchain, what are your DEV and/or Twitter usernames?
