### ISSUE TITLE
Not authorised error when trying to access /internal/config

### ISSUE THREAD

**Issue by boddumanohar** [forem/forem#9457]
**Describe the bug**
I am trying to setup forem using containers. I followed the instructions as listed here: https://docs.dev.to/installation/containers/

I've also setup GitHub authentication and it works.
after the authentication, the UI shows 
```
setup not complete, click here to complete setup
```
when I click on the setup, I am getting:
```
Pundit::NotAuthorizedError in Internal::ConfigsController#show
```
I searched through your documentation, but I couldn't find a reason why I am seeing this.

If there any other manual thing that has to be done, if yes then that information should also be documented.

**To Reproduce**
Follow the instructions as here: https://docs.dev.to/installation/containers/ 

**Expected behavior**
I should be able to get started with no manually actions.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@boddumanohar To have a user that can both view and edit the settings at `/internal/config` you can do the following in the Rails console:

```ruby
user = User.find(...)
user.add_role(:single_resource_admin, Config)
```

**Comment by boddumanohar** [comment]
@citizen428  thanks for your reply, I tried to that, now I am able to access `/internal/config`. but when I try to update the values I get this error: 
```
Pundit::NotAuthorizedError in Internal::ConfigsController#create

```

```ruby
  def not_authorized
    render json: "Error: not authorized", status: :unauthorized
    raise NotAuthorizedError, "Unauthorized"
  end

  def bad_request
```

**Comment by citizen428** [comment]
The reason for this is the `before_action` called `extra_authorization_and_confirmation`. it checks for the presence of a confirmation message:

```ruby
confirmation_message = "My username is @#{current_user.username} and this action is 100% safe and appropriate."
```

There should be a field for setting this in the form.

**Comment by boddumanohar** [comment]
Hi @citizen428 . I didn't fill that field because its not marked as required. Thanks, Will create PRs for the same.

**Comment by boddumanohar** [comment]
Thanks this issue is resolved now.

**Comment by boddumanohar** [comment]
@citizen428 , In the documentation I see the instructions for accessing admin page. https://docs.dev.to/backend/admin/#accessing-the-admin-panel

In here, it tells that to get full access to the admin page. I just need to assign the super_admin role:
```
user.add_role(:super_admin)
```
In that case, the change that you requested to add to the documentation which is: 
```
user.add_role(:single_resource_admin, Config)
```
is this still required?

**Comment by citizen428** [comment]
@boddumanohar Somewhat confusingly we currently have two admin areas, one using the Administrate gem (`/admin`, described in https://docs.dev.to/backend/admin/#accessing-the-admin-panel) and one writen from scratch (`/internal/config`, described in https://docs.dev.to/internal/). Since we'll soon start work on unifying them, maybe it's best to leave the docs alone for now.
