### ISSUE TITLE
Install gitdocs as a devDependency

### ISSUE THREAD

**Issue by abenettt** [forem/forem#9461]
**Is your feature request related to a problem? Please describe.**
Currently running the documentation locally requires one to install the tool `gitdocs` globally or running it via `npx` or `yarn dlx`. 

**Describe the solution you'd like**
Installing `gitdocs` as a devDependency allows the version to be specified and the documentation can still be started by running `yarn gitdocs serve` or `yarn run gitdocs serve` if one would want to be explicit. This would remove one step in the setup of the project and would not make it dependant on tools outside the repository.

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks @abenettt, make sense!

I think the reason why we stuck to the global installation was because we followed https://gitdocs.netlify.app/installation/ which specifies to install it as a global dependency.

We should probably revisit that decision
