### ISSUE TITLE
Add more login options to global-signup-modal

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9467]
**Is your feature request related to a problem? Please describe.**

This is an optimization of the new devise 'invite' functionality. At the moment it isn't present on all sign up modals. This is just a request to add it to the global sign up modal used throughout the platform when trying to perform an action that requires login (until authentication as a whole is refactored).

This can help smaller communities whom are restricted by Twitter as an auth provider.

**Describe the solution you'd like**

Just an updated to include 'more sign in options' as per the standard registration forms.

**Additional context**

See screenshot where 'more sign in options' is not included in the global-signup-modal
<img width="1563" alt="Screenshot 2020-07-23 at 11 48 34" src="https://user-images.githubusercontent.com/12694270/88285369-dbc6ba80-cce6-11ea-8020-a2a015303e08.png">

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).
