### ISSUE TITLE
Not able to post articles

### ISSUE THREAD

**Issue by ezequielfarrell** [forem/forem#9468]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
@ezequielfarrell can you add more details to the bug? What errors are you receiving? Any logged errors in the console? Thank you!

**Comment by citizen428** [comment]
Hello @ezequielfarrell, thanks for notifying us of this problem, this looks an issue specific to your account.
Please email yo@dev.to for more help.
