### ISSUE TITLE
Water Cooler Connect Link Issue

### ISSUE THREAD

**Issue by 802ScubaFish** [forem/forem#9470]
**Describe the bug**

When on the main channel, while opening the discussion side bar, then selecting 'connect' under the water cooler channel the link appears to break at that point.

**To Reproduce**

Open the main panel discussion video. 
Click See Discussion on the right side of the video. 
Scroll down to where it lists the other channel options. Click 'connect' under 'Water cooler'. 
At this point it should return an error 

**Expected behavior**

I expected it to connect me to the water cooler discussion page
**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: moz. firefox
- Version: latest version

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by fdoxyz** [comment]
Really appreciate the early notice on this @802ScubaFish and thank you for tuning in to Codeland!

We were able to sort out the initial issues with our integrations so closing this now
