### ISSUE TITLE
Make new messages in Connect more apparent 

### ISSUE THREAD

**Issue by TerabyteTiger** [forem/forem#9471]
**Is your feature request related to a problem? Please describe.**

Jumping around in the Codeland Connect channels, I noticed that it was fairly difficult to find where the new messages started and previously seen messages ended.

**Describe the solution you'd like**

It would be helpful to include a indicator below the last message that would have been seen the last time the user was viewing the messages. Probably matching the button colors? 

**Describe alternatives you've considered**

Potentially highlighting new messages for a short time when opening the chat could work too? I've also seen other platforms flash the first new message when you reach it, or start you at the first new message instead of at the bottom of the chat.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by sarthology** [comment]
@citizen428 I can work on this.

**Comment by nickytonline** [comment]
Assigned this to you @sarthology.

**Comment by rhymes** [comment]
Are you still working on this @sarthology ? Let me know, otherwise I can unassign it from you

**Comment by sarthology** [comment]
@rhymes Yes, I am. It's a tough one as need to make some changes in the messages table in DB.

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
