### ISSUE TITLE
Highlight @ mentions in Connect 

### ISSUE THREAD

**Issue by TerabyteTiger** [forem/forem#9472]
**Is your feature request related to a problem? Please describe.**

When using Connect, @ mentions directed at the logged in user look identical to @ mentions to other users.

**Describe the solution you'd like**

It would be much easier to find messages directed at you if your @ mentions were highlighted in some way (See Twitch example below). 

**Describe alternatives you've considered**

Bolding and coloring the text a different color could also work and be more subtle. 

**Additional context**

Image example of Twitch's approach: 

![Twitch Chat showing highlighting for @ users vs @ logged in user](https://user-images.githubusercontent.com/16465776/88317779-c56d2e80-cce7-11ea-9d60-8b8f2a753690.png)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
I think this is a neat idea! One thing to keep in mind and consider while working on this is to remember about making it visible and distinguishable no matter what theme are you on. 

@TerabyteTiger would you like to work on it maybe?

**Comment by TerabyteTiger** [comment]
@ludwiczakpawel As much fun as I'd probably have working on this, I don't want to go through the headache of setting up WSL. 

I'll gladly offer additional feedback from the user side to whoever does want to take this on though as needed!

**Comment by timorthi** [comment]
I'd like to take a stab at this! Been away from the platform & codebase for a while now and this feature seems like a good way to get my feet wet again.

**Comment by ludwiczakpawel** [comment]
@timorthi go for it! 💯

I'm assigning you to this one :)

**Comment by timorthi** [comment]
@ludwiczakpawel Thanks! Does the core team have any opinions on how this should look (apart from your comment about it being viable across different themes)?

**Comment by ludwiczakpawel** [comment]
@timorthi i don't think so to be honest. maybe just wrap the username with `<mark>` tag so it gets default browser yellow highlight.

**Comment by rhymes** [comment]
Hi @timorthi, are you still working on this? Let us know in case you need help

**Comment by timorthi** [comment]
Hey @rhymes , sorry for not updating. I ran into a few issues setting up the project (#9604, #9779), preventing me from getting any meaningful work done, and admittedly just kind of gave up.  

I'll try setting up the project again, this time without Docker. I'd still like to work on this ticket, but I'll report back if I'm not making meaningful progress in setting up my local environment, so someone else can take over. 😄

**Comment by rhymes** [comment]
@timorthi thank you for taking the time to circle back on this!

**Comment by citizen428** [comment]
#10216 has been merged, closing this.
