### ISSUE TITLE
[Article] Fix Series widget margin issue

### ISSUE THREAD

**Issue by lisasy** [forem/forem#9486]
![image](https://user-images.githubusercontent.com/833231/88708854-4c544980-d0e2-11ea-8148-b5d18cab01c1.png)

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a Forem team member and is not up for grabs.

**Comment by nickytonline** [comment]
Looks like 9202 is working on this but it is pretty stale.
