### ISSUE TITLE
[Posts] Support slides.com embeds

### ISSUE THREAD

**Issue by ortonomy** [forem/forem#9487]
**Is your feature request related to a problem? Please describe.**

I was trying to write my first article the other day with a link to a slide set that I'd made on https://slides.com. It was frustrating to not be able to embed the slides in the code. 

**Describe the solution you'd like**

Slides.com supports code snippets inside the slides decks, so it's **really** good for developers and tech presentations. I understand why the forem composer doesn't support direct iframe embeds, but it'd be great if there was some liquid tags / 
 to insert a slides.com deck

**Describe alternatives you've considered**

I considered slideshare but 

a) it's linkedin connected
b) I'd have to use either a) their composer or b) PPT. Ugh.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by Link2Twenty** [comment]
Looking at the [documentation](https://help.slides.com/knowledgebase/articles/254996-embedding-decks) the liquid tag just needs to load in an iframe.

We would need username, slide name, a start page (default 0), theme (default dark).

To match current convention we'd do something like this.

```md
{% slides user/slide_name start_page=2 theme=light %}
```

Which would fill in this URL
```md
https://slides.com/{user/slide_name}/embed?style={theme}#/{start_page}
```

**Comment by nickytonline** [comment]
Want to take this one on @Link2Twenty ?

**Comment by rhymes** [comment]
As we review our integration with external services, I went ahead and removed the `ready for dev` label in the meantime

**Comment by cmgorton** [comment]
Thank you for opening this request!
Since this has been open for awhile without much progress I am going to close it here. 

The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
