### ISSUE TITLE
Update Installation docs to WSL2

### ISSUE THREAD

**Issue by Amorpheuz** [forem/forem#9489]
**Is your feature request related to a problem? Please describe.**
It isn't a problem per say, but can be a good QoL addition. With the release of WSL2 in Windows Stable, a ton of benefits are brought to table, particularly in the performance aspect. Forem being a medium-large repository could definitely benefit from those improvements. Apart from that, the Full Linux kernel aspect ensures that everything can be smoothly installed to Linux itself and will also work with less hiccups.

Apart from that Docker Desktop has also been brought to Home Edition of Windows with WSL2. So an update to those docs in case of full compatibility would be great!

**Describe the solution you'd like**
Software and dependencies mentioned in the [Windows Installation docs](https://docs.dev.to/installation/windows/) are moved to a Linux-only installation instead of part Linux, part Windows.

**Describe alternatives you've considered**
Continuing with the current mixed installation.

**Additional context**
Here's [A comparison of WSL-1 & 2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions) along-with many [FAQs - General](https://docs.microsoft.com/en-us/windows/wsl/faq) and [FAQs WSL2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq) that might help take a decision on this.

I would love to help resolve this issue, if approved!

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
This is approved @Amorpheuz !

**Comment by Amorpheuz** [comment]
Hey @maestromac and @rhymes, just had some doubts which I would love to get cleared before I start:

- Is there any particular way in which the updates to the docs would be preferred? Should I send a PR section by section, e.g. Imagemagick, then PostgreSQL and so on...? 

- Also, are you looking to parallelly maintain the current mixed version and want WSL2 only as a separate page or will overwriting the current one with WSL2 is the way to go?

**Comment by maestromac** [comment]
@Amorpheuz 

- We're okay if you want to do section by section or the thing in one go. You could also do 2 sections at a time too. This is up to you.
- I'd say because WinVer 2004 is generally available and WSL2 is very well received, we should make it our default installation method. You can add a note that there are a few other ways but we recommend complete WSL2.
