### ISSUE TITLE
Dev.to signUp with GitHub not able to comment.

### ISSUE THREAD

**Issue by ivanjeremic** [forem/forem#9490]
I have 2 accounts on Dev.to the first one is where I signed up with GitHub but this one was not able to comment all I get when trying to send a comment is a loading animation. This was the reason I signed also with twitter up for Dev and now everything works fine, however, I would like to have the account linked to my GitHub be my main account can anyone look at his issue and why accounts using GitHub are not able to comment?

**Comment by rhymes** [comment]
Hello @ivanjeremic, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
