### ISSUE TITLE
[Connect] Room name overflows (sidecar)

### ISSUE THREAD

**Issue by wafflewitch** [forem/forem#9499]
**Describe the bug**

Sometimes the room name overflows when accessing Connect via the sidecar.

**To Reproduce**

**Expected behavior**

The room name should be made to wrap so that it fits within the box and does not overflow and run off the screen.

**Screenshots**

<img width="514" alt="dev_connect_sidecar_room-name-overflow" src="https://user-images.githubusercontent.com/27379918/88434323-91683b00-cdc5-11ea-8b86-4a16e354d187.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 83.0.4103.116

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by juliannatetreault** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by Veggier** [comment]
I will try to work on this issue

**Comment by nickytonline** [comment]
Sounds good @Veggier. I'll assign it to you.

**Comment by cmgorton** [comment]
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)
