### ISSUE TITLE
[Connect] User cannot change their mind after declining a room invite

### ISSUE THREAD

**Issue by wafflewitch** [forem/forem#9500]
**Describe the bug**

After declining to join a room and changing their mind, user cannot access the accept/decline view again.

**Expected behavior**

User should be able to access the accept/decline view again.

**Screenshots**

![dev_connect_decline-invite-no-return](https://user-images.githubusercontent.com/27379918/88435367-a5ad3780-cdc7-11ea-9e7e-31cffcb4ad1d.gif)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 83.0.4103.116

**Comment by juliannatetreault** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by sarthology** [comment]
@benhalpern @nickytonline What do you guys suggest here? 
Not sure if it's a bug. I can make show a undo button for 5sec, but what do you guys think?

**Comment by nickytonline** [comment]
I don't think this is a bug either. It sounds more like a feature. I would see what other platforms or services do.
