### ISSUE TITLE
[Connect] Room that has been left still shows up in URL

### ISSUE THREAD

**Issue by wafflewitch** [forem/forem#9501]
**Describe the bug**

After leaving a room and then navigating to the /connect view, the room that was left still shows up in the URL.

**To Reproduce**

**Expected behavior**

Any room that has been left should not appear in the URL again when navigating to /connect.

**Screenshots**

![dev_connect_left-room-in-url](https://user-images.githubusercontent.com/27379918/88435904-cc1fa280-cdc8-11ea-85ba-7b01531876cc.gif)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 83.0.4103.116

**Comment by juliannatetreault** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by sarthology** [comment]
@nickytonline Please assign this to me.
