### ISSUE TITLE
[Connect] When joining a new room, user is not taken to the new room

### ISSUE THREAD

**Issue by wafflewitch** [forem/forem#9503]
**Describe the bug**

Sometimes when joining a new room, the room that gets displayed to the user is actually a previously joined room and not the room that the user has just joined. This feels unintuitive and might lead to confusion.

**To Reproduce**

**Expected behavior**

Upon joining a new room, the user should always be taken to that room.

**Screenshots**

![dev_connect_wrong-room-after-accepting-invite](https://user-images.githubusercontent.com/27379918/88437571-59b0c180-cdcc-11ea-9e45-9709bcaadf69.gif)
Here you can see the room the user wants to join is called "show-and-tell", but upon accepting the invite, the room that displays is one that the user previously joined, called "watercooler".

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 83.0.4103.116

**Comment by juliannatetreault** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by sarthology** [comment]
I'm gonna pick this.
