### ISSUE TITLE
Change branch to Main/Version for actions/checkout in rebase.yml

### ISSUE THREAD

**Issue by Amorpheuz** [forem/forem#9510]
**Describe the bug**
The current `rebase.yml` workflow file uses the `master` branch of `actions/checkout` action.
https://github.com/forem/forem/blob/95be4c6308e08d015595617f6e3297d6d709b572/.github/workflows/rebase.yml#L20

 The default branch for the same has moved to `main` though which leads to the following warning in the workflow's run page.

**To Reproduce**

- To view:
  1. Open [Actions tab](https://github.com/forem/forem/actions).
  2. Filter to `Automatic Rebase` Workflow from the list of workflows on left.
  3. Open a recent run.
- To reproduce:
  1. The workflow is triggered every time there is a comment on Pull Request, thus a comment on a PR/Issue should be enough to generate a Run.

**Expected behavior**
Warning doesn't get printed and a specific version/main is pointed in order to ensure stability.

**Screenshots**
![image](https://user-images.githubusercontent.com/22113778/88451649-fed3a480-ce75-11ea-8cd0-5dfff6d7638f.png)

**Additional context**
- Link to [actions/checkout](https://github.com/actions/checkout).
- I would love to help fix this warning.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@Amorpheuz I've assigned the issue to you

**Comment by Amorpheuz** [comment]
Forgot to add the `Fixes`. 🙈

Fixed by #9515.
