### ISSUE TITLE
Set up Github project board #setup

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#9540]
Set up Github project board for the Admin/Internal project and let the team know how we're going to use it!

**Comment by joshpuetz** [comment]
@lisasy @fdoxyz @ludwiczakpawel Here's what I've got so far: 

- a project board at https://github.com/forem/forem/projects/25
- An attempt to try to do some scoping. I add some cards as tasks and put them under 'unscoped':

<img width="583" alt="_HellsBells___Admin_Internal_Consolidation" src="https://user-images.githubusercontent.com/37842/88577453-a8e53500-d00c-11ea-9252-c5e09f0f4e62.png">

- To create a scope: I created a card with a hashtag, and dragged my cards under it (and added that hashtag to each of the cards):

<img width="563" alt="_HellsBells___Admin_Internal_Consolidation" src="https://user-images.githubusercontent.com/37842/88577534-c74b3080-d00c-11ea-82b5-cc252e066457.png">

- If I were to start working on a card, I'd convert it to an issue, assign myself, and move it to either 'figuring out' or 'in progress'  That will end up looking like this:

<img width="380" alt="_HellsBells___Admin_Internal_Consolidation" src="https://user-images.githubusercontent.com/37842/88577675-08434500-d00d-11ea-873c-458773795f86.png">

(**Note** that the hashtag comes along for the ride!)

- Want to see just a single scope? Use the hashtag and filter:

<img width="1377" alt="_HellsBells___Admin_Internal_Consolidation" src="https://user-images.githubusercontent.com/37842/88577867-493b5980-d00d-11ea-936e-fcf3cb64e9a7.png">

**Comment by fdoxyz** [comment]
I like the idea here! Seems very organized although the responsibility to keep it that way is decentralized, hope we can keep it up 😅

My only concern is adding issues for certain tasks may seem like adding overhead to team OSS. Would having a column for "In progress" for each one of us be too much? Not feeling strongly about this suggestion, I like the overall process for this

I so wish cards could be "assigned"!
