### ISSUE TITLE
Remove redundant vscode extension reccomendations

### ISSUE THREAD

**Issue by abenerd** [forem/forem#9549]
**Is your feature request related to a problem? Please describe.**
With the addition of the `nickytonline.dev-to-extension-pack` the same extensions must not be recommended again.  

**Describe the solution you'd like**
Remove recommended extension that are within the `nickytonline.dev-to-extension-pack`.

**Describe alternatives you've considered**

**Additional context**

**Comment by nickytonline** [comment]
I'm fine with removing this. The idea originally was to have an extension pack with all the extensions we use, but then in another PR it was suggested to keep the extension pack and the separate extensions.

**Comment by abenettt** [comment]
I do not see the point of this. The way I understand it the point of the extension pack is to have all the recommended extension bundled together, why would one go and add them again separately? But maybe there was another reason I don't know about.

**Comment by nickytonline** [comment]
Yeah, that is the idea of the extension pack. I think their reasoning was to pick and choose or go all in with the extension pack. In retrospect, doesn't make much sense. Just having the separate extensions probably makes more sense if people do not want to install all of them.

Sound good to you @citizen428 ?

**Comment by citizen428** [comment]
Definitely, IIRC I voiced this concern during the original PR.
