### ISSUE TITLE
Podcasts to add

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#955]
We have not really done a good job of keeping up the podcast section, but we want to do this better.

Admins add podcasts with the consent of the hosts (We're just an RSS player like any other podcast app so we probably don't need permission but I think it makes sense)

Anyway, if you run a dev podcast, feel free to post here and we'll add it.

**Comment by GaProgMan** [comment]
I'd like to put [The 6 Figure Developer](https://6figuredev.com/). In case it's required, here is [the RSS feed](http://6figuredev.com/feed/rss/) for the show.

I'd also like to put forward [The .NET Core Podcast](https://dotnetcore.show/). Again, the RSS feed, if required, is available [here](https://thedotnetcorepodcast.libsyn.com/rss).

**Comment by GaProgMan** [comment]
Title: The .NET Core Podcast
Feed URL: https://thedotnetcorepodcast.libsyn.com/rss
iTunes URL/ Overcast URL: https://itunes.apple.com/gb/podcast/the-net-core-podcast/id1433496275
Android URL: https://subscribeonandroid.com/thedotnetcorepodcast.libsyn.com/rss
Website url: https://dotnetcore.show
Twitter username: @dotnetcoreblog
Pattern image: https://dotnetcore.show/content/images/2018/07/Header-Image-2.jpg
Image: https://dotnetcore.show/content/images/2018/08/jamie-taylor-logo-podcast.svg

**Comment by ovation22** [comment]
Title: The 6 Figure Developer Podcast
Feed URL: https://6figuredev.com/feed/podcast/
iTunes URL/ Overcast URL: https://itunes.apple.com/us/podcast/the-6-figure-developer-podcast/id1217530572
Android URL: https://subscribeonandroid.com/6figuredev.com/feed/podcast/
Website url: https://6figuredev.com/
Twitter username: @6FigureDev
Pattern image: https://6figuredev.com/wp-content/uploads/2018/10/TwitterCover.jpg
Image: https://6figuredev.com/wp-content/uploads/2017/03/6FigurePodcast600.png

**Comment by tedcarstensen** [comment]
Title: EnterpriseReady
Feed URL: https://www.heavybit.com/category/library/podcasts/enterpriseready/feed
iTunes URL/ Overcast URL: https://itunes.apple.com/us/podcast/enterpriseready/id1437951282
Android URL: https://play.google.com/music/listen#/ps/Iq3uifjva44tdvm2orhu4apvjtu
Website url: https://www.heavybit.com/library/podcasts/enterpriseready/
Twitter username: @heavybit
Pattern image: https://www.heavybit.com/wp-content/uploads/2018/10/enterpriseready-wide-artwork.jpg
Image: https://www.heavybit.com/wp-content/uploads/2018/10/enterpriseready.jpg

Title: o11ycast
Feed URL: https://www.heavybit.com/category/library/podcasts/o11ycast/feed
iTunes URL/ Overcast URL: https://itunes.apple.com/us/podcast/o11ycast/id1399777237?mt=2
Android URL: https://play.google.com/music/m/Iqltue6xwsxlkwjpwn2ufnd5taq?t=O11ycast
Website url: https://www.heavybit.com/library/podcasts/o11ycast/
Twitter username: @heavybit
Pattern image: https://www.heavybit.com/wp-content/uploads/2018/06/ollycast-artwork-wide.jpg
Image: https://www.heavybit.com/wp-content/uploads/2018/06/ollycast-artwork.jpg

Title: High Leverage
Feed URL: https://www.heavybit.com/category/library/podcasts/high-leverage/feed
iTunes URL/ Overcast URL: https://itunes.apple.com/us/podcast/high-leverage/id1441169370
Android URL: not yet approved
Website url: https://www.heavybit.com/library/podcasts/high-leverage/
Twitter username: @heavybit
Pattern image: https://www.heavybit.com/wp-content/uploads/2018/11/high-leverage-wide.jpg
Image: https://www.heavybit.com/wp-content/uploads/2018/11/high-leverage.png

**Comment by Zhao-Andy** [comment]
@GaProgMan @ovation22 @tedcarstensen we've added your podcasts!
https://dev.to/dotnetcorepodcast
https://dev.to/6figuredev
https://dev.to/enterpriseready
https://dev.to/o11ycast
https://dev.to/highleverage

@equiman Syntax was already on the list. 👍 
https://dev.to/syntax

Let us know if anything looks amiss.
