### ISSUE TITLE
Unable to write a new post

### ISSUE THREAD

**Issue by TilakMaddy** [forem/forem#9554]
![Screenshot 2020-07-28 at 6 54 35 PM](https://user-images.githubusercontent.com/11134428/88671378-dcef5180-d103-11ea-9392-7581d761f454.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

![Screenshot 2020-07-28 at 6 54 35 PM](https://user-images.githubusercontent.com/11134428/88671407-e4165f80-d103-11ea-910e-d255a58e08bc.png)
![Uploading Screenshot 2020-07-28 at 6.54.35 PM.png…]()

**Comment by TilakMaddy** [comment]
mac OS, chrome browserVersion 84.0.4147.89  as well as safari browser

**Comment by TilakMaddy** [comment]
this seems to happen only with my account cuz i have seen new posts in the past 3 mins whereas I, have had this problem for 30 minutes.

**Comment by jacobherrington** [comment]
Hey @TilakMaddy, this might be an issue that is specific to your account!

Shoot an email to yo@dev.to and we can try to get the issue resolved. Thanks!
