### ISSUE TITLE
Update Documentation to Include Backend Configurations Setup

### ISSUE THREAD

**Issue by PrimeNoodles** [forem/forem#9559]
**Is your feature request related to a problem? Please describe.**

When installing devto locally to test for changes, people have recently run into the issue of their setup page not being completed and the need to go to the configurations page to make changes. However, the user is generally denied access to this page. In order to access it, they would need to give themselves the an admin role (ex. super_admin) to see the internals/configs page. They would also have to give themselves the single_resource_admin role to make changes to the page and it was thanks to @Veggier that I was able to find https://github.com/forem/forem/pull/8435 to see which pre-deploy values needed to be entered.

**Describe the solution you'd like**

Update the documentation in the Backend Guide Configuration to include the changes or make a new section dedicated to this.

**Describe alternatives you've considered**

Perhaps make a new installation preset the configurations page so there's no need to manually setup the page, though this might not be a good fix.

**Additional context**

issue people see:
![image](https://user-images.githubusercontent.com/35935438/88697042-04c5c180-d0d2-11ea-8605-8c4aace1b6a7.png)

**Comment by Ridhwana** [comment]
NOTE: We'll be adding this to `app_initializer:setup forem:setup` + some explanation in the docs, once [this PR](https://github.com/forem/forem/pull/9605) gets merged.

**Comment by cmgorton** [comment]
Looks like this was added per #9664. Let me know if that is not correct and I can reopen this issue. Thanks!
