### ISSUE TITLE
Avatars not showing mobile

### ISSUE THREAD

**Issue by garretcharp** [forem/forem#9574]
**Describe the bug**

On mobile (android) while browsing the posts from the feed, the avatars on the post just shows "undefined profile" rather than a users actual avatar image. Everywhere else it seems to show just fine.

**To Reproduce**

Open the mobile app and go to the posts feed, it should say "undefined profile" where users avatars should be.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device: Android Note 8
- OS: Android Pie 9.0 with One UI 1.0
- Browser: App
- Version: 1.4.1

**Additional context**

**Comment by rhymes** [comment]
Hi @garretcharp, thanks for the heads up, we're aware of the issue and are working on it. Will let you know ASAP

**Comment by Ridhwana** [comment]
Hi @garretcharp, we had fixed this issue soon thereafter, everything is working as normal now. Hence I will close this issue :)
