### ISSUE TITLE
Make users authenticating into email flow to land on Home feed, not Dashboard

### ISSUE THREAD

**Issue by lisasy** [forem/forem#9575]
**Describe the bug**

Currently, when a user signs into Forem via the new email+password auth method, they land on their Dashboard. The more ideal experience is for them to land on their Home feed. Not only is the Home more relevant to them, but changing the flow to this will keep this in parity with Twitter/Github auth.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a Forem team member and is not up for grabs.

**Comment by lisasy** [comment]
This issue has been resolved.
