### ISSUE TITLE
Error in a saved tag #español

### ISSUE THREAD

**Issue by badiali** [forem/forem#9581]
**Describe the bug**

I have a tag #español saved in the section "MY TAGS" that when pressing it gives an error.

**To Reproduce**

1. Go to: [https://dev.to/t/español](https://dev.to/t/espa%C3%B1ol)

**Expected behavior**

At some point I was able to perform that search and save that tag, but it has stopped working and now I cannot delete it. Now I use the tag #spanish

**Screenshots**

![Captura de pantalla 2020-07-31 a las 10 27 43](https://user-images.githubusercontent.com/8589135/89016724-7cd1f880-d319-11ea-82f7-5a4dec8becde.png)

![Captura de pantalla 2020-07-31 a las 10 22 57](https://user-images.githubusercontent.com/8589135/89016734-8196ac80-d319-11ea-973f-bbfbfa7607df.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Google Chrome
- Version: 84.0.4147.105 (Build oficial) (64 bits)

**Comment by Ridhwana** [comment]
Hi @badiali, thank you for your issue and apologies for the inconvenience. 

I've investigated this, and we had most likely merged [this PR where we validate tag names](https://github.com/forem/forem/pull/9006) after you had created your tag, hence allowing you to use #español previously. If you look at the [validate_name method on the tag model](https://github.com/forem/forem/blob/master/app/models/tag.rb#L80), you'll notice that we have stopped allowing tags that contain non-ASCII characters. 

However, given that I18n is on our generalization roadmap, we will have to revisit this decision. Once we do, we will then add functionality to encode/decode tag slugs, but until we are able to reach that milestone you may need to use https://dev.to/t/espanol or as you said https://dev.to/t/spanish.  

For now I will close this issue, as this is on our internal I18n roadmap. Hope this helps.
