### ISSUE TITLE
Markdown parser cannot handle inline code in list items

### ISSUE THREAD

**Issue by yamalight** [forem/forem#960]
**Describe the bug**

Trying to create a list items with inline code results either in broken rendering or in error thrown by parser.

**To Reproduce**

1. Create new post
2. Write a simple list, e.g.:
    ```
    1. some text
    2. some more text
    ```
3. Preview - works as expected.
4. Add code snippet to list, e.g.:
    ```
    1. some text
        ```
        some code here
        ```
    2. some more text
    ```
4. Preview - will result in code snippet expanding to second list item
5. Attempt to specify code langauge, e.g.:
    ```
    1. some text
        ```sh
        some code here
        ```
    2. some more text
    ```
6. Preview - will result in following error:
```
1 error prohibited this article from being previewed:
Liquid syntax error: 'raw' tag was never closed
```

**Expected behavior**

List should render with code inlined with text (like here on github)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Chrome
- Version 70

**Comment by maestromac** [comment]
Thanks for reporting this @yamalight . This happening because our MarkdownParser is escaping all code-block with a `{% raw %}` to avoid being processed by LiquidTag. The escape process definitely the culprit.

**Comment by aspittel** [comment]
After doing some debugging, this actually looks like an issue in RedCarpet -- https://github.com/vmg/redcarpet/issues/664

**Comment by mstruve** [comment]
Thank you so much for submitting this issue. Since it looks to be an issue with the redcarpet gem I am going to close this. Please reach out if you have any questions. Thanks!
