### ISSUE TITLE
Extra CSS style for <code><a href= links

### ISSUE THREAD

**Issue by PELock** [forem/forem#9603]
Consider this:

```html
<code><a href="https://www.php.net/manual/en/function.set-time-limit.php">set_time_limit(10 * 60);</a></code>
```

or this code in editor:

```html
<a href="https://www.php.net/manual/en/function.system.php"><code>system()</code></a>
```

In output it shows a regular code chunk, without any indication it's actually a link, no underline, no hover effect. Consider adding some sort of indication it's a link (maybe dotted underline with some other background color for the ```<code>``` element?

**Comment by Coteh** [comment]
Hey I'd like to tackle this. :)

**Comment by fdoxyz** [comment]
Thank you @Coteh I just assigned the issue to you
