### ISSUE TITLE
Ability to Lock Threads

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#9619]
**Is your feature request related to a problem? Please describe.**

Give admins and users the ability to 'lock' comment threads.

**Describe the solution you'd like**
- Admin can lock comments on an article - possibly through internal/articles?
- User can lock comments on their article - possibly through their dashboard?
- There should be a visual cue to readers that the comment thread is locked. 
- Existing comments should continue to be displayed.
- Users have the option to re-enable comments.

**Additional context**
Here's an old issue (very similar) issue that has some discussion: https://github.com/forem/forem/issues/423

**Comment by ludwiczakpawel** [comment]
@jessleenyc should that be an option for Mods as well? So they can close comments on someone's article?

**Comment by jessleenyc** [comment]
@ludwiczakpawel I think that _could_ be an option but if so, I'd like to add a config so that admins can decide whether or not mods can take that action, or what types of mods could. For example, I could see us potentially giving tag mods that ability, but definitely not our general community mods.

**Comment by ludwiczakpawel** [comment]
Another thing that popped in my mind: When post authors lock the thread, will they still be able to add new comments OR reply? Same question for other user types (mods, admins).

Also, if mod/admin locks the thread, should post author still be able to add comments or reply?

Another thing to consider - when thread is locked by admin or mod, we should probably send notification to post author.

**Comment by ludwiczakpawel** [comment]
Some initial explorations of flows for post author and mods: https://www.figma.com/file/7JNGZfliyJpRRKN0QHQFf1/Locking-comments?node-id=1%3A2

**Comment by benhalpern** [comment]
All the design here looks great. I think we want to finalize our thoughts on _permissions_. Who can close a thread?

Tag mods? Admins only? Authors of the post?

I'd say this is probably going to need to be forem-by-forem config. For DEV I think it makes sense if admins and post authors can close threads but not mods. (At least for now).
