### ISSUE TITLE
App crashes immediately (can't open) 

### ISSUE THREAD

**Issue by uzair004** [forem/forem#9635]
**Bug Description**

related to DEV android app
Can't open App , crashes immediately when clicked. 
**_Error Message_** "_Unfortunately DEV stop working_"

**To Reproduce**

1. Update Android System Web view to _version 84.0.4147.111_
2. Update DEV android app to _version 1.4.1_
3. Click app to open it.

> This issue is tested on Android 5.0 version. others version may not yield same result.

**Expected behavior**

Clicking app should open it to be used as intended. should let user view content and posts.
BUT instead it shows error and redirect back to home menu.

**Screenshots**

![bug image](https://user-images.githubusercontent.com/34101864/89408700-2cec9a80-d73a-11ea-8ae1-fd47c36b6707.jpeg)

**Smartphone:**

- Device: Lenovo P-70 
- OS: Android
- Browser: Google Chrome 84.0.4147.111 (release date: july 29 2020)
- Version: 5.0 Lollipop

**Additional context**

Recently downloaded DEV to app , signed up account and used it a bit.
But after i **updated** my _DEV app_ and _Android Web View_ to latest versions as mentioned above.
DEV app released date: July 21, 2020
Web View released date: July 29, 2020
app disappeared from my Home Menu launcher. 
try opening it from file manager but it throws error. "Unfortunately DEV stop working".
Bug might be in Newer version of DEV app 
OR
latest version of Android Web View may have changes that breaks the app and its not compatible.

**Comment by fdoxyz** [comment]
Hello @uzair004 thank you for the report. Sorry to hear about this, on newer Android versions we're not seeing this problem but we'll investigate so we can try and keep the app as backwards compatible as possible.

I recreated this issue over in the Android repo so we can keep track of it over there, closing this now.
