### ISSUE TITLE
DEV inaccessible on Vivaldi due to Service Worker

### ISSUE THREAD

**Issue by dev-encourt** [forem/forem#9642]
**Describe the bug**
A user wrote in...
"Every couple of days, I can't browse dev.to. I found out it's related to the service worker you register (in screenshots). When I manually unregister the SW (from dev tools) the website works again."

**Expected behavior**

DEV.to should be accessible using Vivaldi .

**Screenshots**

![image](https://user-images.githubusercontent.com/51792350/89446886-1e46b900-d723-11ea-8dc3-f6c60820de87.png)

**Desktop (please complete the following information):**

Vivaldi | 2.11.1811.49 (Stable channel) (64-bit)
Revision | cac8cb477e6de02013662fb5f48ac1a82bca666b
OS | macOS Version 10.15.4 (Build 19E287)
JavaScript | V8 8.0.426.27
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.158 Safari/537.36

**Comment by rhymes** [comment]
@dev-encourt is this still happening to you?

**Comment by mstruve** [comment]
Hi there! We recently removed the majority of our Service Worker caching in #12834 With that change, I believe that this should no longer be an issue going forward. I am going to close this, please feel free to reopen if you continue to see this problem.
