### ISSUE TITLE
Ability to block user on profile page or from comment directly

### ISSUE THREAD

**Issue by stereoplegic** [forem/forem#9644]
**Is your feature request related to a problem? Please describe.**

I never thought I'd say this about DEV, but I recently got into a comment fight more akin to Reddit. For my part, I'll admit that I kept replying for far longer than I should have. I believe the ability to use blockquote in replies is critical, but the user in question proceeded to edit a comment I quoted and insinuate that I was a liar (in addition to other personal attacks he made before and after). On other networks, it is easy to cut such a toxic conversation short by simply blocking the user.

**Describe the solution you'd like**

Ability to block users from their profile page a la Facebook, or possibly from the comment itself (similar to existing "Report Abuse" functionality in comments).

**Describe alternatives you've considered**

"Report Abuse" is the only existing alternative I can think of.

**Additional context**

Can't really think of any. Don't want to see this user, don't want them to see me. That's all.

**Comment by citizen428** [comment]
Thanks for the report @stereoplegic and sorry that you had a bad experience on DEV! 

You can already block a user directly from their profile page, even though it is a bit hidden in the "dot menu":

<img width="1271" alt="Ben_Halpern_-_DEV_Community_👩💻👨💻" src="https://user-images.githubusercontent.com/47985/89485922-0b3bf380-d7cc-11ea-9215-989f76122ce0.png">

Additionally, if you think that this user really overstepped, don't hesitate to use the "Report Abuse" option on the comment so our support team can look into it.

<img width="231" alt="The_Wings_of_the_Dove_Neque_nihil_-_DEV_Community_👩💻👨💻" src="https://user-images.githubusercontent.com/47985/89486402-307d3180-d7cd-11ea-82f3-22da0a024896.png">

Does this resolve your issue?

**Comment by stereoplegic** [comment]
Yeah, I swear I looked there are didn't see it. 🤦🏼‍♂️ I'll chalk it up to a busy work day coupled with the aforementioned distraction. Please don't block Ben just to help me. 😉

**Comment by citizen428** [comment]
> Please don't block Ben just to help me. 😉

Nah, he had it coming anyway 😉
