### ISSUE TITLE
Add Twitter Link to settings page (NOT OAUTH)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [forem/forem#9646]
**Is your feature request related to a problem? Please describe.**

I want to have a link to my twitter profile show up below my posts. Currently the only option for this is to give DEV permissions to access my Twitter account, which is a completely unnecessary invasion of privacy and security in exchange for an `<a>` tag.

**Describe the solution you'd like**

Twitter should be a field in the Links section of the settings page, like any other social media site.

**Describe alternatives you've considered**

* *Manually* typing out the link at the end of every point. No.
* Using a different platform to post content to that doesn't require workarounds.

**Additional context**

**Comment by cmgorton** [comment]
Thanks for this request. Since this is similar to #11404 and I have already tagged that as a potential RFC(a feature request we may work on internally) I am going to close this issue.
