### ISSUE TITLE
[Dev.to] - Profile header height too small for infobox

### ISSUE THREAD

**Issue by zfett** [forem/forem#9647]
**Describe the bug**

On my dev.to profile (@zfett), my infobox on the right of my header has a vertical scroll due to the height. Using Firefox Version 79.0 64-bit. Tested in Edge with the same result.

**To Reproduce**

1. Fill out enough information in your infobox, try filling out your email, work, location, and education.
2. Visit your profile page
3. Height should overflow on Firefox.

**Expected behavior**

.user-profile-header should resize in height with .user-metadata-details to prevent vertical overflow on the default breakpoint.

**Screenshots**

![screenshot](https://imgur.com/JJEKrnX.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10 Home, 10.0.18363 Build 18363
- Browser: Firefox
- Version: 79.0

**Additional context**

This only happens when the page width is at or above the 1216px breakpoint. The minute you resize it below that point and the content reflows, it no longer suffers from this issue.

**Comment by zfett** [comment]
I'd also like to note, I loaded my page in a private window where I was not logged in, and got the same result. It seems to be exclusively a CSS issue.

**Comment by Amorpheuz** [comment]
I would like to work on this issue!

**Comment by rhymes** [comment]
@Amorpheuz sure! I suspect our designers @ludwiczakpawel and @lisasy might have directions here. I might be wrong but having an ever growing header height might be an issue if people start putting lots of text there.

**Comment by Amorpheuz** [comment]
Great! I was thinking of getting their opinions on the same too before I started working on this. Will wait for their guidance!

**Comment by ludwiczakpawel** [comment]
@rhymes @Amorpheuz this is something we're literally looking into at this very moment - we're working on little fixes for profile and this is one of the things on my plate right now. So this time I may just claim this one and assign myself. Is that ok?

**Comment by Amorpheuz** [comment]
That's great, I don't mind if you claim it! I was personally encountering the same issue when I enabled too many things on my profile too 😬. Excited to see the fix for the same. ♥
