### ISSUE TITLE
Do not select Dollar sign in shell command when double clicked

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#9659]
When you double click to select shell command dollar sign at the front also gets selected. It should be excluded

**Describe the solution you'd like**

Exclude the dollar sign when selecting a shell command

**Describe alternatives you've considered**

**Additional context**

![command](https://user-images.githubusercontent.com/8092120/89608358-9089db80-d892-11ea-898c-cdc531def5da.gif)

When you double click to select the whole command $ sign also gets selected and you might have to remove $ sign after pasting it in terminal. This can be really annoying if the command is very long. It would be nice if $ sign is not selected on double click (unless you explicitly select it) when code block type is set to bash.

**Comment by Rafi993** [comment]
> Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.
> 
> To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.
> 
> To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.
> 
> For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

Wow I did not know github-actions can reply. I thought they could only do simple checks.

**Comment by rhymes** [comment]
Hi @Rafi993, thanks a lot for taking the time to highlight this but I feel like we're in default browser territory.

If I write:

```shell
tree /tmp
```

or

```shell
$ tree /tmp
```

or 

```shell
> tree /tmp
```

or 

```shell
➜ tree /tmp
```

double click will correctly select the entire row. I don't think we should mess with that.

In addition to it, the prompt is just a convention, mine for example is the last one, which is a Unicode character.

For that reason I think we should close this issue as it looks like a non issue after all.

**Comment by Rafi993** [comment]
I think you are right. Ideally this should be a zsh extension that would remove $ sign when pasting (which is not related this this repo).
