### ISSUE TITLE
Rate limiting on update article endpoint triggering earlier than expected (DEV API)

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#9674]
**Describe the bug**

A user wrote in to report that they are "noticing 429 errors returned from the [update article endpoint](https://docs.forem.com/api/#operation/updateArticle), well before the stated rate limit of 150 requests per 30 seconds."

**To Reproduce**

See screenshot attached below for full details.

**Expected behavior**

They expect not trip the rate limit when under the 150 requests per 30 seconds.

**Screenshots**

![Image 2020-08-07 at 2 12 24 PM](https://user-images.githubusercontent.com/16007075/89675507-09e7f500-d8b8-11ea-8b78-256deee6cd05.png)

**Comment by rhymes** [comment]
Any ideas @mstruve ?

**Comment by mstruve** [comment]
The rate limit for article updates is 30 updates in 30 seconds. Not sure where 150 came from unless that is in our docs.

@michael-tharrington what is this person's API key?

**Comment by michael-tharrington** [comment]
That's right @mstruve it's in [our docs](https://docs.forem.com/api/#operation/getArticleById) like this:

![Image 2020-08-17 at 12 18 02 PM](https://user-images.githubusercontent.com/16007075/90418889-c04f9500-e083-11ea-88dd-3f0fc0cadb70.png)

If I have a link to the user's profile can I get the API key or do I need to ask the user for it?

**Comment by mstruve** [comment]
Documentation Fix: https://github.com/forem/forem/pull/9832 

However, I still need the key they were using since they said they would not use it for hours and then only after 2 uses would hit the rate limit. Or even if you can get me their dev email then I can look it up. I want to check Honeycomb to see these 429s actually happening.

**Comment by michael-tharrington** [comment]
Rock on! I'll hit you up directly about this one @mstruve

**Comment by mstruve** [comment]
Documentation updated. Since our code has changed a lot since this issue was initially reported and I cant find data about when it happened I am closing.
