### ISSUE TITLE
Editing errors should also be displayed in the preview tab

### ISSUE THREAD

**Issue by caleb15** [forem/forem#9707]
**Describe the bug**

Clicking on preview does nothing. In the console I see:
`POST https://dev.to/articles/preview 422`

**To Reproduce**

1. Go to a article draft / start writing new article
2. Click on preview

**Expected behavior**

A preview to appear

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 18
- Browser: Chrome
- Version: Version 84.0.4147.105 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by caleb15** [comment]
Specifically it happened with my article https://dev.to/caleb15/how-to-never-forget-you-re-in-production-1ma1-temp-slug-5547366?preview=0e327e013f1505cb48a88dea77c83c895055e40ab45288a6d7bcb971c6f0218e3a2b58cf56bce579d3b1206a554a65b2ee1316654b616714797df2bd

The behavior just changed. Before nothing happened when I click preview but now I see a warning in addition to the 422 error:
```
Whoops, something went wrong:
base: Liquid error: Liquid variables are disabled
```

**Comment by caleb15** [comment]
Ah, I see the problem. The warning appears at the top of the draft but if you are scrolled down to a lower part of the article you will not see the warning. The warning should appear outside the scope of the textarea so you can see it wherever you are in the page.

**Comment by caleb15** [comment]
Also the warning was because I had a {{ key_names }} in my article. I put it in backticks and the warning went away: `{{ key_names }}`

**Comment by caleb15** [comment]
Example:

Scrolled down, can't see error!
![image](https://user-images.githubusercontent.com/46505081/89741734-a6410180-da48-11ea-988c-aea25679c4ec.png)

Scrolled to top, can see error:
![image](https://user-images.githubusercontent.com/46505081/89741742-af31d300-da48-11ea-84a9-0016206cf07f.png)

**Comment by caleb15** [comment]
I thought about it a bit more and ideally I think the error would be placed in the preview tab after switching:

![image](https://user-images.githubusercontent.com/46505081/89741847-95dd5680-da49-11ea-8075-a02dd973e801.png)

By switching to preview you:
A) ensure error is seen
B) still fit in with user's expectations - user expects to see preview, they get preview.

It would also be nice to show what line the error occurred on, but not sure if that is possible or not.

**Comment by rhymes** [comment]
@caleb15 renamed the title to make it more explicit, thanks for the explanation!

**Comment by shilpi230** [comment]
@nickytonline @citizen428 @rhymes I would like to take this one! Thanks!

**Comment by citizen428** [comment]
@shilpi230 It's all yours, thanks for volunteering! 😃

**Comment by shilpi230** [comment]
Thanks @citizen428 !

**Comment by shilpi230** [comment]
@citizen428 @rhymes 
- Right now according to the code, 
   - We don't show the preview if article has some error in it. Should we change this behaviour ?
   - Error not being explicit because that's all we are getting from liquid. Do we add some specific message from our side to make it more clear for our user?

**Comment by citizen428** [comment]
> Error not being explicit because that's all we are getting from liquid. Do we add some specific message from our side to make it more clear for our user?

Liquid error messages are a recurring discussion, I wouldn't worry about it in the context of this PR.

**Comment by cmgorton** [comment]
Hey @shilpi230 looks like this has gone a little stale. 
Thanks so much for your work on this issue so far and for all your contributions. 
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. Given this process I am going to unassign you from this issue for now. 
In the meantime if you see any bugs you want to squash let me know and we can assign them to you! 🐛
