### ISSUE TITLE
Broken GIF image in article

### ISSUE THREAD

**Issue by GioLogist** [forem/forem#9715]
Hey there!

Back with a potential bug. At the time of writing, an image I'm trying to add to this [article](https://dev.to/giologist/creating-react-widgets-that-can-be-embedded-on-any-website-by-anyone-1mdg) keeps breaking. I've tried using both your image uploader and a direct link to the image, which can be found [here](https://javascriptpros.com/wp-content/uploads/2020/08/full-reddit-widget.gif).

**Comment by maestromac** [comment]
Hello @GioLogist , I believe the reason the image is not working is because of the size. Can you give it a try again with smaller size file?

**Comment by GioLogist** [comment]
100% possible. In fact, you can nearly confirm it just by the fact that other images (including ones hosted on the same domain) work just fine. 

The solution might be a disclaimer upon saving the post? Or maybe having the CDN render a "size limit" message, instead of a broken image? 

A few options here.

**Comment by mirie** [comment]
Closing as this issue is pretty stale/specific to a single article
