### ISSUE TITLE
Add a "spoiler tag" to optionally hide content

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#9719]
**Is your feature request related to a problem? Please describe.**
As an author and commenter, I might want to hide content that can be optionally viewed when the viewer is ready.  Such as solutions to a problem, etc.

**Describe the solution you'd like**
As a writer — an intuitive, markdown-based ways to include Spoiler text and images in content.

As a reader — the spoiler content is initially hidden, and I have to click to view it.

**Additional context**
Reddit uses the `>!Spoiler Content!<` syntax as seen [here](https://www.reddit.com/wiki/commenting#wiki_posting).

CC @maestromac based on the comment [here](https://github.com/forem/forem/issues/3785#issuecomment-525417377)

**Comment by rhymes** [comment]
Possibly related to https://github.com/forem/forem/issues/947 as well, see the last sentence in the description:

>  This could also be exposed using a {% spoiler %} liquid tag.
