### ISSUE TITLE
Can't remove comment on Forem.dev

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#9725]
**Describe the bug**

I've got 500 error on Forem.dev when trying to remove my own comment.

**To Reproduce**

1. Go to any post.
2. Add a comment.
3. Try to remove the comment...
4. Boom. 500.

**Expected behavior**

Comment being removed.

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Chrome 84.0.x

**Additional context**

It happens on Forem.dev but not on Dev.to

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a Forem team member and is not up for grabs.

**Comment by cmgorton** [comment]
Hey @ludwiczakpawel I just tested this and was able to remove my comment. I am going to close this issue but let me know if you are still experiencing this and we can open it back up :)
