### ISSUE TITLE
Can't see images on Forem.dev

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#9726]
**Describe the bug**

When I upload an image (whether it's comment or actual post) and I paste link to that image in the content it serves me some weird characters instead of image...

**To Reproduce**

1. Go to post editor or comment editor.
2. Upload an image.
3. Paste generated URL in the post/comment body.
4. Submit.
5. Click the image URL.
6. Boom.

**Expected behavior**

To be able to see the image.

**Screenshots**

![image](https://user-images.githubusercontent.com/108287/89877090-e2e33900-dbbf-11ea-8d0f-00cecd11adac.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Chrome 84.x

**Additional context**

Happens on Forem.dev but not on Dev.to.

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a Forem team member and is not up for grabs.

**Comment by cmgorton** [comment]
This also seems to be working correctly now. Again let me know if you are still having issues with this and we can open it back up :)
