### ISSUE TITLE
Can't report abuse on Forem.dev

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#9727]
**Describe the bug**

I can't report abuse on Forem.dev - it looks like reCaptcha must be reconfigured for specific domain.

**To Reproduce**

1. Go to any article
2. Click the three-dots icon on the left and choose "Report abuse"
3. Fill the form and submit
4. Boom.

**Expected behavior**

Being able to report abusive contnet.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Chrome 84.x

**Additional context**

Happens on forem.dev but not on dev.to

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a Forem team member and is not up for grabs.

**Comment by cmgorton** [comment]
I have reported abuse on forem.dev twice this week without any issues so I think this one might be fixed too.
