### ISSUE TITLE
devcomment liquid tag on Forem.dev

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#9728]
**Describe the bug**

I was writing a post and tried to add a liquid tag with particular comment on forem.dev. One thing I've noticed was that liquid tag for showing comments is called `{% devcomment ... %}` which indicates it's DEV-oriented. Now that's one thing, but the actual issue was that I tried to use it with comment's ID from forem.dev and it throw me an error.

**To Reproduce**

1. Try to write a post or comment on Forem.dev
2. Include a liquid tag for comment on Forem.dev `{% devcomment ... %}`
3. Submit.
4. Boom, error.

**Expected behavior**

1. Be able to add liquid tags with comments.
2. Have "generalized" names for liquid tags: `{% devcomment ... %}` --> {% comment ... %}

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Chrome 84.x

**Additional context**

Happens on Forem.dev, not on DEV.to

**Comment by atsmith813** [comment]
`{% comment %}` is already implemented - we should probably update the documentation to display that instead of `devcomment` when we tackle https://github.com/forem/forem/issues/9730.

It's working for me https://forem.dev/atsmith813/test-comment-liquid-tag-3nb6

Maybe something updated?

**Comment by ludwiczakpawel** [comment]
![](https://media.giphy.com/media/3q3QK6KyDVUBzih7hB/giphy.gif)
