### ISSUE TITLE
Safari Bookmark no icon 

### ISSUE THREAD

**Issue by aHudspith** [forem/forem#9731]
When you save dev.to as a bookmark on Safari there is no branded icon. Is it there if you add it to the saved tabs, but not the bookmarks. Would be nice to also have it there.

**Comment by cmgorton** [comment]
Hey @aHudspith . I just tested this and I can see the DEV icon in my bookmarks on Safari. I am going to close this issue but if you are still experiencing this let me know and we can reopen this. Thanks.
