### ISSUE TITLE
Liquid tag for Pastebin

### ISSUE THREAD

**Issue by brandizzi** [forem/forem#9732]
Hello people! Is there any chance forem would have liquid tags for snippets from pastebin.com? 

If the maintainers are open to it, I can implement it myself, I just need to know if it would be accepted (and not a waste of time).

**Comment by brandizzi** [comment]
I would like to claim this issue to work on it myself. But I would not like to work on something to not be accepted later. So, if I worked on it, would the change be accepted in principle?

**Comment by rhymes** [comment]
@brandizzi sure! go ahead! :-) sorry I didn't notice the initial claim

**Comment by rhymes** [comment]
As we review our integration with external services to be less DEV specific and more mindful of the diverse array of users in the Forem ecosystem, I went ahead and removed the `ready for dev` label in the meantime
