### ISSUE TITLE
Can't connect with Twitter on Forem.dev

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#9733]
**Describe the bug**

I've signed up to forem.dev with my github account, but now I can't add Twitter to my account.

**To Reproduce**

1. Signup with GitHub account
2. Go to settings/account
3. Click "Connect Twitter Account"
4. Authenticate with Twitter
5. Boom. You land on dashboard (also, why?) but Twitter is still not connected.

**Expected behavior**

Land on home page with with success message about connecting my twitter account.

**Screenshots**

n/a

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Chrome 84.x

**Additional context**

Happened on forem.dev.

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a Forem team member and is not up for grabs.

**Comment by jdoss** [comment]
What happens when you log out and then log in with Twitter? I can't test this because my Twitters is already connected.

**Comment by ludwiczakpawel** [comment]
@jdoss it takes me to /onboarding like my account didn't exist 👀

**Comment by cmgorton** [comment]
I can log in with both Twitter and Github. Closing this but let me know if it is still an issue for you @ludwiczakpawel and I'll openit back up.
