### ISSUE TITLE
Generalize message in Danger Zone

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#9734]
**Describe the bug**

When going to /settings/account there's still some message being DEV-oriented:
- `@ghost` account is [hardcoded](https://github.com/forem/forem/blob/master/app/views/users/_account.html.erb#L110) and it doesn't seem to exist on forem.dev
-  Not sure about `yo@dev.to`..?

**To Reproduce**

1. Go to /settings/account
2. Scroll down to the "Danger zone"
3. See the message:
    > If you would like to keep your content under the **@ghost** account, please click here. Feel free to contact **yo@dev.to** with any questions.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/108287/89888738-b683e880-dbd0-11ea-821f-694e0608ee31.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Chrome 84.x

**Additional context**

Spotted on forem.dev

**Comment by jeansberg** [comment]
I can take a look at this.

**Comment by rhymes** [comment]
@jeansberg: I've assigned you the issue. Thank you!

**Comment by jeansberg** [comment]
I have looked at the code a bit and am unsure how to proceed.
1. Should the "ghost" account be a feature of all forem sites and if so, do we need to make sure it's created automatically?
2. The email "yo@dev.to" shows up because the account page calls the "email_link" function that by default returns the "DEFAULT_EMAIL" from the .env file. I am not sure if this can be set from the admin view, because I can't seem to access it.

**Comment by rhymes** [comment]
Hi @jeansberg, the ghost feature is gone, see #10139, so nothingt to do there :) 

Regarding the email: as you found out, `email_link` is a helper that allows you to choose which email you should display. The default email is the one you should display there. You can only change it in the environment variable in `.env` yes, you can see all the changeable configuration in http://localhost:3000/admin/config, section "All Site Configuration"

Hope this helps :)

**Comment by jeansberg** [comment]
Thank you. I have been super-busy with moving and other stuff unfortunately so I will have to leave this issue for someone else.

**Comment by afairlie** [comment]
Hi,

I'm planning to participate in hacktoberfest and I'd like to make my first contribution to Forem. I was having trouble with issue #10356, so I offered to help with that, but I'm waiting to hear if I will be permitted to work on it/if it's a reasonable first issue. If it's not too much work I'd be happy to work on both issues (this one and the other mentioned), or I'd be happy just to work on this one if I'm not allowed to work on the other!

Let me know :) Thanks!

**Comment by citizen428** [comment]
@afairlie Thanks for offering to help! Since #10356 has been closed in the meantime, I'll assign you this issue here.

**Comment by afairlie** [comment]
awesome! Thanks @citizen428

**Comment by cmgorton** [comment]
Hey @afairlie 
Thanks so much for your willingness to work on this issue. 
We recently implemented a [new internal RFC process](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) for feature requests. With this new process we are figuring out when a Forem team member or a community contributor should work on a feature request. Given this process I am going to unassign you from this issue for now. 

In the meantime if you see any bugs you want to squash let me know and we can assign them to you!🐞
