### ISSUE TITLE
Logo in Night Mode/TenX Hacker not adhering to theme style

### ISSUE THREAD

**Issue by josefaidt** [forem/forem#9742]
**Describe the bug**

When in Night Mode or TenX Hacker, Forem SVG logo does not update its fill to adhere to the chosen theme. It does not update on theme change, which isn't entirely necessary for the light themes, however logo is very difficult to see in darker themes.

**To Reproduce**

1. Go to [User] Settings > UX (https://forem.dev/settings/ux)
2. Click on "Night Mode" or "TenX Hacker Theme", then "Save"
3. Reload the page
4. See logo color

**Expected behavior**

Logo fill is to be updated upon theme change for visibility. Perhaps `var(--theme-secondary-color)`

**Screenshots**

![image](https://user-images.githubusercontent.com/5033303/89922974-75d2a200-dbc5-11ea-82b0-7753da195ba7.png)

**Desktop (please complete the following information):**

- OS, version: macOS 10.15.5
- Browser, version: Chrome 84.0.4147.105

**Smartphone (please complete the following information):**

- Device: n/a
- OS, version: n/a
- Browser, version: n/a

**Comment by ludwiczakpawel** [comment]
Logo has changed a little so I'm closing this issue since it seems like it's no longer an issue.
