### ISSUE TITLE
Footer is hidden in mobile

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#9751]
**Describe the bug**

When you open https://dev.to/ in mobile you can't see the whole footer when you scroll to the bottom

**To Reproduce**

   1. Go to https://dev.to/ in mobile
   2. Scroll to bottom 
   3. You can't see the whole footer

**Expected behavior**

You should be able to see the whole footer

**Screenshots**
![footer_hidden](https://user-images.githubusercontent.com/8092120/90005611-15bb2900-dcb5-11ea-8a2a-53d8b3cc814a.png)

**Smartphone:**
- Device: Redmi note 6 pro
- OS, version:  Android 9
- Browser, version: Brave 1.11.105

**Comment by kaushikpraveen** [comment]
Hey, I am also able to reproduce this issue on my mobile device as well.
I would very much like to work on it, hence claiming this issue.

**Comment by rhymes** [comment]
Go ahead @kaushikpraveen

**Comment by Link2Twenty** [comment]
Relates to #9362
