### ISSUE TITLE
Cache of reactions not updating on post within an Organization page

### ISSUE THREAD

**Issue by omenking** [forem/forem#9754]
**Describe the bug**

Here is the article:
<img width="847" alt="Screen Shot 2020-08-12 at 11 38 31 AM" src="https://user-images.githubusercontent.com/7776/90035998-7e43df00-dc90-11ea-87e5-3c1e620e4184.png">

Here is the reaction count
<img width="649" alt="Screen Shot 2020-08-12 at 11 38 27 AM" src="https://user-images.githubusercontent.com/7776/90036035-8734b080-dc90-11ea-8790-e8ca1a87efa7.png">

Maybe it's just a slow cache? Is this normal behaviour?  I remember it showing up instantly. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
@omenking has it been updated in the meantime? 

Weird

**Comment by omenking** [comment]
It's up to date now.

<img width="511" alt="Screen Shot 2020-08-12 at 7 36 11 PM" src="https://user-images.githubusercontent.com/7776/90078491-19f63f00-dcd3-11ea-9277-5366b6c055d5.png">

🤷‍♂️

**Comment by rhymes** [comment]
Should we close this then @omenking ?
