### ISSUE TITLE
I cannot write post in the community

### ISSUE THREAD

**Issue by Mahmoud-007** [forem/forem#9755]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
Hello @Mahmoud-007, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
