### ISSUE TITLE
Upgrade to Storybook 6

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#9763]
**Is your feature request related to a problem? Please describe.**

Storybook 6 has been released. We will need to make some changes going forward in regards to Storybook. See https://dev.to/emma/storybook-v6-0-released-1cg4 

<details>
<summary>Details</summary>

There are some breaking/new changes. See https://dev.to/emma/storybook-v6-0-released-1cg4

</details>

**Describe the solution you'd like**

Upgrade to Storybook 6 by making the required upgrade path changes.

**Describe alternatives you've considered**

**Additional context**

**Comment by nickytonline** [comment]
@emgoto, since you posted an article about this, would you like to work on this. Happy to pair with you if you need.

**Comment by emgoto** [comment]
Ooh yes, I would love to!

**Comment by nickytonline** [comment]
Awesome, I've assigned this to you. There is a new part of Storybook for generating CSS utility classes documentation. That will need to be updated as well most likely. See [Forem's CSS Utility Classes](https://forem.dev/nickytonline/forem-s-css-utility-classes-o6j).
