### ISSUE TITLE
Reading list counter

### ISSUE THREAD

**Issue by ezio1404** [forem/forem#9770]
**Describe the bug**

I have a 200+ reading list unopened, I archive them after I read or save, after I clear out my reading list and go back to the main page the reading list on the sidebar has a counter(unopened or unread post) and when I clicked it it's empty.
Things I've done:
- hard refresh and emptying the cache
- closing the browser and opening it again
- logout and logging in again

**To Reproduce**

**Expected behavior**

**Screenshots**
Here are the screenshots:
![readinglist](https://user-images.githubusercontent.com/34921038/90159486-0b875080-ddc3-11ea-96e8-6525afa7a694.JPG)
![reading list list](https://user-images.githubusercontent.com/34921038/90159505-1215c800-ddc3-11ea-9d6f-8ef4b81eacc7.JPG)

**Desktop (please complete the following information):**

- OS, version:
Windows 10 Home single language 64-bit (10.0,Build 18362)
- Browser, version:
Microsoft Edge Version 84.0.522.59 (Official build) (64-bit)
**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
Hi @ezio1404 the counter reflects the non archived items, but it's weird that youur list is empty but the counter says 5. Do you have the items in the archive section?

**Comment by ezio1404** [comment]
Hi @rhymes yes I have 290+ archived items and recently I save 7 post and it backed up to 29
![re1](https://user-images.githubusercontent.com/34921038/90162018-94ec5200-ddc6-11ea-84c0-867d298b653a.JPG)
![re2](https://user-images.githubusercontent.com/34921038/90162031-99186f80-ddc6-11ea-9603-f83e121f5f0f.JPG)

Archived:
![re3](https://user-images.githubusercontent.com/34921038/90162053-a2094100-ddc6-11ea-9b0a-4806e296b239.JPG)

**Comment by takmar** [comment]
Could I take this?

**Comment by rhymes** [comment]
@takmar sure, I've assigned it to you, thanks!

**Comment by rhymes** [comment]
Reopening this as it was reverted in https://github.com/forem/forem/pull/10932

**Comment by rhymes** [comment]
Looks like it was then closed by #10933
