### ISSUE TITLE
Runkit embeds fail with error: Unable to load embed. Syntax error found in Preamble. See console for error.

### ISSUE THREAD

**Issue by joelnet** [forem/forem#9773]
**Describe the bug**

Runkit is reporting an error: `Unable to load embed. Syntax error found in Preamble. See console for error.`

The first 2 Runkit embeds seem to work fine. Others after are failing.

**To Reproduce**

1. Go to https://dev.to/joelnet/creating-a-linked-list-using-only-function-combinators-5hhk
2. Scroll to text `Unable to load embed. Syntax error found in Preamble. See console for error.`
3. See error

**Screenshots**

![https://uc5be8c7b8a7cdc7c2ce1a8c5040.previews.dropboxusercontent.com/p/thumb/AA6W6_WYsViw-ehSsvwbbiBP_WLnI2iVW7D0_m2_pX6sJBcCHUMqxGXEtBn9kgvv2Mi_YA1lHUax5Mn1QkvG7uZlFWLxYvW5KWSu6CFbHt7tOgjrAkT6X6_1ndIPwo7mtE5Q8HarJcbEm-EEOSRGFPQHx298D9tw1Z-ea-qT0U3thEHJ46ozPheVF1So0nEtOx5ZHeQooE0RZK97hVpMzpE6ozzWJZserOaZExyrXITUGpDpRrTseCvdn-taoO0VBPIAN7UG87R3v0G1i9NvNCAo6SaHBhJBLraL-XeeiRdlL4Vf29kgtsYIRKRfEdbc2gVCqDoUdWsTYMFXr6AyhDg42GrcGvbX08WyHOsYSjDMGAGFQeQTsEWHU7AQp4LIA-dAXC1vGlz2HxlvqoSIdGV3/p.png?fv_content=true&size_mode=5](https://uc5be8c7b8a7cdc7c2ce1a8c5040.previews.dropboxusercontent.com/p/thumb/AA6W6_WYsViw-ehSsvwbbiBP_WLnI2iVW7D0_m2_pX6sJBcCHUMqxGXEtBn9kgvv2Mi_YA1lHUax5Mn1QkvG7uZlFWLxYvW5KWSu6CFbHt7tOgjrAkT6X6_1ndIPwo7mtE5Q8HarJcbEm-EEOSRGFPQHx298D9tw1Z-ea-qT0U3thEHJ46ozPheVF1So0nEtOx5ZHeQooE0RZK97hVpMzpE6ozzWJZserOaZExyrXITUGpDpRrTseCvdn-taoO0VBPIAN7UG87R3v0G1i9NvNCAo6SaHBhJBLraL-XeeiRdlL4Vf29kgtsYIRKRfEdbc2gVCqDoUdWsTYMFXr6AyhDg42GrcGvbX08WyHOsYSjDMGAGFQeQTsEWHU7AQp4LIA-dAXC1vGlz2HxlvqoSIdGV3/p.png?fv_content=true&size_mode=5)

**Desktop (please complete the following information):**

- OS, version: Windows 10, IOS
- Browser, version: Edge, FF, Chrome, Brave

**Comment by glebec** [comment]
Also seeing this in https://dev.to/glebec/monadic-parser-combinators-an-interactive-js-tutorial-pt-1-3jbo.

I think the problem _might_ be a regression bug in preamble support, but I haven't done more than a minute's worth of debugging yet. See #662 and #696 for info on how/when preamble support was added.

Example of a snippet without preamble:

```txt
{% runkit %}
foo()
{% endrunkit %}
```

With preamble (possibly what is now breaking):

```txt
{% runkit
let bar = 5
%}
foo(bar)
{% endrunkit %}
```

**Comment by citizen428** [comment]
Thanks for digging into this @glebec! Would this be something you're interested in solving yourself or is this issue still up for grabs?

**Comment by glebec** [comment]
@citizen428 it is certainly up for grabs – I just wanted to provide a little context, but I don't know when I'll have the time to dig deeper.

**Comment by citizen428** [comment]
No worries at all @glebec, thanks for clarifying.

**Comment by akashdotsrivastava** [comment]
@rhymes Hi. I'd like to give this a shot if that's okay.

**Comment by rhymes** [comment]
Hi @akashdotsrivastava, please go ahead! thanks!

**Comment by akashdotsrivastava** [comment]
@joelnet Can you find some time to drop a couple of exact runkit tags with preamble you have included in the article https://dev.to/joelnet/creating-a-linked-list-using-only-function-combinators-5hhk, the ones which are giving the error `Unable to load embed. Syntax error found in Preamble. See console for error.`

Asking because I have tried the example above
```
{% runkit
let bar = 5
%}
foo(bar)
{% endrunkit %}
```
and it seems to render fine. An exact example would help.

**Comment by joelnet** [comment]
> @joelnet Can you find some time to drop a couple of exact runkit tags with preamble you have included in the article https://dev.to/joelnet/creating-a-linked-list-using-only-function-combinators-5hhk

I created a gist here so you can copy the raw https://gist.github.com/joelnet/55aede139467d110e276d0ab71e26776

**Comment by akashdotsrivastava** [comment]
@joelnet Thank you 👍

**Comment by akashdotsrivastava** [comment]
@rhymes Thank you for assigning me this. I added a PR for the fix.

**Comment by glebec** [comment]
I still had this error on https://dev.to/glebec/when-nesting-promises-is-correct-h8f. It turned out that opening the article in edit mode and saving changes fixed it, presumably because the article was re-run through the fixed text processing logic.
