### ISSUE TITLE
Add a filter to https://dev.to/search for organizations

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#9775]
**Is your feature request related to a problem? Please describe.**

Folks occasionally want to browse/search and see what orgs exist on DEV and there's no easy way to get that information.

**Describe the solution you'd like**

I think it'd be good if we added `organizations` as a category/filter to search for.

**Additional context**

I think in addition to this, we may want to have an organization directory. The thing about search is that it doesn't have endless scroll, so folks who just want to browse orgs will have to enter something in the search to refine results.

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
