### ISSUE TITLE
header color not change when visit your (/devteam) profile on night theme

### ISSUE THREAD

**Issue by kaliwa** [forem/forem#9780]
When I entered the devteam profile page, I thought the text color in the `widget` _class_ and the `header` element was indeed black, so I tried to check other people's profile pages I saw the same text and position as I previously described but this one is different, the color is white and there is an additional night-theme class which I did not find when visiting devteam profile page, so I assume there is an error either in logic or because of the profile

the text color in the header element on the devteam profile page is not working as it should

**To Reproduce**

1. Go to this [link](https://dev.to/devteam)
 2. Check on this

![image](https://user-images.githubusercontent.com/49640654/90239798-54d2b100-de52-11ea-8a66-7f624b560706.png)

![check if not clear](https://user-images.githubusercontent.com/49640654/90239993-a713d200-de52-11ea-814f-c71fd5699d04.png)

- OS, version: Ubuntu, 20.04
- Browser, version: Firefox, latest

etc:
_sorry for my bad english_

**Comment by sivaraam** [comment]
I also happened to notice this issue. The organization page doesn't seem dark mode friendly. Few screenshots:

**Comment by kaliwa** [comment]
Firefox on Ubuntu

**Comment by ludwiczakpawel** [comment]
Hey, thanks for this report.

We've very recently updated profile view for users and we're going to do the same thing for Organizations as well, pretty soon. So please bare with me and give it couple days before we ship it :) Then this bug should not be an issue anymore.
