### ISSUE TITLE
Discussion input box changes height when focused

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#9782]
**Describe the bug**
Height of the discussion input box changes when focused

**To Reproduce**
      1. Go to dev.to
      2. Click on article
      3. Scroll down to comment section
      4. Click the discussion box
      5. Height changes focused    

**Expected behavior**
Height of discussion input box should remain same when focused

**Screenshots**
![discussion_box](https://user-images.githubusercontent.com/8092120/90247496-543b1a00-de54-11ea-9b54-40ceaccbcb81.gif)

**Desktop:**
- OS, version: Ubuntu 20.04 LTS
- Browser, version: Brave browser Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

**Comment by Rafi993** [comment]
Hi there, If this issue is not taken I would like to help.

**Comment by citizen428** [comment]
Thanks for volunteering @Rafi993, assigned you the issue now.

**Comment by Rafi993** [comment]
I think this issue has been resolved now since there is a new comment input box now

**Comment by ludwiczakpawel** [comment]
@Rafi993 correct. although autoresizing is still kinda broken :D but we're already working on the [fix](https://github.com/forem/forem/pull/11115) :). So yea, closing this one - thanks a lot!
