### ISSUE TITLE
Is the following system broken?

### ISSUE THREAD

**Issue by catalinpit** [forem/forem#9783]
**Describe the bug**

The following system on dev.to seems to be pointless (sorry if it sounds harsh, that's not the intention for sure). People following you rarely interact with your posts, or anything. 

Could anyone have a look at it, please? Or is there any plan for it?

Thank you!

**Comment by cmgorton** [comment]
Hey Catalin. I opened a discussion on [forem.dev](https://forem.dev/foremteam/forem-following-system-b9f) about this to see what others thought. I am going to go a head and close this issue here. Please leave any more thoughts or feedback on that post. Thanks!
