### ISSUE TITLE
Fetch article by slug API documentation

### ISSUE THREAD

**Issue by Oghenebrume50** [forem/forem#9784]
Following the implementation of this https://github.com/forem/forem/pull/8929

I can see the written doc in here https://github.com/forem/forem/blob/e9c513fb3f7b4c3f72c1339aba75c70c71f32381/docs/api_v0.yml#L1971

But nothing is showing on the official [API docs website](https://docs.forem.com/api/#tag/articles), is there something I am missing or this is yet to be implemented?

**Comment by rhymes** [comment]
Hi @Oghenebrume50, it's here https://docs.forem.com/api/#operation/getArticleByPath :-) 

The website is auto generated from the yml file

**Comment by Oghenebrume50** [comment]
Awesome thank you
