### ISSUE TITLE
Deleting notifications in the model when comment is hidden

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#9807]
**Describe the bug**

Right now in model **app/models/comment.rb:30** the notificatoin gets deleted when the comment is deleted by the following line

```ruby
  after_update :remove_notifications, if: :deleted
  before_destroy :before_destroy_actions
  after_destroy :after_destroy_actions
```

but similar to this notification gets deleted when the user hides a comment in **app/controllers/comments_controller.rb**
added by PR https://github.com/forem/forem/pull/8881/files. could the deleting of notification when comment is hidden also be done in the modal similar to above?

I did not know if I should create a bug or feature since this is code refactoring

**Expected behavior**

Notification gets deleted by the code in model when user hides the comment

**Comment by Rafi993** [comment]
Hi there,
 If this issue is not taken I would like to help.

**Comment by citizen428** [comment]
@Rafi993 While I'm personally not a big fan of conditional callbacks you can do something like this:

```ruby
after_update :remove_notifications, if: :remove_notifications?

private

def remove_notifications?
  deleted? || hidden_by_commentable_user?
end
```

I'll assign you the issue, thanks as always for volunteering! 😃

**Comment by Rafi993** [comment]
> @Rafi993 While I'm personally not a big fan of conditional callbacks you can do something like this:
> 
> ```ruby
> after_update :remove_notifications, if: :remove_notifications?
> 
> private
> 
> def remove_notifications?
>   deleted? || hidden_by_commentable_user?
> end
> ```
> 
> I'll assign you the issue, thanks as always for volunteering! 😃 

Awesome

**Comment by rhymes** [comment]
Are we sure we want to delete notifications when the comment is hidden? What about the chance that a comment gets un-hidden? 

cc @michael-tharrington @vaidehijoshi

**Comment by Rafi993** [comment]
> Are we sure we want to delete notifications when the comment is hidden? What about the chance that a comment gets un-hidden?
> 
> cc @michael-tharrington @vaidehijoshi

I think there was a similar discussion happening about this in PR https://github.com/forem/forem/pull/8881

**Comment by michael-tharrington** [comment]
I think I understand this.

So basically if an author hides a comment on their post, then the notification for that comment on https://dev.to/notifications will be deleted from the author's notifications, correct?

This should be fine.

If they unhide the comment, I think it'd be alright if the notification was still deleted. Another possibility would be that unhiding the comment creates a new notification — perhaps one that says the comment was unhidden.
