### ISSUE TITLE
app crashes on google autofill

### ISSUE THREAD

**Issue by amanintech** [forem/forem#9809]
**Describe the bug**
I have the latest android and downloaded the latest app. When I login and use google autofill in the fields, the app somehow crashes 

**To Reproduce**
1. open the app
2. Sign In
3. type in the fields
4. choose google autofill

**Expected behavior**

app crashes and closes

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28403318/90331781-e0744b00-dfd4-11ea-96d1-15b70f48fc3e.gif)

**Smartphone (please complete the following information):**

- Device: OnePlus 8
- OS, version: Android 10
- Browser, version: Dev.to native app

**Comment by syntaxhacker** [comment]
i have also faced this issue but with github signin . didnt used google signin

**Comment by fdoxyz** [comment]
The problem was caused by all autofill providers during signin. The fix was shipped in the latest release `1.4.2`
