### ISSUE TITLE
RSS feed not syncing

### ISSUE THREAD

**Issue by artis3n** [forem/forem#9840]
**Describe the bug**

Dev.to is not syncing with my blog's RSS feed. I've had the "publish from RSS" settings hooked up for some years now. My recent articles published to my blog, however, are not showing up as drafts in dev.to.

I manually pressed "fetch feed now" but no new drafts appeared. There should be 4 or 5 new articles to cross-post. My feed.xml endpoint on my blog is working fine. Any reason I am not seeing these drafts under my dashboard?

The feed is <https://blog.artis3nal.com/feed.xml>.

**To Reproduce**

Not too sure. Sync to <https://blog.artis3nal.com/feed.xml>, wait for me to push a new article? There's about 6-8 articles at this point that were published to my blog that dev.to did not pick up.

**Expected behavior**

New article in my feed.xml shows up as a draft on dev.to.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: PopOS 20.04
- Browser, version: Google Chrome 84

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by maestromac** [comment]
Hello @artis3n , sorry for the delay. The reason your feed isn't being imported is that it's missing a valid URL in the link tag. Please take a look at https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.artis3nal.com%2Ffeed.xml . Once you resolve that, your feed should be coming through once again.

**Comment by artis3n** [comment]
:O well that would do it

**Comment by maestromac** [comment]
I'm closing this since it sounds like you resolved it. let me know if otherwise!
