### ISSUE TITLE
Allow update user profile via API

### ISSUE THREAD

**Issue by molebox** [forem/forem#9848]
**Is your feature request related to a problem? Please describe.**

This request isnt a problem but a request for an endpoint to allow users to update their profile via an endpoint

**Describe the solution you'd like**

Im developing an app [devpack.dev](https://www.devpack.dev/) which aims to give devs a means to keep their online presence consistent across multiple platforms. I have so far integrated Twitter and GitHub, I would love to add DEV to the list too.

I would like to see an endpoint for updating a users profile information. Just the basics like: 

- name
- location
- description
- website
- email

**Describe alternatives you've considered**

Ive looked through the API docs and it seems that there is no way to do this currently. Im not sure if that is because of security reasons or not.

**Additional context**

None

I appreciate your time reading this. Seeing as DEV is such an awesome medium for developers to share their content i feel that it would be sad if i couldn't add it to devpack. 

The idea behind devpack is pretty simple, if you keep your name, description and images the same across platforms then you can be more easily found and associated with your work. 🤗

**Comment by twinsfan421** [comment]
I would be interested in working on this if approved.

**Comment by rhymes** [comment]
I believe we can find a generalized approach here to play in concert with the generalization efforts for profiles. There's a core of fields that all Forems will have but there will also be Forems that have certain fields and Forems that don't so the API should be flexible enough to account for that

**Comment by citizen428** [comment]
Basically what @rhymes said. Since Forem will be used for many different types of communities, the list of available profile fields can now be configured by admins so there are very little guarantees as to which fields will be available. This means we'd need the following:

1. An endpoint to retrieve the current list of profile fields (either wrapping `Profile.attributes!` or more directly `ProfileField` so we can also return how the information is displayed on the site (text input, checkbox, etc.)
2. An endpoint to perform the update, reusing the `Profiles::Update` service object.

**Comment by molebox** [comment]
Hey folks, I was wondering if anyone had had anytime to look into this any further?

**Comment by citizen428** [comment]
@molebox Unfortunately, not yet. We haven't quite wrapped up the big profile revamp yet and until this is done we probably won't get to it, sorry for that.

**Comment by molebox** [comment]
> @molebox Unfortunately, not yet. We haven't quite wrapped up the big profile revamp yet and until this is done we probably won't get to it, sorry for that.

No worries, I appreciate you getting back to me. I'll drop by again in the spring maybe to check the status. 😊

**Comment by molebox** [comment]
Hey team, any movement on this?

**Comment by cmgorton** [comment]
No movement yet I believe but if you want to get even more eyes on this feature request and support for it you can try creating a post in [forem.dev](https://forem.dev/). Similar to the requests mentioned in this post https://forem.dev/foremteam/let-s-discuss-3-a-roundup-of-feature-requests-5e2e

**Comment by citizen428** [comment]
I added this to our engineering planning funnel now, I hope this will allow us to get a better handle as to when we'll be able to work on this. Thanks for your patience @molebox

**Comment by molebox** [comment]
Much appreciated @citizen428 🙏

**Comment by mstruve** [comment]
Hey @molebox! Thank you so much for submitting this issue. 

We discussed this during our planning meeting today. For some background, every 2 weeks we have a planning meeting with engineering and product folks to figure out what our priorities will be for the next 2 weeks. During that meeting we determined that before we add an endpoint like this we need to sit down and have a more holistic discussion about our API as a whole and how we expect it to be used by Forem creators and users going forward. I am not sure when that discussion will happen but we will definitely keep you posted. 

How does that all sound? Any further questions I can answer?

**Comment by molebox** [comment]
> Hey @molebox! Thank you so much for submitting this issue.
> 
> We discussed this during our planning meeting today. For some background, every 2 weeks we have a planning meeting with engineering and product folks to figure out what our priorities will be for the next 2 weeks. During that meeting we determined that before we add an endpoint like this we need to sit down and have a more holistic discussion about our API as a whole and how we expect it to be used by Forem creators and users going forward. I am not sure when that discussion will happen but we will definitely keep you posted.
> 
> How does that all sound? Any further questions I can answer?

Hey @mstruve! Awesome, that sounds perfect and totally understandable. I'll keep my fingers crossed that you decided to move forward with it. Thanks for keeping me in the loop 💜
