### ISSUE TITLE
Generalise Devise emailer for invitations

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9849]
At the moment Forem is using default values and text for the devise invitation mailer.

**Describe the solution you'd like**

I think the best solution for this is to configure the text used to send invitations out via SiteConfig.

**Describe alternatives you've considered**

Using generalisation in the code base but I think an invitation needs to be more personal from the originating Forem

**Additional context**

Current mail content looks like this

```text
USER ID: #143 - alexjordyssiri_390 ID 283 TOKEN
owhJ4HycRiwkXRqHSBNqjnVrn6mcFLca
TO
someone@hotmail.com
MAILER
Devise::Mailer#invitation_instructions
SUBJECT
Invitation instructions
CONTENT
Date: Tue, 18 Aug 2020 09:40:56 +0000
From: thisMMAlife <yo@thismmalife.com>
Reply-To: thisMMAlife <yo@thismmalife.com>
To: someone@hotmail.com
Message-ID: <5f3ba22844a00_e3304f87726b@c6656b56-eae8-4d80-8739-703718ad78ea.mail>
Subject: Invitation instructions
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5f3ba228416a5_e3304f87715b";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5f3ba228416a5_e3304f87715b
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello someone@hotmail.com

Someone has invited you to https://www.thismmalife.com/, you can accept it through the link below.

https://www.thismmalife.com/users/invitation/accept?invitation_token=t7NuudiqB7ea5nTPQ_Xq


If you don't want to accept the invitation, please ignore this email. Your account won't be created until you access the link above and set your password.
```

**Comment by boardfish** [comment]
I assume this can already be done by overriding `app/views/devise/mailer/invitation_instructions.[html/text].erb`. This should be added to the codebase along with documentation in the relevant place (Backend Guide, probably near Previewing Emails).

**Comment by boardfish** [comment]
I should add that this is something I'd be happy to take on.

**Comment by rhymes** [comment]
Thanks @boardfish, I've assigned you to it

**Comment by jacobherrington** [comment]
I'm not certain #10575 will close this issue because as Lee suggested (using SiteConfig) we'll want some way to modify these emails via the UI.

I don't necessarily know if the Config UI is the *best* place to handle this (it is getting a bit bloated), I'd suggest building another view in the admin namespace to let folks overwrite email templates.

**Comment by boardfish** [comment]
I feel like the PR has addressed the desire to change the text content of those emails. It might not be via SiteConfig as suggested, but it's definitely opened up that avenue. I'd suggest closing this issue with #10574 and opening another to address doing it in the UI.

When it comes to doing that, I've done some wrangling with ActionMailer before and I get the sense it'd be possible to load text or HTML content in for emails from some external model as follows:

```ruby
class ApplicationMailer < ActionMailer::Base
  def mail(**args)
    super do |format|
      format.text { ... }
      format.html { ... }
    end
  end
end
```

In those format blocks, we could look up the text content from a model and render it, or fall back to the existing ActionMailer templates if a model template doesn't yet exist.

**Comment by cmgorton** [comment]
> I feel like the PR has addressed the desire to change the text content of those emails. It might not be via SiteConfig as suggested, but it's definitely opened up that avenue. I'd suggest closing this issue with #10574 and opening another to address doing it in the UI.
> 
> When it comes to doing that, I've done some wrangling with ActionMailer before and I get the sense it'd be possible to load text or HTML content in for emails from some external model as follows:
> 
> ```ruby
> class ApplicationMailer < ActionMailer::Base
>   def mail(**args)
>     super do |format|
>       format.text { ... }
>       format.html { ... }
>     end
>   end
> end
> ```
> 
> In those format blocks, we could look up the text content from a model and render it, or fall back to the existing ActionMailer templates if a model template doesn't yet exist.

Closing per this recommendation. We can open a discussion in [forem.dev](https://forem.dev/) to talk about doing it in the UI.
