### ISSUE TITLE
Consider using rem units

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#987]
**Is your feature request related to a problem? Please describe.**
This relates to #966

I noticed in most of the SASS files something that should be addressed. `font-size`s and other properties with measurement values are set as `em`, `px`, `%`.

**Describe the solution you'd like**

Consider using `rem` (and `em` when necessary). Browsers by default consider `1rem` to be `16px` on the root element, but if a user has different font settings, that `1rem` will be equal to that value. So using `rem`, everything will be sized based off of the browser's or user's font-size setting. `em` is also useful when whatever is being sized is dependent on its element's font-size, not the root element's font-size.

There’s a great discussion in the Bootstrap repo about all this, [Why has Bootstrap 4 changed to using rem? · Issue #19943 · twbs/bootstrap · GitHub](https://github.com/twbs/bootstrap/issues/19943). This is a good comment in there, https://github.com/twbs/bootstrap/issues/19943#issuecomment-224439306

It’s not a quick simple fix, but given this is OSS, I’m sure there would be many that could help with this.

Side note: I think this could be a great issue that could be done with mentors/mentees that are interested in CSS.

**Describe alternatives you've considered**
N/A

**Additional context**

![image](https://user-images.githubusercontent.com/833231/47332360-09338f80-d64d-11e8-8b4a-2a8bbce8d05e.png)

![image](https://user-images.githubusercontent.com/833231/47335514-7f3df380-d659-11e8-82ce-306d64e17d74.png)

**Comment by nickytonline** [comment]
Going all circular dependency here, but I started a discussion that links to this issue on dev.to. If you happen to be arriving here directly from GitHub, you can also check out https://dev.to/nickytonline/which-units-of-measure-do-you-use-and-why-in-css-nf4 to add your two cents about a general CSS discussion about this topic.

**Comment by jessleenyc** [comment]
@benhalpern and i were just chatting about this and he'll leave some additional thoughts but overall we think this is a good suggestion!

**Comment by benhalpern** [comment]
I think this makes sense. It seems like we could start using REMs and gradually work through the codebase without it having to be a largescale overhaul all at once.

I think cleaner, more deliberate CSS and styling could really help us now and in the long run. That's easy to say, but there was a time not-too-long ago that we weren't even really settled enough to bother with good habits here. But I think the timing is right to start addressing CSS in a variety of ways.

I'm happy to start defining some CSS guidelines, rules and principles, including REM.

**Comment by maestromac** [comment]
not stale

**Comment by benhalpern** [comment]
Hey, this is still a good idea. We can officially support the gradual replacement of both `em` and `px` with `rem`. Would there be problems with having only _some_ `rem` given user preferences though? Like, if we are only partly done with this, does the user have a worse experience if they have different preferences of font size?

**Comment by nickytonline** [comment]
Having `em` is actually OK in some contexts, but getting to your first point, I think it might have to be all or nothing. I'm not positive though.

**Comment by brisourceful** [comment]
I agree with @nickytonline that there are use cases for `em` such as media queries. I would love to take this issue on and help define some more guidelines regarding measurement units for CSS.

**Comment by nickytonline** [comment]
Go for it @brisourceful👏 and happy Hacktoberfest!

**Comment by rhymes** [comment]
@brisourceful that would be truly awesome! thanks!

**Comment by brisourceful** [comment]
@emgoto yes I have had a chance to work on it. I'm planning to submit a PR soon.

**Comment by eclectic-coding** [comment]
Hey @nickytonline I would love to help on this one. What is the status?

**Comment by rhymes** [comment]
Pinging @ludwiczakpawel about this as well as he might give some insights on where and how to start on this road

**Comment by ludwiczakpawel** [comment]
I think we can close this issue - [we've started implementing `rem` units](https://github.com/forem/forem/blob/master/app/assets/stylesheets/config/_variables.scss#L69-L77) with new styling a while ago.. It's still long path ahead of us to be 100% on `rem`s but we're getting there gradually while updating all the components and generally frontend codebase :)

**Comment by rhymes** [comment]
@ludwiczakpawel we could use this to coordinate the effort if @eclectic-coding and other contributors want to chip in. The same way we did with eslint issues in the past. It's harder to keep track of what's needed or who is doing what without a single place to share this information :)

**Comment by nickytonline** [comment]
This one is a little bigger @eclectic-coding as it probably requires some coordination with our product designers and myself, but you can definitely lend a hand. I'm not sure if this is the best thing to pair on for live coding though given the back and forth nature/coordination of this issue.

**Comment by cmgorton** [comment]
@nickytonline maybe a good RFC given it's scope and now we have Suzanne and Katie to help!

**Comment by ludwiczakpawel** [comment]
@nickytonline @cmgorton I still think we can close this issue, especially it's been a while since Nick opened it and the state of things has drastically changed.

**Comment by nickytonline** [comment]
@ludwiczakpawel makes a good point. It would probably make more sense to reassess what needs to be done here as a lot of the UI has changed.
