### ISSUE TITLE
Part of the share pop-up when viewing a draft article is cut-off

### ISSUE THREAD

**Issue by Nkemjiks** [forem/forem#9889]
**Describe the bug**
Part of the pop-up that opens when you click on the 3 dots on the left top side of the page is cut-off.

**To Reproduce**

1. Go to the dev.to
2. As a logged in user, try to create an article
3. Add some content and save without publishing 
4. On the top left corner, you should see 3 dots arranged horizontally.
5. Click on it

**Expected behavior**

It should fully show the pop-up list

**Screenshots**

<img width="1400" alt="Screenshot 2020-08-20 at 1 05 13 PM" src="https://user-images.githubusercontent.com/32465536/90768228-4f5be780-e2e6-11ea-9136-356ba198bc91.png">

**Desktop (please complete the following information):**

- OS, version: MacOS
- Browser, version: Chrome version 84.0.4147.105

**Comment by aitchiss** [comment]
Closing as this has been fixed in a previous PR - the dropdown now always opens in the downwards direction, which makes sure this problem doesn't occur.
