### ISSUE TITLE
Add external link icon on /mods 

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#9895]
**Is your feature request related to a problem?**
 

**Describe the solution you'd like**
A icon linked 🔗  to the post who opened to a new tab directly on `/mods` for read the post on a new tab.
![image](https://user-images.githubusercontent.com/14293805/90788970-a2de2d80-e306-11ea-8bea-c11f7a6e63cd.png)

**Describe alternatives you've considered**

Or `See on a new tab` link.

**Comment by michael-tharrington** [comment]
Thanks for writing this up @thomasbnt! Just to be clear, this is a request for an upgrade to the mod center available via [dev.to/mod](https://dev.to/mod) — we'd like the option to be able click on items in the list to see the full article. Something like:

![Image 2020-08-20 at 2 41 18 PM](https://user-images.githubusercontent.com/16007075/90811887-65bc7000-e2f3-11ea-9eb4-bb8b5df4fb90.png)

Right now, the article opens within the center like so:

![Image 2020-08-20 at 2 43 16 PM](https://user-images.githubusercontent.com/16007075/90811979-88e71f80-e2f3-11ea-81a3-c2c906f9d184.png)

This is great for the default action, but occasionally mods may want to click to see the regular article view.

**Comment by thomasbnt** [comment]
Thanks for this presision@michael-tharrington 😄

**Comment by joneskj55** [comment]
I'd like to take a stab at this.

**Comment by rhymes** [comment]
Please go ahead @joneskj55 and thank you!

**Comment by joneskj55** [comment]
Hey guys I think I have this figured out. However, I think I might need a mod account in order to test.

**Comment by rhymes** [comment]
Hi @joneskj55, you can add various admin roles on your user of your local installation with the following in the console:

```ruby
u = User.find_by(username: "")
roles = ["single_resource_admin", "tech_admin", "super_admin", "trusted", "pro"]
roles.each { |r| u.add_role(r) }
u.add_role(:single_resource_admin, Config)
```

In this case `trusted` is the only one strictly needed to test the functionality but you might want to know the others for future reference

**Comment by joneskj55** [comment]
@rhymes Got it, thanks!

**Comment by joneskj55** [comment]
I think I have the solution. However, I cannot get past the home page on local. I cannot login in order to see if what I am doing is working. I was having too many issues with installing locally so I am using Gitpod. Not sure if that helps explain why I can't log in. Any other suggestions?
![Screen Shot 2020-10-09 at 11 09 55 AM](https://user-images.githubusercontent.com/20748598/95606882-97fb6b80-0a20-11eb-901a-4a7dc95d2480.png)

**Comment by joneskj55** [comment]
I have Docker now, I'll give it a shot with that...

**Comment by thomasbnt** [comment]
Closed issue because is now on Forem.
