### ISSUE TITLE
Upgrade reCAPTCHA to v3

### ISSUE THREAD

**Issue by fdoxyz** [forem/forem#9919]
**Is your feature request related to a problem? Please describe.**

Based on community reports (#9908) we see a bit of friction on abuse reports secured by reCAPTCHA (and probably any other flows secured by it). The "I'm not a robot" [checkbox (v2)](https://developers.google.com/recaptcha/docs/display) is reliable probably for most users, but once the connection is [using a VPN](https://superuser.com/questions/1337801/why-is-recaptcha-image-fade-in-out-so-slow) or even on custom browsers (like the native apps) the experience seems to degrade quite a bit.

**Describe the solution you'd like**

[reCAPTCHA v3](https://developers.google.com/recaptcha/docs/v3) seems un-intrusive to the user experience. Although it presents a challenge to implement, because the requests will always succeed and will include a "trust score". It would be up to us to discard or accept the reports in this case, which would require a refactor.

**Describe alternatives you've considered**

Maybe abuse reports could just include the "trust score" and a quick button to manually "discard" the report if at first glance doesn't seem like a valid report instead of having the system discard reports that come in with a low score (since report abuse could have a low score because it was submitted using a VPN). This could be helpful to avoid discarding valid reports because reCAPTCHA didn't trust them.

**Comment by michael-tharrington** [comment]
Heyo!

I also wanted to chime in on this one as a DEV user recently wrote in suggesting that we drop reCAPTCHA in favor of hCAPTCHA.

They mentioned that reCAPTCHA can be pretty annoying for the end user, and said "hcaptcha LOOKS like recaptcha, but you can actually solve it pretty quickly, and no disappearing images, or clipped items you have to guess at."

The pointed to this blog post - https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/ for info on changing it.

**Comment by rhymes** [comment]
A lot of people in the comments there seem to be unhappy with hCaptcha :(

**Comment by bdmorin** [comment]
Another point of view: https://dev.to/elmuerte/hcaptcha-instead-of-google-s-recaptcha-2c92

Also - this epically long thread: https://news.ycombinator.com/item?id=22812509

I'm unsure if hcaptcha is the panacea solution; however I'm not seeing a ton of contenders. 
https://www.phpcaptcha.org/ (self hosted)

If you are looking to stop bot specific transactions, you might want to invest in bot detection, then only show the captcha on a high score, karma scoring based on user profiles and past abuse might be useful too.  example:
 - Is user logged in?
 - Is account age < 1 month
 - Past false report abuse history > YYY

Something like that. I'd understand not making this a priority since it's only for reporting abuse, however I don't know what your factors are in how important abuse reports are to the health of the site.

**Comment by michael-tharrington** [comment]
We may already be doing this, but something else that I just realized is that we need to make sure whatever CAPTCHA option we go with is accessibility friendly. I was just reading a post ["5 most annoying website features I face as a blind person every single day"](https://bighack.org/5-most-annoying-website-features-i-face-as-a-blind-screen-reader-user-accessibility/) that made me realize requiring CAPTCHA to send forms occasionally may cause issues for blind users if they don't have an option to hear the audio. See the heading: Inaccessible web forms.

**Comment by michael-tharrington** [comment]
Just to point out that some users have been hitting issues when using CAPTCHA to report spam - https://dev.to/yellow1912/i-fail-the-spam-report-captcha-on-dev-3397

**Comment by rhymes** [comment]
I was "spying" app.hey.com and noticed they seem to be using hCaptcha in production: 

<img width="1075" alt="Screenshot 2020-12-05 at 3 23 17 PM" src="https://user-images.githubusercontent.com/146201/101245534-d5713200-370d-11eb-8945-706ac9e13989.png">

**Comment by cmgorton** [comment]
Looks like this should have been closed via #10502. If not let me know and I can reopen it!
