### ISSUE TITLE
Generalise email sending logic for smaller communities

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9921]
**Is your feature request related to a problem? Please describe.**

At the moment, smaller communities might not be sending out automated digest emails as the minimal threshold.

**Describe the solution you'd like**

All the settings listed in email_logic.rb:28 to be set within SiteConfig. As they are quiet advanced at the moment maybe a good solutions would be to just set the frequency of sending and order of most popular.

**Comment by rhymes** [comment]
I reckon this is a matter of adding those hardcoded numbers as configurable factors in `SiteConfig`, correct @leewynne ?

**Comment by leewynne** [comment]
Yeah I think so! Although I don't think the experience level ratings will matter too much for smaller communities

**Comment by leewynne** [comment]
Hey there @Link2Twenty & @rhymes I was thinking further about the logic here and how it would work for new Forems. I think it would make sense to have an option for almost a 'basic' version that just emails out based on articles worth reading across the whole community rather than followed tags and experience levels.

**Comment by benhalpern** [comment]
> Yeah I think so! Although I don't think the experience level ratings will matter too much for smaller communities

Good call. We need some "small community alternatives" for a few things, where it's much more about distributing consistent content vs working with the firehose for large ones.

On a separate note: We should also generalize `experience_level` as a general preference gauge which can help match people with content. Anything that can be answered in a "scale" sort of way to qualify. For example: A parenting community might ask for how many children you have. And then your content might become slightly more matched with folks in a similar experience.
