### ISSUE TITLE
Forem.dev: bug with login

### ISSUE THREAD

**Issue by akhil-naidu** [forem/forem#9935]
>  ## Describe the bug

This is related to the live Forem Instance. The user is getting logout and the feed is empty in certain cases. The cases are mentioned below.

> ## To Reproduce

**Case 1**
1. Login to Forem
2. Use the Forem logo and open Forem in a new tab (Right-click on the mouse)

**Case 2**
1. Login to Forem
2. Click on Forem logo (no change at this stage)
3. Double click Forem Logo (the same issue arises)
4. If you can't produce the error, repeat double-clicking Forem Logo

> ## Expected behavior

User should not be logged out and should be able to view the feed

> ## Additional Information
1. You can reproduce these cases in chrome and Incognito chrome. I never tested this in other browsers.
2. Double-clicking and opening in a new tab don't result in any errors if it a mobile device.
3. This is not an issue with my device, I checked it in a few other devices, also as Dev.to is not producing any such errors even though it is running through the same code.

*If anyone can reproduce this in other browsers; like Firefox, Safari, Internet Explorer, or Opera. Please do mention it, it will provide valuable information.*

**Comment by bolsonusc** [comment]
I can reproduce in Safari  https://forem.dev/ too!

**Comment by Amorpheuz** [comment]
Erm, after I reproduced this bug, I can't seem to stay logged into https://forem.dev/ and now get logged out every time I switch pages.

**Comment by akhil-naidu** [comment]
> Erm, after I reproduced this bug, I can't seem to stay logged into https://forem.dev/ and now get logged out every time I switch pages.

Yes, I am facing this now.

**Comment by rhymes** [comment]
I recorded a GIF that should help a bit

![foremdev](https://user-images.githubusercontent.com/146201/91033467-b093fb80-e603-11ea-96da-de8734278ae1.gif)

Nothing is shown in the console errors

**Comment by jdoss** [comment]
This is related to our Nginx Caching efforts. I just disabled it on forem.dev and I will be working with @vaidehijoshi on getting this sorted out. Thanks for the report.

**Comment by akhil-naidu** [comment]
As the mentioned bug was not being reproduced, I'm closing this issue.

Thank you @jdoss
