### ISSUE TITLE
Native sharing not working

### ISSUE THREAD

**Issue by cglong** [forem/forem#9962]
**Describe the bug**

When I tap the ellipsis, I don't see a native share dialog.

**To Reproduce**

1. Open an article
2. Tap the ellipsis

**Expected behavior**

I expected to see a native share dialog, as depicted in #1524

**Screenshots**

![Screenshot_20200823-155343.png](https://user-images.githubusercontent.com/137214/90987479-47f04480-e559-11ea-9670-29c2fb394360.png)

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

- Device: Google Pixel 4
- OS, version: Android 10
- Browser, version: Chrome 84.0.4147.125

**Additional context**

Not familiar with this codebase, but it looks like this area may have been touched in #6815

**Comment by fdoxyz** [comment]
Thank you for the report @cglong. Like you mentioned the related PRs were indeed in place at some point but were commented out because they were apparently not working well or had some issues.

I do think that with some recent work done in the native Android app this could be fixed fairly easy. I'm hoping to get a fix for this improved sharing capability in soon

**Comment by fdoxyz** [comment]
Reopening in order to keep track of a follow up PR that will properly support PWA & other mobile platforms

**Comment by philnash** [comment]
Is there any more detail on what wasn't working with the imports that were commented out in #6815? Perhaps we can fix what is going on there?

**Comment by fdoxyz** [comment]
Hey @philnash thanks for reaching out! We've been considering a few options to make this work but haven't gotten around doing it yet.

The 'web-share-wrapper' works great but there are some certain scenarios we would like to have more control over when to present the share option vs the fallback options (not just whether or not the API is available in the current browser).

Do you think it's possible something like this could be added to the 'web-share-wrapper' package? Maybe if we can pass in a function to be evaluated (which returns true/false) and based on this the tool can decide whether or not to use the share option? It would also depend on the 'navigator.share' API being available for it work, but something along these lines would help us have a bit more "fine grain control" over which platforms we want to present the share functionality.

Just FYI I'm currently offline for vacation this week so I may be a bit slower to follow up, but this is something we're very interested in having work again 🙂 Feel free to ping me regardless, I'll respond as soon as I can. Thanks!

**Comment by philnash** [comment]
Thanks for getting back to me! Do you have an idea what the interface for that would look like? Given that web components in their declarative HTML form can only receive string properties? You can instantiate a component in JavaScript and add it to the DOM yourself and then set attributes with JavaScript?

Alternatively, you could subclass the `WebShareWrapper` class to add further behaviour to it which could incorporate your extra conditional so as not to fundamentally change the use of the original library.

Have a nice vacation!
