### ISSUE TITLE
Convert deprecated autoprefixer-rails gem to an npm dependency

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#9965]
**Is your feature request related to a problem? Please describe.**

The autoprefixer-rails gem has been deprecated.

**Describe the solution you'd like**

The gem should be removed in favour of an npm dependency. See the [migration guide](https://github.com/ai/autoprefixer-rails/wiki/Deprecated) for more details.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by nickytonline** [comment]
I was reading through the migration guide yesterday and this seems pretty involved @rhymes. The guide suggests migrating all assets to webpack. We can do this, but it's a good chunk of work that would require extensive manual testing of the site.

For the time being maybe we should look at the other option they suggest of running a script post asset pipeline processing.

Having said that, I know we have the autoprefixer-rails gem installed, but I do not see where it gets bootstrapped in the asset pipeline. Does the gem just know how to inject itself into the Sprockets asset pipeline?

**Comment by rhymes** [comment]
> I was reading through the migration guide yesterday and this seems pretty involved @rhymes. The guide suggests migrating all assets to webpack. We can do this, but it's a good chunk of work that would require extensive manual testing of the site.

yeah, it sounds like a lot of work! Also I don't know if moving off sprockets is the sensible thing to do in general as many people have experienced issues during the migration of legacy assets to webpack here:  https://discuss.rubyonrails.org/t/sprockets-abandonment/74371

> For the time being maybe we should look at the other option they suggest of running a script post asset pipeline processing.

What would that entail?

> Having said that, I know we have the autoprefixer-rails gem installed, but I do not see where it gets bootstrapped in the asset pipeline. Does the gem just know how to inject itself into the Sprockets asset pipeline?

Yep, it's self installing. Should we try removing it and see if the build happens anyway? Maybe we're not even taking advantage of any of its features. `rails autoprefixer:info` shows which properties it modifies

**Comment by nickytonline** [comment]
@rhymes, I'm pretty sure we don't leverage what `rails autoprefixer:info` gives us and in our SASS files, we actually use vendor prefixes in some cases. cc: @ludwiczakpawel 

Removing the gem should in theory break nothing. 😄 I will try that first and if there seems to be oddities in parts of the site in regards to CSS we can revert or fix those CSS issues as they pop up.

We can also look at running the script on CSS assets generated from the asset pipeline like they mention in the migration guide, but let's start with just removing the gem and see how that goes.

Just FYI, some other gems in the project have this gem as a dependency, so the deprecation warnings might still appear in build logs.

PR coming up!

**Comment by rhymes** [comment]
@nickytonline awesome plan. Apparently `autoprefixer-rails` is a dependency of `administrate` but we are planning to remove that so that's fine :D

**Comment by ludwiczakpawel** [comment]
> I'm pretty sure we don't leverage what rails autoprefixer:info gives us and in our SASS files, we actually use vendor prefixes in some cases. cc: @ludwiczakpawel

I haven't been using vendor prefixes in my CSS quite intentionally because I knew there's a magic that handles that for me :D 

So I'm not sure if dropping vendor prefixes will cause any harm, since I don't know in how many cases exactly vendor prefixes are still needed. But I'm sure there still are some properties that require vendor prefixes to be working on some browsers...

**Comment by rhymes** [comment]
I did a little test. I ran `rails assets:precompile` locally, which builds a production version of all the assets we have. I then grepped those assets (they will be in `public/assets` after the command has run) for vendor prefixes like `-webkit-`, `-moz-`, `-o-` and `-ms-` and found the following:

```shell
rg "webkit\-|moz\-|\-ms\-|\-o\-" *.css | wc -l
     307
```

so we have a bunch of them

**Comment by nickytonline** [comment]
I've done a smoke test and so far not an issue, but... you never know. 😄

Here's the list:

```bash
Browsers:
  Chrome for Android: 81
  Firefox for Android: 68
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 83, 81, 80
  Edge: 83, 81, 18
  Firefox: 77, 76, 75, 68
  IE: 11
  iOS: 13.4-13.5, 13.3, 12.2-12.4
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 46
  Opera: 68, 67
  Safari: 13.1, 13
  Samsung: 11.1-11.2, 10.1

These browsers account for 90.98% of all users globally

At-Rules:
  @keyframes: webkit
  @resolution: webkit
  @viewport: ms, o

Selectors:
  ::backdrop: webkit
  ::placeholder: moz, -ms- old, ms
  ::selection: moz
  :any-link: webkit, moz
  :fullscreen: webkit, ms
  :placeholder-shown: moz, ms
  :read-only: moz
  :read-write: moz

Properties:
  animation-delay: webkit
  animation-direction: webkit
  animation-duration: webkit
  animation-fill-mode: webkit
  animation-iteration-count: webkit
  animation-name: webkit
  animation-play-state: webkit
  animation-timing-function: webkit
  animation: webkit
  appearance: webkit, moz
  backdrop-filter: webkit
  backface-visibility: webkit
  background-clip: webkit
  border-block-end: webkit
  border-block-start: webkit
  border-image: o
  border-inline-end: webkit
  border-inline-start: webkit
  box-decoration-break: webkit
  break-after: moz
  break-before: moz
  break-inside: moz
  clip-path: webkit
  color-adjust: webkit
  column-count: moz
  column-fill: moz
  column-gap: moz
  column-rule-color: moz
  column-rule-style: moz
  column-rule-width: moz
  column-rule: moz
  column-span: moz
  column-width: moz
  columns: moz
  filter: webkit
  flow-from: ms
  flow-into: ms
  font-kerning: webkit
  grid-area *: ms
  grid-column *: ms
  grid-column-align *: ms
  grid-column-end *: ms
  grid-column-start *: ms
  grid-row *: ms
  grid-row-align *: ms
  grid-row-end *: ms
  grid-row-start *: ms
  grid-template *: ms
  grid-template-areas *: ms
  grid-template-columns *: ms
  grid-template-rows *: ms
  hyphens: webkit, ms
  image-rendering: ms
  margin-block-end: webkit
  margin-block-start: webkit
  margin-inline-end: webkit
  margin-inline-start: webkit
  mask-border-outset: webkit
  mask-border-repeat: webkit
  mask-border-slice: webkit
  mask-border-source: webkit
  mask-border-width: webkit
  mask-border: webkit
  mask-clip: webkit
  mask-composite: webkit
  mask-image: webkit
  mask-origin: webkit
  mask-position: webkit
  mask-repeat: webkit
  mask-size: webkit
  mask: webkit
  object-fit: o
  object-position: o
  overscroll-behavior: ms
  padding-block-end: webkit
  padding-block-start: webkit
  padding-inline-end: webkit
  padding-inline-start: webkit
  place-self: ms
  region-fragment: ms
  scroll-snap-coordinate: ms
  scroll-snap-destination: ms
  scroll-snap-points-x: ms
  scroll-snap-points-y: ms
  scroll-snap-type: ms
  tab-size: moz, o
  text-align-last: moz
  text-decoration-color: webkit
  text-decoration-line: webkit
  text-decoration-skip-ink: webkit
  text-decoration-skip: webkit
  text-decoration-style: webkit
  text-decoration: webkit
  text-emphasis-color: webkit
  text-emphasis-position: webkit
  text-emphasis-style: webkit
  text-emphasis: webkit
  text-orientation: webkit
  text-size-adjust: webkit, moz, ms
  text-spacing: ms
  user-select: webkit, moz, ms
  writing-mode: ms

Values:
  cross-fade: webkit
  element: moz
  fill-available: webkit, moz
  fill: webkit, moz
  fit-content: webkit, moz
  grab: webkit
  grabbing: webkit
  grid *: ms
  image-set: webkit
  inline-grid *: ms
  isolate-override: moz
  isolate: webkit, moz
  max-content: webkit, moz
  min-content: webkit, moz
  pixelated: moz
  plaintext: moz
  sticky: webkit
  stretch: webkit, moz

* - Prefixes will be added only on grid: true option.
```

**Comment by rhymes** [comment]
The output of the above command, so that you can inspect the results:

https://gist.github.com/rhymes/001ea0f22549acfcb0b2470d5fb41e24

**Comment by nickytonline** [comment]
Thanks @rhymes. In that case we're using it more than I expected. 🙃 I will look into running a script post asset compile then like they suggest in the migration guide. cc: @ludwiczakpawel

**Comment by rhymes** [comment]
@nickytonline I think the point here circles back to: are they needed? We still haven't decided which browsers Forem is going to support. Maybe we need all the prefixes, maybe we don't 🤷 

I guess in the meantime though we do...

**Comment by nickytonline** [comment]
Some of those prefixes are valid even with up-level browsers, so I'd prefer to air on the side of caution. Once we do decide on official browsers supported, we can re-evaluate. That OK with both of you?

**Comment by nickytonline** [comment]
Here's the script in action [`052351f` (#10017)](https://github.com/forem/forem/pull/10017/commits/052351f67588e5dbe30b621f5368835d3a0e4f29)
