### ISSUE TITLE
RSS Importer doesn't extract image out of responsive picture-tag

### ISSUE THREAD

**Issue by Swimburger** [forem/forem#9973]
**Describe the bug**

When you import posts using an RSS feed and the posts have responsive picture-tags, the HTML of the picture-tag is copied over entirely.

**To Reproduce**

1. Hook up RSS
2. Publish a post with responsive picture-tag
3. Edit post in forem/dev.to and scroll to picture HTML

My RSS has responsive picture-tags: https://swimburger.net/atom.xml

**Expected behavior**

Inside the picture HTML should be an img-tag. This img-tag should be used for the markdown image together with the alt-attribute.

**Comment by rhymes** [comment]
Linking one of such articles https://dev.to/swimburger/how-to-deploy-asp-net-blazor-webassembly-to-azure-static-web-apps-1k32

AFAIK we don't support responsive `<picture>` tags in the editor and the RSS importer just extracts `<img>` tags.

I'm not 100% sure this is technically a bug as the original image is then served responsively with Cloudinary, voiding the need for `<picture>` and `srcset`

**Comment by Swimburger** [comment]
Actually, what happened is that the img-tag wasn't being extracted. The entire picture HTML was being placed into the post.
I manually extracted the img's in the post you linked.

Here's a screenshot of another post (not published) where this issue is present:
![image](https://user-images.githubusercontent.com/3382717/91072142-15048a00-e607-11ea-89ef-7a5465ee61df.png)
![image](https://user-images.githubusercontent.com/3382717/91072185-1fbf1f00-e607-11ea-8acc-fc17d7b4340a.png)

**Comment by rhymes** [comment]
Ooh. I see that, Yeah, definitely a legit bug :-)

Thank you @Swimburger!

**Comment by rhymes** [comment]
I've opened a PR :-) https://github.com/forem/forem/pull/9977

**Comment by Swimburger** [comment]
I'm baffled by the speed of fixing this. Thank you so much.
FYI, how do I know when this will be released?

**Comment by rhymes** [comment]
@Swimburger I'll ping you when it is in production, it should go out with the first deployment today

**Comment by rhymes** [comment]
@Swimburger sorry, totally forgot to update you after deployment, the fix is live in production :)
