### ISSUE TITLE
Some posts are appearing without any padding on the sides of the content

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#9974]
**Describe the bug**

On [this article](https://dev.to/prithvi137/introduction-to-chaos-engineering-its-principles-for-kubernetes-o39) (and at least a few others) I'm seeing the following display issue (screenshot below).

**To Reproduce**

I haven't been able to reliably reproduce.  _Most_ posts are okay, but from just cmd+clicking new posts and looking around I've found these others ones with the same:
- https://dev.to/umamukkara/introduction-to-litmuschaos-4ibl
- https://dev.to/sanjay1611/scheduling-chaos-an-introduction-to-the-litmus-chaos-scheduler-4ca0

Note: it works fine in Incognito, and it doesn't appear to be linked to the Forem browser extension (disabled to test).

**Expected behavior**

Page displays without this issue.

**Screenshots**

![screenshot of CSS issue](https://p241.p3.n0.cdn.getcloudapp.com/items/E0unKgve/Image%202020-08-24%20at%2012.20.02%20PM.png)

**Desktop (please complete the following information):**

- OS, version: Catalina 10.15.5
- Browser, version: Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by benhalpern** [comment]
This was an issue with the series styling PR which updated classes in a way incompatible with styles. I saw this and ran a cachebust loop on a bunch of them... We may see this issue persist on a minority of articles for the next day or so.

**Comment by citizen428** [comment]
@benhalpern Labelled this as "Forem team" for now, please close this issue when you think it's been resolved.

**Comment by cmgorton** [comment]
I am going to go a head and close this issue. If you see if persist @benhalpern let me know and I will reopen it.
