### ISSUE TITLE
Deprecation: Datadog notice about Python 2 based agent

### ISSUE THREAD

**Issue by rhymes** [forem/forem#9979]
**Describe the bug**

The following deprecation notice appears in deploy builds on Heroku:

> Installing Datadog Agent
>       Python 2 will be deprecated soon. Agent 7.x ships with Python 3 only.
>       If you don't run custom checks or those are Python 3 ready, you can
>       move to Python 3 now by setting DD_PYTHON_VERSION to 3 and compiling your slug.

**To Reproduce**

See https://travis-ci.com/github/forem/forem/jobs/376992374#L409 for example

**Comment by maestromac** [comment]
Looks like we unintentionally resolved this.
