### ISSUE TITLE
Missing div.highlight in indented code-blocks

### ISSUE THREAD

**Issue by Amorpheuz** [forem/forem#9988]
**Describe the bug**
Un-indented codeblocks in markdown are enclosed with a `div` with `.highlight` class that adds the required css to make them not overflow and line up correctly. If an indented code-block is inserted, it doesn't get rendered with the `div.highlight` enclosing its `pre` tag causing things to not line-up properly and overflow.

**Markdown code used for test:** (Remove `\` before triple ` at end of code-blocks)
```md
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget nunc sed dolor molestie eleifend. Nulla ut ante ultricies quam accumsan commodo. Curabitur a felis et augue efficitur hendrerit. Sed ultrices tortor nec justo auctor suscipit. Duis accumsan nulla ac dui hendrerit, non porttitor purus tempus. Cras eleifend sodales nisi et vulputate. Phasellus ligula urna, pellentesque ut condimentum ut, porta in magna. Integer sed dictum eros. Duis venenatis erat ut magna accumsan vulputate id nec odio. Etiam fringilla a sapien et mattis. Nunc id sagittis turpis. Phasellus euismod elementum mollis. Curabitur ut pharetra felis. Curabitur congue vel odio sit amet tempus. Donec sodales, quam eget convallis interdum, dui magna pharetra nisl, id finibus felis dolor dignissim velit. Nullam lacus mi, volutpat ac facilisis nec, gravida non dui.

```yml
- name: Get a dad-joke
  run: |
    echo "::set-env name=TEMP::$(curl -H "Accept: text/plain" https://icanhazdadjoke.com/ | sed -r ':a;N;$!ba;s/\n/<br>/g' | tr -d '\r')"
\```
1. Curabitur vel tempus libero, vitae elementum purus. Cras et enim porttitor, congue odio in, eleifend mi. Mauris est nisl, varius quis dolor in, condimentum porta quam.

    ```yml
    - name: Write Commiticon
      run: |
        curl https://avatars.dicebear.com/api/human/$(echo $GITHUB_SHA).svg?h=250 --output .commiticons/$(echo $GITHUB_SHA).svg
    \```
```

**To Reproduce**

1. Write a new post.
2. Copy-paste the test markdown above or add an indented code-block with lengthy line.
3. The indented code-block will be missing correct padding, will overflow if too long and be a bit mis-aligned.

**Expected behavior**

The indented code blocks behave in a similar way to the un-indented code-blocks.

**Screenshots**
- Without being enclosed in `div.highlight`:
![image](https://user-images.githubusercontent.com/22113778/91127227-7427d480-e6c3-11ea-80e4-e07c2b3c14d3.png)

- After enclosing in `div.highlight`:
![image](https://user-images.githubusercontent.com/22113778/91127204-6b370300-e6c3-11ea-96bf-8eab73b2647a.png)

**Desktop (please complete the following information):**

- OS, version: Windows v2004
- Browser, version: Edge v84

**Smartphone (please complete the following information):**

- Device: Nokia 6.1
- OS, version: Android 10
- Browser, version: Edge v45

**Additional context**

Should also fix #9374 and related.

**Comment by Amorpheuz** [comment]
I would love to work on this, as this issue tends to hamper how I write blogs regularly 😅. But I lack the required knowledge in Ruby. Would love to get some pointers from anyone more knowledgeable or hand over the issue to the person.

**Comment by maestromac** [comment]
Hey @Amorpheuz , I'm not sure what's causing this to happen when the code block is indented and part of the list but I do want to give you some info on the tools we use to generate markdown and code block. 

Most of the magic happens within `markdown_parser.rb` and we use Redcarpet + Rouge gem. I don't think we are doing anything to remove that div from the code block because I was getting the same result when using barebone Redcarpet + Rouge in CLI. My guess is there's either a conflict between the two gems or it's just a custom feature we need to implement.
