### ISSUE TITLE
error while save my profile

### ISSUE THREAD

**Issue by Meetanshi-Inc** [forem/forem#9989]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment]
Hello @Meetanshi-Inc , thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
