### ISSUE TITLE
Layout of page of a comment belonging to a deleted article is broken

### ISSUE THREAD

**Issue by rhymes** [forem/forem#9991]
**Describe the bug**

The layout of comment belonging to a deleted article is a bit broken

**To Reproduce**

1. Go to https://dev.to/dorshinar/comment/p4g3
1. see the issue

**Expected behavior**

To be similar to https://dev.to/msarit/comment/1439j

**Screenshots**

Regular comment page:

![Screenshot_2020-08-25 BIG CONGRATS to all the graduates 🎉 🎉 🎉 🎉 - DEV(1)](https://user-images.githubusercontent.com/146201/91166114-25ce0200-e6d2-11ea-8820-fd65d89adc1f.png)

Comment of a deleted article:

![Screenshot_2020-08-25 https dev to(1)](https://user-images.githubusercontent.com/146201/91166118-26ff2f00-e6d2-11ea-97c9-2fde21735523.png)

**Desktop (please complete the following information):**

- OS, version: macOS 10.15.6
- Browser, version: Firefox 80

**Comment by Link2Twenty** [comment]
Points of interest

**Where style is applied**
https://github.com/forem/forem/blob/877bdba176759163f07e69b814400d4537bffa7c/app/assets/stylesheets/comments.scss#L126-L137

**Where classes are applied for a deleted section:**
https://github.com/forem/forem/blob/a081810946f6c32a54a2f5e611878289ab7cf227/app/views/comments/deleted_commentable_comment.html.erb#L2

I spy a missing class `comments-dedicated-page-container`

**Comment by rhymes** [comment]
@Link2Twenty great catch! do you want to submit a patch? :)
