### ISSUE TITLE
Pin a comment

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#9993]
**Is your feature request related to a problem? Please describe.**
Author can pin a comment on this posts for good responses (can be useful for #help) or **for goods questions and resources**. 

I'm going to use a very simple example that I've already seen several times on DEV.

The post is called "Who will participate to the Hacktoberfest 2020? 🙌🏼". ([you can find it here](https://dev.to/thomasbnt/who-will-participate-to-the-hacktoberfest-2020-100e))

And one person comments by asking for help with his plans for the event. 
Why not pin this on? Or pin simple rules for commenting.

**Describe alternatives you've considered**

A triage with "Good responses marked by author".

**Comment by Link2Twenty** [comment]
Related to #4523

**Comment by thomasbnt** [comment]
Oh sorry :x

**Comment by Link2Twenty** [comment]
Nothing wrong with having multiple open 😊
It let's the dev team know it's a feature people want.

It might be worth making a post over on https://forem.dev then people can discuss pros and cons
