### ISSUE TITLE
Generalise: Site mascot footer image

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#9994]
**Describe the bug**

The site mascot currently has a fixed size (52x120) this means if a new forem changes their mascot to something that doesn't fit it will looks stretched

**To Reproduce**

Scroll to the footer on https://forem.dev
Look at Sloan

**Expected behavior**

The forem maintainer should be able to have any image and not have to match a specific size

**Screenshots**

![poor sloan](https://user-images.githubusercontent.com/3534427/91195220-bd424d80-e6f0-11ea-9f35-48b29b095397.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10 - 18363.1016
- Browser, version: Chrome 84.0.4147.135

**Additional context**

Perhaps removing the height would be enough?
https://github.com/forem/forem/blob/0e2fc110b2a48002d6115e64c60a8129a4c27fdf/app/views/layouts/_footer.html.erb#L50-L55

**Comment by jacobherrington** [comment]
@Link2Twenty I'll work on changing this since generalization is currently a focus area for us.

Do you feel like the size values should be configured by an admin user (either in the configuration UI or the image's size), or do you think it should be generated dynamically?
