### ISSUE TITLE
Emojis on onboarding task card don't show properly on Desktop browsers

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#9996]
**Describe the bug**

Emojis on the onboarding task card for new users don't show properly on Desktop (they do on Mobile). I've tested this on different computers on both Opera and Google Chrome. 

**To Reproduce**

1. Go to clusteremployment.com
2. Create new account
3. Follow onboarding flow
4. See error once flow is finished

**Expected behavior**

Emojis to show properly on desktop

**Screenshots**

![issue](https://user-images.githubusercontent.com/32549192/91216724-ce895b00-e6ec-11ea-9893-78f739d05318.png)

**Desktop (please complete the following information):**

- OS, version: Microsoft Windows 8.1 64-bit
- Browser, version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version: 
- Browser, version: 

**Additional context**

**Comment by jeansberg** [comment]
I was not able to reproduce this. Tested it on my dev environment and on the Cluster site. Windows 10, same version of Chrome. I also checked the code for the onboarding task card and there doesn't seem to a difference between the working and non-working emojis.
![image](https://user-images.githubusercontent.com/13261449/91476302-18b13e80-e89d-11ea-8858-2fbb546c3464.png)

**Comment by AdekunleA** [comment]
Big apologies for the very delayed reply to this. 

That's interesting, I'll look into it again from my end and make a PR if I'm able to reproduce it.
