### ISSUE TITLE
Request to make category details/rules more prominent for listings

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#9997]
**Is your feature request related to a problem? Please describe.**

It's not necessarily a problem, but it would serve our use case better if we could have category details/rules show up more prominent. This is because of the high potential for current users to miss the category details/rules.

**Describe the solution you'd like**

Make category details/rules more prominent so users of all skill levels can easily understand the right way to create listings in different categories.

**Describe alternatives you've considered**

Having category details/rules fall directly under the listings body field in bigger and weightier font.

Making the category details/rules a placeholder text that shows up depending on the specific listing category.

**Additional context**

Here's a screenshot of how it currently is:
![feature](https://user-images.githubusercontent.com/32549192/91218120-01345300-e6ef-11ea-8fa8-15cac17b57fd.png)

**Comment by josepplloo** [comment]
hi! 👋 folks If this is available, can I work on it?

**Comment by ludwiczakpawel** [comment]
@josepplloo or @AdekunleA - Do either of you have any ideas on how this could look like?

@josepplloo I wanna be sure we have some good-enough design in place before assigning anyone.

**Comment by AdekunleA** [comment]
Hello @josepplloo  what are your thoughts?

**Comment by josepplloo** [comment]
I was thinking about: depending on what category you choose, it should display only the detail for that category.

eg. by default we can show `Contributors/Collaborators Wanted:` and only its rule below `Projects looking for volunteers. Not job listings.`, with a proper font style, and so on for each category.
 
![image](https://user-images.githubusercontent.com/1114740/93906844-4df55480-fcc2-11ea-949a-f9a9c69eb481.png)

LMK your thoughts.

**Comment by ludwiczakpawel** [comment]
@josepplloo I think it makes sense. Although I'd still like to keep "Category details" visible somehow so ppl can learn what each category means without clicking through every of them in `select` field.

If you wanna work on it, I'm happy to assign you. BUT I do have a [PR in progress with some updates](https://github.com/forem/forem/pull/10429) to this view and I'd love to merge that one first so you don't have to redo your work. It should be merged at the beginning of the week.

**Comment by josepplloo** [comment]
Nice, I'm happy to work on this issue, We can keep all the list, and maybe a good idea to make it more visible is changing the font, something like that:

![Screen Shot 2020-09-26 at 15 38 08](https://user-images.githubusercontent.com/1114740/94349871-7062d700-000e-11eb-9057-9cda34885bc8.png)

**Comment by ludwiczakpawel** [comment]
FYI: new listing form is now live on prod, check it out. The "Category details/rules" elements is also a bit more prominent right now, so maybe that's enough?
